### ISSUE TITLE
[BUG] Home Page Size is not adaptive

### ISSUE THREAD

**Issue by DkRadhey** [twentyhq/twenty#1006]
When I load the site "Try for Free" Button gets cut and privacy policy link under is not visible.

<img width="958" alt="image" src="https://github.com/twentyhq/twenty/assets/122290163/1fea6edc-7f4b-463e-8220-a3699509b6f7">

**Comment by charlesBochet** [comment]
Thank you, @Bonapara FYI

**Comment by DkRadhey** [comment]
@charlesBochet Can I work on this issue?

**Comment by charlesBochet** [comment]
Unfortunately no, this website is a marketing website powered by Framer. @Bonapara is our guy here!
Thanks a lot for reporting it! (and if you want to help, feel free to take a look to issues tagged as "good first issues")

**Comment by Bonapara** [comment]
Got this in mind for the next website refacto, thanks @DkRadhey!
