### ISSUE TITLE
could not clone repo

### ISSUE THREAD

**Issue by Opfour** [twentyhq/twenty#1013]
`root@Merovingian2:~# git clone git@github.com:twentyhq/twenty.git
Cloning into 'twenty'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

is cloning this repo as root allowed or does it need to be run as a user with limited perms?

**Comment by charlesBochet** [comment]
The repo is public so you should not have any issue cloning it. Might be an issue with your github account / cli setup? This seems very independent from this specific repository

**Comment by jessicali2023** [comment]
You might need to generated keys and load into your GitHub settings.
https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey

**Comment by FelixMalfait** [comment]
Yes not linked to our repo. Jessica's link should help you! If you don't manage to clone via SSH you could try cloning via HTTP which shouldn't require keys
