### ISSUE TITLE
Add a button to deploy to Vercel

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#1018]
After a [painful but successful](https://github.com/twentyhq/twenty/pull/974) attempt to implement the `Deploy to render` button, we should now try adding other popular platforms.

Next step: Vercel!

https://vercel.com/docs/concepts/deployments/deploy-button

**Comment by friendlymatthew** [comment]
Hi Felix! May I take on this issue?

I love Vercel, I love Nextjs :)

**Comment by FelixMalfait** [comment]
Thanks @friendlymatthew! We don't use Next.js and I realized Vercel may not be a good fit for this https://github.com/twentyhq/twenty/pull/1049 but I might be wrong, I don't understand Vercel well. What do you think? Should we keep this open or close it?

**Comment by friendlymatthew** [comment]
I think you should close it! I'll be working on a different issue!!
