### ISSUE TITLE
Ability to join a workspace by email domain

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#1021]
If user (workspace?) has a domain that is not a common email provider, then provide a toggle that allows the user to auto-join the existing workspace. Show that toggle during workspace creation (?)

**Comment by Bonapara** [comment]
#behavior:

- When activated, people having the same email domain shouldn't be able to create a new workspace, instead, they should join the existing workspace of their organization.
- People should receive a magic link to confirm they are indeed part of the organization. (Unless they sign in with Google)

# Figma

https://github.com/twentyhq/twenty/assets/19412894/ca6cd21b-1fb6-4941-85d5-7d7f5b0da96c

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=3599-50252&mode=design&t=hGEvUqqbSUFEtpch-4

**Comment by charlesBochet** [comment]
Agree, putting this one on-hold for now

**Comment by charlesBochet** [comment]
Estimating to 8 points assuming we already have the magic link

**Comment by Bonapara** [comment]
Not planned in the short term
