### ISSUE TITLE
I see a confirmation before deleting a member

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#1024]
As of today, it's easy to delete a member by mistake.
We should add a confirmation modale or allow canceling for a few seconds (preference for the first option).
```[tasklist]
### Tasks
- [ ] Introduce a Modal like we have on DeleteAccount or DeleteWorkspace, we might want to refactor this "DeleteModal" in something more generic like "ConfirmationModal"
```

**Comment by Bonapara** [comment]
https://github.com/twentyhq/twenty/assets/19412894/b704a3c1-5543-4bed-9905-04d0a572c455

**Comment by FelixMalfait** [comment]
@Bonapara Sorry I meant a member = workspace user. I should have added a screen to clarify. For People we have just implemented the toast where you can delete for a few seconds which is nice

**Comment by Bonapara** [comment]
Here we go!

https://github.com/twentyhq/twenty/assets/19412894/b1690ea1-1768-4d40-9b9b-fba583f93d75

**Comment by charlesBochet** [comment]
@Mbistami would like to work on this one

**Comment by Mbistami** [comment]
I'll handle this one!

**Comment by charlesBochet** [comment]
Closing as this was implemented, thanks @Mbistami!
