### ISSUE TITLE
On Tables, in the TopBar, Options, add an Import option

### ISSUE THREAD

**Issue by magrinj** [twentyhq/twenty#1025]
<img width="235" alt="Screenshot 2023-08-01 at 11 35 31 AM" src="https://github.com/twentyhq/twenty/assets/3551795/1312275a-285e-42b6-8c1b-786e309ca20d">

**Comment by Bonapara** [comment]
The import button should be in this Option "Dropdown":

https://github.com/twentyhq/twenty/assets/19412894/3171a048-499a-4070-9cda-7531bb55d7db

![image](https://github.com/twentyhq/twenty/assets/19412894/3c46c809-ce22-461f-b855-578fc37f2182)
