### ISSUE TITLE
Style CSV Importer based on Figma

### ISSUE THREAD

**Issue by magrinj** [twentyhq/twenty#1027]

**Comment by magrinj** [comment]
cc @Bonapara

**Comment by jenalla** [comment]
# Design Modifications of Ugnis:
**1.	Import as Modal:**

  o	Convert the CSV import process into a modal for a more streamlined and intuitive user experience.

![Image](https://github.com/twentyhq/twenty/assets/102394218/475b7506-7004-4dd5-9440-1ecad84edc71)


**2.	Automatic Header Row Selection:**

  o	Remove the "select header row" step and automatically select the first row as the header row to simplify the import process.


**3.	Vertical Order of Fields in Match Columns Step:**

  o	Arrange the fields vertically and remove the check symbol in the "Match Columns" step to improve readability and user understanding.


![Image](https://github.com/twentyhq/twenty/assets/102394218/4c6b44d2-0f07-46af-a511-b2acb38b6aa3)




**4.	"Do Not Import" Option in Match Columns Drop-down Menu:**

  o	Add a "do not import" option in the drop-down menu of the "Match Columns" step, providing users with the ability to exclude specific fields from the import if they are not interested in importing them.




![Image](https://github.com/twentyhq/twenty/assets/102394218/bfcda5f7-f288-4033-a5cb-5232692314eb)


**5.  Handling Duplicate Columns:**
When a user attempts to reselect a field that was already chosen before.
  o Display fields that are already used as deactivated in the drop-down menu and add a tooltip on hover saying "You are already importing this column."




https://github.com/twentyhq/twenty/assets/102394218/e762363d-a6c8-4604-a588-c3d3e8f650e9



   
> If not possible apply the field to the one the user just changed and set the other value to 'do not import'. Display an alert using our custom alert component with the message 'Another column unselected. Columns cannot duplicate.'



https://www.figma.com/file/71Y4rtvMOzePW0vSsVFz8u/Ugnis-react-spreadsheet-import-(Community)?type=design&node-id=1226-9632&mode=design&t=Gh6QGadUTCVwJNPZ-4
