### ISSUE TITLE
Add tests on the csv import in backend

### ISSUE THREAD

**Issue by magrinj** [twentyhq/twenty#1029]

**Comment by FelixMalfait** [comment]
@magrinj is this still relevant after we refactored the backend? Could you please give brief directions?

**Comment by magrinj** [comment]
@FelixMalfait I think it's still relevant but the back-end actually lack of tests

**Comment by FelixMalfait** [comment]
Closing as there are not endpoint related to CSV export specifically. It's just the createMany endpoint
