### ISSUE TITLE
Tasks inbox small design improvements

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1037]
- H3 Font weight is 700 instead of 600
- Task title is black instead of Text primary
- Tab switcher is not Figma iso (check prototype for the 'hover' behavior, padding left/right should be 8 and not 16, also there should be a 8px gap between the two tabs)

Figma: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5910-71591&mode=design&t=8qvyT8uwa19R1bVz-0 

![Image](https://github.com/twentyhq/twenty/assets/19412894/904fb177-d24e-4b5c-9b26-9f925ad3bedb)

**Comment by aqsaaqeel** [comment]
Can i work on this?

**Comment by Bonapara** [comment]
Sure @aqsaaqeel

**Comment by aqsaaqeel** [comment]
So i have been trying to set up the project with docker but it appears some dependencies are not installed in the docker container.
![Screenshot from 2023-08-04 14-58-54](https://github.com/twentyhq/twenty/assets/85514520/68cfbffb-1753-411e-bd6c-fe0f3f0a86ac)
As can be seen in this screenshot, @emotion/styled module is not available and in other files @storybook/react is showing a similar error. How do I go about doing this? can anyone help out?

**Comment by kelvinyelyen** [comment]
If a couple of dependencies aren’t installing despite being listed (@storybook/react, @emotion/styled), try checking their versions for compatibility, review the Docker build logs for any errors, and consider deleting cache or lock files before rebuilding the image. If the issue persists, let us know any error messages you’re encountering.

**Comment by Bonapara** [comment]
@charlesBochet can you have a look?

**Comment by charlesBochet** [comment]
@aqsaaqeel I think you need to use Dev Containers in VSCode as you are running your project in Docker. You are not the first person having this issue, we need to add a section in the documentation. Look into dev containers documentation and you can ping me on discord if you need additional guidance

**Comment by charlesBochet** [comment]
@aqsaaqeel any update on this one? should we leave it to you?

**Comment by kelvinyelyen** [comment]
@charlesBochet any further guidance on setting the project using dev containers? I think I've managed to configure it correctly, but I could use more direction. Terminal is showing: `root@############:/workspaces/twenty#` but running ‘make build’ doesn’t work.

**Comment by aqsaaqeel** [comment]
> @aqsaaqeel any update on this one? should we leave it to you?

If it is not on super high priority, I'd still like to work on this. As soon as I am able to run the project, it should take me 3 days max to get the feature working

**Comment by charlesBochet** [comment]
Ok, @kelvinyelyen @aqsaaqeel I'm adding more directions to the official docs today. If it still doesn't work, we can discuss this on discord and I can assist you with project installation

**Comment by kelvinyelyen** [comment]
Sounds good! Appreciate your help.

**Comment by charlesBochet** [comment]
@aqsaaqeel @kelvinyelyen any update on this one? :)

**Comment by kelvinyelyen** [comment]
Finally had some progress setting up, will be up and running soon to start tackling this issue. ;)
