### ISSUE TITLE
Logout button should be change to gray

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1038]
The logout button should be changed to gray:

# current behavior 
![Image](https://github.com/twentyhq/twenty/assets/19412894/8026cd5d-cef8-4faf-9f1c-5391dccfca9b)

# Desired behavior 
![Image](https://github.com/twentyhq/twenty/assets/19412894/a4525681-9779-426c-bfe6-b27973139e25)

**Comment by aqsaaqeel** [comment]
can i work on this?

**Comment by Bonapara** [comment]
Sure @aqsaaqeel ;) Thanks a lot!

**Comment by ducksblock** [comment]
I have fixed this https://github.com/twentyhq/twenty/pull/1052
