### ISSUE TITLE
Display team on Company show

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1040]
As a user, I want to see who's belonging to a company:

# Features
- Link an existing person to the company
- Create a new person and link it to the company
- Navigate to a person show
- Remove a people

Precision:
the "First name - last name" input is not well positioned on the video due to Figma, it should be next to the "+" icon.

https://github.com/twentyhq/twenty/assets/19412894/ccf34831-5795-439a-bbfd-0c4f471b5f68

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5910-71659&mode=design&t=Kg8gykbQHd3TdVkc-4

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=8986%3A32664&mode=dev

```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/1106
- [ ] https://github.com/twentyhq/twenty/issues/1107
- [ ] https://github.com/twentyhq/twenty/issues/1110
- [ ] https://github.com/twentyhq/twenty/issues/1108
- [ ] https://github.com/twentyhq/twenty/issues/1109
```

**Comment by FelixMalfait** [comment]
Good ticket for Gitstart. But we need to split it into subtickets before they can take it, it's a bit too big

**Comment by charlesBochet** [comment]
@gitstart-twenty, I will refine this one tomorrow. All the other tickets assigned to gistart-twenty are ready to be worked on :)
