### ISSUE TITLE
Add "Empty" as value of empty fields inputs

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1042]
# Problem

Today, it's more appealing to click on the label that looks like a placeholder than to click on the blank space to edit the value associated to a field.

https://github.com/twentyhq/twenty/assets/19412894/b8782d5a-f541-4f61-8b97-80f68cba30d2

# Solution

When the field is empty, introduce an "Empty" text that would enable to set up the first value on click

https://github.com/twentyhq/twenty/assets/19412894/96527c17-6141-410c-8cfd-ef062efaca20

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5910-71449&mode=design&t=Kg8gykbQHd3TdVkc-4

```[tasklist]
### Tasks
- [ ] This should be done at the EditableFieldDisplayMode
```

**Comment by Yasir761** [comment]
Is anyone working on this issue ? If not, I would like to work on this.

**Comment by Bonapara** [comment]
Thanks Yasir 🙌 Assigned you

**Comment by charlesBochet** [comment]
@Weiko FYI as you are working on a similar topic

**Comment by charlesBochet** [comment]
Closing this issue as @Weiko worked on it
