### ISSUE TITLE
[Timebox] Prepare Zapier integration

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#1043]
**Step 1: Create Apps concept**
Let's begin by creating a JSON or TypeScript file that keeps track of the available apps and their parameters.
The configuration might look like something like this:
```
[ 
  {
    name: "Zapier",
    logo: "xxx.jpg"
    OAuthRedirectUrl: "https://zapier.com/dashboard/auth/oauth/return/App188609CLIAPI/",
    clientId: process.env.APP_CLIENT_ID_ZAPIER,
    clientSecret: process.env.APP_CLIENT_SECRET_ZAPIER
  }
]
```

**Step 2: Create Authorization page**
Next, create an authorization page where users can authorize apps.
We'll fetch the client id from the url to retrieve the app name / logo. 
For Zapier, you might have a prompt like, "Would you like to authorize Zapier? Click yes to continue." 
cc @Bonapara for design of this screen

**Step 4: Generate Authorization Code**
Create a table to store app connections.
Generate an authorization code to be sent to Zapier and associate that code with the connection/user.
This code will be short-lived and used by Zapier to obtain an access token.

**Step 4: Redirect back to Zapier**
If the user agrees to authorize Zapier, redirect them back to the OAuth Redirect URL, including the authorization code in the URL parameters. The URL will look something like this: <Zapier's Redirect URL>?code=<Your Authorization Code>.

**Step 5: Create Access Token Request endpoint**
Zapier will then make a request to your application's token endpoint, including the authorization code, client id and secret. Our app  should validate these details, and if they're correct, send back an access token (and potentially a refresh token).

**Step 6: Access Token Usage**
Zapier will now use this access token to make authorized requests to your application on behalf of the user. Make sure to validate these access tokens each time a request is made.

**Step 7: webhooks**
Let's do this later in another issue

**Step 8: move the config file from step 1 to a database table**
We'll let people create private apps.
Need to add an additional param to track who the app belongs to and if it's private or shared with everyone.
Create a basic interface for people to create apps

TODO: Check how NestJS passport can help in implementing that

**Comment by FelixMalfait** [comment]
@Bonapara fyi quite high priori in terms of design (but comes after custom objects/fields)

**Comment by charlesBochet** [comment]
Done of this timebox:
- write a serie of accurate ticket on how to implent it
