### ISSUE TITLE
Profile Picture doesn't appear on first settings page load

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1044]
I need to reload the page to make the picture appear:

https://github.com/twentyhq/twenty/assets/19412894/24787b47-82ba-494c-90d2-589b482dbfa0

**Comment by indrajitbnikam** [comment]
Is this issue still valid?

**Comment by Bonapara** [comment]
Did you sign in with Google?

1) Unconnect
2) Sign up with Google
3) Go to settings

**Comment by Daggerhub** [comment]
Have done the same steps as given
Still not able to reproduce.
@Bonapara can you check?

**Comment by Bonapara** [comment]
Still occuring to me. Did you try with Incognito mode?

https://github.com/twentyhq/twenty/assets/19412894/daa2f180-bcb1-4849-85dd-a55e7b0192f5
