### ISSUE TITLE
Add a (+) on page top-right of navbar to create a task

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#1046]
Currently we don't have the (+) button to create a task

See Figma: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5910-71591&mode=design&t=8qvyT8uwa19R1bVz-0

<img width="884" alt="Screenshot 2023-08-01 at 18 48 03" src="https://github.com/twentyhq/twenty/assets/6399865/fc38031a-1779-4cc9-ab64-efc1a7e6cc2c">

**Comment by Nkiriobasi** [comment]
Just the UI ?

**Comment by charlesBochet** [comment]
@Weiko FYI, @Nkiriobasi is working on this one :)

**Comment by charlesBochet** [comment]
@Nkiriobasi any update on this one?
