### ISSUE TITLE
Add our repo to list of awesome self-hosted projects

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#1047]
List: https://github.com/awesome-selfhosted/awesome-selfhosted/
Description: A powerful CRM with a Notion-like UI.
(or whatever you want to put as a description, I'm really bad at this!)

**Comment by jessicali2023** [comment]
@FelixMalfait sure I can take this one 😸 . Is Twenty considered Free or Non-Free? I understand free trial is available but there is also a paid version.

**Comment by FelixMalfait** [comment]
@jessicali2023 sorry for the late reply! I missed the notification. 
Yes AGPLv3 is consider an open source licence / free software!

**Comment by jessicali2023** [comment]
As I was getting a PR ready, I noticed Twenty didn't meet one of the requirements. https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/PULL_REQUEST_TEMPLATE.md

`Any software project you are adding was first released more than 4 months ago.`

We just need to hold off for a couple months!

**Comment by Bonapara** [comment]
@jessicali2023 how are you? We should be good now!

**Comment by jessicali2023** [comment]
@Bonapara Hi, I'll get a PR ready this week 👍

**Comment by jessicali2023** [comment]
@Bonapara So apparently things got moved and now it's in a different repo. Would Twenty still want to be hosted there? Also  if I need to start over, I probably won't be able to get to it this week.

https://github.com/awesome-selfhosted/awesome-selfhosted/issues/4086

**Comment by Bonapara** [comment]
Hi @jessicali2023, thanks a lot for following up! Yes sounds good to me, what do you think?

**Comment by jessicali2023** [comment]
@Bonapara sorry for getting back to you so late. Things have been crazy for me. I'll be able to get to this in mid December. would that be okay?

**Comment by Bonapara** [comment]
Yes it would, thanks for contributing @jessicali2023 🙏

**Comment by jessicali2023** [comment]
@Bonapara I've created a PR: https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/459

**Comment by FelixMalfait** [comment]
Thanks a lot @jessicali2023!

**Comment by Bonapara** [comment]
Thanks @jessicali2023 🙌
