### ISSUE TITLE
Update date style on task page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1057]
# to do:
- Remove the hour in the time as we cannot set an hour yet
- Set the text to "red" when the deadline is past

<img width="1280" alt="Screenshot 2023-08-02 at 14 33 31" src="https://github.com/twentyhq/twenty/assets/19412894/b94f891f-3c63-4658-823d-2e352de7a8bc">

**Comment by takanome-dev** [comment]
Hey @Bonapara, what do you mean by `remove the hour in the time`?
I see that the date is formatted as `Aug 2, 2023`. Is that the desired format?

I'm interested in working on this btw :slightly_smiling_face:

**Comment by charlesBochet** [comment]
@takanome-dev any update on this one? :)

**Comment by takanome-dev** [comment]
Hey @charlesBochet, thanks for checking in. I was having some network issues when installing the packages. Will unassign myself and let you know if they persist :)

**Comment by charlesBochet** [comment]
Ok, I will update the docs today. Once done, if you are still facing issue, we can connect on Discord and see how to fix it

**Comment by srikarsams** [comment]
@charlesBochet Can I work on this?

**Comment by charlesBochet** [comment]
Sure!
