### ISSUE TITLE
Add a notification for "tasks" in the navigation

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1058]
The notification number should be the number of tasks that figures in "Today" (Late + tasks with today's deadline)
It should only take into account the tasks that are assigned to me

![image](https://github.com/twentyhq/twenty/assets/19412894/d05b3401-e510-40da-af30-07d0a4a91b52)

**Comment by FelixMalfait** [comment]
@charlesBochet what would be your recommendation to implement this? Where should this data come from and how should it be updated? It doesn't seem trivial
