### ISSUE TITLE
Replace "Inbox" by "Notifications" in navigation

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1059]
Change "Inbox" in "Notifications"
Change the icon to "bell"
Keep the "Coming soon" badge

# Current behavior
<img width="232" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/d721484e-18a1-4dea-920a-aca268bf4106">

# Desired behavior
<img width="302" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/136729d6-4f7d-4d5b-80c9-a141324c8dfe">

**Comment by jessicali2023** [comment]
I can work on this one! Thanks.

**Comment by Bonapara** [comment]
Thanks @jessicali2023!
