### ISSUE TITLE
I can create a new company from the company picker in people list/show

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#1068]
As of today, you have to switch between the people view and the contact view to create a contact. 

It would be nice to be able to create everything from the people view directly. Probably by editing the company picker?
```[tasklist]
### Tasks
- [ ] We want to update CompanyPickerCell and SingleSelectPicker
```

**Comment by Bonapara** [comment]
Figma:

https://github.com/twentyhq/twenty/assets/19412894/ec6a4f4c-88b9-4ed1-ac88-c2957c32a947

(Click on Sequoia on the People Figma page: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=568-41746&mode=design&t=NdzDsxBTNWCsCjUx-4

**Comment by mustajab-ikram** [comment]
Can I pick this @Bonapara ?

**Comment by FelixMalfait** [comment]
The strange thing is that I believe this feature already existed previously. It must have disappeared during a refactoring but maybe it's just a matter of passing 1 parameter in the right place to re-enable it? I'm not sure

Thanks @mustajab-ikram ! maybe it's better to pick one with the label "good first issue" to get started because of the issue I just mentioned above (it'd be faster to find for someone who already has experience with the codebase). But if you still want to give a shot, feel free to! Otherwise here's the link to see other good issues:
https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
