### ISSUE TITLE
Change User icon into User-circle on "Companies" & Settings

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1076]
The user icon should exclusively be used for reference to "People" while the user-circle icon should exclusively be used for "Team members"

# Current behavior

![Image](https://github.com/twentyhq/twenty/assets/19412894/ad7cc8eb-0c64-4aba-8635-46714bbe02c2)

![Image](https://github.com/twentyhq/twenty/assets/19412894/fa7dcf09-5cc7-40ca-ad7d-ccd53e64be5f)

# Desired behavior

![Image](https://github.com/twentyhq/twenty/assets/19412894/e99aff1a-e231-4145-80e2-ebf41328feb2)

![Image](https://github.com/twentyhq/twenty/assets/19412894/0a8db077-f424-4ffe-972e-a6890733df57)

**Comment by alexdobrenko** [comment]
Heya! Can I tackle this one?

**Comment by neutr0n420** [comment]
I really wanted to work on this can I go ahead with it?
