### ISSUE TITLE
Customize opportunities kanban view – hide/add fields

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1084]
This ticket aims to introduce a new feature for the Opportunities section, allowing users to customize the fields displayed on the Kanban view.

# Feature Details: #

### Remove a field:
- Upon accessing the Opportunities options, a new "Fields" option will be available.
- Clicking on "Fields" will reveal another menu displaying the currently visible fields in the Kanban view.
- Hovering over a field option will reveal two buttons:
- The left button with the "info-circle" icon provides additional information about the field.
- The right button with the "eye-off" icon allows users to hide the field in the Opportunities Kanban view.
- Clicking on the "eye-off" icon will remove the field from the menu and hide it in the Kanban view.

https://user-images.githubusercontent.com/102394218/258550137-a425423c-b992-4e37-b307-543b8c427191.mp4

### Add a field:

- To add a hidden field back to the Kanban view, users can click on the "Add Field" option, which switches to the menu of hidden fields for Opportunities. From there, users can add any desired field back to the Kanban view by clicking on the "eye" icon.

https://user-images.githubusercontent.com/102394218/258550447-68761c7c-7547-4266-9a2e-cfe8331de091.mp4

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=8328-161476&mode=design&t=qLsrIcqPshZ6xPyd-4

By implementing this feature, users will have more control over the fields displayed in the Opportunities Kanban view, allowing for a more personalized and efficient view of their data.

```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/1537
- [ ] https://github.com/twentyhq/twenty/issues/1538
- [ ] https://github.com/twentyhq/twenty/issues/1539
```

**Comment by mohitkadwe19** [comment]
Hey @jenalla , I would like to work on this feature , kindly assign to me

**Comment by charlesBochet** [comment]
This one is on-hold as there is an ongoing work on Tables for the same feature + there is an ongoing refactoring of the pipelines. We will add more details on how to do it end of the week and if you are still interested @mohitkadwe19, you could work on it at this moment

**Comment by SomayChauhan** [comment]
hi, can i try to implement this?
