### ISSUE TITLE
Removing Relations in tasks not refreshed

### ISSUE THREAD

**Issue by brendanlaschke** [twentyhq/twenty#1098]
Removing relations in tasks not refreshed:

https://github.com/twentyhq/twenty/assets/48770548/b6e1be4b-06c0-469c-a09c-375d8e763ad0

**Comment by charlesBochet** [comment]
Good catch, mmh, that's bad. We are merging a refactoring work on the activity targets that might solve it. Let's revisit this bug end of the week once it is merged.

**Comment by Weiko** [comment]
This seems to be fixed, I'm closing this one. Feel free to reopen if needed
