### ISSUE TITLE
On Company Show, I see a a Team section displaying a list of person linked to the company

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1106]
https://github.com/twentyhq/twenty/assets/19412894/ccf34831-5795-439a-bbfd-0c4f471b5f68

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=7813%3A79050&mode=dev

This ticket scope is only to display the list of person attached to a company.
```[tasklist]
### Tasks
- [ ] Create a component in @/ui/company/components/CompanyTeam.tsx that is displaying a list of PeopleCard
- [ ] Create a component in @/ui/people/components/PeopleCard that is displaying the person with its displayName, Avatar and jobTitle
```

**Comment by gitstart-twenty** [comment]
Hello @charlesBochet,

I wanted to bring to your attention that the Figma link attached doesn't appear to direct to the correct component(s).

**Comment by charlesBochet** [comment]
> Hello @charlesBochet,
> 
> I wanted to bring to your attention that the Figma link attached doesn't appear to direct to the correct component(s).

Yes good catch!
