### ISSUE TITLE
When I delete a company, the associated opportunity is not removed until I refresh the page

### ISSUE THREAD

**Issue by deepaksing** [twentyhq/twenty#1111]
Steps to reproduce                                            ( steps similar to `https://github.com/twentyhq/twenty/issues/930`)

1. create a new opportunity for a company.
2. delete the company from companies section.
3. opportunities section doesnt gets changed. raise in this issue `https://github.com/twentyhq/twenty/issues/930`
4. refresh the opportunities page now the opportunities for deleted company is removed.
5. But the Board Column count dosent changes.

![image](https://github.com/twentyhq/twenty/assets/32263182/becb4c4f-3163-466a-810b-c1d654272deb)

in meeting its showing count -> 4 and in proposal -> 1 which is not matching with the opportunities cards count.

deleted companies opportunities is not getting removed from cardIds and in **EntityBoardColumn.tsx**  we have set 
**_numChildren={cardIds.length}_** 
for showing the number of childrens is showing wrong data.

**Comment by charlesBochet** [comment]
It seems that this issue has changed a bit. To me, the current behavior is:
- when I delete a company that is tied to an opportunity, the opportunity is still there. When I refresh, the opportunity is not there anymore
- This means that we need to update apollo cache optimistically using cache.evict()
