### ISSUE TITLE
Optimistic rendering strategy across the app

### ISSUE THREAD

**Issue by emilienchvt** [twentyhq/twenty#1113]
## Scope

This issue is about the optimistic rendering strategy to follow across the application. 
This is **NOT** about loader components or request errors handling.

## Context

When creating/updating/deleting objects from the UI, a request is sent to the server which proceeds to the mutation and returns a response with the updated object. In most cases we do not want to wait for that response in order to reflect the change in the UI. This is optimistic rendering.
Since we have not yet adopted a standard for developing this behaviour, we can find several approaches in the codebase.

The main 3 approaches are:
- 1️⃣ No optimistic rendering, but the UI is updated when the response is received, this is automatically handled by Apollo: [example for the task updates](https://github.com/twentyhq/twenty/blob/77d356f78a3ca299e3a68da2a5c41f951fdff1da/front/src/modules/activities/components/ActivityAssigneePicker.tsx#L55-L62). This is possible when no other request response is affected by the mutation.
- 2️⃣ Still no optimistic rendering, in the case when updating an object has impact on the response of other cached previous queries, we can use `refetchQueries` to refresh data from previous queries that might have come outdated: [example of the table row deletion](https://github.com/twentyhq/twenty/blob/77d356f78a3ca299e3a68da2a5c41f951fdff1da/front/src/modules/companies/table/components/TableActionBarButtonDeleteCompanies.tsx#L17-L22)
- 3️⃣ Having optimistic rendering by maintaining a state, separated from the cache, that is updated when the query is sent: [example for text edit fields](https://github.com/twentyhq/twenty/blob/77d356f78a3ca299e3a68da2a5c41f951fdff1da/front/src/modules/companies/editable-field/components/CompanyNameEditableField.tsx#L37C3-L37C68)

## Proposal

Apollo provides an API for [optimistic UI](https://www.apollographql.com/docs/react/v2/performance/optimistic-ui/). It enables developers to indicate the expected server response to a request and have the apollo cache updated accordingly.
This immediately solves the case 1️⃣ as demonstrated in https://github.com/twentyhq/twenty/pull/1114.

In addition to that, in case 2️⃣ when an update has impact on other queries, we should implement cache updates using Apollo's `update` parameter on the mutation hooks. This `update` of the cache will be performed twice:
- Once with the `optimisticResponse` provided, instantly
- Later on with the response from the server. We could get rid of the refetchQueries in most cases.

3️⃣ already implements refactoring, but we'll want to refactor to the above at some point.

Here is a list of the mutations that will need to be refactored:

| Page          | mutation                           | Status | Current implementation      | Preferred approach                         |
|---------------|------------------------------------|--------|-----------------------------|--------------------------------------------|
| Opportunities | Card fields update                 | ❌      | 2️⃣ refetch queries           | optimistic mutation                        |
|               | Creation                           | ✅      | 3️⃣ refetch + separated state | optimistic mutation + custom cache updates |
|               | Card move                          | ✅      | 3️⃣ refetch + separated state | optimistic mutation + custom cache updates |
|               | Card delete                        | ❌      | 2️⃣ refetch queries           | optimistic mutation + custom cache updates |
|               | Pipeline stage edit (rename/color) | ❌      | 2️⃣ refetch queries           | optimistic mutation                        |
| Tables        | Creation                           | ❌      | 2️⃣ refetch queries           | optimistic mutation + custom cache updates |
|               | Edit for flat fields               | ✅      | 3️⃣ refetch + separated state | optimistic mutation                        |
|               | Edit relations                     | ❌      | 1️⃣ automatic cache update    | optimistic mutation                        |
|               | Delete                             | ❌      | 2️⃣ refetch queries           | optimistic mutation + custom cache updates |
| Tasks         | Edit completed status              | ❌      | 2️⃣ refetch queries           | optimistic mutation + custom cache updates |
|               | Edit flat fields                   | ❌      | 2️⃣ refetch queries           | optimistic mutation                        |
|               | Edit relations                     | ❌      | 1️⃣ automatic cache update    | optimistic mutation                        |

I'll create detailed cards for the complex ones and quickly solve the simple ones.

## Questions

Do we agree with the approach and next steps ?

**Comment by magrinj** [comment]
@emilienchvt The described approach sounds good to me, we should use as much as we can the optimistic response system from Apollo, in some case like `TextInput` using an internal state like in example 3️⃣ is fine as Apollo doesn't really have good system to get a slice of the Apollo cache (like redux, or recoil).

**Comment by emilienchvt** [comment]
> In case of complex list queries this might be difficult

I agree, and this is mostly why we probably won't remove all the `refetchQueries` occurrences.
As you mentioned, in our case, the filters and sorts on the tables and board are the only cases of complex backend logic that we do not want to re-implement on the fronted side for optimistic rendering.

IMO it boils down to a UX question on these pages: When creating/updating rows or cards, do we want:
- 🅰️ The updated list to be filtered and sort as configured, which means seing the updated card/row jump from one place to another
- 🅱️ The updated line/card not to move so the user sees what they updated, with the risk to contradict the filters and sorts configured

Currently, we haven't adopted a consistent approach to this problem. In the table alone, for example: 
- When creating a new entry with active filters (for example on company in the People table), the new line does not show as it is filtered out (due to the refetch query strategy).
- On the contrary, if you filter people from a company, and update the company for one of them, the row still shows in the table (due to the fact that the table is not refetched)

The Opportunity board also has their inconsistencies.

**As a solution:** I think we can go for 🅱️ which sounds like a reasonable experience. For the creation, we mostly add the new item at the top or bottom so the logic is easy. For edits we can just update the card/row in the cache.

> we might want to abstract the reusable cache update logic in hooks?

We'll probably want to factor some code as you propose indeed. I expect to have more ideas on what specific interfaces can be useful when starting to actually implement these `updates`. Definitely open to suggestions if you have ideas!

**Comment by magrinj** [comment]
@thaisguigon @emilienchvt Apollo cache is normalized, so even for list with complex sort or order, Apollo just store a list of ids, and map of `__typename:id` to object.
When the cache is fetch the list is reconstructed.
Each time we fetch the same object, the result is merged with the old one.
We can decide in the Apollo client config how the merge is done, by default it's 1 level deep if I remember.
Here an article that well explain how it works:
https://www.apollographql.com/blog/apollo-client/caching/demystifying-cache-normalization/

**Comment by Bonapara** [comment]
@emilienchvt I think we should go for 🅰️, and implement a **smooth scroll** to move the screen up to the new card position. (B would indeed break the logic unless we add a "save" button that we don't want)

**Comment by emilienchvt** [comment]
@magrinj indeed, this works well for edits! Although in the case where the edit of a list item changes its rank in the list (based on selected sorts), or even gets it our of the list (based on selected filters), we need to decide the experience we want: I assumed we don't want to re-implement sorting on the frontend, but we still want to optimistically show the fresh data.

@Bonapara I agree 🅱️ beaks the filters.

Your proposal makes sense for re-sort on field edition. On the other hand 🅰️ can lead to other weird behaviours, examples (still for people table):
- When a company filter is selected, and a new table item is created, it has no `company` set. Does it mean we want to hide it ? The pattern of creating an object and not seing it in the table seems weird to me (it is the case today).
- When filters are selected for `company.id == companyA` and we edit the company of one of the filters to `companyB, do we want to have that row disappear from the view ? (not the case today)

From my understanding of the above, we seem to have an agreement on the simple "optimistic mutation" cases (see "Preferred approach" column in the table above). We will need to refine the "optimistic mutation + custom cache updates" on a case per case basis.

**Comment by Bonapara** [comment]
@emilienchvt for the first point, this is indeed Notion behavior for instance. (If filtered by greater than 10 they set 11), but I guess this would be really costly to implement? How costly to do this on every kind of fields?

https://github.com/twentyhq/twenty/assets/19412894/67c0a2b5-ec30-476a-b1ab-907444cc0697

For your second point, I think this is a behavior we also want (we might add a alert later to inform the user and help him move to the instance that was just filtered out like Github is doing on projects)

https://github.com/twentyhq/twenty/assets/19412894/4b4a334c-581d-4636-afae-4298da3b52d7

**Comment by magrinj** [comment]
For scenarios involving additions to a list with complex filters or sorting, I feel that leaning towards refetchQueries might be more straightforward and intuitive for users. Instead of grappling with optimisticResponse which might sometimes provide a jarring or unexpected UX (given the potential complexities in predicting the correct final position or state), simply refetching with a visible UI indicator like a subtle loading icon at the top of the list can be a direct way to signal to users that the item's position is being processed.

This approach offers a few advantages:

**Clarity & Expectation Management:** A loading icon effectively communicates to users that the item is being placed correctly, aligning their expectations.
**Simplified Logic:** It side-steps the complexities of creating an optimistic response for multi-faceted filters/sorts, reducing potential bugs or edge cases.
**Rapid Feedback:** Given the typically low response time between our frontend and server, this operation would be relatively quick, ensuring that users aren’t left waiting for long.
**Easy Integration with Other UI Elements:** Building on what @Bonapara showed in the second video, we could seamlessly integrate the snack-bar by examining the refetch-query's response. For instance, detecting a length difference would be straightforward, enabling us to notify users promptly if their action results in items moving out of the current view.

That said, I do recognize the appeal of optimistic updates in various scenarios, and they undoubtedly offer a swift, reactive UI. However, in contexts with intricate filters or sorting mechanisms, sometimes the simplest approach not only reduces developmental overhead but also provides users with the most predictable experience.

**Comment by charlesBochet** [comment]
Great discussion! Let's go for optimistic response as a first approach, then manual caches update in rare cases, and leave refetch queries if this gets too complex

**Comment by emilienchvt** [comment]
Thanks for your contributions! I think we can close the issue with the following

## Conclusion

Optimistic rendering can be straightforward to implement in simple cases, but there are more situations when complex logic such as filter and sorts is involved.
Pragmatically, we'll go for the low hanging fruits for now and leave the more complex cases (involving complex cache update, new UX behaviours and important design decisions) for future issues.

Back on the table in the initial post, here is a recap of the cases found in the app, I created tasks for each of these so we can implement:

| Page          | mutation                           | Status | Preferred approach                       | Created issue                                  |
|---------------|------------------------------------|--------|------------------------------------------|------------------------------------------------|
| Opportunities | Card fields update                 | ✅      | Add optimistic mutation                  |                                                |
|               | Creation                           | ✅      | Leave as it is                           |                                                |
|               | Card move                          | ✅      | Leave as it is                           |                                                |
|               | Card delete                        | ❌      | Add optimistic mutation and update cache | https://github.com/twentyhq/twenty/issues/1132 |
|               | Pipeline stage edit (rename/color) | ❌      | Add optimistic mutation                  | https://github.com/twentyhq/twenty/issues/1133 |
| Tables        | Creation                           | ❌      | Add optimistic mutation                  | https://github.com/twentyhq/twenty/issues/1134 |
|               | Edit for flat fields               | ✅      | Leave as it is                           |                                                |
|               | Edit relations                     | ❌      | Add optimistic mutation                  | https://github.com/twentyhq/twenty/issues/1135 |
|               | Delete                             | ❌      | Add optimistic mutation and update cache | https://github.com/twentyhq/twenty/issues/1137 |
| Tasks         | Edit completed status              | ❌      | Add optimistic mutation                  | https://github.com/twentyhq/twenty/issues/1138 |
|               | Edit flat fields                   | ❌      | Add optimistic mutation                  | https://github.com/twentyhq/twenty/issues/1138 |
|               | Edit relations                     | ❌      | Add optimistic mutation                  | https://github.com/twentyhq/twenty/issues/1138 |
