### ISSUE TITLE
Kill the hex color codes data stored on pipeline Stage

### ISSUE THREAD

**Issue by emilienchvt** [twentyhq/twenty#1116]
With this PR https://github.com/twentyhq/twenty/pull/780 we enabled users to pick a color for the pipeline stage columns from a preset palette.
Previously, the colors were stored as hex codes.

We want to get rid of the old behaviour and force the stored colors to be part of a given enum. This will also simplify the code on the frontend side.

**Comment by charlesBochet** [comment]
Duplicate of https://github.com/twentyhq/twenty/issues/968
