### ISSUE TITLE
Background blur is invisible on menus

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1117]
On the cell menus, I cannot see the background blur because there is two layers of background (Green and red on the picture)
- Check if it's only the case on cell menus. (Not on the filter and sort menu)
- There is also a bad border-radius to fix (the red one)

![Image](https://github.com/twentyhq/twenty/assets/19412894/ca55a2d4-75b2-44be-a33d-1019a3b6a37c)

**Comment by Jforstman** [comment]
I would like to try and work on this.  Can you please assign to me?

**Comment by Bonapara** [comment]
Done, thanks @Jforstman!

**Comment by Bonapara** [comment]
I think it's not. Inputs are not opening above cells but inside cells. They should open above the cell to avoid the following behavior:

https://github.com/twentyhq/twenty/assets/19412894/90cf2ddd-b095-471f-835a-317be2190b35

@lucasbordeau FYI

**Comment by lucasbordeau** [comment]
We could maybe use a createPortal if that looks like a good solution, or else maybe see useFloating like in dropdown, or do it manually with CSS.

**Comment by Bonapara** [comment]
Yes done, @abhithory! Thanks

**Comment by abhithory** [comment]
Hi @Bonapara , I have fixed these issues and made PR, Please review this

**Comment by Bonapara** [comment]
Thanks @abhithory! Our tech team will review it shortly.
