### ISSUE TITLE
Testing stack 

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#1129]
What are the frameworks used for testing? @charlesBochet told me that for frontend Storybook is used while for backend Jest is used. I'd like to know it because I want to help with automated tests and it's important for know in case someone else would like to help as well

**Comment by charlesBochet** [comment]
@BOHEUS We do need help on testing!
Here is our current plan:

## Front-end

### Storybook testing (interaction tests + visual regressions with Chromatic)
- Status: overall good coverage (70%+), the strategy is not 100% clear here, we have different implementations in some tests
- Trigger CI
- Scope: 1) Pages to catch most of the code  2) Modules 3) UI components. The smaller component we test, the more precise we are on edge case

### Unit testing with Jest
- Status: we have written a few examples, we add tests when we fee it's needed (complex logic or many edge cases that cannot be covered by Storybook tests)
- Trigger CI
- Scope: hooks / functions with complex logic

## Back-end

### BE E2E tests with Jest
- Status: we have written one example in companies.e2e-test.ts, we would need to revisit this test to make sure it's complete, then cover all other endpoints. We will measure backend coverage on these tests and aim 80% code coverage
- Trigger: CI
- Scope: All


### Unit testing with Jest
- Status: we have written a few examples, we add tests when we feel it's needed (complex logic or many edge cases that cannot be covered by E2E Jest tests)
- Trigger: CI
- Scope: services / functions with complex logic

## End-to-end

### Cypress E2E
- Status: we have nothing here
- Trigger: Manual, run them on our pre-prod environment (app-next.twenty.com)
- Scope: critical flows: authentification, table views, pipeline views, tasks, ...

**Comment by charlesBochet** [comment]
If you have experience with any of those, or would like to work on a part, we can discuss the details here!

**Comment by BOHEUS** [comment]
I do have experience with manual testing, but I'm open to new testing frameworks, I know Playwright for FE as I'm using it in work and it's user-friendly with its codegen option for beginners (with JUnit). For API, I use requests in Python with Pytest and additional libraries depending on needs.

I can try writing tests in Cypress, but I need to know in which language tests should be written. @charlesBochet

I also thought about writing tests in several frameworks just for comparison to see how they perform, what they are able to do compared to others, etc. but it's not necessary, especially now at the beginning of the project. :)

**Comment by charlesBochet** [comment]
Could you try writing cypress test in typecript, that we would run on app-next.twenty.com?
I'm especially interested into testing authentication and onboarding flow to start with

This would secure release quality on long term!

**Comment by BOHEUS** [comment]
I'll try, but I can't tell how much time it'll take me as I know TS only by the name.

**Comment by charlesBochet** [comment]
Thank you! Feel free to ping me on the issue if you need :)
