### ISSUE TITLE
New contextual menu design

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1151]
On right click on an index cell, change the horizontal context menu to the following design:

https://github.com/twentyhq/twenty/assets/19412894/4542aaa6-c062-4358-8ccd-9475b5353ce2

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=9008-75469&mode=design&t=DKCINynO8chW4xR3-4

**Comment by charlesBochet** [comment]
This has been implemented! Thanks @brendanlaschke!
