### ISSUE TITLE
Add "Task" on the index action bar

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1152]
# Current behavior

https://github.com/twentyhq/twenty/assets/19412894/d1bde166-0af6-43f4-91ef-b19d083f909e

# desired behavior

![Image](https://github.com/twentyhq/twenty/assets/19412894/5f2c244d-cebd-4095-aa2f-21a3d4090eb3)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=3625-51511&mode=design&t=DKCINynO8chW4xR3-4

**Comment by charlesBochet** [comment]
This has been solved by @brendanlaschke, closing it!
