### ISSUE TITLE
Change task titles

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1160]
# Card

Replace "(No title)" by "Task title"
Don't display "(No content)" when there is no content (display nothing, not even a blank space)

![Image](https://github.com/twentyhq/twenty/assets/19412894/f35db550-ac18-46b0-a5b3-62260d9a48e2)

# Panel

Change text from "Task title (optional)" to "Task title"
Don't save tasks without title nor content

![Image](https://github.com/twentyhq/twenty/assets/19412894/ebad09a8-c2c3-47ff-9fde-e1b60ed7a0d0)

**Comment by sunilk4u** [comment]
Hi, I can work on this one.

**Comment by sunilk4u** [comment]
@charlesBochet  I am checking if title and body are empty or not saving their boolean equibalent in a state which i will use when right drawer closes to delete the activity if both are empty. Now the problem with body is that the array contains many objects, and each object has props object and each props has content array. After every body state change if i loop through body to see if every object contains content or not, it will severly affect performace. How should i go about it ?

![image](https://github.com/twentyhq/twenty/assets/42198140/4238ac06-966d-42b6-bd16-19f12cafb616)

**Comment by charlesBochet** [comment]
@sunilk4u sorry for the late answer, I've been very busy this week-end. I have no quick answer to your point. I will investigate tomorrow and provide a documented answer!

**Comment by charlesBochet** [comment]
Regarding your PR, I've commented on it, LGTM with minor comments :)

**Comment by charlesBochet** [comment]
Regarding your question, I think it's about a separate issue which is (I can't find the issue): "Create the task only when the user enter a title or the content"

If you want to work on this one, which is a hard one, here is what I would recommend:
- stop creating the activity in useOpenCreateActivityDrawer. Instead, create a draftTask in a recoil state atom (there are many examples of recoil states in the code viewableActivityIdState is one for example)
- also push task data in this state from useOpenActivityRightDrawer
- then from RightDrawerCreateActivity and RightDrawerEditActivity (and possibly all their children), read the task data from this state
- also create "isTaskPersistedInDBState" that is set to true in edit mode, and to false in create mode
- in edit mode, as the task isTaskPersistedInDB = true, perform graphql mutations to handle update as it is right now
- in create mode, persist the graphql mutation when a title or a content is entered, set this isTaskPersistedInDB to true and then it's same behavior as editmode

Feel free to take another issue if you fill this one might be too complex. If you want to work on it, feel free to ask your questions here, I'll guide you as much as I can

**Comment by sunilk4u** [comment]
I will like to continue on this. Thanks for help.
