### ISSUE TITLE
The scrollbar should fade away when the scroll is finished or not started

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1169]
When the scroll is not being used, the scrollbar should fade away:

# Current behavior

The scrollbar always stays in view, even when the scroll is finished or not started.

![Image](https://github.com/twentyhq/twenty/assets/19412894/6252de01-2253-4b87-a790-9c60d72a750c)

# desired behavior

The scrollbar should fade away when the scroll is finished or not started

https://github.com/twentyhq/twenty/assets/19412894/c5b49b3d-7b18-433b-953f-e22dbe4f6e17

**Comment by charlesBochet** [comment]
Implement something like this:
https://stackoverflow.com/questions/68415973/hide-scrollbar-when-not-scrolling-mac-like-behaviour

1) We would like to introduce a ui hook (similar to useListenClickOutside for example) that can be attached to a div using a ref.
2) On mousewheel, display the scrollbar, then hide it after a delay of 2 seconds if possible with an animation (we use framer motion)
3) make sure this is not creating intempestive re-renders
4) Implement it on PersonShow and CompanyShow in the Timeline section
