### ISSUE TITLE
New behavior for editable fields

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1170]
## Scope: 

This enhancement will be applied to editable fields wherever in the app they are used:

**Opportunities** 

![Image](https://user-images.githubusercontent.com/102394218/259895577-fa0179b8-b1c5-4fb9-8d7d-6545c0d39611.png)

**People show**

![Image](https://user-images.githubusercontent.com/102394218/259895587-84b97b6f-0066-484b-991b-a9d8a6b6183a.png)

**Company show**

![Image](https://user-images.githubusercontent.com/102394218/259895601-b38b79e3-af16-44e0-80d0-4d86d0ea2368.png)

**Task details**

![Image](https://user-images.githubusercontent.com/102394218/259895614-bb07192d-8645-4a47-a570-adfd5a02197f.png)

**Note details**

![Image](https://user-images.githubusercontent.com/102394218/259895633-6d28eb32-371c-4d76-9a4e-fd194967203e.png)

## In those pages we have two main types of fields:

**1. "Type 1"  default editable fields**

Clicking on these default editable fields triggers the display of the edit mode. This behavior is observed in fields containing addresses, job titles, account owner, dates. As an example, clicking on a date field opens a calendar interface.

An example of one of these fields can also be seen in the video. In this ticket, we will refer to them as "type 1"

https://user-images.githubusercontent.com/102394218/259853788-6c8501b7-0bb2-46f9-8fd8-8a8f128392db.mp4

**2.  "Type 2" Relation editable fields**

Fields in which the value can be modified exclusively by clicking on the editable icon, for instance, those containing links, main contact, and more. An example of one of these fields can be seen in the video. In this ticket, we will refer to them as "type 2"

https://user-images.githubusercontent.com/102394218/259853930-653dd1f0-3fce-424f-80e1-cdafc32bc6f4.mp4

# Type 1 - default editable fields :

### Current Behavior

Hover: "Background-color" is transparent/light

![Image](https://user-images.githubusercontent.com/102394218/259856538-07519360-541a-4eaa-9fc3-0537bd5baf13.png)

### Desired Behavior:

Change to "Background-color" = transparent/lighter

![Image](https://user-images.githubusercontent.com/102394218/259857331-43275518-8e6b-4276-802f-172b2050420c.png)

# Type 2 - Relation editable fields:

Unifying Hover Interaction: Implement a consistent hover behavior for all fields. **Same hover behavior between "Type 1" and "Type 2".**

### Current Behavior
The "div" enclosing the content lacks a hover background-color, and the editable icon is positioned at a distance from the content.

![Image](https://github.com/twentyhq/twenty/assets/102394218/a7fbad04-2850-4323-b965-b29333671d79)

### Desired Behavior:
Implement a hover effect for the "div" encompassing the content, setting the "background-color" to transparent/lighter. Additionally, position the editable icon adjacent to the content.

As depicted in the video, you can observe a subtle background-color around the chip when hovering.

https://github.com/twentyhq/twenty/assets/102394218/aa3c4702-64d1-4ce6-917a-f628dd4d735f

When multiple elements are present, the "div" containing them all should have the background-color, and you can observe this behavior in the video.

https://user-images.githubusercontent.com/102394218/259884928-c6a6b2d2-a7c2-4822-ac30-8544ec0120b7.mp4

### Current Behavior
When hovering over a Type 2, only the content experiences a hover effect; there is no visible background-color around the content.

![Image](https://github.com/twentyhq/twenty/assets/102394218/244f8080-6b7f-48c6-b83d-5b87098d9ba2)

### Desired Behavior:
 When the pointer hovers over the content, both the hover effect of the "div" and the content should be triggered.

https://user-images.githubusercontent.com/102394218/259865055-0ae6f5e6-ff18-4ee5-bf1e-4834c95af6fd.mp4

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5910-72411&mode=design&t=yeLiDDEvAXdS8PPk-4

By implementing these changes across various sections, we aim to provide users with a uniform and intuitive hover experience, enhancing usability and maintaining a consistent interface.

**Comment by proof3** [comment]
Hey @jenalla I would like to handle this issue.
