### ISSUE TITLE
Completed tasks should be Strikesthrough

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1176]
# Current behavior

![Image](https://github.com/twentyhq/twenty/assets/19412894/257b82e9-f578-4ef1-8c25-636401846de4)

# Desired behavior

**Make sure to implement everywhere we display completed tasks**

![Image](https://github.com/twentyhq/twenty/assets/19412894/91469378-6f5c-494c-8852-9bf97d94710d)

**Comment by Manikanta528** [comment]
I can work on this issue

**Comment by FelixMalfait** [comment]
Thanks a lot @Manikanta528! Just assigned you to it

**Comment by charlesBochet** [comment]
This as been completed by @Manikanta528! Thank you
