### ISSUE TITLE
Task status update sync issue

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#1203]
The task status on the FE does not reflect its change in DB after an update.
When we check or uncheck the checkbox, it should move to its dedicated section (To do or Done) but we need to refresh the page to see its effect.

https://github.com/twentyhq/twenty/assets/1834158/68ea4c87-fbf2-476c-ba8c-5b9ecbb74b86

```[tasklist]
### Tasks
- [ ] We use apollo cache here. We should make sure to update it when we complete a Task. To do so, please use optimisticResponse in apollo mutation
```

**Comment by Manikanta528** [comment]
I can work on this issue

**Comment by charlesBochet** [comment]
Please go ahead @Manikanta528
