### ISSUE TITLE
When a I delete a Company from Companies Table, the Opportunities tied to this companies are optimistically removed

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1213]
There is a bug currently, to reproduce:
- Go to Opportunities and find a card  that is tied to a company
- Go to companies and delete this company (right click, actionBar > Delete)
- Go back to Opportunities, see that the card is still there
- Refresh and the card disappear

The problem is that apollo cache is not updated. On company deletion, we should manually evict the pipelineprogress from the cache. Use `cache.evict()`, there are a few examples in the codebase

**Comment by bahaar-ghafari** [comment]
Hey @charlesBochet , I'm interested in working on this.

**Comment by charlesBochet** [comment]
@bahaar-ghafari Yes, please! Thanks for the help :)

**Comment by charlesBochet** [comment]
@bahaar-ghafari, any update on this one?

**Comment by lakshay-saini-au8** [comment]
@charlesBochet 
I would like to work on this task

**Comment by charlesBochet** [comment]
@lakshay-saini-au8, I took it actually as I wanted to introduce a new pattern in the app: https://github.com/twentyhq/twenty/pull/1629

Any help is welcome, feel free to take any other good first issue! :)
