### ISSUE TITLE
When I delete a company, people tied to this company are unassigned

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1214]
There is a bug currently, to reproduce:
- Go to People Table and find a person that is tied to a company
- Go to companies and delete this company (right click, actionBar > Delete)
- Go back to People Table, see that person is still assigned
- Refresh and the person is unassigned

The problem is that apollo cache is not updated. On company deletion, we should manually update the cache. use `cache.modify`

**Comment by abhip167** [comment]
I am happy to take this.

**Comment by charlesBochet** [comment]
@abhip167 Please go ahead, thank you for the help :)

**Comment by abhip167** [comment]
While restarting the server, I got this error.
![image](https://github.com/twentyhq/twenty/assets/23724986/3639318c-f463-405f-b6f1-3b295d42ee9c)

**Comment by abhip167** [comment]
Please review it and let me know in case of any edits. I have used ` cache.evict() ` as we are deleting the cached entry itself.

**Comment by Weiko** [comment]
This seems to be fixed, thank you. Closing this one @charlesBochet
