### ISSUE TITLE
Edit filter & Sort style

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1215]
# Current

![Image](https://github.com/twentyhq/twenty/assets/19412894/481c5a74-1226-46b0-a964-bd25f3ad2bb6)

# Desired
- Filter & Sort background should be: Accent quaternary
- Filter & Sort border should be: Accent tertiary
- Filter & Sort border-radius should be 4px
- Filter & Sort "X" close button icon hover should be Accent secondary
- Sort text weight should be medium instead of regular (sort only)
- There should be a separator with 4px padding between Sort & Filter

https://github.com/twentyhq/twenty/assets/19412894/a3fab0a5-21cf-4150-bc30-a085ace82b0e

**Comment by charlesBochet** [comment]
Thank you @brendanlaschke! Closing this issue
