### ISSUE TITLE
Navigation header style fix

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1216]
# Current behavior

The menu header is no more aligned with the underneath content:

![Image](https://github.com/twentyhq/twenty/assets/19412894/f6d091e3-42f2-4b01-875d-4b43b2f6eeaa)

# Desired behavior

The menu header logo should be vertically aligned with the menu element icons. (there should be no margin and only a 4px left padding) 

The "collapse menu" icon should appear only on the menu hover (It should be hidden unless the navigation bar is being hovered). Add a 150ms fade transition from opacity 0% to opacity 100%

![Image](https://github.com/twentyhq/twenty/assets/19412894/9381be3a-8944-4288-806f-80a1cab17e89)

**Comment by Ahsankhalid618** [comment]
/attempt 
Can I start working on this?

**Comment by gracious7** [comment]
I wanted to work on this. Can i start working ?
