### ISSUE TITLE
Bug: Filter Datepicker overflowing and hidden partly

### ISSUE THREAD

**Issue by brendanlaschke** [twentyhq/twenty#1224]
<img width="465" alt="Bildschirmfoto 2023-08-15 um 22 41 29" src="https://github.com/twentyhq/twenty/assets/48770548/9a4b5aa3-2939-4b1e-b305-a85d989b09ee">

This ticket should be worked on once, the Dropdown work is complete. Hold for now. https://github.com/twentyhq/twenty/issues/1265

**Comment by charlesBochet** [comment]
@brendanlaschke thanks for creating the ticket :) We are taking it in the current sprint
