### ISSUE TITLE
Setup Email Verfication

### ISSUE THREAD

**Issue by Palakkgoyal** [twentyhq/twenty#1235]
In the waiting-list form there is a input for email but it doesn't have any verification system. I want to add the verification such that when user clicks the submit button they'll get a OTP in their mailbox.
![Screenshot 2023-08-16 202532](https://github.com/twentyhq/twenty/assets/116902573/549037ee-8649-497d-9cb2-2061d73f3963)

```[tasklist]
### Tasks
```

**Comment by Bonapara** [comment]
Hi @Palakkgoyal. We are using https://tally.so/ for this form. I think it's not possible to insert an email validation with them.

**Comment by FelixMalfait** [comment]
Yes closing since the code for twenty.com is not open source (not by choice but because it's not code it's managed through Framer.com). Feel free to open an issue about anything you see on app.twenty.com which is the app powered by the repo
