### ISSUE TITLE
📮 Email auto logging

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1254]
The goal is to enable emails to auto-log on the "Companies" and "People" detail pages.

Notes: Internal emails should never be synchronized (even if someone adds my company as a company record). For V1, logging is only done when a company or user is already existing in the CRM (no new records creation). V2 will probably auto-populate the CRM from your emails to make it so smooth to onboard Twenty)

```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/1270
- [ ] https://github.com/twentyhq/twenty/issues/1272
- [ ] https://github.com/twentyhq/twenty/issues/1273
```

**Comment by AndryHTC** [comment]
### Integration with Microsoft365 for Email Logging
**Market Share**: Microsoft365, especially Microsoft Outlook, is a dominant player in the email and business productivity landscape. Its integration would significantly expand our potential user base.

**Business Centricity**: With many enterprises and SMBs (Small and Medium-sized Businesses) leveraging Microsoft365 for their daily tasks, integrating with it would enhance the practicality and utility of our CRM for these businesses.

**Comment by Bonapara** [comment]
@AndryHTC Agreed. We feel our first customers will be startups using Google Workspace. Microsoft 365 should come soon though
