### ISSUE TITLE
Options button not available on Opportunities page

### ISSUE THREAD

**Issue by ksafford** [twentyhq/twenty#1258]
![image](https://github.com/twentyhq/twenty/assets/1257916/cc37209f-bb59-4773-9425-2b94a9a1c3eb)

As seen in the image, "Filter" and "Sort" are available on the Opportunities page, but "Options" is not. All three show up on the People and Companies pages.

**Comment by charlesBochet** [comment]
Yes, indeed, the options button is especially useful to deal with views and we haven't implemented views on Opportunities yet. We are going to implement it this week though!
Closing this issue
