### ISSUE TITLE
Find a naming convention for sidecar components

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1263]
The idea is that sibling / sidecar components like PageChangeEffect or HooksCompanyBoard, TableEntityHook, etc. Are always acting as an isolated useEffect that doesn't trigger re-renders in the tree.

Since it's always about a useEffect, we could find a convention for the naming.

We can imagine that the term "Effect" could be a suffix.

The useEffect reacts to some changes in its dependencies, so a list of the main dependencies or their broad scope could also be in the naming.

`HooksCompanyBoard` could be `CompanyProgressQueriesEffect`, when it's about a bunch of queries updating a Recoil state.
```[tasklist]
### Tasks
- [ ] + Doc
```

**Comment by lucasbordeau** [comment]
Let's go for the Effect suffix and the convention that an Effect component should contain at least one useEffect or an equivalent (useGetRequest, etc.) and return no component.

**Comment by charlesBochet** [comment]
This has been completed!
