### ISSUE TITLE
Mock add company progress mutation in storybook and create test

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1266]
We need to add a mock for `useCreateOneCompanyPipelineProgressMutation`, see how it's done in `src/testing/graphqlMocks.ts`.

Then add a step in the `AddCompanyFromHeader` story in `Opportunities.stories.tsx`

**Comment by abhip167** [comment]
I am happy to work on it. Can you assign it to me ?

**Comment by charlesBochet** [comment]
Sure, go ahead @abhip167 :)

**Comment by charlesBochet** [comment]
@abhip167 still workingo n this one?

**Comment by abhip167** [comment]
Hi @charlesBochet, yes I am working on it. Couldn’t spare time for this since past few days but hopefully this week I will be able to contribute.

**Comment by charlesBochet** [comment]
Ok :)

**Comment by cu8code** [comment]
hey, I would love to work on this issue, (it's my first using storybook and graph-ql) here is how I will approach the problem:

> We need to add a mock for useCreateOneCompanyPipelineProgressMutation, see how it's done in src/testing/graphqlMocks.ts.

msm is the plugin that storybook uses to mock the graph-ql query. msm has object called graph-ql with 2 methods query and mutation. query/mutation takes `query_name` and a `function` that returns the mock data. so inside `src/testing/graphqlMocks.ts`

```
  graphql.mutation(
   name_of_the_mutation_called_during_useCreateOneCompanyPipelineProgressMutation,(req,res,ctx) => res(
      ctx.data({
       mock data ...
      }
      )
    )
  )
```

> Then add a step in the `AddCompanyFromHeader` story in `Opportunities.stories.tsx`

In Opportunities.stories.tsx have to create a `storybook step` which will use useCreateOneCompanyPipelineProgressMutation ?

**Comment by lucasbordeau** [comment]
Hi @cu8code, thanks for taking this task on !

Here's an example : 

```typescript
graphql.mutation(
  getOperationName(INSERT_ONE_COMPANY) ?? '',
  (req, res, ctx) => {
    return res(
      ctx.data({
        createOneCompany: {
          id: '9d162de1-cfbf-4156-a790-e39854dcd4ef',
          __typename: 'Company',
        },
      }),
    );
  },
),
```

You just have to return the mocked graphql response from a create mutation.

And yes adding a step in the test will be great.

**Comment by charlesBochet** [comment]
Closing this issue at is not relevant anymore
