### ISSUE TITLE
Link a Gmail account with "Connect with Google"

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1270]
You should be able to link your emails from both settings & the onboarding process:

### As a step of the onboarding, after the "Create profile step"

The default privacy value should be **object and metadata**

![Image](https://github.com/twentyhq/twenty/assets/19412894/5a08c8c8-9d3f-4636-9f9b-3228a0182217)

### From the settings, in a new "email account" section:

The default privacy value should be **object and metadata**

![Image](https://github.com/twentyhq/twenty/assets/19412894/66b11a2f-5645-4e4b-9ca8-5a9f63e99b96)

### Edit your settings once connected

Once connected, you should be able to edit your email sync settings:
- Unsync your email
- Change how people can see your emails
- Add an email to the blocklist (Emails from this person will never be shown on Twenty)

![Image](https://github.com/twentyhq/twenty/assets/19412894/770bb7c5-60ba-425d-8fa8-5b6c2823b7ea)

**Comment by FelixMalfait** [comment]
Don't you think the default setting should be "everything"? People will get more value of the CRM if they do. They are free to opt-out but I'm not sure we should push them to do so

**Comment by Bonapara** [comment]
Agreed

**Comment by FelixMalfait** [comment]
Closing as we have new design for this
