### ISSUE TITLE
📄 New detail page (Show)

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1277]
We will introduce a new show, featuring:
- A new timeline
- A Task tab
- A Note tab
- An Email tab

https://github.com/twentyhq/twenty/assets/19412894/8417dc07-a55c-4e26-addb-3d8bdc017cb7

```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/1278
- [ ] https://github.com/twentyhq/twenty/issues/1279
- [ ] https://github.com/twentyhq/twenty/issues/1280
- [ ] https://github.com/twentyhq/twenty/issues/1281
```

**Comment by FelixMalfait** [comment]
Closing as it's partially completed but keeping the subtasks that aren't finished
