### ISSUE TITLE
New timeline design

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1278]
The new timeline will offer a more compact design

Elements that should be logged into the new timeline:
- A note is created
- A note is edited

- A task is created
- A task is completed

- An opportunity is created
- An opportunity has been moved to another step
- An opportunity fields have been edited (Toggle to show which fields)

- An email has been received

- A person has been associated to a company record

More logs coming soon.

![Image](https://github.com/twentyhq/twenty/assets/19412894/898d4ffb-a04a-4c85-b244-2b7dd97638e4)

P.S: Have a look on how the timeline is made on Figma, I only used Flexbox to make it easy to customize.

![Image](https://github.com/twentyhq/twenty/assets/19412894/f1778147-089c-4371-806d-9f58f8593a36)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=6163-81155&mode=design&t=Og4rTLwXiXSccbH4-4

**Comment by abhip167** [comment]
I am happy to take this.

**Comment by charlesBochet** [comment]
Putting this on-hold as we are waiting for the bases of the new backend to be there

**Comment by FelixMalfait** [comment]
Closing as there is a similar, more detailed, issue + Brendan has done the frontend work
