### ISSUE TITLE
On view creation, use the current selected filters and sorts

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#1292]
Currently when a use creates a view with the Add view button (Views Dropdown) or Create View button (arrow dropdown beside "Update view" button) (see #1147), the new view is always empty (no filters/sorts).

**GIVEN** I am on the Companies/People page
**WHEN** I apply filters and sorts on the table
**AND** I create a new view
**AND** I select the new view in the Views dropdown
**THEN** I see the previously applied filters and sorts that are saved in the newly created view

**Comment by quuu** [comment]
hmm from my testing, the view filters don't save at all either
