### ISSUE TITLE
Bug: Vertical scroll bar graphic artifacts in dark mode

### ISSUE THREAD

**Issue by brendanlaschke** [twentyhq/twenty#1320]
Bottom right:

<img width="488" alt="Bildschirmfoto 2023-08-25 um 23 40 31" src="https://github.com/twentyhq/twenty/assets/48770548/92bc8198-0cb9-4ef6-88d2-983e34467ad6">

Not sure what's it origin maybe some sort of overflow or scroll issue ??

**Comment by mazidhussain** [comment]
Hi . I am fixing this issue.

**Comment by Weiko** [comment]
I renamed the ticket to reflect that fact that the bug seems to affect all scrollbar and not only show pages
