### ISSUE TITLE
[Timebox 1/5] Install a powerful NodeJS ORM that can support live schema changes

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1326]
We want to be able to support customFields, customObjects and remoteObjects while being multi-tenant.
This is not possible with our current Prisma ORM as a lot is happening at build time.

Let's find an ORM and set it up in the codebase in parallel to Prisma.
The goal of this ticket is to have one experimental endpoint that would use this ORM to read data from a database schema that would not be stored in the codebase (or stored as a json)
```[tasklist]
### Tasks
- [x] Pick an ORM, set it up in the codebase (ex: TypeORM)
- [ ] Create a new graphql resolver that uses it
```

For reference https://github.com/twentyhq/twenty/discussions/1142

**Comment by Weiko** [comment]
One note after investigation that was not properly described in discussions yet. We will need to resolve the public schema first to enable proper connection to the tenant, this public schema will have access to the workspace/user tables and will handle the login and prepare the connection to the tenant schema. Each tenant will have its own schema which will be the investigation of the next ticket. This seems promising so far.
