### ISSUE TITLE
Improve documentation submenu styling

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1341]
MedusaJS documentation is great: https://docs.medusajs.com/. This should set the standard for our documentation.

The scope of this ticket is to improve our documentation navigation : 
- we should be able to support 4 levels of documentation menu. Ex: Development > Front > Architecture > Recoil

To do so, we should:
1. Introduce a ModuleNavBar (displaying Back to home)

![Image](https://github.com/twentyhq/twenty/assets/12035771/13375687-8b17-40ab-b89a-438ebc0997ae)

2. Within the CoreNavBar or ModuleNavbar, Introduce a Section, a SubSection and Page Levels

![Image](https://github.com/twentyhq/twenty/assets/12035771/b7e066ba-ac26-4173-9702-6592792d0e54)

3. Style these taking inspiration from medusaJS

**Comment by FelixMalfait** [comment]
Maybe we should wait for a Figma redesign of our documentation?

**Comment by charlesBochet** [comment]
Could we prioritize it, I feel this is our public door for developers and right now it doesn't look good!

**Comment by FelixMalfait** [comment]
I agree it's important to prioritize! So much to do on design :)
cc @Bonapara
