### ISSUE TITLE
Hotkey scope is not correctly set in show pages for title fields

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#1343]
See video below, we shouldn't be able to use goto hotkeys and change pages inside an input.

https://github.com/twentyhq/twenty/assets/1834158/d3d13822-9421-45e5-9099-f2dddde6e3c1

**Comment by lucasbordeau** [comment]
### Technical input 

Components to work on : `CompanyNameEditableField` and `EntityTitleDoubleTextInput`.

Hint to solve this problem : use handlers onFocus on the HTML input components that will call `useSetHotkeyScope` with a EditableFieldHotkeyScope.EditableField and no custom scope.

**Comment by abhithory** [comment]
Hello @Weiko @lucasbordeau ,
As i understood, we should not be able to use 'goto' and 'pagechange' while we are typing in any input box. right? or is there something else?
and is this only for company name input field or for all input fields??
