### ISSUE TITLE
Refactor NavCollapse Hide

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1344]

**Comment by jenalla** [comment]
Check figma and ticket [1611](https://github.com/twentyhq/twenty/issues/1611)
NavCollapseButton need change 
color, stroke and background for hover

**Comment by FelixMalfait** [comment]
@charlesBochet this ticket doesn't have enough context for a good first issue, I'm closing it but feel free to re-open after you edit it. For tickets that are good first issue candidates but don't have yet a good description you can assign it to "CoreTeamTwenty" and/or add a label "Tech spech needed" label
