### ISSUE TITLE
On task assignee single select picker, the current option is not ticked

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1350]
On Tasks Page, we are using a SingleEntitySelect to pick the task assignee (through UserPicker). However, the current assignee is displayed as selected with a tick.

<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/1a1335cf-f1e7-4776-b215-2f5907de9375">

However, selected tick behavior should have been implemented in MenuItemSelectAvatar.

This ticket is about investigating this issue and fixing it! Should be a "small" issue!

**Comment by fadhilradh** [comment]
Hi @charlesBochet, can I take this task ?
