### ISSUE TITLE
As a User, on Tasks page and Done tab, I see my completed tasks without date categories

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#1363]
## Current
<img width="1277" alt="Screenshot 2023-08-28 at 13 26 54" src="https://github.com/twentyhq/twenty/assets/1834158/f4de918d-0364-45d0-af81-d365cccc1106">

## Desired behaviour
<img width="1287" alt="Screenshot 2023-08-28 at 13 34 17" src="https://github.com/twentyhq/twenty/assets/1834158/5a83b3f4-aea0-41fb-b7dd-74265cfc664d">

## Context
Date categories make sense in the "To do" tab because you might need to take actions on them based on their dates and urgency. This is not the case for completed tasks.

## Notes
We can simplify the useTasks hook. This hook should be able to expose completeTasksData with the rest so the consumer can decide if it wants to display completes or incompletes (with their dedicated filtered lists) tasks and then we can remove the need to fetch the activeTabId inside the hook which was making the code a bit confusing. 
{
    todayOrPreviousTasks,
    upcomingTasks,
    unscheduledTasks,
    completeTasksData
  }

**Comment by friendlymatthew** [comment]
Hi Felix! Can I work on this as well?

**Comment by lucasbordeau** [comment]
See this later : https://github.com/twentyhq/twenty/issues/1406
