### ISSUE TITLE
Docs : enum vs. string literal

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1365]
For DX we want either one or the other.

Problem with enums, problematic case : 
- Chip with 3 different variants ChipVariantEnum
- EntityChip with 2 different variants EntityChipVariantEnum

Very difficult to manipulate enums with a Pick.

- Autocompletion with enum has a poor DX

Add external references

**Comment by charlesBochet** [comment]
@lucasbordeau Closing this ticket FYI
