### ISSUE TITLE
Unable to setup server locally on windows, receiving prisma errors

### ISSUE THREAD

**Issue by mhamzabcs** [twentyhq/twenty#1367]
To try and setup on my Windows (with & without wsl is the same) So I have been following the guide: https://docs.twenty.com/developer/local-setup

I receive the following error in both cases as seen in the image, any idea?

![image](https://github.com/twentyhq/twenty/assets/20185057/9b80624c-83d1-41da-89b3-7ceb26395f4d)

**Comment by charlesBochet** [comment]
Hi @mhamzabcs, please join our discord: https://discord.gg/cx5n4Jzs57 and post a message in our #help forum, you'll get help from the community :)

**Comment by mhamzabcs** [comment]
@charlesBochet  Hey, Unfortunately this hasn't happened to anyone. Is there a way I can reach out to someone for support?

**Comment by charlesBochet** [comment]
Let's keep discussing here!
https://discord.com/channels/1130383047699738754/1145826305057767515/1145826305057767515
