### ISSUE TITLE
Update meta description and social card

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#1379]
How it looks like today: 
<img width="402" alt="Screenshot 2023-08-30 at 10 55 24" src="https://github.com/twentyhq/twenty/assets/6399865/c8ae6e15-62b2-412d-a704-88e7d7bab191">

Instead we should display a description: A modern open-source CRM
And a social card: https://github.com/twentyhq/twenty/blob/main/docs/static/img/social-card.png

**Comment by friendlymatthew** [comment]
Hi can I take on this issue?

**Comment by charlesBochet** [comment]
This ticket has been completed! Thanks a lot @friendlymatthew 
<img width="525" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/f0d683bb-85a3-455e-9dac-e4445c371a57">
