### ISSUE TITLE
Refactor icons passed as props with the new way

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1383]
Following up this discussion about how to have a clear and simple pattern to pass icons as props : https://github.com/twentyhq/twenty/discussions/1382

We should refactor the components that takes icon as props for feeding an IconButton or another generic component, that way we don't need to handle size before passing icons everywhere.

Components to refactor (non exhaustive) : 
- IconButton
- FloatingIconButton
- ActionBarEntry
- ContextMenuEntry
- NavItem
- Button

Search for `icon={` to find other components using it.

Be sure to run chromatic tests.

**Comment by friendlymatthew** [comment]
Hi Lucas! May I take this issue?
