### ISSUE TITLE
Handle text overflow in MenuItems

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1398]
Maybe use OverflowingText

**Comment by pranavp10** [comment]
would like to work on this can someone explain me bit about the issue

**Comment by lucasbordeau** [comment]
https://github.com/twentyhq/twenty/issues/1840

**Comment by abhithory** [comment]
@lucasbordeau @charlesBochet , is this still an issue or fixed?? can you please explain little bit more??

i want to work on this

**Comment by lucasbordeau** [comment]
You can work on it.

We need to harmonize overflowing texts in all the menu item variants by using OverflowingTextWithTooltip and verifying that the other elements of the menu item like icons and checkmark aren't shrinking.

Also it's a bit of work but we want it to be properly handled with an exemple in the stories.

**Comment by charlesBochet** [comment]
This has been solved, closing it
