### ISSUE TITLE
BUG - Weird clearing of columns when changing another column directly in the table view

### ISSUE THREAD

**Issue by xprnio** [twentyhq/twenty#1425]
I noticed weird behavior when for example first setting the email address of a person and then setting their city.
Sometimes setting the city clears the email field, sometimes neither of them get saved.
Will try to investigate further

**Comment by xprnio** [comment]
On further investigation, it seems that the table view doesn't send a request for updating the Email field.
I'll investigate the code and try to create a solution to this

**Comment by xprnio** [comment]
On even further investigation, it turns out that there seems to be some weird behavior with whatever decides whether or not to send the requests when editing cells. For example, setting the phone number to a value works, but then clearing it doesn't.

**Comment by xprnio** [comment]
The issue with the email field was that the long list of if-statements in the `useUpdateEntityField.ts` was missing a case for Email fields. Fixed in #1429

**Comment by xprnio** [comment]
What still needs to be investigated is the phone number field, since clearing that is still impossible from the tables view. Will come back with a fix for that soon enough

**Comment by xprnio** [comment]
Upon further investigation, the same issue exists with the LinkedIn and Twitter/X fields. Setting them to a value works, clearing them doesn't. Will try to fix those as well as the aforementioned phone number issues together, since they seem to be related (with them all having some extra functionality regarding formatting and validation).

**Comment by xprnio** [comment]
Turns out that the LinkedIn and Twitter/X fields didn't want to be cleared because they required the new value (an empty string) to be a valid URL.

**Comment by xprnio** [comment]
Somewhat similarly to the URL fields, there was a check missing to see if the field was cleared. Added that as well, both fixed in #1429.

**Comment by magrinj** [comment]
@xprnio Thanks a lot for the investigation, your report, and the fix, I'll definitely take a look this afternoon !

**Comment by charlesBochet** [comment]
These should have been fixed on main! Closing this issue :)
