### ISSUE TITLE
[eslint]: don't allow direct use of useHotkeys()

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1427]
**Context** : We're using https://react-hotkeys-hook.vercel.app/ for handling hotkeys on the app. But we implemented a wrapper around it (useScopedHotkey) to handle hotkey scopes and allow multiple parts of the app to listen to hotkeys at the same time without conflicting.

**Problem** : There's nothing that prevents someone who is not aware of this hook to use the raw useHotkeys hook. And it would also be nice to be told to use useScopedHotkey without waiting for a PR comment.

**Proposed solution** : Add a specific twenty eslint rule that prevents using useHotkeys that tells the developper to use useScopedHotkey.

**Comment by friendlymatthew** [comment]
Hi @lucasbordeau, currently useHotKeys is being used in `AutosizeTextInput`, `useSignInUp`. Should I write the rule, refactor the two occurrences?

Other occurances reside in useScopedHotKeys and useSequenceScopedHotKeys

**Comment by wwzeng1** [comment]
Sweep: retry
