### ISSUE TITLE
Improve stories for MenuItem components

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1464]
Add stories for new MenuItem components : 
- MenuItemSelectAvatar
- MenuItemMultiSelectAvatar
- MenuItemSelectColor

Add new props in relevant stories : 
- hovered
- disabled

**Comment by alfredlouisw8** [comment]
hi can you assign this to me?

**Comment by lucasbordeau** [comment]
Yes , please be sure to check examples of how CatalogDecorator works !
