### ISSUE TITLE
Milestones details != Releases details

### ISSUE THREAD

**Issue by AndryHTC** [twentyhq/twenty#1477]
Am I missing something or are the roadmap/project and the releases not coherent?

The milestone details are not even similar to the release details in 0.1.3
i.e.:
0.1.3 Release -> Views, EditableFields & CSV import
0.1.3 Milestone -> ✨ 0.1.3 UX Improvements
💸 Opportunities v2
🖍️ New Standards fields
🗂️ Views
🌞 Quality and support
🪑 Table fields style update

The milestone tasks are also not closed yet...

**Comment by FelixMalfait** [comment]
Haha yes definitely something we need to improve.
Milestone = initial plan
Release = reality :)

I don't think it's ever going to match perfectly but we can definitely do a much better job at planning!
