### ISSUE TITLE
Refactor useFilteredSearchEntityQuery to pass more filters.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1479]
With https://github.com/twentyhq/twenty/pull/1443, we can see that we might need to pass multiple filters in our where clause. 

For the moment the hook allows us to apply just one string filter to multiple fields. 

It's not enough because we might need to pass different strings to different fields.

The best approach would probably be to have an API like this : 

```tsx
const people = useFilteredSearchEntityQuery({
    queryHook: useSearchPeopleQuery,
    selectedIds: [personId ?? ''],
    filters: [
      {
        fieldName: 'firstName',
        filter: relationPickerSearchFilter,
      },
      {
        fieldName: 'lastName',
        filter: relationPickerSearchFilter,
      },
      {
        fieldName: 'companyId',
        filter: companyIdFilter,
      },
    ],
    mappingFunction: (person) => ({
      entityType: Entity.Person,
      id: person.id,
      name: person.firstName + ' ' + person.lastName,
      avatarType: 'rounded',
      avatarUrl: person.avatarUrl ?? '',
    }),
    orderByField: 'firstName',
    excludePersonIds,
  });
```

Minor details to improve : 
- Rename excludePersonIds to excludedEntityIds (because it's a generic hook)

**Comment by AdityaPimpalkar** [comment]
I'll pick this up @lucasbordeau. Thanks!
