### ISSUE TITLE
Fix design of 'sort' and 'filter' in 'People' and 'Companies' page

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1485]
### Scope:
- 'People' page
- 'Companies' page

# Icon Size Adjustment:

### Current design:

Currently, the icons used in the filter and sort options have a size of 24px.

![Image](https://user-images.githubusercontent.com/102394218/266162076-f47ce419-3207-44ba-bd7f-9ec82fbdbeba.png)

### Expected design:

Modify the icon size to be 14px.

![Image](https://user-images.githubusercontent.com/102394218/266162268-e99ee707-acae-4f35-8d11-a79e0d9866c2.png)

# Arrow Icon Correction:

### Current design:
In the filter functionality, the arrow icons for ascending and descending order are currently represented by "tabler-icon-arrow-_narrow_-up" and "tabler-icon-arrow-_narrow_-down" with a size of 24px.

![Image](https://user-images.githubusercontent.com/102394218/266162924-e9b47f41-9b7b-4290-ab62-f9934f112bf9.png)

### Expected design:

Adjust the arrow icon size to 14px and to "tabler-icon-arrow-up" and "tabler-icon-arrow-down".

![Image](https://user-images.githubusercontent.com/102394218/266163081-4dd68c64-e185-4c58-becc-5a7af95cb617.png)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=6775-72724&mode=design&t=wj3qNRzCpZ4Z34QZ-4

**Comment by PepeGonzale** [comment]
Hey, Can I work on this issue?

**Comment by jenalla** [comment]
Of course @PepeGonzale, thank you!

**Comment by yashug** [comment]
@charlesBochet @jenalla Please Would you kindly consider closing this issue now that the PR has been successfully merged?

**Comment by charlesBochet** [comment]
Yes we can! Thanks!
