### ISSUE TITLE
Fix design of 'Tab list' in 'People Show', 'Company Show' and 'Tasks'

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1486]
###  Scope:
- ShowPageRightContainer component in both the people show and company show.
- TopBar in 'Tasks' page

# 'People' and 'Company' show

### Current design

gap between elements within the StyledTabListContainer is 4px

Each tab has a padding of 8px'

The 

![Image](https://user-images.githubusercontent.com/102394218/266165734-aab8e08a-3648-4eeb-8f79-481c4b1a6b07.png)

### Expected design

Set the gap between elements within the StyledTabListContainer to be 8px.

Modify the styling for individual tabs by setting the padding for the left and right sides to 0.

![Image](https://github.com/twentyhq/twenty/assets/102394218/2f1e6cc7-969b-4979-87f8-db364d94ba68)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=9901-34423&mode=design&t=aiEVp36gXiI1JZeu-4

### Current design
The border is inside the container of the Tab, not on the gray line

![Image](https://github.com/twentyhq/twenty/assets/102394218/cd579fae-099e-48f0-9270-ca545157be91)

### Expected design
Border should be on the gray line

![Image](https://github.com/twentyhq/twenty/assets/102394218/59f51d0f-145b-4b6e-a974-01f18ec010d8)

# 'Tasks' page

### Current design

Each tab has a padding of 8px'

![Image](https://github.com/twentyhq/twenty/assets/102394218/1f627df5-a48e-4d6b-a16c-fa48c671976d)

### Expected design

Modify the styling for individual tabs by setting the padding for the left and right sides to 0.
Add gap of 8px and margin-left 8px on TabList container.

![Image](https://github.com/twentyhq/twenty/assets/102394218/1041dfe7-1335-420a-b212-bdd524244524)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5910-71591&mode=design&t=3YJj0dTADKmD1LhV-4

# Click effect on all TabList

Currently, there is no response when clicking on a tab, but we would like the background to change from 'tertiary' to 'quaternary' while the tab is being pressed.

https://github.com/twentyhq/twenty/assets/102394218/e3f318a7-805b-4476-afe8-7d4836f6e6fb

**Comment by jenalla** [comment]
Hello @zvolcsey, thank you for your work! I've made a few additional updates that need to be addressed on this ticket. If you could incorporate those changes, it would be great!

**Comment by zvolcsey** [comment]
Hi @jenalla! I am on it.

**Comment by zvolcsey** [comment]
Hi @jenalla! In the latest commit, I made improvements in the PR.
