### ISSUE TITLE
Remove Minimum Width for TableView Dropdown Button Label

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1498]
### Scope:
- 'People' page 
- 'Companies' page

# Remove Minimum Width for TableView Dropdown Button Label

### Current design:

label has a minimum width of 118px set 

![Image](https://github.com/twentyhq/twenty/assets/102394218/e297ac63-ba0e-4d4e-bb31-888953e4c466)

### Expected design:

Remove the minimum width constraint applied to the label 

![Image](https://github.com/twentyhq/twenty/assets/102394218/9612fc21-78b5-4ecd-8e6c-c251ab4f51d1)

**Comment by FelixMalfait** [comment]
Not seeing this issue in prod anymore, I think it has been solved. Feel free to re-open if not
