### ISSUE TITLE
Icon Buttons for Modify and Delete Views

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1502]
### Scope:
- 'People' page 
- 'Companies' page

# Icon Buttons for Modify and Delete Views:

### Current behavior:

Currently, the icon buttons to modify and delete a view are always visible.

https://github.com/twentyhq/twenty/assets/102394218/6ae43d97-da0c-415e-a424-dba7084c335b

### Expected behavior:

Modify the behavior so that these icon buttons only appear when a user hovers over a view in the views menu.

https://github.com/twentyhq/twenty/assets/102394218/16ee852a-de1a-455b-a0d6-374a96a2d85e

**Comment by Bonapara** [comment]
Seems to work on app.twenty.com but not on app-main.twenty.com
