### ISSUE TITLE
Create a CLI release command to bump version while publishing a new release

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1507]
## Context

Create a CLI command that would be listed in root package.json called `release`. This is useful as we often forget to perform a manual bump of package.json version while releasing.

## What

This command should take a version as argument: `yarn release {version}`
It should validate the version has the right format: X.X.X where X is a positive integer (or 0).
It should update package.json version

**Comment by Krish-Parekh** [comment]
@charlesBochet  Can I work on this ?

**Comment by ranjanmangla1** [comment]
HI, @charlesBochet , I would love to work on this issue, can you assign me?

**Comment by charlesBochet** [comment]
@Krish-Parekh sure, go ahead!

@ranjanmangla1 Please take any other good-first-issue as @Krish-Parekh asked for this one first :)

**Comment by charlesBochet** [comment]
@Krish-Parekh any update on this one? :)

**Comment by Krish-Parekh** [comment]
@charlesBochet   Can you please validate this approach so I can move ahead with coding it out 


Here's my approach 
---

## Approach to Solve the Issue

### 1. Creating a Root-Level `package.json`:

First and foremost, create a `package.json` file at the root level of the project

### 2. Dependencies Installation:

For our solution, we'll need the `semver` library to validate semantic version strings. Additionally, we'll use Node.js's built-in `fs` module to read and write to the `package.json` file. Install the necessary library with:

```bash
npm install semver
```

### 3. Script for the `release` Command:

Create a script named `release.js` in the root directory. This script will encapsulate the logic for the `release` command.

```javascript
// release.js

const fs = require('fs');
const semver = require('semver');

// Get the version argument from the command line
const [,, version] = process.argv;

if (!semver.valid(version)) {
    console.error('Invalid version. The format should be X.X.X where X is a positive integer (or 0).');
    process.exit(1);
}

const packagePath = './package.json';
const packageData = require(packagePath);

// Update the version
packageData.version = version;

// Write the updated version back to package.json
fs.writeFileSync(packagePath, JSON.stringify(packageData, null, 2), 'utf8');
```

### 4. Updating `package.json`:

Finally, add the `release` command to the `scripts` section of the root-level `package.json`. This allows us to run our new script using npm or yarn:

```json
"scripts": {
    "release": "node release.js"
}
```

**Comment by charlesBochet** [comment]
Looks great! Let's store the **version** in ./front/package.json and ./server/package.json (we should not have the version stored in the root package.json as front and back will likely be considered as independant packages in the future)

But it's nice to have the **command** in the root package.json to update both at the same time for now :) We can move it later when we separate front and server versions.

Thanks a lot!
