### ISSUE TITLE
Column resizing should be save at the device level

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1509]
# current behavior

Today, resizing a column is saved at the view level. 

# desired behavior

It should be saved at the device level (Cookies?) or User level. (Like Notion, and GitHub projects for instance)

**Comment by FelixMalfait** [comment]
@Bonapara we had discussed this before together and said that we'd prefer consistency of behavior for users (e.g. should I click "update" to save size changes or not? if I do, does it impact all users or just me?). What made you change your mind?

What about column visibility? Should that remain team-level + update button needed?

**Comment by FelixMalfait** [comment]
@Bonapara should we close this one since you seem to have create a similar one? Closing but feel free to reopen

**Comment by Bonapara** [comment]
You're fast 👀 Indeed #1580 is replacing this issue, let's forget the user-level column resizing for now
