### ISSUE TITLE
People & Companies bouncing glitch

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1512]
# Current behavior

When loading the page, the screen is "bouncing" horizontally:

https://github.com/twentyhq/twenty/assets/19412894/d26124d6-c4e3-4be0-a5d4-dbe15e927dd9

The same behavior happens when closing & reopening the sidebar:

https://github.com/twentyhq/twenty/assets/19412894/d142742b-b0df-4d3c-b77e-70f2e0adffef

# Desired behavior

No more bouncing!

**Comment by ranjanmangla1** [comment]
Hi @Bonapara , I would love to work on this issue, can you assing me this issue?

**Comment by FelixMalfait** [comment]
Hi @ranjanmangla1, thanks a lot!

**Comment by lucasbordeau** [comment]
#2268 fixes the first issue, we still need to address the right glitch on nav bar open.
