### ISSUE TITLE
Color '+' IconButton to add columns is incorrect on 'People' and 'Companies' pages

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1513]
### Scope:
- 'People' page
- 'Companies' page

In the 'People' and 'Companies' pages, when not all columns are displayed, a '+' icon is displayed to indicate the possibility of adding more columns. (remove properties in options menu)

# Issue:

The color of this '+' icon is currently set to 'text secondary'.

# Correction:

Adjust the color of the '+' icon to 'text tertiary'.

![Image](https://user-images.githubusercontent.com/102394218/266462874-5355c0cf-2f33-44d7-8947-a3d8c46f3704.png)

# Issue 2:

The + button should also be in a proper column:

### Current behavior

![Image](https://github.com/twentyhq/twenty/assets/19412894/748e6046-be04-4ae3-93f4-5b1f46c10643)

### Desired behavior 

![Image](https://github.com/twentyhq/twenty/assets/19412894/e89f29e1-ad1e-4f88-8348-74de192912db)

**Comment by lucasfirmo62** [comment]
Hi @jenalla, can I try to solve this problem? It seems to be something I usually resolve! Put me as Assignees.

**Comment by jenalla** [comment]
Hi @lucasfirmo62 go ahead! Thank you!

**Comment by charlesBochet** [comment]
@lucasfirmo62 Regarding Issue 2,
I've tried to fix it while using only CSS but it does not cover all case.
I believe that setting all column sizes manually (based on fields.size) is the right way to go.
- If with of the column containing the + should be the min of (40px, remaining_width). Remaining width covers the case where displayed columns do not fill the whole scrollable section width.

**Comment by Bonapara** [comment]
@lucasfirmo62 I have unassigned you to let someone else pick the issue

**Comment by PentesterPriyanshu** [comment]
@Bonapara can you assign me so that i can work on this issue

**Comment by charlesBochet** [comment]
Go aheas @PentesterPriyanshu :) thanks for the help

**Comment by Bonapara** [comment]
@PentesterPriyanshu are you on it? If yes I'll assign you to the issue. Thanks!

**Comment by PentesterPriyanshu** [comment]
> @PentesterPriyanshu are you on it? If yes I'll assign you to the issue. Thanks!

yes assign me i am start working on it

**Comment by charlesBochet** [comment]
@PentesterPriyanshu I've assigned the issue to you :) However, we can't guarantee nobody else will be working on it :)

**Comment by PentesterPriyanshu** [comment]
wait i am busy earlier now i am working on it

**Comment by PentesterPriyanshu** [comment]
@charlesBochet  i need help on frontend is not opening taking much time and after opening  not signing in from developer email a

**Comment by PentesterPriyanshu** [comment]
can you help me  how to open this page

**Comment by charlesBochet** [comment]
@PentesterPriyanshu I am not sure how to help you. Could you join our Discord and open a thread in #help?

**Comment by RobertoSimonini1** [comment]
Hi, is it Issue still available?
If it is I'd really like to work on it, it would be my first contribution to Twenty and I'll be very happy to do it.

**Comment by Bonapara** [comment]
Yes it is! I'll assign you :) Thanks @RobertoSimonini1

**Comment by FelixMalfait** [comment]
This seems to be fixed! Please re-open if not, but as I see it on /main the behavior looks nice
