### ISSUE TITLE
Positioning of Overlays for 'Sort,' 'Filter,' and 'Options' Menus

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1521]
### Scope

- 'People' page
- 'Companies' page
- "Opportunities' page

# Current design

Presently, the 'Sort', 'Filter', and 'Options' menus have inconsistent positioning, being too close to their respective buttons. 

https://user-images.githubusercontent.com/102394218/266701082-94e4072e-744b-4b67-a250-9569e7c5c575.mp4

# Expected design

To standardize the positioning, the following adjustments should be made:

- Align the right side of the menu with the right side of the div that contains all those text buttons.
- Position the menu 8px below the same div.

![Image](https://user-images.githubusercontent.com/102394218/266700497-b4456940-fbba-4312-8faf-dfa663d91ed2.png)

**Comment by FelixMalfait** [comment]
Not sure how this is done in the code but this one might be costlier than it seems (might be separate components, so need to refacto). Setting size as days, in doubt

**Comment by charlesBochet** [comment]
It should actually be straight forward. Everything happens in DropdownButton. use useFloating offset parameter to place the dropdown at the right position :)

**Comment by rayyyyofsunshine** [comment]
Is someone already working on this?

**Comment by charlesBochet** [comment]
Nobody! It's yours!

**Comment by rayyyyofsunshine** [comment]
Okay, I'd get on with this.

**Comment by rayy40** [comment]
@charlesBochet 
I positioned the menu 8px below the same div.

![Screenshot 2023-10-01 230748](https://github.com/twentyhq/twenty/assets/128903323/276144b8-43ac-4b3b-a8b7-b5845dc97127)

I was wondering what do you exactly mean by this?

Align the right side of the menu with the right side of the div that contains all those text buttons.
