### ISSUE TITLE
Button with 'IconChevronDown' in 'TableUpdateViewGroupButton' has incorrect size

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1522]
### Scope

- 'People' page
- 'Company' page
- 'Opportunities' page

# Current design

The 'IconChevronDown' button within the 'TableUpdateViewGroupButton' is currently not a square; it has dimensions of 31x24.

![Image](https://user-images.githubusercontent.com/102394218/266703969-c33ceadc-9723-454e-9da3-fe986bf76d33.png)

# Expected design

Adjust the size of the 'IconChevronDown' button to be a square with dimensions of 24px. 

![Image](https://user-images.githubusercontent.com/102394218/266704530-5eed0900-3c0d-4928-a4ef-505eb1c2c1c4.png)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=568-41602&mode=design&t=3YJj0dTADKmD1LhV-4

**Comment by PepeGonzale** [comment]
I would like to work on this

**Comment by FelixMalfait** [comment]
Thanks a lot @PepeGonzale

**Comment by charlesBochet** [comment]
Thank you @PepeGonzale!

**Comment by marcel951** [comment]
Hello! I am new to the open source community and would like to work on your project. Can you assign me this task? It is my first

**Comment by Bonapara** [comment]
Yes sure! Thanks @marcel951

**Comment by veerendra19codes** [comment]
hey @Bonapara I see there are no PR raised can i work on this issue? Please assign me !🥰✌️

**Comment by marcel951** [comment]
it took me a moment to get into the project, i am still working on the problem and will create the rullrequest this week
