### ISSUE TITLE
People & Companies column title menus

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1524]
# Desired behavior

When I click **and release** a column header a menu should appear allowing me to:
1) Move the column to the left
2) Move the column to the right
3) Hide the column

**Nothing should appear until I release the mouse click, see Notion database behavior, holding click on the column header should allow to drag and drop it to another place to reorder columns**

https://github.com/twentyhq/twenty/assets/19412894/0758265a-7ba6-4378-b67b-47ca5b544ada

# Point of attention

This should not concern the first column as we're not supposed to hide and move the first column (People & companies)

**Comment by ranjanmangla1** [comment]
Hi, I would lov eto work on this issue, can you please assign me this issue?

**Comment by FelixMalfait** [comment]
@ranjanmangla1 thanks a lot! @AdityaPimpalkar said he'd work on a similar issue here: https://github.com/twentyhq/twenty/issues/914 
So maybe it's best if you pick another one, or if you coordinate to work on it together and avoid duplicate work?
🙏 to both of you!
