### ISSUE TITLE
Inconsistency in database naming schema

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#1525]
Should we use snake case or camel case?

<img width="206" alt="Screenshot 2023-09-09 at 09 59 26" src="https://github.com/twentyhq/twenty/assets/6399865/7dbefed1-3a7a-4e6e-bb9e-adc85fcac2df">

**Comment by charlesBochet** [comment]
we should be using snake_case. Let's make sure to fix it while moving to the new backend architecture!
 @Weiko

**Comment by charlesBochet** [comment]
Closing this issue as this will be fixed in the new design
