### ISSUE TITLE
Refactor generic entity fields

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1534]
We share generic entity fields between cells and fields.

Right now we don't use generic fields from a generic place. 

Instead we have GenericTextCell or GenericURLField, so there is always a reference meta-type in the context of a generic field manipulation operation.

What we could do for a first refactor is to create one hook per meta-type.

For example : 

```tsx
const { fieldValue, updateField, fieldMetadata } = useGenericTextFieldInContext()
```

Keep in mind that we always manipulate generic fields inside a context.

**Comment by charlesBochet** [comment]
I have added more details here: https://github.com/twentyhq/twenty/issues/1633
Closing this issue
