### ISSUE TITLE
Format numbers on display

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1541]
We could have a generic AmountDisplay that formats number like this : `1,000,000` ? Maybe even localized.

There are plenty of react libraries for that.

@Bonapara

**Comment by brendanlaschke** [comment]
Couldn't the standard browser functionality be used for this? The [`Number.prototype.toLocaleString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) does exactly that: 

For me (browsers locale `de-DE` recognized) results in: 
```js
30000000.22.toLocaleString()
> "30.000.000,22"
```

And for eg. `en-US`:
```js
30000000.22.toLocaleString()
> "30,000,000.22"
```

**Comment by FelixMalfait** [comment]
Thanks a lot @brendanlaschke!
