### ISSUE TITLE
Remove autofocus in 'ShowPageSummaryCard' 

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1542]
### Scope:
- 'People' show
- 'Company' show

Currently, when users navigate to a 'Show' page, the 'EditableField' within the 'ShowPageSummaryCard' is automatically focused (autofocused). This autofocus behavior is unexpected.

The autofocus attribute should be removed from the 'EditableField' element in the 'ShowPageSummaryCard'.

https://user-images.githubusercontent.com/102394218/267098721-09f5c33f-6856-45c7-88df-963cbcb2d65d.mp4

**Comment by jenalla** [comment]
Hello! Thank you for your work@zvolcsey ! However, this issue is also present in the 'person' show, so the ticket is not completely resolved

Uploading Recording 2023-09-12 112946.mp4…

**Comment by zvolcsey** [comment]
Hi! @jenalla Sorry. I am on it.
