### ISSUE TITLE
Create a NumberInput

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1548]
To replace the current logic with TextInput and scattered casting code in handlers.

Proposition for API : 

```tsx
type NumberInputProps = {
  type: "integer" | "decimal";
  sign: "all" | "positive" | "negative"
  placeholder?: string;
  autoFocus?: boolean;
  value: number;
  onEnter: (newValue: number) => void;
  onEscape: (newValue: number) => void;
  onTab?: (newValue: number) => void;
  onShiftTab?: (newValue: number) => void;
  onClickOutside: (event: MouseEvent | TouchEvent, newValue: number) => void;
  hotkeyScope: string;
}
```

The goal is to prevent returning bad inputs, by checking every change in the input and returning either a valid number, either null.

Ideally the number should be formatted as the user type, see if we can use an existing library for that.

We should then use it in NumberCell and MoneyCell

**Comment by charlesBochet** [comment]
This has been solved, closing the issue!
