### ISSUE TITLE
Rename EditableCell, Input, Display, etc.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1549]
Update the naming : 

EditableCell => Cell
EditableField => InlineCell
Input => CellInput (TextCellInput, BooleanCellInput...)
Display => CellContent

So we can keep input for regular inputs: SettingsTextInput => TextInput

And we can also keep Field naming for what it means in data side: a property of an object (customFields, standardFields)

**Comment by shobhitexe** [comment]
Hey i am willing to take this can you plz assign this to me

**Comment by charlesBochet** [comment]
Closing this issue as we are working on https://github.com/twentyhq/twenty/issues/1633
