### ISSUE TITLE
Refactor everything that uses old DropdownButton

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1553]
We currently use two versions of DropdownButton in parallel, that forces us to implement features with legacy code.

We should instead rely on `ui/dropdown/components/DropdownButton` only and use `useDropdownButton()` to manage open/close of the dropdown, and everything that is managed inside the dropdown should not be the responsibility of DropdownButton.

**Comment by charlesBochet** [comment]
Closing this one as this has been done :)
