### ISSUE TITLE
Refactor recoil scope contexts

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1554]
We should avoid drilling down contexts as it totally defeats the purpose of a context ! We should instead call them directly where we need them anywhere below the component that instanciates the context.

Here is an example where it's used : 

```tsx
export function SingleEntityFilterDropdownButton({
  context,
  hotkeyScope,
}: {
  context: Context<string | null>; // <== We shouldn't pass contexts as props
  hotkeyScope: string;
}) {
  const theme = useTheme();

  const [availableFilters] = useRecoilScopedState(
    availableFiltersScopedState,
    context,
  );
```

**Comment by charlesBochet** [comment]
I believe this has been implemented, closing it. Let's discuss separately what we want to write in the doc
