### ISSUE TITLE
Create consistent ui/input and ui/display for Cell and Fields type : Probability, DoubleText, DoubleTextChip

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1562]
We already refactored into ui/inputs and ui/displays for multiple types : Date, Boolean, Phone, Email, Money, Number.

We still need to apply the same process to Probability, DoubleText and DoubleTextChip.

You'll find examples here :
- `ui/input/components/DateInput`
- `ui/input/components/TextInput`
- `ui/content-display/components/DateDisplay`
- `ui/content-display/components/TextDisplay`

It should be applied in Cell and Field components.

We will work on the Relation type in a separate issue.

**Comment by gitstart-twenty** [comment]
Hi @lucasbordeau , does this ticket require us to create `ui/cell/components` and `ui/fields/components` folder and transfer the content of `Probability`, `DoubleText`, and `DoubleTextChip` files to them?

Or, does it require us to create entries for `Probability`, `DoubleText` and `DoubleTextChip` in `ui/input` and `ui/display`?

cc @charlesBochet

**Comment by lucasbordeau** [comment]
Hi, as we have an ongoing refactor to rename input and content-display, that will still take some days, you can put it directly into the existing directories : input and content-display.

**Comment by charlesBochet** [comment]
"Or, does it require us to create entries for Probability, DoubleText and DoubleTextChip in ui/input and ui/content-displays?" ==> yes! 

Similar to:
ui/input/components/DateInput
ui/input/components/TextInput
ui/content-display/components/DateDisplay
ui/content-display/components/TextDisplay

Regarding Probability, you might only need the Input and no Display!

**Comment by charlesBochet** [comment]
Looks like it is exaclty what you've done in: https://github.com/twentyhq/twenty/pull/1658/files :)

**Comment by charlesBochet** [comment]
Regarding: https://github.com/twentyhq/twenty/pull/1658/files

these display and Input should not know about EditableFields/EditableCell and their context (see DateInput and DateDisplay) for example. They will be used by EditableFields and EditableCell in their XXXDisplayMode and XXXInputMode props. see GenericEditableDateFieldEditMode and GenericEditableDateCellEditMode for instance

**Comment by lucasbordeau** [comment]
We should implement this : 

- `ui/input/components/ProbabilityInput` (no content-display counter part, see BooleanInput.tsx)
- `ui/input/components/DoubleTextInput`
- `ui/input/components/DoubleTextChipInput`
- `ui/content-display/components/DoubleTextDisplay`
- `ui/content-display/components/DoubleTextChipDisplay`
