### ISSUE TITLE
Do we want to use function or arrow functions ?

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1563]
Currently we can use both and it would be better for consistency to have only one convention.

We can either : 
- Use `function` for functions and components to clearly mark the difference between a function and a variable
- Use arrow functions everywhere, so there are no questions or specific cases to think about. But then we need to be very rigorous with function naming, it should always start with a verb.

We currently have this eslint rule : `'func-style':['error', 'declaration', { 'allowArrowFunctions': true }],`, which allows both.

If we disallow arrowFunctions it would require to change around 148 functions in front/ and 32 in server/, which is still manageable.

--- Edit: See comment https://github.com/twentyhq/twenty/issues/1563#issuecomment-1718758679

**Comment by magrinj** [comment]
I think your proposal is good, it properly distinguish component and the rest.
But instead of just having function for one thing, maybe we can also consider arrow function everywhere so it's more easy for contributors, and more used in the open source libraries.

**Comment by charlesBochet** [comment]
I feel using both actually adds complexity. Since we must keep arrow functions for useCallback & co, let's use them everywhere and so we keep the simpler rule :)
