### ISSUE TITLE
Bug with auto scroll

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1564]
https://github.com/twentyhq/twenty/assets/26528466/8845c3ae-3587-47da-8f7d-72ecf581818f

If we have a soft focus on a cell, it will auto scroll every time we try to scroll vertically. 

This is problematic because we only want the table to auto scroll when we move the soft focus with the keyboard.

We should find a way to auto scroll only when moving the soft focus, and no other case.

**Comment by gitstart-twenty** [comment]
@lucasbordeau To confirm, the problem we're addressing is that when a cell is active and we scroll vertically, the table automatically scrolls back to that active cell, which isn't the intended behavior?

**Comment by charlesBochet** [comment]
@gitstart-twenty yes! it should not and should scroll to the focused cell only on focus move or if we enter in the cell

**Comment by gitstart-twenty** [comment]
> @gitstart-twenty yes! it should not and should scroll to the focused cell only on focus move or if we enter in the cell

Got it
