### ISSUE TITLE
Naming : the word "key" or "id" in sorts and filters is too vague

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1565]
The word key / id in filters and sorts is too vague.

We don't precisely know what it stores.

Could we use fieldName ? Or databaseFieldName ? 

That way we know precisely what it contains.

**Comment by lucasbordeau** [comment]
Will be completed when the new custom object API has been stabilized.

We will most probably replace `key` by `fieldName`.

**Comment by FelixMalfait** [comment]
@lucasbordeau closing this. Please re-open with instructions if it should be kept open!
