### ISSUE TITLE
Command bar is broken

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#1574]
Shows "no result found" and impossible to navigate with up/down keys, even though there are some results

<img width="702" alt="Screenshot 2023-09-14 at 13 19 25" src="https://github.com/twentyhq/twenty/assets/6399865/a60c0c69-b621-43f7-ad4e-0e6ddb5bd161">

When doing a fix, ideally write a test to make sure it doesn't happen again

**Comment by rishi-raj-jain** [comment]
@FelixMalfait 

Do we have documentation on how to set up the twenty repo? I am failing to find a CONTRIBUTING.md

**Comment by rishi-raj-jain** [comment]
Thank you for the quick turnaround!
