### ISSUE TITLE
First table column should not be hideable

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1581]
# Current behavior

I can hide the "name" of the People and Companies instances. That should not be possible as it prevents the user from accessing the associated detail page.

_In the following picture, I should not be able to hide "People" as first column_
![Image](https://github.com/twentyhq/twenty/assets/19412894/e7b2603e-be7b-4dc8-8482-20eeed5b6d03)

_There is no more people name on the table:_ 
![Image](https://github.com/twentyhq/twenty/assets/19412894/edb8417e-8bd1-413f-83f7-4d6d11344108)

# Desired behavior

The first column should not appear in the Options > Fields menu. The fields displayed in the menu should go from column 2 to column N.

_In the following picture, I cannot see the first table column "People"_
![image](https://github.com/twentyhq/twenty/assets/19412894/d187c746-d1eb-441c-b8f5-a2d167c5f0d9)

**Comment by charlesBochet** [comment]
@thaisguigon I think this should be added as a property in tableAvailableFieldsDefinition, what do you think?

**Comment by FelixMalfait** [comment]
@Bonapara wrong screenshot for desired behavior? (it seems to be the same)

For consistency could we maybe display the field but no "-" button?
Let's imagine we introduce other columns that cannot be hidden. I feel like it's a better design pattern to let people know it can't rather than magically making them disappear. But it's not a strong conviction so let's go with removing the field entirely from the list if you are convinced it's better

**Comment by FelixMalfait** [comment]
@thaisguigon when you decide on tech spec could you please add the scope label ? (front or front+back). I feel like front would be enough but I also understand if you think it's not good enough and we should cover backend. Thanks

**Comment by Bonapara** [comment]
Expected behavior design has been updated.

There are two behaviors we should prevent:
- Hiding the field, today
- Drag and drop the field to change the column order, soon

Both behavior seems ok to me as long it's for the first column. We will also have to prevent the drag & drop behavior, and it's might be easier to hide the full line, I don't have in mind a desactivated state for drag and drop as we speak.

What are the use cases for mandatory columns in the future ?
