### ISSUE TITLE
Company Picker Dropdown content (MenuItem) width is not correct

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1584]
**Current behavior**

On Opportunities page, the top-right '+' dropdown content does not fill the whole width:
<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/5e523c9c-ca7f-46a2-96e2-92a09a11be32">

Same on People Page:
<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/a03f10cf-fe30-4391-856e-701b1a0009f4">

On Opportunities page, the '+ New' Dropdown does not fill the whole column width:
<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/b9a71ac4-56c2-4f80-a082-ee0bcffc4d92">

**Describe the solution you'd like**
We would like the dropdown content to always fill the dropdown width and the '+ New' dropdown to fill the column width

**Comment by charlesBochet** [comment]
Yes, but it's not only the hover, it's the whole MenuItem component that is not large enough. It appears to be an extra padding or margin on the right side

**Comment by lakshay-saini-au8** [comment]
@charlesBochet 
Hey, I would like to work on this task.

Regarding the requirement, I am clear with this requirement
"On the Opportunities page, the '+ New' Dropdown does not fill the whole column width"

Can you give some more context on the other two :

This is the latest screenshot I have taken from
 here: https://app.twenty.com/opportunities
 
 I am using MacBook Pro [Apple M1] and Google Chrome

![Screenshot 2023-09-16 at 5 42 46 PM](https://github.com/twentyhq/twenty/assets/19304527/8c276bb0-910a-4c57-b167-ff1ab4aa282f)

**Comment by charlesBochet** [comment]
Ok, good point! I had a hard time reproducing the issue. It's actually when you have more than 5 items in the dropdown and the scrollbar gutter is appearing.

To reproduce, add a new company from the Companies page, and it should happen.

I think, we should use: `scrollbar-gutter: stable` css property and play with padding to fix it (maybe remove padding-right + update width: calc(100% - padding)

**Comment by lakshay-saini-au8** [comment]
@charlesBochet can I pick this task

**Comment by FelixMalfait** [comment]
Thanks @lakshay-saini-au8!

**Comment by charlesBochet** [comment]
sure!

**Comment by abhithory** [comment]
@charlesBochet , I want to work on this, can you please assign me this?

**Comment by abhithory** [comment]
Hi @charlesBochet , I have fixed this and made PR. Please check this
