### ISSUE TITLE
On Opportunities page, when I click on an item from the top-right '+' dropdown, the dropdown does not close itself

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1585]
**Current behavior**
On Opportunities page, when I click on an item from the top-right '+' dropdown, the dropdown does not close itself

<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/ea50912d-ca97-4231-b68c-9d85d6cf42c0">

**Describe the solution you'd like**
We would like it to close whenever a user clicks on an item. No need to wait for the backend call to resolve, we should immediately close it using `closeDropdownButton`.

**Additional context**

**Comment by zvolcsey** [comment]
Hi! @charlesBochet I added the `closeDropdownButton` function to the `handleCompanySelected` function. I will open a PR soon.
![close_dropdown](https://github.com/twentyhq/twenty/assets/41576384/dcbadf91-679c-4682-a2c4-5f7ad72e8425)
