### ISSUE TITLE
Opportunities options menu items should be reordered

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1594]
### Current order
1. Stages
2. Fields

### Desired order
1. Fields
2. Stages

The goal is to match the order of Companies & People menus where "Fields" is the first choice (before import)

**Comment by arey-pranay** [comment]
I'm having some runtime errors form Apollo, so I can't seem to run it locally, but ig this is the change:

front/src/modules/ui/board/components/BoardOptionsDropdownContent.tsx
Line 184
<StyledDropdownMenuItemsContainer>
           <MenuItemNavigate
              onClick={() => handleMenuNavigate('fields')}
              LeftIcon={IconTag}
              text="Fields"
            />
            <MenuItemNavigate
              onClick={() => handleMenuNavigate('stages')}
              LeftIcon={IconLayoutKanban}
              text="Stages"
            />
  </StyledDropdownMenuItemsContainer>
