### ISSUE TITLE
Implement an example test for hotkeys on dropdown

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1597]
**Current behavior**
Currently we have no extensive testing on the potential hotkey scope conflicts that may arise on components like dropdowns or right drawers

**Expected behavior**
We need to create at least one first test as an example.

In storybook a good place to have those tests would be on complete pages (ex: `Company.stories.tsx`) so everything is loaded and we can create fake conflicts for testing.

**Additional context**
Be careful with storybook as it can be tedious to work with keyboard shortcuts, you may find examples like `userEvent.type(searchInput, '{arrowdown}');` in the code by searching.

**Comment by lucasfirmo62** [comment]
Hello @lucasbordeau, i can do this? Put me as Assignees.

**Comment by lucasbordeau** [comment]
Hi @lucasfirmo62, sorry for the delay, you're welcome to work on this issue, please don't hesitate to join our Discord to discuss the details.

**Comment by lucasbordeau** [comment]
https://discord.gg/bNgBwJny

**Comment by Bonapara** [comment]
Is it still relevant @lucasbordeau? If yes, is it something we should do in the next 6 months? Otherwise I will switch it as a discussion ;)
