### ISSUE TITLE
Bug : View select button hover

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1601]
**Current behavior**
The button group on a menu item in the view select at the top left corner of the table is overflowing, thus making the menu container resizing lightly.

<img width="187" alt="Capture d’écran 2023-09-15 à 13 50 16" src="https://github.com/twentyhq/twenty/assets/26528466/8f66c1c9-44ff-4680-8ace-fc4fe3a2bd42">

**Describe the solution you'd like**
We should handle the case were text is overflowing, maybe the button group need to be place on top of the text. You can see and example of this in EditableCell with `showEditButton`

**Comment by thaisguigon** [comment]
This should be covered by #1610.
