### ISSUE TITLE
Design fixes for the view switcher

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1610]
### Current behavior
- The icon type used for the edition and deletion of a view are not the good one
- There is a responsiveness problem when the view name is too long

<img width="551" alt="Screenshot 2023-09-15 at 10 21 58" src="https://github.com/twentyhq/twenty/assets/19412894/29d786e3-e399-4ebf-8691-7bf134d2c876">

### Desired behavior
- Use the Button/IconButtonGroup components and see the hover behavior on prototype https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=2994-39807&mode=design&t=n8djauqnYlT60HCz-4
- Make the View switcher menu items 200px width **without the button to open the menu beeing 200px**. On the following video, see how the menu items container is wider than the button to opens the menu.
- Make sure nothing is "flashing" on hover, and add quick transitions ( 100ms). 
- Make the Button/IconButtonGroup position "fixed" 

https://github.com/twentyhq/twenty/assets/19412894/e42e6d19-8b44-46de-aae3-8756187e8a5d

**Comment by thaisguigon** [comment]
Hi @Bonapara !

> and add quick transitions ( 100ms).

I was wondering what elements should have a transition, and on which property (background color, opacity when the item appears...) ?

**Comment by Bonapara** [comment]
The transition should be 75ms (made a mistake, 100ms is not in the theme)
It should be on opacity and background.
