### ISSUE TITLE
Fix NavCollapseButton Styling

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1611]
Linked to ticket [1344](https://github.com/twentyhq/twenty/issues/1344)

# Current design

NavbarCollapseButton's icon:
- stroke is md
- color is secondary

https://user-images.githubusercontent.com/102394218/268355304-d14f37b2-f0c5-47d3-a673-2754f7865684.mp4

# Expected design

NavbarCollapseButton's icon should be:
- stroke: sm
- color: tertiary

https://user-images.githubusercontent.com/102394218/268355635-f0df9473-b032-405a-a7fa-e5559242fa4b.mp4

**Comment by parag477** [comment]
Hey, I want to work on this issue. Can you please assign me this issue??

**Comment by Bonapara** [comment]
Hey Parag, yes, thanks for your help!

**Comment by charlesBochet** [comment]
@parag477 I've just refactored NavCollapseButton structure, make sure to pull the latest version of main before starting, thank you!

**Comment by parag477** [comment]
Okay I'll keep it in mind

**Comment by Bonapara** [comment]
@parag477, I have unassigned you to allow someone else to address the issue.

**Comment by Bonapara** [comment]
Hi @alfredlouisw8, yes thanks!

**Comment by charlesBochet** [comment]
That's true, it has been fixed! Sorry about the confusion :)
