### ISSUE TITLE
Scrollbar blank square in DarkMode

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1627]
## Bug

In DarkMode, when scrollbar are displayed (for example on Companies page, with enough companies in the list), we see a blank square in the bottom left corner
<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/0993134f-f1ef-4546-9f78-70c1ce4833bb">

**Expected behavior**
It should be transparent

**Comment by Aspireve** [comment]
Hey Hi!! @charlesBochet 
Could I work on this issue?
I just had a doubt, would I need to have some form of Access Key to use this application while in development (hosted on my device)?

**Comment by charlesBochet** [comment]
sure @Aspireve! Thank you :)
No, no need of any access key, you can just follow the doc here: https://docs.twenty.com/developer/local-setup

**Comment by Aspireve** [comment]
Ohh Sure Ill solve it as soon as possible

**Comment by charlesBochet** [comment]
@Aspireve any update on this one?

**Comment by abhithory** [comment]
@charlesBochet , are you talking about the bottom right white square??

**Comment by abhithory** [comment]
Hi @charlesBochet , I have fixed this. will push in some time. can you please assign me?

**Comment by abhithory** [comment]
@charlesBochet I made PR: #1948 for this. Please check
