### ISSUE TITLE
Fix theme color for components

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1637]
**Current behavior**
Due to the no-hardcoded-color eslint rule, some components have hardcoded colors and have disabled this rule
 
**Expected behavior**
We need to use theme colors for those components, and we need to take care of light/dark theme colors.

Components : 
- AnimatedCheckmark
- Toggle
- DragSelect

**Comment by charlesBochet** [comment]
@lucasbordeau I've taken care of it in your PR: https://github.com/twentyhq/twenty/pull/1640

Closing this ticket
