### ISSUE TITLE
Fix matching-state-variable rule

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1639]
**Current behavior**
With the recent refactors some of our eslint rules aren't working properly. We already refactored some but we need to do the same for others. 

**Expected behavior**
In this ticket we have to refactor our rule `matching-state-variable`, please take care of doing it properly and add tests (ok/not ok) for : 
- useRecoilFamilyState
- useRecoilSelector
- useRecoilScopedState
- useRecoilScopedFamilyState
- useRecoilScopedSelector

**Comment by charlesBochet** [comment]
@lucasbordeau I've taken care of it in your PR: https://github.com/twentyhq/twenty/pull/1640

Closing this ticket
