### ISSUE TITLE
Implement possibilty to move Kaban colomn

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1641]
### Scope
- Opportunities (kanban)

At present, users do not have the ability to change the position of columns on the Kanban. 

# Desired Design:

We want to add a column reordering functionality. This can be achieved by implementing the following changes:
When users click on the name column within the BoardColumnEditTitleMenu, an options to "Move Left" and "Move Right" is present.
Selecting "Move Left" the colomn should shift to the left, and selecting "Move Right" should shift it to the right.

https://github.com/twentyhq/twenty/assets/102394218/24405477-cb6e-4c0e-a911-4c1f95367dca

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11015-55936&mode=design&t=9eeUr4AoZTMi9TEI-4

**Comment by FelixMalfait** [comment]
@AdityaPimpalkar has done most of the work for the companies/people page which have a similar behavior so whoever implements this should re-use most of what he has done

**Comment by AdityaPimpalkar** [comment]
@FelixMalfait I can implement this once the PR is merged. Thanks🙂
