### ISSUE TITLE
Delete Opportunities column + Improving design of BoardColumnEditTitleMenu

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1642]
### Scope:
- Opportunities (kanban)

# Current design:

- The BoardColumnMenu currently appears over the name of the column.
- The delete option is present in the BoardColumnMenu, but it should be removed.
- The title of the BoardColumnEditTitleMenu lacks a distinctive design.
- The width of the overlay for both menus should be set to 200px, centered in the column, and positioned 8px below the div containing the BoardColumn header.

https://user-images.githubusercontent.com/102394218/268788465-e79658c7-712a-483c-b78c-2d88128714ed.mp4

# Desired design:

- Adjust the positioning of both menus so that they have a width of 200px, are centered in the column, and are positioned 8px below the div containing the BoardColumn header.
- Remove the delete option from the menu.
- Change the "Rename" option to "Edit".

![Image](https://user-images.githubusercontent.com/102394218/268789483-8883d9ad-2041-4dd6-ab0c-16271a9558a1.png)

BoardColumnEditTitleMenu's header: 
- add a border (border medium), 
- Set background transparent lighter
- Add autofocus.

![Image](https://user-images.githubusercontent.com/102394218/268788959-f9d2b7bf-904e-4d56-b9b1-3c280ef4121a.png)

- Add the delete option to the BoardColumnEditTitleMenu with a "danger" style at the bottom.

https://user-images.githubusercontent.com/102394218/268788829-4d34c86f-c5db-4bef-9afc-7b6f875b3e4b.mp4

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11052-60568&mode=design&t=9eeUr4AoZTMi9TEI-4

**Comment by FelixMalfait** [comment]
Not sure if backend work involved. Probably not as "deleteOnePipelineStage" is already documented on https://docs.twenty.com/graphql and I'm guessing that's what we would use here (?). Labelling with "scope: front"
