### ISSUE TITLE
Fix design "tabler-icon-arrow" of Sort in 'People', 'Companies' and 'Opportunities'

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1644]
### Scope:
- Companies
- People
- Opportunities

# Design Issue:

The icons used for sorting, specifically 'arrow-up' and 'arrow-down,' do not match the desired design. They are currently represented as 'tabler-icon-arrow-narrow-up' and 'tabler-icon-arrow-narrow-down.'

![Image](https://user-images.githubusercontent.com/102394218/268803439-69cdfbbd-abf7-4085-9263-9b38cf256a29.png)

# Desired design:

- Update the icon for ascending sorting to 'tabler-icon-arrow-up.'
- Update the icon for descending sorting to 'tabler-icon-arrow-down.'

![Image](https://user-images.githubusercontent.com/102394218/268803549-27ff5d6e-9399-452d-a565-e71669afffc0.png)

**Comment by Rishy-2021** [comment]
Hey, I want to work on this issue. Can you please assign me this issue.
