### ISSUE TITLE
Remove the {...props} pattern and props coupling, and create an eslint rule for that.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1647]
**Current behavior**
We have a lot of places in the code where we drill down props from above in a non-readable manner with `{...props}`. Whether from parent components or from HTML elements like div, li, etc.

We also have some props typed by slices (with Pick) of other component props.

This is not ideal for different reasons : 
- Makes the code more difficult to read, we should stick to setting every props one-by-one, if there are too many props, or too many drill downs of the same props, this indicates a code smell, and we can create a ticket to refactor this part with recoil / generic hooks / a new module / etc.
- Adds no real safety since TypeScript is based on duck typing and will catch any type mismatch anyway
- Makes component coupled between each other by their props, which we want to avoid and instead use Recoil or generic hooks to create the necessary dependencies for each component to the necessary modules.
- It's easier to manage a codebase of many components when they have a clear, closed API than having something like Material-UI which is very extensible and flexible and that corresponds to the specific needs of an UI library. 

We have to take the appropriate patterns for scaling a codebase that is product-oriented.

**Expected behavior**
We want to progressively refactor this pattern and use a clear eslint rule with a proper documentation about it so that it's easier to think about another way to do it than to use this pattern.

- We should first create a new eslint rule that prevents the usage of this pattern, with the proper tests
- Then flag every component that uses it in an master issue, and add an eslint-ignore comment for every error
- Create smaller tickets adapted to the level of needed refactor for each component / group of components.

**Comment by lucasbordeau** [comment]
We could use a pattern that seems to be a good trade-off you used in one of your PRs : 

```
{...{
  firstValue,
  secondValue,
  firstValuePlaceholder,
  secondValuePlaceholder,
  firstValueInputRef,
  secondValueInputRef,
}}
```

**Comment by thaisguigon** [comment]
There is an existing `eslint-plugin-react` rule for this: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-props-no-spreading.md

We may want to use this rule instead?
