### ISSUE TITLE
Add Custom Field from table title bar "+" menu

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1652]
# Current behavior

Clicking on the "+" at the right end of a table enable to "show" an hidden standard field.
 
<img width="332" alt="Screenshot 2023-09-19 at 11 06 51" src="https://github.com/twentyhq/twenty/assets/19412894/a8820fe3-84b4-4b62-8977-bd43340035a0">

# Desired behavior

1. The "+" menu at the right end of the title bar should allow to:
- Display an hidden standard or custom field
- Create a new custom field

<img width="1279" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/71d9d4aa-5de9-48e4-b337-5eb349946b74">

2. Clicking on "Add custom field" swap the overlay with another one that allows to select the custom field type:

<img width="1285" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/f20b6495-2100-4219-aaa2-dfa27d9b593e">

3. The new column is created and a "column menu" opens to name the column and choose an icon for the custom field.

![image](https://github.com/twentyhq/twenty/assets/19412894/71b30026-a236-4347-8595-549fb04d84f4)

# Figma
**Prototype**: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=1406-44830&mode=design&t=iF7gvO767aMu93SU-4
**Plus menu** https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11153-52210&mode=design&t=iF7gvO767aMu93SU-4
**Field type menu**: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11153-52211&mode=design&t=iF7gvO767aMu93SU-4
**Custom field** column menu: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11153-52212&mode=design&t=iF7gvO767aMu93SU-4

# Custom fields types:
- Text 
- Number
- True/False (set false as default) (don't call it boolean)
- Link
- Team member (Ability to select one team member)
- Date

```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/1660
- [ ] https://github.com/twentyhq/twenty/issues/1661
- [ ] https://github.com/twentyhq/twenty/issues/1657
```

**Comment by charlesBochet** [comment]
@Bonapara here is the ticket!

**Comment by charlesBochet** [comment]
Do not implement the call to the backend

**Comment by charlesBochet** [comment]
Per discussion with product and design, we are putting this ticket on hold as the new design will be ready soon

**Comment by FelixMalfait** [comment]
Please reopen if needed!
