### ISSUE TITLE
Fix icon Stroke in 'Person' and 'Company' show inside PropertyBox

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1659]
### Scope:
- Company show
- Person Show

In the PropertyBox of 'Person' and 'Company Show' pages, the icons are currently displayed in stroke 'md'. 

- Update the icon stroke to 'sm'

![Image](https://user-images.githubusercontent.com/102394218/269050863-541000e6-3c1d-495d-ac23-527de64e83d8.png)

**Comment by charlesBochet** [comment]
This has been solved, thanks!
