### ISSUE TITLE
New standard field column menu

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1660]
# Desired behavior

Add a disabled icon picker and a disabled input at the top of the menu so it matches the Custom object design. Make sure to add the crossed icon to show it's not editable.
Display the menu **under** the column title (not above)

![image](https://github.com/twentyhq/twenty/assets/19412894/22b59823-2e41-4f4b-aef6-1d6d5c484281)

**Comment by FelixMalfait** [comment]
Closing for now as this might not be the design required. But please reopen if it is!
