### ISSUE TITLE
Add custom field from option menu

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1661]
# Current behavior:

The "field" menu item from the option menu shows both displayed columns, and hidden columns

<img width="237" alt="Screenshot 2023-09-19 at 12 12 43" src="https://github.com/twentyhq/twenty/assets/19412894/476aedf0-81bc-4f06-95de-8427d1ee1339">

# Desired behavior

The "field" menu item from the option menu should only display visible columns (and offer the opportunity to hide them with the hover menu). To display a new column, the user should click on "Add field at the bottom of the menu.

![image](https://github.com/twentyhq/twenty/assets/19412894/73e32921-cf3f-4e4c-a006-d0fcaafcbf7e)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=6377-158599&mode=design&t=iF7gvO767aMu93SU-4

Clicking on this button should swap the menu with the same menu that is used by pressing the "+" button on the table title bar:

![image](https://github.com/twentyhq/twenty/assets/19412894/652dbe7f-5fe1-4fbf-9c87-1aacf2de3ac7)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11153-52210&mode=design&t=iF7gvO767aMu93SU-4

Clicking on "Add custom field" should open swap the menu with the "field type" menu:

![image](https://github.com/twentyhq/twenty/assets/19412894/3f6436a1-efa2-4cb6-b77f-1d6fb562d978)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11153-52211&mode=design&t=iF7gvO767aMu93SU-4

Then, the new column should be created and the column menu be opened:

![image](https://github.com/twentyhq/twenty/assets/19412894/3900801a-5f8c-4442-b6a8-1773567a8725)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11153-52212&mode=design&t=iF7gvO767aMu93SU-4

**Comment by FelixMalfait** [comment]
Closing for now be we can reopen later if needed
