### ISSUE TITLE
Fix design EditableCell 'Hover', 'Focus' and 'Edit Mode'

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1663]
### Scope:
- People page
- Companies page

# Current design:

## 1. Hover and Focus State Box-Shadow:
Currently, the 'box-shadow' in the 'hover' and 'focus' states of cells is positioned inside the cell and does not cover the gray grid lines.

![Image](https://user-images.githubusercontent.com/102394218/269067607-83d76e97-136b-466b-b93d-317131d7e049.png)

## 2. EditableCellEditMode Placement:
When cells are in 'EditMode,' the 'EditableCellEditMode' currently opens partially inside the 'EditableCell.'

![Image](https://user-images.githubusercontent.com/102394218/269067637-6b2f3113-1668-4449-a0ac-a2b0b5fae0cd.png)

# Desired design:

## 1. Hover and Focus State Box-Shadow:

- Adjust the 'box-shadow' in the 'hover' and 'focus' states of cells to cover the gray grid lines of the cell.

![Image](https://user-images.githubusercontent.com/102394218/269067818-6a3b665c-2158-4ecb-9e69-39a4962939dc.png)

## 2. EditableCellEditMode Placement:

- Modify the placement of the 'EditableCellEditMode' so that it opens over the 'EditableCell' rather than inside it. (Should not be able to see the line of the 'EditableCell'.
- The height of the 'EditableCellEditMode' should match that of the 'EditableCell.' (ie. 32px)

![Image](https://user-images.githubusercontent.com/102394218/269067872-9721b14d-4653-4312-8a17-4d9b80c19775.png)

**Comment by FelixMalfait** [comment]
Hey @dev-daizy go ahead you can take this issue if you'd like! Thanks a lot

**Comment by Davidkramer1999** [comment]
Can you please assigned issue to me. I just started working on it. Thank you

**Comment by FelixMalfait** [comment]
Thanks @Davidkramer1999 🙏

**Comment by Davidkramer1999** [comment]
Is there somebody who could help me a little bit a have a hard time figuring out the where EditableCell and EditableCellEditMode are rendered. Quite hard to find out the flow becasue of multiple contexts.

**Comment by FelixMalfait** [comment]
@Davidkramer1999 feel free to join twenty.com/discord support would be better than here where not many people will see you message. Thanks!

**Comment by lucasbordeau** [comment]
Fixed !
