### ISSUE TITLE
Improve Dropdown Draggable list

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1668]
## Scope and Context

In previous PRs: https://github.com/twentyhq/twenty/pull/1667 and https://github.com/twentyhq/twenty/pull/1636, we have introduced a new MenuItem draggable in the dropdown and implemented a drag and drop behavior.

This is working but it would be great to refactor this into separated components so we can re-use them

### MenuItemDraggable

Right now we are using `MenuItem` with `isDraggable` prop to create the DraggableItem
Instead, we want to create a separated component `MenuItemDraggable`, remove `isDraggable` prop from `MenuItem` and `MenuItemLeftComponent`.
We will also need to add a `isDragged` prop to this `MenuItemDraggable` to force the "hover" look while the item is being dragged.

We also want to add storybook tests on `MenuItemDraggable` (like we have on `MenuItemNavigate` for example)

### DraggableList

Having a list that is draggable will be useful, not only in dropdown.
- Create a folder `@/ui/draggable-list `with a `DraggableList` component
- This component should take as prop: `itemsComponents`, `onDragEnd((previousIndex, nextIndex) => {})`
- Use this component in `ViewFieldsVisibilityDropdownSection` (move the logic from ViewFieldsVisibilityDropdownSection to `DraggableList`) by passing a list of `DraggableMenuItems`

Add a storybook test on this list (we don't know how to actually test the draggable behavior, but we can at least make sure the component renders correctly a list of items)

**Comment by charlesBochet** [comment]
@AdityaPimpalkar it's tied to your previous work if ever you want to take it :)

**Comment by AdityaPimpalkar** [comment]
@charlesBochet sure! I can take this up 😄
