### ISSUE TITLE
Bug: Drag Select not working after using dropdown

### ISSUE THREAD

**Issue by brendanlaschke** [twentyhq/twenty#1669]
Steps to reproduce:
1. Open Dropdown
2. Close Dropdown
3. Click and drag to select in table 

Problem created by #1636 

There should be no need to remove the `DragSelect` Component instead the `data-select-disable` attribute may be used on the corresponding html element to disable the drag select start ...

**Comment by charlesBochet** [comment]
Agree, this was added by mistake. 

- In EntityTable, remove the code dealing with: `isDraggingAndSelecting`, `setIsDraggingAndSelecting`, remove `isDraggingAndSelectingState` recoil atom. 
- use data-select-disable on ColumnHead dropdown content to instead
<img width="741" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/4310f1f4-dfc8-4055-97fe-d314aecef8b8">
