### ISSUE TITLE
Move metadata module from tenant module to root module

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1687]
## Scope & Context

While building the new backend supporting per-tenant schema, the metadata module has been placed under server/src/tenant module. It should be placed at the same level as tenant.

## Technical inputs

- move metadata at the same level as tenant
- update the module imports

**Comment by charlesBochet** [comment]
@Weiko this has been done, isn't it?

**Comment by Weiko** [comment]
Yes! Inside https://github.com/twentyhq/twenty/pull/1820

**Comment by charlesBochet** [comment]
Ok, closing the issue!
