### ISSUE TITLE
On Workspace creation, create a tenant schema for this workspace

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1689]
## Scope & Context

We've just merged the work on the new backend enabling per-tenant schema.
We need to start creating schema per-tenant. This ticket is about creating the schema, running the standard migrations (even if incomplete) and updating metadata.
Also create aditonal seeds so the two default seeded workspaces (twenty and twenty dev) also have tenant schemas seeded. (but keep the existing seed in default schema too)

Out of scope: having the standard migrations populating a complete schema. One table with a few field is enough to demonstrate the new system. We can rely on other tickets to create the complete schema

## Current behavior

On workspace creation, nothing is happenning regarding tenant schema
During local seed, only the default schema get's pouplated

### Seed
Let's create/update the seed command (right now it's handled by prisma, we might need to create a typeorm seed and find a way to trigger both, later we are likely to completely remove prisma, even for default schema) to seed twenty and twenty dev custom schema with standard migrations.

### Workspace creation
in workspace.service.ts create, let's also trigger the logic to create workspace, and run standard migrations.

**Comment by charlesBochet** [comment]
@Weiko

**Comment by Weiko** [comment]
Done, this was toggled on in this PR https://github.com/twentyhq/twenty/pull/1725
