### ISSUE TITLE
Fix: Bug running server

### ISSUE THREAD

**Issue by gitstart-twenty** [twentyhq/twenty#1693]
## Bug Description

We've had some issues running the server due to the schema named `metadata` being nonexistent

**Example:** 
![image (1)](https://github.com/twentyhq/twenty/assets/140154534/7d265149-6e7c-4b65-8019-eb5e923855f5)

## Expected behavior

Server should be able to run

**Comment by brendanlaschke** [comment]
```
CREATE SCHEMA IF NOT EXISTS "metadata";
GRANT ALL ON SCHEMA metadata TO twenty;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
```
(maybe depending on your db setup the user `twenty` needs to be replaced)

or drop and recreate your db ...

**Comment by gitstart-twenty** [comment]
Hey @brendanlaschke,
I saw you left a comment but I can't find it, please add it back if possible.

**Comment by brendanlaschke** [comment]
I saw you already opened a pr and my comment was a bit out of place as this only solves your local problem and not the migration. Therefore I removed it ...

> ```
> CREATE SCHEMA IF NOT EXISTS "metadata";
> GRANT ALL ON SCHEMA metadata TO twenty;
> CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
>```
> (copied from Charles in the discord)
> or drop the db and recreate it

But now two new thoughts on this topic:
* Check if the used db user can always do these queries? 
* The pg extensions should also be created?

**Comment by gitstart-twenty** [comment]
Your solution is the better one, so perhaps I can close my PR and the issue. Also, let me check out the discord.

**Comment by charlesBochet** [comment]
Yes, closed your PR and let's close this issue! We have updated the docs so the newcomers will have the metadata schema provisionned!
Thank you @brendanlaschke for the support!
