### ISSUE TITLE
Bug: command menu keyboard inputs not working 

### ISSUE THREAD

**Issue by brendanlaschke** [twentyhq/twenty#1703]
## Bug Description

The command menus keyboard shortcuts are not working at all.

```
1. Open command menu
2. press arrow key down
3. press enter
-> nothing happens 
Video not applicable as nothing changes :)
```

## Expected behavior

Keyboard inputs should work!

## Technical inputs

```
- the handler of the library cmdk seems to not register any keyboard inputs 
- Maybe a stopPropagation?
```

**Comment by charlesBochet** [comment]
I thought this was implemented but I cannot find any mention in the code!
**Naive implementation:**
We will need to implement a useCommandMenuSelect hook that will take a list of commandMenuOptionIds as a parameter and save the currentSelectedOptionId in a state.

Then in CommanMenu, we can show a hover on the option where currentSelectedOptionId == {option_id}
And in useCommandMenuSelect we can register arrow up/down to select the next items. 

**Thinking more about it:**
It's actually very similar to `useEntitySelectScroll`, we should create a utility hook that should handle this for both. useListPreselect() maybe that would take (selectableOptionsIds, preselectedOptionId, and a listContainerRef (to scroll on it's n-th children. I'm not a fan of passing a ref to this abstract component)

@lucasbordeau

**Comment by brendanlaschke** [comment]
@charlesBochet 
This already worked some time ago - I remember this from 20a1946 ...
This was provided by the `cmdk` library (https://github.com/pacocoursey/cmdk/blob/main/cmdk/src/index.tsx#L532)

Maybe we can get this to work again instead of implementing this again?

**Comment by charlesBochet** [comment]
mmmh yes, you are right, I forgot that we were using an external library in CommandMenuStyles!

**Comment by charlesBochet** [comment]
We should indead try to leverage the library
