### ISSUE TITLE
Add a multi-select on relation filters

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1719]
## Scope & Context

In every filter dropdown we have in the app.

## Current behavior

We can only select one relation in a filter : 

<img width="1262" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/17ddc9d5-6e8c-45dc-aa6c-66798e58bc90">

## Expected behavior

We would like to be able to select multiple filters, for example I'd like to create a view "FAANG" in my people table with : Google, Microsoft, Facebook, etc.

## Technical inputs

We can use the same picker we have in the right drawer for relations : 

<img width="336" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/6e02ad25-902b-49c9-bce4-dd50b55ae69f">

We need to modify a little bit our filters structure : 

We can rename `value` to `orValues` or something like that so we know it will always be applied as an OR clause. (AND in the same filter seems less useful and could be another feature if needed)

```tsx
export type Filter = {
  key: string;
  type: FilterType;
  orValues: string[]; // Use an array of string by default to create an OR clause ?
  displayValue: string;
  displayAvatarUrl?: string;
  operand: FilterOperand;
};
```

**Comment by FelixMalfait** [comment]
@lucasbordeau I think this should be part of a broader scope of enabling complex queries long-term, doing something like this https://react-querybuilder.js.org/

**Comment by lucasbordeau** [comment]
We could implement this as a quick win as it is front-end only and pretty much easy to do for a pretty limiting feature we have right now.

If feel like OR multi select on entities, and adding multiple time a filter on the same field is the 80% of what's missing right now.

**Comment by lucasbordeau** [comment]
From a user perspective, I feel like I can add multiple time any filter, since I have the list always visible, I feel like the empty input allows me to add another one, but when I do it overwrites the existing filter, which could be something unexpected in fact.

**Comment by lucasbordeau** [comment]
We could also add the other standard fields we have and/or maybe remove hard coded filter and sort lists and user view fields with seeds ?

**Comment by FelixMalfait** [comment]
OK you've convinced me. Seems like a pretty straightforward task then? Should we remove both "blocked" tags?
cc @Bonapara 

> We could also add the other standard fields we have and/or maybe remove hard coded filter and sort lists and user view fields with seeds ?
Sorry I didn't understand this

**Comment by Bonapara** [comment]
Agreed! Well observed, @lucasbordeau

**Comment by AyushAgrawal-A2** [comment]
Hi @lucasbordeau , I was trying to solve this issue

Please clarify if operand select is required for multi select feature, for selecting 'Is FAANG' or 'IsNot FAANG'.

Operand select is not currently implemented in MultipleEntitySelect component.

**Comment by FelixMalfait** [comment]
@AyushAgrawal-A2 thanks! Operand would apply to the whole group.
So you could do IsNot (A & B) but couldn't do Is A & IsNot B.

@lucasbordeau told me this issue was a bit harder than it seemed to me initially because it requires refactoring the generic hook that does the queries

**Comment by Davidkramer1999** [comment]
So @AyushAgrawal-A2  you are working on this feature? And you will complete ti as well?

**Comment by AyushAgrawal-A2** [comment]
@Davidkramer1999 yup, trying to :sweat_smile:
open to collaboration or skip this one if you have already made some progress

**Comment by Davidkramer1999** [comment]
No I was talking to @lucasbordeau  to take on this one but no problem you can give it a try. Yes I would love to collaborate. Send me a message on discord and we can start working on it together (kramer3271)

**Comment by FelixMalfait** [comment]
Completed!
<img width="298" alt="Screenshot 2024-01-17 at 10 27 49" src="https://github.com/twentyhq/twenty/assets/6399865/c4ff8f3d-cf70-453f-9c53-c87f8f33fde3">
