### ISSUE TITLE
I can drag and drop my favorites to reorder them

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1721]
## Scope & Context

On the left bar, in the favorite section : 

<img width="225" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/aa79127e-498f-4168-bebc-ac7024102a6a">

## Current behavior

Favorites are displayed in their order of creation.

## Expected behavior

I can drag & drop any favorite to re-order them so I'm more in control of the priority of my favorites and can change it when the situation changes (I have some big opportunity on a company and want to make it the first favorite for some weeks)

**Comment by FelixMalfait** [comment]
Adding backend to the scope as I assume it involves adding a position column

**Comment by abhithory** [comment]
Hello @lucasbordeau, I am really interested in working on this issue. Can you please assign this to me?

I am confident that i can do this very soon

**Comment by FelixMalfait** [comment]
Thanks @abhithory!

**Comment by Davidkramer1999** [comment]
Started working on it so you can reassign to me

**Comment by abhithory** [comment]
Frontend part is done, just backend is remaning

[Screencast from 02-10-23 07:23:28 AM CDT.webm](https://github.com/twentyhq/twenty/assets/76877003/0dbda05f-b48b-4ff0-b086-d75b47a637d4)

**Comment by abhithory** [comment]
Hi @FelixMalfait ,

I added a pull request for this, please check

**Comment by abhithory** [comment]
Hi @charlesBochet, here is the new PR #2097  ,  Please check this. 

In the old one, there were many bugs due to old code.

**Comment by charlesBochet** [comment]
This has been implemented, closing it :)
