### ISSUE TITLE
Be able to close TableColumnDropdownMenu with Escape hotkey

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1727]
## Scope & Context

The table column header dropdown menu : 

<img width="210" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/e8f11a94-b5c3-4796-8570-d8421896d01b">

## Current behavior

We can close this menu by clicking outside. But not with the Esc key.

## Expected behavior

We want to be able to close this dropdown like any other dropdown in the app with the Escape hotkey.

## Technical inputs

We should take care of passing the right HotkeyScope when opening this dropdown. We usually change the hotkey scope in click handlers. 

If that is needed a new HotkeyScope can be created for this dropdown.

**Comment by abhithory** [comment]
hi @lucasbordeau , i want to work on this. Can you please assign me this task?

**Comment by FelixMalfait** [comment]
This has been completed according to Charles’ comment in the linked PR
