### ISSUE TITLE
Add an eslint rule to enforce no-type-import and add the why in the docs.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1735]
## Scope & Context

We just removed all type imports from the codebase in #1679, now it would be helpful for people to enforce this with an eslint rule and a section in the documentation.

There's already an existing rule : https://typescript-eslint.io/rules/consistent-type-imports/

And you can find the discussion in the associated [ticket](https://github.com/twentyhq/twenty/issues/1679) and [PR](https://github.com/twentyhq/twenty/pull/1716) to have some material for writing in the documentation in https://docs.twenty.com/developer/frontend/style-guide

**Comment by aman44444** [comment]
@lucasbordeau I want to work on this issue can you please assign this to me ?

**Comment by lucasbordeau** [comment]
@aman44444 Sure please, @rtpa25 can help you with this and the review process.
