### ISSUE TITLE
Command Menu design improvements

### ISSUE THREAD

**Issue by brendanlaschke** [twentyhq/twenty#1741]
## Scope & Context

Improve the command menu display for the navigate (and also create?) commands. 

Github for example shows the corresponding icon:

<img width="310" alt="Bildschirmfoto 2023-09-27 um 15 09 54" src="https://github.com/twentyhq/twenty/assets/48770548/5e142560-1277-45eb-96a7-ccb80fc76561">

maybe we also want to exclude the "Go To" and still show them if you search for "Go To Co..."

For the create command I could imagine an icon combination like a small + in the bottom right? 

What are you're thoughts on this? @charlesBochet @Bonapara 

## Current behavior

<img width="218" alt="Bildschirmfoto 2023-09-27 um 15 16 13" src="https://github.com/twentyhq/twenty/assets/48770548/9cf980cd-5a2b-4739-9692-f02374e64156">

**Comment by Bonapara** [comment]
Hi @brendanlaschke, is your screenshot from Figma or the website?

Seems to me that the "Go to" options are never displayed together online.

### Website
**Default view:**
![image](https://github.com/twentyhq/twenty/assets/19412894/fe1a5995-51fc-40ed-8609-097b729a6c67)

**Typing a page name:**
![Screenshot 2023-09-27 at 16 06 50](https://github.com/twentyhq/twenty/assets/19412894/a5d8325a-2a0b-4508-a470-f9cf52866f6c)

**Comment by brendanlaschke** [comment]
From the current website - Its since https://github.com/twentyhq/twenty/pull/1739#pullrequestreview-1646319546 Charles and i discussed it how it should be displayed ...

**Comment by charlesBochet** [comment]
@brendanlaschke I am not clear on this ticket. Could you clarify the proposed changes?

**Comment by brendanlaschke** [comment]
@charlesBochet Initial Thought was to add a green plus to create icons and an icon instead of the arrow for goto, but im not sure about the design vision ... I think for now it is fine to display it this way and close this issue.

**Comment by rkaushik29** [comment]
Hello! Not sure if this is a core team issue - but if the idea is for it to look like Notion, you could add indicators instead of the generic arrow. For example, using icons for pages, people, or custom icons set by users for pages/profile imgs. 

I'm interested in this project and would love to help build.

**Comment by charlesBochet** [comment]
mmh got you. Why not, what do you thing @Bonapara ?

**Comment by Bonapara** [comment]
Agreed. We can use the page icon instead of an arrow.
