### ISSUE TITLE
[Timebox] Chore: Choose between prisma and typeorm and deprecate the other one

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#1751]
## Scope & Context

Our recent implementation of custom objects/fields has been done via typeorm due to a few things supposely not supported by prisma, mostly dynamic schemas and models but also having a connection pool per tenant, scoped by their own schema (this one might have been possible with prisma though?).
 
To have a consistent backend we should be using the same ORM for everything, including the existing api, and deprecate the other one.
Note: Edit the title of this issue once it has been decided

## Technical inputs

Thanks to @magrinj, we are now using pg_graphql to communicate with our db and our custom objects/fields, which means we are using raw queries and do not depend on any kind of model that would have been generated dynamically by typeorm. This brings the question wether we should still use typeorm or not (but typeorm also has other advantages such as datasources?)

**Comment by charlesBochet** [comment]
Datasource concept might still be useful to split the schemas between different databases (performance). But maybe prisma also supports "datasources" or this can be achieved through a Postgres native "sharding"

**Comment by charlesBochet** [comment]
Also double check subscriptions (they are not supported by prisma)

**Comment by magrinj** [comment]
After some digging, it seems that for the point you made @charlesBochet, we should stick with TypeORM.

Prisma does not support subscriptions, and it could cause problems if we need to add them to custom objects. The other solution is to use Nest.JS to add them, but we are outside the Nest.JS context. (It might still be possible to do something in-house with an event listener, but it doesn’t seem to be a great solution.)

Also, for multiple data sources, it's possible to trick Prisma but not in an official way, and it becomes a bit tricky when implemented.

With all of that, I guess if we think in a long-term way, TypeORM is the way to go.

cc @Weiko
