### ISSUE TITLE
Add custom object creation endpoint

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#1754]
## Scope & Context

We already have a way to create custom fields through the createCustomField endpoint. However, this endpoint expects an object-id as parameter coming from the object storing that field and as of today we have no way to create a new custom object

## Expected behavior

I should be able to call a createCustomObject endpoint that will store its metadata info and update accordingly the associated tenant schema with the new table

## Technical inputs

- Add the new mutation, currently this is the responsibility of MetadataResolver but this is not set in stone.
- Add a new method to ObjectMetadataService to create a new ObjectMetadata
- Check if MigrationGeneratorService is working properly for Table creations 
- Use the above to build the new endpoint and call createMigration from TenantMigrationService, it should look like this
```
      {
        name: tableName,
        change: 'create',
      } satisfies TenantMigrationTableChange,
```

**Comment by charlesBochet** [comment]
tableName: custom_object_1
