### ISSUE TITLE
Implement the "Objects" index page in settings

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1756]
# Scope
This will serve as the default page for the "Data Model" section in the settings. From this page, you will be able to:
-  Add a new object
-  View all active objects
-  View disabled objects

# Definitions
**Object**: can refer to either a standard object (a preexisting universal object developed by Twenty, like 'Companies') or a custom object (an entity designed by a specific company to meet its unique business requirements, for instance, 'Travel Packages'). These objects facilitate tracking of diverse data related to customer interactions and operations.

**Disabled object**: An object that is no longer visible in your CRM. It can be a standard object that has not been activated yet or any standard/custom object that you no longer wish to use. "Disabled" does not imply erasure. The object remains in your data model and can be reactivated at any time.

**Active object**: An object within your CRM that can be utilized and modified.

**New object**: This refers to an object that you wish to activate (if it's a standard object), create (if it's a custom object), or plug in (if it's a remote object).

# Behaviors
Listed in sub-issues.

# Figma
![image](https://github.com/twentyhq/twenty/assets/19412894/b6fdee97-2c88-4c55-88d9-086803c810d4)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11440-65418&mode=design&t=pzLEmoCvOdtrPWEL-4
```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/1760
- [ ] https://github.com/twentyhq/twenty/issues/1761
- [ ] https://github.com/twentyhq/twenty/issues/1762
- [ ] https://github.com/twentyhq/twenty/issues/1913
```

**Comment by charlesBochet** [comment]
Closing this issue :)
