### ISSUE TITLE
[Timebox] Standard objects are automatically created after workspace creation (Company only)

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#1757]
## Scope & Context

Standard objects should live under workspace schemas and for that we need to use our new migration service the same way we operate with custom objects. 

## Technical inputs

Each workspace has its own DB schema and its own tenant_migrations table. This is automatically created after the workspace creation. 
After that we now should:
- Store inside src/tenant/standard (probably moved somewhere else later) our standard objects DB structure following our TenantMigrationTableChange format.
- Write inside the new_workspace.tenant_migrations table all the necessary migrations needed to be executed using a method that will be fetching the standard objects.
- Execute pending migrations using MigrationGeneratorService

Note: there is a dependency on #1751

**Comment by charlesBochet** [comment]
@Weiko this one too!
