### ISSUE TITLE
[Timebox] Add Object and Field Graphql types

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#1759]
## Scope & Context
The frontend will need to fetch the workspace metadata first before being able to fetch standard/custom objects and fields. We need new types and resolvers for that. 
This could be easily cached on the client side (for now)

## Expected behavior
I should be able to call graphql to fetch all my metadata, this will allow me to fetch their associated data and also know how to render them based on their types (number, url, date, phone, ...)

## Technical inputs
TODO

**Comment by charlesBochet** [comment]
Done:
- make the implementation for the easiest fields (text, number, ...)
- then implement "composite" fields: doubleText, amount
- then implement relation

This is a timebox, start with the first step, merge, and then move to the next step
