### ISSUE TITLE
Create a new object

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1764]
# Scope

Clicking on "New object" redirects me to a page where I can perform the following actions:
-  Activate a standard object
-  Create a new custom object
-  [Coming soon] Connect a remote object (possibly)

![image](https://github.com/twentyhq/twenty/assets/19412894/310f30d0-a19f-4fb2-9cdb-49701ec1de2e)

# Desired behaviors

### General
- The route to be used is "Settings/objects/new."
- Please add color transitions to enhance the tab switching experience.
- I should be redirected to the object show page after creation.

### New Standard object
- The table should include all disabled standard objects.
- The "Save button" should be deactivated by default. When a row (a standard object) is selected, it should return to its default state.

https://github.com/twentyhq/twenty/assets/19412894/e6d5c343-f571-424d-9b02-84f59128bfe4

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11452-92426&mode=design&t=JTOVoeCGD6DTr2rv-4

### New Custom object

- Same behavior for the Save button, it should return to default state as soon as the page is edited
- Clicking on the icon should open the icon picker
- Put "Investor" and "Investors" as placeholders of the inputs

![image](https://github.com/twentyhq/twenty/assets/19412894/1c6db129-7bb0-4101-9cda-be62b37c98ec)
Please note that the fields on the screen above are not in their placeholder state.

```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/1919
- [ ] https://github.com/twentyhq/twenty/issues/1918
- [ ] https://github.com/twentyhq/twenty/issues/1809
- [ ] https://github.com/twentyhq/twenty/issues/1807
- [ ] https://github.com/twentyhq/twenty/issues/1808
- [ ] https://github.com/twentyhq/twenty/issues/2010
- [ ] https://github.com/twentyhq/twenty/issues/2173
- [ ] https://github.com/twentyhq/twenty/issues/2155
```

**Comment by rakzool** [comment]
Hi @Bonapara  , if no one is working on thios i would like to work on it

**Comment by Bonapara** [comment]
Hi @rakzool, I believe the core team will take care of this. However, @charlesBochet will confirm it.

**Comment by rakzool** [comment]
@charlesBochet  can you provide a confirmation on this

**Comment by charlesBochet** [comment]
@rakzool Yes, we are currently handling the base of this, we will create tickets for the community on Friday regarding this workstream :)

**Comment by Abhi3685** [comment]
Hi, I would love to work on this. I can pick multiple subtasks as defined here if no one is working on it yet. Please let me know.

**Comment by charlesBochet** [comment]
@Abhi3685 We have set up the base and Settings are open for contributions. This ticket is free to take if you are interested! https://github.com/twentyhq/twenty/issues/1807
