### ISSUE TITLE
feat: advanced ordering and filtering on custom objects

### ISSUE THREAD

**Issue by magrinj** [twentyhq/twenty#1768]
## Scope & Context

With our ongoing efforts to incorporate custom objects and custom fields into "twenty", we've already achieved the capability for users within a workspace to fetch custom objects using a dynamically generated GraphQL schema.

## Current behavior

Currently, we have two dynamic resolvers in place: `findMany${OBJECT_NAME}` and `findOne${OBJECT_NAME}`. While they serve the primary function, they fall short when it comes to accepting arguments that cater to all fields.
For context you can read discussion #1142 

## Expected behavior

To further refine our feature, we aspire to:

Dynamically generate arguments rooted in the custom object fields.

1. Facilitate straightforward as well as intricate filtering mechanisms.
2. Introduce ordering capabilities.
3. Incorporate logical gateways such as AND and OR.
4. Align our approach to mirror the API specification of pg_graphql, which can be referenced [here](https://supabase.github.io/pg_graphql/example_schema/).

**Illustrative Example**: Consider the `StringFilter` and `UUIDFilter` as delineated by `pg_graphql` (but they should be generated too by us):

```graphql
input StringFilter {
  eq: String
  gt: String
  gte: String
  in: [String!]
  lt: String
  lte: String
  neq: String
  is: FilterIs
  startsWith: String
  like: String
  ilike: String
  regex: String
  iregex: String
}

input UUIDFilter {
  eq: UUID
  in: [UUID!]
  neq: UUID
  is: FilterIs
}
```

Given a custom table, say "document", the query should be structured as:

```query
query FindManyDocument($filter: FindManyDocumentFilter) {
  findManyDocument(filter: $filter) {
    edges {
      node {
        id
      }
    }
  }
}
```

Consequently, the `FindManyDocumentFilter` should adopt the following format:

```graphql
input FindManyDocumentFilter {
  id: UUIDFilter
  name: StringFilter
  AND: FindManyDocumentFilter
  OR: FindManyDocumentFilter
}
```

## Task-list

This is the main ticket, the following task-list should be used in order to complete the whole ticket.

```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/1900
- [ ] https://github.com/twentyhq/twenty/issues/1901
- [ ] https://github.com/twentyhq/twenty/issues/1902
```

**Comment by charlesBochet** [comment]
Split this ticket in two:
- where
- order
