### ISSUE TITLE
Edit an object field

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1769]
# Desired behaviors

### Active fields

From an object detail page, clicking on a row opens a contextual menu with 2 options:

**For custom objects** : Edit and disable

![Image](https://github.com/twentyhq/twenty/assets/19412894/9a16b9fc-c923-4e8e-b945-24effc7ac00d)

**For standard objects**: View and disable 

![Image](https://github.com/twentyhq/twenty/assets/19412894/e55e933a-f15c-4880-b7c0-939d0446cdcc)

Both the "edit" and "view" options redirect to the same page: `settings/object-name/field-name`. The only difference is that you cannot edit the values of standard fields (view only), so the inputs will be deactivated. (See **edit page** section below)

### Disabled fields

The contextual three dots menu should offer two behaviors:

Activate and erase. Activate should move back the row to the "Active" section. See the definitions in #1766 to understand the behavior of erasing.

![Image](https://github.com/twentyhq/twenty/assets/19412894/5717a591-f444-4b46-aa9c-bd70c3720465)

## Edit page

**Standard field edition:**

Please note that there is no "save button" available as editing is not possible.

![Image](https://github.com/twentyhq/twenty/assets/19412894/46804dce-c45b-4260-b010-bcb95260640d)

**Custom field edition:** 

Please note that editing the "field type" of custom objects for V1 should not be allowed. (disable the field, not like on the following screenshot)

![Image](https://github.com/twentyhq/twenty/assets/19412894/33b759b0-6abf-480d-9c40-733e0cad17c3)

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5639-59008&mode=design
```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/2159
- [ ] https://github.com/twentyhq/twenty/issues/2160
- [ ] https://github.com/twentyhq/twenty/issues/2161
- [ ] https://github.com/twentyhq/twenty/issues/2163
```

**Comment by charlesBochet** [comment]
This has been implemented, closing it :)
