### ISSUE TITLE
[Timebox] Define how we'll store field and object metadata in the front cache.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1795]
## Scope & Context

We need to query and mutate field and object metadata from the new Data Model settings.

For this we need to have a front end graphql client and decide how we'll cache the data and handle optimistic rendering.

## Current behavior

We currently have nothing.

## Expected behavior

As the graphql endpoint for metadata should be stable across all workspaces, we can use graphql-codegen on it to generate types and hooks for querying and mutating, and also easily handle optimistic rendering with our current solutions.

We may use the same Apollo client if there's no conflict with the authentication layer.

Let's store the metadata in the Apollo cache and try to use the new https://www.apollographql.com/docs/react/data/fragments#usefragment to read slices of the Apollo store.

**Comment by gitstart-twenty** [comment]
Hey @charlesBochet,
Looks like @lucasbordeau picked this up at the same time you were assigning it to us.

**Comment by charlesBochet** [comment]
@gitstart-twenty Yes, it was a wrong assignation to gistart, sorry about that!

**Comment by charlesBochet** [comment]
This has been implemented, closing it :)

**Comment by charlesBochet** [comment]
This has been implemented, closing it :)
