### ISSUE TITLE
Objects Settings - Reorder objects with drag and drop

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#1803]
## Context

See #1762

For this issue, implement reordering table rows in the Table component with drag and drop, and activate it for the Objects table in the Objects Settings page. Add the "Existing objects" section description about reordering in the page.

## Behavior

**GIVEN** I am on an Objects Settings page
**THEN** I see an "Existing objects" section with a description about reordering object table rows
**AND** the object table rows display a drag handle

**GIVEN** I am on an Objects Settings page
**WHEN** I drag and drop object table rows
**THEN** the rows are reordered

**Comment by Bonapara** [comment]
Closing for now. We will probably handle this in a "layout" settings section/page
