### ISSUE TITLE
[Timebox] Separate ViewField logic from FieldMetadata logic

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1805]
## Scope & Context

We have a FieldDefinition type that is used as ViewField logic and FieldMetadata logic at the same time, the distinction is not clear in the codebase.

We want to separate FieldDefinition / FieldMetadata from ViewField / ColumnDefinition into clearly separated types and modules.

## Expected behavior

The result should give us the possibility to remove ColumnDefinition hardcoded arrays, because they will be generated at runtime by the table module that would query field metadata and view field to link those into each column.

**Comment by charlesBochet** [comment]
This has been solved, closing this issue
