### ISSUE TITLE
Implement "Table" component with TableSubSection with stories

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#1806]
## Context

See #1762 

## Figma

![image](https://github.com/twentyhq/twenty/assets/3098428/f389e2f3-8083-4b8a-bdaa-53ab00de37d6)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11519-270312&mode=design&t=JTOVoeCGD6DTr2rv-4

## Behavior

**GIVEN** the table section header is collapsed
**WHEN** I click on the table section header
**THEN** the section is expanded

**GIVEN** the table section header is expanded
**WHEN** I click on the table section header
**THEN** the section is collapsed

**Comment by charlesBochet** [comment]
+ renaming Table into DataTable
