### ISSUE TITLE
New Object - Add Standard "Available" section

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#1807]
Warning: this ticket is part of a series of tickets aiming to create the "Object Creation flow". This is ticket number 4.

## Context

See #1764 

For this issue:
- Create the New Object page "Available" section, with a title and a description. This section is displayed when the "Standard" selectable box is selected.
- Add a table with hardcoded objects for now (use the `Table` component).
- Implement the "checked" state for a table row (pass a `isChecked` prop to change the row's color as seen on Figma). 

## Figma

<img width="766" alt="image" src="https://github.com/twentyhq/twenty/assets/3098428/9c456f73-7b32-4270-acf2-2ccc24653cf8">

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11519%3A270312&mode=design&t=jTM1v8tUAu0OH33q-1

<img width="591" alt="image" src="https://github.com/twentyhq/twenty/assets/3098428/546aac8d-f864-4b5f-94b1-a3e3aa54bf6b">

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11452%3A92426&mode=design&t=jTM1v8tUAu0OH33q-1

### Scenario: Selecting the Standard object type

**GIVEN** I am on the New Object page
**WHEN** I select the "Standard" selectable box
**THEN** I see an "Available" section with a title and a description
**AND** I see a table with available Standard objects

### Scenario: Selecting an available Standard object

**GIVEN** I am on the New Object page
**AND** the "Standard" selectable box is selected
**WHEN** I click on a row's checkbox in the "Available" table
**THEN** the row's object is selected

**Comment by ujwalkumar1995** [comment]
Hey @thaisguigon 
I would like to work on this issue.
Could you please assign?

**Comment by bosiraphael** [comment]
Hello @ujwalkumar1995 I assigned you to the issue, thank you !

**Comment by thaisguigon** [comment]
Closed by #2111
