### ISSUE TITLE
New Object - Add "Cancel" and "Save" buttons

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#1809]
Warning: this ticket is part of a series of tickets aiming to create the "Object Creation flow". This is ticket number 2

## Context

See #1764

For this issue, in the New Object page, add a "Cancel" button that navigates back to the "Objects Settings" page, and a disabled "Save" button.

## Figma

![Image](https://github.com/twentyhq/twenty/assets/3098428/b26b2a16-39aa-4c4a-89ea-ea47ded6bf8f)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11471%3A94401&mode=design&t=jTM1v8tUAu0OH33q-1

## Behavior

**GIVEN** I am on the New Object page
**THEN** I see a "Cancel" button
**AND** I see a disabled "Save" button

**GIVEN** I am on the New Object page
**AND** I click on the "Cancel" button
**THEN** I navigate to the Objects Settings page

**Comment by BhumikP** [comment]
Hi @thaisguigon  I can work on these tasks. assign it to me

**Comment by thaisguigon** [comment]
Hi @BhumikP, this issue is blocked for now (depends on another issue).
Here is an available good first issue: https://github.com/twentyhq/twenty/issues/1816
You can also find other good first issues here: https://github.com/twentyhq/twenty/contribute

**Comment by bosiraphael** [comment]
@BhumikP I assigned this issue to myself as we need it to be done because other issues depend on it
