### ISSUE TITLE
Object Detail - Add "About" section

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#1816]
Warning: this ticket is part of a series of tickets aiming to create the "Object Edition flow". This is ticket number 1.

## Context

See #1765

For this issue:
- Create the Object Detail "About" section with a title and description.
- Add the object's summary block.
- Add a dropdown menu with an "Edit" menu item that navigates to the Object Edit page on click (see #1903).

## Figma

<img width="641" alt="image" src="https://github.com/twentyhq/twenty/assets/3098428/ce575cd1-ad57-407e-a975-0b03b5c5d8a4" />

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11336%3A63490&mode=design&t=lrj7aulu2ylwpN5F-1

### Scenario: Viewing the object's summary

**GIVEN** I am on an Object Detail page
**THEN** I see an "About" section with a title and a description
**AND** I see the object's summary

### Scenario: Opening the object's summary dropdown menu

**GIVEN** I am on an Object Detail page
**WHEN** I click on the object's summary vertical dots icon
**THEN** a dropdown menu with an "Edit" menu item opens

### Scenario: Clicking on the Edit menu item in the object's summary dropdown menu

**GIVEN** I am on an Object Detail page
**WHEN** I open the object's summary dropdown menu
**AND** I click on the "Edit" menu item
**THEN** I navigate to the Object Edit page

**Comment by thaisguigon** [comment]
Sure, thank you!

**Comment by apurvagurme** [comment]
Hi @thaisguigon, can I also start working on this issue?

**Comment by apurvagurme** [comment]
Hi @thaisguigon, I have raised a PR https://github.com/twentyhq/twenty/pull/2028, please look into it.

**Comment by bosiraphael** [comment]
Closed by https://github.com/twentyhq/twenty/pull/2028
