### ISSUE TITLE
Show the record count instead of the view count

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1821]
## Current behavior

The counter near the view on the "People" and "Companies" table views switcher displays the number of views instead of the number of records on a view.

![image](https://github.com/twentyhq/twenty/assets/19412894/c9cd3de1-c70c-4134-8548-cabb0d1982a7)

## Expected behavior
The counter should display the number of records dispayed on the view. For instance, on the above image, it should display **All companies · 6**

**Comment by mittalsam98** [comment]
Hey, I would like to pick this issue. Can you please assign this to me?

**Comment by alfredlouisw8** [comment]
oops sorry I didnt see your comment @mittalsam98 

I can remove my PR if you'd like to work on this issue

**Comment by tomalexing** [comment]
@alfredlouisw8  actually your pr leave the bug on opportunities page

**Comment by lucasbordeau** [comment]
See example in `selectedCardIdsSelector`.

For reference : https://recoiljs.org/docs/api-reference/core/selector/

**Comment by tomalexing** [comment]
The boardColumnsState is a state implememted for CompanyBoard component. 
And in the another pull request, tableRowIdsState is a state implememted for CompanyTable component. 


But <ViewsDropdownButton/> as part of <ViewBar/>(interested us component) use its own ViewBarRecoilScopeContext to be SOLID and be able to be putted in different places.
```
 <EntityTableEffect -- here is populated state (push to state)
       skipped
      />
 <ViewBarContext.Provider
        value={{
         skipped
          ViewBarRecoilScopeContext: TableRecoilScopeContext,
        }}
      >
               <EntityTable skipped/> 
</ViewBarContext.Provider>
```

```
 <HooksCompanyBoardEffect /> -- here is populated state (push to state)
<ViewBarContext.Provider
          value={{
          skipped
            ViewBarRecoilScopeContext: CompanyBoardRecoilScopeContext,
          }}
        >
          <EntityBoard skipped />
        </ViewBarContext.Provider>
```
So how to derive when its different states(boardColumnsState, tableRowIdsState ) and implementation. Dirived is when we pull from one state. to make another virtual state.  But how to make virtual state( aka materialized ) pushed from different implementation. Idk. It should be derived state(selector) dependent on BoardContext.Provider or TableContext.Provider(that are covering those components). 
If you, @lucasbordeau, can refer me to some example it'd be preferable.

**Comment by tomalexing** [comment]
And in my solution with atom, its will be easy to implement count from server when people or companies will not fit to one page.

**Comment by alfredlouisw8** [comment]
One way I can think of is creating a selector that will return the length of either tableRowIdsState or cardIds and use that selector without making a new atom. But I don't know what can be used to determine that.

What do you guys think? @lucasbordeau @tomalexing

**Comment by lucasbordeau** [comment]
You're right @tomalexing, we should keep the two scopes separated.

This is a complex problem.

We should keep your solution @tomalexing but store this in an unscoped atom `entityCountInCurrentViewState` for the moment that stores a number value directly. (not a string)

We'll see how to better integrate this when we'll refactor the contexts which are a bit messy right now.

**Comment by tomalexing** [comment]
@alfredlouisw8 @lucasbordeau  
I have figured out only one way to do it with selectors:

First create 2 selectors:
```

export const lenghtRowIdsSelector = selector<number>({
  key: 'lenghtRowIdsSelector',
  get: ({ get }) => {
    const rowIds = get(tableRowIdsState);

    return rowIds.length;
  },
});
```

```
export const lenghtCardIdsSelector = selector<number>({
  key: 'lenghtCardIdsSelector',
  get: ({ get }) => {
    const boardColumns = get(boardColumnsState);

    const cardIds = boardColumns.flatMap((boardColumn) =>
      get(boardCardIdsByColumnIdFamilyState(boardColumn.id)),
    ).length;

    return cardIds;
  },
});
```
Then path them through the Context:

```
 <ViewBarContext.Provider
        value={{
         skipped
          lenghtSelector: lenghtRowIdsSelector
          ViewBarRecoilScopeContext: TableRecoilScopeContext,
        }}
      > 

```
and 
```
  <ViewBarContext.Provider
          value={{
             skipped
            ViewBarRecoilScopeContext: CompanyBoardRecoilScopeContext,
            lenghtSelector: lenghtCardIdsSelector,
          }}
        >
```

then in ViewsDropdownButton:


```
  const n = useRecoilValue(
    (lenghtSelector || dummyselector) as RecoilValueReadOnly<number>,
  );
```

This will work with cautions: 
1. I have not seen a selector pathing through the context 
3. What to do with server count

**Comment by tomalexing** [comment]
@lucasbordeau I made unscoped atom entityCountInCurrentViewState with number value.

**Comment by lucasbordeau** [comment]
Let's keep the selectors for other features that are less in between all those scopes 👍

**Comment by lucasbordeau** [comment]
Thank you both
