### ISSUE TITLE
Setting up local Database 

### ISSUE THREAD

**Issue by ADIIS007** [twentyhq/twenty#1823]
setting up the project locally causes error in db config
following the given (guidelines)[https://docs.twenty.com/developer/local-setup]
I had to run $ ALTER USER twenty WITH SUPERUSER;
else the Error thrown is 
![image](https://github.com/twentyhq/twenty/assets/145209827/133d1713-0e51-4f20-8264-67a6bd67b0a8)

**Comment by magrinj** [comment]
@ADIIS007 Thanks for your report, did you follow the local documentation setup [here](https://docs.twenty.com/developer/local-setup).
Particularly did you run the command `make provision-postgres` ?

**Comment by ADIIS007** [comment]
@magrinj yes I did go through all the steps but the permissions were not enough if any one able to replicate it bcz My local work with postgreSQL may too have caused it

**Comment by magrinj** [comment]
@ADIIS007 Ok, under `PostgreSQL Database` did you follow the step under `Linux / Windows WSL` tab ?

**Comment by ADIIS007** [comment]
@magrinj  yes I followed each and every command over there (other than installation as it was already installed and updated)

**Comment by magrinj** [comment]
@ADIIS007 You close the issue, did you find a way to fix it ?
If not, can you try this command into your database:
```postgresql
GRANT ALL ON SCHEMA public TO twenty;
```

**Comment by ADIIS007** [comment]
@magrinj  sorry the close was by mistake 
I used the command that didn't work

**Comment by magrinj** [comment]
Hmm, can you try that one:
```sql
GRANT ALL ON ALL TABLES IN SCHEMA public TO twenty;
```

**Comment by ADIIS007** [comment]
is that same as 
`GRANT ALL PRIVILEGES ON SCHEMA public TO twenty;`

**Comment by magrinj** [comment]
No it doesn't really do the same:

```GRANT ALL ON ALL TABLES IN SCHEMA public TO twenty;``
This command grants all available privileges specifically on all tables (including views) in the "public" schema to the user "twenty". It doesn't grant privileges on the schema itself or other objects within the schema such as sequences, functions, etc.

```GRANT ALL PRIVILEGES ON SCHEMA public TO twenty;```
This command grants all available privileges on the "public" schema itself to the user "twenty". This doesn't automatically grant privileges on individual objects within the schema, like tables, sequences, or functions. However, it does allow the user to create, alter, or drop objects within the schema.

**Comment by charlesBochet** [comment]
Yes, we are updating it, thank you!

**Comment by charlesBochet** [comment]
This has been solved and the documentation has been updated :)
