### ISSUE TITLE
chore: drop Prisma in favour of TypeORM

### ISSUE THREAD

**Issue by magrinj** [twentyhq/twenty#1824]
## Scope & Context

With the recent introduction of custom objects into the Twenty platform, we've integrated TypeORM as our new ORM. We opted for TypeORM over Prisma for handling custom objects for several key reasons:

1. **Multitenancy Support:** TypeORM facilitates the use of distinct data sources for each tenant, ensuring greater flexibility in data management.
2. **Subscription Compatibility:** Unlike Prisma, TypeORM natively supports working with subscriptions, which is crucial for our real-time data update needs.

## Current behavior

- Prisma ORM is currently implemented and operational in certain parts of our project.

## Expected behavior

- To maintain consistency and leverage the benefits offered by TypeORM, we aim to phase out Prisma ORM.
- All areas of the project currently utilizing Prisma ORM should transition to TypeORM.
- [nestjs-query](https://tripss.github.io/nestjs-query/) must be used for the new resolvers.

## Sub-tasks

This is the main ticket, please complete the subtasks in order.

```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/1827
- [ ] https://github.com/twentyhq/twenty/issues/1828
- [ ] https://github.com/twentyhq/twenty/issues/1829
- [ ] https://github.com/twentyhq/twenty/issues/1830
- [ ] https://github.com/twentyhq/twenty/issues/1831
- [ ] https://github.com/twentyhq/twenty/issues/2137
- [ ] https://github.com/twentyhq/twenty/issues/1832
- [ ] https://github.com/twentyhq/twenty/issues/2502
```

**Comment by charlesBochet** [comment]
@gitstart-twenty Let's discuss this one together

**Comment by gitstart-twenty** [comment]
Of course, @charlesBochet. Are you available for a call today, or whenever it's convenient for you?

**Comment by charlesBochet** [comment]
Let's discuss async on Discord in our dedicated channel :) We will hop on a call from there if needed

**Comment by gitstart-twenty** [comment]
> Let's discuss async on Discord in our dedicated channel :) We will hop on a call from there if needed

Alright

**Comment by charlesBochet** [comment]
@gitstart-twenty This has been implemented last week-end. Closing this ticket
