### ISSUE TITLE
Two cells can be focused at the same time in the tables

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#1826]
## Bug Description

When pressing the escape key after selecting a cell and using the arrow keys to move, two cells are focused at once.

https://github.com/twentyhq/twenty/assets/71827178/1e4224b7-7dc8-42b9-b504-dafaf5c0f382

## Expected behavior

Only one cell should be focused, at the final position after pressing the arrow keys.

**Comment by lucasbordeau** [comment]
We haven't made any decision about this behavior when we implemented focus on mouse hover. 

Before we hadn't any focus on mouse hover, just by clicking and moving the focus with the keyboard.

We have to create a ticket with the desired behavior and interaction between those different ways of handling the focus, which we should talk about with @Bonapara

**Comment by charlesBochet** [comment]
@lucasbordeau There is also a bug that I've managed to reproduce:
- click on a picker to open it
- move the pointer within the picker
- select a value with ke

https://github.com/twentyhq/twenty/assets/12035771/d33e60b3-1800-4597-8fa8-7c66dabc2561

yboard
- press enter
- press arrow-right

**Comment by lucasbordeau** [comment]
Ok, we need to refactor this part so we don't have the possibility to end with more than 1 focus state.

@Bonapara What happens if we keep only one focus at a time ? If we move the focus with the keyboard, but after that we move the mouse, should we allow the mouse to take back the focus every time ?

**Comment by lucasbordeau** [comment]
@charlesBochet 

<img width="245" alt="Capture d’écran 2023-10-03 à 12 13 04" src="https://github.com/twentyhq/twenty/assets/26528466/98fd9b20-fb7d-49a7-ac00-cf6a287ce28a">

**Comment by Bonapara** [comment]
What are your thoughts on treating the mouse ":hover" as ":focus" to enable keyboard navigation to start from the "hover/focus" location? The keyboard will take control of the focus when "⇥" or "→, ←, ↑, ↓" keys are pressed. It will lose control as soon as the mouse is moved.

-This feature allows users to hover over a field and press "Enter" to edit it.
- It does not prevent the user from using keyboard navigation.

It appears to me that it could be quite useful, even if it's not common.

@lucasbordeau

**Comment by lucasbordeau** [comment]
Yes, I think that using enter to edit the cell that is currently hovered with the mouse is a nice feature. 

Ok let's say that : 
- Mouse hover moves the soft focus state on the cell it hovers
- Keyboard inputs : enter, tab, up, down, etc. trigger actions from the current soft focused cell

We need to refactor some moving parts a bit : 
- In TableCellContainer, don't use isHovered state anymore and directly use `setSoftFocusOnCurrentTableCell` in `handleContainerMouseEnter` 
- Verify that with the new implementation, we cannot have more than one cell in soft focus mode

**Comment by Davidkramer1999** [comment]
You can assign this to me @lucasbordeau
