### ISSUE TITLE
chore: convert User model to TypeORM entity

### ISSUE THREAD

**Issue by magrinj** [twentyhq/twenty#1829]
## Scope & Context

Scope and context are explained in this main [ticket #1824](https://github.com/twentyhq/twenty/issues/1824)
You must use [nestjs-query](https://tripss.github.io/nestjs-query/), example can be found [here](https://github.com/twentyhq/twenty/tree/main/server/src/metadata/object-metadata).

## Current behavior

Prisma ORM is used for the User model.

## Expected behavior

This step aim to convert the`User` model to a TypeORM entity.
This model is more complex than the previous `RefreshToken` and has some relations.
We'll only implement the `RefreshToken` one for now.

```prisma
model User {
  /// @Validator.IsString()
  /// @Validator.IsOptional()
  id             String    @id @default(uuid())
  /// @Validator.IsString()
  /// @Validator.IsOptional()
  firstName      String?
  /// @Validator.IsString()
  /// @Validator.IsOptional()
  lastName       String?
  /// @Validator.IsEmail()
  /// @Validator.IsOptional()
  email          String    @unique
  /// @Validator.IsBoolean()
  /// @Validator.IsOptional()
  emailVerified  Boolean   @default(false)
  /// @Validator.IsString()
  /// @Validator.IsOptional()
  avatarUrl      String?
  /// @Validator.IsString()
  /// @Validator.IsOptional()
  locale         String
  /// @Validator.IsString()
  /// @Validator.IsOptional()
  phoneNumber    String?
  /// @Validator.IsDate()
  /// @Validator.IsOptional()
  lastSeen       DateTime?
  /// @Validator.IsBoolean()
  /// @Validator.IsOptional()
  disabled       Boolean   @default(false)
  /// @TypeGraphQL.omit(input: true, output: true)
  passwordHash   String?
  /// @Validator.IsJSON()
  /// @Validator.IsOptional()
  metadata       Json?
  /// @Validator.IsBoolean()
  /// @Validator.IsOptional()
  canImpersonate Boolean   @default(false)

  /// @TypeGraphQL.omit(input: true)
  workspaceMember WorkspaceMember?
  companies       Company[]
  /// @TypeGraphQL.omit(input: true, output: true)
  refreshTokens   RefreshToken[]
  comments        Comment[]

  authoredActivities  Activity[]   @relation(name: "authoredActivities")
  assignedActivities  Activity[]   @relation(name: "assignedActivities")
  authoredAttachments Attachment[] @relation(name: "authoredAttachments")
  settings            UserSettings @relation(fields: [settingsId], references: [id])
  settingsId          String       @unique

  /// @TypeGraphQL.omit(input: true, output: true)
  deletedAt DateTime?

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@map("users")
}
```

## Technical inputs

- Create the User entity
- Add the RefreshToken relation
- Use [nestjs-query](https://tripss.github.io/nestjs-query/) to generate the services and resolvers
- Test if everything work properly and if we have somme difference between Prisma and TypeORM results

**Comment by Kanav-Arora** [comment]
Hi @magrinj 
Can I work on this issue?

**Comment by magrinj** [comment]
Hi @Kanav-Arora,

Thanks for the proposal, but this issue is related to a bigger one as described in the comment.
We've starting implementing `nests-query`, so tickets need to be updated.
At the time it's assigned to the TwentyCoreTeam, but I'll keep you in touch if it change :)
