### ISSUE TITLE
chore: convert all standard prisma models into TypeORM entities

### ISSUE THREAD

**Issue by magrinj** [twentyhq/twenty#1830]
## Scope & Context

Scope and context are explained in this main [ticket #1824](https://github.com/twentyhq/twenty/issues/1824)
You must use [nestjs-query](https://tripss.github.io/nestjs-query/), example can be found [here](https://github.com/twentyhq/twenty/tree/main/server/src/metadata/object-metadata).

## Current behavior

Prisma ORM is used for the standards models.

## Expected behavior

Based on the work that has been done on #1828 and #1829
We should now be able to convert all the other models:
`WorkspaceMember`, `UserSettings`, `Workspace`.

## Technical inputs

- Create all the standards entities
- Use [nestjs-query](https://tripss.github.io/nestjs-query/) to generate the services and resolvers
- Test if everything work properly and if we have somme difference between Prisma and TypeORM results

**Comment by charlesBochet** [comment]
This ticket has been implemented
