### ISSUE TITLE
chore: generate initial migration for TypeORM

### ISSUE THREAD

**Issue by magrinj** [twentyhq/twenty#1831]
## Scope & Context

Scope and context are explained in this main [ticket #1824](https://github.com/twentyhq/twenty/issues/1824)

## Current behavior

Prisma ORM generate the migration based on the schema.

## Expected behavior

Now that all entities are created, we need to generate the first migration of TypeORM that is going to init the database with all the tables.
https://orkhan.gitbook.io/typeorm/docs/migrations#generating-migrations

## Technical inputs

- Create the migration

**Comment by charlesBochet** [comment]
This has been implemented
