### ISSUE TITLE
chore: drop prisma

### ISSUE THREAD

**Issue by magrinj** [twentyhq/twenty#1832]
## Scope & Context

Scope and context are explained in this main [ticket #1824](https://github.com/twentyhq/twenty/issues/1824)
All the previous steps need to be done before doing this ticket.

## Current behavior

Prisma ORM and TypeORM actually co-exist in the project.
Prisma is used inside the `core` folder and TypeORM inside `core-v2`.

## Expected behavior

We should remove all the Prisma stuff that has been now replaced by TypeORM and replace the `core` module by `core-v2`.

## Technical inputs

- Rename folder `core` into `core.old` and rename `CoreModule` into `CoreOldModule`
- Rename folder `core-v2` into `core` and rename `CoreV2Module` into CoreModule`
- Check if the front-end still work properly or if some queries need to be updated

**Comment by charlesBochet** [comment]
@gitstart-twenty Can you start working on this one as soon as the migration to the new entities is completed. I will send you the green light

**Comment by charlesBochet** [comment]
@gitstart-twenty I've implemented this one this week-end, closing this ticket
