### ISSUE TITLE
Cannot add some fields to companies table.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1836]
## Bug Description

When on companies table, with a clean DB, we cannot add fields ICP and Twitter.

https://github.com/twentyhq/twenty/assets/26528466/ade5e9b3-bef2-4819-87a0-deff8c4075f6

## Expected behavior

We should be able to add those fields to the visible fields.

**Comment by AyushAgrawal-A2** [comment]
@lucasbordeau
May I take this one?

**Comment by lucasbordeau** [comment]
@AyushAgrawal-A2 Sure

**Comment by LakshayGMZ** [comment]
please assign me the issue

**Comment by lucasbordeau** [comment]
Hi @LakshayGMZ we try to respect the order of request as much as possible, I assigned you on another issue.
