### ISSUE TITLE
Crop long text on People dropdown picker

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1840]
# Current behavior
Long text are overflowing the dropdown picker

![image](https://github.com/twentyhq/twenty/assets/19412894/dac439ca-d469-45e0-a007-ee08d9cad381)

# Desired behavior
Long text should be cropped with **...**

![image](https://github.com/twentyhq/twenty/assets/19412894/315a90d1-282f-4657-bc61-d7558a3968b4)

**Comment by BhumikP** [comment]
Hi @Bonapara You can assign it to me.

**Comment by Bonapara** [comment]
@BhumikP yes!

**Comment by lucasbordeau** [comment]
Hi @BhumikP, can you please try to use the `OverflowingTextWithTooltip` in your implementation to see if it can solve this problem ?

**Comment by BhumikP** [comment]
Okay, I will check on that component.

**Comment by BhumikP** [comment]
Hi @lucasbordeau  @Bonapara  , I am using Linux and I have gone through the Local setup [documentation](https://docs.twenty.com/developer/local-setup) .
I am facing the below issue of metadata  does not exist. But when I am checking through Postgress it is showing that metadata is already created.
![Screenshot from 2023-10-05 09-21-57](https://github.com/twentyhq/twenty/assets/57754267/c146e34b-21f6-4baa-80c3-525ba607f547)
![Screenshot from 2023-10-05 09-36-27](https://github.com/twentyhq/twenty/assets/57754267/aeafe1f2-cb18-4f77-a507-292544fe080f)

**Comment by lucasbordeau** [comment]
Could you come on Discord to talk about us with this issue ? https://discord.gg/5P3zAZch

**Comment by BhumikP** [comment]
Yeah, I resolved the issue, Now working on changes .

**Comment by BhumikP** [comment]
Do I have to make changes in all long texts that overflow, or just at two places that are mentioned in the image?
I have made changes for MenuItem as below.
![dropdown_fix](https://github.com/twentyhq/twenty/assets/57754267/d1c2d135-ca9d-4a35-9357-b0b42e83fdc6)

**Comment by BhumikP** [comment]
I have created a PR:- #1923

**Comment by Bonapara** [comment]
@BhumikP, I have closed the issue. Please mention me if you want it reopened.
