### ISSUE TITLE
We should be able to toggle boolean TableCell with enter hotkey.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1841]
## Scope & Context

In a TableCell component, we can have a `BooleanFieldInput` shown on field of type boolean.

## Current behavior

Currently we can only toggle its state by clicking on it.

## Expected behavior

We want to be able to toggle it with "enter" hotkey when the soft focus is on a TableCell which contains a BooleanFieldInput.

## Technical inputs

Please implement the useScopedHotkey hook in `BooleanInput` look for an example in other Input components.

**Comment by LakshayGMZ** [comment]
alright, soft focus to toggle. assign me the issue

**Comment by Bonapara** [comment]
@LakshayGMZ are you still on it? Thanks!

**Comment by tomalexing** [comment]
@Bonapara I could handle this one.

**Comment by LakshayGMZ** [comment]
> @LakshayGMZ are you still on it? Thanks!

i tried to make it work, using custom scoped hotkey hook but it seems to act weird (toggles the cell in first row only no matter where you press enter). I did mention that in discord. Please check it out
https://discord.com/channels/1130383047699738754/1146466959676936192/1159147317375553638

**Comment by Bonapara** [comment]
I'm just the product guy ;) Maybe @LakshayGMZ you may want to have a look and contribute with @tomalexing? I'll assign you too
