### ISSUE TITLE
Have the first column of a table read only after creationg

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1850]
## Scope & Context

On tables, first column OR name column (we have to decide)

## Current behavior

First column / name columns are editable after creation.

## Expected behavior

We want to make people double name and company only editable from show page.

See this issue for reference : https://github.com/twentyhq/twenty/issues/935

**Comment by SiR-PENt** [comment]
I'm on this @lucasbordeau

**Comment by lucasbordeau** [comment]
Hi, this has already been done in https://github.com/twentyhq/twenty/pull/1746, I think we can close this ticket now.
