### ISSUE TITLE
Bug: shadow in relation picker

### ISSUE THREAD

**Issue by brendanlaschke** [twentyhq/twenty#1855]
## Bug Description

Relation picker shadow relation when opening dropdown:

<img width="172" alt="Bildschirmfoto 2023-10-03 um 23 50 12" src="https://github.com/twentyhq/twenty/assets/48770548/1529e402-4030-4d7e-a52c-248117ae7579">

## Technical inputs

It seems like its the transparent background that produces this effect?

**Comment by dev-DTECH** [comment]
@brendanlaschke @Bonapara , I would like to work on this issue

**Comment by Bonapara** [comment]
@dev-DTECH go for it! Thanks
(Tell me if you're no longer interested)

**Comment by dev-DTECH** [comment]
@Bonapara, I fixed the bug please review and approve.
![image](https://github.com/twentyhq/twenty/assets/55497045/53b9ee1a-8d79-42df-996b-571dfbd95869)

**Comment by brendanlaschke** [comment]
fixed in https://github.com/twentyhq/twenty/pull/2078
