### ISSUE TITLE
Bug: Datepicker overlaying year and buttons filter menu

### ISSUE THREAD

**Issue by brendanlaschke** [twentyhq/twenty#1856]
## Bug Description

Open filter menu -> datepicker 

Problems:

* Overlaying Year and buttons
* Drodown chevron for month half visible different colors

<img width="279" alt="Bildschirmfoto 2023-10-03 um 23 51 58" src="https://github.com/twentyhq/twenty/assets/48770548/f820292d-69d7-48bc-b792-8b9d3ba0dc4f">

## Expected behavior

No overlays!

## Technical inputs

We already had the problem some time ago - I'm not sure if it was fixed back then ...

**Comment by brendanlaschke** [comment]
Also only certain dates can be selected ...

**Comment by Bonapara** [comment]
We should increase its width and separate its size from the width of the "filter menu". Please mention me in the PR to review the outcome.

**Comment by jobayer12** [comment]
@Bonapara Review my pull request #1877

**Comment by charlesBochet** [comment]
@jobayer12 Thanks for the help, we have investigated the issue and we have create a more detailed ticket here: https://github.com/twentyhq/twenty/issues/1891

Would you like to work on it? Thanks a lot, I'm closing this ticket and your PR as this is outdated
