### ISSUE TITLE
Refactor ViewBar and Table contexts

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1873]
## Scope & Context
 
ViewBar and Table have their scoped atoms and context, but it is a bit mixed right now, we'd like to clearly define each scope.

## Technical inputs

To be defined.

Ideas : 
- Refactor dropdowns in filters and sorts zone
- Split components that are getting to big

Let's wait for the refactor of Recoil Scope and Contexts before refactoring this part. https://github.com/twentyhq/twenty/issues/1695

**Comment by abhithory** [comment]
@lucasbordeau can you please explain it little bit more about this?? so that i can work on it

**Comment by lucasbordeau** [comment]
Hi @abhithory, we're currently working on a big refactor that need a bit more time, we'll keep you up to date when this ticket is ready.

**Comment by abhithory** [comment]
ok @lucasbordeau thanks. I really interested in working on this. So please let me know

**Comment by charlesBochet** [comment]
This has been implemented, closing it :)
