### ISSUE TITLE
Ability to insert images within notes

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#1878]
See release here: https://github.com/TypeCellOS/BlockNote/releases/tag/v0.9.4

It's now possible to attach images within the Blocknote editor:
https://www.blocknotejs.org/docs/image-toolbar

On the backend we [already have](https://docs.twenty.com/graphql/) the `uploadImage` mutation, so it might not be that complex to implement!

**Comment by AdityaPimpalkar** [comment]
Hey @FelixMalfait can I take this up?🙂

**Comment by FelixMalfait** [comment]
Oh yes of course @AdityaPimpalkar! Thanks a lot
