### ISSUE TITLE
Wrong assignee on loading team member picker

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1883]
# Current behavior

When opening the "team member" picker on a show, "No owner" is selected during the menu loading.

https://github.com/twentyhq/twenty/assets/19412894/ee14a853-a0f4-43a6-a036-3f2df175be85

# Desired behavior

"No owner" shouldn't be selected while the app is loading. Make sure to correct this behavior for all menu picker (not only this one!)

**Comment by lucasbordeau** [comment]
@Bonapara Should we also hide "No owner" while it's in loading state ? So we make sure nothing can be clicked.

**Comment by Bonapara** [comment]
@lucasbordeau Either make it unclickable or hide it! The simplest solution to implement, but hiding it seams a great idea.
