### ISSUE TITLE
Don't show unhideable fields in the Fields menu.

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1886]
# Current behavior 

- In **opportunities**, **companies** and **people**, unhideable field are displayed in Options > Fields.

<img width="186" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/4d071f77-5146-4f96-b462-07a3e66ff3b2">

- In Opportunities, Close date cannot be hidden.

<img width="200" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/2cf8cd3f-f3a6-4272-9410-bd34790db42f">

# Desired behavior

- Fields that cannot be hidden or reordered should not appear. (The names)
- In Opportunities, Close date shouldn't be a required field, it should be hideable as the other fields are

**Comment by alfredlouisw8** [comment]
hi can i work on this issue?

**Comment by tomalexing** [comment]
@alfredlouisw8 Hi, have you done some progress already? I sticked around with dnd , it should be easy task.

**Comment by abhithory** [comment]
Hi @Bonapara , Can you please assign this to me?? i want to work on this

**Comment by Bonapara** [comment]
Hello @abhithory. Yes, thanks.

**Comment by abhithory** [comment]
@Bonapara i have created a pull request for this at #1931 . Please check it

**Comment by Bonapara** [comment]
Hi @abhithory. Thanks for your speed! I'm doing product & I'm not merging PR, but the tech team will have a look.

**Comment by abhithory** [comment]
Ok @Bonapara . Thanks.

here are the results:--

![Screenshot from 2023-10-08 15-26-35](https://github.com/twentyhq/twenty/assets/76877003/2e35d1cb-e263-46c9-91fb-67e3210107f8)
![Screenshot from 2023-10-08 15-26-16](https://github.com/twentyhq/twenty/assets/76877003/34487655-ec4e-4482-bc43-361016b4fde1)

![Screenshot from 2023-10-08 15-11-59](https://github.com/twentyhq/twenty/assets/76877003/f8ad7aee-265a-4a1e-a110-327d68025b5b)

**Comment by tomalexing** [comment]
@abhithory  
You have hard coded name of the field.
`field.name !== 'Name' && (`
This feels error prone approch.
Have you teest it on People page?

**Comment by abhithory** [comment]
@tomalexing ok thanks for mentioning. @Bonapara only added their name so that's why i added the name that way. I will update like this

**Comment by abhithory** [comment]
just improved the code. PR: #1931
