### ISSUE TITLE
Add more typeguards

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1888]
## Scope & Context

Basic typeguards are missing in the front end.

## Technical inputs

We'd like to have common and precise typeguards like : 
- isNumber (that checks null and NaN)
- isNonEmptyString
- isArray
- isNonEmptyArray

etc.

We're open to implement some external libs if there's already something cool for that maybe ?

**Comment by charlesBochet** [comment]
https://github.com/sniptt-official/guards ?

**Comment by TharinduBalasooriya** [comment]
I would like to work on this , could please assign me the task @charlesBochet  , @lucasbordeau

**Comment by charlesBochet** [comment]
@TharinduBalasooriya any update on this one? :)

**Comment by gitstart-twenty** [comment]
Hey @charlesBochet I saw there's already a PR #2013 for this. Should we complete the work based on the dev's changes? And is the package used in the PR okay? I was thinking on using `lodash`, is it good enough or we stick with `@sniptt/guards`?

And should we explicitly export the files from `front/src/modules/ui/data/field/types/guards/`? Or we can just directly import from the library?

![Screenshot 2023-10-18 at 18 04 38](https://github.com/twentyhq/twenty/assets/140154534/71e06a15-7f1a-4094-8706-7a02d83d4800)

**Comment by charlesBochet** [comment]
@lucasbordeau do you have an advice here?

**Comment by lucasbordeau** [comment]
I would not recommend `lodash` as it's designed in a pure JavaScript paradigm and we're tackling a TypeScript problem here.

We can see the lodash does not offer a typeguard by checking the source code of its functions : https://github.com/lodash/lodash/blob/4.17.15/lodash.js#L12003

With [@sniptt/guards](https://github.com/sniptt-official/guards) however, it's a clear typeguard : https://github.com/sniptt-official/guards/blob/76ff862ed0eb2d3bcc622552e255426cf274a67b/lib/guards/primitives.ts#L11

So let's implement [@sniptt/guards](https://github.com/sniptt-official/guards) and replace every homemade typeguard in our codebase.

**Comment by magrinj** [comment]
I agree with @lucasbordeau, [sniptt/guards](https://github.com/sniptt-official/guards) seems to be the way to go

**Comment by gitstart-twenty** [comment]
Thanks all for the feedback
