### ISSUE TITLE
Create Storybook tests for the DropdownMenu component

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#1889]
## Scope & Context

Create Storybook tests for DropdownMenu component.

## Technical inputs

The DropdownMenu test in front/src/modules/ui/dropdown/components/__stories__/DropdownMenu.stories.tsx is currently a style test.
It should be an interaction test to test if clicking on the clickable component opens the DropdownMenu and clicking outside of it closes it.

**Comment by aman44444** [comment]
@bosiraphael i want to work on this can you please assign this to me?

**Comment by bosiraphael** [comment]
@aman44444 I assigned you the issue, thank you !

**Comment by Bonapara** [comment]
@aman44444 are you still on it? Thanks!

**Comment by aman44444** [comment]
@Bonapara i am preparing for my interview so i can't work on this you can assign someone else.
