### ISSUE TITLE
Update the width of the Dropdown component when it's a DatePicker

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#1891]
## Scope & Context

Follows https://github.com/twentyhq/twenty/pull/1877#issuecomment-1749030983

Right now, we have a bug on the Table > Filter > Created_at filter where the dropdown is not large enough to fit the date picker.
<img width="611" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/9600f954-dcb2-44df-91f2-088d106d43a9">

1) We want to update the width of the Dropdown component based on its width props, but also we want to provide a hook API to update it programmatically later.
2) We want MultipleFiltersDropdownFilter to use this capability to set the dropdown width based on filter type

We don't want the dropdown to fit its content as we don't want the content to dictate the dropdown width by default, this should be case by case and that's why we need to expose a hook. In different cases, we want to enforce the dropdown width (example, we want filter dropdown to be 160px, but on the board, we want the Add new to be 200px)

## Technical inputs

Part 1: Dropdown component
- introduce a recoil state to store the dropdown width
- Create a `DropdownOnWidthChangeEffect` which contains a  useEffect that listens to the width props to store it in a state
- add { width, setWidth} to `useDropdown()` to modify the width of the component from outside of it
- Rename `DropdownEffect` to `DropdownOnToggleEffect`

Part2: MultipleFiltersDropdownFilter
- Also add MultipleFiltersDropdownFilterOnFilterChangedEffect to front/src/modules/ui/view-bar/components/MultipleFiltersDropdownContent.tsx . 
- this useEffect will listen to filterDefinitionUsedInDropdown.type and use dropdown setWidth to update the width

**Comment by AyushDhimanIITR** [comment]
hey @bosiraphael can I work on this issue?

**Comment by bosiraphael** [comment]
@AyushDhimanIITR I think we still have to specify some details with the team for this issue, but as soon as it's ready, I will assign it to you. Thank you very much.

**Comment by alfredlouisw8** [comment]
hi can i work on this issue?

**Comment by FelixMalfait** [comment]
Sure @alfredlouisw8 thanks! Assigning it to you

**Comment by charlesBochet** [comment]
sure @alfredlouisw8
