### ISSUE TITLE
[Timebox] Create a front generic query generator from metadata.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1905]
## Scope & Context

With the new `/metadata` endpoint that returns the metadata of the current workspace objects, we need to be able to generate dynamic GraphQL queries that will return objects that we'll 

## Current behavior

We're currently requesting typed entities and store them in generic recoil family states.

## Expected behavior

We can use pretty much all of our existing frontend logic for handling generic objects, because the common family state we use stores everything field as unknown and then unwraps its type at runtime in Field components, based on its field type.

Since we'll now have the field type from the metadata, we'll be able to rely on those metadata to generate queries and mutations.

TODO: add example of a request on the generic /graphql endpoint to have the request and the response structure for a complex query and mutation.

**Comment by FelixMalfait** [comment]
That sounds nice 😍. Looking forward to seeing this!
