### ISSUE TITLE
Separate storybook docs and storybook tests

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#1906]
## Scope & Context

Currently, we are building two storybooks: modules + pages (see packages.json)
We want to build a third one that will only have docs components that will be used by the documentation

Right now, we only have one docs.mdx file: Button.docs.mdx, but we will add more very soon

## Technical inputs

- Rename STORYBOOK_STORIES_FOLDER in STORYBOOK_SCOPE
- Create a `storybook:docs:build` script in front/package.json
- Create a `storybook:docs:dev` script in front/package.json
- Use STORYBOOK_SCOPE=docs in front/.storybook/main.js to only generate `*.docs.mdx`

**Comment by FelixMalfait** [comment]
@nimraahmed would you feel comfortable handling this?

**Comment by nimraahmed** [comment]
Sure, I can try this out @FelixMalfait

**Comment by charlesBochet** [comment]
We have chosen to go with SandPack instead. Closing this issue
