### ISSUE TITLE
Create a "components" submodule in the documentation inside "frontend"

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#1908]
## Scope & Context

We would like to add a `components` section in the docs inside `docs/docs/developer/frontend` which will contain all the necessary information about the UI components and their APIs.

## Technical inputs

- Create a `components` folder inside `docs/docs/developer/frontend`
- Create all [componentName].mdx files
- [Not sure yet] Embed storybook docs with an iframe https://storybook.js.org/docs/react/sharing/embed
- Add information if necessary

**Comment by FelixMalfait** [comment]
I’m not convinced this is a good idea. Every time we duplicated something like this it ended up being outdated pretty quickly. Why not have the doc live next to each component?

**Comment by bosiraphael** [comment]
Has been done in https://github.com/twentyhq/twenty/pull/1926
