### ISSUE TITLE
Object Edit - Add Name and description section and form

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#1910]
Warning: this ticket is part of a series of tickets aiming to create the "Object Edition flow". This is ticket number 4

## Context

See #1765

For this issue:
- Add to the Object Edit page a "Name and description" section with a title, a description, and a form.
- For the form:
  - Use the `TextInputSettings` component with the `label` prop.
  - Add a new `TextareaSettings` component (see comment below: https://github.com/twentyhq/twenty/issues/1910#issuecomment-1752936568).
  - This section is shared with the New Object page (see #1808).

## Figma

![Image](https://github.com/twentyhq/twenty/assets/3098428/e3faa111-b16d-48be-a87f-a3a985bbc2b7)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11473%3A95826&mode=design&t=2s2xr7WoDZl6NpbR-1

### Scenario: Viewing the "Name and description" section

**GIVEN** I am on an Object Edit page
**THEN** I see a "Name and description" section with a title, a description, and a form
**AND** the form contains:
- an input for the object's singular name
- an input for the object's plural name
- a textarea for the object's description

### Scenario: Changing values in the "Name and description" form

**GIVEN** I am on an Object Edit page
**WHEN** I change a value in the "Name and description" form
**AND** I leave the field (on blur)
**THEN** the value is saved

**Comment by charlesBochet** [comment]
Textarea could be autogrowing. We already have a old text area autogrowing component in the project that you can take inspiration from (only for the autogrowing logic)

**Comment by martins5225** [comment]
Hi I would like to work on this issue

**Comment by martins5225** [comment]
Hi @charlesBochet there's no `TextInputSettings` in the codebase to reuse, I've read the ticket series and none seems to specify the component creation as well. Should i create one?

**Comment by charlesBochet** [comment]
@martins5225 We have refactored frontend components, it's called TextInput now :)

**Comment by thaisguigon** [comment]
Hi @martins5225, the Core team will be addressing this issue as other issues are dependent on this one.
