### ISSUE TITLE
Object Edit - Add danger zone section

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#1911]
Warning: this ticket is part of a series of tickets aiming to create the "Object Edition flow". This is ticket number 5

## Context

See #1765

For this issue, add to the Object Edit page a "Danger" section with a title, a description, and a "Disable" button.

## Figma

![Image](https://github.com/twentyhq/twenty/assets/3098428/c9da89b9-6285-4132-a97e-1929ab87c9e9)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11336%3A63490&mode=design&t=lrj7aulu2ylwpN5F-1

## Behavior

**GIVEN** I am on an Object Edit page
**THEN** I see a "Danger" section with a title, a description, and a "Disable" button

**Comment by thaisguigon** [comment]
Hi @abhithory, this issue is blocked for now as it depends on another issue being solved, but it should be available soon!

**Comment by thaisguigon** [comment]
The other issue was just solved and merged, so this issue is now ready. I assigned it to you @abhithory.

**Comment by bosiraphael** [comment]
Hello @abhithory, are you still working on it?

**Comment by bosiraphael** [comment]
Great thank you!

**Comment by abhithory** [comment]
Hello @bosiraphael and @thaisguigon . Please check
