### ISSUE TITLE
Reorganize UI components into folders in modules/ui

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#1912]
## Scope & Context

Think about a uniform way to organize UI components in the UI folder and in Storybook.
We want to introduce folders in ui: layout, feedback, data, form, ...

## Technical inputs

- Start by searching inspiration by looking at how other UI libraries organize their components : MUI, Chakra UI, Ant Design ...
- Reorganize the components in the same way in front/src/modules/ui and in Storybook

**Comment by FelixMalfait** [comment]
@nimraahmed related to the docs so could be interesting for you (but linked to frontend / so feel free to say if you’re not comfortable)

Or @bosiraphael are you working on it already?

**Comment by nimraahmed** [comment]
@FelixMalfait i can do this!

**Comment by nimraahmed** [comment]
@FelixMalfait  Suggested structure:

```
UI
  └───Inputs (folder already exists)
  │   └───button
  │   └───field
  │   └───tag
  └───Data Display
  │   └───Chip
  │   └───Data Table
  │   └───Inline-Cell
  │   └───Tooltip
  │   └───Typography
  │   └───Icons (Not sure)
  │   └───Checkmark (Not sure)
  └───Feedback
  │   └───Dialog
  │   └───Draggable List
  │   └───Modal (not sure, maybe in a separate Overlay folder)
  │   └───Progress Bar
  │   └───Snack Bar
  └───Navigation
  │   └───Breadcrumbs
  │   └───Context Menu
  │   └───Dropdown
  │   └───Link
  │   └───Nav Bar
  │   └───Menu
  │   └───Drawer
  └───Layout (folder already exists)
  │   └───Board
  │   └───Section
  │   └───Tabs
  │   └───Table
  └───Others (Not sure where they go best)
  │   └───Action Bar
  │   └───color scheme
  │   └───stepbar
  │   └───theme
  │   └───pill
  │   └───top bar
  │   └───view bar
```

**Comment by FelixMalfait** [comment]
@nimraahmed you categories look fine but I don't agree with the categorization for many of them at first sight (although I didn't look into the components and spend time checking)
Random examples: Checkmark would be an input for me, Draggable List could be input or data display, Modal would go in Layout or Others, Board in others, Tabs in Navigation, Dropdown in inputs...
Could you please double check everything and raise a PR once you have a strong conviction you got them right?
Thanks!

**Comment by charlesBochet** [comment]
It's not an easy one! I think we have specificities on the project around "Data" which is a central piece where we should put: Fields, DataTable, DataBoard, ViewBar.

Dropdown, Modal should go into Layout
Let's do a pass this morning over the components @nimraahmed, I would like to give you other inputs

**Comment by charlesBochet** [comment]
After discussing with Nimra:

UI
  └───Inputs
  │   └───Button
  │   └───Checkbox
  │   └───...
  │   └───Relation Picker
  └───Data
  │   └───Data Table
  │   └───Inline Cell
  │   └───Field
  │   └───Data Board
  │   └───View Bar
  └───Display
  │   └───Chip
  │   └───Tag
  │   └───Tooltip
  │   └───Typography
  │   └───Icons
  │   └───Checkmark
  │   └───Pill
  └───Feedback
  │   └───Dialog
  │   └───Progress Bar
  │   └───Snack Bar
  └───Navigation
  │   └───Breadcrumbs
  │   └───Context Menu
  │   └───Action Bar
  │   └───Stepbar
  │   └───Link
  │   └───Nav Bar
  │   └───Menu
  └───Layout
  │   └───Page
  │   └───Board
  │   └───Section
  │   └───Tabs
  │   └───Table
  │   └───Draggable List
  │   └───Dropdown
  │   └───Drawer
  │   └───Modal
  │   └───Top Bar
  └───Theme
  │   └───color scheme
  │   └───theme
  └───Utilities
