### ISSUE TITLE
Objects Settings - Add the "New object" button

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#1913]
## Context

See #1756 

For this issue, in the Objects Settings page, add a "New object" button that redirects to the "New object" page (see [#1764](https://github.com/twentyhq/twenty/issues/1764))

## Figma

![Image](https://github.com/twentyhq/twenty/assets/3098428/e1379176-fdb3-4f1d-a249-f38e26d5ec7a)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11489%3A98999&mode=design&t=NWGUrAMIRJvlOlxg-1

## Behavior

**GIVEN** I am on the Objects Settings page
**THEN** I see a "New object" button

**GIVEN** I am on the Objects Settings page
**AND** I click on the "New object" button
**THEN** I navigate to the "New object" page

**Comment by Abhi3685** [comment]
Hi, Can I work on this? From my understanding, seems like we need to add a button which would redirect to the already created "New object" page. Please correct me if I missing something here. Would love to contribute on this one.

**Comment by FelixMalfait** [comment]
Yes assigning it to you since it's been labelled as "good first issue" it should be doable. Let us know if you need help! Thanks 

It's indeed part of a big workstream to introduce "custom objects" to the app 

cc @charlesBochet
