### ISSUE TITLE
Create Storybook tests for the link components

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#1916]
## Scope & Context

Create Storybook tests for all the UI components.

## Technical inputs

Only two stories have been created in front/src/modules/ui/link/components/__stories__/ for the link components : RoundedLink.stories and PrimaryLink.stories

Based on these two files, we need to create stories for : 
- ContactLink (test email + phone)
- RawLink
- SocialLink (test twitter + linkedin)

Also delete PrimaryLink and its story that is not used anymore

**Comment by rsato10** [comment]
Hello, can I be assigned to Issue #1916. I am new so if you need any other issues resolved I can work on those as well.

**Comment by FelixMalfait** [comment]
Thanks a lot @rsato10!
