### ISSUE TITLE
New Object - Add "Object type" section

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#1918]
Warning: this ticket is part of a series of tickets aiming to create the "Object Creation flow". This is ticket number 3

## Context

See #1764 

For this issue:
- Create the New Object page "Object type" section, with a title and a description.
- Add three selectable items: Standard, Custom and Remote (disabled).

## Figma

![Image](https://github.com/twentyhq/twenty/assets/3098428/4c498625-9224-4c86-aa30-c3e0404b688b)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11452-92426&mode=design&t=JTOVoeCGD6DTr2rv-4

## Behavior

**GIVEN** I am on the New Object page
**THEN** I see an "Object type" section with a title and a description
**AND** I see two selectable boxes: Standard and Custom, and a disabled box: Remote

**Comment by Kanav-Arora** [comment]
Hey 
Can I work on this issue?

**Comment by thaisguigon** [comment]
Hi @Kanav-Arora, this issue is blocked for now as it depends on another issue being solved first, but should be available soon!

**Comment by thaisguigon** [comment]
The other issue was solved and merged, you can now work on this issue @Kanav-Arora.

**Comment by Kanav-Arora** [comment]
Hi @thaisguigon 
Please refer PR #1985
