### ISSUE TITLE
React DnD bug on Company, People, Opportunities pages

### ISSUE THREAD

**Issue by tomalexing** [twentyhq/twenty#1920]
## Bug Description

On Company, People, Opportunities pages in the Options > Fields the drag and drop generates a bug while I am reordering items.
It occurs on secons or third reordering.

https://github.com/twentyhq/twenty/assets/9631913/9871ee0c-856b-4509-918b-cd44cb028b7b

## Expected behavior

Should work.

## Technical inputs

Dnd seems to be often re-rendered. So it loses its placeholder and initial height.

**Comment by FelixMalfait** [comment]
Removing the good first issue label since Tom proposed a fix along with creating the issue (thanks for that!!!)
