### ISSUE TITLE
Refactor and extract View/ViewField module from ViewBar and other places with new Scopes.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1939]
### Context

We have an ongoing refactor of recoil scopes and react contexts into a unified Scope concept that allows us to create state modules with integrated react contexts.

### Required 

We would like to place in a separate module everything that is related to view. You can see why by looking at the Task filtering feature, which has nothing to do with the ViewBar module.

The ViewBar module feels almost like the View module but we should separate everything.

We should also include the filtering feature of views into the View module and not in view bar module, because it is used in Task module, and could be used elsewhere.

ViewBar module should be focused on managing the states of the UI components and other ViewBar specific feature. Maybe we can put a lot of the states and events in View module.

Take care of using the V2 useRecoil hooks and convert all the atoms to the new createScopedState and other atom utility functions.

**Comment by charlesBochet** [comment]
This has been implemented, closing it :)
