### ISSUE TITLE
Refactor Table with ViewScopes

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1941]
### Context

We have an ongoing refactor of recoil scopes and react contexts into a unified Scope concept that allows us to create state modules with integrated react contexts.

### Required

We would like to place in a separate module everything that is related to Table. Like we did on issue https://github.com/twentyhq/twenty/issues/1939, for ViewBar and View module, the goal is to extract everything that is specific to Table module only.

Take care of using the V2 useRecoil hooks and convert all the atoms to the new createScopedState and other atom utility functions.

**Comment by charlesBochet** [comment]
This has been implemented, closing it :)
