### ISSUE TITLE
Update the frontend to adhere to the custom eslint rule `twenty/no-spread-props`

### ISSUE THREAD

**Issue by gitstart-twenty** [twentyhq/twenty#1956]
## Scope & Context

In previous PR: #1733 , we have introduced a new custom eslint rule that removes the `{...props}` pattern and props coupling. This ticket is to update the code in the frontend to adhere to this new rule since for now we're ignoring the rule.

## Technical inputs

- Remove all places in the code where we ignore the rule i.e `// eslint-disable-next-line twenty/no-spread-props`
- Update the code in the frontend to adhere to this new rule since for now we're ignoring the rule.

**Comment by charlesBochet** [comment]
@thaisguigon
