### ISSUE TITLE
When in local development mode, we have silent authentication errors caused by the tokenPair.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1959]
## Bug Description

In local development mode, on the front folder, we get silent errors after a few app fast reloads. 

<img width="1240" alt="Capture d’écran 2023-10-10 à 12 31 42" src="https://github.com/twentyhq/twenty/assets/26528466/edec8d45-1dbf-4593-8d6a-c2e57e8a2097">

We have to manually delete the tokenPair cookie in chrome devtools.

Refreshing and hard-refreshing the page doesn't help.

## Expected behavior

We shouldn't have this silent error, or this behavior.

The tokenPair cookie should be deleted or we should have a visible error on the front end, maybe we should even get redirected to the login page.

It started appearing with : https://github.com/twentyhq/twenty/pull/1843, https://github.com/twentyhq/twenty/issues/1337 and https://github.com/twentyhq/twenty/issues/1846

**Comment by khakimov** [comment]
Found in server/src/app.modules.ts:

```
60  // If there is no token or flexible backend is disabled (_default is false_), return an empty schema
61  if (!token || !environmentService.isFlexibleBackendEnabled()) {
62    return new GraphQLSchema({});
63  }
64
65  // Verify and decode JWT
66  ...
```
returns before verify() and doesn't catch error with UNAUTHENTICATED. 

Easiest way to fix it:

```
          // If there is no token return an empty schema
          if (!token) {
            return new GraphQLSchema({});
          }

          // Verify and decode JWT
          const decoded = verify(
            token,
            environmentService.getAccessTokenSecret(),
          );
          
          // If there is flexible backend is disabled return an empty schema
          if (!environmentService.isFlexibleBackendEnabled()) {
            return new GraphQLSchema({});
          }
```

**Comment by khakimov** [comment]
No more silent errors anymore with new runtime error in /metadata :) 

<img width="954" alt="image" src="https://github.com/twentyhq/twenty/assets/396223/69d1c709-054f-4265-97fb-bdc7e2a57a72">

Guessing that error pops up from this code

https://github.com/twentyhq/twenty/blob/b128d53b584783d6bc4ae9d3197ebc5d2669a060/front/src/modules/metadata/components/FetchMetadataEffect.tsx#L17-L37

https://github.com/twentyhq/twenty/blob/b128d53b584783d6bc4ae9d3197ebc5d2669a060/front/src/modules/metadata/components/ApolloClientMetadataProvider.tsx#L17-L29

Shall we add onError in apolloClientMetadata to handle it?

**Comment by FelixMalfait** [comment]
Closing as it seems so be solved (?)
