### ISSUE TITLE
Set single notes in a 2 columns layout on people & companies detail pages

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1966]
## Current behavior

Single card is taking the full page width:

![image](https://github.com/twentyhq/twenty/assets/19412894/e67c886c-5507-4332-8ccf-3e93f6d810c0)

## Expected behavior

There should already be a column system: 

![image](https://github.com/twentyhq/twenty/assets/19412894/491fcbb6-bb14-460c-b629-41bcafaab0a3)

**Comment by gaurab-khanal** [comment]
Can I work on this issue?

**Comment by rajvinder-kaur** [comment]
can u please add a hactoberfest tag aswell

**Comment by martins5225** [comment]
HI I'd like to work on this issue

**Comment by cricket-lover** [comment]
Hi @Bonapara I see there are no PRs raised yet. can I also work on this?

**Comment by Bonapara** [comment]
Yes, @cricket-lover thanks!

**Comment by cricket-lover** [comment]
@Bonapara I have raised a PR, Please have a look
