### ISSUE TITLE
Chore(front): Improve Test Coverage and/or Add New Tests

### ISSUE THREAD

**Issue by gitstart-twenty** [twentyhq/twenty#1980]
## Scope & Context

- Increase test coverage in the frontend repo
- Aim for 80% coverage

## Technical inputs

Below are files with less than 80% coverage.

- [ ] **src/**

  - [ ] `src/AppNavbar.tsx`: 58.33%

- [ ] **src/modules/activities/components/**

  - [ ] `ActivityBodyEditor.tsx`: 76.47%
  - [ ] `ActivityComments.tsx`: 43.33%
  - [ ] `ActivityCreateButton.tsx`: 50.00%
  - [ ] `ActivityEditor.tsx`: 64.52%

- [ ] **src/modules/activities/editable-fields/components/**

  - [ ] `ActivityRelationEditableFieldEditMode.tsx`: 7.14%

- [ ] **src/modules/activities/hooks/**

  - [ ] `useHandleCheckableActivityTargetChange.ts`: 5.56%
  - [ ] `useOpenCreateActivityDrawerForSelectedRowIds.ts`: 50.00%

- [ ] **src/modules/activities/notes/components/**

  - [ ] `Notes.tsx`: 38.46%

- [ ] **src/modules/activities/right-drawer/components/**

  - [ ] `ActivityActionBar.tsx`: 71.43%

-  [ ] **src/modules/activities/tasks/components/**

  - [ ] `PageAddTaskButton.tsx`: 12.50%

- [ ] **src/modules/activities/tasks/hooks/**

  - [ ] `src/modules/activities/tasks/hooks/useCompleteTask.ts`: 75.00%

- [ ] **src/modules/activities/timeline/components/**

  - [ ] `Timeline.tsx`: 50.00%
  - [ ] `TimelineActivityTitle.tsx`: 78.57%

- [ ] **src/modules/activities/utils/**

  - [ ] `flatMapAndSortEntityForSelectArrayByName.ts`: 33.33%
  - [ ] `getRelationData.ts`: 77.78%

- [ ] **src/modules/apollo/optimistic-effect/hooks/**
  - [ ] `useOptimisticEvict.ts`: 44.44%

- [ ] **src/modules/auth/components/**
  - [ ] `Logo.tsx`: 62.50%

- [ ] **src/modules/auth/hooks/**
  - [ ] `useAuth.ts`: 41.18%

- [ ] **src/modules/auth/sign-in-up/components/**
  - [ ] `SignInUpForm.tsx`: 70.27%

- [ ] **src/modules/auth/sign-in-up/hooks/**
  - [ ] `useSignInUp.tsx`: 55.56%

- [ ] **src/modules/command-menu/components/**
  - [ ] `CommandMenuItem.tsx`: 50.00%

- [ ] **src/modules/companies/components/**
  - [ ] `AddPersonToCompany.tsx`: 8.11%
  - [ ] `CompanyTeam.tsx`: 42.11%
  - [ ] `NewCompanyProgressButton.tsx`: 56.52%

- [ ] **src/modules/companies/hooks/**
  - [ ] `useCompanyTableActionBarEntries.tsx`: 63.64%
  - [ ] `useCompanyTableContextMenuEntries.tsx`: 62.50%
  - [ ] `useCreateCompanyProgress.ts`: 40.00%
  - [ ] `useDeleteCompanies.ts`: 47.06%
  - [ ] `useSpreadsheetCompanyImport.ts`: 46.15%

- [ ] **src/modules/companies/table/components/**
  - [ ] `CompanyTable.tsx`: 60.00%

- [ ] **src/modules/favorites/components/**
  - [ ] `Favorites.tsx`: 55.56%

- [ ] **src/modules/favorites/hooks/**
  - [ ] `useFavorites.ts`: 69.23%

- [ ] **src/modules/people/components/**
  - [ ] `FilterDropdownPeopleSearchSelect.tsx`: 16.67%
  - [ ] `PeopleCard.tsx`: 11.11%
  - [ ] `PeoplePicker.tsx`: 10.00%

- [ ] **src/modules/people/editable-field/components/**
  - [ ] `PeopleFullNameEditableField.tsx`: 63.64%

- [ ] **src/modules/people/hooks/**
  - [ ] `useCreateActivityForPeople.ts`: 33.33%
  - [ ] `useFilteredSearchPeopleQuery.ts`: 33.33%
  - [ ] `usePeopleTableContextMenuEntries.tsx`: 55.17%
  - [ ] `usePersonQuery.ts`: 25.00%
  - [ ] `usePersonTableActionBarEntries.tsx`: 47.62%
  - [ ] `useSpreadsheetPersonImport.ts`: 46.15%

- [ ] **src/modules/people/utils/**
  - [ ] `fieldsForPerson.tsx`: 50.00%

- [ ] **src/modules/pipeline/components/**
  - [ ] `PipelineAddButton.tsx`: 37.50%

- [ ] **src/modules/pipeline/constants/**
  - [ ] `pipelineAvailableFieldDefinitions.tsx`: 50.00%

- [ ] **src/modules/pipeline/hooks/**
  - [ ] `usePipelineStages.ts`: 63.64%

- [ ] **src/modules/settings/profile/components/**
  - [ ] `DeleteAccount.tsx`: 66.67%
  - [ ] `DeleteWorkspace.tsx`: 6.67%
  - [ ] `NameFields.tsx`: 53.85%
  - [ ] `ProfilePictureUploader.tsx`: 41.67%
  - [ ] `ToggleField.tsx`: 54.55%

- [ ] **src/modules/settings/workspace/components/**
  - [ ] `NameField.tsx`: 9.52%
  - [ ] `WorkspaceLogoUploader.tsx`: 63.64%

- [ ] **src/modules/spreadsheet-import/components/**
  - [ ] `MatchColumnSelect.tsx`: 56.67%
  - [ ] `ModalCloseButton.tsx`: 66.67%

- [ ] **src/modules/spreadsheet-import/hooks/**
  - [ ] `useSpreadsheetImportInitialStep.ts`: 54.55%

- [ ] **src/modules/spreadsheet-import/provider/components/**
  - [ ] `SpreadsheetImport.tsx`: 42.86%

- [ ] **src/modules/spreadsheet-import/steps/components/**
  - [ ] `Steps.tsx`: 21.43%
  - [ ] `UploadFlow.tsx`: 5.56%

- [ ] **src/modules/spreadsheet-import/steps/components/MatchColumnsStep**
  - [ ] `MatchColumnsStep.tsx`: 44.78%
  - [ ] `SubMatchingSelect.tsx`: 20.00%
  - [ ] `TemplateColumn.tsx`: 56.41%

- [ ] **src/modules/spreadsheet-import/steps/components/SelectHeaderStep**
  - [ ] `SelectHeaderStep.tsx`: 61.54%
  - [ ] `SelectHeaderTable.tsx`: 44.44%

- [ ] **src/modules/spreadsheet-import/steps/components/SelectSheetStep**
  - [ ] `SelectSheetStep.tsx`: 70.59%

- [ ] **src/modules/spreadsheet-import/steps/components/UploadStep**
  - [ ] `UploadStep.tsx`: 66.67%
  - [ ] `DropZone.tsx`: 61.54%

- [ ] **src/modules/spreadsheet-import/steps/components/ValidationStep**
  - [ ] `ValidationStep.tsx`: 45.07%
  - [ ] `columns.tsx`: 66.67%

- [ ] **src/modules/spreadsheet-import/tests**
  - [ ] `mockRsiValues.ts`: 33.33%

- [ ] **src/modules/spreadsheet-import/utils**
  - [ ] `dataMutations.ts`: 77.55%
  - [ ] `exceedsMaxRecords.ts`: 25.00%
  - [ ] `getFieldOptions.ts`: 20.00%
  - [ ] `mapWorkbook.ts`: 25.00%
  - [ ] `normalizeCheckboxValue.ts`: 40.00%
  - [ ] `normalizeTableData.ts`: 4.00%
  - [ ] `readFilesAsync.ts`: 14.29%
  - [ ] `setColumn.ts`: 50.00%
  - [ ] `setIgnoreColumn.ts`: 50.00%
  - [ ] `setSubColumn.ts`: 14.29%
  - [ ] `uniqueEntries.ts`: 25.00%

- [ ] **src/modules/ui/board/components/**

  - [ ] `BoardColumnEditTitleMenu.tsx`: 50.00%
  - [ ] `BoardColumnMenu.tsx`: 4.65%
  - [ ] `BoardHeader.tsx`: 63.33%
  - [ ] `BoardOptionsDropdownContent.tsx`: 52.08%
  - [ ] `EntityBoard.tsx`: 60.71%
  - [ ] `EntityBoardCard.tsx`: 63.64%

- [ ] **src/modules/ui/board/hooks/**

  - [ ] `useBoardCardFields.ts`: 62.50%
  - [ ] `useBoardColumns.ts`: 50.00%
  - [ ] `useCurrentCardSelected.ts`: 33.33%
  - [ ] `useDeleteSelectedBoardCards.ts`: 60.00%
  - [ ] `useRemoveCardIds.ts`: 25.00%
  - [ ] `useSetCardSelected.ts`: 27.27%
  - [ ] `useUpdateBoardCardIds.ts`: 7.69%

- [ ] **src/modules/ui/board/states/selectors/**

  - [ ] `hiddenBoardCardFieldsScopedSelector.ts`: 75.00%

- [ ] **src/modules/ui/checkmark/components/**

  - [ ] `AnimatedCheckmark.tsx`: 33.33%

- [ ] **src/modules/ui/chip/components/**

  - [ ] `EntityChip.tsx`: 60.00%

- [ ] **src/modules/ui/color-scheme/components/**

  - [ ] `ColorSchemePicker.tsx`: 30.77%

- [ ] **src/modules/ui/data-table/components/**

  - [ ] `DataTableCell.tsx`: 66.67%
  - [ ] `DataTableColumnDropdownMenu.tsx`: 6.25%
  - [ ] `DataTableEffect.tsx`: 61.54%
  - [ ] `DataTableHeader.tsx`: 62.22%
  - [ ] `DataTableHeaderPlusButton.tsx`: 14.29%

- [ ] **src/modules/ui/data-table/hooks/**

  - [ ] `useDisableSoftFocus.ts`: 33.33%
  - [ ] `useLeaveTableFocus.ts`: 69.23%
  - [ ] `useMapKeyboardToSoftFocus.ts`: 60.00%
  - [ ] `useMoveSoftFocus.ts`: 16.00%
  - [ ] `useSelectAllRows.ts`: 33.33%
  - [ ] `useSetRowSelectedState.ts`: 66.67%
  - [ ] `useTableColumns.ts`: 37.50%

- [ ] **src/modules/ui/data-table/options/components/**

  - [ ] `TableOptionsDropdownContent.tsx`: 48.84%

- [ ] **src/modules/ui/data-table/states/selectors/**

  - [ ] `numberOfTableColumnsScopedSelector.ts`: 33.33%

- [ ] **src/modules/ui/data-table/table-cell/components/**

  - [ ] `TableCell.tsx`: 58.33%
  - [ ] `TableCellSoftFocusMode.tsx`: 76.47%

- [ ] **src/modules/ui/data-table/table-header/components/**

  - [ ] `TableHeader.tsx`: 60.00%

- [ ] **src/modules/ui/dialog/states/**

  - [ ] `dialogState.ts`: 28.57%

- [ ] **src/modules/ui/dropdown/components/**

  - [ ] `DropdownMenu.tsx`: 78.57%
  - [ ] `DropdownMenuContainer.tsx`: 28.57%

- [ ] **src/modules/ui/field/hooks/**

  - [ ] `usePersistField.ts`: 63.89%

- [ ] **src/modules/ui/field/meta-types/__stories__/**

  - [ ] `FieldContextProvider.tsx`: 75.00%

- [ ] **src/modules/ui/field/meta-types/display/content-display/components/**

  - [ ] `ChipDisplay.tsx`: 66.67%
  - [ ] `PhoneDisplay.tsx`: 66.67%

- [ ] **src/modules/ui/field/meta-types/hooks/**

  - [ ] `useMoneyField.ts`: 66.67%
  - [ ] `useNumberField.ts`: 66.67%
  - [ ] `useURLField.ts`: 72.73%

- [ ] **src/modules/ui/field/meta-types/input/components/**

  - [ ] `ChipFieldInput.tsx`: 7.14%
  - [ ] `DateFieldInput.tsx`: 75.00%
  - [ ] `DoubleTextChipFieldInput.tsx`: 7.14%
  - [ ] `DoubleTextFieldInput.tsx`: 7.14%
  - [ ] `EmailFieldInput.tsx`: 71.43%
  - [ ] `MoneyFieldInput.tsx`: 7.69%
  - [ ] `NumberFieldInput.tsx`: 7.69%
  - [ ] `PhoneFieldInput.tsx`: 7.69%
  - [ ] `TextFieldInput.tsx`: 7.14%
  - [ ] `URLFieldInput.tsx`: 7.69%

- [ ] **src/modules/ui/field/types/guards/**

  - [ ] `isFieldBooleanValue.ts`: 50.00%
  - [ ] `isFieldChipValue.ts`: 50.00%
  - [ ] `isFieldDateValue.ts`: 50.00%
  - [ ] `isFieldDoubleTextChipValue.ts`: 50.00%
  - [ ] `isFieldDoubleTextValue.ts`: 50.00%
  - [ ] `isFieldEmailValue.ts`: 50.00%
  - [ ] `isFieldMoneyValue.ts`: 50.00%
  - [ ] `isFieldNumberValue.ts`: 50.00%
  - [ ] `isFieldPhoneValue.ts`: 50.00%
  - [ ] `isFieldProbabilityValue.ts`: 50.00%
  - [ ] `isFieldTextValue.ts`: 50.00%
  - [ ] `isFieldURLValue.ts`: 50.00%

- [ ] **src/modules/ui/inline-cell/components**
  
  - [ ] `InlineCell.tsx`: 52.00%
  - [ ] `InlineCellEditButton.tsx`: 20.00%
  - [ ] `InlineCellEditMode.tsx`: 33.33%

- [ ] **src/modules/ui/inline-cell/hooks**

  - [ ] `useInlineCell.ts`: 53.85%

- [ ] **src/modules/ui/input/components**

  - [ ] `AutosizeTextInput.tsx`: 66.04%
  - [ ] `CountryPickerDropdownButton.tsx`: 8.82%
  - [ ] `CountryPickerDropdownSelect.tsx`: 21.43%
  - [ ] `DoubleTextInput.tsx`: 5.26%
  - [ ] `PhoneInput.tsx`: 18.75%
  - [ ] `RadioGroup.tsx`: 66.67%

- [ ] **src/modules/ui/input/image/components**

  - [ ] `ImageInput.tsx`: 76.67%

- [ ] **src/modules/ui/input/relation-picker/components**

  - [ ] `MultipleEntitySelect.tsx`: 5.88%
  - [ ] `SingleEntitySelect.tsx`: 75.00%

- [ ] **src/modules/ui/menu-item/components**

  - [ ] `MenuItemToggle.tsx`: 75.00%

- [ ] **src/modules/ui/modal/components**

  - [ ] `ConfirmationModal.tsx`: 60.00%

- [ ] **src/modules/ui/navbar/components**

  - [ ] `MainNavbar.tsx`: 77.78%
  - [ ] `SupportChat.tsx`: 43.48%

- [ ] **src/modules/ui/snack-bar/states**

  - [ ] `snackBarState.ts`: 28.57%

- [ ] **src/modules/ui/step-bar/components**

  - [ ] `Step.tsx`: 31.82%
  - [ ] `StepBar.tsx`: 25.00%

- [ ] **src/modules/ui/step-bar/hooks**

  - [ ] `useStepBar.ts`: 78.57%

- [ ] **src/modules/ui/theme/hooks**

  - [ ] `useColorScheme.ts`: 7.14%

- [ ] **src/modules/ui/utilities/drag-select/components**

  - [ ] `DragSelect.tsx`: 57.14%

- [ ] **src/modules/ui/utilities/hotkey/hooks**

  - [ ] `useGoToHotkeys.ts`: 75.00%
  - [ ] `useSequenceScopedHotkeys.ts`: 31.25%

- [ ] **src/modules/ui/utilities/pointer-event/hooks**

  - [ ] `useTrackPointer.ts`: 30.43%

- [ ] **src/modules/ui/utilities/scroll/hooks**

  - [ ] `useListenScroll.ts`: 61.11%

- [ ] **src/modules/ui/view-bar/components**

  - [ ] `FilterDropdownDateSearchInput.tsx`: 9.09%
  - [ ] `FilterDropdownEntitySearchSelect.tsx`: 67.57%
  - [ ] `FilterDropdownNumberSearchInput.tsx`: 10.00%
  - [ ] `FilterDropdownOperandButton.tsx`: 75.00%
  - [ ] `FilterDropdownOperandSelect.tsx`: 5.56%
  - [ ] `GenericEntityFilterChip.tsx`: 50.00%
  - [ ] `SingleEntityFilterDropdownButton.tsx`: 7.69%
  - [ ] `UpdateViewButtonGroup.tsx`: 73.33%
  - [ ] `ViewFieldsVisibilityDropdownSection.tsx`: 4.55%
  - [ ] `ViewsDropdownButton.tsx`: 52.17%

- [ ] **src/modules/ui/view-bar/hooks**
  
  - [ ] `useRemoveFilter.ts`: 62.50%
  - [ ] `useRemoveView.ts`: 41.67%
  - [ ] `useUpsertView.ts`: 25.71%

- [ ] **src/modules/ui/view-bar/states/selectors**
  
  - [ ] `savedFiltersByKeyFamilySelector.ts`: 75.00%
  - [ ] `savedSortsByKeyFamilySelector.ts`: 75.00%

- [ ] **src/modules/ui/view-bar/utils**

  - [ ] `getOperandLabel.ts`: 38.89%
  - [ ] `getOperandsForFilterType.ts`: 66.67%
  - [ ] `turnFilterIntoWhereClause.ts`: 33.33%

- [ ] **src/modules/users/components**

  - [ ] `UserPicker.tsx`: 14.29%

- [ ] **src/modules/users/utils**

  - [ ] `getProfilePictureAbsoluteURI.ts`: 77.78%

- [ ] **src/modules/views/hooks**

  - [ ] `useBoardViewFields.ts`: 58.54%
  - [ ] `useBoardViews.ts`: 61.90%
  - [ ] `useMoveViewColumns.ts`: 23.08%
  - [ ] `useTableViewFields.ts`: 63.41%
  - [ ] `useTableViews.ts`: 66.67%
  - [ ] `useViewFilters.ts`: 34.09%
  - [ ] `useViewSorts.ts`: 34.09%
  - [ ] `useViews.ts`: 78.95%

- [ ] **src/modules/workspace/components**

  - [ ] `WorkspaceInviteLink.tsx`: 77.78%
  - [ ] `WorkspaceMemberCard.tsx`: 33.33%

- [ ] **src/pages/auth**

  - [ ] `CreateProfile.tsx`: 63.33%
  - [ ] `CreateWorkspace.tsx`: 65.22%
  - [ ] `VerifyEffect.tsx`: 5.88%

- [ ] **src/pages/impersonate**

  - [ ] `ImpersonateEffect.tsx`: 3.70%

- [ ] **src/pages/people**

  - [ ] `PersonShow.tsx`: 4.55%
  - [ ] `people-sorts.tsx`: 33.33%

- [ ] **src/pages/people/constants**

  - [ ] `personShowFieldDefinition.tsx`: 50.00%

- [ ] **src/pages/settings/**

  - [ ] `SettingsExperience.tsx`: 33.33%
  - [ ] `SettingsNewObject.tsx`: 50.00%
  - [ ] `SettingsObjectDetail.tsx`: 20.00%
  - [ ] `SettingsObjectEdit.tsx`: 20.00%
  - [ ] `SettingsWorkspace.tsx`: 50.00%
  - [ ] `SettingsWorkspaceMembers.tsx`: 50.00%

- [ ] **src/pages/tasks/**
  - [ ] `Tasks.tsx`: 50.00%
  - [ ] `TasksEffect.tsx`: 10.00%

- [ ] **src/testing/mock-data/**
  - [ ] `index.ts`: 79.31%

- [ ] **src/utils/**
  - [ ] `cast-as-integer-or-null.ts`: 8.57%
  - [ ] `cookie-storage.ts`: 62.50%
  - [ ] `date-utils.ts`: 59.65%
  - [ ] `debounce.ts`: 40.00%
  - [ ] `is-url.ts`: 50.00%
  - [ ] `logError.ts`: 50.00%
  - [ ] `measureTotalFrameLoad.ts`: 20.00%
  - [ ] `recoil-effects.ts`: 58.82%
  - [ ] `title-utils.ts`: 23.53%

**Comment by gitstart-twenty** [comment]
Hey @charlesBochet,
What do you think of this?

**Comment by alfredlouisw8** [comment]
hi can i take the `src/AppNavbar.tsx`?

**Comment by gitstart-twenty** [comment]
> hi can i take the `src/AppNavbar.tsx`?

@charlesBochet
