### ISSUE TITLE
Improve docker db init / reset

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1981]
## Scope & Context

When using make `provision-postgres` we can face different problems :  
- If we have an old image for postgres, the init.sql script might not be up to date
- If we have an old db_data volume, it might conflict with new changes
- The volume name db_data might conflict with other apps in our script

## Technical inputs

- Have a script `hard-reset-postgres` or change `provision-postgres`
- Change volume name `db_data` to `twenty_db_data`
- The script should stop the container postgres, delete the container, prune the volume `twenty_db_data`
- The script should rebuild the image every time, use `--build` in docker compose to force build.

**Comment by khakimov** [comment]
let me do that 🙋

**Comment by charlesBochet** [comment]
This has been merged! Thank you @khakimov, I'm re-testing everything and updating the doc

**Comment by tomalexing** [comment]
/dev/null is not working on windows

**Comment by khakimov** [comment]
> /dev/null is not working on windows

Oops, thanks for catching this. Removed /dev/null. 

Output is informative enought to see when docker is not running, no need extra checking:

> Cannot connect to the Docker daemon at unix:///tmp/.docker/run/docker.sock. Is the docker daemon running?

**Comment by charlesBochet** [comment]
This has been merged! Thank you @tomalexing @khakimov!
