### ISSUE TITLE
CMD-K → remove line break

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1983]
# Current behavior

The line breaks after "then"

![image](https://github.com/twentyhq/twenty/assets/19412894/835cab03-13ee-4569-bbd0-6fe62a5c5f3e)

# Desired behavior

All the content "G then P" should fit on a single row.

**Comment by alfredlouisw8** [comment]
can i work on this issue?

**Comment by growupanand** [comment]
can i pick this issue?
