### ISSUE TITLE
Display custom objects in navbar.

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1990]
## Desired behavior

When a custom object is created, it should be displayed in the navbar below the standard objects:

![image](https://github.com/twentyhq/twenty/assets/19412894/6c6ed7da-ff93-4b93-8951-a010d99abd56)

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
Can you assign me this issue?

**Comment by Bonapara** [comment]
It's not ready yet @Kanav-Arora! Thanks

**Comment by Kanav-Arora** [comment]
Okay 
Please update me once its ready

**Comment by charlesBochet** [comment]
Sure, we will ! Likely early next week!

**Comment by thaisguigon** [comment]
Closing this issue as it has already been addressed.
