### ISSUE TITLE
Empty state V1 for tables

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1991]
## Current behavior

There is no empty state, we display a blank page.

![image](https://github.com/twentyhq/twenty/assets/19412894/82777862-484a-4a34-ae07-0d290a49c3a5)

## Desired behavior

We should add this empty state on both **Standard objects** and **Custom objects**

![image](https://github.com/twentyhq/twenty/assets/19412894/cd4b08e9-3825-4b42-b50d-358333e0ae59)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=12639-96903&mode=design&t=uMog7Tqon1L3Ogmq-4

**Comment by martins5225** [comment]
Hi @Bonapara  can you assign me this issue? would love to work on this

**Comment by Bonapara** [comment]
Hi @martins5225. Just assigned you, thanks a lot! Make sure this can be handle by an outside contributor with @thaisguigon .

**Comment by Bonapara** [comment]
Hi @martins5225, I unassign you unless you still want to address the issue. Let me know!

**Comment by tmahabir** [comment]
Hi @Bonapara! I'm looking for a good first issue to do! Can you assign this issue to me please?
