### ISSUE TITLE
Custom objects shows (detail pages)

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1992]
## Expected behavior

We want custom objects to have a show page similar to standard objects, including the following features:

### Ability to add notes and tasks

It should be possible to add a note and a task on a custom object:

![image](https://github.com/twentyhq/twenty/assets/19412894/cebe92c0-fe14-49e9-99fc-140b10c4440f)

When adding a note or task, it should automatically tag the parent object. We have already implemented this behavior on the people show. For example, when I create a note on a person, we add the corresponding company tag. As a result, the note will appear in both the person's and the company's show.

To achieve this, we should study situations where there is a one-to-many relationship between objects in order to generalize this behavior. We will assess later whether to apply this behavior to one-to-one and many-to-many relationships.

![image](https://github.com/twentyhq/twenty/assets/19412894/102f3b66-423e-4280-b0ad-c8002fb3a9ed)

### Timeline

The behavior of this should be identical to that of standard objects.

**Comment by alfredlouisw8** [comment]
hi can i take this issue?

**Comment by Bonapara** [comment]
Hi @alfredlouisw8 thanks! I think the @CoreTeamTwenty is gonna take this issue, isn't it @charlesBochet?

**Comment by charlesBochet** [comment]
This has been implemented, closing it :)
