### ISSUE TITLE
New object field - Step 2 - Add form

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#2001]
Warning: this issue is part of a series of issues aiming to create the "Object Field Creation flow". This is issue number 6

## Context

See #1767

For this issue:
- Add to the New Field - Step 2 page a "Name and description" section with a title, a description, and a form.
  - Use the `IconPicker` component.
  - Use the `TextInput` component.
  - Use the `Textarea` component from #1910.
  - This section is shared with the Field Edit page (see #1769).
- Add a "Type and values" section with a title, a description and a select.
  - We might need to implement a `SingleSelect` component for the select.
  - The select options are the list of Data Types (see #1815).

## Figma

![Image](https://github.com/twentyhq/twenty/assets/3098428/40df35e8-dcea-4fc0-9f77-93483774b15d)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11459-93766&mode=design&t=xSdrIMXJed2ZTg34-4

### Scenario: Viewing the "Name and description" section

**GIVEN** I am on the New Field - Step 2 page
**THEN** I see a "Name and description" section with a title, a description, and a form
**AND** the form contains:
- an icon picker for the field's icon
- an input for the field's name
- a textarea for the field's description

### Scenario: Viewing the "Type and values" section

**GIVEN** I am on the New Field - Step 2 page
**THEN** I see a "Type and values" section with a title, a description, and a select
**AND** the select's options are a list of data types for the field

### Scenario: Filling the form

**GIVEN** I am on the New Field - Step 2 page
**WHEN** I fill all the required form fields
**THEN** the Save button is enabled

**Comment by Kanav-Arora** [comment]
Hi @thaisguigon 
Can I work on this issue?

**Comment by thaisguigon** [comment]
Hi @Kanav-Arora! Thank you, however this issue has already been addressed by the Core team. You can find issues to contribute to here: https://github.com/twentyhq/twenty/contribute
