### ISSUE TITLE
[Timebox] Add filter and sort on queries for /graphql custom objects

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2002]
## Scope & Context

The new flexible backend allows us to query objects and fields metadata and their data, but we cannot filter or sort at the moment.

## Current behavior

We can query on  /graphql dynamic objects and fields without any parameter.

## Expected behavior

We want to have filter and sort in queries for /graphql.

For this the flexible backend needs to implement this feature.

For the moment we can restrict this to simple field types like text, money and url.

**Comment by charlesBochet** [comment]
Duplicate
