### ISSUE TITLE
Implement Flexible frontend

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2004]
## Scope & Context

The new flexible backend has been released and the foundations have been laid out for CRUDing metadata and custom objects.

## Current behavior

We currently have a generic implementation with the modules : field, data-table, inline-cell, table-cell, views, etc. 

Although we're still using standard static GraphQL queries on known types.

## Expected behavior

We want to create a parallel version of all those modules, by suffixing everything we need with v2, that will only use the new flexible backend.

Once everything will be stable on v2, we'll be able to migrate every standard object to a  custom object and decomission v1 and rename everything afterwards.

The goal of this issue is to go as far as possible in sandbox mode on the v2 of custom objects on the frontend for DataTables and ShowPages mainly, and create other issues along the road, while things become more clear.
```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/2040
- [ ] https://github.com/twentyhq/twenty/issues/2041
- [ ] https://github.com/twentyhq/twenty/issues/2042
- [ ] https://github.com/twentyhq/twenty/issues/2043
- [ ] https://github.com/twentyhq/twenty/issues/2044
- [ ] https://github.com/twentyhq/twenty/issues/2045
- [ ] https://github.com/twentyhq/twenty/issues/2046
- [ ] https://github.com/twentyhq/twenty/issues/2047
```

**Comment by charlesBochet** [comment]
This has been implemented, closing it :)
