### ISSUE TITLE
New object field - Step 2 - Add "Cancel" and "Save" buttons

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#2006]
Warning: this issue is part of a series of issues aiming to create the "Object Field Creation flow". This is issue number 5

## Context

See #1767

For this issue, in the New Field - Step 2 page, add a "Cancel" button that navigates back to the "Object Detail" page, and a disabled "Save" button.

Note that #1809 implements a similar set of buttons, see if we can reuse those (also shared with #1787).

## Figma

![Image](https://github.com/twentyhq/twenty/assets/3098428/dec77f75-c8d0-45ed-9a0b-34a2bde110db)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11459-93766&mode=design&t=xSdrIMXJed2ZTg34-4

## Behavior

**GIVEN** I am on the New Field - Step 2 page
**THEN** I see a "Cancel" button
**AND** I see a disabled "Save" button

**GIVEN** I am on the New Field - Step 2 page
**AND** I click on the "Cancel" button
**THEN** I navigate to the Objects Settings page

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
Can you assign me this request

**Comment by charlesBochet** [comment]
Sure!

**Comment by bosiraphael** [comment]
Hello @Kanav-Arora, you can now work on this issue since it is no longer blocked. You can reuse the SaveAndCancelButtons component in front/src/modules/settings/components/SaveAndCancelButtons/SaveAndCancelButtons.tsx, and see how the component is used in front/src/pages/settings/data-model/SettingsNewObject.tsx. Thank you!

**Comment by Kanav-Arora** [comment]
Hi @bosiraphael 
I'll start working on it 
Thanks for the update

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
Kindly review PR #2092

**Comment by charlesBochet** [comment]
The PR has been merged, thank you!
