### ISSUE TITLE
[Timebox] Object Detail & New Field - Step 1 - Get data from backend

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#2008]
Use the new endpoints to get an object and their fields from backend.

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
Can you assign me this issue? 
I'll start working on it when it gets unblocked

**Comment by charlesBochet** [comment]
@Kanav-Arora we can't assign this issue right now as we are unsure about the technical direction yet. @thaisguigon will take a look tomorrow and likely complete it.

There is an area that has not been covered yet if you are interested working on it: we are missing all the "..." dropdown compared to the figma (https://www.figma.com/proto/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11440-65418&t=LZi3PiqRuyz8MqdT-0&scaling=min-zoom&page-id=5639%3A59008&starting-point-node-id=11440%3A65418) for objects and fields.

It's captured by this issue for objects: https://github.com/twentyhq/twenty/issues/1762 and I am unsure we have an issue for fields but you can find the behavior in the figma

Objects: (3 dots menu here)
<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/a1e520cf-dd25-44c3-a7a6-5622b4adb1ad">

Fields: (3 dots menu here)
<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/d745e6ce-53a7-4d5c-b46c-16823ee05ab5">
