### ISSUE TITLE
Bug: Multiselect opening on notes

### ISSUE THREAD

**Issue by AdityaPimpalkar** [twentyhq/twenty#2015]
## Bug Description

https://github.com/twentyhq/twenty/assets/13139771/31e40b5f-5823-416d-a46b-ab456329ecee

## Expected behaviour

Dropdown should open on only one place at a time

**Comment by MudityaQQ** [comment]
Hi @AdityaPimpalkar,

I've looked into the "Multiselect opening on notes" bug you've reported. I'll be working on addressing this issue. I'll keep you updated on the progress and reach out if I need any further information.

Best regards,
Muditya Raghav

**Comment by charlesBochet** [comment]
Haha, it's a funny bug, good catch!
