### ISSUE TITLE
Page does not exist for a link in README (contributing)

### ISSUE THREAD

**Issue by AkasshShah** [twentyhq/twenty#2024]
## Bug Description

In the README.md (currently) the local env setup points to https://docs.twenty.com/developer/local-setup which currently does not exist
![image](https://github.com/twentyhq/twenty/assets/25800250/7a6851a6-eb5a-4023-a1d9-a47a9a233267)
![image](https://github.com/twentyhq/twenty/assets/25800250/60fa49c3-9733-4b4c-8e2f-0dad7161fd42)

## Expected behavior

I think it can now point to https://docs.twenty.com/contributor/frontend/basics/contributing perhaps.

## Technical inputs

This is not a technical issue.

**Comment by AkasshShah** [comment]
I can create a PR for this, but i want to confirm, is https://docs.twenty.com/contributor/frontend/basics/contributing the right address for this to finally be?

**Comment by encg** [comment]
Might be this: https://docs.twenty.com/contributor/local-setup

**Comment by AkasshShah** [comment]
Closing since https://github.com/twentyhq/twenty/pull/2025 was merged.
