### ISSUE TITLE
feat: I can use graphql to deactivate/soft-delete a metadata object/field

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#2036]
We need to introduce soft-delete concept inside metadata and add deleted_at columns inside object-metadata and field-metadata. 
Then we need a resolver for soft-deletion. 
Since this is a soft-deletion, we should not delete the associated data.

is_active boolean already exists, we now need a custom resolver to activate/deactivate the object or the field

**Comment by shavidze** [comment]
@charlesBochet  Can  I work on it ?

**Comment by Weiko** [comment]
Hi @shavidze, unfortunately this one has already been solved and merged this week. 
Feel free to pick something there https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 🙂
