### ISSUE TITLE
Fix icon for single "New note" "New task" buttons

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2037]
# Definition

Single buttons refer to individual buttons, as opposed to button groups that consist of three buttons placed together.

![Image](https://github.com/twentyhq/twenty/assets/19412894/89daa63b-76c2-4fe2-8feb-111f01b448ff)

![Image](https://github.com/twentyhq/twenty/assets/19412894/56ce3274-a2bd-4ed2-a1a0-8d4f37d075ed)

# Current Behavior

When there is a single button, the icon displays a note or checkmark. 

![Image](https://github.com/twentyhq/twenty/assets/19412894/da01d61a-4b46-49e9-9d44-5b9f05dd6b18)

# Desired behavior

Single buttons for "New note" or "New task" should display a "+" icon:

![Image](https://github.com/twentyhq/twenty/assets/19412894/54970381-32f5-470f-b12e-9fd6358e7681)

The group button should retain the "illustration" icon to avoid having three "+" icons together.

This pertains to the placeholder button in the empty state and the button located at the top right when a task or note already exists.

**Comment by AnuMessi10** [comment]
Hi @Bonapara, I am new to this and would like to contribute, let me know if you can assign this to me, cheers!

**Comment by Bonapara** [comment]
Sure! Thanks a lot @AnuMessi10

**Comment by cricket-lover** [comment]
Hi @Bonapara Can I work on this, If this is not picked yet?

**Comment by Bonapara** [comment]
@cricket-lover, please connect with @AnuMessi10. You may collaborate together

**Comment by cricket-lover** [comment]
@Bonapara Sure, Thanks.

**Comment by AnuMessi10** [comment]
Hi @Bonapara, I have made a fix but someone else who wasn't assigned created a PR which has been merged, I am not sure that is how open source works 😄

**Comment by Bonapara** [comment]
Hi @AnuMessi10 You're right something went wrong here. Will have a look with the tech team. What do you think we should implement to prevent this? A 2 days safe period for "Good first issues"?

**Comment by AnuMessi10** [comment]
Yes, a safe period sounds good, also updating the contributing guidelines wrt raising PRs without prior assignment can be additionally done.
