### ISSUE TITLE
[Timebox] Integrate DataTable and ShowPage fields type (except relations)

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2040]
In this ticket we just want the FieldInput and FieldDisplay to work on DataTable and ShowPage, except for the relation type, which is not yet implemented on flexible backend.

We can just deactivate the edit mode if the type is relation.

Also we can create temporary v2 types like dateV2 in `FieldType`

```[tasklist]
### Tasks
- [x] Text
- [ ] Number
- [ ] Date
- [ ] Boolean
- [ ] Chip
- [ ] Double text
- [ ] Double text chip
- [ ] Email
- [ ] Phone
- [ ] URL
- [ ] Probability
- [ ] Money amount
```

**Comment by charlesBochet** [comment]
This has been implemented, closing it :)
