### ISSUE TITLE
[Timebox] Create v2 of Views and ViewField for flexible backend

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2047]
With the new flexible backend and custom objects, we don't need to have hardcoded FieldDefinition anymore.

In this ticket we need to find everything we need to initialize our views (which should already handle any custom field that has the right type)

And also check that the existing features of Views are working with the new implementation.
```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/2162
- [ ] https://github.com/twentyhq/twenty/issues/2166
- [ ] https://github.com/twentyhq/twenty/issues/2164
- [ ] https://github.com/twentyhq/twenty/issues/2165
- [ ] https://github.com/twentyhq/twenty/issues/2198
- [ ] https://github.com/twentyhq/twenty/issues/2167
- [ ] https://github.com/twentyhq/twenty/issues/2169
```

**Comment by charlesBochet** [comment]
This has been implemented, closing it :)
