### ISSUE TITLE
Custom objects are automatically created during seeding

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#2055]
## Context
We recently introduced a TenantInitialisation service which takes care of creating StandardObjects after workspace creations.
To improve development experience, we need to seed the DB and with that we need to create StandardObjects as well as CustomObjects.

**Comment by shavidze** [comment]
Could you please provide more details to work on?

**Comment by charlesBochet** [comment]
@shavidze we will handle this one internally as it's touching the core of custom objects and the team is currently working on it.

@Weiko could you still provide more details to help everybody getting the direction of this ticket?
