### ISSUE TITLE
See all internal integrations

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2059]
# Scope

Create a new page called "Developers" in the settings. This page will allow users to create and manage their API keys.
The route will be `settings/apis``

# Desired behavior

- This page should utilize the same components as the one used in the Objects settings. 
- For now, all API keys should be indicated as "Internal"
- The owner should feature the API's creator's first name, or "you" if you're the creator.

**OUT OF SCOPE:**
- Do not implement the logo left to the api name (as we don't have it).
- Do not implement the api owner as we don't have it on the backend ==> create a ~~created~~ Expiration at column instead

# Figma

![Image](https://github.com/twentyhq/twenty/assets/19412894/0be35148-5c3c-40e7-b00f-4167958477be)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=12949-98791&mode=design&t=jkTwYBvK9iqKle0h-11

**Comment by Bonapara** [comment]
@martmull Does "Owner" makes sense to you?

**Comment by shavidze** [comment]
Can I take it?

**Comment by martmull** [comment]
Nice to meet you @shavidze don't hesitate to ping me if you need help

**Comment by shavidze** [comment]
@martmull @charlesBochet Thanks guys for your support. I will start working on it.

**Comment by martmull** [comment]
@Bonapara 
- I think you can add expiry information for each api keys
- I would add a Figma view of the form to create a new apiKey with "Name" and "Expiry" parameters (date format)
- I see on the figma that api keys are displayed after they had been registered, we don't store them so it won't be possible for the user to see keys after they had been created
- Then I think a figma view of the screen when an api key has been just been created would be nice (with a warning like 'copy this key, you won't be able to see it again')
- backend don't store logos for now but I can create a ticket for that

**Comment by charlesBochet** [comment]
I have added a OUT OF SCOPE section:

Do not implement the logo left to the api name (as we don't have it).
Do not implement the api owner as we don't have it on the backend ==> create a created at column instead

**Comment by shavidze** [comment]
[__Related PL__](https://github.com/twentyhq/twenty/pull/2071)

**Comment by Bonapara** [comment]
Figma has been updated. (Noticed the font is red when the key is expired)
