### ISSUE TITLE
Create a new API key

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2060]
# Scope & behavior

This page enables users to create a new API key for developing a new internal integration. Its route should be `settings/apis/new` Clicking on "Save" should redirect to the integration detail page.  Clicking on "Cancel" should go back to `settings/apis` without creating the integration.

The options for the expiration enum should be:
- 15 days
- 30 days
- 90 days
- 1 year
- 2 years
- Never

**OUT OF SCOPE:** Do not implement the logo upload for now

# Figma

### First screen: 

![Image](https://github.com/twentyhq/twenty/assets/19412894/a146f388-925a-4651-a324-bf1f30312d6d)

### Second screen:

![Image](https://github.com/twentyhq/twenty/assets/19412894/536d43ac-403f-46be-8191-4e8d1311103e)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=12955-102858&mode=design&t=jkTwYBvK9iqKle0h-11

**Comment by Bonapara** [comment]
Figma has been updated. Please use the Figma prototype by clicking "play."

**Comment by avijeetpandey** [comment]
@Bonapara I would like to work on this could you please assign this to me , thanks

**Comment by avijeetpandey** [comment]
I have setup the project and ran it successfully on the local machine.

**Comment by Bonapara** [comment]
Yes @avijeetpandey, thanks!

**Comment by avijeetpandey** [comment]
Thanks will submit the PR as soon as possible

**Comment by martmull** [comment]
Hello @avijeetpandey, don't hesitate to ping me when you submit your PR

**Comment by avijeetpandey** [comment]
sure , have started understanding the codebase, will ping if i need some help thanks @martmull

**Comment by martmull** [comment]
Hey @avijeetpandey this issue become pretty urgent now so i will take it

**Comment by avijeetpandey** [comment]
apologies @martmull for the delay.

**Comment by martmull** [comment]
No problem @avijeetpandey
