### ISSUE TITLE
View / edit an API key

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2062]
# Desired behavior

- The route of the page should be `settings/apis/API_NAME`
- Copying the key will trigger a green alert message saying, "The key has been copied to the clipboard." (see WorkspaceMember InviteLink for an example)

**OUT OF SCOPE:** Do not implement the logo upload section.

# Figma 

https://github.com/twentyhq/twenty/assets/19412894/b33d64b7-a544-467e-8755-680e1b801168

![Image](https://github.com/twentyhq/twenty/assets/19412894/7f2542d9-5923-440c-89a6-9209f827ad1e)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=12955-101202&mode=design&t=jkTwYBvK9iqKle0h-11

**Comment by mrkirthi-24** [comment]
Hi @Bonapara I would like to work on this issue.

**Comment by Bonapara** [comment]
Hi @mrkirthi-24, Yes for sure. Many thanks

**Comment by b9aurav** [comment]
@Bonapara I gave it a try and my front-end is ready, I just need to generate api key but i don't know how to do it. Is there any server-side function or do i need to write my own function?

https://github.com/twentyhq/twenty/assets/79157299/b335fa1f-b0fc-43be-819e-a57beef697b7

**Comment by martmull** [comment]
@b9aurav the ticket to generate an api key is not done yet. You can generate one by calling the api route `createOneApiKey`
