### ISSUE TITLE
Ability to reorder objects by drag & drop

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2066]
# Current behavior

We cannot reorder the standard & custom objects in the navigation bar.

![Image](https://github.com/twentyhq/twenty/assets/19412894/9bd3a182-df0a-40e0-b565-c4d1d1b6d5c8)

# Desired behavior

We should have the ability to rearrange the navbar items (Similar to notion.so)

https://github.com/twentyhq/twenty/assets/19412894/3dff24b1-c89d-4a1d-b68e-00e4cdeeeb1d

link to #1930

**Comment by charlesBochet** [comment]
Hold a bit on this one, we are merging a PR regarding the ability to re-order favorites https://github.com/twentyhq/twenty/pull/1930 . This one should be very similar and be built with same pattern

**Comment by abhithory** [comment]
@charlesBochet @Bonapara , re-order favorites is done. Can I now work on this?

**Comment by charlesBochet** [comment]
Yes, We just need to clarify the data model on backend side before working on this.
I feel we should introduce a MenuItem model (very similar to favorite) that would point to the object.
So: id (uuid), created_at, updated_at, deleted_at, objectId, position

**Comment by abhithory** [comment]
Ok @charlesBochet, I can do this.  So, is this final or is there something left to do before starting on this??
If everything   else is ready then i am ready to do this.

Please assign me.

**Comment by charlesBochet** [comment]
@FelixMalfait @Bonapara does it look good to you?

**Comment by Bonapara** [comment]
Good for me. However, I haven't tested favorites reordering yet.

**Comment by FelixMalfait** [comment]
Good for me too!

**Comment by charlesBochet** [comment]
@abhithory Green light!

**Comment by abhithory** [comment]
@charlesBochet thanks

**Comment by Bonapara** [comment]
Closing because currently, we don't want users (as opposed to admins in the future) to have the ability to reorder standards and customs objects.
