### ISSUE TITLE
Bug: scrolling down on a companies table causes some erratic behavior

### ISSUE THREAD

**Issue by khakimov** [twentyhq/twenty#2076]
### Bug Description

when scrolling down to load more companies:

https://github.com/twentyhq/twenty/assets/396223/3bd4f18c-b134-48d7-b255-27d75a4863d5

## Expected behavior

- handle 500 error from [favicon](https://favicon.twenty.com/) to show default favicon and avoid requesting in the loop
- check what makes the scroll goes up and down

## Technical inputs

not sure if its related but if https://favicon.twenty.com returns 500 its goes in the loop spamming with requests favicon server.  

<img width="1397" alt="image" src="https://github.com/twentyhq/twenty/assets/396223/6a0e88df-0bc0-42ae-8b95-55153f1d91fc">

https://github.com/twentyhq/twenty/blob/a6542719df220a4f60990abfb3c8bdb21272264e/front/src/modules/users/components/Avatar.tsx#L102-L113

**Comment by FelixMalfait** [comment]
Thanks! This seems to be fixed! Some maybe-related issues are still open around favicon and board rerendering, should be solved next week
