### ISSUE TITLE
Pre-build Docker Images (front + server) and Push to GitHub Packages

### ISSUE THREAD

**Issue by khakimov** [twentyhq/twenty#2099]
## Scope & Context

- **Pre-building Docker Images**: We need to set up a process to pre-build Docker images for both the front and server components. 
- **Pushing to GitHub Packages**: After the Docker images are built, they should be pushed to a Docker registry.

Currently, our deployment process involves building **twenty** directly on the servers. This process can be time-consuming. 

By pre-building Docker images and pushing them to a Docker registry, we can make our deployment process faster and more consistent. The servers can simply pull the pre-built images and run them, without needing to build the application themselves. 

## Technical inputs

1. Dockerfiles. 
2. Build Process. Set up a process to automatically build Docker images for each release.
3. Docker Registry. Set up an account on the chosen registry and create repositories for the front-end and server images.
4. Push to Registry. Configure the CI service to push the built Docker images to the Docker registry.
5. Deployment Process: Update the deployment process to pull the Docker images from the Docker registry and run them, instead of building the application on the servers

**Comment by charlesBochet** [comment]
I have taken care of 3 already: created the organization and twenty-front and twenty-server repository.
We are submitting an application to Docker Verified program to ease the download of twenty docker images (otherwise I believe users have to log in into Dockerhub)

**Comment by khakimov** [comment]
lets try in two step, first step will try to do it manually and when everything works manually, next step will be to automate it using **Actions** and build and push images for each release. 

for server:

docker build -f ./infra/prod/server/Dockerfile -t twenty-server
docker tag twenty-server:latest twentycrm/twenty-server
docker login
docker push twentycrm/twenty-server:latest

for front:

docker build -f ./infra/prod/front/Dockerfile -t twenty-front
docker tag twenty-front:latest twentycrm/twenty-front
docker login
docker push twentycrm/twenty-front:latest

I added to each Dockerfile, which could be useful if will decide to host and use Packages on github

```
LABEL org.opencontainers.image.source=https://github.com/twentyhq/twenty
LABEL org.opencontainers.image.description="This image provides a consistent and reproducible environment for the backend, ensuring it deploys faster and runs the same way regardless of the deployment environment."
```

lets push the images and I will test deployment on render using them.

**Comment by charlesBochet** [comment]
I've built images, here are the commands I have used:
docker login
docker build -f ./infra/prod/server/Dockerfile -t twentycrm/twenty-server:0.1.5 -t twentycrm/twenty-server:latest .
docker push  twentycrm/twenty-server

docker login
docker build -f ./infra/prod/front/Dockerfile -t twentycrm/twenty-front:0.1.5 -t twentycrm/twenty-front:latest .
docker push  twentycrm/twenty-front

I have pushed them, could you try deploying on render using them?

**Comment by khakimov** [comment]
> I have pushed them, could you try deploying on render using them?

oops, render wants linux/amd64 images:

docker buildx build --platform linux/amd64 -f ./infra/prod/server/Dockerfile -t twentycrm/twenty-server:0.1.5 -t twentycrm/twenty-server:latest .

docker buildx build --platform linux/amd64 -f ./infra/prod/front/Dockerfile -t twentycrm/twenty-front:0.1.5 -t twentycrm/twenty-front:latest .

ps: I have already tested on my images and its... fast! deploy takes 2 minutes and only because of postgres is building :)

**Comment by khakimov** [comment]
front is working, setting the enviroment at deployment and looks good 👍

The ./server has been updated. The /app/server kept in the image to enable the execution of yarn prisma:migrate && yarn database:setup during deployment.

For improved readability, created ./infra/prod/server/entrypoint.sh, and the Dockerfile has been modified to use it at ENTRYPOINT ["/entrypoint.sh"]

**Comment by charlesBochet** [comment]
it's a good idea to introduce an entrypoint.sh. I'm puzzled that it is trying to setup + migrate the DB, i feel this should not be part of the entrypoint. But for now that's fine

**Comment by Ethan-Hou1117** [comment]
@khakimov Trying to implement the updated dockerfiles on render, but running into some issues with yarn on amd64. Did you run into this issue as well or are aware of any workaround? Thanks.

Ethan

**Comment by khakimov** [comment]
> @khakimov Trying to implement the updated dockerfiles on render, but running into some issues with yarn on amd64. Did you run into this issue as well or are aware of any workaround? Thanks.

Hey Ethan, could you show what kind of issue?

I remember building docker images required platform specs like this.

```
docker buildx build --platform linux/amd64 ...
```
