### ISSUE TITLE
Add V2 objects initialisation using TenantInitialisation service

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#2109]
## Scope & Context

More context in this PR https://github.com/twentyhq/twenty/issues/2035
We did a first version of an initialisation of our standard objects inside a new TenantInitialisation service.
The idea was to setup our workspace as we normally do then now do a few preparations so the new user can fetch standard objects and create new custom objects. Which means populating the metadata schema (representation of our objects, used by our dynamic graphql resolver) and the workspace schema (containing the actual data of each object). The service has the responsibility to:
- Create a schema dedicated to the workspace
- Store the connection info (the newly created schema) into metadata.datasource-metadata for the new workspace
- Insert all the standard migrations from our code (src/metadata/tenant-initialisation/standard-object/*.json) needed (Company, People, etc) into metadata.object-metadata, metadata.field-metdata tables
- Insert into metadata.tenant_migrations table all the existing migrations (src/metdata/tenant-migration/migrations) and execute them.

## Current behavior

Standard objects are not created automatically when a workspace is created. Except for CompanyV2

## Expected behavior

We want to have all our objects populated the same way CompanyV2 is

## Technical inputs

Use TenantInitialisation service and add metadata representation of each objects inside src/metadata/tenant-initialisation/standard-object/ and update src/metadata/tenant-initialisation/standard-object/standard-object-metadata.ts
Note: To avoid conflict in the generated graphql schema, nameSingular and namePlural should have V2 as a suffix for now.

Create a new migration inside src/metdata/tenant-migration/migrations, TIMESTAMP-migrationName.ts, that will return a TenantMigrationTableAction[] and update src/metdata/tenant-migration/standard-migrations.ts accordingly

Note: A few things are not implemented yet, for example the "relation" type, which means the MigrationExecutor won't know it needs to create foreign keys

**Comment by charlesBochet** [comment]
Closing this issue as this has been completed
