### ISSUE TITLE
Rename pipelines to opportunities

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2112]
## Context
Pipeline was initially thought as a generic concept to represent any process (e.g. hiring pipeline, fundraising pipeline, etc.)
But we ended up adding fields that are clearly linked to the business concept of an opportunity directly on the table (e.g. amount, close date).
Before we release the official API next month, we need to commit to names that we're not going to change.

## Discussion
I suggest we rename:
- `pipeline_progresses` to `opportunities`
- `pipelines` to `opportunity_types`

As for `pipeline_stages` it's trickier. Because we might want to keep this concept of "ordered enum" or "kanban stages" for other objects (why not let user add a kanban process with a custom column on people view?). So the current name isn't that bad. The only condition would be to drop the "type" column (won/close) which relates to the business concept of an opportunity and not a generic kanban concept. This column isn't used so we're not losing anything by dropping it.
The options are:
(1) Rename to `opportunities_stages`, keep type column
(2) Drop type column, keep name
(3) Drop type column, change to a different name like `kanban_stages` or `ordered_options`

## Decision
I'm in favor of going with (1) for now. It makes sense to have a standard object for that because type=won/lost can be translated into UI-specific behavior (e.g. glitter when switching step, stats of % won, etc.)
We can always refactor `opportunity_stages` to fit into the generic options framework when we introduce it

**Comment by FelixMalfait** [comment]
@charlesBochet fyi I think it would be good to prioritize this before we release the API

**Comment by charlesBochet** [comment]
@FelixMalfait I was thinking of completely getting rid of pipeline_stages as it could be replaced by a grouping by an enum field of the opportunity (or we could go further and group by date, assignee...).

Regarding Pipeline, I am unsure of the product. We can either:
-  see it as a type of View (like a table, it's just a Kanban), in this case we don't need it at all and everything can be captured by the View 
- or we can keep it to enable to "classify" opportunities in different pipelines (let's imagine we have two different operational team that don't want their opportunities to be mixed). In this case, I would keep it. 

As we get rid of pipeline_stages, we still need to think about what it need to change the color, or the stage name : it could be overrides of the enum at pipeline level, it could also be stored in the enum itself (metadata). It depends if we want these customization (color, name) to be shared cross pipelines

**Comment by Bonapara** [comment]
@FelixMalfait it reminds me of Notion "Status" (see below) where you can group several "tags" under a category. 

![image](https://github.com/twentyhq/twenty/assets/19412894/f88b3228-981c-41fe-8b29-3a3a655e0fbd)

We could allow users to establish pipelines using either enums or kanban steps field types. (But alternatively, we might consider offering pipeline creation exclusively with kanban steps?) I'm wondering if we could allow people to use the "kanban steps" as a generic field type that associates "tags" with "tag groups." For opportunities, they could be "Win/Lost," but for other kanban boards, they could be something else such as "To Do," "In Progress," and "Done."

If so we could keep it as "kanban_steps" and not "opportunity_steps"?

**Comment by Bonapara** [comment]
We could consider adding an option called "No Steps Group" or making no steps groups the default, with the ability to activate the option as needed.

**Comment by charlesBochet** [comment]
@FelixMalfait Ok, interesting! I have looked at the Salesforce standard object list and they indeed have an OpportunityStage (but not Pipeline equivalent?). I think we should take a product decision here, either we say that opportunity stages, pipelines are standard objects or we say it is just a way of viewing the opportunities (we could also imagine viewing the opportunities as a table).

Personally, in term of vision and flexiblity I think the best of two world would be:
- indeed keep opportunityStage and pipeline
- have the kanban board be a type of view (like table). So opportunity page default view will be a **Kanban View** on **Opportunity standard object** grouped by **opportunityStage** (which is a relation of opportunity, so actually grouped by OpportunityStageId but display OppotunityStage->name).

I think uncoupling the View part which is flexibile from the opportunity + pipeline + stage which is about the data will give us the flexibility on long term.
Regarding short term, we can indeed rename to opportunity and opportunity stage and keep for later abstracting a bit more Kanban View.
Wdyt?

**Comment by FelixMalfait** [comment]
@charlesBochet aligned with what you said above. 

@Bonapara yes good point for introducing categories.

So we agree that:
- we need a robust way for users to create a custom field with selectable options. Those options can eventually be _categorized_, _colored_ and _ordered_.
- opportunity is a standard object, so it makes sense to have something opinionated (won, lost, etc.). But as we introduce a global patterns we will refactor it to make sure it leverages the common framework as much as possible

**Comment by Bonapara** [comment]
Why keeping "opportunityStages" rather than a generic "progress" field type? Why not having a generic "progress" field type from day 1 layer under both "opportunities" and other tables?

Later, the standard fields could "lock" some properties of generic fields type. So for instance for opportunity "progress" would lock the groups to "Open / Won / Lost" 

Is it possible to distinguish between generic field types (which allow you to create custom fields) and standard fields that restrict certain properties of generic field types?

**Comment by FelixMalfait** [comment]
@Bonapara OpportunityStage is a standard object, not a column on a standard object, because in SFDC -and probably in our case too- it has several fields (type, probability, etc.) therefore it needs its own object.
Post refactoring the opportunity stage could eventually leverage the "categorized, colored, ordered, selectable option" field type, to remove columns such as color and position from its table and only keep the business-related column (type, probability, etc.).
I think we should be careful about the metadata framework. Introducing a field type is a bigger decision than introducing a column on a standard object. Usually field types are relatively low-level. I'm not saying introducing "progress" is a bad decision, but introducing something higher level like this is a big choice that we should definitely not tackle as part of this issue which was meant to be a quick change to unblock the API release.

**Comment by Bonapara** [comment]
Do we really need an OpportunitStage standard object?

I noticed Salesforce's approach. But perhaps "Progress %" could be an automated feature instead of a column in the OpportunitStage object. Currently, `pipeline_progress` holds the "probability" value, not `pipelines_stages`. We could automate the updating of the probability value when the card is moved to a different column.

Do you believe that "Opportunities" can hold a wealth of information, and that automations would be an interesting solution for maintaining universal "Progress" object?

**Comment by FelixMalfait** [comment]
@Bonapara I'm 100% convinced `progress` as a standard object is a bad idea. Standard objects should represent business concepts, meta data / field types should represent abstract concepts. Introducing something in the middle is wrong imo.

> But perhaps "Progress %" could be an automated feature instead of a column in the OpportunitStage object. Currently, pipeline_progress holds the "probability" value, not pipelines_stages. We could automate the updating of the probability value when the card is moved to a different column.
That's why you need pipeline stage. If you want to automate, you need a table to store the default value, that table is OpportunityStage.

If we didn't have it, I would probably not advocate for creating it now. But since we have it, and we'll likely have it long-term, then let's keep it. The goal of this issue is to move forward with the API. We can refactor step-by-step. We will create the "selectable colored ordered categorized options" field type next. If we need to create a new progress type that derives from that field type then we will, and eventually refactor.

**Comment by charlesBochet** [comment]
Closing this issue as this has been implemented!
