### ISSUE TITLE
DataTable '+' button dropdown positioning glitch

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#2126]
## Bug Description

On Table pages (ex: /companies), the "+" button dropdown is badly positionned.
<img width="325" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/0eca7e30-2d96-4cc5-893c-11c7e9b1aba6">

## Expected behavior

It should be floating below the "+" button and aligned right on the "+" button.

## Technical inputs

Refactor the plus button to use DropdownMenu (specifying clickable component and dropdown component). A good example is `SettingsObjectDisabledMenuDropDown` component.

**Comment by rishabh1S** [comment]
Hi @charlesBochet , I would like to work on this.

**Comment by charlesBochet** [comment]
@rishabh1S sure! Thank you :)
