### ISSUE TITLE
DataTable column head menu is badly positioned

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#2127]
## Bug Description

On Table views (ex: /companies), if you click on a column head, a dropdown is appearing to move or hide the column. It's not correctly positioned:
<img width="611" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/54bc3610-5069-4b70-bac9-7b77cbe08bfb">

## Expected behavior

It should be aligned on the left of the column and align on the bottom of the column
<img width="611" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/a4d6e822-fc54-4401-bdbb-09f58148604d">

## Technical inputs

You can plan with Dropdown Menu "dropdownPlacement" and "offset" props

**Comment by ttlpta** [comment]
@charlesBochet Pls help me review this PR https://github.com/twentyhq/twenty/pull/2135
