### ISSUE TITLE
In Settings > Data Model, the page glitches while loading the top banner

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#2129]
## Bug Description

On `/settings/objects`, we are displaying a top banner. While this image is loading, its container height is 0. Once loaded, the container takes the height of the image. This makes the page layout glitch a bit.

## Expected behavior

It should not glitch.

## Technical inputs

We would like to apply a min-height to the container so it keeps the same height while the image is loading

**Comment by mrkirthi-24** [comment]
hey @charlesBochet I would like to work on this

**Comment by charlesBochet** [comment]
Sure :) Thanks!
