### ISSUE TITLE
On Settings > Member page, if a member has a long name, it causes a text overflow

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#2130]
## Bug Description

On /settings/workspace-members, if a member name is very long, it is overflowing its container.
<img width="930" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/1451703f-c995-4c2e-9a95-f500e9fe61db">

## Expected behavior

In case of long names, the name should be truncated with ellipsis.

## Technical inputs

Ideal would be to use OverflowingTextWithTooltip component

**Comment by mrkirthi-24** [comment]
Hi @charlesBochet I would like to take this issue

**Comment by Jat1nSood** [comment]
hi @charlesBochet I would like to work on this

**Comment by charlesBochet** [comment]
Go ahead @Jat1nSood! Thank you :)

**Comment by ttlpta** [comment]
![image](https://github.com/twentyhq/twenty/assets/9917124/4402adcc-fe02-437d-af55-c2c09aceab45)
It looks fine at my local.

**Comment by IbrahimBagalwa** [comment]
> ![image](https://user-images.githubusercontent.com/9917124/276819514-4402adcc-fe02-437d-af55-c2c09aceab45.png) It looks fine at my local.

Hello @ttlpta, I noticed that there's good progress on your side. Have you already submitted a pull request for it? If not, I'd be interested in working on it, so please let me know if you haven't started yet. Thank you!

**Comment by ttlpta** [comment]
@IbrahimBagalwa No, I mean I can not reproduce this issue at my local.

**Comment by ttlpta** [comment]
Thank @charlesBochet , I can reproduce it now. This is PR to fix it. pls help me review it.
![image](https://github.com/twentyhq/twenty/assets/9917124/31cb5b20-e860-425f-a07d-a4d7ec267337)

**Comment by IbrahimBagalwa** [comment]
@ttlpta, @charlesBochet thanks, let me try and let you know

**Comment by ttlpta** [comment]
Hi @IbrahimBagalwa , we comment nearly the same time. I can reproduce this, and created PR for it. Pls hele me review it https://github.com/twentyhq/twenty/pull/2192

**Comment by IbrahimBagalwa** [comment]
Hi @ttlpta, Wow, you did a great job on implementing the feature. It looks good to me.💯
