### ISSUE TITLE
feature: Add comments count on notes

### ISSUE THREAD

**Issue by AdityaPimpalkar** [twentyhq/twenty#2133]
## Scope & Context

Person and Company notes section

## Current behavior

Currently we have no way of knowing if anyone has left comments on a note until you open it

https://github.com/twentyhq/twenty/assets/13139771/3a434114-f7a8-4f4e-96f5-8bfdfcb67fe2

## Expected behavior

Perhaps a message icon with the number to its right (which will be number of comments)  on the bottom right corner of notes will be helpful

**Comment by mrkirthi-24** [comment]
Hey let me know if I can work on this issue

**Comment by Vvvv77777** [comment]
If you haven't solved it yet, can I take this issue?

**Comment by FelixMalfait** [comment]
Yes good point @AdityaPimpalkar! 
@mrkirthi-24 @Vvvv77777 we don't have any design yet for the solution. 
CC @Bonapara

**Comment by codergirl2023** [comment]
Hi @FelixMalfait,

 I've made some enhancements to the interface to improve the user experience. You can now see a comments icon, similar to what you see for tasks, when someone adds comments to a task. I've also included a count to the right in the footer, making it easy to keep track of the comments.

Take a look at how it looks in the screenshot below:
![Screenshot](https://github.com/twentyhq/twenty/assets/123604478/d7d44459-5ec0-4711-a18d-0101c19fdb12)


Looking forward to your feedback!

**Comment by FelixMalfait** [comment]
Thanks a lot @codergirl2023! Could you please stick the icon + count on the bottom right? make sure the padding/margin looks nice and symetric to the left side. Also increase distance between icon and comment count to make sure it's consistent with the rest of the app (seems a bit close). cc @Bonapara 

Could you please also add this comment count to the card which is visible in the timeline?

Related: https://github.com/twentyhq/twenty/issues/1086 which will help improve the display when there are many relations (but Charles will work on this)

**Comment by codergirl2023** [comment]
@FelixMalfait sure I will make the changes and raise the PR.

**Comment by codergirl2023** [comment]
Raised PR https://github.com/codergirl2023/twenty/commit/e394395e851276626c34074fdbf161152426cb21
![Screenshot from 2023-10-22 09-55-40](https://github.com/twentyhq/twenty/assets/123604478/202beffe-de7c-4906-a5fd-c5155f8c3eb7)

**Comment by codergirl2023** [comment]
@FelixMalfait I've made changes to include no of comments in Timeline section also. Please give feedback
![Screenshot from 2023-10-22 13-09-20](https://github.com/twentyhq/twenty/assets/123604478/09362aef-22ea-46a6-89b5-460d40d97964)

**Comment by FelixMalfait** [comment]
Oh thanks @codergirl2023 that looks nice! Could you please also align it on the right for the timeline card?

**Comment by codergirl2023** [comment]
sure

**Comment by codergirl2023** [comment]
@FelixMalfait Raised PR to add comment icon and count to Timeline card https://github.com/twentyhq/twenty/pull/2205

**Comment by charlesBochet** [comment]
@codergirl2023 Thank you, I've added comments on the PR

**Comment by codergirl2023** [comment]
@charlesBochet I've made necessary changes as suggested. Please review https://github.com/twentyhq/twenty/pull/2205

**Comment by codergirl2023** [comment]
@charlesBochet Please review https://github.com/twentyhq/twenty/pull/2205
