### ISSUE TITLE
[Timebox] feat: support relation type for custom/standard objects

### ISSUE THREAD

**Issue by magrinj** [twentyhq/twenty#2143]
## Scope & Context

With our ongoing efforts to incorporate custom objects and custom fields into "twenty", we've already achieved the capability for users within a workspace to create custom objects metadata, query the custom objects, and create them.
Now we want to implement the `relation` between custom and standard objects.

## Current behavior

Relation are actually not supported.

## Expected behavior

<img width="521" alt="Screenshot 2023-10-20 at 11 04 39 AM" src="https://github.com/twentyhq/twenty/assets/3551795/e34d9341-cf57-4f4a-b3c8-50f880b784f5">

When a user create fields for a custom object, this one should be able to create field of type `relation`.
This kind of field allow to create a relation of multiple type: `one-to-one` or `one-to-many`.

To make this work the generate `graphQL` schema should be able to add relation inside `ObjectType`.

## Technical inputs

- Create `ObjectType` based on type `relation` inside `FieldMetadata`
- Add the relations to the `ObjectType`

**Comment by FelixMalfait** [comment]
Done!
