### ISSUE TITLE
Object Detail - Add "About" section dropdown

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#2148]
## Context

See #1765 

For this issue:
- In the "Object Detail" page, open a dropdown when the "three dots" icon button is clicked.
- Add 2 menu items to the dropdown: "Edit" and "Disable"
- Clicking on the "Edit" item navigates to the "Object Edit" page
- Clicking on the "Disable" item disables the object (use `useUpdateOneMetadataObject` to set the object's `isActive` property to `false`) and navigates to the "Object Settings" page.

## Figma

![Image](https://github.com/twentyhq/twenty/assets/3098428/90bdcb43-3b68-4930-a35a-40e1c82fe399)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11489%3A96093&mode=design&t=LrzAJ8APKvOBTM9h-1

## Behavior

**GIVEN** I am on the "Object Detail" page
**WHEN** I open the "About" section dropdown
**AND** I click on the "Edit" menu item
**THEN** I navigate to the "Object Edit" page

**GIVEN** I am on the "Object Detail" page
**WHEN** I open the "About" section dropdown
**AND** I click on the "Disable" menu item
**THEN** the active object becomes disabled
**AND** I navigate to the "Object Settings" page

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
Can I work on this issue?
