### ISSUE TITLE
Kanban compact view

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2149]
## Scope & Context

We aim to simplify navigation in opportunities with numerous cards.

## Expected behavior

When clicking on the Opportunities `options` menu, a new "Compact view" menu item should be displayed:

<img width="223" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/03f52b7d-d966-47be-8d9b-d053f8d7ff60">

The compact view should only display the card name. Make sure top & bottom borders are the same:

<img width="1281" alt="Screenshot 2023-10-20 at 11 26 18" src="https://github.com/twentyhq/twenty/assets/19412894/7854163b-665f-4568-a3a8-52839b3534d8">

When Hovering a card, an eye `button icon` should be displayed. **Clicking on it** should extend the card. Clicking anywhere else on the card should keep the normal behavior of the card. Make sure, the eye `button icon` is always visible, even when the card title is too long. In that case, we should crop the card title to have the space to display the eye `icon button` next to the `checkbox`. 

https://github.com/twentyhq/twenty/assets/19412894/338169e5-c5cb-4874-9f60-3d918f232d9c

When the mouse leaves the card, the card should collapse again:

https://github.com/twentyhq/twenty/assets/19412894/55d7fa57-95e1-47dc-a9a4-a2a60fe43277

## Figma

**Use the prototype!**

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=8283-85440&mode=design&t=wWftMO92NToto67x-4

**Comment by mrkirthi-24** [comment]
@Bonapara I would like to work on this issue

**Comment by thaisguigon** [comment]
@mrkirthi-24 I assigned you to this issue, thank you!

**Comment by abhithory** [comment]
Hello @thaisguigon @Bonapara , I think this is same as #1259 . And i was working on that and Created A PR. Please check #2182

**Comment by mrkirthi-24** [comment]
Hey @Bonapara I think this issue is resolved already

**Comment by charlesBochet** [comment]
This has been implemented, closing it :)
