### ISSUE TITLE
New Object - Create Custom object

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#2155]
## Context

See #1764 

For this issue: in the "New Object" page, when the "Custom" tab is selected:
- Clicking on the "Save" button creates a new custom object and navigates back to the "Object Settings" page.
- Use the `useCreateOneMetadataObject` hook.

## Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11471%3A94401&mode=design&t=LrzAJ8APKvOBTM9h-1

## Behavior

**GIVEN** I am on the "New Object" page
**WHEN** I select the "Custom" tab
**AND** I fill the required "Custom" form fields
**AND** I click on the "Save" button
**THEN** a custom object is created
**AND** I navigate to the "Object Settings" page

**Comment by magrinj** [comment]
@thaisguigon For name -> we must match this regex (![0-9]...[a-zA-Z0-9]+)

**Comment by thaisguigon** [comment]
@magrinj I used `/^[a-zA-Z][a-zA-Z0-9 ]*$/` for the label, and converted it to PascalCase for the name. With `^[^0-9]` the first character could be a special character (for instance `*`), we might want to avoid that?

**Comment by magrinj** [comment]
@thaisguigon Oh yes you're right, my bad !
I wrote it really fast without really testing it sorry
