### ISSUE TITLE
Frontend development server is slow

### ISSUE THREAD

**Issue by u5r0** [twentyhq/twenty#2156]
## Scope & Context

I'm experiencing a hard time with server reload on the current setup. Frontend developement requires fast refresh because of many modifications you do per minute.

## Technical inputs

If there's no work around, would you accept a PR for a move from craco/webpack to vite?

**Comment by charlesBochet** [comment]
hi @u5r0, I would be interested into investigating it. What configuration do you have?
Why not!

**Comment by ArijitCloud** [comment]
Good idea! I was trying to enable HMR with craco and vanilla webpack configuration last week and was failing miserably 😄

**Comment by PentesterPriyanshu** [comment]
yes it is very slow taking more time to open

**Comment by charlesBochet** [comment]
What is your configuration? Is it only the first time build that is taking time?

None of us have experienced slow build internally but we all have similar configuration (Mac M2 or M1)

**Comment by charlesBochet** [comment]
Anyway, if there is a way to improve developer experience there, we should invest into it :)

**Comment by u5r0** [comment]
Is there a way for current setup to separate typechecking on its own script?
```json
"scripts": {

}
```

**Comment by charlesBochet** [comment]
Why are we closing it @u5r0? :)

**Comment by charlesBochet** [comment]
What configuration do you have? And do you have experience with setting up vite for react projects?

**Comment by u5r0** [comment]
I don't have an existing config, tinkering is the plan. I've implemented projects in Vite, but haven't migrated from CRA. Twenty's codebase isn't that large just yet, and thought I'd give it a shot. 

This is an [initial setup](https://github.com/u5r0/twenty/commit/f1bf9713b86e5c9dc0c36eb2cdb7b06a9f1042b6), the vite server started but couldn't handle `/companies` after sign-in and crashed with this [recoil error](https://github.com/facebookexperimental/Recoil/issues/1994). Next step is setting up a testing environment with jest/vitest, whatever works

**Comment by ArijitCloud** [comment]
I did a setup jest few days back with vite, was a bit pain. Probably vitest would be easier to get started, I also have the Jest and RTL combination with Vite running, but it's not a big repo.

**Comment by u5r0** [comment]
I work on Linux and I ran into [couple of issues](https://github.com/u5r0/err.log/blob/main/vite.md), plus the mentioned recoil issue. I haven't touched the codebase since, I've been exploring other Vite react projects: [unleash](https://github.com/Unleash/unleash/blob/main/frontend/vite.config.ts), [oxide-console](https://github.com/oxidecomputer/console/blob/main/vite.config.ts) and [saleor-dashboard](https://github.com/saleor/saleor-dashboard/blob/main/vite.config.js) but I'm not that immersed into the react toolchain to figure all things on my own. I'll rebase and take a look.

**Comment by u5r0** [comment]
@charlesBochet Hey, this's a working environment https://github.com/u5r0/twenty/tree/vite4/vitro
Run `yarn dev` against the server
This's just `/src` from yesterday's last commit, no eslint, no test, no storybook..

**Comment by charlesBochet** [comment]
Thanks to @u5r0, twenty-front has just migrated to vite. It's indeed faster and less resource intensive! 
We have also migrated to yarn4
Closing this issue!
