### ISSUE TITLE
Object Field Edit - Create page

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#2159]
Warning: this issue is part of a series of issues aiming to create the "Object Field Edition flow". This is issue number 1.

## Context

See #1769 

For this issue:
- Create an empty page with the route: `/settings/objects/[PLURAL_OBJECT_NAME]/[FIELD_NAME]`.
- Use the breadcrumb component from #1814.

## Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11383%3A58516&mode=design&t=EynOEhEsP06qxkYt-1

## Behavior

**GIVEN** I am on an Object Field Edit page
**THEN** I see a breadcrumb

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet  
Can I work on this issue?

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
Please respond

**Comment by thaisguigon** [comment]
Hi @Kanav-Arora, I assigned you to this issue

**Comment by Kanav-Arora** [comment]
Thanks
I'll start working on it

**Comment by Kanav-Arora** [comment]
Hi @thaisguigon 
I am working on updated branch but the UI is not as per the Figma shared. Could you please help with the path of file to be added and naming.
<img width="1440" alt="Screenshot 2023-10-24 at 2 47 35 PM" src="https://github.com/twentyhq/twenty/assets/62852363/7009c346-4977-4f58-b573-c7a4d53f76f4">

**Comment by charlesBochet** [comment]
@Kanav-Arora there are env variables to set in your server/.env (you can take a look at server/.env.example). Then you'll need to restart your server!
IS_DATA_MODEL_SETTINGS_ENABLED=true

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
I have raised a PR with the required changes
