### ISSUE TITLE
Views: Update data model to work with new flexible schema

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#2162]
Update backend schema to support custom and standard objects
- ViewField (-key, +fieldId, -name, index ->position) (tag key and name as deprecated but don't delete them)
- ViewFilter (-key, -name, +fieldId)
- ViewSort (-key, -name, +fieldId)

**Comment by codergirl2023** [comment]
@charlesBochet i would like to work on this

**Comment by charlesBochet** [comment]
@codergirl2023 This one is needed for Thursday. We were planning to work on it internally. If you can get it done by Thursday why not :) otherwise it would be better to work on less time sensitive issues!

**Comment by charlesBochet** [comment]
This has been implemented, closing it :)
