### ISSUE TITLE
Isolate Filter in its own module

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#2164]
We want to decouple the ViewBar and the Filter and Sort components, so that these components can be used outside of the ViewBar.
Currently, the filter components live in front/src/modules/ui/data/view-bar/components.

We want to create a filter module which will contain all the filter components:
- AddFilterFromDetailsButton.tsx
- FilterDropdownButton.tsx
- FilterDropdownDateSearchInput.tsx
- FilterDropdownEntitySearchInput.tsx
- FilterDropdownEntitySearchSelect.tsx
- FilterDropdownEntitySelect.tsx
- FilterDropdownFilterSelect.tsx
- FilterDropdownNumberSearchInput.tsx
- GenericEntityFilterChip.tsx
- FilterDropdownOperandButton.tsx
- FilterDropdownOperandSelect.tsx
- FilterDropdownTextSearchInput.tsx
- MultipleFiltersButton.tsx
- MultipleFiltersDropdownButton.tsx
- MultipleFiltersDropdownContent.tsx
- SingleEntityFilterDropdownButton.tsx

We would like to create a API similar to DropDown:

- Create a ViewFilterScope similar to DropdownScope which will wrap the Filter component

```
export const DropdownScope = ({
  children,
  dropdownScopeId,
}: DropdownScopeProps) => {
  return (
    <DropdownScopeInternalContext.Provider value={{ scopeId: dropdownScopeId }}>
      {children}
    </DropdownScopeInternalContext.Provider>
  );
};
```

- Create [NameOfTheState]ScopedState for each state that we need in the ViewFilter inspired by isDropdownOpenScopedState:

```
export const isDropdownOpenScopedState = createScopedState<boolean>({
  key: 'isDropdownOpenScopedState',
  defaultValue: false,
});

```

- Create useViewFilterStates inspired by useDropdownStates:

```
export const useDropdownStates = ({ scopeId }: { scopeId: string }) => {
  const [isDropdownOpen, setIsDropdownOpen] = useRecoilScopedStateV2(
    isDropdownOpenScopedState,
    scopeId,
  );

  const [dropdownHotkeyScope, setDropdownHotkeyScope] = useRecoilScopedStateV2(
    dropdownHotkeyScopeScopedState,
    scopeId,
  );

  return {
    isDropdownOpen,
    setIsDropdownOpen,
    dropdownHotkeyScope,
    setDropdownHotkeyScope,
  };
};
```

- Create a useFilter() hook inspired by useDropdown():

```
export const useDropdown = (props?: UseDropdownProps) => {
  const {
    setHotkeyScopeAndMemorizePreviousScope,
    goBackToPreviousHotkeyScope,
  } = usePreviousHotkeyScope();

  const scopeId = useAvailableScopeIdOrThrow(
    DropdownScopeInternalContext,
    props?.dropdownScopeId,
  );

  const {
    dropdownHotkeyScope,
    setDropdownHotkeyScope,
    isDropdownOpen,
    setIsDropdownOpen,
  } = useDropdownStates({
    scopeId,
  });

  const closeDropdownButton = () => {
    goBackToPreviousHotkeyScope();
    setIsDropdownOpen(false);
  };

  const openDropdownButton = () => {
    setIsDropdownOpen(true);

    if (dropdownHotkeyScope) {
      setHotkeyScopeAndMemorizePreviousScope(
        dropdownHotkeyScope.scope,
        dropdownHotkeyScope.customScopes,
      );
    }
  };

  const toggleDropdownButton = () => {
    if (isDropdownOpen) {
      closeDropdownButton();
    } else {
      openDropdownButton();
    }
  };

  return {
    isDropdownOpen: isDropdownOpen,
    closeDropdown: closeDropdownButton,
    toggleDropdown: toggleDropdownButton,
    openDropdown: openDropdownButton,
    scopeId,
    dropdownHotkeyScope,
    setDropdownHotkeyScope,
  };
};
```

- Since Filter components always live in a view, we will use the scopeId from the ViewScope inside the ViewFilterScope

**Comment by charlesBochet** [comment]
This has been implemented, closing it :)
