### ISSUE TITLE
Improve ViewBar API

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#2166]
In #2164 and #2165, we isolate filter and sort in their own modules and update their API.
We will need to take these changes into account to refactor the ViewBar component.

- Create a ViewScope component
- Wrap the View and the ViewBar in a scope cascade:
```
<ViewScope>
    <FilterScope>
        <SortScope>
        ...
        <SortScope/>
    <FilterScope/>
<ViewScope/>
```

- Expose a useView() hook.

See https://github.com/twentyhq/twenty/issues/1939

Ideas:
- FieldDefinition is stored in metadata
- ViewField is stored in data/public
- The ViewScope component should have an API that can be used by Showpage, DataTable and Board
- FilterScope and SortScope should use the scopeId from ViewScope

**Comment by charlesBochet** [comment]
@bosiraphael I've found this related ticket: https://github.com/twentyhq/twenty/issues/1939
