### ISSUE TITLE
New object field - Step 1 - Save activated/disabled fields

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#2170]
## Context

See #1767

For this issue:
- In the "New Field - Step 1" page, when the "+" button of a disabled field row is clicked, the field row moves to the "Active" section. If the "Active" section was collapsed, it is expanded.
- When the "-" button of an active field row is clicked, the field row moves to the "Disabled" section. If the "Disabled" section was collapsed, it is expanded.
- Clicking on these buttons does **NOT** update the backend.
- If fields were enabled/disabled (there are changes compared to the backend data), the "Save" button is enabled.
- Clicking on the "Save" button updates the changed fields (use `useUpdateOneMetadataField`) and navigates back to the "Object Detail" page.

## Figma

![image](https://github.com/twentyhq/twenty/assets/3098428/8b6cfb87-7b7b-4bda-84c3-310dd019d552)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11336%3A63097&mode=design&t=EynOEhEsP06qxkYt-1

## Behavior

**GIVEN** I am on the "New Field - Step 1" page
**WHEN** I click on a field row's action icon in the "Disabled" section
**THEN** the field row moves to the "Active" section
**AND** the "Active" section is expanded
**AND** the "Save" button is enabled

**GIVEN** I am on the "New Field - Step 1" page
**WHEN** I click on a field row's action icon in the "Active" section
**THEN** the field row moves to the "Disabled" section
**AND** the "Disabled" section is expanded
**AND** the "Save" button is enabled

**GIVEN** I am on the "New Field - Step 1" page
**WHEN** I enable/disable fields
**AND** I click on the "Save" button
**THEN** the fields are updated
**AND** I navigate to the "Object Detail" page

**Comment by Kanav-Arora** [comment]
Hi @thaisguigon 
Can I work on this issue?

**Comment by Kanav-Arora** [comment]
Hi @thaisguigon 
Please respond

**Comment by thaisguigon** [comment]
@Kanav-Arora usually yes we recommend contributing on issues with the `Good first issue` tag as they are more detailed, and avoiding issues that are already assigned to another user (even to @CoreTeamTwenty) to prevent duplicate PRs.
We're not working on [#2159](https://github.com/twentyhq/twenty/issues/2159) right now so you can contribute on this one if you want.
