### ISSUE TITLE
Record type and opportunity type

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2176]
## Scope & Context
Salesforce has a concept of record type, which is a way to group many records together and assign them different business processes and layout. For example if you're a marketplace you might want to have 2 record types for your contact : buyer and seller. 

It's probably premature for us to introduce such a generic concept. We are already introducing custom objects soon which will give a lot of flexibility, so we can learn from that already.

But we've already created the backend for OpportunityType (currently named `pipeline`, see https://github.com/twentyhq/twenty/issues/2112). So we can learn from that, quickly implement a frontend that's aligned with the long-term direction of record types, but that relies on this simple backend object at first.

## Required changes
**1. Settings**
- Add a subsection below "Fields" on the Opportunities object customization page called "Opportunity Types".
- I can view the list of opportunity types in that section
- I can edit an opportunity type
- I can delete an opportunity type
- I can add an opportunity type

**2. Opportunities page**
Dropdown in top bar to navigate between the opportunity types

**Comment by codergirl2023** [comment]
@FelixMalfait can i work on this task?

**Comment by Bonapara** [comment]
Hi @codergirl2023, thanks a lot! I'm almost done with the design, will ping you when they get ready
