### ISSUE TITLE
Export as csv 

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2183]
## Scope & Context
It would be handy to be able to export the data as csv.

## Expected behavior

Add an export button below (icon FileExport)

<img width="190" alt="Screenshot 2023-10-22 at 14 10 02" src="https://github.com/twentyhq/twenty/assets/6399865/c6f0d30e-07e6-4f0a-89c2-655253630e33">

It should create a csv file to download what I'm seeing now on the page. So if I'm on a specific view or I have filters set, the filters should be applied to that export. Sorting should be applied too.

## Technical inputs
- Build it on the frontend
- Set a small delay between each query to avoid overloading the server (100ms ?)
- Show progress by updating the button label : Export (xx %) - the xx% can be computed since we have the total count and allocate 10% for the json 2 csv part.
- Set a limit: 100 queries
- Write tests
- You can use https://github.com/mrodrig/json-2-csv

**Comment by mrkirthi-24** [comment]
@FelixMalfait I would like to work on this issue

**Comment by FelixMalfait** [comment]
Thanks a lot @mrkirthi-24! Feel free to check the strategy with us before starting implementation if you have doubts

**Comment by mrkirthi-24** [comment]
Sure @FelixMalfait 👍

**Comment by charlesBochet** [comment]
@mrkirthi-24 This should be done on the backend side as we have a pagination, we will need to introduce a new graphql endpoint

**Comment by FelixMalfait** [comment]
I was convinced we'd do this on the backend side but I changed my mind. I think we should do it on the frontend.

The business use-cases for data exports range from distinct needs:
- Large data exports that need to be processed async, they are stored on S3 and sent via email, they usually contain very raw data (all columns available, closer to the database layer than the metadata layer)
- Small in-app data exports that match applied filters. For exemple the marketing team wants to export 100 contacts to send an email campaign in another software.

And there roughly are 3 ways we could implement it within the app:
- Frontend: loop over API results and build the CSV file on the client side
- Backend Light: loop over pg_graphql queries and build the CSV file on the server side, return it directly
- Backend Heavy: dispatch a job, job loops over pg_graphql queries  and build the CSV file on the server side, uploads it to S3, email it to client.

The Pros/Cons are the following:
- Frontend: timeout depends on client so potentially higher than in Backend Light ; good user experience that reflects "what you see is what you get"
- Backend Light: lower timeout set by server ;  average user experience as I see no progress bar
- Backend Heavy: no timeout ; poor user experience as I have to wait for an email

I think we should go with the Frontend solution in the Options menu.
And probably one day we'll have to build the Backend Heavy solution within Settings.
But the "Backend Light" solution feels like a bad intermediate.

I will update the issue accordingly.

**Comment by FelixMalfait** [comment]
@quest-bot stash 250

**Comment by mrkirthi-24** [comment]
@quest-bot embark

**Comment by mrkirthi-24** [comment]
@FelixMalfait what is the deadline for submission?

**Comment by FelixMalfait** [comment]
@mrkirthi-24 3 days after assignment to an issue! Thanks

**Comment by mrkirthi-24** [comment]
@FelixMalfait please assign this issue to me

**Comment by mrkirthi-24** [comment]
![Screenshot 2024-02-02 at 9 15 15 PM](https://github.com/twentyhq/twenty/assets/53830546/44ecc993-d097-4f04-805b-a6e2fa5fcc3f)

I am getting this error while setting up macOS using docker

**Comment by mrkirthi-24** [comment]
Hi @FelixMalfait I am having problems starting frontend code. Please help.
![Screenshot 2024-02-03 at 6 12 54 PM](https://github.com/twentyhq/twenty/assets/53830546/79f43802-8e84-482b-872f-72811564d4b4)
![Screenshot 2024-02-03 at 6 12 46 PM](https://github.com/twentyhq/twenty/assets/53830546/55aec312-1f8a-4da0-9414-e320d3b84ba0)

**Comment by FelixMalfait** [comment]
@mrkirthi-24 pretty hard to debug these kind of things remotely. This is the kind of issue where starting from a fresh start could help (remove node_module, re-run yarn, close and re-open VSCode, etc.)

**Comment by anoopw3bdev** [comment]
@quest-bot embark

**Comment by anoopw3bdev** [comment]
@FelixMalfait feel free to assign me, I have started working on this

**Comment by anoopw3bdev** [comment]
Hi @FelixMalfait 
My understanding on the implementation of this feature is that, it relies completely on the frontend.
However, I have some doubts in the technical inputs shared 
1. `Set a small delay between each query to avoid overloading the server (100ms ?)`
2. `Set a limit: 100 queries`

Can you elaborate little more on what do you mean by the above two points.

**Comment by FelixMalfait** [comment]
Hey @anoopw3bdev we need to handle pagination so we will only be able to fetch a limit number of records at a time (60?). 
If we do a for loop with 100 requests in a row I'm afraid this will overload the browser and make some people's computer freeze. It could also hit the server's API rate limit. Instead, we'd like to have a nice feedback loop with progress % and give a little time to breath to the browser and the server.

This PR hasn't been merged yet https://github.com/twentyhq/twenty/pull/3566/files but in the future it would be cool if we used the LOGGED_IN_SHORT_TTL  and LOGGED_IN_LONG_TTL to determine respectively the delay between queries and the max number of queries.

**Comment by anoopw3bdev** [comment]
Thanks @FelixMalfait 
After carefully considering technical challenges involved in this feature, I believe it would be best to reassign this task to someone else who may be bit more experienced with codebase to handle it efficiently. Hence reassigning myself from this issue.

**Comment by tatethurston** [comment]
@quest-bot embark

**Comment by tatethurston** [comment]
@FelixMalfait I took a first pass in #4034. There's some light refactoring it could use, but I have a few broader, clarifying questions:

1. Are there existing test patterns / examples you could point me to in the application?
2. Currently, I have the CSV download wired up to simply produce a CSV based on the records the user is viewing. For the API pagination, is your thinking that the current filters will remain applied, and the frontend will follow the pagination back up to 100 "pages"?
3. What kind of presentation / formatting do you expect for the csv columns? Eg dates, links, null/empties, etc. [Example](https://github.com/twentyhq/twenty/pull/4034#issuecomment-1950019633)
