### ISSUE TITLE
[Timebox 3 days] Fix test database on twenty-server

### ISSUE THREAD

**Issue by martmull** [twentyhq/twenty#2196]
Today, test-database is not usable in twenty-server, developers cannot implement tests checking modification in the database. The goal is to have a ci running with a test checking data on a test database

**Comment by martmull** [comment]
Issue with environment variable loading. nx is loading env file by himself, depending on the "target" of the command launched. I had to rename `.env.test` into `.env.test:e2e` in order to have the test env variables loaded

**Comment by FelixMalfait** [comment]
Closing this for now as it's a timebox and has been open for long, see also https://github.com/twentyhq/twenty/issues/3862
