### ISSUE TITLE
Add relation field type v2 on front end

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2199]
## Scope & Context

New flexible backend, refactor of the field types V2. 

Focus on the field type `relation`.

## Current behavior

Currently we have a ticket for implementing the v2 of fields on the new flexible backend. https://github.com/twentyhq/twenty/issues/2040

We kept the `relation` type separated because it needs more work on the backend side.

## Expected behavior

We'd like to have this type implemented as well, see with ticket https://github.com/twentyhq/twenty/issues/2191 assignee.

**Comment by TharinduBalasooriya** [comment]
@lucasbordeau  Hi I would like to work on this

**Comment by lucasbordeau** [comment]
Hi @TharinduBalasooriya, all the issues assigned to @CoreTeamTwenty are locked because it touches core functionalities that are being discussed internally.

**Comment by charlesBochet** [comment]
Closing this issue as this has been implemented
