### ISSUE TITLE
UNAUTHENTICATED error is not correctly handled

### ISSUE THREAD

**Issue by tomalexing** [twentyhq/twenty#2202]
When a user leaves the browser tab untouched for 30 minutes, the user gets  UNAUTHENTICATED error.
The Apollo docs says how to handle this type of errors, so it is now used in codebase.
![Image 3](https://github.com/twentyhq/twenty/assets/9631913/c4e2f8cc-483f-4ab8-9f09-4e0a7ed686df)

But how you can see from image, they use async function in sync manner. Than is not gonna work.

How to verify:
1. change ACCESS_TOKEN_EXPIRES_IN to 1m
2. not do anything on page for 1minute
3. try do anything

**Comment by charlesBochet** [comment]
Thank you!
