### ISSUE TITLE
User identification via e-mail is case-sensitive 

### ISSUE THREAD

**Issue by joshuajung** [twentyhq/twenty#2208]
## Bug Description

When users sign up via their e-mail address, a case-sensitive version is stored in the database. To sign in later, they need to enter the address with exactly the same casing to be identified.

## Replication
1. Register to a workspace with the address `Foo@bar.com`
2. Try to sign in with `foo@bar.com`

## Expected behavior
The user is identified correctly and asked for their password. 

## Actual behavior
The user is not identified and can register a second time.

**Comment by FelixMalfait** [comment]
Thanks for reporting this!

**Comment by ttlpta** [comment]
Hi @FelixMalfait , @joshuajung 

For this issue, I gonna update checkUserExists of AuthService from ```findUnique()``` to ```count()``` to add   ```mode: 'insensitive'```. And on the frontend side I add one more rule for valid sign up email is should be not contain uppercase character. What do you think?
![image](https://github.com/twentyhq/twenty/assets/9917124/b649fd87-1003-48f5-883a-9845908e1eed)

**Comment by b9aurav** [comment]
@FelixMalfait I would like to work on it, Can you assign it to me?

**Comment by FelixMalfait** [comment]
Thanks @b9aurav!
