### ISSUE TITLE
Regenerating prisma types on server is too long because of linter

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#221]
Maybe we should deactivate linting for this folder instead because it's painful to wait so long for linting-generated code.

**Comment by charlesBochet** [comment]
Why do you need to wait for linter to be done? You can still use the code even if it's not linted. Linting is just a reformatting to meet our readability standards and has no impact on prisma code behavior

**Comment by charlesBochet** [comment]
Closing this ticket as we have decided to stop linting generated types and made the change this week.
