### ISSUE TITLE
Lookup fields: last opportunity and next task

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2213]
## Context
As of today, on the people or companies view, it's not possible to view fields that are not directly linked to the table.
It would be useful to be able to display and filter by those relation fields.
We could start with:
- Last opportunity (sort by created_at DESC)
- Next task (filter completed_at != null && sort by due_date ASC)

Show by default when workspace is setup:
- due date of next due task
- status of last opportunity

## Design 
cc @Bonapara 

## Technical inputs
cc @Weiko

**Comment by Bonapara** [comment]
See https://github.com/twentyhq/twenty/discussions/3645
