### ISSUE TITLE
Assign a record identifier.

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2219]
## Scope & Context

The identifiers for records in an object view are the "name" and "illustration" of each record, They will be displayed in the first column of an object table view. 
- Record text identifier can either be a `text` field or a `Number` field. (In the future they might also be `Computed fields`)
- Record image identifier should be an `image` field type (Not implemented yet)

![image](https://github.com/twentyhq/twenty/assets/19412894/1d8b1544-cfb4-4a48-b075-d5ecd67b6597)

## Expected behavior

In the settings, on a **Custom Object** detail page, the second column of the fields should be "Identifier" instead of "Field type" (As all fields of a custom object are custom)

![image](https://github.com/twentyhq/twenty/assets/19412894/0dee914d-aad5-494e-8e14-684a8895beb4)

### Edit a record text identifier

The first method is to click on the dropdown menu for the fields:

![image](https://github.com/twentyhq/twenty/assets/19412894/13f855aa-b8cb-42ea-a6d1-d0a701ebf8cb)

The second method is shown in the creation and detail page of the custom field settings. **But only for custom fields of custom objects!** As mention in the scope section, this section should only appear when the above field type has been set to **text** or **number**

![image](https://github.com/twentyhq/twenty/assets/19412894/95873c5a-42b0-4454-b7b1-c068fde492e3)

### Table views

As for Standard objects, the record identifier should be displayed in the first column of the table. It should not be movable or hideable.

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11383-58516&mode=design&t=JFqF92iemcbzIUHs-4

**Comment by FelixMalfait** [comment]
Note we also have a similar concept on standard objects (cf entityChipDisplayMapper I think), we should probably unify all

**Comment by Bonapara** [comment]
Depreciated & replaced by: https://github.com/twentyhq/twenty/issues/2489
