### ISSUE TITLE
Remove no-console rule from main eslint configuration

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2238]
## Scope & Context

We've implemented a new ESLint rule to prevent merging console.log statements into production.

The problem is that we still need to allow console.log during the development process, and right now we have to do extra work each time we want to do a simple console.log to deactivate the ESLint rule for this particular line.

We need to tackle the problem with a different approach : 
- Create a separate eslint config file that will contain rules for CI only
- Add no-console (level: error) in the new CI eslint config file
- Create a new script that will run eslint only on this specific config file
- Call this script in the CI in a new step

That way we let developers put as many console.log as they want but the CI will crash if they don't remove them before merging.

**Comment by alfredlouisw8** [comment]
can i work on this issue?
