### ISSUE TITLE
Build a script to cleanup inactive workspaces

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2252]
Linked to #2355

## Goal
We need a way to cleanup unused workspaces (it's a healthy habit to have for data privacy reasons).

## Context
We need:
- A way to run a command
- A way to identify inactive workspaces
- A way to send an email to a user

## Creating a command
We have just introduced a way to create commands. 
See https://github.com/twentyhq/twenty/pull/2236/files
It hasn't been merged yet but should soon be!

The command should take several optional flags:
--dry-run to disable sending email and deleting workspaces
--alert {number_of_days} to send a notice email but not delete any workspace
--silent-deletion to delete the workspaces but not send any email

It should take as mandatory parameter the number of days of inactivity.

##  Inactive workspaces
Initially I thought the best definition for an inactive workspace is a workspace in which every member is inactive.
And an inactive member could be defined with a new field lastActiveAt.
But introducing such a field at login would be inaccurate (you might stay logged in for weeks lastLoginAt != lastActiveAt) ; and updating it on every request seems like a bad choice (very tiny % performance drop yes, but on 100% request, so it's not worth doing it).

So my recommandation for now would be to use an approximate definition of inactive workspace such as `any workspace where (activities + companies + people) where ( updated_at > today -  X_days) is null`

## Deleting workspace
We already have an endpoint to delete workspaces (see https://github.com/twentyhq/twenty/pull/896 for history)
Let's make sure we share the same logic and don't duplicate code.

## Preparing the email template
It would be nice to have a base email template we can use. 
For the UI lib, I thought we could use https://github.com/resendlabs/react-email but it seems to be optimized for Tailwind? We use styled components. (No reply here: https://github.com/resendlabs/react-email/discussions/916)

Maybe look into something like this https://github.com/sbekrin/styled-email-components and quickly build a few components?

Figma for the 2 templates: https://www.figma.com/file/VTJQSQNmchLwS7uO8bn3TJ/Workspace-deletion-emails?type=design&node-id=3%3A89&mode=design&t=MkRdmfmnlfmybNhH-1

##  Sending an email
I recommend introducing 2 new packages:
(2) https://github.com/nodemailer/nodemailer
(3) https://www.npmjs.com/package/@aws-sdk/client-ses

Our cloud app is on AWS so we could use (3) directly, but going through (2) instead as a wrapper around (3) will give more flexibility for people who self host to use a different option. We should let it be configurable in .env file

**Comment by mrkirthi-24** [comment]
Hi @FelixMalfait I would like to work on this issue.

**Comment by FelixMalfait** [comment]
Hey @mrkirthi-24 great thanks a lot! Let me know if you have any question, this isn't a small task
Also we need Weiko's PR to be merged

**Comment by mrkirthi-24** [comment]
Sure @FelixMalfait I will let you know if I need your help. Thank you 🙏

**Comment by shavidze** [comment]
If you  need help I would be glad to help you. @mrkirthi-24

**Comment by FelixMalfait** [comment]
Thanks @martmull for working on that. Just commenting on the PR to make sure @mrkirthi-24 sees it and can build on top of wht you've done already

**Comment by mrkirthi-24** [comment]
@FelixMalfait I am really sorry for being inactive the last week as I was not feeling well. But now I am good and surely complete the rest.
