### ISSUE TITLE
Improve mobile display with tab bar 

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2261]
## Scope & Context
The current app isn't optimized for mobile, with minimal changes we can significantly improve the overall experience.

<img src="https://github.com/twentyhq/twenty/assets/6399865/94241717-242a-4f9a-8e57-99334e97c987" width="300" />
<img src="https://github.com/twentyhq/twenty/assets/6399865/1768edd2-8f9f-4904-99cf-64d50dabec33" width="300" />

Please refer to this Figma for design: https://www.figma.com/file/DprZh6sInsEiPZdvqx2TH5/Mobile-menu?type=design&node-id=0%3A1&mode=design&t=jG08VNZjU66rfvCK-1
(login and use developer mode)

## Steps

<details>
  <summary><strong>Create a tab bar component</strong></summary>
  <p>
Here's what the tab bar should look like: <br>

<p>
<img src="https://github.com/twentyhq/twenty/assets/6399865/ddba18cb-eb07-4ba9-a3ec-67c790934d39" >

</details>

<details>
  <summary><strong>Create a mobile menu component</strong></summary>
  <p>
  Since the desktop and mobile menu are starting to diverge in different differections, it's probably time to introduce a dedicated component. The 2 main differences will be : (1) we only display favorite and workspace sections (and not the first section with search, etc.), (2) styling changes a bit. <br>
  We still want to avoid duplicate code for the favorite/workspace sections, we should only have one place to maintain for both menus.
  </p>
</details>

<details>
  <summary><strong>Hide menu icon on mobile</strong></summary>
  <p>
<img src="https://github.com/twentyhq/twenty/assets/6399865/cab964a7-724c-4862-a9bf-ad495acec7da" width="300" />
  </p>
</details>

<details>
  <summary><strong>Display tab bar on mobile and link the tabs</strong></summary>
  <p> Display the component you created in the first step, on mobile only, sticked to the bottom. <br> Link the different actions (open menu, open search, open settings, open tasks)
  </p>
</details>

<details>
  <summary><strong>Adapt search</strong></summary>
  <p>
  The current display on mobile is bad. <br>
  Instead we should aim to have something that takes the full page <br>
<img width="350" alt="Screenshot 2023-10-27 at 14 44 24" src="https://github.com/twentyhq/twenty/assets/6399865/6bee1195-df2a-4778-b376-a9f79b302d03">

<br>
This is not a Figma to replicate exactly but here's something I did quickly in by editing the CSS in the browser to give an idea of the direction we should take: <br>
<img width="380" alt="Screenshot 2023-10-27 at 14 50 47" src="https://github.com/twentyhq/twenty/assets/6399865/964448e3-2c9e-4558-b7f4-68b08ea1e913">

  </p>
</details>

<details>
  <summary><strong>Adapt settings</strong></summary>
  <p> 
  Same as the other menu, we need to adapt the styling and what's displayed a little bit. Since it's accessible through a tab we should hide the title with back button <br>
  <img width="321" alt="Screenshot 2023-10-27 at 14 42 30" src="https://github.com/twentyhq/twenty/assets/6399865/91c8ece5-196a-4914-905b-8f44a522fa42">
  </p>

</details>

**Comment by shavidze** [comment]
Can I take it?

**Comment by FelixMalfait** [comment]
Of course @shavidze thanks a lot

**Comment by FelixMalfait** [comment]
@shavidze I added the "good first issue" tag because complexity is not too high but it's not a quick win, should still take a few hours to implement well! Let me know if you have any question or if you later decided you cannot do it anymore

**Comment by shavidze** [comment]
Okay, I will start today, If I will have some question I will ask here @FelixMalfait

**Comment by shavidze** [comment]
@FelixMalfait  I have problems running application with docker or with yarn, I wrote in discord and trying to understand the issue.

**Comment by shavidze** [comment]
[__Related PL__](https://github.com/twentyhq/twenty/pull/2304)

**Comment by charlesBochet** [comment]
This has been completed, closing this issue :)
