### ISSUE TITLE
Implement Button Component in Design System

### ISSUE THREAD

**Issue by Parvezkhan0** [twentyhq/twenty#2271]
## Scope & Context

We are working on implementing a Button component in the design system. This component will be used to maintain consistency and improve the user experience across the application.

## Current behavior

Currently, there is no Button component available in the design system. Developers are using custom styles for buttons, which leads to inconsistent UI elements across the application.

## Expected behavior

We expect to have a Button component available in the design system. This component should follow the design guidelines provided in the design system documentation. It should include appropriate states such as hover and active.

## Technical inputs

- Create a new folder named `Button` within the `ui` folder in the project directory.
- Implement the Button component using styled-components.
- Include styles for default, hover, and active states.
- Ensure accessibility considerations are taken into account (e.g., keyboard navigation, focus states).
- Test the Button component in isolation using Storybook.
- Integrate the Button component into relevant parts of the application where buttons are used.

**Comment by Kanav-Arora** [comment]
Hi @Parvezkhan0 
Can I work on this?

**Comment by FelixMalfait** [comment]
Hey @Parvezkhan0 we do have a button component used across the app already! I'm not sure if you're using a LLM to write these issues automatically 😏 ?

See https://storybook.twenty.com/?path=/story/ui-input-button-button--default > it comes with lots of options and is already flexible! But maybe this is not automated and you were misled by the doc which have an empty page and aren't properly linked to Storybook yet? @nimraahmed is working on fixing that
