### ISSUE TITLE
Icon picker spacing should be 2px

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2279]
## Current behavior

There is no **vertical** and **horizontal** spacing between icons hover

<img width="238" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/174f2a7b-c2e6-4ab9-8755-423ae1da9583">

## Expected behavior

- Add a 2px gap between icon buttons
- Selected icon background color should be the one of the "focus" state (darker than hover)

![image](https://github.com/twentyhq/twenty/assets/19412894/667a8202-d2ea-4083-8f2b-5e88d9c8e171)

## Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=14289-112692&mode=design&t=RpvU692SSqxgmoS4-4

**Comment by Asymtode712** [comment]
I want to work on it. Please assign me

**Comment by tanish-malekar** [comment]
Hi, can I work on this?

**Comment by AnuMessi10** [comment]
Hi @Bonapara I have made a fix for this, let me know if you can assign this to me so I can raise a PR, cheers!

**Comment by Bonapara** [comment]
Hi @tanish-malekar. I have just assigned you.
@AnuMessi10, I apologize, but @tanish-malekar was quicker this time!
Thank you both very much!

**Comment by fitrahfm** [comment]
Hi @Bonapara, would love to work on this

**Comment by Bonapara** [comment]
@tanish-malekar are you still on it? Thanks
