### ISSUE TITLE
Layout shift between DateInput and DateDisplay of 1px

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2284]
## Bug Description

When we open a table cell of type input, there's a layout shift of 1px.

https://github.com/twentyhq/twenty/assets/26528466/d6cdbd7c-da7f-4c4f-ab74-217407ae0251

## Expected behavior

We want it to be pixel perfect like other cells.

## Technical inputs

See styled components in components : `DateInput`, `DateDisplay`

**Comment by Kanav-Arora** [comment]
Hi can I work on this?

**Comment by lucasbordeau** [comment]
@Kanav-Arora Sure, I just assigned you.

**Comment by Kanav-Arora** [comment]
@lucasbordeau I have raised a PR
Please review and ping if any further changes are required.

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
Please review #2292
