### ISSUE TITLE
Rework Relation Search & Select & Create new dropdown to match Figma

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#229]
It's not taking 100% so we can see that borders aren't touching the container border
![image](https://github.com/twentyhq/twenty/assets/19412894/f87ae64b-dd25-477b-86ec-699ce37eef1d)

**Comment by charlesBochet** [comment]
UI components:

@/ui/menu
Menu
SearchInput
SelectSingleItem(children)
SelectMultipleItem(children)
SelectDropdownText(children)

SelectItem(avatar, text)

@/relation-picker
components/
Picker
- Menu
-- SearchInput
-- SelectSingleItem
---- SelectItem / CompanyItem

hooks

@/company
CompanyItem(avatar, text)
