### ISSUE TITLE
Correct tags spacings

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2299]
# ❗Edited

## Current look

On `Settings/Objects` the **Standard** and **Custom** tags look like this:

![image](https://github.com/twentyhq/twenty/assets/19412894/da8cb910-afac-4870-9045-cac5f3398368)

## Correction

- The tag text should be vertically centered (and the height should be 16px)
- The Left and right padding should be 4px instead of 8px.

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
Can I work on this?

**Comment by Bonapara** [comment]
Hi @Kanav-Arora Yes! Thanks

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
Please review PR #2302
