### ISSUE TITLE
Embed keyboard shortcuts within the app

### ISSUE THREAD

**Issue by nimraahmed** [twentyhq/twenty#2311]
## Scope & Context

We want to embed keyboard shortcuts within the app (like Gmail, Linear, etc., do), something similar to:

<img width="275" alt="keyboard shortcuts example" src="https://github.com/twentyhq/twenty/assets/50912134/32510402-abfd-48ba-8e01-db79795cffc9">

## Current behavior

Currently, we only have shortcuts related to the command bar. 

## Expected behavior

There can be 2 approaches:

1. User hits the ? key anywhere within the app, which brings up a list/panel of available shortcuts
2. Have a '?' somewhere at the bottom of the screen, which opens up a menu with a link to the 'shortcuts'. Something similar to:
 
![image](https://github.com/twentyhq/twenty/assets/50912134/e8cb11a2-c94e-49bd-94b8-1df04a46fd13)

Clicking on shortcuts should open up a panel with all available shortcuts.  

A possible enhancement in both cases is to have the ability to search for shortcuts as well.

cc @FelixMalfait @Bonapara

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait 
Can I work on this?

**Comment by FelixMalfait** [comment]
Hey @Kanav-Arora thanks! I think the designed haven't been done by @Bonapara yet so it's still blocked.
It will probably look very close to the design above, but they are taken from Linear

**Comment by charlesBochet** [comment]
@Bonapara for you!

**Comment by Bonapara** [comment]
Here we go!

![CleanShot 2023-11-06 at 14 23 01](https://github.com/twentyhq/twenty/assets/19412894/6417845f-fea7-4285-a804-15ec9fbcd2a9)

### Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=14556-49368&mode=design&t=A9asaF1ZRB33Eiw6-11

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
Please assign me this issue!

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait 
I am bit unsure about the issue. I need to map invoke keys for Keyboard Shortcuts?

**Comment by charlesBochet** [comment]
@Kanav-Arora Not sure to get your comment? We want to display a static list of all available hot keys

**Comment by Kanav-Arora** [comment]
> @Kanav-Arora Not sure to get your comment? We want to display a static list of all available hot keys

Actually what needs to be implemented is not mentioned in the issue.
Implementation of component for shortcuts is required or `?` and `What's New` section is required?

**Comment by charlesBochet** [comment]
> `⇧`+`?`

@Kanav-Arora This is what should be implemented. Forget about the other parts :D

**Comment by Kanav-Arora** [comment]
Thanks for clarifying
I'll start working on it

**Comment by Kanav-Arora** [comment]
And the shortcuts are as shown in this screenshot or needs to be fetched dynamically?

**Comment by charlesBochet** [comment]
@Kanav-Arora 
They are actually wrong :D

Table as shown
General: cmd+K + Go To (see cmd+K) menu

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
Please review #2507
