### ISSUE TITLE
Wrong size for the icon picker dropdown

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#2317]
## Bug Description

The right icons in the icon picker dropdown are cropped.
<img width="194" alt="Capture d’écran 2023-11-02 à 13 34 27" src="https://github.com/twentyhq/twenty/assets/71827178/34443f66-d804-4ecd-97cc-fe1abf0384f7">

## Expected behavior

The right icons shouldn't be cropped.

## Technical inputs

Probably a CSS fix in IconPicker.

**Comment by Dhoni77** [comment]
Hi @bosiraphael I would like to work on this

**Comment by bosiraphael** [comment]
@Dhoni77 I assigned you to this issue, thank you!
