### ISSUE TITLE
New object field - Step 2 - Add "Text" field preview

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2325]
# Current behavior

Today, there is a simple dropdown to select the **Text** field type

![CleanShot 2023-11-02 at 17 04 34@2x](https://github.com/twentyhq/twenty/assets/19412894/146642e1-cef4-4877-a1e8-1ee3c4bcf842)

# Expected behavior

We want to add a preview of how the field will render:

![CleanShot 2023-11-02 at 17 13 31@2x](https://github.com/twentyhq/twenty/assets/19412894/0cd51605-2932-41be-8740-b78ad0ef2275)

1) The name and icon below should match the field above.
2) If there are existing record values, display the value of the first field that contains content. Otherwise, fill the field value with lorem ipsum.

# Figma

![image](https://github.com/twentyhq/twenty/assets/19412894/0387551a-6857-438d-b92a-cd020acfdf9e)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=14456-174969&mode=design&t=avVSH5fvDzQPdLL9-11

**Comment by thaisguigon** [comment]
Use component from #2343

**Comment by charlesBochet** [comment]
See how we can re-use existing ReordInlineCell component in read-only mode
