### ISSUE TITLE
New object field - Step 2 - Add "Link" field preview

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2326]
# Current behavior

![CleanShot 2023-11-02 at 17 21 09@2x](https://github.com/twentyhq/twenty/assets/19412894/5e03c583-7ba6-4c9f-8038-414e5257cd8d)

# Desired behavior

We want to add a field preview under the field type:

![CleanShot 2023-11-02 at 17 22 09@2x](https://github.com/twentyhq/twenty/assets/19412894/9f5ce551-7fff-4946-a7f4-7ee20d788655)

1) The name and icon below should match the field above.
2) If there are existing record values, display the value of the first field that contains content. Otherwise, fill the field value with _www.twenty.com_

# Figma

![image](https://github.com/twentyhq/twenty/assets/19412894/b8354ab9-b86c-4dd1-a60e-6ef6e67790c4)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=14456-175677&mode=design&t=avVSH5fvDzQPdLL9-11

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
Can I work on this? What's the working timeline for this?

**Comment by thaisguigon** [comment]
Use component from https://github.com/twentyhq/twenty/issues/2343

**Comment by thaisguigon** [comment]
Hi @Kanav-Arora, this issue will be addressed by the core team.
