### ISSUE TITLE
New object field - Step 2 - Add "Number" field preview

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2327]
# Current behavior

![CleanShot 2023-11-02 at 17 25 43@2x](https://github.com/twentyhq/twenty/assets/19412894/d9113631-4f5a-49ab-84fb-b46b9266b72e)

# Desired behavior

![CleanShot 2023-11-02 at 17 26 09@2x](https://github.com/twentyhq/twenty/assets/19412894/795461cc-f259-4cfa-bfbb-3f83243b0468)

1) The name and icon below should match the field above.
2) If there are existing record values, display the value of the first field that contains content. Otherwise, fill the field value with "2.000"

# Figma

![image](https://github.com/twentyhq/twenty/assets/19412894/e504e2ba-af08-410e-93fa-7aaf4eab3eb9)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=14456-175924&mode=design&t=avVSH5fvDzQPdLL9-11

**Comment by thaisguigon** [comment]
Use preview component from https://github.com/twentyhq/twenty/issues/2343 and preview card component from https://github.com/twentyhq/twenty/issues/2349.
For now **do not** implement the "Type" select below the preview.
