### ISSUE TITLE
New object field - Step 2 - Add "True/False" field preview

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2328]
# Current behavior

![CleanShot 2023-11-02 at 17 29 37@2x](https://github.com/twentyhq/twenty/assets/19412894/7345abb1-241c-4d17-984b-659815d186cb)

# Desired behavior

![CleanShot 2023-11-02 at 17 30 12@2x](https://github.com/twentyhq/twenty/assets/19412894/c3d89658-885f-4a85-80ec-b936a411fda8)

1) The name and icon below should match the field above.
2) If there are existing record values, display the value of the first field that has either _True_ or _False_ Otherwise, fill the field value with _True_.

# Figma

![image](https://github.com/twentyhq/twenty/assets/19412894/853a0992-a92f-4d7b-bc54-3e807289d77e)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=14456-175924&mode=design&t=avVSH5fvDzQPdLL9-11

**Comment by thaisguigon** [comment]
Use component from https://github.com/twentyhq/twenty/issues/2343

**Comment by Anurag-modgil** [comment]
is anyone working on this issue

**Comment by thaisguigon** [comment]
Hi @Anurag-modgil, this issue will be addressed by the core team. You can find other issues to contribute on here: https://github.com/twentyhq/twenty/contribute
