### ISSUE TITLE
New object field - Step 2 - New field type: Currency

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2330]
# Desired behavior

![CleanShot 2023-11-02 at 18 21 35@2x](https://github.com/twentyhq/twenty/assets/19412894/18fffa58-aaba-436a-8cb2-25716f931352)

The **Unit** pick list should enable people to choose between:

1. United States dollar (USD)
2. Euro (EUR)
3. Japanese yen (JPY)
4. British pound (GBP)
5. Canadian dollar (CAD)
6. Swiss franc (CHF)
7. Chinese yuan (CNY)
8. Hong Kong dollar (HKD)

**Do not implement** the uniqueness & required features yet.

If there are any existing records with this field, display the value of the first non-empty field. Otherwise, the preview value should be $2.000. (without space between the $ and the number behind)

# Figma

![image](https://github.com/twentyhq/twenty/assets/19412894/e4f4a62f-f273-43fe-bf5c-2c01ca9e1467)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=13884-61375&mode=design&t=avVSH5fvDzQPdLL9-11
```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/2346
- [ ] https://github.com/twentyhq/twenty/issues/2347
```

**Comment by FelixMalfait** [comment]
@thaisguigon do you know what's missing to roll this out to users? Would be nice to be able to create custom currency fields

**Comment by FelixMalfait** [comment]
We talked with @Bonapara and we realized that currency unit is at the field level. So design above for setting page is incorrect. And we will need a new design to change the unit at the field level

**Comment by FelixMalfait** [comment]
Actually we discussed it again and we can keep "unit" but as a defaultValue for the field

**Comment by Bonapara** [comment]
Replaced by https://github.com/twentyhq/twenty/issues/4122
