### ISSUE TITLE
New object field - Step 2 - New field type : Date

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2331]
# Scope & current behavior

Date field type is today used as a standard field for **creation** in **Company**

![CleanShot 2023-11-02 at 18 32 41@2x](https://github.com/twentyhq/twenty/assets/19412894/eaf4bf13-8a60-4c8b-a70a-44b1a2125546)

A calendar redesign is in the works to match the other field designs. A future version will also allow time assignment with dates and more customisation options.

# Desired behavior

Provide a preview for the field. Show the value of the first non-empty field with a date from existing records. If no records, set the preview value to the date two years from today.

![CleanShot 2023-11-02 at 18 35 04@2x](https://github.com/twentyhq/twenty/assets/19412894/1699f943-0d6d-4a97-9c80-28eebdcdae58)

# Figma

![image](https://github.com/twentyhq/twenty/assets/19412894/e6ac43cd-bd00-441c-b661-476ea84d4278)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=14456-175229&mode=design&t=avVSH5fvDzQPdLL9-11

**Comment by thaisguigon** [comment]
- Add the "Date" option to the select in `SettingsObjectFieldTypeSelectSection`
- Use preview component from https://github.com/twentyhq/twenty/issues/2343
