### ISSUE TITLE
Refresh bug in the doc: part 1

### ISSUE THREAD

**Issue by nimraahmed** [twentyhq/twenty#2348]
## Bug Description

The telemetry page in the document breaks when you hit refresh or try to directly go to https://docs.twenty.com/others/telemetry. This is what you see in both cases:

![image](https://github.com/twentyhq/twenty/assets/50912134/ac713173-b712-405e-91b8-e3019a420501)

## Expected behavior

On refresh (or when you directly go to https://docs.twenty.com/others/telemetry), the page shouldn't break and you should still see: 

![image](https://github.com/twentyhq/twenty/assets/50912134/66a6e46f-1742-43da-a400-b8de8990e5d3)

iI you go to docs.twenty.com and then navigate to the telemetry page, everything works fine. 

## Note 
This works fine in dev mode, but you can reproduce this error locally by running:

`yarn build`
`npm install --global serve`
`serve -s build`

**Comment by charlesBochet** [comment]
@nimraahmed Do you plan to work on this one or do you want somebody else to work on it?

**Comment by charlesBochet** [comment]
@nimraahmed The bug seems to be fixed since we've updated Docusaurus :)
