### ISSUE TITLE
Refresh bug in the doc: part 2

### ISSUE THREAD

**Issue by nimraahmed** [twentyhq/twenty#2350]
This is part 2 of a refresh bug in the doc. You can refer to part 1 [here](https://github.com/twentyhq/twenty/issues/2348)

## Bug Description

We use multiple sidebars for our documentation, like for our [frontend section](https://docs.twenty.com/contributor/frontend/). When you directly go to this frontend link (instead of going to docs.twenty.com and then navigating to the frontend section from there) or refresh the page, a few things happen:

1. the back button at the top disappears
2. the sidebar links (on hover) and the icon (but not the text) change and what you start seeing is basically the level 0 sidebar (that's at the homepage). And you can tell that by hovering over a page or by looking at the emojis. After refresh, this is what the sidebar looks like:

![image](https://github.com/twentyhq/twenty/assets/50912134/f1cfb541-cfee-4488-b8f9-228d0816efd4)

But this is what the actual sidebar should look like:

![image](https://github.com/twentyhq/twenty/assets/50912134/acfb4ee9-4ab5-421b-9692-b97035dd49c0)

In addition to the changed icons that come from the main sidebar at docs.twenty.com, notice the link at the bottom. In both cases I'm hovering over contributing, and the link is different for both (it's correct in the latter). Also of interest is the soon pill in front of the UI components in the first screenshot, this also comes from level 0 (the soon pill comes from the overview file in the developer section in the sidebar on the homepage). 

3. In case of the frontend section, the text in the following files disappears when you hit refresh or directly navigate:

- https://docs.twenty.com/contributor/frontend/
- https://docs.twenty.com/contributor/frontend/basics/design-system
- https://docs.twenty.com/contributor/frontend/advanced/hotkeys

Similar things happen in the backend section. 

## Expected behavior

1. The back button shouldn't disappear on refresh
2. The sidebar icons + link shouldn't change
3. Directly going to a doc link or refreshing the page shouldn't cause things to stop functioning as you'd expect

## Note

Everything works as it should in dev mode, but you can reproduce this error locally by running:

`yarn build`
`npm install --global serve`
`serve -s build`

**Comment by charlesBochet** [comment]
@nimraahmed This seems to be fixed since docusaurus 3.0 upgrade
