### ISSUE TITLE
Using yarn workspace and fixed yarn version for local setup with yarn

### ISSUE THREAD

**Issue by ttlpta** [twentyhq/twenty#2352]
## Scope & Context
1, Local setup with yarn.

- At the Step 4: Server setup and Step 5: Frontend setup. We have to go to folder "server" or folder "front" to do some npm scripts,  Intead of that we can run all scrips at root folder "twenty" with [yarn workspace](https://classic.yarnpkg.com/lang/en/docs/workspaces/)

2, Fix yarn version
- At root folder, we can specify version of yarn for everyone with [yarn version](https://classic.yarnpkg.com/lang/en/docs/cli/version/)

**Comment by charlesBochet** [comment]
This has been completed, closing this issue :)
