### ISSUE TITLE
I can edit basic workspace settings

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#236]
* Logo
* Name

TBD if this task is mostly Front or Front + Back, depending on if [T-280](https://linear.app/twentyhq/issue/T-280/if-i-login-with-an-unknown-domain-then-im-asked-for-workspace-namelogo) is done before or after this one

Related: [https://github.com/twentyhq/twenty/issues/238](https://github.com/twentyhq/twenty/issues/238)

<sub>From [SyncLinear.com](https://synclinear.com) | [T-55](https://linear.app/twentyhq/issue/T-55/i-can-edit-basic-workspace-settings)</sub>

**Comment by charlesBochet** [comment]
Implemented by https://github.com/twentyhq/twenty/pull/553
