### ISSUE TITLE
Review pagination implementation on frontend

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2370]
## Scope & Context

Pagination of /metadata and /graphql endpoint returns.

## Current behavior

We currently request with a hard coded page of 1000 items.

## Expected behavior

We want to implement pagination with infinite scroll on both /metadata and /graphql on the frontend.

## Technical input

See existing libs for implementing it directly in the Apollo clients.

**Comment by charlesBochet** [comment]
This has been implemented, closing it :)
