### ISSUE TITLE
Remove "pen icon" on Team member field

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2384]
# Current behavior

![CleanShot 2023-11-07 at 15 30 05](https://github.com/twentyhq/twenty/assets/19412894/c711a172-a274-463b-a01b-0e8b980ff9c2)

# Desired behavior

Remove the pen icon on this field type (Team member). Clicking on a team member won't navigate anywhere, it only permits value modification.

**Comment by pokegh0st** [comment]
Hello, I'd be happy to take on this issue!

**Comment by Bonapara** [comment]
@pokegh0st just assigned you!
