### ISSUE TITLE
Correct the "+" icon button style on tables

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2385]
# Current behavior

![CleanShot 2023-11-07 at 15 34 18](https://github.com/twentyhq/twenty/assets/19412894/fe2ae5b9-6231-4173-a6e0-710a64f6bbaa)

The color looks like secondary and the hover take the whole cell.

# Desired behavior

The icon color should be **Tertiary**

its hover should take the full width (fill the red square below)

![CleanShot 2023-11-07 at 15 37 29](https://github.com/twentyhq/twenty/assets/19412894/2bae2a99-0676-4468-834b-d18937631944)

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
Can I work on this

**Comment by Bonapara** [comment]
Yes @Kanav-Arora! Thanks

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
I am getting some issues reproducing the issue. Please help with it

<img width="1440" alt="Screenshot 2023-11-07 at 9 32 08 PM" src="https://github.com/twentyhq/twenty/assets/62852363/e52b6c9d-59a3-4194-a457-b9ef0f820bc7">

<img width="1440" alt="Screenshot 2023-11-07 at 9 32 53 PM" src="https://github.com/twentyhq/twenty/assets/62852363/2dd977cc-39f5-4d8a-b84b-0b35f85548e9">

**Comment by Bonapara** [comment]
Maybe you can post in #help in our Discord? I'm not technical!

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
I have raised a PR for this issue
Please take a look

**Comment by charlesBochet** [comment]
@Bonapara do we want the hover effect (on the whole table header cell) to happen for all table header cells ; it would make sense as the other table headers are clickable

**Comment by Bonapara** [comment]
As discussed last week, yes!
