### ISSUE TITLE
The "company" field in the "People" behavior is incorrect

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2386]
# Current behavior

- The company is not displayed in a **chip**
- There is no "Pen icon button" on the cell
- Clicking on the cell open the menu instead of navigating to the company

![CleanShot 2023-11-07 at 15 39 59](https://github.com/twentyhq/twenty/assets/19412894/571c444d-464b-475c-98bc-8390f1e853e1)

# Desired behavior

Use the "Relation" field type:

- Add the "pen icon button" on the cell
- Put companies inside **relation** chips
- Make clicking on a chip goes to the corresponding detail page.

![CleanShot 2023-11-07 at 15 46 07](https://github.com/twentyhq/twenty/assets/19412894/b7d15037-0ef4-4ba5-beea-6942739fcf9d)

**Comment by shiv-tyagi** [comment]
Hi @Bonapara! I am new here and would like to try my hands on this issue. Can you please assign this to me?

**Comment by Bonapara** [comment]
Done, thanks for contributing @shiv-tyagi 🙏

**Comment by ritikprajapat21** [comment]
Hi @Bonapara! Can I also start contributing on this issue ??

**Comment by shiv-tyagi** [comment]
Hi @ritikprajapat21! I got busy with my university exams so I could not get time to work on it. I have unassigned this issue to myself. 

@Bonapara Feel free to assign this to @ritikprajapat21. Apologies from my side. I'll pick up some issues soon.

**Comment by ritikprajapat21** [comment]
@Bonapara Can you tell how can I reproduce this error?

**Comment by Bonapara** [comment]
Hi @ritikprajapat21, thanks for contributing! You can reproduce this by going to the "People object":

![Screenshot 2023-12-13 at 09 56 03](https://github.com/twentyhq/twenty/assets/19412894/b1289897-54af-4502-9d6c-6738efb95041)

Good luck @shiv-tyagi for your exams!

**Comment by FelixMalfait** [comment]
The issue mentions the list view but the place where it's most problematic is the show/detail page, let's make sure to fix that as well. Thanks 🙏
