### ISSUE TITLE
Danger button background is too dark

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2390]
# Current behavior

The danger button (Button tertiary) on the **action bar** is too dark. Also, the spacing between the icon & the text is too wide.

![CleanShot 2023-11-07 at 18 32 54](https://github.com/twentyhq/twenty/assets/19412894/2429ab34-4de3-46cd-810c-ce16c0789023)

# Desired behavior

- The spacing between the text & the button should be 4px
- The button background color should be `Background/danger`

![CleanShot 2023-11-07 at 18 35 27](https://github.com/twentyhq/twenty/assets/19412894/da10811d-bfad-489f-a598-f5de8d5eb8f6)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=3122-142114&mode=design&t=VAvSqM07BnWVQg4Y-11

**Comment by khoadangtran** [comment]
Hi, I want to work on this issue, Can you please assign it to me?
