### ISSUE TITLE
The calendar is truncated in the filter menu.

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2392]
# Bug 

When willing to `Filter` by `Created_at` the calendar display is cropped.

![CleanShot 2023-11-07 at 18 48 17](https://github.com/twentyhq/twenty/assets/19412894/7b2c96ab-afe2-44eb-bb93-5cfa909cc92d)

**Comment by joshLumpkin** [comment]
Hey @Bonapara, I would like to start contributing to open source. Can I work on this issue?

Thank you!

**Comment by Bonapara** [comment]
Hi @joshLumpkin. Sure, thanks a lot! Just assigned you on this issue

**Comment by charlesBochet** [comment]
This has been fixed :)
