### ISSUE TITLE
Add live code editors in docs for ui components

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#2393]
## Scope & Context

We want our documentation to be interactive like chakra-ui's doc: https://chakra-ui.com/docs/components

## Current behavior

The doc is not interactive.

## Expected behavior

Allow the user to edit the ui components directly in the docs to test and understand the component's api.

## Technical inputs

We use Sandpack for that: https://sandpack.codesandbox.io/docs
Instructions: https://docs.google.com/document/d/1LR5CxMwxq2KB5mUvRyjBD_INv9IWPeRGVXDxtslYm60/edit?usp=sharing

**Comment by charlesBochet** [comment]
I'm closing this issue as it has been implemented
