### ISSUE TITLE
New "+" icon on first column header to create record

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2394]
# Current behavior

You have to press the **+** button on the top right of the screen to add a record

![CleanShot 2023-11-08 at 10 21 00](https://github.com/twentyhq/twenty/assets/19412894/8b480c2d-3575-4e5f-8886-85bf1a580fbc)

# New additional behavior

We are introducing a new method for creating records. This involves adding a `+` icon button in the first header column. Please use a light button icon (tertiary) with a size of 24px. Additionally, remember to include a 4px margin to the right of the first column header to ensure a 4px padding around the button.

https://github.com/twentyhq/twenty/assets/19412894/ac36a459-73fc-4a93-8bb7-9577d332b342

![CleanShot 2023-11-08 at 10 25 12](https://github.com/twentyhq/twenty/assets/19412894/69d4895e-40e7-44e3-98eb-4981410a164a)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=151-10764&mode=design&t=aMr2FiocTLUMAPDG-11

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
As discussed in #2385 with @charlesBochet 
Don't you think it would be better to show this icon only on hover?

**Comment by Bonapara** [comment]
Hello @Kanav-Arora, the icon should be perpetually visible for easy record creation. Let's implement a hover on the entire header cell. Clicking on the header cell or the '+' button should initiate a new record. The `Icon button` and its own hover behavior should remain, even with a clickable header. Thanks!

**Comment by Kanav-Arora** [comment]
> Hello @Kanav-Arora, the icon should be perpetually visible for easy record creation. Let's implement a hover on the entire header cell. Clicking on the header cell or the '+' button should initiate a new record. The `Icon button` and its own hover behavior should remain, even with a clickable header. Thanks!

Actually after @charlesBochet comments on #2411
I have already raised a PR for these changes for issue #2385 which is now merged.

So all headers have hover effect. Now implementation of onclick and icon is pending.

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
As I have worked on related issue #2385 
Can I work on this?

**Comment by charlesBochet** [comment]
Sure :)

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
I have raised a PR closing this issue

**Comment by charlesBochet** [comment]
@Kanav-Arora Thanks! I have left comments on the PR :)
