### ISSUE TITLE
Data Table: Unfocus cells when mouse leaves the table area

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2395]
# Current behavior

When I move my mouse away from a table, the last hovered cell remains in focus. In the example below, the mouse moves away from the table, but the focus remains on "Figma."

https://github.com/twentyhq/twenty/assets/19412894/9824b36b-5d65-499c-b814-6288bcbcecc3

# Desired behavior

When the mouse moves away from the table, the focus should be removed from the last hovered cell.

**Comment by uwemneku** [comment]
I observed that the mouse hover effect isn't activated unless interaction occurs with a column other than the first one.

https://github.com/twentyhq/twenty/assets/30045115/351721f5-3af4-42f9-93e3-7b9818cb2cda

https://github.com/twentyhq/twenty/assets/30045115/f0d6efab-9e1b-4bb8-88d5-5993cee902e9

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
I think I can try this issue. May I?

**Comment by Bonapara** [comment]
@Kanav-Arora, apologies for the delayed response. A pull request was initiated in the interim.
