### ISSUE TITLE
Border color for danger button is incorrect in dark mode

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2396]
# Current behavior

The border color is the one of the light button

![CleanShot 2023-11-08 at 10 49 27](https://github.com/twentyhq/twenty/assets/19412894/33ef5056-1c5b-44ce-b4f1-c9bfdef8a01e)

# Desired behavior

Please use the `Border/Danger` border color. If it is not already part of the design system, it should be added as a new color variable.

![CleanShot 2023-11-08 at 10 53 00](https://github.com/twentyhq/twenty/assets/19412894/4738eb3c-a5b4-4ff7-a5d2-74cc04f1b033)

**Comment by uwemneku** [comment]
can this issue be assigned to me ?

**Comment by charlesBochet** [comment]
This has been already fixed, thank you @uwemneku :)
