### ISSUE TITLE
See and remove the users of my workspace

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#240]
<sub>From [SyncLinear.com](https://synclinear.com) | [T-279](https://linear.app/twentyhq/issue/T-279/i-can-see-the-workspace-users)</sub>

<sub>[T-388](https://linear.app/twentyhq/issue/T-388/[t-279]-i-can-see-the-workspace-users)</sub>

**Comment by FelixMalfait** [comment]
cc @Bonapara to confirm design before sprint starts

**Comment by Bonapara** [comment]
![Image](https://github.com/twentyhq/twenty/assets/19412894/ada6edfd-94e0-4de6-9dbf-cce76179d65c)

New design

**Comment by charlesBochet** [comment]
Implemented in https://github.com/twentyhq/twenty/pull/552
