### ISSUE TITLE
Basic profile information edition

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#241]
* First Name
* Last
* Email is READ only for now, it shouldn't be possible to change it

<sub>From [SyncLinear.com](https://synclinear.com) | [T-56](https://linear.app/twentyhq/issue/T-56/i-can-edit-basic-profile-settings)</sub>

**Comment by FelixMalfait** [comment]
cc @tdesfrancs FYI I think it's best if we can avoid Twenty in text copy (for various reason, first Airbnb wouldn't do it in that context, but also because self-host = they're making this their own app on their own server, Twenty will not appear anywhere)

**Comment by FelixMalfait** [comment]
![Screenshot 2023-05-24 at 10.46.50.png](https://uploads.linear.app/b1acf0dc-e74a-40f6-989b-074be1c096b2/7a4e04cc-d9e0-48fb-898e-cae3a3e837b6/a4096f77-8b9b-4346-be9a-ffde4158ac22)

Something like this

**Comment by FelixMalfait** [comment]
cc @Bonapara to confirm design before sprint starts

**Comment by Bonapara** [comment]
![Image](https://github.com/twentyhq/twenty/assets/19412894/2520a4ef-09bf-411e-88d4-0c23881664e7)

**Comment by Bonapara** [comment]
Email field should be disabled

**Comment by charlesBochet** [comment]
This has been implemented
