### ISSUE TITLE
Makefile command to provision database on MacOS and Linux

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#2412]
## Scope & Context

New contributors are facing issues with missing graphql schema. It's usually because they haven't run the setup scripts:

- postgres on Linux (or WSL): ./infra/dev/scripts/setup-postgres-linux.sh
- postgres on Mac: ./infra/dev/scripts/setup-postgres-macos.sh
- postgres in Docker: make provision-postgres

For docker, we have a make command, but we don't for Linux and Mac postgres hosting.
It would be nice to have one, will make things symetrical + make sure that people are running those script from twenty root

## Technical inputs

Create makefile commands for (similar to make provision-postgres)
- postgres on Linux (or WSL): ./infra/dev/scripts/setup-postgres-linux.sh
- postgres on Mac: ./infra/dev/scripts/setup-postgres-macos.sh

Update yarn setup documentation: https://docs.twenty.com/contributor/local-setup/yarn-setup

**Comment by shiv-tyagi** [comment]
Hey @charlesBochet! I am new here. I would like to work on this issue. Can you please assign this to me?

**Comment by charlesBochet** [comment]
sure!
