### ISSUE TITLE
[Timebox] Sorts and Filters are refactored

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#242]
New scope for this ticket:
- move sort and filters components into @/ui/sort and @/ui/filter
- these components should expose a simple API that direclty uses DropdownMenu, MenuItems, SingleSelect components + hooks to use them. Remove the current "configurable api"

Put all the FilterDropdownState information in a recoil state or context
read this state from FilterDropdown components to display the right dropdown content
make this "generic"
use DropdownMenu hook to pilot the dropdown itself
use existing filterDefinition recoil state to communicate with view system

**Comment by FelixMalfait** [comment]
@charlesBochet sorry I don't get this issue, would you mind adding one sentence to explain?

**Comment by charlesBochet** [comment]
We have refactored Filters into a much simpler API, we would like to do the same for Sorts. It is not super prioritary but that's a tech debt area we would like to imrpove

**Comment by lucasbordeau** [comment]
Is this issue still relevant now that we've done the sorts refactor ?

**Comment by charlesBochet** [comment]
We can close it! Congrats for the work!
