### ISSUE TITLE
feat: support `SELECT` type on per tenant back-end

### ISSUE THREAD

**Issue by magrinj** [twentyhq/twenty#2445]
## Scope & Context

The per tenant backend can handle a list of simple and complex types.

## Current behavior

`ENUM` as already been added to the list but is not yes fully implemented.

## Expected behavior

We should be able to create a field metadata of type `ENUM` and provide him an array of values.

## Technical inputs

• We need to define if we're storing directly the enum values inside the `FieldMetadata` table of if we're creating a special table for that (cc @Weiko)

**Comment by charlesBochet** [comment]
While thinking about it, also take in account: "SELECT", "MULTISELECT", "PIPELINESTEP", "RATING" (color + ordering)
