### ISSUE TITLE
Rename Money field metadata type to Currency

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#2456]
## Scope & Context
We currently have a Money field metadata type that represents both Currency and Amount. 
Our plan is to align with other CRM and use commonly used "Currency" type instead.

## Technical inputs

Rename Money to Currency inside tenant and metadata modules
Regenerate frontend graphql schema

Currency {
   CurrencyCode
   AmountMicros
}

Link {
   URL
   Label
}

**Comment by magrinj** [comment]
@Weiko I'm not sure I understand this, the new `Currency` type will also host `amount` and `currency` values ?

**Comment by Weiko** [comment]
> @Weiko I'm not sure I understand this, the new `Currency` type will also host `amount` and `currency` values ?

Yes, in the code it means we will see things like `Currency.currency` which might sound redundant and I'm not a big fan of it but we are going for that to align with other famous CRM that took the decision to make it standard.

**Comment by magrinj** [comment]
@Weiko Sounds really redundant, not sure if align with other CRM on this is the good choice to make, how about `Price` ?
