### ISSUE TITLE
On RecordTable, if I have no records, the Record Table Layout is not broken

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#2466]
We are experiencing issues with our RecordTable Layout. The root cause of the problem is that we want two behaviors that are incompatible with display: table-cell behaviors:

- If the columns are larger than the screen, we want the + button to add new viewFields to be visible at the end: 
<img width="1266" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/e8910cda-1779-47d8-a90f-9213c37ec7c7"> ==> this means we want a fixed width

- if the columns are smaller than the screen, we want the + button to take the whole width:
<img width="1266" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/5b676ac0-2822-4b5c-8d3d-fbb5a3d68030">
 ==> this means we want a 100% width

In display: block css we would do a width: 100% + min-width: 32px.
However this is incompatible with table-cell behavior that does not support it.

We have hacked it to work but it does not work when the table is loading:
<img width="1266" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/b1b8917c-fcd3-4525-9a6b-38086bc49dbf">

The proposal is to keep a table-cell display as it is BUT to compute the + column size programmatically in javascript. This should be doable in RecordTableHeader using Refs and getting width of the table and columns.

## Alternative solutions:
We could also decide to not use the table-cell display in this case but this would break other nice behaviors (alignment, nice border collapsing...) and make it complex.

**Comment by gitstart-twenty** [comment]
Hey @charlesBochet,
We noticed an issue here: When the screen width is less than the table width, some columns are hidden(as expected) but it is not possible to scroll horizontally to get to them. Also you state that "We have hacked it to work but it does not work when the table is loading:" but this is not the case?

![localhost_3001_objects_peopleV2_view=20202020-1979-447d-8115-593744eb4ead(1280 x 720)](https://github.com/twentyhq/twenty/assets/140154534/916e1cb7-8123-40bd-8f50-6d0d5b77bc23)

**Comment by charlesBochet** [comment]
@gitstart-twenty Interesting ; I cannot actually reproduce. On my end, the table scrolls horizontally. 
What browser are you using?

Yes, let's add this bug to the ticket scope too.

**Comment by gitstart-twenty** [comment]
> What browser are you using?

@charlesBochet 
![Screenshot 2023-11-20 at 07 03 21](https://github.com/twentyhq/twenty/assets/140154534/3227b371-6238-41a6-b52e-65af2f2eced6)

**Comment by gitstart-twenty** [comment]
> Yes, let's add this bug to the ticket scope too.

I'm going to check this again, perhaps something wasn't right last time
