### ISSUE TITLE
[Timebox] Support list of addresses

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#2471]
Discuss with @Bonapara @FelixMalfait

**Comment by charlesBochet** [comment]
@Weiko Let's hold on this one. We are unsure if we should support a list of address or only one
@FelixMalfait @Bonapara

**Comment by Bonapara** [comment]
As of today, we have no plans to support address lists. Closing the issue!

**Comment by charlesBochet** [comment]
@Weiko we have decided to treat address as a composite field. It won't be an array of addresses like phones, emails or links
