### ISSUE TITLE
Enable custom field type: phone

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2494]
# Scope

We have a "Phone" field type in the standard "People" object. Our goals are:
1. To enable users to add a phone field to any object.
2. To improve the design of the phone picker.

# Desired behavior

## New phone field

![CleanShot 2023-11-14 at 09 56 10](https://github.com/twentyhq/twenty/assets/19412894/484056aa-e2fd-4328-bbcc-2e0ab50c6d48)

There should be an "edit" button (in the form of a `pen icon button`) to modify the phone number. Clicking on the phone number should initiate a call.

## Design improvements

_Note the following phones are random!_

### Current behavior

![CleanShot 2023-11-14 at 10 03 50](https://github.com/twentyhq/twenty/assets/19412894/15f28836-bd2f-457b-bbaa-6c2d00521444)

### Desired behavior

![CleanShot 2023-11-14 at 09 47 37](https://github.com/twentyhq/twenty/assets/19412894/aad21fee-4e3f-41cc-8dbb-16f3d3b00d43)

1. The flag should be **16x12** instead of **24x12**
2. There should be a border to separate the two sub-items
3. The country indicator should be in light gray (if possible/not too hard)

Furthermore, the flag picker should not have a border radius:

![CleanShot 2023-11-14 at 09 51 21](https://github.com/twentyhq/twenty/assets/19412894/11365437-ae8f-4c81-9568-f519a197122a)

```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/2700
```

**Comment by praveenb4305** [comment]
Hi, I would like to work in this issue. Please let me know if I can contribute. Thanks in advance.

**Comment by Bonapara** [comment]
Hi @praveenb4305, I think Core team is handling this one Sorry 🙁

**Comment by FelixMalfait** [comment]
Closing, I will make the UI changes today. And let's keep just 1 issue to enable the custom field type
