### ISSUE TITLE
Remove cmkd package from CommandMenu

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#2495]
## Scope & Context

In the early days, we were using cmdk package to power our CommandMenu. We would like to get rid of it.

## Technical inputs

Search for `import { Command } from 'cmdk';` in the codebase. We want to remove all of these. In most cases, we use Command.XXX as a styled component base: e.g `const StyledGroup = styled(Command.Group)`. We want to replace it by: `const StyledGroup = styled.div`

However, we still want to have a nice user experience (especially regarding the arrow up and down behavior). To re-implement this, you can take a look at the arrow up and down behavior for SingleEntitySelect in `useEntitySelectScroll`

**Comment by charlesBochet** [comment]
@Kanav-Arora here you go!

**Comment by Kanav-Arora** [comment]
Thanks, I'll start working on it after completion of #2311

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
Should I wait for new design changes?

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
I have raised a PR and as discussed I have also added toggle functionality.
