### ISSUE TITLE
Include a button in table views new column menu linking to an object detail page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2496]
# Current behavior

![CleanShot 2023-11-14 at 11 01 01](https://github.com/twentyhq/twenty/assets/19412894/1279a481-597c-4e9f-8df0-2c4d12618ccd)

Users can show or hide `enabled` fields 

# Additional behavior

We want to add a button that allows users to easily navigate to the object settings page for customizing, editing, and removing fields.

![image](https://github.com/twentyhq/twenty/assets/19412894/bd107951-4f5c-4376-95c7-4d1fb1701223)

**Comment by umrkhn** [comment]
@Bonapara I would like to work on this issue.

**Comment by Bonapara** [comment]
@umrkhn, Thanks so much! Just assigned you
