### ISSUE TITLE
Style "loading more" rows on tables

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2498]
# Desired behavior

Style the newly added "Loading more" on table views (appears when there is more than 30 records)

![CleanShot 2023-11-14 at 11 35 33](https://github.com/twentyhq/twenty/assets/19412894/41f1f826-9fee-4f98-832c-bc34497ca7c8)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=1406-44830&mode=design&t=on8QtLtJT8F8jGf5-11

**Comment by qmohitsingh** [comment]
Hey @Bonapara , Could you please assign this to me? Thank you

**Comment by Bonapara** [comment]
Sure, @qmohitsingh, I've assigned this to you. Thanks!

**Comment by qmohitsingh** [comment]
hey @Bonapara , i couldn't really find Loading more.. text in the codebase, but I found Fetching more.. which is present in RecordTableBody.tsx. is this what needs to be updated? Also, I can not see this on the company's page as well it's using the new RecordTableV1.tsx

**Comment by Bonapara** [comment]
Hi @qmohitsingh, @charlesBochet would be the best person to answer your question!

**Comment by charlesBochet** [comment]
@qmohitsingh yes exactly!

**Comment by charlesBochet** [comment]
@qmohitsingh We also need to take care of the styling :)

**Comment by qmohitsingh** [comment]
> @qmohitsingh We also need to take care of the styling :)

My bad!!! I will create another PR for this. Thank you

**Comment by FelixMalfait** [comment]
@qmohitsingh do you think you could take care of styling? Or should we unassign you? Thanks!
You can use Figma in dev mode to view css

<img width="1146" alt="Screenshot 2023-12-20 at 09 07 22" src="https://github.com/twentyhq/twenty/assets/6399865/c42617e8-c4eb-485c-ab29-0064143bec69">

**Comment by qmohitsingh** [comment]
@FelixMalfait yeah,  I'll handle this. I was by with my final, so apologies for the delay. Thanks for your understanding.

**Comment by FelixMalfait** [comment]
Great thanks a lot @qmohitsingh, no worries!

**Comment by suman-somu** [comment]
Are you working ?

**Comment by charlesBochet** [comment]
Hi @suman-somu! Most of the team was off during the Christmas break
I have left comments on your PR :)
