### ISSUE TITLE
Adjust the tag font weight in objects settings

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2500]
# Scope

Page: `/settings/objects`

# Current behavior

Font-weight is: medium

![CleanShot 2023-11-14 at 12 12 51](https://github.com/twentyhq/twenty/assets/19412894/b9b4ebad-d8a4-464c-8cf4-1bb1e861963b)

# Desired behavior

Font-weight should be:  regular

![CleanShot 2023-11-14 at 12 13 55](https://github.com/twentyhq/twenty/assets/19412894/6d7d69b5-2fdf-4ae8-b529-e094a4be9305)

**Comment by qmohitsingh** [comment]
hey @Bonapara, Could you please assign this to me? Thank you

**Comment by Bonapara** [comment]
@qmohitsingh, I assigned you with the other issue, do you want this one as well? Thanks

**Comment by qmohitsingh** [comment]
Yeah @Bonapara , I would love to do this as well!!

**Comment by Bonapara** [comment]
@qmohitsingh, assigned you as well then, thanks!

**Comment by charlesBochet** [comment]
Closing as this has been solved. Thank you!
