### ISSUE TITLE
No location found to create a normal user

### ISSUE THREAD

**Issue by Teamz00n** [twentyhq/twenty#2512]
No location found to create a normal user
I didn’t find the module to create a normal user in the settings. Could you please point it out? Thanks!

**Comment by charlesBochet** [comment]
Hi @Teamz00n, I'm just seing this issue now. What do you mean, create a normal user in the settings? 
If you want other person to join your team, you can use the invite link provided in Settings > Workspace Members

**Comment by charlesBochet** [comment]
@Teamz00n I'm closing the issue, feel free to reopen it if it doesn't solve your problem :)
