### ISSUE TITLE
Find a plugin / eslint-rule or anything that can prevent vscode to add duplicate imports automatically

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2515]
## Scope & Context

VSCode can import automatically anything that is missing in imports that we use in the code.

## Technical inputs

Right now we have a lot of issues with this feature, it imports two times or more the same missing function / hook and we have to manually remove the duplicates.

Example : 

```ts
import { Key, Key } from 'ts-key-enum';
```

We can create our own rule in the package `eslint-plugin-twenty`, it should auto fix this problem.

**Comment by BalanaguYashwanth** [comment]
I think this issue is closed
