### ISSUE TITLE
Redirect to workspace creation if user isn't associated with any workspace

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2524]
Related to #4036 

# Current behavior
<img width="1488" alt="Screenshot 2023-11-15 at 16 16 08" src="https://github.com/twentyhq/twenty/assets/6399865/972c0348-199e-4111-9d1c-99f815d3bb4e">

# Desired behavior
We should see the workspace creation modal:
<img width="759" alt="Screenshot 2023-11-15 at 16 40 41" src="https://github.com/twentyhq/twenty/assets/6399865/1d224e23-008c-4364-ae08-a15286aea7cb">

**Comment by dev-DTECH** [comment]
Hey @FelixMalfait , I want to work on this can you assign me this issue.

**Comment by FelixMalfait** [comment]
Assigned @dev-DTECH thanks a lot!

**Comment by martmull** [comment]
This should not happen anymore, users are either associated with a workspace, or deleted
