### ISSUE TITLE
I shouldn't have to type "enter" to save cell content

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2526]
##  Bug Description
If I modify a cell then click somewhere or escape the cell, it reverts back to its previous state.
In order to save I have to click "enter"

## Expected behavior
We should attempt to save by default. We don't want the cell content to be lost!

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait 
Can I work on this?

**Comment by FelixMalfait** [comment]
@Kanav-Arora of course! thanks a lot

**Comment by charlesBochet** [comment]
@FelixMalfait @Kanav-Arora I think this is incorrect.

We should only save when we leave the cell and not when we type. This allow us to put some validation rule on the cell on mid-term.
For instance, if we want to validate that an EMAIL field is containing an email:
-  we let the user type whatever he wants
- and when he leaves the cell the cell, we trigger a validation logic to check that what has been typed is an email.
- if it is valid, we persist in DB
- if it is not, we can either return an error (show a red border on the cell and leave it open) or we can put back the previous value, or convert it as best as we can (notion behavior)

IMO, we shoud save when hitting "Enter", "Tab", "Arrow up/down/left/right", "Shift+Enter", **"Click outside"** and put back previous value when hitting "Esc"

I think the "Click outside" save has not been implemented

@Bonapara I know you also thought about it

**Comment by FelixMalfait** [comment]
Yes I agree we don't necessarily need to save on each character because it would make validation tricky. Sorry @Kanav-Arora I should have been more explicit.
I just disagree with the behvior for escape @charlesBochet ; we should still save on escape imo.

**Comment by charlesBochet** [comment]
Ok, let's do that then, we save for all keyboards and click behavior that lead to closing the cell. 
@Kanav-Arora could you take another shot? Sorry about the confusion!

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet @FelixMalfait 
I agree I also saw that due to prop drilling of onChange handler, app was getting bit slower.

I'll proceed with it so are we creating a new issue for it?
Just to be clear in new issue
- I'll create validation functions for various types of inputs
- Check the validation, if passed update the state else show red border

Now this validation check will be done on all save criteria i.e Clicking outside, Enter, Tab, Shift+Tab and esc will simply revert the field to previous state.

Please correct me if I'm wrong and if any changes specify in the new issue to avoid any miscommunication.

**Comment by charlesBochet** [comment]
@Kanav-Arora 
No, the scope of the ticket is not to improve validation, we are not completely sure on how we would handle it on the technical design side.

The scope of this ticket is to save the value on "Esc" or "click outside" events. By saving, I mean that we should have exactly the same behavior as when we hit "Enter"

**Comment by Kanav-Arora** [comment]
Cool 
I'll start working on it

**Comment by Kanav-Arora** [comment]
Closing my current PR for this as due to change of approach, I'll be raising a new PR.

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
Please review PR #2750
