### ISSUE TITLE
Cannot refresh with cmd + r in table

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2533]
## Bug Description

When in table focus mode, we cannot refresh the page with cmd + r, maybe use other shortcuts as well.

## Expected behavior

If no useful shortcut is detected on the table, then just allow the default browser shortcut to work.

## Technical inputs

See maybe in `RecordTableCellSoftFocusMode` component in the `useScopedHotkeys('*',`

**Comment by CodeVibranium** [comment]
Hello @lucasbordeau ,

I've successfully cloned the repository and followed the setup documentation, which I found to be very comprehensive and helpful. The backend installation went smoothly and is functioning correctly. However, I encountered an issue during the process that I need assistance with. Could you please provide some guidance?


<img width="1044" alt="Screenshot 2023-11-17 at 6 05 35 PM" src="https://github.com/twentyhq/twenty/assets/62259994/d583be24-592d-43f3-aea0-d7ef8f138e69">

<img width="1440" alt="Screenshot 2023-11-17 at 6 05 16 PM" src="https://github.com/twentyhq/twenty/assets/62259994/29e983e1-61ab-4cdb-b3df-0d593f05467d">
