### ISSUE TITLE
Referer/origin table and field

### ISSUE THREAD

**Issue by GP-S** [twentyhq/twenty#2534]
## Scope & Context

On our CRM we use to have a custom field linking to track how we met ou lead (from an event, via a website subscription, partner network, cold call, etc...). It helps to have context but more importantly it provide a statistical data  on the efficiency of our methods.

**Example:** 
```
For instance when creating an opportunity I would like to add a field explaining how I got this lead , or when I add people I could have a field helping me to remember when we met the first time.
```

## Current behavior

Currently we can use note to add referer. The issue with notes is that they won't help to filter by refere nor provide informations on how many opportunity I got from this or this partner nor the lead's maturity .
```

**Comment by GP-S** [comment]
looking forward 🤩

**Comment by FelixMalfait** [comment]
Hey, custom fields are there and the big migration is finally over! It's not perfect (we don't have all custom field types yet) but should be good enough. 
I'm closing this but feel free to re-open an issue if you have feedback

**Comment by GP-S** [comment]
> @FelixMalfait UX is not that bad ! It is even pretty good if you compare to some other CRM.
> 
> Yes I can create custom object but I can't define a custom field that refers to a custom object : I created a custom object nemed _referer_ and I want my _Opportunities_ to have a _referer_ field. I may miss something but I did not find any way to do that.

My bad I missed your last sentence. Okay #2764 seems to do what I want !

**Comment by FelixMalfait** [comment]
I'm not sure if #2764 would be needed, or if you're just missing the ability to creating a relationship between 2 objects (in that case between the opportunity object and referrer). The "relationship" field type is created but read-only for now and it's not possible to create a new relationship. But that should come soon!
Another field type coming soon that could help is this one: https://github.com/twentyhq/twenty/issues/2329 ; then you can create views based on that
