### ISSUE TITLE
No job title filter on people list view

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2541]
I wanted to filter people by job title but the filter isn't available.

<img width="269" alt="Screenshot 2023-11-16 at 16 32 04" src="https://github.com/twentyhq/twenty/assets/6399865/1e327762-2153-460f-81b6-c9cd5980ca9f">

**Comment by dev-DTECH** [comment]
@FelixMalfait , It is there for me can you mention the steps to recreate this?
![image](https://github.com/twentyhq/twenty/assets/55497045/a32cb5fd-7a5b-4347-a44e-74701f46dea0)

**Comment by FelixMalfait** [comment]
@dev-DTECH mmh it seems it's been fixed then. Thanks a lot! Closing the issue
