### ISSUE TITLE
Search seems to be very slow in production

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2542]
It takes 1.7s on average for the server to respond when I type a name in the command bar.

Is there an easy way to improve this performance?

**Comment by charlesBochet** [comment]
Closing this issue as we have improved performance.
We also have an issue for indexation: https://github.com/twentyhq/twenty/issues/3708

Other techniques that will be implemented:
- relation specific eager loading to remove useless join in search (related to https://github.com/twentyhq/twenty/issues/4399)
- group query by object into 1 queries, we already have created a hook to do that, related to https://github.com/twentyhq/twenty/issues/3298
