### ISSUE TITLE
IconPicker component not working correctly  

### ISSUE THREAD

**Issue by nimraahmed** [twentyhq/twenty#2551]
## Bug Description

Clicking the icon picker button opens up a box of icons to search/select, but the placement is not right, i.e., the search box opens up at the end of the container. 

Example: 
![image](https://github.com/twentyhq/twenty/assets/50912134/345ec2b4-521a-491f-ba5a-0e90265dc656)

## Expected behavior

This is what it should actually look like:

![image](https://github.com/twentyhq/twenty/assets/50912134/2c8c494a-8708-4cbe-8be0-54d29a1b5091)

**Comment by nimraahmed** [comment]
Yep I've fixed this, will push it in the next PR

**Comment by nimraahmed** [comment]
@charlesBochet should we see the selected icon when we're searching for another one? like so:

![image](https://github.com/twentyhq/twenty/assets/50912134/c9bf0b80-eb8a-449b-9ef8-40a9308b5971)

**Comment by charlesBochet** [comment]
@Bonapara, true this seems a bit weird to me too that we keep seeing the selected icon even if it does not correspond to the search
