### ISSUE TITLE
Spacing issue in Entity Title Double Text Input

### ISSUE THREAD

**Issue by nimraahmed** [twentyhq/twenty#2562]
## Bug Description

the entity title double text input is not wide enough to accommodate the entire input/placeholder text: 

![image](https://github.com/twentyhq/twenty/assets/50912134/d19185aa-07bf-4922-8fa0-4a6882ed4350)

## Expected behavior

The input text areas need to be bigger to not cut off the text

**Comment by hemu-git-hub** [comment]
hi @nimraahmed  can you assign me to this issue ?

**Comment by nimraahmed** [comment]
@hemu-git-hub hi, thank you so much for your interest in the project. I'm already working on this issue, but maybe you can keep an eye out for more [good first issues](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)

**Comment by nimraahmed** [comment]
@charlesBochet the calculated width for the input/placeholder is a little smaller than the width needed to display the full text. My approach for this was to change:

`width: ${({ width }) => (width ? `${width}px` : 'auto')};` in EntityTitleDoubleTextInput.tsx

and add some padding based on the width, like so:

`width: ${({ width }) => (width ? `calc(${width}px + 1.5%)` : 'auto')};`

this is what i get then:  

![image](https://github.com/twentyhq/twenty/assets/50912134/a8183249-1728-43db-a58f-cac8d2aa6fbb)
