### ISSUE TITLE
[ESLint rule] prevent useRecoilCallback without a dependency array

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2570]
## Scope & Context

We can currently use `useRecoilCallback` without passing it a dependency array, this is the source of many silent errors.

## Technical inputs

We want to enforce the usage of dependency arrays for each `useRecoilCallback` with a new ESLint rule in our package.

**Comment by boringlyBoring** [comment]
I want to take this up.

**Comment by anthonygenovese** [comment]
Is this being worked on? 
If not, I'll do it.

**Comment by charlesBochet** [comment]
@anthonygenovese Nobody is working on it! Thank you :)

**Comment by anthonygenovese** [comment]
Understood. I'll get it done.

**Comment by FelixMalfait** [comment]
Hint: Use https://www.npmjs.com/package/eslint-plugin-react-hooks which as `exhaustive-deps` deps rule (set `additionalHooks` config)

Also import rules-of-hooks? It seem that eslint-plugin-react-hooks is already in package.json but not in eslint config? Or maybe I missed something

**Comment by anoopw3bdev** [comment]
I would like to work on this

**Comment by FelixMalfait** [comment]
@anoopw3bdev assigned! thanks

**Comment by anoopw3bdev** [comment]
I had a look at this issue, the configurations for custom hooks is already added in the eslint configuration file.
<img width="426" alt="Screenshot 2024-02-08 at 10 25 59 PM" src="https://github.com/twentyhq/twenty/assets/44577841/a79bdf2e-af66-4b2e-bc40-9aca2724e507"> 

I couldn't find anything on the internet other than these existing configuration. Appreciate additional inputs and thoughts .

**Comment by lucasbordeau** [comment]
@charlesBochet Yes !
