### ISSUE TITLE
[Timebox] feat: can create relations between core entities and standard object records

### ISSUE THREAD

**Issue by magrinj** [twentyhq/twenty#2581]
## Scope & Context

This ticket is following the new implementation of flexible back-end well described here: #1142 
The goal is to add ability to create relations between core entities and workspace entities.
This should be only faisable manually and not dynamically.

## Current behavior

Doesn't seem to be possible.

## Expected behavior

User can create a relation between a core entity and a workspace entity and query this relation in both ways.

## Technical input

- Should this be related to the datasource ?

**Comment by FelixMalfait** [comment]
Closing as it's marked as "done" in Product Development board
