### ISSUE TITLE
[Timebox] feat: enhance the backend seed

### ISSUE THREAD

**Issue by magrinj** [twentyhq/twenty#2582]
## Scope & Context

This ticket is following the new implementation of flexible back-end well described here: #1142 
We already have a seeding mechanism, but this one is not really clean and is not type safe.

## Current behavior

Working but not user friendly and type safe.

## Expected behavior

We should create functions like factories, that are building the seed queries and verify the type safety of the entities.

**Comment by charlesBochet** [comment]
This has been completed, closing this issue :)
