### ISSUE TITLE
New Object Field - Step 2 & Object Field Edit - Relation field type is not showing in Field Type select

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#2585]
## Context

See #2340

## Current behavior

In New Object Field - Step 2 and Object Field Edit pages, the "Field type" select is showing the "Select" field type but not the "Relation" field type.

## Expected behavior

The "Select" field type is not included in the options as it is not ready.
The "Relation" field type is included in the Object Edit page options (don't display it for now in the New Object Field - Step 2 page for now).

## Figma

![Image](https://github.com/twentyhq/twenty/assets/3098428/ecf53b89-1899-43b1-a270-620c0637f52d)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=14407-174415&mode=design&t=nJ2HHxP3xoTZJB7T-11

**Comment by charlesBochet** [comment]
Show it on ObjectFieldEdit (but disabled)
But remove it from Field New
