### ISSUE TITLE
Put ObjectMetadataItem in recoil state to avoid massive re-renders

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2596]
## Scope & Context

The `useFindManyObjectMetadataItems` hook returns the result of a query everywhere it is called and it is called from many places. Causing many re-renders.

## Current behavior

We currently rely on the returned data of a useQuery for our subsequent hooks.

## Expected behavior

We want to store the return of the useQuery in a recoil state, and then use a selectorFamily on top of it to have a more flexible management of re-renders and subscription.

**Comment by charlesBochet** [comment]
@lucasbordeau Closing this one as I have implemented it
