### ISSUE TITLE
Setup guide Postgres setup has wrong command

### ISSUE THREAD

**Issue by RohitLakh** [twentyhq/twenty#2601]
## Scope & Context
Wrong commands in project setup using `yarn` at https://docs.twenty.com/contributor/local-setup/yarn-setup

<img width="876" alt="image" src="https://github.com/twentyhq/twenty/assets/34619861/aa0f7dc2-0586-43a7-b6b3-c0ae44893b1f">

The right command was 
```
make provision-postgres-docker 
```

**Comment by RohitLakh** [comment]
It feels like the changes are live on the code but the version is yet to release?

**Comment by brendanlaschke** [comment]
Yes that's the case with release 0.2 the docs will be updated ...

**Comment by charlesBochet** [comment]
This has been fixed! Thanks for reporting it
