### ISSUE TITLE
Unused packages: server

### ISSUE THREAD

**Issue by brendanlaschke** [twentyhq/twenty#2629]
## Scope & Context

We currently have large node_modules folder and some packages in yarn.lock which shouldn't be there anymore (e.g. `@prisma/engines`) 

## Technical inputs

Here a list of packages (for the server package.json) which are not imported / used and can be removed? cc @charlesBochet 

- @paljs/plugins - (package causing the prisma packages installation)
- @types/date-fns (date-fns includes types)
- reflect-metadata
- ms
- @casl/ability (do we still need this? - at the moment it is not used)
- all the corresponding @types packages

**Comment by RobertoSimonini1** [comment]
hi, @charlesBochet could I work on this issue?

**Comment by charlesBochet** [comment]
@RobertoSimonini1 Thanks you, I have merged your PR. Are we missing other packages we could remove?

**Comment by RobertoSimonini1** [comment]
Thanks @charlesBochet, I've just checked the server dependencies and I actually found out that there are others unused depencencies, here is the list:
- @apollo/server
- @nestjs/apollo
- @nestjs/serve-static
- @sentry/tracing
- @types/lodash.merge
- add
- apollo-server-express
- dataloader
- graphql-yoga
- jest-mock-extended
- lodash.isequal
- lodash.merge
- passport-local
- postinstall-postinstall

Should I open another PR to remove those dependencies?

**Comment by brendanlaschke** [comment]
Great you found some more :) 

I think we can also remove some packages from the front dir:
* @tanstack/react-virtual
* @types/intl-tel-input

**Comment by charlesBochet** [comment]
Closing this issue, good one!
