### ISSUE TITLE
Filter the opportunities "Point of contact" field

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2632]
# Current behavior

![CleanShot 2023-11-22 at 11 17 36](https://github.com/twentyhq/twenty/assets/19412894/6e3eb146-f72a-400a-99b8-2e86af64ecae)

# Desired behavior

1. Filter the list to display only the employees of a company. For example, if the company is "Figma," only Figma's employee (Dylan Field in the seed) should be shown.

![CleanShot 2023-11-22 at 11 19 50](https://github.com/twentyhq/twenty/assets/19412894/b572f071-10f5-445d-bd53-4dd77336b9e4)

2. Add an "Add People" button at the bottom of the menu if there are no matching records in the search or if there are no employees associated with the company.

See Companies show pages behavior:

![CleanShot 2023-11-22 at 11 45 43](https://github.com/twentyhq/twenty/assets/19412894/c9241655-8d06-48bb-a6d8-59236e15e889)

If there are no employees linked to the company, display only the "Add new people" button, excluding the search and result section.

When a new person is created, it should be automatically associated with the corresponding company (the one from the opportunity).

**Comment by jioh-kim** [comment]
Hi @Bonapara is anyone working on this? If not, I'd like to pick it up. Thanks!

**Comment by jioh-kim** [comment]
Could you assign it to me? :) Thanks

**Comment by Bonapara** [comment]
Just assigned you @jioh-kim. Thanks!

**Comment by charlesBochet** [comment]
@jioh-kim any update on this one? :)

**Comment by Bonapara** [comment]
@charlesBochet, Discord update received, this issue is available for assignment

**Comment by a-kud** [comment]
is this issue available for grabs?

**Comment by Bonapara** [comment]
Hi @a-kud, I think @gitstart-twenty is handling this one!

**Comment by FelixMalfait** [comment]
Re-opening as this was lost during refacto 🥲 - not convinced the implementation in #3191 was the right long-term approach. Would be great if we had a more generic design pattern for this that was driven by the backend.

E.g. use Options column in Field Metadata (on the record representing the point of contact field), something like `{ filter:  {sourceField: 'companyId', targetField: 'companyId', operand: 'eq'}}`)
