### ISSUE TITLE
The first column of objects table should be fixed

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2657]
# Current behavior

When scrolling horizontally, it is possible to lose sight of the first column, which contains the record identifiers.

![CleanShot 2023-11-22 at 18 21 57](https://github.com/twentyhq/twenty/assets/19412894/7b674bec-4340-4552-8240-dc4402a12720)

# Desired behavior

Fix the first column. Horizontally scroll the other columns on the left under the first column. Add the `light` box-shadow.

![CleanShot 2023-11-22 at 18 41 20](https://github.com/twentyhq/twenty/assets/19412894/e0f1e17f-97c3-42a0-bfe1-8a2dc9ca3b57)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=15958-80931&mode=design&t=Po49evZYh3XZYIxG-11

**Comment by tarnveerSingh** [comment]
Hey @Bonapara .! I would like to work on it, can you please assign and is there a timeline on this task ( when it needs to done or anything like that ). Last thing, just wanted to clarify the issue - First column needs to be sticky while scrolling to the left and need to add light box-shadow on the first column.?

**Comment by Muralidhar22** [comment]
Hi @Bonapara could you please assign me this issue.

**Comment by FelixMalfait** [comment]
Thanks @Muralidhar22!

**Comment by charlesBochet** [comment]
@Muralidhar22 any update on this one?

**Comment by Muralidhar22** [comment]
Hi @charlesBochet, haven't started on this, if we have time until 20th dec IST, will try to raise an MR or please re assign

**Comment by charlesBochet** [comment]
this week is perfect, there is no rush on this one. It will be part of 0.2.3, we can ship 0.2.2 without it :)

**Comment by lucasbordeau** [comment]
@Bonapara Would be nice to have the same behavior for the label row ! 
<img width="1268" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/bae2db6b-d35d-4f62-9c07-8dbfb42725e8">

**Comment by FelixMalfait** [comment]
@lucasbordeau agreed! Created #3156
