### ISSUE TITLE
New field type: formatted address

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2661]
# Context

We want to create a new field type "formattedAddress" = street + city + country + ...
The implementation should be very similar to "fullName" = first name + lastname

# Frontend

### Edit mode
![CleanShot 2023-11-22 at 18 59 49](https://github.com/twentyhq/twenty/assets/19412894/8108e4f9-31b2-4c66-9643-493da4b3b942)

Link to Figma: [figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=15828%3A60465](https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=15828%3A60465&mode=dev
)

### Read-only mode
Concatenate:  Street, City, Country
If not street then: City, Country
If no city then Country

## Backend
```
addressStreet1
addressStreet2
addressCity
addressPostcode
addressState
addressCountry
addressLat
addressLng

```
Note: lat/long can't be populated for now but we'll soon create a backend a follow-up ticket with Google Maps (or other provider) dropdown that will enable filling this

Bonus point (optional): Add optional Google autocomplete https://developers.google.com/maps/documentation/javascript/place-autocomplete

**Comment by Bonapara** [comment]
# Custom address field

Here is also the design for the `address field type` to create a custom address field in settings.

![image](https://github.com/twentyhq/twenty/assets/19412894/bb0cc57b-a831-4090-8f61-2b4af169edac)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=15964-91182&mode=design&t=0ARQwG9ztW9zC0Zf-11

**Comment by lakshay-saini-au8** [comment]
@FelixMalfait I would like to work on this issue

**Comment by FelixMalfait** [comment]
@lakshay-saini-au8 fyi this is a pretty big task. Happy to assign to you — thanks a lot!
Let us know if you need help (you can ask on Discord).

**Comment by lakshay-saini-au8** [comment]
@FelixMalfait 
Is anyone else is working on this

**Comment by FelixMalfait** [comment]
@lakshay-saini-au8 nobody's working on this no! Sorry I didn't assign it after my message
Thanks again!

**Comment by capaj** [comment]
I started working on this issue.

**Comment by FelixMalfait** [comment]
Thanks @capaj!

**Comment by FelixMalfait** [comment]
@capaj feel free to reach out on Discord if you need help, backend is fairly complex

**Comment by capaj** [comment]
I will not be able to finish this, but if anyone picks it up, feel free to start where I left off using my WIP commit: https://github.com/capaj/twenty/commit/671178352d264d373cd4c11a67e32e0a11d93601

**Comment by FelixMalfait** [comment]
@capaj thanks for this already 🙏

**Comment by antoniopresto** [comment]
I'm going to start this this weekend 👍🏽

**Comment by Bonapara** [comment]
Thanks @antoniopresto!

**Comment by FelixMalfait** [comment]
@antoniopresto fyi we're going to re-organize the folder structure this week-end so if you want to re-use @capaj's work and avoid conflicts, maybe you could raise a v1 PR (e.g. no frontend just backend / with feature flag on the object) and then raise a v2 later during the week

**Comment by antoniopresto** [comment]
Im sorry, I ended having no time to work on this

**Comment by rostaklein** [comment]
Id liek to tackle this one :) Dont worry @antoniopresto your work wont come wasted. Ill try to reuse your WIP branch.

**Comment by Bonapara** [comment]
Thanks @rostaklein, just assigned you!
