### ISSUE TITLE
Introduce basic feature flags framework

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2693]
# Goal 
In order to ship the messaging feature (logging emails), we need to pass the Gmail API verification process which requires that we ship the feature **in prod**. That means we need to setup a feature flag system! That will be useful for many other things. 

The feature flag can be set:
- at the environment level, with prefix FLAG_xxx
- at the backend/database level, for a given workspace
And the value at the environment level takes precedence over the backend value. I.e. if both are set, the the environment value should prevail.

# Data model
### core/featureFlag
Fields:
- id (unique, primary)
- key (text, not null)
- value (boolean, default false)
- workspace_id (text, not null)

Constraint:
- unique {key + workspace_id } 

# Usage

### frontend
We already have a clientConfig endpoint so I think we don't need to create a new hook nor a new endpoint.
We can just nest `featureFlags` as property of `clientConfig`.

### backend
The value of a feature flag can be checked with `featureFlagService.get("myFeatureFlag")`

# Other considerations
- We don't want to use a feature flag system like Flagsmith because we want to keep the install simple for people who self-host, therefore we always try to limit the number of third-party services.
- On the backend side, it would be nice to consider caching the database request for a few minutes at least (see a related PR that introduces caching here: https://github.com/twentyhq/twenty/pull/2620). 
- It's not always easy to determine what fits in the "env variable category" and what fits in the "feature flag category". I think the two questions we need to ask are: do we need to access this value before the app is fully bootstrapped? Is there any interest in changing this setting at the workspace level? I don't feel like any existing environment variable really needs to be migrated 
- It would be nice to add a page in the documentation
- No need to consider setting a flag at user-level
- No need to consider multivariate flags, a simple boolean state is enough (more can always be done later if needed)
- There is no "source of truth" for existing flags across in the above setup - a flag value can be set for any key. This can always be improved later if needed. I think if later we'll probably do a json that lists flags, + a page in workspace setting where users can manually toggle flags that have `"public": true`

**Comment by charlesBochet** [comment]
This has been implemented! Congratulations @bosiraphael!
