### ISSUE TITLE
Enable phone field type

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#2700]
## Context

See #2494 

For this issue:
- Display a preview for the `PHONE` field type.
- The preview by default displays: +1234-567-890.
- Add `SettingsObjectFieldPreview` stories for the "PHONE" field type.

## Figma

![Image](https://user-images.githubusercontent.com/19412894/282717894-484056aa-e2fd-4328-bbcc-2e0ab50c6d48.png)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=15330%3A137231&mode=design&t=iJT6qeSb4rQhANlX-1

**Comment by FelixMalfait** [comment]
Most of the work has been done for this, it should be quick to enable it!
