### ISSUE TITLE
Create MultiSelectFieldDisplay component

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#2705]
## Context

See #2329 

For this issue:
- Implement the `useMultiSelectField` hook
- Implement the `MultiSelectDisplay` and `MultiSelectFieldDisplay` components

## Figma

<img width="785" alt="image" src="https://user-images.githubusercontent.com/19412894/280068461-cda052ab-016f-4b22-8a91-1c769fe552bb.png">

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=13884-59286&mode=design&t=avVSH5fvDzQPdLL9-11

**Comment by ARSHIL1804** [comment]
I would like to work on this @thaisguigon. Please assign it to me.

**Comment by Bonapara** [comment]
Linked to #4237

**Comment by FelixMalfait** [comment]
I think this has been completed in #4887 by @martmull, closing (we need to remove the feature flag though, I can't see it on app-main?)

**Comment by martmull** [comment]
Yes there is a feature flag
