### ISSUE TITLE
Invoking Command Menu should close Keyboard Menu

### ISSUE THREAD

**Issue by Kanav-Arora** [twentyhq/twenty#2727]
## Bug Description

A clear and concise description of what the current behavior is.
Please also add **screenshots** of the existing application.

**Example:** 
```
When Command Menu is invoked, if keyboard menu is open it should close and vice-a-versa.
Currently they are getting overlayed.
```

## Expected behavior

A clear and concise description of what the expected behavior is.

**Example:** 
```
Only one dialog should be visible at a time.
```

## Technical inputs

**Example:** 
```
Requires change in toggle handler.
```

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
I'll start working on this after #2622 and #2528 gets merged.

**Comment by charlesBochet** [comment]
@Kanav-Arora One merge, one left!

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
Raised a PR to fix this
