### ISSUE TITLE
Clean "edges" typing for object records

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2731]
Right now, in the FE, queries are returning paginated object:
companies { edges: [ nodes { people

We want the frontend to manipulate companies: people

Once done, we can type the frontend with standard objects: Company { people: Person[] }

**Comment by charlesBochet** [comment]
Places to add/remove nesting:
- useFindManyRecords
- useCreateManyRecords

- optimisticEffect : read/write from cache
- modifyCache:  write in cache
- optimisticResponse for createMany?

**Comment by charlesBochet** [comment]
Introduce standards types (see GraphQLView that should become View)

**Comment by lucasbordeau** [comment]
Duplicate of https://github.com/twentyhq/twenty/issues/2781
