### ISSUE TITLE
Open file in new tab and download with correct filename

### ISSUE THREAD

**Issue by brendanlaschke** [twentyhq/twenty#2739]
## Scope & Context

The introduction of attachments brings a problem: We want to open files in a new tab with the same name as we upload them. 

## Current behavior

Currently, files are stored with a random identifier e.g. `3fecdfc0-a798-4581-906f-5cbff225a5f7.pdf`. #2716 adds attachments and opens files in a new tab but only provides them with an incorrect name (`3fecdfc0-a798-4581-906f-5cbff225a5f7.pdf`) instead of `MyFileName.pdf`. 

## Expected behavior

We can download files with their correct name if opened in a new tab.

## Technical inputs

fetch & open via url isn't a solution on the frontend: https://stackoverflow.com/questions/58721150/open-a-pdf-in-a-new-tab-and-download-with-file-name-in-angular 

Maybe we could add the filename to the URL requested from the server to provide the filename? like
`@Get('*/:fileId/:fileName?')`

**Comment by charlesBochet** [comment]
@brendanlaschke I will play with the feature this week-end and post an educated feedback on this ticket!

**Comment by BalanaguYashwanth** [comment]
Can i know the feedback ?

**Comment by FelixMalfait** [comment]
Good point but closing in favor of https://github.com/twentyhq/twenty/issues/4115 for now - since we're going to store email attachments it's good to increase security on that endpoint :)

Probably later we'd included an embedded file viewer for the most common types (images/pdf)
