### ISSUE TITLE
Refactor RelationPicker, SingleEntitySelectBase and MultipleEntitySelect to use SelectableList

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#2747]
## Scope & Context

We have introduced a `SelectableList` component to easily track selection with keyboard (arrow up and down)
We are currently using it on CommandMenu.

We want to use it on RelationPicker, SingleEntitySelectBase and MultipleEntitySelect

## Technical inputs

- improve SelectableList API to provide a HotkeyScope and store it in its state (right now we have hard coded CommandMenu one)
- use it on RelationPicker
- use it on SingleEntitySelectBase
- use it on MultipleEntitySelect

**Comment by Kanav-Arora** [comment]
I'll start working on it

**Comment by charlesBochet** [comment]
Yes that could be nice.
in useSelectableList, you could add a onEnter callback as part of the SelectableList API (you will need to store it in a RecoilState see how we do it for useObjectFilter for example) ==> add setOnEnter as part as return of useSelectableList

Then you can add a "Enter" scoped hotkey recoilCallback in useScopedHotkey. that would trigger this onEnterCallback with selectedItemId ==> useScopedHotkey('Enter', useRecoilCallback(({snapshot}) => () => { onEnter(selectedItemId) }

Not sure I'm very clear! Let me know if you need more information

**Comment by Kanav-Arora** [comment]
No thanks I'll figure the approach just wanted your views on it

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
I can see there's no code for onEnter HotKeyScope but it accepts only one function which will be called onEnter now please guide that if each item has different onEnter functions so should I create different state for that and keep the list onEnter function 
or 
should I delete the universal onEnter state and keep only individual onEnter state

I came up with below solution,
- There will be an onEnter function on List (which is already in the code)
- There will be an onEnter for individual items
- Now onEnter key press, if there's an individual function then that would be called else universal.

With above approach this list can be used in both the cases were each item has different onEnter (like CommandMenu) or with onEnter (like SingleEntitySelectBase)

**Comment by charlesBochet** [comment]
@Kanav-Arora I think we are happy with one onEnter function by selectableList for now, which is set on the selectableList globally. What is the case where we we would need to have multiple ones?

**Comment by Kanav-Arora** [comment]
> @Kanav-Arora I think we are happy with one onEnter function by selectableList for now, which is set on the selectableList globally. What is the case where we we would need to have multiple ones?

In CommandMenu we need onEnter different for each item

**Comment by charlesBochet** [comment]
If we want to implement individual ones, we need: 
- either to store an array of onEnter in recoil (which I want to avoid for now, we should not even be storing functions in recoil)
- either register a "Enter" hotkey for each component. I'm worried many would be triggered at the same time and that this would also cause re-render

**Comment by charlesBochet** [comment]
Ok, I think this has been actually fixed recently by @gitstart-twenty. Take a look at the code on main, we have one global onEnter function for the commandMenu

**Comment by Kanav-Arora** [comment]
Yes so how should I proceed for CommandMenu?

**Comment by charlesBochet** [comment]
You should have nothing to do, it has already been done (appart from the bug you found with no item being selected)
