### ISSUE TITLE
Fix Sentry implementation

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2751]
Sentry has been implemented as a log driver and not as an exception handler.

We should:
- catch errors and pass them to Sentry through Sentry's captureException method and not captureMessage
- not log info/debug/verbose/log messages to Sentry (they should be logged to the console instead)

Not sure how to refactor this (e.g. several LOGGER_DRIVERS with different levels? or refacto Sentry just as an exception handler?) Needs an investigation...

**Comment by charlesBochet** [comment]
This has been completed, closing this issue :)
