### ISSUE TITLE
I should be able to use "enter key" to navigate through signup/login/onboarding forms

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2755]
As of today the "enter key" doesn't work to these forms.
We should allow user to signup exclusively with the keyboard, without having to click.

**Comment by PaulaPerdomo** [comment]
Hi @FelixMalfait, can I be assigned to this issue?

**Comment by FelixMalfait** [comment]
Yes of course thanks a lot @PaulaPerdomo!

**Comment by charlesBochet** [comment]
This has been completed, closing this issue :)
