### ISSUE TITLE
I should be able to change my password in settings

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2756]
Example from Slack 
(compatible with Magic Link / Reset password form if user doesn't use password)+

<img width="640" alt="Screenshot 2023-11-28 at 18 23 27" src="https://github.com/twentyhq/twenty/assets/6399865/59059df5-9f3d-48eb-b040-915ce6cc2f08">

**Comment by Bonapara** [comment]
Replace by #3245
