### ISSUE TITLE
Fix broken docs build (impacting CI)

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#2762]
## Scope & Context

On every PR we run CIs. Since the big Oct/November refactoring many CI are broken. We are already covering front CIs in other tickets but we still need to fix server CI and docs CI.

While server CI might be a bit hard to troubleshoot, I believe the docs CI should be not that hard. This ticket is about fixing it

## Technical inputs

Right now, it's failing:
<img width="1050" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/0230c7f9-94af-49e7-9525-45c322f3cd9b">

Example: https://github.com/twentyhq/twenty/actions/runs/7030386923/job/19131150072?pr=2683

Locally, go to docs and try to build it using `yarn build`. I think you should get the same error. Fix the error and we should be good to go!

**Comment by nimraahmed** [comment]
hi @charlesBochet, i'll take care of this!

**Comment by charlesBochet** [comment]
Thank you!

**Comment by nimraahmed** [comment]
@charlesBochet fixed in PR #2771
