### ISSUE TITLE
Fix date equals filtering

### ISSUE THREAD

**Issue by martmull** [twentyhq/twenty#2765]
Filtering on dates does not work:

`filter: { and: [{createdAt: {eq: '2023-07-14T15:09:17.679Z'}}]}` returns 0 values even if such a record exists in the db

**Comment by FelixMalfait** [comment]
Filtering seems to be expecting seconds/minutes/hours while most of the time we want to compare YMD.


<img width="247" alt="Screenshot 2024-01-17 at 15 24 59" src="https://github.com/twentyhq/twenty/assets/6399865/96030a42-d66e-40d6-b408-e70fc93e4b4f">


Probably something to clarify around DATE vs DATETIME  field, and make sure that even if DATETIME the filter only compares YmD

**Comment by FelixMalfait** [comment]
Equal date filtering was removed from DateTime field on the ui, we kept greater than / lesser than only
We will introduce a Date field soon (no time), which should support equal filtering
