### ISSUE TITLE
fix: avoid being able to create custom entities with the same name as core and standards entities

### ISSUE THREAD

**Issue by magrinj** [twentyhq/twenty#2768]
## Scope & Context

Since we've added the flexible back-end, we're now able to create custom objects per workspaces.
As the core graphQL schema is seeing merged with the workspace schema we must avoid conflict in the naming of custom objects against core and standards entities.

## Current behavior

We can create a custom object with the same name as a core or standard entity.

## Expected behavior

The backend should throw an error while trying to create an object with Workspace, User, RefreshToken, FeatureFlag (core entities) but also Company, Person, Activity... (standard objects)

**Comment by a-kud** [comment]
I already started to work on this one, please assign it to me.
