### ISSUE TITLE
Improve typing of filter and sort on metadata and record hooks.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2780]
## Scope & Context

All the hooks for query and mutation of object-records and object-metadata.

## Current behavior

The props `filter` and `orderBy` are typed with `any`.

## Expected behavior

We want them to be typed at least with the allowed structure (and, or, eq, not, etc.) and if a type is provided, with the fields of the type.

**Comment by FelixMalfait** [comment]
Closing as it's marked as "done" in Product Development board
