### ISSUE TITLE
Design and implement error fallback component

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2788]
## Scope & Context

When a synchronous React error is caught.

## Current behavior

We have a very rough error fallback component : 

<img width="2345" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/161ac128-842d-4072-9e30-ec1ca0350399">

## Expected behavior

We'd like to have a pretty error fallback component. 
The retry button allows to reload the page. 
Use the same style of empty states.

![image](https://github.com/twentyhq/twenty/assets/19412894/b926d2f3-8bac-400a-8451-5970361f91a9)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=16596-94606&mode=design&t=paVI9QsoQYc5qsKU-11

**Comment by lucasbordeau** [comment]
@Bonapara

**Comment by harrisonJones12** [comment]
Can you assign this issue to me?

**Comment by harrisonJones12** [comment]
How would I pull down this app and start a dev server?

**Comment by RohinMarok** [comment]
hi i'll try taking this on and submitting a pr soon

**Comment by FelixMalfait** [comment]
@Kanav-Arora could you please handle this as part of https://github.com/twentyhq/twenty/issues/3310 ? I think it'd be nice if we still display the error though - but small font. Thanks 🙏 cc @Bonapara

**Comment by Bonapara** [comment]
Let's put the error under the "Server’s on a coffee break" like this. (With a max width 600px)

![image](https://github.com/twentyhq/twenty/assets/19412894/504666bb-41df-4b23-a918-a615f79d3b26)

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait @Bonapara 
Sure

**Comment by FelixMalfait** [comment]
Thanks @Kanav-Arora!

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait @Bonapara 

I don't think so we should show error message also. What do you think? Its too technical

<img width="1440" alt="Screenshot 2024-01-17 at 7 50 04 PM" src="https://github.com/twentyhq/twenty/assets/62852363/494b8f4b-80e4-4c78-8979-8694bd35733c">

**Comment by FelixMalfait** [comment]
Thanks @Kanav-Arora I agree it's ugly but it will be handy in the coming months as we are still receiving a lot of bug reports directly from self-hosting users (that we would not see in Sentry). Maybe set a max width on the text so that at least it's a bit more redeable and over multiple line ? And eventually also limit the height so that we only see at most 3 lines? What matter is the beginning of the message usually

**Comment by Bonapara** [comment]
The max-width should be 600px indeed!

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait 
This issue is completed

**Comment by FelixMalfait** [comment]
Great thanks!
