### ISSUE TITLE
Views count should be computed on the backend side

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2794]
Currently the view count here reflects the number of items displayed on the page (it goes up if you scroll).
<img width="265" alt="Screenshot 2023-12-03 at 11 46 33" src="https://github.com/twentyhq/twenty/assets/6399865/892ebc72-3f6c-4540-b31d-6af5accbab91">

Instead, it should be computed on the backend and reflect the total number of items that match the applied filters.

Note: you can use `yarn run database:seed:demo` to generate a great number of seeds with pagination

**Comment by tmahabir** [comment]
Hi @FelixMalfait ! Can you assign this issue to me please?

**Comment by FelixMalfait** [comment]
Of course thanks @tmahabir - let us know if you need help

**Comment by tmahabir** [comment]
Hi @FelixMalfait ! 

I spent all of yesterday trying to understand the server code. I'm completely new to GraphQL so I had trouble figuring out how to add a new find all query that will return all records with no pagination affecting it.

I'm in university and it's currently finals season, so I'll unfortunately not be able to resolve this issue assigned to me.

**Comment by FelixMalfait** [comment]
Hi @tmahabir no problem! 
I didn't add the "good first issue" tag at the time because it's not not easy indeed.
We use pg_graphql under the hood, here's what they say in [their doc](https://supabase.github.io/pg_graphql/api/):
>  The totalCount field is disabled by default because it can be expensive on large tables. To enable it use a [comment directive](https://supabase.github.io/pg_graphql/configuration/#totalcount)
So probably that's something we should do upon table creation in workspace/sync-metadata, then modify the server to return it. I'm not sure, this would require testing. 
Good luck for your finals and thanks for giving it a try! Hope your learned some things along the way :)

**Comment by magrinj** [comment]
Hey @tmahabir,

Thanks a lot for the try, I made a PR to fix the issue !
