### ISSUE TITLE
Fix mobile tab bar positioning

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2798]
On mobile mode, sometimes the tab bar background becomes white and the positioning is incorrect (you have to scroll by the size of the sidebar to view it, it's not visible if you don't scroll)

![image](https://github.com/twentyhq/twenty/assets/6399865/0c08ef16-1ccc-413c-9ad7-589fe427a116)

**Comment by FelixMalfait** [comment]
OK actually I can't reproduce it now 🤔 - I'll reopen it if it happens again

**Comment by charlesBochet** [comment]
This seems to have been fixed, closing this issue :)
