### ISSUE TITLE
FloatingButton in FloatingButtonGroup should have adaptable borders

### ISSUE THREAD

**Issue by nimraahmed** [twentyhq/twenty#2800]
## Bug Description

<img width="244" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/64a54a06-444b-459d-9573-95eedacf853d">

The borders of a FloatingButton inside a FloatingButtonGroup should change depending on its position.

(Note that in the documentation there's a problem because both buttons have the focus and there should only be one. Link to other issue : https://github.com/twentyhq/twenty/issues/3161)

## Expected behavior

We need to copy the behavior of a FloatingIconButton in a FloatingIconButtonGroup, see `FloatingIconButton.tsx`

<img width="116" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/6c4b1d2d-1c45-48fe-8f17-a27b503f3ff8">

You can see that the button in the middle has different border-radius because its position is `middle`.

**Comment by Kanav-Arora** [comment]
Hi @nimraahmed 
Can I work on this?

**Comment by BalanaguYashwanth** [comment]
Got it thanks

**Comment by a-kud** [comment]
can I take this one?

**Comment by BalanaguYashwanth** [comment]
You can go head @a-kud

**Comment by nimraahmed** [comment]
@charlesBochet is anyone working on this or can i take this up?

**Comment by charlesBochet** [comment]
@nimraahmed Not than I know about! Please go ahead :)

**Comment by a-kud** [comment]
I'm still working on it, can finish this week.

**Comment by charlesBochet** [comment]
Ok, thank you @a-kud!

@nimraahmed: @a-kud is already working on it :)

**Comment by lucasbordeau** [comment]
@a-kud I updated the issue to give you more context, could you please make according changes in your PR ?

**Comment by a-kud** [comment]
I have a high workload right now, feel free  to work on this one.
