### ISSUE TITLE
Attachments drop file

### ISSUE THREAD

**Issue by brendanlaschke** [twentyhq/twenty#2804]
## Scope & Context

Attachments allow for a file upload - do we want the ability to drop a file onto the attachments tab @Bonapara? 

## Current behavior

We can add files only via the button.

## Expected behavior

Drop a file to upload it.

**Comment by FelixMalfait** [comment]
This would be very cool! I added "design needed" for the drop area (when you're hover it but haven't released it yet), but we can start with something very basic

**Comment by Bonapara** [comment]
Replace by #3345
