### ISSUE TITLE
Finish Board Scope Refactoring

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#2808]
## Scope & Context

Finish Board refactoring. This ticket follows #2426.

## Technical inputs

- Make filter and sort work
- Get rid of `BoardOptionsContext.Provider` and `CompanyBoardRecoilScopeContext.Provider` and replace them with scopes.
- Clean code

**Comment by charlesBochet** [comment]
This has been completed, closing this issue :)
