### ISSUE TITLE
Add Sentry on Frontend

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#2829]
We want to add Sentry on the newly created ErrorBoundaries and also in our logError util. 

We should verify that every onError in the app (usually Apollo), uses this logError.

**Comment by a-kud** [comment]
can I take this one?

**Comment by charlesBochet** [comment]
@a-kud Sure, thank you!
Here is a bit more information, we would like to add https://docs.sentry.io/platforms/javascript/guides/react/

You'll need to create a test sentry account on your own as we cannot give you access to Twenty production sentry account  to test it
This sentry DSN (api key) is already stored in server .env. You'll need to communicate it to the frontend through ClientConfig. You can take a look at how we pass and use SUPPORT_FRONT_CHAT_ID in the frontend.

Once done, you'll need to setup Sentry. It probably make sense to set it up in a <LoggerProvider> that would read the DSN from clientConfig and init Sentry. You can take a look at AppThemeProvider to see how a Provider would be added to index.tsx

I'm available if you need more help while working on it :)

**Comment by charlesBochet** [comment]
@a-kud any update on this one? :)

**Comment by a-kud** [comment]
no update at this time, if anyone is interested to take over go ahead

**Comment by i-am-chitti** [comment]
@charlesBochet Can I work on this?

**Comment by charlesBochet** [comment]
@i-am-chitti sure! This one is quite time sensitive as we want to include is 0.2.2 this week but I can guide you if you need hints :)

**Comment by i-am-chitti** [comment]
Hey @charlesBochet,
Sentry requires `tracePropagationTargets` to control for which URLs distributed tracing should be enabled. Have a look here in docs - https://docs.sentry.io/platforms/javascript/guides/react/.
Going to allow `localhost:3001` where frontend is running. Any other specific URLs to be allowed or should I make it dynamic?

**Comment by charlesBochet** [comment]
@i-am-chitti Interesting option. I think it's optional at this point, let's only add localhost, we will look into it later if we want to get a continuity between front and server sentry logs

**Comment by charlesBochet** [comment]
Actually, let's add put localhost and REACT_APP_SERVER_BASE_URL: import { REACT_APP_SERVER_BASE_URL } from '~/config';
Might be useful!

**Comment by i-am-chitti** [comment]
One more doubt, I'm getting the Sentry DSN key in `ClientConfigProvider.tsx` file that's where the fetch operation is being performed. 
Now, what's the best place to `init` Sentry? Sentry recommends to `init` it as early as possible. But since we are getting the DSN key in ClientConfigProvider and after so, does it make sense to init there itself or any other place you may recommend.

**Comment by i-am-chitti** [comment]
@charlesBochet ☝️ In case you missed.

**Comment by charlesBochet** [comment]
@i-am-chitti Sorry for the late response! I think we could create a ExceptionHandlerProvider that would be added in the index.tsx too

**Comment by i-am-chitti** [comment]
Thanks @charlesBochet. In that case, only errors in components below the ExceptionHandlerProvider will be able hit Sentry - https://github.com/i-am-chitti/twenty/blob/18b2e2b7484b5b65d34d53101cde3313af2beebe/packages/twenty-front/src/index.tsx#L34-L67. What if errors occur before that for example in `ApolloProvider` then, it won't be traced in Sentry. I saw `AppErrorBoundary` where a todo is added for logging error to Sentry - https://github.com/i-am-chitti/twenty/blob/18b2e2b7484b5b65d34d53101cde3313af2beebe/packages/twenty-front/src/modules/error-handler/components/AppErrorBoundary.tsx#L8. I think, it need Sentry to be initialized before. But, DSN key is not available until ClientConfigProvider. 
Shall I still go with ExceptionHandlerProvider approach?

**Comment by charlesBochet** [comment]
that's a good point. We should put the ExceptionHandlerProvider almost on top of the hierarchy (above apollo)
in ExceptionHandlerProvider, we can still access the value of ClientConfig (it will be undefined in the beginning but then defined), it doesn't matter that ExceptionHandlerProvider is above ClientConfigProvider

**Comment by i-am-chitti** [comment]
Hey @charlesBochet, have raised a PR here - https://github.com/twentyhq/twenty/pull/3111

The CI builds are failing because of non-modification of yarn.lock. Could you tell me how can I modify it as I have added [Sentry React package](https://www.npmjs.com/package/@sentry/react)? It's working on my local and didn't have any yarn.lock changes. This is weired. I've not worked much with monorepo. Any help would be appreciated. Thanks.

**Comment by charlesBochet** [comment]
Taking a look :)

**Comment by charlesBochet** [comment]
@i-am-chitti I have left comments on your PR and fixed your yarn.lock issue!

**Comment by i-am-chitti** [comment]
Thanks @charlesBochet for quick reply and awesome reviews. Gonna address the feedbacks and get back.

May I know how did you execute the change in yarn.lock? I also executed the `yarn` from inside docker container, but it didn't modify it. I'll learn from it and take note for future.

**Comment by charlesBochet** [comment]
I took a look and it seems to be broken on the docker setup!
In: packages/twenty-docker/dev/docker-compose.yml, we should do
`      - ../../..:/app`

instead of
```
      - ../../../packages/twenty-front:/app/packages/twenty-front
      - ../../../packages/twenty-server:/app/packages/twenty-server
      - ../../../packages/eslint-plugin-twenty:/app/packages/eslint-plugin-twenty
```

I will update this
