### ISSUE TITLE
Accounts/Emails - Add Blocklist section

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#2832]
## Context

For this issue:
- Add to the Settings/Accounts/Emails page a "Blocklist" section with a title, a description, an input, an "Add to blocklist" button, and a table that displays blocked emails.
- For the input and button:
  - Clicking on the "Add to blocklist" button adds a row in a state local to the component for now.
- For the table:
  - Reuse the table component from [#1806](https://github.com/twentyhq/twenty/issues/1806)
  - Use mock data for now.
  - The "X" icon button at the end of a row removes the row from the local state for now.

## Figma

![Image](https://github.com/twentyhq/twenty/assets/3098428/81bb4aec-6077-4d29-b674-efb231f907bd)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=15568%3A45759&mode=dev

**Comment by lakshay-saini-au8** [comment]
@thaisguigon 
Please assign this issue
