### ISSUE TITLE
Extract @/ui/objects to @/object-record (RecordTable, RecordBoard) and transform identifiersMapper into utils

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2833]
Move from folder @/modules/ui/object/ to @/modules/object-record and @/modules/object-metadata.

We want to keep purely UI components : 
- @/modules/ui/object/field/meta-types/input/internal/components in @/modules/ui/object/field/components

**Comment by charlesBochet** [comment]
This has been completed, closing this issue :)
