### ISSUE TITLE
Rework and merge Multi-Select on Relation Filter

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2836]
Scope:
- Rework MultipleEntitySelect
- Upgrade FilterEntitySelect to support MutliSelect instead of SingleSelect + store selected values in state
- upgrade turnFiltersIntoWhereClause 

Out of scope:
- useSearchQuery
- label identifiers
- SIngleSelect and its usage
- out of scope improve typing of filter

**Comment by charlesBochet** [comment]
This has been completed, closing this issue :)
