### ISSUE TITLE
When a workspaceMember is deleted from Settings > Workspace Member, it is not possible to invite the user to the workspace again

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#2848]
Related to #4036 

## Bug Description

From Settings > WorskpaceMember, delete a workspaceMember.
This will remove the workspaceMember. However as we plan to allow users to join multiple workspace (have multiple workspaceMembers), this is not deleting the user itself.

However, then the sign up logic does not allow a new sign up as the user already exist.

## Expected behavior

We need to clarify the business logic first, and then implement it properly in the codebase:
- What does it mean to delete a workspaceMember, should the user still be able to connect but not see any workspace
- Should we delete the user if it has no workspaceMembers attach

Related question:
- what happens to the objects (activities, companies, ...) authored by the WorkspaceMember. Should we delete them? Should we just set the related relationId to null?

@FelixMalfait @Bonapara

**Comment by Bonapara** [comment]
What about finding a quick fix on this one?

Could deleting users instead of workspace members be one? (Until we prioritize implementing the workspace switching UI, it doesn't feel like a priority at the moment) WDYT?

Unless @FelixMalfait's first solution is easy to implement!

**Comment by mlsmith** [comment]
On Google Drive, you can transfer ownership of the deleted user's files to another user, which may be a good alternative approach in this case.

**Comment by FelixMalfait** [comment]
@mlsmith yes great idea for a future iteration, it would be nice.

**Comment by FelixMalfait** [comment]
@AdityaPimpalkar does your PR solve this?

**Comment by AdityaPimpalkar** [comment]
Yes! #4232 should solve this too :)
