### ISSUE TITLE
Accounts/New - Create page

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#2891]
## Context

For this issue:
- Create an empty page with the route: `/settings/accounts/new`.
- Use the breadcrumb component from #1814.

## Figma

<img width="617" alt="image" src="https://github.com/twentyhq/twenty/assets/3098428/4f0c243a-9260-49f1-a9a4-51c1e1191665">

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=15568%3A45961&mode=dev

**Comment by lakshay-saini-au8** [comment]
@thaisguigon , I think this issue is a good fit for me to begin working on. Can you please assign it to me?

**Comment by lakshay-saini-au8** [comment]
@thaisguigon 
Please review the PR
https://github.com/twentyhq/twenty/pull/2960
