### ISSUE TITLE
Accounts/New - Add New account section

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#2894]
## Context

For this issue:
- Add to the Settins/Accounts/New page a "New account" section with a title, a description, and a card.
- For the card:
  - Reuse the empty state card from #2817

## Figma

<img width="617" alt="image" src="https://github.com/twentyhq/twenty/assets/3098428/4f0c243a-9260-49f1-a9a4-51c1e1191665">

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=15568%3A45961&mode=dev

**Comment by lakshay-saini-au8** [comment]
Hey @thaisguigon ,
Possible to assign this issue to me as I also worked on the create new account page

**Comment by thaisguigon** [comment]
@lakshay-saini-au8 Sure, thank you!

**Comment by lakshay-saini-au8** [comment]
@thaisguigon Please Review the PR
https://github.com/twentyhq/twenty/pull/3000

**Comment by lakshay-saini-au8** [comment]
Also here in this design, it says 
Connect a Google Account 

but the card you suggested use 
No connected account

Currently I use as you suggested 

But let me know if we need to update the content

**Comment by lakshay-saini-au8** [comment]
@charlesBochet @thaisguigon 
I think we can close this issue
