### ISSUE TITLE
Fix the "hover" behavior on button to add a column

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2902]
Related discussion on Discord: https://discord.com/channels/1130383047699738754/1146466959676936192/1181976629757620364

As @Kanav-Arora suggested, something feels off about the behavior of this button.

We should  consider dropping the grey background when hovering the cell and having it on the (+) button instead.

cc @Bonapara to confirm/edit

![image](https://github.com/twentyhq/twenty/assets/6399865/d61f64a0-ec2d-4825-be0f-6080e5e808a0)

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait 
Any update on this?

**Comment by FelixMalfait** [comment]
Hi @Kanav-Arora thanks! Good on my side but let's wait for @Bonapara to confirm if this change makes sense or if he suggests something else

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait 
Raised a PR for the same
