### ISSUE TITLE
I should be able to see related object on show page 

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2903]
I created a listing attached to Andrea.
I would have expected this object to appear on Andrea's show page.

<img width="994" alt="Screenshot 2023-12-09 at 16 59 40" src="https://github.com/twentyhq/twenty/assets/6399865/fd6b5b82-5444-4bee-96c9-22711deae304">
<img width="1073" alt="Screenshot 2023-12-09 at 17 00 27" src="https://github.com/twentyhq/twenty/assets/6399865/891bcd0d-35f7-4e6f-888e-0964a1a2719f">

cc @Bonapara 
cc @charlesBochet to confirm if this isn't a duplicate ticket

**Comment by Bonapara** [comment]
Replaced by:
https://github.com/twentyhq/twenty/issues/3099
