### ISSUE TITLE
I shouldn’t see disabled fields in show view

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2904]
I've disabled this field but can still see it in the show view.
This isn't the expected behavior, is it? cc @Bonapara to confirm

<img width="1028" alt="Screenshot 2023-12-09 at 17 02 30" src="https://github.com/twentyhq/twenty/assets/6399865/559663bb-b9fd-4a48-8d33-2c17e1aa16e8">

**Comment by Bonapara** [comment]
Nope indeed, well spotted @FelixMalfait!
Disabled fields in object settings should never appear in the product.
