### ISSUE TITLE
Concurrency issue when updating view filters

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2905]
Not sure if it's something we want to solve, but just logging it to discuss it quickly.
The way we update view filter is not idempotent ; if we click twice quickly it generates an error.

<img width="1512" alt="Screenshot 2023-12-10 at 14 58 41" src="https://github.com/twentyhq/twenty/assets/6399865/ffa2a1eb-df77-4eb3-afca-d164ef9fbd83">
<img width="611" alt="Screenshot 2023-12-10 at 15 04 08" src="https://github.com/twentyhq/twenty/assets/6399865/96a52d37-812f-4c42-8021-d1cb319127a9">
<img width="696" alt="Screenshot 2023-12-10 at 15 04 20" src="https://github.com/twentyhq/twenty/assets/6399865/e8ccf322-aedd-4859-b81d-240f6809b070">

```[tasklist]
### Tasks
```

**Comment by Bonapara** [comment]
Il we click twice on what?

**Comment by FelixMalfait** [comment]
@Bonapara On "update view" (in my case, as can be seen in screenshot it's "deleteViewFilter" in particular that caused the issue)

**Comment by Bonapara** [comment]
On my side, the filter appears multiple times on the filter bar when I click on "update view" even once. Do you think it's related @FelixMalfait?

![Screenshot 2023-12-11 at 10 04 58](https://github.com/twentyhq/twenty/assets/19412894/3d58640e-b638-45fc-95bb-94f0c15e6923)
![Screenshot 2023-12-11 at 10 03 19](https://github.com/twentyhq/twenty/assets/19412894/c8c12995-f10e-478e-b30e-037cca09e05a)

**Comment by charlesBochet** [comment]
Switch to createMany, updateMany, deleteMany

**Comment by FelixMalfait** [comment]
We could probably add a debounce on the "update view" button as a first step / good enough quickfix

**Comment by FelixMalfait** [comment]
Tested today. Issue is still there.

**Comment by charlesBochet** [comment]
@FelixMalfait solved in v0.3.3!
