### ISSUE TITLE
Fix CSS when escaping the "Import" flow

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2906]
It's impossible to read the button's content 

<img width="1135" alt="Screenshot 2023-12-10 at 15 15 18" src="https://github.com/twentyhq/twenty/assets/6399865/354c604e-66e4-4c01-86c8-1e937367eaed">

**Comment by karishma-shah** [comment]
Hi @FelixMalfait, can I work on this bug fix please?

**Comment by FelixMalfait** [comment]
@karishma-shah yes of course, thanks! Feel free to reach out on Discord if you ever need help
