### ISSUE TITLE
GraphQL API documentation

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2914]
There is currently no way to explore the mutations/queries available for standard or custom objects.
[docs.twenty.com/graphql/](https://docs.twenty.com/graphql/)  is a good starting point but because we are not logged in, it only shows the endpoint for the metadata api, and not the actual object endpoints.
One way to solve this would maybe be to ask for a token/login on that page?

**Comment by charlesBochet** [comment]
I would recommend to put in place a proper oauth flow here so docs.twenty.com can get a valid token from api.twenty.com in 1 click / automated redirection on first graphql playground load

**Comment by FelixMalfait** [comment]
@charlesBochet that's nice but that's not what we did with the REST API. Shouldn't we be consistent? Maybe the same API key input overlay would be simpler as step 1?

**Comment by charlesBochet** [comment]
Yes but right now, the user needs to copy his Authorization token himself which is quite technical? I'm fine with both approach

**Comment by FelixMalfait** [comment]
>  the user needs to copy his Authorization token himself which is quite technical
They will need to generate a token to use the API though 😅
I agree OAuth is slightly better but I'd say it's low prio, and that if we do it we need to do it on both GraphQL+REST to keep consistency

**Comment by charlesBochet** [comment]
Ok, so then, let's do the same as for RestAPI and invite the user to input their token

**Comment by martmull** [comment]
You mean GraphqlAPI @charlesBochet? I can definetly investigate that
