### ISSUE TITLE
Rest API Documentation

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2915]
Edit: 
- After some research, we will give [this package](https://github.com/stoplightio/elements?tab=readme-ov-file) a try. It has the Swaggers functionalities, but more beautiful.
- we will create the playground in the twenty-docs package, like we do for graphql
- we need to add a div to let the user fill its token to request the user workspace open api schema 

We will soon have an endpoint the generate the OpenAPI schema (https://github.com/twentyhq/twenty/pull/2900)
But we need a more user-friendly way to generate a documentation from this

**Comment by charlesBochet** [comment]
This has been completed, closing this issue :)
