### ISSUE TITLE
Error not sent to Sentry

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2916]
The error documented [here](https://github.com/twentyhq/twenty/issues/2905) was not sent to Sentry.
It seems like we should add something to throw an Exception when pg_graphql throws an error?

**Comment by bosiraphael** [comment]
I tried to do:
```
throw new ConflictException(
        'This account is already connected to your workspace.',
      );
```
but it wasn't caught by the HttpExceptionFilter
