### ISSUE TITLE
README images broken with change to monorepo

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2921]
We would need to update the link to the logo and screen captures in the README.
They've been broken when we moved to the monorepo structure this week-end.

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait 
I'll fix the paths

**Comment by FelixMalfait** [comment]
Thanks a lot @Kanav-Arora!

**Comment by Kanav-Arora** [comment]
@FelixMalfait done!
