### ISSUE TITLE
[Timebox] Create a Health check command to check for workspace metadata and migration status

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#2930]
We now have a command to "sync" metadata and migrations on deployment. However, we are afraid to run it on production as it could result in data loss

To make sure this command is as predictible as possible, we would like to run before and after (and also regularly once we have crons) a "health check" command that would make sure that a specific workspace is in a healthy state.

This command should check:
- workspace metadata match standard objects
- workspace postgres structure match standard objects migrations
- workspace metadata match relation and field type structure  
- workspace postgres structure match field type structure

**Comment by FelixMalfait** [comment]
I think this has been completed already! Please re-open if I'm wrong
