### ISSUE TITLE
Deploy and review setup on docs.twenty.com

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#2932]
As we have migrated to yarn4, monorepo and vite, we need to update the documentation.
A first pass has been done but we need to make sure that the following docs are as smooth as possible:
- yarn setup on MacOS ARM with docker postgres/with local postgres
- yarn setup on MacOS Intel with docker postgres/with local postgres
- yarn setup on Linux/WSL with docker postgres/with local postgres
- docker setup

Also, we should add binaries of pg_graphql to our docker-postgres package to ease yarn setup on MacOS ARM and Intel

**Comment by Varrooo** [comment]
Hi ! If this issue is still available, me and my group are going to work on it. 
First we're going to check the yarn setup on Linux/WSL and the docker setup, then the MacOS setups (if we can do it with a virtual machine). 
If anyone feels to check the MacOS setups before us, feel free to do it. I will let you know if we're working on it or not.
Can you tell us more about the binaries of pg_graphql ? What is it exactly ? Maybe we can try to do it.

**Comment by charlesBochet** [comment]
This has been completed, closing this issue :)

**Comment by Varrooo** [comment]
Hey ! My bad, i forgot to give you the feedback this weekend. 
I've encountered a few errors in the Linux setup, I'm checking with my team to see if they've also encountered errors on other setups and I'll get back to you shortly.

**Comment by charlesBochet** [comment]
Thank you! I'll happily update the doc and the setup with your feedbacks

**Comment by Varrooo** [comment]
Hello again

So here is our feedback from the different Twenty setups :

I've checked the Linux setup and made some changes in the Linux script, I've explained why in the commit descriptions (some are already explained by their names). Here is the PR : #3067 #

I've encountered an issue about the "yarn nx start twenty-front" with the error code :
node:internal/errors:490 
      ErrorCaptureStackTrace(err);
Error: ENOSPC: System limit for number of file watchers reached

I did some research and found this : 
https://bobbyhadz.com/blog/system-limit-for-number-of-file-watchers-reached
His fix made my twenty-front start, so maybe you can try to add it to a script to fix the problem. I don't know if this causes security breaches or else.
I've got an other issue with the yarn setup, the "corepack enable" didn't work, I had to install it myself with "npm install --global yarn", maybe we can add it in the docs ?

@33luap checked the WSL setup, obviously he had the same issues as me but nothing more.
@xNeroForte @alexandrabrbk and i checked the docker setup, everything is fine except that we can't access our postgres database from our browser : 
![image](https://github.com/twentyhq/twenty/assets/131566087/716b4a55-1a3b-433c-b55e-bc8e1537a463)

So i've checked if postgres was running and yes it does but we can't access it.
![image](https://github.com/twentyhq/twenty/assets/131566087/25eec3ec-59e9-4c44-bda8-4a1bbac7b569)

That's all for our feedback and sorry again for the delay.

**Comment by charlesBochet** [comment]
We can add the paragraph about the watchers limit to the troubleshooting section of the doc.
Regarding postgres not being accessible, this is normal, it's not http protocol so your browser won't know how to talk to postgres. But if you use a postgres client, you should be able to talk to it
