### ISSUE TITLE
Fix depth parameter in api-rest

### ISSUE THREAD

**Issue by martmull** [twentyhq/twenty#2935]
Depth parameter seems ignored in api-rest, we get the same result when depth=1 and depth=2 for GET /rest/people

**Comment by Ankit-Dwij** [comment]
@martmull is anyone working on this ? If not , can you assign this to me . Thanks

**Comment by martmull** [comment]
Hey @Ankit-Dwij , no you can take it if you want

**Comment by martmull** [comment]
@Ankit-Dwij -> think this fix should make it 
![image](https://github.com/twentyhq/twenty/assets/29927851/cf960c76-1ba3-47fa-bf9d-174fce55944f)

**Comment by martmull** [comment]
@Ankit-Dwij I will need to fix that today. Thank you for proposing help on that. Don't hesitate to assign yourself on other `good first issue` labeled issues! Have a great day
