### ISSUE TITLE
I should be able to create a company from the people list view

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2965]
It used to be possible to create a company from there, but it got lost during a refactor.
There used to be a "create new" button in the list.

<img width="231" alt="Screenshot 2023-12-12 at 18 30 29" src="https://github.com/twentyhq/twenty/assets/6399865/35a7eae7-537f-4808-937f-d307e5cacefb">

**Comment by Bonapara** [comment]
<img width="283" alt="Screenshot 2023-12-15 at 20 12 56" src="https://github.com/twentyhq/twenty/assets/19412894/b25aaa99-f200-41a5-9a5e-9c4beefdb737">

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=17404-41837&mode=design&t=FgTQBl2iVzooomzb-11

Here is the design (Keep the No company option)

**Comment by lucasbordeau** [comment]
We should expand this to creating a new object from a relation picker, which involves displaying the proper input field for the object's label identifier.

**Comment by lucasbordeau** [comment]
See : https://github.com/twentyhq/twenty/issues/3729
