### ISSUE TITLE
Keep the filter edition open if it is empty

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#2967]
## Scope & Context

Filter dropdown input

## Current behavior

If we empty the filter input, it will delete the filter, and it's a problem because we might want to clear the input to type in something else without having to open it again.

https://github.com/twentyhq/twenty/assets/26528466/a1713f2e-04f4-45f1-ace1-30365a885ef1

## Expected behavior

We would like the filter dropdown to stay open if the input is empty, and trigger the filter reset only if we close the dropdown (by clicking outside) with an empty input.

It should work on every filter dropdown.

**Comment by CzhCN0** [comment]
I attempted to fix this issue. Please don't hesitate to reach out if you have any questions or concerns.

**Comment by lucasbordeau** [comment]
@CzhCN0 Thanks for your contribution, I added some comments.
