### ISSUE TITLE
Back ton index button is no more square

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2971]
# Current behavior

The button is not square:

![Screenshot 2023-12-13 at 11 58 06](https://github.com/twentyhq/twenty/assets/19412894/b651240a-c9ae-4baa-8eee-3f2843de6af2)

# Desired behavior

The button should be a 24px light icon button 

![Screenshot 2023-12-13 at 11 58 58](https://github.com/twentyhq/twenty/assets/19412894/b9f9d229-e49c-4ec4-b0b2-aacab3ab50ce)

### Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=9901-34423&mode=design&t=pfE2hTyckvmdvs26-11

**Comment by Sidd-77** [comment]
i will try

**Comment by Sidd-77** [comment]
![image](https://github.com/twentyhq/twenty/assets/102907405/e06700c2-2547-4281-910f-da9a6dc9b5aa)
When I try to setup the project locally I get this error while using the yarn command
I have installed all dependencies.
Help please

**Comment by madangopal16072000** [comment]
I am also trying

**Comment by charlesBochet** [comment]
@Sidd-77 we have updated our installation in the last days. Could you give another try using docs.twenty.com (yarn setup)

If you face issues, please join our Discord (https://discord.gg/jj2bxudu)  and post in #help channel
Thanks for the help :)

**Comment by Sidd-77** [comment]
@charlesBochet sure mate !
Thanks

**Comment by suman-somu** [comment]
on it

**Comment by Bonapara** [comment]
Thanks @suman-somu 🙏
