### ISSUE TITLE
Link fields design is incorrect.

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2972]
# Current behavior

The link field design looks like a regular text field:

### Index page:

![Screenshot 2023-12-13 at 12 06 06](https://github.com/twentyhq/twenty/assets/19412894/57a46c08-1f3c-4ead-b857-df3cb2aa77cd)

### Show page:

![Screenshot 2023-12-13 at 12 12 46](https://github.com/twentyhq/twenty/assets/19412894/6d90d3a3-9158-46da-88a7-3c82141e5f61)

# Desired behavior

Put the link in the link field type on both index & show:

### Index:

![Screenshot 2023-12-13 at 12 07 26](https://github.com/twentyhq/twenty/assets/19412894/d6a41b32-aa46-431c-8436-403323bf0d3c)

![Screenshot 2023-12-13 at 12 04 55](https://github.com/twentyhq/twenty/assets/19412894/f9b91230-5de6-420d-8af1-2b6764e1e9a5)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=14603-76540&mode=design&t=pfE2hTyckvmdvs26-11

### Show:

https://github.com/twentyhq/twenty/assets/19412894/c95501ef-6e16-4ec7-bce6-dd326699f47e

![Screenshot 2023-12-13 at 12 08 40](https://github.com/twentyhq/twenty/assets/19412894/bf7b4deb-73a5-469f-8d99-f88cba65e1c5)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=14603-76540&mode=design&t=pfE2hTyckvmdvs26-11

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
I can work on this

**Comment by Bonapara** [comment]
Sure, thanks @Kanav-Arora ;)

**Comment by charlesBochet** [comment]
@Bonapara @Kanav-Arora this is not a link field currently, this is a text field. 
We will actually need to migrate this to a Link field but we are holding as we don't support array fields for now (as we would need to properly implement domain names).
What you can do for now @Kanav-Arora is to introduce a DomainFieldInput and DomainFieldDisplay and to conditionnally use it if fieldName = 'domainName' and objectMetadataSingularName = 'company' in FieldDisplay and FieldInput components
We do that for phone and email that are not implemented yet either

Long term what we want:
- migrate it to link once array fields are supported + we know how to smoothly migrate existing workspaces
- treat this as a LinkField with option isDomain

**Comment by FelixMalfait** [comment]
Closing because there is now https://github.com/twentyhq/twenty/issues/3607
