### ISSUE TITLE
New colum annualRevenueRange and rename ARR

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2977]
Step 1: rename annualRecurringRevenue to annualRevenue
Step 2: disable this field by default for newly created workspace
Step 3: create a new field, enabled by default on all new workspaces, called annualRevenueRange, of type enum, with values:
- $0-$1M
- $1M-$10M
- $10M-$50M
- $50M-$100M
- $100M-$250M
- $250M-$500M
- $500M-$1B
- $1B-$10B
- $10B+

Related: https://github.com/twentyhq/twenty/issues/2975

**Comment by charlesBochet** [comment]
@FelixMalfait FYI "enum" is named "select" in the product :)

This is still a bit early to do this ticket:
- the health check method that allows us to smoothly migrate workspace is not ready yet, this means that renaming a field is not well supported for now
- we are just starting testing enums (behind feature flags) and they are likely to be buggy. I would wait a bit before starting this one

**Comment by FelixMalfait** [comment]
@charlesBochet okay! Great if we can prioritize it soon after those requirements are filled

**Comment by charlesBochet** [comment]
@gitstart-twenty Do not take this ticket for now :)

**Comment by gitstart-twenty** [comment]
> @gitstart-twenty Do not take this ticket for now :)

Alright

**Comment by charlesBochet** [comment]
This can be picked, we have all the tooling required now!
