### ISSUE TITLE
Creating Notes they are created correctly but ui not correctly updating

### ISSUE THREAD

**Issue by brendanlaschke** [twentyhq/twenty#2990]
## Bug Description

Add multiple notes. Not all of them will be shown, they are merged into one, multiple relations are show for one note and more ...

## Expected behavior

Create notes and display them correctly.

## Technical inputs

Maybe an optimistic response problem ?

**Comment by charlesBochet** [comment]
We are working on the optimistic response system. I would recommend to wait a bit before tackling this one, the new system will give new tools
