### ISSUE TITLE
[Timebox] Display the label identifer again on shows/ detail pages

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3003]
# Current behavior

The identifier is displayed as a field:

<img width="436" alt="Screenshot 2023-12-15 at 11 43 33" src="https://github.com/twentyhq/twenty/assets/19412894/69dbe1fc-4e92-499f-87cd-7d8bd29e17c0">

# Desired behavior

The identifier should not be displayed as a field but appear under the picture/initials:

<img width="686" alt="Screenshot 2023-12-15 at 11 44 13" src="https://github.com/twentyhq/twenty/assets/19412894/93a0f7ca-9e81-4f54-a2ae-f3e30a8d0abc">

**Comment by Adity20** [comment]
I'd like to work upon this 
Can you assign this issue to me @Bonapara

**Comment by Bonapara** [comment]
Hey @Adity20, I assigned you on the other one, maybe I'll let someone else pick this one if ok for you?

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
Ig you need to give figma design for this as it requires change in PageSummaryCard so style needs to be changed.

**Comment by Adity20** [comment]
Thanks @Bonapara

**Comment by charlesBochet** [comment]
Also:
- make sure that for standard object, the label identifier is set
- on custom object creation, label identifier is set
- label identifier field should not be disabled
- update UI to show inplace input for label identifer
