### ISSUE TITLE
Last header column style on indexes (border and "+ icon button")

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3005]
# Current behavior

When there aren't enough fields to fill the horizontal space, there is no border on the top and left of the last cell. Additionally, there is no "Plus button icon" to add fields.

![CleanShot 2023-12-15 at 11 48 25@2x](https://github.com/twentyhq/twenty/assets/19412894/3bfd6f29-53c5-4274-80e4-d07171b3b374)

# Desired behavior

Ensure a plus button icon with "Customized fields" as the unique value. Include top and left borders. Make sure there is this "plus button icon" on every kind of Object table.

<img width="612" alt="Screenshot 2023-12-15 at 11 53 39" src="https://github.com/twentyhq/twenty/assets/19412894/6f29baaf-9c27-4265-bf78-c744ea09a230">

**Comment by Adity20** [comment]
I'd like to work on this issue 
Can you assign this to me @Bonapara

**Comment by Bonapara** [comment]
Done, Thanks @Adity20!

**Comment by charlesBochet** [comment]
@Adity20 this part of the code as recently been updated (the issue with the border has been fixed). You would only need to make the + button always appear

**Comment by haseeb196** [comment]
Can i work on this? and in which file?

> @Adity20 this part of the code as recently been updated (the issue with the border has been fixed). You would only need to make the + button always appear

**Comment by charlesBochet** [comment]
@haseeb196 Sure go ahead! Please take a look at the codebase first, I'm happy to assist once you've take a first look!

**Comment by FelixMalfait** [comment]
Fixed
