### ISSUE TITLE
Entity Chips should have an ellipsis if their name is overflowing their max-width

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#301]
Since entity chips can have different max width, whether they are used in a table cell or a entity picker, they should handle themselves the text that is overflowing the max width.

We should also find a way to fix their max width : 
- Have separate components wrapping a generic EntityChip component 
- Giving width or max-width in a props

**Comment by Bonapara** [comment]
We should crop the content with [...] when the content is overflowing (Don't wrap content)

**Comment by charlesBochet** [comment]
<img width="279" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/fcb92705-6757-4f24-af8b-7f2cb197732d">

**Comment by magrinj** [comment]
@Bonapara To fix this, I had to made some change so the text field for companies will never go behind the comment chip, it's in #428

**Comment by Bonapara** [comment]
@lucasbordeau cannot the comment chip be in position absolute **above** the text?

**Comment by magrinj** [comment]
@Bonapara Yes it can, but if you put `ellipsis` this one is not going to be visible and hide by the comment button.
Seems it's more a design problem actually, for now when it's too long the text is cut before the `CommentChip` with an ellipsis

**Comment by charlesBochet** [comment]
Fixed by https://github.com/twentyhq/twenty/pull/428
