### ISSUE TITLE
Fix Danger CI on push trigger

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#3022]
## Scope & Context

Danger CI is passing on pull_requests but failing when we merge on main.
We are getting the following error:
<img width="1188" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/3e1ec289-1ff2-419b-8f30-22489bda8af1">

## Technical inputs

It looks like `danger.git.modified_files` is undefined in the case of a `push` (on main) action trigger.
My recommendation is to disable the danger CI on push. It seems to me that this is useful to post messages on PRs only

**Comment by charlesBochet** [comment]
@FelixMalfait @brendanlaschke do you agree?

**Comment by brendanlaschke** [comment]
Looks good to me - seems logical for danger to have no modified files for the push ...
