### ISSUE TITLE
On Sign Out > Sign In, States are not loaded properly

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#3026]
## Bug Description

I have noticed that if, as a logged in user, you sign out. All recoil states are erased. This is causing multiple issues:
- ClientConfig is not properly loaded anymore (so Google SSO button disappears for example)
- If you sign in again, Icons are missing
<img width="1485" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/f5b7b511-421a-443b-a113-8237d92589a2">

## Technical inputs

I think it is related to the `handleSignOut` function in `useAuth` and especially:
`goToRecoilSnapshot(snapshot_UNSTABLE());`

What we want is to reset all recoil states except: clientConfigState + iconsState

**Comment by a-kud** [comment]
@charlesBochet  _If you sign in again, Icons are missing_ 
what icons are you referring to here?

**Comment by charlesBochet** [comment]
@a-kud Thanks for taking a look! On the screenshot above you can see that many Icons are '123' which is the default Icons when the icons have not been properly loaded
