### ISSUE TITLE
On RecordTable and on RecordBoard, when deleting many lines, use batch deleteMany

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#3027]
## Scope & Context

On RecordTable (respectively on RecordBoard), if you select multiple lines (resp. cards) and click on "Delete" in the Action Bar, this will loop over each record (resp. card) and delete them one by one. This could be improve to improve the user experience.

<img width="1485" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/f56eb22e-1c15-4036-8d0c-706cbeaf33e2">
<img width="1485" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/3113da2a-fa43-4ec8-bc9c-58e9acc8a7f0">

## Current behavior

1 graphQL call per row / card deleted

## Expected behavior

1 graphQL for all rows

## Technical inputs

The deleteMany endpoint is available on graphQL backend.
To implement this feature, you'll need to implement something very similar to `useDeleteOneRecord`: `useDeleteManyRecords`.
Once done, use it in the Action Bar of RecordTable and RecordBoard

While implementing it, make sure that optimistic rendering (optimisticEffect call in the code) is working. It's recommended to use "Slow 3G" as your network parameter in Chrome/Firefox

**Comment by CzhCN0** [comment]
Please forgive me for directly submitting the code review without claiming it first, as I noticed that this issue has been open for over a week without any progress. There are some details that still need discussion; we can continue the conversation within the code review.

**Comment by charlesBochet** [comment]
No problem, as the issue was not assigned there is no need to claim it! Taking a look :)
