### ISSUE TITLE
On Tasks page, when I select assignees, the graphQL query is broken

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#3028]
## Bug Description

Go to /tasks page and play with the assignee picker.
<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/d225dd05-9113-467b-b1cb-891899a53065">

The AssigneePicker is trying to send an array of assignee id to the backend within an `{ eq: xxx }` filter. we should be using a `{ in: [xx, xx] }` filter. 

## Technical Inputs

I think the issue is in useTasks:
```
assigneeId: {
          eq: selectedFilter?.value,
        },
```
with selectedFilter?.value being an array.
it should be `in`.

Also, the filter is working on page load (as long as we don't change the assignee), so I suspect the default value to be a string xxxId. We should pass [xxxId] instead

**Comment by i-am-chitti** [comment]
@charlesBochet, I debugged the `useTasks` hook and made the changes as you suggested in the technical inputs, but the same error is still persistent. 

I looked under the hood and found that `assigneeId` has UUID type - https://github.com/twentyhq/twenty/blob/main/packages/twenty-server/src/database/typeorm-seeds/metadata/field-metadata/activity.ts#L324-L337

So, on initial render, it is passed a valid UUID - https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/pages/tasks/TasksEffect.tsx#L26-L37 but after any selection, it's passed a stringified array which is reflected in error -
```
Variable "$filter" got invalid value "[\"20202020-0687-4c41-b707-ed1bfca972a7\"]" at "filter.assigneeId.eq"; Expected type "UUID". Invalid UUID
```

```
Variable "$filter" got invalid value "[\"20202020-0687-4c41-b707-ed1bfca972a7\",\"20202020-77d5-4cb6-b60a-f4a835a85d61\"]" at "filter.assigneeId.eq"; Expected type "UUID". Invalid UUID
```

This is where the selected filter values are stringified - https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownRecordSelect.tsx#L64-L74

Let me know if the types are correct and how should I proceed here.

**Comment by charlesBochet** [comment]
@i-am-chitti Thanks for taking a look!
The type of `assigneeId` is indeed UUID but the type for `filter: { assigneeId }` depends on what operand you are using. Right now we use `eq`. But I think that if we use `in`, it should accept an array

This is an example from the Companies Record Table where I filter by multiple accountOwnerId:
<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/a7f0ce25-97ce-4b8b-88db-0212063e0a7f">

You can see the `in` filter in action in the graphql Query
