### ISSUE TITLE
Bug: having ResizeObserver error when selecting / deselecting elements in entity picker

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#303]
The error is : ResizeObserver loop limit exceeded
<img width="1490" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/49b8d80a-48cb-421f-933b-1439547c5fb6">

**Comment by charlesBochet** [comment]
@lucasbordeau I could not reproduce, is it still occuring?
