### ISSUE TITLE
Two fixes for dark mode.

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3030]
# 1 Color outside the viewport

###  Current behavior

the body above the content is white in dark mode.

https://github.com/twentyhq/twenty/assets/19412894/c9f434ca-fbe2-4a52-bc88-33363482332f

### Desired behavior

It should be background secondary or even better, the noisy background if possible.

https://github.com/twentyhq/twenty/assets/19412894/aa77dad2-3898-4f0a-a3c6-5933342d9e47

# 2 Default color

### Current behavior

The default theme color is light:

<img width="220" alt="Screenshot 2023-12-15 at 18 16 02" src="https://github.com/twentyhq/twenty/assets/19412894/8a4e9231-5205-41bf-8424-728cbe6a63e9">

### Desired behavior

The default theme color should be "System Settings"

<img width="215" alt="Screenshot 2023-12-15 at 18 15 34" src="https://github.com/twentyhq/twenty/assets/19412894/22780ed3-a350-4e25-9784-937cc71949fd">

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 

Default Color Scheme is "System"

<img width="1440" alt="Screenshot 2023-12-15 at 11 04 42 PM" src="https://github.com/twentyhq/twenty/assets/62852363/2e6cd8e6-1b3a-4121-a9c0-cd948ffb0f67">

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
I found a way to do the noise change please provide me with the color tone you want for both dark as well as light mode

@charlesBochet should I add this color to background.ts

**Comment by charlesBochet** [comment]
> Hi @Bonapara
> 
> Default Color Scheme is "System"
> 


@Kanav-Arora, no because workspaceMember.colorScheme is not empty in DB. I think what @Bonapara means is that, when a workspaceMember is created, it should be associated with "System" color scheme by default

Regarding your other question, I am not sure to get it. what do you mean by noise change?

**Comment by Kanav-Arora** [comment]
WorkspaceMember default state is null and as on line in my screenshot System will be assigned so ig when new member is created System is default?

Regarding noise I'm saying that as Thomas specified that colour should be noisy so I was asking which color do I have to use?

**Comment by thaisguigon** [comment]
Hi @Kanav-Arora, you can find the "noisy" background in the theme (`theme.background.noisy`).

**Comment by Kanav-Arora** [comment]
Hi @thaisguigon 
The noisy background is same issued in the page whereas the background shown in the issue should be contrasting to the background.
Should I go with this only?

**Comment by charlesBochet** [comment]
@Kanav-Arora I think we want the same, where do you see it different?

**Comment by Kanav-Arora** [comment]
In the Github reference Thomas added in the issue description. There's a contrast with the header so do we want some contrast or same noisy background.

**Comment by charlesBochet** [comment]
Oh true, that's on the Github video example. Let's do something simple and put the same color!

**Comment by Kanav-Arora** [comment]
Okay I'll put same color only

**Comment by FelixMalfait** [comment]
@Kanav-Arora assigning this issue to you as I see it was discussed. Let us know if you're stuck / how we can help!

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait 
Its done sorry I was busy I'll raise a PR soon

**Comment by FelixMalfait** [comment]
@Kanav-Arora great thanks! no problem

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait 

Actually If I'm applying constant colors then its working but with noisy image string its not working

<img width="1440" alt="Screenshot 2024-01-07 at 11 04 41 PM" src="https://github.com/twentyhq/twenty/assets/62852363/f360d741-08ae-4cef-b24a-39d20ac50ae9">

**Comment by FelixMalfait** [comment]
Yes I've experimented that a few years ago too I remember. Let's settle for colors.
@Bonapara could you please point @Kanav-Arora to the right colors? Thanks a lot

**Comment by Bonapara** [comment]
Hi @Kanav-Arora,

We should use `Background Tertiary`, as it closely matches the noisy background:

![Screenshot 2024-01-09 at 15 37 03](https://github.com/twentyhq/twenty/assets/19412894/7a8e3176-eca8-4316-8083-0dd51418f7bc)
