### ISSUE TITLE
Missing bottom margin and unexpected left margin 

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#3046]
## Bug Description

I've noticed to regressions on the design:
<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/a66d353f-f829-423f-bdb8-06ec8836ada3">

1. We are missing a 12px bottom margin or padding:
<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/babfdfbd-7a8d-45bb-912b-3a8a8f25bd4e">

See: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=568%3A41661&mode=dev

2. We have an additional 12px left margin or padding on the main container:
<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/c0b9f3b8-ea5d-4e7d-ac5b-b1666cb5dd96">

This left margin should not exist.
I suspect that we have mixed things while working on responsiveness.

## Expected behavior

- 12px bottom margin
- no additional 12px left margin

Compare with Figma: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=478%3A19796&mode=dev

## Technical inputs

However, make sure the behavior on mobile (screen with small width) do not change. You might have to use useIsMobile if these margins are useful on mobile

**Comment by charlesBochet** [comment]
@Bonapara FYI so you don't re-create it!

**Comment by HuijungYoon** [comment]
may i take this issue?

**Comment by charlesBochet** [comment]
Sure! Thank you!

**Comment by charlesBochet** [comment]
@HuijungYoon As this issue needs to be fixed before 0.2.2 release, I will tackle it, feel free to take any other good first issue :)

**Comment by FelixMalfait** [comment]
This was fixed. Closing!
