### ISSUE TITLE
Add new field on company: industry

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3048]
Related: https://github.com/twentyhq/twenty/issues/2977

We want to create a new standard fields, of type "select" to represent the industry.

Reference for possible values:
https://docs.peopledatalabs.com/docs/industries

**Comment by Bonapara** [comment]
Would be cool to use the gray tag color and add an emoji before each category name:

<img width="487" alt="Screenshot 2023-12-18 at 11 32 04" src="https://github.com/twentyhq/twenty/assets/19412894/9ecb2f01-2577-4c7b-abb0-71313d35a61e">

**Comment by FelixMalfait** [comment]
Here's the updated list with emojis

💼 Accounting
✈️ Airlines/Aviation
⚖️ Alternative Dispute Resolution
🌿 Alternative Medicine
🎨 Animation
👗 Apparel & Fashion
🏗️ Architecture & Planning
🖌️ Arts and Crafts
🚗 Automotive
🚀 Aviation & Aerospace
🏦 Banking
🔬 Biotechnology
📺 Broadcast Media
🧱 Building Materials
📦 Business Supplies and Equipment
💹 Capital Markets
🧪 Chemicals
🤝 Civic & Social Organization
🌉 Civil Engineering
🏢 Commercial Real Estate
🔒 Computer & Network Security
🎮 Computer Games
💻 Computer Hardware
🌐 Computer Networking
💾 Computer Software
🏗 Construction
📱 Consumer Electronics
🛍 Consumer Goods
🛎 Consumer Services
💄 Cosmetics
🐄 Dairy
🚀 Defense & Space
✏️ Design
💻 E-learning
🎓 Education Management
⚡ Electrical/Electronic Manufacturing
🎭 Entertainment
🌱 Environmental Services
🎉 Events Services
🏛 Executive Office
🏠 Facilities Services
🚜 Farming
💰 Financial Services
🖼 Fine Art
🐟 Fishery
🍔 Food & Beverages
🏭 Food Production
💸 Fund-Raising
🛋 Furniture
🎲 Gambling & Casinos
🧱 Glass, Ceramics, & Concrete
🏛 Government Administration
🗣 Government Relations
📐 Graphic Design
🏋️‍♂️ Health, Wellness and Fitness
🎓 Higher Education
🏥 Hospital & Health Care
🏨 Hospitality
👥 Human Resources
🛳 Import and Export
👨‍👩‍👧‍👦 Individual & Family Services
🤖 Industrial Automation
📚 Information Services
💻 Information Technology and Services
🛡 Insurance
🌐 International Affairs
🌍 International Trade and Development
🕸 Internet
💹 Investment Banking
💼 Investment Management
⚖️ Judiciary
🚔 Law Enforcement
⚖️ Law Practice
⚖️ Legal Services
🏛 Legislative Office
✈️ Leisure, Travel, & Tourism
📚 Libraries
🚚 Logistics and Supply Chain
💎 Luxury Goods & Jewelry
🏗 Machinery
💡 Management Consulting
⚓ Maritime
🔍 Market Research
📈 Marketing and Advertising
🏭 Mechanical or Industrial Engineering
🎬 Media Production
🏥 Medical Devices
🩺 Medical Practice
🧠 Mental Health Care
💂‍♂️ Military
⛏ Mining & Metals
🎥 Motion Pictures and Film
🏛 Museums and Institutions
🎵 Music
🔬 Nanotechnology
📰 Newspapers
🤲 Non-Profit Organization Management
⛽ Oil & Energy
🌐 Online Media
🌏 Outsourcing/Offshoring
📦 Package/Freight Delivery
📦 Packaging and Containers
🌳 Paper & Forest Products
🎭 Performing Arts
💊 Pharmaceuticals
❤️ Philanthropy
📸 Photography
🧴 Plastics
🏛 Political Organization
🎓 Primary/Secondary Education
🖨 Printing
🧑‍🏫 Professional Training & Coaching
💻 Program Development
🏛 Public Policy
📣 Public Relations and Communications
🚒 Public Safety
📚 Publishing

**Comment by ehconitin** [comment]
can I work on this issue?

**Comment by FelixMalfait** [comment]
@ehconitin this one is unclear, still needs to be refined to see exactly where we want to go! Thanks
