### ISSUE TITLE
Add new field on company: related companies

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3057]
Many-to-many relationship between company and company. 
The joint table will probably have a column to indicate the nature of relationship (e.g. subsidiary)

**Comment by FelixMalfait** [comment]
Blocked because we don't know how to do many-to-many relationships still

**Comment by thilles** [comment]
This is something our company would highly appreciate found its way into twenty down the line

**Comment by FelixMalfait** [comment]
@thilles this is for sure something we will support by end of year. But probably not yet in the next 2-3 months. 

We already have a form of many-to-many relationship on the app (activities like notes and tasks can be linked to several companies and a company can have several notes). But we'd need to extend that to work in a more generic use-case.
