### ISSUE TITLE
Forbid the creation of field named "and", "or" and "not"

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3066]
## Scope & Context

In standard field features, and custom field creation.

## Current behavior

We can currently input anything we want in a field name's singular or plural.

## Expected behavior

In this case we want to forbid using pg_graphql's reserved operator for filtering. See https://supabase.github.io/pg_graphql/api/#filtering

> Avoid naming your columns and, or or not. If you do, the corresponding filter operator will not be available for use.

Note that there could be other words we would want to forbid as well.

We would want to forbid this on the backend endpoint and also in the front end on field creation / update.

**Comment by FelixMalfait** [comment]
See also #2146 which is similar. Maybe we should just do 1 regex for both object name and field name

**Comment by FelixMalfait** [comment]
@mozesi I'm sorry we didn't reply, if you're still interested let us know!

**Comment by mozesi** [comment]
@FelixMalfait am still interested.

**Comment by FelixMalfait** [comment]
Great! Assigned you :). Thanks a lot!

**Comment by FelixMalfait** [comment]
@mozesi any progress on this? Thanks!

**Comment by AbuHafsa** [comment]
@FelixMalfait you could assign it to me. I can give it a shot

**Comment by FelixMalfait** [comment]
Great thanks!

**Comment by FelixMalfait** [comment]
Ah indeed thanks @AbuHafsa!
