### ISSUE TITLE
New line behavior on table views

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3069]
# Current behavior

Clicking on the "plus" button icon adds a new line. You then have to click on the first cell to edit the identifier.

<img width="787" alt="Screenshot 2023-12-19 at 08 44 16" src="https://github.com/twentyhq/twenty/assets/19412894/3600de26-8332-4bff-965c-05fba1d20937">

# Desired behavior

Clicking on the "plus" icon on the top right should directly open the first cell of the new empty line. 

- After entering a company name and closing the input, clicking the first cell should redirect to the corresponding show page.
- Delete the new line if the first cell input is closed without content. (To avoid displaying empty lines).

https://github.com/twentyhq/twenty/assets/19412894/98a237a8-2c5c-4f34-b1b3-dd58c52d0314

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
This looks interesting I can work on this

**Comment by Bonapara** [comment]
Ok, I'll assign you! Thanks @Kanav-Arora ;)

**Comment by Kanav-Arora** [comment]
@Bonapara 
I must say this one is a really interesting issue
