### ISSUE TITLE
Update 'new object' page design in settings

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3082]
## Scope & Context

Today the "new object" page in settings displays three tabs:

![Screenshot 2023-12-19 at 18 32 38](https://github.com/twentyhq/twenty/assets/19412894/e6d8da59-4251-4cdc-b840-c75dfcd14c76)

## Expected behavior

1. We want to change the CTA name on the `Settings/Objects` page to "add object" instead of "new object"

![CleanShot 2023-12-19 at 18 24 00](https://github.com/twentyhq/twenty/assets/19412894/5884ea65-507f-4e18-92b0-99c9aef7fcac)

2. We want to remove the Standard and remote fields tabs and keep only the content of the "Custom field tab":

![image](https://github.com/twentyhq/twenty/assets/19412894/dd4f455c-24c7-468e-b178-3966db5299b1)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=14465-178772&mode=design&t=JJOijbrWPEg9mHWr-11

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
I can work on this

**Comment by Kanav-Arora** [comment]
I'm more interested in #3069 so ig someone else can take this one
