### ISSUE TITLE
Fix dark mode light box shadow

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3084]
# Context

On dark mode, the icon button box shadow is white. It should be dark in both light and dark mode:

# Current behavior

![Screenshot 2023-12-19 at 18 59 41](https://github.com/twentyhq/twenty/assets/19412894/5032e5a6-c6ab-4f3e-96a9-83e0e462b374)

# Desired behavior

- Apply the same box shadow to dark mode as the one used for light mode.
- Remove the "Scale" effect when hovering over the button, but retain the colored hover effect.

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=3063-45160&mode=design&t=JJOijbrWPEg9mHWr-11

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
I can work on this

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 

The box shadow used for these buttons is hard coded that's why its different in dark mode and no matching shadows exists for now. So should I create one?

<img width="1440" alt="Screenshot 2023-12-21 at 10 30 53 PM" src="https://github.com/twentyhq/twenty/assets/62852363/c5bd6808-20c9-4236-8c71-9f249fe8dd3d">

**Comment by charlesBochet** [comment]
@Kanav-Arora good point
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=2993%3A39004&mode=dev
Let's use the boxShadow `light` from the theme

**Comment by Kanav-Arora** [comment]
> @Kanav-Arora good point
> https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=2993%3A39004&mode=dev
> Let's use the boxShadow `light` from the theme

I tried but it looks really dull as the pixels are same but the color is dull in `light`

**Comment by charlesBochet** [comment]
ok! so it means that the design system should be adjusted. That's a question for @Bonapara to answer :)

**Comment by Kanav-Arora** [comment]
> ok! so it means that the design system should be adjusted. That's a question for @Bonapara to answer :)

Wait see below screenshot with `light` boxshadow
Please check if this looks okay

<img width="309" alt="Screenshot 2023-12-22 at 12 03 39 AM" src="https://github.com/twentyhq/twenty/assets/62852363/f63aaea9-e6c4-4343-bd68-cd068b148a68">

<img width="309" alt="Screenshot 2023-12-22 at 12 04 11 AM" src="https://github.com/twentyhq/twenty/assets/62852363/f7f203ff-86ff-4f45-9faf-7b2e43a60e88">

**Comment by Kanav-Arora** [comment]
Hi @Bonapara @charlesBochet 
Is this okay?

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
Please take a look at this

**Comment by Bonapara** [comment]
Hi @Kanav-Arora! Happy New Year! Yes, it's a good temporary solution. I'll address the floating buttons in a future issue to enhance their design for dark mode.

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
Happy New Year to you too! May this year brings happiness to your family.
Cool I'll raise a PR for this
