### ISSUE TITLE
I should be able to reset a date field

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3086]
# Current behavior

Once a date is set on the calendar, it cannot be reset or removed.

<img width="333" alt="Screenshot 2023-12-20 at 08 46 26" src="https://github.com/twentyhq/twenty/assets/6399865/6c786853-5f1d-42ec-ac16-336b01a6549c">
<img width="343" alt="Screenshot 2023-12-20 at 08 47 24" src="https://github.com/twentyhq/twenty/assets/6399865/1870f94f-d08b-4cee-aa8c-d6319ad02580">

**Comment by Bonapara** [comment]
# Desired behavior

- Change the popup padding from 8px to 4px.
- Add a "Clear" MenuItem button below the calendar to remove the selected date.

![image](https://github.com/twentyhq/twenty/assets/19412894/72aed941-130b-4925-a0ce-3bb325a887f5)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=2709-52753&mode=design&t=rheVYIEo1KPmumd2-11

**Comment by jss475** [comment]
Hey @FelixMalfait! Would I be able to take this on as my first issue?

**Comment by FelixMalfait** [comment]
@jss475 yes that's a good candidate if you've got a little frontend experience! (no backend needed)
- https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/ui/input/components/internal/date/components/InternalDatePicker.tsx#L235 > see how we use an external lib (react-date-picker)
- https://reactdatepicker.com/#example-children > see how you can inject something in the calendar here
- use developer mode in Figma to view the CSS

<img width="1084" alt="Screenshot 2023-12-22 at 10 03 07" src="https://github.com/twentyhq/twenty/assets/6399865/293fc4f4-e540-486b-8303-4ff7d155b91b">

Should I assign this to you?

**Comment by jss475** [comment]
@FelixMalfait Yup that would be great! I've been having trouble doing the local setup with yarn. Is there someone I can reach out to for some help?

**Comment by i-am-chitti** [comment]
@FelixMalfait, if @jss475 hasn't started, can you assign this to me? I'll work on this.

**Comment by atharvParlikar** [comment]
Hey @FelixMalfait, I got the styles working but I can't seem to get the CalendarInput back to "Empty" at first I thought maybe changing the value to something like null would do the job but that is not the case, the reactdatepicker docs doesn't seem to help, if you could guide me in some direction it would be great.

<img width="336" alt="screenshot" src="https://github.com/twentyhq/twenty/assets/58113282/76245129-7f8c-41ea-8ab3-d005e7693cb9">

**Comment by haseeb196** [comment]
maybe just change it to new date()

> Hey @FelixMalfait, I got the styles working but I can't seem to get the CalendarInput back to "Empty" at first I thought maybe changing the value to something like null would do the job but that is not the case, the reactdatepicker docs doesn't seem to help, if you could guide me in some direction it would be great.
> 
> <img alt="screenshot" width="336" src="https://private-user-images.githubusercontent.com/58113282/292760156-76245129-7f8c-41ea-8ab3-d005e7693cb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MjA5MjcsIm5iZiI6MTcwMzUyMDYyNywicGF0aCI6Ii81ODExMzI4Mi8yOTI3NjAxNTYtNzYyNDUxMjktN2Y4Yy00MWVhLThhYjMtZDAwNWU3NjkzY2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDE2MTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NjkxZWYyNDNhMmMwM2E1M2E4NDUyNTExNTk4MzY0ZGEwYzlmN2M3YWIyMjhjM2EyOWIwZmYzMGVkODgwY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vURIzc7u-zVKedJaGzIpPf1mIqG1PlomBrW2IztFdxA">

**Comment by FelixMalfait** [comment]
Appreciate the enthusiasm from all of you thanks a lot! Sorrywe'll be much slower to respond during this Christmas week

@atharvParlikar Maybe this can help? I didn't dig into it and this might be a false lead.
https://github.com/Hacker0x01/react-datepicker/blob/cd481302684f8487f5fc9445694ae774edba634d/src/index.jsx#L952
Otherwise can you show the code you've been trying? 

@jss475 Discord is usually a good place to get help. As mentioned this week we are mostly off so might be getting a little bit behind the requests!

@i-am-chitti Thanks! This one should be covered but I'll cleanup the good first issue tomorrow morning to make sure it's easier to find a good one that is unassigned

**Comment by atharvParlikar** [comment]
> maybe just change it to new date()
> 
> > Hey @FelixMalfait, I got the styles working but I can't seem to get the CalendarInput back to "Empty" at first I thought maybe changing the value to something like null would do the job but that is not the case, the reactdatepicker docs doesn't seem to help, if you could guide me in some direction it would be great.
> > <img alt="screenshot" width="336" src="https://private-user-images.githubusercontent.com/58113282/292760156-76245129-7f8c-41ea-8ab3-d005e7693cb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MjA5MjcsIm5iZiI6MTcwMzUyMDYyNywicGF0aCI6Ii81ODExMzI4Mi8yOTI3NjAxNTYtNzYyNDUxMjktN2Y4Yy00MWVhLThhYjMtZDAwNWU3NjkzY2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDE2MTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NjkxZWYyNDNhMmMwM2E1M2E4NDUyNTExNTk4MzY0ZGEwYzlmN2M3YWIyMjhjM2EyOWIwZmYzMGVkODgwY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vURIzc7u-zVKedJaGzIpPf1mIqG1PlomBrW2IztFdxA">

@haseeb196 Tried that, it just changes to the todays date which we do not want, we want the default "Empty" or no selected date.

**Comment by atharvParlikar** [comment]
Hey @FelixMalfait, I couldn't find how to make use of that clear function in the reactdatepicker but after further digging I found out that all it was doing was setting selected date to null, earlier when I tried using null the persistField won't allow, but I didn't pay much attention.

setting selected date as null was working, so I just changed the persistField to accept null also.

setting null as selected :=
<img width="903" alt="Screenshot 2023-12-25 at 11 05 21 PM" src="https://github.com/twentyhq/twenty/assets/58113282/fc235434-6fb7-406f-b9bd-c152b56c4a7c">

I have opened a pull request with all the changes, check it out if you get time
