### ISSUE TITLE
Add ability to paste an image directly into the activity body editor

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3090]
## Scope & Context

In ActivityBodyEditor.tsx, following https://github.com/twentyhq/twenty/pull/3044

## Current behavior

We can currently add an image by clicking on "+" and then on "Insert an image" in the contextual menu.

<img width="459" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/cca83015-df86-40a7-a4a0-13efa918c144">

## Expected behavior

We want the user to be able to just use cmd + v (paste) to insert an image from the clipboard with the same mechanism.

**Comment by Kanav-Arora** [comment]
Hi @lucasbordeau 
Can I work on this?
