### ISSUE TITLE
Improved menu item button design

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3098]
# Current Behavior

- Menu item's icon buttons look too large. 
- its background color in dark mode seems odd.

![Screenshot 2023-12-21 at 10 00 07](https://github.com/twentyhq/twenty/assets/19412894/d2a0d32a-3268-45fe-a005-7dd17ab1f911)

# Desired Behavior

In menu items, replace "floating buttons" with tertiary "light icon buttons":

https://github.com/twentyhq/twenty/assets/19412894/f61314cb-968d-410c-9b20-e8839f2acb5e

Also, replace the "icon group buttons" with multiple "light icon buttons" placed side by side, with a 2px gap between them:

https://github.com/twentyhq/twenty/assets/19412894/fe8e5acb-a27d-4ac9-9589-f32b68f0e584

Make sure the gap between the text and buttons is 4px. The icon buttons should never be on top of the text as their background is transparent. 

![CleanShot 2023-12-21 at 10 15 54](https://github.com/twentyhq/twenty/assets/19412894/7da697e1-e990-4ef7-9835-972305fd3d8b)

Update the revised Menu Item component:

![Screenshot 2023-12-21 at 10 21 37](https://github.com/twentyhq/twenty/assets/19412894/53406dd4-89e8-486c-af60-710c33b350de)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=2979-174004&mode=design&t=9XKex9M2nYivWERq-11

### Credits ;)

Thanks to @Kanav-Arora  🙌

![Screenshot 2023-12-21 at 10 19 52](https://github.com/twentyhq/twenty/assets/19412894/1a345b68-c8c3-4034-a55f-cef3ad784f4f)

**Comment by CzhCN0** [comment]
@Bonapara I believe I can complete this optimization. However, how do we intend to handle the possibility of overflowing text?

**Comment by Kanav-Arora** [comment]
> @Bonapara I believe I can complete this optimization. However, how do we intend to handle the possibility of overflowing text?

Hi @CzhCN0 
In this issue we'll be replacing floating button with light icon buttons so text will not overflow currently its not overflowing but being overlayed by floating buttons.
So there's a prebuilt component for light icon buttons

**Comment by CzhCN0** [comment]
> Hi @CzhCN0 In this issue we'll be replacing floating button with light icon buttons so text will not overflow currently its not overflowing but being overlayed by floating buttons. So there's a prebuilt component for light icon buttons
Hi @Kanav-Arora  Thank you for your response. I have pushed the code; please take a look and let me know if I misunderstood anything.

**Comment by Kanav-Arora** [comment]
Hi @CzhCN0 look good to me but @charlesBochet reviews and merge the code.
But great work with LightButtonGroup
