### ISSUE TITLE
Bug when deleting the last relation target on a comment thread (fe two calls are performed)

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#310]
<img width="1489" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/cefe568b-0dfa-4785-bc1f-ece561626123">

To reproduce, open a comment thread and remove all the companies / persons, the last one should stay checked and if you click one more time on it it will throw this error.

**Comment by charlesBochet** [comment]
I wonder if this is related to the fact that when we "connect" a comment to a Commentable with type and id, we are not checking if there is already one. As we are using StrictApp mode, the connection call is called twice and creates two associates, which leads to bugs on deletion.

**Comment by charlesBochet** [comment]
Resolved!
