### ISSUE TITLE
Add back the ability to multi-note/task on index with the action bar

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3106]
# Current behavior

We can only delete records with the action bar on the index

![Screenshot 2023-12-21 at 15 43 50](https://github.com/twentyhq/twenty/assets/19412894/4a267311-621c-4a01-8d0d-a5046798d58a)

# Desired behavior 

The action bar should also allow to add a note/task on multiple records at once:

![Screenshot 2023-12-21 at 15 46 12](https://github.com/twentyhq/twenty/assets/19412894/a9dc66dc-baa9-4180-923e-971e667e7474)

**Comment by i-am-chitti** [comment]
Hey @Bonapara,
Is there any UI flow or wireframe document here? Like on click of "Task" what should open up or how user will add the task or notes?

Also, as issue title contains "Add back". Does it mean, it was present early and has been removed?

**Comment by Bonapara** [comment]
Hi @i-am-chitti It should open the Note/task side panel of the record shows over the index:

![image](https://github.com/twentyhq/twenty/assets/19412894/951a6606-ba96-4de2-becc-24b879c67ff3)

https://github.com/twentyhq/twenty/assets/19412894/758f7d71-e733-4217-b289-265f4d2b32dd

**Comment by Kanav-Arora** [comment]
Hi @i-am-chitti 
Are you working on it?

**Comment by i-am-chitti** [comment]
@Kanav-Arora, yes, I'm working on it.

**Comment by i-am-chitti** [comment]
@Bonapara, have raised a PR here - https://github.com/twentyhq/twenty/pull/3137
