### ISSUE TITLE
Table Views - Temporary View

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#3127]
## Context

See #3099 

For this issue, following #3125:
- In the table page, when temporary view filters for this table are set:
  - Display "Back to [record label]" in place of the breadcrumb (to refine: use url parameters? Recoil State?)
  - Display the Object's icon + label in place of the View selector.
  - Disable removing the current filters.
  - Do not show the Object as "Active" in the Nav's Workspace section. Clicking on it removes the temporary filters.

## Figma

![image](https://github.com/twentyhq/twenty/assets/3098428/df6d9b34-deef-44c5-a252-96dbd4f71571)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=17774%3A52894&mode=dev

**Comment by FelixMalfait** [comment]
Note: I don't think we should call this "temporary view". For me this is the page for `/objectName?view=none`- it's not temporary, will always be there :)

**Comment by thaisguigon** [comment]
@FelixMalfait For now the way I implemented it for sake of simplicity, I use the currently selected view but I override only the View Filters (without persisting them). The user can persist the filters to the currently selected view if they want.
This is simpler because I only need to override the View Filters, otherwise I would need to provide the View Fields for the "none" view as well. But this can be changed later so we use all the available View Fields.
Also, the feature was named "Temporary filtered index" in the original issue written by @Bonapara: https://github.com/twentyhq/twenty/issues/3099

**Comment by thaisguigon** [comment]
Closed in favor of: https://github.com/twentyhq/twenty/issues/4093
