### ISSUE TITLE
Tasks and Notes activities update

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3132]
# Current behavior

Only task and note creation appear on the timeline.

# Notes activities

![CleanShot 2023-12-22 at 15 08 24](https://github.com/twentyhq/twenty/assets/19412894/db3840ea-29e7-4e85-bc47-2b6f4f4ddfab)

We want to display 4 kinds of activities:

1. A note has been deleted
2. A note has been commented
3. A note has been edited
4. A note has been created

# Tasks activities

![CleanShot 2023-12-22 at 15 11 14](https://github.com/twentyhq/twenty/assets/19412894/b1e4f992-991f-4021-86cf-740c70028dde)

We want to display 6 kinds of activities:

1. Someone commented a task
2. A task has been deleted
3. A task has been completed
4. A task has been assigned to
5. A task has been edited
6. A task has been created

Ensure the checkbox and strikethrough text reflect the task's status. For instance, incompleted tasks, even if deleted, should not appear as checked or crossed out.

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=17557-98088&mode=design&t=b1PFpV7KkNPNAh81-11

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
I can work on this

**Comment by AbhinawRatan** [comment]
> Hi @Bonapara I can work on this

Have you worked on this issue if no then please let me know

**Comment by Kanav-Arora** [comment]
> > Hi @Bonapara I can work on this
> 
> Have you worked on this issue if no then please let me know

I'm working
