### ISSUE TITLE
Timeline Calendar Event Details

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3134]
# Behaviors

![CleanShot 2023-12-22 at 15 31 08](https://github.com/twentyhq/twenty/assets/19412894/7ccdbad7-9ad7-460e-b903-2d11f6be2f2d)

Let's introduce two key activities: 

1. A team member gets an event invitation.
2. A team member organizes an event.

Let's use the Google Calendar API to fetch this information.

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
Can I work on this once design gets finalized?

**Comment by Bonapara** [comment]
Hello @Kanav-Arora let's wait for the specs first. I guess the core-team will handle a part of this one too!

**Comment by Bonapara** [comment]
@Weiko, did we implement 1 & 2?

**Comment by Weiko** [comment]
@Bonapara today we always show "${You / User.fullName} linked a calendar event with ${objectRecord.name} regardless of the participant status
