### ISSUE TITLE
Accounts/Emails/Inbox Settings - Add Contact auto-creation section

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3136]
# Desired behavior

We want to provide an option to automatically create contacts for people to whom you have sent emails:

![CleanShot 2023-12-22 at 15 54 26](https://github.com/twentyhq/twenty/assets/19412894/91dbcdbb-baeb-40c5-a885-c82b4c6e3c67)

This should be activated by default.

![image](https://github.com/twentyhq/twenty/assets/19412894/1c717a5c-64f5-48fd-8c1d-b5d3f2b11452)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=15568-46027&mode=design&t=b1PFpV7KkNPNAh81-11

**Comment by lakshay-saini-au8** [comment]
@thaisguigon @Bonapara 
Would like to work on this

**Comment by lakshay-saini-au8** [comment]
Created PR for the same Please Review

**Comment by thaisguigon** [comment]
Closed by: [#3188](https://github.com/twentyhq/twenty/pull/3188)
