### ISSUE TITLE
Demo Credentials not working

### ISSUE THREAD

**Issue by dotslashbit** [twentyhq/twenty#3148]
I tried to login using the demo credentials but it's not working.
<img width="1709" alt="Screenshot 2023-12-24 at 3 13 13 AM" src="https://github.com/twentyhq/twenty/assets/46224156/65d9f94d-ec6b-40d0-aa6c-8aefd8b95284">

**Comment by dotslashbit** [comment]
I can create a PR for this, cause I was going through the code contribution documentation and there you have the correct seed credentials

**Comment by charlesBochet** [comment]
Someone had deleted the user account. I have re-created the demo environment, it should be back :)
