### ISSUE TITLE
Search box: It should disappear when we click on any other link or anywhere on screen.

### ISSUE THREAD

**Issue by seAfnan** [twentyhq/twenty#3150]
## Bug Description

Search box remains open unless we click again on Search link on sidebar.

![twenty-bug](https://imgur.com/v9XqypC.gif)

## Expected behavior

Search dialog should be disappear when click on any other link or anywhere on page.

**Comment by seAfnan** [comment]
If i am right then, can i try to resolve this issue?

**Comment by Kanav-Arora** [comment]
Hi @seAfnan
@charlesBochet can guide better on this. But I just want to add one thing that 'esc' scoped key can also be added to close command menu.
You can achieve this by triggering `closeCommandMenu()` from `useCommandMenu()` api

**Comment by FelixMalfait** [comment]
@seAfnan thanks a lot! Good catch and I agree we should fix it (+ agree with @Kanav-Arora's comment that adding a shortcut for escape key would be cool).
Our inspiration for the command bar was Linear.app and Notion.so ; they both have the behavior you describe (for Notion they also added a dark overlay so it's even more obvious that if you click outside the window will go away. But we don't want that)

**Comment by Kanav-Arora** [comment]
@seAfnan If you want help you can ping me in the discord I have worked on most of the CommandMenu api so if you need any help feel free to ping.

**Comment by charlesBochet** [comment]
Thank you!
Yes, we would like to close it on "Esc" + on click outside.

A few hints to treat this ticket:
- In CommandMenu, set a new "hotkeyScope" called `command-menu-opened` (see `setHotkeyScope` and `useScopedHotkey`, you'll find many example in the code base)
(we cannot use `command-menu` as it is already the name of the global hotkeyScope listening to` Cmd+K` ; if we attach `Esc` to this existing hotkeyScope, as "command-menu" is a global hotkeyScope, it will be always listening to `Esc` and preventing other hotkeyScope to function properly)
- add onClickOutside behavior (they are existing hooks, you'll also find many example in the codebase)

**Comment by seAfnan** [comment]
Thanks guys for this acceptance. Its my first try to contribute. I noticed this issue in the live version and will try my best to resolve.
Sure @Kanav-Arora I will keep in touch with you.

**Comment by seAfnan** [comment]
I have done closing with "Esc", but couldn't understand how to apply onClickOutside. Can you please share your Discord so I can show/discuss.

**Comment by Kanav-Arora** [comment]
https://discord.com/invite/N7ZWMnZJ
