### ISSUE TITLE
Fixed header row 

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3156]
## Desired behavior
Creating an issue following Lucas' comment here: https://github.com/twentyhq/twenty/issues/2657#issuecomment-1869440868

It would be nice if the header row remained fixed as we scrolled (when there is a large number of items)

<img width="326" alt="Screenshot 2023-12-26 at 11 34 48" src="https://github.com/twentyhq/twenty/assets/6399865/9fe4403f-6f98-4689-8630-ae27f3aca069">

## Current behavior
It's not clear what the number I'm viewing refer to
<img width="327" alt="Screenshot 2023-12-26 at 11 33 00" src="https://github.com/twentyhq/twenty/assets/6399865/bd9cd3fd-2151-4b8b-b510-e5ff177da036">

**Comment by lucasbordeau** [comment]
Please use the same technical solution as in https://github.com/twentyhq/twenty/pull/3147, because re-rendering the RecordTable is very costly.

**Comment by dotslashbit** [comment]
@FelixMalfait I have only modified the styling of the header table, I hope this is what you are expecting, if there's any modification needed, then please let me know

**Comment by FelixMalfait** [comment]
@dotslashbit that looks great!

**Comment by FelixMalfait** [comment]
This is still open as the first attempt wasn't successful :)

**Comment by pranay911** [comment]
@FelixMalfait @lucasbordeau can you please assign this issue to me?
