### ISSUE TITLE
Fix navigation item height

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#316]
Coming soon item in the navigation menu are to heigh 28px instead of 24px.

**Comment by Bonapara** [comment]
![Image](https://github.com/twentyhq/twenty/assets/19412894/13842384-47d1-4165-a9c7-e6c8d4936fb0)

@charlesBochet pour info

**Comment by charlesBochet** [comment]
Fixed by https://github.com/twentyhq/twenty/pull/428
