### ISSUE TITLE
OSS Friends list is out of date

### ISSUE THREAD

**Issue by elie222** [twentyhq/twenty#3181]
## Bug Description

The OSS Friends list on Twenty.com is out of date.

For example, the official list includes Inbox Zero (and many others), but are not listed on Twenty:
https://twenty.com/oss-friends

The official list:
https://github.com/formbricks/formbricks/blob/ae530d710b3784b003a5b825b89646331cfdfbf4/apps/formbricks-com/pages/api/oss-friends/index.ts

**Comment by FelixMalfait** [comment]
Thanks! We've used Framer so far which made it hard to keep this list up to date.
But I just started out this week building a complementary Next.js version, see here: https://github.com/twentyhq/twenty/tree/main/packages/twenty-website
We'll be able to migrate the list once this is live in a few weeks

**Comment by FelixMalfait** [comment]
Steps to resolve:
- Create a new folder oss-friends in twenty/packages/twenty-website/src/app
- Create a page.tsx file in it
- In page.tsx  do GET request to https://formbricks.com/api/oss-friends to retrieve json that will be displayed
- Copy/adapt style from current page https://twenty.com/oss-friends (we cannot reuse any of the code, that page was built with Framer)

**Comment by gitstart-twenty** [comment]
On this

**Comment by suman-somu** [comment]
Hey, I want to try this to get done.

**Comment by elie222** [comment]
Feel free to copy the code from https://getinboxzero.com/github 

Simple page.tsx that loads the latest data.

**Comment by suman-somu** [comment]
Hey @Thiagomn1 , I was trying to do this one. 🙄
I couldn't make a draft yesterday due to some unwanted errors.

**Comment by suman-somu** [comment]
But your commit looks good than what I have made. So, maybe you should continue this.

**Comment by gitstart-twenty** [comment]
> But your commit looks good than what I have made. Maybe you should continue this.

Alright, no worries. All the best on your next ticket.

**Comment by FelixMalfait** [comment]
Thanks @suman-somu - we'll create many similar tickets this week :)

**Comment by suman-somu** [comment]
Looking forward to it.
