### ISSUE TITLE
Add scroll to left-side menu

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3185]
People have been playing around creating objects on the demo and it shows that left-side menu doesn't behave properly when there is a large number of items. We should introduce a scroll.

<img width="668" alt="Screenshot 2023-12-30 at 14 46 34" src="https://github.com/twentyhq/twenty/assets/6399865/ed9ca226-1abe-4b20-917d-49bbc7394f52">
<img width="635" alt="Screenshot 2023-12-30 at 14 45 52" src="https://github.com/twentyhq/twenty/assets/6399865/b6f67e95-7681-4fa0-ae79-1676f292e715">
<img width="441" alt="Screenshot 2023-12-30 at 14 47 48" src="https://github.com/twentyhq/twenty/assets/6399865/988e14c3-fb4d-4928-8865-42713fb63800">

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait 
Can I work on this?

**Comment by FelixMalfait** [comment]
Yes of course @Kanav-Arora thanks

**Comment by jordan-sussman** [comment]
@FelixMalfait Came across this and put a PR fix up here - https://github.com/twentyhq/twenty/pull/3187
@Kanav-Arora apologies if I got to this before you, but feel free to look it over.

**Comment by Kanav-Arora** [comment]
@jordan-sussman its a standard practice to raise PR post allocation of issue.
@FelixMalfait you should add this to contribution guideline as with increase in popularity of repo there will be multiple PRs for same issue and I think this should not be entertained

**Comment by dotslashbit** [comment]
I think it's best to start a pr if there's no PR linked to this issue and keep it as a draft pr, so that other contributors can see that there's someone already working.

If someone can only create a PR after getting assigned, then it should be mentioned clearly in the contribution instruction.

**Comment by FelixMalfait** [comment]
@jordan-sussman thanks! 
@Kanav-Arora I understand the frustration but it starts from a good intention, and it's such a small fix that it's not like there's ongoing work that's getting lost :)

I agree with you @Kanav-Arora @dotslashbit that we need to clarify the rules to find a good balance between people getting assigned but not doing the tasks, and people doing duplicated work because of lack of assignation. We'll braintstorm and update within a few weeks, along with the new contributors page / probably some form of non-monetary reward program.
It's a great problem to have - we're lucky to have all this community support!
