### ISSUE TITLE
README demo user (noah@demo.dev) does not work

### ISSUE THREAD

**Issue by dvmonroe** [twentyhq/twenty#3190]
## Bug Description

The demo user mentioned [here](https://github.com/twentyhq/twenty#demo) does not work.

**Example:** 

![Screenshot 2024-01-01 at 9 34 09 AM](https://github.com/twentyhq/twenty/assets/6183213/7830a5d6-1628-4d53-a411-0fc86f260886)

## Expected behavior

noah@demo.dev either logs me into the app for a demo or demo user is removed from README

**Comment by FelixMalfait** [comment]
Sorry I'm not sure why it didn't work for you :-(. I just tested and it works for me
