### ISSUE TITLE
icons in the footer lack noticeable interactivity

### ISSUE THREAD

**Issue by prashikk** [twentyhq/twenty#3196]
Description:
The social media icons in the footer lack noticeable interactivity when hovered over. This diminishes the user experience, considering the overall high-quality animation and CSS styling on the website.

Steps to Reproduce:
Navigate to the footer of the website.
Hover over the social media icons.

Expected Behavior:
The icons should exhibit a visible change when hovered over, such as lighting up or a similar appealing effect.

Suggestion for Enhancement:

Description:
To enhance the user experience, consider implementing a subtle but noticeable interactive behavior for the social media icons in the footer when hovered over.

Proposed Solution:
Apply a light-up effect or another visually appealing animation when the user hovers over the icons. This will not only improve the overall aesthetics but also encourage user engagement.

**Comment by Bonapara** [comment]
Done ;)

https://github.com/twentyhq/twenty/assets/19412894/4021979c-8670-4e93-b5df-f981ad34b4b6
