### ISSUE TITLE
Error with storybook addons due solved by removing ~/.pnp.cjs

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#3199]
I had this error when starting my storybook dev server:
![Capture d’écran 2023-12-29 à 16 36 28](https://github.com/twentyhq/twenty/assets/71827178/80e71643-47dd-4081-b4f1-07e3f5d5ce5f)

I saw this issue https://github.com/storybookjs/storybook/issues/20876 and tried the following solution: removing ~/.pnp.cjs and it worked.
![Capture d’écran 2023-12-29 à 16 43 39](https://github.com/twentyhq/twenty/assets/71827178/db279842-bab1-481a-b103-89c4daa13eaf)

**Comment by FelixMalfait** [comment]
Closing as I'm not sure there's anything we can do about it? Feel free to reopen @bosiraphael if you think there's something we can do in our repo
