### ISSUE TITLE
Implement RecoilScope

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#320]
Implement scoping of recoil atomFamily by using a generic react context.

The idea is to create a RecoilScope component that will be used to wrap a hierarchy of components.

Each component or hook called inside a RecoilScope component can then use something like : 

`useRecoilState(myAtomFamily(useContext(RecoilScopeContext)))`

Which can be factorized to : 

`useRecoilState(myAtomFamily(useRecoilScope()))`

See atomFamily documentation here : https://recoiljs.org/docs/api-reference/utils/atomFamily/#example

**Comment by charlesBochet** [comment]
This feature has been implemented this week. Thanks @lucasbordeau!
