### ISSUE TITLE
Add option to disable Signups

### ISSUE THREAD

**Issue by wladpaiva** [twentyhq/twenty#3201]
## Scope & Context
If you self host twenty right now, you would be essentially hosting a competition to the cloud service. Self-hosting usually means that they are going to be used internally therefore you wouldn't want to allow anyone to sign up at any time.

## Current behavior
There's no way to disable sign ups

## Expected behavior
Disable not authorized people to sign up.

## Technical inputs
Add an `IS_SIGNUP_DISABLED` env var to control whether signups are allowed or not.

**Comment by FelixMalfait** [comment]
Good idea! 
Declare env variable in EnvironmentService, and protection should be done on the backend side in AuthService.
We should add a check in the signup method of that service.
Probably in that case we also always want to return true in checkUserExists() - that way user is not redirected to signup form when trying to login with an email that is recognized. Let's try it, unless I'm missing something that goes against it...

**Comment by arthureichelberger** [comment]
Would be interested in taking this 👋

No problem with this?

**Comment by FelixMalfait** [comment]
Of course @arthureichelberger thanks a lot! Let us know if you're stuck
