### ISSUE TITLE
Broken links in Getting Started documentation

### ISSUE THREAD

**Issue by gabriel-r** [twentyhq/twenty#3227]
## Bug Description

Broken links in Getting Started documentation:

> For correct operation your will need to set [environment variables](https://docs.twenty.com/start/self-hosting/enviroment-variables), a example configuration can be found [here](https://github.com/twentyhq/twenty/blob/main/server/.env.example).

I'd like to help fix this, but the link to "Edit this page" is also borked:

> [Edit this page](https://github.com/twentyhq/twenty/edit/main/docs/docs/start/self-hosting/self-hosting.mdx)

**Comment by Jeong-Min-Cho** [comment]
![image](https://github.com/twentyhq/twenty/assets/9837449/9d3eb465-30ab-4b56-8fca-21c68fb6e7ca)
![image](https://github.com/twentyhq/twenty/assets/9837449/5329a4b5-e6e0-4fd1-9336-4718811d04b5)

This seems to be already **fixed** in the main branch. 
I guess the live version uses the outdated documents.

**Comment by gabriel-r** [comment]
Someone please push the button :)

**Comment by FelixMalfait** [comment]
Sorry for the delay! Closing as this is now fixed
