### ISSUE TITLE
Fix Comments arrow button color

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#324]
The placeholder arrow is black
Should be light40

**Comment by Bonapara** [comment]
<img width="70" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/02f2c824-c5d7-47cb-81ef-32854bceff7c">
Micro fix pour release V0.1

**Comment by charlesBochet** [comment]
Fixed by https://github.com/twentyhq/twenty/pull/389
