### ISSUE TITLE
First column box shadow fix

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3241]
# Expected Behavior

1. Change the box shadow to strong instead of light.
2. We need to keep the right border of the cells on the right in addition to the box shadow.
3. The box shadow should stay dark even in dark mode (White box shadows are prohibited 😅 - Make sure to remove them from the whole project)

### To do
![CleanShot 2024-01-04 at 18 22 02](https://github.com/twentyhq/twenty/assets/19412894/b035b116-c30a-4608-ba41-1447eb007357)

![CleanShot 2024-01-04 at 18 27 30](https://github.com/twentyhq/twenty/assets/19412894/0f87c2ea-3d87-4c6c-a8b9-0c3486e69c43)

### To avoid

![CleanShot 2024-01-04 at 18 25 16](https://github.com/twentyhq/twenty/assets/19412894/66fa58ad-1aef-46a7-bac1-110a6766c1b9)

### Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=15958-80931&mode=design&t=BFCEpNNScuH0kXRo-11

**Comment by HodaSalim** [comment]
I would like to work on this please

**Comment by Jeong-Min-Cho** [comment]
@Bonapara The pull request for this issue is up now
