### ISSUE TITLE
Padding on Menu Item with icon button

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3248]
# Current behavior

The right padding of the icon button is bigger than the other one

![CleanShot 2024-01-05 at 09 47 00](https://github.com/twentyhq/twenty/assets/19412894/f4e54173-643a-49a7-b6de-cdf6605e6ff0)

# Desired behavior

The padding around the icon button should be 4px on all side

![CleanShot 2024-01-05 at 09 45 50](https://github.com/twentyhq/twenty/assets/19412894/4411649e-de8f-4556-aeec-380bb418d9b4)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=2979-174004&mode=design&t=tY8CUvxiUNT2VRnR-11

**Comment by suman-somu** [comment]
I'm trying this one.
