### ISSUE TITLE
Calendar clear button should take the full width

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3249]
# Current behavior

![CleanShot 2024-01-05 at 10 36 06](https://github.com/twentyhq/twenty/assets/19412894/21807d4f-a444-436a-a539-5192b9b6f512)

# Desired behavior

The button should take the full width as a regular menu item

**Comment by Jeong-Min-Cho** [comment]
Hello, I have a quick question on it.

As you said, "The button should take the full width as a regular menu item", should we keep the text on the left like this?

![image](https://github.com/twentyhq/twenty/assets/9837449/29e4a76e-135f-4c0e-87de-1b83e4749458)

Or should we centralize it?

![image](https://github.com/twentyhq/twenty/assets/9837449/74e13414-8eab-4e6f-bfff-8e47942584b1)

Thanks
