### ISSUE TITLE
New fields should be sorted on objet detail page

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3253]
URL to settings page: https://localhost/settings/objects/companies
<img width="533" alt="Screenshot 2024-01-05 at 12 11 21" src="https://github.com/twentyhq/twenty/assets/6399865/4dfcd1bc-c104-469e-a656-a9eace29c450">

I just created the fields "start date" and "end date" and they were randomly added in the middle of the list of fields.
Instead, we would like to sort this list.

We'd like to show all the standard fields at first, then all the custom fields.
And within each, fields should be sorted by their creation date. So the custom field I've just created should appear last in the list.

**Comment by Jeong-Min-Cho** [comment]
@FelixMalfait The pull request for this issue is up now.
