### ISSUE TITLE
All active participants should be displayed within the same thread

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#3257]
## Scope & Context

The frontend should only display the recipients that have "from" as a role meaning they've sent at least 1 message in the thread.

### Current behaviour

Currently we only display 1 "participant".

### Desired behaviour

We want to display at least 2 "participants" in the UI 

![Frame 4097](https://github.com/twentyhq/twenty/assets/1834158/cf3f3122-b63a-4ff0-8b44-419bb5376829)

## Technical inputs

```typescript
  getTimelineThreadsFromPersonId(personId: "") {
    body
    numberOfMessagesInThread
    read
    receivedAt
    senderPictureUrl
    senderName
    subject
  }
```

```typescript
  getTimelineThreadsFromPersonId(personId: "") {
    body
    numberOfMessagesInThread
    read
    receivedAt
    recipients {
        displayName
        pictureUrl
    } 
    subject
  }
```

**Comment by Weiko** [comment]
@bosiraphael to update BE with the new recipients list

**Comment by Weiko** [comment]
@bosiraphael actually, before doing that, the BE should probably adapt the structure of TimelineThread so it contains all the messages as well; In preparation for the ticket that will add the opened thread component.

**Comment by bosiraphael** [comment]
@Weiko Good point

**Comment by Weiko** [comment]
Blocked by #3450
