### ISSUE TITLE
When I add a new field on opportunities, it should be visible in Kanban view

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3258]
I was doing a demo to someone and saw the following bug:
- I added a new column on the opportunity model (settings > data model)
- I switched back to the app on the opportunities kanban view, the field wasn't visible
- I refreshed the page, the field became visible

**Comment by CzhCN0** [comment]
It looks like it might be an issue with the state update. In the next few days, I will attempt to troubleshoot this bug.

**Comment by FelixMalfait** [comment]
@CzhCN0 Yes probably linked to Apollo's caching mechanism, and we need to update `refetchQueries` but not sure, to be confirmed!

**Comment by AdityaPimpalkar** [comment]
@FelixMalfait It seems like the field is hidden by default after creating it, toggling it from hidden to visible worked just fine. Do you mean it should be visible by default?

**Comment by FelixMalfait** [comment]
@AdityaPimpalkar you're right I couldn't reproduce, closing this!
