### ISSUE TITLE
Add a page to create and edit webhook

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3272]
Followup of #3271 

![Edit](https://github.com/twentyhq/twenty/assets/6399865/52e0436f-acb4-4c7f-a790-3916ca1174e3)
![Edit](https://github.com/twentyhq/twenty/assets/6399865/1bc22f78-73dc-440b-81ad-899927286937)

We already have the backend completed for webhooks.
We need to be able to create a new webhook.
Note: set `operations` column on webhooks table to be equal to `*.*` that will mean every event should be sent to that URL (in later iterations we will let users customize this)

**Comment by i-am-chitti** [comment]
Hey @FelixMalfait, I'm ready to pick both tickets. Could you check the Figma designs? The attached screenshots on this issue are not present in Figma referred on other ticket.

**Comment by FelixMalfait** [comment]
@i-am-chitti thanks again! I made those designs quickly in Figma based on the existing designs for the API Keys so you shouldn't have to redesign anything I believe - everything is already there. I lost the source file but if it's really a blocker let me know and I can redo it :)

**Comment by FelixMalfait** [comment]
@i-am-chitti just noticed that @lakshay-saini-au8 had sent a message before on the other issue. If you don't mind we can assign him? Sorry for the confusion

**Comment by FelixMalfait** [comment]
@lakshay-saini-au8 if it's okay with you would you mind commenting on this issue that way I can assign it to you? Thanks!

**Comment by lakshay-saini-au8** [comment]
sure i will take on this too

**Comment by kuluruvineeth** [comment]
@lakshay-saini-au8 are u working on this issue?, If not could i ask @FelixMalfait to assign this issue to me

**Comment by martmull** [comment]
Hello @lakshay-saini-au8, the previous PR for the webhook list has been merged -> https://github.com/twentyhq/twenty/pull/3567
Do you plan to work on the update?
Cheers

**Comment by lakshay-saini-au8** [comment]
Great @martmull 
I am starting on this

**Comment by martmull** [comment]
@lakshay-saini-au8 I will work on this this week
