### ISSUE TITLE
Adapt Tab List on Record Show Page for iPad and mobile display

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3275]
The tab bar is becoming too big.

On smaller desktop (e.g. iPad), it's impossible to access the emails tab:
<img width="675" alt="Screenshot 2024-01-07 at 19 18 09" src="https://github.com/twentyhq/twenty/assets/6399865/3c1068ae-0e2f-4860-b1ee-4d8a51a645a2">

On mobile this adds a scroll to the page:
<img width="352" alt="Screenshot 2024-01-07 at 19 18 53" src="https://github.com/twentyhq/twenty/assets/6399865/8686d201-7313-4249-8d80-b73c2d2f3312">

cc @Bonapara for recommandations

**Comment by Bonapara** [comment]
Quick fix:

![image](https://github.com/twentyhq/twenty/assets/19412894/481a78b0-4040-4def-8504-c19f5fa57157)

The timeline menu should have a horizontal scroll to view the tabs on the right.

**Comment by jeet1desai** [comment]
@Bonapara @FelixMalfait, could you please assign it to me, I'd love to do it.

**Comment by FelixMalfait** [comment]
Thanks @jeet1desai! Done
