### ISSUE TITLE
Release 0.2.3

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#3283]
Very similar to previous releases:

- Deploy on next, prod
- Build 4 docker images (server, docs, front, postgres) and push them to docker hub
- Create release note

**Comment by TBG-FR** [comment]
Hello there ! Awesome project ✨ 

Just a small suggestion/improvement related to Docker images : Twenty DockerHub page(s) could use some "tuning" to look like something official (at least a logo, and also maybe a README) 😉 That would avoid any doubt on the legitimacy of the user/images on the Hub !

**Comment by TBG-FR** [comment]
@FelixMalfait You're welcome 😉 DockerHub new pricing rules are crazy... I naively believed it would be free of charge for open source projects 😅 No worries, that's already much better ! And I really hope you do 🤞
