### ISSUE TITLE
Create an empty Thread component

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#3290]
See #3264 

# Create an empty Thread component

We have a list of threads in the UI.
We want to display the following component after clicking on one thread.

<img width="360" alt="Capture d’écran 2024-01-05 à 17 32 36" src="https://github.com/twentyhq/twenty/assets/71827178/6f2da938-98dc-477f-917e-fb11502819a3">

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=16042%3A37861&mode=dev

For this ticket, we want to create an empty `Thread` component.

**Comment by bosiraphael** [comment]
@i-am-chitti can you comment here so I can assign you to this issue ? :)

**Comment by suman-somu** [comment]
Shouldn't there be any styling to the container holding all the other components ?

**Comment by i-am-chitti** [comment]
Hey @bosiraphael, I'm currently working on this https://github.com/twentyhq/twenty/issues/3245. Will be able to take this once I complete that.

**Comment by bosiraphael** [comment]
@suman-somu Hello ! Yes there is one :)

<img width="240" alt="Capture d’écran 2024-01-08 à 17 49 28" src="https://github.com/twentyhq/twenty/assets/71827178/46f6dfa7-c4b6-445f-a8d9-7baca2dd9e71">

**Comment by bosiraphael** [comment]
Hey @i-am-chitti, thank you very much. I'm assigning you to this one then !

**Comment by bosiraphael** [comment]
Hello @i-am-chitti ! Any update on this one?

**Comment by i-am-chitti** [comment]
Hey @bosiraphael I'm still working on the other issue mentioned above. I can take this in the next week. If it's on priority, may be un-assign me accordingly.

**Comment by bosiraphael** [comment]
Hey @i-am-chitti, sorry for the inconvenience but we will assign this issue to @thomtrp since we need this done by the end of the week. Thank you very much for contributing !

**Comment by abdul-irfan-k** [comment]
Hi can i work on this
