### ISSUE TITLE
Create a ThreadActionBar component

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#3291]
See #3264 

# Create a `ThreadActionBar` component

<img width="361" alt="Capture d’écran 2024-01-05 à 17 40 08" src="https://github.com/twentyhq/twenty/assets/71827178/e7ad9f04-3365-4d95-8ca9-02b57ebbdffe">

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=16042%3A37861&mode=dev

For the V1 of the component we don't want to show the ThreadMembers in the upper right corner.

<img width="361" alt="Capture d’écran 2024-01-05 à 17 40 08" src="https://github.com/twentyhq/twenty/assets/71827178/f0311978-366a-432a-992e-d1ba004a9e87">

Add it to the `Thread` component.

**Comment by abdul-irfan-k** [comment]
Hi can i work on this
