### ISSUE TITLE
Create a ThreadHeader component

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#3292]
See #3264 

# Create a `ThreadHeader` component

<img width="359" alt="Capture d’écran 2024-01-05 à 17 40 17" src="https://github.com/twentyhq/twenty/assets/71827178/de77cc96-1a1d-4e0c-a4b0-28bbf9b6a09c">

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=16042%3A37861&mode=dev

Props:
- subject: string
- lastMessageSentAt: Date

Add it to the `Thread` component.

**Comment by suman-somu** [comment]
I'm on this

**Comment by suman-somu** [comment]
I made progress with the layout. 
Currently i don't have access to my machine. I will make a pr on tuesday once i'm back. If that's okay for you. 
You can reassign someone if urgent.

**Comment by bosiraphael** [comment]
No problem ! Thank you very much for contributing :)

**Comment by suman-somu** [comment]
Hey @bosiraphael , I've made the pr. Sorry for taking so long.
