### ISSUE TITLE
Create a ThreadBottomBar component

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#3294]
See #3264 

# Create a `ThreadBottomBar` component

<img width="359" alt="Capture d’écran 2024-01-05 à 17 40 36" src="https://github.com/twentyhq/twenty/assets/71827178/efee556f-c875-4ba5-a27b-a367cb29cb68">

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=16042%3A37861&mode=dev

For now, the buttons should do nothing.

Add it to the `Thread` component.

**Comment by AFZL210** [comment]
@bosiraphael  I would love to work on this if no one else is working on it.

**Comment by bosiraphael** [comment]
Hello @AFZL210 ! Thank you very much, I'm assigning you to this issue.

**Comment by bosiraphael** [comment]
Hello @AFZL210 ! Any update on this one?

**Comment by AFZL210** [comment]
> Hello @AFZL210 ! Any update on this one?

Sorry for the delay, will make a PR before Sunday.

**Comment by bosiraphael** [comment]
No problem :) Thank you !

**Comment by AFZL210** [comment]
I am unassigning myself due to some hardware issues. feel free to take this up.

**Comment by abdul-irfan-k** [comment]
Can i work on this

**Comment by bosiraphael** [comment]
Okay @AFZL210, no worries ! Thank you for your response.
Hello @abdul-irfan-k, thank you for taking the issue, I'm assigning you ! :)

**Comment by abdul-irfan-k** [comment]
Hi @bosiraphael  please review it #3474
