### ISSUE TITLE
Find unique logic for multi-object request and pickers

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3298]
## Scope & Context

- Relation multi-object picker
- Command menu

## Expected behavior

We want to find a good DX for multi-object request and pickers in any part of the app.

We have currently three good places to start with : 
- Activities relations
- Show page relations
- Command menu

See also how to make single queries for activity target picker and other related pickers.

**Comment by lucasbordeau** [comment]
Closing https://github.com/twentyhq/twenty/issues/3424

**Comment by FelixMalfait** [comment]
@ijreilly was this tackled as part of search? I think we should tackle it if no as it's one of our oldest tech debt ticket

**Comment by ijreilly** [comment]
I will add it to the current sprint ! @FelixMalfait
