### ISSUE TITLE
Remove the comment thread level scrollbar

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#330]
With many relations : 
<img width="343" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/9e8ca09c-1f9d-49fe-bf83-52c773404480">

Multiple threads : 

<img width="325" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/1b92734e-8266-466a-833b-9584c50b68b8">

Is it normal that the right drawer can overflow but it's not normal that in this use case it expands outside of its parent container

**Comment by Bonapara** [comment]
Remove the comment thread level scrollbar
