### ISSUE TITLE
Settings/Objects/Object Detail - Fields section - Implement "Set as record text" menu item for Custom objects

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#3302]

**Comment by charlesBochet** [comment]
+ prevent user from disabling a field that is set as record identifier (also prevent in backend)

**Comment by charlesBochet** [comment]
@Weiko can provide more context on how to handle the backend

**Comment by Weiko** [comment]
> @Weiko can provide more context on how to handle the backend

@charlesBochet @thaisguigon you can check fireld-metadata.service.ts#updateOne method. 
We already fetch the object so you can add this in the method
```
    if (
      objectMetadata?.labelIdentifierFieldMetadataId ===
        existingFieldMetadata.id &&
      fieldMetadataInput.isActive === false
    ) {
      throw new BadRequestException('Cannot deactivate label identifier field');
    }
```
