### ISSUE TITLE
On user details page, task tab selected, when I click on the user of the task, I get a 404

### ISSUE THREAD

**Issue by thomtrp** [twentyhq/twenty#3305]
## Bug Description

See screenshot. Hitting back button in navigator does not work either 

<img width="400" alt="Capture d’écran 2024-01-08 à 12 49 16" src="https://github.com/twentyhq/twenty/assets/22936103/abe0c3a3-7166-42ab-b69d-6ed01d307366">

## Expected behavior

Display user details page

**Comment by charlesBochet** [comment]
This has been fixed!
