### ISSUE TITLE
Unify standard and custom object n+1 requests and mutations for activityTargets

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3309]
## Scope & Context

On GraphQL queries and mutations for n+1 relations.

## Current behavior

Requesting an object n+1 of activityTarget : 

```gql
{
  ...
  myStandardObject {
    id
    ...
  }
  myCustomObject {
    id 
    ...
  }
}
```

Requesting an object id n+1 of activityTarget : `_myCustomObjectId`

```gql
{
  ...
  myStandardObjectId 
  _myCustomObjectID
}
```

Creating an activity target : 

```gql
// OK ✅
createActivityTarget(
  data: {
    activityId: "00b59efd-9618-4101-abcc-f2bea869de7d"
    _customObjectId: "3af52962-869f-47d8-a34f-3d7447386b5d"
  }
) {
  id
}

// OK ✅
createActivityTarget(
  data: {
    activityId: "00b59efd-9618-4101-abcc-f2bea869de7d"
    customObject: "3af52962-869f-47d8-a34f-3d7447386b5d"
  }
) {
  id
}


// Not OK ❌
createActivityTarget(
  data: {
    activityId: "00b59efd-9618-4101-abcc-f2bea869de7d"
    standardObject: "3af52962-869f-47d8-a34f-3d7447386b5d"
  }
) {
  id
}

// OK ✅
createActivityTarget(
  data: {
    activityId: "00b59efd-9618-4101-abcc-f2bea869de7d"
    standardObjectId: "3af52962-869f-47d8-a34f-3d7447386b5d"
  }
) {
  id
}
```

We currently use `getActivityTargetObjectFieldIdName` to handle this and as it may be the case on other objects n+1 fields too, this minor difference is very error prone during development of complex n+1 features.

We'd like to unify this, either by proposing a common API on the backend side, or by abstracting this on the frontend side each time we manipulate an n+1 query or mutation field.

**Comment by charlesBochet** [comment]
Yes, it is still an issue on our GraphQL schema 
@Weiko @magrinj

**Comment by lucasbordeau** [comment]
We need to check if it is still an issue.
