### ISSUE TITLE
New Empty states

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3310]
# Current Behavior

The empty states consist of two texts and a call-to-action (CTA):

| 404 & 500 Error pages | Indexes Empty state |
| --- | --- |
| ![image](https://github.com/twentyhq/twenty/assets/19412894/56a83ab7-06d7-42ff-af0f-74490bb604ed) | ![image](https://github.com/twentyhq/twenty/assets/19412894/c617b62a-d4c9-420b-8334-e08721d7dec3) |

# Desired behavior

We want to update the following empty States with an animated illustration:

**ERROR PAGES**

- [500 error page](https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19450-93391&mode=design&t=OsVwULzMocuuEGia-11)
- [404 error page](https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19450-93376&mode=design&t=OsVwULzMocuuEGia-11)

**INDEXES**

- [No records on an index](https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19429-87978&mode=design&t=OsVwULzMocuuEGia-11)
- [500 error on an index](https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19439-92929&mode=design&t=OsVwULzMocuuEGia-11)

**SHOWS**

-[ No activities in the record timeline.](https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19429-88646&mode=design&t=OsVwULzMocuuEGia-11)
- [No tasks associated with the record.](https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19429-89899&mode=design&t=OsVwULzMocuuEGia-11)
- [No notes associated with the record.](https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19429-90524&mode=design&t=OsVwULzMocuuEGia-11)
- [No files associated with the record.](https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19437-91183&mode=design&t=OsVwULzMocuuEGia-11)

The goal is to make the illustration track the mouse:

https://github.com/twentyhq/twenty/assets/19412894/edb1624b-30d6-41a2-bb3a-1b246918cb45

Ensure that the size of the Figma files is appropriate. For small illustrations, the largest side should be 160px, while for larger illustrations like error 500 and 404, the bigger side should be 240px.

![image](https://github.com/twentyhq/twenty/assets/19412894/a1d73fd0-70fe-418d-8520-01b62f6140e8)

### Export the images:

Export the images in PNG format using the X2 parameter in Figma:

1. Select an image.
2. Set up the export preferences.
3. Click "export."

![CleanShot 2024-01-08 at 17 09 23](https://github.com/twentyhq/twenty/assets/19412894/38994670-67fe-44f2-8efd-747b64d8caec)

### Implement the effect.

Please ensure that the dimensions of the illustrations are as specified above.

Bonus: The moving image should return to its initial position when the mouse leaves the window. Use Framer Motion as library.

[👀See effect on codesandbox
](https://codesandbox.io/p/sandbox/moving-effect-twenty-empty-states-pgzcc2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr5039vi00063b6k99w7fxz9%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr5039vi00023b6k8m8eto64%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr5039vi00033b6k87r4hc3g%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr5039vi00053b6ktyz6bwwm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B58.21267403811194%252C41.78732596188806%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr5039vi00023b6k8m8eto64%2522%253A%257B%2522id%2522%253A%2522clr5039vi00023b6k8m8eto64%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clr5039vi00053b6ktyz6bwwm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr5039vi00043b6kqu8l09x2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clr5039vi00053b6ktyz6bwwm%2522%252C%2522activeTabId%2522%253A%2522clr5039vi00043b6kqu8l09x2%2522%257D%252C%2522clr5039vi00033b6k87r4hc3g%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clr5039vi00033b6k87r4hc3g%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Implement the new titles & subtiles

![Screenshot 2024-01-08 at 17 25 22](https://github.com/twentyhq/twenty/assets/19412894/dc6cc738-5042-4a80-b15c-5b906370a533)

(The spacing also have been updated)

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19450-97860&mode=design&t=OsVwULzMocuuEGia-11

# Codesandbox

[Link](https://codesandbox.io/p/sandbox/moving-effect-twenty-empty-states-pgzcc2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr5039vi00063b6k99w7fxz9%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr5039vi00023b6k8m8eto64%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr5039vi00033b6k87r4hc3g%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr5039vi00053b6ktyz6bwwm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B58.21267403811194%252C41.78732596188806%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr5039vi00023b6k8m8eto64%2522%253A%257B%2522id%2522%253A%2522clr5039vi00023b6k8m8eto64%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clr5039vi00053b6ktyz6bwwm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr5039vi00043b6kqu8l09x2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clr5039vi00053b6ktyz6bwwm%2522%252C%2522activeTabId%2522%253A%2522clr5039vi00043b6kqu8l09x2%2522%257D%252C%2522clr5039vi00033b6k87r4hc3g%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clr5039vi00033b6k87r4hc3g%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by FelixMalfait** [comment]
This looks so cool! 😍

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait 
Looks interesting. I can give this one a shot. Please assign me.

**Comment by Bonapara** [comment]
Thanks so much @Kanav-Arora 🙌

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
I have thought of way of using a reusable component for this one
Can you give me an idea of naming and the desired directory for the component ?
and I am adding these images to the `public/images/status` if its alright

I'm just asking this beforehand to save to effort of renaming the files

**Comment by charlesBochet** [comment]
Love the design!

**Comment by charlesBochet** [comment]
@Kanav-Arora 
- I would go with: `public/images/placeholders` for the images
- I would create a "animated-placeholder" section in ui/layout folder that would be able to display an image and to track the mouse
- then I will use it directly in the Pages for 404, 500 global handler
- and I will use it in the existing empty states / error components

**Comment by Kanav-Arora** [comment]
Hi

In the figma files the design is not corresponding to our theme values. I'm not sure about the gap.
@charlesBochet I have introduced Title and Subtitle columns which can be reused instead of creating styled components for every section.

@Bonapara I'm not sure about the gap between image, title and subtitle
Can you look into it and confirm so that I can proceed to other sections.

I have taken design values which were close to figma but this looks small to me. Please confirm once

<img width="1440" alt="Screenshot 2024-01-16 at 10 25 46 PM" src="https://github.com/twentyhq/twenty/assets/62852363/cd4ff09f-a9b5-4a01-b5b1-4a186ff02e38">

**Comment by Bonapara** [comment]
Hi @Kanav-Arora! Good catch! On Figma, there should be a 24px gap between the illustration and text, as well as between the text and CTA. Does your branch follow this guideline? Looks indeed too narrow, otherwise we should switch it to 32px

![CleanShot 2024-01-17 at 10 07 38](https://github.com/twentyhq/twenty/assets/19412894/cedec7c6-d670-4374-beef-fdec33ef0cb9)

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait @charlesBochet @Bonapara 
Can you give latest commit a look. Text looks small to me

**Comment by Kanav-Arora** [comment]
Hi @charlesBochet 
I need a suggestion
Error 500 and 404 are being enqueued to Snackbar queue.
Now if error.status is 500 and 404 we want this new page so should I add this condition in enqueue function?
if status code will be 500 or 404 instead of adding error to queue we'll show that route

**Comment by FelixMalfait** [comment]
@Kanav-Arora Not 100% sure I understood correctly but I feel like errors that are in snackbars should remain in snackbars - we don't want to make the experience worth than it is by redirecting them to a different page and losing ongoing work/context.
We already have a 404 page:
<img width="602" alt="Screenshot 2024-01-17 at 17 51 24" src="https://github.com/twentyhq/twenty/assets/6399865/825a8fd4-1384-44f8-9c96-c94d5668627f">

The 500 design we can use for when it looks like in #2788? Not really a 500 / server error though so probably we should adapt the naming a bit (e.g. error_404, error_critical instead of 500)

**Comment by FelixMalfait** [comment]
@Kanav-Arora yes but after consideration I think we should keep those 500 errors on apollo queries as snackbar. For example if you're looking at a given company then you attempt to create a note and it doesn't work for some reason, you don't want to make it worse by redirecting them to a different page. 
The only use-case for the 500 design would be when the frontend server returning the initial App.tsx  / handling the initial load returns a 500. That's seems unlikely to happen often.

**Comment by charlesBochet** [comment]
Indeed, errors can happen at 3 level:
- App level: display the big 500 error
- Page or section level: display the 500 within the page
- Server side / apollo query : let's keep it in the snack bar

**Comment by Kanav-Arora** [comment]
> Hi @Kanav-Arora! Good catch! On Figma, there should be a 24px gap between the illustration and text, as well as between the text and CTA. Does your branch follow this guideline? Looks indeed too narrow, otherwise we should switch it to 32px
> 
> ![CleanShot 2024-01-17 at 10 07 38](https://private-user-images.githubusercontent.com/19412894/297324182-cedec7c6-d670-4374-beef-fdec33ef0cb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MDI0MjgsIm5iZiI6MTcwNTYwMjEyOCwicGF0aCI6Ii8xOTQxMjg5NC8yOTczMjQxODItY2VkZWM3YzYtZDY3MC00Mzc0LWJlZWYtZmRlYzMzZWYwY2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDE4MjIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZjM4YmM0ZDI3ZGEwNGU0ZDRkMjdjMzJiNmIxNTYxZjU5NDBiNjkxNGU2MDMwMzM5NTRmMTAwNDA0MDcxY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c8_pJFZRK4GbyQlUz7_MC2YuC38DmkIJuhk8JaPu-nk)

@Bonapara 

What should be the gap between title and subtitle

**Comment by Bonapara** [comment]
@Kanav-Arora supposed to be 12px

**Comment by Kanav-Arora** [comment]
<img width="1440" alt="Screenshot 2024-01-19 at 10 08 15 PM" src="https://github.com/twentyhq/twenty/assets/62852363/24f1bb08-4c9b-487c-a77a-c1e68bb0d8f7">

Hi @Bonapara 
I'm not sure I have taken font size according to figma only but for 404 and 500 error these look bit small to me. Am I taking the right sizes?

**Comment by Bonapara** [comment]
Hi @Kanav-Arora, the title font size is 24px, and the subtitle is the regular 13px.
The gap between the two titles is 16px.

Do you have access to the Figma? https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19450-93376&mode=design&t=gJFE7wMxsSs71Fru-11
