### ISSUE TITLE
Bug when trying to access the file page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3315]
# Description

When accessing the `files` tab on a company show, an alert gets triggered: 

`Error during useFindManyRecords for "attachments", Response not successful: Received status code 400`

![Screenshot 2024-01-08 at 18 40 31](https://github.com/twentyhq/twenty/assets/19412894/1108b4df-19b7-4465-bc7b-1d6e5e3e2bcc)

**Comment by FelixMalfait** [comment]
I'm not able to reproduce it. Does it happen on every page for you? would it be possible give the response to the graphql request (from your network tab)?

**Comment by Bonapara** [comment]
![CleanShot 2024-01-09 at 10 02 16](https://github.com/twentyhq/twenty/assets/19412894/e1749ac3-a402-40fe-9cfa-969258cc7e5e)

**Comment by Bonapara** [comment]
`{
    "errors": [
        {
            "message": "Variable \"$filter\" got invalid value { companyId: { eq: \"8ad6b436-0b8b-4c7e-b649-946305aa8e5e\" } }; Field \"companyId\" is not defined by type \"AttachmentFilterInput\". Did you mean \"company\"?",
            "locations": [
                {
                    "line": 1,
                    "column": 27
                }
            ]
        }
    ]
}`
