### ISSUE TITLE
Add tests for `modules/spreadsheet-import`

### ISSUE THREAD

**Issue by gitstart-twenty** [twentyhq/twenty#3316]
## Scope & Context

This is a child issue of #2992 which addresses increasing test coverage for the front-end. This issue is for the increasing coverage for `/modules/spreadsheet-import`

**Comment by FelixMalfait** [comment]
We are currently rewriting the spreadsheet import so might be best to put this on hold

**Comment by gitstart-twenty** [comment]
> We are currently rewriting the spreadsheet import so might be best to put this on hold

Okay, @FelixMalfait

**Comment by gitstart-twenty** [comment]
- modules/object-record
- modules/object-metadata

**Comment by gitstart-twenty** [comment]
Hey @FelixMalfait x @charlesBochet,
Which of these are going to undergo changes/refactors in the near-future so we hold back on tests?

- modules/object-record
- modules/object-metadata
- modules/navigation
- modules/keyboard-shortcut-menu
- modules/favorites
- modules/companies
- modules/command-menu
- modules/auth
- modules/apollo
- modules/analytics
- modules/activities

**Comment by charlesBochet** [comment]
Discussed with you! LGTM :)

**Comment by gitstart-twenty** [comment]
> Discussed with you! LGTM :)

Okay

**Comment by FelixMalfait** [comment]
Spreadsheet import has been refactored.

**Comment by charlesBochet** [comment]
@gitstart-twenty could you pick this ticket?

**Comment by gitstart-twenty** [comment]
> @gitstart-twenty could you pick this ticket?

Yes, please

**Comment by charlesBochet** [comment]
Thank you!
