### ISSUE TITLE
I shouldn't be able to remove myself from a workspace

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3330]
We can do a fix on the frontend side only.
User should use the "delete account" button if they want to remove their account, not remove themselves from the workspace.

<img width="700" alt="Screenshot 2024-01-09 at 14 55 11" src="https://github.com/twentyhq/twenty/assets/6399865/e31d34b2-3fa3-4fbb-af32-22ea76efcdd2">

**Comment by ollymac1** [comment]
Looks like the currentWorkspace ID is used instead of the currentWorkspaceMember ID in the conditional logic for the WorkspaceMemberCard accessory. 

PR: https://github.com/twentyhq/twenty/pull/3349
