### ISSUE TITLE
My checkbox selection shouldn't be reset as I load new records

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3331]
As can be seen on the noah@demo.dev account, if I select 50 records, then scroll to load more records, then the initially selected records are automatically unselected. We should leave them as they are when we load new records.

https://github.com/twentyhq/twenty/assets/6399865/94831cf7-6683-4a0c-973c-aae63c1d4ca3

**Comment by lucasbordeau** [comment]
Use this issue to implement an improvement.

We want to display divs of n records, corresponding to pagination pages, to avoid re-rendering the whole table every time we change the records.
