### ISSUE TITLE
Server error If I create a column then immediately add an opportunity to it

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3341]
Steps to reproduce:
- Go to opportunities kanban board
- Click on options, add a stage
- Add an opportunity in the stage you've just created 

```
GraphQL errors on insertIntoopportunity: [{"message":"insert or update on table \"opportunity\" violates foreign key constraint \"FK_e20026fa3f5ec08efdb42e62061\""}]
```

**Comment by charlesBochet** [comment]
Should be fixed by https://github.com/twentyhq/twenty/pull/3391

**Comment by FelixMalfait** [comment]
Yes I can confirm it's fixed, thanks!
