### ISSUE TITLE
FindManyTarget on company Show Page

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3342]
I was checking a company and saw this failed request which fails (no id):

<img width="585" alt="Screenshot 2024-01-09 at 23 13 55" src="https://github.com/twentyhq/twenty/assets/6399865/4f2e3d44-1f4e-4dd3-bef5-f994b439cad1">

It's immediately followed by the following request so the timeline loads properly in the end, this bug isn't really visible to end users:

<img width="776" alt="Screenshot 2024-01-09 at 23 13 29" src="https://github.com/twentyhq/twenty/assets/6399865/f1676c60-e5ef-402f-88a5-61e91e96ea97">

**Comment by FelixMalfait** [comment]
I still have issues creating tasks, not sure what the issue is yet


https://github.com/twentyhq/twenty/assets/6399865/5700a08a-35a3-4da0-b6e4-810a7ce8d424


Note after the video I refreshed the page and the tasks were actually there:

<img width="886" alt="Screenshot 2024-01-12 at 09 45 56" src="https://github.com/twentyhq/twenty/assets/6399865/9434eebe-faad-434b-8674-825aede3887a">

**Comment by charlesBochet** [comment]
Is that old objects? The data might be corrupted, I will try run the health check command on this workspace

**Comment by FelixMalfait** [comment]
@charlesBochet yes I tried recreated a completely new workspace from scratch, I didn't do any action besides creating the workspace before I recorded this video:

https://github.com/twentyhq/twenty/assets/6399865/ef6ccc91-90b5-4dbc-bf36-137eb86d43f0




Also after this video I went to the Tasks tab and the task "Test 3" wasn't there. It only appeared once i clicked on "create new task"
