### ISSUE TITLE
bug: Error while putting a comment on a Task

### ISSUE THREAD

**Issue by AdityaPimpalkar** [twentyhq/twenty#3343]
## Bug Description
https://github.com/twentyhq/twenty/assets/13139771/8f0dbde4-2c05-4f59-bb4a-4e863472b9f9
## Expected behavior

Should see the comment without any errors

**Comment by charlesBochet** [comment]
Should be fixed by https://github.com/twentyhq/twenty/pull/3392

**Comment by charlesBochet** [comment]
This has been solved, closing it
