### ISSUE TITLE
Drag & drop attachements on the files tab

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3345]
## Current Behavior

In the "Files" tab, I have to click the "New file" button to add a file.

![CleanShot 2024-01-10 at 10 25 38](https://github.com/twentyhq/twenty/assets/19412894/555f4730-4b3a-4dd3-a82a-8eff35754d5e)

## Desired Behavior

We would like to enable users to drag and drop files. The design should be a reusable component that can be used in various locations.

When a user drags a file to the window, the list of files or the empty state image disappears and is replaced by this dotted-line area.

Also make sure margin bottom is at 24px to be consistent with side-margins.

![image](https://github.com/twentyhq/twenty/assets/19412894/2beec7e3-1a70-48c5-acec-d449a2c922ae)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19653-53231&mode=design&t=txqcMkvyI6oYlDZr-11

@brendanlaschke, thanks for the idea 🙌 closing #2804

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait 
I can work on this one

**Comment by FelixMalfait** [comment]
Thanks @Kanav-Arora 🙏
