### ISSUE TITLE
I should be able to filter/sort for select fields

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3354]
I added a select field with multiple options as a custom column.
It's displayed in the table but doesn't show up as an option in filter/sort menus
<img width="222" alt="Screenshot 2024-01-10 at 16 11 08" src="https://github.com/twentyhq/twenty/assets/6399865/552fbcd8-b259-44a0-a7c4-c2c1226dbc00">
<img width="553" alt="Screenshot 2024-01-10 at 16 12 10" src="https://github.com/twentyhq/twenty/assets/6399865/01fb8cc7-f269-4f13-bee7-139dffe784a4">

**Comment by ARSHIL1804** [comment]
Hey @FelixMalfait, I would like to take this. Can you assign this to me? Thank you

**Comment by FelixMalfait** [comment]
@ARSHIL1804 thank you!

**Comment by ARSHIL1804** [comment]
@FelixMalfait I am not able to see the Select field dropdown. Is it the issue with setup or something?

**Comment by FelixMalfait** [comment]
@ARSHIL1804 you need to add `IS_SELECT_FIELD_TYPE_ENABLED` for your workspace in core > featureFlags table

**Comment by ARSHIL1804** [comment]
@FelixMalfait is there any figma design for this? Or it will be the same as the Relation field?

**Comment by FelixMalfait** [comment]
@ARSHIL1804 there's a separate ongoing issue to update the component but so far it looks like this -> https://github.com/twentyhq/twenty/issues/3356

**Comment by charlesBochet** [comment]
This has been implemented and shipped in v0.3.2!
