### ISSUE TITLE
Select component should have a scroll and be searchable

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3356]
I created a custom column in the data model with lots of options.

Settings:
<img width="511" alt="Screenshot 2024-01-10 at 16 15 00" src="https://github.com/twentyhq/twenty/assets/6399865/fda48b10-b5d7-410b-b1f4-8e0ff74bdd34">

Here's how it was displayed in the UI — I had to scroll the page to scroll the list, there was no "sub scroll":
<img width="162" alt="Screenshot 2024-01-10 at 16 13 49" src="https://github.com/twentyhq/twenty/assets/6399865/e0a6722b-22ce-4bf0-a85a-66cd2da1f2f8">

Can we create a component similar to the component we use for account owner field or even better adapt it re-use that one? The main difference is that the search here would probably be done on the frontend side only.

A quick fix would be to just set a max-height + make this scrollable, but it would be best if we can add search.

Figma: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=3007%3A69739&mode=dev

<img width="617" alt="Screenshot 2024-01-10 at 16 21 24" src="https://github.com/twentyhq/twenty/assets/6399865/16f6af57-e7d0-4d60-b9b5-9c69db887935">

**Comment by gold-olar** [comment]
Hi @FelixMalfait a first-time contributor here, but can I take this ??

**Comment by FelixMalfait** [comment]
@gold-olar The scroll part would be easy but what's hard is the search.
You would probably need to adapt and migrate to this existing component that does search already: 
https://storybook.twenty.com/?path=/story/ui-input-relationpicker-singleentityselect--default 

So probably not very easy for a first issue. But if you feel confident and still want to give it a shot let us know!

**Comment by gold-olar** [comment]
Yeah, I saw that component, I was thinking I would need to just add the search functionality to the current component (instead of re-working the relationship picker component) since this search is going to be done on the frontend side only.

**Comment by FelixMalfait** [comment]
@gold-olar Yes you're right, probably worth keeping 2 separate high-level components but reusing the same underlying components as much as we can (so that we don't duplicate keyboard behavior code for example). So you can start in this direction!

@charlesBochet can give better guidance than I would

**Comment by charlesBochet** [comment]
@gold-olar 
A few hints about this one: 
- we would like to improve the SelectFieldInput (which should stay different from the RelationFieldInput)
- you can use SelectableList to make it scrollable and navigable with keyboard
- you can use components from ui/layout/dropdown for the UI layer (DropdownMenuSearchInput, DropdownMenuSeparator, DropdownMenuItemsContainer...)

You should find example in the code about how to use these components
Good luck! :)

**Comment by Bonapara** [comment]
A little design hint:

The following picker should be used for `Select`. The label size should be 20px and not 16px. 

![image](https://github.com/twentyhq/twenty/assets/19412894/5924e4b1-5703-4a83-ac13-bd8d9fbd7654)

As a reminder the tag background color is the one set here:

![CleanShot 2024-01-24 at 16 55 28](https://github.com/twentyhq/twenty/assets/19412894/f95bb751-54ba-4c63-b8fd-041ae800b6fd)

**Comment by FelixMalfait** [comment]
Hey @gold-olar have you made any progress on this yet? Would be amazing to have it in the next release! Thanks a lot

**Comment by ARSHIL1804** [comment]
@FelixMalfait I am working on #3354 and all requirements will be covered in that as I have added the Search and Listing filter. Since I have made lot of progress in that it would be easy if I resolve this along with that issue.

**Comment by FelixMalfait** [comment]
@ARSHIL1804 oh cool

**Comment by ARSHIL1804** [comment]
> A little design hint:
> 
> The following picker should be used for `Select`. The label size should be 20px and not 16px.
> 
> ![image](https://private-user-images.githubusercontent.com/19412894/299374050-5924e4b1-5703-4a83-ac13-bd8d9fbd7654.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTY4NTAsIm5iZiI6MTcwNjE5NjU1MCwicGF0aCI6Ii8xOTQxMjg5NC8yOTkzNzQwNTAtNTkyNGU0YjEtNTcwMy00YTgzLWFjMTMtYmQ4ZDlmYmQ3NjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1MjkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZGE4NjNhODM0OGU2MTQ5ZmNlMzZkZGMyMzJlYzNkZTMzZTQxZTc4ZjI3NzZhOWViMTQ3YmQyN2Y4ZGQ0ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LBF4w2n4cOjRCrdIUqtmc7YXdDMIEp-4SavhRWfYCJI)
> 
> As a reminder the tag background color is the one set here:
> 
> ![CleanShot 2024-01-24 at 16 55 28](https://private-user-images.githubusercontent.com/19412894/299374919-f95bb751-54ba-4c63-b8fd-041ae800b6fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTY4NTAsIm5iZiI6MTcwNjE5NjU1MCwicGF0aCI6Ii8xOTQxMjg5NC8yOTkzNzQ5MTktZjk1YmI3NTEtNTRiYS00YzYzLWI4ZmQtMDQxYWU4MDBiNmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1MjkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2N2U2ODY2ODQwNzQyZWNhNjUwOWYwMWMwMWZiOGI4ZGU1Nzk5NWIxNjIxNzg3N2ZjNzRjM2NlNTI5NDNkYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3nHjmob1xwRkpWa-qOIFImWEGRNELNkgzjK2w9BUJE8)

@Bonapara for the options we need to create this select with label background?. Or we can make change in exsisting MenuItemSelect?

**Comment by FelixMalfait** [comment]
@ARSHIL1804 Charles gave some direction above. MenuItemSelect is something different that is not related I think

> we would like to improve the SelectFieldInput (which should stay different from the RelationFieldInput)
you can use SelectableList to make it scrollable and navigable with keyboard
you can use components from ui/layout/dropdown for the UI layer (DropdownMenuSearchInput, DropdownMenuSeparator, DropdownMenuItemsContainer...)
