### ISSUE TITLE
Introduce duplicate query for objects

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3362]
On a record's detail page, we would like to display to user if there are any record that appears to be a duplicate.

 
## Backend

For v1 we could start with those 3 rules:
```
const duplicateCriterias = 
[
    {
        "object": "company",
        "fields": ["domain"]
    },
    {
        "type": "person",
        "fields":  ["firstName", "lastName"], 
    },
    {
        "type": "person",
        "duplicateCriteria":  ["email"], 
    }
];
```
In the future this will be configurable for any type of object as the config will be pulled from DB and configured individually for each workspace.  Also we will likely add other columns such as `actionOnCreate : disallow/alert`, `actionOnEdit: alert/no_regression` or `alertText: string`.

And the API you will need to create to retrieve duplicates on the frontend for a given record should look like something like this:

<img width="369" alt="Screenshot 2024-02-08 at 17 05 47" src="https://github.com/twentyhq/twenty/assets/6399865/1dcd2cd4-5acb-49b0-8488-ea3cede24f64">

Note there are two parameters: `data` and `id`, they can be null but both can't be null at the same time.

If data is given then we compute the duplicate criteria based on the data (e.g. we can pass {"domain": "airbnb.com", "name":"Airbnb"}.
If ID is given, then we pull the data  for that given record from DB.
In both cases, we will then find if there's any duplicate by applying the `duplicateCriterias` and return the list of duplicates. We just return an empty array if there isn't any, no need for a specific config. 

This should result in the creation of as many queries as there are non-technical objects: `companyDuplicates, personDuplicates, opportunityDuplicates, customObject1Duplicate, customObject2Duplicates`. Every object that is visible in /settings/object page should have its dedicated query. Technical objects such as "View" or "ViewFilter" should not have a query.

**Before jumping into this issue, please note that our backend is very complex and different from traditional infrastructure because of the specific requirements of a CRM** (custom objects/fields). We've got one schema per workspace in Postgres, each workspace can define the metadata for their business and our engine automatically generates the sql migration / the GraphQL queries based on that. So if you're new to this project it would probably take a few hours for you to understand this.

Test coverage is poor for backend but please write at least a few basic tests for this.

## Frontend

If there is no duplicate, we shouldn't display anything.

If there is a duplicate, we should show it in a similar fashion to how relationships are currently displayed:
<img width="381" alt="Screenshot 2024-02-08 at 16 59 23" src="https://github.com/twentyhq/twenty/assets/6399865/f82c471b-8c67-41c3-947a-5cbc740af77c">

**Comment by rostaklein** [comment]
I would like to take this one. Looks challenging enough 🚀

Im trying to make myself familiar with the data/generated schema infrastructure on backend side of this project. I started in this draft https://github.com/twentyhq/twenty/pull/4038 will appreciate a brief look from someone who can tell me whether im going in a right direction or not. 😊
