### ISSUE TITLE
`make docker-dev-down` removes the volumes along with containers

### ISSUE THREAD

**Issue by i-am-chitti** [twentyhq/twenty#3364]
## Bug Description

On executing `make docker-dev-down`, the volumes are removed and container is destroyed. It removes the mounted `twenty_db_data` as well as all other containers. Due to this, one has to install all dependencies, initialize the database everytime they need to start the project.

This is quite cumbersome in case of development.

## Expected behavior

On turning containers down, the volume should be persistent and hence should not be removed.

## Technical inputs

I suspect that containers are removed with destroying the volumes.

**Comment by i-am-chitti** [comment]
JFYI, on removing the `-v` flag here - https://github.com/twentyhq/twenty/blob/main/packages/twenty-docker/Makefile#L16 - I'm able to skip the packages installation(skip doing yarn) but still, the database is not persisted. It's lost if containers are turned down. So, I still need to initialize the DB.
I seems that `twenty_db_data` volume is removed. Not a PRO in docker. It's just a guess. Tried it making `external: true`, but no luck.

**Comment by Sinister-00** [comment]
Hi @i-am-chitti ,

I've created a pull request (https://github.com/twentyhq/twenty/pull/3376) that addresses the Docker volume persistence problem you mentioned. The changes include updating the `docker-compose.yaml` file to ensure the `twenty_db_data` volume persists even when containers are turned down. Additionally, the `Makefile` now includes the creation of the volume before running `docker compose -f dev/docker-compose.yml up -d`.

Could you please test the changes from the PR and check if you're still facing the issue?

**Comment by i-am-chitti** [comment]
Hey @Sinister-00, 
I tested with your changes and volumes are still getting destroyed. This time, I need to execute the `yarn` also. Attaching an output of terminal of tearing down and getting up again after successful initialization of DB -

<img width="838" alt="image" src="https://github.com/twentyhq/twenty/assets/60139930/8143e38b-c43d-40c2-a26b-3f92fdccd2db">

**Comment by Sinister-00** [comment]
@i-am-chitti 

After the `make docker-dev-down` try with this command to check if the {`twenty_db_data`} volume is deleted or not:

```bash
docker volume inspect twenty_db_data
```

**Comment by charlesBochet** [comment]
Referencing #3376
