### ISSUE TITLE
New Contributors Page for Twenty Website

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3365]
# Scope

We aim to highlight our contributors on the Twenty website. We'll develop a webpage featuring each contributor's picture and a dedicated page showcasing their work, including latest pull requests, activity, and other key information.

# Desired behavior

## Index

![CleanShot 2024-01-11 at 09 53 42](https://github.com/twentyhq/twenty/assets/19412894/7850a04d-30e8-47dd-8671-39107a7d1cdc)

Ensure to add a box shadow on image hover: (and use cursor:pointer;)

https://github.com/twentyhq/twenty/assets/19412894/e8bd70d9-b71c-4530-95f4-4526be79798c

Implement Desktop and Mobile modes. Adjust font size and padding for Mobile mode:

![CleanShot 2024-01-11 at 10 00 08](https://github.com/twentyhq/twenty/assets/19412894/cdcdc9ce-1335-4b9d-90ee-d3f776004266)

https://www.figma.com/file/aNpCjwN9wg2DqLWAHPS0ll/%F0%9F%8C%8D-Website?type=design&node-id=1-4175&mode=design&t=DOFln1l9kC95T2pW-11

## Show page

![CleanShot 2024-01-11 at 10 01 18](https://github.com/twentyhq/twenty/assets/19412894/627d482f-0ff4-445e-a9ee-e093125f3bd7)

Implement both desktop and mobile versions of the show page. Link the Github icon to the contributor's profile. Calculate rank based on merged PR count. Replicate the activity graph function from Github.

## Navbar

![CleanShot 2024-01-11 at 10 07 07](https://github.com/twentyhq/twenty/assets/19412894/9ef2cabf-896f-4696-8ba9-60568a8b6116)

Create a navbar component for both desktop and mobile, mirroring Twenty.com's Framer-developed version. Ensure a transition exists between open and closed states on mobile:

https://github.com/twentyhq/twenty/assets/19412894/8973441c-1d0a-463b-8ff5-1da201dd1c0e

## Background Pattern 

Pattern:

(Compressed to maintain file quality)

[Patterns.zip](https://github.com/twentyhq/twenty/files/13901108/Patterns.zip)

![Website pattern](https://github.com/twentyhq/twenty/assets/19412894/70a7d6f6-7ce4-435a-b485-031dc0d273d9)

Here is the code used on Framer to implement the background pattern:

The typical parameters were:
Rotation: -16°
Gradient Rotation: 185°

``` React
import * as React from "react"
import { addPropertyControls, ControlType } from "framer"

type Props = {
    image: string
    rotation: number
    gradientRotation: number
}

export function patternBackground(props: Props) {
    // Generate the CSS for the background image
    const backgroundImageStyle = {
        position: "absolute",
        top: "-50%",
        left: "-50%",
        width: "200%", // Increased to cover the area when rotated
        height: "200%", // Increased to cover the area when rotated
        backgroundImage: `url(${props.image})`,
        backgroundSize: "auto 20px", // Adjust for maintaining aspect ratio
        backgroundRepeat: "repeat",
        transform: `rotate(${props.rotation}deg)`,
        transformOrigin: "center center",
    }

    // Generate the CSS for the gradient overlay
    const gradientOverlayStyle = {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: `linear-gradient(${props.gradientRotation}deg, #FFF 8.33%, rgba(255, 255, 255, 0.08) 48.95%, #FFF 92.18%)`,
        zIndex: 1, // On top of the background image
    }

    // Generate the CSS for the container
    const containerStyle = {
        height: "100%",
        width: "100%",
        position: "relative",
        overflow: "hidden",
    }

    // Return a div with the container, background image, and gradient overlay
    return (
        <div style={containerStyle}>
            <div style={backgroundImageStyle} />
            <div style={gradientOverlayStyle} />
        </div>
    )
}
})
```

# Technical input

Some work has already be done on the subject. Check:

`https://github.com/twentyhq/twenty/tree/main/packages/twenty-website/src/app/developers/contributors`

And the API:

`packages/twenty-website/src/app/developers/contributors/api/generate/route.tsx`

# Figma

https://www.figma.com/file/aNpCjwN9wg2DqLWAHPS0ll/%F0%9F%8C%8D-Website?type=design&node-id=5-4946&mode=design&t=DOFln1l9kC95T2pW-11

@Kanav-Arora I hope you don't mind that I used your username as an example ;)

**Comment by Kanav-Arora** [comment]
@Bonapara ofcourse not

**Comment by FelixMalfait** [comment]
Note part of the work for this has already been done (pages already exist) so this is mostly about frontend / UI.
The way it works is you have to hit the /generate endpoint first to fill the SQLite database with Github data.

**Comment by Kanav-Arora** [comment]
@Bonapara @FelixMalfait 
There can be a section which fetches the latest 3 PRs, which can be done by Github API and clicking on it will take you to that PR. This will also help move traffic to Twenty's Github Repo

**Comment by FelixMalfait** [comment]
@Kanav-Arora the backend logic is mostly there already. We do a full copy of Github's data to a SQLite database in Next.js. We display every PR that has been done by that user on each user profile.
For the homepage we only display the list of contributors for now but later we'll improve and surface good first issues, organize challenges with rewards, etc
We also plan to use Danger.js to reply to contributions and show user we've created a profile for them / recognize when they reach new steps.

**Comment by i-am-chitti** [comment]
@FelixMalfait, @Bonapara Can I work on this? Since backend is ready, I'm up for developing the frontend.

**Comment by Kanav-Arora** [comment]
Hi @i-am-chitti 
Since this issue has a lot of work if you need any help we can divide some parts of it

**Comment by FelixMalfait** [comment]
Thanks Deepak! I assigned you / feel free to collaborate with Kanav of course

**Comment by FelixMalfait** [comment]
For the backend you need to hit the /generate endpoint first to fill the SQLite DB with Github data

**Comment by i-am-chitti** [comment]
@Kanav-Arora, thanks for offering the help. At the moment, I've decided to tackle this task independently. However, I'll definitely reach out if I find myself needing assistance in the future. Thanks again for your support!

**Comment by i-am-chitti** [comment]
@FelixMalfait, please confirm and clarify some doubts - 
- the new pages should be at `/developers/contributors` and `/developers/contributors/{id}`. The `id` would be coming from DB or should I use the `login` column.
<img width="869" alt="image" src="https://github.com/twentyhq/twenty/assets/60139930/fa04624f-f21e-4a26-8fae-225786b9c4d7">

- for selecting data, I'll be directly SQL in any component like how it's currently done here- https://github.com/twentyhq/twenty/blob/main/packages/twenty-website/src/app/developers/contributors/page.tsx#L12-L32
- I can see a Nav bar already present on this page. Though not able to find the code, probably getting from Framer via Cloudflare. So, how do I remove this in order to develop custom Nav bar as suggested above?
<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/60139930/22fd51ce-d885-45dd-93ca-7a6cac651c8f">

- How a visitor should reach out to the contributors page? I'm not able to see any link in design either in nav bar or in footer which can direct user to this page. Maybe we can have "Contributors" in nav bar as another link.

**Comment by i-am-chitti** [comment]
@FelixMalfait, could you please have a look at this comment - https://github.com/twentyhq/twenty/issues/3365#issuecomment-1900865919 . Will need confirmation for a GO AHEAD!

**Comment by FelixMalfait** [comment]
Oh sorry I had missed your comment @i-am-chitti 

> the new pages should be at /developers/contributors and /developers/contributors/{id}. The id would be coming from DB or should I use the login column.

yes

> for selecting data, I'll be directly using SQL in any component like how it's currently done here- https://github.com/twentyhq/twenty/blob/main/packages/twenty-website/src/app/developers/contributors/page.tsx#L12-L32

yes it's not the cleanest but I wanted to start with something quick and simple. Just make sure you use prepared statements where variables are substituted by the package and not do concatenation yourself to avoid SQL injection.

> I can see a Nav bar already present on this page. Though not able to find the code, probably getting from Framer via Cloudflare. So, how do I remove this in order to develop custom Nav bar as suggested above?

The navbar and footer are actually in `twenty-website`. I looked at the recommended way of sharing components between Framer and a React app and they basically said "don't bother just recreate an identical version and maintain both separately". We'll have a reverse proxy in front that will point to the right server based on the URL.
Let's keep the sidebar as it is now for v1 (maybe just move Docs to the right position and make it link to docs.twenty.com). We can start shipping it this way and evolve it soon after in a followup ticket.

> How a visitor should reach out to the contributors page? I'm not able to see any link in design either in nav bar or in footer which can direct user to this page. Maybe we can have "Contributors" in nav bar as another link.

The idea is to have a developer hub where we'd group docs + contributors + blog with technical articles. 
As a v1 we'd just have the contributors page. We can probably add it as a Resource link here first and then we'll make it more visible once we have the full hub:
<img width="638" alt="Screenshot 2024-01-24 at 11 27 25" src="https://github.com/twentyhq/twenty/assets/6399865/6ed6cf3e-65b1-4855-b817-94f5c9ebdbc1">

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait @Bonapara 
In the merged PR card onclick we can redirect it to below url with change in author parameter
https://github.com/twentyhq/twenty/commits?author=Kanav-Arora

**Comment by FelixMalfait** [comment]
@i-am-chitti yes good catch, we want the same gradient! 

@Kanav-Arora Not sure what you mean? Each PR item in the list should redirect to its respective PR on Github. But maybe I didn't understand what you said

**Comment by i-am-chitti** [comment]
@FelixMalfait ,
How should I compute rank and active days here on single contributor page - 
<img width="986" alt="image" src="https://github.com/twentyhq/twenty/assets/60139930/38c1af03-b4e9-448d-982c-1704050cff87">

Can't see any DB field dedicated to them on any table.

Also, merged PR count here is same as the number of pull request rows whose `mergedAt` is not NULL. That's is, it would be computed by getting list of pull requests and filtering if `mergedAt` is present.
<img width="1415" alt="image" src="https://github.com/twentyhq/twenty/assets/60139930/3369f4e2-c9d8-4466-b5fa-db5d011562be">

**Comment by FelixMalfait** [comment]
@i-am-chitti I was thinking we could compute the rank on the fly. I'm not sure if it needs to be cached in a column, as long as we don't have hundreds of contributors and not thousands performance should probably be okay!

Just asked ChatGPT to provide a request, it looks okay to me but I did not test it!
```
SELECT 
  merged_pr_counts.*,
  (RANK() OVER(ORDER BY merged_count DESC) - 1) / total_authors::float * 100 as rank_percentage
FROM
  (
   SELECT 
     authorId,
     COUNT(*) FILTER (WHERE mergedAt IS NOT NULL) as merged_count
   FROM 
     pullRequests
   GROUP BY 
     authorId
  ) AS merged_pr_counts
CROSS JOIN 
  (
   SELECT COUNT(DISTINCT authorId) as total_authors
   FROM pullRequests
  ) AS author_counts
WHERE 
  authorId = (SELECT id FROM users WHERE login = :user_id);
  ```
  
  >Also, merged PR count here is same as the number of pull request rows whose mergedAt is not NULL. That's is, it would be computed by getting list of pull requests and filtering if mergedAt is present.

Yes

Thanks!

**Comment by i-am-chitti** [comment]
@FelixMalfait , for some reason, the above query is giving error -
<img width="684" alt="image" src="https://github.com/twentyhq/twenty/assets/60139930/007dfcad-ee4a-45bc-b43a-64a37454d33e">

After casting proper types of `total_authors` to float using `CAST`, the results are always 0 -
```
SELECT 
  merged_pr_counts.*,
  (RANK() OVER(ORDER BY merged_count DESC) - 1) / CAST( total_authors as float) * 100 as rank_percentage
FROM
  (
   SELECT 
     authorId,
     COUNT(*) FILTER (WHERE mergedAt IS NOT NULL) as merged_count
   FROM 
     pullRequests
   GROUP BY 
     authorId
  ) AS merged_pr_counts
CROSS JOIN 
  (
   SELECT COUNT(DISTINCT authorId) as total_authors
   FROM pullRequests
  ) AS author_counts
WHERE 
  authorId = (SELECT id FROM users WHERE login = :user_id)
```

<img width="543" alt="image" src="https://github.com/twentyhq/twenty/assets/60139930/1c578602-82d6-4ba6-9b5c-49d14dc5f307">

I'm not able to grasp the logic for computing the rank. Could you tell the logic? I'll write down the SQL query as above AI's query is wrong, 🤔 .

**Comment by i-am-chitti** [comment]
Also, let me know the `Active Days` logic too.

<img width="440" alt="image" src="https://github.com/twentyhq/twenty/assets/60139930/3a4403a2-7a2a-428b-bb3c-2e31d87163b6">

**Comment by FelixMalfait** [comment]
@i-am-chitti 
The first part of the query creates a table with the PR count for each author.
The second part just adds the total number of authors.
I think the issue is with the final WHERE clause, also we probably don't need the (-1). If you remove them it gives this:

<img width="849" alt="Screenshot 2024-01-29 at 21 54 46" src="https://github.com/twentyhq/twenty/assets/6399865/0fef5312-d22f-4e70-b34a-aa8a4a876c23">

So you need to wrap that within another SQL query to apply the WHERE, e.g.
<img width="852" alt="Screenshot 2024-01-29 at 21 56 34" src="https://github.com/twentyhq/twenty/assets/6399865/2b2ea8d2-4661-4473-a593-d60d7d28bad6">

Active Days logic should reflect the number of colored dots in the Activity section.
So everyday you authored an issue or a PR.

Also I think we want to entirely filter out core team members from everything (also when computing ranking), we'd filter this out with isEmployee=false

**Comment by i-am-chitti** [comment]
Hey @FelixMalfait, The PR - https://github.com/twentyhq/twenty/pull/3745 is ready for review four days ago. I missed informing here.

**Comment by Kanav-Arora** [comment]
@FelixMalfait @i-am-chitti 
Instead of Rank you can use Top as rank can't be a decimal number
