### ISSUE TITLE
Favorites should be user-level not workspace-level

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3374]
We should add a `workspaceMemberId` table on favorites and make favorites user-level.
If I add a record as favorite, it shouldn't be listed as a favorite for other workspace members.

**Comment by abhisheksharma010** [comment]
Hello, can you assign this issue to me? I can easily resolve this.

**Comment by FelixMalfait** [comment]
Thanks @abhisheksharma010! The backend is not well documented yet so it might not be that easy, let us know
