### ISSUE TITLE
Add a throbber after the first step of sign-up

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3375]
# Current Behavior

After clicking the sign-up button, the loading time is notably long without any progress indication:

https://github.com/twentyhq/twenty/assets/19412894/17f3c650-c7fc-460f-8939-7086e7fd6232

# Desired Behavior

Add a throbber to indicate loading. Make sure to animate both the loader and the transition between the button states:

https://github.com/twentyhq/twenty/assets/19412894/d414799e-b0a8-443f-b44e-b019246f470e

# Figma

### Prototype

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19818-110033&mode=design&t=pE5HVoWI8nv3HPyu-11

### BTN Component

![Screenshot 2024-01-11 at 14 40 02](https://github.com/twentyhq/twenty/assets/19412894/a9c34d9c-b333-44ad-bbe9-7fb9e70d69b2)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=3122-142114&mode=design&t=pE5HVoWI8nv3HPyu-11

### Loader

![Screenshot 2024-01-11 at 14 40 22](https://github.com/twentyhq/twenty/assets/19412894/e9818ed5-a9fe-479e-9a3c-8a4b04f05443)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=3122-142114&mode=design&t=pE5HVoWI8nv3HPyu-11

**Comment by FelixMalfait** [comment]
Great! Small detail but what do you think about changing the text from "Sign up" to "Creating workspace" ? Not more complex from a dev perspective and I feel like it reinforces the reassuring factor (With signup you feel like the request is being sent but you're not sure it's been received)

**Comment by iampaandey** [comment]
Please assign this to me i have worked on same issues earlier.

**Comment by Bonapara** [comment]
Done, Thanks @iampaandey!

**Comment by FelixMalfait** [comment]
@iampaandey have you made any progress on this yet? Thanks!
