### ISSUE TITLE
Use "ilike" for activities search instead of "like"

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3385]
I just realized search in command bar was case-sensitive for Notes but not for companies and people:

<img width="450" alt="Screenshot 2024-01-11 at 18 23 31" src="https://github.com/twentyhq/twenty/assets/6399865/f9727e9f-a13c-43f6-add8-a4d10346e84b">
<img width="496" alt="Screenshot 2024-01-11 at 18 23 25" src="https://github.com/twentyhq/twenty/assets/6399865/a1baf58e-2fc1-4ef7-9c5c-040a7e2835c6">

This is because we use ILIKE for companies and LIKE for activities.
We should use ILIKE for everything.

Two likes to change in the same file:
https://github.com/twentyhq/twenty/blob/4b97625f374341ac5ead4308c846d0ad43197ccd/packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx#L160
https://github.com/twentyhq/twenty/blob/4b97625f374341ac5ead4308c846d0ad43197ccd/packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx#L161

**Comment by neerajkumarc** [comment]
Hi @FelixMalfait 
Can I work on this?

**Comment by FelixMalfait** [comment]
@neerajkumarc of course, thanks!
