### ISSUE TITLE
Improve search for multi-words input

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3386]
As of today, search works if I type the first name or last name only but behaves badly as soon as we add spaces (e.g. first name + last name doesn't work).

A less naive approach would be to explode the string before and use OR for each word.

<img width="477" alt="Screenshot 2024-01-11 at 18 26 58" src="https://github.com/twentyhq/twenty/assets/6399865/b7ae37e6-12c8-4506-97bc-9864ba2a5a82">

<img width="410" alt="Screenshot 2024-01-11 at 18 31 40" src="https://github.com/twentyhq/twenty/assets/6399865/047ff516-ba71-4d0f-a856-01548d41024f">

This logic is used in at least three different places. We should probably abstract it.

https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx#L139

https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/object-record/relation-picker/hooks/useSearchFilterPerMetadataItem.ts

https://github.com/twentyhq/twenty/blob/2e571976fb4518b2ef75c91804cbc3aa4067f2c1/packages/twenty-front/src/modules/object-record/record-filter/utils/turnObjectDropdownFilterIntoQueryFilter.ts

**Comment by charlesBochet** [comment]
Candidate for @thomtrp

**Comment by FelixMalfait** [comment]
I realized we should probably do this before: #3424

**Comment by FelixMalfait** [comment]
From @Bonapara's issue:


# Current Behavior

When associating a contact with a relation (like a company or opportunity), the system doesn't permit full-name search. This necessitates either the first or last name being deleted for search.

https://github.com/twentyhq/twenty/assets/19412894/131c2078-7efc-4520-916c-6420a0af90aa

# Desired Behavior

Enable full name search functionality when adding a contact to a relation.
