### ISSUE TITLE
Self-Service Onboarding Implementation

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3387]
### Current Behavior

You cannot create an account without getting in touch with the core team.

### Desired Behavior:

# 1. The pricing page should redirect to the app sign_in / sign_up

_Framer will handle this._

# 2. Sign in / Sign up blocking

We want to substitute the actual "Plan Required" popup with a more detailed one. When the user clicks "Subscribe", we should transmit his workspace ID to Stripe.

![image](https://github.com/twentyhq/twenty/assets/19412894/c15859dc-9095-4d21-abd4-a56de34fd2d8)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19861-67256&mode=design&t=pE5HVoWI8nv3HPyu-11

# 3. Bill the correct number of seats

We want to retrieve the number of workspace members and adjust the Stripe pricing accordingly.

https://stripe.com/docs/billing/subscriptions/quantities

# 4. Payment on Stripe

The user should use the Stripe checkout page to buy his licenses

# 5. After payment, the user should be redirected to Twenty

We can now redirect the user to app.twenty.com and activate his workspace. He should already be signed in.

https://stripe.com/docs/payments/checkout/custom-success-page

# 6. New Billing page in Settings

We want to add a page that allows a user to edit his Billing details

![image](https://github.com/twentyhq/twenty/assets/19412894/d8bbb608-9215-4ca2-9549-c21b838749be)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19770-109130&mode=design&t=pE5HVoWI8nv3HPyu-11

### Billing details

Clicking "View billing details" should display the Stripe. Use https://stripe.com/docs/billing to achieve this:

![CleanShot 2024-01-11 at 18 36 02](https://github.com/twentyhq/twenty/assets/19412894/28b73f10-30dc-4f8c-a17e-405d6d851666)

### Switch Plan

Clicking "Switch to Yearly" triggers a popup. Ensure the "Switch to Monthly" option is displayed when the yearly plan is chosen.

![image](https://github.com/twentyhq/twenty/assets/19412894/03613a39-457c-47f7-a83a-d438fa603470)

### Cancel Plan

The Workspace Plan should be canceled. The blocking popup in the sign-in/sign-up process should be displayed again.

**Comment by charlesBochet** [comment]
Shipped with v0.3.3, closing this ticket!
