### ISSUE TITLE
Database call of custom object should be in a transaction

### ISSUE THREAD

**Issue by magrinj** [twentyhq/twenty#3397]
## Scope & Context

Move all database command when we create a new custom object into a transaction, to avoid errors and synchronisation problem. 

## Current behavior

Database calls are not in a transaction.

## Expected behavior
 
All calls should be in a transaction to add ability to rollback if an error occurred.

## Technical inputs

[https://orkhan.gitbook.io/typeorm/docs/transactions](https://orkhan.gitbook.io/typeorm/docs/transactions)

**Comment by FelixMalfait** [comment]
Is this still relevant?
