### ISSUE TITLE
Index cells hover is no longer working

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3402]
# Description

There are no more hover effects on index cells:

https://github.com/twentyhq/twenty/assets/19412894/dd119e65-0e80-435b-a5f5-d83bd6d6510b

# Desired behavior

Add back the hover effects on cells:

https://github.com/twentyhq/twenty/assets/19412894/06ce6c67-579c-4482-aa15-ed7eebf33ac9

**Comment by iampaandey** [comment]
Please assign this to me i have worked on same issues earlier.

**Comment by Bonapara** [comment]
Hi @iampaandey, I have assigned you another task. Would you prefer this one instead? Thank you for your contribution!

**Comment by charlesBochet** [comment]
@iampaandey @Bonapara This has already been fixed in the following PR: #3404
