### ISSUE TITLE
Object relation variant in case of 1:N or 1:1

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3409]
# Desired Behavior

When the relationship displayed on the show is either `One to One` or `Many to One` (The record has only one parent but some "siblings."), we should adapt the display as follows:
1. Display the related object name in singular form.
2. Hide the "Display All" option.
3. When hovering, show a pen icon instead of a "+" symbol.

![CleanShot 2024-01-12 at 16 26 08](https://github.com/twentyhq/twenty/assets/19412894/873724e1-fd57-43b8-949a-7d9885b7d55f)

**Comment by thaisguigon** [comment]
Hi @Bonapara,
For 1), I think it should be the field name instead of the related object's singular name.
For instance, if Company has a "CEO" field which is a Person, we should see "CEO", not "Person". Which is already implemented.

**Comment by Bonapara** [comment]
Yes @thaisguigon, well noticed
