### ISSUE TITLE
Refine Settings Layout

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3411]
# Current Behavior

1. The page layouts have different widths. For example, `/settings/profile` is much narrower (350px) than `/settings/objects` (512px)

| 350px | 512px |
|---|---|
| ![CleanShot 2024-01-12 at 17 08 04](https://github.com/twentyhq/twenty/assets/19412894/6e8125cc-8bbb-4ddf-8180-7912354bd9b4) | ![CleanShot 2024-01-12 at 17 08 54](https://github.com/twentyhq/twenty/assets/19412894/d591849a-12f6-425b-872e-d9fc7f0f672c) |

2. The content is not horizontally centered on the page:

![CleanShot 2024-01-12 at 16 58 04](https://github.com/twentyhq/twenty/assets/19412894/2e76f487-f183-4b01-954a-bc5e62fff4ca)

# Desired Behavior

1. All the settings' content width should be 512px. Designs have been updated:

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=13273-96299&mode=design&t=cT75gYTM64rGg00A-11

![CleanShot 2024-01-12 at 17 08 54](https://github.com/twentyhq/twenty/assets/19412894/180472e4-4e5e-4b1b-baf3-73f2365ca540)

2. The content should be centered in the middle of the screen:

![CleanShot 2024-01-12 at 17 00 41](https://github.com/twentyhq/twenty/assets/19412894/dae8651f-2e15-4e75-8675-5c746c840642)

**Comment by vimal20002** [comment]
Please assign this to me i have worked on same issues earlier.

**Comment by Bonapara** [comment]
Hi @vimal20002, I've assigned you to another issue. Would you prefer this one instead?
Thanks for contributing!

**Comment by charlesBochet** [comment]
@abdul-irfan-k has opened a PR about this!

**Comment by Bonapara** [comment]
More details on the responsive on #3479 (Related)

![image](https://github.com/twentyhq/twenty/assets/19412894/c401f177-7d26-4a12-aa80-e55c78ef2c96)

**Comment by abdul-irfan-k** [comment]
Ok I am trying to fix it

**Comment by abdul-irfan-k** [comment]
@Bonapara  Please review #3429
