### ISSUE TITLE
Multiple useListenClickOutside can conflict

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3416]
## Bug Description

When activity drawer is open, and we are on a activity target multi select picker, it correctly saves the new selection if we click outside but inside the activity drawer, but if we click outside the activity drawer, it will close and not close nor save the activity target picker.

## Expected behavior

Following up https://github.com/twentyhq/twenty/issues/3412, we want to use listenerId to prevent conflicts by disabling certain id manually.

A good use case to test would be to deactivate drawer listen click outside if activity target picker is open.

**Comment by charlesBochet** [comment]
Candidate for @thomtrp
