### ISSUE TITLE
When creating a task, the task list re-renders multiple times

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3418]
## Bug Description

https://github.com/twentyhq/twenty/assets/26528466/a1e62feb-077b-4e15-8bba-2f58336f881d

The task list re-renders multiple times, and even becomes empty to re-render with the new correct state.

## Expected behavior

We don't want any re-render of the list.

**Comment by PepeGonzale** [comment]
Can I work on this issue?

**Comment by lucasbordeau** [comment]
@PepeGonzale Sorry it's part of our current core team issues.
