### ISSUE TITLE
Split useTask hook

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3419]
## Scope & Context

The useTask hook is used by two different zones in the app. They don't have the same goal and starting state, so it would make more sense to split this hook.

- Create a useUserTasks that will be used to display tasks (not all activities) on task page
- Create a useActivityByObject that will be used to display all activity types related to an object on the show page.

**Comment by charlesBochet** [comment]
We have decided to not do it in the end. Closing this ticket
