### ISSUE TITLE
Improve Floating Button Icon style

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3420]
# Current Behavior

Today, the contrast of the floating button icon in dark mode is poor:

![image](https://github.com/twentyhq/twenty/assets/19412894/e162d2b6-06f8-44c1-8f50-6bef659f18b2)

# Desired behavior

Add a border around the floating button icon (in both light and dark modes):

![CleanShot 2024-01-12 at 17 44 15](https://github.com/twentyhq/twenty/assets/19412894/86e3b44e-b623-432b-b4d8-ba8ed841165f)

![CleanShot 2024-01-12 at 17 45 00](https://github.com/twentyhq/twenty/assets/19412894/f7398698-5f5b-48dc-af91-e45f3d1db797)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=3122-142114&mode=design&t=cT75gYTM64rGg00A-11

### Point of caution

On Figma, the border is set to "Transparent Light". When changing to the "Hover State", it flashes because it needs to be re-rendered. Please ensure that this doesn't occur in the browser. If it does, please notify me!

https://github.com/twentyhq/twenty/assets/19412894/9e778159-680b-4e2f-ba89-0e9af2f84c18

**Comment by GARY121github** [comment]
Can I work on this issue?

**Comment by FelixMalfait** [comment]
@GARY121github sure thanks! Assigning you

**Comment by GARY121github** [comment]
@FelixMalfait I have created the PR for the issue please merge it.
