### ISSUE TITLE
Refactor CommandMenu to use FindManyRecordsMultipleMetadataItems

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3424]
We introduced the `FindManyRecordsMultipleMetadataItems` query for the relation picker search (e.g. attaching an activity to objects).

We should refactor the command menu to use this endpoint.
That way we will do 1 query instead of N and can delegate for of the search logic to the backend since this is a specialized endpoint.

**Comment by lucasbordeau** [comment]
We'll be addressed in https://github.com/twentyhq/twenty/issues/3298
