### ISSUE TITLE
Connect Settings/Accounts/Emails to the backend

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#3434]
## Scope & Context

Currently, we display mock data in Settings/Accounts/Emails:

<img width="893" alt="Capture d’écran 2024-01-15 à 11 02 27" src="https://github.com/twentyhq/twenty/assets/71827178/5cc51440-6ad9-4d2d-af18-4683e82b3e52">

We need to connect this page to the backend.

## Technical inputs

- Get connected accounts
```
const currentWorkspaceMember = useRecoilValue(currentWorkspaceMemberState);

  const accounts = useFindManyRecords<Account>({
    objectNameSingular: 'connectedAccount',
    filter: {
      accountOwnerId: {
        eq: currentWorkspaceMember?.id,
      },
    },
  }).records;
```
- Display them in the UI

**Comment by lakshay-saini-au8** [comment]
@bosiraphael I can work on this as I worked on the UI development of this page too
