### ISSUE TITLE
Add user to sentry when an error is thrown

### ISSUE THREAD

**Issue by magrinj** [twentyhq/twenty#3468]
When an error is thrown and caught by the exception handler, we should include the user it will help for debugging.

**Comment by FelixMalfait** [comment]
Cool! Does that also solve performance tracing (and eventually profiling which seems to be enabled too) ? I see it's supposed to be enabled in the code but not working in the Sentry console. I think this would be nice to prioritize it this week (we have performance on the frontend but I feel it's harder to interpret than if we had the backend side)
