### ISSUE TITLE
Replace Text input by Texterarea for field type TEXT

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3472]
The text field type doesn't look nice with longer texts.
There's already a PR to fix the view mode (https://github.com/twentyhq/twenty/issues/3300), but we should also improve the edit mode (on show page and table view).

<img width="291" alt="Screenshot 2024-01-15 at 18 59 01" src="https://github.com/twentyhq/twenty/assets/6399865/f237bfea-1712-4da2-b741-6e0f5b32976c">

When we are in edit mode we should change it to a Textarea.
The field should keep the same default height, so for short inputs, this PR shouldn't change anything on the display - the result should be exactly the same. But for longer inputs, it should automatically expand into a multi-row textarea as I type.

Would be great if a video can be provided on the PR. 🙏

**Comment by abhisheksharma010** [comment]
Hello, can you assign this issue to me? I can easily resolve this.

**Comment by FelixMalfait** [comment]
@abhisheksharma010 thanks! saw @jeet1desai had raised a PR right after your comment. I'm cleaning the good first issues today and recreating new ones!
