### ISSUE TITLE
Fix migration command

### ISSUE THREAD

**Issue by martmull** [twentyhq/twenty#3475]
## Scope & Context

In twenty-server, when trying to rename a column on the webhook table with `yarn command workspace:sync-metadata -w "27249421-642e-4963-9751-7850f01d5572"`

## Current behavior

Encountering the following error:
<img width="1468" alt="image" src="https://github.com/twentyhq/twenty/assets/29927851/a35206bd-d1e5-4a6b-a7f1-0a0b53dc5d6e">
<img width="1470" alt="image" src="https://github.com/twentyhq/twenty/assets/29927851/cbb37197-6741-478b-b095-49c0a28183fa">
<img width="1470" alt="image" src="https://github.com/twentyhq/twenty/assets/29927851/648f5532-b99d-4cf8-8dbd-db947a0e8305">

## Expected behavior

A functional command

**Comment by charlesBochet** [comment]
Fixed! Closing this issue
