### ISSUE TITLE
Round sum in board column total value

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3476]
Here's how bad a large number or number with cents currently looks like on the opportunities board:
<img width="488" alt="Screenshot 2024-01-16 at 09 52 56" src="https://github.com/twentyhq/twenty/assets/6399865/5b13fe8c-29a4-4c8f-8254-b3815718ede1">

Instead we shouldn't display cents and use K,M,B formatting (kilo, million, billion).

Let's keep a precision of 3 decimals.
Ex:
900
1.25k
5.35k
10.3k
102k
1.35m
15.2m
500m

**Comment by jeet1desai** [comment]
Hello @FelixMalfait, Please assign it to me, I'd love to work on it.

**Comment by FelixMalfait** [comment]
@jeet1desai thanks!
