### ISSUE TITLE
Improve Settings Display on intermediate screen size

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3479]
I know we're not optimizing for that format in settings but I feel like there would be a very quick fix to make the left sidebar width more adaptable on intermediate screen size (ex: iPad).

<img width="548" alt="Screenshot 2024-01-16 at 11 37 58" src="https://github.com/twentyhq/twenty/assets/6399865/92e6c140-2e08-4d3c-abc9-be8a6ae1e6c4">

**Comment by Bonapara** [comment]
Agreed! Related to #3411.

When stating "The content should be centered in the middle of the screen":

![image](https://github.com/twentyhq/twenty/assets/19412894/eb2859ef-6bef-4b7d-aac5-b261a7da178f)

This means that the margin should vary to adapt responsively:

![image](https://github.com/twentyhq/twenty/assets/19412894/4b7f6a22-9ad8-4f4d-841b-67cd7ee95af0)

**Comment by FelixMalfait** [comment]
Great! closing, let's keep the first issue only (which I had missed)
