### ISSUE TITLE
Improve sidebar object for long record names and long object names

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3489]
Here's how the left-side menu currently behaves with longer texts:

<img width="230" alt="Screenshot 2024-01-16 at 16 19 43" src="https://github.com/twentyhq/twenty/assets/6399865/f7e3ee9f-eda0-40fb-b789-5235e5b43fad">

We should do an ellipsis instead keep everything on a single line.

cc @Bonapara fyi

**Comment by jeet1desai** [comment]
Hello @FelixMalfait, Could you please assign it to me, I'd love to do it.

**Comment by FelixMalfait** [comment]
Of course @jeet1desai thanks!
