### ISSUE TITLE
Launch cleaning cron

### ISSUE THREAD

**Issue by martmull** [twentyhq/twenty#3491]
## Scope & Context

In twenty-server, the cleaning job has been developed and in running in production. It has a feature flag so it does not run on all workspaces.

The goal is to make it run on all workspaces

## Technical inputs
- dry run on sensitive workspaces to make sure everything works well
- remove feature flag
- add a command to actually delete inactive workspaces

**Comment by charlesBochet** [comment]
Disable "incomplete" workspaces
