### ISSUE TITLE
When I create a card in a board it should be created at the bottom

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3493]
If I create a card from the new button, then it should be created at the bottom and not at the top - otherwise we don't realize it's been created.

See video for current behavior:

https://github.com/twentyhq/twenty/assets/6399865/b463c55c-c375-41d9-8b3f-38e03575cf19

If I create the card through the top-right (+) button then it should still be created at the top

cc @Bonapara

**Comment by Varrooo** [comment]
Hey @FelixMalfait !
Could you assign it to me ? I would like to work on this

**Comment by salehsami** [comment]
Hi @FelixMalfait
I was going through the code and  am ready to work on the issue, kindly assign this to me

**Comment by FelixMalfait** [comment]
Assigning @Varrooo since you came first. Thanks!

@salehsami Thanks! We'll create more good first issues today

**Comment by Varrooo** [comment]
Hey @FelixMalfait

This should be good, let me know what you think :)
 #3541

**Comment by FelixMalfait** [comment]
This is still open as the first attempt wasn't successful :)

**Comment by Mishra-Pravin** [comment]
Hey @FelixMalfait @Bonapara, I am working on it.
