### ISSUE TITLE
Fix z-index for menu to add a new field

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3495]
See current behavior :

<img width="287" alt="Screenshot 2024-01-16 at 18 25 10" src="https://github.com/twentyhq/twenty/assets/6399865/5705b720-9267-4b52-a014-35cd28f4a656">

Instead that menu should be above the cells

**Comment by jeet1desai** [comment]
Hello @FelixMalfait, could you please assign it to me, I'd love to do it.
