### ISSUE TITLE
Some pages are not reachable with documentation search

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3496]
## Bug Description

<img width="1455" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/3239a177-25ee-4ff9-a179-b4c736878d1e">

When we search with "demo" and click on the first result, we have a 404.

## Expected behavior

The search shouldn't give results that redirects to non existing pages.

**Comment by FelixMalfait** [comment]
Thanks for the report! This is now fixed
