### ISSUE TITLE
Fix relation picker behavior to add a chip

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3499]
### Current behavior:
I cannot click to access the related record.
For example, I cannot access the company from the people list view
<img width="225" alt="Screenshot 2024-01-17 at 10 20 15" src="https://github.com/twentyhq/twenty/assets/6399865/a0fde22a-0e82-4582-abba-398038f31d55">

### Desired behavior
- Put companies inside **relation** chips
- Make sur the chip is clickable and links to the related show page
![CleanShot 2023-11-07 at 15 46 07](https://github.com/twentyhq/twenty/assets/19412894/b7d15037-0ef4-4ba5-beea-6942739fcf9d)

**Comment by FelixMalfait** [comment]
Sure! Thanks @jeet1desai

**Comment by jeet1desai** [comment]
It is now resolved. closing the PR. @FelixMalfait
