### ISSUE TITLE
Adding a company/person while a filter is active

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3501]
## Bug Description

While a filter is active, adding a company/person is possible. But, when removing the filter, the added company disappears and reappears only after a refresh.

https://github.com/twentyhq/twenty/assets/71827178/0f15d904-900d-4d4e-a4d7-14cffea8ce7b

## Expected behavior

The new company/person should be visible when the filter is removed.

**Comment by abhishek20111** [comment]
I believe I can do it, but when I open the website, it shows a book priced at $9. 
Can you guide me on how to preview it and check its functionality?

**Comment by FelixMalfait** [comment]
@abhishek20111 yes the cloud-hosted version is what allows us to fund this project and keep the development going. But the self-hosted version is free, if you setup the project locally you wouldn't see that message.
https://docs.twenty.com/contributor/local-setup/yarn-setup

**Comment by kuluruvineeth** [comment]
@FelixMalfait I would like to work on this issue, would you please assign this to me.

**Comment by FelixMalfait** [comment]
Thanks @kuluruvineeth!

**Comment by IsabelaPO** [comment]
Hello! When trying to recreate the bug, this error message appears: 
<img width="540" alt="image" src="https://github.com/twentyhq/twenty/assets/106828051/0191ef54-936d-4ac8-a535-f8f9aab8e629">
Can anyone help me?
