### ISSUE TITLE
[T-405] Workspace name is not refreshed after login

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#351]
I logged in to the Apple workspace but it was still showing "Twenty" on the top-left corner until I refreshed.

![](https://uploads.linear.app/b1acf0dc-e74a-40f6-989b-074be1c096b2/0d13e939-f6c9-46ec-a3a4-90dc06bf61d6/b73d4273-d8fc-470e-b333-3e5f5f08596c)

<sub>From [SyncLinear.com](https://synclinear.com) | [T-405](https://linear.app/twentyhq/issue/T-405/workspace-name-is-not-refreshed-after-login)</sub>

**Comment by charlesBochet** [comment]
This issue has been resolved in: https://github.com/twentyhq/twenty/pull/361
