### ISSUE TITLE
Improve performance of demo workspace

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3514]
In demo workspace we are storing 1000+ image as base64 in the DB.
This slows down the database and we need to move to another solution (use a profile pic generator website and link to these urls, host our own images on S3, etc.)

**Comment by FelixMalfait** [comment]
**Step 1: useful function convert UUID to a number**
```
import { createHash } from 'crypto';

function uuidToNumber(uuid: string, N: number): number {
  // Create a hash of the UUID
  const hash = createHash('sha256').update(uuid).digest('hex');
  
  // Convert the first 8 characters of the hash to a decimal number
  const intHash = parseInt(hash.substring(0, 8), 16);
  
  // Use modulus operation to map the hash number to the range [1, N]
  return intHash % N + 1;
}

// Example usage:
const uuid = '123e4567-e89b-12d3-a456-426614174000';
const N = 100;  // Adjust N as needed
console.log(uuidToNumber(uuid, N));
```

(not required, you can also do the matching without this if you prefer)

**Step 2:  image service**

Opt1: use https://i.pravatar.cc but I'm afraid it will break, doesn't seem to be a reliable service
Opt2: store our photos in a dedicated private git repo which we simply expose with Github pages ; I'm afraid the Opt1 service will break. Repo should be named "placeholder-images". We just need ~100 photos. Can come from existing base64 set we had created or saving it from https://thispersondoesnotexist.com

**Step 3: Check that image are properly displayed on demo, I remember there was a bug but I'm not sure it's still there.**

**Comment by FelixMalfait** [comment]
Ok I created the repo and exposed it through Github pages. Should be fairly simple!

**Comment by charlesBochet** [comment]
Still accurate
