### ISSUE TITLE
Slash Menu Activity Editor

### ISSUE THREAD

**Issue by brendanlaschke** [twentyhq/twenty#3518]
## Scope & Context

I think the menu items in the slash menu are to big, icon sizes are different and the usability is not great with many objects. I think Craft solves this better:

<img width="371" alt="Bildschirmfoto 2024-01-17 um 15 49 34" src="https://github.com/twentyhq/twenty/assets/48770548/30a5fea2-eac9-4a7d-93d3-d566fd040bf8">

## Current behavior

<img width="374" alt="Bildschirmfoto 2024-01-17 um 15 50 36" src="https://github.com/twentyhq/twenty/assets/48770548/139c8f49-3b2c-4e1f-9b5c-18a6b5a22ed1">

## Expected behavior

Submenus for Header/Text Blocks and list types & smaller menu items?

What do you think @FelixMalfait ?

**Comment by FelixMalfait** [comment]
100% agree yes @brendanlaschke thanks for always being so relevant!

cc @Bonapara fyi

**Comment by Bonapara** [comment]
Agreed! I think we'll have a lot of work on the editor soon. So, I'll encourage to do only quick fixes.
