### ISSUE TITLE
Fix broken calendar component on filter

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3520]
I added a date filter to the companies list view and it looked like this:

<img width="340" alt="Screenshot 2024-01-17 at 16 52 15" src="https://github.com/twentyhq/twenty/assets/6399865/b69e1cdb-15ec-4aad-8f2d-597341d5e831">

**Comment by jeet1desai** [comment]
@FelixMalfait could you please assign to me!!
