### ISSUE TITLE
Favicons are being re-rendered on hover

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3523]
Not sure how this would best be solved cleanly, but it's a bit annoying from a UI perspective.

https://github.com/twentyhq/twenty/assets/6399865/31ce34ac-1491-450b-bc99-57d445e6602f

**Comment by ijayhub** [comment]
Is it that the favicon should remain visible even when hovering?

**Comment by ijayhub** [comment]
I would like to work on it

**Comment by FelixMalfait** [comment]
Hi @ijayhub as you can see hovering the components triggers a re-render of the image. We want to do something clean to avoid that. I don't think we should refetch the favicons on hover at - if there's been a 500 then we just accept it and live the placeholder icon as it is. Assigned you! Thanks

**Comment by ijayhub** [comment]
Good morning,
I won't be able to work on this repository at the moment. Can I extend it, please? or assign it to someone else?
Thank you

**Comment by FelixMalfait** [comment]
Sure! unassigned you

**Comment by essofyany** [comment]
Hi @FelixMalfait 
I would like to take this issue

**Comment by FelixMalfait** [comment]
@essofyany sorry for the late reply - just assigned you! Thanks
