### ISSUE TITLE
On demo account, impossible to create a new opportunity

### ISSUE THREAD

**Issue by martmull** [twentyhq/twenty#3527]
## Bug Description

<img width="1147" alt="image" src="https://github.com/twentyhq/twenty/assets/29927851/2b5773b6-c5d5-4f2a-aadf-f29f7fbc4d5f">
<img width="1151" alt="image" src="https://github.com/twentyhq/twenty/assets/29927851/860dd1e5-ef33-4971-bdb3-61243199ec49">
<img width="1135" alt="image" src="https://github.com/twentyhq/twenty/assets/29927851/64f5d3da-0f1e-44a0-8fd9-c442bd0eb855">

Returns this error:
```
{
    "errors": [
        {
            "message": "Variable \"$input\" got invalid value { id: \"f5abd906-60a1-4be2-b951-a0dce10cea7d\", name: \"Opportunity\", pipelineStepId: \"249ef6c2-588d-41b7-9b96-622d080411fa\", companyId: \"0028e75b-deaf-4afc-8f97-efe7ffb3d039\" }; Field \"name\" is not defined by type \"OpportunityCreateInput\".",
            "locations": [
                {
                    "line": 1,
                    "column": 31
                }
            ]
        }
    ]
}
```

**Comment by jeet1desai** [comment]
Hello @charlesBochet,  I wanted to bring to your attention this issue I've investigated. It appears that two days ago, the addition of name: 'Opportunity', in the useCreateOpportunity.ts file has led to an error.

Upon removing this line, the functionality is restored and everything seems to be working fine. I would appreciate your thoughts on this matter.

Thank you.

**Comment by charlesBochet** [comment]
It will also break other workspaces, we should run a migration command today

**Comment by FelixMalfait** [comment]
Assuming this was fixed @charlesBochet. Please re-open if not!

**Comment by zzzhangqi** [comment]
@charlesBochet 
I encountered the same problem in v0.2.3, how can I solve it?
