### ISSUE TITLE
Fix relation picker 

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3533]
Just noticed the relation picker isn't properly displayed on Storybook.
Probably something to fix on the component itself

https://storybook.twenty.com/?path=/story/ui-input-relationpicker-singleentityselect--with-selected-entity

<img width="943" alt="Screenshot 2024-01-18 at 12 04 03" src="https://github.com/twentyhq/twenty/assets/6399865/e1d3f3ee-16a3-4772-afb5-fe4e33b2fe3f">

**Comment by anoopw3bdev** [comment]
@FelixMalfait I had checked this issue and in storybook it is breaking, do you find out any place in the application where it is breaking? because I could see it working correctly.

**Comment by FelixMalfait** [comment]
@anoopw3bdev it seems to be working correctly in the app yes, not sure why it's breaking - I haven't investigated

**Comment by anoopw3bdev** [comment]
It seems to be breaking due to the `height: 100%` property of the styled component `StyledDropdownMenuItemsExternalContainer` in  `DropdownMenuItemsContainer` component

**Comment by FelixMalfait** [comment]
@anoopw3bdev feel free to raise a fix if you're confident in your solution! Thanks 🙏

**Comment by anoopw3bdev** [comment]
Sure @FelixMalfait will raise a fix soon

**Comment by anoopw3bdev** [comment]
FYI, I'm still on it @FelixMalfait,
caught up with some issues with running the twenty app locally, requested some help from the team.

**Comment by anoopw3bdev** [comment]
@FelixMalfait this issue no more seems to exist. Please confirm.
<img width="421" alt="Screenshot 2024-02-01 at 6 24 16 PM" src="https://github.com/twentyhq/twenty/assets/44577841/71729230-f1af-4105-81bd-4787fce516f4">
