### ISSUE TITLE
Setup rate limiting with NestJS throttler

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3545]
We need to setup rate limiting to improve security.

It's well documented here: https://docs.nestjs.com/security/rate-limiting

We want to do the async configuration to allow each self-hosted instance to set their own parameters as environment variable.

We want to have a different throttling for users and non logged in users (overwrite key with generateKey).
And for logged in users we want to be able to both set a short TTL limit and a long TTL limit, so there will be 6 environment variables total.

TBD if it's worth allowing Redis as an optional Driver for those who want (we already have a redis implem for queue).

**Comment by jss475** [comment]
Hey @FelixMalfait! I hope you don't mind, but I wanted to challenge myself and gave this a try. Let me know if I need to change anything!

**Comment by FelixMalfait** [comment]
@jss475 oh great thanks! We'll do the review this week and let you know!
