### ISSUE TITLE
Display Email Instead of Duplicate Name in 'Members' Settings

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3554]
## Current Behavior

The user's name is displayed twice on the "Members" page.

![CleanShot 2024-01-19 at 14 46 29@2x](https://github.com/twentyhq/twenty/assets/19412894/3ddd2335-e979-4843-a882-2d81501de68d)

## Desired Behavior

Display the user's email below their name.

![CleanShot 2024-01-19 at 14 50 50@2x](https://github.com/twentyhq/twenty/assets/19412894/c618bcf5-1556-45d6-87d5-ffbd8b0ab5a4)

**Comment by LogiqueClergyman** [comment]
I could fix this issue if you could assign this to me. Thanks.

**Comment by danieldsouza13** [comment]
Hi I would like to work on fixing this issue. Please assign it to me.
