### ISSUE TITLE
Enhance Authentication Security - Generic Error Messaging

### ISSUE THREAD

**Issue by mohamedamara1** [twentyhq/twenty#3564]
## Scope & Context

In the current authentication system, the handling of incorrect credentials exposes specific details about whether the email or password is incorrect. This information leakage can pose a security risk by potentially aiding attackers in unauthorized access attempts.

## Technical inputs

The current authentication code returns specific error messages like "This user doesn't exist" or "Wrong password," which may inadvertently reveal information to potential attackers. Instead, adopting a practice of consistently returning a generic error message like "Invalid credentials" would enhance security by reducing the amount of information disclosed to unauthorized users.

Refactor the authentication code to return a generic error message in case of incorrect credentials.

Ensure that the error message is consistent and does not reveal details about whether the email or password is incorrect.

**Comment by mohamedamara1** [comment]
I don't think this is needed

**Comment by FelixMalfait** [comment]
Yes this is a frequent debate. I think as long as we rate-limit the API we're fine - the risk remains limited and it clearly enhances the user experience to get clear feedback. @jss475 has onopened a PR for the rate limiting already. There's also one ongoing to add captcha
