### ISSUE TITLE
Env set up issue. Not able to setup repo using Docker.

### ISSUE THREAD

**Issue by yashdev9274** [twentyhq/twenty#3565]
## Scope & Context

**Issue:** 

Working on setting up environment for this resp repository, but I'm unable to do it facing some issue while setting up it with Docker

## Current behavior

**Example:** 

This issue I'm facing is due to "make " cmd of Docker

```
$ make docker-dev-build
bash: make: command not found

```
[Screenshot] :
![image](https://github.com/twentyhq/twenty/assets/72986960/bfab1243-6b01-456d-955b-1eb4936ae44b)

**Comment by GARY121github** [comment]
You have to download **make** command.
You can refer this -> [https://bobbyhadz.com/blog/make-is-not-recognized-as-internal-or-external-command](url)

**Comment by FelixMalfait** [comment]
yes thanks @GARY121github 

Make is just there to alias commands, if you don't want to install make you can just find the commands to run in this file https://github.com/twentyhq/twenty/blob/main/Makefile
