### ISSUE TITLE
The calendar component is hidden behind the tab container

### ISSUE THREAD

**Issue by jeet1desai** [twentyhq/twenty#3569]
## Bug Description
The calendar component is hidden behind the tab list container and in dark mode calendar display value is supposed to be white.

**Example:** 
![image](https://github.com/twentyhq/twenty/assets/52026385/7cc66fa7-9d55-48db-97af-5b3004fc9198)
![image](https://github.com/twentyhq/twenty/assets/52026385/31f49c64-c123-4ef9-910a-de73d2012a0d)

**Comment by Bonapara** [comment]
Well noticed, thanks @jeet1desai!

**Comment by pranay911** [comment]
Hey @Bonapara Can you please assign this to me? Thanks

**Comment by Bonapara** [comment]
@pranay911 I assigned you as you were first. If no longer interested, I'll assign you @vikki9121. Thanks both for contributing to Twenty

**Comment by pranay911** [comment]
Thanks @Bonapara I started working on the issue

**Comment by pranay911** [comment]
@jeet1desai @Bonapara can you please provide steps to reproduce?

**Comment by jeet1desai** [comment]
Yes @pranay911,
To reproduce the issue, follow these steps:

1. Navigate to the "Companies" or "People" list page.
2. Select any record by clicking on the respective name.
3. You will be directed to the details page for the selected record.
4. On the details page, observe the issue as described.

**Comment by pranay911** [comment]
Thanks, @jeet1desai, I need one more help can you please help me to find out the codebase?

**Comment by FelixMalfait** [comment]
Same issue for the new "address" field type

**Comment by FelixMalfait** [comment]
This has been fixed!
