### ISSUE TITLE
User still displayed on Task screen/dropdown after account deletion

### ISSUE THREAD

**Issue by TBG-FR** [twentyhq/twenty#3591]
## Bug Description

1. A new user (here `Jean Jean`) creates his account using the homepage `/sign-in`
2. After login and initial setup, this user goes to `/settings/profile` and hits `Delete account`
3. This user cannot log-in anymore ✅ 
3. This user doesn't appear in Workspace members anymore ✅ 
4. However, we can still select him on the `Tasks` screen to assign him a task 🛑 

![Capture d'écran 2024-01-23 160823](https://github.com/twentyhq/twenty/assets/18146038/3e469bd2-e402-4ca2-afb6-faa9c7b33daf)

![Capture d'écran 2024-01-23 160905](https://github.com/twentyhq/twenty/assets/18146038/b93b659d-f27f-487c-8ef1-b9d729e6bf12)

## Expected behavior

User should be fully deleted, and shouldn't appear in any field or screen.

## Technical inputs

GraphQL response seem alright, so I guess the user is still present in the database 🤔 
```
{
    "data": {
        "updateActivity": {
            "id": "977a26b9-8acd-43ae-88b3-8ccc0cf77d5f",
            "assigneeId": "86e3014e-c922-44ba-a7bb-a227bb2ceefa",
            "assignee": {
                "id": "86e3014e-c922-44ba-a7bb-a227bb2ceefa",
                "userEmail": "",
                "userId": "f6ba3c6d-1a21-4964-9493-562933cb8df4",
                "name": {
                    "firstName": "Jean",
                    "lastName": "Jean",
                    "__typename": "FullName"
                },
                [...]
```

**Comment by TBG-FR** [comment]
- After restarting the `server` container, this user came back in Workspace's Members list 
- After deleting it directly from the list (using my own account/user), it's gone for good

So maybe that's only the "self-deletion" of an user/account that has an issue

**Comment by FelixMalfait** [comment]
Thanks for the detailed report @TBG-FR super helpful!

Currently a user is represented in multiple tables:
- there is one table `users` that is shared acrossed all workspaces, as one user can belong to multiple workspaces
- each workspace has its own `workspace_member` table that holds the list of users that belong to the workspace

Based on your description, my intuition is that in the `deleteUser` method we only delete the user, but we don't delete its representation in the `workspace_members` tables.

I think what we should implement is:
- Check if the user has more than 1 workspace, in that case we DONT delete the user record, we just delete the workspace member object upon clicking on this button
- If the user has only one workspace, then we can safely delete the user AND the workspace member

**Comment by sriram-V20** [comment]
Hi @FelixMalfait ,

Can I work on this issue ?

**Comment by FelixMalfait** [comment]
@sriram-V20 thanks! There's a recent ongoing PR that we might want to wait for: https://github.com/twentyhq/twenty/pull/4036
(done by @AdityaPimpalkar and waiting for review by @martmull). Probably we'll also need to remove the `userWorkspace` (or maybe that's something that will be tackled as part of the PR already

**Comment by FelixMalfait** [comment]
@AdityaPimpalkar can you confirm we can close with #4232?

**Comment by AdityaPimpalkar** [comment]
Yes! we can close it, tested it out. Works perfectly now 👍
