### ISSUE TITLE
Navigating from the NavBar after an error is catched by a boundary should reset the error's state

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3592]
## Scope & Context

Error boundary : 

<img width="1487" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/5118b062-229c-4629-87da-3115a77ff950">

## Current behavior

We have to refresh the page or both navigate and reload to reset the app.

## Expected behavior

We want to reset the error state if we navigate to a page with the left menu.

**Comment by Mic-hvel** [comment]
Hello, can you assign this to me?

**Comment by sethshivam11** [comment]
Please provide steps to reproduce?

**Comment by FelixMalfait** [comment]
Hi @Mic-hvel @sethshivam11 any of you two working on this? Thanks 🙏

**Comment by sethshivam11** [comment]
Demo account giving errors of "Error: ApolloError: Response not successful: Received status code 500" and no tabs are opening just giving errors
![Screenshot 2024-02-21 212122](https://github.com/twentyhq/twenty/assets/130232913/2d80c839-e671-440d-bae2-5077b0615458)

**Comment by charlesBochet** [comment]
@sethshivam11 Yes, someone managed to break the demo workspace. Found the bug and reset the demo workspace, it should work now :)

**Comment by lucasbordeau** [comment]
See https://github.com/twentyhq/twenty/pull/5084
