### ISSUE TITLE
Cannot create new opportunities after recent update  (docker 0.2.3)

### ISSUE THREAD

**Issue by iamDecode** [twentyhq/twenty#3597]
## Bug Description

After updating to the latest docker images (server, postgres, front, all 0.2.3), I don't seem to be able to create any new opportunities. 

**Example:** 
Just create a new opportunity, select a company and wait. The frontend gives a generic:

![Screenshot 2024-01-23 at 22 43 12](https://github.com/twentyhq/twenty/assets/1223300/d8816f47-e5e7-4f74-b77a-036ea7bb413e)

in the server logs I get a more specific:

```
  Error: Cannot return null for non-nullable field Mutation.updateOpportunity.
      at completeValue (/app/node_modules/@graphql-tools/executor/cjs/execution/execute.js:421:19)
      at /app/node_modules/@graphql-tools/executor/cjs/execution/execute.js:334:49
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/node_modules/@envelop/core/cjs/orchestrator.js:383:27
      at async YogaServer.getResultForParams (/app/node_modules/graphql-yoga/cjs/server.js:304:26)
      at async YogaServer.handle (/app/node_modules/graphql-yoga/cjs/server.js:77:29)
query time: 110.48989100009203 ms on query opportunity
```

## Expected behavior

The opportunity is created.

## Related

Perhaps its useful context that when I click an opportunity, the page I end up at seems half-broken too. I see the normal object details, but the icon/picture and title are missing. Other fields and relations are showing. However, clicking the tasks/notes/files tabs gives me errors, and I am not able to create any of those in those tabs either.

Example:
![Screenshot 2024-01-23 at 22 49 25](https://github.com/twentyhq/twenty/assets/1223300/d8b7a432-18a2-41b5-a655-1a082c977d9f)

Server response for those:

```
  Error: Invalid UUID
      at GraphQLScalarType.checkUUID (/app/packages/twenty-server/dist/src/workspace/workspace-schema-builder/graphql-types/scalars/uuid.scalar.js:11:15)
      at coerceInputValueImpl (/app/node_modules/graphql/utilities/coerceInputValue.js:151:26)
      at /app/node_modules/graphql/utilities/coerceInputValue.js:75:16
      at Function.from (<anonymous>)
      at coerceInputValueImpl (/app/node_modules/graphql/utilities/coerceInputValue.js:73:20)
      at coerceInputValueImpl (/app/node_modules/graphql/utilities/coerceInputValue.js:117:34)
      at coerceInputValueImpl (/app/node_modules/graphql/utilities/coerceInputValue.js:117:34)
      at coerceInputValue (/app/node_modules/graphql/utilities/coerceInputValue.js:32:10)
      at coerceVariableValues (/app/node_modules/@graphql-tools/executor/cjs/execution/values.js:68:65)
      at getVariableValues (/app/node_modules/@graphql-tools/executor/cjs/execution/values.js:19:25)
```

## Note

I just got started with the project, and am not sure this is a bug or my mistake in updating incorrectly. Are there any other steps required for upgrading to a newer docker image that I may have missed?  Let me know I should move the discussion elsewhere (discord?) Instead. I tried running `yarn database:migrate` on the server to be sure, but there was nothing to migrate.

**Comment by FelixMalfait** [comment]
Hey @iamDecode sorry about this (and replying late to this issue).
While we're in alpha we're still introducing breaking changes between version - this will change soon as we focus on stabilization.
In your case, what might have happened is that we introduced a "name" field on Opportunities.
We have a pretty complex engine that looks at the meta data defined for a given workspace and should apply the missing migration if there's a difference between what we've seen in Postgres and what is given by the metadata layer. That's been built as a one off "health check" command we run manually in production for the cloud version for now but the goal is to make it run automatically for smoother upgrades for people who self-host. 

`yarn database:migrate` wouldn't help indeed because the migrations are generated one layer above: CRM allows you to define your business logic and the field you need, and then the engine will run the relevant migration for each individual workspace.

**Comment by FelixMalfait** [comment]
Closing the issue for now but feel free to reply / keep discussing if we can help - I should receive a notification

**Comment by iamDecode** [comment]
Thanks for the clarification! I see the health check you mentioned can be ran using `yarn command workspace:health` (or perhaps I should use `sync_metadata`, since the `--fix` arguments seems to still be in development). However its a bit unclear how I can figure out the workspace id.

**Comment by FelixMalfait** [comment]
@iamDecode Workspace id can be found in the `id` column on the `workspaces` table in Postgres. 
Those 2 commands are still a bit experimental yes. They will be documented in a couple month once we have more experience with them. We will probably even introduce a web UI to trigger them directly

**Comment by zzzhangqi** [comment]
@FelixMalfait I have also encountered this problem, how can I solve it?
