### ISSUE TITLE
Add background transparency and blur on menus

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3617]
# Current Behavior

Today, the menu background color is `rgb(252, 252, 252)`

![CleanShot 2024-01-25 at 10 35 01](https://github.com/twentyhq/twenty/assets/19412894/98c792fa-31be-4db3-b9c6-4c7f0aa60147)

# Desired Behavior

The menu background color should be transparent and have a blur effect, just like the input.

![image](https://github.com/twentyhq/twenty/assets/19412894/cb4ce1d4-efd3-45f3-bc48-074dfe20124b)

See the input CSS: 
![CleanShot 2024-01-25 at 10 38 42](https://github.com/twentyhq/twenty/assets/19412894/1e982a33-48c0-45cf-bb89-ebe94ee23e23)

**Comment by jeet1desai** [comment]
Hey @Bonapara Could you please assign it to me, I'd love to do it.

**Comment by Bonapara** [comment]
@jeet1desai, done, thanks for contributing ❤️
