### ISSUE TITLE
[Timebox] Separate user creation from workspace creation

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3628]
As of today, when someone signs up we create the workspace along with the user in the signup method of the Auth service.
This clutters the database with a lot of unused schemas. 

Instead we should only create the workspace upon clicking on the workspace creation form if it's possible.

The issue is with billing on our cloud version... Currently the "plan required" screen is displayed based on the workspace status so that would break. I feel like we have to add a flag like `hasSetupBilling` or something like this on the `user` table to restrict access.

**Comment by charlesBochet** [comment]
Scope:
- do not create workspace on user sign up
- make sure the front is still working
- create an endpoint to "activate" the workspace
