### ISSUE TITLE
Remove unnecessary bottom border on shows tasks tab

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3640]
# Current behavior

There is an unnecessary 1px border bottom/breakline under the (last) task:

![CleanShot 2024-01-26 at 14 58 43@2x](https://github.com/twentyhq/twenty/assets/19412894/0f971ac4-4fc0-49df-b5b2-a9b3ebf2b608)

Zoomed:
![CleanShot 2024-01-26 at 15 01 44@2x](https://github.com/twentyhq/twenty/assets/19412894/fe24ed5e-28b2-410c-95df-62f72edad8de)

# How to reproduce

Go to a detail page/ show without tasks
Create a task

# Desired Behavior

Remove this border-bottom

**Comment by pranay911** [comment]
@Bonapara ,Can you please this issue to me?

**Comment by Bonapara** [comment]
Done @pranay911, thanks!

**Comment by pranay911** [comment]
@Bonapara Already fixed by @jeet1desai Thanks!
