### ISSUE TITLE
Add REST endpoints for metadata API

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3648]
We have built a rest wrapper for the `/graphql` endpoint (company, person, opportunities, views)

But we have not built a wrapper for the `/metadata` graphql endpoint so it is not possible to create an object through the rest api for example. We should make it available and provide an API for that two.
Make sure to update the docs so that we can access the docs for that API too.

**Comment by FelixMalfait** [comment]
Once this is done, make sure to update the docs :)

**Comment by AdityaPimpalkar** [comment]
Hi @FelixMalfait. Currently the rest api is on path `rest/*` would it be easier to modify the existing rest-api files to fit in the metadata path too? or write a separate service file to a `rest/metadata/*` path to query fields, objects?

Is `rest/field` okay? or `rest/metadata/field` good?

**Comment by FelixMalfait** [comment]
Hey @AdityaPimpalkar 👋
I'd say we should keep the `/rest/` api path for core queries (on /graphql) ; and redirect to the /metadata graphql endpoint under `/rest/metadata` endponts

Maybe just adapt the `callGraphql` method? I'm not sure we need something more complex than that but maybe I'm missing something
