### ISSUE TITLE
Prevent creating Empty Note & Task

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3649]
# Current behavior

After clicking on `new task` or `new note` a note is created and saved even if it's empty:

![CleanShot 2024-01-26 at 17 04 47@2x](https://github.com/twentyhq/twenty/assets/19412894/c237e1a0-252c-4ab1-ad31-ab186c483c77)

![CleanShot 2024-01-26 at 17 06 34@2x](https://github.com/twentyhq/twenty/assets/19412894/192b2864-a493-4102-965f-ab4d634af2ff)

![CleanShot 2024-01-26 at 17 06 58@2x](https://github.com/twentyhq/twenty/assets/19412894/600761a1-efc6-4739-ab42-700af35360c0)

# Desired Behavior

We don't want to save empty notes & tasks (if the title doesn't contain anything or blank spaces) They should be deleted and not be displayed in the timeline.

# Very Private Comment

Il paraît que tu es déjà dessus @lucasbordeau ;) Il y a une autre issue sur le sujet ?

**Comment by charlesBochet** [comment]
This has been solved, closing this issue
