### ISSUE TITLE
Update doc to point directly to the GraphQL/REST APIs

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3650]
The current documentation is confusing and has some useless text about GraphQL and REST APIs.

We want to:
- Remove the two pages for REST api / GraphQL API
- Instead directly link to https://docs.twenty.com/graphql/ and https://docs.twenty.com/rest-api/
- Create a second GraphQL console for the /metadata endpoint ; add a link to that console as well (labelled "GraphQL Metadata API")

**Comment by Satyabhama-Reddy** [comment]
Hi,

Can I contribute to this?
Also, I didn't quite understand the last point. Could you please elaborate.

Thanks,
Satya

**Comment by FelixMalfait** [comment]
@Satyabhama-Reddy sure! Assigning you :)

For the last item, see here:
https://github.com/twentyhq/twenty/blob/main/packages/twenty-docs/src/pages/graphql.tsx#L21

We are dynamically fetching the schema from the `graphql` endpoint.
But we actually have two APIs:
- `graphql` endpoint is the standard api to manipulate objects (e.g. create a company, update a person, etc.
- `metadata` endpoint is the api to manipulate object metadata (e.g. create a new type of object, create a new field on an existing object, etc.)

So we need to adapt the code a bit to be able to have 2 different pages, one for each api.
(please don't copy paste too much code ;))

Thanks!

Note there is also a console in "twenty-website" folder but you can ignore it.

**Comment by FelixMalfait** [comment]
@Satyabhama-Reddy good for you? Thanks!

**Comment by FelixMalfait** [comment]
Hey @Satyabhama-Reddy unassigning you since we don't have any news. Thanks!

**Comment by FelixMalfait** [comment]
Closing the issue here as Brendan's PR solves the GraphQL part and we'll use #3648 to followup on the REST part
