### ISSUE TITLE
Bug: Can't add relations on Note & Tasks

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3651]
# How to reproduce

1. Go to the `Notes` or `Tasks` panel
2. Create a new `Note` or `Task`
3. Add some records as relations
4. A `400` error appears

Also happens in the "Task" tab

https://github.com/twentyhq/twenty/assets/19412894/03df24de-73fc-494e-9d32-f5915bb4d116

**Comment by brendanlaschke** [comment]
I think it's the same as #2990 - Only a reload fixes the ability to create relations on the newly created activities ...

**Comment by charlesBochet** [comment]
Closing this one as this has been solved
