### ISSUE TITLE
Implement 'Forgot Password' from Sign In

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3652]
# Current behavior

To change your password, you need to be logged in and navigate to the Settings.

# Desired Behavior

With the completion of #3245 backend, we're now able to insert a `Reset Password` link at the base of the Email & Password login page.

### Update the Email & Password login page

Please ensure this update only applies to the `Email & Password` login page. The initial login page should still display the agreement to Twenty's Terms of Service and Data Processing Agreement.

**Email & password page to update:**
![image](https://github.com/twentyhq/twenty/assets/19412894/3f1ddfd7-d2d8-4d5e-9d3b-b355c0b54f8f)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19209-62847&mode=design&t=5z3QOvk8fZV3xVB3-11

**First Login page to keep as it is:**
![image](https://github.com/twentyhq/twenty/assets/19412894/f9b8925c-b392-445a-bb18-b10232be1695)

### Send an Email with a link to reset password 

![image](https://github.com/twentyhq/twenty/assets/19412894/661a36cd-34a0-4444-a464-44f4a0187568)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=16594-92960&mode=design&t=5z3QOvk8fZV3xVB3-11

### Update your password

![image](https://github.com/twentyhq/twenty/assets/19412894/d8014fdc-de8f-451d-a494-472df857fb11)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19100-70339&mode=design&t=5z3QOvk8fZV3xVB3-11

### Send an email to notify about password update (Security)

![image](https://github.com/twentyhq/twenty/assets/19412894/e1e8837a-04a9-4fb6-a30b-459153a3be5c)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=20829-56525&mode=design&t=5z3QOvk8fZV3xVB3-11

**Comment by martmull** [comment]
@i-am-chitti would you like to continue with this? There's no problem if you're not interested, but I wanted to check in with you to see if you are.

**Comment by i-am-chitti** [comment]
@martmull Sure. Please assign to me. I'll work on this.

**Comment by charlesBochet** [comment]
Related issue @i-am-chitti https://github.com/twentyhq/twenty/issues/3734

**Comment by Bonapara** [comment]
Hi @i-am-chitti, exactly it should only be present on the second step.

On the second step (sign in with password) Let's replace the footer text with "Forgot password" since the Terms of Service (TOS) and Data Processing Agreement (DPA) will be shown in the previous step where you can choose to either connect with Google or sign up with email.

So: 
First step is "By using Twenty..."
Second step is " Forgot password"

**Comment by i-am-chitti** [comment]
Hey @martmull, here is the PR - https://github.com/twentyhq/twenty/pull/3789
