### ISSUE TITLE
On RecordTable, we can see text behind the checkboxes

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#3670]
## Scope & Context

https://github.com/twentyhq/twenty/assets/71827178/50452a85-cd31-4578-8870-cbfa93e681cd

## Technical inputs

Background should not be transparent.

**Comment by alexandrabrbk** [comment]
Hello! Is it possible to assign this issue to me? I would like to try it! 🙂

**Comment by FelixMalfait** [comment]
Sure @alexandrabrbk thanks!

**Comment by FelixMalfait** [comment]
@alexandrabrbk actually we'll fix it, it isn't as easy as it looks sorry :-(

**Comment by charlesBochet** [comment]
This has been fixed!
