### ISSUE TITLE
Create new activity in DB after cache injection

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#3674]
When the user changes anything into the activity editor, we want to create in DB from what we have in cache + modification.

All fields on activity drawer should trigger this.

TBD with @Bonapara : what do we have to modify to trigger creation ?
```[tasklist]
### Tasks
- [ ] Do not display empty state on task, note or file tab during first fetch.
```

**Comment by lucasbordeau** [comment]
@charlesBochet @Bonapara We settled for triggering creating on any modification.
