### ISSUE TITLE
Set empty state placeholder to singular

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3697]
# Current behavior

If there is no record in the object index, the plural form of the object name is used

![CleanShot 2024-01-30 at 15 13 57](https://github.com/twentyhq/twenty/assets/19412894/80c1cfae-5d85-4544-bef1-5891091faced)

# Desired Behavior

We should display it in singular form.

![CleanShot 2024-01-30 at 15 14 40](https://github.com/twentyhq/twenty/assets/19412894/d272b593-4360-477a-acb8-b60568ba2e5e)

**Comment by alexandrabrbk** [comment]
Hi, do you think I could try working on this issue?

**Comment by lucasbordeau** [comment]
@alexandrabrbk We're already working on it.

**Comment by lucasbordeau** [comment]
Closed by #3703
