### ISSUE TITLE
When scrolling horizontally through the table component, content is overlapping with the checkbox column

### ISSUE THREAD

**Issue by anoopw3bdev** [twentyhq/twenty#3704]
## Bug Description

When scrolling horizontally thorough the tables, the contents are getting overlapped

**Example:** 

Try scrolling through the table horizontally in either people or company page. The content of the table cells will overlap with the checkbox column.

<img width="469" alt="Screenshot 2024-01-30 at 10 32 35 PM" src="https://github.com/twentyhq/twenty/assets/44577841/a2bf52f2-0198-4c4b-9770-42d07edc31c3"> 
<img width="491" alt="Screenshot 2024-01-30 at 10 32 48 PM" src="https://github.com/twentyhq/twenty/assets/44577841/1686d090-b02d-4007-949e-5a0eaef280b6">

## Expected behavior

The content should not overlap

**Comment by Bonapara** [comment]
🙀
