### ISSUE TITLE
[Flexible-Schema] Add an onDelete property to relation decorators

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#3711]
## Scope & Context

Currently, all relations have "ON CASCADE DELETE" by default. This causes some issues for certain objects. Ideally we would like to define this individually for each FK. 
For example, deleting a Favorite row when the associated entity has been deleted is a good thing to delegate to the DB. However we don't want to delete a person if a company has been deleted because a person can be re-attached to another company.

We could have something like this (taking typeorm implementation as an example)
```
  @RelationMetadata({
    type: RelationMetadataType.ONE_TO_MANY,
    objectName: 'messageChannel',
    onDelete: 'CASCADE'
  })
```

ON DELETE SET NULL
ON DELETE RESTRICT
ON DELETE SET DEFAULT
ON DELETE CASCADE

**Comment by FelixMalfait** [comment]
This is an issue for messageParticipants. Today if we delete the contact or workspace memeber, it will delete the messageParticipant which won't be visible in the message thread anymore. We should SET NULL on cascade instead

**Comment by Weiko** [comment]
cc @charlesBochet

**Comment by charlesBochet** [comment]
Let's prioritize this one for the next sprint (we should be able to find some space). I think the technical direction is quite clear:
- add this as an option in metadata
- add this to health check
- add this to health check fix
- add this to sync metadata
