### ISSUE TITLE
Upload button border are too light

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3715]
# Current behavior

In Settings > Profile:

The button border is made of Transparent / Light

![CleanShot 2024-01-31 at 10 54 47](https://github.com/twentyhq/twenty/assets/19412894/5e8d0d23-edf6-47ba-975b-9ed9afac4987)

# Desired Behavior

The border should use Transparent / Medium

![CleanShot 2024-01-31 at 10 51 48](https://github.com/twentyhq/twenty/assets/19412894/9ccab7dd-16bf-4f6e-9363-4cd4604f8fcb)

Ensure that the default border of every secondary button with "Default" accent is transparent medium, not transparent light.

# Figma

![Screenshot 2024-01-31 at 10 53 57](https://github.com/twentyhq/twenty/assets/19412894/29135dcf-ba44-425b-8f8a-14c15dadf4ef)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=3122-142114&mode=design&t=dsODXEtZQcZiflS5-11

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
I can work on this

**Comment by Bonapara** [comment]
Thanks @Kanav-Arora!

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait @Bonapara @charlesBochet 
I really love contributing to Twenty but this need some strict guidelines. It has happened with me for the 4th time ig that people directly raise a PR for an already assigned issue. This is a unprofessional behaviour and mustn't be entertained.
Like I also have my corporate job so I can't compete like who raise the PR first. Please take a look at this. I mean this is waste of time for the person who has partially written the code. Now with the increase in contributors there should be strict guidelines on issue assignment and PR merging. And after few warnings some ban policy can also be introduced.

**Comment by Kanav-Arora** [comment]
This is not a time taking issue but I have wasted my time earlier also with 2 issues. If you remember @FelixMalfait I even pointed it out to you.
