### ISSUE TITLE
Box shadow is cropped / Floating cell appears under next cell

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3718]
# Description

![CleanShot 2024-01-31 at 11 41 50](https://github.com/twentyhq/twenty/assets/19412894/adc38b2f-55ca-4371-9edc-09094efda49a)

The floating cell should appear **above** the underneath cell

**Comment by alexandrabrbk** [comment]
Hi, I would like to work on this issue, is it possible to assign it to me  ?

**Comment by Bonapara** [comment]
more context here: #3220

**Comment by Bonapara** [comment]
@alexandrabrbk, thanks for contributing !

**Comment by charlesBochet** [comment]
I have investigated this one, it's actually not that simple (it has to do with the sticky position). As we move to the right drawer to create new record, should we invest on it @Bonapara?
