### ISSUE TITLE
Avoid showing undefined undefined on show page first load

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3722]
## Bug Description

When we first load a show page, there is a flash of undefined undefined in the top left corner of the show page.

<img width="591" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/660400b4-0979-4949-aa44-f8581eb20d65">

## Expected behavior

Let's put a skeleton loader, what do you think @Bonapara ?

**Comment by jeet1desai** [comment]
Hey @lucasbordeau, Could you please assign it to me, I'd love to do it

**Comment by Bonapara** [comment]
Yes @jeet1desai, thanks! Here's the design:

![Screenshot 2024-01-31 at 18 21 52](https://github.com/twentyhq/twenty/assets/19412894/872db1f5-d243-42b9-b937-1fc2321490be)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5910-72493&mode=design&t=BldR9ZSWSwcVhWo9-11
