### ISSUE TITLE
Type to enter cell edit mode places the cursor before the first character

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3723]
## Bug Description

https://github.com/twentyhq/twenty/assets/26528466/acb4de46-6e7b-4c4f-b44d-12e61c70d697

When we type to enter edit mode on a table cell, we want the text to be written directly.

The problem is that the first character we type stays at the end of the text, because the cursor is placed before the character we entered.

## Expected behavior

We want the cursor to be at the end, after the first character we used to enter edit mode.

See related issue https://github.com/twentyhq/twenty/issues/3724

**Comment by andjimenezuf** [comment]
Hi @lucasbordeau I am also open to work on this issue. Thanks
