### ISSUE TITLE
Place cursor at the end when entering cell edit mode

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3724]
## Scope & Context

On a record table cell.

## Current behavior

When we enter a cell the cursor is at the beginning of the cell.

## Expected behavior

We want the cursor to be placed at the end as it is the default behavior in spreadsheet editors.

**Comment by jeet1desai** [comment]
Hey @lucasbordeau, Could you please assign it to me, I'd love to do it
