### ISSUE TITLE
Documentation for UI Components is broken

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3725]
See: https://docs.twenty.com/contributor/frontend/ui-components/input/image-input

<img width="850" alt="Screenshot 2024-01-31 at 16 24 19" src="https://github.com/twentyhq/twenty/assets/6399865/a14a3420-6a9c-4039-aa51-2a0d424d61d7">

**Comment by anoopw3bdev** [comment]
@FelixMalfait updating sandpack-react to latest version fixed this issue. Will create a PR, can assign to me.

**Comment by FelixMalfait** [comment]
Thanks @anoopw3bdev!
