### ISSUE TITLE
Clear record table cell content when using delete / backspace

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3726]
## Scope & Context

In a record table cell.

## Expected behavior

We want to empty any cell content when using delete / backspace.

Here are the guidelines to complete this feature : 
- Create a new hook `useClearRecordTableCell`
- Call it in `RecordTableCellSoftFocusMode` component in the `useScopedHotkeys([Key.Backspace, Key.Delete]` callback.

To create the `useClearRecordTableCell` hook, you might have to use `generateEmptyFieldValue` and pass the generated value to `usePersistField`, this part is a bit complex so don't hesitate to reach us on our discord.

**Comment by andjimenezuf** [comment]
May I take on this issue?

**Comment by selango1** [comment]
Can I contribute to this issue if its still open?

**Comment by lucasbordeau** [comment]
@selango1 Sure, here's a link to our Discord server if you need help : https://discord.gg/y3peVFBM

**Comment by selango1** [comment]
I wrote the code with the changes, please let me know if I did it right.

**Comment by lucasbordeau** [comment]
@selango1 This seems on the right track, could you send a PR showing the actual changes so we can test it ?

**Comment by lucasbordeau** [comment]
Your assigned to this so please take your time and we'll work better on a PR than a commit.

**Comment by selango1** [comment]
Thank you for your patience, I think I have created a file for the PR. Let me know if that works :)
