### ISSUE TITLE
Add a create new button on relation picker

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3729]
## Scope & Context

Relation picker on a relation field.

## Current behavior

We can select from a list of objects in a relation picker.

## Expected behavior

We want to be able to create an object from a relation picker 

![image](https://github.com/twentyhq/twenty/assets/26528466/5c5a2d8b-8201-4adb-9d26-a6024b4510e2)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=17404-41837&mode=design&t=FgTQBl2iVzooomzb-11

## Tech specs : 

- Extract the relation object's label identifier field id
- Get the field type from this field metadata
- Use the proper inline cell for this field type
- Trigger the creation of an object when exiting this field

It should be the same experience as when we create a new record table row, with the input field taking the focus, you can find it on people or companies tables.

Linked issue : https://github.com/twentyhq/twenty/issues/2965

**Comment by anoopw3bdev** [comment]
Hello @lucasbordeau what is the expected completion date of this feature? I feel like I am taking more time to understand how components are organized and connected each other and I am afraid I might not be able to complete it soon.

**Comment by lucasbordeau** [comment]
@anoopw3bdev There's no deadline right now, are you in our Discord server ?

**Comment by anoopw3bdev** [comment]
Sorry, I missed this thread @lucasbordeau yes I am in twenty Discord. Will try to resolve this in a week.

Thanks for the patience!

**Comment by anoopw3bdev** [comment]
Hi @lucasbordeau / @Bonapara do you have a design on how the UI will look like?

**Comment by Bonapara** [comment]
Hi @anoopw3bdev! Figma is running slowly. Here's the behavior:

https://github.com/twentyhq/twenty/assets/19412894/6ec7b734-06a4-4f64-9319-f100b9a0dcf4

-  The `Add new` button should always be visible.
-  When searching for a company like "Google" and clicking "add new," the company name should be automatically inserted, requiring only the URL input.

# Components

![Screenshot 2024-03-13 at 09 00 12](https://github.com/twentyhq/twenty/assets/19412894/04728e22-f2ec-4b88-9147-e2d9a96b1679)

Figma Links:
-  [Main Design](https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=2979-197197&mode=design&t=75yrmyKfqMepmFVt-11)
-  [Picker Design](https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=17404-41837&mode=design&t=75yrmyKfqMepmFVt-11)

**Comment by anoopw3bdev** [comment]
Thanks a lot @Bonapara!
