### ISSUE TITLE
make-server start command not working in docker installation

### ISSUE THREAD

**Issue by deepaksing** [twentyhq/twenty#373]
In documentation, the command to run the server
![image](https://github.com/twentyhq/twenty/assets/32263182/1a754cee-b791-49bc-8a5b-8c32a64d1f71)

error: **'make-server' is not recognized as an internal or external command,
operable program or batch file.**

reolution: i think the command should be make server-start

**Comment by charlesBochet** [comment]
Thanks for the feedback

I've made a PR here which is fixing it https://github.com/twentyhq/twenty/pull/376

**Comment by charlesBochet** [comment]
Fixed by https://github.com/twentyhq/twenty/pull/376
