### ISSUE TITLE
Add a more granular debug mode

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3733]
## Scope & Context

Debug mode, front and back.

## Current behavior

We have a single environment variable DEBUG_MODE to activate all debug features at the same time.

## Expected behavior

We would like to have an environment variable that could take : 
- all
- recoil
- hotkey_scopes (replace currently hard coded constant)
- apollo_queries
- apollo_logs
- db_pg_graphql
- db_postgres

**Comment by lucasbordeau** [comment]
@Weiko @charlesBochet What would you add as options in the list ?

**Comment by Weiko** [comment]
> @Weiko @charlesBochet What would you add as options in the list ?

For the DB I think we can separate pg_graphql and others yes.
Maybe we can also add the list of active feature flags but not sure if it's really useful as of today 🤔

**Comment by charlesBochet** [comment]
@lucasbordeau hotkey scopes?

**Comment by lucasbordeau** [comment]
@Faisal-imtiyaz123 You might be interested by this one !

**Comment by FelixMalfait** [comment]
Closing as this as been open for a very long-time
