### ISSUE TITLE
Reset Password Form is not in modal

### ISSUE THREAD

**Issue by martmull** [twentyhq/twenty#3734]
![image](https://github.com/twentyhq/twenty/assets/29927851/c0b946a5-f65f-496e-93ab-e853afa0a015)

When connected, the reset password form is not displayed in a modal. It should be

## Technical hints:

**In DefaultLayout:**
See condition:
 `onboardingStatus && onboardingStatus !== OnboardingStatus.Completed`

We should introduce a helper function that compute wether or not set modal mode according to route

**Comment by i-am-chitti** [comment]
While developing, I tried putting this in modal, but had hit blocker. Didn't know this could have been so simple based on route 😅  . Thanks @martmull . I've raised PR for this - https://github.com/twentyhq/twenty/pull/3764

**Comment by martmull** [comment]
@i-am-chitti perfect thank you! Great work
