### ISSUE TITLE
Implement event emitter/listiner

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3736]
As of today we call the `triggerWebhooks` directly in the query runner service.
It would be nice to add an intermediate layer for event management.

See: https://docs.nestjs.com/techniques/events

We should replace `triggerWebhooks` by `eventEmitter.emit` and create a module dedicated to listeners.
One listener will be dedicated to triggering webhooks.
But this will allow us to add additional listeners when we need to implement business-logic after object mutations.

**Comment by jss475** [comment]
Hey @FelixMalfait! Let me know if you want me to change the file structure for the listener. I just made the listener specific for the workspace queries. I can make it more broad if necessary!
