### ISSUE TITLE
Hide the Default/Selected icon from search results

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3748]
# Current behavior

In the icon picker, the default/selected icon is always displayed in the first position, even when I'm searching for another icon.

https://github.com/twentyhq/twenty/assets/19412894/01d08854-bde7-491c-bd34-a9f88c276079

# Desired behavior

Hide the "selected icon" from the search results when something is typed that does not match the selected icon. For example, if the default icon is "box", it should not be shown when typing "Food".

**Comment by jeet1desai** [comment]
Hey @Bonapara, Could you please assign it to me, I'd love to do it

**Comment by Bonapara** [comment]
Done, Thanks @jeet1desai ;)
