### ISSUE TITLE
Bug when creating empty object

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3754]
See video:

https://github.com/twentyhq/twenty/assets/6399865/b15ff157-3c5d-4d39-9ce3-f110a68ad454

Not sure what's going on but we probably implemented something to delete empty records to avoid polluting the workspace, and this doesn't behave as expected?

**Comment by parthiv360** [comment]
Hey @FelixMalfait, can you please elaborate on what is expected in the solution and if nobody is working on this I can pick this up.

**Comment by FelixMalfait** [comment]
Hey thanks for the ping on this. It's probably not an issue anymore, this part has been refactored
