### ISSUE TITLE
Update frontend to show correct view count

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3757]
Followup of https://github.com/twentyhq/twenty/pull/3384 and https://github.com/twentyhq/twenty/issues/2794

The backend work has been completed but we still haven't updated the frontend:
https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/views/components/ViewsDropdownButton.tsx#L140
https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/object-record/record-index/components/RecordIndexTableContainerEffect.tsx#L71

Instead of computing the count on the frontend we should use the totalCount parameter now sent from the backend.

**Comment by charlesBochet** [comment]
@martmull
