### ISSUE TITLE
In development mode, when clicking continue after putting email, no response in showed. 

### ISSUE THREAD

**Issue by adisagar2003** [twentyhq/twenty#3765]
## Bug Description

In development mode, when clicking continue after putting email, no response in showed. 
![image](https://github.com/twentyhq/twenty/assets/69413640/0466f615-5391-476c-975d-a7f8ce1d9cfd)
![error](https://github.com/twentyhq/twenty/assets/69413640/d02d282b-f299-486d-8c03-9b994f6082bd)
There is a post request sent by the button, but the frontend shows no response. 
![image](https://github.com/twentyhq/twenty/assets/69413640/bb2f09b1-ac94-4e92-abe6-d9e8ffe6a317)

## Expected behavior

Just like production build, after clicking continue after putting a valid email, an input for password must be visible. 
![image](https://github.com/twentyhq/twenty/assets/69413640/c55b0be7-a132-49dc-b539-43a23fc234b2)

**Comment by FelixMalfait** [comment]
Thanks for raising this and sorry we didn't reply earlier.
I'm not able to reproduce and can't tell what's wrong based on your screenshots 🤔
Could you show the response of the graphQL queries you have on the network tab?
Also no JS error in the browser console?
