### ISSUE TITLE
Add placeholder to empty task in task list

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3769]
# Current behavior

When creating a task, there is a placeholder in the right panel but not in the task list on the left

![CleanShot 2024-02-02 at 09 59 30](https://github.com/twentyhq/twenty/assets/19412894/c15df3c4-a7f5-4fb9-b8d8-577a9adceb9a)

# Desired Behavior

Display a "Task title" placeholder also on the task list:

![CleanShot 2024-02-02 at 09 57 33](https://github.com/twentyhq/twenty/assets/19412894/f8d181f2-4a1d-4d45-a388-1ee9e6258104)

# Figma 

The font-color of the placeholder should be `light.`

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=9901-34957&mode=design&t=s1GHZupTo8uw8lbB-11

**Comment by pranay911** [comment]
can you please assign this issue to me?

**Comment by Bonapara** [comment]
Done, thanks @pranay911 :)

**Comment by jeet1desai** [comment]
Hey @Bonapara, just a quick question. Once a task is completed without a task title, could we have the task title placeholder struck through or kept in its original format for a neater appearance? Thanks!

**Comment by Bonapara** [comment]
Hi @jeet1desai, good point. You can indeed set the placeholder title to have a strikethrough.
