### ISSUE TITLE
feat: add fix options to workspace health check command

### ISSUE THREAD

**Issue by magrinj** [twentyhq/twenty#3773]
## Scope & Context

We introduce a new `workspace:health-check` command in this PR #3344, the goal of it is to control health of a given workspace.
This command is working fine but we want to add `--fix` option in order to auto-fix common issues.

## Current behavior

We don't have any `--fix` option.

## Expected behavior

We want to add a `--fix` options with multiple kind of fix:
`nullable` -> Should fix all nullability conflicts issues
`type` -> Should fix type mismatch when possible
`default-value` -> Should fix incorrect default value
`target-column-map` -> Should fix inconsistent `targetColumnMap`
`missing-column` -> Happen when `targetColumnMap` is empty

## Technical inputs

We must create `workspaceMigration` for each fix.
```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/3839
- [ ] https://github.com/twentyhq/twenty/issues/3840
- [ ] https://github.com/twentyhq/twenty/issues/3841
- [ ] https://github.com/twentyhq/twenty/issues/3842
- [ ] https://github.com/twentyhq/twenty/issues/3844
- [ ] https://github.com/twentyhq/twenty/issues/3846
```

**Comment by charlesBochet** [comment]
Bravo @magrinj Closing this issue!
