### ISSUE TITLE
Change REST API Base URL

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3776]
Not a big deal but API base URL should probably be https://api.twenty.com/rest/ instead of https://api.twenty.com/

<img width="482" alt="Screenshot 2024-02-02 at 11 52 26" src="https://github.com/twentyhq/twenty/assets/6399865/3b098dba-7c4b-4d1c-9e5b-de386ef1a95b">

And the /rest/ part here wouldn't be bold:
<img width="545" alt="Screenshot 2024-02-02 at 11 53 34" src="https://github.com/twentyhq/twenty/assets/6399865/d81996ac-9833-480e-b430-9b8e1a61c9db">

**Comment by HakSooDev** [comment]
@FelixMalfait 
Hi! 
I like to work on this. Can you assign me?
