### ISSUE TITLE
Fix DeveloperSettings stories

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#3798]
## Scope & Context

Our storybook tests are reporting a broken state on Settings > Developers section
<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/0c45f47b-8ce7-4c7b-9a73-517c09ea4f97">

## Technical inputs

Take a look at files located in `packages/twenty-front/src/pages/settings/developers`. 
Run stories using: 
- `yarn nx storybook:pages:dev twenty-front`

The story should display a functional Developper settings page (same as when you browse the Settings > Developers page on your local frontend)

**Comment by selango1** [comment]
I want to take up this issue, but I have a few questions. Is there a discord group that I can directly reach out to?

**Comment by charlesBochet** [comment]
Thanks @selango1 :)
Feel free to join our Discord here: https://discord.gg/ZdHGRR5d and use the #development channel
