### ISSUE TITLE
Sign up with Magic link

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#380]
Design available here: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=2440-89414&mode=design&t=cWYMj8qsXliMDnzN-0

<img width="1007" alt="Screenshot 2023-07-21 at 14 11 25" src="https://github.com/twentyhq/twenty/assets/6399865/cddfa343-66ec-434b-b207-734794f443ef">

The email a user will receive if he doesn't sign up with Google and has an email server configured / using the cloud version.

![Image](https://github.com/twentyhq/twenty/assets/19412894/b5eec574-6bca-45b0-819f-ff797260acef)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=4162-56741&mode=design&t=SEFgiMdVeuQAfxfM-4

**Comment by abhithory** [comment]
Hi @Bonapara @FelixMalfait  , is this still an issue or is it fixed???

I would like to work on this.

**Comment by Bonapara** [comment]
Hi @abhithory, thank you for your willingness to contribute to these issues! It might be better to start with a "good first issue" as the core team may have a specific implementation idea for this particular issue.
