### ISSUE TITLE
Error: 500 - Email Settings page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3802]
# Description

`Object metadata item "connectedAccount" cannot be found in an array of 16 elements`

![CleanShot 2024-02-05 at 10 15 06](https://github.com/twentyhq/twenty/assets/19412894/0cfd76d8-f919-466b-be53-e31333bf58cf)

# How to reproduce

Just went to the Email settings page

**Comment by charlesBochet** [comment]
@Bonapara closing it, it was because your workspace was missing the email standard objects
