### ISSUE TITLE
Currency type is not implemented in optimistic cache update

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#3806]
## Bug Description

- Go to /companies table page
- filter on a currency field (example ARR)
- update a record in the table
- You should see a red snack bar "Not implemented yet" appearing

## Technical inputs

The error is triggered by our optimistic update of our cache ; we are trying to update the filtered query results based on the update but the Currency field type is not supported yet
Update packages/twenty-front/src/modules/object-record/record-filter/utils/isRecordMatchingFilter.ts to support Currency type

**Comment by anoopw3bdev** [comment]
Hi @charlesBochet I had created a PR for this issue. Could you please assign this issue to me if its okay.

**Comment by FelixMalfait** [comment]
Thanks @anoopw3bdev!
