### ISSUE TITLE
Blocklist: Backend

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#3816]
```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/4746
- [ ] https://github.com/twentyhq/twenty/issues/4747
- [ ] https://github.com/twentyhq/twenty/issues/4748
```

**Comment by FelixMalfait** [comment]
@bosiraphael do you think you could take this on next week when you come back and see this message? We've done most of the work right? Would be nice to close this and include it in the next release!
