### ISSUE TITLE
Improve activity loading UX

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3817]
## Scope & Context

Opening an activity in the right drawer

## Current behavior

It takes some time to load and the activity drawer shows empty fields

## Expected behavior

We want an optimistic behavior.

Should we use skeleton loaders @Bonapara ?

- Check if we can improve loading time or if it's just a matter of displaying a UI loading state, if so then give the issue to the community.

**Comment by Bonapara** [comment]
Do a V1 & contact me to adjust the linear gradient effect as it's hard to prototype

![image](https://github.com/twentyhq/twenty/assets/19412894/d86187d8-6d93-43b0-b3bd-908b79cf3840)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=22292-116857&mode=design&t=nEULyoDTwEUBfZUC-11

**Comment by FelixMalfait** [comment]
@Bonapara closing since we've made quite a lot of progress on that topic since then and the screen isn't fully up-to-date but feel free to re-create a new one
