### ISSUE TITLE
[Timebox] Fix double imports on save from VSCode

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3819]
## Bug Description

VSCode auto-imports and re-order imports via ESLint, it can happen that it imports twice the same thing.

## Expected behavior

We want to avoid this and see if there are known bugs about this : 
- Look for "VSCode double import", "simple-import-sort double imports"

See if VSCode or ESLint is causing this

**Comment by FelixMalfait** [comment]
For a given package we have two eslint config files, one at the root level and one at the package level, with duplicated config. Could be linked to that? Didn't find any know issue online so I'd say it's due to a misconfiguration on our side.

**Comment by lucasbordeau** [comment]
Here are the results of my investigation : 

Root cause : 

When saving too fast multiple times, and when the typescript server first sent the import to be add through the addMissingImports action, then if we save too fast again, the typescript server serves another additional refactor that doubles a random import in the import section.  

It's hard to determine what causes this but it's probably related to a TypeScript server race condition.

Solutions found :

1. We can leave it as is for now as the fix is not trivial
2. We can use organizeImports in VSCode which will fix this but will change our import sort from the eslint plugin we use, and organizeImports has no config, so we cannot just model our eslint config.
3. We can use a PR that fixes this problem with an eslint plugin see https://github.com/import-js/eslint-plugin-import/pull/2269, https://github.com/import-js/eslint-plugin-import/issues/1812 The problem is that this doesn't fix the underlying problem and the TypeScript will still produce duplicate imports.

The best is probably to go for 2. but we'll have to re-order all the imports of the codebase probably, which can introduce nasty bugs and would be hard to test thoroughly.

**Comment by charlesBochet** [comment]
This has been solved by removing our custom rule
