### ISSUE TITLE
ESLint rule: const naming

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3825]
## Scope & Context

Constants naming is inconsistent in the codebase.

We want to enforce this : 
- JS variables should be ALL_CAPS : `export const MY_CONSTANT = 2;`
- There should be one constant per file, file should be PascalCased : `MyConstant.ts`

## Technical inputs

The rule should check that there is only one constant per file and that it is ALL_CAPS. 

Bonus : see if ESLint can also lint file names.

**Comment by gitstart-twenty** [comment]
Hello @lucasbordeau, I have a couple of questions for you:

1. When you refer to constants, are you specifically targeting constants within a `/constants` sub-folder (`**/constants/*.ts`), or should we analyze the code to identify all constants (those using UPPERCASE_CONSTANTS) and relocate them to their respective files in `**/constants/`?

2. Regarding files like `packages/client/src/constants/app.ts`, should we break down everything within the file into separate files, or is it preferable to keep it as is, considering it doesn't utilize the `const` keyword?

**Comment by lucasbordeau** [comment]
Hi,

Yes, we should break down into one file per constant. It would be really great to extract all constants into their separate file too, but you can just focus on implementing this eslint rule for every existing constant file for now.
