### ISSUE TITLE
Update loading images

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#3833]
## Scope & Context

The dots on the + icon pattern are too big

Example:

![CleanShot_2024-02-01_at_09 00 56](https://github.com/twentyhq/twenty/assets/71827178/3af83d46-c2f7-4edd-a0fc-f203fd8d38df)
![CleanShot_2024-02-01_at_09 01 57](https://github.com/twentyhq/twenty/assets/71827178/c8384502-5836-457a-b079-dba145598bdf)

**Comment by jeet1desai** [comment]
Hello @charlesBochet @bosiraphael I can work on that, could you please assign it to me

**Comment by bosiraphael** [comment]
Hello @jeet1desai ! I assigned you the issue. Thank you for wanting to contribute :)
PS: Make sure you export the image from the Figma in the appropriate size (should be 2x I think)
