### ISSUE TITLE
Settings/Objects/Object Detail - Display banner if Record identifier has not been set

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#3837]
![Image](https://github.com/twentyhq/twenty/assets/3098428/fcd5a0e7-56e2-410a-9992-69441600e187)

**Comment by FelixMalfait** [comment]
Not sure we should implement this now. Are we setting records identifier for standard objects? We should. And for custom objects we still create a `name` column so we should set it a record identifier as well no? That wouldn't leave anything without a record identifier

**Comment by thaisguigon** [comment]
@FelixMalfait 

> Are we setting records identifier for standard objects? We should.

Yes, we always set a Record identifier for Standard objects. This would be for Custom objects only.

> And for custom objects we still create a `name` column so we should set it a record identifier as well no? That wouldn't leave anything without a record identifier

Indeed a "Name" column is always created for Custom objects and set as Record identifier, but I was under the impression we might not enforce the "Name" column in the future? @Bonapara

**Comment by Bonapara** [comment]
You're right! Let's postpone this one for now
