### ISSUE TITLE
Record card position in board

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#3848]
## Context

When the user drag and drops a card in the board, the cards are immediately re-sorted by "createdAt" property by default, instead of keeping the card where the user dropped it.

A new property `recordPosition` has been introduced in the backend. This issue aims to use this property on the frontend in order to keep the order chosen by the user.

**Comment by charlesBochet** [comment]
More technical input:
- [nothing to do] We have introduced recordPosition on non system standard object: company, person, opportunity. When we create a new custom object, the recordPosition is also created. So all objects that can be used for table or board should have a recordPosition
- [nothing to do] RecordPosition should be automatically fetched by the front autogenerated query
- Update dev seed and demo seed to fill record positions on companies, opportunities, person: 0, 1, 2, 3, ...
- Apply sortBy recordPosition 'asc' on recordTable and new recordBoard as last sort (if there is no sort, we should still apply this sort, if there is a sort, we should apply it as secondary sort)
- On Drop on the recordboard, compute the recordPosition to be the average of the card before and after and persist it. The RecordBoard, already has the record update mutation available, it should be straightforward
