### ISSUE TITLE
Add integrations tab in Settings

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3865]
Our app was finally approved on Zapier! https://zapier.com/apps/twenty/integrations

Let's add a new page in Settings to advertise it 🤩

Link to main Zapier app: https://zapier.com/apps/twenty
Link to sub-integrations: https://zapier.com/apps/twenty/integrations/{...tally...}
Link to Windmill: https://www.windmill.dev/

![Settings - Integrations store V2 (1)](https://github.com/twentyhq/twenty/assets/6399865/07825c0c-5916-4041-bbff-e3b8ddbbb3a8)

Initial Figma page: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19581-11218&mode=design&t=OL1cvUsqcqLaPYOQ-0
(as you can see I updated the text  - but don't have edit rights to the original Figma)

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait 
I can work on this. Could you please assign me this?
And may I know the timeline of this issue?

**Comment by Kanav-Arora** [comment]
> Of course @Kanav-Arora thanks! I'd say a week if that's doable for you?

Yeah sure! I'll try to do it beforehand

**Comment by Kanav-Arora** [comment]
@FelixMalfait for this issue which page do I have to design? Like I have added a path and a root page but are these integrations constant or are we fetching them dynamically? In this figma design there are 3 different pages
