### ISSUE TITLE
LinkedIn links with unicode are truncated when displayed

### ISSUE THREAD

**Issue by majorproblem** [twentyhq/twenty#3873]
## Bug Description

A LinkedIn button in the People screen with unicode characters in the URL gets truncated at that character.

Example:
A LinkedIn URL such as `https://www.linkedin.com/in/håkan-fisk` is displayed as a button with only the character `h` in the LinkedIn column

## Expected behavior

The button in the LinkedIn column should in this case display `håkan-fisk`

**Comment by FelixMalfait** [comment]
Thanks for the report. I can confirm I was able to reproduce the bug. 

https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/ui/navigation/link/components/SocialLink.tsx#L39


https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/ui/field/display/components/URLDisplay.tsx#L28

Related: wrong assumption that a URL cannot contain special characters seems to be also made here: https://github.com/twentyhq/twenty/blob/b0b033aec9fed61ddefd31b5f21bb7b7d2464571/packages/twenty-front/src/utils/is-url.ts#L6

**Comment by zvolcsey** [comment]
@FelixMalfait Hi! I modified the regex.
```SocialLink.ts``` - ```/(?:https?:\/\/)?(?:www.)?linkedin.com\/(?:in|company)\/(.*)/``` - (allow any chars) OR
```SocialLink.ts``` - ```/(?:https?:\/\/)?(?:www.)?linkedin.com\/(?:in|company)\/([-a-zA-Z0-9@:%_+.~#?&//=å]*)/``` - (add just å char)
The button displays ```håkan-fisk``` in each case.

https://github.com/twentyhq/twenty/assets/41576384/444a6f7b-69b2-4ca1-a2f2-546081aa5a49

**Comment by FelixMalfait** [comment]
Great @zvolcsey thanks! I'd go with `/(?:https?:\/\/)?(?:www.)?linkedin.com\/(?:in|company)\/(.*)/` 
Also change checkUrlType?
Would be great if you raise a PR!

**Comment by zvolcsey** [comment]
@FelixMalfait Your welcome!

First I just changed the ```SocialLink.tsx``` and it worked fine. I also changed the ```checkURLType``` function now. This is the first check and it can return a proper linkedin type. It worked well on the people screen.

You mentioned 
https://github.com/twentyhq/twenty/blob/b0b033aec9fed61ddefd31b5f21bb7b7d2464571/packages/twenty-front/src/utils/is-url.ts#L6
but I could not find this function in the ```URLDisplay.tsx``` and in the ```SocialLinks.tsx```. Should I also change this regex? The ```SocialLink``` component displays the ```håkan-fisk``` username well even without it.

**Comment by FelixMalfait** [comment]
Yes it seems to be used in a single test only so it doesn't really matter! https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/utils/__tests__/is-url.test.ts#L21

**Comment by majorproblem** [comment]
I have not had a chance to try this but I wanted to add that I have seen the same behavior with names such as "Matías" (notice that there is an _accent aigu_ on the letter "I") and others like "Mårten" or "Sörvik". Just so the fix is not limited to "håkan-fisk" but to all URLs with in essence any diacritical marks

**Comment by FelixMalfait** [comment]
Yes that should work with @zvolcsey's fix!
