### ISSUE TITLE
Update empty state when applying filters

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3877]
I feel like this message is a bit misleading because I had already added my first person.
We should display something else when filters have been set.

<img width="552" alt="Screenshot 2024-02-07 at 20 18 53" src="https://github.com/twentyhq/twenty/assets/6399865/1b2cec03-6172-4f73-b1c3-6b298aa559c2">

cc @Bonapara fyi

**Comment by Kanav-Arora** [comment]
Hi @Bonapara @FelixMalfait 
I'm working on issue for filters, so I have bit knowledge, we can get the selectedFilters from `useFilters` api and on click of create person we can check if selectedFilters have an email filter. If it has we can pass its value as prop to create Person component for email fields default value.

How it sounds?

**Comment by Bonapara** [comment]
@Kanav-Arora, that's a great idea! I'm just wondering how this would work with field validation. For example, you can filter emails by domain name like `google.com`. However, if there's a validation for email validity on the email field, `google.com` wouldn't be recognized as a valid email.

**Comment by Kanav-Arora** [comment]
There's no validation on email filter chip. So I think the approach would be to like
If email contains @ like "kanav@gmail.com" we can move to add person page but if email fields doesn't contains @ like "yahoo.com" we can move to person page without email prop. 

I don't know if this is a great idea

**Comment by Bonapara** [comment]
The email validation has not been implemented yet indeed. In the future, we plan to introduce a side panel for creating records. With this feature, you will be able to pass the email params of the filters, such as @example.com, and the validation will only occur when you click on "create".

![image](https://github.com/twentyhq/twenty/assets/19412894/49d61f3b-7dcc-4c90-a8c0-b731f751bd51)

**Comment by Kanav-Arora** [comment]
Oh great!
So how can we proceed for this issue?

**Comment by Bonapara** [comment]
@Kanav-Arora, I discussed this with Charles and we believe we can migrate to the side panel ASAP. I will handle the design and the issue creation. Meanwhile, you can update the wording to match the one in the second screenshot and maintain the current behavior when clicking on "Create Person"!
