### ISSUE TITLE
Search a person by email

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3878]
Currently we can only search by first name / last name on the command search bar. 
We would also like to be able to search by email.

Probably blocked by #3298

**Comment by rostaklein** [comment]
Hey hey :) Just saw this issue and felt like exploring the project through this a bit. I just made a PR https://github.com/twentyhq/twenty/pull/3997 dont know much the relation to https://github.com/twentyhq/twenty/issues/3298 though. Let me know if the PR i created is really blocked by the mentioned issue.
