### ISSUE TITLE
Enable floating input for record name when creating Kanban view records

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3880]
# Current Behavior

Company name defaults as opportunity name.
Company relation doesn't seem to be visible by default.

# Desired Behavior

1. Display the company field type by default. 
2. Introduce an editable, pre-filled floating input for the name.

![image](https://github.com/twentyhq/twenty/assets/19412894/83acadca-e4be-4594-948c-9922abfbc71e)

**Comment by Mishra-Pravin** [comment]
Hey @Bonapara, I am working on it.

**Comment by Bonapara** [comment]
Thanks @mishra-Pravin! Just assigned you

--- original message ---
On February 8, 2024 at 1:49 PM GMT+1 ***@***.*** wrote:



Hey @Bonapara, I am working on it.

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you were mentioned.Message ID: ***@***.***>
--- end of original message ---

**Comment by Kanav-Arora** [comment]
Hi @Mishra-Pravin 
Can you cover below issue in this? It's related to opportunity board and the first attempt was not good so it was closed.
https://github.com/twentyhq/twenty/issues/3493

If you want to discuss anything feel free to ping in the discord server.

**Comment by Kanav-Arora** [comment]
@Bonapara 
Please assign #3493 issue to @Mishra-Pravin to avoid any confusions

**Comment by Bonapara** [comment]
Hi @Kanav-Arora, cannot assign @Mishra-Pravin on #3493 as he didn't comment

**Comment by Kanav-Arora** [comment]
Oh sorry @Bonapara I forgot
@Mishra-Pravin please drop a comment in that issue just to avoid multiple PRs for same issue.

**Comment by FelixMalfait** [comment]
Hey @Mishra-Pravin should we unassign you? Thanks

**Comment by Bonapara** [comment]
@Mishra-Pravin closing this issue as deprecated. Replaced by #4484
