### ISSUE TITLE
Add a shortcut to sort/filer from column

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3886]
In Notion it's possible to click on a column to filter/sort. This would make the feature a little bit more discoverable (I had this feedback a few times during customer calls where people didn't see the top right sort/filter buttons).

Should be relatively straightforward to implement I guess.

<img width="224" alt="Screenshot 2024-02-08 at 16 05 01" src="https://github.com/twentyhq/twenty/assets/6399865/55c82f42-d490-4ecc-adfb-124841b60deb">

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait so you mean clicking on column header?

**Comment by FelixMalfait** [comment]
Yes @Kanav-Arora exactly

cc @Bonapara fyi

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait @Bonapara 
I can work on this

**Comment by Bonapara** [comment]
Thanks @Kanav-Arora 🙏

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
What's the possible timeline for this?

**Comment by Bonapara** [comment]
You mean to implement the feature @Kanav-Arora? Is a week enough for you?

**Comment by Kanav-Arora** [comment]
Two days are enough 😆 . It was tagged hours but the components have useState which needs to be replaced by recoil state, that's why I asked.

**Comment by Bonapara** [comment]
Perfect ;)
