### ISSUE TITLE
Utilize product within Openshift

### ISSUE THREAD

**Issue by gil0109** [twentyhq/twenty#3891]
Currently the Docker file assumes write access to update js file. 

Within Openshift environment this causes the following erro:

Generating env-config.js file from runtime environment variables...
rm: can't remove './build/env-config.js': Permission denied
./scripts/inject-runtime-env.sh: line 8: can't create ./build/env-config.js: Permission denied

Can you change to run the dockerfile as user? or have a volume mount for files that require modification? Or use environment variables instead?

https://developers.redhat.com/articles/2023/03/23/10-tips-writing-secure-maintainable-dockerfiles#10_tips_and_best_practices_for_dockerfiles

**Comment by FelixMalfait** [comment]
Hey Karim, good point. We need to improve the self-hosting experience, this hasn't been a top priority yet as we are still focused on feature development.

CC @charlesBochet assigning you

**Comment by charlesBochet** [comment]
@gil0109 We do it for our twenty-postgres container here: packages/twenty-docker/prod/twenty-postgres/Dockerfile but we don't for our twenty-server and twenty-front containers.

If you feel confortable, it would be great to update these two so it follows the same pattern

**Comment by gil0109** [comment]
There seems to be more work needed with the twenty-server as well and I don't think I have the skillz.

For Front-End: I am thinking that there may need to be a PV created, a read/write area for just the files that need to be updated.
--> I just copied the contents of the build folder to a PV.  It started but I think that may be a security issue. 

For Server:  

I am wondering if there is script needed that checks if the DB exists and isn't initialized, and then initialize it.
When I run the  yarn nx database:init twenty-server command in the twenty-server pod, i get the following error:
 >  NX   EACCES: permission denied, open '/app/.nx/cache/d/daemon.log'

**Comment by FelixMalfait** [comment]
Will by fixed by https://github.com/twentyhq/twenty/issues/5340
