### ISSUE TITLE
Add ability to create an other activity from the open activity drawer

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3895]
## Scope & Context

In activity right drawer

## Current behavior

If we want to add another activity after creating or modifying an existing one, we have to exit the right drawer, click on +, then click on "task" (or note).

## Expected behavior

We could have a + new task in the right drawer ? @Bonapara

**Comment by Bonapara** [comment]
We can add a "+" buttons with the actions then @lucasbordeau 

![CleanShot 2024-02-09 at 14 19 34](https://github.com/twentyhq/twenty/assets/19412894/65478bd0-14f6-4ea9-b0a3-a5c0fcb8bc61)

**Comment by jeet1desai** [comment]
@Bonapara @lucasbordeau could you please assign it to me, I'd love to do it.

**Comment by Bonapara** [comment]
Done, Thanks @jeet1desai!
