### ISSUE TITLE
Remove lodash.debounce and use `use-debounce` instead.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3896]
## Scope & Context

Everywhere lodash.debounce is used in `twenty-front` package.

## Technical inputs

Due to re-render not being handled properly in some parts of the app, it can break lodash.debounce and make it useless.

Lodash.debounce is a naïve implementation that is not specific to the reactive world of React, we want to use something specifically designed for React : https://www.npmjs.com/package/use-debounce

**Comment by manya706** [comment]
@lucasbordeau Please assign this issue to me

**Comment by FelixMalfait** [comment]
Thanks @manya706
