### ISSUE TITLE
Implement the dark mode version of empty states

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3898]
# Current Behavior

The empty state contrasts too strongly in dark mode.

![CleanShot 2024-02-09 at 15 10 39](https://github.com/twentyhq/twenty/assets/19412894/cd3a761c-e4b2-4d14-9a65-d2d4f2e3fa08)

# Desired Behavior

Implement the dark mode version of empty states:

![CleanShot 2024-02-09 at 15 09 24](https://github.com/twentyhq/twenty/assets/19412894/7bb95788-0ed0-4f37-a49f-e6d84352d35b)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19450-97860&mode=design&t=ZX0lIIYB8eSNRZZ4-11

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
I can work on this

**Comment by Kanav-Arora** [comment]
Hi @jeet1desai 
Its mentioned in the guidelines and I have been neglecting this from the past 2-3 times. I usually help peer contributors but I don't want to entertain this kind off behaviour. Raising PRs to others issue or to an unassigned issue shows the indiscipline. This is not a race of making changes and raising PRs, if you are interested you could have asked and I would have stepped down.

@Bonapara
I have pointed out this to you several times and I don't like to act like this but I like to work in a discipline manner. I don't interfere in others work and expect same from others. I mean what's the point of assigning the issue if some guy is gonna jump into any issue. Can you please look into it?

**Comment by Bonapara** [comment]
Hi @jeet1desai, @Kanav-Arora is right on this one. Please make sure to check if an issue has been assigned before picking it up! You're making great contributions and I would love to assign you on your own issues when you're interested and don't make you lose your time!

Regarding this issue, as mentioned in the contributors read-me, @Kanav-Arora you still have a week to complete this one and we'll merge yours as you've been assigned to it.

@jeet1desai please also have a look to the contributors read-me!

**Comment by jeet1desai** [comment]
Hey @Kanav-Arora and @Bonapara,

When I created the pull request, I noticed that the issue wasn't assigned to anyone and isn't right now. I realize now that it was my oversight, and I should have either asked or waited for an assignee. I'll be careful next time.

As @Kanav-Arora messaged first, @Bonapara, you can assign it to him.

Thanks!

**Comment by Bonapara** [comment]
@jeet1desai @Kanav-Arora nicely said we can merge your PR so you won't lose your work this time! Thanks to you both!
