### ISSUE TITLE
Create new field type JSON

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3900]
It would be handy to be able to create JSON field type (jsonb in database).
Search for `FieldMetadataType.DATE_TIME` for an example of another field type implemented across the codebase. (FieldMetadataType.DateTime on frontend)

It's a request we've received from a user. Could be useful for some standard objects too (I know we almost did it for emails/connectedAccount, I'm pretty sure the need will come back).

**Comment by Bonapara** [comment]
# Design 

Use the `LongText Floating input` to display the JSON from a front-end perspective:

![image](https://github.com/twentyhq/twenty/assets/19412894/7e2484ed-e1c3-49a3-8a25-9ae5aa86094e)

### Figma 

![image](https://github.com/twentyhq/twenty/assets/19412894/be6e3f1e-285b-425c-a383-940c3a08b746)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=3007-69739&mode=design&t=Y37fjrXMoxHDcc3A-11

**Comment by FelixMalfait** [comment]
Note the first part of this task is now complete. I've done a PR for the backend side: https://github.com/twentyhq/twenty/pull/4566

But someone still needs to do the frontend side, letting people create new custom JSON field type, having a display component like in the screen above, etc.
