### ISSUE TITLE
Add a single command to start server and frontend

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3904]
Saw this in /activepieces Github project:

```
> cross-env-shell FORCE_COLOR=true concurrently -n "GUI,API,ENG,PCS" -c "bgBlue.bold,bgGreen.bold,bgRed.bold,bgYellow.bold" "npm:serve:frontend" "npm:serve:backend" "npm:serve:engine" "npm:serve:pieces"
```

<img width="346" alt="Screenshot 2024-02-09 at 18 07 45" src="https://github.com/twentyhq/twenty/assets/6399865/4fedb5aa-cc11-4b25-ba5b-4a551072acb8">

I feel like it could be handy to have a single command to run backend/frontend at the same time too? 
We could call it `yarn start` (add to package.json)

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait 
I can look into this
