### ISSUE TITLE
Improper behavior when pressing "Enter" in the password step of the onboarding flow

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3910]
# Current behavior

In the password entry step, pressing `Enter` with a weak password resets to the email input step without any alert, causing confusion.

https://github.com/twentyhq/twenty/assets/19412894/1e404edb-31dd-42b4-bcc2-9f2e27ec211b

# Expected behavior

Pressing `Enter` should mimic the `Continue` button behavior, displaying an alert for weak passwords. 

The `Enter` shortcut should work as `Continue` at every step of the onboarding process.

**Comment by Anchit1909** [comment]
Hey @Bonapara, I would like to work on this. Could you please assign this issue to me?

**Comment by tusharwebd** [comment]
Hi @Bonapara! Is the issue assigned to anyone? I see @Anchit1909 is interested to work on this as well. Let me know if I can pick this up. Thanks!

**Comment by Bonapara** [comment]
Hi @Anchit1909, just assigned you if you are still interested! If not, will assign @tusharwebd. Thank you both for contributing!

**Comment by Bonapara** [comment]
@tusharwebd, you might be interested by this one? #3908

**Comment by Anchit1909** [comment]
Hey @Bonapara , I am going to unassign myself from this issue because I'm experiencing some problems with my setup. I contributed 2 months ago, and it was working well at that time. However, I think due to recent changes, the server is consuming lots of memory, which is causing the issue. So, I will need some time to figure this out. Sorry for the inconvenience.

**Comment by Bonapara** [comment]
No worries @Anchit1909, thanks for giving it a try :) @tusharwebd are you still interested by this one too?

**Comment by charlesBochet** [comment]
I have also noticed an issue with hotkey scope recently. Sometimes on app.twenty.com, I start typing a password and it no longer works
