### ISSUE TITLE
In settings I should be able to press "enter" instead of clicking "save"

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3928]
When I create a webhook or an API key, I would like to be able to press "enter" to move to the next step instead of having to use the mouse.

<img width="554" alt="Screenshot 2024-02-13 at 12 15 14" src="https://github.com/twentyhq/twenty/assets/6399865/dbfd76d9-3f0f-41e4-b108-6b656249c4c6">

<img width="560" alt="Screenshot 2024-02-13 at 12 15 25" src="https://github.com/twentyhq/twenty/assets/6399865/f1acad54-33b0-4a6d-adb7-b8f701edbd4f">

There's also the issue here - although it's a bit more dangerous since we have a multi-line text field and that we can't erase an object that's been created. I still think we should implement it here too for consistency.

<img width="553" alt="Screenshot 2024-02-13 at 12 14 22" src="https://github.com/twentyhq/twenty/assets/6399865/ec46a7ad-7eca-408d-9bd5-c9fb4baa43b6">

**Comment by jeet1desai** [comment]
Hello @FelixMalfait, 

Is this what we can do? In a multi-text field, when pressing  `shift+enter`  it moves to a new line, and only pressing `enter ` will submit the form.

**Comment by Jonathanlemon** [comment]
Hi @FelixMalfait I would like to tackle this issue as my first ever issue on an OSS project. Would I be able to work on this?

**Comment by FelixMalfait** [comment]
Hey @Jonathanlemon sure thank you! I believe there's already an api for this, something like "onEnter" on our input fields, so you should probably add that to the 4 input fields (let's not add it to the textarea, that would be confusing. While it's true that people should press shift+enter for new lines, I think it's safer not to enable it here)

@jeet1desai if you don't minding letting Jonathan give it a try since it's his first issue :)

**Comment by jeet1desai** [comment]
Sure @FelixMalfait 

@Jonathanlemon let me know if you need any help, happy to help

**Comment by Jonathanlemon** [comment]
Hi @FelixMalfait @jeet1desai , I have implemented the changes that I believe will fix the issue. However, this is my first Open Source project I've ever worked on and am wondering how to go about pushing my changes and issuing a PR. What is the standard procedure for me to go forward with these changes?
