### ISSUE TITLE
Enable Attachments on Custom Objects

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3942]
As of today it's is not possible to attach a file to a custom object.

<img width="725" alt="Screenshot 2024-02-13 at 17 19 34" src="https://github.com/twentyhq/twenty/assets/6399865/d0d1e9c8-7bf6-4cd9-8037-a41a95bc72c8">

This is probably similar to what we've done with activityTargets already, we'll need to create the foreign key and column.

**Comment by charlesBochet** [comment]
Only on new custom object
