### ISSUE TITLE
Enable Sync Metadata command on Custom Objects

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3943]
We've worked on a Sync Metadata command to make it easier to evolve a standard object. 
So for example when a new column is added on a standard object, then the command will point out the difference an automatically run a migration to fix things.

For standard objects, there are also a few key requirements: we create a relation with activityTarget, with attachments, we create createdAt/updatedAt/position. These requirements might change in the future so we also need a way to evolve them through the sync metadata command.

**Comment by charlesBochet** [comment]
@magrinj I think this one is duplicated from: #4004
