### ISSUE TITLE
Create a ActivationStatus in core.workspace and use it in front to redirect properly

### ISSUE THREAD

**Issue by martmull** [twentyhq/twenty#3959]
Currently, we use some artefact to infer if a workspace schema is created or not. This occurs some useless redirections that impact front performances. We should have a computed field in workspace entity that gives the information wether a workspace has a schema or not, and use that field in the front

**Comment by charlesBochet** [comment]
@FelixMalfait @Bonapara  I'm not fully convince by activationStatus = 'active' | 'inactive'. I'm mixed between it actually being an 'onboardingStatus': 'creation_pending' | 'completed' and it being a 'schemaStatus' = 'pending' | 'created' | 'hybernated'
I think it's fine as we don't plan to actually create this field in database and compute it on the fly but we could use some product vision input to clarify this, it will help build a better code logic!

**Comment by FelixMalfait** [comment]
@charlesBochet I agree it's not ideal but not a big deal since this is code-only and not db-level. I'm fine with any option. Could be creationStatus too. This will probably evolve in any case!
