### ISSUE TITLE
New User guide styling

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3960]
# Current behavior

We have completed the initial version of the user guide, but it is not yet available online.

![Screenshot 2024-02-14 at 10 41 40](https://github.com/twentyhq/twenty/assets/19412894/0694fd02-4574-49d5-923b-aafb3efafc6c)

# Desired behavior

We aim to enhance its design before online publication:

![image](https://github.com/twentyhq/twenty/assets/19412894/2dd55a5d-81c4-41bf-9a6e-6a37140103e5)

https://www.figma.com/file/aNpCjwN9wg2DqLWAHPS0ll/%F0%9F%8C%8D-Website-%26-Marketing?type=design&node-id=252-14685&mode=design&t=XF47MemVcHVfJEtr-11

For V1, don't implement the breadcrumb and Section pages. Create the styles for the Inter font.

![Screenshot 2024-02-14 at 11 04 47](https://github.com/twentyhq/twenty/assets/19412894/12520e51-3445-483d-b4da-1533fb79c84c)

We only use the 'Mobile' font size for the Gabarito font. This ensures titles and fonts don't appear oversized, even on desktop.

### Effects

Apply smooth transitions using Framer Motion. Use the "Present" view to preview the animations in Figma

https://github.com/twentyhq/twenty/assets/19412894/b5fed9a0-9db6-47e8-89f6-6857c6087ecb

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
I can work on this

**Comment by Bonapara** [comment]
Thanks so much @Kanav-Arora !

**Comment by Bonapara** [comment]
@Kanav-Arora can @manya706 help you?

**Comment by Kanav-Arora** [comment]
Hi @Bonapara
Sure

**Comment by Bonapara** [comment]
Amazing, thanks to you both!

**Comment by Bonapara** [comment]
@Kanav-Arora and @manya706, I just realized that we need to add a few more things to make it responsive.

Specifically, we need:

-  A breadcrumb at the top
-  Additional navigation pages

Here is the updated design:

### Navigation pages

![image](https://github.com/twentyhq/twenty/assets/19412894/1b11d1dd-cf83-440f-b923-b9a3b038f17f)

![image](https://github.com/twentyhq/twenty/assets/19412894/9028164b-969a-44dc-b9d5-786071794738)


### Breadcrumb

![CleanShot 2024-02-14 at 16 39 30](https://github.com/twentyhq/twenty/assets/19412894/409d1cb3-52c1-411a-ae08-9275319c5ef7)
![CleanShot 2024-02-14 at 16 44 04](https://github.com/twentyhq/twenty/assets/19412894/529c0bc8-283e-4d9b-a37f-8028d07d9eb8)

(Mobile = short breadcrumb)


Please ask me if you have any questions about the behaviors!

**Comment by Kanav-Arora** [comment]
@Bonapara 
I am working on twenty-website package for the first time I have a doubt that currently there's no route being rendered in the entrypoint. So am I missing something like there are multiple pages but currently nopage is being rendered so which package is currently hosted on twenty.com?
<img width="1440" alt="Screenshot 2024-02-14 at 10 05 24 PM" src="https://github.com/twentyhq/twenty/assets/62852363/c9141708-557f-44f2-86fe-bfdbaace4ef1">
