### ISSUE TITLE
Notes relation field should be aligned on left

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3961]
# Current behavior

The relation field is centered

![CleanShot 2024-02-14 at 11 30 01](https://github.com/twentyhq/twenty/assets/19412894/3f49adc5-b7fc-4aa0-baa9-0d1ba2d844d1)

# Desired Behavior

The relations should be aligned on the left side

![Screenshot 2024-02-14 at 11 30 56](https://github.com/twentyhq/twenty/assets/19412894/eb5e5636-8a13-4dba-ad4b-dd8520c64b9f)

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
Raising a PR on this
