### ISSUE TITLE
Remove the boxes around fields on shows and side panel

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3963]
# Current Behavior

There are some boxes around the fields, which take up unnecessary space:

![CleanShot 2024-02-14 at 12 09 16](https://github.com/twentyhq/twenty/assets/19412894/710f7159-65f8-4266-b2b6-1a11de3dea88)

![CleanShot 2024-02-14 at 12 11 05](https://github.com/twentyhq/twenty/assets/19412894/e798ff66-21a1-4d2d-ab5e-ef0975de792e)

# Desired Behavior

We want to remove these boxes and introduce vertical separators for the show's information panel:

![image](https://github.com/twentyhq/twenty/assets/19412894/4774bd52-c420-4d71-842a-cc3e23b2ecb6)

On the side panel, we simply want to remove the border and unnecessary padding:

![image](https://github.com/twentyhq/twenty/assets/19412894/cde7fc41-c985-49ad-a7de-13a4c01b8687)

Make sure to keep the actual behavior for the header and record hover:

https://github.com/twentyhq/twenty/assets/19412894/2a14ea07-7015-473e-a941-10c8d6e28612

### Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=22955-71338&mode=design&t=l7uX9xQSVZm5ArDW-11

**Comment by jeet1desai** [comment]
Hey @Bonapara can I take this? I have worked on this befere.

**Comment by Bonapara** [comment]
@jeet1desai, Yes thanks a lot!

**Comment by jeet1desai** [comment]
Hello @Bonapara, what should be the icon when there is no record?

![image](https://github.com/twentyhq/twenty/assets/52026385/e600500c-c295-4d38-a528-02cd93bdeae9)

**Comment by Bonapara** [comment]
Hi @jeet1desai, thanks for the question!

When there is no record, we should use the current display, which includes an icon representing the object:

![image](https://github.com/twentyhq/twenty/assets/19412894/c4f93e63-8e8b-40a2-aa6f-1f5de5475b2d)
