### ISSUE TITLE
Adjusted Sidebar menu design

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3969]
# Current behavior

- The sidebar items font-weight is regular
- The spacing between the workspace name and the first section is 32px
- (In both the app and settings)

App:

![CleanShot 2024-02-14 at 14 59 10](https://github.com/twentyhq/twenty/assets/19412894/877e8e8f-ade1-4776-9595-f6193cae191c)

Settings:

![CleanShot 2024-02-14 at 14 59 55](https://github.com/twentyhq/twenty/assets/19412894/1d890929-5b3c-4fd2-afe9-24a9d8c6ff51)

# Desired Behavior

- We want to switch the sidebar menu item font-weight from `Regular` to `Medium` (For both the app and settings)
- We want to change the **app sidebar** spacing between the workspace name and first section to 12px
- Update the `settings icons` to match the screenshot/design while you're at it 🙌 

App:
![image](https://github.com/twentyhq/twenty/assets/19412894/fd630963-09e4-430b-8f20-b637744be081)

Settings:
![image](https://github.com/twentyhq/twenty/assets/19412894/13e82719-c32a-4e42-82b6-a0a052f3fdab)

# Figma

Components:
![Screenshot 2024-02-14 at 15 15 52](https://github.com/twentyhq/twenty/assets/19412894/d7a41c83-1d2c-49f0-b9f2-b98260a1b77f)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=115-6252&mode=design&t=TA6lDS1qNLARKYoW-11

App:
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=568-41657&mode=design&t=TA6lDS1qNLARKYoW-11

Settings:
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19581-11218&mode=design&t=TA6lDS1qNLARKYoW-11

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
Raising a PR for this
