### ISSUE TITLE
Update the "label" font style

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3970]
# Current behavior

Labels are transformed to uppercase

![CleanShot 2024-02-14 at 15 21 08](https://github.com/twentyhq/twenty/assets/19412894/28e0bb01-4d17-4587-a9c4-10da195612d0)

# Desired Behavior

We want the labels to remain in their normal form (No uppercase anymore)
Update the label style everywhere, for both 11px & 9px labels.

![image](https://github.com/twentyhq/twenty/assets/19412894/6d578649-b5ce-4eaf-bfa9-71ae3d56adff)

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
Raising PR for this
