### ISSUE TITLE
Sidebar is cropping calendar picker on shows

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3988]
# Current behavior

The calendar is cropped by the sidebar on shows:

![CleanShot 2024-02-15 at 10 34 35](https://github.com/twentyhq/twenty/assets/19412894/72687c1d-bd9e-4ebe-8fcc-064493815c26)

# Desired Behavior

... ;)

**Comment by jeet1desai** [comment]
Link: #3569

**Comment by Bonapara** [comment]
Well noticed, @jeet1desai! I'll close it as "duplicate" Thanks

**Comment by Bonapara** [comment]
Well noticed, @jeet1desai! I will close it as a duplicate.
