### ISSUE TITLE
Bug with text editor when creating a note on detail page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3998]
# Description

On any detail page:

1. When creating a note, the user is prevented from inserting content without closing and reopening the note.
2. When closing and reopening the note, the content of the note appears centered instead of at the top.

# How to reproduce

On app.twenty.com, go to any detail page and create a note

# Video

SD
https://github.com/twentyhq/twenty/assets/19412894/184446f8-9679-4ebc-83a7-6aa4063f5a56

HD
https://0x0.st/HnbR.02.mov

**Comment by jeet1desai** [comment]
Hey @Bonapara just want to mention that the video is not properly uploaded.

**Comment by Bonapara** [comment]
Hi @jeet1desai, Yes it won't upload, trying to solve this!

**Comment by jeet1desai** [comment]
Hey @Bonapara could you please assign it to me!

**Comment by Bonapara** [comment]
Sure, thanks !
