### ISSUE TITLE
Inconsistency between DB constraints and API on messageParticipants

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4010]
In `getTimelineThreadsFromPersonId` we make the assumption that  every message has a `messageParticipant` with `role=from` (i.e. every message has a sender).

This is not consistant with DB Constraints.

I don't see a nice path to resolve this.
The 3 options I see are:
(1) migrate the from participants to columns in `message` table (create new columns in message table: fromHandle, fromDisplayName, fromPersonId, fromWorkspaceMemberId)
(2) add a column fromParticipantId that is not nullable on message table
(3) remove the assumption that every message has a sender in the code and fallback on something else in the code for firstParticipant (the firstParticipant could be the "To" field if there's no from)

**Comment by FelixMalfait** [comment]
See also: https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/activities/emails/components/EmailThreadPreview.tsx#L89 -> it seems we're circumventing this assumption in the frontend (?) but not sure if it's useful because a 500 error was thrown on the backend side when I had no message sender

**Comment by Weiko** [comment]
Also the message component will not load if from is missing, see here https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/activities/emails/components/EmailThreadMessage.tsx#L48

I think 3) will bring too much complexity in the code for something that should not happen, I agree that we should enforce that on the DB level if possible

**Comment by FelixMalfait** [comment]
Discussed it on Discord: let's go with (2). 

Note: need to change a bit the code because we are currently creating the message before we create participants

**Comment by charlesBochet** [comment]
@Weiko Do we take this one in the current sprint?

**Comment by Weiko** [comment]
> @Weiko Do we take this one in the current sprint?

I think this issue arises because of the cascade delete so once we've fixed that it shouldn't be a big issue, but I agree that ideally we could enforce it on the DB. 
I wouldn't prioritize it during this sprint if we also address the cascade issue but we could do it now to avoid future unnecessary migrations if we are sure about this change.
