### ISSUE TITLE
Add a confirmation modal when deleting/regenerating an API Key

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4016]
Currently you can invalidate an API Key and break an entire application by clicking "Regenerate key" or "Delete".
This is dangerous and it'd be nice to have a confirmation message to prevent any error.

In account deleting we already have a mechanism to confirm the action:

<img width="716" alt="Screenshot 2024-02-16 at 15 46 54" src="https://github.com/twentyhq/twenty/assets/6399865/ff6beef4-ce52-4c27-a1b1-15c152d93280">

We should implement the same mechanism for token regeneration and token deletion.

The message should be 
`Please type "yes" to confirm you want to delete this API Key. 
Be aware that any script using this key will stop working. `

`If you’ve lost this key, you can regenerate it, but be aware that any script using this key will need to be updated.
Please type "yes" to confirm`

**Comment by Bonapara** [comment]
Thanks @anoopw3bdev! While you're at it, can you bring back the spacing between the text & inputs? Thanks🙌

![image](https://github.com/twentyhq/twenty/assets/19412894/8a361018-1f13-4c58-9966-fe507c4096d4)

**Comment by FelixMalfait** [comment]
@anoopw3bdev I forgot but let also add this confirmation message to webhook deletion!

`Please type "yes" to confirm you want to delete this webhook.`

Thanks!

**Comment by anoopw3bdev** [comment]
Sure thing @Bonapara @FelixMalfait

**Comment by anoopw3bdev** [comment]
@Bonapara In the design, the "Delete" button is positioned below the "Cancel" button but in actual implementation, "Delete" is above "Cancel". Should that be changed?

**Comment by anoopw3bdev** [comment]
@Bonapara How much spacing would you suggest between the text and inputs?  
18px margin-bottom will look like this
<img width="473" alt="Screenshot 2024-02-16 at 10 38 09 PM" src="https://github.com/twentyhq/twenty/assets/44577841/4a168ee6-038f-422a-a688-5b2cdc320844">

**Comment by Bonapara** [comment]
24px @anoopw3bdev!

Yes you can also change the order, many thanks 🙏

**Comment by anoopw3bdev** [comment]
Hello @FelixMalfait @Bonapara this task has been completed, please take a look at the screenshot attached and let me know if you have any comments. 

Also, is there any webhook end point that I can use locally to test out the webhook part.

<img width="374" alt="Screenshot 2024-02-20 at 1 19 27 PM" src="https://github.com/twentyhq/twenty/assets/44577841/4aac377b-290b-42d3-89a0-708ba8959445"> 
<img width="383" alt="Screenshot 2024-02-20 at 1 19 42 PM" src="https://github.com/twentyhq/twenty/assets/44577841/1cec97b0-f714-432e-9400-d8cc0ed25d93">

**Comment by Bonapara** [comment]
Thanks @anoopw3bdev! From a design perspective can you just remove the line break in the text?

**Comment by anoopw3bdev** [comment]
Hi @Bonapara sure
