### ISSUE TITLE
Add validation on webhook creation

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4018]
I tried to enter a webhook URL that wasn't an URL and there was no validation which caused the server to crash:

<img width="459" alt="Screenshot 2024-02-16 at 15 52 13" src="https://github.com/twentyhq/twenty/assets/6399865/a5340abc-b160-464c-a196-a4794d0cecd2">
<img width="1203" alt="Screenshot 2024-02-16 at 15 54 15" src="https://github.com/twentyhq/twenty/assets/6399865/d02be4b4-50b6-4b1b-96b5-7396b50ab7e2">

We should at least add server-side validation

**Comment by rostaklein** [comment]
I was looking into this one and found out that webhook object has create/update query generated same way as the other objects. I couldnt find any backend validation for inputs for the generated operations. Only the manually created mutations/queries have such validation. I guess I shouldnt create two new operations for create/update to be able to include validation there. Did I miss anything? 🤔

**Comment by FelixMalfait** [comment]
@rostaklein ah yes that's a good point. We have a hook system (you can look at `MessageFindManyPreQueryHook`) but I feel like we're creating tech debt by doing it this way.

The right way would be to find a way to bring class-validator decorators instead. But that seems like a though problem 🤯. 

Let's do frontend validation only then!
