### ISSUE TITLE
Issue with sort on tables

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4022]
Seems like we have broken the sort feature.

When I first sort by ASC it didn't work but then sorting by DESC works.
And if I sort by DESC but go to a new page and then come back, the sorting filter is still visible but it's not sorted by DESC anymore

https://github.com/twentyhq/twenty/assets/6399865/b72b410d-74f4-4e48-9023-e710aac747ac

**Comment by charlesBochet** [comment]
@FelixMalfait I'm planning to refactor ViewBar next week, I'll take this into my scope, it seems related
