### ISSUE TITLE
Add "Beta" on Email tab

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4040]
# Current behavior

We cannot see the Email feature is still in Beta

![CleanShot 2024-02-19 at 09 34 06](https://github.com/twentyhq/twenty/assets/19412894/cda00fa8-7bd5-4ae3-a149-fe2331acaa7a)

# Desired Behavior

We want to indicate that we are still working on the feature with a "Beta" chip.

![CleanShot 2024-02-19 at 09 30 46](https://github.com/twentyhq/twenty/assets/19412894/19fae881-687e-4e47-94e1-bf303de9d8d1)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=15563-46189&mode=design&t=ra3J03wCTupiWgIi-11

On Figma, I implemented the Chip on ".Tab/content" (hidden by default) You might want to change this component! 

![CleanShot 2024-02-19 at 09 32 13](https://github.com/twentyhq/twenty/assets/19412894/15c7897a-f599-4a59-bbb8-56a590495cf0)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=3122-142114&mode=design&t=ra3J03wCTupiWgIi-11

**Comment by jeet1desai** [comment]
Hey @Bonapara can you please assign it to me?

**Comment by Bonapara** [comment]
Done, Thanks @jeet1desai!
