### ISSUE TITLE
Add linter to Chrome Extension

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4044]
Followup of https://github.com/twentyhq/twenty/pull/3430

We need to add a proper linter and config to this new package

**Comment by mabdullahabaid** [comment]
Happy to resolve this too. I expect most of the rules to be similar to those of twenty-front, but let me know if you think there's something more to add.

**Comment by FelixMalfait** [comment]
Great thank you @mabdullahabaid!
