### ISSUE TITLE
Write tests for Chrome Extension

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4045]
Followup of https://github.com/twentyhq/twenty/pull/3430

As of now we didn't write any test. 
Would be nice to have some basic coverage

**Comment by teyim** [comment]
hi @FelixMalfait , would like to take this up. whats the scope of the test we are looking at?

**Comment by FelixMalfait** [comment]
Hey @teyim thanks a lot!
I think we can start with very basic coverage. Maybe save a LinkedIn profile and a LinkedIn company page as html files in a test folder. And write one or two basic test for each to check the parsing works correctly?
We use Jest for testing in twenty-front, we should also use it in the chrome extension.
