### ISSUE TITLE
Small fixes for Chrome Extension

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4046]
1. The default route if no custom route was added should be https://api.twenty.com not http://localhost:3000

<img width="378" alt="Screenshot 2024-02-19 at 10 53 29" src="https://github.com/twentyhq/twenty/assets/6399865/c1de87ca-7992-4bb9-ba12-daf1e49ce7ca">

2. We should add a logo with a better resolution here
<img width="387" alt="Screenshot 2024-02-19 at 10 58 01" src="https://github.com/twentyhq/twenty/assets/6399865/953b6b2c-2061-4017-884c-f49a466d4291">

**Comment by mabdullahabaid** [comment]
Assign this to me, should be a quick one. Would need access to a higher resolution logo though.

**Comment by FelixMalfait** [comment]
Thanks! There are several versions of the logo around the repo, here's the svg https://github.com/twentyhq/twenty/blob/main/packages/twenty-website/public/images/core/logo.svg

**Comment by FelixMalfait** [comment]
* I said app.twenty.com but it should have been https://api.twenty.com

**Comment by mabdullahabaid** [comment]
So, if I set a custom route, close the options page, and come back to it again, the custom route toggle should be true and the route itself should be visible. This is what I gather from the last comment. Is it so?

**Comment by FelixMalfait** [comment]
Yes exactly!
