### ISSUE TITLE
See when a record has already been saved in Chrome Extension

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4048]
As of today if you come back to a profile you have already saved on the Chrome Extension, it's impossible to know it. 

<img width="192" alt="Screenshot 2024-02-19 at 11 08 26" src="https://github.com/twentyhq/twenty/assets/6399865/27736dd7-6175-4876-893f-87f7ad1fe164">

Instead it would be nice if the button was disabled and showed "View in Twenty".

TBC if we should do a simple find query of eventually leverage the duplicate endpoint https://github.com/twentyhq/twenty/pull/4038 (probably not)

**Comment by Bonapara** [comment]
Or even "See on Twenty"?

**Comment by FelixMalfait** [comment]
@Bonapara yes good point that's better with a link! In that case I prefer "View" which is a little less casual + "in" rather than "on". I edited the issue

**Comment by mabdullahabaid** [comment]
A simple find query to check for a record against the LinkedIn username could be a good fix. 
If a record is found, the text can display "View in Twenty".

**Comment by FelixMalfait** [comment]
@AdityaPimpalkar could you please comment so that I can assign you to this? Thanks

**Comment by AdityaPimpalkar** [comment]
Thanks @FelixMalfait :)
