### ISSUE TITLE
The rest docs generator should use the given base URL in sample requests

### ISSUE THREAD

**Issue by SkepticMystic** [twentyhq/twenty#4070]
## Bug Description

In the [rest API docs generator](https://docs.twenty.com/rest-api/core#/operations/GetOpenApiSchema), one has to give an API token and their instances base URL. It then generates documentation and sample requests. However, the sample requests use the fixed url `https://api.twenty.com`, instead of the given base URL from above. This leads to sample requests failing from invalid API keys, when the instance is self-hosted.

**Example:** 

The generated samples don't use the given base URL.

![image](https://github.com/twentyhq/twenty/assets/70717676/679b1450-d76c-418b-b7ad-25babd93e656)

## Expected behavior

The generated samples should use the given base URL.

**Comment by FelixMalfait** [comment]
Thanks, good catch!

https://github.com/twentyhq/twenty/blob/6fb0099eb3884f6e8c9d137eeb50e5689fbd077f/packages/twenty-server/src/core/open-api/utils/base-schema.utils.ts#L24 <-- I'm guessing it'd need to be changed here. We should probably use `getServerUrl()` instead...
