### ISSUE TITLE
Update the Tasks inbox empty state wording

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4078]
# Current behavior

```
No Task
There are no tasks for this user filter
```

![Screenshot 2024-02-20 at 10 50 00](https://github.com/twentyhq/twenty/assets/19412894/4125b30f-483c-456c-9ac5-824395f5e31d)

# Desired Behavior

To:

```
Mission accomplished!
All tasks addressed. Maintain the momentum.
```

![image](https://github.com/twentyhq/twenty/assets/19412894/06c78eca-a4d4-4df4-919c-cdbeeab708d3)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=7778-103692&mode=design&t=IVCEqnfy6obdFjnm-11

**Comment by jeet1desai** [comment]
Hey @Bonapara can you please assign it to me
