### ISSUE TITLE
Implement a loading state on list page

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#4079]
## Scope & Context

Sub-pages that are loading lists like : timeline, task tab, note tab, task page, etc.

## Current behavior

Either there is a flash with the empty state page, which is not what we want, or there is a blank page while loading.

## Expected behavior

We would like to implement the loader @Bonapara has designed.

**Comment by Bonapara** [comment]
![image](https://github.com/twentyhq/twenty/assets/19412894/c41c256a-3a2b-4c59-9227-a36b6927a9a9)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5910-72493&mode=design&t=IVCEqnfy6obdFjnm-11

**Comment by FelixMalfait** [comment]
We should have skeleton loading instead
