### ISSUE TITLE
[Timebox] Refactor - remove duplicate nested relations in queries.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#4085]
## Scope & Context

The hook that creates graphql queries.

Every query where we request relations with a depth more than 1.

## Current behavior

The generated queries will have recursive loop of relations : 

For example : company -> people -> company -> people -> company ...

## Expected behavior

We want to prevent that from happening, but we have to be sure that it won't create bugs either, because if we just put _typename and id some operation like cache update are sending bugs like "missing fields on Company : createdAt, updatedAt ..."

**Comment by charlesBochet** [comment]
Eager load relations
+ don't load inactive fields
