### ISSUE TITLE
Refactor relations in backend end

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#4086]
## Scope & Context

We have a problem of complexity when we manipulate relations metadata and object metadata items relations between each other.

## Current behavior

We have hooks and utils to parse the relation metadata we get from the backend and in our object metadata items.

## Expected behavior

We want to create a new way of representing relations in the frontend that introduces a separate terminology from the backend, which is hard coded in one direction.

This terminology will be implemented when we first get object metadata items, and will put every relation information on each object metadata item so that we always have it available.

**Comment by charlesBochet** [comment]
To discuss with @magrinj
