### ISSUE TITLE
Add REST metadata endpoint to documentation

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4089]
Followup of #3912

Right now the metadata endpoint is still marked as "soon" in the docs. We should update it :)

<img width="285" alt="Screenshot 2024-02-20 at 15 00 23" src="https://github.com/twentyhq/twenty/assets/6399865/39dd6ebe-c570-4979-808a-8ced22fe812e">

**Comment by AdityaPimpalkar** [comment]
Hey @FelixMalfait, I'll have the open-api routes initialised for metadata along with updating the docs 👍

**Comment by FelixMalfait** [comment]
@AdityaPimpalkar amazing thanks!
