### ISSUE TITLE
Remove cursor pointer on Workspace name

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#409]

**Comment by Bonapara** [comment]
> Is it that part ?
> 
> ![Image](https://user-images.githubusercontent.com/3551795/248792454-ed871cc9-ae4b-468a-bb71-f83c9fa58582.png)
> 
> @Bonapara Should we keep it clickable for now and simply redirect it to the home page?

It should not be clickable, as you cannot change your workspace today. It should neither redirect to the homepage, just display the workspace name as an information without any specific behavior ;)

**Comment by charlesBochet** [comment]
Fixed by https://github.com/twentyhq/twenty/pull/428
