### ISSUE TITLE
Fix Back-Button Loop and View Overrides when displaying Shows Linked Records

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4093]
# Current behavior

In shows, if there are multiple linked records, you can click "See all" to go to the relation index page showing only the records linked to the show.

![CleanShot 2024-02-20 at 16 29 40](https://github.com/twentyhq/twenty/assets/19412894/c23cf8c5-6a53-49da-9b26-6c0d08ed3a17)

Goes to:

![Screenshot 2024-02-20 at 16 30 17](https://github.com/twentyhq/twenty/assets/19412894/3fd13be2-7a18-4e8b-be27-efb2e8b46290)

# Issue

We are facing two issues with the solution that has currently been implemented:

1. Clicking the `Back` button creates an infinite loop because the previous page redirects to the generated index, preventing returning to the initial show page using the `Back` button.

![Screenshot 2024-02-20 at 16 31 45](https://github.com/twentyhq/twenty/assets/19412894/2d91b8cd-25ff-4568-afb6-0b4f0d0ebb9c)

2. We can override the initial view parameters by pressing the `Update view` button. This is dangerous!

![CleanShot 2024-02-20 at 16 34 01](https://github.com/twentyhq/twenty/assets/19412894/9782f966-3083-44ac-a427-9b256b325102)

# Desired Behavior

1. The intermediate redirection page should not be persisted in the history so pressing the back button redirects to the show page.

2. We should redirect the user to a `filtered default view` named `All [Object_plural_name]`. Pressing the `X` button should go back to the first user view. **We shouldn't display the "update view" and "reset" buttons on this default view.** (The filters applied to this view cannot be persisted). This _"default view"_ **should not appear in the view Switcher.**

![image](https://github.com/twentyhq/twenty/assets/19412894/676800e7-1031-4734-9f0d-bdb400705cc9)

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=23405-37282&mode=design&t=r4mnIyW3DIbSmeHA-11

**Comment by Muralidhar22** [comment]
Hi @Bonapara Can I work on this issue.

**Comment by Bonapara** [comment]
Just assigned you @Muralidhar22. Thanks!

**Comment by Muralidhar22** [comment]
Hi @Bonapara could you please clarify what is **view switcher** (This "default view" should not appear in the view Switcher.)

**Comment by Bonapara** [comment]
@Muralidhar22 Here is an explanation:

![CleanShot 2024-02-29 at 13 15 05](https://github.com/twentyhq/twenty/assets/19412894/12ccdf83-525c-487a-a817-0e0ea4a2542e)

But:

![CleanShot 2024-02-29 at 13 16 58](https://github.com/twentyhq/twenty/assets/19412894/f0598ba7-23cf-4c1a-8c23-12c8f8366ef6)

**Comment by Muralidhar22** [comment]
Thanks @Bonapara I might need bit more time was occupied with something, I was able to replicate the issue and debug a bit, if that's okay I'll try to give an update with in a day or two, if not please re assign

**Comment by Muralidhar22** [comment]
`We should redirect the user to a filtered default view named All [Object_plural_name]. Pressing the X button should go back to the first user view. `

for the above point in figma linked, when I hover on All [Object_plural_name] it is converting into dropdown, I believe that's not what expected? @Bonapara

**Comment by Bonapara** [comment]
Yes indeed, it's not what's expected, just a Figma convenience. Thanks @Muralidhar22

**Comment by Muralidhar22** [comment]
@charlesBochet , @Bonapara want to clarify what changes are still needed from this issue
Fixed issues from the PR: #4516 
- back navigation is fixed now, I can't replicate anymore.
- Pressing the [X] button should go back to the first user view.(this is also now working as expected)

Changes need to be made:
- Removing View switcher in the filtered object in records page
- Hiding the `Reset` and `Save as new view button`
<img width="1712" alt="Screenshot 2024-03-27 at 9 40 31 PM" src="https://github.com/twentyhq/twenty/assets/33935339/70673cda-0a8d-4383-9a2d-014ea261b9dd">

**Comment by Bonapara** [comment]
Hi @Muralidhar22, indeed 1. and 2. seem to be fixed.

**We only proceed with:**
- Hiding the Reset and Save as new view button

As the `default view` introduction removed the need to remove the view switcher.

Thanks for contributing!!
