### ISSUE TITLE
New field: Currency

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4122]
# More context

https://github.com/twentyhq/twenty/issues/2330

# Desired behavior

Introduce the currency field. The "Default Unit" picker allows you to choose which default currency will be chosen by default. (Required and unique should be implemented later)

![CleanShot 2024-02-21 at 17 02 28](https://github.com/twentyhq/twenty/assets/19412894/1133e20b-8071-4dc5-b3b1-64fb18f4a016)

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=13884-61375&mode=design&t=qpJNVAebuHYFQT5A-11
```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/4123
```

**Comment by Bonapara** [comment]
See https://github.com/twentyhq/twenty/issues/2330 for context

**Comment by anoopw3bdev** [comment]
Hi @Bonapara I would like to work on this, can you assign this to me
