### ISSUE TITLE
New CurrencyFieldInput design

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4123]
# Desired Behavior

![image](https://github.com/twentyhq/twenty/assets/19412894/43d2d577-3049-487c-ae48-b36843c17946)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=3007-69739&mode=design&t=qpJNVAebuHYFQT5A-11

Clicking on "USD" should open a dropdown menu with a search. The default value should be set by default:

![image](https://github.com/twentyhq/twenty/assets/19412894/421d632b-b78e-4b39-995c-b1183ae59822)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=23581-64924&mode=design&t=qpJNVAebuHYFQT5A-11

**Comment by jeet1desai** [comment]
Hey @Bonapara @FelixMalfait can you please assign it to me, I'd love tot try.

**Comment by FelixMalfait** [comment]
@jeet1desai changed your mind haha 👀 ?

**Comment by FelixMalfait** [comment]
Oh great @jeet1desai! There's no rush for this one, it's not blocking anything else. You can take up to 10 days that won't be a problem
