### ISSUE TITLE
Bug in Chrome Extension when parsing fails

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4125]
We should improve parsing and avoid sending "NaN" to the API.

<img width="622" alt="Screenshot 2024-02-21 at 17 32 27" src="https://github.com/twentyhq/twenty/assets/6399865/7f52ef6c-3b11-4ca7-a184-1e41ba5d7b1c">

<img width="1498" alt="Screenshot 2024-02-21 at 17 32 13" src="https://github.com/twentyhq/twenty/assets/6399865/5a94033e-361e-4898-abb9-c3a820f4fdc5">

**Comment by 16dango** [comment]
I'll try to work on, please assigned me sir🙇

**Comment by FelixMalfait** [comment]
Sorry I missed that!

**Comment by FelixMalfait** [comment]
cc @AdityaPimpalkar maybe it's something you've fixed already in your latest PRs?

**Comment by AdityaPimpalkar** [comment]
In the current codebase, It sends `null` instead of `NaN`, so this shouldn't be an issue anymore 👍

**Comment by FelixMalfait** [comment]
Thanks!
