### ISSUE TITLE
Create company along with person in Chrome Extension

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4126]
As of today if I go to a person's profile on LinkedIn and click on "Add to Twenty" this will fill all the person fields but this will not create or attach a company.

We should find a way to parse basic info about that company and create it along with the user if it doesn't exist, or attach it if it does (use companyDuplicate endpoint to find out?)

We don't have much info on the company so maybe we should click on the company page then come back (not amazing for the user experience but better than not having company domain name and therefore no icon)

**Comment by FelixMalfait** [comment]
Bump @AdityaPimpalkar 😁 thanks

**Comment by AdityaPimpalkar** [comment]
Thanks @FelixMalfait :)
