### ISSUE TITLE
Improve CurrencyFieldDisplay 

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4127]
As of now we don't format the amount at all in `CurrencyFieldDisplay`.
We should:
1. Rename `amountFormat.ts` util to  `formatCurrency.ts`
2. Rename `number.ts` util to `formatNumber.ts`
3. Adapt `formatCurrency` to also take a currency as optional input (USD, EUR...) then happen the matching symbol for that currency in front of the returned number (e.g. $900k instead of just 900k). If no currency is passed, return it with a $ sign.
4. Remove the $ sign in front of ${boardColumnTotal} in `RecordBoardDeprecatedColumnHeaderProps`. Adapt recordBoardColumnTotalsFamilySelector so that the currency displayed is the currency of the first item (not great but that's good enough for now)
5. Change the default icon on `opportunity.object-metadata.ts` from `IconCurrencyDollar` to `IconCoins`

For currency <> symbol matching you should provide a mapping for all available currencies on `CurrencyCode.ts` (server side)

**Comment by FelixMalfait** [comment]
Thanks!

**Comment by anoopw3bdev** [comment]
Hi @FelixMalfait sorry I took more time to complete this issue and now this file `RecordBoardDeprecatedColumnHeader` and `recordBoardColumnTotalsFamilySelector` doesn't exist any more in the codebase. Could you update/ remove the requirement 4 from the issue? Thanks.
