### ISSUE TITLE
Adjust the background on the contributors page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4130]
# Current behavior

1- The dotted background only appears in the middle of the scroll. 
2- It's not tall enough.
3- The Background is not rotated

![CleanShot 2024-02-22 at 10 58 35](https://github.com/twentyhq/twenty/assets/19412894/5c534fd2-dd34-4b6b-8481-94acb784470a)

# Desired Behavior

Make it Taller. It must be responsive to the page height (See https://twenty.com/oss-friends for inspiration)

Rotate the background and make it appear from the top of the page:

![Contributor Index](https://github.com/twentyhq/twenty/assets/19412894/78ea418b-0320-4e9e-864a-8d0befb2ed03)

https://www.figma.com/file/aNpCjwN9wg2DqLWAHPS0ll/%F0%9F%8C%8D-Website-%26-Marketing?type=design&node-id=1-553&mode=design&t=vEUqotmUtTXDOUR1-11

# Create a component that allows the background to be used on any page

Here is the Framer code I implemented. The component should have two variables: "Dots Rotation" and "Gradient Rotation)

```
import * as React from "react"
import { addPropertyControls, ControlType } from "framer"

type Props = {
    image: string
    rotation: number
    gradientRotation: number
}

export function patternBackground(props: Props) {
    // Generate the CSS for the background image
    const backgroundImageStyle = {
        position: "absolute",
        top: "-50%",
        left: "-50%",
        width: "200%", // Increased to cover the area when rotated
        height: "200%", // Increased to cover the area when rotated
        backgroundImage: `url(${props.image})`,
        backgroundSize: "auto 20px", // Adjust for maintaining aspect ratio
        backgroundRepeat: "repeat",
        transform: `rotate(${props.rotation}deg)`,
        transformOrigin: "center center",
    }

    // Generate the CSS for the gradient overlay
    const gradientOverlayStyle = {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: `linear-gradient(${props.gradientRotation}deg, #FFF 8.33%, rgba(255, 255, 255, 0.08) 48.95%, #FFF 92.18%)`,
        zIndex: 1, // On top of the background image
    }

    // Generate the CSS for the container
    const containerStyle = {
        height: "100%",
        width: "100%",
        position: "relative",
        overflow: "hidden",
    }

    // Return a div with the container, background image, and gradient overlay
    return (
        <div style={containerStyle}>
            <div style={backgroundImageStyle} />
            <div style={gradientOverlayStyle} />
        </div>
    )
}

// Add property controls to show in the props panel
addPropertyControls(patternBackground, {
    image: {
        type: ControlType.Image,
        title: "Image",
    },
    rotation: {
        type: ControlType.Number,
        defaultValue: 16,
        min: -360,
        max: 360,
        unit: "°",
        step: 1,
        displayStepper: true,
    },
    gradientRotation: {
        type: ControlType.Number,
        defaultValue: 185,
        min: -360,
        max: 360,
        unit: "°",
        step: 1,
        displayStepper: true,
    },
})

```

**Comment by WilliamWong55955** [comment]
Hello! Can my team and I work on this issue?

**Comment by Bonapara** [comment]
Sure! Thanks for contributing @WilliamWong55955

**Comment by Bonapara** [comment]
@WilliamWong55955, unassigning you now since two weeks have passed. Thanks!

**Comment by kbarr1212** [comment]
Hello! I was a part of William's team and I was wondering if I could be assigned again? It took us a bit to successfully build the local setup. After, we were working on a patternBackground.tsx file and were coming up with some issues so we weren't able to submit a pull request. If it's possible I'd like to continue to work on it!

**Comment by Bonapara** [comment]
Hi @kbarr1212, Thank you! Unfortunately, @ady-beraud has already fixed it. Perhaps you can pick up another issue?
