### ISSUE TITLE
Rename "Disabled" fields & objects into "Inactive" in Settings

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4153]
# Current Situation

The interface displays inactive objects and fields as "Disabled".

<img width="612" alt="Screenshot 2024-02-23 at 15 13 22" src="https://github.com/twentyhq/twenty/assets/19412894/22c5e557-675f-4296-94b0-c38e9156230c">

# Desired Behavior

Rename "Disabled" sections to "Inactive" and change the "Disable" CTA to "Deactivate".

### Section names
![CleanShot 2024-02-23 at 15 11 12@2x](https://github.com/twentyhq/twenty/assets/19412894/85c1035b-5eb9-4e12-8dfe-0fbd7af88c20)

### CTA
![CleanShot 2024-02-23 at 15 11 42@2x](https://github.com/twentyhq/twenty/assets/19412894/b5a0cfcc-1445-4303-b3f4-4007d75749f5)

**Comment by selango1** [comment]
Hi, I want to take up this issue

**Comment by Bonapara** [comment]
Just assigned you, thanks for contributing @selango1!

**Comment by khodidasgamdha** [comment]
@Bonapara I Renamed the fields, pls assign me so I can push

**Comment by Bonapara** [comment]
Hi @selango1? Are you still on it?

**Comment by selango1** [comment]
I have completed the changes, please check and let me know! Thank you for your patience :)
