### ISSUE TITLE
Add a link to developer documentation in developers tab

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4154]
Feedback I got during a call this morning.
They expected to find a link to the documentation in the developers tab and couldn't find it.
That would be a good idea!

It should link to https://docs.twenty.com

**Comment by Bonapara** [comment]
![image](https://github.com/twentyhq/twenty/assets/19412894/40d08fa8-d322-49c5-af09-396862393c86)

Easy V1. Looks good to you @FelixMalfait?

**Comment by FelixMalfait** [comment]
Great!

**Comment by sohalkumar** [comment]
Hi @Bonapara , @FelixMalfait

I implemented the button from the given design.
[Screencast from 29-02-24 03:24:06 PM IST.webm](https://github.com/twentyhq/twenty/assets/68388983/67a1e0bb-e012-4aac-92f6-4b9b4d621ba1)
![Screenshot from 2024-02-29 15-24-44](https://github.com/twentyhq/twenty/assets/68388983/42dd6a24-3ad2-4f8a-93cc-c4d29ac33ed7)
![Screenshot from 2024-02-29 15-24-44](https://github.com/twentyhq/twenty/assets/68388983/4790540a-1482-4956-8204-2462ce6467b8)

modified:  ` packages/twenty-front/src/pages/settings/developers/SettingsDevelopers.tsx`
![image](https://github.com/twentyhq/twenty/assets/68388983/113841bb-637a-4dc6-bbca-c161eb954cbd)

created: `packages/twenty-front/src/modules/settings/components/ReadDocumentationButton.tsx`
![image](https://github.com/twentyhq/twenty/assets/68388983/a0292b76-563a-4f46-881a-66bb2ea03abb)
Is this approach alright?

added `IconBook2` icon import in `packages/twenty-front/src/modules/ui/display/icon/index.ts`

**Comment by FelixMalfait** [comment]
@sohalkumar yes that looks great! `ReadDocumentationButton` is really specific to developpers so you can keep it in /developers/components/. Also your button import looks incorrect in the screenshot but I guess you fixed that after

**Comment by sohalkumar** [comment]
@FelixMalfait I have moved the `ReadDocumentationButton` in 
packages/twenty-front/src/pages/settings/developers/components/

and the button import is now 
`import { Button } from '@/ui/input/button/components/Button';`

If everything looks right, should I proceed with the PR?

**Comment by FelixMalfait** [comment]
Yes pleas @sohalkumar thanks!

**Comment by sohalkumar** [comment]
@FelixMalfait please review the PR.
Thanks :D
