### ISSUE TITLE
Adapt Index first column Stickiness on Mobile

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4155]
# Current behavior

The Index first column is Sticky when horizontally scrolling the columns

![image](https://github.com/twentyhq/twenty/assets/19412894/3fdf5a93-02b8-480a-98a1-8291bfe136ac)

# Desired Behavior

We want to adapt the first column stickiness **on Mobile** as it prevents good content readability. We want to keep only the companies Favicon and the checkboxes as we scroll to the right

![image](https://github.com/twentyhq/twenty/assets/19412894/cfe12598-8426-41ff-a54f-4bf4d7303c1b)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=23796-35984&mode=design&t=0qrJcy4ODeblizYh-11

**Comment by jeet1desai** [comment]
Hey @Bonapara can you please assign this to me

**Comment by Bonapara** [comment]
Done, thanks @jeet1desai!
