### ISSUE TITLE
Study Apollo client only directives and what we could do with them

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#4157]
## Scope & Context

Apollo has introduced some client only directives that could help us handle some use cases more easily : 
https://www.apollographql.com/docs/react/data/directives/#client

It would help to talk about it with the @CoreTeamTwenty

**Comment by FelixMalfait** [comment]
Closing this as it's been open for some time now @lucasbordeau @charlesBochet 

I don't see many use-cases for local fields.

The only use-case I see is for things we store in localStorage (for example the last seen view), maybe it could have been done this way. But I don't think the current implementation is bad.

**Comment by charlesBochet** [comment]
@FelixMalfait agree, we don't need it. I think we have solved all the current issues with the cache
