### ISSUE TITLE
[BE] I have standard fields on Pipeline Entities and they are exposed for read and update through the API

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#416]
@Bonapara @FelixMalfait could you provide more information about what StandardField field we would add to a PipelineProgress.

**Comment by Bonapara** [comment]
@charlesBochet 

### Sales B2B

**Record type** - Companies

**Status** - One choice tag - [Identified, Qualified, Engaged, Proposed, Negotiated, Closed, Lost]

---

************Value************ - Number (Dollars)

**Estimated Close** - date

**Confidence** - confidence bar

**Accountable** - Team member

**Recurring** - dropdown - [One-time, monthly, Annual]

**Contacts** - Associated People

**Comment by Bonapara** [comment]
For V1 we should have only one sales pipeline with companies (Not People)

**Comment by charlesBochet** [comment]
For future reference: https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_opportunity.htm

**Comment by charlesBochet** [comment]
First standards fields have been implemented (amount and closeDate)
