### ISSUE TITLE
Set the "Field/Column header bar" to stick when scrolling indexes

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4162]
# Desired Behavior

We want to set the `Field bar` to remain sticky when scrolling an Index. It should **not** have a box shadow (Unlike the sticky first column). It should scroll Under the first column.

![image](https://github.com/twentyhq/twenty/assets/19412894/ed3ae167-9c6b-4c8f-b7cf-77d08cd95988)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19116-70395&mode=design&t=4aSfJfQmK603xoqE-11

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
I can work on this

**Comment by Bonapara** [comment]
Thanks @Kanav-Arora!!

**Comment by FelixMalfait** [comment]
I feel like I had seen a PR for this that was stuck but I can't find it? Or is there a duplicate? @Kanav-Arora maybe you know? thanks

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait 
I confirmed it in the discord I don't think so there is any
