### ISSUE TITLE
Add a page to indicate that server is unreachable

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#4163]
## Scope & Context

Frontend when server is down or unreachable.

## Current behavior

Since it is not handled, we have a 404 with random error popups : 

<img width="1484" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/b758ae6d-75f0-44b3-bd0e-a1a46ed9ea85">

## Expected behavior

@Bonapara Could we have a dedicated page ? Maybe with a dinosaur game 😄 ...

**Comment by Bonapara** [comment]
Is it not supposed to be a 500 error then?

![image](https://github.com/twentyhq/twenty/assets/19412894/f69f86b8-dda5-46d8-8a8e-a8cfc9340f28)

**Comment by lucasbordeau** [comment]
@Bonapara 500 is when the server is responding but had a problem with the request.

We want to indicate that the connection is broken, the server is down and not responding, maybe something like : our server is not responding right, can you retry in a few moments.

**Comment by Bonapara** [comment]
Would it be a `504 Gateway Timeout`?

**Comment by lucasbordeau** [comment]
It cannot be any error code because the server is not responding, so we don't consider it as an error but as a connection problem 

<img width="516" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/338fe2f5-7a2f-42ff-9b5a-7ef5c01f2dbc">

**Comment by Ethan-new** [comment]
Hi can you assign this to me

**Comment by lucasbordeau** [comment]
Hi @Ethan-new this issue is currently blocked. We'll update you when the discussion will be settled.

**Comment by lucasbordeau** [comment]
@Bonapara Any update on this ? Should we close this issue ?

**Comment by Bonapara** [comment]
Can we display the Chrome default alert instead of the 404?

**Comment by lucasbordeau** [comment]
Seems difficult, should we close this issue and leave it like that ?
