### ISSUE TITLE
Replace useDeviceType by media queries on website

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4165]
On the website we copied the code we had in `twenty-front` to adapt the site between mobile/desktop version.
But this approach doesn't work with SSR and Next.js (this ends up with the desktop version being loaded at first and then once React is loaded it switches to the mobile version).
We need to change this and use media-queries instead https://emotion.sh/docs/media-queries

@Kanav-Arora will handle this :)

**Comment by Kanav-Arora** [comment]
Hi @FelixMalfait 
Fixed
