### ISSUE TITLE
Cannot display "name" field in Opportunities view

### ISSUE THREAD

**Issue by pombredanne** [twentyhq/twenty#4167]
## Bug Description
In the "All Opportunities" board view, I want to display the name I gave to opportunities
I go to options/fields/hidden/Name but there is no way to add the Name to the view (no + sign) and I cannot take the field out from its hidden state

## Expected behavior

I want to display the "Name" field in Opportunities view and there should be a way to do this, otherwise naming opportunities has no purpose at all. 

For reference, the doc is at https://github.com/twentyhq/twenty/blob/fb920a92e749f6e9a1be1d183d99d780b1ef54ef/packages/twenty-website/src/content/user-guide/basics/opportunities.mdx

**Comment by FelixMalfait** [comment]
Hey I'm sorry for the delayed reply. Is it still broken? It seems to work on my side, I was not able to reproduce. 

<img width="245" alt="Screenshot 2024-02-29 at 10 50 55" src="https://github.com/twentyhq/twenty/assets/6399865/67d3ca98-180f-4f93-95cf-652fd89396ff">

<img width="366" alt="Screenshot 2024-02-29 at 10 51 06" src="https://github.com/twentyhq/twenty/assets/6399865/518ced06-10d2-4f41-809d-c730a6d2a2fd">

**Comment by pombredanne** [comment]
This is fixed in the latest alright. Thanks!
