### ISSUE TITLE
LinkedIn field doesn't parse schools correctly

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4181]
Got a bug report from a user today that is also selling to schools.

In that case the URL isn't `https://www.linkedin.com/company/{name}/` but `https://www.linkedin.com/school/{name}/`

We should fix the parsing for the LinkedIn field type to parse school urls correctly.

<img width="391" alt="Screenshot 2024-02-26 at 10 25 38" src="https://github.com/twentyhq/twenty/assets/6399865/44a2a32e-e862-4410-9c3c-6ab34eb60f46">

**Comment by EltonGohJH** [comment]
I am new to Twenty. Can I give this a try?

**Comment by FelixMalfait** [comment]
@EltonGohJH yes of course! assigning you. Thanks
