### ISSUE TITLE
Add relation in CSV exports

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#4183]
## Scope & Context

Record table CSV export

## Current behavior

The relations are not exported currently.

## Expected behavior

We want to export relations in the CSV.

**Many to one**

Export only the ID 

Example : 
- Table people
- Field company
- Should export a column with the ID of company

**One to many**

Don't export it in CSV

**Comment by FelixMalfait** [comment]
This should be a very quick one!
