### ISSUE TITLE
When filter is removed it's not removed from the dropdown

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#420]
Step 1: Add a filter, then remove it by clicking on "X"
<img width="1250" alt="Screenshot 2023-06-25 at 18 54 27" src="https://github.com/twentyhq/twenty/assets/6399865/9546f1ca-26a3-44f2-a865-a27b2b2f673a">

Step2: Re-open filter dropdown, it is still checked
<img width="268" alt="Screenshot 2023-06-25 at 18 55 05" src="https://github.com/twentyhq/twenty/assets/6399865/2c06ef7d-f911-4910-8219-2a9f1dfd5a4b">

Expected behavior: it shouldn't be checked in dropdown menu anymore

**Comment by charlesBochet** [comment]
This bug as been fixed!
