### ISSUE TITLE
Inputs height should be 32px instead of 34px

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4201]
### Current Behavior

The input height is 34px because the border is on the outside.

![Screenshot 2024-02-27 at 10:46:02](https://github.com/twentyhq/twenty/assets/19412894/7f98ed76-f5e7-48f0-a1a0-20cb26d0f084)

### Desired Behavior

Ensure all inputs have a consistent height of 32px for uniformity, (especially for when placing buttons next to them)

**Comment by Bonapara** [comment]
Hi @jrachelr, done. Thanks for contributing!

**Comment by shree-1788** [comment]
Hey @Bonapara can I work on this issue?

**Comment by jrachelr** [comment]
Hey @shree-1788, I'm still working on it! Had some issues with local setup hence the delay.

**Comment by shree-1788** [comment]
@jrachelr Thanks for the update! Appreciate it.
