### ISSUE TITLE
Account deletion broken

### ISSUE THREAD

**Issue by martmull** [twentyhq/twenty#4202]
## Bug Description

When deleting an account or a workspace, we encounter a queryFailedError:
<img width="866" alt="image" src="https://github.com/twentyhq/twenty/assets/29927851/f4225166-ec53-42cc-a2cc-3b6592c73e4a">
<img width="881" alt="image" src="https://github.com/twentyhq/twenty/assets/29927851/1eaa63be-e197-47aa-bb20-9f7f7ea49502">

## Expected behavior

No error when deleting an account or workspace

## Technical inputs

The issue comes from the new `core.userWorkspace` we add. When deleting an account, we don't properly cascade to that table
<img width="808" alt="image" src="https://github.com/twentyhq/twenty/assets/29927851/6b541813-c1e5-40be-9d1b-48b1ebf2a1c9">

## How to?
- add a `{cascade: true}` option to userWorkspace.entity.ts

**Comment by martmull** [comment]
@AdityaPimpalkar Do you think you will have the time to fix that? Maybe you can do that in the multi-workspace PR

**Comment by tutizaraz** [comment]
in the main branch that logic now works correctly on my side. this comment is for contributors who want to find something to contribute
