### ISSUE TITLE
Panel Reopening Text Wrapping Glitch

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4204]
# Current Behavior

There is a glitch when reopening a thread (both at the message and field level)

https://github.com/twentyhq/twenty/assets/19412894/582ca4e0-73fc-4fde-8006-2f67feaed999

The Chrome Performance tab shows what's happening: the text is wrapping:

![data_image_jpg;base…](https://github.com/twentyhq/twenty/assets/19412894/6db2311d-fc2f-4795-8ccf-462e35c8c917)
![data_image_jpg;base… (2)](https://github.com/twentyhq/twenty/assets/19412894/89bbde34-2aa6-4b1b-97a6-e6806cfb7acc)
![data_image_jpg;base… (1)](https://github.com/twentyhq/twenty/assets/19412894/25aadaf7-3dbe-496a-b4bb-0606ef6222af)
# Desired behavior

The text should not wrap when the panel opens. Its container needs a minimum width?

**Comment by simaosanguinho** [comment]
Hi! Can I be assigned to this issue?

**Comment by Bonapara** [comment]
Sure! Thanks @simaosanguinho :)
