### ISSUE TITLE
Close the email side panel upon clicking an open email thread

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4205]
# Current Behavior

When attempting to close the side panel (without utilizing the 'x' button icon), users must click away from the email list.

https://github.com/twentyhq/twenty/assets/19412894/71f0ff27-2820-44f2-9e5f-acf864a59fe4

# Desired Behavior

The side panel should close when a user clicks on an already-opened email.

**Comment by sooster910** [comment]
hi @Bonapara  can I work on this issue?  Thanks.

**Comment by Bonapara** [comment]
Done, thanks for contributing @sooster910 !

**Comment by Bonapara** [comment]
During the demo - do you mean in the issue description video? The only way to get emails is to plug a Gmail mailbox, the video is showing mine!
