### ISSUE TITLE
Add ability to create company and people directly from commandbar 

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#421]
<img width="411" alt="Screenshot 2023-06-25 at 19 01 46" src="https://github.com/twentyhq/twenty/assets/6399865/e2e85c7c-2797-4671-ba5f-ccb18c0b9f0b">

**Comment by Ashutosh-Bhadauriya** [comment]
@FelixMalfait I have been following Twenty for a while now and love what you folks are building. Would love to try this out. Is there a discord/slack community I can join, if I need any help? Thanks! 🙂

**Comment by FelixMalfait** [comment]
@Ashutosh-Bhadauriya thank you so much, that means a lot! 
I've just setup one over the week-end but you'll see it's not very active 😂
https://twenty.com/slack

If you want to do a call to walk you through the project/where we're going, happy to! You can reach out on Slack
