### ISSUE TITLE
Bug on API playground when using a custom URL with a folder path

### ISSUE THREAD

**Issue by paulyili** [twentyhq/twenty#4210]
## Bug Description

The method of using 1 URL (twenty.myurl.com/API) didn't work in the playground, but using a separate subdomain did work. Twenty-api.myurl.com) 

## Expected behaviour

for a domain with a path e.g: twenty-api.com/api should work in the playground.

**Comment by charlesBochet** [comment]
@paulyili The title of the issues seems to be wrong, right?

**Comment by martmull** [comment]
Hey @paulyili, can you provide some more detail for that issue? I don't understand your problem. The baseUrl is used to make the calls with the api, I don't get why `twenty.myurl.com/API` would not work
