### ISSUE TITLE
Design improvements for the releases page.

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4215]
# Intro 

Please also review the Figma thoroughly as many details have been wrongly implemented.
https://www.figma.com/file/aNpCjwN9wg2DqLWAHPS0ll/%F0%9F%8C%8D-Website-%26-Marketing?type=design&node-id=412-921&mode=design&t=KNvKF4m1rCIy4sGT-11

# Desktop, Tablet & Mobile

### Title

`Releases` font color is black instead of `primary` (#141414)
![CleanShot 2024-02-27 at 17 52 30](https://github.com/twentyhq/twenty/assets/19412894/5e30c8b4-6d4a-449b-b4ec-de977ad31ecc)

### Release infos

Date font-weight is `500` instead of `400`
![CleanShot 2024-02-27 at 17 54 04](https://github.com/twentyhq/twenty/assets/19412894/1ec831d8-af2f-434a-91da-5a1f1a313050)

### Paragraph

Font-color should be `Secondary` (#474747)
![CleanShot 2024-02-27 at 17 56 37](https://github.com/twentyhq/twenty/assets/19412894/8a99060e-17e6-4a44-a240-9ca13b904589)

### Gap inside a release

The gap should be 40px instead of 16px
![CleanShot 2024-02-27 at 18 18 15](https://github.com/twentyhq/twenty/assets/19412894/f217d106-5e2b-4b69-a6a2-340c7dcf3f51)

# Desktop & Tablet

### Release infos

The gap between release title & paragraph should be 40px instead of 16px
![CleanShot 2024-02-27 at 18 17 06](https://github.com/twentyhq/twenty/assets/19412894/916b0d30-5da1-408e-a8bd-87ce343a38b1)

### Gap

Should be 80px in desktop instead of 64px
![CleanShot 2024-02-27 at 17 59 31](https://github.com/twentyhq/twenty/assets/19412894/6a10db1c-ca88-4a73-a7d7-4ff69f195a2b)

### Margin bottom

Should be 160px
![CleanShot 2024-02-27 at 18 00 22](https://github.com/twentyhq/twenty/assets/19412894/03ecf2b6-d962-43cb-8aaa-4ae64fc0158b)

# Tablet

### Margin Left & Right

Should be 64px instead of 12px
![CleanShot 2024-02-27 at 18 03 09](https://github.com/twentyhq/twenty/assets/19412894/f96bb392-8333-4458-ac6a-ea2957520c39)

### Release title

Should be  24px instead of 40px  (Tablet H3)
![Screenshot 2024-02-27 at 18 05 17](https://github.com/twentyhq/twenty/assets/19412894/05452d76-bd8d-47a0-8e99-bbb7ec17bf66)

# Mobile

### Title spacing

The spacing around the title is 16px instead of 64px
![Screenshot 2024-02-27 at 18 13 00](https://github.com/twentyhq/twenty/assets/19412894/f8e9e59e-fb7f-46d6-9c50-3821a35daf1d)

### Margin Left & Right

Should be 24px instead of 12px (CF Tablet)

### Release title

Should be Mobile H3 (24px)
![CleanShot 2024-02-27 at 18 09 37](https://github.com/twentyhq/twenty/assets/19412894/57b1b460-d073-4a43-bdbf-5aa1c1a0fcee)

The spacing 1- should be 24px
The spacing 2- should be 40px 

![CleanShot 2024-02-27 at 18 14 03](https://github.com/twentyhq/twenty/assets/19412894/cb17d739-8c14-450d-99dc-8cd82ea4ae5d)
 

### Gap

Should stay 64px
![CleanShot 2024-02-27 at 18 10 58](https://github.com/twentyhq/twenty/assets/19412894/a34b4e64-5f60-4efb-8d8c-6de32dc4ba7d)

# Figma

![image](https://github.com/twentyhq/twenty/assets/19412894/50053222-8e1b-4070-9caf-b0e7f1e3a2d1)

https://www.figma.com/file/aNpCjwN9wg2DqLWAHPS0ll/%F0%9F%8C%8D-Website-%26-Marketing?type=design&node-id=572-53&mode=design&t=KNvKF4m1rCIy4sGT-11

**Comment by selango1** [comment]
Hi, I want to help with this issue.
Are these changes directly made through Figma?

**Comment by brendanlaschke** [comment]
> Hi, I want to help with this issue. Are these changes directly made through Figma or Github?

have a look at [`packages/twenty-website/src/app/releases`](https://github.com/twentyhq/twenty/tree/main/packages/twenty-website/src/app/releases)

**Comment by Bonapara** [comment]
Looks good to me, but I haven't worked on the codebase. I'll ping @FelixMalfait to confirm.
