### ISSUE TITLE
Select Default Value is not properly updated

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#4224]
## Bug Description

When setting a specific Select option as default from the Settings (ex: Data Model > Opportunities > Stage), it does not save the defaultValue in the right format in database.

<img width="1291" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/2df7fee6-a74c-4fb9-aa35-26b681ce8fb0">

## Expected

1) For Select Field, when fieldMetadata.defaultValue = '{ "value": "NEW" }', the New option is marked as default in Settings UI
2) When I Update the default value in SettingsUI, the defaultValue is properly formatted in fieldMetadata column. Right now it's 'NEW' instead of '{ "value": "NEW" }' (it's actually triggering a bug while trying to update postgres default Value)

## Technical input

I think there is a global problem with the way we write and read the defaultValue from fieldMetadata in the Settings. We only observe it on Select Field type because it's the only one where we allow defaultValue update. We should store it as '{ "value": "NEW" }' and read it from '{ "value": "NEW" }' format too

**Comment by FelixMalfait** [comment]
<img width="1457" alt="Screenshot 2024-02-29 at 17 17 43" src="https://github.com/twentyhq/twenty/assets/6399865/ebcf10b8-7d2d-43d8-b127-5227d07e8229">

**Comment by martmull** [comment]
@charlesBochet I think this is already solved. Can I close the issue?

**Comment by charlesBochet** [comment]
I think so! closing :)
