### ISSUE TITLE
Cannot create an Opportunity when a Person has a relation with a Company

### ISSUE THREAD

**Issue by paulyili** [twentyhq/twenty#4234]
## Bug Description

When a "Person" has a relation with a "Company" 
i.e Brian Cesky listed under Airbnb. 
You cannot create an opportunity. 

if i remove the company relation from the person, you can create the opportunity. 

You get a popup "ApolloError: Internal Server Error" 

On v0.3.1 (docker)

**Comment by FelixMalfait** [comment]
I'm closing as I think it's not a current bug but if you manage to repo on a fresh install let us know the steps and I'll re-open!
