### ISSUE TITLE
Only show 2 relations in ActivityTargetChips

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4235]
## Current behavior

<img width="840" alt="Screenshot 2024-02-29 at 08 27 20" src="https://github.com/twentyhq/twenty/assets/6399865/6f1abeac-5c20-4cc5-abde-66c7d75f89d1">

<img width="473" alt="Screenshot 2024-02-29 at 08 30 04" src="https://github.com/twentyhq/twenty/assets/6399865/161f4e57-6871-43a4-9712-35b2ba4690fb">

## Expected behavior

https://user-images.githubusercontent.com/102394218/258555611-b7dc316e-b028-4b35-b414-5bb7a3e21b7e.mp4

## Techical details

Note there used to be a more-complex version of this issue where the number of items displayed would be computed dynamically based on the space available. I spent some time trying to implement it and it's too complex because there are too many moving pieces. This issue should be much easier!

**Comment by Abhi3685** [comment]
Hi @FelixMalfait, Can I work on this one?
Please share the figma link for design reference.

**Comment by FelixMalfait** [comment]
Thanks @Abhi3685! I assigned you

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5910-71591&mode=design&t=lwrbImj8cZsYB9oy-0

**Comment by Abhi3685** [comment]
PR is approved and merged. Good to close this one. Thanks!

**Comment by FelixMalfait** [comment]
Thank you @Abhi3685!
