### ISSUE TITLE
Update the Kanban column menu

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4244]
# Current behavior

There is only one button "Edit from settings" that links to the object page in Settings

![CleanShot 2024-02-29 at 16 04 49](https://github.com/twentyhq/twenty/assets/19412894/85128c42-139b-4fd0-af85-91578a242d5b)

Links to Object Settings:

![CleanShot 2024-02-29 at 16 05 28](https://github.com/twentyhq/twenty/assets/19412894/4d12df5d-74bc-47f7-8429-572aa2385b18)

# Desired Behavior

There should be 3 buttons:
1- Edit (Should redirect to the field settings page instead of the object settings page)
2- Hide (Should hide the step)
3- Add Record (It should add a record in the column below)

![CleanShot 2024-02-29 at 16 03 59](https://github.com/twentyhq/twenty/assets/19412894/34f3d516-41f5-4717-a520-e9387954f385)

1- Should link to the corresponding Select Field settings instead of Object Settings
![CleanShot 2024-02-29 at 16 06 42](https://github.com/twentyhq/twenty/assets/19412894/9c85e654-a878-46a9-a070-9924a7bdf098)

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=19118-196797&mode=design&t=ZRf0c7Ey66nuhFnZ-11

**Comment by Bonapara** [comment]
Thanks @Kanav-Arora!

**Comment by FelixMalfait** [comment]
@Kanav-Arora do you think you can tackle this with previous feedback? Thanks 🙏

**Comment by Bonapara** [comment]
@Kanav-Arora I just unassigned you but tell me if you want to pick it up again. Thanks!

**Comment by ehconitin** [comment]
@Bonapara 
Add record should be fairly easy as it was already done in #6649 
I had questions regarding hide button.
How would user unhide the stage?
presently user can hide/unhide fields 


![Image](https://github.com/user-attachments/assets/9361bba9-585a-48e9-8fa5-edd59bc422ee)

But this new hide/unhide would be on stages right?

**Comment by Bonapara** [comment]
Hi @ehconitin! It's related to https://github.com/twentyhq/twenty/issues/4356

**Comment by ehconitin** [comment]
Got it!
Thanks 👍🏻

**Comment by FelixMalfait** [comment]
@ehconitin see comment here for implementation details https://github.com/twentyhq/twenty/pull/4640#issuecomment-2036856758 ; not sure if you did any backend yet, this requires changing the data model

But since then I changed my mind. I think adding a JSONB is not a great practise, and there's a way to build something more generic as that notion of "grouping" we need for kanban could also be useful to listViews.

So instead now I would create a new object ViewGroup that would be very similar to ViewField in its implementation.

**Comment by charlesBochet** [comment]
The backend is not there yet
@ehconitin do you need assistance on the backend or you can take care of it too?

@FelixMalfait could you explain a bit more what you have in mind for ViewGroup from a product perspective and how you would use it for this case?

As a reminder this is our view database structure
<img width="827" alt="image" src="https://github.com/user-attachments/assets/9e4558d5-4b7b-4c1e-beeb-c58f0203e14a">

**Comment by ehconitin** [comment]
@charlesBochet 
I would need some help with backend, just to get me started!
I’m slowly getting the hang of it !

**Comment by charlesBochet** [comment]
In a nutshell:

1) View Group Object
- you'll need to create a view-group.workspace-entity.ts (similar to view-field). This will be the code representation of the standard object
- then new workspaces will have it (on sign up), when you seed workspaces too. For existing ones, you'll need to sync-metadata to get it

2) View Group Object Record
- You'll need to add seed data for your new object (you can take inspiration on viewFIeld). Here are the case too tests: seed:dev and seed:demo
- you'll need to add prefill data for your new object for new workspaces. You can test it by signing up
- you'll need to add this data to existing workspaces, to do that please create a migrate-0.31 command. You also have example in the code

that should be it all the rest should be dynamically and automatically generated by the engine

**Comment by FelixMalfait** [comment]
From a product perspective what I meant is that it isn't just a kanban problem, groups could be useful to other types of views. 

For example in Notion, it can be used on ListViews
<img width="348" alt="Screenshot 2024-09-16 at 17 29 05" src="https://github.com/user-attachments/assets/4d6b2f08-e29c-4fba-8c4b-4ad9bc0317d9">

It then becomes the exact same principles as for kanbans. The only difference is that we don't have auto-load but we have a "load more" button under each group if they are more than 20 records

@ehconitin assigning this to you for later, no rush! happy to answer any question you have as this isn't an easy task

**Comment by Bonapara** [comment]
![image](https://github.com/user-attachments/assets/b9c3f383-0337-4fcf-948a-4fd8f0f4e23b)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=39994-147104&node-type=frame&t=ORiKleP9aYfoCt0X-11

**Comment by Bonapara** [comment]
https://github.com/user-attachments/assets/453313a5-0aaa-4f99-b02a-e736340dec10

Settings part → https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=40011-268035&node-type=frame&t=vjg6Ofev4bkaijG1-11
