### ISSUE TITLE
Change duplicate formula from ILIKE to strict match

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4268]
https://github.com/twentyhq/twenty/blob/main/packages/twenty-server/src/workspace/workspace-query-builder/factories/find-duplicates-query.factory.ts#L123

I think we should change this to a strict equality check because it causes false positive.

Also I've received an email from one our users who had many false matches, their contacts that had "-" as LinkedIn URLs instead of leaving the URL empty. I feel like we could also add a min of 3 letters for it to be taken into account, but I'm not 100% sure it's a good idea. What do you think @rostaklein? Do you see any downside to it?

**Comment by rostaklein** [comment]
Makes sense :) Prepared a PR here https://github.com/twentyhq/twenty/pull/4273
