### ISSUE TITLE
Create calendarEventAttendee data model 

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#4283]
## Scope & Context

We are implementing the google calendar integration.

## Technical inputs

Create calendarEventAttendee data model:
- **eventId**: uuid
- **handle**: string
- **displayName**: string
- **isOrganizer**: boolean
- **personId**?: uuid (ONE TO MANY)
- **workspaceMemberId**?: uuid (ONE TO MANY)
- **responseStatus**: string

In V2 maybe:
- **optional**: boolean default **false**

**Comment by Weiko** [comment]
- remove externalId we don't need the attendee id
- rename email by handle to align with messages
