### ISSUE TITLE
[Timebox] Create google calendar full-sync

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#4285]
## Scope & Context

We are implementing the google calendar integration.

## Technical inputs

[https://developers.google.com/calendar/api/guides/sync](https://developers.google.com/calendar/api/guides/sync)

Similar to emails.

- Create a `calendar` folder in `packages/twenty-server/src/workspace`.
- Create repositories to interact with calendar data
- Create a google-calendar-full-sync service
- Create a job
- Call the job after the creation of a connected account
- Save **nextSyncToken** after completing full-sync (only present on the last page)

**Comment by Weiko** [comment]
Add nextSyncToken to CalendarChannel
