### ISSUE TITLE
Enforce consistent function style across repo

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#429]
I think the steps would be the following:

Step 1. Add "func-style":['warn', 'declaration'] to rules in .eslintrc.js
Step 2. Fix issues across the repo

(Reference: https://eslint.org/docs/latest/rules/func-style)

**Comment by Morning1139Angel** [comment]
hi ! I am kind of a new developer ... but this seems like something I would be able to do ! I would love to try to do it !

**Comment by FelixMalfait** [comment]
@Morning1139Angel  I saw your message before you removed it ;-). Happy to help and guide you if you're stuck! 
We're setting up a Slack workspace this week: https://twenty.com/slack we can also discuss there

**Comment by Morning1139Angel** [comment]
hi again :DDD thanks alot ! this is also related to my college web dev course so I had to first get my instructor's approval thats why I deleted the message first :")))) .... but hey ! they agreed ! and I would love to help ! will start working on it right away ! thx alot for the kindness ! Ill be sure to ask my questions if I feel stuck <3 @FelixMalfait

**Comment by FelixMalfait** [comment]
@Morning1139Angel 
Great! Thanks! I assigned you this issue.
The eslint might cause a lot of errors so it might be a bit painful to fix, unless maybe "--fix" works for that rule? But I don't think so. 
At least it'll make you read a lot of files so that's good for your we dev course / learning by seeing things 😅

**Comment by Morning1139Angel** [comment]
@FelixMalfait hi again ! 
so been working on this for a while...as u have guessed the --fix doesnt work :"))) ...about only 15 more cases left to convert and thought Id give u an update and discuss a  few things... 
1 - I did use the rule func-style":['warn', 'declaration'] as u asked and converted every thing to function deceleration...but I was wondering if also allowing arrow functions  would be a bad idea or not ? ...cuz like Ive kinda wondered around and found this :https://github.com/typescript-eslint/typescript-eslint/blob/ca41dcf6c0fbfc19975b18ffb5b44c0cbe8adb06/packages/eslint-plugin/ROADMAP.md which recommends : ["error", "declaration", { "allowArrowFunctions": true }] ...
2- kinda related to arrow functions again .... In some places there arrow functions where declared with a given function type like for example this : 
```
const MockedAuth: React.FC<React.PropsWithChildren> = ({ children }) => {
  const [, setCurrentUser] = useRecoilState(currentUserState);
  const [, setIsAuthenticating] = useRecoilState(isAuthenticatingState);

  setCurrentUser(mockedUsersData[0]);
  setIsAuthenticating(false);

  return <>{children}</>;
};
```
and I dont know really how one would convert that to a function declaration while still keeping the type assigned to the function...I have yet not touched these ...
3-funny enough but eslint doesnt check this func-style rule for returned functions and I think call back ones like in here this is allowed :
```
function cookieStorageEffect(key: string): AtomEffect<AuthTokenPair | null> {
  return ({ setSelf, onSet }) => {
    const savedValue = cookieStorage.getItem(key);
    if (savedValue != null && JSON.parse(savedValue)['accessToken']) {
      setSelf(JSON.parse(savedValue));
    }

    onSet((newValue, _, isReset) => {
      if (!newValue) {
        cookieStorage.removeItem(key);
        return;
      }
      isReset
        ? cookieStorage.removeItem(key)
        : cookieStorage.setItem(key, JSON.stringify(newValue));
    });
  };
}
```

**Comment by magrinj** [comment]
Hello @Morning1139Angel, and thanks a lot for your help !

Regarding your last message, I think we should allow `allowArrowFunctions` and use the proper type for all the react component, I mean by that `React.FC` as it's the official type for component and allow the use of properties like `displayName`, `defaultProps`.

At first this one was tagged as shouldn't be used, because it [implicitly include children in the props](https://juhanajauhiainen.com/posts/should-you-use-reactfc-to-type-your-components).
But now it's fixed, and it's not the case anymore since React 18.

So, in my opinion using the official `React.FC` type is a good option and for that we need arrow functions.

What is you opinion about that @FelixMalfait, @charlesBochet, @lucasbordeau ?

**Comment by charlesBochet** [comment]
We should make a decision on the overall codebase if we want to use
```
 function doSomething({ children }: PropType) {
    // ...
}
```
or 
```
const doSomething: React.FC<React.PropsWithChildren> = ({ children }) => {
 //
};
```
and apply it across the whole codebase.

I personally find the first option more readable and we could argue that this will make the product easier to contribute to. So I would advocate for it unless we are convinced there is a real utility in option 2

Regarding displayName and defaultProps, I am not sure to see the value either: 
- defaultProps can be replaced by default parameters: function doSomething({ prop1 = 'xxx', prop2 = 'yyy' }: PropType)
- displayName doesn't seem to be particularly useful IMO

**Comment by magrinj** [comment]
@charlesBochet `displayName` can be really useful when debugging react three

In my opinion React.FC ensure the return type of the component, and avoid missing providing `JSX.Element` in the return signature.
Providing the return type avoid some mistakes 🙂

**Comment by Morning1139Angel** [comment]
ok so for now Ill make a new branch and do this for it  :  ```["warn", "declaration", { "allowArrowFunctions": true }] ``` and fix the code for it and do a PR ... if u guys decided only declerations is better then Id go ahead with that ...
and hey ! this became way more interesting than I thought it would be :DDD  ... its quite intriguing to me to see ur different reasoning for wanting to keep this or not so yeah ! awesome :))

**Comment by charlesBochet** [comment]
Closing this issue has PR has been merged.
Thanks @Morning1139Angel. Let us know if you want to contribute more!
