### ISSUE TITLE
Add emails seed data for demo and dev seeds

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#4298]
## Scope & Context

We have recently released the email sync feature. It would be great to add some fake data : 
- to our dev seeds to help developers work on email related features
- to our demo seeds to demonstrate it on app.twenty.com / Demo account

## Technical inputs

For Dev Seeds:
- do something similar to `packages/twenty-server/src/database/typeorm-seeds/workspace/companies.ts`

For Demo seeds:
- do something similar to `packages/twenty-server/src/workspace/workspace-manager/demo-objects-prefill-data/companies-demo.json
`

You'll need to fill several models: connectedAccount, messageChannel, messageThread, messageChannelMessageAssociation, message, messageParticipant

**Comment by hannafeddersen** [comment]
I would like to work on this issue :) @charlesBochet

**Comment by hannafeddersen** [comment]
I would like to work on this Issue :)

**Comment by charlesBochet** [comment]
sure thank you @hannafeddersen :)

**Comment by 3llla** [comment]
@charlesBochet could you assign me?

**Comment by charlesBochet** [comment]
sure! Thank you :)

**Comment by hannafeddersen** [comment]
I created a pull requestto add the dev seed data [https://github.com/twentyhq/twenty/pull/4513](url)

**Comment by charlesBochet** [comment]
This has been done! Thank you!
