### ISSUE TITLE
OnMultiSelectPicker, changes are persisted only when leaving the input + put back the previous value if nothing is selected while leaving

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#431]
- Change the MultiSelectPicker behavior to persist changes to data only while leaving (click outside, tab, enter)
- add an option required={true|false}
- if required=true, put back the previous value if nothing is selected while leaving the field and do not persist

**Comment by Bonapara** [comment]
Solution: prevent closing the relation picker if no relation is left/selected. 
Would it be costly?
