### ISSUE TITLE
Inline Select field fixes

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4311]
# Current behavior

- No "Empty" Placeholder is displayed when no option is selected
![CleanShot 2024-03-05 at 12 38 43](https://github.com/twentyhq/twenty/assets/19412894/a104a2b5-0a2f-48ae-aa95-c59b06eaf2ac)

We can't close the option menu by clicking outside of it:
https://github.com/twentyhq/twenty/assets/19412894/cd5c5c05-909a-4724-b76a-34cbc053dc59

# Desired Behavior

- We should display an "Empty" placeholder
- Clicking outside should close the option menu

Related: #3656

**Comment by 609harsh** [comment]
Hello @Bonapara Please assign this issue to me

**Comment by Bonapara** [comment]
Done, thanks for contributing @609harsh!

**Comment by Bonapara** [comment]
Has been implemented
