### ISSUE TITLE
Add storybook tests on ObjectFilterDropdownOptionSelect

### ISSUE THREAD

**Issue by thomtrp** [twentyhq/twenty#4316]
## Scope & Context

Follow-up on this PR: https://github.com/twentyhq/twenty/pull/3656
New components have been added without any storybook test. 

## Technical inputs

File paths are the following:
- packages/twenty-front/src/modules/ui/navigation/menu-item/components/MenuItemSelectTag.tsx
- packages/twenty-front/src/modules/object-record/object-filter-dropdown/components/ObjectFilterDropdownOptionSelect.tsx

**Comment by themujahidkhan** [comment]
I want to work on this. Can you assign it to me?

**Comment by anoopw3bdev** [comment]
Hi @thomtrp I took a look the folders, none of the components in packages/twenty-front/src/modules/object-record/object-filter-dropdown/components have a story, ideally when we create a new component we should write the respective story too?

**Comment by ZichenMen** [comment]
I'm going to work on this issue.

**Comment by clrminded** [comment]
I will be working on this issue as well.

**Comment by BalanaguYashwanth** [comment]
Hello @thomtrp,

- MenuItemSelectTag -  already story exists for this component

- ObjectFilterDropdownOptionSelect - related to `object-filter-dropdown` folder, there are no stories written in it.

- So can you close this issue and create separate issue to `write stories for **object-filter-dropdown** folder`

**Comment by charlesBochet** [comment]
@BalanaguYashwanth Thanks for checking, I have renamed the issue

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by rashap224** [comment]
Hi @thomtrp Can you explain a bit about this issue. I am curious to know and work on it.

**Comment by Khaan25** [comment]
Hey @charlesBochet, Can I work on this?

**Comment by charlesBochet** [comment]
sure

**Comment by Khaan25** [comment]
Hey @charlesBochet, I've created story and only imported the component to see but I'm getting this error? Do we've some providers to wrap around the story in decorators?
![image](https://github.com/user-attachments/assets/b95e9a51-e8be-412a-86e4-e64007eb117e)

**Comment by FelixMalfait** [comment]
From @charlesBochet on the PR:

> I have taken a close look, looks like the ObjectFilterDropdownOptionSelect component is coupled with many things: 4 recoil states + parent dropdown + selectableList + object filter dropdown. Which is typical from an internal component that is not meant to be used of its context.
> 
> Because of that, I don't think it makes a lot of sense to test it as a standalone.
> 
> Instead, we should add more cases (including the Select field type here) to multiplefiltersdropdownbutton story
