### ISSUE TITLE
Invite team members by email

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#432]
Email template that a teammate will receive when invited to join its organization workspace

![Image](https://github.com/twentyhq/twenty/assets/19412894/09a9b69a-86a7-4809-9812-b15444127823)
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=4162-56708&mode=design&t=SEFgiMdVeuQAfxfM-4

**Comment by FelixMalfait** [comment]
Lib that might be relevant for our first email template: https://github.com/resendlabs/react-email (cc @charlesBochet if you have an opinion)

Small implementation details:
*  The address is incorrect.
Our postbox is:
2261 Market Street #5275
San Francisco, CA 94114
* dash between user/friendly (+ we're introducing yet another description haha, but that can be debated later, let's keep this for now)
* If the workspace doesn't have a logo, then don't display anything

**Comment by Bonapara** [comment]
Closing this issue as depreciated
