### ISSUE TITLE
Navigation menu item icons should be bolder

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4321]
# Current behavior

Icon stroke weight is light
![CleanShot 2024-03-05 at 17 45 37](https://github.com/twentyhq/twenty/assets/19412894/1a4ca9c4-07cc-487e-824f-9667a6b68d91)

Same thing in Settings
![CleanShot 2024-03-05 at 17 48 47](https://github.com/twentyhq/twenty/assets/19412894/99823df0-cdaa-40e6-bfa4-563dce6f148e)

# Desired Behavior

Icon stroke should be medium to fit with the font-weight:
![CleanShot 2024-03-05 at 17 47 15](https://github.com/twentyhq/twenty/assets/19412894/e896060e-7f13-4ef9-84ee-247824b88401)

Fix the settings accordingly.

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5910-77814&mode=design&t=pco7kMQF3KPgiZHv-11

**Comment by shree-1788** [comment]
Hey @Bonapara I'd like to work on this issue?

**Comment by zaryanz** [comment]
Hi @Bonapara! The following pull request fixes this issue:

https://github.com/twentyhq/twenty/pull/4331

Thanks!
