### ISSUE TITLE
Make Select Field filter (ViewBar) and Select Field Input navigable via keyboard arrows

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#4322]
## Scope & Context

We have recently merged https://github.com/twentyhq/twenty/pull/3656 
This ticket is about making two components: `SelectFieldInput` and `ObjectFilterDropdownOptionSelect` navigable via arrows.

## Technical inputs

Implement SelectableList. Implement it in MenuItemMultiSelect and in SelectFieldInput. There are already a few example of this being implemented in the code base

**Comment by khareyash05** [comment]
Hi Can I take up this ?

**Comment by charlesBochet** [comment]
@khareyash05 sure, thank you!

**Comment by Nabhag8848** [comment]
@charlesBochet working on it. also we just need to fix viewBar cause select field input is already navigable now.

**Comment by charlesBochet** [comment]
Indeed! Thank you!

**Comment by Nabhag8848** [comment]
Hey @charlesBochet I think this will be solved in issue #4365 on which someone is already working on - PR #6613 we should close this one.
