### ISSUE TITLE
Magic link email template

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#433]
The email a user will receive if he doesn't sign up with Google and has an email server configured / using the cloud version.

![Image](https://github.com/twentyhq/twenty/assets/19412894/b5eec574-6bca-45b0-819f-ff797260acef)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=4162-56741&mode=design&t=SEFgiMdVeuQAfxfM-4

**Comment by FelixMalfait** [comment]
Merging with issue 380 for now
