### ISSUE TITLE
Adapt skeleton loading on picker

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#434]
The loading should be:

1) Display one line with either a skeleton loading or the content of the cell which has just been clicked. 
![image](https://github.com/twentyhq/twenty/assets/19412894/0afc749d-c876-4ebe-bd8d-63a6ad482aea)
2) Load the other results and insert them:
![image](https://github.com/twentyhq/twenty/assets/19412894/32eb9005-005b-4ae8-a29e-5ece74c6e378)

Adapt the actual skeleton loading to it's:
- Lighter (Background tertiary)
- 16px heigh but their container 32px so they match a usual result size to avoid blinking

Ask me if you need some explanations.

**Comment by FelixMalfait** [comment]
The tricky part is that the skeleton should be 1 line initially then have the same number of lines as the previous number of results. We can't just stick to skeleton = 1 line if we want it to look nice, it would cause "flash images" for each character you type. OR other solution would be to display skeleton only when no character is typed and not when string.length >= 1 (which isn't the current behavior), but it's probably not as nice

**Comment by Bonapara** [comment]
This one-line skeleton is indeed for the **opening loading**, once the menu is opened, loading should behave differently. We should wait to get results before replacing the first results with the new one, without loading.

https://github.com/twentyhq/twenty/assets/19412894/fa98c875-7dc6-4286-aaf1-a61d9d4f2603

oading. See Notion for full behavior:
