### ISSUE TITLE
Improvement to comments: timestamp and display option

### ISSUE THREAD

**Issue by majorproblem** [twentyhq/twenty#4340]
## Scope & Context

Adding a comment to tasks has turned out to be very important to create traceability. For this to work I need a date for the comment, as well as visibility, and that I have done manually.

It would be nice if this was automated somehow.

## Current behavior

When I add a comment to a task it gets appended to the end of the list of comments. When I look at the list of tasks, the only comment visible is the first in the list, not the last one.

## Expected behavior

I would like a comment to have an automatic date inserted in the beginning:

```
23-03-06: <cursor should be here>
```

When it comes to the display it would be very nice if the comment shown in the task list is the last in the list, i.e., the latest.

With theses changes i can see at a glance from the task list the latest comment to a task, as well as the date for this.

```
O Schedule a meeting with Fubar 23-03-06: Emailed them again…
```

## Technical inputs

None

**Comment by FelixMalfait** [comment]
Closing as we deprecated comments, it wasn't mature enough. We'll bring it back one day but it needs to be more powerful
