### ISSUE TITLE
Unable to open email content on Show page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4341]
# Bug

When clicking on an email on the show page, the side panel opens but the email content does not load:

![CleanShot 2024-03-06 at 15 52 42](https://github.com/twentyhq/twenty/assets/19412894/e8a9be84-57cf-4b59-81e7-ba79c2a05af0)

The error hasn't been logged in Sentry

**Comment by dev-DTECH** [comment]
Hey @Bonapara, I would like to work on this issue.

**Comment by Bonapara** [comment]
Thanks for contributing @dev-DTECH!
