### ISSUE TITLE
Align the view switcher icon on the table checkboxes

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4351]
# Current behavior

The view switcher icon is not aligned with the table checkboxes 

![CleanShot 2024-03-06 at 19 05 26](https://github.com/twentyhq/twenty/assets/19412894/99528787-46cc-49d0-ab26-e5659461c5bd)

# Desired behavior

The view switcher icon should be centered above the checkboxes

![CleanShot 2024-03-06 at 19 07 38](https://github.com/twentyhq/twenty/assets/19412894/f07d405c-4fa9-4eb4-bed8-5df7e51e363b)

![CleanShot 2024-03-06 at 19 15 15](https://github.com/twentyhq/twenty/assets/19412894/fcc034d7-ea32-4934-926a-1e1cdd384443)

Make sure to keep the kanban column header name aligned with the view switcher icon:

![CleanShot 2024-03-06 at 19 22 12](https://github.com/twentyhq/twenty/assets/19412894/6611d077-d072-4f9a-9fc7-2534d7c7307b)

# Figma

Inspect the Figma to get the good dimensions:

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=1406-44830&mode=design&t=sNBVaMdbaG082qYQ-11

**Comment by mayixiaobai248** [comment]
Hi, Could I be assigned to this issue? Thanks

**Comment by mayixiaobai248** [comment]
Hi! Can you assign this issue to me?

**Comment by kevin-wu01** [comment]
hello! can I take this issue?

**Comment by Bonapara** [comment]
Just assigned you, thanks @kevin-wu01!

**Comment by Palabhishek18** [comment]
hello can I take this issue

**Comment by Bonapara** [comment]
@kevin-wu01, are you still working on this? If not, @Palabhishek18, you can start. Thanks to both of you!

**Comment by kevin-wu01** [comment]
Yeah I got started on a fix, but currently going thru some dev environment problems

**Comment by Palabhishek18** [comment]
can you tell me the location of this file and when I use yarn in terminal it give me error

**Comment by rathodvinod5** [comment]
@Bonapara is this issue resolved? or can you assign this to me? I will be happy to resolve this issue.

**Comment by Bonapara** [comment]
@rathodvinod5, I can assign this task to you, but it's related to https://github.com/twentyhq/twenty/issues/4906, which needs to be completed first. @kevin-wu01, I'm unassigning you as it's been a month. Thanks to you both!
