### ISSUE TITLE
Implement a masked currency input

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#4358]
## Scope & Context

Currency input.

## Current behavior

The input only supports raw text.

## Expected behavior

We want a masked input that adapts to the currency : 

![currency_input_demo](https://github.com/twentyhq/twenty/assets/26528466/9dfe8ffd-573f-4259-bae2-85dfb122775e)

We should benchmark existing libraries while keeping in mind that : 
- The masked input should handle the different currencies we have : USD, EUR, YUAN, ... Because every currency behaves differently with thousands/hundreds separators.

Resources : 
- https://www.nicknish.co/blog/react-currency-input
- https://www.npmjs.com/package/@react-input/mask
- https://sanniassin.github.io/react-input-mask/demo.html

**Comment by FelixMalfait** [comment]
@gitstart-twenty assigning to you since you mentioned you're implementing `react-imask` already. Just aim for something simple and quick in edit mode, should take 1 line only to change probably! https://imask.js.org/ I see they have input type

**Comment by lucasbordeau** [comment]
@gitstart-twenty `react-imask` is a good library for this, yes.
