### ISSUE TITLE
Correct right margin + container padding on Show

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4359]
# Current Behavior

1. The right margin is 12px instead of 8px
2. There is an unwanted right margin on the fields panel

![CleanShot 2024-03-07 at 16 51 50](https://github.com/twentyhq/twenty/assets/19412894/b9e287ff-b066-4dda-afd2-49839733b442)

# Desired behavior

Set the right margin to 8px and remove the right margin of the left fields panel:

![CleanShot 2024-03-07 at 17 16 58](https://github.com/twentyhq/twenty/assets/19412894/04f6e1d9-5d4f-429f-a74f-3802dc44cbac)

**Comment by ijayhub** [comment]
Is it still open? @Bonapara

**Comment by brendanlaschke** [comment]
> Looks like @brendanlaschke you're on it?

Yes the overlay scroll pr should fix it (if we decide to merge it ;) )

**Comment by Bonapara** [comment]
@ijayhub I think you can still create a PR for point 1!

Thanks to you both :)
