### ISSUE TITLE
Create a client config function that is retrieved when app is loaded

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#436]
**Issue:** 
On the frontend we don't always have access to config parameters from the backend.
For example, to prefill the login/password in local env I had to check node_env.
Or if tomorrow we want to hide the Google sign-in button if Google Auth parameters weren't filled in server.env

**Backend:**
- Create graphQL field named clientConfig  (resolver)
-  It could return could be something like this
```
{
  "flags": {
     "display_google_login":  process.env.AUTH_GOOGLE_CLIENT_ID !== ...
     "prefill_login_with_seed": process.env.NODE_ENV === ...
  }  
}
```

**Frontend**
- Do a request to load this clientConfig when app is loaded (no need to refresh automatically or implement any complex behavior, loading once when app is loaded is enough)
- Create a client config module with a provider that apps can access to retrieve config (it's better to abstract with a module that using recoil directly to retrieve the module, cf userProvider which I think was done this way already)

**Comment by FelixMalfait** [comment]
Probably a bit difficult for a first issue but adding the flag if anyone feels brave 😄

**Comment by deepaksing** [comment]
Hi, @FelixMalfait, can you assign this issue to me. I would like to work on this.

**Comment by FelixMalfait** [comment]
Thanks @deepaksing, done!

**Comment by deepaksing** [comment]
> {
>   "flags": {
>      "display_google_login":  process.env.AUTH_GOOGLE_CLIENT_ID !== ...
>      "prefill_login_with_seed": process.env.NODE_ENV === ...
>   }  
> }

@FelixMalfait, both **display_google_login** & **prefill_login_with_seed** should be boolean values?
