### ISSUE TITLE
Add Syncing synchronization status

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4362]
## Current behavior 

As soon as I connect my account, it's marked as synced, even if the sync process has just begun.
<img width="550" alt="Screenshot 2024-03-07 at 17 31 24" src="https://github.com/twentyhq/twenty/assets/6399865/8560cd83-50b7-4982-ae05-36f2ded4eb2d">

## Desired behavior 

<img width="541" alt="Screenshot 2024-03-07 at 17 33 57" src="https://github.com/twentyhq/twenty/assets/6399865/e0cf1056-9096-45cd-810c-368376de1c1f">

## Technical details
We need to:
- introduce a column `isInitialSyncCompleted` on the `messageChannel` table 
- display syncing status instead of `synced` if `!isInitialSyncCompleted`

**Comment by FelixMalfait** [comment]
Of course! thanks @PepeGonzale 
Not sure if you've touched the backend yet, we've got our own engine that takes metadata config files and runs the required migrations. You can simply do a database reset after you've edited the object-metadata file to add the column

https://github.com/twentyhq/twenty/blob/main/packages/twenty-server/src/workspace/workspace-sync-metadata/standard-objects/message-channel-message-association.object-metadata.ts

**Comment by FelixMalfait** [comment]
OK backend has been done. Field is now called "syncSatus" and automatically updated
This should be easier now :)

**Comment by i-am-chitti** [comment]
@PepeGonzale Have you started working on this?
If not, @FelixMalfait, you can assign this to me? I'll work. 

One doubt, how do I test this specifically make the backend into the syncing state for the pre-filled email?

**Comment by FelixMalfait** [comment]
Thanks @i-am-chitti! This should be a quick issue as I see most of the work is already done. 
No need to check the status change on server side it should work already hopefully!

Check MessageChannelSyncStatus on server side and SettingsAccountsCalendarChannelsListCard
