### ISSUE TITLE
Modify the Fields menu in tables and Kanbans Options menu.

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4363]
## Updated behavior

1. Both visible and hidden fields appear in one menu.
2. The first row has an alignment issue with the missing grip icon.
3. No button allows accessing object settings to edit fields.
4. The menu width is too narrow.

![CleanShot 2024-03-07 at 17 38 05](https://github.com/twentyhq/twenty/assets/19412894/74a5e878-4094-4ee1-9ae1-6bf287137b6e)

5. The light icon button doesn't look properly aligned with the text
![CleanShot 2024-03-07 at 17 43 24](https://github.com/twentyhq/twenty/assets/19412894/18f9edc7-6854-467b-98b9-265f327a9293)

# Desired Behavior

1. We want to change the hide/show icon from a "-/+" to an eye/eye-off:
![CleanShot 2024-03-07 at 17 38 29](https://github.com/twentyhq/twenty/assets/19412894/387644f6-3133-42cb-91f0-80eadb55166f)

2. Clicking on "Hidden fields" should navigate to a second menu with hidden fields:
![CleanShot 2024-03-07 at 17 47 49](https://github.com/twentyhq/twenty/assets/19412894/8933934e-f0d5-49ee-84cf-a5e5e7a3d4e5)
3. The menu width should be set to 200px.

4. We want to add a button on hidden fields menu that goes to the object settings page
![CleanShot 2024-03-07 at 17 41 33](https://github.com/twentyhq/twenty/assets/19412894/21e35eee-d8f3-4f39-9ddd-7e6106828100)

5. We want to implement a "Disabled" state for the grip menu item that displays a light grip icon:
![CleanShot 2024-03-07 at 17 42 31](https://github.com/twentyhq/twenty/assets/19412894/104e002b-58c1-4966-bbda-61be5048928b)

6. Align vertically the light icon button and the text:
![CleanShot 2024-03-07 at 17 46 08](https://github.com/twentyhq/twenty/assets/19412894/0b9c5307-12be-4a08-8cf0-a878682afa0f)

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=6377-158599&mode=design&t=LORfESmPs8dJ3RY2-11

**Comment by Bonapara** [comment]
Sure, thanks for contributing @PepeGonzale!

**Comment by kiridarivaki** [comment]
i see this is still open, can i get assigned? i am currently trying to familiarize with the project, so i would appreciate if you confirm if one of the corresponding files is RecordIndexOptionsDropdownContent.tsx

**Comment by charlesBochet** [comment]
Yes it is @kiridarivaki :)

**Comment by kiridarivaki** [comment]
Can i work on this?

**Comment by Bonapara** [comment]
Sure @kiridarivaki, thanks for contributing!

**Comment by FelixMalfait** [comment]
@Bonapara I'm closing this but would you mind re-creating  a new issue just for the disabled state (first column)? The rest has been tackled as you can see on `app-main`

**Comment by Bonapara** [comment]
https://github.com/twentyhq/twenty/issues/5653
