### ISSUE TITLE
Display tags in multi-select picker

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4364]
# Current behavior

The tags are not displayed in the Select picker:
![CleanShot 2024-03-07 at 18 00 34](https://github.com/twentyhq/twenty/assets/19412894/ba27f7df-e763-497d-a5c8-0fd7ef9c67e1)

# Desired Behavior

We want to display the (colorful) tags!
![CleanShot 2024-03-07 at 18 02 15](https://github.com/twentyhq/twenty/assets/19412894/5660aaec-715f-4215-b878-c6100fb7eed0)

**Comment by Anchit1909** [comment]
Hey @Bonapara, I would like to work on this. Could you please assign this issue to me?

**Comment by Bonapara** [comment]
Done, thanks for contributing @Anchit1909!
