### ISSUE TITLE
The whole Ascending/Descending menu should be clickable

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4366]
# Current Behavior

I have to click on the icon button to open the sorting order menu
![CleanShot 2024-03-07 at 18 14 43](https://github.com/twentyhq/twenty/assets/19412894/daec41af-f517-402e-be0c-197b8bbe0c63)

# Desired Behavior

Clicking on the entire cell should open the sorting order menu. Additionally, there should be a hover effect on the menu:

https://github.com/twentyhq/twenty/assets/19412894/6daeb915-c0e7-442f-b9da-998df05ba3d8

# Figma

![image](https://github.com/twentyhq/twenty/assets/19412894/feeeac37-e3c3-46c5-9ee0-2d466ff049e2)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=2979-174004&mode=design&t=LORfESmPs8dJ3RY2-11

**Comment by Anchit1909** [comment]
Hey @Bonapara, I would like to work on this. Could you please assign this issue to me?

**Comment by Bonapara** [comment]
@Anchit1909 thanks for contributing. Yes!
