### ISSUE TITLE
New Datetime field picker

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4376]
# Current Picker

![CleanShot 2024-03-08 at 16 10 45](https://github.com/twentyhq/twenty/assets/19412894/0286f647-3220-4837-9a74-ecad57cfe608)

# Desired Behavior

1. We need to add a field that shows the selected date. This field should be editable using the keyboard. The calendar picker below should adjust when the date in the field is changed.

This field should appear above the cell, mimicking the behavior of other fields:

![CleanShot 2024-03-08 at 16 38 37](https://github.com/twentyhq/twenty/assets/19412894/8ecef246-49dd-4f74-ae9a-cd522e91737f)

2. We aim to add a 'Time' field set to midnight by default, only editable via keyboard input. Only numerical input will be accepted, adapting to the user's chosen date format.

![CleanShot 2024-03-08 at 16 15 47](https://github.com/twentyhq/twenty/assets/19412894/16630e29-a9aa-4ea3-a361-c5c60fc16fe9)

### Small calendar behavior

Clicking the calendar icon button should open a menu with two dropdowns that allow easy navigation to a specific month or year:

https://github.com/twentyhq/twenty/assets/19412894/2bf750ab-82a7-46ab-969c-e40329562a1e

### Settings

We want to rename this field type "Date and Time" and associate it to the [calendar-time](https://tabler.io/icons/icon/calendar-time) icon.

![CleanShot 2024-03-08 at 16 32 39](https://github.com/twentyhq/twenty/assets/19412894/916931f4-609d-4784-a6e3-b383b4114ffc)

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=2709-52753&mode=design&t=VIGvBjH3RmxJw3iZ-11

**Comment by symrin** [comment]
Hi, could I please take this up?

**Comment by Bonapara** [comment]
Sure, thanks @symrin!

**Comment by dragos-cojocaru** [comment]
Do we want to have a separate new component with these specs or do we want these new specs to be a variant of the existing component? @Bonapara 

I ask this because in Figma I see we have two components: Datetime and Date, which are quite different.

**Comment by Bonapara** [comment]
Hi @dragos-cojocaru, I think this can be a variant of the existing component indeed, one variant for `date` and one variant for `Datetime`

**Comment by symrin** [comment]
Hi @Bonapara, I can see currently a metadata type - datetime is being used for all date objects. After this requirement, will all these dates use the Datetime variant then?

**Comment by Bonapara** [comment]
Exactly, @symrin, 
Thanks!
