### ISSUE TITLE
[Timebox] Companies "People count" broken when adding another People field

### ISSUE THREAD

**Issue by iero** [twentyhq/twenty#4385]
When I add a Founders field with "People" type, it cannot calculate the number of people

Here is my data model with a new "Founders" field :

![shot 2024-03-08 at 21 27 10](https://github.com/twentyhq/twenty/assets/2870245/73fdcdb7-0981-4821-a6aa-425c1de0f889)

Here the Company see the Founder but not People (count 0)

![shot 2024-03-08 at 21 24 43](https://github.com/twentyhq/twenty/assets/2870245/5e7f46bc-b33c-4f78-8cee-9d00aebe68f2)

But there are some :

![shot 2024-03-08 at 21 24 04](https://github.com/twentyhq/twenty/assets/2870245/12b6eccd-b40b-4d2e-8e4a-f1e46d13007d)

**Comment by martmull** [comment]
Looks like count is broken even without additional relation field
