### ISSUE TITLE
Implement hotkeys scope for DoubleText

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#439]
Now that everything is optimized for hotkeys on table, to avoid rerenders, we can safely implement hotkeys scope for particular inputs.

A good simple use case would be to implement it on EditableDoubleText, we need to have tab / shift+tab to navigate between the two inputs, but to still keep switching to other EditableCells if we do 2 times tab or shift+tab. 

So we have to override tab and shift+tab hotkeys behavior on this specific scope.

https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/disable-hotkeys

**Comment by charlesBochet** [comment]
Is it related to https://github.com/twentyhq/twenty/issues/372?

**Comment by lucasbordeau** [comment]
No initially but we should check

**Comment by lucasbordeau** [comment]
Completed in https://github.com/twentyhq/twenty/pull/581
