### ISSUE TITLE
Filter/Sort labels should be medium instead of bold

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4394]
# Current behavior

Font-weight is bold

![CleanShot 2024-03-11 at 10 24 06](https://github.com/twentyhq/twenty/assets/19412894/36753c1a-1204-4cff-8928-d750436bea30)

# Desired Behavior

Font weight should be `500`:

```
color: var(--Palette-Blue, #1961ED);
leading-trim: both;
text-edge: cap;

/* Base/Small/Medium */
font-family: Inter;
font-size: 12px;
font-style: normal;
font-weight: 500;
line-height: 150%; /* 18px */
```

![CleanShot 2024-03-11 at 10 19 40](https://github.com/twentyhq/twenty/assets/19412894/844e19ab-40ae-4da6-a5cd-03c66ea839a2)

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=808-58800&mode=design&t=TfgOb9tmSY4z3hyb-11

**Comment by pojith** [comment]
/assign me
i can solve this issues

**Comment by Bonapara** [comment]
@pojith, Done. Thanks for contributing!

**Comment by Bonapara** [comment]
🎉🎉🎉🎉
