### ISSUE TITLE
Autoscroll EntityTable when moving soft focus.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#440]
See example in useEntitySelectLogic hook.

As a user I want the entity table to auto scroll when I move the soft focus cell with up/down keyboard keys.

<img width="577" alt="Capture d’écran 2023-07-03 à 20 31 20" src="https://github.com/twentyhq/twenty/assets/26528466/2ecc2742-a54c-46a4-b88e-867ad56d9c6c">

**Comment by abhip167** [comment]
I am working on this.

**Comment by brendanlaschke** [comment]
> I am working on this.

This was implemented by me in #1008 maybe test if it already works as expected…

**Comment by charlesBochet** [comment]
It works, thank you! Closing this issue
