### ISSUE TITLE
Check if eager load can override and delete a relation in Apollo cache

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#4401]
## Scope & Context

Following https://github.com/twentyhq/twenty/pull/4391,

Eager load everywhere in the app.

Should be done after https://github.com/twentyhq/twenty/issues/4399

## Technical inputs

We want to check that eager load on index table page won't remove relations that could be loaded elsewhere for the same record.

Example : 
- We are loading activity targets on company show page
- We are not loading activity targets on company table page
- Are activity targets still present in the cache for this company ?

**Comment by lucasbordeau** [comment]
@charlesBochet I think we solved this ?

**Comment by charlesBochet** [comment]
Yep!
