### ISSUE TITLE
Make sure that newly loaded records adopt the status of the Select/Unselect all checkbox

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4406]
# Current Behavior

The "Select/Unselect all" checkbox isn't applying its status to newly loaded records on `Indexes`. When users check the `Select` box, all records, including those loaded later, should be selected. Currently, this isn't happening, causing a mismatch between user selection and visual feedback.

https://github.com/twentyhq/twenty/assets/19412894/60295f88-0f60-4a43-8a67-36acfffaf4fb

# Expected Behavior

Newly loaded records and records that are not in view should match the status of the `Select/Unselect all` checkbox. If checked, new records should also be checked. If unchecked, new records should stay unchecked.

**Comment by WilliamWong55955** [comment]
Hello, can I claim this issue? Also I will have two of my team members work with me as well.

**Comment by WilliamWong55955** [comment]
Oh wait didn't see the pull request made, nevermind!
