### ISSUE TITLE
Clicking on "Select/Unselet all" Should select all records with Backend

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4407]
# Current Behavior

The Frontend currently manages record selection, limiting "Select/Unselect All" to approximately 60 records. This limitation is confusing as the user expects it to apply to all records.

# Desired Behavior

The backend should handle the "Select All" functionality to allow actions (such as export or delete) to be applied to all data within an index.

# Technical Input

@FelixMalfait

**Comment by FelixMalfait** [comment]
(Taken by Gitstart)

**Comment by FelixMalfait** [comment]
Closing to keep parent issue only as it's the one assigned to @gitstart-twenty
