### ISSUE TITLE
Impossible to "Unselect All" records

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4408]
# Current Behavior

Currently, the 'unselect all' button fails to function when a user has more than approximately 60 records. This issue is linked to others, see #4397.

[Related Issue Screenshot](https://github.com/twentyhq/twenty/assets/19412894/60295f88-0f60-4a43-8a67-36acfffaf4fb)

# Desired Behavior

The checkbox should be in `Indeterminate state`. Upon clicking, it should unselect all records.

![image](https://github.com/twentyhq/twenty/assets/19412894/ab7071f2-380e-4ce2-97df-95be17af8dd5)

**Comment by lucasbordeau** [comment]
Duplicate #4487
