### ISSUE TITLE
AAU, when opening cell by typing text, I want to have cell value cleared before my text is entered.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#441]
By default, when we are opening a table cell by typing text, it should erase before entering the keys we just typed in. 

Because those values are controlled by different inputs, and edit mode is a generic implementation, we have to find a way to have maybe a resetValue hook that has to be implemented in any editable cell, or maybe implement this behavior directly into the editable cell editable component ?

**Comment by abhithory** [comment]
Hello @lucasbordeau @FelixMalfait , i want to work on this. Can you please assign me this?

**Comment by FelixMalfait** [comment]
Of course @abhithory thanks a lot!

This one can be a bit confusing.
If the cell is in this mode:
<img width="202" alt="Screenshot 2023-10-10 at 18 32 29" src="https://github.com/twentyhq/twenty/assets/6399865/d7f30156-8d3a-406f-b09e-bb24681f32ac">
Then the current behavior is fine, we don't want to erase the text

We are talking about the case when the cell is in soft focus like this:
<img width="198" alt="Screenshot 2023-10-10 at 18 32 56" src="https://github.com/twentyhq/twenty/assets/6399865/cc729e2f-5ec2-4cad-9592-306bbadfed04">
You can enter such state by focusing on a cell (click) then using tab to navigate or arrow keys


I think fixing this should also fix this at the same time: https://github.com/twentyhq/twenty/issues/447

**Comment by abhithory** [comment]
@FelixMalfait thanks for explaining. I got it. I will fix this

**Comment by abhithory** [comment]
I fixed this and created a PR here #2021 . Please check.
@FelixMalfait @lucasbordeau
