### ISSUE TITLE
Implement Confirmation Prompt for Multiple Record Deletion

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4410]
# Current Behavior

Users can delete multiple records without confirmation, risking unintentional removal or misunderstanding of the consequences. This process lacks a confirmation step, which could lead to irreversible data loss.

# Desired Behavior

A confirmation prompt should appear before deletion, ensuring the user knows several records, not just visible ones, are going to be deleted.

![image](https://github.com/twentyhq/twenty/assets/19412894/92fe25e3-7b92-47e8-a638-c441d709e409)

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=25201-46329&mode=design&t=Lc9vv0ssYD3TZhft-11

**Comment by Anchit1909** [comment]
Hey @Bonapara, I would like to work on this. Could you please assign this issue to me?

**Comment by Bonapara** [comment]
Sure, Thanks for contributing @Anchit1909!
