### ISSUE TITLE
Migrate the "Export" Feature to the action bar

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4412]
# Current Behavior

The Export feature is currently located in the "Options" menu. This placement is due to the "Select All" functionality today only selecting approximately 60 records.

![CleanShot 2024-03-11 at 16 49 55](https://github.com/twentyhq/twenty/assets/19412894/abca0098-c604-4c36-acf9-df80a0dae533)

# Desired Behavior

With the introduction of the new "Select all / Unselect all":

The Export feature should be moved to the action bar. The `progress indicator` (try an export to see) should be displayed on the button label, similar to its current implementation in the options menu.

![CleanShot 2024-03-11 at 16 50 28](https://github.com/twentyhq/twenty/assets/19412894/3d5178df-ea1b-4990-8fa8-854ddcd3539f)

![image](https://github.com/twentyhq/twenty/assets/19412894/a4f08a32-b382-49a8-9322-b82b57ad66c4)

**Comment by lucasbordeau** [comment]
@Bonapara Shouldn't we keep both ? Because export table currently allows to export a filtered view and one might want to export without selecting, what do you think ?

**Comment by lucasbordeau** [comment]
Could you link the issue that introduces select all ? Because right now it only selects what's loaded in the table on the frontend client.

**Comment by FelixMalfait** [comment]
(Taken by Gitstart)

**Comment by FelixMalfait** [comment]
Closing to keep parent issue only as it's the one assigned to @gitstart-twenty
