### ISSUE TITLE
Enable `⌘ + click` for Opening Links in New Tabs

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4422]
# Current behavior

I cannot use `⌘ + click` to open links in new tabs. E.g. for opening several opportunities at once or opening the opportunity, company, and the person of that opportunity.

# Desired Behavior

`⌘ + click` should open links in a new tab.

**Comment by FelixMalfait** [comment]
The underlying issue is that we use onClick and not properly Link/a tags. One additional benefit of using those would be that the url would be displayed at the bottom-left.

I think we should do it at least on the following components:
- left side menu (clicking on object names)
- record chips
- clickable left cell on tables

**Comment by ktang520** [comment]
I'm working on this

**Comment by FelixMalfait** [comment]
Thanks @ktang520! Assigning you

**Comment by ravidyarev** [comment]
@FelixMalfait - Need some help. In reference to the comment above on where the change should be done, is the "left side menu" same as "Navigation Bar"?

**Comment by FelixMalfait** [comment]
Yes it's called the navigation bar in code I believe @ravidyarev ; you can use React's chrome extension to view the name of components when hovering them, it's handy

https://chromewebstore.google.com/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi

Thanks!

**Comment by ravidyarev** [comment]
Thank you @FelixMalfait !

**Comment by FelixMalfait** [comment]
<img width="525" alt="Screenshot 2024-05-03 at 15 08 52" src="https://github.com/twentyhq/twenty/assets/6399865/6368852b-5101-4950-b389-ae6c5000eb16">
 Here too it would have been nice to be able to open each object in a new tab

**Comment by ravidyarev** [comment]
@FelixMalfait Can you please reassign the issue to @ktang520 . We are working on it together.

**Comment by FelixMalfait** [comment]
@ravidyarev Ok I did re-assign you! This issue has been open for quite some time so could you please try to raise something within a week? Thanks

**Comment by FelixMalfait** [comment]
@ ktang520 @ravidyarev could you please confirm if you'll be able to raise a PR by end of week? Thanks

**Comment by ktang520** [comment]
Hi @FelixMalfait, we are still currently working on the issue still. We figured out the Control + Click function for record chips and are currently trying to implement it in the other areas. We will most likely not have a PR for the whole issue by Friday but we can still push the work we have for review. If you could let us know whether or not that is fine, that would be great! We are happy to provide additional information in a comment about what we have found and tested if that helps. Thank you for your patience and understanding.

**Comment by FelixMalfait** [comment]
Hey @ktang520 thanks for the update! It would be great if you can please raise a PR by end of week yes, the context/what you've found will be very helpful indeed!  See also my comment on @gitstart-twenty's PR.

**Comment by ktang520** [comment]
@FelixMalfait just for clarification, by end of the week do you mean Friday or Sunday?

**Comment by FelixMalfait** [comment]
@ktang520 Sunday 👌
