### ISSUE TITLE
Sort People by Name

### ISSUE THREAD

**Issue by iero** [twentyhq/twenty#4424]
In the default "People" view, People are displayed as "last created" first.

It will be great to add an option to sort them by name (not firstname but name)

![shot 2024-03-11 at 13 30 51](https://github.com/twentyhq/twenty/assets/2870245/a2ab540d-8b02-484d-8cf3-1a6baaabe6d8)

**Comment by pombredanne** [comment]
Same here, sorting by name does not work on 0.3.2

**Comment by xNeroForte** [comment]
Hello, I would like to work on the issue please !

**Comment by nadasuhailAyesh12** [comment]
Please could you assign me to this issue, I need a merged PR contribution for my university assignment.

**Comment by SanjaySiddharth** [comment]
Hey team ! Is this still open ? If so , I'd like to lend my hand at it.

**Comment by FelixMalfait** [comment]
Agree we should be able to do this on the first column
We'd still disable hiding/reordering the first column for now, so it'd look like this.
<img width="167" alt="Screenshot 2024-06-04 at 17 28 09" src="https://github.com/twentyhq/twenty/assets/6399865/3a761b63-366f-4fad-a0ec-07b2e053dd88">
cc @thomtrp 

Assigning Gitstart to take care of this

**Comment by charlesBochet** [comment]
This one will likely be hard as we store first name and last name in different columns. It might be tied to computedFields / search key here

**Comment by FelixMalfait** [comment]
This seems to be solved! Not sure when we did it
