### ISSUE TITLE
Boolean (True/False) display "empty"

### ISSUE THREAD

**Issue by iero** [twentyhq/twenty#4438]
I created a "Non Profit" field with boolean :

![shot 2024-03-13 at 09 12 06](https://github.com/twentyhq/twenty/assets/2870245/42c812bc-f307-4177-81f3-8bc07e27936f)

But when I click in the Company, it says "Empty" :

![shot 2024-03-13 at 09 12 44](https://github.com/twentyhq/twenty/assets/2870245/cc8dce73-6c77-4f49-9cff-cace5e1e55db)

**Comment by ijayhub** [comment]
Is it still open? Interested

**Comment by slavakurilyak** [comment]
Yes, I confirm this issue has not been resolved as it's affecting my CRM as well

**Comment by brendanlaschke** [comment]
@ijayhub, @slavakurilyak, @Jonathanlemon I already raised a pr (https://github.com/twentyhq/twenty/pull/4468) - which is waiting for changes in another one on the default value saving in the field metadata. We also discussed there how we want to solve this... which I will continue once the other pr is ready and merged. For other good first issues take a look here: https://github.com/twentyhq/twenty/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22 :)
