### ISSUE TITLE
When I click on an opportunity, activating the delete option should not be the default

### ISSUE THREAD

**Issue by pombredanne** [twentyhq/twenty#4439]
When I click on an opportunity "box" (outside of a field), the delete option is the only option that gets enabled and should not be the default. This is dangerous.
I would expect to open the opportunity details instead. Deleting opportunities is a rare thing. Viewing details is a common thing.

**Comment by FelixMalfait** [comment]
Good feedback! Cc @Bonapara related to the "deletion confirmation" screen we talked about

**Comment by Bonapara** [comment]
Yes! Related to #4410. We will also add more features to this menu soon, like export, creating a note, or task. Thanks for the feedback @pombredanne :)
