### ISSUE TITLE
We shouldn't allow GraphQL field types as object names

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4443]
Demo environment was broken because someone create an object named "Int". This conflicts with the existing type in GraphQL.

We shouldn't allow object names to be the same as existing GraphQL field types

Related: https://github.com/twentyhq/twenty/pull/3957
@AbuHafsa had already created a fix for a similar issue - so we probably just have to edit the function

**Comment by AbuHafsa** [comment]
@FelixMalfait you could assign this to me and I can exclude all the GraphQL data types to avoid any conflicts

**Comment by FelixMalfait** [comment]
thanks a lot @AbuHafsa!!!
