### ISSUE TITLE
Prefetch Skeleton Loading on Indexes and Shows

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4458]
# Desired Behavior

As soon as #4456 is complete, we can display the permanent navigation items (Settings, Search...) and the top navbar. 

We should now launch the Prefetch Loading with a new Skeleton Loading. The goal of this step is to load the view content and metadata:

### Index

![image](https://github.com/twentyhq/twenty/assets/19412894/c1b2bc4e-5952-4911-a6d9-bc2236b2f0fa)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=25426-62817&mode=design&t=75yrmyKfqMepmFVt-11

### Show

![image](https://github.com/twentyhq/twenty/assets/19412894/e00464f0-db67-49bd-a77a-fd2848bdad99)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=25429-70482&mode=design&t=75yrmyKfqMepmFVt-11

**Comment by saadfrhan** [comment]
Assign me!
