### ISSUE TITLE
Data Skeleton Loading on Indexes

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4459]
# Current Behavior

On indexes, we display a blank page while the data is loading:

https://github.com/twentyhq/twenty/assets/19412894/c8380422-74dd-465c-818c-6703839b27cf

# Desired Behavior

After the prefetch is done, we should be able to display the Favorites, Sidebar Objects, View name, Filters, and Column names. It's now time to load the content. Ensure a smooth fade transition between the end of skeleton loading and the appearance of content. (See #4462 for videos)

## Table views

We want to display a few lines:

![image](https://github.com/twentyhq/twenty/assets/19412894/9072320f-c17c-4f14-b2c0-2d2b7d6fffd7)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=25426-64677&mode=design&t=75yrmyKfqMepmFVt-11

## Kanban views

We want to detect if the kanban is in its "Compact mode" or not and adapt the loading accordingly:

### Normal mode

![image](https://github.com/twentyhq/twenty/assets/19412894/3e567b71-348c-4202-aa76-73778f144da3)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=25429-76436&mode=design&t=75yrmyKfqMepmFVt-11

### Compact view

![image](https://github.com/twentyhq/twenty/assets/19412894/74d8200b-ab6d-4e3d-a372-c07895daecc3)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=25429-76395&mode=design&t=75yrmyKfqMepmFVt-11

**Comment by saadfrhan** [comment]
Assign me!
