### ISSUE TITLE
AADev, I want to be sure that there is no possible race condition in openEditableCell and closeEditableCell recoilCallbacks

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#446]
We might have silent problematic behavior because of the setTimeout in openEditableCell, because there could be race conditions.

Maybe we could build a switchEditableCell to handle the case where we go from one cell to another.

Or just implement logic to handle this specific case in openEditableCell, and also in closeEditableCell.

**Comment by lucasbordeau** [comment]
It may be due to useListenClickOutside and onClick executing at the same time, maybe we should prevent listen click outside if the target ref is another cell.

**Comment by charlesBochet** [comment]
Closing as this ticket is outdated
