### ISSUE TITLE
Show Data Skeleton Loading 

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4460]
# Desired Behavior

(See #4462 for videos)

Thanks to prefetch loading, we can now display the correct number of field lines and their names. It's time to launch the content loading:

![image](https://github.com/twentyhq/twenty/assets/19412894/b56d86a9-ea4c-49aa-8a5a-794a06e0d132)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=25429-70096&mode=design&t=75yrmyKfqMepmFVt-11

**Comment by FelixMalfait** [comment]
Assigned to @saadfrhan

**Comment by Bonapara** [comment]
@charlesBochet, did you not want to address these issues this week with the core team?

**Comment by gitstart-twenty** [comment]
Hey @Bonapara,
Mind sharing a resource so we can get more familiar with prefetch loading?

**Comment by gitstart-twenty** [comment]
Hey @Bonapara 
Should the skeleton in the timeline be the length of the tabs at the top, or `440px` like in the design?

![Screenshot 2024-05-06 at 20 11 48](https://github.com/twentyhq/twenty/assets/140154534/83c753a4-0833-4023-a619-b73429599613)

**Comment by Bonapara** [comment]
440px is ideal, I fear a larger size would be overwhelming. Thanks!
