### ISSUE TITLE
⌛ Improve loading with Skeleton Loading

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4462]
# Desired Behavior

We aim to improve page loading by adding more skeleton loading.

Here is the desired behaviors:

### Table indexes

https://github.com/twentyhq/twenty/assets/19412894/b553f61c-b4be-4e69-a937-8446e6273102

### Kanban indexes

https://github.com/twentyhq/twenty/assets/19412894/ded246e6-0d8c-44f2-95b8-30c51549293f

### Shows

https://github.com/twentyhq/twenty/assets/19412894/095a89c3-09a9-4c4f-a7c5-23fd4941e4d2

```[tasklist]
### Tasks
- [ ] #4456
- [ ] #4458
- [ ] #4459 
- [ ] #4460 
```

**Comment by charlesBochet** [comment]
Hints for technical part:
- look at the XHR queries, you'll see:
1) ClientConfig + CurrentUser + Metadata
2) Prefetch
3) Other data queries
- look at index.tsx, you'll see:
1) ClientConfigProvider, UserProvider, MetadataProvider
2) PrefetchProvider
3) Layout and rest of the app

On the figmas, you'll see different loading state corresponding to these 1, 2, 3 steps

I think it's better to do one loading state at a time so we can discuss technical implementation before you go to all of them

**Comment by Bonapara** [comment]
Hi @saadfrhan, thanks for your contribution. Please tag me in the sub-issues you'd like to address, so I can assign them to you!

**Comment by saadfrhan** [comment]
Can you assign me to all of them?

**Comment by saadfrhan** [comment]
Oh my bad. Okay

**Comment by Bonapara** [comment]
@saadfrhan, my apologies, I overlooked that the sub-issues were already assigned.

**Comment by saadfrhan** [comment]
No problem. 🙌

**Comment by saadfrhan** [comment]
Hi @Bonapara 👋, can you assign me to one of the sub-issues?

**Comment by Bonapara** [comment]
Hi @saadfrhan, unfortunately, as I mentioned earlier, those tasks have already been assigned. Maybe would you like to pick another one?

**Comment by saadfrhan** [comment]
Oh ok. Thanks!

**Comment by FelixMalfait** [comment]
@saadfrhan thanks and sorry for the confusion! This is a fairly big issue so make sure to break it into 1 first PR and ping us on Discord if you need intermediate feedback. @Bonapara will be happy to support you if there are design considerations

**Comment by saadfrhan** [comment]
Ok. Thanks @FelixMalfait!

**Comment by saadfrhan** [comment]
Sorry, I am unassigning myself because I am failing to do it.

**Comment by charlesBochet** [comment]
Ok no worries :) thanks for taking a look
