### ISSUE TITLE
Add Location (Lat/Long) object

### ISSUE THREAD

**Issue by iero** [twentyhq/twenty#4463]
As a "person" contains Forename and Lastname, it will be very usefull to have an object called "Location" where we can enter a Latitude and Longitude in decimal (+ or - X.xxx).

**Comment by FelixMalfait** [comment]
Thanks a lot for the suggestion! I'm closing it for now as it should be covered by https://github.com/twentyhq/twenty/issues/2661 which hopefully should come in Q2!

**Comment by iero** [comment]
@FelixMalfait 
I'm not sure that #2661 is the same thing? 
I use lat/long coordinates that are not related to any "address", ie in the middle of a desert or a forest.

Maybe it's the good time to investigate Plus Codes.
https://www.geoapify.com/google-plus-code-as-a-location-code
