### ISSUE TITLE
Show Page/Activities Panel/Calendar Tab/Calendar Event Details - Display Attendees related fields

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#4465]
## Context

For this issue:
- In the Show Page/Activities Panel/Calendar Tab/Calendar Event Details panel, implement the attendees related fields ("Yes", "Maybe", "No").

## Figma

<img width="209" alt="image" src="https://github.com/twentyhq/twenty/assets/3098428/523abac9-4b0f-4713-98f1-8429d3794f21">

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=23094%3A45816&mode=design&t=BKJvP4z6fus3X2za-1

**Comment by FelixMalfait** [comment]
I think this has been implemented so I'm closing the issue 
<img width="285" alt="Screenshot 2024-09-11 at 12 18 55" src="https://github.com/user-attachments/assets/a8b89dc5-606c-4aaf-8f4d-7ffcbd88057f">
