### ISSUE TITLE
Opportunity list view: Name field & Currency Picker Position

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4474]
# Current Behavior

On Opportunity List view:

- The first column displays the opportunity amount.
-  Currency picker appears below cells:

![Screenshot 2024-03-14 at 11 09 05](https://github.com/twentyhq/twenty/assets/19412894/9b616083-99d3-46ff-b6b2-a4315d698037)

# Desired Behavior

-  First column should be the opportunity name.
-  Amount picker should open above cells.

**Comment by devalade** [comment]
Hey @Bonapara 
I think someone has fixed this issue
![Screenshot from 2024-03-24 13-00-52](https://github.com/twentyhq/twenty/assets/74435372/b46d586b-a0cc-4bff-8241-b71c88ee889d)

**Comment by Bonapara** [comment]
Hi @devalade, I think the main problem is that the first column should be the opportunity name. (This is the one causing the issue)
