### ISSUE TITLE
Correct Select Field Input Height to 24px

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4477]
# Current Behavior

The height of the select field input has been shrunk to 18px.

![Current Input Field](https://github.com/twentyhq/twenty/assets/19412894/9910a067-27df-4d60-ae87-f57ab2422dce)

# Desired Behavior

The select field input should be adjusted to a height of 24px.

![CleanShot 2024-03-14 at 15 09 51](https://github.com/twentyhq/twenty/assets/19412894/47784085-3b3c-4a98-a848-4beac24ba0d1)

**Comment by adityavashisht9** [comment]
Hey, I'm a new contributor in the project. I've fixed the issue in [this](https://github.com/twentyhq/twenty/pull/4493) PR. Kindly check.

**Comment by Jonathanlemon** [comment]
@Bonapara Could I tackle this?

**Comment by Bonapara** [comment]
Hi @Jonathanlemon, I think a PR is already opened!
