### ISSUE TITLE
Connect Calendar tab to backend

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#4488]
## Scope & Context

Connect Calendar tab to backend

<img width="913" alt="Capture d’écran 2024-03-14 à 17 47 01" src="https://github.com/twentyhq/twenty/assets/71827178/acba8cec-8815-4c0f-8e97-70817d045edb">

## Technical inputs

- Use the custom resolver created in #4485 to get the events

**Comment by charlesBochet** [comment]
Also add prehook on /event (findOne / findMany)
