### ISSUE TITLE
Creating an object with cyrillic alphabet name breaks the application

### ISSUE THREAD

**Issue by thomtrp** [twentyhq/twenty#4497]
## Bug Description

A new custom object has been created with a cyrillic alphabet name.
All graphQL calls to the server were then broken with the error:
`Names must only contain [_a-zA-Z0-9] but \"Лист\" does not.`

<img width="1512" alt="Capture d’écran 2024-03-15 à 10 26 29" src="https://github.com/twentyhq/twenty/assets/22936103/2eca57d9-8120-42ed-8c7d-5359b719f1f5">

## Expected behavior

We need to decide if we either support that alphabet or if we block it.

**Comment by FelixMalfait** [comment]
I feel like we should be:
- permissive for the label (cyrilic, accents, maybe even emojis..)
- strict for the name

Not sure how we convert label into names today? 
We could import this file as a util: https://github.com/dundalek/latinize/blob/master/latinize.js
It helps but doesn't cover cyrillic, chinese, etc. so maybe just generate a random string to happen at the end if (1) the version striped of exotic characters is strictly shorter than the initial version and (2) it's shorter than 3 characters?

**Comment by charlesBochet** [comment]
Agree with Felix, LGTM :)
