### ISSUE TITLE
Replace Terms & Conditions with Sign Up Link on Sign In

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4502]
# Current Behavior

Currently, the default landing page upon entering `app.twenty.com` is the sign-in page (`app.twenty.com/sign-in`).

![CleanShot 2024-03-15 at 14 54 36@2x](https://github.com/twentyhq/twenty/assets/19412894/aefb1c9e-3870-43f9-a5e3-370456a27575)

# Desired Behavior

We aim to replace the terms & conditions with a link that takes users directly to the sign-up page, following the style of the "Forgotten Password" link:

![image](https://github.com/twentyhq/twenty/assets/19412894/1ac0249b-0768-49ea-826e-cdd306c64f3a)

**Comment by j-devaraj** [comment]
I can work on this!

**Comment by MamathaYarramaneni** [comment]
please assign this issue to me.
