### ISSUE TITLE
Change field labels and field type for calendarEvent object metadata to match Figma

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#4506]
## Scope & Context

Change field labels and field types for calendarEvent object metadata to match Figma

## Technical inputs

Change Labels:
- 'Conference URI' to 'Meet Link'
- 'Start DateTime' to 'Start Date'
- 'End DateTime' to 'EndDate'

Change FieldType for `conferenceURI` to LINK

**Comment by FelixMalfait** [comment]
"Meet Link" seems very Google specific no? And is it a Link field type? If not I don't think we should us "Link". I don't dislike conferenceUri!

Also for dateTime fields isn't the convention in DB tu use xxxAt? Eg. StartsAt, EndsAt?

**Comment by bosiraphael** [comment]
I was proposing only to change the label, not the name of the column, so we can use the field metadata label and type in the frontend to deduce the correct field display.

![Profile](https://github.com/twentyhq/twenty/assets/71827178/acd71e24-2e24-4c69-a88b-eeb232173b22)

**Comment by FelixMalfait** [comment]
Ah ok my bad thanks! great then
