### ISSUE TITLE
Database Setup Failures: Missing Extensions and FDWs in twenty-server@0.3.2

### ISSUE THREAD

**Issue by slavakurilyak** [twentyhq/twenty#4515]
#### Bug Description

During the `database:setup` process of `twenty-server@0.3.2`, multiple errors occurred related to missing PostgreSQL extensions and foreign data wrappers (FDWs). These failures prevent the successful setup of required schemas and extensions, hindering the proper initialization of the database for the server.

The errors are as follows:
- Failed to create extension "wrappers": Extension not available.
- Failed to create extension "mysql_fdw": Extension not available.
- Failed to create FDWs for various services (Airtable, BigQuery, ClickHouse, Firebase, Logflare, S3, Stripe) due to missing handler functions.

These errors suggest that the required extensions/FDWs are either not installed or not available in the PostgreSQL instance being used.

**Screenshots**: 

<img width="839" alt="Screen Shot 2024-03-17 at 3 35 18 PM" src="https://github.com/twentyhq/twenty/assets/6625584/8fe772b2-65a7-4768-bc21-5e72fb857815">

#### Expected Behavior

The expected behavior is a successful execution of the `database:setup` script without encountering errors related to missing extensions and FDWs. All necessary schemas, extensions, and FDWs should be created without issues to allow for the proper setup and initialization of the database for `twenty-server`.

#### Technical Inputs

- The database setup process involves creating schemas and installing necessary PostgreSQL extensions and FDWs to facilitate communication with various services and data sources.
- The failure points are specifically at the steps where the script attempts to create extensions and FDWs that are not found in the PostgreSQL instance. This indicates a possible misconfiguration or missing installations in the database environment.
- Resolution may involve ensuring that all required PostgreSQL extensions and FDWs are correctly installed and available in the PostgreSQL instance before running the `database:setup` script. This may include installing custom or third-party extensions and FDWs that are not included in the default PostgreSQL setup.

**Comment by FelixMalfait** [comment]
Hey I'm sorry we never replied to this. I'm cleaning up old issues. We'll try to be more responsive next time and avoid accumulating a backlog which led us to miss this one.
FDW are not mandatory, we added it for an experimental feature but never launched that feature
