### ISSUE TITLE
Create "Pets" custom object in seeds

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4526]
## Context
We have two types of seeds:
- development seeds 
- demo seeds

In **both context**, it would be useful to have one custom object to demo.
I thought we could create something like `Invoice` or `Ticket` to demo an obvious business use-case, but then people might assume it's a custom object, so let's do something more obvious

## Implementation
Create a table `Pets` with an image, an enum (e.g. size or type = cat/dog), a name, a size attribute.
Link people to their pets.

**Comment by bottlewook** [comment]
Can i work on this issue? kindly assign it to me!

**Comment by FelixMalfait** [comment]
Yes of cours @bottlewook let me know if you need help / feedback

**Comment by manthan-sharma-23** [comment]
Hey there can you ellaborate on this
