### ISSUE TITLE
Add an hover on the collapsable navigation button

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#453]
Add hovers on the collapsable navigation buttons:

https://github.com/twentyhq/twenty/assets/19412894/15ec4d8d-949a-4b25-afd8-3f7e7a56077f

https://github.com/twentyhq/twenty/assets/19412894/dcb04e6d-7cf9-4107-9762-474466b41809

Component: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=1458-86002&mode=design&t=kejd6gCCVsSeTixS-4

**Comment by charlesBochet** [comment]
Closing as this issue was fixed by https://github.com/twentyhq/twenty/pull/492
