### ISSUE TITLE
You are Offline screen

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#454]
### Figma
![Image](https://github.com/twentyhq/twenty/assets/19412894/5cee6091-d5b4-42a7-b245-bbf549394d60)
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=4218-61196&mode=design&t=kejd6gCCVsSeTixS-4

### Bonus
Fade in animation when it appears (300ms)

**Comment by FelixMalfait** [comment]
(use dev mode on Figma to view CSS to implement)

<img width="1226" alt="Screenshot 2023-06-26 at 18 22 11" src="https://github.com/twentyhq/twenty/assets/6399865/f5722eba-e55a-4ad8-891b-8dfcd8edbf11">

**Comment by charlesBochet** [comment]
@Bonapara fontSize, lineHeight, iconSize and iconStroke do not exist in theme, how should we call them?

**Comment by Bonapara** [comment]
@charlesBochet can we add the font size as Marketing Titles / Large?
For the icon size & weight, should we create the "Marketing Icon Large" now or should we wait to have several usecases to put them in the theme

**Comment by Mbistami** [comment]
I'll handle this one.

**Comment by FelixMalfait** [comment]
@Mbistami great! Thanks a lot

**Comment by FelixMalfait** [comment]
Closing after discussion with @Mbistami. We realize that PWA already offers an offline screen and that we should handle network errors differently than by showing a screen that blocks the app entirely
