### ISSUE TITLE
Replace the view toggle by a "Soon" tag

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#455]
![Image](https://github.com/twentyhq/twenty/assets/19412894/1cc1af48-ca9c-4378-befb-a4594bfd1c90)

Figma:
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=4228-58301&mode=design&t=kejd6gCCVsSeTixS-4
```[tasklist]
### Tasks
- [ ] Make sure the color is Extra Light (Desactivated)
```

**Comment by FelixMalfait** [comment]
Closing as views are probably coming within a couple weeks
