### ISSUE TITLE
ApolloError: Unexpected token '<', "<!doctype "... is not valid JSON

### ISSUE THREAD

**Issue by sebastienhouzet** [twentyhq/twenty#4551]
## Bug Description

Juste after installation with Docker Version.
I open http://localhost:3001 and i have this error on my browser :

ApolloError: Unexpected token '<', "<!doctype "... is not valid JSON
<img width="943" alt="Capture d’écran 2024-03-18 à 16 21 19" src="https://github.com/twentyhq/twenty/assets/2550639/db643fb5-5ccd-4ee6-ad88-ba47c4622985">

## Expected behavior

A clear and concise description of what the expected behavior is.

Impossible to start the application on the browser

## Technical inputs

User docker-compose.yml and .env exemple on documentation
https://docs.twenty.com/start/self-hosting/docker-compose#docker-compose-file

**Comment by sebastienhouzet** [comment]
@FelixMalfait i'am available to test this new version of docker.

**Comment by FelixMalfait** [comment]
@Freebios will raise a PR today which should be merged by end of week :)

**Comment by StreamlinedStartup** [comment]
Same thing here using the new `bash <(curl -sL https://git.new/20)` command.

**Comment by FelixMalfait** [comment]
@StreamlinedStartup could you be a bit more explicit? This should not happen anymore with the new install. 
Would be great if you can send screenshot of the requests that are failing (using chrome inspector).
Thanks a lot

**Comment by StreamlinedStartup** [comment]
Was seeing the exact same thing as the screenshot from @sebastienhouzet so decided one wasn't necessary. 

After uninstalling/reinstalling a few times along with running random DB commands I found in the discord, it is currently working. Not sure what did it, but it did it!

**Comment by FelixMalfait** [comment]
Ok! Thanks for the feedback
