### ISSUE TITLE
Login and delete account does not work

### ISSUE THREAD

**Issue by dbeck121** [twentyhq/twenty#4564]
## Bug Description

When trying to log in via https://app.twenty.com/sign-in I get redirected to a blank page with url https://app.twenty.com/create/profile. We signed up for a 7 days trial and wanted to delete the account (we love your work but want to wait for more mature version). 
Two days ago the login worked but delete account button resulted in error. We would like to delete the account before 7 day trial ends.

## Expected behavior

Login works and delete account also works.

## Technical inputs
We did not receive any mails. That is also suspicious in some way.

**Comment by FelixMalfait** [comment]
Sorry about that @dbeck121! We'll fix this. I can confirm you will not be charged.
And thanks for the kind words. We're early indeed and working hard to improve the product :)
