### ISSUE TITLE
The icon search is not accurate

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4565]
# Current behavior

The icon search is not accurate
E.g. Typing `Star` does not locate the `Star` icon:

### Twenty search

<img width="278" alt="Screenshot 2024-03-19 at 08 35 40" src="https://github.com/twentyhq/twenty/assets/19412894/1b13eaa6-c34b-4403-b1b6-a216bb601c2b">

### Tabler search

https://tabler.io/icons

<img width="1181" alt="Screenshot 2024-03-19 at 08 37 37" src="https://github.com/twentyhq/twenty/assets/19412894/d5abe170-ff6e-4978-81f6-5a5c2b2be076">

# Desired Behavior

The `Star` icon should appear first

**Comment by simaosanguinho** [comment]
Hi! Can I be assigned this issue?

**Comment by Bonapara** [comment]
Done, Thanks for contributing @simaosanguinho!

**Comment by simaosanguinho** [comment]
Hey! Is it necessary to include a test to the **useIconPicker.text.tsx** file or is fix enough for this case?

**Comment by Bonapara** [comment]
Is there a test existing today? If not, I think no need to add one!
