### ISSUE TITLE
lodash.groupBy package is missing in package.json

### ISSUE THREAD

**Issue by anoopw3bdev** [twentyhq/twenty#4578]
## Bug Description

lodash.groupBy package is missing in package.json which is breaking the local setup 

<img width="850" alt="Screenshot 2024-03-20 at 5 21 37 PM" src="https://github.com/twentyhq/twenty/assets/44577841/1098c733-8989-4c44-ab85-df78c95e5c7c">

**Comment by charlesBochet** [comment]
There is a typo in the case, I'm fixing in another PR

**Comment by anoopw3bdev** [comment]
ok @bosiraphael closing this issue then

**Comment by charlesBochet** [comment]
I see that you have opened a PR, let's merge it as mine will take more time :)
ty!

**Comment by anoopw3bdev** [comment]
I have added the missing package in package.json
