### ISSUE TITLE
When I paste a full name in the field to create a new people, split first and last name 

### ISSUE THREAD

**Issue by pombredanne** [twentyhq/twenty#4582]
When I paste a full name in the field to create a new people, I would like the first and last name to be split or inferred by default.

**Comment by FelixMalfait** [comment]
Should be doable by adding a special `onPaste` handler on the first name field that `splits(' ')` the past input into 2 parts to fill lastName with the second part, ifthe firstName/lastName are empty (keep the current behavior if firstname/lastname is already filled, we only want to cover the use-case when it's empty)
