### ISSUE TITLE
One person can have more than one email

### ISSUE THREAD

**Issue by pombredanne** [twentyhq/twenty#4583]
One person can have more than one email and today I am forced to create multiple persons with the same name

**Comment by FelixMalfait** [comment]
https://github.com/twentyhq/twenty/issues/4525 <- once we do that we'll get the array field type which should be a good first step to achieve array links, array email, etc.

**Comment by FelixMalfait** [comment]
On second thought, I think the best approach for you would be to create a custom column `secondary email` (and eventually third email etc). I had a look at how it was done in other software providers such as Notion and Salesforce, and no one came up with a solution that gets you email format validation + multiple values in a single field.
We've just introduced the multi-select field which is inherently an array, we'll work to make it more flexible (e.g. option to let user create their own select value directly from the UI without having to go through settings) - that could also fit your use-case
