### ISSUE TITLE
An opportunity should have a description, not only notes

### ISSUE THREAD

**Issue by pombredanne** [twentyhq/twenty#4584]
An opportunity should have a description, not only notes. I would like to have a top level description text that is shown when I hover or drill down on an opportunity.

**Comment by FelixMalfait** [comment]
Creating a a custom text field isn't enough? You could display it on the opportunity card if you wish to

**Comment by pombredanne** [comment]
@FelixMalfait re:

> Creating a a custom text field isn't enough? You could display it on the opportunity card if you wish to

Yes, it would be enough, but this should be a default field IMHO.

**Comment by FelixMalfait** [comment]
Noted! We will add it to the default company model soon when we revisit the model 👌
