### ISSUE TITLE
Introduce APP_SECRET to replace SECRETS

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4588]
## Context

We currently have 4 environment variables to specify our SECRETS in `packages/twenty-server/.env`:
- ACCESS_TOKEN_SECRET
- LOGIN_TOKEN_SECRET
- REFRESH_TOKEN_SECRET
- FILE_TOKEN_SECRET

We would like to replace those by a unique APP_SECRET env variable and to generate those 4 when needed as:
- ACCESS_TOKEN_SECRET=SHA256({APP_SECRET}+{workspaceId}+"ACCESS")
- LOGIN_TOKEN_SECRET=SHA256({APP_SECRET}+{workspaceId}+"FILE")
- ...

# What & How

- Remove those 4 secrets from the code base
- introduce APP_SECRET instead (this needs to be introduced in several places, I would recommend look for ACCESS_TOKEN_SECRET and to mimick it)
- compute accessTokenSecret based on the formula above whenever it's needed

**Comment by charlesBochet** [comment]
We can leverage the keyValuePairs table to store it

**Comment by charlesBochet** [comment]
I have updated the tickets desc, ready to be picked!

**Comment by charlesBochet** [comment]
/oss.gg 500

**Comment by charlesBochet** [comment]
@Devessier Let's go with sha as discussed together!

**Comment by Khaan25** [comment]
If I'm not wrong, we'll have a function.

`function generateSecret(workspaceId: string, type: 'ACCESS' | 'LOGIN' | 'REFRESH' | 'FILE'): string`

Which is gonna return `${appSecret}${workspaceId}${type}`

where appSecret = process.env.APP_SECRET
where workspaceId = we will pass it?

Please correct me if I'm wrong.

@FelixMalfait @Bonapara

**Comment by FelixMalfait** [comment]
@Khaan25 that's correct! Thank you

**Comment by Khaan25** [comment]
One quick question, @FelixMalfait,

I see some functions
![image](https://github.com/user-attachments/assets/52b6e551-e651-4147-905a-2eb81c680005)


They don't have workspaceId as prop, I believe we're gonna modify the function params to include it? Right?

**Comment by Khaan25** [comment]
Maybe we can make the workspaceId optional?
Could you please guide me here?

**Comment by FelixMalfait** [comment]
@Khaan25 no we don't want to make workspaceId optional, you should usually be able to retrieve it in the context (it's available at the resolver level usually since most API calls require to be logged in). Thanks

**Comment by charlesBochet** [comment]
@Khaan25 in some sign-in / sign-up cases, we indeed don't have the workspaceId available.

@FelixMalfait, we could either append the userId in this case or try to get the defaultWorkspaceId

**Comment by Khaan25** [comment]
Well, let's do defaultWorkspaceId, how do we get that?

there's workspaceRespository.getId() function but not sure if that's correct to use. I'll dig into further.
Is there any function or anything to get or we can pass userId?

@charlesBochet
