### ISSUE TITLE
Email field should have copy button

### ISSUE THREAD

**Issue by JDWNL** [twentyhq/twenty#4595]
## Scope & Context
Copy button for text fields.

## Current behavior

An edit button is in place, but to copy a users email address, one has to click edit, select the email address, then cmd+c to copy. Perhaps this should even be the case for all text fields? An easy way to copy names (full name, not just the first or last name) would also be very useful.

## Expected behavior
See above

## Technical inputs
N/A

**Comment by Bonapara** [comment]
Great idea @JDWNL, Thanks! Created a `Good first issue` from it: #4599
