### ISSUE TITLE
Feature Request: Enable Deletion of Custom Fields in Workspace

### ISSUE THREAD

**Issue by slavakurilyak** [twentyhq/twenty#4597]
#### Scope & Context
Currently, Twenty CRM users can add custom fields to their workspace, specifically on the Companies and People pages. This feature enhancement aims to provide users with the ability to not just deactivate but completely delete custom fields.

#### Current Behavior
The "field" menu item on the Companies and People pages shows both displayed and hidden columns. Users lack the ability to permanently delete a custom field, which can lead to issues such as incorrect data types being used.

#### Expected Behavior
Users should be able to permanently delete custom fields from the "field" menu. This feature is expected to enhance data management flexibility, allowing users to correct mistakes like incorrect data type selection (e.g., selecting Text instead of True/False).

- The "field" menu item should include an option to permanently delete a field.
- A confirmation prompt should be presented to the user to prevent accidental deletions.

#### Technical Inputs
- Implement a confirmation dialogue to prevent accidental deletion of fields.
- Ensure that the deletion process completely removes the field and its data from the system.

#### Motivation
As a user of Twenty, being able to delete custom fields is crucial for maintaining accurate and relevant data within my workspace. Correcting mistakes such as an incorrect data type selection is essential for data integrity and user satisfaction.

**Comment by charlesBochet** [comment]
Implementing a full deletion should be a good-first issue :)
