### ISSUE TITLE
Add Copy Button to Floating Input

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4599]
# Current Behavior

There is no button or shortcut to copy the content of a field.

# Desired Behavior

Add a `copy` button to the floating inputs for `Text`, `Number`, `Phone`, `Link` and `Email` fields, enabling users to easily copy the input content.

![CleanShot 2024-03-21 at 09 37 54](https://github.com/twentyhq/twenty/assets/19412894/01e3f175-8bad-4f06-8df4-88be1ed44720)

![image](https://github.com/twentyhq/twenty/assets/19412894/26f5e4b5-d37a-40bd-ac19-b499d7f68d45)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=3007-69739&mode=design&t=KLtBvS4nmd26fA0m-11

**Comment by Bonapara** [comment]
Sure, thanks for contributing @Anchit1909!

**Comment by 16dango** [comment]
@Bonapara 
I was wondering if I can try also,
I was finding the issues with good first issue, but most of people are assigned few weeks, months but never finished.
Is it nessesary for commented when I try the issues?

**Comment by Bonapara** [comment]
Hi @16dango, you're welcome to start working on 'good first issues' that have been assigned a while ago, particularly those tagged with 'minutes'.

https://github.com/twentyhq/twenty/blob/main/.github/CONTRIBUTING.md

I encourage you to start with the oldest inactive issues. Thanks for contributing :)

**Comment by 16dango** [comment]
@Bonapara 
Thank you for responsing my comment. The messege from you means that I can also work on this issue even though someone has already been asigned?

**Comment by Bonapara** [comment]
Yes, especially for a long-overdue quick fix. However, it's best to consult the assigned person first!

**Comment by Anchit1909** [comment]
Hey @Bonapara,
Is there a reason the PhoneInputField looks like this? Because after adding the copy button, it does not look good. Should I just style it as a Normal TextInput as shown in the video, or would you prefer that I use the current design.

https://github.com/twentyhq/twenty/assets/22574091/c9472864-037e-404c-83d8-e208cec42750

**Comment by Bonapara** [comment]
Hi @Anchit1909, are you referring to the textbox that seems to be appearing within the field? If so, this behavior is not normal indeed. The input should resemble a regular text field. Thank you!

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
I think @Anchit1909 is trying to add the button in the edit mode. Instead it should be visible in display mode field along with the pencil icon.

@Anchit1909 for the difference between the two refer below screenshots:


Below cell is in edit mode 

<img width="578" alt="Screenshot 2024-04-03 at 9 21 11 PM" src="https://github.com/twentyhq/twenty/assets/62852363/8c602b39-773e-4348-b7da-589b4dd8fb29">

In below screenshot, the same field is in display mode.

<img width="578" alt="Screenshot 2024-04-03 at 9 21 48 PM" src="https://github.com/twentyhq/twenty/assets/62852363/de5c5e37-f367-4f4f-a55c-d2a6a8c27e09">

**Comment by Bonapara** [comment]
Hi @Kanav-Arora 
No, it should indeed be in edit mode to save some place in display mode :) 

@Anchit1909 FYI!

**Comment by Kanav-Arora** [comment]
Ok @Bonapara 
@Anchit1909 feel free to connect if you need any help

**Comment by lucasbordeau** [comment]
- For text inputs it's not placed correctly : 
<img width="218" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/6a81d218-0b3f-4b59-8790-77c9c035caf0">
- For phone inputs, it should be wider : 
<img width="221" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/f0399e60-7625-494f-9a14-8fa308b200b2">

Reference : 
<img width="475" alt="image" src="https://github.com/twentyhq/twenty/assets/26528466/e5e06f33-ca18-4381-ba74-992139e91e88">

**Comment by lucasbordeau** [comment]
The icon should be smaller also
