### ISSUE TITLE
Repurpose ActivityTarget work for many-to-many relationships

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4603]
(to be discussed / not ready)

We've invested quite a lot on ActivityTarget, especially on the frontend. But since we're introducing logs in lieu the current timeline, some of it might go away?
I feel like it would be beneficial to introduce a new type of many-to-many relationship across the application.
For example we could say their can be several Point of contacts for an opportunity.
Then repurpose activityTargets backend table to be a generic "relations" table that store all many-to-many and morph relations.

**Comment by FelixMalfait** [comment]
Talked with Lucas: frontend work will probably have to go away, this should be done on the backend instead.
But backend isn't mature enough to support this short-term. Something we should revisit in a couple months

**Comment by m-salman-afzal** [comment]
Just came rumbling through trial. How exactly can we make relations between objects? The options seems to be greyed out for me. Is this because of trial?

**Comment by charlesBochet** [comment]
Hi @m-salman-afzal, it should not be greyed out. All features are available in the trial

You should be able to select relation when creating a new field:
<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/9064d938-b893-49ef-8bfa-ede324fa73ef">


Note that you cannot edit existing field types as it is too dangerous to migrate your data to a different type
