### ISSUE TITLE
Using up+right keyboard in the table makes the soft focus go one cell too far.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#462]
To reproduce : go to an entity table cell and and do up and down rapidly, it should go one cell too far.

**Comment by FelixMalfait** [comment]
I was able to reproduce by pressing ⬆️ and ➡️ at the same time on my keyboard

**Comment by brendanlaschke** [comment]
The cause seems to be in the react-hotkeys-hook library as wrong events are sent while the keyup event not has been registered: 
https://github.com/JohannesKlauss/react-hotkeys-hook/issues/1013

**Comment by brendanlaschke** [comment]
Update: the fix has been merged we are waiting for a new release of https://github.com/JohannesKlauss/react-hotkeys-hook
