### ISSUE TITLE
Company > Timeline Tab displaying wrong elapsed time 

### ISSUE THREAD

**Issue by pacyL2K19** [twentyhq/twenty#4620]
## Bug Description

I am using a local setup to test out the project, and after creating a new Task / Notes in the company page, the timeline tab is showing wrong time elapsed since the creation of items(notes or tasks)

As you can see in the sceenshot below, I have created the company via seeds 8 minutes ago, then I created a few notes / tasks, just a few minutes elapsed but the tab is showing 2 hours ago, btw I am testing the app in the CAT timezone(UTC+2)

![Screenshot 2024-03-22 at 17 06 30](https://github.com/twentyhq/twenty/assets/61581306/b979fe9d-7a01-43c1-8d88-c3d83a896e1c)

## Expected behavior

The elapsed time should be accurate no matter where the user is, in this case a `few minutes ago` or something else accurate

## Technical inputs

> N/A

## Setup info

OS: MacOS 14.4
Timezone: UTC+2

**Comment by pacyL2K19** [comment]
I can work on a fix as part of my first contribution to the project

**Comment by charlesBochet** [comment]
Hi @pacyL2K19, thanks for creating the issue. 

We have discussed this one and here is our strategy:
- use timestampz postgres type instead of the current timestampz

It should be fixed as part of 0.3.4 already, no need to work on this one. Feel free to tackle any good first issue for your first contribution!

**Comment by charlesBochet** [comment]
@Weiko FYI

**Comment by charlesBochet** [comment]
Related to https://github.com/twentyhq/twenty/issues/3822

**Comment by Weiko** [comment]
The DB now uses timestamp with timezone for all date_time fields, issue should be resolved
