### ISSUE TITLE
In the opportunities kanban, put the new button at the top of the page, not the bottom

### ISSUE THREAD

**Issue by pombredanne** [twentyhq/twenty#4629]
In the opportunities kanban, put the new button at the top of the page, not the bottom.
Otherwise, it forces to scroll all the way down as soon as you have more than a few oppties

**Comment by FelixMalfait** [comment]
Mmh great point we used to have a button on top right and it's just disappeared during the refactoring last week. We need to add it back (but it's a special type of button so it's not that easy, might take a bit of time)

**Comment by pombredanne** [comment]
This is a bit of a PITA when there are many opportunities FWIW.
Each page seems to have the "new" button positioned at different places... consistency would help a lot. 

As reported elsewhere, not being able to create new records from the list or details of other records is also a minor PITA

Here are the current positions:
- opportunities kanban: bottom left corner
- opportunities list: upper right corner
- people list: upper right corner and also in the name in the first/title row of the list
- companies list: upper right corner and also in the name in the first/title row of the list

**Comment by FelixMalfait** [comment]
I agree! We'll improve this

@Bonapara fyi if you didn't see this already

**Comment by Bonapara** [comment]
We should also:

- Implement/reimplement this behavior: https://github.com/twentyhq/twenty/issues/2503
- Include an "Add record" option in the column menu:
![CleanShot 2024-04-29 at 12 00 14@2x](https://github.com/twentyhq/twenty/assets/19412894/f15a82a7-312c-4a66-a675-6b4c3bcf5160)

**Comment by ehconitin** [comment]
Should it look like this?
If the button is meant to be there, where should the dropdown appear? at the end of the column where new opportunity is being created? or is it fine this way?
Could you tell how should the ui/ux look like?


https://github.com/user-attachments/assets/2523ee5b-751b-47ed-aeb1-a0b68519cb7a

**Comment by FelixMalfait** [comment]
@ehconitin thanks!
The "+ New" should stay at the bottom where it was (with opportunity created at the bottom)
What @Bonapara had in mind was to add in it the menu that appears when you click on a column's header. 

We should also add it to the upper-right corner like on list-views  yes  ; v1 is to make it create it at the top in the column which is most on the left probably. We can always iterate from there

**Comment by FelixMalfait** [comment]
Should I assign this to you @ehconitin? Assigning you but let me know if not!

**Comment by ehconitin** [comment]
Created [PR 6649](https://github.com/twentyhq/twenty/pull/6649)

Thanks

**Comment by FelixMalfait** [comment]
Amazing thanks @ehconitin! I'll be mostly away from keyboard for the next 2 weeks but someone else will review :)

**Comment by ehconitin** [comment]
Enjoy your time off @FelixMalfait! 🫡

**Comment by FelixMalfait** [comment]
Amazing thanks a lot @ehconitin!
@Bonapara would you mind re-recreating a separate issue for the "+" button on top-right? You probably had something designed/in mind already?

**Comment by Bonapara** [comment]
Yes! -> https://github.com/twentyhq/twenty/issues/6783

**Comment by pombredanne** [comment]
@lucasbordeau Thanks! :heart:

**Comment by FelixMalfait** [comment]
Thanks @pombredanne for the great feedback always! 
@ehconitin deserves most of the credit here 😁

**Comment by lucasbordeau** [comment]
@pombredanne You're welcome !
