### ISSUE TITLE
Events cannot be logged on Favorite standard object

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#4631]
## Bug Description

When adding a new favorite in the app, this is triggering the `save-event-to-db.job.ts`, itself triggering the following query: 
```
 await this.workspaceDataSourceService.executeRawQuery(
      `INSERT INTO ${dataSourceSchema}."event"
      ("name", "properties", "workspaceMemberId", "${objectName}Id")
      VALUES ($1, $2, $3, $4)`,
      [name, properties, workspaceMemberId, objectId],
      workspaceId,
    );
```

However, the `Event` standard object does not have a relation to `Favorite` standard object, leading to a bug while executing the job:
```
SELECT * FROM workspace_1wgvd1injqtife6y4rvfbu3h5."workspaceMember" WHERE "userId" = $1
INSERT INTO workspace_1wgvd1injqtife6y4rvfbu3h5."event"
      ("name", "properties", "workspaceMemberId", "favoriteId")
      VALUES ($1, $2, $3, $4)
/Users/charles/dev/twenty/twenty/packages/twenty-server/src/engine/workspace-datasource/workspace-datasource.service.ts:129
      throw new Error(
            ^
Error: Error executing raw query for workspace 20202020-1c25-4d02-bf25-6aeccf7ea419: column "favoriteId" of relation "event" does not exist

```

## Technical inputs

I feel we should decide what we want to log (maybe we want to ignore system objects) or add the relation to events on all standard objects

**Comment by charlesBochet** [comment]
Let's ignore standard objects having isSystem flag to true for now :)

**Comment by devalade** [comment]
Can you assign the issue to me?

**Comment by charlesBochet** [comment]
sure!

**Comment by Weiko** [comment]
@devalade I've just merged a fix as this bug was quite urgent and blocking our upcoming deploy. Closing the issue.
