### ISSUE TITLE
Update Background Blur on Menus

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4641]
# Desired behavior

The background blur properties should be:

```
backdrop-filter: blur(12px) saturate(200%) contrast(50%) brightness(130%)
background: rgba(252, 252, 252, 0.5)
```
### Add background blur on the calendar

![CleanShot 2024-03-25 at 09 14 45](https://github.com/twentyhq/twenty/assets/19412894/7d6b2ce9-e8ca-495d-ba9e-cfc192da0cca)

### Change the background opacity from 0.8 to 0.5 on the menus

![CleanShot 2024-03-25 at 09 21 19](https://github.com/twentyhq/twenty/assets/19412894/1be588ec-a9e5-418c-b83c-04629ade55b8)

**Comment by bottlewook** [comment]
Hey @Bonapara, I would like to work on this.

**Comment by Bonapara** [comment]
Sure, thanks @bottlewook!
