### ISSUE TITLE
Move all development commands to project.json

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#4645]
## Scope & Context

We are shifting to the following guideline to bring clarity in the Developer XP:
- production commands are located in the package.json and do not require `nx`
- development command (for contributors / individuals working on the project) should be located in project.json and require nx

The change has been done for `twenty-server` in: https://github.com/twentyhq/twenty/pull/4644/files

1) We should also do it for all other typescript packages
2) we should introduce a root project.json containing the main `start` command

**Comment by pacyL2K19** [comment]
We need to reflect these changes in the documentation as well
Currently some parts of the doc are broken due to #4644 

Should every PR associated with this issue come with an update on the documentation? Or you are planning another approach?

@charlesBochet

**Comment by pacyL2K19** [comment]
I can work on this @charlesBochet @FelixMalfait

**Comment by charlesBochet** [comment]
Hi @pacyL2K19, feel free to work on it, assigning it to you
The documentation has been updated (there is currently a slight delay between the PR being merged and the documentation being deployed)
