### ISSUE TITLE
Event description is overflowing

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#4647]
## Bug Description

Event description is overflowing in right drawer.

https://github.com/twentyhq/twenty/assets/71827178/5611a34b-cd5b-4624-a6af-b926448ad623

## Expected behavior

The line should break.

**Comment by martmull** [comment]
@bosiraphael there is an ellipsis now, and a tooltip to see the whole description:
![image](https://github.com/twentyhq/twenty/assets/29927851/c945ddcf-e47c-431b-b64c-42cd73cb998c)

Do you think there is still a bug?

**Comment by bosiraphael** [comment]
Yes, I fixed it he other day, I forgot to close the issue.
