### ISSUE TITLE
Update Card Name Chip Design on Kanban Views

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4651]
# Current behavior

The Kanban card name chips are `plain` and darker when being hovered.

![image](https://github.com/twentyhq/twenty/assets/19412894/09c47054-a99d-466b-a425-d597ba821611)

# Desired Behavior

The kanban card name chip should be transparent when not hovered, and `Transparent/Light` when hovered

![image](https://github.com/twentyhq/twenty/assets/19412894/d8a8b8a3-0ef5-4893-968f-80c662240ca8)

![CleanShot 2024-03-25 at 19 02 11](https://github.com/twentyhq/twenty/assets/19412894/c3cced76-142d-48f6-bfb6-52e293864ec2)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=24955-194300&mode=design&t=xKOKPr1F1nQcJSIR-11

**Comment by emadbaqeri** [comment]
Hey @Bonapara, I would like to work on this, 
the first image you've attached is broken. I think there is something in that picture that make me understand the problem

**Comment by Bonapara** [comment]
Fixed and done @emadbaqeri! Thanks for contributing :)
