### ISSUE TITLE
Update Icon Button Color and Menu Transparency with Icons

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4654]
# Current behavior

1. The icon color in the icon button is not dark enough.
2. The menu is not transparent and lacks icons

![CleanShot 2024-03-26 at 10 09 14](https://github.com/twentyhq/twenty/assets/19412894/49f03bbf-7e10-4984-859f-e36153183e69)

# Desired Behavior

1. It should use the "Secondary" variant
2. It should be transparent and utilize the same menu dropdown component as the filter/sort menu.

![CleanShot 2024-03-26 at 10 13 18](https://github.com/twentyhq/twenty/assets/19412894/3ac57ba0-2242-47c3-84ca-853fcfbe149c)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=24955-194210&mode=design&t=tQhqc1Lmoswn8bXw-11

**Comment by jeet1desai** [comment]
@Bonapara I can take this one, please assign this to me.

**Comment by Bonapara** [comment]
Sure @jeet1desai, thanks for contributing as always!
