### ISSUE TITLE
Batch endpoints on the REST API

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4655]
We currently have createMany endpoints on the GraphQL api but don't have a similar endpoint on the REST version.

We're currently building an "import from CRM X" feature and it would be handy to have it.

Note: this is not needed for metadata api. I think we'll rewrite the metadata REST API anyway

**Comment by charlesBochet** [comment]
Goal: rest api iso with graphql api on batch endpoints

**Comment by martmull** [comment]
Change or add to limit breaking changes, PUT to PATCH rest api verb
