### ISSUE TITLE
Save view by clicking outside popup while editing

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4657]
# Current Behavior

Pressing `Enter` while editing a view is necessary to save changes. However, this momentarily disables the "Delete" button, giving the impression it has been clicked.

https://github.com/twentyhq/twenty/assets/19412894/7c6c0d3e-67a6-42e0-883f-ba14234c1750

# Desired Behavior

Changes should be saved when clicking outside the popup or closing it with the "X" button. 

The popup should close instantly and save data in the background when 'Enter' is pressed, the popup is clicked outside, or the 'X' button is clicked.

**Comment by jeet1desai** [comment]
hello @Bonapara I can take this one, please assign this to me.
