### ISSUE TITLE
When clicking developers, a TypeError causes server error

### ISSUE THREAD

**Issue by arnavsaxena17** [twentyhq/twenty#4669]
## Bug Description

A clear and concise description of what the current behavior is.

When developers is clicked in the settings tab; it is expected to show the API keys section, however it is redirecting to a server error. 

The error log in the console is : Uncaught TypeError: Cannot destructure property 'length' of 'rawRows' as it is undefined.

<img width="1470" alt="Screenshot 2024-03-26 at 21 07 40" src="https://github.com/twentyhq/twenty/assets/16238974/4c71ac61-d192-4620-a18e-d4d63b7b1588">

https://github.com/twentyhq/twenty/assets/16238974/8098665e-1297-4d4a-b0a3-0131def4aa64

Please advise on how to go about to fix this?

**Comment by Jonathanlemon** [comment]
Hi @arnavsaxena17, I am unable to replicate this in main. Whenever I click developers I see the API keys section

**Comment by arnavsaxena17** [comment]
Tried resetting the database and reinstalling twenty but getting the same error.
What could I be missing?

**Comment by arnavsaxena17** [comment]
The problem is with react-data-grid. I tried - "7.0.0-beta.13", "7.0.0-beta.43".

While .13 is giving "Cannot destructure property 'length' of 'rawRows' as it is undefined"; .43 is giving "Uncaught TypeError: rawColumns2 is not iterable"


<img width="1470" alt="Screenshot 2024-03-27 at 16 12 45" src="https://github.com/twentyhq/twenty/assets/16238974/3633ed00-7f44-4e0d-844c-476f5d53495c">

**Comment by arnavsaxena17** [comment]
Fixed this by modifying Table component with the following initilization:

`export const Table = <Data,>({
  className,
  columns,
  components,
  headerRowHeight,
  rowKeyGetter,
  rows=[],
  onRowClick,
  onRowsChange,
  onSelectedRowsChange,
  selectedRows,
}: TableProps<Data>) => {
  console.log(rows);
  const { rtl } = useSpreadsheetImportInternal();

  return (
    <StyledDataGrid 
      columns={columns || []}
      direction={rtl ? 'rtl' : 'ltr'}
      rowHeight={52}
      {...{
        className,
        components,
        headerRowHeight,
        rowKeyGetter,
        rows,
        onRowClick,
        onRowsChange,
        onSelectedRowsChange,
        selectedRows,
      }}
    />
  );`
  
  
However, subsequently running into the issue of https://github.com/twentyhq/twenty/issues/4675

**Comment by thaisguigon** [comment]
Thank you for investigating @arnavsaxena17! I opened a PR that fixes this issue: https://github.com/twentyhq/twenty/pull/4722
