### ISSUE TITLE
BUG: When focusing the comment input, the new character are written on the last focused cell in the table

### ISSUE THREAD

**Issue by BenjaminBeguin** [twentyhq/twenty#468]
Here is a brief video demonstration for you to see:

https://github.com/twentyhq/twenty/assets/12866555/92d285a8-d25d-4d74-a6bb-a4912083e70c

I am suggesting a solution on my branch called **fix/comment_when_table_cell_focused** . Feel free to use it or not.

Note: I'm currently facing an issue with the Eslint configuration. The import order is not automatically fixed in my VScode for some reason. I will investigate it later.

## Here is some additional information:

Based on my understanding (since I only pulled the project a few hours ago and haven't went deep into it yet), the selection state is stored in a Recoil state, containing a position and a boolean indicating whether the selection is active or not. Additionally, there is a useHotKey function that captures key events and triggers certain actions. I believe the responsible code block is as follows:

```
useHotkeys(
  '*',
  (keyboardEvent) => {
    const isWritingText =
      !isNonTextWritingKey(keyboardEvent.key) &&
      !keyboardEvent.ctrlKey &&
      !keyboardEvent.metaKey;

    if (!isWritingText) {
      return;
    }

    if (captureHotkeyTypeInFocus) {
      return;
    }
    openEditableCell();
  },
  {
    enableOnContentEditable: true,
    enableOnFormTags: true,
    preventDefault: false,
  },
);
```

My proposed solution is to disable selection when the user clicks outside of the table. However, this may not be perfect, as it may not work if the comment input was automatically focused without a click from the user. 
A potentially better solution than the one I propose could involve using the onKeyDown event on the cell components to open the editable cell at that level instead of using the useHotkeys. That actually looks simpler to implement too.

I'm curious to hear your thoughts on this!

Please feel free to disregard everything I've mentioned. I was simply experimenting with the application and encountered a bug. I wanted to find a solution. I hope it is still helpful!

Ben

**Comment by FelixMalfait** [comment]
Wow thanks a lot Ben that's a nice and very well-detailed issue!

**Comment by FelixMalfait** [comment]
Sorry I couldn't find your branch or a fork on your profile? I don't think you have the permissions to create a branch on that repo so maybe your push failed for that reason?

I'd say removing the soft focus when clicking outside of the table could be a nice behaviour, regardless of the bug. I'm not sure we should always have 1 cell soft-focused as it's the case currently.
As for the second solution, I'm not good enough to have an opinion 😅. But I'm sure @lucasbordeau will!

**Comment by lucasbordeau** [comment]
We're actually looking into this, the new implementation of table keyboard controls we just merged introduced conflicts and side effects with other parts of the app.

The current solution we think about is to use the scope feature of useHotkeys and/or also allow the table to lose its focus (like you mentioned) by clicking outside or using escape.

**Comment by lucasbordeau** [comment]
https://github.com/twentyhq/twenty/issues/469

**Comment by BenjaminBeguin** [comment]
Make sense! 
We had very similar issues at my company (We build low code / Excel like tables) and scoping things (States / events)  was our way to go

@FelixMalfait Oh yeah, I couldn't push!  
I will push in my fork in a couple of minutes, just in case it's helps

**Comment by BenjaminBeguin** [comment]
There we go: 
https://github.com/twentyhq/twenty/pull/470/files 

I used usehook-ts package for simplicity. 
Again, feel free to disregard it :) I'm pretty sure there is a better solution than my patch 

https://bundlephobia.com/package/usehooks-ts@2.9.1

**Comment by charlesBochet** [comment]
Thanks a lot for this discussion. We have introduced a new hotkey pattern to fix this behavior. We will add a section in the documentation shortly
