### ISSUE TITLE
The View switcher is hidden behind the table header

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#4681]
## Bug Description

The View switcher is hidden behind the table header

<img width="302" alt="Capture d’écran 2024-03-27 à 16 21 31" src="https://github.com/twentyhq/twenty/assets/71827178/a0fd23ce-5c52-4034-8f99-432b5946155f">

## Expected behavior

Should be above the table header.

## Technical inputs

Probably a z-index problem

**Comment by arnavsaxena17** [comment]
Solved it by increasing the z index of the TopBar from 5 to 7. Z index of the dropdown is 6.

**Comment by FelixMalfait** [comment]
Sure thanks @arnavsaxena17!
