### ISSUE TITLE
[Multi-workspace] I should be able to accept an invite if I'm already logged in

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4689]
Since we introduced the 1-user to multiple-workspaces use-cases this created a few edge cases.
One of which is that, to accept an invite, you have to be logged out and then login again.

**Comment by Bonapara** [comment]
Can we display the actual onboarding flow over his workspace for this usecase? We can also redirect to the actual onboarding flow when he opens the invite

**Comment by FelixMalfait** [comment]
It felt like it's a slightly longer loading time for something that could be a more streamlined page, but if you prefer it this way we can yes @Bonapara! so just to be sure: also for OAuth flow you would do that over the workspace? cc @AdityaPimpalkar would you mind taking this into account then? Thanks!

**Comment by martmull** [comment]
# Technical Stategy

- add userToWorkspace if loggedIn and /invite/<inviteHash> path
- use switchWorkspace to log user to new workspace
