### ISSUE TITLE
"This user already exists" when creating a new workspace

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4695]
# Description

When trying to create a workspace, I get the following bug (Private mode - email that is not in the system)

![CleanShot 2024-03-28 at 16 24 53@2x](https://github.com/twentyhq/twenty/assets/19412894/028b0eee-f8e9-428f-9b92-0603932e9b49)

**Comment by Bonapara** [comment]
![CleanShot 2024-04-15 at 12 35 25@2x](https://github.com/twentyhq/twenty/assets/19412894/2d5b036b-d832-41ad-

When attempting to create an account, this error message is displayed. Could still reproduce it, will investigate more

**Comment by FelixMalfait** [comment]
Duplicate: https://github.com/twentyhq/twenty/issues/4809
