### ISSUE TITLE
Rename "Notifications" into "Inbox" in the Sidebar

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4698]
# Current behavior

Name is "Notifications"
The icon is a "Bell"

![CleanShot 2024-03-28 at 16 42 52@2x](https://github.com/twentyhq/twenty/assets/19412894/327a813d-f428-4b5b-8bf4-29ca021d108d)

# Desired Behavior

Should be changed to "Inbox"
The icon should be set to "Inbox" as well

![CleanShot 2024-03-28 at 16 44 42@2x](https://github.com/twentyhq/twenty/assets/19412894/5ca6e55d-2750-40fb-b583-e9d7ad34799c)

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
Raising PR for this
