### ISSUE TITLE
Add queue worker to docker compose

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4703]
We worked on a docker compose but I realized we don't have a queue worker.

While this isn't strictly required to run the app, it's helpful to have it for some features (mostly gmail sync for now)

`yarn nx worker twenty-server`

**Comment by Freebios** [comment]
Added by @charlesBochet in https://github.com/twentyhq/twenty/commit/abcec13379db12b85d907b2fbf0b128adec94202
Closing!
