### ISSUE TITLE
Table rendering very slow after a large number of contacts are uploaded

### ISSUE THREAD

**Issue by arnavsaxena17** [twentyhq/twenty#4708]
## Current behavior
If the number of records is more than say a few hundred, the table is not rendering efficiently after a few lines of scrolling. 

To replicate this issue, upload the attached csv with over 400 lines and then scroll through the page. The table render is very slow.

https://github.com/twentyhq/twenty/assets/16238974/25cd4edf-7a9f-4472-be9b-2b5a332f5b2b

[upload_candidates.csv](https://github.com/twentyhq/twenty/files/14801376/upload_candidates.csv)

## Expected behavior
Table scrolls smoothly and data is displayed API response is received.

**Comment by FelixMalfait** [comment]
Closing as we did a lot of improvements since this was open!
