### ISSUE TITLE
Implement google calendar incremental sync

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#4710]
## Scope & Context

We are implementing google calendar integration.

https://developers.google.com/calendar/api/guides/sync#incremental_sync

## Technical inputs

Create `google-calendar-incremental-sync.service`:
- Get the syncCursor for the calendarChannel
- Call [events.list](https://developers.google.com/calendar/api/v3/reference/events/list) method and provide the sync token as a parameter
- Save the new events
- Update the events for which there are some changes
- Delete the deleted events

A cron job will call this service regularly to keep the events updated.

**Comment by Kanav-Arora** [comment]
Hi @bosiraphael 
Can I work on this issue?

**Comment by bosiraphael** [comment]
Hello @Kanav-Arora! Sorry, I will work on this issue next week, I just forgot to assign myself ;)
