### ISSUE TITLE
Api key doesn't display the good expiration date

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4714]
# Bug

The expiration date display `29 days` instead of `Never`

https://github.com/twentyhq/twenty/assets/19412894/ee8222b9-b2e1-4081-b8b3-3a9fa21e2cfa

**Comment by IsabelaPO** [comment]
Hello! While trying to recreate the bug, this appears: 
<img width="1439" alt="image" src="https://github.com/twentyhq/twenty/assets/106828051/e1bedc3c-3feb-420b-9ebb-9c6e33a2f1ce">
Im not sure why this is happening. Can someone help?

**Comment by Kanav-Arora** [comment]
Hi @IsabelaPO 
I think this is being fixed on main branch. Please wait will update once done
