### ISSUE TITLE
Selected search hit has visibility issues in Dark Mode and has styling inconsistency in Light Mode

### ISSUE THREAD

**Issue by pereira0x** [twentyhq/twenty#4719]
## Bug Description

In Dark Mode, the active hit search on the search menu cannot be seen, while in Light Mode, it does not follow the styling type of other search hits. This inconsistency makes it difficult for users to identify the active mark search hit.

In Dark Mode, the active hit search appears to blend with the background, making it virtually invisible.
<img src="https://github.com/twentyhq/twenty/assets/26422084/94f45da4-9483-466d-ae56-60ce49488d16 " alt="img" width="500"/>

In Light Mode, the active hit search has a different styling compared to other search hits, creating a visual inconsistency.
<img src="https://github.com/twentyhq/twenty/assets/26422084/a8ac108b-d2d5-4d6d-851e-fb4439791525" alt="img" width="500"/>

## Expected behavior

In Dark Mode, the active hit search should have a contrasting color or highlight to ensure visibility against the background.
<img src="https://github.com/twentyhq/twenty/assets/26422084/2278f7f8-9c2f-4dc3-a3d1-4d6e80298115" alt="img" width="500"/>

In Light Mode, the active hit search should adhere to the same styling as other search hits for consistency across themes.
<img src="https://github.com/twentyhq/twenty/assets/26422084/f051adcd-bf3c-48e8-b9b1-51b6422d82eb" alt="img" width="500"/>

## Technical inputs

We may need to adjust the CSS to ensure proper visibility and consistency in both Dark and Light Modes.

**Comment by pereira0x** [comment]
Im already working on this, can I be assigned to this issue?

**Comment by martmull** [comment]
closing because it is fixed by https://github.com/twentyhq/twenty/pull/4720
