### ISSUE TITLE
Implement Non-dismissable Action-required Alerts in UI

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4723]
# Scope

We want to display alerts that cannot be dismissed until an action is taken, which is useful for situations like errors requiring action, such as resynching your email mailbox.

# Desired Behavior

Display banners/alerts at the top of the content section:

### Indexes

![image](https://github.com/twentyhq/twenty/assets/19412894/7f42016e-2410-459a-9184-88cb26e688dc)

### Record pages

![image](https://github.com/twentyhq/twenty/assets/19412894/2f6f51e8-c3a9-4e54-a440-03738d4f7b0a)

### Settings

![image](https://github.com/twentyhq/twenty/assets/19412894/dfe145df-d081-4d93-bad6-7a146ff13efd)

### Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=26972-65984&mode=design&t=mzGw3gdPlFH6KOCR-11

# Components

![CleanShot 2024-04-01 at 10 50 23@2x](https://github.com/twentyhq/twenty/assets/19412894/8ec6e3c7-bd1b-4e56-9282-049214d58973)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=26972-55801&mode=design&t=mzGw3gdPlFH6KOCR-11
```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/4725
- [ ] https://github.com/twentyhq/twenty/issues/4726
```

**Comment by Kanav-Arora** [comment]
Hi @Bonapara 
Could you assign me this issue and mark it as blocked as it can be done after above two issues are done

**Comment by Bonapara** [comment]
Done, thanks @Kanav-Arora!

**Comment by DecodersLord** [comment]
@Bonapara What's the status of this issue? I see that the code 'informationBanner' exists and works to display the same. If this still needs to be worked on please assign this to me and give me some input on what needs to be added to the the existing module.

**Comment by Bonapara** [comment]
I think @bosiraphael is on it but otherwise happy to assign it to you

**Comment by bosiraphael** [comment]
This issue is already done :)
