### ISSUE TITLE
Add 'Inverted' Variants to Button Component for Banners

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4725]
# Scope

We want to add new "Inverted" variants to the button component to be used first for the banners. These variants are meant to be used on a colorful background.

# New variants

![CleanShot 2024-04-01 at 11 34 13@2x](https://github.com/twentyhq/twenty/assets/19412894/dd97e9db-dc2f-441b-ad86-dec7a3b065b0)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=3122-142114&mode=design&t=mzGw3gdPlFH6KOCR-11

**Comment by flatypus** [comment]
Hi! I'll try to work on this!

**Comment by Bonapara** [comment]
Thanks for contributing @flatypus!

**Comment by Bonapara** [comment]
Hi @flatypus are you still on it? @charlesBochet maybe we should do it together

**Comment by flatypus** [comment]
Hey! Sorry, I've been busy with work in the last month, but I have started on completing this on my branch. If you could give me until the end of the week to try to finish this that'd be great, I'll leave a post on Sunday if I can't.

**Comment by flatypus** [comment]
Here's the PR, I'm not sure if there's a better way to modify the Storybook component background color to make the inverted buttons actually look good, so pls lmk

**Comment by Bonapara** [comment]
Hey @flatypus, thanks for your work! When you mentioned you couldn't find a `Transparent Blue`, was it for the disabled states? If so, disabled states are created by applying transparency to the entire button, not by using a specific color. In your video, I noticed at 24 seconds that the button text is lighter than the button border. Do you know why?

**Comment by flatypus** [comment]
> Hey @flatypus, thanks for your work! When you mentioned you couldn't find a `Transparent Blue`, was it for the disabled states? If so, disabled states are created by applying transparency to the entire button, not by using a specific color. In your video, I noticed at 24 seconds that the button text is lighter than the button border. Do you know why?

Oh, no I've already added that opacity line for the disabled bit. That's not the problem. 

If you notice for focused elements (like in the screenshot), the box-shadow isn't red or anything; it's a 10% transparency shade of blue. I wasn't sure how to get that in code. I also wanted to point out that it's that shade of blue for all the types (danger, blue, and default).

<img width="1261" alt="image" src="https://github.com/twentyhq/twenty/assets/68029599/8723c566-053e-4491-92f3-5774e8e1dd40">

**Comment by Bonapara** [comment]
Oh I see! You're right, that feels awkward, thanks for noticing! I just updated the focus color to `Transparent/medium` for all inverted buttons:
![CleanShot 2024-06-03 at 11 08 56](https://github.com/twentyhq/twenty/assets/19412894/dd930542-5462-4543-bfe4-65e5d8365e28)

**Comment by flatypus** [comment]
Got it; I will update the code to reflect that. In that case, do you know if there's a dedicated way to make colors transparent in the codebase? I've just been doing the template string thing with ${__}1A, but that feels strange given how much effort we've put in to using defined strings.

**Comment by flatypus** [comment]
Cool, thanks @Bonapara! I've just updated the code to reflect your figma change. It should be ready for a review now.
