### ISSUE TITLE
latest docker composenot works

### ISSUE THREAD

**Issue by NikolayBuslaev** [twentyhq/twenty#4744]
yarn nx database:reset return error

![image](https://github.com/twentyhq/twenty/assets/22391269/e372186b-998d-419e-b842-cb206d2822ab)

**Comment by FelixMalfait** [comment]
Sorry we deprecated docker for local dev and recommend just running node locally for now (but your Postgres can run in a docker). It's easier to have just 1 install for every.

Docker-compose is still recommended for simple self-hosting configs!
