### ISSUE TITLE
[Multi-workspace] [Timebox 1d] When clicking on invitation link, if I am connected, I am not added to the new workspace

### ISSUE THREAD

**Issue by martmull** [twentyhq/twenty#4751]
# Feature
Users needs to be logged out to join new workspace. This should be possible by being logged in.

# Technical Strategy
Use the useSignInUp hook logic and make it available when a user is logged in

**Comment by FelixMalfait** [comment]
duplicate: https://github.com/twentyhq/twenty/issues/4689
