### ISSUE TITLE
Floating Icon Button Blurs on Hover

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4764]
# Description

When hovering over the "Floating icon button," the scale effect causes it to blur:

https://github.com/twentyhq/twenty/assets/19412894/959339c5-c96f-48ec-87c5-dc4e925bc15f

# Desired Behavior

The button shouldn't be blurred when hovered.

**Comment by martmull** [comment]
Can't reproduce, this looks fixed
