### ISSUE TITLE
High memory usage while running migrations in the Docker-compose

### ISSUE THREAD

**Issue by Freebios** [twentyhq/twenty#4772]
## Bug Description

In order to run Twenty using docker-compose, we must run migrations and seeding of the database on the first run. This leads to a high memory usage of about 1.5GiB.

One explanation could be the installation of additional dependencies using yarn as recommended in the Docker doc https://docs.twenty.com/start/local-setup/docker-setup#step-4-migrate--seed

## Expected behavior

It would be nice to be able to reduce this in order to be able to run the docker-compose on smaller HW configs

## Technical inputs

We could check what dependencies are missing and include them in the prod dependencies of twenty-server

**Comment by amitoo7** [comment]
Hi @Freebios 
Do you know of any expected date to solve this issue?
