### ISSUE TITLE
AAU I want to re-order my views with drag & drop.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#4782]
## Scope & Context

In the view list : 

![image](https://github.com/twentyhq/twenty/assets/26528466/6ed3a6b4-2ab3-444b-978b-f10bf971c075)

## Current behavior

I can create and edit views but not re-order them.

## Expected behavior

I want to be able to re-order my views in the list, the same way that I do it with my favorites.

**Comment by lucasbordeau** [comment]
@charlesBochet Do we need to add a position field on views ?

**Comment by charlesBochet** [comment]
Yes! 
position field of type POSITION

**Comment by FelixMalfait** [comment]
fyi position field is already there 

<img width="1040" alt="Screenshot 2024-04-05 at 13 26 06" src="https://github.com/twentyhq/twenty/assets/6399865/87ac3ec2-194b-4091-9a02-96c1a8740138">
