### ISSUE TITLE
Disable Command Menu Scrollbars

### ISSUE THREAD

**Issue by Kanav-Arora** [twentyhq/twenty#4788]
## Bug Description

In `cmd + k` for command menu on clicking arrow down key the view is getting shifted due to horizontal and vertical scrollers.

https://github.com/twentyhq/twenty/assets/62852363/c0999cd3-6651-421f-93c8-dedf7d84e038

## Expected behavior

There should be no scrollers and padding should remain same.

## Technical inputs

Disable scrollers.

**Comment by FelixMalfait** [comment]
would be great to fix before we release the next version, thanks for catching this 
<img width="730" alt="Screenshot 2024-04-03 at 21 38 30" src="https://github.com/twentyhq/twenty/assets/6399865/bf5c9759-246c-44a3-8832-9a7dcc4700bd">

Probably introduced by this https://github.com/twentyhq/twenty/pull/4512
