### ISSUE TITLE
STORAGE_LOCAL_PATH env var is always interpreted as relative with origin '/app/packages/twenty-server' 

### ISSUE THREAD

**Issue by Flexusma** [twentyhq/twenty#4794]
## Bug Description

When setting the `STORAGE_LOCAL_PATH` env var it is interpreted as a relative path (originating at `/app/packages/twenty-server`) even if it starts with a /.

**Example:** 
Set STORAGE_LOCAL_PATH=/storage

Data is stored at `/app/packages/twenty-server/storage`

## Expected behavior

The folder at `/storage` should be used for storing data

## Technical inputs

On further note, the startup script uses another prefix to create the db_initialized file:

Logs:
```
No migrations are pending

Successfuly migrated DB!

touch: /app/<path>
```
The STORAGE_LOCAL_PATH is being prefixed with `/app/`. This would only make sense, if the server would use /app as a storage root and not /app/packages/twenty-server.

Setting `STORAGE_LOCAL_PATH=../../<path>` env variable only and manually setting the volume mount to `/app/<path>` works.
Let me know if I misunderstood or overlooked something.

**Comment by Freebios** [comment]
Hi there, sorry for this delay.
@FelixMalfait I assume that this is not an issue completely related to the Dockerfile entrypoint, but I notice that we have a mismatch of how this path is being handled anyway.

I think that @Flexusma was refering to the use of the STORAGE_LOCAL_PATH in here https://github.com/twentyhq/twenty/blob/c76bc4729d2ec29dcb5b07c43b0e333cc2ab4467/packages/twenty-server/src/engine/integrations/file-storage/file-storage.module-factory.ts#L26

I do use the `STORAGE_LOCAL_PATH` in https://github.com/twentyhq/twenty/blob/c76bc4729d2ec29dcb5b07c43b0e333cc2ab4467/packages/twenty-docker/twenty/entrypoint.sh#L13 to write a lock after initializing the database, it's actually in the wrong path `/app/$STORAGE_LOCAL_PATH` vs `/app/packages/twenty-server/$STORAGE_LOCAL_PATH`, but doesn't seem related to the issue.

Two things to consider:
- If we change the behavior of the server, it would be great to harmonize it with the dockerfile's entrypoint
- We need to make sure that there won't be any breaking change related to eventually running the init database script again (as the lock will not be found)

**Comment by Flexusma** [comment]
> I do use the STORAGE_LOCAL_PATH in https://github.com/twentyhq/twenty/blob/c76bc4729d2ec29dcb5b07c43b0e333cc2ab4467/packages/twenty-docker/twenty/entrypoint.sh#L13 to write a lock after initializing the database, it's actually in the wrong path /app/$STORAGE_LOCAL_PATH vs /app/packages/twenty-server/$STORAGE_LOCAL_PATH, but doesn't seem related to the issue.

This does happen for my setup as well, so the database initialisation is run on every container startup. Not a huge problem though, just increases container startup time.

**Comment by Freebios** [comment]
Good to know, it mean we can issue a fix without breaking people DB!
Thanks for the feedback

**Comment by magrinj** [comment]
Hello @Flexusma,
I've just created a PR to fix this issue, we'll now handle absolute path if your env variable start with an `/`, if it's not the case we'll still prefix it with `process.cwd()`

**Comment by Flexusma** [comment]
Sounds great, thanks! I didn't want to make a PR for this, as this var is used in a lot of places and I'm honestly not too deep into the codebase yet :)
