### ISSUE TITLE
Phone field isn't nicely formatted in display mode

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4796]
# Current Behavior
Input mode is nicely formated:

<img width="307" alt="Screenshot 2024-04-04 at 09 39 52" src="https://github.com/twentyhq/twenty/assets/6399865/d33b4cf6-16ee-475c-a3b6-cdc1396db944">

But display mode isn't :
<img width="361" alt="Screenshot 2024-04-04 at 09 40 24" src="https://github.com/twentyhq/twenty/assets/6399865/5a96b8a7-d9eb-439f-97ab-a6ec41962bd9">
<img width="216" alt="Screenshot 2024-04-04 at 09 40 18" src="https://github.com/twentyhq/twenty/assets/6399865/81d88def-19a0-4a82-9598-6e94f18f26ab">

# Implementation

It seems that the lib we use has a built-in function to format number.
Let's display number in the nice national format with space/dash formatting 

<img width="1261" alt="Screenshot 2024-04-04 at 09 42 37" src="https://github.com/twentyhq/twenty/assets/6399865/1b973586-87ef-4353-9bab-98337f41b352">

**Comment by TheUnspokenFifth** [comment]
I am working on this.
