### ISSUE TITLE
Add calendar settings option in settings account dropdown

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#4798]
## Scope & Context

Add calendar settings option in settings account dropdown

## Technical inputs

<img width="715" alt="Capture d’écran 2024-04-04 à 10 44 53" src="https://github.com/twentyhq/twenty/assets/71827178/858e467c-b15b-4e27-8349-f914abf17465">

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=23338-13897&mode=design&t=ObzjUTqSP8jR9DQz-11

- Add link to calendar settings in `SettingsAccountsRowDropdownMenu`

**Comment by Anchit1909** [comment]
Hey @bosiraphael, I would like to work on this. Could you please assign this issue to me?

**Comment by FelixMalfait** [comment]
Thanks @Anchit1909!
