### ISSUE TITLE
I should be able to use "enter" key to create profile

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4808]
Enter key doesn't seem to work to move to the next stage here:

<img width="1202" alt="Screenshot 2024-04-04 at 15 09 19" src="https://github.com/twentyhq/twenty/assets/6399865/ea9b6ce1-a1f3-4493-94ea-9f216c896cd8">

**Comment by shubh0709** [comment]
Hey @FelixMalfait, I can take this up, can you please assign this to me 🙂

**Comment by FelixMalfait** [comment]
Thanks @shubh0709!

**Comment by ijreilly** [comment]
After a quick investigation, it seems that we already have a piece of code attempting to enable this behaviour, based on hotkeyScope as we want to: [CreateProfile.tsx#L129](https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/pages/auth/CreateProfile.tsx#L129), but it's not working most of the time indeed (from my tests). 
There is something to fix with the hotkeyScope. 

@qnsi thank you for your contribution, are you still interested in further digging into this given the above? If so I can assign you to the issue. thanks

**Comment by qnsi** [comment]
Hi, @ijreilly I am interested, although I will be going on vacation, having computer access back on Wednesday. So if @shubh0709 want to take over I am fine with that. If not I can come back to this Wednesday

**Comment by ijreilly** [comment]
@qnsi I am taking over the issue as we are working on a new release. Thank you for having digged into it :)
