### ISSUE TITLE
Records with empty date fields disappear when sorting in descending order in Kanban view

### ISSUE THREAD

**Issue by joachimBrindeau** [twentyhq/twenty#4818]
## Bug Description

When viewing object opportunities (or potentially other objects) in the Kanban view and sorting by a date field, records that have an empty value for the sorted date field completely disappear from the view when sorting in descending order. This issue does not occur when sorting in ascending order.

## Expected behavior

As when sorting in ascending order, Records with an empty value for the sorted date field should remain visible in the Kanban view, grouped together at the end of the list.

**Comment by charlesBochet** [comment]
Hi @joachimBrindeau Thanks for reporting it. I'm linking it in another issue. It should be tackled soon

**Comment by joachimBrindeau** [comment]
Merci !
