### ISSUE TITLE
Add a basic Github CI workflow and Playwright test for the website

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4832]
We don't test the build/start of twenty-website (our marketing website).

Would be good to add a Github workflow that runs if some files where modified in `packages/twenty-website` and checks that the website is still building.

We don't have any test but having a basic integration test with playwright  would also be helpful 
https://nextjs.org/docs/app/building-your-application/testing/playwright

**Comment by anoopw3bdev** [comment]
Sure thing @FelixMalfait

**Comment by anoopw3bdev** [comment]
Hi @FelixMalfait I have created a draft PR for the workflow, this is my first time working on writing a workflow, do you have any suggestions on how can i test and verify the same before creating a PR to main branch. Thanks!

**Comment by BOHEUS** [comment]
@FelixMalfait can this issue be closed and new one created only for writing Playwright tests as Github workflow was merged earlier?

**Comment by FelixMalfait** [comment]
@BOHEUS sure good point! Although this was for the website (twenty.com), I don't think we have an issue to track E2E tests for that
