### ISSUE TITLE
Implement Context-Specific Icons in Breadcrumb Navigation

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4834]
# Current Behavior

Company icon is universally present in the breadcrumb of all object detail pages, irrespective of the object type.

![CleanShot 2024-04-05 at 10 00 32](https://github.com/twentyhq/twenty/assets/19412894/7b30e23f-09c8-40f1-ba3c-e3acfd96e5f7)

# Desired Behavior

The breadcrumb should display an icon that matches the type of the record object, e.g., a User icon for People detail pages.

![CleanShot 2024-04-05 at 10 01 28](https://github.com/twentyhq/twenty/assets/19412894/8c22f5d9-c2aa-42ea-badd-30fb8ad12d01)

**Comment by anoopw3bdev** [comment]
Hi @Bonapara feel free to assign this to me!

**Comment by Bonapara** [comment]
Sure @anoopw3bdev, thanks for contributing!
