### ISSUE TITLE
Update Opacity and Apply backdrop-filter to all Transparent Colors

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4836]
# Current Behavior

We have 3 transparent colors in the theme. We should only have: `Transparent/Primary` and `Transparent/Secondary`. 

# Desired Behavior

The plan is to switch the opacity from 0.8 to 0.5 on `Transparent/Primary` and `Transparent/Secondary`. 

This should allow us to **remove** `forBackdropFilter: RGBA(GRAY_SCALE.gray10, 0.5)` from the theme. 

We need to ensure that `backdrop-filter: blur(12px) saturate(200%) contrast(50%) brightness(130%);` **applies to all elements/components** using `transparent/primary` or `transparent/secondary`. Specifically, this parameter needs to be updated on the 'Floating icon button' and All menus (That should have these properties = blur + transparent/secondary).

### Floating icon button:
![CleanShot 2024-04-05 at 11 06 10](https://github.com/twentyhq/twenty/assets/19412894/986992eb-d691-47bf-b2e8-d5d98619de29)

### Menus:
![CleanShot 2024-04-05 at 11 06 41](https://github.com/twentyhq/twenty/assets/19412894/81d5171b-bee6-4c23-ae5e-d88e9b89003b)

Please verify if any other elements use ﻿Transparent/Primary and ﻿Transparent/Secondary to apply the background filter to them. Avoid referring to Figma, as the blur effect differs there.

**Comment by jss475** [comment]
Hey @Bonapara. Can you assign this to me? :)

**Comment by Bonapara** [comment]
Sure @jss475 , thanks for contributing!
