### ISSUE TITLE
Implement row re-ordering via drag-n-drop on the frontend

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4846]
# Current Behavior

Currently, we have implemented "positions" for rows on the backend, which are already functional in the kanban view. However, this feature is not yet utilized in list views.

# Desired Behavior

The objective is to enhance the list view functionality by introducing a grip that appears when hovering over the left space preceding the 24px checkbox container, enabling the repositioning of rows. This grip should not be available for the first row. Additionally, ensure the margin between the table and the container (2) is preserved.

### Grip should appear on Hover
https://github.com/twentyhq/twenty/assets/19412894/e5c1c2d4-8c27-4751-964a-3f252aac041d

### Maintain the left gap
![CleanShot 2024-04-05 at 16 57 31](https://github.com/twentyhq/twenty/assets/19412894/a7490d17-1f5e-49d1-b513-cf375f37b971)

# Figma

### Prototype
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=1406-44830&mode=design&t=PmgkzYTgKU0jhKkl-11

### Component

![CleanShot 2024-04-05 at 16 59 38](https://github.com/twentyhq/twenty/assets/19412894/084dc80e-7ee2-4d0a-9277-e4215c59b115)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=27329-204639&mode=design&t=PmgkzYTgKU0jhKkl-11

**Comment by FelixMalfait** [comment]
I think for v1 we should do like Notion if a filter was applied and someone tries to drag:

<img width="512" alt="Screenshot 2024-04-16 at 09 21 46" src="https://github.com/twentyhq/twenty/assets/6399865/91e3e179-8dab-4138-b1cb-855d8440648d">

**Comment by charlesBochet** [comment]
We already have a few drag and drop features implemented on the frontend:
- ViewPicker > View re-ordering
- Kanban view (Opportunities view)
- Table Options > Fields re-ordering

1) To do this feature, we should first try to use DraggableList components (see example in the implementations listed above).
2) On drop, we need to update the position of the dropped record (1 record = 1 row). All records that are displayed in views have a position field where you can store the position. This field is a float so you can just compute the average of the record below and above the dropped record
3) The table view is sorted by position by default. We can also add additional sorts. If additional sorts are present, we would need to implement the modal according to the screenshot of @FelixMalfait 
4) If you drop last, you can set the position as 'last'

**Comment by vascopaisana** [comment]
Hello, could you assign me and @kikoleitao this issue, as we will try and work together on it?

**Comment by Bonapara** [comment]
Hi @vascopaisana, I've just assigned you! I couldn't assign @kikoleitao because he needs to comment on the issue first. Thanks to both of you for contributing!

**Comment by kikoleitao** [comment]
> Hi @vascopaisana, I've just assigned you! I couldn't assign @kikoleitao because he needs to comment on the issue first. Thanks to both of you for contributing!

Hi! Could you also assign this issue to me?

**Comment by FelixMalfait** [comment]
Thanks @kikoleitao @vascopaisana - love the idea of people pairing to solve issues :)

**Comment by FelixMalfait** [comment]
Hey @kikoleitao @vascopaisana did you manage to build something? Thanks!

**Comment by kikoleitao** [comment]
Hi! Yes, we are still working on it! One problem we are having is that while dragging a row, the rows are also being selected like shown in this video: 

https://github.com/twentyhq/twenty/assets/92337535/6389e2c4-e7c6-451c-a3c5-97a86e08382b

Is this a problem or should we limit the zone where row selection is possible? If so, where would we make this change? Thanks!

**Comment by Bonapara** [comment]
@kikoleitao yes we should keep the `drag to select` but exclude `the drag to reorder` "column" from it:
![image](https://github.com/twentyhq/twenty/assets/19412894/549e73a3-9906-4de5-8dd2-ceb5866bb63c)

**Comment by FelixMalfait** [comment]
Great! Yes you need to exclude the column on the left from the drag selection area, the drag selection area should start on its left. A good starting point would be `DragSelect.tsx`

**Comment by vascopaisana** [comment]
Thank you for your advice, we managed to fix that! We're hopeful we'll get it ready soon as just the modal implementation is left.

**Comment by FelixMalfait** [comment]
Great!!! Can't wait to see!

**Comment by kikoleitao** [comment]
Hi!

I'm working on the modal implementation and need some help with two issues regarding table sorting:

Checking if the table is sorted: I initially tried using [isSortSelectedState](https://github.com/twentyhq/twenty/blob/4e533bf2ef631c7a77872fae4240bd3c5b961bd6/packages/twenty-front/src/modules/object-record/object-sort-dropdown/hooks/useObjectSortDropdown.ts#L54), but it remains false even after sorting the table.

Removing the table's sorting: I considered using the [resetState callback,](https://github.com/twentyhq/twenty/blob/4e533bf2ef631c7a77872fae4240bd3c5b961bd6/packages/twenty-front/src/modules/object-record/object-sort-dropdown/hooks/useObjectSortDropdown.ts#L24), but I'm not sure if this is the correct approach.
Could you provide some guidance on how to achieve these tasks?

Thank you for your assistance!

**Comment by charlesBochet** [comment]
HI @kikoleitao, you'll need to update the view sorting actually, and the table will follow.
to check if a sort is selected: useGetCurrentView

And to change it: removeCombinedViewSort / upsertCombinedViewSort
