### ISSUE TITLE
Update the checkbox component on Tables Rows and Kanban cards

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4850]
# Current behavior

The current checkbox component used for table rows and Kanban cards lacks hover functionality:

https://github.com/twentyhq/twenty/assets/19412894/45977959-2c6c-4b4b-b043-db69a51371a1

# Desired Behavior

```
🚨Make sure to respect the spacings of the Figma 🙌
```

We want to replace them with the hoverable variant of the checkbox:

### Table
https://github.com/twentyhq/twenty/assets/19412894/8c00e648-0fd1-449e-bc1a-2515405ab599

### Kanban
![CleanShot 2024-04-05 at 17 22 31](https://github.com/twentyhq/twenty/assets/19412894/f6bc433c-26a2-4301-a31d-dcfa2ecc705e)

### Component
![CleanShot 2024-04-05 at 17 19 21](https://github.com/twentyhq/twenty/assets/19412894/174002c6-e2f4-45c7-9ac6-432a77559116)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=14603-51328&mode=design&t=PmgkzYTgKU0jhKkl-11

**Comment by auroOra3** [comment]
Hello, could I have this issue?

**Comment by Bonapara** [comment]
Sure @auroOra3, thanks for contributing! We only need #4848 to be merged first

**Comment by Bonapara** [comment]
Hi @auroOra3, it seems the other issue has finally been completed. Do you still want to work on this one?

**Comment by Faisal-imtiyaz123** [comment]
@lucasbordeau Can you assign this also please.

**Comment by mittalsam98** [comment]
Hey @lucasbordeau I would to pick this up, seems no fix is raised by anyone till now

**Comment by Faisal-imtiyaz123** [comment]
Hi @mittalsam98 Just a heads-up that I'm currently working on this issue!

**Comment by lucasbordeau** [comment]
@Faisal-imtiyaz123 Assigned, don't hesitate to open a draft PR and link this issue with "Closes #4850"

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara For the checked and intermediate checkboxes the current behavior is that they have a square blue background.
<img width="232" alt="Screenshot 2024-07-30 at 4 18 34 PM" src="https://github.com/user-attachments/assets/99012794-e35e-4eee-bf0a-0c02126a60ee">
So Should it be removed ?? Because this is not how it is done in figma. Also these checkboxes should also have a background color on hover as is in the figma file. ryt??

**Comment by Bonapara** [comment]
@Faisal-imtiyaz123, I believe the issue lies not with the checkbox background but with the row background, which no longer changes when selected. I've created this issue to address it:

https://github.com/twentyhq/twenty/issues/6461
