### ISSUE TITLE
Kanban table left padding is too big 

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4852]
# Current behavior

At the left of the Kanban views, the padding is 2x larger than on Figma and the `table` views

https://github.com/twentyhq/twenty/assets/19412894/9b917901-3acd-4632-93f5-fc7f6c3b300f

# Desired Behavior

The padding should only be 8px and perfectly fit with the Table view.

**Comment by TahsinAyman** [comment]
The video seems to be wrong or corrupted. 
![image](https://github.com/twentyhq/twenty/assets/87863787/35bb7841-a31e-409d-bc02-f71685fa69f4)

**Comment by Bonapara** [comment]
Hi @TahsinAyman, can you try with another browser? 
![CleanShot 2024-04-05 at 17 47 00](https://github.com/twentyhq/twenty/assets/19412894/6adf8acf-8f58-4113-8811-42d6e10c0f40)

Working well for me and the person next to me :)

**Comment by YubaNeupane** [comment]
Can i get this issue?

**Comment by Bonapara** [comment]
Sure @YubaNeupane, thanks for contributing!

**Comment by FelixMalfait** [comment]
Actually issue was completed by @karthikkashyap98 already :)
Other issues are still up for grab! Thanks
