### ISSUE TITLE
Hot Reload Not Working in WSL  (Ubuntu) VM

### ISSUE THREAD

**Issue by sibshahz** [twentyhq/twenty#4864]
## Bug Description

I have set this repo in WSL (Ubuntu) using this [guide](https://docs.twenty.com/start/local-setup/yarn-setup#step-6-running-the-project), when I tried to make some changes, they weren't applied and I had to manually restart vite using r+enter command.

## Expected behavior

It should reload on any css or component changes

## Some tips to resolve this issue will be appreciated

**Comment by FelixMalfait** [comment]
cc @thaisguigon any lead? thanks

**Comment by FelixMalfait** [comment]
Sorry I'm going to close as it's hard to resolve (we can't reproduce on our side). A fix is obviously welcome if you find out what's going on!
