### ISSUE TITLE
Missing docker postgres image for v0.4.0

### ISSUE THREAD

**Issue by darekdesu** [twentyhq/twenty#4867]
## Bug Description

Installation script `install.sh` (available with: `bash <(curl -sL https://git.new/20)`)  doesn't work with latest published version: `0.4.0` of `twenty-postgres`: https://hub.docker.com/layers/twentycrm/twenty-postgres/0.4.0/images/sha256-60c6d9de1299cd37a3c788050146c48fbab1b2ab2e8eee4ea56572c9c049d0a7?context=explore

**Example:** 
```
$ docker compose up -d
[+] Running 2/2
 ✘ server Error                                                                                                                                      1.5s
 ✘ db Error                                                                                                                                          1.5s
Error response from daemon: manifest for twentycrm/twenty-postgres:v0.4.0 not found: manifest unknown: manifest unknown
```

## Expected behavior

Instead of  `twenty-postgres:0.4.0` the `twenty-postgres:v0.4.0` is expected to exist in Docker Hub. Yep, the missing `v` suffix  in the version name:  `0.4.0 vs v0.4.0` needs to be published or installation script should be updated accordingly.

**Comment by ruban-s** [comment]
Hi,

this issue handled with #4868 pull request.

this can be fixed with docker-composer.yml 

```
db:
   +  image: twentycrm/twenty-postgres:lastest or
   +  image: twentycrm/twenty-postgres 
```

Thanks

**Comment by charlesBochet** [comment]
Sorry about that, I have published the missing image :)
