### ISSUE TITLE
Add Buttons Shortcuts Helpers to the Design System

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4871]
# Desired Behavior

We're planning to introduce an optional shortcut helper on buttons, with color variations (for text and vertical separator) based on different variants.

**The separator and shortcut helper colors are different.**

![CleanShot 2024-04-08 at 10 38 26](https://github.com/twentyhq/twenty/assets/19412894/6448d35c-7236-4820-9c18-6c4d250cf130)

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=27442-83448&mode=design&t=rBbwIqCdtFV9i9Jg-11

**Comment by DevStackArchitect** [comment]
@Bonapara I wanted to pick the issue but I am having issues setting it up on local.

`ry: SELECT * FROM current_schema()
Error during migration run:
Error: Cannot find module '../../user/user.entity'
Require stack:
- /Users/ashish/Documents/Workarea/twenty/packages/twenty-server/dist/src/engine/core-modules/auth/dto/verify.entity.js
- /Users/ashish/Documents/Workarea/twenty/node_modules/typeorm/util/ImportUtils.js
- /Users/ashish/Documents/Workarea/twenty/node_modules/typeorm/commands/CommandUtils.js
- /Users/ashish/Documents/Workarea/twenty/node_modules/typeorm/commands/SchemaSyncCommand.js
- /Users/ashish/Documents/Workarea/twenty/node_modules/typeorm/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/ashish/Documents/Workarea/twenty/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/Users/ashish/Documents/Workarea/twenty/packages/twenty-server/src/engine/core-modules/auth/dto/verify.entity.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .js] (/Users/ashish/Documents/Workarea/twenty/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ashish/Documents/Workarea/twenty/packages/twenty-server/dist/src/engine/core-modules/auth/dto/verify.entity.js',
    '/Users/ashish/Documents/Workarea/twenty/node_modules/typeorm/util/ImportUtils.js',
    '/Users/ashish/Documents/Workarea/twenty/node_modules/typeorm/commands/CommandUtils.js',
    '/Users/ashish/Documents/Workarea/twenty/node_modules/typeorm/commands/SchemaSyncCommand.js',
    '/Users/ashish/Documents/Workarea/twenty/node_modules/typeorm/cli.js'
  ]
}
Warning: command "ts-node ../../node_modules/typeorm/cli.js migration:run -d src/database/typeorm/core/core.datasource" exited with non-zero status code
——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target typeorm for project twenty-server (1s)

      With additional flags:
        migration:run
        --d=src/database/typeorm/core/core.datasource

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]

Warning: command "nx typeorm -- migration:run -d src/database/typeorm/core/core.datasource" exited with non-zero status code
`


`
> nx run twenty-ui:generateBarrels

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/ashish/Documents/Workarea/twenty/packages/twenty-ui/scripts/generateBarrels.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
    at defaultLoad (node:internal/modules/esm/load:143:22)
    at async nextLoad (node:internal/modules/esm/hooks:865:22)
    at async nextLoad (node:internal/modules/esm/hooks:865:22)
    at async Hooks.load (node:internal/modules/esm/hooks:448:20)
    at async MessagePort.handleMessage (node:internal/modules/esm/worker:196:18) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

`

**Comment by Bonapara** [comment]
@DevStackArchitect You can ask for help in Discord :)

**Comment by jss475** [comment]
Hey @Bonapara!

Mind if I work on this?

**Comment by Bonapara** [comment]
Sure @jss475, Thanks!

**Comment by Bonapara** [comment]
Hi @jss475, I'm unassigning you. Ping me if you still want it!

**Comment by ehconitin** [comment]
@Bonapara Couldnt find the the properties in figma.
Could you please reshare the figma designs.

**Comment by sarthak25sharma** [comment]
Hey @Bonapara!
If this is still open ,mind if I work on this?

**Comment by lucasbordeau** [comment]
@Mihan786Chistie You can work on this issue

**Comment by Mihan786Chistie** [comment]
Thanks @lucasbordeau, looking into it

**Comment by Mihan786Chistie** [comment]
@Bonapara can you give more details for the issue. I am still very confused about it. Also the Figma designs doesn't seem to be updated as the one provided for the issue

**Comment by Bonapara** [comment]
The shortcuts helper are there but hidden otherwise they would appear everywhere in the Figma 😄

Duplicated the file and displayed them here: https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=38933-151210&node-type=FRAME&t=1bOEBMGNbJiNYwdc-11

Thanks @Mihan786Chistie!

**Comment by Mihan786Chistie** [comment]
Thanks for the clarification! I checked out the Figma file, but I’m still a bit confused about how to implement the color variations for the shortcut helper and separator. Could you guide me on how these color changes should be applied?

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by unrenamed** [comment]
@Bonapara Is the goal to enhance the existing button component ([Button.tsx](https://github.com/twentyhq/twenty/blob/4156d7821c20685360ba55e8708398a733463db5/packages/twenty-front/src/modules/ui/input/button/components/Button.tsx#L8)) with a keyboard shortcut action based on the provided Figma design, or should a new button component be composed for this?

**Comment by Bonapara** [comment]
Hi @AdityaJadhav9423, I am unassigning you as it has been 1 week. Thanks for contributing!

**Comment by Bonapara** [comment]
Hi yes @emshyu, glad to be your first contribution to open-source!

**Comment by emshyu** [comment]
Thanks! Sorry for my groupmate's spam, in total we are looking for two issues.

**Comment by tinchil** [comment]
Hi @Bonapara, would you be able to clarify what do you mean by the "Design System". Is there a particular section/part of the website you would like to see the Filter Shortcut Added? Would it be something similar to the image below, or do u just want edits to the Button.tsx component to allow for different color choices.

![Image](https://github.com/user-attachments/assets/312ee182-2dd5-4602-9cb4-22474fd7bbf8)

**Comment by Bonapara** [comment]
Hi @tinchil! We would like to add a parameter to the `button.tsx` component indeed.

**Comment by muraliSingh7** [comment]
Hey @Bonapara ,

I think the filter, sort, and options are separate from the button itself, and they are actually customized button components. For instance, the filter is using a component called `MultipleFiltersButton.tsx`. I tried customizing MultipleFiltersButton, and it worked as expected. Here is the screenshot :
![Image](https://github.com/user-attachments/assets/c2eb8010-9930-4c21-b8e1-bd437ec2db54)


However, for all buttons, we’ll need to identify which ones need customization and which ones don’t. If you’d like the button to include the shortcut and left icon, those features already exist in the `Button.tsx` component; you just need to add the shortcuts and icons where necessary.

This is my understanding of the current issue. If anything is unclear or if I have misunderstood your expectations, please provide further clarification.

**Comment by Bonapara** [comment]
Hi @muraliSingh7 This design only regards the Button component, and not the light icon buttons. @lucasbordeau can you guide @muraliSingh7? I don't have a such  `MultipleFiltersButton.tsx` button in Figma.

**Comment by emshyu** [comment]
Hi @Bonapara, I agree with @muraliSingh7 and it seems that separators and shortcuts seem to already be included in Button.tsx. I am currently writing storybook tests, but I am having trouble with running the catalog tests for Button.stories.tsx. Is there a way for me to find them in the local storyboard UI?

**Comment by Bonapara** [comment]
I guess there @emshyu? https://storybook.twenty.com/

Thanks for your answer, will close this issue then
