### ISSUE TITLE
Fix explicit boolean predicates rule not working with boolean constants

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#4881]
# Context

Custom eslint rule : @nx/workspace-explicit-boolean-predicates-in-if

# Technical requirements 

The eslint rule does not work well with boolean constants : 

https://github.com/twentyhq/twenty/blob/42a878008d693a774c3f556fb2e5ccaa0455ba22/packages/twenty-front/src/modules/ui/utilities/hotkey/hooks/useSetHotkeyScope.ts#L81

**Comment by charlesBochet** [comment]
Related PR: https://github.com/twentyhq/twenty/pull/4879#pullrequestreview-1986736971
