### ISSUE TITLE
Introduce isAuditLogged column on ObjectMetadata

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4890]
We currently use a variable `isSystem` to determine whether we should log events on an object or not (currently in EntityEventsToDbListener).

We should instead introduce a more granular control by creating a new column `isAuditLogged` on ObjectMetadata

**Comment by AjaySDwivedi1** [comment]
Is the issues just changing isSystem to isAduitLogged? If so, I can work on this issue.
