### ISSUE TITLE
Cannot create related company/person/opportunity in place

### ISSUE THREAD

**Issue by pombredanne** [twentyhq/twenty#4901]
## Scope & Context

Create new person, company or opportunity in the UI.

## Current behavior

When I create a new opportunity for a person in a company, I need to jump through hoops in this sequence:
- first I need to create the company because opportunity needs it
- then the person because I cannot relate a new person to a non existing company
- and then the opportunity because it needs a company first

Same when I am in a company card: I cannot create an opportunity or person directly from there, breaking again the flow.

Same when I am in a person card: I cannot create an opportunity or company directly from there, breaking again the flow.

This is a poor, non intuitive workflow to me; this is a productivity drag and I feel I am fighting against the app each time I create new entities.

The current approach forces me in a basic, crude CRUD  https://en.wikipedia.org/wiki/Create%2C_read%2C_update_and_delete way to deal with records based on the app data model in the backing postgres tables and not based on how I work. 

## Expected behavior

When I create a new person, company or opportunity, I want to create related company/person/opportunity in-place in the card or list.

- For instance when I create a person in the list view, I should be able to create the company right away.
- From a person card, I would like to add a new opportunity from there.
- From a opportunity, I would like to add a new company and person from there.

**Comment by FelixMalfait** [comment]
I agree this is painful when using the app
