### ISSUE TITLE
Cache metadata for each workspace and replace get request

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#4903]
## Scope & Context

Metadata querying on front.

## Current behavior

Each time we reload the page, a request is sent to the DB.

## Expected behavior

We have a cache service on the backend, and since the metadata collection is unique for each workspace, it could be generated only once in the cache and then queried in the cache directly.

We could create a new service that relies on the cache and if not present for a workspace, make a call in the DB.

See also if we could initialize it from WorkspaceSchemaStorageService, or completely rely on this service.

@magrinj What are your thoughts ?

**Comment by FelixMalfait** [comment]
I think this has been solved @lucasbordeau no? If not please re-open
