### ISSUE TITLE
Fix View switcher Left Padding Misalignment

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4906]
# Current Behavior

The left padding is not functioning as expected, causing misalignment.

![Current Behavior Image](https://github.com/twentyhq/twenty/assets/19412894/f490e536-e82d-4813-aa61-1dfd566a847f)

I think this was caused by #4852

# Desired Behavior

Correct the padding issue to ensure alignment with the Select dropdown. Make sure it's still working on Kanban views as is it today

![image](https://github.com/twentyhq/twenty/assets/19412894/9dbec843-490f-4004-95d2-4a788ef55c98)

**Comment by Jeetch8** [comment]
Can i please resolve this issue ?

**Comment by Bonapara** [comment]
Sure @Jeetch8, thanks for contributing!
