### ISSUE TITLE
On RecordShow Page > Notes, if I click on the Target of an existing Note, it logs an error in the console

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#4917]
## Bug Description

Go to a record (example a Company record), go to Notes tab and create a note. Then click on the Note record target within the Notes tab:
<img width="1279" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/8044b76f-aee7-40e6-bda9-b765fbf2d933">

## Expected behavior

No error in the console

## Technical inputs

Not sure about this one, I suspect that the FieldContext is not properly initizalied in this case

**Comment by MRLab12** [comment]
Hey! I'm working on this, will get a PR up. Can it be assigned to me?

**Comment by MRLab12** [comment]
If someone has more context, would this be the same issue that I'm getting locally? Not sure if it's an issue with my local DB setup missing data.

<img width="1788" alt="Screenshot 2024-04-12 at 9 33 28 PM" src="https://github.com/twentyhq/twenty/assets/150161290/6175aec4-0c56-4300-aec4-40bc40cd67ab">

**Comment by charlesBochet** [comment]
I don't think so, is your server up? What do you have in your network tab? CORS issue usually means your server is badly configured but in localhost, it's unlikely to be so I suspect your server was not up when these messages got printed in your console

**Comment by MRLab12** [comment]
Yes it is, sorry should had mentioned in my comment that I'm getting `Error: Error executing raw query for workspace 20202020-1c25-4d02-bf25-6aeccf7ea419: column "activityId" of relation "event" does not exist` in the server. I'll look into it more later today.

**Comment by charlesBochet** [comment]
@FelixMalfait do we create events for activities?

**Comment by FelixMalfait** [comment]
@charlesBochet yes we do, since a recent change end of last week we log events on pretty much everything except on workspaceMember and Events.
I think you just need to run `nx yarn database:reset twenty-server` @MRLab12

**Comment by MRLab12** [comment]
@charlesBochet I'm trying to replicate these errors. What I tried:

- Created a test note in a company.

- Clicked on the edit button next to the target company within the Notes tab.


<img width="1785" alt="Screenshot 2024-05-02 at 10 37 29 AM" src="https://github.com/twentyhq/twenty/assets/150161290/15554711-21ce-4039-a7c6-d5efc1ae538b">


Is there something else I need to do to trigger the errors you got?

**Comment by charlesBochet** [comment]
@MRLab12 I actually think this has been solved by recent changes on the Tasks page, closing this issue, thanks for taking a look :)
