### ISSUE TITLE
Auto-Reset for Opportunity Creation Search Field

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4923]
# Current Behavior

The search field retains the previous company name when creating a new opportunity.

https://github.com/twentyhq/twenty/assets/19412894/d9b7fb77-fca4-47ce-b96e-c2448c426768

# Desired Behavior

The search field should reset to blank each time the opportunity creation picker is opened.

**Comment by agupta0001** [comment]
Can I work on this?

**Comment by Bonapara** [comment]
Sure @agupta0001, thanks for contributing!
