### ISSUE TITLE
Enable Full Name Search in Contact Association

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4926]
# Current Behavior

When associating a contact with a relation (like a company or opportunity), the system doesn't permit full-name search. This necessitates either the first or last name being deleted for search.

https://github.com/twentyhq/twenty/assets/19412894/131c2078-7efc-4520-916c-6420a0af90aa

# Desired Behavior

Enable full name search functionality when adding a contact to a relation.

**Comment by Bonapara** [comment]
Related to https://github.com/twentyhq/twenty/issues/3386

**Comment by FelixMalfait** [comment]
Closing to cleanup as this is related to the other issue (I copied your message/video!), would be great if we manage to prioritize it next sprint!
