### ISSUE TITLE
Default country for phone numbers should be defined at the field level

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4952]
Just noticed we assumed by default the country is FR which is wrong. We should be be able to set the default country at the field level and/or at the address level. Same for the address field - we should introduce a country dropdown with a similar default value. 

https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/ui/field/display/components/PhoneDisplay.tsx

Also the default country should be the US not FR.

**Comment by FelixMalfait** [comment]
Copy design and implementation from currency.
It should be very similar approach, except the list is a list of countries and not a list of currencies.

<img width="560" alt="Screenshot 2024-04-16 at 11 56 48" src="https://github.com/twentyhq/twenty/assets/6399865/af9cd19b-7137-4cc8-9f30-176145955f21">

**Comment by gitstart-twenty** [comment]
Hey @FelixMalfait,

Just to confirm, we're converting the phone field from a string to a composite that will also include the `countryCode`.

The address is already a composite that includes the countryCode, we just need to add the country picker for it.

If yes, are we also handling migrating the current phoneNumbers to this new type?

Cheers!

**Comment by FelixMalfait** [comment]
Answered on Discord

> 
> Hey @Mayanja - I didn't think we'd need to create the  column to set a default value but it would make sense to create it.
> 
> The thing is we already had plans to create a new field type for phone numbers, see issue #4985
> 
> I'd split that in multiple steps/tickets:
> - create a new field type with 3 columns: phone, country, additionalPhones ; focus on the above ticket only (additional default country) and let aside additionalPhones for now (as long as it doesn't break anything)
> - work on v2 of that new field type, mostly frontend work to enabled additionalPhones based on the designs in #4985
> - add a new fields phoneS as on people standard object, prepare a migration script from phone to phoneS
> - deprecate phone
> 
> But I do realize that this might not be the best thing to work on now given the other field types ongoing. Would you mind waiting ~ a week?
>

**Comment by FelixMalfait** [comment]
@gitstart-twenty since you have tackled https://github.com/twentyhq/twenty/pull/6882 you should be able to pickup this one now

**Comment by FelixMalfait** [comment]
Closing this as it's not that relevant. It seems the default country isn't France anymore but has been left as blank which is fine!
