### ISSUE TITLE
Claude / LLM integration?

### ISSUE THREAD

**Issue by jaanli** [twentyhq/twenty#4957]
## Scope & Context
```
I am spending too much time writing emails.
One-click email drafts given the same prompt would help automate organizing social events and sharing information.
```

## Current behavior

A clear and concise description of what the current behavior is.
```
I cannot click a button and have an open source local large language model (e.g. using llamafile) draft an email or SMS to folks in my Twenty instance.
```

## Expected behavior

```
I am able to click a button and have a local large language model draft SMS/emails, or do so on a schedule/cron job.
```

## Technical inputs

```
- Opera supports this: https://press.opera.com/2024/04/03/ai-feature-drops-local-llms/
- Mozilla's Llamafile is good too: https://github.com/Mozilla-Ocho/llamafile
- User should have control over their prompt library
```

Please let me know if tips on integration would help, I've built this kinda stuff a bunch!

**Comment by jaanli** [comment]
Jan is an example local app: https://jan.ai/

**Comment by FelixMalfait** [comment]
Hey @jaanli thanks for the suggestion.
This is definitely on the roadmap for this year but more towards the second half. We're still working on finishing the foundations for the next few months.
I'll close the issue since it's not a short-term fix, but thanks for taking the time to write this - feedback helps us!

**Comment by jaanli** [comment]
So exciting, thank you!! That will be a massive differentiator and unlock really cool use cases :)
