### ISSUE TITLE
Multiple phone numbers, links, and emails

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4985]
### Previous data structure
```
{
   email 
   phone 
   link {
      label
      url
   } 
}
```

### Future data structure

```
{
   emails {
     primaryEmail 
     additionalEmails (array)
   } 
   phones {
     primaryPhone {
        number
        country
    }
    additionalPhones (json)
   }
   links {
      primaryLink {
      label
      url
      }
     additionalLinks (json) 
   } 
}
```

I.e. we create composite field including the current structure + an additional optional additonal array column.

In the field settings we should have an option to enable/disable multi-input

**Comment by Bonapara** [comment]
![CleanShot 2024-04-22 at 16 21 36](https://github.com/twentyhq/twenty/assets/19412894/0f8603d9-dfb8-4de8-a483-f0f55dcf977e)

**Comment by r0bbie** [comment]
Was looking to request this, so very happy to see you guys are working on it :) 

It's definitely an issue right now that we have duplicate entries for a lot of people if they have more than one email (like a work and personal one for example), and would be great to get these merged!

**Comment by FelixMalfait** [comment]
@r0bbie we've shipped the "multi-links" field so the hardest part is done because multi-phone number and multi-emails should be pretty similar. But unfortunately we don't have multi-emails / phone planned yet.

@Bonapara would you mind eventually closing this issue and creating 2 new issues with links to your clean Figma design for the emails + phone number? Email is probably easier than phone number (because of the composite nature, there might be an additional complexity), pointing to LINKS as a reference implementation.

**Comment by Bonapara** [comment]
Closing this issue and replacing it with two dedicated issues:

**Emails**
https://github.com/twentyhq/twenty/issues/6261

**Phones**
https://github.com/twentyhq/twenty/issues/6260
