### ISSUE TITLE
In the demo datamodel's view, entering singlular and plurar values like 3vent, 3vents crashed the demo

### ISSUE THREAD

**Issue by janipaijanen** [twentyhq/twenty#5001]
## Bug Description

Using the demo at https://demo.twenty.com/. After poking a round found the setting. Tried adding an object 'Event', 'Events' in plural form. The UI responded that it can not be added. 

Thought that 'Event' could be a reserved word, so tried entering an object with '3vent' and '3events' in singlar and plural forms. 
There was an error message saying something like 'expected numbers but failed'.  Since then the demo has been unaccessible. Maybe this is a timing issue, and the apparently incorrect user input did crash the demo... Might worth checking and validing user input..

## Expected behavior

System either accepts the entered values or rejects them gracefully with an error message, but does not crash. 

## Technical inputs

Enter '3vent' and '3events' in add new object view.

**Comment by FelixMalfait** [comment]
Thanks for the report! I think this was fixed now. 
@ijreilly if not please re-open the issue!
