### ISSUE TITLE
Migrate passwordResetToken and passwordResetTokenExpiresAt to AppTokens table

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5021]
We have two columns `passwordResetToken` and `passwordResetTokenExpiresAt` on the users table.
We should delete them and use a new dedicated type in the `AppTokens` table instead.

Marking as "good first issue" but backend issues are usually harder than frontend good first issues.

**Comment by pacyL2K19** [comment]
@FelixMalfait I can work on this

**Comment by FelixMalfait** [comment]
@pacyL2K19 Thanks!!!
