### ISSUE TITLE
Optimistic rendering issue when changing the workspace name

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5024]
If you change the workspace name in settings > general, then come back to the app, it remains the same workspace name on top-left menu. You have to refresh the page entirely for changes to be taken into account.

Probably a simple optimistic rendering issue.

**Comment by palerdot** [comment]
Root cause of this issue is local recoil state was not updated when workspace name is changed. I have a PR that addresses this issue - https://github.com/twentyhq/twenty/pull/5033/files
