### ISSUE TITLE
Reload button on JS error does not do anything

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5027]
<img width="720" alt="Screenshot 2024-04-18 at 10 15 02" src="https://github.com/twentyhq/twenty/assets/6399865/449b760a-d64f-4ec7-b897-7bc0ce00cf4a">

Once it's that state it's very annoying because it's impossible to access any page (reload button doesn't solve anything).
We should either trigger a full reload or find a way to let the user go back to the previous page / click on menu, etc.

**Comment by yurimutti** [comment]
Hi, can you assign to me please ?

**Comment by FelixMalfait** [comment]
@yurimutti sure thanks! To get into that state you'll need to create a fake frontend error

**Comment by FelixMalfait** [comment]
Let's change this button behavior to entirely reload the page (browser level), this will be more efficient.  Right now I think we're attempting something else which is more local but then in many case it doesn't work.

Also the title "Server's on a coffee break is misleading" since this is actually for frontend error. Let's change it to "Sorry, something went wrong."

@ehconitin

**Comment by khuddite** [comment]
Oh ignore my comment, it seems I didn't fully understand how `ErrorBoundary` component works

**Comment by khuddite** [comment]
@ehconitin Don't worry about this, I am addressing this in #8588

**Comment by ehconitin** [comment]
Thanks @khuddite 
@FelixMalfait the PR seems to be merged, was this issue fixed? Could we close this issue?

**Comment by khuddite** [comment]
I believe so, we can close out this issue.

**Comment by FelixMalfait** [comment]
Thanks!
