### ISSUE TITLE
Why did you move off of Hasura?

### ISSUE THREAD

**Issue by brentshulman-silkline** [twentyhq/twenty#5050]
Genuine question about the technical decision to do so

**Comment by FelixMalfait** [comment]
Hey Brent, Hasura is a great product but it wasn't flexible enough for our use-case.
Our goal was to build a multi-tenant cloud with unlimited schema flexibility for each workspace.
We have:
- a code layer where we define standard objects with our own definitions/field types (e.g. full name, email)
- metadata tables that define the metadata schema for each workspace (this metadata is a mixed of standard objects that are synced from code, and custom objects created from the UI)
- a dedicated schema in Postgres for each tenant
We wrote custom code for everything, to sync the code layer to the metadata layer, to keep the metadata layer in sync with each schema by computing and generating each sql migration, a layer to generate dynamically the graphql api for each workspace based on the data schema, etc.
So much of our engine is actually similar to Hasura's engine. We have a different business purpose than Hasura, but in some ways we have similar technical foundations - building on top of it didn't given us the right level of control.

**Comment by FelixMalfait** [comment]
Closing to keep the repo clean but you can still answer!
