### ISSUE TITLE
Ellipsis doesn't take into account clickable fields

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5064]
We have an issue with long texts:
<img width="379" alt="Screenshot 2024-04-19 at 16 23 38" src="https://github.com/twentyhq/twenty/assets/6399865/744ead86-8d18-445d-81ca-4a6d69107d06">
<img width="535" alt="Screenshot 2024-04-19 at 16 25 22" src="https://github.com/twentyhq/twenty/assets/6399865/63ecd5f5-c9a3-4828-b827-af1107834800">

As you can see, for the address or input fields that are not clickable it works well.
But for input fields that have a pen icon (e.g. link, email...) then it becomes impossible to modify the input if you input something too long.
Instead, the ellipsis should come earlier and we should see the pen icon

Marking this as good first issue but it might not be that easy - tbc!

**Comment by DevanandGowda** [comment]
@FelixMalfait could you please assign me this issue? I have started working on it. Thanks!
