### ISSUE TITLE
Doc nitpick

### ISSUE THREAD

**Issue by emehrkay** [twentyhq/twenty#5076]
## Bug Description

https://docs.twenty.com/start/self-hosting/docker-compose#manual-installation

Step 2 says `Run the command openssl rand -base64 32 three times, make note of the string for each` and in the example there are four places that need to be replaced

## Expected behavior

Change `three times` to `four times`

**Comment by FelixMalfait** [comment]
Haha good catch! Although I think it should shortly become "one time" when we solve this: https://github.com/twentyhq/twenty/issues/4587
