### ISSUE TITLE
Setup Sentry for cron monitoring

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5079]
We have cron jobs to import email, we should setup Sentry monitoring for those.

https://docs.sentry.io/product/crons/

**Comment by Freebios** [comment]
After a quick search in the doc, this is probably something to implement as code, there are automated registration helpers https://docs.sentry.io/platforms/javascript/guides/node/crons/ , but you can also manually notify Sentry of a job start, finish and error https://docs.sentry.io/platforms/javascript/guides/node/crons/#check-ins
