### ISSUE TITLE
Email contact autocreation settings V2

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#5090]
<img width="749" alt="Capture d’écran 2024-04-22 à 15 13 52" src="https://github.com/twentyhq/twenty/assets/71827178/4b073617-0097-4d8a-ac73-832a0522182f">

- Create `contactAutoCreationFor` of type `FieldMetadataType.Select` with 3 options: SENT_AND_RECEIVED, SENT, NONE
- Create `MessagingSettingsContactAutoCreationV2ModelEnabled` feature flag
- Create `MessagingSettingsContactAutoCreationV2Enabled` feature flag
- Create frontend component and connect it to the backend: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=28538-71635&mode=dev
- Update contact auto creation logic to make V1 and V2 work concurrently

**Comment by FelixMalfait** [comment]
I think this has been done! @bosiraphael please re-open if not
