### ISSUE TITLE
Fix mixed uncontrolled / controlled form input

### ISSUE THREAD

**Issue by ijreilly** [twentyhq/twenty#5118]
## Scope & Context
In SettingsDataModelObjectAboutForm, we are performing what aims to be a before-hand input validation in the onChange.
While this callback is executed upon input change, it is not responsible for updating the input value (because it is not a controlled component). 
That behaviour works in SettingsObjectFieldEdit but only thanks to re-renders. 

We should try to fix that, controlling how inputs are updated.

**Comment by FelixMalfait** [comment]
@ijreilly closing as this issue seems old but please re-open if this is still relevant!
