### ISSUE TITLE
npx nx start does not exit gracefully

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#5125]
## Bug Description

Running: npx nx start from twenty root works but does not exit gracefully (hitting Ctrl+C)

<img width="842" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/cb39f95a-cf56-4df8-9d2c-e5f74b5b3c75">

It would be great to make it stop gracefully

**Comment by charlesBochet** [comment]
Input: 
- I think it comes from server start sub command: npx nx start twenty-server

**Comment by flatypus** [comment]
> @charlesBochet can you assign to me, i will look into it.

My PR should resolve the issue, it's to do with the version of nx

**Comment by charlesBochet** [comment]
Thank you both!
