### ISSUE TITLE
Add names to Demo Opportunities

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5129]
# Current behavior

On demo.twenty.com, connected as `noah@demo.dev`, Opportunities have no names

![CleanShot 2024-04-23 at 17 25 30](https://github.com/twentyhq/twenty/assets/19412894/40d7d1f6-b3da-4fe4-a0f7-0121d984c35d)

![CleanShot 2024-04-23 at 17 26 25](https://github.com/twentyhq/twenty/assets/19412894/267158c0-4c76-40a0-86be-350a0f470d96)

# Desired Behavior

Add the company name they are related to as Record Name

**Comment by saram-aman** [comment]
@Bonapara can I work on the issue? if so then please assign!

**Comment by Bonapara** [comment]
Sure @saram-aman, thanks for contributing!

**Comment by Bonapara** [comment]
Hi @saram-aman, are you still on it? Thanks!

**Comment by Bonapara** [comment]
Hi @saram-aman, I'm unassigning you. Ping me if you still want it!
