### ISSUE TITLE
Calendar events I participated in should be displayed in red

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5131]
### Current behavior

![image](https://github.com/twentyhq/twenty/assets/6399865/b64e7c82-7343-4e88-ab8d-1e09c4e57af7)

### Desired behavior

It should be displayed in red (not only in setting, but also check that the behavior is implemented in the app)

<img width="356" alt="Screenshot 2024-04-23 at 17 36 47" src="https://github.com/twentyhq/twenty/assets/6399865/2599cba4-1740-49be-83f5-0482d10f8386">

**Comment by orinamio** [comment]
@FelixMalfait I'll take this issue. Can you assign me to it?
