### ISSUE TITLE
Display "Syncing" in Emails Settings as import is in progress

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5134]
# Current Behavior

There is no indicator to show that an email import is in progress.

# Desired Behavior

Introduce an indicator featuring our loader inside a tag. Ensure equal margins on the left, top, and bottom surrounding the loader for consistent spacing.

https://github.com/twentyhq/twenty/assets/19412894/15232c5e-4b21-460e-87fa-f283727fee22

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=23338-13746&mode=design&t=QBOPZS1EGbvwxH7Y-11

**Comment by orinamio** [comment]
@Bonapara I'll take this issue. Can you add me to it?

**Comment by Bonapara** [comment]
Sure @orinamio, thanks for contributing!

**Comment by orinamio** [comment]
@Bonapara which `syncStatus` is appropriate for the loader? `PENDING` or `ONGOING`?

I currently have it set to `ONGOING`. Awaiting your confirmation.

**Comment by Bonapara** [comment]
@bosiraphael should be able to help you!

**Comment by bosiraphael** [comment]
I think this is for the ONGOING state indeed. Maybe we should display something like "Awaiting import" for the PENDING state, what do you think @Bonapara @Weiko ?

**Comment by Bonapara** [comment]
> I think this is for the ONGOING state indeed. Maybe we should display something like "Awaiting import" for the PENDING state, what do you think @Bonapara @Weiko ?

How about using 'Preparing' or 'Awaiting'? (The shorter the better)
