### ISSUE TITLE
Calendar is displaying "Not synced" right after connecting emails

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5150]
<img width="1048" alt="Screenshot 2024-04-24 at 16 23 23" src="https://github.com/twentyhq/twenty/assets/6399865/e46aec89-56a6-41cb-910c-2a09a1c0bf36">

Workspace id: 74345ac3-b4cb-40bc-85a0-aed6aedd0fc8

We should have an intermediate state as we do in emails?

**Comment by FelixMalfait** [comment]
<img width="537" alt="Screenshot 2024-05-03 at 13 31 56" src="https://github.com/twentyhq/twenty/assets/6399865/05268bbd-97b2-433a-96a3-991aa8e1622d">

It's bothering because it's not consistent with emails, so it really makes it look like something isn't working

**Comment by FelixMalfait** [comment]
I think @Weiko partially fixed this, but did not introduce "Pending"? Should we close it @Weiko? Or should it be improved?

**Comment by Weiko** [comment]
@FelixMalfait yes this was partially fixed. We don't have a syncStatus column in the calendar table (yet?) so we had to mimic that using other info. cc @charlesBochet

**Comment by FelixMalfait** [comment]
Ok so let's keep it to do it cleanly!
