### ISSUE TITLE
On GraphQL/REST API docs, introduce a dropdown to pick known servers

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#5156]
## Scope & Context

Improve the UX of GraphQL and REST APIs documentation.

## Current behavior

Right now if you browse: https://docs.twenty.com/rest-api/core#/ or https://docs.twenty.com/graphql/core, you have the option to set your server URL.
The server URL is prefilled with the api.twenty.com production URL.

<img width="1503" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/e00848bb-e48e-4cce-b038-856219500cd2">

## Expected behavior

We would like to have:
- a dropdown with "Production API" / "Demo API" / "Localhost" / "Other". (default Production API)
- a text input: filled with 'api.twenty.com' / 'api-demo.twenty.com' / 'localhost:3000' / ''. The text input should be disabled if something else than Other is selected in the dropdown.

**Comment by charlesBochet** [comment]
@Bonapara FYI, if you want to have a different approach

**Comment by Bonapara** [comment]
LGTM!
