### ISSUE TITLE
Workspace Icon is broken within the workspace picker

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#5157]
## Bug Description

In case a user is part of two different workspaces, we display a workspace picker in the navigation bar. The workspace icon are not shown at all

<img width="228" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/5aad4256-516d-4933-a606-72e3594ec69b">

## Expected behavior

Workspace icons should be present

**Comment by flatypus** [comment]
> Has this issue been resolved? First-timer here and when I'm running this locally, I see an icon next to each workspace. Can you share how this bug can be duplicated?
> 
> <img alt="Screenshot 2024-04-24 at 16 03 03" width="235" src="https://private-user-images.githubusercontent.com/122317795/325365388-c662265c-c52a-4c81-96cc-dcb15d39ff86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzM4MjcsIm5iZiI6MTcxNDAzMzUyNywicGF0aCI6Ii8xMjIzMTc3OTUvMzI1MzY1Mzg4LWM2NjIyNjVjLWM1MmEtNGM4MS05NmNjLWRjYjE1ZDM5ZmY4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwODI1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGQyMGFhOTUxMTVlNzBiYmQ2ODBhNGJkZDVhZDVmNmU1ZWM2NDYxNmEzOTAzOGJhMDQwN2E2YTE4Nzk3ZGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zi_Z5vHmzj4vGHt18o6qw17ECE60tN45v6xZP2RY5tg">

This issue has now been resolved. The reason why the icon is fine for you is both icons there are saved as data:image... icons, but uploaded icons are saved relative to {host}/files{path}. I've fixed this issue in #5161.

**Comment by charlesBochet** [comment]
Thank you!
