### ISSUE TITLE
Duplicated calendar events

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5159]
# Current behavior

It appears that some events are getting duplicated when they're in different team members' calendars.

![CleanShot 2024-04-24 at 22 19 42](https://github.com/twentyhq/twenty/assets/19412894/d7d471d2-5963-4ec1-ad21-9eae2343b639)

The second event side panel is empty:

![CleanShot 2024-04-24 at 22 19 13](https://github.com/twentyhq/twenty/assets/19412894/ba156b9e-bc39-42d4-8ef2-5e3fac96e0de)

# Desired Behavior

Have one event only! 

@Weiko any idea? Great for Experienced contributors?

**Comment by Weiko** [comment]
@Bonapara @bosiraphael is on it! Thanks 👍
