### ISSUE TITLE
Workspace icon is missing on multi-workspace switcher

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5161]
![CleanShot 2024-04-24 at 22 28 14](https://github.com/twentyhq/twenty/assets/19412894/59c7335c-fb1c-4258-a96a-f5c32a38cce4)

@martmull any idea?

**Comment by flatypus** [comment]
I think I've identified the problem for it, I've fixed it for the icon, now just need to fix the dropdown as well.

<img width="179" alt="image" src="https://github.com/twentyhq/twenty/assets/68029599/36c11b72-22e2-4399-919f-b6255b42c757">

**Comment by Bonapara** [comment]
Great, thanks @flatypus! Would you like to be assigned to the issue?

**Comment by flatypus** [comment]
> Great, thanks @flatypus! Would you like to be assigned to the issue?

Sure! Just made the PR :)
