### ISSUE TITLE
Cannot access calendar Settings

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5162]
While my Google account is connected, I can access Email Settings, but cannot open Calendar Settings

https://github.com/twentyhq/twenty/assets/19412894/cc111b57-856d-42a7-9c10-2c097adf9c51

**Comment by flatypus** [comment]
It says calendar (soon) for me?
<img width="230" alt="image" src="https://github.com/twentyhq/twenty/assets/68029599/ff058fcf-3918-4631-be50-ce4085e525d6">

**Comment by Bonapara** [comment]
Hi @flatypus, the calendar is still behind a feature flag!

**Comment by flatypus** [comment]
ohh of course, i just found the feature flag.mdx doc, thanks!

**Comment by FelixMalfait** [comment]
I'm going to close this because I'm guessing this is linked to a rollout issue (account connected before we rolled out Calendar). If you see it happening on a new account please re-open!
