### ISSUE TITLE
Change Past Events Font-Color to Secondary for Visibility

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5164]
# Current behavior

The past events font-color is "Tertiary"

![CleanShot 2024-04-25 at 09 24 54](https://github.com/twentyhq/twenty/assets/19412894/93c8359a-fdcb-4b72-9c49-408a267c2387)

# Desired Behavior

Let's change it to "Secondary" to improve visibility

![CleanShot 2024-04-25 at 09 25 59](https://github.com/twentyhq/twenty/assets/19412894/c35fa890-3523-46ff-a235-83b4fb7febe6)

**Comment by pilladipesh33** [comment]
Is this issue assigned to anyone if not can you assigned me

**Comment by Bonapara** [comment]
Sure @pilladipesh33, thanks for contributing!

**Comment by FelixMalfait** [comment]
@pilladipesh33 assigning you since no PR was raised. Thanks for trying :)

**Comment by Shyesta** [comment]
Hi @Bonapara, is this issue still available? If so, can you assign me to it?

**Comment by FelixMalfait** [comment]
@Shyesta it is, thanks!

**Comment by Bonapara** [comment]
Hi @Shyesta thanks for your message! No the time can stay in tertiary. But you're right, we can put the event title in primary!

**Comment by Shyesta** [comment]
Sounds good, I will update that. Thanks @Bonapara!
