### ISSUE TITLE
Send global errors to Sentry

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5191]
We need to fix this asap:
https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/error-handler/components/AppErrorBoundary.tsx#L8C18-L8C23

I saw a major error that wasn't catched. In that case it was linked to a one-off data sync issue but we could be missing more important errors.

**Comment by shubham-kumar10** [comment]
@FelixMalfait 
Have added a fix here: [https://github.com/twentyhq/twenty/pull/5198](url)
I hope this should do it
