### ISSUE TITLE
Filter is null / is not null

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5216]
Current filters for TEXTS for example:

<img width="257" alt="Screenshot 2024-04-29 at 23 48 26" src="https://github.com/twentyhq/twenty/assets/6399865/84342dd8-464c-4268-837e-113242af0568">

It would be useful to have is null / is not null (probably for the majority of filter types)

**Comment by Bonapara** [comment]
Maybe "Is empty" for the wording?

**Comment by FelixMalfait** [comment]
@Bonapara agreed!

**Comment by FelixMalfait** [comment]
Marking as "good first issue" but even though the change is small, it requires going into our backend which is fairly complex to understand!

**Comment by pacyL2K19** [comment]
Can you assign this to me @FelixMalfait ?
Thanks

**Comment by FelixMalfait** [comment]
Thanks @pacyL2K19!
