### ISSUE TITLE
Favorite Lists

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5220]
### Backend

We need to create a new object `FavoriteList`
- id, createdAt, updatedAt
- name
- icon

And add a new nullable column `favoriteListId` on  `favorite` table.

### Frontend

TBC with Thomas, but it could be something like this:

<img width="207" alt="Screenshot 2024-04-30 at 13 36 39" src="https://github.com/twentyhq/twenty/assets/6399865/f4d51f9b-a679-4a89-98e7-b690db91d788">

That would open a filtered list view.

And the existing favorite button would morph into something like this

<img width="251" alt="Screenshot 2024-04-30 at 13 37 14" src="https://github.com/twentyhq/twenty/assets/6399865/27ed5270-3721-43e3-857a-587d93d97154">

We also need to think of a UI to name the list. 
The list selection/edition/creation could be inspired/reuse most of the view switcher?

**Comment by kiridarivaki** [comment]
Hi! I would like to work on this. I haven't yet worked on a back-end issue, do you think I could be of help? If not, could you recommend another issue?

**Comment by FelixMalfait** [comment]
Closing in favor of #5755
