### ISSUE TITLE
Check order of tasks on task page

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5222]
It seems that the order is not the most efficient one (feedback received during a call)

We should hide overdue tasks / have several sections?

Also think about pagination, how does this work? we should probably leverage standard list views

**Comment by JarWarren** [comment]
I love this idea. I had suggested sorting by due "day" if that's still an option https://github.com/twentyhq/twenty/discussions/6006.

FWIW, I think hiding overdue tasks is a recipe for forgetting them. Current behavior of highlighting overdue in red is probably a good thing.

**Comment by Bonapara** [comment]
This also raises the question of standard views versus custom views. We might want several views to be default, such as "My tasks" and "Done tasks."
