### ISSUE TITLE
Ability to "lock" fields within the UI to prevent accidental updates

### ISSUE THREAD

**Issue by skyfox675** [twentyhq/twenty#5240]
## Scope & Context

In the UI, for fields that may never see updates such as "customer anniversary date" where once it is set, it remains that value. Prompt me to confirm or "unlock" the field prior to giving me the option to alter it's value.

Possibly making the value slightly grey'ed-out as weill to indicate that it is a more restrictive value might be helpful as well.

**Comment by FelixMalfait** [comment]
Thanks for the suggestion! cc @Bonapara who leads product/decide to decide any followup

**Comment by Bonapara** [comment]
I think we should wait to have a better vision of permissions and read-only to handle this one
