### ISSUE TITLE
feat: use duplicateCompanies when saving a company entity

### ISSUE THREAD

**Issue by AdityaPimpalkar** [twentyhq/twenty#5259]
When saving a company we need to check if we already have a company entry with a same name.

If `duplicateCompanies` returns more than one entry, we can give the choice to user to select the corresponding company or create new entry. If it returns a single entry, we automatically map it without giving user the choice to select

(UI/UIX on this to be decided yet - @Bonapara could you help with this? Thanks!)

**Comment by FelixMalfait** [comment]
I think for v1 we don't want to provide a select, let's just take first match if there are several matches
