### ISSUE TITLE
Fix scroll right on mobile

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5275]
2 issues I've noticed on mobile.

On List view, I can scroll too far to the right
<img width="328" alt="Screenshot 2024-05-03 at 15 23 59" src="https://github.com/twentyhq/twenty/assets/6399865/3f51dd89-7200-4f1a-8a03-7c43040921e3">

On Kanban view there the border to separate the two sections suddenly stops:
<img width="328" alt="Screenshot 2024-05-03 at 15 24 19" src="https://github.com/twentyhq/twenty/assets/6399865/14b60d12-622f-4e2b-8d59-35fa53840873">

**Comment by orinamio** [comment]
I'll look into this issue. Can you assign me to it?

**Comment by FelixMalfait** [comment]
On fire @orinamio 😅 - don't pay too much attention to Greptile's comment, it's nice to give ideas but I think most of the time it's not correct. Just assigned you
