### ISSUE TITLE
Can't deactivate custom object

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5276]
# Description

On some workspaces (demo) I cannot deactivate a custom object I created:

https://github.com/twentyhq/twenty/assets/19412894/c852c2cb-2869-4fe8-9bfd-ed7e71fd84db

Even after refresh. Also occurres on Twenty (demo) workspace

**Comment by eberkund** [comment]
I am experiencing this too, it wasn't a problem with 0.4.0 if that helps.
