### ISSUE TITLE
Fix spacing on mobile for show page 

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5277]
cc @Bonapara 

We should add space before the image and after the button group 
<img width="322" alt="Screenshot 2024-05-03 at 15 32 11" src="https://github.com/twentyhq/twenty/assets/6399865/07ad6dcd-9b1c-4c0a-b793-505528cfd6a4">

I think we should also add a border-bottom to the last element - here "Projects" (same at the border-top), as it makes it seem Timeline/Tasks/etc are part of project

**Comment by hnrykm** [comment]
@FelixMalfait Can I pick this up?

**Comment by FelixMalfait** [comment]
Sure @hnrykm thanks!

cc @Bonapara for more clear directions

**Comment by Bonapara** [comment]
![CleanShot 2024-05-06 at 12 13 12](https://github.com/twentyhq/twenty/assets/19412894/721efd0b-6f59-49e9-b878-1bac589e58e8)

1. We should add a border-top (color: Light)
2. & 3. We should add a `padding of 64px` before and after the empty state placeholder.

**Comment by FelixMalfait** [comment]
@hnrykm let us know if we should unassign you or if you're working on this. Thanks a lot :)
