### ISSUE TITLE
Object creation takes too long

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5278]
# Description

Creating a custom object takes around 4s. If you mistakenly click the create button twice, an "object already exists" error will appear.

https://github.com/twentyhq/twenty/assets/19412894/06a95c7b-f5de-4ac0-80d8-6ad5d33d24fc

# Desired Behavior

- We want to show a loading indicator in the button after clicking. (See below)
- We want to prevent the "this object already exists" error from appearing when the button is clicked twice.
- We should also cut down the loading time.

Button loader:

https://github.com/twentyhq/twenty/assets/19412894/53f51de3-2ec2-4320-a972-aa6e6019bda5

**Comment by JustGJ** [comment]
Hi, this is my first contribution to an open-source project, and I'm willing to challenge myself by attempting to solve this issue! Thank you in advance for the assignment!

**Comment by pacyL2K19** [comment]
I can work on this
@Bonapara @FelixMalfait @charlesBochet

**Comment by Bonapara** [comment]
I am assigning you then @pacyL2K19, thanks for contributing!
