### ISSUE TITLE
Add Signout + Book a Call buttons to the "Choose your plan" page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5281]
# Current behavior

Today, on the "Choose your plan" page, I cannot log out or book a call in case I have an issue (already have an account etc...)

# Desired Behavior

Add a `book a call` & `log out` buttons as follows:

https://github.com/twentyhq/twenty/assets/19412894/5280b423-cbec-4977-9e95-59500f43f8ff

The book a call button should redirect to: https://cal.com/team/twenty/talk-to-us

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=23229-55049&mode=design&t=HJbRpWcvHNE7lD8B-11

**Comment by orinamio** [comment]
I'll look into this issue. Can you assign me to it?

**Comment by Bonapara** [comment]
Yes, thanks (again!) @orinamio
