### ISSUE TITLE
Fix message thread pagination

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5282]
On a company or person's detail page, go to the emails tab. 
You will see the frontend does two request to `GetTimelineThreadsFromCompanyId`.
It seems it only stops doing request when it finds an empty array. 
Instead, it should rely on the count returned in `totalNumberOfThreads` variables.
If that count it inferior to the total number of records we ask for, then we already know we don't have to ask for a second page.

**Comment by orinamio** [comment]
I'll look into this issue. Can you assign me to it?

**Comment by FelixMalfait** [comment]
Let's leave this one to someone else while you work on the others? Happy to assign it after. Thanks again!!!

**Comment by Nabhag8848** [comment]
- Similarly **Calendar** is making **[GetTimelineCalendarEventsFromCompanyId]** even all records are fetched.
