### ISSUE TITLE
Duplicated Calendar Events Display

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5296]
# Current Behavior

Duplicate display of certain calendar events occurs, likely due to their presence in both my calendar and a team member's.

![image](https://github.com/twentyhq/twenty/assets/19412894/b2bc36e8-c611-498d-aaf0-541c96dc688e)

# Desired Behavior

Merge the display of duplicate events.

**Comment by tiagoapolo** [comment]
@charlesBochet has anyone worked on this?

**Comment by Bonapara** [comment]
@bosiraphael do you confirm it was fixed?
