### ISSUE TITLE
bug: user has to re-login every time chrome sidepanel opens

### ISSUE THREAD

**Issue by AdityaPimpalkar** [twentyhq/twenty#5297]
## Bug Description

Chrome sidepanel doesn't persist state in the background, every time we close/open sidepanel it loses its previous state and restarts again. So we end up having to login everytime.

https://github.com/twentyhq/twenty/assets/13139771/66a586bb-f78f-4bbd-86a7-14c93ab60258

## Expected behavior

Ideally need to bypass login automatically and directly route to desired page

## Technical inputs

One way could be to use our `/verify` route with `authToken` as query parameter, like `/verify?authToken=....` similar to  `loginToken` query parameter which is already present. We can get our authToken from chrome's storage, verify it on backend and return if its valid, then set the required state for the app to load and then redirect it to our desired route

**Comment by GTgyani206** [comment]
If the issue is still open, I would like to work on it!
