### ISSUE TITLE
Icon Position Adjustment in Relation Chip

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5298]
# Current Behavior

The icon in the relation chip is currently positioned to the right of the text.

![CleanShot 2024-05-06 at 10 32 07](https://github.com/twentyhq/twenty/assets/19412894/bf74d459-e0b2-4450-990e-bc846be18ba9)

# Desired Behavior

The icon should be on the left side, preceding the text within the chip.

![CleanShot 2024-05-06 at 10 38 59](https://github.com/twentyhq/twenty/assets/19412894/45fcfd23-0d8e-4e21-83ed-4e3043df11e9)

**Comment by JustGJ** [comment]
Hi, great for my first contribution! Could you please assign me to this issue please ?

**Comment by Bonapara** [comment]
I just assigned you on the other issue you mentioned earlier @JustGJ 🙏

**Comment by JustGJ** [comment]
Thanks so much !

**Comment by jeet1desai** [comment]
@Bonapara can you please assign this to me, if no one is working on this one, I'd love to do it

**Comment by Bonapara** [comment]
Sure, thanks @jeet1desai!
