### ISSUE TITLE
Poor contrast on Notes & Tasks "block menu" 

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5304]
# Current behavior

The menu contrast is not great

![CleanShot 2024-05-06 at 16 06 52](https://github.com/twentyhq/twenty/assets/19412894/97247fb2-6448-494e-ace5-62a635db4ee0)

# Desired Behavior

It should look like other Menus.

```
Color: text-secondary
Background: transparent-secondary
backdrop-filter: blur(12px) saturate(200%) contrast(50%) brightness(130%);
```

![CleanShot 2024-05-06 at 16 12 28](https://github.com/twentyhq/twenty/assets/19412894/690a953f-fd16-4c6a-ac78-40fc56d98f7d)

**Comment by its-id** [comment]
@Bonapara can I take it?

**Comment by Bonapara** [comment]
Sure, thanks @its-id! 🙏
