### ISSUE TITLE
Blue Button Secondary Color Issue in Dark Mode

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5305]
# Current Behavior

![CleanShot 2024-05-06 at 16 16 34](https://github.com/twentyhq/twenty/assets/19412894/5bb602b1-c63a-44a0-b846-147e0cf3df21)

# Desired Behavior

![CleanShot 2024-05-06 at 16 18 07](https://github.com/twentyhq/twenty/assets/19412894/875b62ff-264a-4aa0-98d5-f790d8461a20)

# Component

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=3122-142114&mode=design&t=jnteOz7Mv90WFi3R-11

**Comment by its-id** [comment]
Hi 👋 @Bonapara, looks like a good first issue for me to start with. can u assign it to me?

thanks

**Comment by Bonapara** [comment]
Sure @its-id, thanks for contributing!

**Comment by its-id** [comment]
> BTW, I keep getting the following error **(TS5042)** when trying to start the app. completed the setup as instructed in docs.
> 
> <img alt="image" width="816" src="https://private-user-images.githubusercontent.com/60315832/328419460-ae8d4a9b-ad55-4169-b844-18d3b1f9eb9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTQ4MjAsIm5iZiI6MTcxNTA5NDUyMCwicGF0aCI6Ii82MDMxNTgzMi8zMjg0MTk0NjAtYWU4ZDRhOWItYWQ1NS00MTY5LWI4NDQtMThkM2IxZjllYjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE1MDg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MjQwNzkxZWY2NzM3MzQwNDlmNDkwMzY3M2ExMTc4ZjkzMGEwZTgzOTdhNzllNzFmZTU1MTVhZTUwYzgwYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hx-NljmHbFDp0Gyr_ry7gkaXNjJhsxybSOhs5JOMQrg">
> 
> I looked it up and got to know its somewhat related to VSCode ([here](https://github.com/microsoft/vscode/issues/32400)), but the fix is unclear to me. Any help would be very much appreciated. ❤️

ok. seems like there was a space in my folder name causing this entire headache. fixed it. credits to @charlesBochet
