### ISSUE TITLE
Missing Team Member Images in Calendar Events

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5308]
# Current Behavior

Team member images are absent from Calendar events participant chips.

![Current Behavior](https://github.com/twentyhq/twenty/assets/19412894/148e7047-c084-46a8-9cbd-cb4b50631fae)

# Desired Behavior

Integrate display of team member profile pictures in Calendar events participant chips.

**Comment by emiliomarquez** [comment]
Hi can I be assigned to this issue? I'd like to try to implement it, thank you!

**Comment by Bonapara** [comment]
Sure, Thanks @emiliomarquez

**Comment by mritosa** [comment]
Hello, im new to contirbuting. I would like to fix this issue.

**Comment by Bonapara** [comment]
Sure thanks for contributing! @mritosa

**Comment by mritosa** [comment]
Hi, i need some help with this problem. I found out that response of request is not good. 
<img width="443" alt="Screenshot 2024-05-09 at 17 50 20" src="https://github.com/twentyhq/twenty/assets/100703401/50ec0d59-4591-4fc4-b26e-aa5d8e179271">
The request should return the Person object, but it only returns its ID. Do you have any idea where is the problem?

**Comment by Bonapara** [comment]
@mritosa, could you ask on Discord? I'm not the right person to help!
