### ISSUE TITLE
Secondary Button accent danger problem in dark mode

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5325]
# Current Behavior

When deleting an API key in `Settings/Developers`, the confirmation button currently appears as follows:

![image](https://github.com/twentyhq/twenty/assets/19412894/8026e464-78da-4042-b865-c99ddf05090b)

# Desired Behavior

The button should match the design system's color specifications.

![CleanShot 2024-05-07 at 17 11 44](https://github.com/twentyhq/twenty/assets/19412894/dbb7db40-6b9b-4caf-85cd-9659c0c607c3)

**Comment by Bonapara** [comment]
Other buttons look right, It might not be the theme

![CleanShot 2024-05-07 at 17 15 25](https://github.com/twentyhq/twenty/assets/19412894/e688fc4d-d088-4e56-97b3-27e11655db10)

**Comment by kapilkumar9395** [comment]
Hi @Bonapara ,
I would like to work on this. Could you please assign this to me.

**Comment by its-id** [comment]
can start working on it. if not assigned.

thanks.

**Comment by Bonapara** [comment]
Let's merge the first PR for this one as it's a small issue!
