### ISSUE TITLE
Json field is broken, trying to parse json

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5329]
Json field is broken.

It seems that it's trying to parse the JSON and displaying is as a JS object

<img width="209" alt="Screenshot 2024-05-07 at 18 13 25" src="https://github.com/twentyhq/twenty/assets/6399865/2565d861-289d-47d3-a985-42e4e9175f74">

Note: Greptile is only giving potential direction, sometimes it says inaccurate things and gives wrong directions

**Comment by aojunhao123** [comment]
I would like to solve this issue

**Comment by FelixMalfait** [comment]
Thanks @aojunhao123

**Comment by MRLab12** [comment]
@FelixMalfait Hey, I was trying to replicate this bug. Do you mind sharing what you did to trigger the raw JSON?

**Comment by charlesBochet** [comment]
@FelixMalfait @MRLab12 I think this has been fixed already by @thaisguigon
