### ISSUE TITLE
Add new Currencies with Corresponding Icons

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5351]
# Desired Behavior

Add 3 new currencies to the currency field options:

MAD -> https://tabler.io/icons/icon/currency-dirham
QAR -> https://tabler.io/icons/icon/currency-riyal
AED -> https://tabler.io/icons/icon/currency-dirham

**Comment by kusumdesai** [comment]
Hey @Bonapara !!!!
Can you please assign these issue to me under GSSoC'24??

**Comment by Bonapara** [comment]
@kusumdesai sorry I was not quick enough, a commit has already been pushed :)

**Comment by kusumdesai** [comment]
@Bonapara No worries!!
