### ISSUE TITLE
If an account connection failed I should be able to reconnect it

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5371]
I just noticed that, within settings > account, if your connection failed you see an arrow ">" that takes you to the email tab (where the thing can be succesful). It's misleading (user I was talking to didn't find a way to re-connect their account, they kept coming back to the account that to do it which makes sense). If a connection failed we should provide a way for people to reconnect easily directly from the account tab.

**Comment by charlesBochet** [comment]
This has been completed
