### ISSUE TITLE
[Timebox] Fix "defaultValue": "'undefined'"

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#5381]
## Bug Description

Fix https://twenty-v7.sentry.io/issues/5201989611/events/f05bd5c263c84c7d8de11fb8dd7b3464/?project=4507072499810304&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=previous-event&statsPeriod=24h&stream_index=6

**Comment by FelixMalfait** [comment]
Closing this for now as I don't see a recent occurence and not much context was provided in the issue.
cc @charlesBochet feel free to re-open if you know it's still an open issue
