### ISSUE TITLE
Display issue in kanban options

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5393]
Just came across this:

<img width="234" alt="Screenshot 2024-05-13 at 17 42 06" src="https://github.com/twentyhq/twenty/assets/6399865/38127f2a-93c1-4952-9eb3-43ae969805e1">

Also this isn't very pretty
<img width="179" alt="Screenshot 2024-05-13 at 17 43 30" src="https://github.com/twentyhq/twenty/assets/6399865/f8ebb226-e3bd-4cf2-8d1b-5ffb7cf763bd">

**Comment by H0onnn** [comment]
@FelixMalfait Hello ! Can I solve this problem ?

**Comment by FelixMalfait** [comment]
Thanks @H0onnn!

**Comment by H0onnn** [comment]
@FelixMalfait I have uploaded a PR for this issue. Please review :) #5397
