### ISSUE TITLE
URL Hostname from link fields shows IP address when providing ip format

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#5396]
## Bug Description

For example if you input '300' it will show `0.0.1.44`.
Another example:
<img width="430" alt="Screenshot 2024-05-13 at 18 10 34" src="https://github.com/twentyhq/twenty/assets/1834158/6459eea5-f673-40ce-92c1-161309e407ef">

## Expected behavior

It should probably not accept links that don't have top-level domain like `.com`

## Technical inputs

Check getUrlHostName which is using `new URL("http://300").hostname`.
Here 300 without tld is considered valid and is interpreted as an IP and converted back to IPv4 dotted decimal notation by URL.

**Comment by bravo1goingdark** [comment]
Can you please assign this issue to me?
