### ISSUE TITLE
Field formatting options for dateTime and date fields

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5398]
We've started introducing field options, for example on the currency field type:

<img width="542" alt="Screenshot 2024-05-14 at 09 43 28" src="https://github.com/twentyhq/twenty/assets/6399865/deb302b2-2ace-4d4c-a9fe-b5db606db0c0">

We should provide formatting options for the date fields.
For example this isn't very nice and it would be nice if we could set this up in settings and model annotations to display in a human readable format  (e.g. 2 minutes ago, 2 days ago)

<img width="150" alt="Screenshot 2024-05-14 at 09 44 27" src="https://github.com/twentyhq/twenty/assets/6399865/bc55bcfc-6f0b-4200-8478-6f418e702aee">

**Comment by FelixMalfait** [comment]
We should do a boolean on the date field "Display as relative date"
we should enable that boolean by default on all createdAt, updatedAt, deletedAt fields

**Comment by AdityaPimpalkar** [comment]
I can take this up

**Comment by Bonapara** [comment]
![image](https://github.com/user-attachments/assets/b856c0f5-9796-4718-9c7b-268aa044ca42)

**Comment by ad-elias** [comment]
Hi, could you please assign this issue to me? :)
