### ISSUE TITLE
Select Sheet step no sheet names and spacing not working

### ISSUE THREAD

**Issue by brendanlaschke** [twentyhq/twenty#5415]
## Bug Description

<img width="839" alt="Bildschirmfoto 2024-05-14 um 16 17 04" src="https://github.com/twentyhq/twenty/assets/48770548/989323b2-7e4e-431a-bd63-bbe91e6d49ea">

## Expected behavior

Show the sheet names & correct spacing.

## Technical inputs

`SelectSheetStep.tsx`& `RadioGroup.tsx`

**Comment by FelixMalfait** [comment]
this is just 1 line to change I'm doing it as it's extremely small change and I'm raising another PR related to CSV import
