### ISSUE TITLE
Box shadow on frozen header and first column

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5421]
We used to have a nice box shadow on header/first column. 
We disabled it because it was affecting performance, we need to bring it back

**Comment by FelixMalfait** [comment]
When re-implementing, check this #3241

**Comment by charlesBochet** [comment]
This one might not be trivial. Make sure to check the performances here.
@lucasbordeau FYI

**Comment by FelixMalfait** [comment]
@lucasbordeau I can't see box-shadows on the main branch, is this really closed?

cc @charlesBochet fyi

**Comment by lucasbordeau** [comment]
@FelixMalfait I opened this to finish the work, because our recent refactor didn't keep the box-shadow on first frozen column : https://github.com/twentyhq/twenty/issues/6403
