### ISSUE TITLE
Add Creation Date to Notes Panel

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5424]
# Current behavior

Creation date is not displayed

![CleanShot 2024-05-15 at 15 29 39](https://github.com/twentyhq/twenty/assets/19412894/f2ae6c5b-417b-4fa4-8ee2-9bfaab7174fe)

# Desired Behavior

![CleanShot 2024-05-15 at 15 29 07](https://github.com/twentyhq/twenty/assets/19412894/4583d8df-dec4-40b1-bba9-8927642c033c)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=5910-70825&t=00mreZdX36oeyYMJ-11

**Comment by SoraXV** [comment]
Hey, i want to try to do this, can you assign this issue to me?

**Comment by Bonapara** [comment]
Sure @SoraXV, thanks for contributing!
