### ISSUE TITLE
Support all Composite Fields Import

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#5425]
## Scope & Context

Table views currently support an "Import" feature (that can be found in the "Option" menu)
This feature enable a user to upload a csv and automatically/manually map the csv columns to record fields.

## Current behavior

Currently, the feature does not handle all composite fields (having multiple fieldColumns) properly ; selecting an ADDRESS or a CURRENCY does not work.

<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/0bb7de0e-6ce4-4fb0-8600-e5dd81f5dae6">

## Expected behavior

Import feature supports ADDRESS and CURRENCY field types like it supports FULL_NAME field type.
1) Check the behavior of Full_name by trying to make an import on People table. You'll see that fields list is exposing Firstname (Name) + Lastname (Name)
2) We want something similar for Currency: Currency Code (Amount) + Amount Micros (Amount) (Amount being the field name)
3) Similar for Address fields

## Technical inputs

The work should be done in: `packages/twenty-front/src/modules/object-record/spreadsheet-import/useSpreadsheetRecordImport.ts
`

Make sure to properly test this hook with composite case. It would also be nice to extract an util to ease testing.

**Comment by ijayhub** [comment]
good-evening, is it still, open?

**Comment by charlesBochet** [comment]
Hi @ijayhub, thanks for looking to contribute, it's much appreciated
The existing PR looks good, we still need to review it and propose a few improvements, no need to open a new one!
They are other good-first-issues available :)

**Comment by ijayhub** [comment]
Okay... 👍

**Comment by lucasbordeau** [comment]
Fixed by https://github.com/twentyhq/twenty/pull/5470
