### ISSUE TITLE
Add error helpers for metadata settings inputs in form

### ISSUE THREAD

**Issue by ijreilly** [twentyhq/twenty#5428]
## Scope & Context
For now we are impeding users from trying to save an Object, a field or an option if the inputted value is not valid (because it starts with a digit or only contains empty char or is not transliterable, depending on the concerned data object). Let's add helpers in the form to help them understand what is wrong with their value (ex: "This field cannot be empty" / "Object names cannot start with digits".). 

Expected behaviour can be clarified with @Bonapara

**Comment by Bonapara** [comment]
![image](https://github.com/twentyhq/twenty/assets/19412894/3a599b2c-a251-40f4-9144-f7d0341fc389)

We should use this design!

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=3007-69739&t=vYBsvz4IWvZL44UI-11

**Comment by t007rushi** [comment]
@Bonapara this is closed?

**Comment by Bonapara** [comment]
No! I just assigned you to it. Let me know if you don't want to handle it. If you do, thank you for contributing!

**Comment by t007rushi** [comment]
Thanks @Bonapara will be happy to contribute, will ask if need any help

**Comment by t007rushi** [comment]
No issues @ijreilly
kudos for issue got solved 
understanding/learning and contributing to the repo is motive
will pick another one 👍
