### ISSUE TITLE
Depreciate the comment feature

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5440]
# Current Behavior

Currently, users can comment on Notes & Tasks. However, this feature is missing several functionalities such as mentions and edits, and the user experience is outdated.

<img width="528" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/e5ed6ef9-024d-4676-a659-8b80481a163b">

# Desired Behavior

Remove the commenting feature from the front end but retain the backend components for future reintegration.

**Comment by its-id** [comment]
Would like to take it.

**Comment by FelixMalfait** [comment]
@its-id thanks! sorry I hadn't seen this issue, I've just done in another PR this afternoon

**Comment by Dan6erbond** [comment]
Hey! Is there any roadmap on when we'll see comments make a comeback in TwentyCRM?

**Comment by FelixMalfait** [comment]
@Dan6erbond No this year sorry, probably more like the Q3'2026 (I know it's very far!)

**Comment by Dan6erbond** [comment]
@FelixMalfait ok thanks for the info! That's definitely pretty far, but I'm hoping with rich-text coming to data models soon we can bridge the gap in the meantime.

Comments would be a really great enhancement for collaboration so fwiw we would definitely consider paying for a Twenty Cloud subscription if that feature was available (and rich-text fields). :)
