### ISSUE TITLE
Introduce computed field on kanban column 

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5445]
We used to have a nice feature where you could show the total value of all deals at the top of kanban columns, but it was lost in a refactoring.

We should bring it back in a more abstract way. When creating a kanban view, we should be able to pick a column, Github calls it "field sum"  

<img width="501" alt="Screenshot 2024-05-16 at 17 41 47" src="https://github.com/twentyhq/twenty/assets/6399865/b7b274cb-eb24-4bba-9908-95ab53614ee5">

**Comment by mipmip** [comment]
I found this issue when I was creating a new feature request I named "lane statistics". To see the total quoted amount in a Kanban lane would be super useful.

**Comment by FelixMalfait** [comment]
Pre-requisite: https://github.com/twentyhq/twenty/issues/6868
Once we have that it should be pretty easy to add it in the UI

**Comment by FelixMalfait** [comment]
Done. Coming in the next release!

**Comment by FelixMalfait** [comment]
@mipmip there is something similar already. That wouldn't work for you?

<img width="889" alt="Image" src="https://github.com/user-attachments/assets/9e143e74-b1f3-4e2b-aa87-650cda31ad83" />

**Comment by mipmip** [comment]
@FelixMalfait sorry for my late reply... his is exactly what I meant. Thanks!
