### ISSUE TITLE
Improve Menu Contrast and Brightness in Dark Mode

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5446]
# Current Behavior

In dark mode, the menu borders are currently darker than the content, and the menu background appears too light.

Contrast is set to 50% **in both light and dark mode**

```
backdrop-filter: blur(12px) saturate(200%) contrast(50%) brightness(130%);
```

![image](https://github.com/twentyhq/twenty/assets/19412894/6f1eb6fb-4d70-46f6-8cc0-b346d4b8dfd0)

# Desired Behavior

Contrast should be set to 100% **in dark mode**:

```
backdrop-filter: blur(12px) saturate(200%) contrast(100%) brightness(130%);
```

<img width="374" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/8f85c46e-e840-45ba-8419-8ec61ae421b8">

**Comment by Bonapara** [comment]
@charlesBochet, wouldn't this break the design system? How would you implement it?

**Comment by its-id** [comment]
I think I might have done similar fixes in the past. Awaiting [here](https://github.com/twentyhq/twenty/pull/5342).

Can I take a look?

**Comment by FelixMalfait** [comment]
Thanks @its-id! Assigning you

**Comment by Bonapara** [comment]
Hi @its-id are you still on it?

**Comment by its-id** [comment]
Hi,
really sorry for the delay. was busy for the past weeks due to personal reason. will complete by today.

**Comment by its-id** [comment]
I think this issue has already been fixed 3 days ago.
<img width="954" alt="image" src="https://github.com/twentyhq/twenty/assets/60315832/661c8676-8a74-4b4f-91f8-d3ab3f1a00ea">
<img width="718" alt="image" src="https://github.com/twentyhq/twenty/assets/60315832/5f99b16d-2fb8-4abc-a9bd-47d4d2b8232f">

can you confirm?

**Comment by Bonapara** [comment]
Don't worry, and thanks for contributing! Yes, it seems to have been fixed.
