### ISSUE TITLE
Settings > Release page is not readable in Dark Mode

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#5459]
## Scope & Context

Go to Settings > Release page in Dark Mode (can be set from Settings > Appearance)
See that title are not readable:
<img width="697" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/f85709db-06f3-49e0-ba51-082f51646c44">

## Fix

Add font colors on Release page

**Comment by H0onnn** [comment]
@charlesBochet Hello, I am a new contributor. I would like to resolve this issue if possible.

**Comment by ahsanfarooq210** [comment]
@charlesBochet  I want to work on this issue. assign it to me

**Comment by H0onnn** [comment]
@ahsanfarooq210 Sorry, I'm working on the issue
