### ISSUE TITLE
Expose duplicate check on REST API and enable batch duplicate checks

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5472]
We've developed a graphql query to check for duplicates for each object (`CompanyDuplicates`, `PersonDuplicates`,...).
It would be great to expose this also on the REST API, so that it could be leverage by revert.dev when doing a mass import, therefore avoiding duplicates.

It should probably be a POST request to https://api.twenty.com/rest/{companies|people|...}/duplicates
With body containing `ids` or `data`

**Comment by charlesBochet** [comment]
@martmull
