### ISSUE TITLE
Fix emoji import in CSV 

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5476]
I tried to import the following CSV on the companies tab:
[companies.csv](https://github.com/twentyhq/twenty/files/15377451/companies.csv)

But the emojis are not displayed properly:
<img width="202" alt="Screenshot 2024-05-20 at 15 15 44" src="https://github.com/twentyhq/twenty/assets/6399865/1fefa01a-e14e-417e-b024-9204504da53b">

Probably something to change to force utf-8? Not sure if it's at the API level or on the frontend side

**Comment by FelixMalfait** [comment]
Sure @nishit-g thanks!

**Comment by FelixMalfait** [comment]
Hey @nishit-g unassigning you since it's been 10 days but feel free to raise a PR if you're working on it

**Comment by rostaklein** [comment]
Hey @FelixMalfait please assign this to me and find the solution in the PR mentioned above :)
