### ISSUE TITLE
Support custom object renaming

### ISSUE THREAD

**Issue by ijreilly** [twentyhq/twenty#5491]
# Scope & Context

Currently, renaming a custom object is not permitted. 

# Desired behavior

Api name and table name are dependent: if I update the api name, the table name is updated.
Label and api names can be independent or not:
- dependent (sync): updating the label will entice api name update. Direct api name update is not allowed. 
- independent (not sync): updating the label does not update anything else. 
By default, they are dependent (sync).

Steps: 
1) Add an Advanced Settings option on the Developer Settings page that allows to sync or unsync all **labels** and **API names**:

![CleanShot 2024-07-15 at 10 53 25](https://github.com/user-attachments/assets/79eab3ea-ac74-4825-9fcf-817d856d8671)

2) Behavior on an object detail page when this sync setting is activated:

- C) and D) are deactivated (Read-only)
- Changing A) **always** changes B) and D)
- C) reflects the value of B), regardless of whether B) is overridden or updated by A)
- C) and D) field Info button (i) should inform the user that he should deactivate the Sync settings in Advanced Developer settings to set a custom API name 

![CleanShot 2024-07-15 at 10 28 13](https://github.com/user-attachments/assets/d0541504-f9e2-4728-9f60-c02202505fbe)

3) Behavior on an object detail page when this sync setting is deactivated:

- Changing A) updates B)
- C) & D) are not impacted when A) or B) are updated
- C) & D) are activated and their value can be updated
- C) & D) field info button (i) should explain the constraints of the API names

4) Behavior on the Developer advanced Setting activation and deactivation:

- Deactivating the toggle should stop the synchronization, the API names should stay what they are.
- When reactivating the toggle, a for-each loop should iterate over every object to set the API names to match the object labels. C) should be updated with B) and D) should be updated with A)

5) Object creation

When creating a new object, even if the `Sync labels & API names` setting is deactivated, the API names should match the labels.

# Technical inputs

1. In discussion: should sync/unsync choice be defined/stored at object or workspace level?
2. In discussion: should sync/unsync choice allow/prevent api name update in the product only or in the api too?
3. Table name migration is already handled in our workspace migration runner. Check out `renameTable` method.

**Comment by Bonapara** [comment]
Related to https://github.com/twentyhq/twenty/issues/6145

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara Do you need me to work on this as part of 6145?

**Comment by Bonapara** [comment]
f

**Comment by ijreilly** [comment]
@Bonapara I think we need to clarify if we want to migrate the table names or not upon renaming the objects. (For now that is required for the application to work correctly, beyond the desire of consistency.)

@Faisal-imtiyaz123 thanks for your interest, lets wait until this is clarified !

**Comment by Bonapara** [comment]
![image](https://github.com/twentyhq/twenty/assets/19412894/14e985ab-adfa-41b2-a8c2-f5e75ad0f71c)

Everything should be deducted from the plural label at creation. The singular label should automatically update when the plural label is updated, even if it was overwritten in advanced settings.

The API names should **not** be updated when the labels are updated.

@FelixMalfait Does this look good to you too?

**Comment by ijreilly** [comment]
@Bonapara the "api name" needs to follow a series of constraints: being camelCased, only contain latin characters etc .(from the product we do the transliteration from the label). I think some hints may be useful here, maybe a front-end validation with hints as we do here: https://github.com/twentyhq/twenty/issues/6094

Also just my opinion but I am not sure whether this section should show directly for all users, or be semi-hidden behind an expandable section. Thinking of cloud non-tech users here

**Comment by Bonapara** [comment]
![23af7638932672bcd6b8b976daaecdcc46a8af7c00a75b64611a389b82b07c1d](https://github.com/twentyhq/twenty/assets/19412894/898a1ebf-d1a0-4d0f-97ac-b6292853595a)

> @Bonapara the "api name" needs to follow a series of constraints: being camelCased, only contain latin characters etc .(from the product we do the transliteration from the label). I think some hints may be useful here, maybe a front-end validation with hints as we do here: #6094

@ijreilly just added an info icon at the end of the input. We could also use a helper under the field, but it was redundant.

> Also just my opinion but I am not sure whether this section should show directly for all users, or be semi-hidden behind an expandable section. Thinking of cloud non-tech users here

I think it should be hidden. It's under the Advanced Mode settings.

**Comment by charlesBochet** [comment]
I am not 100% convinced by this feature :
1)  if the label change is what is displayed in regular mode but does not change the apiName (nameSingular and namePlural in database), for most of the users the label will diverge from the database model which is an issue for readability using tools such as metabase. I feel that by default both should go together and we would need to introduce a way to in advance mode to: override the labels OR to use the apiNames.

2) For labels we have singular and plural, for names we should have the same

**Comment by Bonapara** [comment]
For 2. @charlesBochet did you see the screenshot in the thread?

(The idea would be to deduct the singular name for both the API and Labels from the plural label input)

**Comment by FelixMalfait** [comment]
@charlesBochet I also didn't feel 100% good about the feature. Maybe one option to avoid introducing the overwrite boolean is to build a function that detects automatically if it's been 'unsychronized' for each field? From a UX perspective we could also display it as "suggested: xxx" @Bonapara, that way if a user wants to "re-sync" they can set the suggested value. Even if the fields are not displayed in non-advanced mode, they would still be sent.

It puts the weight on the frontend which isn't great, but I don't think it's that bad, if someone uses the metadata api to update fields, they are tech-saavy enough to be on their own.

**Comment by charlesBochet** [comment]
@FelixMalfait, I still worry about this unsynchronization not being shown in non-advanced mode. I feel the source should actually be the apiName (aka nameSingular + namePlural) and the overwrite should be the label (aka labelSingular + labelPlural).

Regarding your suggestion, I like the the suggested placeholder if unsynced and if they put the same value the FE considers it synced again. Let's see what @Bonapara thinks

**Comment by FelixMalfait** [comment]
@charlesBochet In non-advanced mode we could show a small warning that indicates it's not going to be synced or something like that (@Bonapara what do you think?)

I disagree with apiName being the source of truth. Label works well for me. You can go from Label -> API Name but can't go from API Name to label (e.g. CamelCase "HelloC" and "Hello C" give the same output) . Also from a user-perspective, in non-advanced mode, they should care about label only.

**Comment by Bonapara** [comment]
We could introduce the following system:

1) An Advanced Settings option on the Developer Settings page that allows to sync or unsync all **labels** and **API names**:

![image](https://github.com/user-attachments/assets/a71e7d7b-5efd-4892-b0c6-8efd6c6952cb)

2) Behavior on an object detail page when sync is activated:

- C) and D) are deactivated (Read-only)
- Changing A) **always** changes B) and D)
- C) reflects the value of B), regardless of whether B) is overridden or updated by A)

![CleanShot 2024-07-15 at 10 28 13](https://github.com/user-attachments/assets/d0541504-f9e2-4728-9f60-c02202505fbe)

3) Behavior on an object detail page when sync is deactivated:

- Changing A) updates B)
- C) & D) are not impacted when A) or B) are updated
- C) & D) are activated and their value can be updated

4) Behavior on the Developer advanced Setting activation and deactivation:

- Deactivating the toggle should stop the synchronization, the API names should stay what they are.
- When reactivating the toggle, a for-each loop should iterate over every object to set the API names to match the object labels. C) should be updated with B) and D) should be updated with A)

5) Object creation

When creating a new object, even if the `Sync labels & API names` setting is deactivated, the API names should match the labels.

**Comment by FelixMalfait** [comment]
Good for me @Bonapara! 👌

**Comment by ijreilly** [comment]
Blocked by https://github.com/twentyhq/twenty/issues/6147
@gitstart-twenty FYI !

**Comment by ijreilly** [comment]
Comment from @charlesBochet:

_@gitstart-twenty @ijreilly @Bonapara
I'm not a big fan of:

storing this at workspace level (we don't have a storage for it right now beside workspace table and keyValuePairs table but it feels off to put it in both table)
having the for loop checking and updating all objects, this is a slow and risky operation and it can fail, it can be challenging to rollback in case of issues and display it properly to the user if we choose to go async
Could we instead keep this on the Object Edit / Field Edit page and keep it field or object level?_

**Comment by ijreilly** [comment]
We have two decisions to make 

1. should sync/unsync choice be defined/stored at object or workspace level?
--> I agree with @charlesBochet above
2. should sync/unsync choice allow/prevent api name update in the product only or in the api too?
--> I think product and api should be iso 

@Bonapara @charlesBochet @FelixMalfait

**Comment by Bonapara** [comment]
> should sync/unsync choice allow/prevent api name update in the product only or in the api too?
> --> I think product and api should be iso

Agreed on Iso!

> > dependent (sync): updating the label will entice api name update. Direct api name update is not allowed.

**Comment by gitstart-twenty** [comment]
Hello @ijreilly , we would like to confirm a few points:

- the sync/unsync will only happens on the app and not in the API, right?
- regarding the sync/unsync choice, where should we save this information at the workspace level?

> storing this at workspace level (we don't have a storage for it right now beside workspace table and keyValuePairs table but it feels off to put it in both table)

- what triggers the sync/unsync choice is the advanced settings button, but what happens if the user turn on the toggle to see another feature, in another page for example? should we update sync/unsync choice regardless of where the user is? It seems more appropriate just update if the user is editing a custom object, do you agree?

**Comment by ijreilly** [comment]
Hi @gitstart-twenty 

1. Not sure to understand your question, but the sync/unsync **does** regard a back-end behaviour. Today each object has a `labelSingular` and a `labelPlural` (ex: "Companies" or "House listings" as label plural) and a `namePlural` that is the camel-cased version of the label in latin characters (ex: "companies" or "houseListings"). The object `nameSingular` gives its name to the table in database (prefixed with a _ for custom object: ex table for "House Listings" is `_houseListing`) where the data is stored on the individual workspace schema. (You can observe all this creating a custom object and inspecting your database's metadata.objectMetadata table and the custom table created in your workspace schema).
So far in the product the name is directly inferred from the label in the back-end, there is no "name" input. It is not possible to update the label.
We want to add the possibility for the user to update both the label and the name, and to be able to do so independently: 
if the sync is disabled, it is possible to update solely the label (from "House Listings" to "Listings" while leaving houseListing as name) or solely the name (from houseListings to listings while leaving "House Listings" as label). 
if the sync is enabled, it is only possible to update the label in the product, and the name will be inferred in the back-end from it (from "House Listings" to "Listings"  as label plural will update the name plural to "_listings").

2. From the conversation above, the sync/unsync status should be stored **at object level**, so you should add a column areLabelAndNameSync on objectMetadata table I think (@charlesBochet right?). So @Bonapara 's design should be adapted to move the case below to objects' individual settings pages: 
<img width="435" alt="Capture d’écran 2024-09-30 à 09 26 44" src="https://github.com/user-attachments/assets/870ebf8c-fafe-44e8-b913-68e52c6a74f5">

4. What triggers the sync/unsync choice is not the advanced settings button. The advanced settings button only fulfills a hide/display role on the product. 
The sync/unsync choice is stored at object level and can be updated with this toggle, that will trigger an objectMetadata update (calling object-metadata.service)
<img width="435" alt="Capture d’écran 2024-09-30 à 09 26 44" src="https://github.com/user-attachments/assets/870ebf8c-fafe-44e8-b913-68e52c6a74f5">

I hope this helps !

**Comment by gitstart-twenty** [comment]
Thanks for the clarification @ijreilly 🤝 

@Bonapara , could you provide the Figma link for this page?

**Comment by Bonapara** [comment]
https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34855-565832&node-type=frame&t=YZppWDu8cDmzxDmJ-11

**Comment by gitstart-twenty** [comment]
Hello @Bonapara 
![image](https://github.com/user-attachments/assets/09e0d42c-294d-467f-bd22-476fba9f4d26)


are these `settings` and `fields` tabs part of this ticket?
Also, we could not see the toggle below in the design, is it on another page?

![image](https://github.com/user-attachments/assets/22b8ef17-ea67-4abf-9fc0-8d8ee87e3836)

**Comment by Bonapara** [comment]
Hi @gitstart-twenty yes it is.

You're right, here is the updated design:

![image](https://github.com/user-attachments/assets/16257a54-b092-4c6d-9feb-3100fa9ff7e1)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34855-565832&node-type=frame&t=tQMdDCnS2jhEWHND-11

**Comment by gitstart-twenty** [comment]
Hello @Bonapara 
about the UI changes, the action button is different when the design is on the field tab, but there is no save button for the settings tab
![image](https://github.com/user-attachments/assets/c2b793f8-1864-4b39-924b-b825605ad887)

![image](https://github.com/user-attachments/assets/003ff4a5-a984-4012-b7a2-10c9cb3016a3)


we are assuming that the save button would appear as the action button if the user is on the settings tabs, is this correct?
but if this is correct how about the cancel button?

**Comment by Bonapara** [comment]
Hi @gitstart-twenty, we should do some auto-save for the `Object Settings Tab` edits and not display a save button at the top right.
