### ISSUE TITLE
Fix field positionning on Record page

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5500]
I just noticed we broke the positioning of input fields on the record show page:

<img width="170" alt="Screenshot 2024-05-21 at 11 30 26" src="https://github.com/twentyhq/twenty/assets/6399865/11e9a164-8fcb-4fb6-8e58-92ee26eb8750">

Ideally it should open exactly where the read-only text was. So if I the input is filled and I click on edit the text should really move.

Related: #5416

**Comment by thomtrp** [comment]
@FelixMalfait do you still see the bug? I cannot reproduce
