### ISSUE TITLE
Change Email tab illustration color to pink

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5502]
# Current Behavior

The email tab placeholder on the people record page is red, giving the impression of an error.

# Desired Behavior

Change the placeholder color to pink.

![image](https://github.com/twentyhq/twenty/assets/19412894/2aa365e6-3508-40ce-b866-3a9c5d5c1d2f)

![image](https://github.com/twentyhq/twenty/assets/19412894/35f7091f-940c-49e1-856e-f4e04feb9375)

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=21628-53011&t=bcKzeniOHKNgwiqg-11

**Comment by jeet1desai** [comment]
hey @Bonapara please assign it to me, I'll look into it

**Comment by Bonapara** [comment]
Sure [@jeet1desai](https://github.com/jeet1desai), thanks for contributing!
