### ISSUE TITLE
With CSV import, special characters are garbled

### ISSUE THREAD

**Issue by livingstonlarus** [twentyhq/twenty#5511]
## Bug Description

Importing a CSV that contains special characters in some columns results in garbled characters in the imported records.

**Example:** 

In a People record, the Firstname column contains "François" in the CSV, but is imported as "FranÃ§ois" in Twenty.

Same issue with other French characters like é (Ã©), è (Ã¨), etc.

## Expected behavior

Special characters should be supported and imported properly.

## Technical inputs

If this makes any sense or have any importance in terms of character encoding of the file: my CSV file is an export from Pipedrive. It's been stored on OneDrive and then downloaded to my Mac before uploading to Twenty. I'm running Twenty 0.11.2 on RepoCloud.

On my Mac in Terminal, `xattr -l` on the CSV file returns:

`com.apple.TextEncoding: utf-8;134217984`

**Comment by FelixMalfait** [comment]
Thanks for the report. This was fixed, thanks to @rostaklein 🙏.
