### ISSUE TITLE
Update Docker Hub image

### ISSUE THREAD

**Issue by livingstonlarus** [twentyhq/twenty#5513]
## Scope & Context

At Docker Hub, the latest tag is 0.3.3: https://hub.docker.com/r/twentycrm/twenty-front/tags

While at GitHub it's 0.11.0: https://github.com/twentyhq/twenty/releases

The Docker Hub image should be updated for each new release.

## Why it's important?

From the docs, it's suggested to install Twenty to Render or RepoCloud:

https://docs.twenty.com/start/self-hosting/cloud-providers

=> https://render.com/deploy?repo=https://github.com/twentyhq/twenty

=> https://repocloud.io/details/?app_id=259

When installing on RepoCloud, I have version 0.11.2 that's pulled directly from GitHub (notice that it's even fresher than the latest release on GitHub, which shows 0.11.0).

But when installing to Render, it's pulling the image from Docker Hub (image URL: `docker.io/twentycrm/twenty-front:latest`). So I'm running an outdated image, 0.3.3.

**Comment by charlesBochet** [comment]
@livingstonlarus we recommend using twenty image now (not twenty-front or twenty-server). That's the only one we publicly maintain

We need to update the docs and render to use twenty instead of the previous images. Regarding repocloud it's community maintained at the moment

**Comment by moltar** [comment]
> we recommend using twenty image now

@charlesBochet So there's just one container then now that holds both BE & FE? Or are we supposed to run separate services still, just a single image is baked?

**Comment by charlesBochet** [comment]
@moltar just one :) You can host the FE separately on an S3 if you wish but it's not mandatory
