### ISSUE TITLE
"Delete" option in Kanban board contextual menu does not delete

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#5520]
## Bug Description

On any Kanban board (ex: Opportunity Kanban Board), right click on a record and click on "Delete". Nothing happens

<img width="905" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/da32a12a-d72d-47dd-942f-c69b5916a250">

## Expected behavior

The record is deleted (same behavior as when left clicking and using the Action Bar)

**Comment by pacyL2K19** [comment]
I can pick this up @charlesBochet

**Comment by charlesBochet** [comment]
sure @pacyL2K19, thank you!
