### ISSUE TITLE
Fix Captcha when entering a wrong password

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5522]
We recently implemented captchas to improve the app's security.

But one think we didn't anticipate is the renewal of captcha in case you type a wrong password.
In that case, when frontend receive a negative response, it should ask for a new token.
Currently it still sends the old token which has already been used once for the first password attempt and which is therefore invalidated already.

**Comment by nganphan123** [comment]
Hi @FelixMalfait I'd love to work on this. Can I take this?

**Comment by FelixMalfait** [comment]
Sure thanks @nganphan123!

**Comment by FelixMalfait** [comment]
Please keep us updated as it's something that ideally shouldn't stay open for too long. Thanks a lot!

**Comment by piyushyadav1617** [comment]
Hey @FelixMalfait, I found the issue and was able to resolve it. I see that the issue is currently assigned to @nganphan123. If it is an immediate concern, I would like to create a PR for this. Could you please assign this issue to me if possible?

**Comment by FelixMalfait** [comment]
Thanks @piyushyadav1617 ; let the best PR win then 😁 

🙏

**Comment by nganphan123** [comment]
Hi @FelixMalfait , I had my solution ready. But, I stuck at rebuilding the image to test code in deployment. Since @piyushyadav1617 created a PR, I'll leave it to them then. I'll take a look at another issue. Thanks for assigning this to me before.

**Comment by FelixMalfait** [comment]
@nganphan123 no problem! Thanks for taking a shot at it!
