### ISSUE TITLE
Add support for CZK Currency

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#5530]
## Scope & Context

In CurrencyInput, we are supporting the following currencies: 
```
  CAD = 'CAD',
  CHF = 'CHF',
  CNY = 'CNY',
  EUR = 'EUR',
  GBP = 'GBP',
  HKD = 'HKD',
  JPY = 'JPY',
  USD = 'USD',
  NOK = 'NOK',
  SEK = 'SEK',
  MAD = 'MAD',
  QAR = 'QAR',
  AED = 'AED',
```

Let's also add CZK currency

## Current behavior

It should be reflected on CurrencyFields (example Opportunity > Amount)

**Comment by charlesBochet** [comment]
Sure, go ahead! Thank you :)

**Comment by shashankvish0010** [comment]
Hi @charlesBochet, I have solved the issue, so can I raise a PR for it?

**Comment by Princeyadav05** [comment]
> Hi @charlesBochet, I have solved the issue, so can I raise a PR for it?

Hi @shashankvish0010 I've also solved the issue. Don't have time to raise the PR today. Go ahead and raise your PR.
