### ISSUE TITLE
Add a ⏎ shortcut on Select options

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5540]
# Desired Behavior

When I type an `option value` while creating a new `Select Field`, pressing `⏎` should validate the option, create a new one, and move the focus to it.

![CleanShot 2024-05-22 at 18 12 11](https://github.com/twentyhq/twenty/assets/19412894/991d927d-40a6-46ec-9208-5e2358188dba)

**Comment by kelcied** [comment]
Hi @charlesBochet, I think I could do this issue!

**Comment by ejmoore99** [comment]
Hi I want to get on this issue!

**Comment by Bonapara** [comment]
Sure @ejmoore99, thanks for contributing!
