### ISSUE TITLE
Emails sync failing - Google account connects but sync state is either stuck on "pending" or immediate "failed"

### ISSUE THREAD

**Issue by r0bbie** [twentyhq/twenty#5549]
## Bug Description

Initially tried on a self-hosted install (v0.11.2 Docker). My Google account successfully connects, and calendar sync seems to work flawlessly. Email sync however shows "pending" and never syncs:

<img width="533" alt="Screenshot 2024-05-23 at 13 45 05" src="https://github.com/twentyhq/twenty/assets/1804229/864308c8-4c42-40e8-9e2d-7e6fad5a480a">

To rule out a problem with my specific setup I then tried this on https://app.twenty.com and there it also fails. Again calendar connects and syncs successfully, but here email sync state immediately goes to "failed":

<img width="532" alt="Screenshot 2024-05-23 at 13 46 50" src="https://github.com/twentyhq/twenty/assets/1804229/89d5997a-f8e6-4d9d-ab84-e3d5d23f8d65">

So slightly different behaviour on hosted vs self-hosted but failing on both.

## Expected behavior

Expected emails to successfully sync.

## Technical inputs

Tried on a self-hosted install, and a newly created workspace on https://app.twenty.com

The account is a Google Workspace account in case relevant. I've been trying to rule out issues with the account itself - my first thought was it could be API access permissions being blocked at the workspace level, but in Google Workspace admin "App access control" has Gmail set to unrestricted. And again calendar sync succeeds, so it's strange.

Please let me know if I can provide any further detail / logs etc!

**Comment by bosiraphael** [comment]
Hey @r0bbie ! Thank you for documenting on this issue.
I think that the self hosted problem comes from the fact that you might have not started the cron jobs which are needed to sync the emails.
These are the commands:
- `npx nx run twenty-server:command cron:messaging:gmail-partial-sync`
- `npx nx run twenty-server:command cron:messaging:gmail-fetch-messages-from-cache`
Also, you can check that your worker is running correctly:
- `yarn nx worker twenty-server`
Tell me if this solves the problem, or if it's something else :)

I will take a look at the problem in production.

**Comment by r0bbie** [comment]
Thanks **@bosiraphael**! By the way let me know if I should have split this out as two separate issues, wasn't sure if they were the same cause or not!

On self-hosted install (and stuck on "pending" issue) should say I'm running this self-hosted following Docker instructions at [https://docs.twenty.com/start/self-hosting/docker-compose](https://docs.twenty.com/start/self-hosting/docker-compose) (with additional Google environment variables added though not currently documented there, i.e. AUTH\_GOOGLE\_CLIENT\_ID AUTH\_GOOGLE\_CLIENT\_SECRET etc etc)

Should the cron jobs not run already in the Docker container, or is that not setup by default at the moment? I tried running those commands in the container (i.e. `npx nx run twenty-server:command cron:messaging:gmail-partial-sync`) but that didn't seem to work - it tried to install a load of missing dependencies with yarn, then said it had to rebuild the app before the command would run, which then broke the live app. Recreating the Docker container got me up and running again easily enough.. but assuming this isn't the right approach anyway, since any changes to the container would just be lost each time it's rebuilt from the image anyway I think right? Maybe I'm being dumb / running them in the wrong place though, if so please let me know 😅

For the in-production issue, please let me know if I can provide any further info that might help :)

**Comment by charlesBochet** [comment]
We can discuss your self-hosting issues from #help on Discord, you'll get faster answers

Feel free to ping the team using the Support button in the left navigation bar on app.twenty.com

**Comment by deurk** [comment]
Facing the same issue, some steps are missing for self-hosting the docker versions apparently. I had to dig to find the `AUTH_GOOGLE` credentials as well, and the commands mentioned above end up with errors `ERROR [Error] Nest could not find GmailPartialSyncCronJob element (this provider does not exist in the current context)` for example.

Really looking forward to find out the missing pieces, as Twenty looks exciting to work with!

**Comment by bonnlei** [comment]
I have same issue by self-hosting. It shows always pending.
I have seen that the email async added. 
![Snipaste_2024-05-25_19-15-50](https://github.com/twentyhq/twenty/assets/2550769/b804aeab-da64-462b-af10-e87f2692a5e1)
How to check the sync cron running?

**Comment by FelixMalfait** [comment]
We've made significant improvements to the sync process since this was last discussed so I'm going to close this, hopefully it should work well by know, just make sure the worker is running!
