### ISSUE TITLE
Adding a task with attached text containing a long first line isn't truncated, and breaks layout

### ISSUE THREAD

**Issue by r0bbie** [twentyhq/twenty#5552]
## Bug Description

Adding a task either without attached text, or with attached text containing a short initial line, keeps layout fine:

<img width="1060" alt="Screenshot 2024-05-23 at 17 15 20" src="https://github.com/twentyhq/twenty/assets/1804229/470443fa-fdb0-4ddb-9bd8-8cff409e8455">

<img width="1057" alt="Screenshot 2024-05-23 at 17 17 56" src="https://github.com/twentyhq/twenty/assets/1804229/19573918-31df-4f69-87c9-074b6692afc4">

If however text is attached with a longer first line, then the full line is displayed without truncation, which breaks the table layout:

<img width="1066" alt="Screenshot 2024-05-23 at 17 18 21" src="https://github.com/twentyhq/twenty/assets/1804229/f54619c5-0407-4610-8e16-0710d9d1ab9f">

## Expected behavior

Expected attached text to be truncated regardless or content or length, to ensure table layout remains consistent.

## Technical inputs

- Create a new task
- Add text with a very long single line and save

Observed on v0.11.2 installed via Docker.

**Comment by charlesBochet** [comment]
Very similar to: https://github.com/twentyhq/twenty/issues/5267
