### ISSUE TITLE
Comments left on tasks don't attach to / display the user who left the comment, but instead show "undefined undefined" (also uneditable / undeletable)

### ISSUE THREAD

**Issue by r0bbie** [twentyhq/twenty#5554]
## Bug Description

I can leave a comment on a task, but it doesn't correctly attach to my user. It shows "undefined undefined" for user

<img width="487" alt="Screenshot 2024-05-23 at 17 25 37" src="https://github.com/twentyhq/twenty/assets/1804229/fdbeaad6-a454-4589-8d46-b4e102387355">

There also then doesn't seem to be any way to edit or delete a comment once left (I'm assuming because it doesn't recognise it's _my_ comment and I should have access to do this?)

## Expected behavior

Comment correctly displays as left by my user, and I have access to edit/delete (or at least delete!) after creation.

## Technical inputs

- Leave a comment on any task

Observed on v0.11.2 self-hosted with Docker.

**Comment by richardwiden** [comment]
We are seeing the same behaviour on self hosted docker v0.11.2

**Comment by richardwiden** [comment]
In v0.11.3 the comments are removed/not visible for us atleast

**Comment by FelixMalfait** [comment]
Apologies for the delayed reply :-/

We removed the comments feature as it was really half-baked yes. It will make a come back once we're able to build something more robust with tagging, etc. probably not short-term. 
We saw usage was very low. I'm sorry if you had workflows/data that relied on this. The table is still there, we just hid the frontend part.
