### ISSUE TITLE
When creating custom object, the API could guide the user more.

### ISSUE THREAD

**Issue by waynehamadi** [twentyhq/twenty#5575]
I did this:
```
export async function main(twenty_api_key: string, campaign_name: string) {
  const url = 'https://api.twenty.com/rest/campaigns';
  const options = {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Authorization': `Bearer ${twenty_api_key}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      campaign: campaign_name
    })
  };

  const response = await fetch(url, options);
  return await response.json()
}
```

The campaigns object is a custom object without any custom fields, just a name.

I made a mistake using a field called campaign that doesn't exist but the api didn't return anything to tell me this was incorrect. 
In the loom video you will see that I end up realizing the field is incorrect but I wish the API had told me:
https://www.loom.com/share/ded9f1e638f84b518fff13ec150d6033

-----------------------------------------------------------------------

I want to say you're the CRM with the best API out there. But it could really become a top-notch stripe-level API if you use a library that automatically validates the input of the schema and simply returns it.

**Comment by BOHEUS** [comment]
@FelixMalfait I think this issue can be closed as now examples with available fields are provided for custom objects in REST
![image](https://github.com/user-attachments/assets/c7011eb4-aafa-4282-91c1-cf6ad3051883)

**Comment by FelixMalfait** [comment]
Thanks @BOHEUS
