### ISSUE TITLE
GET https://api.twenty.com/rest/metadata /relations not working?

### ISSUE THREAD

**Issue by waynehamadi** [twentyhq/twenty#5581]
## Bug Description

It looks like the REST endpoint is not working:
https://www.loom.com/share/87837147044748dfad7ce2f54d866e48

**Comment by FelixMalfait** [comment]
Thanks! We should prioritize that next sprint (~2 weeks)

**Comment by dialnco** [comment]
Error persist or regression.  `/rest/metadata/relations` endpoints keeps returning 500 server error. (cloud and self-host)

**Comment by FelixMalfait** [comment]
@dialnco would you mind opening a new issue with the payload/endpoint you're sending? Thanks a lot

**Comment by FelixMalfait** [comment]
FYI we're making a big change on relationMetadata in the next release (cc @charles), it's going to be simpler. So you might want to hold for this if it's an option for you
