### ISSUE TITLE
GET https://api.twenty.com/rest/metadata /objects filters don't work

### ISSUE THREAD

**Issue by waynehamadi** [twentyhq/twenty#5582]
## Bug Description
Try this.
since the date is lte 2020 this should return nothing:
https://docs.twenty.com/rest-api/metadata#/paths/objects/get
<img width="1050" alt="Screenshot 2024-05-26 at 1 54 43 PM" src="https://github.com/twentyhq/twenty/assets/9652976/6d7c7bca-fb5f-49e1-9184-a3fc08302f09">

And yet, it returns something.
https://www.loom.com/share/76d7bc5e82e149238484c4dca5e61aa7

**Comment by FelixMalfait** [comment]
Thanks! We should prioritize that next sprint (~2 weeks)

**Comment by martmull** [comment]
We will remove filters for metadata as it does not bring a lot of value compared to the work it requires
