### ISSUE TITLE
Data model diagram front-end improvements

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5586]
# Current Behavior

![CleanShot 2024-05-27 at 10 23 07](https://github.com/twentyhq/twenty/assets/19412894/749a53a4-eeb2-42af-86b7-69c1c06734c3)

![CleanShot 2024-05-27 at 10 31 36](https://github.com/twentyhq/twenty/assets/19412894/9ff16de6-6674-4bbf-83c9-4960bf1ab56b)

# Desired Behavior

### Card

1. Increase the border-radius to 8px
2. Add some box-shadow

![image](https://github.com/twentyhq/twenty/assets/19412894/4a2d13c9-437d-44ad-b7f8-1c8e2b6211b3)

### Card title

1. Increase the spacing between the icon and the name
3. Reduce the font-weight to "Medium"

![CleanShot 2024-05-27 at 10 24 00](https://github.com/twentyhq/twenty/assets/19412894/443bccb9-5db6-4e4b-9955-62dd5c827917)

### Relation Fields

1. Check the spacing
2. Label color should be "Primary"

![CleanShot 2024-05-27 at 10 28 04](https://github.com/twentyhq/twenty/assets/19412894/4cae5b0e-b375-4a18-ab76-5155f105a5e8)

### Other fields

Color should stay the same. Icon should be a "chevron down"

![CleanShot 2024-05-27 at 10 30 28](https://github.com/twentyhq/twenty/assets/19412894/caf19f57-78a0-4045-a425-c8df01b482e1)

### Buttons

We should use the `iconButtonGroup` and Tabler icons

![CleanShot 2024-05-27 at 10 33 47](https://github.com/twentyhq/twenty/assets/19412894/4ea5f97b-ca8c-4592-a1cb-f0ce2c56fafc)

Shadow on hover: 

![CleanShot 2024-05-27 at 10 34 04](https://github.com/twentyhq/twenty/assets/19412894/11159085-e77e-422d-8999-0f294af99a60)

**Comment by RamK777-stack** [comment]
@Bonapara I am new. How can I view this data model diagram page?

**Comment by Bonapara** [comment]
By clicking on "Visualise" on the data model settings tab!

**Comment by metc** [comment]
@FelixMalfait  Is there a way to show hidden fields?

**Comment by FelixMalfait** [comment]
On the data visualisation no you can't as of today ; probably someone will implement it as some point (not costly)
