### ISSUE TITLE
Focused cell is acting weird when scrolling horizontally 

### ISSUE THREAD

**Issue by ijreilly** [twentyhq/twenty#5595]
https://github.com/twentyhq/twenty/assets/51697796/1cb614ea-b73f-4629-abd8-7341b826dee2

**Comment by its-id** [comment]
looking into it. let me see if this can be fixed.

**Comment by ijreilly** [comment]
+ this could be linked - when selecting multiple rows they become transparent

https://github.com/twentyhq/twenty/assets/51697796/aa848bab-e849-4352-aab8-2d7525a673bf

<img width="740" alt="Capture d’écran 2024-06-05 à 12 23 57" src="https://github.com/twentyhq/twenty/assets/51697796/e7a6df16-68f4-443f-a6ed-e09c896a13b3">

**Comment by charlesBochet** [comment]
Duplicated issue: https://github.com/twentyhq/twenty/issues/6813, let's make sure both are fixed

**Comment by charlesBochet** [comment]
The issue is still there!

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by kshitij-codes** [comment]
Hey @Bonapara can I work on this issue?

**Comment by kshitij-codes** [comment]
Hey @Bonapara is it enough to just stop the scroll when a cell is clicked and is in edit mode OR it is necessary to get rid of overlap by hiding the floating element when scrolled inward?
