### ISSUE TITLE
When a new field is created, it is not optimistically added to the corresponding views

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#5598]
## Bug Description

- Go to Settings > DataModel > Person object (or any other object)
- Create a new custom field (for example a TEXT field)
- add name and save it
- exit Settings and go to People table view
- Click on the + in column Header to add a field
- Add the newly created field
- Refresh

You'll see that the field is added twice
<img width="1379" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/c3eb2341-8ff1-4a94-996c-c138945fdb52">

## Expected behavior

The viewField is correctly added to all object views in backend (if you create the field in Settings, then refresh, then go to People table, you should see it)
The front end should optimistically add it to all views. There is a piece of code about it in SettingsObjectNewFieldStep2.ts but it does not seem to work

**Comment by piyushyadav1617** [comment]
Created a PR for this (#5708)
