### ISSUE TITLE
Create a cron to refresh the connected account access token

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#5632]
## Scope & Context

Create a cron to refresh the connected account access token.

## Technical inputs

- Create two new fields in connectedAccount `accessTokenNeedsRefresh` and `accessTokenRefreshedAt`
- Create `RefreshConnectedAccountCronJob` which will run every 5 minutes and will refresh the token if `accessTokenNeedsRefresh` is true or `accessTokenRefreshedAt` > 30 minutes. After refreshing the token, set `accessTokenNeedsRefresh` to false and reset `accessTokenRefreshedAt` with the new date.
- Every sync cron for messaging or calendar should skip if `accessTokenNeedsRefresh`.
- If error 401 during one of the sync jobs: set `accessTokenNeedsRefresh` to true.
- Create a command to run the cron

**Comment by rostaklein** [comment]
Please, assign this one to me. 😊 I think I know what to do.

**Comment by charlesBochet** [comment]
@rostaklein we have actually decided to do this in the message-import script, so we don't need a cron anymore here! Closing this one. We still need help on the email and calendar if you are available, ping us on Discord :)
