### ISSUE TITLE
Add option to sync other email accounts then gmail

### ISSUE THREAD

**Issue by JakubHelis** [twentyhq/twenty#5635]
## Scope & Context

**Example:** 
```
I would like to add emails outside gmail
```

## Current behavior

We can only sync gmail emails.
*

## Expected behavior
Some option to add other email by imap?

```[tasklist]
### Tasks
```

**Comment by FelixMalfait** [comment]
Hello, I'll close this issue as their is already an open discussions (in the discussions tab) about this. This is definitely something on the roadmap, but not on the short-term roadmap. Thanks
