### ISSUE TITLE
Column Header Font Weight Too Bold - Regression

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5643]
# Current behavior

We have a regression on how the columns header looks like. Font weight is too bold:

![CleanShot 2024-05-29 at 10 42 31](https://github.com/twentyhq/twenty/assets/19412894/31a8edbb-f692-483c-8caf-2d484911a030)

# Desired Behavior

Font weight should be "medium" & Color "Tertiary"

![CleanShot 2024-05-29 at 10 45 03](https://github.com/twentyhq/twenty/assets/19412894/2634950c-4ddf-49b1-944a-1bb5779bddf6)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=568-41746&t=OdBFyvM9bUwzzntM-11

**Comment by DevGajjar28** [comment]
@Bonapara can you assign me ?

**Comment by Bonapara** [comment]
Sure @DevGajjar28, thanks for contributing!

**Comment by suman-somu** [comment]
This is also seen. Maybe related !?
![image](https://github.com/twentyhq/twenty/assets/75962762/ca90b21e-a96f-410b-9c3e-b8eb57acee82)

**Comment by suman-somu** [comment]
It works fine in Chrome. But showing the above behaviour in Firefox.

**Comment by DevGajjar28** [comment]
@Bonapara you can assign someone ,i am facing setup issue .

**Comment by Bonapara** [comment]
Thanks for giving it a try @DevGajjar28 🙏

**Comment by richkevan** [comment]
I would like to take a crack at this issue if feasible. Have some free time and want to start doing more than commits and pr's.

**Comment by Bonapara** [comment]
Sure @richkevan, thanks for contributing!

**Comment by Bonapara** [comment]
I think this one is linked to #5704

**Comment by Bonapara** [comment]
This one is fixed!
