### ISSUE TITLE
Add Background Blur to Input Fields in Edit Popups

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5644]
# Current behavior

Some input fields lack a backdrop filter and have a plain background color.

Current:
![CleanShot 2024-05-29 at 10 52 59](https://github.com/twentyhq/twenty/assets/19412894/5132f1fb-d4f0-435f-9e56-b3f98fd87fa4)

Desired:
![CleanShot 2024-03-12 at 17 20 10](https://github.com/twentyhq/twenty/assets/19412894/aacc5b1e-ce5e-4153-86b1-2289205ae765)

# Desired Behavior

Add the background blur to every field edit popup

```
backdrop-filter: blur(12px) saturate(200%) contrast(50%) brightness(130%)
background: rgba(252, 252, 252, 0.5)
```

Fields to update (but do check if I missed any):

- Calendar field
- Domain name
- Address
- Json
- Left part of the phone number field

![CleanShot 2024-05-29 at 10 50 59](https://github.com/twentyhq/twenty/assets/19412894/b1b3b769-e6a8-4dd0-9ed1-c532eeef5c0d)

**Comment by shyamsundertard** [comment]
@charlesBochet I'd like to work on this. Could you assign it to me, please?

**Comment by Bonapara** [comment]
Sure @shyamsundertard, thanks for contributing!

**Comment by charlesBochet** [comment]
@shyamsundertard FYI backdrop filters cannot be superposed in Chrome only one child should set it, this might be the cause of the issue

**Comment by shyamsundertard** [comment]
> @shyamsundertard FYI backdrop filters cannot be superposed in Chrome only one child should set it, this might be the cause of the issue

Ok I'll take care about it.
