### ISSUE TITLE
Show a disabled grip for non-movable menu items

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5653]
# Current Behavior

Non-movable menu items (in the View switcher and in the fields menu) lack the grip design present on movable items, causing icon misalignment and a less aesthetically pleasing interface.

### View switcher

![CleanShot 2024-05-29 at 16 44 04](https://github.com/twentyhq/twenty/assets/19412894/fe2af81e-47d0-4cc8-872e-75bf51b964df)

### "Fields" Menu

![CleanShot 2024-05-29 at 16 45 17](https://github.com/twentyhq/twenty/assets/19412894/d525f0b7-c282-4fee-a561-14009e692a8d)

# Desired Behavior

Add a disabled state to the grip of non-movable menu items that feature a grip to align with other items:

![CleanShot 2024-06-04 at 09 41 47](https://github.com/twentyhq/twenty/assets/19412894/5a9cf7fd-dc8b-4239-a11d-a60b453ecaa8)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=2979-174004&t=8MOAX804qj8LgKKz-11

Render:

![CleanShot 2024-06-04 at 09 43 50](https://github.com/twentyhq/twenty/assets/19412894/59570c00-3ef3-46d7-b6a0-261d43067e49)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=6377-158599&t=8MOAX804qj8LgKKz-11

**Comment by Anand-Krishnan-M-J** [comment]
Hey @Bonapara 
Could you please assign this to me?
I can work on it

**Comment by sagarhedaoo** [comment]
Hi @Bonapara Can I start working on this?
