### ISSUE TITLE
Inline fields Link chips are cropped

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5654]
# Current Behavior

On record detail pages, link chips are getting cropped.

![image](https://github.com/twentyhq/twenty/assets/19412894/5b2c63ed-69cb-4a86-8420-c0efb3b1dd7b)

This is because they are 24px instead of 20px. They are also too big in the link input popup.

![CleanShot 2024-05-29 at 17 12 46](https://github.com/twentyhq/twenty/assets/19412894/e167b896-df3f-49bd-b72e-4fe45073f54d)

# Desired Behavior

Change the height to 20px (Everywhere)

![CleanShot 2024-05-29 at 16 58 41](https://github.com/twentyhq/twenty/assets/19412894/536fe11b-3555-43a9-8593-3a95abd476f1)

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=9901-34957&t=AMFwUdc5nRYV3Nyn-11

**Comment by TheUnspokenFifth** [comment]
I am interested in this ticket, can you assign me to it?

**Comment by Bonapara** [comment]
Sure @TheUnspokenFifth, thanks for contributing!

**Comment by Bonapara** [comment]
@thomtrp All fixed?

**Comment by thomtrp** [comment]
@Bonapara it should be but can you confirm on your side? On my side that was a bit cropped but not as much as you
