### ISSUE TITLE
Replace Fast Loader with Skeleton on Account Settings Page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5659]
# Current Behavior

On the `Settings > Account` page, we display an image, text, and a loader to indicate loading. However, the loading is so fast that it causes the page to flash.

https://github.com/twentyhq/twenty/assets/19412894/960fb72b-27ae-4d45-ad26-e96f66786f86

# Desired Behavior

We want to replace this with a light skeleton loading that's `20px` high and `512px` wide. Ensure the skeleton box is perfectly aligned with the "Connected accounts" title that appears at the end of loading.

Implement the same behavior on `Settings > Account > Emails` and `Settings > Account > Calendar`

![image](https://github.com/twentyhq/twenty/assets/19412894/a77ec74d-d0c8-46c6-bc1f-7e733f1f330e)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=32014-75244&t=P12gjv5ZcZ9hChR8-11

**Comment by rostaklein** [comment]
please assign this to me and see the prepared PR :) I had an urge to do at least a small contribution

**Comment by Bonapara** [comment]
Sure @rostaklein, thanks for contributing!
