### ISSUE TITLE
Standardize Relation Icons Across Application

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5660]
# Current Behavior

We have an inconsistency in how we display relation icons across the app.

Fields list on an object detail page:

![CleanShot 2024-05-29 at 17 57 14](https://github.com/twentyhq/twenty/assets/19412894/fa6f1433-13ba-492c-9d0a-39ef5111936b)

New relation field icon:

![CleanShot 2024-05-29 at 17 56 58](https://github.com/twentyhq/twenty/assets/19412894/46a5686f-a2d6-42bf-93bf-74430b49caa3)

Customization of a new relation field:

![image](https://github.com/twentyhq/twenty/assets/19412894/3a480ca6-57ee-49c0-95ed-4b98baf69603)

# Desired Behavior

We want to display [this icon](https://tabler.io/icons/icon/relation-one-to-many) for one-to-many relations:

![CleanShot 2024-05-29 at 17 57 37](https://github.com/twentyhq/twenty/assets/19412894/71bcf521-7df2-4536-9455-198508ce3b63)

And [this icon](https://tabler.io/icons/icon/relation-many-to-many) for many-to-many relations.

![CleanShot 2024-05-29 at 17 59 07](https://github.com/twentyhq/twenty/assets/19412894/7996aa44-11c8-4f02-b812-3d38d79b9d84)

By default, we want to display the one-to-many icon everywhere.

**Comment by ijayhub** [comment]
Please is this opened? If it is can I work on this.

**Comment by Bonapara** [comment]
Sure @ijayhub, thanks for contributing!

**Comment by ijayhub** [comment]
I am currently having an issue forking the repo 
![GitHubDesktop_cJQiTnnbli](https://github.com/twentyhq/twenty/assets/66119709/88f597a1-679d-49bd-8595-3477c53ff520)
please could anyone assist me?
Thanks

**Comment by Bonapara** [comment]
@ijayhub maybe ask on our Discord: https://discord.com/invite/cx5n4Jzs57

**Comment by ijayhub** [comment]
okay thanks

**Comment by Bonapara** [comment]
@ijayhub did it work?

**Comment by NitinPSingh** [comment]
hi, "has many" and "belongs to one" both are 1:N relationship ?
![download (1)](https://github.com/user-attachments/assets/72179eb8-1f2e-481e-8f7a-63131acf7907)

and can you tell where N:N relationship is used in app?
![download](https://github.com/user-attachments/assets/02554bb9-5fb9-4b62-a94e-499d88a4f69f)

**Comment by Bonapara** [comment]
@NitinPSingh, you're right. All relations are indeed 1:N for now. "Belongs to" is N:1, but there's no icon for this, so let's use 1:N as well!

**Comment by NitinPSingh** [comment]
@Bonapara can you review the changes made in pr #6504
