### ISSUE TITLE
Increase the inline relation field hover surface

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5662]
# Current Behavior

When hovering over a relation inline field, I have to hover over the chip to display the pen icon button. Hovering over the pen icon button area does not make it appear.

https://github.com/twentyhq/twenty/assets/19412894/1bdd2286-2241-4fca-ad3e-e2de0779eb6c

# Desired Behavior

The hover should be triggered when hovering over either the content or the icon button surface.

https://github.com/twentyhq/twenty/assets/19412894/669f34e4-e567-4fb2-88e3-e47d3e67d45d

# Figma Component

![image](https://github.com/twentyhq/twenty/assets/19412894/7dd3d0d7-fb69-465f-959b-ddf5e7855d6d)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=14603-76540&t=P12gjv5ZcZ9hChR8-11

**Comment by El-47** [comment]
@Bonapara Can you please assign me the issue?

**Comment by Bonapara** [comment]
Sure @El-47, thanks for contributing!

**Comment by RobertoSimonini1** [comment]
I would like to work on that issue, can I?

**Comment by Bonapara** [comment]
@RobertoSimonini1, perhaps you could take on a "good first issue" that hasn't been assigned to anyone? https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee

**Comment by El-47** [comment]
@RobertoSimonini1 yes you can, i am having some problem with setting up the project, @Bonapara you can assign him

**Comment by RobertoSimonini1** [comment]
@El-47 ok brother, if you need some help to set up the project I think you can join discord and get some help :)

**Comment by Bonapara** [comment]
Thanks to you both @RobertoSimonini1 and @El-47!
