### ISSUE TITLE
Align Skeleton with content on Sidebar

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5664]
# Current Behavior

As we removed the `Inbox - soon` navigation item, the skeleton is no longer aligned with the content that appears after loading is complete.

https://github.com/twentyhq/twenty/assets/19412894/c3c23d2b-33f6-4b47-bf55-5e93d5c1ce27

# Desired Behavior

Remove one of the four skeleton boxes and ensure everything is properly aligned with the loaded content.

**Comment by El-47** [comment]
@Bonapara Can you please assign me the issue?

**Comment by its-id** [comment]
Hi @Bonapara, can you check on the above. I have also fixed the alignment of the skeletons to be the same as followed by the actual content.

Thanks

**Comment by martmull** [comment]
closed with https://github.com/twentyhq/twenty/pull/5705
