### ISSUE TITLE
Regression - navigation items font weight should be medium

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5665]
# Current behavior

We have a regression on the navbar menu item. They are back to `font-weight: regular`

![image](https://github.com/twentyhq/twenty/assets/19412894/b7b3a9f2-0329-4720-9d9c-ce672f136bf7)

# Desired Behavior

The Navbar menu item font weight should be  `medium`

![image](https://github.com/twentyhq/twenty/assets/19412894/ca65c618-9069-4bb4-962a-42eb781dfb0f)

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=5910-77814&t=P12gjv5ZcZ9hChR8-11

**Comment by t007rushi** [comment]
@Bonapara please assign it to me want to get started to contribute

**Comment by its-id** [comment]
Hi @Bonapara,
It looks like the medium font is assigned correctly to the navigation labels. But, its value was modified last week, can you confirm the reason behind the below change? and if you allow, then I can just hardcode it to '500'?

<img width="955" alt="Screenshot 2024-06-02 at 1 12 57 AM" src="https://github.com/twentyhq/twenty/assets/60315832/021c98a8-7218-4360-abcf-a806568b2b5f">
<img width="1201" alt="Screenshot 2024-06-02 at 1 14 20 AM" src="https://github.com/twentyhq/twenty/assets/60315832/40879510-3ebb-47e2-b94a-fcbd75f77e72">

**Comment by Bonapara** [comment]
Thanks @its-id! It looks like someone made a mistake with ChatGPT 😂

I think we could hardcode it to `500`, but maybe @lucasbordeau can explain why there is a `twentycrm-font-weight-medium` variable in :root and if we should use it.

**Comment by its-id** [comment]
@Bonapara Thanks for the resolution. I have provided a working fix for now. Can you check the above linked PR and let me know if it works.

@lucasbordeau by the time, can wait for some insights on this.

**Comment by Bonapara** [comment]
I'll let @lucasbordeau check the PR!

@its-id are you on our Discord by any chance? Would love to schedule a call to thank you for contributing. My username: `tdesfrancs`

**Comment by its-id** [comment]
Sure, I am on the server as well. Sending you a DM.
