### ISSUE TITLE
Reduce Spacing in Notes & Tasks Side Panel Titles

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5669]
# Current behavior

The spacing between the notes & tasks side panel title & subtitle is too big

![CleanShot 2024-05-29 at 19 05 30](https://github.com/twentyhq/twenty/assets/19412894/9e5d2411-6983-4552-833f-70b02151ecd4)

# Desired Behavior

- Reduce the title container to 24px height
- The subtitle container is 9px on figma vs 16px online

![CleanShot 2024-05-29 at 19 07 41](https://github.com/twentyhq/twenty/assets/19412894/6b9a6990-a253-42b2-8d0e-64ef71848f76)

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=5910-70825&t=P12gjv5ZcZ9hChR8-11

**Comment by jeet1desai** [comment]
Hey @Bonapara please assign to me, I'll look into it.

**Comment by ishan21sh** [comment]
Is this issue resolved ?

**Comment by Bonapara** [comment]
Hi @ishan21sh, @jeet1desai is on it but several other `good first issue` are still available!

**Comment by ishan21sh** [comment]
ok thank you
