### ISSUE TITLE
The "Cancel" Button should be disabled on Object creation

### ISSUE THREAD

**Issue by pacyL2K19** [twentyhq/twenty#5675]
## Bug Description

Currently, on object creation, the "Create" button is being disabled until we get a response from the server, but the cancel button is active. If a user clicks on the "Cancel" button before the API call fulfills, it gives a bad user experience, redirecting the user to the newly created Object ignoring the cancel button click and without any user's action (see record attached below)

https://www.loom.com/share/3335196a5d1f40c091d10586898937ee?sid=12c7dabf-ed53-42ad-a3bb-1aeeae4dcfdd

## Expected behavior

- The cancel button should be disabled on object creation, as the create button
- [ ] ~add a confirmation modal before saving the object - from the fact that once created, you can't update the object's names~ let's not do this now

## Related issues

- #5352 
- #5278 

cc: @Bonapara @charlesBochet 

@FellipeMTX feel free to update the issue based on the suggestion I added

**Comment by pacyL2K19** [comment]
I can work on this once the scope is fully sorted out @FelixMalfait

**Comment by Bonapara** [comment]
It looks fine to me to deactivate the field after "create" has been clicked. Regarding the modal, we shouldn't implement it and work soon on the ability to edit names & improve speed.

**Comment by FelixMalfait** [comment]
Hey @pacyL2K19 assigning this to you to disable the "cancel" button as you suggested. Thanks!

Related: https://github.com/twentyhq/twenty/issues/6118 (field creation can be tackled in the same PR)
