### ISSUE TITLE
[workflow][engineering]: Implement a `post-rewrite` hook

### ISSUE THREAD

**Issue by pacyL2K19** [twentyhq/twenty#5677]
## Scope & Context

Everytime before I start working on the project, here are the steps I follow:

- Stash my changes with a `$ git add . ; git stash`
- Fetch the upstream repo with `$ git fetch upstream`
- Rebase with the upstream's main branch with `$ git rebase upstream/main` 
- Install packages, in case the package list updated since the last time I fetched the changes with `$ yarn install`
- Then I run database migration (in case the schema has changed to sync with local db) with `$ npx nx database:migrate twenty-server` 
- Then, I "unstash" my latest stash with `$ git stash apply` 

This whole process can be simplified in a 2 hooks:

- A pre-rebase hook that will do 2 commands, the stash and the fetch upstream(or however we decide to call the original repo)
- A post-rewrite hook after rebasing successfully that will install packages, run migrations and unstash the latest stash
- These 2 hooks will be called anytime a contributor executes a `git fetch <remote_ref>` 

## Technical inputs

We can use husky to add this to the development workflow, I can help work on this if we decide putting some effort - _should not be a big task_

cc: @charlesBochet @FelixMalfait

**Comment by FelixMalfait** [comment]
Hey @pacyL2K19 good point! Initially I really liked the idea but the more I thought about it, I don't like as much the idea of magic happening behind well-known commands. For a smal engineering team of full time employees it'd work very well, but for a community of contributors that most often don't read of much the docs I'm afraid this could cause more confusion/problems to resolve than anything.

Maybe you can do those hooks for yourself either via a bash alias or leveraging [husky locally](https://github.com/typicode/husky/issues/993)?

**Comment by pacyL2K19** [comment]
> Hey @pacyL2K19 good point! Initially I really liked the idea but the more I thought about it, I don't like as much the idea of magic happening behind well-known commands. For a smal engineering team of full time employees it'd work very well, but for a community of contributors that most often don't read of much the docs I'm afraid this could cause more confusion/problems to resolve than anything.
> 
> Maybe you can do those hooks for yourself either via a bash alias or leveraging [husky locally](https://github.com/typicode/husky/issues/993)?

Thanks for your answer @FelixMalfait 
It makes 100% sense
Working on setting it up on my local environment while ignoring then in my commits

This can be closed, I think
