### ISSUE TITLE
Incorrect Icon Width on Menu Items

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5678]
# Current behavior

The icon width `on menu items with an icon on their right edge*` is wrongly fixed to 12.5px, even if 14px is specified in their width

*MenuItem Navigate
*MenuItem Select
*MenuItem Select Avatar
*MenuItem Select Color

![CleanShot 2024-05-30 at 15 02 55](https://github.com/twentyhq/twenty/assets/19412894/ff982aa7-e29e-4f92-8b2f-c28914d5296b)
![CleanShot 2024-05-30 at 15 19 30](https://github.com/twentyhq/twenty/assets/19412894/83e219a7-32b3-450b-969e-8ec043d6d9e1)
# Desired Behavior

1. Their size should be **16px by 16px** (not 14px by 14px).
2. The browser should consider this specified width (and not set 12.5px for unknown reasons)

![image](https://github.com/twentyhq/twenty/assets/19412894/d967caa8-47d1-4bef-bc13-95004cb41294)

**Comment by Sudarsh1010** [comment]
I would like to take this issue

**Comment by Bonapara** [comment]
Sure @Sudarsh1010, thanks for contributing!
