### ISSUE TITLE
Can't `make postgres-on-linux` on arch linux

### ISSUE THREAD

**Issue by AmmarHaddadi** [twentyhq/twenty#5679]
## Bug Description

after running `make postgres-on-linux` I get these errors (highlighted in yellow)

![image](https://github.com/twentyhq/twenty/assets/75220043/60fefe55-bd98-4797-9370-43a81e4dd928)
- ./linux/provision-postgres-linux.sh: line 52: dpkg: command not found
- sh: line 1: lsb_release: command not found
- sh: line 1: /etc/apt/sources.list.d/pgdg.list: No such file or directory
- sudo: apt: command not found
- make[1]: *** [Makefile:11: provision-on-linux] Error 1
- make: *** [Makefile:26: postgres-on-linux] Error 2

## Technical inputs
- the install script is built with only **Ubuntu** in mind? I see `apt` there but **Arch** has `pacman`.

OS: Arch Linux (I had the same problem on NixOS too)

**Comment by FelixMalfait** [comment]
Thanks for the report! Would you be able to raise a PR for this? We'd be happy to merge it obviously. 
I don't think anyone in the core team uses Linux on a distrib that doesn't have apt

**Comment by AmmarHaddadi** [comment]
OK just to let you know I'm working on an AUR package for **Twenty**, I will share it when it's ready

**Comment by FelixMalfait** [comment]
You mean publishing a package? Just want to make sure it's in the same script within our repo as a package would probably be forgotten and not kept up-to-date. Thanks!

**Comment by AmmarHaddadi** [comment]
I've made some decent progress but I don't quite understand **Twenty**'s strucure well and I need help, here are the steps I followed to install on my **Arch linux**, let me know if I missed anything
1. install `postgresql`
2. `git clone https://github.com/twentyhq/twenty.git && cd twenty`
3. download the debian package of `pg-graphql` from github, convert it to an **Arch** package and install it. 
   *I believe this is faster than cloning the whole project and building it locally*
4. follow [Official guide](https://wiki.archlinux.org/title/PostgreSQL#Installation) to initialize **postgres** on **Arch** if `/var/lib/postgres/data` is not found
```
su root -c 'mkdir -p /var/lib/postgres/data; \
chown postgres /var/lib/postgres; \
chown postgres /var/lib/postgres/*; \
su postgres -c "initdb -D /var/lib/postgres/data"'
```
5. starting postgres service with `systemctl start postgresql.service`
6. `cp ./packages/twenty-postgres/init.sql /tmp/init.sql` 
7. `sudo -u postgres psql -f /tmp/init.sql`
8. installing and using node 18
9. `cp ./packages/twenty-front/.env.example ./packages/twenty-front/.env` 
    `cp ./packages/twenty-server/.env.example ./packages/twenty-server/.env`
10. `yarn`
11. `npx nx database:reset twenty-server` 
12. `npx nx start`
13. server starts at `http://localhost:3001`
14. I log in but I get a notification error saying **useFindManyRecords for "views", QueryFailedError** _(I remember seeing some error about graphql in terminal which I couldn't find or reproduce)_



here's is my PKGBUILD so far

```
# Maintainer: Ammar Haddadi <ammarhaddadi@protonmail.com>
pkgname=twenty
pkgver=0.12.0
pkgrel=1
pkgdesc="Modern, powerful, affordable platform to manage your customer relationships"
arch=('x86_64')
url="https://twenty.com"
license=('AGPL-3.0 license')
depends=('postgresql')
makedepends=('git' 'yarn')
source=("git+https://github.com/twentyhq/twenty.git")
sha256sums=('SKIP')

# seetings
PG_GRAPHQL_VERSION=1.5.1
PG_MAIN_VERSION=15
TARGETARCH=amd64

# installing AUR dependencies
build() {
	paru -S --needed aur/debtap || yay -S --needed aur/debtap || exit 1

	# installing pg-graphql
	cd twenty
	mkdir pgql
	cd pgql
	curl -L https://github.com/supabase/pg_graphql/releases/download/v$PG_GRAPHQL_VERSION/pg_graphql-v$PG_GRAPHQL_VERSION-pg$PG_MAIN_VERSION-$TARGETARCH-linux-gnu.deb -o pg_graphql.deb || {
		echo 'Error: Command 1 failed.'
		exit 1
	}
	sudo debtap -uQP pg_graphql.deb
	sudo pacman -U pg-graphql-$PG_GRAPHQL_VERSION-1-x86_64.pkg.tar.zst
	cd ..

	if [ -d "/var/lib/postgres/data" ]; then
		echo "User already has postgres configured"
	else
		# initializing postgres
		su root -c 'mkdir -p /var/lib/postgres/data; \
			 chown postgres /var/lib/postgres; \
			 chown postgres /var/lib/postgres/*;  \
			 su postgres -c "initdb -D /var/lib/postgres/data"'
	fi

	systemctl start postgresql.service
	cp ./packages/twenty-postgres/init.sql /tmp/init.sql
	sudo -u postgres psql -f /tmp/init.sql || echo "Failed to execute init.sql script."

	# Setup environment variables
	cp ./packages/twenty-front/.env.example ./packages/twenty-front/.env
	cp ./packages/twenty-server/.env.example ./packages/twenty-server/.env

	# node and yarn
	source /usr/share/nvm/init-nvm.sh
	nvm install 18
	nvm use 18
	yarn


	#DB setup (pc might freeze here!)
	npx nx database:reset twenty-server

}

check() {
	# any checks here
}

# here need to create shortcut for the app to run
# source /usr/share/nvm/init-nvm.shs # for nvm to work
package() {

}

```

**Comment by AmmarHaddadi** [comment]
ok so when running `npx nx database:reset twenty-server` I get this 
![image](https://github.com/twentyhq/twenty/assets/75220043/b6e7890e-1202-4172-92dd-ddfabb963e9e)
with error a bunch of other ones 
![image](https://github.com/twentyhq/twenty/assets/75220043/d52591a2-867f-4848-96a2-707f71664aad)

but errors are only in the part where the script does these commands:
`nx ts-node-no-deps -- ./scripts/setup-db.ts`
`nx run twenty-server:ts-node-no-deps ./scripts/setup-db.ts`
![image](https://github.com/twentyhq/twenty/assets/75220043/41904490-4998-450b-91ab-3ee9947b393b)
I believe I have missed some steps when installing pg-graphql since I only followed `packages/twenty-postgres/linux/provision-postgres-linux.sh`
II couldn't undesrstand what does the file next to it `build-postgres-linux.sh` does

**Comment by FelixMalfait** [comment]
Yes pg_graphql is mandatory for the app to function and they seem to only provide builds for debian https://github.com/supabase/pg_graphql/releases/tag/v1.5.4 ; so you'd have to rebuild it with cargo probably https://supabase.github.io/pg_graphql/installation/ ?
Sorry I guess we might just not support those linux distros. Maybe run this in a docker instead?

**Comment by AmmarHaddadi** [comment]
Problem is patching `pg_graphql` is really tricky for me
I got told by a dev that you plan to drop `pg_graphql` at some point anyway so I'm just going with Docker

**Comment by FelixMalfait** [comment]
Ok thanks!
