### ISSUE TITLE
Mouse down and drag is selecting records, while file import modal is open

### ISSUE THREAD

**Issue by Muralidhar22** [twentyhq/twenty#5701]
## Bug Description
Mouse down and drag is selecting records in the background, while file import options modal is open in object records table page
## Video description

https://github.com/twentyhq/twenty/assets/33935339/c1ee8ef2-c9da-4083-b6fe-6bfd98e65c6f

## Tested browser
- Chrome

**Comment by Bonapara** [comment]
Thanks for noticing the issue @Muralidhar22!

**Comment by Anand-Krishnan-M-J** [comment]
Hey @Bonapara 
I have raised a PR for this, Could you please assign this issue to me?
Looking forward to make my first of many contributions

**Comment by Bonapara** [comment]
Sure @Anand-Krishnan-M-J, thanks for contributing!

**Comment by Nabhag8848** [comment]
@Bonapara can be closed, already resolved #5716
