### ISSUE TITLE
twenty.com/contributors data inconsistencies

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5715]
# Description

Some contributors have an incorrect number of merged PRs displayed on their profiles.

For instance, @pacyL2K19 merged https://github.com/twentyhq/twenty/pull/5051 three weeks ago, but it is not shown as "Merged" on his profile.

![CleanShot 2024-06-03 at 13 53 05](https://github.com/twentyhq/twenty/assets/19412894/46ee1d73-0852-456f-82f9-fd7acd434c0b)

The data from the comment we make when merging a PR also has some inconsistencies:

![image](https://github.com/twentyhq/twenty/assets/19412894/5b0adf57-99a6-462b-9eb1-d5e16456509a)

**Comment by sagarhedaoo** [comment]
Hi! Can I start working on this? @Bonapara

**Comment by Bonapara** [comment]
Sure @pacyL2K19, thanks for contributing!

**Comment by sagarhedaoo** [comment]
<img width="1424" alt="image" src="https://github.com/twentyhq/twenty/assets/10000167/1d0314bc-a826-452d-b525-85f2d3044744">
Hi! I am not able to see any contributor on localhost, is there any specific package I need to run to see the contributors?

**Comment by Bonapara** [comment]
@FelixMalfait will be able to help!

**Comment by Bonapara** [comment]
@sagarhedaoo, unfortunately, after discussing with the team, I realized we need to handle this issue internally since you won't be able to access the data locally. Perhaps you can take on another `Good First Issue`? Thanks a lot for contributing to Twenty!

**Comment by FelixMalfait** [comment]
@Freebios would you mind looking into this? I think it's a prod issue (cron not running or something like that). But I don't know how to access the logs

**Comment by Freebios** [comment]
@FelixMalfait the job seems to be running correctly, I do run this command every 5mn but I only get a successfull output :/ 
![image](https://github.com/user-attachments/assets/d79c740a-ff4b-495d-a824-a4ae979b6a1c)

Could there be dirty data in database ?

**Comment by FelixMalfait** [comment]
This should probably fix it #7040 ; we'll need to relaunch a full sync after it's merged (--isFullSync flag on the previous command). Could you please do it @Freebios? Thanks!

**Comment by FelixMalfait** [comment]
@thomtrp ran the command. It should be working now. Closing the issue!
