### ISSUE TITLE
Possibility to create a person from the company page

### ISSUE THREAD

**Issue by pacyL2K19** [twentyhq/twenty#5724]
## Scope & Context

To enhance the user experience, we should allow users to create people from the company page with a `New` button below the dropdown of the people suggestion.

## Current behavior

Currently you only have a possibility to pick up a person from the existed list of people, if the person doesn't exist yet, you have to first create him from the people page then get back to the company page

![Screenshot 2024-06-03 at 12 31 44](https://github.com/twentyhq/twenty/assets/61581306/f0b8f842-d07d-4d6d-b196-758a3b4898ef)

## Expected behavior

Adding a `New` button to allow users to create person, then auto selection after the creation succeeded

## Technical inputs

N/A

@FelixMalfait Is this something we can implement to improve the ux on this page? Please have a look

**Comment by FelixMalfait** [comment]
Hey @pacyL2K19 great suggestion which we actually just implemented 😁 https://github.com/twentyhq/twenty/pull/5551
Looking forward to your feedback after you try it
