### ISSUE TITLE
Introduce Delay Options for Tooltip Display

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5727]
# Current Behavior

The tooltips appear without delay on hover.

# Desired Behavior

We want to introduce a delay before displaying the tooltip so they don't pop up as soon as the mouse moves across the screen.

To achieve this, we should introduce a global tooltip component to customize the react-tooltip library with several delay options:

```
no delay: 0ms
short delay: 300ms
medium delay: 500ms
```

**Comment by OHSOHYEON00** [comment]
Hi, also can I work on this? @Bonapara

**Comment by Bonapara** [comment]
Sure @OHSOHYEON00, thanks for contributing!
