### ISSUE TITLE
Side Panel field value alignment

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5730]
# Current Behavior

The field values appear immediately after the labels.

![CleanShot 2024-06-04 at 12 26 56](https://github.com/twentyhq/twenty/assets/19412894/137fcd7d-e725-4798-b037-c1b004504db5)

# Desired Behavior

The field values should be aligned vertically, with the labels having a fixed width.

![CleanShot 2024-06-04 at 12 23 47](https://github.com/twentyhq/twenty/assets/19412894/04301646-65be-4cdb-98fa-cb1c04e816b9)

They should use the same design (and component) that the field panel:

![CleanShot 2024-06-04 at 12 25 29](https://github.com/twentyhq/twenty/assets/19412894/3b70ee88-decf-43ed-8cd8-2fd09e1d2725)

**Comment by marteenaf** [comment]
Hi @Bonapara, if this seems a better fit for a new contributor, I'd like to work on it! Thanks!

**Comment by Bonapara** [comment]
Sure @marteenaf, thanks for contributing!
