### ISSUE TITLE
Adding members/users

### ISSUE THREAD

**Issue by yassine-himite** [twentyhq/twenty#5738]
Hi, A quick question.

is it possible to add multiple members/users on a self-hosted Twenty.
if so where can i do so, because i can't find it anywhere.

thank you

**Comment by FelixMalfait** [comment]
Hi 👋, if you go to Settings > members in the app then you can share an invite link to add members to your existing workspace.
And if you are logged out and signup with an email that isn't recognized, you will be creating a new workspace.
You can disable workspace creation with `IS_SIGN_UP_DISABLED`
