### ISSUE TITLE
Webhooks does not trigger on email automatic events

### ISSUE THREAD

**Issue by deurk** [twentyhq/twenty#5739]
## Bug Description

The initial POST request of a webhook occurs on webhook creation and any manual creation/update/deletion of company/user sends a payload as well but the webhook doesn't get triggered when email import automatically creates a user/company (and possibly in other automated situations).

## Expected behavior

Any event, automated or manual should trigger the webhook POST request.

## Technical inputs

Tested with Docker v0.12.1

**Comment by FelixMalfait** [comment]
I believe this should work now. @bosiraphael please re-open if not

**Comment by charlesBochet** [comment]
No it's not! We need to move the event emission within twenty-orm. We will do it once pg_graphql migration is complete!

**Comment by FelixMalfait** [comment]
Yes sorry you're right, I realized that after sending my message: https://github.com/twentyhq/twenty/issues/4575#issuecomment-2331168171
We can use #4575 to track progress so I'll close this one again
