### ISSUE TITLE
Make the onboarding full screen on mobile.

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5740]
# Current Behavior

We display a mobile onboarding popup, but it doesn't render well.

![CleanShot 2024-06-05 at 10 29 03](https://github.com/twentyhq/twenty/assets/19412894/e50da5c6-41b2-4540-89ed-23120e540e81)

# Desired Behavior

Make the content full-screen on mobile:

![image](https://github.com/twentyhq/twenty/assets/19412894/f76efc71-b736-4ac9-9420-63c0d10b10d7)

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=32468-360264&t=XbbQ79dyfHCjEchG-11

**Comment by sagarhedaoo** [comment]
I can work on this as well! @Bonapara

**Comment by Bonapara** [comment]
Sure @sagarhedaoo, thanks for contributing (again)!

**Comment by RobertoSimonini1** [comment]
I would like to work on this issue, may I? @Bonapara

**Comment by Bonapara** [comment]
Hi @RobertoSimonini1, thanks! I'll let you sync with @sagarhedaoo, but I believe he's already on it. :)

**Comment by RobertoSimonini1** [comment]
@Bonapara yes, I didn't know he was already working on it, sorry :)

**Comment by Bonapara** [comment]
Hi @sagarhedaoo! Are you still on it?

**Comment by dhruvdabhi101** [comment]
If no one is working on it then I would love to take it up.

**Comment by Bonapara** [comment]
Sure @dhruvdabhi101, thanks for contributing!

**Comment by ehconitin** [comment]
Hey @Bonapara 
I need a clarification.
currently `MOBILE_VIEWPORT` is 768px.
which means mobile components are rendered when the screen width is below 768px.
So do you want this fullscreen signinup and pricing  mobile screen to be rendered for screens below 768px?
I ask this because the figma u shared has a narrow viewport.

**Comment by ehconitin** [comment]
@Bonapara 

Check [PR 6386](https://github.com/twentyhq/twenty/pull/6386)

**Comment by mittalsam98** [comment]
Hey @Bonapara it seems @dhruvdabhi101 is not working on this since there is no update from him on this. can I pick this up?

**Comment by Bonapara** [comment]
@ehconitin you plan to fix this issue in https://github.com/twentyhq/twenty/pull/6386 right?

**Comment by ehconitin** [comment]
@Bonapara Yes, I am.  I have raised the [PR 6386](https://github.com/twentyhq/twenty/pull/6386) regarding the same 
Could you please check.

**Comment by Bonapara** [comment]
Not reviewing PR myself @ehconitin ;) Thanks again for your contribution!

**Comment by ehconitin** [comment]
@FelixMalfait This issue can be closed right? #6386 closes thi!

**Comment by FelixMalfait** [comment]
Indeed thanks!
