### ISSUE TITLE
Sort Button Size Too Small on Mobile

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5743]
# Current behavior

The `Sort` button is smaller than expected on mobile

![IMG_E3E14B927C7F-1](https://github.com/twentyhq/twenty/assets/19412894/7722f3f6-6111-4872-8841-0a3bf14203f3)

# Desired Behavior

The `Sort` button should have the same size as `Filter` and `Options`. It should use the same component that filter and options button

**Comment by sagarhedaoo** [comment]
Can I start working on this? @Bonapara

**Comment by Bonapara** [comment]
Sure @sagarhedaoo, thanks for contributing!
