### ISSUE TITLE
Bottom Bar Not Visible on Mobile Without Scrolling

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5744]
# Current Behavior

The bottom bar is not directly visible on mobile. To see it, I have to scroll the page by placing my finger at the extreme edge of the screen.

https://github.com/twentyhq/twenty/assets/19412894/f03234f6-a580-4ffb-a473-282773cda1b7

# Desired Behavior

The bottom bar should always be visible. Use `LVH` or other modern [CSS viewport units](https://blog.logrocket.com/improving-mobile-design-latest-css-viewport-units/) to account for the browser's collapsing navbar.

**Comment by OHSOHYEON00** [comment]
Hi, Can I work on this? @Bonapara

**Comment by Bonapara** [comment]
Sure @OHSOHYEON00, thanks for contributing!

**Comment by Bonapara** [comment]
Hi @OHSOHYEON00, are you still working on this? I'm unassigning you, but let me know if you still want to handle it!

**Comment by dhruvdabhi101** [comment]
Hey, If no one is working, then can you please assign this issue? i might want to give it a try. Thanks : )

**Comment by Bonapara** [comment]
Sure @dhruvdabhi101, thanks for contributing!
