### ISSUE TITLE
Disable Horizontal Scrolling on Mobile Record Page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5745]
# Current Behavior

There is an unwanted ability to horizontally scroll the record page on mobile.

https://github.com/twentyhq/twenty/assets/19412894/a6445078-1fef-4351-863d-020a7aa0b06e

# Desired Behavior

The width should be set to 100vw, and no horizontal scrolling should be possible. Only the tab bar should scroll horizontally.

**Comment by OHSOHYEON00** [comment]
Hi, I would like to work on this. If there's problem please let me know :)

**Comment by prashant2599py** [comment]
Can I start working on this, Can you assign it to me. @Bonapara

**Comment by Bonapara** [comment]
Sure @prashant2599py, thanks for contributing!
