### ISSUE TITLE
REST API  error with timelineActivities

### ISSUE THREAD

**Issue by ingego** [twentyhq/twenty#5752]
Hi, some problem with restAPI^ try this curl 
```
curl --request POST \
  --url 'https://api-demo.twenty.com/rest/people?depth=1' \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMTIxMjEyMS0yNmExLTRkODktYjQ2YS0wNDI0NTViODM3N2YiLCJpYXQiOjE3MTc1OTUwODUsImV4cCI6NDg3MTE5NTA4NCwianRpIjoiYzg5NjA0OTQtODIyNC00NDJlLWIxNTAtYjU1MjAwZjZmNDYzIn0.cW3c4dDy-9j_ilvJT1Rm3KqolbnTC8yOBq85Hw90P7c' \
  --header 'Content-Type: application/json' \
  --data '{
"name":{
"firstName":"anaconda"
}, 
"timelineActivities":[{}]
}
```

and get error ->
```
{
  "statusCode": 400,
  "message": "Variable \"$data\" got invalid value { position: \"first\", name: { firstName: \"anaconda\" }, timelineActivities: [{}] }; Field \"timelineActivities\" is not defined by type \"PersonCreateInput\".",
  "error": "Bad Request"
}
```

**Comment by anbatista-com** [comment]
in my setup I'm getting similar error:

{
  "statusCode": 400,
  "message": "Variable \"$data\" got invalid value { position: \"first\", name: { firstName: \"Alexandre\", lastName: \"Nunes Batista\" }, phone: \"5511934165086\", zapUser: [{ remoteJid: \"5511934165086@s.whatsapp.net\", name: \"Alexandre\", voice: \"nova\" }] }; Field \"zapUser\" is not defined by type \"PersonCreateInput\".",
  "error": "Bad Request"
}

**Comment by ingego** [comment]
> in my setup I'm getting similar error:
> 
> { "statusCode": 400, "message": "Variable "$data" got invalid value { position: "first", name: { firstName: "Alexandre", lastName: "Nunes Batista" }, phone: "5511934165086", zapUser: [{ remoteJid: "[5511934165086@s.whatsapp.net](mailto:5511934165086@s.whatsapp.net)", name: "Alexandre", voice: "nova" }] }; Field "zapUser" is not defined by type "PersonCreateInput".", "error": "Bad Request" }

@anbatista-com  try GraphQl, this REST is broken, ~40% api is not working

**Comment by FelixMalfait** [comment]
Hey sorry for this. This was an issue from the API's documentation. We'll improve it this week, make sure they are clear examples and everything that appears in there is actually correct.
In the meantime, the GraphQL API is very stable yes.
