### ISSUE TITLE
Favorite folders and new type of favorites

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5755]
We want to introduce the ability to add Notes, Tasks, Records, and Views as favorites.
# Feature Overview

https://github.com/twentyhq/twenty/assets/19412894/cb372cb0-b075-4987-9798-46ddd7aadc22

# Global behavior

Clicking a folder name should expand or collapse the folder with a 100ms animation. The task icon should be clickable to mark a task as done.

# Create a folder

Users should be able to create a new favorite folder directly from the navigation bar or the favorite menu:
### Navigation
![CleanShot 2024-06-05 at 17 24 10](https://github.com/twentyhq/twenty/assets/19412894/2551013d-41fd-4766-b649-c5d9cfd9bb08)

### Favorite menu
![CleanShot 2024-06-05 at 17 24 58](https://github.com/twentyhq/twenty/assets/19412894/9f697e0b-b6f4-4e7e-ab3e-829811b26b49)

# Edit a folder

By clicking the menu at the right edge of the folder navigation item, you will either be able to rename the folder, or to delete the folder with its whole content

![CleanShot 2024-06-05 at 17 26 00](https://github.com/twentyhq/twenty/assets/19412894/a3c2c37d-15ba-413e-a1c8-78e746bd39d5)

# Add as Favorite

To add a Record or View as favorite, just press the `heart` button at the top right edge of the screen:

![CleanShot 2024-06-05 at 17 37 17](https://github.com/twentyhq/twenty/assets/19412894/81645beb-7d5d-4412-8950-c207f884bd1d)

To add a  Note or a Task, press the similar button to the top right edge of the side-panel:

![image](https://github.com/twentyhq/twenty/assets/19412894/6114dae4-2884-46a2-8a19-08af298eaa8a)

**Important behavior:** By default, a new favorite is added to the "No folder" section, which acts as a "default folder." It will be displayed at the root of the Favorites section in the navigation menu. When choosing a specific folder, the favorite should be moved out of the "No folder." However, the user should still be able to add the favorite back to the "No folder" section. See the feature overview video for better illustration.

# Remove a Favorite

Either deselect a checkbox on the favorite top right menu:

![CleanShot 2024-06-05 at 17 30 11](https://github.com/twentyhq/twenty/assets/19412894/b0fcd69a-0efd-42c4-9e31-30ed2bd9b9dc)

Or click the `Unstar` light icon button on any favorite in the navigation menu

![CleanShot 2024-06-05 at 17 31 15](https://github.com/twentyhq/twenty/assets/19412894/f4a58aa8-2d19-4859-a46f-fa7b6dab581c)

# Breadcrumb

The line going to the active navigation item should be darker

![CleanShot 2024-06-05 at 17 43 50](https://github.com/twentyhq/twenty/assets/19412894/b2bc3eab-8956-4dcf-af55-4ff7ebc1f163)

vs

![CleanShot 2024-06-05 at 17 44 24](https://github.com/twentyhq/twenty/assets/19412894/57456ae6-ed2c-4f36-8702-2c174996f8e5)

# Figma

### Componenents

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=115-6252&t=D4lb89ry3MvwwMqw-11

### Prototype

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=32481-369067&t=D4lb89ry3MvwwMqw-11

**Comment by pacyL2K19** [comment]
@Bonapara isn't good to break this down into sub tasks?
I can work on some sub-task if we decide to create some

cc: @FelixMalfait

**Comment by Bonapara** [comment]
Hi @pacyL2K19! We plan to handle this internally for convenience :)

**Comment by pacyL2K19** [comment]
> Hi @pacyL2K19! We plan to handle this internally for convenience :)

Got it, thanks @Bonapara 
I will pick another one from the queue

**Comment by Bonapara** [comment]
Hi @shyamsundertard the core team will handle this one. Thanks for contributing!
