### ISSUE TITLE
Migrate Domain Field to the new Link Field Type

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5759]
# Current Behavior

The domain field on the company object uses a "Text" field type.

![CleanShot 2024-06-06 at 10 26 52](https://github.com/twentyhq/twenty/assets/19412894/ff9eaf6b-812b-4a3b-add2-c925f45a822d)

# Desired Behavior

We want to migrate the domain field to the newly introduced linked field type, allowing users to specify multiple values (several domains).

![CleanShot 2024-06-06 at 10 27 14](https://github.com/twentyhq/twenty/assets/19412894/969c39e6-bda2-4f13-9606-f536846506e0)

We should adapt the email syncing logic to account for companies having different domains attached. We should sync emails from any matching domain name (e.g., tim@apple.com or tim@apple.dev).

We should keep the custom logic for the domain field, such as fetching the favicon.

**Comment by pacyL2K19** [comment]
I can work on this next @Bonapara

**Comment by Bonapara** [comment]
Sure @pacyL2K19, thanks for contributing!

**Comment by pacyL2K19** [comment]
Starting work on this @Bonapara 
Please assign it to me

**Comment by Bonapara** [comment]
Done! Thanks @pacyL2K19

**Comment by Bonapara** [comment]
@ijreilly is it related to what you're working on?

**Comment by ijreilly** [comment]
vision: add settings on field types to be able to add business logic executed at save.
e.g.: "isDomain" setting to remove protocol
