### ISSUE TITLE
Change Filtered Index Empty State Message

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5761]
# Current Behavior

The empty state of a filtered index displays "Add your first XXX."

![image](https://github.com/twentyhq/twenty/assets/19412894/7ee888fa-28a5-4c52-ba55-26ddec29664e)

# Desired Behavior

It should display "No XXX found" if we know that some companies exist in the database instead.

![image](https://github.com/twentyhq/twenty/assets/19412894/71bc8b39-3c8e-4fc9-accc-0c33b02ee7f7)

**Comment by FelixMalfait** [comment]
Duplicate of https://github.com/twentyhq/twenty/issues/3877 but closing 3877 to keep this fresh issue

**Comment by Weiko** [comment]
This one seems to have already been resolved in https://github.com/twentyhq/twenty/pull/5838
