### ISSUE TITLE
Ability to sort on setting tables 

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5772]
We should be able to sort tables in settings.

Mostly SettingsObjects, SettingsObjectDetail, but also potentially other ones (e.g. webhooks/api keys)

<img width="535" alt="Screenshot 2024-06-07 at 13 56 47" src="https://github.com/twentyhq/twenty/assets/6399865/c1ff6260-3f80-476f-84bf-4290d58fa8b6">

<img width="546" alt="Screenshot 2024-06-07 at 13 58 59" src="https://github.com/twentyhq/twenty/assets/6399865/d4f726e6-bf1f-4545-8f14-d03eaa4542d2">

We want to do this in a clean and generic way. Avoid having too much duplicated code :)

CC @Bonapara fyi if you want to add arrow up/down keys on table header upon click?

**Comment by Bonapara** [comment]
Sorting should always be applied by default. Clicking on a header should change the sorting direction. Clicking on a different header should cancel and replace the previous sorting. The arrow should be on the right for text, relation, and tag headers, and on the left for number headers.

https://github.com/twentyhq/twenty/assets/19412894/0c29caa3-c214-4e02-a2db-ffaba8699e58

![image](https://github.com/twentyhq/twenty/assets/19412894/0e17c9ac-23a1-4c8c-b522-26cbc3cafa75)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=11519-270312&t=CaT8OmWYVmqhuf0a-11

**Comment by FelixMalfait** [comment]
Thanks! Adding "good first issue" tag as it doesn't require much context on the overall project but it needs to be someone experienced to do this well

**Comment by Anand-Krishnan-M-J** [comment]
Hey @Bonapara 
Could you please assign this issue to me?
I would like to work on this.

**Comment by FelixMalfait** [comment]
Hey @Anand-Krishnan-M-J thanks 🙏

**Comment by Bonapara** [comment]
Hi @Anand-Krishnan-M-J, thanks for contributing & your PR draft! I was wondering, are you still on it?

**Comment by Anand-Krishnan-M-J** [comment]
@Bonapara 

Yeah, I am still on it. Would it be okay if I update the PR by July 04?
I have a few doubts in some areas, especially as to why we would have to keep the key in the specific way as mentioned in the comments. Will add them as comments

**Comment by Bonapara** [comment]
@Anand-Krishnan-M-J Sure! Thanks a lot for working on it 😊

**Comment by Anand-Krishnan-M-J** [comment]
Updated PR: https://github.com/twentyhq/twenty/pull/5787
