### ISSUE TITLE
Overflow issue on tables

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5774]
# Bug description

Resizing a table and then scrolling it horizontally causes an overflow issue.

https://github.com/twentyhq/twenty/assets/19412894/a7da9610-0cbf-457a-aa59-a60b5d11c652

**Comment by adilkadivala** [comment]
Hey,  I want to contribute on this project, and I forked, but can't setup properly,  I have read carefully CONTRIBUTING.md,  and also https://docs.twenty.com/start/local-setup,  ooof, but I can't,  may I get help ??

**Comment by Bonapara** [comment]
Sure @adilkadivala, the best way to get some help is on our Discord: https://discord.com/invite/cx5n4Jzs57

**Comment by RobertoSimonini1** [comment]
can I work on this issue? @Bonapara

**Comment by Bonapara** [comment]
Sure @RobertoSimonini1, thanks for contributing!

**Comment by thomtrp** [comment]
@Bonapara can you still see the issue? I cannot reproduce

**Comment by Bonapara** [comment]
Cannot reproduce too
