### ISSUE TITLE
Text Field Overflow Beyond Cell Limits in UI

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5775]
# Current Behavior

Opening a text field with a lot of content causes the content to overflow beyond the cell's limits.

https://github.com/twentyhq/twenty/assets/19412894/fcfebbab-e30a-4c41-80bd-772bbe992e89

# Desired Behavior

The cell should extend up to a maximum of 400px without overflowing the bottom of the page ( And become scrollable if the content doesn't fit).

![image](https://github.com/twentyhq/twenty/assets/19412894/06253537-df2c-40f6-9a3e-573bc274c17a)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=32671-75159&t=CaT8OmWYVmqhuf0a-11

**Comment by ijayhub** [comment]
Is it fixed if not will like to work on this

**Comment by Bonapara** [comment]
Do you want to pick this one as well @ijayhub?

**Comment by ijayhub** [comment]
yes when am through with the current am assigned to #5660
thanks

**Comment by siiddhantt** [comment]
hi @Bonapara added a fix for this issue, do let me know if it needs changes. thanks!
