### ISSUE TITLE
Misleading Rest Api docs

### ISSUE THREAD

**Issue by brendanlaschke** [twentyhq/twenty#5778]
## Bug Description
Create Object shows relations as attributes.

For example companies include the opportunities key in the post request description. But you can't create an opportunity via this request. 

<img width="1093" alt="Bildschirmfoto 2024-06-07 um 22 45 51" src="https://github.com/twentyhq/twenty/assets/48770548/d9109f63-f9ee-4f1f-9530-f9cec7030e4e">

See: https://discord.com/channels/1130383047699738754/1248725608457048136/1248725608457048136

## Expected behavior

Either allow creating related objects (I don't think it is possible at the moment or feasible at all) or remove the attributes from the docs ...

**Comment by FelixMalfait** [comment]
Yes good point! We should just remove it from the doc 👍
So in the scren we should keep `accountOwnerId` but remove `accountOwner`, `activityTargets`, `favorites`, `opportunities`, `people`
