### ISSUE TITLE
Ability to prevent new workspace creation

### ISSUE THREAD

**Issue by 23sergej** [twentyhq/twenty#5779]
## Scope & Context

Is it possible to disable new workspace creation?

**Example:** 
I've launched app using docker on my local machine. Everything works fine, I can open `http://localhost:3000` and it automatically redirects me to the `http://localhost:3000/welcome`.

I create a workspace with my email.

Then I logout and see `http://localhost:3000/welcome` again.

But if I type **new email** address I'm able to create another workspace.

## Current behavior

At the moment anybody, who knows public URL can create workspaces.

## Expected behavior

It would be nice to have `.env` setting that will disable or limit new workspace creation.

Or maybe, there is an option to disable redirect to the `/create/workspace` route if user not found?

**Comment by FelixMalfait** [comment]
Hey @23sergej this is already possible :)

Set `IS_SIGN_UP_DISABLED` in your .env.

Closing but let me know if I missunderstood

**Comment by 23sergej** [comment]
Thank you @FelixMalfait 

I've missed it somehow when reading docs :slightly_smiling_face: 

Now everything works perfect!
