### ISSUE TITLE
If CSV imports returns a 400 then we should return to the previous step 

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5790]
Currently if the CSV import fails (e.g. send a wrong value to a SELECT field), we optimistic-render the result which still appear in the table even though the import failed.
Instead, we should stay in the import modal and give explicit feedback on what needs to be fixed.

**Comment by FelixMalfait** [comment]
@ad-elias will check if this is still relevant

**Comment by eliasylonen** [comment]
Not able to reproduce this, import seems to handle errors well.
