### ISSUE TITLE
Field search in csv import column matching step is not good

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5792]
When importing a CSV, the second step is to match columns with the file's header.
For each header item, we show a dropdown with our model fields which has a search bar.
But that search is very inefficient, often it doesn't even return exact matches.

**Comment by PKNaveen** [comment]
Hi @FelixMalfait  could you share some columns that your not able to find or where you they dont share exact columns on searching? I have tried recreating this with some csv files. I dont seem to find this issue.

Each csv file you import suppose you import it into the companies dashboard you only select the following headers:

- account owner
- address
- arr
- domain name
- employees
- ICP
- LinkedIn
- name
- X Link

**Comment by FelixMalfait** [comment]
Hey @PKNaveen thanks for the ping and sorry I left this open :(
You're right, this is already fixed, here's the quick fix I did https://github.com/twentyhq/twenty/pull/6045/files - I forgot that I had created an issue for it
