### ISSUE TITLE
Support multi-select in CSV import

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5793]
Followup of #5471, we should also support multi-select fields with comma separated values (or even a dropdown select to indicate what separator has been used). The default separator should be the same we use for exports so that people can export/re-import and it stays idempotent.

**Comment by thinkbig1979** [comment]
Just curious whether this is on the roadmap. As it stands the app cannot import its own exported CSV files due to this issue. Its also blocking me from moving my current CRM data into Twenty, as I have quite a few mulit select fields in there. This is a shame, as I'd love to start using the app. 🙂

**Comment by FelixMalfait** [comment]
/oss.gg award 1200

**Comment by FelixMalfait** [comment]
/oss.gg 1200

**Comment by FelixMalfait** [comment]
@thinkbig1979 sorry about that, I agree we should fix it. So much to do 😅

**Comment by thinkbig1979** [comment]
> @thinkbig1979 sorry about that, I agree we should fix it. So much to do 😅

No worries! Really happy to see this being picked up.
Thanks all!
