### ISSUE TITLE
Calendar Tile Fonts Underlined in Account Settings

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5797]
# Bug description

In the Account Settings, the `Calendar tile` fonts are underlined when they shouldn't be:

![CleanShot 2024-06-10 at 10 39 30](https://github.com/twentyhq/twenty/assets/19412894/ef9e25d1-2795-4e91-a6a4-5235d07141f9)

**Comment by pranay-0512** [comment]
I can work on this issue!

**Comment by Bonapara** [comment]
Sure @pranay-0512, thanks for contributing!

**Comment by siiddhantt** [comment]
Hi 👋 @Bonapara Added a fix for it
