### ISSUE TITLE
Emails and Calendar Events Not Syncing

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5808]
# Description

Even after disconnecting and reconnecting my mailbox, my emails and calendar events still won't sync with Twenty.

![CleanShot 2024-06-10 at 22 30 58@2x](https://github.com/twentyhq/twenty/assets/19412894/7b6816ce-1d6a-4e87-a303-fdb20b000bff)

![CleanShot 2024-06-10 at 22 32 23@2x](https://github.com/twentyhq/twenty/assets/19412894/488cbfd7-9057-4387-902f-36bf82dddf04)

**Comment by Bonapara** [comment]
Are we good with this one @bosiraphael? @Weiko?

**Comment by Weiko** [comment]
@Bonapara I would double check but @charlesBochet and @bosiraphael refactored a lot of code during the last few weeks which should have improved stability. Can you retry on your side?
