### ISSUE TITLE
Adding one more Column in view, last column disappears

### ISSUE THREAD

**Issue by markusthiel** [twentyhq/twenty#5822]
Before the last version, there were issues with columns being displayed twice. Now it seems the error has been fixed, but I can only add one additional column. When I select an additional column, the first column disappears.

**Comment by rob-luke** [comment]
Interesting that you don’t get repeat columns any more, I still get columns appearing twice (or more). I tested this on v0.12.2 and main today. Did you do anything beyond upgrading to fix it? @markusthiel

**Comment by PeterBaker0** [comment]
I am seeing duplicated columns still (I currently have 10 copies of the same column :/ )

**Comment by markusthiel** [comment]
Did nothing else. However, I reinstalled it once and then duplicated columns are gone but instead this happened.

**Comment by FelixMalfait** [comment]
Sorry we didn't reply to this. I'm pretty sure it's been fixed since I haven't seen that bug since then. Thanks for the report!
