### ISSUE TITLE
Add 8px Left Margin to Tasks Page Tab Group

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5827]
# Current behavior

The left tab (or the tab group) on the tasks page index doesn't have a left margin/padding

![CleanShot 2024-06-11 at 19 33 10](https://github.com/twentyhq/twenty/assets/19412894/e354245a-12b8-4980-ade8-a2a11b115832)

# Desired Behavior

The left margin/padding should be 8px

![CleanShot 2024-06-11 at 19 34 47](https://github.com/twentyhq/twenty/assets/19412894/2561ed4a-3cb8-4245-98bd-96011ba3b7ad)

**Comment by ramnaresh8** [comment]
On it, please assign it to me while I'm setting up this
