### ISSUE TITLE
Blank Screen after docker compose up -d, graphql error

### ISSUE THREAD

**Issue by technicalnoodles** [twentyhq/twenty#5830]
## Bug Description

I am getting a blank screen of twenty after all the containers come up.

The only error I see in the console is this graphql error, along with failed fetches to the graphql api.

<img width="630" alt="image" src="https://github.com/twentyhq/twenty/assets/10239022/399a8891-cf70-4cf9-841a-52726ae6a02f">

## Expected behavior
I was expecting to see something similar to login of the demo

## Technical inputs
I do have the server url set to http://0.0.0.0:3000.
I also tried it with the front url set to http://0.0.0.0:3000

I did the same using localhost.

**Comment by technicalnoodles** [comment]
I forgot to mention, I have turned off the firewall on the ubuntu server too

**Comment by hoeoek** [comment]
I have the same problem

**Comment by nickwild-999** [comment]
Not sure it is related, but I have the same error when running on Digital Ocean drplet (although works well locally).

In addition I have this too
```
http://localhost:3000/graphql' from origin 'http://xxx.xx.xxx.xx:3000' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `local`.
```

**Comment by nickwild-999** [comment]
Has anybody had any success fixing this - on another installation I too have the same ERR_CONNECTION_REFUSED error

**Comment by nickwild-999** [comment]
See here for the solution that fixed my problem
https://github.com/twentyhq/twenty/issues/5184

**Comment by FelixMalfait** [comment]
Sorry we couldn't help. I'm closing this, leaving https://github.com/twentyhq/twenty/issues/5184 open - we'll try to better better document/simplify the install process
