### ISSUE TITLE
404 errors in Extending docs section

### ISSUE THREAD

**Issue by tgehrs** [twentyhq/twenty#5845]
## 404 errors in documentation

The icons in each of these two pages lead to 404 errors, the links on the left navbar do not. It appears to be the result of relative linking, but I can't figure out what needs to be changed for a PR

https://twenty.com/developers/section/graphql-apis
https://twenty.com/developers/section/rest-apis

**Example:** 

Core tile links to https://twenty.com/developers/section/graphql-apis/graphql/core

<img width="1228" alt="Screenshot 2024-06-12 at 2 26 37 PM" src="https://github.com/twentyhq/twenty/assets/9788919/12117de4-9f52-42d8-9220-1e6a4ae764c9">
<img width="1261" alt="Screenshot 2024-06-12 at 2 29 46 PM" src="https://github.com/twentyhq/twenty/assets/9788919/b9dbf4e6-0384-47d6-9133-1621df768365">

## Expected behavior

Should go to this page and https://twenty.com/developers/graphql/core not go to 404

Essentially, this change is required for the links. I am unfamiliar with your framework and not sure what to change for a PR 

https://twenty.com/developers/ ~~section/graphql-apis/~~ graphql/core

**Comment by FelixMalfait** [comment]
It seems this has been fixed! Thanks
