### ISSUE TITLE
Not able to add relation between custom object and standard object

### ISSUE THREAD

**Issue by Dharmil1225** [twentyhq/twenty#5847]
Risk is a custom model I have created. 
I am trying to create a relation field called "Account" which will map to existing model "Company" in many to one relationship. Meaning A Company (which is also called Account) can have multiple Risks associated with it. 

But the Save buttons remains disabled.  

![image png](https://github.com/twentyhq/twenty/assets/97499003/6d7db25a-f414-4ef5-b0df-16caee22f6e3)

**Comment by FelixMalfait** [comment]
Mmh very strange. I haven't been able to reproduce this. It should be possible to create that kind of relationship. 
I'm sorry for the late reply, it was a though month. Would you mind letting us know if there's an error in your console / if you're still able to reproduce the issue? If you can provide that I will re-open the issue
