### ISSUE TITLE
Impossible to filter Relational ID on "Find Many XXX" REST API

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5862]
# Description

Currently, filtering a REST "Find Many XXX" endpoint by a relational ID doesn't work, resulting in an empty array.

For example, it's impossible to filter by workspaceId[eq]:"xxx" or workspaceId[is]:"xxx".

<img width="544" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/5c869449-8520-4528-aced-2d4936fc2a4c">

**Comment by martmull** [comment]
Think there is no issue on that, we tested with workspaceId `78e46b47-dc0b-4967-9607-a9318788f47` that works in the app because we use a filter `ilike`, but the real id is `78e46b47-dc0b-4967-9607-a9318788f47f` (missing `f` at the end)
Wait for @Bonapara confirmation to close that issue
