### ISSUE TITLE
Inconsistent Task Naming in Timeline

### ISSUE THREAD

**Issue by tim-x-y-z** [twentyhq/twenty#5864]
## Bug Description
**Issue**: Task names appear inconsistently in the timeline, leading to confusion.

**Description**: Task names in the timeline do not match the detailed task view, making it unclear that they refer to the same task. This inconsistency can cause confusion for users trying to track updates and manage tasks effectively.

**Steps to Reproduce:**

1. Create a task and assign it to a company.
2. Update the task name.
3. Check the timeline and detailed task view for consistency.

<img width="1207" alt="Screenshot 2024-06-14 at 08 57 15" src="https://github.com/twentyhq/twenty/assets/86600518/285bda24-c037-427b-8b2b-11b40cb39753">

## Expected behavior

Task names should be consistent across all views.

**Comment by FelixMalfait** [comment]
Thanks for the report. This is a known compromise, as we decided to compute the timeline asynchronously for performance reasons. I agree we should probably updated the name retroactively in the future
