### ISSUE TITLE
render.yaml using deprecated docker images

### ISSUE THREAD

**Issue by nickwild-999** [twentyhq/twenty#5874]
## Bug Description
When clicking on the one click install to render it uses lt deprecated Docker Images

## Expected behavior
It should use upto date images

**Comment by FelixMalfait** [comment]
I think we should deprecate render/railway for now. We don't have time to keep it up-to-date as we are still focused on bringing Twenty to parity with the best CRMs. We will focus on easy self-hosting options once we get out of beta mode. Right now the recommended option to self-host should be the docker-compose

**Comment by FelixMalfait** [comment]
https://github.com/twentyhq/twenty/pull/6167
