### ISSUE TITLE
Ex: Add  support for THB Currency (Thai Baht)

### ISSUE THREAD

**Issue by Boomgeek** [twentyhq/twenty#5876]
### Feature Request: Support for THB Currency

**Description:**
I would like to request the addition of support for the Thai Baht (THB) currency. This feature will be beneficial for users in Thailand and those who deal with transactions involving THB.

**Reference:**
For more information about the Thai Baht, please refer to the [Wikipedia page on Thai Baht](https://en.wikipedia.org/wiki/Thai_baht).

Thank you for considering this request.

**Comment by Ymirke** [comment]
@Boomgeek made a pull request for this issue.

This is how it looks like:

https://github.com/twentyhq/twenty/assets/36711026/ff4b7501-7427-439b-9024-d6661476ae21
