### ISSUE TITLE
Many to many Relationships and exporting comprehensively

### ISSUE THREAD

**Issue by markusthiel** [twentyhq/twenty#5878]
I think many-to-many relationships would make sense. I would like to create a new object in which I list various topics. I want to assign these topics to companies so that on one hand, I can see which topics the company covers, potentially several. On the other hand, I also want to be able to see in the "Topics" object which companies are assigned. Additionally, it should be possible to export everything comprehensively.

The export function should (this is a second topic) also work comprehensively for companies and people. For example, so that you can export a list with companies and the assigned people along with their contact information and roles.

Couldn't find that. But You guys are on an amazing way and i wish i would be able to assist you, but unfortunately, I am not a programmer.

**Comment by FelixMalfait** [comment]
Thanks a lot for this feedback and sorry for the late reply. We improved the export function a bit to include IDs now. 

I agree many-to-many relationships would be amazing to have. I will close this issue since it's tracked here: https://github.com/twentyhq/twenty/issues/4986
