### ISSUE TITLE
Note to task

### ISSUE THREAD

**Issue by vasnt** [twentyhq/twenty#5879]
Is there any way to convert item from notes into task?

**Comment by FelixMalfait** [comment]
It's the same object in the background ("activity"), just a different value in type column. So technically it'd be easy. But that's not possible through the UI yet.
CC @Bonapara to decide next steps (closing or exposing field)

**Comment by Bonapara** [comment]
![image](https://github.com/twentyhq/twenty/assets/19412894/66b52531-10c6-4af2-bf65-9d002d366b6e)

@vasnt Sure, great idea. We could offer it in a menu next to the trash.

**Comment by vasnt** [comment]
or near to 6 dots/Plus sign? so it(task) can be applied to concerned bulleted item.

**Comment by Bonapara** [comment]
Oh, that's a great idea too, but it's too early to implement for the core team. We need to focus on more important features for now!
