### ISSUE TITLE
Make sidebar items taller

### ISSUE THREAD

**Issue by Ymirke** [twentyhq/twenty#5882]
## Scope & Context

I wish to increase their height of the sidebar menu items, so that they're more clickable.

## Current behavior

A clear and concise description of what the current behavior is.
Please also add **screenshots** of the existing application.

Currently the sidebar items are quite thin. I spend some milliseconds making sure I'm aiming the mouse precisely to hit them.

The "People" item which is highlighted here is about one cursor height on my mac. I would like it to be 1.5x or 2x.
<img width="239" alt="Screenshot 2024-06-16 at 01 36 45" src="https://github.com/twentyhq/twenty/assets/36711026/13bed1b7-8c97-49fe-ad24-0cce7f0fdb5f">

## Expected behavior
Here I have increased the padding through the browser from 4px to 12px. This makes it easier to hit the buttons.

<img width="234" alt="Screenshot 2024-06-16 at 01 42 23" src="https://github.com/twentyhq/twenty/assets/36711026/449481b6-a80d-407b-9a21-119f15c0efac">

It does look a bit unpolished, as the icons and text should likely be increased to match.

Here is a quick example video to demonstrate:

https://github.com/twentyhq/twenty/assets/36711026/1a612fa1-4054-4dff-98e2-1d6ead5c5ee4

## Technical inputs
None, might author a PR for this as it's driving me a bit crazy 😅

**Comment by FelixMalfait** [comment]
Thanks for the feedback! I like it this way but it's true that Notion is slightly bigger (20 + 5x2 while we are 16 + 4x2)
CC @Bonapara who leads design, can decide if we should close this or take action!

**Comment by Bonapara** [comment]
Great suggestion, @Ymirke, thanks! I created a new "good first issue" to provide more visibility on how to implement it: https://github.com/twentyhq/twenty/issues/5902
