### ISSUE TITLE
Phone contacts Management via Twenty

### ISSUE THREAD

**Issue by vasnt** [twentyhq/twenty#5884]
Just set up Twenty (after some hiccups), It is awesome product. 
I would like to centralise all tabular data in/via twenty.

Is there any way to manage all phone contacts/numbers etc. in twenty table?

```[tasklist]
### Tasks
- [ ] Is there any way to manage all phone contacts/numbers etc. in twenty table? if real-time/bidirectional possible, then it would be great.
- [ ] Is it possible to store messages/sms into Twenty table/database/notes
```

**Comment by FelixMalfait** [comment]
You could create dedicated objects to store the message data but that's not ideal. Or we've designed "message" and "messageChannel" to be agnostic of the underlying communication type and support that kind of use-case but we don't really have an example of such implementation yet so it would probably not work well and need a few adjustments. That's something we should tackle this year hopefully but not very short-term. Closing this for now but please feel free to re-open a discussion (e.g. with a specific message integration type such as WhatsApp)
