### ISSUE TITLE
Dynamic Filtering while typing

### ISSUE THREAD

**Issue by vasnt** [twentyhq/twenty#5888]
<img width="152" alt="image" src="https://github.com/twentyhq/twenty/assets/117589240/ec1521bd-8d5f-4980-bf4c-ba33ece5048b">

upon typing "Fu", it should automatically filter out rest of options & show only "Furniture" in Multi-Select Column.

**Comment by FelixMalfait** [comment]
I wasn't able to reproduce anymore so I think this has been fixed in the meantime
