### ISSUE TITLE
Adding Options Easily in Multi-Select Column

### ISSUE THREAD

**Issue by vasnt** [twentyhq/twenty#5889]
![image](https://github.com/twentyhq/twenty/assets/117589240/9fb0337b-5aab-4f6e-9183-e68c35d543f1)

it should be possible to enter new options easily from table itself instead of going to Setting screen.

**Comment by FelixMalfait** [comment]
Hi! Thanks for the suggestion - this is is a feature not a bug, we're taking a Salesforce-like approach not a Notion/Airtable-like approach. We want the data model to remain stable and not every user should be able to change it easily
