### ISSUE TITLE
Add name search box at the top, instead of having to click Filter and then add

### ISSUE THREAD

**Issue by JJKnegtel** [twentyhq/twenty#5895]
## Scope & Context

**Example:** 
There is no quick way to search any list by name, a common search. I have to apply a filter option. 

## Current behaviour

Currently I have to move my mouse all the way to the right, then click filter and then select what I want. 

Most of the time, I just want to search by name. So this is a lot of wasted mouse movement / clicks. 

## Expected behaviour
I just want to be search here, either by clicking an icon on the colmoun name or next to the total, add a search bar. 

![CleanShot 2024-06-17 at 11 42 23](https://github.com/twentyhq/twenty/assets/155550137/613db39b-ea4a-43c3-8a41-84b84f5e3340)

**Comment by FelixMalfait** [comment]
That's a feedback we get very frequently. Thanks for creating this.

cc @Bonapara to decide any followup action

**Comment by Bonapara** [comment]
Replaced by this issue: https://github.com/twentyhq/twenty/issues/6272
