### ISSUE TITLE
Navigation Panel UI Updates

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5902]
# Current behavior

- The workspace switcher and the Navigation items are 24px high. 
- The gap between each navigation section is 32px 
- The workspace switcher icon is not aligned with the menu items

![CleanShot 2024-06-17 at 15 30 27](https://github.com/twentyhq/twenty/assets/19412894/0bbf3d5d-e54e-4ce8-b1ae-cb396ceb7dc6)

# Desired Behavior

-[ ] Navigation items' height should be risen to 28px. 
-[ ] The gap between sections should be reduced to 12px

![CleanShot 2024-06-17 at 15 29 35](https://github.com/twentyhq/twenty/assets/19412894/e8bf0f63-6857-4b0a-8be6-383275638963)

-[ ] The workspace switcher should be aligned with the navigation items

![CleanShot 2024-06-17 at 15 32 47](https://github.com/twentyhq/twenty/assets/19412894/ade439b4-fe52-4b48-8a64-303d1bef80c4)

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=1406-44830&t=QzHWEjAMYRBmJkM8-11

**Comment by Ymirke** [comment]
# [-> Here's a PR](https://github.com/twentyhq/twenty/pull/5964)

## Fixes:
- [x] Navigation items' height should be risen to 28px.
> For clarity:
- [x] Also increased the height of NavigationDrawerSectionTitle to 28px to match navigation item.
- [x] The gap between sections should be reduced to 12px
> Was already completed it seems.
- [x] The workspace switcher should be aligned with the navigation items
