### ISSUE TITLE
[Timebox] Migrate `Link` Field Type to the new `Links` field type

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5909]
# Current behavior

We do offer two Link field types:
`Link` and `Links`

![CleanShot 2024-06-17 at 16 33 40](https://github.com/twentyhq/twenty/assets/19412894/ddf55525-1e75-43c6-a8de-5b98c09e3ac3)

# Desired Behavior

We should migrate the `Link` field type to the new `Links` field type

**Comment by charlesBochet** [comment]
We want to keep Links

**Comment by charlesBochet** [comment]
Same work as Address + remove Link from the codebase
