### ISSUE TITLE
AAUser, I can edit Text fields on Show pages and Kanban cards

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#591]
Right now we just display a few fields on company/person show page.
We should display all fields available.

Eventually implement a "See more" button to hide part of the list on the frontend when the list is too long (cf Figma design)

Also creating a separate issue for the field edition: https://github.com/twentyhq/twenty/issues/592

**Comment by charlesBochet** [comment]
Add fields that are available in schema, don't handle edition for now

**Comment by Bonapara** [comment]
Also make sure the icons are the right one 
<img width="183" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/ce92f4c3-ab93-4b21-8c30-e62397466499">

**Comment by FelixMalfait** [comment]
I'm not sure it's worth investing  in a clean read-only version ; doing a quick and dirty read-only version would be cheap, but doing a clean/abstracted read-only version would likely cost more than integrating the editable fields directly

**Comment by lucasbordeau** [comment]
Fix min width on other fields in Company Show page
