### ISSUE TITLE
Update UI to Match Figma Specs: Labels, Buttons, Gaps

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5910]
# Current Behavior

-  Section labels are uppercase.
-  The "Esc to cancel" text helper should be removed.

![CleanShot 2024-06-17 at 17 10 22](https://github.com/twentyhq/twenty/assets/19412894/2de131d5-295b-4b65-9748-16ceda56ffc0)

# Desired Behavior

Match the following Figma design:
-  Replace the `Esc to cancel` helper with an `X` button.
-  Set the section labels to lowercase - except the first letter of course (use the same style as NavigationDrawerSectionTitle.tsx, and ideally the same component).
-  Add a gap between the first section label and the search bar.
- Check if other details are matching

![image](https://github.com/twentyhq/twenty/assets/19412894/16189b23-bf78-4d35-a408-f3c892ea0f8c)

**Comment by sanidhyasin** [comment]
hey @Bonapara, would love to work on this issue, please assign this to me.

**Comment by Bonapara** [comment]
Sure @sanidhyasin, thanks for contributing!

**Comment by ehconitin** [comment]
Could u assign this to me @Bonapara

**Comment by Bonapara** [comment]
Sure @sanidhyasin, thanks for contributing!

**Comment by ehconitin** [comment]
@Bonapara  please check [PR 6415](https://github.com/twentyhq/twenty/pull/6415)

**Comment by ehconitin** [comment]
@charlesBochet 
Should this issue be closed?
