### ISSUE TITLE
Customize the email onboarding Settings

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5912]
# Current Behavior

Today, we ask which level of information a user wants to share with their team while syncing their email for the first time during onboarding.

![image](https://github.com/twentyhq/twenty/assets/19412894/875c1da1-3dfe-4f3c-b42c-6d312d403eb8)

# Desired Behavior

We want to reduce the choices to either "Everything" or "Metadata only" to create more space to ask if the user wants to exclude non-professional emails from being synchronized.

![image](https://github.com/twentyhq/twenty/assets/19412894/196b9aa2-72a8-44e9-bbe5-2883b2a5744b)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=33430-185278&t=QzHWEjAMYRBmJkM8-11

Blocked by ongoing work on Settings V2 by @bosiraphael

**Comment by RobertoSimonini1** [comment]
can I work on this issue?

**Comment by Bonapara** [comment]
Sure @RobertoSimonini1, thanks for contributing!

**Comment by RobertoSimonini1** [comment]
@Bonapara, before start working on it, should I wait the ongoing work by @bosiraphael?

**Comment by RobertoSimonini1** [comment]
@Bonapara ok, thanks :)

**Comment by FelixMalfait** [comment]
Coming back on old issues in the backlog @Bonapara ; I feel like "exclude professional emails" is not clear enough, few people would understand it's about contact creation. Maybe we should close this for now until the feedback comes again? Or re-work on it to find something that would be more clear to users?

**Comment by jchristman** [comment]
Reading this issue, I wonder if there isn't a way we could add some admin privacy settings @Bonapara that disables the Everything button? I'd prefer for my users to not be able to accidentally click that button during onboard.

**Comment by Bonapara** [comment]
Hi @jchristman, at some point, we will introduce options for admins to choose what their users share with the CRM. Thank you for your comment!
