### ISSUE TITLE
[Timebox] Convert Company's address field to Address type

### ISSUE THREAD

**Issue by ijreilly** [twentyhq/twenty#5916]
## Technical inputs

To be refined:
- Add @TypeChange (TBD) annotation on the WorkspaceEntity
- When the sync-metadata script reads it, it suffixes the existing field to _v20 + set it as custom, and create a new field of desired type
- Discuss with Felix / Thomas if we want to backfill (best effort the new field)

**Comment by vprathap21** [comment]
@ijreilly  Can I work on this issue?

**Comment by charlesBochet** [comment]
We should think if renaming existing custom fields that have same name as newly introduced standard field is using the same logic or is leveraged here
