### ISSUE TITLE
Date filter improvements

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5917]
# Current behavior

Users can only filter dates with the `Greater than` and `Less than` filters. 

# Desired behavior

We want to rename `Greater than` to `Is After`
We want to rename `Less than` to `Is Before`

We want to introduce some new filters: 
- Is 
- Is Empty
- Is Not Empty
- Is Relative
- Is in the past
- Is in the future
- Is today

![CleanShot 2024-06-18 at 10 51 34](https://github.com/twentyhq/twenty/assets/19412894/0b79df88-ffa9-4467-bdbf-fde3da3058ae)

### Is Relative

![CleanShot 2024-06-18 at 10 49 57](https://github.com/twentyhq/twenty/assets/19412894/6842c3b7-7ac5-4374-9d79-b045ee47ffc3)

1. Values: Past, Next, This
2. Number
3. Day, Week, Month, Year

We should reflect the selected values in the calendar. For instance, if someone chooses "This Week," it should be displayed in the calendar as selected. The calendar is only here for visualisation, it's not possible to click into the calendar to generate "last 2 weeks" for examples.

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=2709-52753&t=jqRWyAJosBHzOW0I-11

**Comment by Bonapara** [comment]
Related to https://github.com/twentyhq/twenty/issues/6299 that should be handled first

**Comment by FelixMalfait** [comment]
Relative for range only or can I set a relative date for a simple filter? (e.g. before Today)

**Comment by Bonapara** [comment]
You mean add

- Before 
- After

within the following list?

- Is 
- Is Empty
- Is Not Empty
- Is Relative

Yes we can!

**Comment by FelixMalfait** [comment]
@Bonapara Mmm kind of but "before last 2 weeks" wouldn't really make sense? 
I think the most frequent use-case for relative date filters is "in the future", "in the past" (request I've had during demo calls and from K). User could hack this by setting a very large number in the number of days/week, but it doesn't feel very elegant, any idea how to do it? Maybe there's no good solution

**Comment by Bonapara** [comment]
Agreed - I meant before a date, with that date being chosen in the calendar and defaulting to "Today".

![CleanShot 2024-08-28 at 09 46 49](https://github.com/user-attachments/assets/ccc07274-ee7b-4a0f-8ad5-39ef71526cca)

**Comment by ad-elias** [comment]
Hello, I'd like to work on this after #5398, could you please assign this issue to me?

**Comment by Bonapara** [comment]
@ad-elias are you still on it? :)

**Comment by FelixMalfait** [comment]
@Bonapara yes he is!

**Comment by FelixMalfait** [comment]
This has been shipped :)) - really great work by @ad-elias!
