### ISSUE TITLE
As admin, I can impersonate users 

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#594]
(1) Create columns on table `users`
First column:`canImpersonate` (false by default)
Second column: `allowsImpersonation` (true by default)

(2) Create new endpoint `/impersonate/{userId}`
That endpoints check that the logged-in user has the required privilege to impersonate, then proceeds to re-login as the user, then redirects to the home page or shows an error if the user isn't found or the logged in user doesn't have the required privileges

(3) Todo later (not for this issue): 
Give the user an easy way to revert to his admin account (For now the user can go to settings > logout and re-login)

Note: CRMs like Salesforce or Hubspot allow workspace admin to impersonate their team member. Probably a bit premature since we don't have a strong permissionning system yet but maybe something to have in mind as we design this

**Comment by FelixMalfait** [comment]
We also need to let users opt-out from this feature. Here is how Notion is doing it: 
 
![image](https://github.com/twentyhq/twenty/assets/6399865/d9c06d80-a60e-4bfc-b72e-60aea87365f7)

**Comment by Bonapara** [comment]
# Design

![Image](https://github.com/twentyhq/twenty/assets/19412894/37e6d7fc-ab97-49a0-8496-5428da9f4de1)

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=6150-74138&mode=design&t=osHJgWcPOurIAUbB-4
