### ISSUE TITLE
Border-Radius on Calendar 

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5940]
# Current behavior

The calendar has no more top border-radius

![CleanShot 2024-06-18 at 18 19 43](https://github.com/twentyhq/twenty/assets/19412894/8d8f064f-442d-40d6-a149-75725d30d131)

# Desired Behavior

Border-radius should be 8px all around the calendar

**Comment by theonly1me** [comment]
Hi @Bonapara, #5946 fixes this issue, can you please assign it to me and review the PR? Thanks!

**Comment by Bonapara** [comment]
Thank you for your contribution! The tech team will review your PR shortly.
