### ISSUE TITLE
Update Country Selector background color

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5943]
# Current Behavior

The phone country selector background doesn't match the color of the phone input part.

![image](https://github.com/twentyhq/twenty/assets/19412894/491a6310-20ee-464d-952d-4c03d44e4d27)

# Desired Behavior

The background color should be the same as the input part. (Include some transparency).

**Comment by JoshuaZacek** [comment]
Is it okay if I work on this? @Bonapara

**Comment by Bonapara** [comment]
Sure @JoshuaZacek, thanks for contributing!
