### ISSUE TITLE
Rating field cannot be edited if it's empty

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5948]
Steps to reproduce:
1) create a new field, with type rating on People
2) don't set the fields value on the list view. Go directly to a person's show page
3) try to set the field's value from there.
4) if you click, nothing happens - it's not possible to edit the field

**Comment by Bonapara** [comment]
@lucasbordeau, is it related to the rating field being displayed only on hover?

**Comment by lucasbordeau** [comment]
@Weiko See in `RecordInlineCellDisplayMode`, empty state is checked for all display field components and prevents components like RatingDisplay to show up.

Maybe the fix could be to show RatingInput when we click on "Empty" for rating field display ?
