### ISSUE TITLE
Save last view as the default view when I come back

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5949]
We recently introduced a localStorageEffect which enables us to persist recoil states in local Storage:
https://github.com/twentyhq/twenty/blob/d045bcbb94a5027f8e4cafc129056653670a4b16/packages/twenty-front/src/modules/ui/navigation/navigation-drawer/states/isNavigationSectionOpenComponentState.ts#L8
(in that case it's used to persist if the left-side menu is collapsed ; thanks to this effect if you refresh the page it will remain on the same state)

We should leverage this for the view switcher. If I'm on a view "filtered companies" and I refresh the page or I click on the left menu to go to people then come back to companies, I should remain on the Filtered companies view.

Marking as good first issue but it might be trickier than it seems as always!

**Comment by freakchand** [comment]
Hey Felix, Can you please assign this request to me?

**Comment by FelixMalfait** [comment]
Sure thanks @freakchand!
