### ISSUE TITLE
Column header menu Filter button doesn't work

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5957]
# Current Behavior

When clicking `Filter` in the column header menu, I cannot assign a value to the filter; clicking anywhere else removes it.

https://github.com/twentyhq/twenty/assets/19412894/992ce82f-1b64-4848-8fc1-79f9cc803c79

# Desired Behavior

I should be able to add a value, and the filter should not disappear when clicking somewhere else.

**Comment by Bonapara** [comment]
@thomtrp - do you have room for this one?

**Comment by thomtrp** [comment]
@Bonapara yep I'll have a look!

**Comment by thomtrp** [comment]
Leaving it to @AdityaPimpalkar. Looks like this bug has been introduced by multi-filtering https://github.com/twentyhq/twenty/pull/5892
