### ISSUE TITLE
Sort & Filter by Emails - Sort by Name (identifer)

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5958]
# Current Behavior

Today, I cannot sort by emails, nor can I sort by name (identifier) on the People object.

https://github.com/twentyhq/twenty/assets/19412894/0ab53948-24b0-449f-b90b-96f21137dd7f

# Desired Behavior

I should be able to sort by email.
I should be able to sort by name.
Clicking anywhere on the first column menu header, except the "+" icon button, should open the column header menu with the ability to sort and filter this column (but not move or hide it).

**Comment by markusthiel** [comment]
same!
