### ISSUE TITLE
Adjust Table Header Hover Background Color

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5959]
# Current behavior

The header hover column looks too dark

![CleanShot 2024-06-19 at 15 02 14](https://github.com/twentyhq/twenty/assets/19412894/90c01f67-09ad-4c79-a2c8-b1c45a554543)

# Desired Behavior

The hover background color should be `Background-Secondary`

![bd1dd32720c14a92fc4ad7bf23dd48f1888e653146160790b5c2e735cdee24fd](https://github.com/twentyhq/twenty/assets/19412894/4440d853-6f1e-4c46-aace-079008c29e43)

The `on click` background color should be `Background-Tertiary`

![CleanShot 2024-06-19 at 15 04 38](https://github.com/twentyhq/twenty/assets/19412894/7c4b1412-11ab-45bf-9264-0ea069c1412c)

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=151-10764&t=XlTGtYIpRqo74fNb-11

**Comment by joshmurdock** [comment]
Hello! I would like to work on this issue.

**Comment by Bonapara** [comment]
Sure @joshmurdock, thanks for contributing!

**Comment by joshmurdock** [comment]
I am unfortunately having issues setting up my dev database. I will continue to troubleshoot but with such a simple bug I would remove this assignment from me.

**Comment by Spikoftw** [comment]
Hello, can i work on this ?

**Comment by AkiPraveen** [comment]
Hi @Spikoftw I have a change completed for this, I am waiting for permissions to open a PR :) 

cc @Bonapara

**Comment by Bonapara** [comment]
Close by https://github.com/twentyhq/twenty/pull/5967
