### ISSUE TITLE
Fix height of relation picker in property box

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#598]
(1) Should be 32px not 34px

(2) Should extend when many items are added, not like current behavior: 
<img width="442" alt="Screenshot 2023-07-11 at 13 29 13" src="https://github.com/twentyhq/twenty/assets/6399865/be4a6b56-4747-43eb-9c33-c0898741112c">

**Comment by Bonapara** [comment]
Relations title should stay aligned on top left when there in a wrapping (on screen capture it's aligned on middle instead)
