### ISSUE TITLE
Add Tooltips to Kanban Card Icons for Better Clarity

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5982]
# Current Behavior

Currently, the field icons displayed on each kanban card do not have any tooltips when hovered over. Users must rely on their knowledge or guess what each icon represents.

![CleanShot 2024-06-21 at 15 03 08](https://github.com/twentyhq/twenty/assets/19412894/1027a15e-4f89-489d-a559-d5f91de7a812)

# Desired Behavior

When a user hovers over each field icon within a kanban card, a tooltip should appear displaying the name of the field. For example, hovering over the dollar sign icon should show a tooltip with the text "Amount," hovering over the calendar icon should display "Close Date," and so on. 

Make sure there is a slight delay when hovering the icon before displaying the tooltip: https://github.com/twentyhq/twenty/issues/5727

**Comment by Karlo-Zivkovic** [comment]
I want to work on this! Is this still open and can you assign? :)

**Comment by Manab-upadhyay** [comment]
hello @Bonapara , please assign me this issue.

**Comment by atharvParlikar** [comment]
I was just looking around and found this

<img width="893" alt="Screenshot 2024-06-23 at 5 30 39 PM" src="https://github.com/twentyhq/twenty/assets/58113282/5aa4560b-5b63-4eda-b794-77ea5bbc67a6">

also I got the tooltip to appear just by flipping disableTooltip to false in a RecordInlineCell's field context wasn't so sure after reading the above comment.
