### ISSUE TITLE
Add Chevron Icon to Indicate Submenu on "Fields" Menu Item

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5986]
# Current behavior

The "Fields" menu item doesn't have a chevron to indicate there will be a submenu:

![CleanShot 2024-06-21 at 17 58 26](https://github.com/twentyhq/twenty/assets/19412894/baa80c37-d2ac-4b17-8fa8-abf29975f58f)

# Desired Behavior

Menus that hide a "Sub-Menu" should display a `chevron-right` icon on their right edge.We should add it to the `Fields` menu Item:

![8944f34e929f88037a50e458a221c23686168a8e15529a1be52ee5abdda27395](https://github.com/twentyhq/twenty/assets/19412894/9da6b1ff-8404-465d-870a-faaa43b962f1)

And make the chevron color `Tertiary` Instead of `Secondary` + check its font weight:

![CleanShot 2024-06-21 at 18 03 37](https://github.com/twentyhq/twenty/assets/19412894/80afd9d8-84b7-4213-a029-9d824d793a86)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=24955-194238&t=zLGqFerIr4FJfuka-11

**Comment by akarsanth** [comment]
In the figma design, the left and right chevron have different size. Is it supposed to be like that or of same size?

**Comment by Manab-upadhyay** [comment]
hello @Bonapara . please assign me this issue .

**Comment by Manab-upadhyay** [comment]
Hi @Bonapara ,

I noticed that the PR for this issue is currently awaiting review. If there are any additional tasks or improvements needed, I'd be happy to assist.

Thank you!

**Comment by Bonapara** [comment]
> Hi @Bonapara ,
> 
> I noticed that the PR for this issue is currently awaiting review. If there are any additional tasks or improvements needed, I'd be happy to assist.
> 
> Thank you!

Thanks @Manab-upadhyay! Feel free to grab another [Good First Issue](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee) if you want!
