### ISSUE TITLE
Add Stage Management and "No Value" Column to Kanban

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5987]
# Current Behavior

Records without a Select value assigned are not visible on the Kanban board displaying the given Select.

We cannot show/hide or reorder stages on a Kanban view.

# Desired Behavior

We want to introduce a new `Stage` menu in the Kanban Options menu. This will allow users to choose which Select value should be displayed and in what order:

![CleanShot 2024-07-01 at 16 31 20@2x](https://github.com/twentyhq/twenty/assets/19412894/ec821979-863d-4e43-b5c1-1a90a85fcd38)

We also want to introduce a "No Value" column that should behave like other columns, with the possibility to show/hide it.

![15d001fdcdf525385e62258c659fd1004c653876bde120ceebc6cb5e7bf54448](https://github.com/twentyhq/twenty/assets/19412894/2668f17c-ffd1-4416-8a06-9f7784237650)

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=24955-194483&t=zLGqFerIr4FJfuka-11

**Comment by Sudarsh1010** [comment]
I'd like to work on this.

**Comment by Bonapara** [comment]
Hi @Sudarsh1010! Thanks! Maybe you can pick a [good first issue](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee) first? This issue is for contributors with a bit more Twenty experience :)

**Comment by Sudarsh1010** [comment]
yeah, My bad. I didn't saw the badge properly. Thank You.

**Comment by Us3r-gitHub** [comment]
Do we plan to take action to change the 'select' field used in the view?
If yes, is this included in this issue??

**Comment by Us3r-gitHub** [comment]
> Are you often in need of changing the view type?

No, But I had dealt with issues #5915 related

When I develop, I create select fields and delete them over and over again
Sometimes, I just find a new bug (maybe)

When I delete a select field that is being used on a view, the view goes blank
That's right because select has been removed, but view must also be removed, right?
OR, we can add an action to change which select will be used

**Comment by Bonapara** [comment]
Thanks for the detailed explanation, @Us3r-gitHub! I think the best solution is to delete the corresponding views simultaneously. We can also display a confirmation window in the settings when this field is deleted to inform the user that several views will be removed. Do you want to create an issue for this?

**Comment by Us3r-gitHub** [comment]
It's possible to change 'select' after issue #6048 is resolved, right?

**Comment by Bonapara** [comment]
@Us3r-gitHub yes!

**Comment by shashankvish0010** [comment]
Hey @Bonapara , I would like to work on it; could you assign it to me?

**Comment by Bonapara** [comment]
It looks like we will handle it internally for now @shashankvish0010. Maybe have a look on other [Good First Issues](https://github.com/twentyhq/twenty/issues/5987#issuecomment-2201107396)
