### ISSUE TITLE
Error Message When Click on Connect WIth Google Button

### ISSUE THREAD

**Issue by weir1** [twentyhq/twenty#5993]
## Bug Description

{"statusCode":404,"message":"Google apis auth is not enabled","error":"Not Found"}
getting above message after I entered into setting & trying to add my email

## Expected behavior

It should let me add my gmail account

...

I tried installation via a single click script

**Comment by weir1** [comment]
> The error message 'Google apis auth is not enabled' is thrown in the `GoogleAPIsProviderEnabledGuard`. Ensure that the environment variables `MESSAGING_PROVIDER_GMAIL_ENABLED` and `CALENDAR_PROVIDER_GOOGLE_ENABLED` are set to `true`.
> 
> ### References
> [/packages/twenty-server/src/engine/core-modules/auth/guards/google-apis-provider-enabled.guard.ts](https://github.com/twentyhq/twenty/blob/main/packages/twenty-server/src/engine/core-modules/auth/guards/google-apis-provider-enabled.guard.ts) [/packages/twenty-server/src/engine/core-modules/auth/controllers/google-apis-auth.controller.ts](https://github.com/twentyhq/twenty/blob/main/packages/twenty-server/src/engine/core-modules/auth/controllers/google-apis-auth.controller.ts)
> 
> [**Ask Greptile**](https://app.greptile.com/chat/github/twentyhq/twenty/main)

I am using twenty via script aka docker
root@twenty:~/twenty# ls -la
total 16
drwxr-xr-x 2 root root 4096 Jun 23 15:02 .
drwx------ 6 root root 4096 Jun 23 15:01 ..
-rw-r--r-- 1 root root 1072 Jun 23 15:02 .env
-rw-r--r-- 1 root root 2761 Jun 23 14:23 docker-compose.yml
root@twenty:~/twenty# 

but I didnt find anywhere to enable these settings in .env file or docker-compose file

how to access those settings so that I can make them true

**Comment by weir1** [comment]
I added these 2 lines in .env
MESSAGING_PROVIDER_GMAIL_ENABLED=true
CALENDAR_PROVIDER_GOOGLE_ENABLED=true

also in compose file i added
MESSAGING_PROVIDER_GMAIL_ENABLED: ${MESSAGING_PROVIDER_GMAIL_ENABLED}
CALENDAR_PROVIDER_GOOGLE_ENABLED: ${CALENDAR_PROVIDER_GOOGLE_ENABLED}

when I run twenty then I am getting 
This page isn’t working
s currently unable to handle this request.
HTTP ERROR 500

**Comment by volfadar** [comment]
> I added these 2 lines in .env MESSAGING_PROVIDER_GMAIL_ENABLED=true CALENDAR_PROVIDER_GOOGLE_ENABLED=true
> 
> also in compose file i added MESSAGING_PROVIDER_GMAIL_ENABLED: ${MESSAGING_PROVIDER_GMAIL_ENABLED} CALENDAR_PROVIDER_GOOGLE_ENABLED: ${CALENDAR_PROVIDER_GOOGLE_ENABLED}
> 
> when I run twenty then I am getting This page isn’t working s currently unable to handle this request. HTTP ERROR 500

![image](https://github.com/twentyhq/twenty/assets/44869940/9e9449e9-77aa-44bf-9803-36cfccee4c08)

i suspect you didn't fill the `AUTH_GOOGLE_CLIENT_ID`, `AUTH_GOOGLE_CLIENT_SECRET`, and `AUTH_GOOGLE_APIS_CALLBACK_URL`.
https://github.com/twentyhq/twenty/blob/158e7a31f4ea3d02367db2599f43e9176d95a078/packages/twenty-server/src/engine/core-modules/auth/strategies/google-apis.auth.strategy.ts#L56-L62

**Comment by weir1** [comment]
> > I added these 2 lines in .env MESSAGING_PROVIDER_GMAIL_ENABLED=true CALENDAR_PROVIDER_GOOGLE_ENABLED=true
> > also in compose file i added MESSAGING_PROVIDER_GMAIL_ENABLED: ${MESSAGING_PROVIDER_GMAIL_ENABLED} CALENDAR_PROVIDER_GOOGLE_ENABLED: ${CALENDAR_PROVIDER_GOOGLE_ENABLED}
> > when I run twenty then I am getting This page isn’t working s currently unable to handle this request. HTTP ERROR 500
> 
> i suspect you didn't fill the `AUTH_GOOGLE_CLIENT_ID`, `AUTH_GOOGLE_CLIENT_SECRET`, and `AUTH_GOOGLE_APIS_CALLBACK_URL`.
> 
> https://github.com/twentyhq/twenty/blob/158e7a31f4ea3d02367db2599f43e9176d95a078/packages/twenty-server/src/engine/core-modules/auth/strategies/google-apis.auth.strategy.ts#L56-L62

No I didnt should I add these in .env or compose file?

**Comment by weir1** [comment]
OK Now I can see authentic with google but after connecting it shows 404 off the beaten path

**Comment by weir1** [comment]
> > > I added these 2 lines in .env MESSAGING_PROVIDER_GMAIL_ENABLED=true CALENDAR_PROVIDER_GOOGLE_ENABLED=true
> > > also in compose file i added MESSAGING_PROVIDER_GMAIL_ENABLED: ${MESSAGING_PROVIDER_GMAIL_ENABLED} CALENDAR_PROVIDER_GOOGLE_ENABLED: ${CALENDAR_PROVIDER_GOOGLE_ENABLED}
> > > when I run twenty then I am getting This page isn’t working s currently unable to handle this request. HTTP ERROR 500
> > 
> > 
> > i suspect you didn't fill the `AUTH_GOOGLE_CLIENT_ID`, `AUTH_GOOGLE_CLIENT_SECRET`, and `AUTH_GOOGLE_APIS_CALLBACK_URL`.
> > https://github.com/twentyhq/twenty/blob/158e7a31f4ea3d02367db2599f43e9176d95a078/packages/twenty-server/src/engine/core-modules/auth/strategies/google-apis.auth.strategy.ts#L56-L62
> 
> No I didnt should I add these in .env or compose file?

I am attaching a my screen to show exact issue please check

![Animation](https://github.com/twentyhq/twenty/assets/74604555/93206d83-c595-4b6e-b0d6-72bad4d06252)

**Comment by weir1** [comment]
@volfadar please help

**Comment by volfadar** [comment]
I'm sorry i can't help right now, and now i'm not actively working with twenty right now.

**Comment by felixlu07** [comment]
Hey there @weir1 . I faced the same issue as you, and I think the solution might be the same for your issue. I did a quick search for Google auth related in the code base, and I would that there are actually two variables that we have to set in the .env file. `AUTH_GOOGLE_CLIENT_SECRET` `AUTH_GOOGLE_CALLBACK_URL`

I didn't have this `AUTH_GOOGLE_CLIENT_SECRET`  in my yml file, but it still worked nevertheless. Finally got my Google account to be connected after 3 hours. :)

Respectively, their values should look something like **https://YOURWEBSITE.com/auth/google/redirect** AND **https://YOURWEBSITE.com/auth/google-apis/get-access-token**


![image](https://github.com/user-attachments/assets/17ce33df-acae-4680-9673-bfcf8de935af)

**Comment by FelixMalfait** [comment]
Thanks @felixlu07
