### ISSUE TITLE
Inline Field data overflowing on Kanban cards

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6000]
# Current Behavior

The inline field data overflows on Kanban cards.

![image](https://github.com/twentyhq/twenty/assets/19412894/dc095cfa-e15f-435a-8f0e-7a8dbdb23b97)

# Desired Behavior

The content should be cropped with ellipses to prevent overflow.

**Comment by rksingh2001** [comment]
Can I get assigned to this issue?

**Comment by Bonapara** [comment]
Sure @rksingh2001, thanks for contributing!

**Comment by rksingh2001** [comment]
Hi @Bonapara, I have implemented ellipses for the straightforward text like field types, what about these types: JSON, multi select etc. I don't think ellipsis will work for them.

![image](https://github.com/twentyhq/twenty/assets/59247136/dead5dc9-d84f-4c90-bbb7-bf63982309d7)

**Comment by Bonapara** [comment]
Thanks @rksingh2001! Yes, it should be the case for every field. But the Link and Multi-Select field have special behavior: https://github.com/twentyhq/twenty/issues/4900

**Comment by lucasbordeau** [comment]
Closing this issue as it has been fixed by recent changes.

**Comment by rksingh2001** [comment]
@lucasbordeau, I would like to learn how it was fixed, can you point me to PR which fixed it or change (if u remember)? I will appreciate it.

**Comment by lucasbordeau** [comment]
@rksingh2001 This issue was fixed by https://github.com/twentyhq/twenty/pull/6061
