### ISSUE TITLE
Drag and Drop Causes Flashing and Disappearing Cards

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6001]
# Current Behavior

1. I grab the "Twitch" card.
![CleanShot 2024-06-24 at 15 35 31](https://github.com/twentyhq/twenty/assets/19412894/0ebdac4c-a846-4b3b-b584-5aca12879de8)

2. I drag the card between "VMware" and "HP." The "Twitch" card disappears from the right column.
![CleanShot 2024-06-24 at 15 33 50](https://github.com/twentyhq/twenty/assets/19412894/7d13350b-a6f9-41a2-ac04-ffbf213f80d8)

3. When I release the click, the card is added to the left column but is displayed again in the right column.
![CleanShot 2024-06-24 at 15 37 42](https://github.com/twentyhq/twenty/assets/19412894/a0dfa950-5ed0-4320-b589-b5b3d11ff254)

4. The card disappears from the left column, even though we want to drag it there.
![CleanShot 2024-06-24 at 15 38 58](https://github.com/twentyhq/twenty/assets/19412894/c1cc9323-f248-4dd6-9303-5a99ea9a6839)

5. The card disappears from the right column and finally appears in the left column.
![CleanShot 2024-06-24 at 15 40 03](https://github.com/twentyhq/twenty/assets/19412894/a6f6abdd-343d-4fff-8726-25dbda330bc5)

### Full Behavior in Video:

https://github.com/twentyhq/twenty/assets/19412894/d2068f3e-9e5e-4de1-a8c7-42c1ddcda7d7

# Desired Behavior

Prevent any flashing when dragging and dropping a card to another column.

**Comment by rksingh2001** [comment]
Can I get assigned to this issue?

**Comment by Bonapara** [comment]
Sure @rksingh2001, thanks for contributing!

**Comment by rksingh2001** [comment]
@Bonapara I think you forgot to assign me :)

**Comment by Bonapara** [comment]
done, Sorry 😅
