### ISSUE TITLE
Person Switcher Broken on Tasks List Page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6007]
# Bug Description

The "Person switcher" on the tasks list page is broken:

https://github.com/twentyhq/twenty/assets/19412894/0d488d1b-f398-4eca-9717-96b683ef7cbb

A React context must be missing

**Comment by srikary12** [comment]
Can I work on this?

**Comment by Bonapara** [comment]
Sure @srikary12, thanks for contributing!

**Comment by srikary12** [comment]
I've identified the issue,

In ObjectFilterDropdownRecordSelect.tsx
const { removeCombinedViewFilter } = useCombinedViewFilters();

is failing, we need to provide viewBarComponentId.

Not sure how to proceed

**Comment by srikary12** [comment]
The context is not received properly by the child components

**Comment by srikary12** [comment]
@Bonapara I've raised a PR, let me know how it goes

**Comment by Bonapara** [comment]
We will review it shortly, thanks @srikary12!
