### ISSUE TITLE
Multi-select values blink

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6011]
# Bug Description

Multi-select values blink and are not registered when clicked to be selected or deselected.

https://github.com/twentyhq/twenty/assets/19412894/eb5dbb49-86c4-4a1c-8373-98e102140f52

**Comment by charlesBochet** [comment]
+ Check sort behavior on Select

**Comment by ehconitin** [comment]
Can  I work on this?

**Comment by Bonapara** [comment]
@lucasbordeau will you handle it or can @ehconitin do it?

**Comment by ehconitin** [comment]
@Bonapara , on a second thought let me finish my already assigned issues. If i get time Ill work on it. 
Sorry for the inconvenience.

**Comment by lucasbordeau** [comment]
@Bonapara @ehconitin I'm currently quite busy with code review (including many from @ehconitin !) so I would be glad to let it to contributors.

**Comment by ehconitin** [comment]
Hi @Bonapara, I could not reproduce this bug.
Worked fine for me.

https://github.com/user-attachments/assets/13fe8feb-82eb-49a1-9e14-6f6a440c0d6c

**Comment by Bonapara** [comment]
Could not reproduce as well, @charlesBochet was it fixed?

**Comment by charlesBochet** [comment]
Cannot reproduce either, let's close it
