### ISSUE TITLE
Ability to Reset Selected Field Value to Empty

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6012]
# Current behavior

I cannot reset the value of `Select` fields

https://github.com/twentyhq/twenty/assets/19412894/b0c0b779-7c29-4e44-9395-f38660eac703

# Desired Behavior

Users should be able to set no value for a select field. Clicking on the selected value should remove it.

**Comment by DubemObi** [comment]
Hello, I'll like to work on this can you please assign to me

**Comment by Bonapara** [comment]
Sure @DubemObi, thanks for contributing!

**Comment by Weiko** [comment]
Closing this issue in favour of https://github.com/twentyhq/twenty/issues/6064 as discussed with @FelixMalfait and @Bonapara
