### ISSUE TITLE
Add Ability to filter Webhooks

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6015]
# Current Behavior

Webhooks are currently set to send all data without discrimination. There is no functionality to trigger webhooks based on specific objects or actions.

# Desired Behavior

We aim to introduce a "Filter" section to allow users to specify which objects and actions should trigger the webhooks. By default, if no filters are specified, the webhook will operate as it currently does, triggering for all objects and actions.

https://github.com/twentyhq/twenty/assets/19412894/223de412-6540-4d1d-90d0-fff41a2fea33

When a user selects an object to edit, a new row should automatically appear below it to enable adding additional filters. If a selected object is clicked in the menu, it should be deselected and the corresponding filter row removed.

![315505f156e52d615f28afb763f1033bc1ac6f1002ef9675d4f7adf77d5ecdc2](https://github.com/twentyhq/twenty/assets/19412894/188215d7-822d-4cf1-a708-f56f235d70c9)

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34028-89194&t=zgRl269mYJtgBgxt-11

**Comment by adwait-godbole** [comment]
Hey @Bonapara I am new to Twenty and just completed the setup on my local system. Can I work on this issue? Will try to resolve it in 2-3 days since it involves both changes to frontend and the backend side.

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara I would like to work on this as my first back-end issue please.

**Comment by Bonapara** [comment]
Sure @Faisal-imtiyaz123, thanks for contributing!

**Comment by Faisal-imtiyaz123** [comment]
@charlesBochet Do you intend to work here yourself?

**Comment by charlesBochet** [comment]
This has been implemented :)
