### ISSUE TITLE
Hide Delete Button for Selections Over 100 Records

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6023]
# Current behavior

The front end allows the deletion of more than 100 records, while the back end does not.

![image](https://github.com/twentyhq/twenty/assets/19412894/983e8e4d-74c4-4ada-8edd-17a50b1f01ef)

```
{
"errors": [
{
"message": "Cannot delete person because it impacts too many records (more than 100).",
"extensions": {
"code": "GRAPHQL_VALIDATION_FAILED",
"response": {
"statusCode": 400,
"message": "Cannot delete person because it impacts too many records (more than 100).",
"error": "Bad Request"
}
}
}
],
"data": {
"deletePeople": null
}
}
```

# Desired Behavior

We want to hide the "Delete" Button when more than 100 records are Selected

![CleanShot 2024-06-25 at 17 39 04](https://github.com/twentyhq/twenty/assets/19412894/473e62b8-658d-45e8-9d05-24d3eec99d7b)

**Comment by Adithej** [comment]
Hi , I am happy to work on this issue

**Comment by Bonapara** [comment]
Sure @Adithej, thanks for contributing!
