### ISSUE TITLE
AA User I can run intensive mutations without getting an error 

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#6025]
## Scope & Context

Currently we have a limitation on the API - MUTATION_MAXIMUM_RECORD_AFFECTED, defined as an env variable - which specifies the number of records that can be affected during a GraphQL mutation (most specifically update and deletions mutations, creations are not concerned for some reason).
This limitation comes from pg_graphql limitation, see "atMost" in the documentation here https://supabase.github.io/pg_graphql/api. If it's not specified, it falls back to the default value (60).
This is also a good practice to avoid overloading the server and in this case the DB. This also tells the user "We handle this much so you should expect an acceptable timeframe for your request, more of it might result in degraded performances/timeout."

## Current behavior

For example, when we try to delete more than {MUTATION_MAXIMUM_RECORD_AFFECTED} records, we get an error, which is fine from the API point of view but the Frontend should handle this properly, this is even more an issue UX wise when people want to check the box at the top of the table which implies that it should select all records and mutation affects all of them (even those that are not loaded yet).

## Expected behavior

We still want to keep a limitation on the API but we should handle intensive mutations on the client with some strategies:
- The FE should run multiple mutations in batch. Which means we should call sequentially each mutation (following the limitation of 
MUTATION_MAXIMUM_RECORD_AFFECTED). (e.g: MUTATION_MAXIMUM_RECORD_AFFECTED=160 means we will paginate our mutations with 160 records per page until all records have been affected). The UI should reflect this, similarly to the csv export, with pagination/percent view.
- Above a certain threshold, we need to find another solution and tell the user that they should defer their action because it's too intensive => Here we want to run an async job in the background. This should be well represented on the UI

## Technical inputs
- To know MUTATION_MAXIMUM_RECORD_AFFECTED, we need to expose this value in getClientConfig endpoint so the frontend can use it
- ...

**Comment by Weiko** [comment]
See https://github.com/twentyhq/twenty/issues/6023 as a "temporary" solution.

**Comment by Bonapara** [comment]
Is #6039 fixing this issue? If not, could you add some tags, @Weiko? :)

**Comment by Weiko** [comment]
Only part of it, this should go with #5169

**Comment by Weiko** [comment]
@lucasbordeau is working on it

**Comment by lucasbordeau** [comment]
Closed by https://github.com/twentyhq/twenty/pull/5320
