### ISSUE TITLE
View becomes blank after deleting select

### ISSUE THREAD

**Issue by Us3r-gitHub** [twentyhq/twenty#6027]
## Bug Description

View becomes blank once we delete the select field that is currently being used.

![image](https://github.com/twentyhq/twenty/assets/58467104/dfbad3cf-df8f-41cc-b42c-9c31d5f22023)

Steps to Reproduce:
1. Create new Select field
2. Create new View-Kanban (use Select field that created before)
3. Delete Select field on Settings Page
4. Back again to View Page (it shows blank)

## Expected behavior

Delete corresponding view simultaneously once select field is deleted.
Add confirmation window to inform user that several views will be removed.

**Comment by Bonapara** [comment]
@Weiko https://github.com/twentyhq/twenty/issues/6028 may be related to this one too if you have any inputs?

**Comment by Us3r-gitHub** [comment]
The mentioned issue will be the next impact if this is not addressed/fixed

After this object field deletion and navigate back to view again

**Comment by ijreilly** [comment]
@Bonapara is it ok to delete the view directly when deleting the field, or should we add a modal when deleting the field to warn that the view will be deleted ?

**Comment by Bonapara** [comment]
We can delete it directly, at least for now!
