### ISSUE TITLE
Blank Kanban View after creation

### ISSUE THREAD

**Issue by Us3r-gitHub** [twentyhq/twenty#6028]
Scope & Context

Create a Kanban view again after deleting select

## Bug Description

Steps to Reproduce:
1. Follow reproduce on issue #6027
2. Create new Kanban View with new Select
3. After creation, Kanban View becomes blank

## Technical inputs

- After research, its occured due incorrect id is being used

Suggested Solution:
Add conditional check, if current id is still exist on list

**Comment by Us3r-gitHub** [comment]
At Select UI Component
Currently, there is a mechanism to set the label with the first data item.
Can we also implement this for setting the value too?

**Comment by Bonapara** [comment]
@Weiko any idea on this one too?

**Comment by Us3r-gitHub** [comment]
We can add a condition to set the ID in these [lines](https://github.com/twentyhq/twenty/pull/5985/files#diff-36a1c9c19086d25a008a0b836c1c5c99492a6413a1fedb61b83a23b632c6236aR69-R72).

However, I don't think it's the best approach to resolve the issue.
