### ISSUE TITLE
I should be able to reset the primary link of a Links field

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6041]
I've created a custom field of type Links:

<img width="211" alt="Screenshot 2024-06-26 at 15 52 20" src="https://github.com/twentyhq/twenty/assets/6399865/3e3da0a6-9731-4468-87d4-7db532658920">

I can remove the second option:
<img width="215" alt="Screenshot 2024-06-26 at 15 52 48" src="https://github.com/twentyhq/twenty/assets/6399865/5bb92ea7-a115-45f0-ac84-ad1bf1fff51d">

But I cannot remove this first: 
<img width="220" alt="Screenshot 2024-06-26 at 15 53 11" src="https://github.com/twentyhq/twenty/assets/6399865/6b996b60-b8ab-4c83-9f2a-828021c8b248">

I get why we didn't do it in v1 (because it's not just about deleting the primary link, it's also about moving the first element of secondary links into the primary link it there are any secondary link). But we should prioritize it

**Comment by rostaklein** [comment]
Hey there 😉 Ive implemented this in https://github.com/twentyhq/twenty/pull/6185 looks like no backend was needed. Let me know your feedback.
