### ISSUE TITLE
Edit kanban's main field

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6048]
After creating a kanban it's not possible to view the field that was used to create the kanban or to modify it to another type of select field:

<img width="236" alt="Screenshot 2024-06-26 at 18 47 03" src="https://github.com/twentyhq/twenty/assets/6399865/21bf6422-5cee-4ce3-ba50-4e8bcd430674">

Edit: we might as well allow viewing or even changing the view type if we do this...

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by Supratim69** [comment]
Can i pick this up?

**Comment by hacanand** [comment]
can you please elaborate the issue with some video. as  its not clear

**Comment by Bonapara** [comment]
https://github.com/user-attachments/assets/17b715da-8f20-49cc-993b-1c7f2e4baff9

We cannot access the stage select when editing a kanban view

![CleanShot 2024-10-21 at 10 01 20](https://github.com/user-attachments/assets/829d413e-f651-4730-abff-21bfdebafc02)

**Comment by Hitarthsheth07** [comment]
@FelixMalfait @Bonapara 

# The Problem

The button is disabled when there are 1 or less fields available for Kanban view... 

Do you want to show the label `No select field` when there's no field to select. 
![image](https://github.com/user-attachments/assets/1823319d-e066-450d-9063-d4a7d4c5fdc9)

Suggestion: A better alternate phase instead of `No select field` would be `No field to Select`

**Comment by Hitarthsheth07** [comment]
![image](https://github.com/user-attachments/assets/5f59f00e-adb4-4a07-b08f-0ca8da4a04c7)

Should I use a `Save` button to save the view user selects 
OR 
The view automatically changes when dropdown is out of focus? 

Do we have this in design?

**Comment by Bonapara** [comment]
Thanks @Hitarthsheth07! I think we can auto-save when a user is editing a field indeed.

**Comment by FelixMalfait** [comment]
@Hitarthsheth07 sorry I will close this since your PR is still quite far away from the attempted result and we might want to wait for https://github.com/twentyhq/twenty/issues/8255 instead of wasting efforts on this. Thanks!
