### ISSUE TITLE
text input field focus should deactivate shortcuts

### ISSUE THREAD

**Issue by mxcrbn** [twentyhq/twenty#6051]
## Bug Description

typing specific characters (eg "g") in a text field triggers shortcuts

**Example:** 
```
i was trying to add a stage in opportunities ("Contacting") but can't type the "g" + if I type eg "t" after typing "g", i'm redirected to that tasks screen

screen:
https://github.com/twentyhq/twenty/assets/53276986/b038280b-ac0a-42c1-a6fa-122f3cd6d203
```

## Expected behavior

i can type my text without triggering shortcuts when focus is on text input field / can trigger shortcuts when no focus is on text input field

**Comment by Bonapara** [comment]
@lucasbordeau, the problem also occurs in muti-select

**Comment by lucasbordeau** [comment]
The issue has been fixed.
