### ISSUE TITLE
Add member (eg "invite sent" state) in members list when inviting a new member via email

### ISSUE THREAD

**Issue by mxcrbn** [twentyhq/twenty#6055]
# Current behavior

When adding members via email, a toast message confirms the action but those members don't appear anywhere, which can be confusing (on perso & even more on team level).

# Desired Behavior (Core team edit)

We want to display an `Invite Sent` status chip on the person card for users who have been invited by email but have not yet joined.

![image](https://github.com/user-attachments/assets/decadca8-64f0-4221-97f3-88a61c3a672e)

[Figma](https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34845-126561&t=hrDkyWQ3cs5iGjno-11)

Edit Félix: we also need to be able to resend a new email (or cancel invit / recreate a new one)

**Comment by Bonapara** [comment]
Thanks for the good feedback @mxcrbn ;)

**Comment by FelixMalfait** [comment]
Related: https://github.com/twentyhq/twenty/issues/5078
In the initial version of this issue we also had one expiring link per-user. We ended up with a quicker implementation but we need to move away from this(see Github edition history of above issue for initial requirements). Maybe it's worth creating a dedicated table or at least having a shared field to store that info in appTokens.

**Comment by FelixMalfait** [comment]
Closing as it will be merged this week and is tracked by the 2 other issues. Thanks a lot for the suggestion!
