### ISSUE TITLE
Ability to Reset Selected Field Value to Empty

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#6064]
# Current behavior

I cannot reset the value of `Select` fields

https://github.com/twentyhq/twenty/assets/19412894/b0c0b779-7c29-4e44-9395-f38660eac703

# Desired Behavior

Users should be able to set no value for a select field. Here "Industry" comes from the name of the field and should be computed dynamically. Selecting "No [fieldName]" should set the value as null in the API call.

![CleanShot_2024-06-26_at_16](https://github.com/twentyhq/twenty/assets/1834158/c6aa1406-4f05-477e-8fdf-cde6ee04834e)

**Comment by Bonapara** [comment]
Related to https://github.com/twentyhq/twenty/issues/5987
