### ISSUE TITLE
Docker: in version 0.20 timelime is empty

### ISSUE THREAD

**Issue by stupkad** [twentyhq/twenty#6068]
## Bug Description

In version 0.20.0 the timeline for records (tested with company and opportunity) is empty. This behaviour occours in an self hosted environment using the available docker containers. The timeline keeps showing no information (but does not crash) even when new entries (e.g. a note) are created.

## Expected behavior

Timeline shows same information as before.

## Technical inputs

Pulled both latest db and server, and deleted existing volumes.

**Comment by Us3r-gitHub** [comment]
This seems to duplicate #6054

**Comment by FelixMalfait** [comment]
Closing to continue on #6054, thanks for the report and apologies for the late reply. We're catching up on all issues just now
