### ISSUE TITLE
Disable New Registrations and Signups

### ISSUE THREAD

**Issue by client4** [twentyhq/twenty#6074]
I would like the ability to disable new signups to a self-hosted instance.  As it stands anyone can create an account.

**Comment by client4** [comment]
Found it, it's an option set in the env. https://github.com/twentyhq/twenty/blob/main/packages/twenty-server/.env.example

**Comment by huksley** [comment]
This options does not exist anymore, how to disable signups?

**Comment by adiologydev** [comment]
> This options does not exist anymore, how to disable signups?

It is now disabled by default if you don't have multi-workspace enabled. If you want to add more people, you'd have to send them an email or share the invite link.
