### ISSUE TITLE
Add deletion confirmation modals to tasks, notes and single objects

### ISSUE THREAD

**Issue by JarWarren** [twentyhq/twenty#6075]
## Scope & Context

In many cases, deletion is an irreversible single-click procedure.

## Current behavior

Tasks and notes can be deleted by (mis)clicking a trash button. No confirmation is needed.

Objects (Person, Company, etc) can be deleted through the menu option, which requires a second click, but still no confirmation is needed. This risks substantial data loss for large objects.

## Expected behavior
A confirmation modal, similar to batch deletion or API key deletion.

**Example:** 
See #4016 for an example modal.

**Comment by Us3r-gitHub** [comment]
#6027

**Comment by Bonapara** [comment]
Hi @JarWarren, thanks for the feedback! We will address your issue soon by implementing the Soft Delete feature (https://github.com/twentyhq/twenty/issues/6075), which will allow you to retrieve a deleted issue. 

In this context, resolving this issue
