### ISSUE TITLE
Make the authentication cookie available across the entire website.

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6097]
# Current Behavior

The authentication cookie is only available on `app.twenty.com`.

# Desired Behavior

It should also work on `Twenty.com` so we can customize the website behavior if the user is connected.

# How

We should add a `path: '/'` because, by default, the cookie's path is the page where it was created (standard browser behavior). To make it available across the entire domain, use `path: '/'`. For more details, refer to the [js-cookie documentation](https://github.com/js-cookie/js-cookie/tree/v1.5.1?tab=readme-ov-file#path).

**Comment by FelixMalfait** [comment]
Note, this is not ideal from a security standpoint (see: https://security.stackexchange.com/questions/212809/what-is-the-most-secure-way-to-store-cross-subdomain-cookies for options). But I think it's the best for now.

I thought we could introduce an option like `COOKIE_SHARED_WITH_ROOT_DOMAIN` that's false by default (for self-hosters), but that's probably a bit overkill (?)

**Comment by FelixMalfait** [comment]
FYI @AMoreaux - might be something we want to consider in followup PRs (auto-redirect from app.twenty.com to the right domain, being logged-in)
