### ISSUE TITLE
Display issue with long record names

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6102]
We don't display longer names properly.

This is especially bad on the opportunity object where names tend to be long:

<img width="381" alt="Screenshot 2024-07-03 at 09 00 12" src="https://github.com/twentyhq/twenty/assets/6399865/9ee330b6-629e-454a-8ac1-297adbe3a57a">

cc @Bonapara

**Comment by RobertoSimonini1** [comment]
what should we do?
wrap the sentence, scale down the size of the text or truncate the string?

**Comment by Bonapara** [comment]
We should truncate the text and maintain a 12px padding on the left and right to keep it aligned with the fields:

![image](https://github.com/twentyhq/twenty/assets/19412894/f2f4dc15-f99e-4a9d-9b6f-a284e0c99a9f)

**Comment by gowreesh369** [comment]
Is this issue open ? Can i take it?

**Comment by Bonapara** [comment]
@RobertoSimonini1 do you want it? Otherwise I'll assign you @gowreesh369, but in the meantime you can look our other 
Good First Issues: https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee

**Comment by RobertoSimonini1** [comment]
@Bonapara yes, I would like to solve it :)

**Comment by Bonapara** [comment]
Thanks @RobertoSimonini1 !

**Comment by RobertoSimonini1** [comment]
hi guys, I'm working on the issue now since I was a bit busy last days, btw, I think we should set some variables setting the max lenght of the string and use those instead of writing numbers in the code, what do you think?
Now I'm gonna open a PR and maybe we can discuss there

**Comment by FelixMalfait** [comment]
Answered in the PR. I think you should use CSS ellipsis and base it on the parent container's size, not hardcode values. Thanks!
