### ISSUE TITLE
Strange behavior when re-ordering options of a select field

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6103]
Go to a select field, for example the opportunity stage field.

Try to re-order the fields, you'll see the behavior is strange. There's an offset, the mouse isn't directly attached to the item you're dragging.

<img width="488" alt="Screenshot 2024-07-03 at 09 02 15" src="https://github.com/twentyhq/twenty/assets/6399865/88d1a802-9d4f-494a-8f1b-1577e499d1a6">

**Comment by Faisal-imtiyaz123** [comment]
@FelixMalfait can I work?

**Comment by FelixMalfait** [comment]
@Faisal-imtiyaz123 since you are already assigned to the other issue, let's tackle it first. But feel free to raise a PR for this one after!

**Comment by Faisal-imtiyaz123** [comment]
I raised a P.R for that one. Can I work here now?

**Comment by FelixMalfait** [comment]
Sure thanks @Faisal-imtiyaz123!

**Comment by Faisal-imtiyaz123** [comment]
Uploading Screen Recording 2024-07-10 at 10.56.50 PM.mov…

**Comment by Faisal-imtiyaz123** [comment]
I can re-order things. Could you provide more description of the problem please.

**Comment by Faisal-imtiyaz123** [comment]
![Uploading Screenshot 2024-07-10 at 1.58.41 PM.png…]()

**Comment by FelixMalfait** [comment]
@Faisal-imtiyaz123 the problem is the feeling you get when you drag and drop. For me the mouse is "detached" from the element I'm dragging (I.e. my mouse is not where the draggable element is, even though if I move it by x pixels the draggable element moves by x pixel). I think the screen recording upload fail. Does it work perfectly on your side?

**Comment by Faisal-imtiyaz123** [comment]
@FelixMalfait 

https://github.com/user-attachments/assets/f50b1198-3586-4d74-b522-fba10e8c839a

**Comment by FelixMalfait** [comment]
@Faisal-imtiyaz123 the screenshot I posted is from the settings page. In your screenshot you're trying to reorder cards in a kanban, not to re-order the steps of a select field. Go to /settings/objects/opportunities/stage to edit the stage field for example :)
Thanks

**Comment by Faisal-imtiyaz123** [comment]
<img width="296" alt="Screenshot 2024-07-16 at 2 54 25 PM" src="https://github.com/user-attachments/assets/22178127-1096-4f37-bbb1-6ea1d88f6879">
@FelixMalfait I am sorry for misunderstanding the issue and taking up your time. This is how my settings look like, unfortunately don't have an `Object` tab

**Comment by FelixMalfait** [comment]
No problem. The tab is called "data model", what I gave was the url :)

**Comment by Faisal-imtiyaz123** [comment]
@FelixMalfait In addition to `views` and `opportunities stage` where else is re-ordering feature presen?
