### ISSUE TITLE
Global search doesn't bring up opportunities

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6104]
Someone that primarily uses opportunities complained about the fact that there was no efficient way to search them.

@Bonapara what objects should be displayed in the command bar? Should it be a setting?

**Comment by Bonapara** [comment]
I think we can add opportunities to the search results while maintaining the current behavior of displaying only three results per category when different sections are shown.

![CleanShot 2024-07-03 at 11 08 46@2x](https://github.com/twentyhq/twenty/assets/19412894/c0d9046d-fb25-4925-b873-4f3510fa3117)

I'm not sure about the current rule, but more results are displayed later, which works well:

![CleanShot 2024-07-03 at 11 09 45@2x](https://github.com/twentyhq/twenty/assets/19412894/e2e6fe78-45e7-4384-8dd4-73ca2796c69f)

**Comment by FelixMalfait** [comment]
Great! 

Long term vision on the backend is probably a table `commandBarLayout [id, objectId, position, maxRecords]`, which will be similar to another table for the left-menu `menuLayout [id, objectId, position]`
