### ISSUE TITLE
Dropdowns should have a max-height and a scroll bar

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6105]
I was shadowing a client that had created lots of field and the Filter dropdown was bigger than their screen's height.
We might (or might not?) want to set a max-height.
Also we want to make sure there's a scroll bar upon scroll (when I added a max-height directly in Chrome, the dropdown become scrollable but I couldn't see any scroll bar)

cc @Bonapara for recommandation

**Comment by Bonapara** [comment]
The max-height should be automatically determined based on the screen height. We should always maintain a **minimum** **20px bottom margin** between the menu and the screen bottom:

![image](https://github.com/twentyhq/twenty/assets/19412894/40a17142-8fcb-4dda-b7e9-56008c0f2736)

![image](https://github.com/twentyhq/twenty/assets/19412894/4671d2ad-edd0-4569-ba43-1d57e0b50c13)

**Comment by gowreesh369** [comment]
Is this issue open ? Can i take it?

**Comment by Bonapara** [comment]
Sure! Thanks for contributing @gowreesh369

**Comment by Faisal-imtiyaz123** [comment]
@cooldude6000 are you working here?

**Comment by Bonapara** [comment]
Just assigned you @Faisal-imtiyaz123, thanks for contributing!

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara Thanks for your quick response as always!

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara What should be scroll bar dimensions and color??

**Comment by Bonapara** [comment]
Hi @Faisal-imtiyaz123, we should use the default scroll bar! Thanks for handling this one ;)

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara The reason scroll-bar is not visible is because its background gets set to ```transparent```.
<img width="590" alt="Screenshot 2024-07-29 at 3 44 45 PM" src="https://github.com/user-attachments/assets/e2e154bf-fb1a-4d43-930b-b1e70b5909cd">
Now will have to override it . Which color should be used?

**Comment by Bonapara** [comment]
I see @Faisal-imtiyaz123, we should remove it indeed!

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara So will you provide a different color for the `scroll-bar` ryt? Is that what you mean. Pardon me if i misunderstood.

**Comment by Bonapara** [comment]
@Faisal-imtiyaz123 I think we should remove the "background-color" property for the scrollbar so the default browser color applies automatically.

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara I think the best fix to get a natural scroll bar behaviour and  which shows only on scroll is to remove the ```scroll bar styles ``` from the global styles.

**Comment by Bonapara** [comment]
@Faisal-imtiyaz123, where else are they used apart from menus?

**Comment by Faisal-imtiyaz123** [comment]
In ```DefaultLayout.tsx``` only  these styles are applied globally.
<img width="486" alt="Screenshot 2024-07-30 at 3 07 37 PM" src="https://github.com/user-attachments/assets/603ab764-876d-42aa-9dd5-b40141b51856">
These aren't then overriden anywhere. I think we should not remove these.

**Comment by Bonapara** [comment]
maybe @lucasbordeau will have an input

**Comment by lucasbordeau** [comment]
@Faisal-imtiyaz123 Here's how to do it : 
- All dropdowns are using the DropdownMenuItemsContainer component
- This component has a `hasMaxHeight` property which allows to add a scroll behavior
- Right now the max-height is hard coded at `188px`

We would like to refactor all the dropdowns of the app so that they stop at 20px from the bottom of the viewport and remove this hasMaxHeight props from DropdownMenuItemsContainer and the max-height from dropdown menu container.

Instead we should implement the size middleware from `floating-ui` :  https://floating-ui.com/docs/size 

Put the availableHeight in a react state and use it in a new props `height` in DropdownMenu. 

From here it should be straightforward to adjust CSS in sub components to have all the dropdowns behaving the same.

**Comment by Faisal-imtiyaz123** [comment]
@lucasbordeau I think we can set `max-height` using `Object-assign` directly . Is there a necessary need for `availableHeight` state and `height` props I might have missed??

**Comment by FelixMalfait** [comment]
When merging a PR for this, make sure it also solves #6864

**Comment by harshrajeevsingh** [comment]
@FelixMalfait I got this working. Can I raise a PR?

**Comment by martmull** [comment]
Reopening as the fix as been reverted due to side effects @harshrajeevsingh

**Comment by martmull** [comment]
@harshrajeevsingh you can create a new branch linked to that issue if you want. If you need to add back your previous fix, just revert the Revert "fix: dropdowns should have a max-height & padding from screen" commit in your branch
