### ISSUE TITLE
Date filter doesn't work well with month / year dropdown

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6106]
Changing the month/year work but it's not reflect in the component, only in the filter:

https://github.com/twentyhq/twenty/assets/6399865/de1cc427-600e-4a47-928b-1f9f6e77f16e

**Comment by Faisal-imtiyaz123** [comment]
@FelixMalfait can I work?

**Comment by FelixMalfait** [comment]
Sure! Assigned it to you. Thanks

**Comment by ijreilly** [comment]
Hey, while editing the filter, should we initiate the date picker with the date used in the filter or keep today's date?

I feel I would expect to find the date used in the filter but maybe that's not what we want.
https://github.com/user-attachments/assets/4047205f-7eca-40bd-b437-223740d3dccb

**Comment by Faisal-imtiyaz123** [comment]
@ijreilly Thanks for pointing it out. Let me see what @FelixMalfait has to say about it.

**Comment by FelixMalfait** [comment]
@ijreilly fully agree but I think it's not specifically related to the date field, it's for any filter - the value isn't passed. I've created an issue https://github.com/twentyhq/twenty/issues/6278
