### ISSUE TITLE
Deeplink or Permalink to Note or Task

### ISSUE THREAD

**Issue by mipmip** [twentyhq/twenty#6111]
## Scope & Context

Having a permalink to a note would allow to refer to this note from inside a task. or to link to this note inside another application.

## Current behavior

Currently it seems to be a pure javascript event which makes a note popup.

## Expected behavior

A share button which includes a copy url action would make it possible to use permalinks to notes or tasks.

![](https://github.com/twentyhq/twenty/assets/658612/2b7b6022-b08f-46a5-8e47-30a5dfe20a0c)

**Comment by Bonapara** [comment]
Hi @mipmip, that sounds like a good idea! I think we need to release the action menu first to start working on this one.

**Comment by FelixMalfait** [comment]
This would be great yes. This is linked to a bigger refactoring. Tasks should become standard objects like any others. @Bonapara has made designs for that already, relying on the standard table view and standard show page to display tasks, but this requires a significant amount of work.

**Comment by mipmip** [comment]
> This would be great yes. This is linked to a bigger refactoring. Tasks should become standard objects like any others. @Bonapara has made designs for that already, relying on the standard table view and standard show page to display tasks, but this requires a significant amount of work.

Sounds good. And notes too,I hope.

**Comment by FelixMalfait** [comment]
This was shipped! Thanks for the suggestion.
