### ISSUE TITLE
Default View Font Color and Reordering

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6114]
# Current Behavior

The default view font color is tertiary. 
We cannot reorder the default view.

![CleanShot 2024-07-03 at 17 40 30@2x](https://github.com/twentyhq/twenty/assets/19412894/be3f9c69-435d-4cff-afc4-d765dea398eb)

# Desired Behavior

The text color should be primary, like other views' title color. 
It should be possible to reorder this view. 

![CleanShot 2024-07-03 at 17 38 12@2x](https://github.com/twentyhq/twenty/assets/19412894/71857748-0577-4f70-ac22-1612068b2418)

Ensure this edit doesn't change the color of the non-movable item in the "Options > Fields" menu.

![CleanShot 2024-07-03 at 17 39 19@2x](https://github.com/twentyhq/twenty/assets/19412894/67c40fd8-8978-4be9-a176-2728754cc01a)

**Comment by Adithej** [comment]
Hi @Bonapara 

Is this the desired behavior you are looking for? Or are you expecting the default view eg: `All Companies` to be draggable as well?

Text color issue has been rectified

https://github.com/twentyhq/twenty/assets/32978688/88aef3f8-c6a3-4956-a3df-5601334c13ce

**Comment by Bonapara** [comment]
Hi @Adithej, thanks for your work! I was indeed expecting the default view to be draggable too.

**Comment by Adithej** [comment]
Thanks @Bonapara 

I am working on it but not that sure I will be able to, but still being optimistic.
The default gets draggable but it goes back to the last position. I am not being able to find the root cause.

On `ViewPickerListContent.tsx` I have made these changes.
```
<DropdownMenuItemsContainer>
        <DraggableList
          onDragEnd={handleDragEnd}
          draggableItems={viewsOnCurrentObject.map(
            (view, index) => (
              <DraggableItem
                key={view.id}
                draggableId={view.id}
                index={index}
                isDragDisabled={viewsOnCurrentObject.length === 1}
                itemComponent={
                  <MenuItemDraggable
                    key={view.id}
                    iconButtons={indexView?.id === view.id ? 
                      [{
                        Icon: IconLock,
                      },]
                      :
                      [{
                        Icon: IconPencil,
                        onClick: (event: MouseEvent<HTMLButtonElement>) =>
                          handleEditViewButtonClick(event, view.id),
                      },]
                    .filter(isDefined)}
                    isIconDisplayedOnHoverOnly = {indexView?.id === view.id ? false : true}
                    onClick={() => handleViewSelect(view.id)}
                    LeftIcon={getIcon(view.icon)}
                    text={view.name}
                  />
                }
              />
            ),
          )}
        />
      </DropdownMenuItemsContainer>
```
And the `handleDragEnd` seems okay but I belive the state is not getting upaded.

```
const handleDragEnd = useCallback(
    (result: DropResult) => {
      if (!result.destination) return;
      
      moveArrayItem(viewsOnCurrentObject, {
        fromIndex: result.source.index,
        toIndex: result.destination.index,
      }).forEach((view, index) => {
        if (view.position !== index) {
          updateView({ ...view, position: index });
        }
      });
      // console.log("view before", viewsOnCurrentObject)
    },
    [updateView, viewsOnCurrentObject],
  );
```
It would be helpful if I could find any leads that may help me fix this


https://github.com/twentyhq/twenty/assets/32978688/7413cf0a-4705-4cd7-b20e-e24b0b7968ab

**Comment by Bonapara** [comment]
Perhaps Lucas Bordeaux has some thoughts for you!

**Comment by Adithej** [comment]
Thanks @Bonapara  and @lucasbordeau if you have some thoughts about it , will be wonderful.

**Comment by Faisal-imtiyaz123** [comment]
@Adithej May you tell me if you are still working here?

**Comment by Adithej** [comment]
No @Faisal-imtiyaz123  if you are interested please have a look

**Comment by Faisal-imtiyaz123** [comment]
@Adithej Thanks for replying. Sure, I will take it up then

**Comment by Bonapara** [comment]
It was not implemented, or there was a regression. We should try to understand what happened @charlesBochet

**Comment by charlesBochet** [comment]
/oss.gg 300

**Comment by Bonapara** [comment]
@vamus092 do you think you will be able to open a PR today?
