### ISSUE TITLE
Remove "Compact View" Toggle from L2 Kanban Option Menu

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6116]
# Current Behavior

The "Compact view" toggle is visible on every Kanban sub-option menu (like the `Fields` menu and `Fields > Hidden Fields`).

https://github.com/twentyhq/twenty/assets/19412894/d17ef2f1-223c-495b-8fdc-8fff71ada3e3

# Desired Behavior

It should only be visible in the level 1 `Options` menu.

**Comment by saurabhsubham113** [comment]
Hi @Bonapara ,

I want to work on this.

**Comment by Bonapara** [comment]
Sure @saurabhsubham113, thanks for contributing!

**Comment by saurabhsubham113** [comment]
Hi @Bonapara 

one small help required. do you have any documentation on how to setup this monorepo project in local and run the twenty-front project.

It would be really helpful

**Comment by Bonapara** [comment]
Hi @saurabhsubham113, we have docs.twenty.com. If you have further questions, feel free to ask on Discord!

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara I would like to work.
