### ISSUE TITLE
Improve Error Message for Duplicate Field Creation

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6117]
# Current Behavior

When creating a field with the same name as an existing one, we get an error with the title "Error" and the description "Error."

https://github.com/twentyhq/twenty/assets/19412894/39c27718-d4f5-4323-be2b-9a00e8651d38

# Desired Behavior

The alert should be:

Title: `Can't create this field`
Description: `A field with a similar name exists`

**Comment by srikary12** [comment]
@Bonapara I'll be working on this

**Comment by Bonapara** [comment]
Sure @srikary12, thanks for contributing!

**Comment by srikary12** [comment]
The same goes for the step 1 too, I'll fix both of them :)

**Comment by srikary12** [comment]
If we create duplicate data objects, it shows the same error. It's not detailed.

**Comment by FelixMalfait** [comment]
Related: #4786

**Comment by srikary12** [comment]
@Bonapara I was occupied last week, will try to get this done by the end of the week.

**Comment by ijreilly** [comment]
This has been tackled in the meantime with #6100.
@srikary12 there are plenty of other issues if you are still keen to contribute - like the related issue #4786 :)
