### ISSUE TITLE
Reduce Field Creation Time

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6118]
# Current Behavior

Creating a field is taking around 7 seconds.

https://github.com/twentyhq/twenty/assets/19412894/e3e95701-817d-413c-a601-a24059b147dc

# Desired Behavior

We should reduce the loading time to under 2 seconds, as it currently feels like a bug.

**Comment by pacyL2K19** [comment]
@Bonapara
I am working on a linked issue to this one, could you please assign it to me?
A fix PR is available at -> https://github.com/twentyhq/twenty/pull/6204

**Comment by Bonapara** [comment]
Sure @pacyL2K19, thanks for contributing!
