### ISSUE TITLE
Open Last Seen View instead of the First View

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6125]
# Current Behavior

When navigating to an object, the view that appears first in the view switcher opens.

https://github.com/twentyhq/twenty/assets/19412894/3aa76a29-cffa-4476-b1e3-8fa1d04ec4ca

# Desired Behavior

We should open the last seen view instead.

**Comment by FelixMalfait** [comment]
Duplicate of https://github.com/twentyhq/twenty/issues/5949 - I'll close the older issue but you can refer to it for deeper technical instructions

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara May I work here.

**Comment by Bonapara** [comment]
Hi @Faisal-imtiyaz123, this task is better suited for a more experienced contributor, but thanks for asking ;) I've assigned you to some other issues you commented on.
