### ISSUE TITLE
Update Support Button to Menu

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6127]
# Current Behavior

Clicking the `Support` button opens the chat.

https://github.com/twentyhq/twenty/assets/19412894/4254e69d-91ef-4495-a695-6d3750c066f3

# Desired Behavior

Clicking the `Support` button should open a menu that allows users to either access the [user guide](https://twenty.com/user-guide) or contact support through the chat.

https://github.com/twentyhq/twenty/assets/19412894/f1cf50da-dbba-4a08-956d-1f7c1c53f9f4

**Comment by FelixMalfait** [comment]
On self-hosted instances, redirect Talk to Us to https://twenty.com/Book-a-call

**Comment by IlyasOsman** [comment]
I would like to work on this.

**Comment by FelixMalfait** [comment]
Thanks @IlyasOsman! Assigned

**Comment by KrishDave1** [comment]
Hey Felix I would like to work on this.

**Comment by FelixMalfait** [comment]
Hey @KrishDave1 - I think @IlyasOsman is already on it. In case he doesn't raise a PR within this week you could work on it but let's give him a shot :)

**Comment by IlyasOsman** [comment]
Thanks @FelixMalfait.  @KrishDave1 please go ahead and tackle the issue.

**Comment by KrishDave1** [comment]
@FelixMalfait Please assign this task to me

**Comment by FelixMalfait** [comment]
Thanks!

**Comment by KrishDave1** [comment]
Hey @FelixMalfait Just getting this error while trying to run frontend.Could you please guide here.

Command : npx nx start twenty-front --verbose


vite v5.0.10 building for production...
transforming...
error TS5023: Unknown compiler option '-'.

———————————————————————————————————————————————————————

 NX   Running target start for project twenty-front and 2 tasks it depends on failed

Failed tasks:

- twenty-ui:build

Hint: run the command with --verbose for more details.

**Comment by FelixMalfait** [comment]
@KrishDave1 Sorry, I'm not familiar with this error
