### ISSUE TITLE
How can i take the backup if my docker is shutdown 

### ISSUE THREAD

**Issue by muzzamilshaikh** [twentyhq/twenty#6129]
If my docker got shut down from the server then how could I get the backup data? What's the process to get back the Postgres data?
help me in this 

https://github.com/twentyhq/twenty/tree/5b4d2d989a3f79d1d500a3baa995acbcd6a8a441/packages/twenty-docker

**Comment by Bonapara** [comment]
Hi @muzzamilshaikh, this seems like a troubleshooting issue. You should ask on our [Discord](https://discord.com/invite/cx5n4Jzs57). Best, Thomas

**Comment by muzzamilshaikh** [comment]
I'm not able to accept the invite
