### ISSUE TITLE
keyboard shortcuts hijack inputs: In settings > data model > fields

### ISSUE THREAD

**Issue by McPizza0** [twentyhq/twenty#6133]
## Bug Description

When in Settings > Data model > Fields > Select > Edit
Pressing `"To` as a field name will navigate away from settings
A few other keyboard shortcuts also seem to do the same
and the letter `G` does not type in

https://github.com/twentyhq/twenty/assets/17185737/7cb42dec-6f4f-4fc7-98dd-fcf6ef4fcbe9

## Expected behavior

When an input field is selected, all keyboard shortcuts should be disabled

## Technical inputs

**Comment by FelixMalfait** [comment]
Oh that's bad :/

**Comment by FelixMalfait** [comment]
@lucasbordeau this is an annoying bug, would you mind taking a look? 
I was able to reproduce with him during a call.
Thanks @McPizza0 for the video!

**Comment by lucasbordeau** [comment]
Fixed by https://github.com/twentyhq/twenty/pull/6322

**Comment by lucasbordeau** [comment]
@McPizza0 Should be fine now.
