### ISSUE TITLE
Data Importer Shows Incorrect Unmatched Fields Count

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6138]
# Current Behavior

The data importer Select mapping displays "XX unmatched" even when all fields are matched.

https://github.com/twentyhq/twenty/assets/19412894/afc90b58-66cc-4119-8d7a-bdd990dfc9c3

# Desired Behavior

The data importer should dynamically display the number of unmatched Select fields. This number should decrease as new fields are matched.

Here is how the `react-spreadsheet-import` library that we use is working:

https://github.com/twentyhq/twenty/assets/19412894/20893701-bf0e-4e27-b1ba-0e39b39ceebd

**Comment by k-parihar** [comment]
I think I take this one up, can you provide the file or some sample data which you uploaded to replicate the same?

**Comment by Bonapara** [comment]
[exampleCSV.csv](https://github.com/user-attachments/files/16109594/exampleCSV.csv)

Here is a CSV file Sample!

**Comment by k-parihar** [comment]
When I tried importing csv I am not able to locate select option in UI can you guide me how I can reach that option in UI?

**Comment by Faisal-imtiyaz123** [comment]
@k-parihar u working on the issue? Cuz I  don't see it assigned

**Comment by k-parihar** [comment]
@Faisal-imtiyaz123 you can go ahead and work on it if you want, I was facing issues with wsl while running it on my machine.

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara  Just to clarify first, In people and companies , I go to options n import, then I import the exampleCsv but I don't see a `select` option Like in your recording. But in opportunities in options n import, I import the same exampleCsv and I see a field `stage` in the dropdown, like u had `select` in the dropdown , in the recording. I click on it, and get the same `match columns ` , with the same bug. So am I supposed to work here??

**Comment by Bonapara** [comment]
Hi @Faisal-imtiyaz123, I think you don't see the Select because there is no Standard Select field in Companies and People. You should first create a Select Custom field to have the ability to match the values of the CSV.
