### ISSUE TITLE
ERROR: Version in "./docker-compose.yml" is unsupported.

### ISSUE THREAD

**Issue by muzzamilshaikh** [twentyhq/twenty#6139]
im trying to run the twenty CRM in aws light sail  after doing the setup im getting this error 
"
ubuntu@ip-172-26-12-102:~/twenty/packages/twenty-docker$ sudo docker-compose up -d
WARNING: The STORAGE_S3_REGION variable is not set. Defaulting to a blank string.
WARNING: The STORAGE_S3_NAME variable is not set. Defaulting to a blank string.
WARNING: The STORAGE_S3_ENDPOINT variable is not set. Defaulting to a blank string.
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error be
cause you're using the wrong Compose file version. Either specify a supported version (e.g
 "2.2" or "3.3") and place your service definitions under the services key, or omit the 
version key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-
file/"
can someone help me how to fix it ? i didn't change anything in that file

**Comment by Bonapara** [comment]
Hi @muzzamilshaikh! Please ask on our Discord: https://discord.com/invite/cx5n4Jzs57 :)
