### ISSUE TITLE
Identifier Preview is Empty in Object Settings

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6143]
# Current Behavior

In the Object settings, the "Identifier preview" is empty.

![CleanShot 2024-07-05 at 18 33 58@2x](https://github.com/twentyhq/twenty/assets/19412894/4d6acaba-b78f-4539-85e8-7a21a51e1cf3)

# Desired Behavior

We should display the first record of the table as a sample in the identifier preview.

If there is no record yet, we should display placeholder content such as "Text" for a text field or "12345" for a number field.

![CleanShot 2024-07-05 at 18 37 03@2x](https://github.com/twentyhq/twenty/assets/19412894/19d0f5dc-ae29-410d-a5a4-daded0f0d716)

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara I would like to work here. Assign me Please.

**Comment by Bonapara** [comment]
Sure @Faisal-imtiyaz123, thanks for contributing!

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara Can you share the first record of your customs object?

**Comment by Bonapara** [comment]
@Faisal-imtiyaz123, it should be dynamic and work on any object!

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara I have got few questions regarding this issue. Should I message you via discord?
