### ISSUE TITLE
New Settings Layout

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6144]
# Current behavior

The settings layout differs from the app layout: The breadcrumb merges with the page title and there is no top navbar.

Having no breadcrumb will present some limitations tomorrow.
This also causes the top page CTAs to be unresponsive when scrolling down and the animation from the App to the Settings to be choppy.

![image](https://github.com/twentyhq/twenty/assets/19412894/8a70ee27-2852-460f-9999-b96bb51cdc03)

# Desired Behavior

![image](https://github.com/twentyhq/twenty/assets/19412894/554ee292-4cbe-47bb-aa0e-921ae656f4b6)

We want to introduce a revamped layout for the Settings pages featuring:

1. A new Back button to the app/content
2. A navbar breadcrumb for better navigation within the settings
3. A CTA zone that remains visible, even when scrolling
4. A page title
5. (Not to do in this issue) An "Advanced Settings" parameter that unlocks additional options, such as customizing API names (Dedicated issue: https://github.com/twentyhq/twenty/issues/6147)

![09a7d1d05f28280064f532adddfb79a08a9f7570ec67f44582f991577e5dfb17](https://github.com/twentyhq/twenty/assets/19412894/5c917b1a-ff0e-44b9-8a8f-6102ea274d73)

# Figma

All the Settings Layouts have been updated in the `⚙️ Settings - New Layout` Figma page:

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34845-125317&t=H5hfHOgNoulsToAq-11

The Navbar component is here:

![image](https://github.com/twentyhq/twenty/assets/19412894/742cb03e-e8e9-4fbf-b1f3-56aeca4d78a4)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=11519-270312&t=H5hfHOgNoulsToAq-11

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara The Advanced Mode Button has been made ryt?

**Comment by Bonapara** [comment]
Hi @Faisal-imtiyaz123, @martmull  did you make it?

**Comment by martmull** [comment]
You can go @Faisal-imtiyaz123

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara I haven't. I mistook #6147 as merged.

**Comment by Bonapara** [comment]
Hi @Faisal-imtiyaz123, thanks for your message! This issue requires an experienced contributor as it is quite significant. Maybe you can pick some other [Good First Issues](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee) first?

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara Thanks for replying. No worries!

**Comment by ijreilly** [comment]
Work has started on [this](https://github.com/twentyhq/twenty/commit/db54469c8a70d4dd02de0c80242c751bc2696d9b), but not everything was done
- breadcrumbs were moved but not always with the same padding in top and bottom, this should be fixed
- back button is left to be changed
- same for page titles
- Advanced part was not done yet **but is not to do in this issue**

@gitstart-twenty 
@Bonapara fyi

**Comment by Bonapara** [comment]
The design has been partially implemented. 

For 2) → Improve the vertical spacing and remove the icon to the left of the breadcrumb.

**Comment by charlesBochet** [comment]
@gitstart-twenty this ticket is important, would you have an ETA on it?

**Comment by gitstart-twenty** [comment]
Hello @charlesBochet this PR is under internal review and should be pushed by Tuesday

**Comment by Bonapara** [comment]
🎉 Thanks @ congrats @gitstart-twenty!
