### ISSUE TITLE
Avanced Settings: Custom API names for Object and Fields

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6145]
# Desired Behavior

Introduce the following system:

1) An Advanced Settings option on the bottom of the API & Webhooks Settings page that allows to sync or unsync all **labels** and **API names**:

![CleanShot 2024-07-15 at 10 53 25](https://github.com/user-attachments/assets/79eab3ea-ac74-4825-9fcf-817d856d8671)

2) Behavior on an object detail page when this sync setting is activated:

- C) and D) are deactivated (Read-only)
- Changing A) **always** changes B) and D)
- C) reflects the value of B), regardless of whether B) is overridden or updated by A)
- C) and D) field Info button (i) should inform the user that he should deactivate the Sync settings in Advanced Developer settings to set a custom API name 

Use a library like https://www.npmjs.com/package/pluralize to generate singular forms.

![CleanShot 2024-07-15 at 10 28 13](https://github.com/user-attachments/assets/d0541504-f9e2-4728-9f60-c02202505fbe)

3) Behavior on an object detail page when this sync setting is deactivated:

- Changing A) updates B)
- C) & D) are not impacted when A) or B) are updated
- C) & D) are activated and their value can be updated
- C) & D) field info button (i) should explain the constraints of the API names

4) Behavior on the Developer advanced Setting activation and deactivation:

- Deactivating the toggle should stop the synchronization, the API names should stay what they are.
- When reactivating the toggle, a for-each loop should iterate over every object to set the API names to match the object labels. C) should be updated with B) and D) should be updated with A)

5) Object creation

When creating a new object, even if the `Sync labels & API names` setting is deactivated, the API names should match the labels.

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara  Can I work?

**Comment by Bonapara** [comment]
Sure @Faisal-imtiyaz123, thanks for contributing!

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara Do I have to make this `Text Field` Component.

**Comment by Bonapara** [comment]
We should use the **standard text field** component but add a **yellow border and a wrench icon component**. This component will either have an absolute or relative position. The border's height should always match the height of the element it's applied to, and the wrench should always be positioned on top.

See #6146 for the "position: relative" of the yellow border and Wrench component.

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara pardon me but there is no directory` text-input` under @ui/input. If i import the snippet `import { TextField } from '@/ui/input/text-field/components/TextField';` it's not recognized. Sorry for asking a lot. I am new to the project.

**Comment by Bonapara** [comment]
Are you talking about this? https://storybook.twenty.com/?path=/story/ui-input-textinput--default

**Comment by Faisal-imtiyaz123** [comment]
Got it ! Thanks

**Comment by charlesBochet** [comment]
I'm not fully convinced by this feature, left a comment on the main thread here: https://github.com/twentyhq/twenty/issues/5491#issuecomment-2226833596

**Comment by Bonapara** [comment]
Replaced by https://github.com/twentyhq/twenty/issues/5491

**Comment by Bonapara** [comment]
Hi @gitstart-twenty, since the sync API names setting will be on the API & Webhooks settings page in advanced mode, we won't need to make the Sync API names an advanced settings. 

We can show it in blue as a result:

![image](https://github.com/user-attachments/assets/5c22f870-d3ef-4a5c-9953-8418bc98f0be)

**Comment by charlesBochet** [comment]
@gitstart-twenty @ijreilly @Bonapara 
I'm not a big fan of: 
- storing this at workspace level (we don't have a storage for it right now beside workspace table and keyValuePairs table but it feels off to put it in both table)
- having the for loop checking and updating all objects, this is a slow and risky operation and it can fail, it can be challenging to rollback in case of issues and display it properly to the user if we choose to go async

Could we instead keep this on the Object Edit / Field Edit page and keep it field or object level?

**Comment by ijreilly** [comment]
Merged with https://github.com/twentyhq/twenty/issues/5491
