### ISSUE TITLE
Avanced Settings: Custom API names for Select & Multi-Select Keys

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6146]
# Current behavior

Users cannot edit the API Keys of `Select` and `Multi-Select`

![image](https://github.com/twentyhq/twenty/assets/19412894/69f9db68-d811-4138-91ae-eeabc089bb56)

# Desired Behavior

![image](https://github.com/twentyhq/twenty/assets/19412894/3f5ec78e-1056-497b-a7dd-87a35b96d702)

Enabling the `Advanced Mode` in Settings for new Select fields should display a column that allows users to edit the Select API keys.

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34851-536975&t=H5hfHOgNoulsToAq-11

**Comment by lucasbordeau** [comment]
I suggest that we change the naming to API VALUES because API_KEYS is conflicting with the well known wording API Keys that allow people to authenticate to the API.

**Comment by Bonapara** [comment]
What about API_ID? Is it really "Values" @lucasbordeau?

**Comment by lucasbordeau** [comment]
Yes both work.
