### ISSUE TITLE
Settings Advanced Mode

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6147]
# Desired Behavior

We want to introduce a new `Advanced Settings` toggle allowing users to view advanced (often technical) settings. The goal is to reduce interface clutter.

The toggle should always be at the settings page bottom left. We want the following issues addressed before displaying it:

https://github.com/twentyhq/twenty/issues/6145
https://github.com/twentyhq/twenty/issues/6146

![image](https://github.com/twentyhq/twenty/assets/19412894/b8b45fab-ff31-4ae1-ba5b-5e50d715b70e)

# Component

![image](https://github.com/twentyhq/twenty/assets/19412894/a9fc41ff-6caa-4bd3-8ca7-c77051629c2e)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=11519-270312&t=H5hfHOgNoulsToAq-11

# Settings Navbar

Add a new Developers section that would have two sub-pages: 
- API & Webhooks
- Functions

![CleanShot 2024-09-11 at 15 29 59](https://github.com/user-attachments/assets/d8c2305a-a866-4a1d-b112-f6e854447709)

**Comment by prevar** [comment]
Hi, Please let me know if this issue is available. Can I can pick it up? Thanks.

**Comment by Bonapara** [comment]
Hi @prevar, this issue is available, but it should be toggled under a feature flag while we wait for the two mentioned issues to be completed.

**Comment by prevar** [comment]
Ok. Thanks I will wait for the 2 issues to be completed to start working on this issue.

**Comment by FelixMalfait** [comment]
Store this in localstorage (https://github.com/twentyhq/twenty/blob/9683a19287d62e23dcb91c256f7b74ca667fd11b/packages/twenty-front/src/utils/recoil-effects.ts#L7)

**Comment by ijreilly** [comment]
Let's kickstart this issue together when it is ready to be taken. I think we can start with the FE only behind a **feature flag**, that would cover 
1. the Advanced component feature here in the left bar
2. the front-end only for the first advanced feature we will have: https://github.com/twentyhq/twenty/issues/6145
<img width="368" alt="Capture d’écran 2024-09-11 à 15 40 49" src="https://github.com/user-attachments/assets/b7aaa09a-fce7-4408-970d-0e1673cb2e36">
To make the toggle work (show/hide "Api name" upon toggle, with an animation perhaps?)

@gitstart-twenty fyi for when you will start working on it. @Bonapara fyi

**Comment by gitstart-twenty** [comment]
Hello @ijreilly 
so, we would need to implement the toggle and use this API Name input to test the implementation of the feature, but just to show the feature working, right?

I imagine that in this case, we would just need to get the field name and display it on a disabled input, is that correct?
do we need to add any other part of the other issue?

Also, we could not find the designs in Figma, I think the link is broken, it redirects to this page:
![image](https://github.com/user-attachments/assets/3cc7a124-5fb6-4909-9434-c2ff0048a14b)

Hey @Bonapara 
could you provide the links for the toggle and for the feature mentioned above? Also, would be very nice if you could give us access to the dev mode on the Figma 🤝

**Comment by Bonapara** [comment]
### Toggle

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34851-536797&t=emUxzrvX6zNaHyLZ-4

### Navbar

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34845-235253&t=emUxzrvX6zNaHyLZ-4

Please get in touch with me on Discord for Dev mode access ;)

**Comment by gitstart-twenty** [comment]
Hello again @Bonapara 👋 
Currently we have this GitHub version component in the same place where the toggle would be implemented, we would like to confirm if we should remove the component or keep this along the toggle
![image](https://github.com/user-attachments/assets/9bf69e4a-4291-4601-9d64-e10faaffd4f5)

**Comment by Bonapara** [comment]
Hi @gitstart-twenty 👋 We should move the version to the bottom of the General Settings page. Thanks!

![image](https://github.com/user-attachments/assets/a7e9b33a-3ba8-430a-bcd6-bee4c05188c4)

**Comment by gitstart-twenty** [comment]
ok, thank you
