### ISSUE TITLE
Tab Navigation for Object Detail Page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6148]
# Current Behavior

To access an object's settings, you have to click on the three-dot menu in the right part of the object name banner. This is cluttered and unclear. We want to improve this display.

![3bfebc3f17f24c96b0cc8d82f3ff1037ac290f19b420e42bcd3e86120e914180](https://github.com/twentyhq/twenty/assets/19412894/762bde0f-7d4b-4bee-bb78-17a717f20839)

# Desired Behavior

We want to introduce tab navigation on the Object detail page. We should use the same component that we started using for the "Email and Calendar" advanced settings. The first tab should be "Fields" and the second tab should be "Settings."

![image](https://github.com/twentyhq/twenty/assets/19412894/a1229f53-e54f-470d-8324-d14b058cdf54)

**Comment by abdulqdaer-q** [comment]
Hey @Bonapara
can u assign me to this

**Comment by Bonapara** [comment]
Sure @abdulqdaer-q, thanks for contributing!

**Comment by Faisal-imtiyaz123** [comment]
@abdulqdaer-q Are you working on this?

**Comment by abdulqdaer-q** [comment]
@Faisal-imtiyaz123 
Hey Faisal, sorry I could not find the time to work on it yet, if you want to do it feel free to assign yourself, since I won't be available until next week 😞

**Comment by Faisal-imtiyaz123** [comment]
@abdulqdaer-q Thanks for replying!. @Bonapara Assign me this Please.

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara Do i just need to create the `Tabs UI component here` without content for `SettingsTab` . Also what is the icon for `Fields`?

**Comment by Bonapara** [comment]
Hi @Faisal-imtiyaz123 the Tabs UI component already exists: https://storybook.twenty.com/?path=/story/ui-layout-tab-tablist--tab-list-display

 The icon for fields is `list-details` https://tabler.io/icons/icon/list-details

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara What I meant to say is that do I just incorporate `Tab List` component without any content for the `Settings Tab`. So clicking on `Settings Tab` would essentially not show different content than the `Fields Tab`.

**Comment by Bonapara** [comment]
Oh, I understand! The `Settings tab` should include the object details that are currently here:

![image](https://github.com/user-attachments/assets/b5749feb-395b-48cb-baf8-1ac8ad878178)

Something like this: (Don't take into account the advanced mode)

![image](https://github.com/user-attachments/assets/c889eb5a-e113-4d76-a122-d518628b3d32)

**Comment by Bonapara** [comment]
@Faisal-imtiyaz123 are you still on it?

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara Yes! I have been lately quite busy. I will try to do this asap!

**Comment by JorgeGraciaViveros** [comment]
Hi @FelixMalfait  ! I am currently working in a group of 5 students from Carnegie Mellon taking a software engineering course and our final project is to contribute to an open-source repo. Our project has multiple checkpoints and will be due on December 8 (meaning our PR will take longer to open). Would it be possible for us to be assigned to this issue (or any issues that you think would be a good fit)? Thanks!

**Comment by FelixMalfait** [comment]
I think this has been done already!
