### ISSUE TITLE
Settings Advanced Mode

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6149]
# Desired Behavior

We want to introduce a new `Advanced Settings` toggle that will allow users to view advanced (often technical) settings. The goal is to reduce interface clutter.

The toggle should always be at the settings page bottom left. We want the following issues addressed before displaying it:

https://github.com/twentyhq/twenty/issues/6145
https://github.com/twentyhq/twenty/issues/6146

![image](https://github.com/twentyhq/twenty/assets/19412894/b8b45fab-ff31-4ae1-ba5b-5e50d715b70e)

# Component

![image](https://github.com/twentyhq/twenty/assets/19412894/a9fc41ff-6caa-4bd3-8ca7-c77051629c2e)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=11519-270312&t=H5hfHOgNoulsToAq-11

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara can i work on this?

**Comment by Bonapara** [comment]
Sorry, @Faisal-imtiyaz123 Made a duplicate of #6147
