### ISSUE TITLE
Fix Nested Bullet Points Rendering with Proper Padding

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6183]
# Current Behavior

In the [Changelog](https://twenty.com/releases), Lists with nested bullet points are not rendered properly.

No nested bullet points:
![image](https://github.com/twentyhq/twenty/assets/19412894/a548627e-d459-4498-83eb-e13b4418f03b)

Whereas the IDE text contains some:
![CleanShot 2024-07-09 at 18 11 51](https://github.com/twentyhq/twenty/assets/19412894/416f6d07-92a5-4975-9c6e-6b6ad0c383ba)

# Desired Behavior

There should be padding to indicate that a bullet point is nested under another point.

![CleanShot 2024-07-09 at 18 10 05](https://github.com/twentyhq/twenty/assets/19412894/8685f27f-9f96-4c00-a1a9-8a8e6c60a439)

**Comment by Adithej** [comment]
Hi @Bonapara , Is this how you wanted ? 

# Advanced Email and Calendar Settings

We've introduced advanced settings for email and calendar management:
-  **Auto-Create Contact Options:** Choose when an email interaction should automatically create a contact. Options include:
    - People I've sent emails to and received emails from
    - People I've sent emails to
    - Don't auto create contact

-  **Email Exclusions:** Ability to exclude non-professional emails (e.g., Gmail, Outlook) and team emails (e.g., support@, team@) from being synced to the CRM.
-  **Calendar Events:** Auto-contact creation settings are now available for calendar events as well.

**Comment by Adithej** [comment]
I am happy to work on this

**Comment by Bonapara** [comment]
Thanks @Adithej 🙏

**Comment by saloni0419** [comment]
@Bonapara can you please assign me this issue

**Comment by Bonapara** [comment]
@saloni0419 I believe @Adithej is on it, maybe you can have a look on Other [Good First Issues](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)

**Comment by sarthaklaptop** [comment]
Hello @Bonapara  can I work on this issue !!

**Comment by Adithej** [comment]
Hi, I think it's already merged

https://github.com/twentyhq/twenty/pull/6195

**Comment by Bonapara** [comment]
Closing the issue then, thanks @Adithej!
