### ISSUE TITLE
Cannot add People/Company etc from web-interface when No Data(New Setup)

### ISSUE THREAD

**Issue by mnbro** [twentyhq/twenty#6186]
Hi,

For all versions : v0.21.x of twentycrm, after a fresh Install if i delete all pre-generated records for an Object, one cannot add any data from web interface, only using REST/GraphQL API.

When the buttons '+' or '+ Add Object' are clicked nothing happens.

Is there any other info that I can offer in order this bug to be solved ?

**Comment by FelixMalfait** [comment]
Sorry closing since it's an old issue and it's probably linked to a setup issue at the time.
