### ISSUE TITLE
Ability to reset rating field

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6191]
It's a bit frustrating that once you've set a rating it's impossible to come back to the previous state where it wasn't sett.

<img width="289" alt="Screenshot 2024-07-10 at 10 33 51" src="https://github.com/twentyhq/twenty/assets/6399865/919db3bc-f6c5-4943-bb74-dd4fa9dda8f0">

cc @Bonapara, should be add a "X" or something like that?

**Comment by FelixMalfait** [comment]
@Bonapara I don't feel that it's intuitive vs a X displayed on hover, but if you think it's the best path OK

**Comment by Bonapara** [comment]
Replaced by a fresh issue: https://github.com/twentyhq/twenty/issues/6224
