### ISSUE TITLE
Hard to deploy stack on portainer

### ISSUE THREAD

**Issue by elefantemarketing** [twentyhq/twenty#6211]
Following the documentation, docker compose yaml into twenty instructions, but erro 404 everytime, blank screen.

I will send the docker-compose file that i tried to deploy into container

[version-twenty-check-it.txt](https://github.com/user-attachments/files/16170120/version-twenty-check-it.txt)

**Comment by elefantemarketing** [comment]
version: "3.9"

services:
  change-vol-ownership:
    image: ubuntu
    user: root
    volumes:
      - server-local-data:/tmp/server-local-data
      - docker-data:/tmp/docker-data
    command: >
      bash -c "
      chown -R 1000:1000 /tmp/server-local-data
      && chown -R 1000:1000 /tmp/docker-data"
    networks:
      - network_public
    deploy:
      restart_policy:
        condition: none

  db:
    image: twentycrm/twenty-postgres:latest
    volumes:
      - db-data-new:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
      POSTGRES_DB: exampledb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U exampleuser -d exampledb"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    networks:
      - network_public

  server:
    image: examplecrm/example:latest
    volumes:
      - server-local-data:/app/packages/example-server/.local-storage
      - docker-data:/app/docker-data
    environment:
      PG_DATABASE_URL: postgres://exampleuser:examplepass@db:5432/exampledb
      SERVER_URL: http://api.example.com
      FRONT_BASE_URL: http://example.com
      MESSAGE_QUEUE_TYPE: pg-boss
      ENABLE_DB_MIGRATIONS: "true"
      SIGN_IN_PREFILLED: "true"
      STORAGE_TYPE: s3
      STORAGE_S3_REGION: us-east-1
      STORAGE_S3_NAME: example
      STORAGE_S3_ENDPOINT: http://s3.example.com
      ACCESS_TOKEN_SECRET: example_access_token_secret
      LOGIN_TOKEN_SECRET: example_login_token_secret
      REFRESH_TOKEN_SECRET: example_refresh_token_secret
      FILE_TOKEN_SECRET: example_file_token_secret
    depends_on:
      - change-vol-ownership
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/healthz || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    networks:
      - network_public
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.example.com`)
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.services.api.loadbalancer.server.port=3000
      - traefik.http.routers.api.service=api

  worker:
    image: examplecrm/example:latest
    command: ["yarn", "worker:prod"]
    environment:
      PG_DATABASE_URL: postgres://exampleuser:examplepass@db:5432/exampledb
      SERVER_URL: http://api.example.com
      FRONT_BASE_URL: http://example.com
      MESSAGE_QUEUE_TYPE: pg-boss
      ENABLE_DB_MIGRATIONS: "false" # it already runs on the server
      STORAGE_TYPE: s3
      STORAGE_S3_REGION: us-east-1
      STORAGE_S3_NAME: example
      STORAGE_S3_ENDPOINT: http://s3.example.com
      ACCESS_TOKEN_SECRET: example_access_token_secret
      LOGIN_TOKEN_SECRET: example_login_token_secret
      REFRESH_TOKEN_SECRET: example_refresh_token_secret
      FILE_TOKEN_SECRET: example_file_token_secret
    depends_on:
      - db
      - server
    restart: always
    networks:
      - network_public
    labels:
      - traefik.enable=true
      - traefik.http.routers.front.rule=Host(`example.com`)
      - traefik.http.routers.front.entrypoints=web
      - traefik.http.services.front.loadbalancer.server.port=3000
      - traefik.http.routers.front.service=front

volumes:
  docker-data:
  server-local-data:
  db-data-new:

networks:
  network_public:
    external: true

**Comment by aficiomaquinas** [comment]
i believe the API and SERVER_URL might be missing the external :3000 port? I was never able to make it work with traefik though also I believe that twenty expects a PORT env var... at least in my case I had to use it.

**Comment by aficiomaquinas** [comment]
the first step would be to know if you are able to make it work without traefik on a given port, because that 404 might be traefik or might be the twenty server, better to take that away and once you get it working without traefik then maybe put that on top? A bit more information on that 404 would be useful too.

**Comment by elefantemarketing** [comment]
traefik should be able to turn this port available?

- traefik.http.services.front.loadbalancer.server.port=3000

**Comment by aficiomaquinas** [comment]
does the stack work without traefik?, do you get 404 without traefik?, at this point is difficult for me to give you advice because i don't have enough information, relevant logs from the server, the http 404 response response contains anything else? what are the headers of the response?, etc. As i said i wasn't able to make twenty run with traefik myself but a good first step is debug without. once you make it work without it will be easier to find out why traefik doesn't work

**Comment by elefantemarketing** [comment]
i tried with cloudflared services cutting of traefik and dos not work

**Comment by aficiomaquinas** [comment]
removing cloudflare and just confirming that it works on a port would be the first step i think. is your server configuration making you unable to not use traefik? afaic you can skip traefik if you bind the address of the server to other than currently used by traefik? Still very little information to be able to make any suggestions on my part.

**Comment by aficiomaquinas** [comment]
just a quick glance at your traefik suggests to me that you are missing the server base url, not just the api...
      - "traefik.http.routers.api.rule=Host(`${SERVER_SUBDOMAIN}.${EXTERNAL_DOMAIN_NAME}`) || Host(`${API_SUBDOMAIN}.${EXTERNAL_DOMAIN_NAME}`)"

**Comment by aficiomaquinas** [comment]
again, without additional information, logs, http responses, chrome inspector logs, from your part it's gonna be tough to throw anything that could help you...

**Comment by elefantemarketing** [comment]
version: "3.9"

services:
  change-vol-ownership:
    image: ubuntu
    user: root
    volumes:
      - server-local-data:/tmp/server-local-data
      - docker-data:/tmp/docker-data
      - change-vol-ownership_data:/var/www/html
    command: >
      bash -c "
      chown -R 1000:1000 /tmp/server-local-data
      && chown -R 1000:1000 /tmp/docker-data"
      && chown -R 1001:1001 /app/db-data
    networks:
      - network_public
    deploy:
      restart_policy:
        condition: none

  db:
    image: twentycrm/twenty-postgres:latest
    volumes:
      - db-data-new:/var/lib/postgresql/data
      - db_data:/var/www/html
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ficticious_user
      POSTGRES_PASSWORD: ficticious_password
      POSTGRES_DB: default_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ficticious_user -d default_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    networks:
      - network_public

  server:
    ports:
      - "3001:80"
    image: twentycrm/twenty:latest
    volumes:
      - server-local-data:/app/packages/example-server/.local-storage
      - docker-data:/app/docker-data
      - server_data:/var/www/html
    environment:
      PG_DATABASE_URL: postgres://ficticious_user:ficticious_password@db:5432/default_db
      SERVER_URL: https://api.ficticious.example.com
      FRONT_BASE_URL: https://ficticious.example.com
      MESSAGE_QUEUE_TYPE: pg-boss
      ENABLE_DB_MIGRATIONS: "true"
      SIGN_IN_PREFILLED: "true"
      STORAGE_TYPE: s3
      STORAGE_S3_REGION: us-east-1
      STORAGE_S3_NAME: ficticious_bucket
      STORAGE_S3_ENDPOINT: http://s3.ficticious.example.com
      ACCESS_TOKEN_SECRET: UjmxZcFoIca2SUKVYkIdIsIO0IR9dFB9JkjQes82fz8
      LOGIN_TOKEN_SECRET: S3nfOCdPD31VOBN9zt2sGFZUOqbiWIwr2iRZfKHrT-I
      REFRESH_TOKEN_SECRET: PZi_g3lDjBURW_zIlIRNlt1WZSsCutgF7BUX-Sx6kuM
      FILE_TOKEN_SECRET: 2bER-mnJlkeRaU2qlZZR2EUVwU_oSV49kmWQ2UwFa6E
    depends_on:
      - change-vol-ownership
      - db
    healthcheck:
      test: curl --fail http://localhost:3000/healthz
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    networks:
      - network_public
    
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token=eyJhIjoiY2Y4NzlkZmI1NmZjYmU1NTdmOTY5MmNlODY4Y34325325k3MTBjYWEtNDIxMy00MmZmLTk2NGUtOGJjN2Q5MjFjODJkIiwicyI6ImZpY3RpdGlvdXNfdG9rZW4ifQ235
  
  worker:
    image: twentycrm/twenty:latest
    volumes:
      - worker_data:/var/www/html
    command: ["yarn", "worker:prod"]
    environment:
      PG_DATABASE_URL: postgres://ficticious_user:ficticious_password@db:5432/default_db
      SERVER_URL: https://api.ficticious.example.com
      FRONT_BASE_URL: https://ficticious.example.com
      MESSAGE_QUEUE_TYPE: pg-boss

      ENABLE_DB_MIGRATIONS: "yes" # it already runs on the server

      STORAGE_TYPE: s3
      STORAGE_S3_REGION: us-east-1
      STORAGE_S3_NAME: ficticious_bucket
      STORAGE_S3_ENDPOINT: http://s3.ficticious.example.com
      ACCESS_TOKEN_SECRET: UjmxZcFoIca2SUKVYkIdIsIO0IR9dFB9JkjQes82fz8
      LOGIN_TOKEN_SECRET: S3nfOCdPD31VOBN9zt2sGFZUOqbiWIwr2iRZfKHrT-I
      REFRESH_TOKEN_SECRET: PZi_g3lDjBURW_zIlIRNlt1WZSsCutgF7BUX-Sx6kuM
      FILE_TOKEN_SECRET: 2bER-mnJlkeRaU2qlZZR2EUVwU_oSV49kmWQ2UwFa6E
    depends_on:
      - db
      - server
    restart: always
    networks:
      - network_public

volumes:
  change-vol-ownership_data:
    external: true
    name: change-vol-ownership_data
  server_data:
    external: true
    name: server_data
  db_data:
    external: true
    name: db_data
  worker_data:
    external: true
    name: worker_data
  docker-data:
    external: true
    name: docker_data
  server-local-data:
    external: true
    name: server-local_data
  db-data-new:
    external: true
    name: db-data-new

networks:
  network_public:
    external: true
    name: network_public
[_twenty_worker.1.apk6cdtj95pulc3jgkmyzhnmc_logs.txt](https://github.com/user-attachments/files/16188264/_twenty_worker.1.apk6cdtj95pulc3jgkmyzhnmc_logs.txt)
[_twenty_server.1.w6rpocsstvbg6ahuf6jgkfnya_logs.txt](https://github.com/user-attachments/files/16188265/_twenty_server.1.w6rpocsstvbg6ahuf6jgkfnya_logs.txt)
[_twenty_db.1.o4istlx1xmsgkuoguvph4wi79_logs.txt](https://github.com/user-attachments/files/16188266/_twenty_db.1.o4istlx1xmsgkuoguvph4wi79_logs.txt)
