### ISSUE TITLE
Link to navigate to object settings is broken

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6213]
Steps to reproduce:
1. Create a new object called "Test 2"
2. Go to that object's list view
3. Click on "Customize Fields"
<img width="663" alt="Screenshot 2024-07-11 at 07 45 54" src="https://github.com/twentyhq/twenty/assets/6399865/8d738045-f2fb-41d1-9cc9-fe52e3043cac">
4. You'll get a 404 because it redirects to http://localhost:3001/settings/objects/test2 instead of http://localhost:3001/settings/objects/test-2

<img width="708" alt="Screenshot 2024-07-11 at 07 46 47" src="https://github.com/twentyhq/twenty/assets/6399865/a63331eb-a26e-43a8-b90e-3659cedcac37">

We probably hardcoded the url and passed the wrong variable. We should let the Router build the url if possible and share a common logic between the 2 page. Do something as clean/robust as possible.

**Comment by rostaklein** [comment]
Ah, sry @saloni0419 Ive fixed this in the meantime https://github.com/twentyhq/twenty/pull/6228 hope you dont mind and will take another issue 😉
