### ISSUE TITLE
Graph Button in Data Model Settings Blends with Background

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6223]
# Current behavior

In `Settings > Data model`, the Graph button is indistinguishable from the background.

![CleanShot 2024-07-11 at 17 35 55](https://github.com/twentyhq/twenty/assets/19412894/6a22f81d-29aa-41fb-8383-1035c0cb52e7)

# Desired Behavior

Use the Floating button instead:

https://storybook.twenty.com/?path=/story/ui-input-button-floatingbutton--catalog

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara Please assign me. I raised a P.R on the last assigned one.
