### ISSUE TITLE
Reset Rating field to "No Value" on Star Re-click

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6224]
# Current Behavior

Once a rating field value is set, it's impossible to return the field to its "no value" state.

https://github.com/twentyhq/twenty/assets/19412894/cd7e3391-78bd-4797-a584-7c28707beb62

# Desired Behavior

Clicking again on the selected star should reset the field to its original "no value" state.

For instance, if the field is set to 3, clicking again on the third star should reset the field to "no value."

**Comment by saloni0419** [comment]
@Bonapara can i work on this issue

**Comment by Bonapara** [comment]
Sure @saloni0419, thanks for contributing!

**Comment by devansh-m12** [comment]
is it still open i would like to work on this issue ?

**Comment by saloni0419** [comment]
@devansh-m12 i am currently working , I will let you know if I am able to solve then

**Comment by Ashmash100** [comment]
Hi @Bonapara,

I have worked out a solution for this issue. I noticed that @saloni0419  is currently working on it. If the issue does not get closed, I am ready to create a PR with my solution.

**Comment by Ashmash100** [comment]
> Hi @Bonapara,
> 
> I have worked out a solution for this issue. I noticed that @saloni0419 is currently working on it. If the issue does not get closed, I am ready to create a PR with my solution.

@Bonapara shall I create a PR?

**Comment by Bonapara** [comment]
Hi @Ashmash100, yes you can create a PR as it's been 3 days, we will merge the first one! Thanks
