### ISSUE TITLE
Creating records of custom data models with the UI is not possible

### ISSUE THREAD

**Issue by janbiasi** [twentyhq/twenty#6231]
## Bug Description

It is not possible to add an item for custom defined data models (at least with the UI, API not tested yet). 
However, adding records to predefined data models (eg. company, opportunity or people) works without any issues. 
I'm not sure if this is a potential regression issue caused by the latest release [v0.21](https://github.com/twentyhq/twenty/releases/tag/v0.21.0).

Let me know if I can assist by providing more details or run more tests.

## Expected behavior

It should be possible to add records of custom data models when using the _"Add a MyModel"_ button.

## Technical inputs

- I'm running the latest `v0.21` image without a worker on a VPS with debug mode enabled
- There are no logs in the console, literally no feedback 
- There are no pending/failed network requests
- I've tried to replicate this on the demo instance, but login seems broken
  `relation \"workspace_1ylwcbp5eqhp9ac9lt1eyvofz.workspaceMember\" does not exist`

**Comment by Jank1310** [comment]
Same for me (https://discord.com/channels/1130383047699738754/1260859941682544651):

> After adding a new custom object I'm not able to add new records for the new custom object. 
Also the table view doesn't show the columns and when selecting "Kanban" in the add view dialog the dialog just closes.
If I add the new Invoice custom object as a relation to company, I'm able to add new invoices using the company detail dialog.
Everything works fine with 0.20.0

**Comment by janbiasi** [comment]
Update from the maintainers on [discord](https://discord.com/channels/1130383047699738754/1260859941682544651/1261986394956496936):
> This has been fixed on main and will be part of v0.22 release tomorrow 🙂

**Comment by janbiasi** [comment]
Everything's working again with [v0.22.0](https://github.com/twentyhq/twenty/releases/tag/v0.22.0), thanks!
