### ISSUE TITLE
Webhook - Add Title or Description field

### ISSUE THREAD

**Issue by skyfox675** [twentyhq/twenty#6236]
Hi team!

Requesting a field be added to the webhook object for "title" or a "description" to help identifying what each webhook is used for at a later time. If these could be displayed in the list of webhooks in the Settings page that would be really helpful!

Thanks!

**Comment by FelixMalfait** [comment]
Thanks for the suggestion!

We don't want to make the creation process more complex but we can add an option `description` field when in edit mode like Stripe is doing.

<img width="601" alt="Screenshot 2024-07-17 at 12 28 36" src="https://github.com/user-attachments/assets/67f3164d-db4a-418b-b134-084bf84b3aab">

<img width="570" alt="Screenshot 2024-07-17 at 12 33 42" src="https://github.com/user-attachments/assets/8236c871-dd92-4c3e-8d0c-33005d692be1">

(placeholder = (Optional))

**Comment by FelixMalfait** [comment]
Related: #6302

**Comment by abdulqdaer-q** [comment]
@FelixMalfait 
Hey Felix can you assign me on this

**Comment by FelixMalfait** [comment]
@abdulqdaer-q thanks!

**Comment by abdulqdaer-q** [comment]
Created PR at #6327
