### ISSUE TITLE
Unable to Use a Google Cloud Storage Bucket

### ISSUE THREAD

**Issue by awgneo** [twentyhq/twenty#6246]
## Bug Description

I cannot seem to get Twenty to use my GCP storage bucket.

## Expected behavior

Twenty should connect with my storage bucket.

## Technical inputs

Here is the error I am getting:

```
[Nest] 1  - 07/13/2024, 10:25:30 PM   ERROR [ExceptionsHandler] Invalid character in header content ["authorization"]
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["authorization"]
    at ClientRequest.setHeader (node:_http_outgoing:651:3)
    at new ClientRequest (node:_http_client:291:14)
    at request (node:https:358:10)
    at /app/node_modules/@smithy/node-http-handler/dist-cjs/node-http-handler.js:102:25
    at new Promise (<anonymous>)
    at NodeHttpHandler.handle (/app/node_modules/@smithy/node-http-handler/dist-cjs/node-http-handler.js:57:16)
    at async /app/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsResponseMiddleware.js:23:20
    at async /app/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:5:26
```

Here are my environment variables:

```
STORAGE_TYPE: s3
STORAGE_S3_NAME: thought-patterns-twenty
STORAGE_S3_REGION: auto # also tried "us"
STORAGE_S3_ENDPOINT: https://storage.googleapis.com
STORAGE_S3_ACCESS_KEY_ID: blah
STORAGE_S3_SECRET_ACCESS_KEY: blah
```

**Comment by awgneo** [comment]
Nevermind :) I was using jq to extract these secret values from a json file and jq adds a newline after each output by default (use -rj to avoid this).

**Comment by ruipoliveira** [comment]
Hi @awgneo .

I need to use the Google Cloud Storage on Twenty, but I have any questions:

-  The STORAGE_S3_NAME must have the bucket name?
- The STORAGE_S3_ACCESS_KEY_ID must have the "private_key_id" on service account json?
- The STORAGE_S3_SECRET_ACCESS_KEY must have the "private_key" on service account json?

Thanks!
