### ISSUE TITLE
Support for multiple values in the Phone field

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6260]
# Current Behavior

Currently, our system allows for only a single phone number to be added to a phone field. However, individuals often have multiple phone numbers, which may vary significantly. To accommodate this, we need a more flexible solution than adding multiple fields like "Phone 2, Phone 3, Phone X."

# Desired Behavior

We should adapt our data structure to allow for multiple phone numbers in a single phone field, similar to our previous enhancement for multiple links. The proposed data structure is as follows:

```
phones {
  primaryPhone {
    number
    countryCode
  }
  additionalPhones 
}
```

This structure will enable us to store a primary phone and an array of additional phone numbers. The implementation should mirror the approach used in the [multiple links field update](https://github.com/twentyhq/twenty/issues/3607).

![CleanShot 2024-07-15 at 14 55 10](https://github.com/user-attachments/assets/aac742b6-2574-4a64-a688-8e8bbf2614d3)

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=28562-74913&t=hrDkyWQ3cs5iGjno-11

**Comment by charlesBochet** [comment]
Discuss with @ijreilly before tackling this one

**Comment by FelixMalfait** [comment]
Closing the issue as the PR was merged. @gitstart-twenty please create a new issue if they are any followups to do! Thanks!
