### ISSUE TITLE
Support for multiple values in the Email field

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6261]
# Current Behavior

Currently, we only allow a single email address to be added to an email field. However, individuals often have multiple email addresses, which may vary significantly. To accommodate this, we need a more flexible solution than adding multiple fields like "Email 2, Email 3, Email X."

# Desired Behavior

We should adapt our data structure to allow for multiple email addresses in a single email field, similar to our previous enhancement for multiple links. The proposed data structure is as follows:

```
{
   emails {
     primaryEmail 
     additionalEmails (array)
   } 
```

This structure will enable us to store a primary email and an array of additional email addresses. The implementation should mirror the approach used in the [multiple links field update](https://github.com/twentyhq/twenty/issues/3607).

![CleanShot 2024-07-15 at 15 02 39](https://github.com/user-attachments/assets/835c080e-81dd-4e38-baa4-622514e28bea)

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=28562-75025&t=hrDkyWQ3cs5iGjno-11

**Comment by charlesBochet** [comment]
Discuss with @ijreilly before taking this one

**Comment by gitstart-twenty** [comment]
Hello @ijreilly 👋 
Could you provide more details about this task? 
Such as which files should we pay attention to, how should the data structure change be done, and other general advices for this task? This other [issue](https://github.com/twentyhq/twenty/issues/6260) also involves the same type of feature, could you also clarify what should be done in the phone field, if there is any difference? Thank you in advance.

**Comment by ijreilly** [comment]
Some technical hints here

1.  (PR 1) **Introduce new “Emails” composite field type** (similar to “Links”). After this step is merged it is no longer possible to create custom field with the “old” email/phone type, but they are still part of the created standard fields, are still displaying correctly etc.
- Create the new field type (`FieldMetadataType.Emails`)
- Handle field display (inspiration: `LinksFieldDisplay`)
- Handle field update (inspiration: `LinksFieldInput`)
- Prevent creation of new fields with "Email" type ([example PR](https://github.com/twentyhq/twenty/pull/6237/files))
- To test: reset of db, creation of a new workspace, creation and filling of emails and phone...

2. (PR 2) **Update standard fields of type "Email" to the new type**. After this step is merged, newly created workspaces will directly benefit from the new types, while the existing workspaces need to have their migration to the new type done before they can have their metadata synchronized again; so this should only be merged and deployed when we are ready to do the migrations (step 3).
- Update standard objects' standard fields of type Link. I think you only need to update person's email field here, updating type from Email to Emails. ([example PR](https://github.com/twentyhq/twenty/pull/6372/files))

3. (PR 2 - same as step 2) **Write script to replace "email" fields with "emails" fields, handling the data migration**
- Example [migration script](https://github.com/twentyhq/twenty/blob/main/packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-migrate-link-fields-to-links.command.ts) - [full PR](https://github.com/twentyhq/twenty/pull/6332/files).
- This type of command is now usually added to a group of commands that need to be run to allow for the upgrade to a new version of twenty, eg [upgrade:0-23](https://github.com/twentyhq/twenty/blob/main/packages/twenty-server/src/database/commands/upgrade-version/0-23/0-23-upgrade-version.command.ts). You can probably add this to a future 0.24 command as this will not be ready by the time we release 0.23. For instance for 0.23 the command to run is `yarn command:prod upgrade-0.23`
- We want to migrate the current value of email field to the new fields' `emails.primaryEmail`
- To test: migration of data, sync-metadata on migrated workspaces, running command multiple times of the same workspace that initially required a migration, running command simulating errors to ensure rollback is working correctly

**Comment by prateekj117** [comment]
@charlesBochet @ijreilly @Bonapara Can I take the (PR 1) part of this? If you are on a deadline, let me know. I can take this up at priority.

**Comment by Bonapara** [comment]
Sorry @prateekj117 @gitstart-twenty will handle this one :)

**Comment by ijreilly** [comment]
Hi @gitstart-twenty 
You will also need to adapt messaging sync for this work,.
I added [documentation about it](https://github.com/twentyhq/twenty/discussions/6464):

_(...)
**Notions**
(...)
2. Messaging and calendar sync 
Users can synchronize data from their gmail account (“Settings” > “Account” > “Emails”), which will trigger the creation of People and Company records based on the emails and events. If changes are brought to some fields’ column names of fields used in the gmail synchronization operation (ex: Company’s domainName field), a change needs to be made not to break the synchronization process by allowing the fill of the column for both their deprecated and new names. ([example PR: check create-company-and-contact.service.ts](https://github.com/twentyhq/twenty/pull/6410/files#diff-959d5bea9da3bc1019c034766c3041b93fb21c3918d4363c47e7681316337958): if the domainName field is still of type “Text”, fill the “domainName” column; if it is of type “Links”, it means the migration has been performed already, and we should now fill “domainNamePrimaryLinkUrl” column).
To test this feature locally, in addition to running your server, you need to 

Run a worker: npx nx run twenty-server:worker

Launch the crons (only once):

npx nx run twenty-server:command cron:messaging:messages-import

npx nx run twenty-server:command cron:messaging:message-list-fetch 

npx nx run twenty-server:command cron:calendar:calendar-event-list-fetch_

Contacts are created with emails so the code needs adaptation.
Example of adaptation: https://github.com/twentyhq/twenty/pull/6410 in create-company-and-contact.service.ts.
Do not hesitate to ask for help on this

**Comment by lucasbordeau** [comment]
@BOHEUS This the typical case where we E2E tests would be of great help, especially for step 3.
