### ISSUE TITLE
Ability to pick a relation when creating a record on Kanban Boards

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6266]
# Current Behavior

When creating an opportunity from the Opportunity Kanban board:
1. I click on "New."
2. A menu opens, allowing me to choose which company to associate with my opportunity.
3. The opportunity is created with the company relation field directly associated with the correct company.

When creating a record on a regular Kanban board:
- The card is directly created and I have to specify the relations afterwards from the dedicated field on the card.

# Desired Behavior

We should either:
- Remove this specific logic on Opportunities
- Refacto this feature to be linked with `Required relationships`

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara Sorry I couldn't understand what exactly is required in the desired behaviour. Could you please explain a bit further.

**Comment by Bonapara** [comment]
Hi @Faisal-imtiyaz123, unfortunately, this issue is not ready to be picked up. It's here to log the issue, but we have not decided on a solution yet. Thanks!

**Comment by FelixMalfait** [comment]
I think we can close this for now because this is linked to the broader topic of "required fields" not just in the context of kanban/opportunities
