### ISSUE TITLE
Hide Navigation Tabs if Single connected Account

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6267]
We should hide the navigation tabs that allow switching between different email/calendar accounts when the user has only connected one account:

![image](https://github.com/user-attachments/assets/f1825c53-a606-4203-9bd8-3cd9ed4deda3)

![CleanShot 2024-07-15 at 17 01 58](https://github.com/user-attachments/assets/b8c3385c-5098-4bfa-a41f-193c6f57c36c)

**Comment by Adithej** [comment]
Hi, I am interested in working on this, please assign me

**Comment by Bonapara** [comment]
Sure @Adithej, thanks for contributing!

**Comment by ViditJain123** [comment]
I have created a pull request addressing this issue [here](https://github.com/twentyhq/twenty/pull/6277)

**Comment by prateekj117** [comment]
@charlesBochet CMIIR, but I think we can close this one as the related MR is already merged.

**Comment by Adithej** [comment]
Yes , it's been merged , refer : https://github.com/twentyhq/twenty/pull/6274
