### ISSUE TITLE
Method to merge Duplicates

### ISSUE THREAD

**Issue by aficiomaquinas** [twentyhq/twenty#6276]
## Scope & Context

I'm submitting a feature request for enabling users to merge duplicate person records in their workspace. This feature is important for maintaining clean and accurate data, especially in cases where partial information about a person is entered separately, resulting in duplicate records. The primary focus is on consolidating all related data, including the full history, opportunities, tasks, notes, and other relationships associated with each person record.

## Current behavior

Currently, there is no built-in functionality to merge two person records. While users can manually copy basic information from one record to another, the main problem lies in consolidating the associated data:

- Historical data (e.g., interaction history, changes to the person record) is split between two records
- Related entities such as opportunities, tasks, and notes are attached to separate person records
- Timeline events and activities are distributed across multiple records
- Relationships with other entities (e.g., companies, projects) may be incomplete on each record

This fragmentation of data leads to:
1. Incomplete views of a person's history and relationships
2. Potential loss of critical information if one record is deleted
3. Inefficiencies in managing customer relationships with external systems via API
4. Inaccurate reporting and analytics

## Expected behavior

A comprehensive person merge feature that not only combines basic contact information but also consolidates all related data and maintains the full history of both records. This should be achievable through multiple interfaces: REST API, GraphQL, and User Interface.

The merge process should:
- Combine all non-conflicting information from both records
- Consolidate all related entities:
  * Opportunities
  * Tasks
  * Notes
  * Timeline events
  * Activity history
  * Relationships with other entities (e.g., companies, projects)
- Preserve the full history of both records, including past changes and interactions
- Update all related entities to reference the merged record

**Comment by aficiomaquinas** [comment]
As I go further down the investigation on how to deduplicate persons in Twenty from my app through the API I think that it would be very useful to have company merging too.

**Comment by FelixMalfait** [comment]
Thanks for the suggestion! We always try to build features in the most agnostic way possible so if we build it for People, we would also build it for companies, opportunities or any custom object at the same time. 

I think it's around 2 to 3 weeks or eng work to do this well. Backend is pretty simple but it would require significant frontend work (+ @Bonapara has not designed this )

Related: https://github.com/twentyhq/twenty/discussions/5244
