### ISSUE TITLE
Existing filter value isn't passed to the component to edit it

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6278]
# Current behavior

Filter is set to January 16, but when I open it, it's set to the default value (today):
<img width="361" alt="Screenshot 2024-07-16 at 10 17 41" src="https://github.com/user-attachments/assets/0b0a2f9f-2fc8-4eb6-bae4-27373bc8b837">

Same for other filter types, for example, amount:
<img width="216" alt="Screenshot 2024-07-16 at 10 18 28" src="https://github.com/user-attachments/assets/b2ee9aea-6f42-4f9a-92f0-f067d480acc3">

# Desired behavior

The filter amount should be pre-filled with 10. The input should be focused, and its text should be selected:

![CleanShot 2024-07-16 at 11 33 35](https://github.com/user-attachments/assets/4e2d4eb3-d509-4c67-bc01-8b8720517eb4)

**Comment by ViditJain123** [comment]
I have created a pull request addressing this issue [here](https://github.com/twentyhq/twenty/pull/6284)

**Comment by ehconitin** [comment]
@FelixMalfait can I work on this, if the issue is still open?

**Comment by FelixMalfait** [comment]
@ViditJain123 had given it a try but it seems the PR is still open so yes feel free to raise a new one taking into account the feedback :). Thanks

**Comment by ehconitin** [comment]
This is fixed in PR #6449 
Thanks

**Comment by ehconitin** [comment]
this issue can be closed ig. :)

**Comment by FelixMalfait** [comment]
Thanks @ehconitin!
