### ISSUE TITLE
Change amount to cents in pipeline table

### ISSUE THREAD

**Issue by emilienchvt** [twentyhq/twenty#628]
## Context
Since we introduced `amount` on `PipelineProgress `, we are showing currency amounts on the UI, but for now the currency does not show and there is no specific formatting in the UI. We need to align on this.

In the schema, `amount` is stored as an Int:
https://github.com/twentyhq/twenty/blob/164f9fd2e636030cb9e3973ab3242028c6467ba2/server/src/database/schema.prisma#L470

## Proposal

- **Convention:** I suggest we consider all currency amounts in our database are stored in cents. We may consider renaming it to `amountCents` but I think we can assume all amount fields are in cents in the DB from now.
- **Displaying amounts:** In the UI we'd have a util function `getAmountHumanReadable(amount: integer) => string` that we'll call every time we show a money amount.
- **Editing amounts**: We also have to provide an experience to enable users to edit formatted amounts smoothly. We can follow example 1 from [this set](https://cchanxzy.github.io/react-currency-input-field/).

## Question
Do we agree on this ?

**Comment by FelixMalfait** [comment]
Thanks! Closing https://github.com/twentyhq/twenty/issues/621 since your issue talks about currency and is more detailed

**Comment by lucasbordeau** [comment]
Ok for me.

Should we put a String instead of Int ? As it is may not be relevant to have a limit on the amount that will force us to handle all the associated edge cases.

**Comment by FelixMalfait** [comment]
From a product perspective, dealing with cents is a nice to have but not a priority ; it will probably be a requirement once we integrate [CPQ](https://www.salesforce.com/products/cpq/resources/what-is-cpq/) but that's not before 18+ months.

For text vs Int, can't we use Bigints? We'll need to compute average, sums, etc. so keeping a numeric format would make sense imo.

**Comment by FelixMalfait** [comment]
Fixed https://github.com/twentyhq/twenty/blob/5bdca9de6cd44ba70f12140f3920b46426792286/packages/twenty-server/src/metadata/field-metadata/composite-types/currency.composite-type.ts#L52
