### ISSUE TITLE
Fix post merge Revamp navigation bar

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#6285]
## Scope & Context

After merge of https://github.com/twentyhq/twenty/pull/6031, we have a lot of small fixes and refactors to do. We left them aside to release a working feature.

## Technical inputs

- [x] Use a recoil state instead of useFindRecordCursorFromFindManyCacheRootQuery
- [x] Refactor useRecordIdsFromFindManyCacheRootQuery to be used only if there's a cursor in recoil state
- [x] Refactor useRecordShowPagePagination to be generic with views
- [x] Merge useScrollToPosition and useScrollRestoration if possible, or refactor accordingly
- [x] Refactor RecordIndexContainer => move logic outside, useGeCurrent
- [x] Fix RecordShowPage story (see msw mocks, because requests changed)
- [x] Rename RecordIndexRecordChip to RecordIdentifierChip
- [x] Rename isFieldChipDisplay to isFieldIdentifierDisplay
- [x] Refactor findView and view: any
- [x] Refactor URL building in shared utils
- [x] Refactor ROW_HEIGHT extract

**Comment by lucasbordeau** [comment]
@FelixMalfait @charlesBochet 
- Scroll restoration is used on Boards only, and for now this feature is not implemented on Boards

Passing the cursor from table seems useless, because we can already have it from the return of the findOne request by using the same query variables than the passed view.

+ we decided to base the behavior on saved views only, thus passing a cursor seems redundant because we already have the view + the recordId

+ we have to request the record id if we don't come from a table page, thus requesting it when we come from the table page seems to be ok conceptually because the common denominator is the view+recordId not the cursor.

+ this way we'll always have the right position, no matter the cursor position (it should be the same but in any case)

**Comment by FelixMalfait** [comment]
The assumption that led to passing the parameter was that recomputing the position / converting the sorts into filters would be too expensive, but great if it's not!
