### ISSUE TITLE
Invalid URL Redirects for X and LinkedIn Fields

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6287]
# Bug description

X and LinkedIn fields accept links without "https," but they fail to redirect to the corresponding pages on X and LinkedIn.

For instance, if I enter: 
linkedin.com/in/tdesfrancs/

I get redirected to:
https://app.twenty.com/objects/linkedin.com/in/tdesfrancs/

**Comment by Adithej** [comment]
Hi I am happy to look into it, please assign me 😊
