### ISSUE TITLE
Update Default Icons for Table and Kanban Views

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6298]
# Current behavior

When creating a new view, the default icon is set to that of the object.

![CleanShot 2024-07-17 at 11 27 01](https://github.com/user-attachments/assets/708776df-6992-48e8-a305-f6285f79c021)

# Desired Behavior

We want the default icons to be:

| View type | Default Icon |
| ------- | ------- |
| Table view | https://tabler.io/icons/icon/table |
| Kanban view | https://tabler.io/icons/icon/layout-kanban |

**Comment by t007rushi** [comment]
Hey @Bonapara can you assign me this one

**Comment by Bonapara** [comment]
Sure @t007rushi, thanks for contributing!

**Comment by Ashmash100** [comment]
Hi @Bonapara can I also work on this issue?

**Comment by Bonapara** [comment]
Sorry @t007rushi closing this issue as it's been fixed on a side PR by @FelixMalfait.

**Comment by t007rushi** [comment]
No issue will pick another one 
this time first resolve it from now on 😄 
good way to contribute
