### ISSUE TITLE
Ability to filter on DATE fields

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6299]
While it's possible to filter on DATE_TIME fields, it's not currently possible to filter on DATE fields.

We should fix this.

<img width="423" alt="Screenshot 2024-07-17 at 11 45 40" src="https://github.com/user-attachments/assets/dab47f25-b413-43b0-b6a8-c9bcd0c918c9">

**Comment by Anubhav-2003** [comment]
Please assign it to me. Interested to work on it. Thank You.

**Comment by FelixMalfait** [comment]
Hey, might not be as easy as it looks! Feel free to raise a PR if you've understood how it works. Thanks!
