### ISSUE TITLE
I should be able to view the expiration date of an api key or edit the name

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6302]
Currently on the show page of API keys, I can't edit the name or view  the expiration date.
<img width="528" alt="Screenshot 2024-07-17 at 12 37 11" src="https://github.com/user-attachments/assets/f40abdbd-02bd-4301-a851-75d00a8a5779">

**Comment by Bonapara** [comment]
Figma: (Don't take into account the new layout - but just the page content)

![image](https://github.com/user-attachments/assets/db3d08a3-1fd7-4e9e-b523-f3f74055bef5)

**Comment by prateekj117** [comment]
@Bonapara Steps to solve this:
- Make a new component similar to `NameField` in `General`, but to update the API Key Name. New component would be inside `packages/twenty-front/src/modules/settings/developers/components/`
- Use the component inside the `SettingsDevelopersApiKeyDetail.tsx` to use the new component.
- We also need to make sure to reset the name in the Breadcrumb component.
- Display expiration date component too.

If this sounds good, let me know if I can take it up?

**Comment by Bonapara** [comment]
@martmull does it sounds good to you?

**Comment by martmull** [comment]
@prateekj117 think you just need to remove the disable in the name `<TextInput` of `SettingsDevelopersApiKeyDetail.tsx` and handle changes there using an autosave function that uses `useDebouncedCallback`, and add a disabled field that displays the expiration date (cannot be updated technically)

**Comment by prateekj117** [comment]
@martmull  Yup! The `NameField` implementation uses debounce. And I use the same kin do logic, remove the TextInput and use the new component instead, and add disabled field for expiration date.

**Comment by prateekj117** [comment]
If this sounds good, let me know and I will take it up. 

Just another point to add is, we will also have to update the Breadcrumb value.

**Comment by prateekj117** [comment]
Taking this up then! Thanks @martmull .

**Comment by prateekj117** [comment]
@martmull @Bonapara This is ready for review.
