### ISSUE TITLE
When scrolling horizontally, table header goes behind the first frozen column

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#6304]
## Bug Description

When scrolling horizontally, table header goes behind the first frozen column and becomes visible again when we scroll too much.
See video below

https://github.com/user-attachments/assets/a5b3f92b-dd83-488f-93c2-44a02919cf13

## Expected behavior

I should not see table header of other columns

**Comment by Weiko** [comment]
FYI @charlesBochet @lucasbordeau

**Comment by Antardas** [comment]
@Weiko , @Bonapara . 
Hello, I have created a PR on this issue.
https://github.com/twentyhq/twenty/pull/6315

**Comment by lucasbordeau** [comment]
FIxed by https://github.com/twentyhq/twenty/pull/6315
