### ISSUE TITLE
Number of records design on kanban

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6306]
# Current behavior

The number of records is shown in an oval at the right edge of the header.

![CleanShot 2024-07-17 at 15 07 26](https://github.com/user-attachments/assets/792b1896-de1b-4a55-8ef0-28ee838ce089)

# Desired Behavior

It should be displayed without a background immediately after the tag.

![CleanShot 2024-07-17 at 15 09 43](https://github.com/user-attachments/assets/430a8683-bca2-4dd5-9540-d8bf3586f713)

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=24955-194300&t=Qr4NRtxy8wlihUHN-11

**Comment by sanidhyasin** [comment]
Hey @Bonapara, I can work on this issue. Please assign this to me.

**Comment by t007rushi** [comment]
Hey @Bonapara can you assign me this one

**Comment by Bonapara** [comment]
Let's merge the first PR on this one as I assigned you both another issue! Thanks for contributing @sanidhyasin @t007rushi
