### ISSUE TITLE
Adjust empty tag style

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6307]
# Current behavior

The empty tag border width is `2px`
The empty tag border color is `#1F1F1F`
The empty tag color is `4C4C4C`

![CleanShot 2024-07-17 at 17 16 46](https://github.com/user-attachments/assets/80758786-6917-4e1f-ba5c-b4b231f8542f)

# Desired Behavior

Set the border width to `1px`
Set the border color to `Border: Stronger`
Set the tag color to `Text: Tertiary`

![CleanShot 2024-07-17 at 17 18 59](https://github.com/user-attachments/assets/7b7d81aa-3bbc-40eb-82dc-d3dd9fba34a3)

**Comment by sanidhyasin** [comment]
Hey @Bonapara, Please assign this issue to me.

**Comment by t007rushi** [comment]
Hey @Bonapara can you assign me this one

**Comment by CodeMaverick2** [comment]
Hey @Bonapara I would love to work on this issue

**Comment by ehconitin** [comment]
Hey @Bonapara, I couldnt find these empty tags.
Could you please tell me where to find them so that I could work on it?
:)

**Comment by Bonapara** [comment]
It should be a part of the `tag` React Component. It seems that it's not on Storybook. Can you add it in this PR?

**Comment by sanidhyasin** [comment]
@Bonapara on it.

**Comment by ehconitin** [comment]
@sanidhyasin do you need any help?

**Comment by sanidhyasin** [comment]
@ehconitin oh yeah, you can do this one

**Comment by Bonapara** [comment]
Ok, I'm assigning both of you! Thanks 🙏

**Comment by ehconitin** [comment]
@Bonapara 
Completely forgot about this issue :(
Its fixed in [PR 6465](https://github.com/twentyhq/twenty/pull/6465)

**Comment by ehconitin** [comment]
@FelixMalfait 
This is fixed
Could you please close this one too.
