### ISSUE TITLE
Need Setup section in Readme.md

### ISSUE THREAD

**Issue by CodeMaverick2** [twentyhq/twenty#6312]
**The current README.md lacks a dedicated setup section for new contributors. Adding one would greatly assist and streamline the onboarding process for new contributors.**
@Bonapara I would like to solve this issue should I go ahead

**Comment by Bonapara** [comment]
Hi @CodeMaverick2! Thanks for the suggestion, What do you think of our [Contributing rules](https://github.com/twentyhq/twenty/blob/62e9492e8bf77e502f25b7f161ec174522d58bf3/.github/CONTRIBUTING.md)

Did you know they existed? There is a small getting started guide inside.

**Comment by CodeMaverick2** [comment]
@Bonapara I know that exists it would be easier for new comers to be able to find it on readme it's more efficient if u have different opinions please say so

**Comment by Bonapara** [comment]
![CleanShot 2024-07-18 at 18 39 32@2x](https://github.com/user-attachments/assets/a1487f41-2b58-4e52-b93e-86038ebda2b0)

We could introduce some tabs at the top like https://github.com/calcom/cal.com is doing

**Comment by CodeMaverick2** [comment]
@Bonapara Like the section development they have right
