### ISSUE TITLE
In opportunities kanban don't show company picker if company field is disabled

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6316]
We hardcoded a way to create opportunities from the company:

<img width="217" alt="Screenshot 2024-07-18 at 08 07 19" src="https://github.com/user-attachments/assets/9aa99d33-45e6-4c8c-9d90-ead98e196311">

(see the dropdown with Qonto, etc)

This becomes an issue if someone wants to deactivate the Company field on Opportunities (usually to recreate a similar Person field because they are B2C and not B2B). We should only show this company picker if the Company field isn't deactivated. If not, we should fallback to the standard card creation process where a card appears immediately as you click new.

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara I would like to work here. Assign me please.

**Comment by Faisal-imtiyaz123** [comment]
?

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara Here I would require to know if the `company field is disabled or not` so should I use `useObjectMetadataItem` because I don't think there is a hook to get a particular `field` on an `object`. In case there isn't should I create a function `getFieldMetadataItem` in `useFieldMetadataItem.ts` with params `objectNameSingular and fieldName`.

**Comment by Bonapara** [comment]
@FelixMalfait maybe you have an opinion on this?

**Comment by FelixMalfait** [comment]
@Faisal-imtiyaz123 I don't think you need that. I didn't dig into it but I would have done something like 
```
objectMetadataItem.nameSingular === CoreObjectNameSingular.Opportunity && objectMetadataItem.fields.find(field => field.type === 'RELATION' && field.toRelationMetadata?.fromObjectMetadata.namePlural === CoreObjectNameSingular.Company && !field.isActive) &&
`````
In `
RecordBoardColumnCardsContainer` where there is 
```

{objectMetadataItem.nameSingular ===
              CoreObjectNameSingular.Opportunity ? (
                <RecordBoardColumnNewOpportunityButton />
              ) : (
                <RecordBoardColumnNewButton />
              )}
```

Note this code is *not* tested so it is most likely wrong!!! But you get the idea

**Comment by Faisal-imtiyaz123** [comment]
@FelixMalfait Oops! I missed that I already have access to `objectMetadataItem`. Thank you for the detailed answer.
