### ISSUE TITLE
Allow creating folders for file-management

### ISSUE THREAD

**Issue by Der-Feind** [twentyhq/twenty#6318]
## Scope & Context

```
I'm working in Twenty with Clients and I have to upload some files to them.
In my case, these are contracts, invoices and Audio-Files.
```

## Current behavior

A clear and concise description of what the current behavior is.
Please also add **screenshots** of the existing application.

```
On "Files" there is only the possibility to upload files.
```

## Expected behavior
Please also add **figma screenshots or figma links** if available

```
It would help, if I could create folders for files inside of each person/company, where I can store and manage the documents, that are important to this person or company.

That would make an impact in document management inside of twenty.
```

## Technical inputs

```
None.
```

**Comment by Bonapara** [comment]
I'm not sure we want to introduce folders in the short term. Instead, we could introduce a `"Files" field type` that allows uploading dedicated files in a specific field, providing another way to sort files. Would that work for you?

**Comment by Der-Feind** [comment]
Hard to say, as I sometimes have more than 1 file (contracts, invoices) for the clients to get uploaded into them.
A folder-like-structure would be awesome. Or an opportunity to label the files as "contract" or "invoice" for example.
