### ISSUE TITLE
make postgres-on-linux uses sudo unexpectedly

### ISSUE THREAD

**Issue by strk** [twentyhq/twenty#6319]
Following instructions in https://twenty.com/developers/local-setup I've ended up running `make postgres-on-linux` but that command used `sudo` and did administrative tasks, which wasn't anticipated.

In general, I think you should NEVER use sudo in scripts. It's tipical to need `sudo make install`, for example, so don't force that to users who are unaware. If you really want to provide it as a service, do implement a prompt

**Comment by BOHEUS** [comment]
I'll fix this since it's a simple task, @charlesBochet should I also delete the pg_graphql 1.4.2 and 1.5.1 since they're not used?
