### ISSUE TITLE
Record Page Navigation Arrows Cause Unnecessary skeleton loading

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6325]
# Current Behavior

When navigating from one record page to another using the record page navigation arrows, the page navigation I just clicked on displays a skeleton loading before being displayed again.

https://github.com/user-attachments/assets/4c21c091-09c6-47e3-a128-6f2087328952

# Desired Behavior

The navigation should always be visible. Clicking on a `Next/Previous` arrow should immediately increment the number without switching to the skeleton loading step.

**Comment by sanidhyasin** [comment]
Hey @Bonapara, I can work on this.

**Comment by sanidhyasin** [comment]
Hey @Bonapara 
I was looking into this issue and found that a skeleton loader is necessary as the title contains total number of companies and it takes time to load. If we remove the loader, it will look like this.
let me know if this is the desired behavior.

[Screencast from 2024-07-22 13-13-24.webm](https://github.com/user-attachments/assets/47f987ad-69d8-4923-95ba-c4768ed6e9e5)

**Comment by Bonapara** [comment]
Hi @sanidhyasin, thanks! Maybe we can keep the old total number (27) visible since it will usually stay the same and update it when we get the response if it changes?

**Comment by ehconitin** [comment]
Hey @Bonapara 
Could you review  [PR](https://github.com/twentyhq/twenty/pull/6367) for this issue.

:)

**Comment by sanidhyasin** [comment]
@Bonapara made a pr for this one, please review.

**Comment by Nabhag8848** [comment]
@Bonapara  can be closed as resolved in #6367 and #6405

**Comment by Bonapara** [comment]
Thanks @Nabhag8848 ;)
