### ISSUE TITLE
Replace entityId by recordId in the front end.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#6334]
## Scope & Context

We used entityId quite everywhere before we settled for recordId.

## Technical inputs

Now entityId doesn't correspond to our naming, so we should replace it by recordId and rename everything that has entityId in its naming : 
- Variables
- States
- Functions
- Hooks
- Etc.

**Comment by devansh-m12** [comment]
can i work on this issue ?

**Comment by FurquanAnwer** [comment]
@lucasbordeau Could you assign me this issue ?

**Comment by maheshcodes12** [comment]
I would love to work on this issue.

**Comment by ehconitin** [comment]
Hey @lucasbordeau,

I have created a pull request to address this issue. Please check it here: [PR #6355 ](https://github.com/twentyhq/twenty/pull/6355)

Thanks!
