### ISSUE TITLE
Refactor RecordInlineCell tree with a Context to avoid props drilling

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#6335]
## Scope & Context

All the hierarchy of RecordInlineCell components

## Technical inputs

We currently use a lot of props drilling, with components slicing props types of more than 10 properties, it's difficult to maintain and should be better placed in a context at the top of the hierarchy since those values are all readonly and defined when the component is mounted. 

Example in RecordInlineCellValue : 

```tsx
type RecordInlineCellValueProps = Pick<
  RecordInlineCellContainerProps,
  | 'displayModeContent'
  | 'customEditHotkeyScope'
  | 'editModeContent'
  | 'editModeContentOnly'
  | 'isDisplayModeFixHeight'
  | 'disableHoverEffect'
  | 'readonly'
  | 'buttonIcon'
  | 'loading'
  | 'showLabel'
  | 'label'
  | 'isCentered'
>;
```

We shouldn't have even one props because everything is passed at the top of the hierarchy.

Please note that it shouldn't be put in FieldContext as it is not in the domain of a Field but of RecordInlineCell which are two different abstractions.

**Comment by hansol-y** [comment]
Hi @lucasbordeau, can you please assign me for this issue? I'm interested in this one!
