### ISSUE TITLE
Upgrade guide - missing upgrade guide for versions previous to 0.21.0

### ISSUE THREAD

**Issue by mnbro** [twentyhq/twenty#6336]
## Scope & Context

Hi,

Upgrade guide is missing the guide for versions previous to 0.21.0.

## Expected behavior

Please include upgrade guides for all releases of twenty or include a match all.

Also, an upgrade guide for things not going as expected should be provided and common upgrade errors.

**Comment by Bonapara** [comment]
@ijreilly, what do you think of this?

**Comment by ijreilly** [comment]
Hey, I will close this issue for now -  we don't have the historic for previous upgrades, you would have to go through the [discord #general channel](https://discord.com/channels/1130383047699738754/1130383048173682821).
We don't have common upgrades errors either so far, but it's definitely a good idea to introduce a Troubleshooting section - keeping it in mind for when we will have things to add to it. 

@mnbro thanks for your feedback and your interest in twenty! We are still building our product, thanks for your indulgence :)
