### ISSUE TITLE
Setup Script / Docker Compose: Custom port does not work, attempting to access graphql on port 3000 still

### ISSUE THREAD

**Issue by scosman** [twentyhq/twenty#6341]
## Summary:

Attempting to access graphql on the wrong port.

## Steps:

1) Create a fresh install using the setup script [here](https://twenty.com/developers/section/self-hosting/docker-compose) (`bash <(curl -sL https://git.new/20)`):
2) it properly detects port 3000 is in use and prompts for another port
3) if updates the docker-compose file with the new port
4) Launch the applicaiton

## Expected

App to work

## Actual

App is just a white page. Web console show errors from trying to connect to graphql on port 3000 (this docker container isn't bound to that port, should be connecting on new custom port).

**Comment by Murkyskate** [comment]
Hey can you please share the screenshot of change that you have made for the ports?

**Comment by scosman** [comment]
I didn't make manual changes, this all came out of setup script. It makes the needed change in docker-compose, but not in .env

Setup Script:

<img width="615" alt="Screenshot 2024-07-19 at 12 06 40 PM" src="https://github.com/user-attachments/assets/fbfcc3ca-aeae-4add-b5d8-c0426cfc6f39">

Docker compose now has:
<img width="195" alt="Screenshot 2024-07-19 at 12 07 11 PM" src="https://github.com/user-attachments/assets/406af76d-11f4-41c7-a236-ab3da2d3cb22">

The issue - the .env file isn't updated so internally it's looking for the wrong port
<img width="325" alt="Screenshot 2024-07-19 at 12 08 39 PM" src="https://github.com/user-attachments/assets/326cd410-7ec8-45d9-9fc9-4f2da2ef5c44">

**Comment by Murkyskate** [comment]
Yeah so you have done it correctly try doing compose build again

**Comment by scosman** [comment]
Oh yeah. I resolved it. 

Just reporting that the setup script a bug. It has an option to set port that doesn’t work out of the box.

**Comment by speerer** [comment]
I have just experienced this bug: having set the port to a custom port during setup script, I loaded it up in-browser and was faced with a blank page. 

To solve it, I inspected the resource at  `/env-config.js` and realised that had port 3000 hardcoded. 

Solved with: 

```
~$ sudo docker exec -it twenty-server-1 /bin/sh
~$ vi  /app/packages/twenty-server/dist/front/env-config.js
```

...and then replace port 3000 with my custom port (in this case, 1999):

```
window._env_ = {
  "REACT_APP_SERVER_BASE_URL": "http://localhost:1999"
};
```
