### ISSUE TITLE
Add Back Navigation on detail page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#636]
I should be able to go back to the previous page (using react router history) with a Previous button
<img width="440" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/3804ee13-1ce0-4d57-813d-cffa4a2df11f">

**Comment by FelixMalfait** [comment]
How does this work with React router history? 
I feel like this needs backend work and is more than 2 points. I might be missing something?

**Comment by thaisguigon** [comment]
Associated Figma: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=4547-67611&mode=design&t=IKNWYrGlNFJYEqX1-0

- Should this be implemented only in the Company details page, or in all pages that use a TopBar?
- Where should the left chevron go when the nav is collapsed? Should the chevron be to the left or right of the "nav collapse" button? Right now it looks like this:

<img src="https://github.com/twentyhq/twenty/assets/3098428/2c26c9d4-6491-45ce-90dc-82c996c189a1" width=500 />

**Comment by Bonapara** [comment]
https://github.com/twentyhq/twenty/assets/19412894/0776f6be-51b2-43bf-9e44-5ee47d361949
