### ISSUE TITLE
Setup E2E testing

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#6360]
Twenty starts to have a lot of features and different use cases to test.

When doing refactors we usually try to test the app manually to make sure everything is working as expected.

But as it can now take a long time, we would like to have at least manual e2e tests to launch locally while developing or reviewing PR that involve refactors.

We already have integration tests with storybook and a lot of unit tests with jest, we also have visual regression testing with chromatic.

So e2e should focus on the most basics things to detect bugs : 
- Ensuring login works
- Ensuring there's no bug or errors when we visit each page
- Ensuring different workflows are executing without bugs or errors

Where e2e would compound efficiently is to offer us a minimal test coverage on a lot of small workflows because tests are easy to write.

We would see later how to integrate this in CI as it is not the main priority right now.

TODO : 
- [ ] Create a new package twenty-e2e-testing and install playwright following its documentation
- [ ] Setup environment variables for the base url, etc.
- [ ] Create a basic test that visits /objects/companies and that verifies there's a table shown

**Comment by BarryByte** [comment]
Hey @lucasbordeau I would like to take this issue, please assign it to me.

**Comment by pacyL2K19** [comment]
Any chance I can work on this issue?
@Bonapara @lucasbordeau

**Comment by lucasbordeau** [comment]
@BarryByte I'll assign you since you're first.

**Comment by Nabhag8848** [comment]
hey @BarryByte just checking, are you still working on it and made some progress? let us know if its available to take, I'm interested to work on this, also just want to mention, making **draft PRs** are great way to avoid this workflow. 

cc @lucasbordeau

**Comment by BarryByte** [comment]
sorry, currently i am unable to do take this forward. @lucasbordeau Please assign @Nabhag8848 for this issue. Thank you.
