### ISSUE TITLE
Improve `workspace:seed:dev` command to seed all field types

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#6364]
## Scope & Context

When seeding the database in dev mode.

## Technical inputs

Right now we use the seeds that were relevant months ago, but now we have multiple new field types like JSON, Address and Links, and we have to create them manually each time we want to test them while developing our features.

What would really help all the community is to seed people and company with all possible field types, and fill all rows with more demo data so our initial tables aren't so empty.

A nice good first issue !

**Comment by otutukingsley** [comment]
I'm interested in helping! can you assign this issue to me? @lucasbordeau

**Comment by Bonapara** [comment]
Sure @otutukingsley, thanks for contributing!

**Comment by prateekj117** [comment]
@otutukingsley If you have not taken it up yet or not planning to take it up, I can have a look into this?

@Bonapara I see in the command, we only seed for 2 companies, ```SEED_APPLE_WORKSPACE_ID, SEED_TWENTY_WORKSPACE_ID```, and not 5. Or am I missing something here?

**Comment by prateekj117** [comment]
Ohh and in the case of all companies and all people, it's 13 companies and 15 people. I think this is what you were talking about. My bad.

**Comment by prateekj117** [comment]
@Bonapara Can I take this up?

**Comment by Bonapara** [comment]
@otutukingsley are you still on it? Otherwise I'll assign you @prateekj117!

**Comment by lucasbordeau** [comment]
@Bonapara I'm assigning @prateekj117 as it would be nice to have it soon.

**Comment by prateekj117** [comment]
@lucasbordeau This is ready for review!

**Comment by prateekj117** [comment]
@lucasbordeau This gave me a good idea of the db structuring haha! Thanks for assigning this to me.
