### ISSUE TITLE
Fix RecordTableHeaderCell

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#6365]
## Bug Description

In RecordTableHeaderCell, there is a small gap where we can see components scrolling under it. 

<img width="133" alt="Capture d’écran 2024-07-22 à 12 34 30" src="https://github.com/user-attachments/assets/6becdd9e-4f45-46a0-9a46-e43006004d3b">

## Expected behavior

We want to find the right place to apply a CSS fix to avoid this, maybe see with borders because it seems to be only on the side of the checkbox component.

## Technical inputs

**Comment by ehconitin** [comment]
I could not reproduce this bug.
Would love to work on it though.

**Comment by Bonapara** [comment]
https://github.com/user-attachments/assets/ca30d247-ad69-4089-a772-2b86bc911db9

Really? I get it on every object list page too 🤔

**Comment by ehconitin** [comment]
Got it, will check on this issue.

**Comment by ehconitin** [comment]
Fixed the bug!
Please review [PR 6383](https://github.com/twentyhq/twenty/pull/6383)

**Comment by lucasbordeau** [comment]
Fixed by https://github.com/twentyhq/twenty/pull/6383
