### ISSUE TITLE
REST APIs Not Responding?

### ISSUE THREAD

**Issue by AddoSolutions** [twentyhq/twenty#6368]
## Bug Description

Not sure if I am mising some step here, but running twnty inside docker, tried 0.22.1 and 0.22.0, both timeout on any operation (ex. companies, people, etc. metadata/objects)

Am I missing something?

Tried via CURL, JS, and the provided API browsers. None work.

Nothing special, pretty generic setup

Tried enabling LOG_LEVELS and DEBUG_ENABLED on the server container, I don't even see the API requests generating logs.  But if I hit the open-api path it works fine

**Comment by Bonapara** [comment]
Hi @AddoSolutions, are you sure this is coming from Twenty and not your environment?

**Comment by AddoSolutions** [comment]
Fairly confident.  ex. If I remove one character from the `Authorization` header, it correctly sends an access denied.  Likewise, if I hit the `open-api/...` path that works as well.

I am thinking there is a bug somewhere that is breaking at one of the fields I added, but its not logging any errors so its hard to tell.

**Comment by Bonapara** [comment]
Maybe @martmull will have an idea about this.

**Comment by martmull** [comment]
Hey, @AddoSolutions @Bonapara yes we updated the way we compute depth parameter. Default value is 2 on latest release which causes the request to be very heavy and causes timeouts. A fix has already been merged to default depth to 1.
You can update to the latest commit, or set the depth parameter to 1 if you prefer to wait next release.
Sorry for the inconvenience

**Comment by Bonapara** [comment]
Is there another issue @martmull? Or should we keep this one?

**Comment by martmull** [comment]
Fix is already merged so we can close this issue a
