### ISSUE TITLE
When we add a custom field in data model, we should go back from origin page

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#6374]
## Scope & Context

Adding a custom field from a table by using the option dropdown.

## Current behavior

When we add a custom field, and we go back by exiting settings, we land on the default page (companies) instead of the page we went from

## Expected behavior

We want to go back to the page we added the custom field from, for example if we added the custom field from People table, we should go back on people table, same view, when we exit settings.

See how we use `setNavigationMemorizedUrl`

**Comment by Faisal-imtiyaz123** [comment]
@lucasbordeau I would like to work here.

**Comment by ehconitin** [comment]
@lucasbordeau 

Have fixed the issue.
Please check [PR 6399](https://github.com/twentyhq/twenty/pull/6399)

**Comment by Faisal-imtiyaz123** [comment]
@ehconitin I think the proper conduct is to ask one if one is  working on the issue when one has shown interest of working there even if it is unassigned. Otherwise it wastes one's time if he had made some progress on the issue.

**Comment by lucasbordeau** [comment]
@Faisal-imtiyaz123 Sure, @ehconitin seems to be very motivated right now so we're glad that he's putting so much efforts in ! 

There are old good first issues that are still there to be taken : 
- https://github.com/twentyhq/twenty/issues/5267
- https://github.com/twentyhq/twenty/issues/4832
- https://github.com/twentyhq/twenty/issues/4850

**Comment by ehconitin** [comment]
This issue can be closed, fixed in #6399
