### ISSUE TITLE
Align Workspace Switcher with Breadcrumb by Adjusting Height

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6375]
# Current behavior

The workspace switcher is not aligned with the breadcrumb.

![CleanShot 2024-07-23 at 15 13 30](https://github.com/user-attachments/assets/a4b944f5-1c0d-48fb-affa-0a268fd10427)

# Desired Behavior

The container height should be `32px` instead of `28px`

![CleanShot 2024-07-23 at 15 16 07](https://github.com/user-attachments/assets/f6f721d6-2dc5-46e4-aca2-0a1057c56d3e)

Also make sure to fix the Skeleton Loading alignment

**Comment by ehconitin** [comment]
Created  [PR6384](https://github.com/twentyhq/twenty/pull/6384).
Would you please look into it.

**Comment by shivam-bhushan** [comment]
Hey, I am working on this. I am new to open source and this repo so respecting your time here are a few questions I have. 
- Which file contains the workplace file switcher component? 
- When I make a pull request should I create a new branch and commit to that or  should I do it in main?

Sorry for the noobie questions but I really want to get this right.

**Comment by soumyo123-prog** [comment]
Hi @Bonapara , is this issue still open, if so, I would like to work on it.

**Comment by charlesBochet** [comment]
It seems to be solved, closing the issue :)

@soumyo123-prog feel free to take any other good first issue on the project!
