### ISSUE TITLE
I can rename a Pipeline stage + I can change color

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#638]
When I click on a column name, a menu should open so I can rename a column / stage. V1 is creating a menu with only one choice "New opportunity"

https://github.com/twentyhq/twenty/assets/19412894/a822ab46-c512-444a-9b51-b4a709ff66fd

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=4228-58301&mode=design&t=4w8xiymKy6QbuWXg-4

**Comment by Bonapara** [comment]
8px gap between the tag and the input

**Comment by FelixMalfait** [comment]
Is this issue dedicated to colors? I think name change has been shipped already?

**Comment by Bonapara** [comment]
Yes but not in the good way! This popup is the same that will be used in Opportunities settings so it's a double win
