### ISSUE TITLE
Create a command to add a userVar in the key value pair table for every account which needs to reconnect

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#6382]
- Loop on every workspace
- Get all the message channels and calendar channels in FAILED_INSUFFICIENT_PERMISSIONS
- Add the account to the key value pair table

**Comment by prateekj117** [comment]
@Bonapara Can I take this up?

**Comment by Bonapara** [comment]
@bosiraphael will handle it, thanks @prateekj117 ;)
