### ISSUE TITLE
Sporadic & Unusual Log-Outs While Active (Token Expired)

### ISSUE THREAD

**Issue by jmessy919** [twentyhq/twenty#6400]
## Bug Description

While active & logged in, I am periodically informed via a toast in the lower right about a token expiring. This immediately logs me out, and I am forced to enter my credentials again to access the platform. This occurred 2-3 times within 20 minutes. I am usually entering data into objects when this issue occurs.

## Expected Behavior

Users should have a default, consistent, and reasonable (subjective, I know) session length, and perhaps a configuration for overriding the default session length.

## Technical Inputs

Twenty was deployed using Docker via Portainer. No other Stacks/Containers in my Portainer instance have this issue.

I am using Vivaldi (a Chromium Browser) on Windows 11 Home.

**Comment by FelixMalfait** [comment]
Yes sorry about that, you can find the variable name here: https://github.com/twentyhq/twenty/issues/6598#issuecomment-2304017594
(and sorry for the late reply)

**Comment by FelixMalfait** [comment]
Closing in favor of #6598 but thanks a lot for the report, we need to fix this
