### ISSUE TITLE
Add box-shadow on column freeze

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#6403]
## Scope & Context

RecordTable, when scrolling horizontally.

## Current behavior

We don't have box-shadow on first column.

## Expected behavior

We want box-shadow on first column, as it is now refactored with new states that indicates if we are scrolling or not.

**Comment by ehconitin** [comment]
@lucasbordeau is the box shadow styles available in figma ?

**Comment by Bonapara** [comment]
@lucasbordeau, there appears to be a slight box-shadow, but I couldn't locate it while inspecting.
