### ISSUE TITLE
Inconsistent behavior in record navigation

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#6413]
## Bug Description

After refreshing on a showPage, the record navigation isn't correctly displaying the record position and total number of records.

https://github.com/user-attachments/assets/bf979ef7-dc4d-4131-a226-c4a19b9f7f40

## Expected behavior

The record navigation should correctly display the record position and total number of records.

**Comment by Bonapara** [comment]
I think the way we implemented it prevents the navigation count from being displayed through direct access, right @FelixMalfait?

**Comment by Bonapara** [comment]
I think it's an experienced contributor issue @jayprakash25, maybe you can grab another [Good First Issue?](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)

**Comment by jayprakash25** [comment]
Okay sure.

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara I would like to work.

**Comment by Bonapara** [comment]
This behavior is expected since we don't have the position on direct page access.
