### ISSUE TITLE
Update yarn start command and doc for worker

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6420]
As we deprecate the `sync` driver for worker we need to update the documentation and make it seemless for people to start the worker in a development environment (including adding it to `yarn start`)

**Comment by BOHEUS** [comment]
Is it still valid? @martmull added worker to `npx nx start` in #7820

**Comment by martmull** [comment]
Maybe we could check if doc is updated but worker starts when now nx start is launched

**Comment by BOHEUS** [comment]
I checked docs and there's no mention about `sync` driver in environmental variables, also checked pages in Backend development, no mention too but won't hurt if someone else also re-check

**Comment by FelixMalfait** [comment]
All good now, thanks! Closing
