### ISSUE TITLE
Redis cache store cannot be password protected

### ISSUE THREAD

**Issue by falko100** [twentyhq/twenty#6423]
Currently only REDIS_HOST and REDIS_PORT are available within the .env settings.
If we want to use a managed redis cluster for our self-hosted twenty, we need to enter a password.

**Comment by Bonapara** [comment]
@charlesBochet WDYT?

**Comment by charlesBochet** [comment]
@falko100 @Bonapara Happy to review a PR to add it to environment variables and leverage it in the code :) Looks a legit feature

**Comment by borel** [comment]
Hey @charlesBochet  , @Bonapara  hope everything fine .

It looks quite straight forward to do by adding REDIS_USERNAME and and REDIS_PASSWORD as var env and manage them in  [ cache-storage.module-factory, message-queue.module-factory, .env ]

I can work on it if needed

**Comment by charlesBochet** [comment]
@borel sure, go ahead! I'm happy to review and merge the PR as part of 0.24

**Comment by BalanaguYashwanth** [comment]
Hello @borel, 

Are you working on it ?

**Comment by borel** [comment]
hey @BalanaguYashwanth  , hope you well .
Yes i am .

**Comment by BalanaguYashwanth** [comment]
ok

**Comment by BalanaguYashwanth** [comment]
@borel Didn;t understand

**Comment by Bonapara** [comment]
Are you still on it @borel? Thanks for contributing

**Comment by borel** [comment]
Hey @Bonapara  ,  i started to contribute on it but i will probably don't have time in the coming days :(

https://github.com/twentyhq/twenty/pull/6745

**Comment by DurgaManikantaSai** [comment]
are anyone working on this? I want to work on it. May I ?

**Comment by Bonapara** [comment]
I think you can work on it, @DurgaManikantaSai, either starting from scratch or using @borel's draft!

Thank you for contributing :)

**Comment by DurgaManikantaSai** [comment]
@Bonapara I am working on It. Thanks

**Comment by DurgaManikantaSai** [comment]
@Bonapara I think some one known as @Weiko fixed this from @borel's draft. Should I have to leave this and search for some other suitable issues ?

**Comment by Bonapara** [comment]
@Weiko should we close it?
