### ISSUE TITLE
Enable Filtering by Sub-fields in Composite Fields

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6425]
# Current Behavior

Currently, applying filters on the sub-fields of a Composite field is impossible. For example, users cannot filter Addresses by specific attributes such as **Postcode** or **Country**.

# Desired Behavior

Introduce a submenu that allows users to navigate and select sub-fields for filtering. This submenu should appear above the current "Filter" menu and list all the sub-fields available within the Composite field.

Additionally, it **should include an option to filter by "Any" sub-field**, labeled as `Any XXX Field`. This feature would enable users to input a term like "Paris" and filter records containing _23 Paris Street_ and _Paris_ as a city.

![Filter submenu mockup](https://github.com/user-attachments/assets/24346faf-e1e5-4451-9f6f-99f698f2dbe4)

**Comment by parthiv360** [comment]
@Bonapara Can you please assign this to me?

**Comment by Bonapara** [comment]
Hi @parthiv360, thanks for your message! This issue is better suited for experienced contributors or the core team. Maybe you can pick a [Good first issue](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee) instead?

**Comment by pacyL2K19** [comment]
Hi @Bonapara 
I worked on this feature before, I would like to pick this one next

**Comment by Sohamnimbalkar07** [comment]
I am experienced full stack developer.
in my project. I worked on this type of functionality.
can you assign this issue to me?

**Comment by Bonapara** [comment]
Hi @pacyL2K19, assigning you, thanks for contributing! Sorry @Sohamnimbalkar07, he was first

**Comment by pacyL2K19** [comment]
Hi @Bonapara 
I am currently working on this ticket, per our last comments, can u formally assign it to me please? :)

**Comment by Bonapara** [comment]
Are you still interested in this issue, @pacyL2K19?

**Comment by pacyL2K19** [comment]
Hi @Bonapara 
Yes, still interested, I was on a leave but I am back to work
Please assign it to me

**Comment by Bonapara** [comment]
Thanks @pacyL2K19!

**Comment by charlesBochet** [comment]
@pacyL2K19 do you still plan to work on it or should we leave it to another contributor? :)

**Comment by pacyL2K19** [comment]
I'll be able to raise a PR this weekend @charlesBochet 
I am still on it

**Comment by lucasbordeau** [comment]
We need to tackle https://github.com/twentyhq/twenty/issues/7188 next
