### ISSUE TITLE
Clicking on the support dropdown immediately opens the support chat.

### ISSUE THREAD

**Issue by NitinPSingh** [twentyhq/twenty#6428]
## Bug Description

Bug: The support chat opens immediately upon clicking the support dropdown

![All Companies - Companies - Google Chrome 2024-07-28 17-29-45 (online-video-cutter com)](https://github.com/user-attachments/assets/0997264f-fc08-419c-9ec1-682f5941d855)

## Expected behavior

The correct behavior should display two options in the dropdown, with the support chat opening only when 'Talk to Us' is clicked.

**Comment by heysolomon** [comment]
I would like to like to work on this issue @NitinPSingh

**Comment by Bonapara** [comment]
Thanks for raising the issue @NitinPSingh 🙌 Assiging you @heysolomon, thanks for contributing!

**Comment by mittalsam98** [comment]
I would love to work on this

**Comment by Bonapara** [comment]
It's already assigned, maybe have a look to other [Good First Issues?](https://github.com/twentyhq/twenty/issues?)q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee

**Comment by NitinPSingh** [comment]
Apologies for the confusion. I actually resolved the issue yesterday before creating this GitHub issue. You can see my commit detailing the fix above. Linting issue was there , that i fixed in this commit
