### ISSUE TITLE
Add all TS files to front type checker.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#6436]
## Scope & Context

We often have problems with the CI for typecheck because stories and test files aren't tested by the typescript process during regular development.

This makes us lose time during code review and create work that could just be solved easily when the developer sees warnings in the console.

## Technical inputs

We want to integrate all typescript files in the typescript process that Vite uses for running the frontend, so that even test files TS errors appear during the normal development flow.

**Comment by Mihan786Chistie** [comment]
@lucasbordeau I would like to work on this issue
