### ISSUE TITLE
Problem with Babel, wyw-in-js and Linaria with Storybook

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#6437]
## Scope & Context

When we use Storybook, stories can take a long time to load, even crashing ou performance CI.

We have this warning when we open a story that contains a component that uses Linaria : 

```
[BABEL] Note: The code generator has deoptimised the styling of /Users/lucas/code/twenty/packages/twenty-front/node_modules/.cache/sb-vite/deps/@tabler_icons-react.js as it exceeds the max of 500KB.
```

## Technical inputs

Things to investigate : 
- Can we exclude @tabler-icons from Babel / wyw-in-js / the vite config of Storybook ?
- Is there a reproducible difference between non-Linaria components loading time and Linaria components loading times ?
- Is there something we can find related to this warning ?

**Comment by lucasbordeau** [comment]
@jayprakash25 Sure !

**Comment by jayprakash25** [comment]
On it

**Comment by jayprakash25** [comment]
I’m having some trouble setting up the project. I’m encountering a "JS heap out of memory" error even after increasing the memory limit to 8GB. It seems like there might be a memory leak. Any advice on where to look or how to fix this would be appreciated.![IMG_20240731_223541.jpg](https://github.com/user-attachments/assets/d944d4f3-6b68-4482-9180-3d8d188be71f)

**Comment by Nabhag8848** [comment]
Hey @jayprakash25 are you still working or its ready to take, were you able to setup, yet ?

**Comment by jayprakash25** [comment]
Hi @Nabhag8848 , I have found temporary fix for this an hour ago, trying to fix this. If the issue persists, I'll let you know.

**Comment by Nabhag8848** [comment]
Awesome @jayprakash25  lemme know if you have any trouble setting up, if your machine doesn't allow to setup. use gitpod,  https://www.gitpod.io/docs/introduction/gitpod-tutorial/1-start-your-workspace **50 hours free per month** is always free, if you require more than you need to pay but its lot already.

**Comment by jayprakash25** [comment]
@Nabhag8848, my system's causing the error again, unable to keep server and the front running for a long time. You can take up this one.

**Comment by Nabhag8848** [comment]
Cool, On it, started working. I would recommend to use gitpod, its very easy to run project as we have very few scripts to start development.

cc @lucasbordeau
