### ISSUE TITLE
Introduce ARRAY field type

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#6447]
# Current Behavior

Currently, our system allows to store MULTI_SELECT field types

# Desired Behavior

We would like to support an ARRAY field type which is very similar to MULTI_SELECT but which enables to store an array of TEXT. We should use the postgres ARRAY field type.

Regarding the technical inputs, it will be similar to https://github.com/twentyhq/twenty/issues/6260

<img width="357" alt="image" src="https://github.com/user-attachments/assets/0dde83c8-7749-4778-8ce2-0bd22b74730e">

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=29045-86637&t=uYTygUMcKhmPTRsa-0

**Comment by prateekj117** [comment]
@Bonapara Can I take this up?

**Comment by Bonapara** [comment]
@prateekj117 Sorry, this issue is not available for contributors. We will handle it :)

**Comment by prateekj117** [comment]
@Bonapara Cool. I see this is very similar to https://github.com/twentyhq/twenty/pull/5176/files

Let me know if I can help here!
