### ISSUE TITLE
Row Background Not Changing to Blue on Selection

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6461]
# Current Behavior

Selecting a row in an object table doesn't change the row background to blue. Only the checkbox background changes to blue.

![CleanShot 2024-07-30 at 17 46 30](https://github.com/user-attachments/assets/af1d53bc-65be-4e97-a548-74f27300a7c2)

# Desired Behavior

The entire row background should change to blue when selected.

![image](https://github.com/user-attachments/assets/7ac64991-b168-4e84-9e92-33023de674ac)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=33272-126639&t=LPiUwvAWRH2dg73a-11

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara Assign me this Please.

**Comment by Faisal-imtiyaz123** [comment]
Thanks @Bonapara .

**Comment by mittalsam98** [comment]
I would love to work on this next

**Comment by siddamvinay2001** [comment]
@Bonapara 
I raised a Pr to fix this issue can you please check [PR6479](https://github.com/twentyhq/twenty/pull/6479)
