### ISSUE TITLE
I can view timeline and add notes from board directly

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#648]

**Comment by Bonapara** [comment]
I'm not convinced we should to this but rather ease the navigation with the detail page. (Which will be easily accesible by clicking on a card and should be easily closable by clicking on "back")

**Comment by FelixMalfait** [comment]
@Bonapara  OK!  What part of the card should be clickable. Is it okay if it's just the title? Do you except the full card outside of editable fields to be clickable? (might be confusing?)

**Comment by Bonapara** [comment]
@FelixMalfait Just the title indeed! Also, I was thinking that one day we could add a nice timeline/show preview on card title hovers if needed.
