### ISSUE TITLE
Sidebar Tree View to Display Object Views

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6484]
# Current Behavior

Currently, object views are displayed in the sidebar with the same design as the objects themselves. This similarity in design causes confusion between objects and views.

![CleanShot 2024-08-01 at 10 50 07](https://github.com/user-attachments/assets/eed29bce-4058-48fe-a787-eb2540d212bb)

# Desired Behavior

We aim to introduce a `Tree view` in the sidebar to clearly distinguish between objects and views. This will help users easily identify which item is a view, which is an object, and which view is currently selected.

![CleanShot 2024-08-01 at 10 50 31](https://github.com/user-attachments/assets/26d0aa92-98ef-46a8-b259-0b615b5afc86)

# Behaviors

![CleanShot 2024-08-01 at 10 51 05](https://github.com/user-attachments/assets/1c7de77e-d518-4bbf-ba15-f935b8340b1a)

The line going to the selected element should be darker.

# Figma

Make sure to be pixel perfect ;)

![image](https://github.com/user-attachments/assets/a8fda8f2-f6ba-4225-bdd9-cca760369c8d)

![image](https://github.com/user-attachments/assets/5db579b1-740a-4cd6-a2b9-7740368d94bb)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=115-6252&t=7he5Wg1gGH5yGp53-11

![image](https://github.com/user-attachments/assets/0945fcfa-cc30-4c4e-9c2b-bf2d9c3a7247)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=36818-237476&t=7he5Wg1gGH5yGp53-11

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara Can I work here?

**Comment by Bonapara** [comment]
Sorry I missed your comment, @Faisal-imtiyaz123! We decided to handle it internally :)
