### ISSUE TITLE
Side Panel compact header

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6487]
# Current behavior

The Note side panel looks like the left column of the Record detail page

![CleanShot 2024-08-01 at 11 14 53](https://github.com/user-attachments/assets/7242f8db-7623-4ac5-bc2b-0560a1132d77)

# Desired Behavior

We want to introduce a more compact header that looks like this for **all side panel headers**

![image](https://github.com/user-attachments/assets/c21a9198-43c9-4db9-a201-aa849f5f26cb)

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=36824-90523&t=7he5Wg1gGH5yGp53-11

**Comment by ehconitin** [comment]
@Bonapara 
Could this be dealt with issue #6489

**Comment by Bonapara** [comment]
I think it might be better to separate them so the PRs are easier to merge. Do you see another reason?

**Comment by ehconitin** [comment]
Yea, its easy that way.
Assign this to me.
working on this also

**Comment by ehconitin** [comment]
@Bonapara 

Fixed in #6560
