### ISSUE TITLE
Going to settings from table and back from settings misredirect.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#6488]
## Scope & Context

Table and Settings

## Current behavior

1. Going to settings from a table "customize fields" button
2. Adding a custom field
3. Going back from settings
4. We land on the default page (usually companies)

## Expected behavior

1. Going to settings from a table "customize fields" button
2. Adding a custom field
3. Going back from settings
4. We land on the original table we went from

## Technical details 

See example with using `navigationMemorizedUrlState` in `useGetAvailableFieldsForKanban` hook

## Bonus

Please also fix the fact that we have to click two times on "customize fields" to go to settings

**Comment by ehconitin** [comment]
@lucasbordeau 

Did u check [PR 6399](https://github.com/twentyhq/twenty/pull/6399)
I fixed this issue there.

**Comment by FelixMalfait** [comment]
Thanks @ehconitin!
