### ISSUE TITLE
Rich Notes UX improvements

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6489]
# Current behavior

The Notes body doesn't fit well in the Content tab.
-  The content is not properly aligned both horizontally and vertically.
-  The "+" and dots menu take up too much horizontal space.
-  There are several UX flaws.

# Desired Behavior

### Remove the Plus icon, and add a "New Block" option in the `6 dots menu`

Update the style of the Delete and Change color buttons at the same time.

https://github.com/user-attachments/assets/1371ff47-75eb-48cf-9b4a-cc99a9735f5a

### Correct spacings

![CleanShot 2024-08-01 at 11 30 42](https://github.com/user-attachments/assets/db75dbc8-dae5-4236-b438-2154c6b497cc)

### Align icon and content

The content should be vertically aligned

![CleanShot 2024-08-01 at 11 35 18](https://github.com/user-attachments/assets/345c48c8-9b5c-4402-afcb-f5760151bc64)

### Update the style of the `6 dots icon button`

![CleanShot 2024-08-01 at 11 35 58](https://github.com/user-attachments/assets/b13f7905-9dd2-46b2-b4e0-cc0769cc91e1)

### Update the placeholder color to Text > Light

(It is lighter today)

![CleanShot 2024-08-01 at 11 37 44](https://github.com/user-attachments/assets/63592325-9a22-4956-bba1-4c868d4a991a)

# Figma

![image](https://github.com/user-attachments/assets/27e3778f-2d91-4d7b-88c8-1e5ecea3f1d9)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=36824-90376&t=7he5Wg1gGH5yGp53-11

**Comment by ehconitin** [comment]
@Bonapara 
I would like to work on this

**Comment by ehconitin** [comment]
@Bonapara 
Created [PR 6527](https://github.com/twentyhq/twenty/pull/6527) to address this issue
