### ISSUE TITLE
New field: Field type selection page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6496]
# Current behavior

Today, the field type select is lost in the middle of the new field page, even though it's an important setting.

![CleanShot 2024-08-01 at 16 23 51](https://github.com/user-attachments/assets/59a3bde8-e68b-4d18-a9c1-2c1ffe4ee82e) 

# Desired Behavior

We want to implement a two steps new field process, instead of the single page that we have today.

### 1. Choose your field type:

![image](https://github.com/user-attachments/assets/93b11516-5251-4d45-a92e-582a963032e8)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=36855-123514&t=INaINry7ZZWkjyD1-11

![CleanShot 2024-08-01 at 16 31 07](https://github.com/user-attachments/assets/166cb619-e848-4fe1-a095-5ee3b39dac7b)

↑ Some field types should only be accessible in advanced mode.

### 2. Customize your field (similar to today)

![image](https://github.com/user-attachments/assets/d6e018b3-344e-42ab-836e-6c7f08225737)

# Tech Specs

@lucasbordeau if you need to add some!

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara Can I work here?

**Comment by lucasbordeau** [comment]
@Faisal-imtiyaz123 I assigned you.

**Comment by ehconitin** [comment]
@lucasbordeau @Faisal-imtiyaz123  I am sorry but I am done with this issue since it was not assigned for a long time :)
Going to create a PR in a while
mb

**Comment by lucasbordeau** [comment]
@ehconitin Sure, I'll review your PR shortly.

**Comment by Faisal-imtiyaz123** [comment]
@ehconitin It's ideal to first ask If i was working here, since I expressed the desire to work here. Then you may go ahead and work. I could have been miday working and if u suddenly raised a PR., it would have nullified all my work. I hope you will be mindful next time.
