### ISSUE TITLE
Alignment issue on workspace switcher

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6499]
# Current behavior

The navbar is not aligned with the page content when there is no workspace Switcher:

![0c454b4743fa8dda76d41072841e54ffeb9023c001e7e2eeaa30e597f1524304](https://github.com/user-attachments/assets/dec8edc6-f222-49ef-98e7-090c1540e755)

# Desired Behavior

The content should be aligned, and the workspace name container should be 32px high, not 40px:

![CleanShot 2024-08-01 at 17 11 34](https://github.com/user-attachments/assets/2e1d203e-9a66-430d-9b86-8b3afd865a85)

![CleanShot 2024-08-01 at 17 13 34](https://github.com/user-attachments/assets/17c900fb-77b5-4b58-8bb8-ffe2b1948df3)

**Comment by t007rushi** [comment]
Hi @Bonapara, Can I work on this issue?

**Comment by Bonapara** [comment]
Sure @t007rushi, thanks for contributing!

**Comment by AbdurRahman2004** [comment]
Hey @Bonapara Can I Contribute to this one?
