### ISSUE TITLE
During local setup on WSL through docker, found an issue with NX

### ISSUE THREAD

**Issue by rudrasgithub** [twentyhq/twenty#6522]
If I command `npx nx start twenty-front`, the frontend is not running!!! Backend is running as expected

### Current behaviour:
error TS5042: Option 'project' cannot be mixed with source files on a command line.
Failed tasks:
- twenty-ui:build
- Hint: run the command with --verbose for more details.
![image](https://github.com/user-attachments/assets/39d553ac-0914-4aa2-94e4-7723a51c35a4)
### Expected Behaviour:
Should start running on the [localhost](http://localhost:3001/)

**Comment by FelixMalfait** [comment]
Hey, I've been trying to replicate but couldn't (I don't have access to a Windows laptop unfortunately).
I'll be closing this since the core team won't be able to solve it but if you find a fix, we'd be happy to merge the PR obviously! Thanks

**Comment by FelixMalfait** [comment]
Thanks for providing a resolution path @chandraguptgosavi 

cc @charlesBochet fyi if you have any idea 

https://github.com/twentyhq/twenty/pull/3289/files
