### ISSUE TITLE
Using global shortcut for tasks, page redirects to wrong URL

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6523]
Scenario:
1. Log in
2. Click G and T (shortcut for redirecting to Tasks page)

Actual: Redirected URL is `http://localhost:3001/tasks`
Expected: Redirected URL must be `http://localhost:3001/objects/tasks?view=10817448-f640-4f39-b5de-22edbef01a3a`

**Note:** URL can't be `http://localhost:3001/objects/tasks` because it gives blank page, when user normally clicks on 'Tasks' button, page automatically redirects to the 'By status' sub-page

**Comment by Nabhag8848** [comment]
Hey @BOHEUS  started working on it.

**Comment by Nabhag8848** [comment]
we need to fix this in two places -> also when we are opening CommandMenu CMD+K it has same issue with **G + T**

**Comment by Nabhag8848** [comment]
@BOHEUS I noticed that on other **gotohotkeys** 

- for eg: for companies`G+C`. if we open to `/objects/companies` without **view=** it does show table and doesn't show blank page. I tried to look but haven't found by default what **view=id?** is used there ? 

- Ain't we need the same behaviour like companies or do we need to solve all the gotohotkeys for all objects which includes view=id. cause it doesn't show up when navigation with hotkeys (for eg: in companies)  but it does uses that view query internal .

**Comment by BOHEUS** [comment]
I'll leave this decision to the @CoreTeamTwenty

**Comment by FelixMalfait** [comment]
Thanks @BOHEUS for spotting this (and the other bugs!)
@Nabhag8848 you're right it's better to remain consistent and not introduce a different pattern, let's leave it without the view if it works but still fix the url. Thank you!

**Comment by Nabhag8848** [comment]
@BOHEUS @FelixMalfait This happens same with **/objects/notes** (blankpage without view queryparam) - will fix too.
