### ISSUE TITLE
In DarkMode, bullet points in Releases aren't visible

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6524]
Scenario:
1. Log in
2. Go to Settings > Appearance
3. Set Dark mode
4. Go to Releases

Actual: Bullet points aren't clearly visible on dark background
![image](https://github.com/user-attachments/assets/0fa0d61d-fe2c-4809-8085-22a680cfdf44)
Expected: Bullet points should be clearly visible on dark background, similarly to other text

**Comment by mittalsam98** [comment]
I would love to work on this, pls assign this to me

**Comment by Nabhag8848** [comment]
Hey @BOHEUS fixed, can you have a look. Thanks !
