### ISSUE TITLE
Command menu is not scrollable

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#6538]
## Bug Description

The command menu is not scrollable.

https://github.com/user-attachments/assets/13dabe73-ce13-442f-b7fb-c6a0b2791d24

## Expected behavior

The command menu should be scrollable.

## Technical inputs

`packages/twenty-front/src/modules/command-menu/components/CommandMenu.tsx`

**Comment by ehconitin** [comment]
Fixed in PR #6541
