### ISSUE TITLE
[BUG] twenty-front vite package causing error logs due to vite trying to serve blocknote fonts which is outside of allow list

### ISSUE THREAD

**Issue by Nabhag8848** [twentyhq/twenty#6546]
## Bug Description 

- As can be seen in screenshot, twenty-front vite package causing error logs due to vite trying to serve blocknote fonts which is outside of allow list, because by default vite restrict serving files outside of workspace root 

- refer here as mentioned: https://vitejs.dev/config/server-options.html#server-fs-strict , https://vitejs.dev/guide/#index-html-and-project-root (third paragraph is helpful) 

- we have not set the serving strict, so by default its restricting to serve only from workspace root which is causing the below error. 

```
The request url "**/twenty/node_modules/@blocknote/core/src/fonts/inter-v12-latin/inter-v12-latin-regular.woff" is outside of Vite serving allow list.
The request url "**/twenty/node_modules/@blocknote/core/src/fonts/inter-v12-latin/inter-v12-latin-500.woff2" is outside of Vite serving allow list.
 ----
```

<img width="1770" alt="twenty" src="https://github.com/user-attachments/assets/515dbea1-2b60-4280-ad15-1df7885fb44e">

### We have two solutions
1. In order to solve it: we must include the path to file "@blocknote/path/to/font" in the allow list under package.json (server.fs.allow) that could be served.
2. or we can set server.fs.strict:false to serve to override the default behaviour of restricting serving files just from workspace root.

- [x] willing to push changes and make a pr -> waiting for confirmation.

**Comment by Nabhag8848** [comment]
@CoreTeamTwenty Lemme know, How should we proceed with this ?

**Comment by FelixMalfait** [comment]
@Nabhag8848 thanks for raising this! I'd say we can go with the first option and add the path to the allow list

**Comment by Nabhag8848** [comment]
On it.
