### ISSUE TITLE
ServerlessFunctions Followup

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6556]
Question for @martmull 

- How to access build logs?
- How to access runtime logs?
- How to store a custom environment variable? How to preload with env variable like an API key (should there be one API key/function?)
- How can I add multiple files to one function?
- How can we set a quota to avoid having a huge bill? And provide feedback on usage to users? (dashboards?) 
- We should disable auto-save and replace the "Test" button by a proper deploy button)
- We should be able to use "enter" key to delete or create function
- Access full fledged editor (costly?)
- Write tests for function (less prio, but what is the strategy?)
- Improve description in Lambda for debugging (currently "Lambda function to run user script")
- Auto-generate typescript SDK (based on rest + https://github.com/hey-api/openapi-ts ; and Lambda layer) 
- Move build to Lambda to avoid risks? Or at least limit the size of build (e.g. number/length of files) to avoid costly transpilation that crashes the server?

**Comment by martmull** [comment]
Question for @martmull 
- How to access build logs? -> not V1
- How to access runtime logs? -> not V1
- How to store a custom environment variable? How to preload with env variable like an API key (should there be one API key/function?) -> V1
- How can I add multiple files to one function? -> pas V1
- How can we set a quota to avoid having a huge bill? And provide feedback on usage to users? (dashboards?) -> V1 (@thomtrp)
- We should disable auto-save and replace the "Test" button by a proper deploy button) -> We should not be able to break workflows if we just made a small change without deploying -> V1
- We should be able to use "enter" key to delete or create function -> V1
- Access full fledged editor (costly?) -> not V1
- Write tests for function (less prio, but what is the strategy?) -> not V1, we can store test files to do it
- Improve description in Lambda for debugging (currently "Lambda function to run user script") -> @FelixMalfait can you precise?
- Auto-generate typescript SDK (based on rest + https://github.com/hey-api/openapi-ts ; and Lambda layer) -> not V1, will investigate

**Comment by FelixMalfait** [comment]
Thanks @martmull besides the v1 / not v1 one thing we should clarify imo is whether we want to be a UI layer over AWS (including Cloudwatch, etc.), or if we're meant to collect and build some of those features in the app metrics in the app. Strategy is not yet clear for me. I don't mind creating a dependency on AWS if it means offering an amazing development experience we couldn't offer otherwise.

> Improve description in Lambda for debugging
I meant that if you login to the AWS console it's hard to figure out which Lambda belongs to who
