### ISSUE TITLE
Add delete confirmation dialog for object detail view

### ISSUE THREAD

**Issue by Taldres** [twentyhq/twenty#6559]
## Current behavior

When I click on the delete button at the top right of an object detail page, it will instantly delete the selected record without any confirmation.

![Bildschirmfoto 2024-08-06 um 19 06 36](https://github.com/user-attachments/assets/fce6f2dd-c78a-4170-ad7e-0c8e3d5827be)

## Expected behavior
A confirmation dialog should appear, similar to the one in listings via the action bar delete button, as implemented in the latest release. This is the PR of the mentioned implementation: [Add Confirmation Modal for Deletion Action and Map All Action Bar Entries #6357](https://github.com/twentyhq/twenty/pull/6357)

![Bildschirmfoto 2024-08-06 um 19 07 03](https://github.com/user-attachments/assets/4c091748-5152-42e8-889e-e76ef6e0ff77)

**Comment by FelixMalfait** [comment]
@Taldres agree we could have built this! We didn't prioritize it because we want to work on #4956 instead, which is more difficult but more powerful. @magrinj will work on that when he comes back in September

**Comment by Taldres** [comment]
@FelixMalfait thank you for your quick response. I just wanted to let you know that it would be great to get, but soft-deletes are absolutely worth the wait 🙌.

**Comment by FelixMalfait** [comment]
Closing in favor of https://github.com/twentyhq/twenty/issues/4956
 https://github.com/twentyhq/twenty/pull/6576 a v1 of soft delete is coming soon, very likely to be in the next release
