### ISSUE TITLE
Ability to indent bullet points in notes/tasks

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6561]
On blocknote it's possible to indent note with tabs: https://www.blocknotejs.org/

<img width="209" alt="Screenshot 2024-08-06 at 22 03 27" src="https://github.com/user-attachments/assets/a3ea38dc-6b0f-4b62-a067-66fc4c10b0aa">

But it doesn't work in Twenty because Tab is hijacked by the app

**Comment by ehconitin** [comment]
I've been diving deep into the Blocknote docs while working on the side menu , so I think I can take this one on. Mind assigning it to me? 
Thanks!

**Comment by ehconitin** [comment]
Closes #6580
