### ISSUE TITLE
Editing a RICH_TEXT field should update the attachment table when new images are added.

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#6565]
## Scope & Context

Enrich text fields allow you to include images in your text, however images are uploaded through the server and directly inserted in the json without editing the attachment table. We would like to update the table as well to track those attachments and show them in the appropriate "files" tab.

## Technical inputs

TODO

**Comment by yadavshubham01** [comment]
hey @Weiko check it out this PR #7617
