### ISSUE TITLE
Add search for people/companies in command  bar

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#657]
Now that we have a show view we can add search for people/companies in the commandbar

cc @Bonapara could you please provide a design? Thanks a lot

**Comment by Bonapara** [comment]
<img width="600" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/99b4549f-acca-43e8-88db-177a1018d6ea">

Done!

**Comment by FelixMalfait** [comment]
@Bonapara we will have a separate search index for companies and people which means they will come as 2 separate results set. But in your case there is a single header "Search for XXX" for 2 indexes. How do you expect us to merge the results from the 2 indexes?  I'm not sure if company.relevance can be compared to people.relevance ; if not then how would you sort it?

**Comment by Bonapara** [comment]
@FelixMalfait do you mean something like this? 
<img width="697" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/c2fc775a-bb93-4691-9b2b-0b740b66b868">

**Comment by Bonapara** [comment]
Done
