### ISSUE TITLE
Webhook URL sanity check is too restrictive

### ISSUE THREAD

**Issue by FreakyPenguin** [twentyhq/twenty#6570]
Hi everyone,

We just ran into this with our on-prem deployment for testing. The sanity check regex for an URL seems way too restrictive: https://github.com/twentyhq/twenty/blob/9a0c9672a0ce7939ab393f4fe971eaf8f7726735/packages/twenty-front/src/utils/is-url.ts#L6

This precludes ip addresses, or hostnames without a tld and a number of other useful urls. I would suggest using something more generic here or adding a config option to override.

Thanks

**Comment by FelixMalfait** [comment]
Good point! Since it's on the frontend, if you're blocked by this you can probably do an API call directly (copy the curl in your Chrome network inspector for example and change the url to the one that wasn't accepted)

**Comment by AnanteshG** [comment]
Hi, I’d like to work on this issue.

**Comment by AnanteshG** [comment]
#6575 : Fixed restrictive URL sanity check #6570

**Comment by Weiko** [comment]
imho, there is no way to know 'google' is an url if we make the protocol (already the case) and the tld optionals. If we want to remove restrictions I wouldn't update the isUrl method (that could have impact in the rest of the app) but would remove the call to isUrl in the webhook section.
