### ISSUE TITLE
Ability to mention someone or a something in notes / task etc

### ISSUE THREAD

**Issue by tim-x-y-z** [twentyhq/twenty#6577]
## Scope & Context
It would be nice to be able to mention someone or anything in a note / task.

## Current behavior
Currently this doesn't seem possible.

## Expected behavior
Typing `@` and the username of the person should mention them.
Copy and pasting the link to another page within the app should highlight the page correctly not just show the url.

**Comment by Bonapara** [comment]
Great idea! Closing this issue as we first need to handle the inbox/notifications first, but keeping this in mind
