### ISSUE TITLE
Missing field name tooltip

### ISSUE THREAD

**Issue by Taldres** [twentyhq/twenty#6596]
## Scope & Context

Object Record Detail Page

## Current behavior

I added some fields to my custom investor model. The field names are a bit too long to be fully displayed on the object record detail page. Because of this, I couldn't distinguish between the "Initial Investment (min)" and "Initial Investment (max)" fields and ended up entering the wrong values.

![Bildschirmfoto 2024-08-09 um 20 46 17](https://github.com/user-attachments/assets/b9f4025d-42ba-4ea4-886a-352625f460cd)

## Expected behavior

There should be a tooltip or hover text that appears when hovering over the field name, allowing the full field name to be read. Additionally, it would be very helpful if fields could be sorted manually rather than alphabetically.

**Comment by FelixMalfait** [comment]
Thanks for bringing this up!
It should be easy to add, we already have a similar behavior on other fields where a tooltip can be displayed on hover if there's an ellipsis

**Comment by Sandheep-OSC** [comment]
Hi @FelixMalfait , Can i work on this issue?

**Comment by Sandheep-OSC** [comment]
@FelixMalfait raised #6601, would you please look into it.

**Comment by FelixMalfait** [comment]
Thanks @Sandheep-OSC ; I'm not sure about the performance comment near your code change so that's why I assigned it to @charlesBochet who will know best

**Comment by charlesBochet** [comment]
@lucasbordeau is taking ownership on this one!
