### ISSUE TITLE
Token expires despite actions from user

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6598]
**Scenario:**
1. Log in
2. Wait 30 min? (I'm not sure about the time, could be less or more)

**Actual:** Token expires despite actions from the user
**Expected:** Token's lifetime should be updated each time user performs any action e.g. going from People tab to Companies tab, if user doesn't perform any action within 30 min (lifetime of token must be decided by core team), then user is logged out.

# Edit

We should update the refresh mechanism

**Comment by FelixMalfait** [comment]
Is that locally or on the cloud? We don't have a good token refresh mechanism yes, it needs to be improved. On the cloud we've set a long expiration time for now

**Comment by BOHEUS** [comment]
Local setup with database in Docker

**Comment by linjoe2** [comment]
@FelixMalfait, can you at least explain how I could change this expiration date? because I'm having the same issue

**Comment by FelixMalfait** [comment]
@linjoe2 you should set `ACCESS_TOKEN_EXPIRES_IN` to a different value in your environnement variables (currently set to "30m")

@charlesBochet should we change the default value?

**Comment by charlesBochet** [comment]
I think we should solve the root issue :p
30min is actually a good practice!

**Comment by FelixMalfait** [comment]
@charlesBochet then it's an top priority! It must be very painful in self-hosting mode
cc @Bonapara for prioritisation

**Comment by Weiko** [comment]
Imho the issue you have is with the refresh token. This is set to 30mn by default which is very low for a refresh token. With a larger one (usually 30 days, sometimes up to a few years depending on the context...), the frontend is already able to renew a token using the refresh token.
