### ISSUE TITLE
Server can't find records when user logs in after token expiration

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6599]
Related to #6598 

**Actual:** When user logs in after token expiration, server can't find records and throws 35 errors in devtools (no errors in the `npx` logs)
![image](https://github.com/user-attachments/assets/82e3a8d4-c3b5-4f6b-9e83-8df98aba976e)
**Expected:** When user logs in after token expiration, server should find records like earlier.

**Comment by FelixMalfait** [comment]
I suspect that's a different error that caused this initially. Can you look at all backend errors in your network tab?

**Comment by BOHEUS** [comment]
There are many `Uncaught TypeError: column is undefined RecordTableCellWrapper RecordTableCellWrapper.tsx:68` errors but 1 error is related to ORM and I think it may be the cause of this
```
useFindManyRecords for "favorites" error : ApolloError: Cannot query field "myCustomObjectId" on type "Favorite".
Cannot query field "myCustomObject" on type "Favorite".
Cannot query field "myCustomField" on type "Company".
Cannot query field "myCustomObjectId" on type "Person".
```

**Comment by FelixMalfait** [comment]
Closing as I'm not sure how to reproduce properly :(
