### ISSUE TITLE
API endpoints export

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6600]
While API endpoints can be accessed using Stoplight in documentation (https://twenty.com/developers/rest-api/core#/), I think it's nice to have possibility to export these endpoints to e.g. Postman, especially when hosting locally has subset of GraphQL API without REST API. This way, users can be independent of web interface and use the API without the access to the Internet when self-hosting.

**Comment by FelixMalfait** [comment]
Can you please provide a few examples of how other apps make it available?
If you look at the network tab we have an openapi schema so it would be easily to copy/paste it to the tool you use

**Comment by BOHEUS** [comment]
I didn't see the option for exporting OpenAPI schema, which is right in the Overview, my bad
![image](https://github.com/user-attachments/assets/8a856df1-cbe5-408a-9e03-42d12875606b)
Tried to import it to Postman, which supports OpenAPI schema 3.0 but it didn't work, I'm not sure why, could you try to reproduce it?

About examples, here are few examples of exporting OpenAPI schema:
- https://api.artic.edu/docs/#introduction
- https://apis.guru/api-doc/
- https://digidates.de/en/

**Comment by FelixMalfait** [comment]
<img width="1500" alt="Screenshot 2024-08-12 at 16 39 40" src="https://github.com/user-attachments/assets/167edf84-f064-48ea-a900-f3a86bb8ff32">

I just tried to export then import in Postman but it worked well for me, I didn't get any error sorry. Will close this issue for now. Let us know if you identify steps to reproduce that show we have a problem in the openAPI schema generation
