### ISSUE TITLE
Improve Usability of Adding Options via Return Key for Multi-Select Field

### ISSUE THREAD

**Issue by Taldres** [twentyhq/twenty#6602]
## Scope & Context

The behavior for adding new options to a multi-select field via the Enter key can be made more convenient, especially when quickly adding multiple entries.

## Current behavior

When I add a new option by pressing the return key **instead** of clicking the "Add option" button it will be added with an generated text including an incremental number and the cursor is positioned at the end of the text.

![Bildschirmfoto 2024-08-10 um 12 56 58](https://github.com/user-attachments/assets/1e7c2808-ec91-4282-ae7e-fee4bda50234)

## Expected behavior
When I add a new option by pressing the return key, it should add a new option with an empty text and place the cursor at the first position. Alternatively, it should add the new option with the generated text (like actually), but the text should be selected so I can easily overwrite it.

The goal is to achieve a better behavior without the need to manually select the generated text.

Example:
![Bildschirmfoto 2024-08-10 um 13 09 54](https://github.com/user-attachments/assets/b9512430-e489-4d0d-87fb-78a44753d3ef)

**Comment by Sandheep-OSC** [comment]
Hey Team Twenty, Please assign me to this issue, i would like to work in this.

**Comment by Bonapara** [comment]
The text should indeed be selected. @Sandheep-OSC are you still willing to take this up? I'll let @lucasbordeau tell if we have a global strategy to handle this one yet or if we need to wait

**Comment by Sandheep-OSC** [comment]
Yeah sure, i can take this up

**Comment by Bonapara** [comment]
Assigned you @Sandheep-OSC, thanks for contributing!

**Comment by Sandheep-OSC** [comment]
Hey @Bonapara , I went through the code and the corresponding components. I have a technical query to ask. Could you please let me know who would be an appropriate person to tag the question with.

**Comment by Bonapara** [comment]
Hey @Sandheep-OSC, I think @ijreilly will be able to help if you ask your question here!

**Comment by Sandheep-OSC** [comment]
Hey @ijreilly, for the content of the input element to be selected, we need to use the ref on the input element which provides a method like `inputRef.current.selected()` to select the content of the input. But the component which can accept a ref (`TextInputV2`) is 2 component hierarchy below (`SettingsDataModelFieldSelectFormOptionRow` > `TextInput`) the component (`SettingsDataModelFieldSelectFormOptionRow`) which is being used in the `SettingsDataModelFieldSelectForm` component. Should i make the `SettingsDataModelFieldSelectFormOptionRow` and `TextInput` to forward ref or do you have any other suggestion?

**Comment by FelixMalfait** [comment]
Hey @Sandheep-OSC sorry for the late reply.

You can see a similar behavior when editing a filter on a view:
<img width="208" alt="Screenshot 2024-09-17 at 22 30 55" src="https://github.com/user-attachments/assets/4bce7fbc-3ded-4748-ac9d-4aa93f8d08eb">

It seems the ref is passed (with `useCombinedRefs` to pass multiple refs) so I guess it's ok if you take the same approach.

cc @lucasbordeau who knows best

Do you want to stay assigned @Sandheep-OSC? Thanks!

**Comment by Bonapara** [comment]
/oss.gg 150
