### ISSUE TITLE
If user clicks on different field while adding new Company, page crashes

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6603]
**Scenario:**
1. Log in
2. Go to Companies
3. Try to add new Company but instead of typing a name, click other field in new row.

**Actual:** Page crashes and can't be accessed until user changes the workspace or relogs.
![image](https://github.com/user-attachments/assets/deffd5e0-cfbd-4980-a420-57223c992bff)
**Expected:** Page shouldn't crash

**Comment by Bonapara** [comment]
Cannot reproduce 🤔 

https://github.com/user-attachments/assets/ada45759-c042-4e0d-a961-8c7af58e944d

**Comment by BOHEUS** [comment]
Maybe it's fixed with other commit, I'll try to reproduce it on newest version

**Comment by BOHEUS** [comment]
I can't reproduce it on newest version so I'm closing it.
