### ISSUE TITLE
Column's name overlays other column's name

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6604]
**Scenario:**
1. Log in
2. Go to People tab
3. Add "Linked Opportunities" column

**Actual:** Column's name overlays other column's name making it hard to read.
![image](https://github.com/user-attachments/assets/6645b96e-ab3a-4c11-bce4-46ed6d6af957)
**Expected:** Column's name shouldn't overlay other column's name like e.g. emails in screenshot above.

**Comment by Nabhag8848** [comment]
working on it.
