### ISSUE TITLE
Indicator for hidden columns

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6605]
## Current behavior

As of now, if table has more columns than the width of user's view, user may not see all columns and not know that there are more columns hidden. Perfect example of it is People's default view on devices with Full HD resolution (1920x1080).

**Example:** 
[Screencast from 2024-08-10 18-58-51.webm](https://github.com/user-attachments/assets/c7360644-71f5-4b48-9322-f12335989a05)

## Expected behavior
If there are any hidden columns, there should be an indicator for them so user may e.g. move the table to the right to see normally hidden columns.

**Comment by Bonapara** [comment]
Notion is not showing any indicator of this, not sure we should either (at least for now!)

![CleanShot 2024-08-28 at 18 25 33](https://github.com/user-attachments/assets/7370df0c-8e95-4690-96d6-22216d6b0aed)
