### ISSUE TITLE
Field "body" on Create note and task API creates error 

### ISSUE THREAD

**Issue by gianniskotsas** [twentyhq/twenty#6608]
## Bug Description

I've noticed that whenever I try to create a note via the API, I get an error as seen below. 

It seems that the body field is somehow misconfigured and cannot recognise a string input. 

**Example:**
```
Note text is "Hey, I'm a note" and the error shows that the "H" (first letter of any string that you put in the body field) gets a flag as unexpected token.
```

<img width="487" alt="Screenshot 2024-08-11 at 09 59 03" src="https://github.com/user-attachments/assets/5e08e40e-ec97-4214-ac15-b7a3f9455125">

<img width="749" alt="Screenshot 2024-08-11 at 09 59 39" src="https://github.com/user-attachments/assets/e4e456e9-5317-4727-b30f-e2e12ee96c7a">

## Expected behavior

When I parse a string on { "body": "example string"}, it should be recognised and correctly parsed to the object note or task

## Technical inputs

```
- Probably fixable by changing the parameter type of the body field on the note / task API 
```

**Comment by gianniskotsas** [comment]
Actually i managed to debug it. It seems that note is a string that contains inside it an array of JSONs, where each element of the array represents the different type of paragraph / heading / bulleted list that you use. 

<img width="483" alt="Screenshot 2024-08-11 at 12 28 27" src="https://github.com/user-attachments/assets/a486e0df-e6ea-4406-acec-41ddc35b0bc0">

I think the solution should be just to update the api documentation.

**Comment by gianniskotsas** [comment]
Btw I also think that there is no validation when I send a POST request (so I can create a note with incorrect format), but it seems that GET requests have validation and I cannot retrieve any of my notes. 

I see that there are 27 notes created (via the api) but I cannot read any of them in the platform or via a GET request.

**Comment by Bonapara** [comment]
@gianniskotsas, I'll close this issue, but it would be great if you could update your findings in the documentation if you have time! Thanks for contributing to twenty
