### ISSUE TITLE
Ex: In DarkMode, a blank square appears in bottom right corner while scrolling

### ISSUE THREAD

**Issue by tgelabs** [twentyhq/twenty#6615]
## Bug Description

Cycling loop between https://app.twenty.com/plan-required and https://app.twenty.com/settings/billing

**Example:** 
```
Unable to login as the browser is cycling between billing settings and plan-required
```

## Expected behavior

Access to the homepage, or either page

I've provided recorded video screen capture
https://github.com/user-attachments/assets/78783312-8e43-47b1-878a-af90db596334

**Comment by abhishekmmgn** [comment]
@tgelabs  Are you sure the title of the issue is correct?

**Comment by tgelabs** [comment]
Oh, sorry, I will fix it

**Comment by Bonapara** [comment]
@tgelabs thanks for reporting this bug. Do you remember making something specific to help me reproduce this bug?

**Comment by FelixMalfait** [comment]
Fixed!
