### ISSUE TITLE
In Search, redirect 'Create Task' doesn't work

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6630]
**Scenario:**
1. Log in
2. Click on "Search"
3. Click on "Create Task"
**Actual:** User stays on the same page, empty Task is created and error is thrown both in UI and devtools' console
![image](https://github.com/user-attachments/assets/c9e4f97d-b057-4096-a62a-ec07aa4a95f5)

**Expected:** User should be redirected to Tasks > By status (to verify with @CoreTeamTwenty) and create new Task

Logs:
![image](https://github.com/user-attachments/assets/6f2cf474-1ee3-484e-8352-ecac9b681f77)

**Comment by ehconitin** [comment]
PR #6635

**Comment by ehconitin** [comment]
@BOHEUS this is fixed! ;)
Could you please close this issue.
Thanks

**Comment by BOHEUS** [comment]
I'll check it and close if everything works fine

**Comment by ehconitin** [comment]
Please tag me if does not works as expected

**Comment by BOHEUS** [comment]
It works but it creates a new empty object by default, I don't think that's expected, @lucasbordeau what do you think?

**Comment by ehconitin** [comment]
I don’t think it’s supposed to be that way. This behavior existed even before this change. When adding tasks in any objects, it results in creating an empty object. This might be a different issue than #6633, as these appear to be two distinct behaviors. However, they could potentially be resolved together. I’ll investigate further. Thanks for pointing it out—good catch!

**Comment by Bonapara** [comment]
Looks fixed to me - Thanks!
