### ISSUE TITLE
Visualisation of relations between objects doesn't work

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6632]
**Scenario:**
1. Log in
2. Go to Settings > Data model
3. Click on "Visualize" button

**Actual:** Nothing happens

**Expected:**  Map of relations between objects is visible

**Comment by Nabhag8848** [comment]
@BOHEUS I think this is already fixed.

https://github.com/user-attachments/assets/cc5f3f0d-76e2-4bdb-a27b-d92d5a3ad64b

just an info in case: Testing from current main branch **HEAD**.
