### ISSUE TITLE
Editing empty name of Company 

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6634]
Related to #6633, possibly both can be fixed at the same time

**Scenario:**
1. Log in
2. Go to Companies
3. Create new object by either pressing '+' in right top corner or 'c' on keyboard, type anything, delete it and press Enter
**Actual:** Object is created
4. Click on name of newly created Company

**Actual:** When clicked in right place, "Name" field can be edited which normally is not possible

**Expected:** Object shouldn't be created due to missing data, if object is created, its' name should be editable only from detailed view of the object

**Comment by Stroller15** [comment]
hey @BOHEUS can you pls assign me this, I can help to resolve this

**Comment by BOHEUS** [comment]
@Stroller15  I can't as I don't have enough permissions to do so, if you know how to do it, then please fix this and create a PR, someone from Core team will review it

**Comment by BOHEUS** [comment]
Video how to reproduce a bug
[Screencast from 2024-08-25 13-25-09.webm](https://github.com/user-attachments/assets/2e933c88-02d1-4e07-9c28-37894ec2cdfd)

**Comment by Bonapara** [comment]
Closing this issue because other issues will prevent the creation of empty objects.
