### ISSUE TITLE
Create an e2e test for login

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#6637]
## Scope & Context

Let's create our first relevant e2e test. 

## Expected behavior

We should have an e2e test that logs in with the default account credentials : `tim@apple.dev` : `Applecar2025`

Make sure that the credentials are typed in and that you validate by clicking on "Continue".

We should test that there is a table visible.

**Comment by BOHEUS** [comment]
@lucasbordeau please assign me, I'm working on it here https://github.com/BOHEUS/twenty/tree/playwright_qa_tests

**Comment by BOHEUS** [comment]
Done in #6712

**Comment by BOHEUS** [comment]
Done in #6719

**Comment by BOHEUS** [comment]
Done in #6717

**Comment by BOHEUS** [comment]
@lucasbordeau could you please close this issue?

**Comment by lucasbordeau** [comment]
Yes
