### ISSUE TITLE
No login page after changes introduced in #6621

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6639]
As of now, instead of standard login page, there is blank white page and error in devtools, logs don't return any warning nor error
![image](https://github.com/user-attachments/assets/24470073-90d0-4ed6-a4fe-7a5f0580404a)

Please investigate changes introduces in #6621 

Workaround: revert commit

Logs from devtools
```
Uncaught SyntaxError: The requested module 'http://localhost:3001/@fs/home/user/Desktop/projects/twenty/node_modules/prop-types/index.js?v=759aeb0f' doesn't provide an export named: 'default'
```

**Comment by Nabhag8848** [comment]
Hey @BOHEUS had you cleared yarn cache ? after syncing the new changes from main HEAD and installed node_modules again by **deleting** the old node_modules ? cause when we include optimizeDeps.exclude configuration, i believe it doesn't clear / update cache by default and it has issues with installed dependency. 

- I'm current running on same main head and I'm not able to reproduce this.

**Comment by BOHEUS** [comment]
@lucasbordeau I'm still able to reproduce it, all what I did was reverting the revert of changes and rerun the server, tried clearing the cache and reinstalling all packages but in the end I'm unable to access the app.

**Comment by Bonapara** [comment]
@BOHEUS do you still have it?

**Comment by BOHEUS** [comment]
@Bonapara I can reproduce it only if those 3 lines from mentioned issue are added to vite.config.ts, otherwise no
```
optimizeDeps: {
      exclude: ['@tabler/icons-react'],
    },
```
