### ISSUE TITLE
Harmonize clickable field / inputs / cells / chips

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#664]
Expected behavior : 

- If I have a field with a clickable link, the background doesn't change
- If I have a clickable field / cell that should be editable, we should put a pen icon next to it to edit it
- Only clickable relations have a chip with a non-transparent background, event if they are in an editable input.
- Non-clickable chips have no background, and a click on the editable component just put the component in edit mode.

**Comment by charlesBochet** [comment]
Work on EditableCell + Editable fields. Only on existing fields (CompanyShow, PeopleTable, CompanyTable)

**Comment by Bonapara** [comment]
See #701
