### ISSUE TITLE
Update AWS SDK to v3

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6643]
AWS SDK for JS should be updated to v3 as it approaches the end of maintenance support

![image](https://github.com/user-attachments/assets/dbd177a6-68c9-420f-aa5a-6fc65053f847)

**Comment by naineel1209** [comment]
Hi @BOHEUS, I’m new to the project and looking to help out with this issue. I’ve reviewed the usage of aws-sdk across the project and noticed that it no longer uses `aws-sdk v2`. All current implementations appear to follow the v3 specifications. To resolve this, it seems we only need to remove `aws-sdk v2` from the dependencies. Can you please confirm if this is correct?

**Comment by BOHEUS** [comment]
@CoreTeamTwenty could you confirm this?

**Comment by FelixMalfait** [comment]
You can check with `yarn why` ; I think there's a direct dependency that does need to be upgraded

**Comment by BOHEUS** [comment]
![image](https://github.com/user-attachments/assets/2a424fa1-1d16-41f7-8aad-5e2c1a9acf1e)

**Comment by naineel1209** [comment]
According to `aws-sdk` v3, each service is packaged as a separate module, and the codebase uses it accordingly. Therefore, removing the direct dependency on `aws-sdk v2` should resolve the error.

**Comment by FelixMalfait** [comment]
Great! Let's go ahead and do that

**Comment by charlesBochet** [comment]
Closing thanks @naineel1209 and @BOHEUS!
