### ISSUE TITLE
bug: when sign in is completed, items in ObjectMetadataItems has mismatch  isActive Field from actual state

### ISSUE THREAD

**Issue by Nabhag8848** [twentyhq/twenty#6652]
## Bug Description

- when signin for the first time we are getting objects as active even its disable. encountered while solving and blocking this case in #6612

https://github.com/user-attachments/assets/827705f0-6680-42fe-bc57-582655417276

## Expected behavior

- it should return correct objectMetadataItems before navigation to defaultHomePagePath.

**Comment by charlesBochet** [comment]
I wonder if Twenty is still using the mocked objects (used to display the background behind sign-in modal). I think we should reset the objectMetadataItem recoil state upon login

**Comment by Nabhag8848** [comment]
Includes Fix in #6612 , Thanks.
