### ISSUE TITLE
Serverless Functions: Add a deploy button, disable deploy when autosave, add code versioning

### ISSUE THREAD

**Issue by martmull** [twentyhq/twenty#6654]
- ✅ disable deploy when autosave, juste save the typescript code in the file
- ✅ add function versioning
- add a deploy button that build and transpile the typescript into the executable javascript file
- ✅ check autosave does not move caret when updating the function
- leave the test button, deploy a temporary serverless function for testing

**Comment by thomtrp** [comment]
Double check behavior with product (draft vs previous version)
