### ISSUE TITLE
Migrate from reactflow to @xyflow/react

### ISSUE THREAD

**Issue by Devessier** [twentyhq/twenty#6662]
To do:

- The reactflow library should now be replaced with @xyflow/react. It will prevent duplicating an external dependency. The migration should be fast as the API hasn't changed.

**Comment by FelixMalfait** [comment]
https://github.com/search?q=repo%3Atwentyhq%2Ftwenty++reactflow&type=code

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by jeffersonnnn** [comment]
can i get this assigned to me? @Bonapara

**Comment by Bonapara** [comment]
Sure @jeffersonnnn, thanks for contributing!

**Comment by spawade99** [comment]
@Bonapara can you assign this to me? it’s been a week since no PR

**Comment by anoopw3bdev** [comment]
Hey @Bonapara, I'd like to take this up. Can you assign it to me

**Comment by FelixMalfait** [comment]
Thanks @anoopw3bdev!

**Comment by pradeepkaswan** [comment]
Can I have this assigned to me? @FelixMalfait

**Comment by FelixMalfait** [comment]
Yes sure! Whoever raises a PR first. Thank you!
