### ISSUE TITLE
Missing verification when deleting the account

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6663]
# Do not try to repeat this on paid version!

**Scenario:**
1. Log in
2. Go to Settings > Profile
3. Click "Delete account" button
4. Type anything and press Enter

**Actual:** User is deleted and if that's the only member of workspace, the workspace is also deleted

**Expected:** User should be deleted ONLY IF the user's email was typed correctly (and maybe the button was pressed instead of pressing Enter key but that's up to decide)

**Note:** Reproduced on demo

**Comment by BOHEUS** [comment]
I checked more and it appears that whenever there's check to type something in order to confirm like e.g. when deleting webhook, there's missing validation

**Comment by Bonapara** [comment]
Couldn't reproduce:

https://github.com/user-attachments/assets/6aa3c651-a8a0-404d-9f04-dae754c2c06e

**Comment by Bonapara** [comment]
Thanks for raising this issue @BOHEUS! Nice one. Do you want to handle it?

**Comment by BOHEUS** [comment]
I can find all places which need such verification and report them but I don't think I'll be able to fix this @Bonapara

**Comment by BOHEUS** [comment]
After investigation, these are all missing verification:
- delete account in Settings > Profile
![image](https://github.com/user-attachments/assets/4ce082dd-2954-4368-a1b4-12b003c8e680)
- delete workspace in Settings > General
![image](https://github.com/user-attachments/assets/c7ea08c6-c792-4db0-b245-38466953082d)
- delete webhook in Settings > Developers
![image](https://github.com/user-attachments/assets/eaee7fe0-6f8a-411e-8942-6415024bd3c1)
- delete key in Settings > Developers
![image](https://github.com/user-attachments/assets/c34ac13c-2717-4e96-a07b-a612fa1b5e74)
- delete function in Settings > Functions
![image](https://github.com/user-attachments/assets/b3b7a8db-ae68-42d9-b5de-3a4a2db22f02)

Maybe they are also some missing verifications in Google integration but I don't know since I don't have such account which allows for integration.

**Comment by charlesBochet** [comment]
Thank you! tagging this as good first issue, we don't want to save if the validation rule is not respected. Should be easy enough to fix

**Comment by bachtly** [comment]
May I take this as my first issue @charlesBochet, @Bonapara?
I figured out the issue lies at https://github.com/twentyhq/twenty/blob/44ff55f5504c04c26dc8095b5c006d366ef8776d/packages/twenty-front/src/modules/ui/layout/modal/components/ConfirmationModal.tsx#L96

**Comment by Bonapara** [comment]
Sure @bachtly, thanks for contributing and welcome to Twenty community!
