### ISSUE TITLE
Optimize Vite to avoid fetching all files on hard refresh

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#6676]
## Scope & Context

Optimize Vite to avoid loading all files for each hard refresh.

See : https://dev.to/greggcbs/vite-how-to-bundle-group-chunks-together-1dnl

**Comment by charlesBochet** [comment]
@lucasbordeau I have deeply investigated this one, I was wrong about what we can do with vite.

1) Specifying chunks is only possible in production roll up. It's quite easy to use and it's called ManualChunks, it's particularly useful to create a chunk for the app shell (the base with React) + one for each page + some dependencies that are used on particular pages.

2) Before introducing chunks we should introduce lazy loading on routes (other wise we need all chunks anyway), I have done it on Settings Route and it make the app loading ligher

3) Regarding developer experience, chunks are not used and there is no satisfying way to make vite bundle things by itself. However I think this is good to push us in the right direction and won't be an issue if: we use routes lazy loading (this reduces the number of files watched, I've done it on the Settings routes and the number of loaded files has reduced by 25%) + we extract some packages such as twenty-ui that will be build separately and loaded as a npm package (vite won't watch them as they will be pre-built separately). I think we can keep the number of files served by vite around ~1000 if we do that which will provide good performances even on slower computers

Closing this issue as I have investigated it. I think we are already working toward the next steps: lazy loading (already in place) + extracting twenty-ui
