### ISSUE TITLE
[Timebox] Dark mode is hard to read

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#668]
cc @Bonapara (you can edit the content here directly if you want)

**Comment by charlesBochet** [comment]
Waiting for Design inputs

**Comment by Bonapara** [comment]
Coming this week

**Comment by Bonapara** [comment]
New colors are ready to be implemented

**Comment by FelixMalfait** [comment]
https://news.ycombinator.com/item?id=36799022

**Comment by FelixMalfait** [comment]
Closing as this seems to be have been done here: https://github.com/twentyhq/twenty/pull/781 please reopen if this isn't complete

**Comment by FelixMalfait** [comment]
Closing as this seems to be have been done here: https://github.com/twentyhq/twenty/pull/781 please reopen if this isn't complete
