### ISSUE TITLE
Add messaging sync Status on the FE

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#6685]
## Scope & Context

We would like to display Connected Account sync status on the Settings UI:
<img width="799" alt="image" src="https://github.com/user-attachments/assets/0e7d29b8-7e77-4b50-9a6b-2e7de2597906">

See Figma here: https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34844-84769&t=EmToUlIDemK21HZA-0

In database, we have a syncStatus on the related calendarChannel (cC) and messagingChannel (mC). Here should be the logic to compute connectedAccount status:
- mCSyncStatus = 'ACTIVE' && cCSyncStatus = 'ACTIVE' ==> Synced
- mCSyncStatus = 'NOT_SYNCED' && cCSyncStatus = 'NOT_SYNCED' => Not synced
- if mCSyncStatus = 'NOT_SYNCED' ignore it in the upcoming conditions (same for cCSyncStatus = 'NOT_SYNCED' case)

- mCSyncStatus = 'ONGOING' || cCSyncStatus = 'ONGOING' ==> Importing
- mCSyncStatus = 'FAILED' or 'FAILED_INSUFFICIENT_PERMISSIONS' || cCSyncStatus = 'FAILED' or 'FAILED_INSUFFICIENT_PERMISSIONS' ==> Failed

**Comment by sarthak25sharma** [comment]
Hi
Can I work on this?

**Comment by charlesBochet** [comment]
@sarthak25sharma sure :)

**Comment by sarthak25sharma** [comment]
Cool will get to it asap

**Comment by shwetd19** [comment]
Hey @charlesBochet 
To fix the issue, modify the `Accordion` component to ensure it closes an open item when another is clicked. Use state management to track the active item, allowing only one to be open at a time.
Can I work on this ?

**Comment by ehconitin** [comment]
@sarthak25sharma are  you still working on it or should I pick it up?

**Comment by charlesBochet** [comment]
@shwetd19 are you containing on the right issue?

@ehconitin thanks for your enthusiasm, our rule is that the assignment last 3 days, then it's free again :)

**Comment by ehconitin** [comment]
[PR 6730](https://github.com/twentyhq/twenty/pull/6730)
