### ISSUE TITLE
Small refactor from #5983

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#6698]
## Scope & Context

https://github.com/twentyhq/twenty/pull/5983 has been merged with things left to refactor, see comments on PR and refactor it.

```[tasklist]
### Tasks
```

**Comment by ehconitin** [comment]
Can I work on this?

**Comment by lucasbordeau** [comment]
Another contributor is already working on it in https://github.com/twentyhq/twenty/pull/6613

**Comment by lucasbordeau** [comment]
@ehconitin Sure

**Comment by ehconitin** [comment]
@lucasbordeau Could you specify what exactly needs to be refactored? 
I noticed some instances of useSetHotkeyScope() that could be optimized. 
It would be helpful to have a clearer direction or path for these improvements.
Thanks

**Comment by lucasbordeau** [comment]
We'll close this for now.
