### ISSUE TITLE
The dragged block gets appended to the body on dragging

### ISSUE THREAD

**Issue by ehconitin** [twentyhq/twenty#6724]
## Bug Description

When dragging a block in the editor, the block is appending to the body.

https://github.com/user-attachments/assets/fb00a63e-9b43-46d3-9c68-8c156b44b551

## Expected behavior

The block should not clutter the body upon being dragged.

## Technical inputs
This issue is caused by `setActivityBody(newStringifiedBody)` in the `handleEditorChange` function within the `RichTextEditor` component, which triggers re-renders causing the issue.
[Relevant Code](https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/activities/components/RichTextEditor.tsx#L262)

## Proposed Solutions
I have identified two potential solutions which works: 

- Use `useRef` instead of `useRecoilState` for state management: This approach could prevent re-renders but may conflict with existing ESLint rules.

- Add a slight delay to `setActivityBody(newStringifiedBody)` using `setTimeout`: This could mitigate the re-render issue without violating ESLint rules.

Which one should I go ahead with?

**Comment by charlesBochet** [comment]
Weird one, I think we can get it right, re-renders should not matter
