### ISSUE TITLE
Update dev's documentation for enabling webhooks on self-hosted

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6727]
Based on conversation in Discord server https://discord.com/channels/1130383047699738754/1276587741144154193

Right now, there's no documentation regarding enabling webhooks on self-hosted. As it turned out, a new docker instance and change in .env variables are needed in order to send webhooks. Please create a new page or update an existing one with all information required to run the worker responsible for sending webhooks.

Summary:
- instead of using Postgres, Redis must be used (thus new container)
- in .env MESSAGE_QUEUE_TYPE=bull-mq, REDIS_HOST=127.0.0.1, REDIS_PORT=6379
- `npx nx twenty-server:worker` must be running in parallel to `npx nx start` or `npx nx twenty-server:start`

Ideally, another command similar to `make postgres-on-docker` or `make postgres-on-linux` should be added to make transition easier (and also a way of controlling it for non-tech people)

**Comment by skyfox675** [comment]
@charlesBochet I can take a run at the doc updates if you like

@BOHEUS, I missed the worker for the first view months of running Twenty 😂, @LumosViridi is finishing up a follow-on to #6356 for the worker container and storage changes. But, we're still running with `MESSAGE_QUEUE_TYPE=pg-boss` with webhooks working. I think Redis is the path forward but this is working as of `v0.23.2`

**Comment by Bonapara** [comment]
Thanks to you both! @charlesBochet is going to update it as he updates the system :)
