### ISSUE TITLE
2 windows are opened when exporting records for the first time [Linux]

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6729]
**Scenario:**
1. Log in
2. Go to any object page (e.g. Companies)
3. Click Options > Export

**Actual:** 2 windows requesting file are opened
**Expected:** 1 window requesting file should be opened

### Context

Seems to appear only on Linux

**Comment by ehconitin** [comment]
Couldnt reproduce this bug.
Could you share a screen recording of the mentioned bug.

**Comment by BOHEUS** [comment]
@ehconitin 
[Screencast from 2024-08-24 12-14-12.webm](https://github.com/user-attachments/assets/e0c4c28f-12ad-4b91-937c-dbe6aa31a8bd)

**Comment by ehconitin** [comment]
@charlesBochet 

Could you take a look at this please.
[here](https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/object-record/record-index/options/hooks/useTableData.ts#L144) useEffect seems to be triggering twice on the first call only.
is it beacuse of `fetchMoreRecordsWithPagination`?
weird bug.

**Comment by Bonapara** [comment]
Could not reproduce it either

**Comment by ehconitin** [comment]
I was able to reproduce this Thomas.
Do you have your download location set already?

**Comment by Bonapara** [comment]
Maybe it's an issue specific to Windows

**Comment by BOHEUS** [comment]
@Bonapara I'm using Linux, not Windows 😂

**Comment by Bonapara** [comment]
Are you on Linux too @ehconitin?

**Comment by ehconitin** [comment]
Yep, linux!

**Comment by charlesBochet** [comment]
Weird one, I don't have Linux could you guys investigate to try to find the root cause?

**Comment by BOHEUS** [comment]
@Bonapara @charlesBochet this issue becomes even more clear when exporting records using standard actions from right menu, I managed to get 5 files downloaded at the same time (I'm not even sure how :laughing:)

**Comment by BOHEUS** [comment]
Video just in case

https://github.com/user-attachments/assets/200d3b7c-12af-42bb-8551-b970ea93eef9

**Comment by FelixMalfait** [comment]
It's not just on Linux, I saw it on Mac too. 
Closing to keep the other one but thanks a lot for being the first to report (as always 😁) @BOHEUS

**Comment by BOHEUS** [comment]
@FelixMalfait no problem, could you link the mentioned issue?

**Comment by FelixMalfait** [comment]
Sure! #8239
