### ISSUE TITLE
useFindManyRecords error after token expiration with more than 250k objects

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6732]
**Scenario:**
1. Create at least 250k objects of any type, e.g. Companies
2. Log in
3. Go to Companies page

**Actual:** The page itself is loading but the problem appears when scrolling through the page

**Note:** Local setup with database in Docker
Logs:
```
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
```

**Comment by BOHEUS** [comment]
Found while testing #4817, average time of loading several objects from 250k row table is ~115 ms @FelixMalfait

**Comment by FelixMalfait** [comment]
Oh 115ms seems good, cool
I'm not sure we can do anything with the error code above, are you sure it's linked to the large number of records? This seems to be just a DB connection issue
Could you provide the code you used to create 150k records?

**Comment by BOHEUS** [comment]
I've sent how-to in DMs just in case so nobody will use it for malicious goals

**Comment by BOHEUS** [comment]
I checked once again and the error itself is thanks to changed variable MESSAGE_QUEUE_TYPE in .env as I was using earlier worker for webhook calls and forgot to deactivate it 🤦 (error appears if app is working, MESSAGE_QUEUE_TYPE is set to bull-mq but Redis is not working which is expected)

**Comment by BOHEUS** [comment]
I'm reopening this issue as I found a real bug this time

**Scenario:**
1. Log in
2. Create 250k Companies
3. Wait for token expiration (~30 min)

**Actual:** Many errors are appearing in devtools and UI
[Screencast from 2024-08-25 15-40-44.webm](https://github.com/user-attachments/assets/192d23f7-6bac-4704-a7ad-fc3800291a32)

**Expected:** Server shouldn't find for objects until user is logged in
