### ISSUE TITLE
Whitespacing issue allows users to create empty objects

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#6734]
## Bug Description

Currently, User can create / update `Text Input` and various other components using whitespaces.

**Example:** 

1. Under developers in settings, While creating an API key or webhook `Name` and `URL` field will accept whitespace as a valid input.

https://github.com/user-attachments/assets/548524ab-13fe-4e00-ac07-6cf5daa1882d

2. Under members in settings, `Invite an email` will accept whitespace as an valid email regex and send the email invite link.

https://github.com/user-attachments/assets/7cd63411-6011-4448-bd99-7ccc8a9ce797

3. Under General, `Name` accepts whitespace as valid.

https://github.com/user-attachments/assets/7de30df5-4517-4dc9-a3ef-c4e7cba51589

4. Minor issue, While creating a new field under opportunities, `header` tag lacks sufficient width

<img width="1786" alt="Screenshot 2024-08-25 at 5 42 49 PM" src="https://github.com/user-attachments/assets/2a2a26b9-e8d7-4264-b405-8b8b74275773">

5. Currency field seems to accept whitespace and creates the field.

https://github.com/user-attachments/assets/68c5f537-cdb7-4609-9e25-37fed86f756f

These issue are of the same behaviour as the existing issue #6634 #6633 

## Expected behavior

A clear and concise description of what the expected behavior is.

**Example:** 

- Name and URL should not accept whitespace and throw error just lke the existing behaviour of name. This applies for the rest.

<img width="549" alt="Screenshot 2024-08-25 at 10 58 09 PM" src="https://github.com/user-attachments/assets/be202c81-6a7f-433d-9b68-e753d1612dc4">

## Technical inputs

**Example:** 

We can use `trim()` to detect for whitespaces and run a if loop to check for it and `throw new Error` for most of the issues. 

## Solution

I have solved the tagged issues and tested them. I'll create the PR for the following as I was working on them.

**Comment by BOHEUS** [comment]
Nice one!

Related to #6633

**Comment by Nabhag8848** [comment]
Nice one ! @harshit078 the core issue is in the draftValue, so when string gets "" when deleting. the draft value isn't getting reset to undefined. In ISSUE 6633 once you will clear the name field and tap once under Name InputAreaField and press the Enter it won't create object-record with empty field name.

**Comment by Nabhag8848** [comment]
Related: 

https://github.com/user-attachments/assets/2ed39a5b-ee22-4558-8215-f7b1fa8dd6f0

**Comment by Bonapara** [comment]
Do you want to handle it @Nabhag8848? Thanks for raising the issue @harshit078!

**Comment by Nabhag8848** [comment]
yes @Bonapara

**Comment by Bonapara** [comment]
Thanks @Nabhag8848 ;)

**Comment by Nabhag8848** [comment]
One other case which can be solved right here: 

When we paste / someone tries to break via `FirstName<whitespaces>LastName` in fullname field its pasting Firstname and ""

**Comment by charlesBochet** [comment]
Thanks for the detailed issue, happy to review PRs regarding this, it looks like we need several separated PRs indeed

Overall direction:
we should watch for what's typed in the fields, trigger a validate function (on the trimmed value) and maintain a "isValid" state that we should check to disable the Save button / display an error message

**Comment by harshit078** [comment]
Hi @Nabhag8848, there is one more field which is missed which occcurs when creating a new task wherein task with whitespace can be created.

<img width="1196" alt="Screenshot 2024-09-02 at 1 30 43 AM" src="https://github.com/user-attachments/assets/db412bc4-26b6-4c67-9769-2d50bb814e26">
