### ISSUE TITLE
Field name is oddly displayed when long 

### ISSUE THREAD

**Issue by ijreilly** [twentyhq/twenty#6738]
## Bug Description

<img width="1029" alt="Capture d’écran 2024-08-26 à 11 37 08" src="https://github.com/user-attachments/assets/f5af6900-c661-4316-9db3-c4ffc94f3bce">

## Expected behavior

Field name is truncated with "..." when display starts being flawed. 
On hover, the full name is displayed.

## Technical inputs

For the record, we have introduced a char limit of 63 characters on names).

**Comment by harshit078** [comment]
Hi @ijreilly, If not taken Can I take this up ?

**Comment by ijreilly** [comment]
Hi @harshit078 sorry I assigned this to @gitstart-twenty !
