### ISSUE TITLE
bug(ui): when hovering over currenty field cell currency symbol is visible

### ISSUE THREAD

**Issue by Nabhag8848** [twentyhq/twenty#6741]
### Actual 

https://github.com/user-attachments/assets/f5b33063-568f-4a13-a9e8-65e774769352

### Expected

- On hover it shouldn't.

**Comment by nolostra** [comment]
@Nabhag8848 how can i get it assigned to me ?

**Comment by Nabhag8848** [comment]
@nolostra just drop the comment here, **working on it** and start working. someone from core team will assign. small issues which are good first issues like this one can be tackle like this, to avoid assignment workflow, cause until you wait for assignment to get started this issue could be fix. many many orgs use this including supabase just drop a comment and start working. more better if you make a draft PR.

**Comment by nolostra** [comment]
started to work on this

**Comment by ArnavNath550** [comment]
**working on it**

**Comment by Bonapara** [comment]
@nolostra are you still on it? If yes I will assign you. Thanks for contributing!

**Comment by nolostra** [comment]
yes please assign @Bonapara .

**Comment by Bonapara** [comment]
Done! Thanks @nolostra

**Comment by nolostra** [comment]
![image](https://github.com/user-attachments/assets/36453e5a-8d4e-4c28-b39a-1ab8a7794b2d)


hey guys , i am getting this issue when i try to do setup on windows , forward slash are converted to backslash 
@Bonapara @Nabhag8848

**Comment by Nabhag8848** [comment]
Are you using WSL in windows ? if not it is recommended to use.

**Comment by nolostra** [comment]
yes i am using WSL, i was able to run the server on docker without any issues 
but frontend gave me some bugs

**Comment by Bonapara** [comment]
The same bug exists in the cloud version (the currency appears when hovering over the cells).

**Comment by charlesBochet** [comment]
@nolostra it's likely an issue with your IDE

**Comment by krVatsal** [comment]
Can i work on it?

**Comment by Bonapara** [comment]
Sure @krVatsal, thanks for contributing!

**Comment by FelixMalfait** [comment]
/oss.gg 150

**Comment by sans-byte** [comment]
Hi I would like to work on this issue can you please assign it to me?

**Comment by droidbg** [comment]
Hey @FelixMalfait, since it's been two days since the assignment, and I also noticed a similar issue with task items (#8058), could you please assign it to me. I have submitted a PR that is fixing both.


> Assigned to @Udaypawar004! Please open a draft PR linking this issue within 48h ⚠️ If we can't detect a PR from you linking this issue in 48h, you'll be unassigned automatically 🕹️ Excited to have you ship this 🚀
