### ISSUE TITLE
Upload Profile picture error

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#675]
Profile picture upload didn’t work for my image (JPEG 1.4MB) (You say up to 10MB work in the copy). Same image but smaller (JPEG 1MB) worked (see screenshot for errors when uploading the 1.4MB image)

**Comment by charlesBochet** [comment]
https://stackoverflow.com/questions/52783959/nest-js-request-entity-too-large-payloadtoolargeerror-request-entity-too-larg
