### ISSUE TITLE
Adjust height of Notes grip menu

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6759]
# Current Behavior

The 6-dot icon in the note grip menu is 20px in height. The padding within its white container is too small.

https://github.com/user-attachments/assets/247ecf1b-0328-4acd-b333-8982fd9aef1c

# Desired Behavior

We should reduce the SVG size to 16x16px while keeping the container size at 20px.

https://github.com/user-attachments/assets/e8fddf40-6063-4e5a-a628-e9af1efd7536

**Comment by kant-github** [comment]
Hey @Bonapara, it was an easy fix. Raised a PR.
Thanks.

**Comment by Bonapara** [comment]
Thanks for addressing it so quickly, @kant-github ;)

**Comment by lucasbordeau** [comment]
Closed by https://github.com/twentyhq/twenty/pull/6780
