### ISSUE TITLE
feat(invitations): improve invitations management + add personal invitations

### ISSUE THREAD

**Issue by AMoreaux** [twentyhq/twenty#6763]
## Scope & Context

We want to improve the invitation flow by displaying invitations in settings and creating one invitation by email. We will do the job in two milestones. 

### 1.  Manage global invitations #6626 
- [x] Allow to display invitations in the Members settings section
- [x] Allow to invite a user
- [x] Allow to delete an invitation
- [x] Delete invitation when a user uses it during the signup 
- [x] Prevent failure if multiple invitations are sent and only one or more failed
- [x] Prevent duplication invitation
- [x] Prevent invitations that target an existing user in the same workspace

### 2. Manage personal invitations -> #6782 
- Add an expiration date to an invitation
- Allow to renew an invitation to postpone the expiration date
- Display an error if a user tries to use an expired invitation
- Display an error if a user uses another mail than the one in the invitation

## Current behavior

There is a single invitation link for the entire workspace and user invited are not displayed.

## Expected behavior
- Allow to manage invitations in a dedicated section
- Switch from a global invitation to a personal invitation

## Technical inputs
- Create a domain `workspace-invitation` in core-module.
- Update the `appToken` table to store invitations.
- Remove features that use the `inviteHash`

## Suggestion

We could retain the global invitation link and make it optional.

**Comment by Bonapara** [comment]
Thanks Antoine! Do you have all what you need from a design point of view?

**Comment by AMoreaux** [comment]
> Thanks Antoine! Do you have all what you need from a design point of view?

Today it's like this:
![image](https://github.com/user-attachments/assets/a1390eb0-e89e-403a-9ac0-92bf66b27b3b)

Is it ok for you?

### For the second milestone: 

- I suggest adding the IconReload next to the trash icon to allow users to resend the invitation and extend the expiration date.

- Additionally, we need to handle the scenario where an invitation has expired. We could indicate this by adding a tag with "Expired" on the card. And maybe in the opposite case, the number of days left before the expiration.

- I opted to use the first letter of the email as the avatar for the invitation. However, considering it's an invitation, an icon or a different UI element might be more appropriate.

**Comment by Bonapara** [comment]
@AMoreaux I suggest this design what do you think?

- Create an "invite by email" section with the invitation status
- Change the cards to lists for a more compact view
- Customize the invited avatar as you suggest
- Remove the email icon from the add email input
- Add a "Reload" to send a new invite mail
- Add a "Sent X days ago" to indicate when the invitation was sent (just saw you said days remaining, that's a good idea too!)
- Add an "Expired" status for when the invite is expired
- We should add some tooltips over the icon button to indicate what they are doing

- We could also auto-delete the expired invitation after some time? e.g 1 month?

![image](https://github.com/user-attachments/assets/99ea04aa-38d2-4a34-bbf1-27023ce8bd8d)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=38473-36126&t=DznyWuGmdqYLC3zq-11

**Comment by Bonapara** [comment]
Actually, I think we should use the tables since these cards are not used anywhere else in the app. I initially created them to "fill the space," but we don't need to do that anymore. However, I can create a separate issue if you want, @AMoreaux!

![image](https://github.com/user-attachments/assets/f4ec5f4b-0a09-4f94-b3fe-4e1ac514c012)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=38473-99867&t=DznyWuGmdqYLC3zq-11

**Comment by AMoreaux** [comment]
Thanks @Bonapara. Yes for the new UI it's better to do another issue.
