### ISSUE TITLE
Add ability to search objects and fields

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6770]
# Current Behavior

Today, searching for objects and fields in the data model settings is impossible. This makes it difficult for users to find what they're looking for when there are many items.

![CleanShot 2024-08-28 at 16 27 28](https://github.com/user-attachments/assets/a0612f83-1c8d-479f-876b-68d7ea09c816)

# Desired Behavior

We want to introduce an input field to search these tables. It should have an 8px bottom padding and use the standard input component:

![image](https://github.com/user-attachments/assets/13d6082f-f241-445e-8f60-25c21a4e0eb0)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34845-129115&t=DznyWuGmdqYLC3zq-11

**Comment by Bonapara** [comment]
@ijreilly FYI! Do you think it's suitable for an external contributor?

**Comment by ijreilly** [comment]
assigning you @ehconitin !

**Comment by ehconitin** [comment]
https://github.com/twentyhq/twenty/pull/6775  :)
