### ISSUE TITLE
Deactivated objects can still be accessed using shortcuts & cmd+k

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6776]
**Scenario:**
1. Log in
2. Go to Settings > Data Model
3. Click on any active object, e.g. Companies, then on three dots near "Standard" label and click "Deactivate"
4. Go back to main page and use corresponding shortcut to access deactivated objects

**Actual:** Deactivated objects can still be accessed using shortcuts
[Screencast from 2024-08-28 20-43-15.webm](https://github.com/user-attachments/assets/425d21d4-62a1-43de-86e2-b48049d7baae)

**Expected:** Deactivated objects shouldn't be accessed using shortcuts until they're re-activated by the user.

**Comment by Bonapara** [comment]
This should be tackle when we will work on the cmd+k

**Comment by charlesBochet** [comment]
Should still be easy to change in the current code base, tagging it as good first issue

**Comment by FelixMalfait** [comment]
@sid0-0 could you please comment on the issue to let me assign it to you? Thanks a lot

**Comment by lucasbordeau** [comment]
See https://github.com/twentyhq/twenty/issues/7503
