### ISSUE TITLE
Api instead of API in API key details

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6778]
**Scenario:**
1. Log in
2. Go to Settings > Developers
3. Generate new API key if there are no API keys
4. Check details of API key

**Actual:** In some places there are "Api" instead of "API"
![image](https://github.com/user-attachments/assets/1d08526a-4804-421b-a13d-d0b4081e3b5f)

**Expected:** In all places there must be "API" as it's abbreviation for Application Programming Interface

**Comment by patch-sys** [comment]
Hey @BOHEUS , I'm new to contributing in OSS could I take this up?

**Comment by BOHEUS** [comment]
@patch-sys no because it's already taken as you can see linked pull request, if you want, you can take different "good first issue"

**Comment by charlesBochet** [comment]
@patch-sys this issue was indeed already taken but feel free to tackle any other good first issue :)

**Comment by BOHEUS** [comment]
@charlesBochet this issue can be closed as PR is merged
