### ISSUE TITLE
feat(invitation): allow to use personal invitation + improve UI on member settings page

### ISSUE THREAD

**Issue by AMoreaux** [twentyhq/twenty#6782]
## Scope & Context

Milestone 2 of #6763 

## Current behavior

![image](https://github.com/user-attachments/assets/8210f284-95e3-4719-977f-7cfe0cdbbd98)

## Expected behavior

![image](https://github.com/user-attachments/assets/c05b74fc-f741-41a0-b324-571b502211b1)

### Must have
- [x] Create an "invite by email" section with the invitation status
- [x] Change the cards to lists for a more compact view
- [x] Customize the invited avatar as you suggest
- [x] Remove the email icon from the add email input
- [x] Add a "Reload" to send a new invite mail
- [x] Add a "Sent X days ago" to indicate when the invitation was sent (just saw you said days remaining, that's a good idea too!)
- [x] Add an "Expired" status for when the invite is expired

### Should have
- [ ] We should add some tooltips over the icon button to indicate what they are doing

### Nice to have
- [ ] We could also auto-delete the expired invitation after some time? e.g 1 month?

## Technical inputs

I don't know for now.

**Comment by AMoreaux** [comment]
@Bonapara I can't display a Name on an invitation since I don't have it. I have only an email and an expiration date.

**Comment by Bonapara** [comment]
True... Good point, thanks!

![image](https://github.com/user-attachments/assets/35d538d8-a8bf-43ee-ba54-95bccf8326db)

**Comment by charlesBochet** [comment]
I've seen you have opened PR recently, we will take a look to them :)
