### ISSUE TITLE
Ability to add a Kanban card from the navbar

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6783]
# Current Behavior

Currently, users cannot add a card to a Kanban board (other than opportunities) directly from the navbar, unlike in table views where this functionality is available.

![CleanShot 2024-08-29 at 11 39 39](https://github.com/user-attachments/assets/fa1681b0-43df-48d3-b800-96f94cff47d8)

On opportunities, the company picker that is displayed after the stage picker appears on the top right.

# Desired Behavior

### Case 1: Other Kanban Boards

Reintroduce the `plus icon button` in the navbar. Clicking this button should display a menu to select the Kanban stage where the new card will be added.

![CleanShot 2024-08-29 at 11 32 59](https://github.com/user-attachments/assets/36dc46a4-8901-48a8-90b7-48e3a18b1732)

A new, empty card should be added directly at the top of the selected column. Ideally, implement https://github.com/twentyhq/twenty/issues/6957 simultaneously.

![CleanShot 2024-08-29 at 11 37 23](https://github.com/user-attachments/assets/e36bc0f0-fbf4-4692-8c77-01ffdb36e114)

### Case 2 Opportunities Kanban

When adding a card on an opportunity kanban, the interface should show a company selection menu at the top of the selected stage, similar to the column-specific plus icon button. This will enable a consistent behavior for the + button at the top right corner, displaying only the stage selector.

![image](https://github.com/user-attachments/assets/23157bf7-46a5-44bf-adbd-2cea9bb7d36a)

**Comment by ehconitin** [comment]
Assign me please 😅

**Comment by Bonapara** [comment]
Done. You're a beast @ehconitin, thanks for contributing this much ;)

**Comment by charlesBochet** [comment]
@Bonapara could you clarify this issue, it's discussing both the '+' on top of a column and the '+' on top of the page.

The behavior regarding the '+' of the column is clear but could you clarify the '+' on top of the page in case of 'Opportunity' board ; we would need to select both the related company and the stage, it might be expensive. In this case should we only select the stage and let the user select the related company later?

**Comment by ehconitin** [comment]
@charlesBochet I agree it is expensive!
I could get this work but not as @Bonapara expected.
Will be cleaning up the code and creating a PR when done.
adding a record without relations is super easy, its selecting relation is what expensive.


https://github.com/user-attachments/assets/04c3b96b-a6eb-4cde-bc84-6af043af0e68


https://github.com/user-attachments/assets/36dd7144-add0-478c-9962-00cc046d3aa9

**Comment by ehconitin** [comment]
[PR 6829](https://github.com/twentyhq/twenty/pull/6829)

**Comment by Bonapara** [comment]
Closing and replacing with https://github.com/twentyhq/twenty/issues/7002, which is up to date with the changes from the last PR @ehconitin

**Comment by ehconitin** [comment]
Thanks @Bonapara !
