### ISSUE TITLE
Background Missing on Cards and Search Inputs

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6791]
# Current Behavior

Depreciation: Many cards have lost their background/secondary background:

Now:

![CleanShot 2024-08-29 at 18 33 41](https://github.com/user-attachments/assets/66d3f3fe-a3a6-40c2-98ea-eaf39d7c4862)

![CleanShot 2024-08-29 at 18 35 09](https://github.com/user-attachments/assets/78758586-7843-48ea-8ab7-087ff0f69586)

![CleanShot 2024-08-29 at 18 35 57](https://github.com/user-attachments/assets/d114774a-9ca8-4c7c-abb5-14f132503cce)

I think it is also the case for the **search inputs** introduced on https://github.com/twentyhq/twenty/pull/6700

# Desired Behavior

Before (Desired):

![image](https://github.com/user-attachments/assets/3fc06822-3505-4978-844a-c2d62f251ae8)

![image](https://github.com/user-attachments/assets/9f37e5d0-2ace-4fa1-95e9-e2850e89d4d6)

![image](https://github.com/user-attachments/assets/dbe3cce7-1ad1-4646-905e-cfdd7449ac22)

**Comment by Bonapara** [comment]
@charlesBochet a quick fix for tomorrow patch

**Comment by Bonapara** [comment]
@lucasbordeau maybe you can fix ittt

**Comment by kant-github** [comment]
Hey @Bonapara, I feel this was the solution, Although not all the workflow action has passed..
Let me know If this was right or not,
Thanks anyways.

**Comment by Bonapara** [comment]
We found the issue—it was with the background color of the page, not the cards!
