### ISSUE TITLE
fix: Deactivate & Activate icons should be swapped UI improvemets

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#6795]
## Bug Description

1. Based on Icon, the Deactivate and Activate icon propose opposite functionality. Swapping them would sync in with their purpose.

2. Minor bug but Delete Button under general has a white background when hovered as compared to traditional transparent background.

<img width="283" alt="Screenshot 2024-08-30 at 1 03 10 AM" src="https://github.com/user-attachments/assets/95c6b607-b55e-47ff-ba91-3bd73776359c">

<img width="301" alt="Screenshot 2024-08-30 at 1 04 27 AM" src="https://github.com/user-attachments/assets/9cfd536d-c064-4168-b4dd-ceeee655d7d8">

## Before

<img width="162" alt="Screenshot 2024-08-29 at 7 35 21 PM" src="https://github.com/user-attachments/assets/bf0bc2f1-cee5-403f-9a08-97c784e9637c">

<img width="165" alt="Screenshot 2024-08-29 at 7 35 39 PM" src="https://github.com/user-attachments/assets/e30591d1-8690-434e-8c7d-f6e8b9659d5e">

## After
<img width="157" alt="Screenshot 2024-08-30 at 12 52 53 AM" src="https://github.com/user-attachments/assets/97412e2a-df78-4f93-96b3-f9a7978c3889">

<img width="161" alt="Screenshot 2024-08-30 at 12 53 09 AM" src="https://github.com/user-attachments/assets/3fecbf56-4c1d-4741-9fa2-d58b15bfc7f8">

## Technical inputs

- Change the icons
- Change the button format

**Comment by charlesBochet** [comment]
Closing this as the fix on Delete button has been merged and "Activate" / "Deactivate" icons were actually correct
Thanks @harshit078!
