### ISSUE TITLE
fix: When clicked on InActive fields, 404 error is thrown

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#6797]
## Bug Description

Under Settings > Data Model, When clicked on a an Inactive field, An 404 error is thrown. The field can be Activated again and nothing happens. Only when clicked the field, the 404 error is thrown.

## Current behavior

https://github.com/user-attachments/assets/030f2423-26b2-4d2b-92d0-8dd656973fda

## Expected behaviour

- It should not thrown the 404 error and instead the edit Field component should be shown.

**Comment by bobbyy16** [comment]
hey @harshit078 and @FelixMalfait, Can I work on this?

**Comment by bobbyy16** [comment]
@harshit078, I don't see any issue with that, Can you elaborate more on this issue?

**Comment by FelixMalfait** [comment]
@bobbyy16 we should still be able to view/edit deactivated fields in settings. Because a field is deactivated doesn't mean it doesn't deserve its own page in settings :)

Thanks!

**Comment by HKS07** [comment]
hey @harshit078 and @FelixMalfait , can i work on it?

**Comment by FelixMalfait** [comment]
Yes sure, if the bug is clear for you! Thanks

**Comment by DurgaManikantaSai** [comment]
Hey @FelixMalfait, I want to work on it. Can I?

**Comment by charlesBochet** [comment]
@DurgaManikantaSai for now @HKS07 has been assigned and is probably working on it. We have a 3 days assignment rule. If we have no news from @HKS07 tomorrow, you'll be free to take it :)

Feel free to tackle any other unassigned good first issue

**Comment by HKS07** [comment]
Hey @charlesBochet, I am currently working on the task. As this is the first time contributing it took me some time to setup [ due to some errors].

I am able to generate the above behaviour. I will now be working to get the expected behaviour.

**Comment by HKS07** [comment]
Hey @charlesBochet, I have solved this issue before creating PR, I want to ask do I have to update the test where I have done some changes?

I have written this code to get object metadata item by slug

![image](https://github.com/user-attachments/assets/c7398b64-18ff-4d97-9842-02f24cc2a910)

**Comment by FelixMalfait** [comment]
Yes please create a test if you introduce a new util like that! Quickly checked a commit that referenced this issue, I don't have full context but a few notes: Try avoid using navigate() and use UndecoratedLink or something like that instead (better browser accessibility), make sure you update the H2Title description in the danger zone, don't redirect to another page when activating/deactivating if the page now becomes accessible, don't leave console logs
Thanks!

**Comment by HKS07** [comment]
Hi, @FelixMalfait and @charlesBochet, I have opened the pull request please have a look and let me know if I need to do any changes.

**Comment by HKS07** [comment]
Hi @FelixMalfait and @charlesBochet,

Just wanted to follow up on the pull request I submitted. Let me know if you have any feedback or if any changes are needed.

Thanks!

**Comment by charlesBochet** [comment]
@HKS07 sorry for the slow review, we have a lot right now! I will review it shortly
