### ISSUE TITLE
Dark mode Switcher

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#680]
Ability to switch to dark mode from the settings in an "Appearance" section:

https://github.com/twentyhq/twenty/assets/19412894/ff9fabd2-1f5b-46ea-806f-6a546cad562e

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5527-64077&mode=design&t=7EMwHjFESDCXfV66-4

**Comment by charlesBochet** [comment]
Todo:
- add user setting (theme: enum: Light | Dark | Auto) 
- add experience page
- add updateUser on experience page
- integrate Appearance switcher on FE
- user theme in AppThemeProvider
- best effort on animation : try to match figma (talk to Thomas before starting animation)

**Comment by FelixMalfait** [comment]
Great job with the design @Bonapara, love it and didn't expect something so nice!
Auto is a bit confusing for me I prefer "System preference" but I understand it's not as nice visually

**Comment by Bonapara** [comment]
Let's go for "System settings" then!
<img width="658" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/1d21d9e3-fd67-4c78-980e-7cfa3333517d">
