### ISSUE TITLE
[Bug] SingleEntitySelectMenuItemsWithSearch and MultiRecordSelect Creating Empty Object Record

### ISSUE THREAD

**Issue by Nabhag8848** [twentyhq/twenty#6801]
## Bug Description
- MultiRecordSelect Creating Empty Object Record on Add New.

https://github.com/user-attachments/assets/2ed39a5b-ee22-4558-8215-f7b1fa8dd6f0

- Similarly SingleEntitySelectMenuItemsWithSearch Creating Empty Object Record on Add New.

https://github.com/user-attachments/assets/bba15d0a-7aa9-4105-81ef-1cf54b405334

### Expected

- [ ] Shouldn't create empty new object record

**Comment by charlesBochet** [comment]
@FelixMalfait could you clarify what we want here with the Add New behavior?

**Comment by FelixMalfait** [comment]
Mmh I don't get the bug here @Nabhag8848 to be honest, what would you have expected? Thanks!

**Comment by Nabhag8848** [comment]
@FelixMalfait So when we add empty view -> that leads to creation of new object record with Name Field as empty which i believe we don't need it as per #6734

https://github.com/user-attachments/assets/a3e47eb6-374c-4a24-9a1d-dbea5d89ebd6

**Comment by FelixMalfait** [comment]
It's a good point but I don't see a good/clean short-term fix for that. I think we'll need to introduce a backend status like "draft" or some similar concept in the future, but the product specs aren't clear yet. We could hack something in the context of the list view but it seems harder to hack it in a sidepanel context. I'd say we should close this for now unless somehow has a great idea to improve the behavior here.

Closing but let's reopen if someone does! Thanks for the suggestion @Nabhag8848
