### ISSUE TITLE
CurrencyField Isn't Showing 0 on cell and record page and by default doesn't differentiate between empty and zero when changing to empty

### ISSUE THREAD

**Issue by Nabhag8848** [twentyhq/twenty#6802]
## Bug Description

- [ ] Doesn't diffrentiate between Zero as currency value and Empty. 
- [ ] Doesn't show Zero as Currency Value on Record Cell and Record Page. 

https://github.com/user-attachments/assets/15e5bd66-7f8f-406c-bc84-91d46d4ae380

**Comment by shagunsharma6677** [comment]
Hey @Nabhag8848 

I would like to work on this issue. Can you please assign this issue to me.

Thanks

**Comment by charlesBochet** [comment]
Thanks for reporting!

What we want:
- in database, the empty value should be a NULL value ; a 0 should be 0
- in FE, if empty is should be fully blank in RecordTableCell and (Empty) in RecordInlineCell on showPage and board cards

**Comment by charlesBochet** [comment]
@shagunsharma6677 Assigning you, thank you!

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by nganphan123** [comment]
Hi @charlesBochet , I'd love to work on this and will create a PR soon.
