### ISSUE TITLE
Ability to Filter by Creation Source

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6808]
# Current Behavior

We introduced the `Created by` standard field recently which is comprised of:

- A Creation Source
- A Creator Name

Today it's not possible to filter by creation source, only by creator name.

![CleanShot 2024-08-30 at 16 33 19@2x](https://github.com/user-attachments/assets/be4645a6-2119-424c-9676-c8cee08c464e)

# Desired behavior

We want to introduce a way to filter by `Creation source` for instance filter the records that were created by `API`

Related to https://github.com/twentyhq/twenty/issues/6425

**Comment by charlesBochet** [comment]
@ijreilly Adding this to gitstart scope

**Comment by Bonapara** [comment]
![CleanShot 2024-09-02 at 12 16 24](https://github.com/user-attachments/assets/be1e1fba-39fd-4139-8767-92a1f5ce90e4)
