### ISSUE TITLE
Independent Handling of Relations Between Objects

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6809]
# Current Behavior

When there are multiple relations between two objects, if two relations link to the same distant record, detaching one relation will detach the other.

https://github.com/user-attachments/assets/0afcf204-6fe4-4fbd-b145-b4b602f1c4a7

# Desired Behavior

Relations should behave independently from each other.

**Comment by charlesBochet** [comment]
@Weiko FYI, this should not be an issue anymore when we deprecate pg_graphql

**Comment by charlesBochet** [comment]
I'm going to close this issue as this will be fixed by design :)

**Comment by Weiko** [comment]
Agreed! Reopening as a 0 point issue just to keep in mind and check after the new implementation.

**Comment by FelixMalfait** [comment]
Linked: #6859

**Comment by charlesBochet** [comment]
This has been fixed by pg_graphql deprecation, closing :)
