### ISSUE TITLE
fix: Minor UI bug

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#6811]
## Bug Description

- Deleted button lacked `accent danger` on options menu
- Customize fields `onhover` lacked width to cover entire div tag
- Deactivate button lacked variant

## Currently

<img width="245" alt="Screenshot 2024-08-31 at 1 09 12 AM" src="https://github.com/user-attachments/assets/24cde5b9-ba5b-44ba-9c99-12fd989b236e">

<img width="177" alt="Screenshot 2024-08-31 at 1 10 06 AM" src="https://github.com/user-attachments/assets/39662317-6636-48bb-9878-f7278908962a">

<img width="263" alt="Screenshot 2024-08-31 at 1 42 42 AM" src="https://github.com/user-attachments/assets/1a53618b-c6d9-4efd-acec-ed26fe0d846d">

## Expected behavior

<img width="305" alt="Screenshot 2024-08-31 at 1 43 29 AM" src="https://github.com/user-attachments/assets/82852227-e7d2-4327-a8cc-8f9f0e84f488">

<img width="229" alt="Screenshot 2024-08-31 at 1 09 31 AM" src="https://github.com/user-attachments/assets/4783dd5a-a8ab-41b5-83d5-95425b6bebc4">
<img width="163" alt="Screenshot 2024-08-31 at 1 07 49 AM" src="https://github.com/user-attachments/assets/33ec9928-6463-4797-bfc4-b40a927ec8ec">

## Technical inputs

- Add accent danger on Dropdown
- Increase the width

**Comment by charlesBochet** [comment]
Fix has been merged thanks @harshit078 for reporting and fixing it!
