### ISSUE TITLE
[bug 🐛] : Cell in edit mode clips around when scrolled across page

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#6813]
## Bug Description

When a cell is in edit mode, if the user scrolls across the page then it clips through the table and hinders with the view.

## Current behaviour

https://github.com/user-attachments/assets/7c6625bb-4c04-4f8b-b3b1-ba9308b9ea47

## Expected behavior

It should stay at its original position or come up with an another workaround for this.

**Comment by Nabhag8848** [comment]
- duplicate / related  #5595

**Comment by charlesBochet** [comment]
Closing as duplicated, let's make sure it's resolved while merging the other issue
