### ISSUE TITLE
[bug 🐛 ] : fix page header accessible when deleting webhook

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#6817]
## Bug Description

- Settings> Developers> open any existing webhook > Delete
- When Deleting a webhook, the header and `save` and `cancel` buttons are still accessible
- For mobile Viewport, the save and cancel buttons are not present itself.

## Current Behaviour

https://github.com/user-attachments/assets/75b18ffd-0f65-481c-9065-7cd09a315ba3

## Expected behavior

https://github.com/user-attachments/assets/cbac0b56-578f-49d5-a092-84f936016ca6

## Technical inputs

**Example:** 
```
- Change propties of Header and apply CSS properties
- Rearrange the logic for Save and Cancel button for mobile viewport(768)
```

**Comment by harshit078** [comment]
## Proposal

- Either the Save and Cancel button remain in header or we can move their state in page body like the existing. What are your views on this @Bonapara @lucasbordeau 

<img width="700" alt="Screenshot 2024-08-31 at 7 14 03 PM" src="https://github.com/user-attachments/assets/50a3e5f8-2af4-40f0-b253-172c2323c7bb">

**Comment by charlesBochet** [comment]
@harshit078 I'm not sure to see the issue
When you hit 'Delete' the modal background overlay should make impossible to click on the button (and if they are keyboard listener they should be disabled too)

Isn't it the case?

**Comment by charlesBochet** [comment]
I see that we have the following behavior:

<img width="1496" alt="image" src="https://github.com/user-attachments/assets/aa6ef7c7-60e3-41bf-b98e-79a22a8929b5">

I don't think this is right and will likely be fixed in an upcoming PR

**Comment by harshit078** [comment]
I already came up with the solution and tested it locally have it ready with me. If not taken internally, can I push the PR on it ?

**Comment by Bonapara** [comment]
We should revert to that behavior indeed:

> When you hit 'Delete' the modal background overlay should make impossible to click on the button (and if they are keyboard listener they should be disabled too)

I think there is another PR on this one: https://github.com/twentyhq/twenty/issues/6737#issuecomment-2323315465

**Comment by harshit078** [comment]
Would eliminating  - `z-index:20`; on `PageHeader.tsx `  

and adding -
```
  @media (max-width: ${MOBILE_VIEWPORT}px) {
    width: 93%;
    padding-top: ${({ theme }) => theme.spacing(3)};
    }
```
be a correct apporach ? As in the video attached, it shows the exact code running.

**Comment by harshit078** [comment]
@charlesBochet @Bonapara , is this issue resolved ?

**Comment by Bonapara** [comment]
Just checked—nope, it's still there!

**Comment by harshit078** [comment]
@Bonapara, Can I work it on then ?

**Comment by Bonapara** [comment]
Sure @harshit078, thanks for contributing!
