### ISSUE TITLE
404 error when accessing deactivated field

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6818]
**Scenario:**
1. Log in
2. Go to Settings > Data model
3. Go to any object
4. Go to any field details and deactivate it (it can also deactivated by clicking 3 vertical dots and selecting "Deactivate" option)
5. Try to access details of deactivated field

**Actual:** User is redirected to 404 error page
[Screencast from 2024-08-31 18-41-47.webm](https://github.com/user-attachments/assets/db4d8f0e-fd27-495c-8371-273e7bd56e74)

**Expected:** User should be redirected to details page of deactivated field? (final expected result decided by @CoreTeamTwenty)

**Comment by harshit078** [comment]
Hey @BOHEUS, this issue is already addressed in #6797

**Comment by BOHEUS** [comment]
Oh, my bad then, I'm closing this as duplicated, thanks @harshit078 for info
