### ISSUE TITLE
Data capture integrations

### ISSUE THREAD

**Issue by oddieis** [twentyhq/twenty#6822]
### Discussed in https://github.com/twentyhq/twenty/discussions/6799

<div type='discussions-op-text'>

<sup>Originally posted by **oddieis** August 30, 2024</sup>
It would be very helpful to remove friction from data capture by enabling one click browser plugins a la Folk CRM, so with a single click I can pull in linkedin records, create records from my browser url, etc. Are there any plans?</div>

**Comment by oddieis** [comment]
It would be good to add the ability to integrate the chrome plugin to gmail, to twitter, and to any wb page to be added to the crm. and i have not checked but it would be ideal that the plugin allows integration with a self hosted instance of twenty.

**Comment by charlesBochet** [comment]
@oddieis We have started working on a chrome extension with the community: https://github.com/twentyhq/twenty/tree/main/packages/twenty-chrome-extension

I think it's what you are looking for, would it work for you?
However, at the moment we do not have the bandwidth to maintain it and it's community maintained. It's likely that the core team owns it a bit later once the main product get more mature

**Comment by Grienauer** [comment]
I think this is what you are searching for
https://chromewebstore.google.com/detail/twenty/lanlmmgcjjmlbfbooodedgblillmnafb
maybe we can have this somewhere visible on the official page and also in the readme?

**Comment by Grienauer** [comment]
Is there another appropriate issue or label to report a problem with the Chrome extension?
I tested it but did not work out porperly…

![CleanShot 2024-09-03 at 11 26 46@2x](https://github.com/user-attachments/assets/27728480-9311-4fe5-b85c-0b43b5a06681)
A click on "generate a Key opens allways http://localhost:3001/settings/developers/api-keys even if I have set a custom Route.

**Comment by gaetan-puleo** [comment]
> Is there another appropriate issue or label to report a problem with the Chrome extension? I tested it but did not work out porperly…
> 
> ![CleanShot 2024-09-03 at 11 26 46@2x](https://private-user-images.githubusercontent.com/1458107/363928652-27728480-9311-4fe5-b85c-0b43b5a06681.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1Njc4MTUsIm5iZiI6MTcyNTU2NzUxNSwicGF0aCI6Ii8xNDU4MTA3LzM2MzkyODY1Mi0yNzcyODQ4MC05MzExLTRmZTUtYjg1Yy0wYjQzYjVhMDY2ODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMjAxODM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTAwZjZiNDVhNWRjNWNkY2E2YTRjMmFiM2U5YTgwMjc1NzUyMzYwODc3YTZjMWQwOTQ5YTNkNTgwZmQyNDFhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RrkoqK1czzoOuwh2BDieia_Oci28bZEPCvMe80lQB3A) A click on "generate a Key opens allways http://localhost:3001/settings/developers/api-keys even if I have set a custom Route. I want to use it with my selfhosted version of twenty

Same issue for me

**Comment by FelixMalfait** [comment]
Yes the chrome extension is not in a decent state we don't want to advertise it. We'll come back to it next year when we have more bandwidth to build something really nice
