### ISSUE TITLE
Data model list view - read-only mode

### ISSUE THREAD

**Issue by Taldres** [twentyhq/twenty#6823]
## Scope & Context
It's about the overview page in a data model. In my opinion, it lacks an option for a read-only switch.

This came to my attention when I was scrolling through my list and accidentally touched my touchpad. This immediately altered a value and in the worst case, I wouldn't even realize it. This is particularly problematic with boolean fields.

![Bildschirmaufnahme 2024-09-01 um 10 25 32](https://github.com/user-attachments/assets/6205f52a-6857-452f-8a58-105342d57b26)

## Current behavior

Inline editing of fields is enabled by default and there doesn't seem to be an option for disabling it or setting it to read-only mode.

## Expected behavior

I would like to see a read-only switch within the data models or generally in lists where fields are editable, or even in views that do not belong to a detail view.
Additionally, it might be helpful to introduce a general read-only switch for the entire application (topmost icon).

**Just an example:**
<img width="540" alt="Bildschirmfoto 2024-09-01 um 10 24 42 (1)" src="https://github.com/user-attachments/assets/bee3f28c-bfaf-408a-b827-4a2ffd3709e4">

**Comment by charlesBochet** [comment]
I'm not sure we want to integrate such option, maybe we want to make more explicit that a data has just been modified?

@Bonapara what do you think?

**Comment by Taldres** [comment]
> I'm not sure we want to integrate such option, maybe we want to make more explicit that a data has just been modified?
> 
> @Bonapara what do you think?

Thank you for the prompt response. You're probably right, such a function might seem not the right since a CRM is primarily for maintaining data. Perhaps what we really need is better handling of switch fields like "boolean," etc., to prevent unwanted changes with a single click.

I read something in another PR about read-only permission/role, which made me think that at least the option could also be interesting for other users, without the read-only role.

If such a mode is not desired, that's absolutely fine. :)

**Comment by Bonapara** [comment]
Hi @Taldres, thanks for creating this issue!

I believe the permissions will indeed serve as the ultimate read-only method. We are also planning to introduce read-only access for certain system fields, such as rich text, which cannot be edited from the list view. You can follow the progress here: https://github.com/twentyhq/twenty/issues/6491.
