### ISSUE TITLE
[Firefox] Reset button in Deleted {object} view is too high

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6826]
**Scenario:**
1. Log in
2. Go to any Object page (e.g. Companies)
3. Click on Options > Deleted {Object}

**Actual:** "Reset" button is too high
![image](https://github.com/user-attachments/assets/5ca1a030-e809-4851-9702-add6d6c04a39)

**Expected:** "Reset" button should be the same height as "Save as new view" button near it

**Comment by kant-github** [comment]
I have looked into the issue @BOHEUS 
Checked twice but the _'Reset'_ button looks perfectly placed with _"Save as new view"_ button to me.
Or may be someone has already solved this

**Screenshots**
<img width="451" alt="Screenshot 2024-09-02 at 12 52 23 AM" src="https://github.com/user-attachments/assets/2efaa4ca-002d-45fe-9209-8ff3e8f333cf">

**Comment by BOHEUS** [comment]
@kant-github because you're checking it on Chrome while I sent a screenshot from Firefox, upon further checking it turns out it's Firefox problem, I'll fix the title
![image](https://github.com/user-attachments/assets/4fa5a729-63e6-4592-91dc-e13fb7392ed0)

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by vamus092** [comment]
i would like to work on this please assign the task to me

**Comment by ehconitin** [comment]
![Image](https://github.com/user-attachments/assets/8e3d8e19-3655-4c82-9e08-806a437b6c1d)

@BOHEUS was this fixed? can not reproduce!

**Comment by ehconitin** [comment]
I am closing this issue! @BOHEUS please re-open if you can reproduce this bug.

**Comment by BOHEUS** [comment]
@ehconitin from what I'm checking, it seems it's working fine but I'm not sure when or by who it was fixed...
