### ISSUE TITLE
When user wants to import data, error in devtools appears

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6827]
**Scenario:**
1. Log in
2. Go to any Object tab (e.g. Companies)
3. Click on Options > Import

**Actual:** Error in devtools appears
![image](https://github.com/user-attachments/assets/06851e35-cf33-458f-a07d-a774c09646bd)

**Expected:** No error should appear in devtools

Error:
```
Warning: SpreadsheetImport: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
```

**Comment by FelixMalfait** [comment]
I think this should be fairly easy to fix (?).
We need to update `spreadsheetImport.tsx` and get rid of `defaultProps`.
Not sure what's the impact but it's probably not very hard to replace it (?)

**Comment by gazjones00** [comment]
I'll pick this up @FelixMalfait

**Comment by FelixMalfait** [comment]
Thank you @gazjones00!

**Comment by gazjones00** [comment]
@FelixMalfait can we mark this as closed, please?

**Comment by FelixMalfait** [comment]
Yes @gazjones00 thank you! Next time you can add "fixes #xxxx" in your PR description to link it and close the issue automatically

**Comment by gazjones00** [comment]
> Yes @gazjones00 thank you! Next time you can add "fixes #xxxx" in your PR description to link it and close the issue automatically

Sounds good, thank you!
