### ISSUE TITLE
[bug 🐛 ]: when moving a task from ToDo to Done, the transition glitches out

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#6830]
## Bug Description

- Under Tasks, check the first most task to state done by clicking the circle icon. The state performs a weird animation. Only happens when selecting the very first task.

## Current behavior

https://github.com/user-attachments/assets/5a03133f-f965-4014-84fd-7d92d8635a53

## Expected Behaviour

The transition should occur normally just like other tasks.

**Comment by Bonapara** [comment]
The done & to do sections switches positions on click. They should not.

**Comment by lucasbordeau** [comment]
Closed by https://github.com/twentyhq/twenty/pull/6886
