### ISSUE TITLE
unable to login after upgrading to v0.24

### ISSUE THREAD

**Issue by Rounak826** [twentyhq/twenty#6831]
### Issue Summary

**Error after upgrading from version v0.23.1 to v0.24**

After upgrading the application from version `v0.23.1` to `v0.24`, I'm encountering the following error:

### Steps to Reproduce

1. Upgrade the application from version `v0.23.1` to `v0.24`.
2. Attempt to log in.
3. Observe the error message.

### Observed Behavior

- The login request in the network tab indicates that the login was successful and a token was generated.
- However, the subsequent `verify` mutation fails with the following error response:

```json
{
    "errors": [
        {
            "message": "column User__User_defaultWorkspace.metadataVersion does not exist",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "response": "column User__User_defaultWorkspace.metadataVersion does not exist"
            }
        }
    ],
    "data": null
}
```
### Expected Behavior
The verify mutation should succeed without any errors, and the application should continue to function normally after the upgrade.

### Additional Information
1. Version: Upgraded from v0.23.1 to v0.24
2. Error Message: "column User__User_defaultWorkspace.metadataVersion does not exist"
3. Network Logs: The login request is successful, but the verify mutation fails with the above error.
This issue appears to be related to a missing column in the database schema after the upgrade. Please investigate and advise on how to resolve this.

**Comment by Bonapara** [comment]
@Weiko bug?

**Comment by Weiko** [comment]
Hi @Rounak826, please follow this guide https://twenty.com/developers/section/self-hosting/upgrade-guide#v0.23.0-to-v0.24.0
We have added a new metadataVersion in 0.24 which is why you see this error.
