### ISSUE TITLE
Critical Bug: Filters apply to all views

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6833]
# Bug Description

Filters apply to **all views** instead of the selected view.

# How to Reproduce

1. Add a filter to a view.
2. Switch to another view of the same object.
3. The temporary filter is wrongly applied to that view too.

https://github.com/user-attachments/assets/60a5f4ab-4356-4476-8f19-e3818a9c27c3

# Desired Behavior

The temporary filter should only apply to the view from which it's added.

**Comment by Bonapara** [comment]
@thomtrp @lucasbordeau, do you think we might have a quick fix on this one?

**Comment by thomtrp** [comment]
@lucasbordeau do you have more context on this? I guess the state is global while it should be linked to the viewId?

**Comment by Nabhag8848** [comment]
> @lucasbordeau do you have more context on this? I guess the state is global while it should be linked to the viewId?


@Bonapara @thomtrp 

- ++1 currently Filters, Sort and Soft Deletes are global and aren't associated with views. 

I think following is the solution for that, Add viewId to Filter type:   

https://github.com/Nabhag8848/twenty/blob/f15c5e5b585d1121e1f631ee3f06d69335ed8b57/packages/twenty-front/src/modules/object-record/object-filter-dropdown/types/Filter.ts#L5-L14

and when we upsert for example for filter add viewId: currentViewId using already hooks we have here, similarly for sort and delete.

https://github.com/Nabhag8848/twenty/blob/f15c5e5b585d1121e1f631ee3f06d69335ed8b57/packages/twenty-front/src/modules/object-record/record-index/hooks/useHandleToggleColumnFilter.ts#L49-L62

and at the end we should mapViewFiltersToFilters by also filtering with the viewId adding condtion in this file.

https://github.com/Nabhag8848/twenty/blob/f15c5e5b585d1121e1f631ee3f06d69335ed8b57/packages/twenty-front/src/modules/views/utils/mapViewFiltersToFilters.ts#L7-L29

Should I tackle this with #6786 as both have similar issues and it makes more sense ?, if yes do assign :)

**Comment by Bonapara** [comment]
Bien joué !
