### ISSUE TITLE
Customize soft-delete empty state

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6834]
# Current Behavior

We display the "No records" empty state, which is confusing. Additionally, we offer the ability to add a record from the soft delete, which should not be allowed.

![CleanShot 2024-09-02 at 11 22 55](https://github.com/user-attachments/assets/7b2444df-f51c-456b-81ce-ca5f08d39a51)

# Desired Behavior

Display the following empty state: The "Remove Deleted Filter" should remove the deleted filter to allow the user to see non-deleted records.

![image](https://github.com/user-attachments/assets/1fb7e949-a0bb-4034-8ede-e196b16f7a2a)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=38833-78611&node-type=FRAME&t=W5U3Vvrsy9T8wUjD-11

**Comment by pacyL2K19** [comment]
I can work on this next @Bonapara

**Comment by Bonapara** [comment]
Sure @pacyL2K19, thanks for contributing and the previous PR on soft-delete!
