### ISSUE TITLE
Improve the soft delete style

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6836]
# Current Behavior

### Option Menu

1. The "Deleted XXX" menu item is displayed in red.
2. The "Deleted XXX" menu item icon is a trash can.

![CleanShot 2024-09-02 at 11 30 09](https://github.com/user-attachments/assets/3a74a88e-3aa0-459d-9752-2bfd93afda51)

### Filter Bar

3. We display the "Deleted XXX" as label in the filter bar.

![CleanShot 2024-09-02 at 11 31 09](https://github.com/user-attachments/assets/faa413c7-d6cd-47a7-bfb5-39d18309dfc9)

# Desired Behavior

### Option Menu

1. The "Deleted XXX" menu item should be displayed in gray (default color of menu items).
2. The "Deleted XXX" icon should be `Rotate-2`.

![image](https://github.com/user-attachments/assets/9c56b55f-2c83-4b27-928c-85a300f0d187)

### Filter Bar

3. We should display "Deleted" instead of "Deleted XXX". The icon should remain a trash can.

![CleanShot 2024-09-02 at 11 31 56](https://github.com/user-attachments/assets/93515002-79f1-4018-93f1-0d3aad5d2e57)

**Comment by pacyL2K19** [comment]
I can work on this next @Bonapara

**Comment by Bonapara** [comment]
Sure @pacyL2K19, thanks for contributing!
