### ISSUE TITLE
Breadcrumbs Ignore Temporary Filters on Detail Page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6837]
# Current Behavior

Temporary filters are not applied to detail page navigation. For example, I used a `name contains: l` temporary filter. However, when navigating to a detail page from that list, the temporary filter is ignored, and all companies appear in the breadcrumb navigation. (13 instead of 6)

https://github.com/user-attachments/assets/4e9ad0af-788f-49d1-a762-7a915448b70a

# Desired Behavior

We want the breadcrumb navigation on the detail page to reflect the filter applied to the list view.

**Comment by pacyL2K19** [comment]
Hi @Bonapara 
I can pick this next, please assign it to me

**Comment by Bonapara** [comment]
Sure @pacyL2K19, thanks for contributing!
