### ISSUE TITLE
Abstract company editable fields in generic ones by types

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#685]
AADev, right now we are duplicating some logic between PeopleCity, PeopleEmail, CompanyAddress... these could be refactored in a more flexible component. This is challenging regarding typescript as these fields will need to handle queries and mutations.
- Text
- Integer
- Float
- Date
- Relation
- URL

**Comment by FelixMalfait** [comment]
@lucasbordeau was this solved by the latest refacto?
