### ISSUE TITLE
Default "All" view in Tasks and Notes is not secured

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6863]
**Scenario:**
1. Log in
2. Go to Tasks or Notes
3. Click on number or rows near left top corner

**Actual:** Default "All" view in Tasks and Notes is not secured
![image](https://github.com/user-attachments/assets/2f4e8893-6442-401f-a8ca-754d6685cb59)
![image](https://github.com/user-attachments/assets/e4a48d21-3db4-4666-9e0c-ca1dd549275a)

**Expected:** Default "All" view in Tasks and Notes should be secured
![image](https://github.com/user-attachments/assets/3dd40cc9-92de-46c6-8f15-58de463c88d4)

**Comment by FelixMalfait** [comment]
Good point! Should be an easy fix in `tasks-all.view.ts` (and note), add `key: 'INDEX'`
