### ISSUE TITLE
Detail page inputs style

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6870]
# Current Behavior

1. Some input backgrounds are #FFF instead of being transparent with some blur.

![CleanShot 2024-09-03 at 09 36 46](https://github.com/user-attachments/assets/467069dc-b6ba-4c86-87b0-85e755bbfd8d)

2. The inputs are too large (320px)

![CleanShot 2024-09-03 at 09 41 19](https://github.com/user-attachments/assets/0425fdf1-5f8c-4930-a8b4-2f0a8be825fb)

# Desired Behavior

- Make sure the blur is applied on every field type input
- Make the inputs 240px wide 

![89200a6f70c897eef8c91da12b0ec0315027a99b6d27a7bb0e9112e537407bca](https://github.com/user-attachments/assets/8f41ec7e-13a6-48d4-a7f6-e3759562c487)

**Comment by harshit078** [comment]
Hi @Bonapara, Should reducing the width for Address field also count in this issue too ?

## Current
<img width="568" alt="Screenshot 2024-09-04 at 1 30 33 AM" src="https://github.com/user-attachments/assets/87fd35cc-2411-4784-b7ce-bb90618cfb47">

## After
<img width="489" alt="Screenshot 2024-09-04 at 1 30 42 AM" src="https://github.com/user-attachments/assets/79975ebd-ea98-4904-904a-4df91be4f2fa">

**Comment by Bonapara** [comment]
Hey @harshit078, you're right, let's keep the actual width for the address field!

**Comment by harshit078** [comment]
If we keep the current width of the address field then it clips through the page and goes overflow for mobile viewports. Decreasing the width for only mobile viewports can be the optimal solution. What are your views on this ? 
<img width="403" alt="Screenshot 2024-09-04 at 1 24 44 PM" src="https://github.com/user-attachments/assets/dccd71e1-323f-4631-ad96-89144ef7c060">

**Comment by Bonapara** [comment]
![CleanShot 2024-09-04 at 10 28 47](https://github.com/user-attachments/assets/57299626-b5de-427c-8db4-453eb814ca5b)

I think we could adapt the responsiveness like this on mobile. Thanks for the great input, @harshit078!

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=39053-99397&node-type=FRAME&t=RwXmhjVOkDpZzIFz-11

**Comment by harshit078** [comment]
Can I take this issue up @Bonapara ? Was working in this area already .

**Comment by Bonapara** [comment]
Sure @harshit078, thanks for contributing!
