### ISSUE TITLE
Migrate featureFlags to keyValuePair

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6875]
We had introduced a type=FEATURE_FLAG on keyValuePair but never finished migrating the config there

**Comment by Virajjai** [comment]
Hi there, @FelixMalfait could you explain a bit more with some code reference on this.

**Comment by FelixMalfait** [comment]
Hi @Virajjai thanks! This one is not very well defined so will probably be handled by the core team
