### ISSUE TITLE
Update Menu Item Font Size from 12px to 13px

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6878]
# Current behavior

Menu item font-size is +- 12px.

![CleanShot 2024-09-03 at 15 49 09](https://github.com/user-attachments/assets/bed8d708-ea01-48a4-87fc-7ed3e356428a)

# Desired Behavior

It should be base/regular (13px). Check everything works fine

![CleanShot 2024-09-03 at 15 46 59](https://github.com/user-attachments/assets/52d261d8-02bd-4e6e-b27d-3bca387326a1)

**Comment by harshit078** [comment]
Hi @Bonapara, Pushed the PR for this issue !

**Comment by Bonapara** [comment]
Thanks @harshit078! Looks good to me ;)
