### ISSUE TITLE
Update Date & Time default value placeholders

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6880]
# Current behavior

In the `Date & Time` menu in the `Appearance Settings`, we display "System Settings" everywhere. It's hard to grasp what I will see in the app

![CleanShot 2024-09-03 at 16 26 20](https://github.com/user-attachments/assets/d8de4cd0-4eaa-4b22-a88b-5e1f98cffa03)

# Desired Behavior

We want to add the value preview after "System Settings" to indicate what settings is currently applied:

![CleanShot 2024-09-03 at 16 26 00](https://github.com/user-attachments/assets/5a31b14a-0459-44bf-ada6-bf284f2b6907)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34845-125367&node-type=FRAME&t=k1LPRiYmNTVMVXNL-11

**Comment by rohitkumar1801** [comment]
Can I work on this issue ?

**Comment by Weiko** [comment]
Sure @rohitkumar1801, thanks!

**Comment by anuran0** [comment]
can I please work on this? will you please assign it to me?

**Comment by Bonapara** [comment]
Looks @angelali314159 already made a PR on this one @anuran0!

**Comment by G-gunjan** [comment]
Hello @Bonapara 
Can I work on this issue

**Comment by j4nlksh** [comment]
Lemme Know if this issue is up for grab - assign to me!

**Comment by Bonapara** [comment]
We already have a PR on this one ;) Thank you all!

**Comment by j4nlksh** [comment]
@Bonapara - Gotcha, Thanks!
