### ISSUE TITLE
When left menu is hidden, links can still be accessed

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6883]
Found during writing QA tests

**Scenario:**
1. Log in
2. Click on button on the left of icon of Object page (e.g. Companies)
3. On the left border of page try to click on link (if cursor's changed, then it's on right spot)

**Actual:** When left menu is hidden, links can still be accessed
[Screencast from 2024-09-03 19-49-34.webm](https://github.com/user-attachments/assets/62875a9e-fcfa-4a0b-9919-f9f2e196b1c2)

**Expected:** When left menu is hidden, links shouldn't be accessed

**Comment by Faisal-imtiyaz123** [comment]
@BOHEUS could you assign me?

**Comment by Bonapara** [comment]
Hi @BOHEUS, we will introduce a compact sidebar to fix this issue. I'll create the issue soon!

![image](https://github.com/user-attachments/assets/de74073d-b85e-4ac9-88b6-5fa7f8b215dd)
