### ISSUE TITLE
[bug 🐛 ]: Minor UI fixes in Settings page 

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#6887]
## Bug Description

- In Appearance under mobile viewport, page carries same width as normal viewport as a result it overflows.
- in  profile, Remove button doesn't have accent danger which doesn't maintain uniformity across UI.

## Current Behaviour

- https://github.com/user-attachments/assets/6e53f7f5-7fed-4482-9c67-fb33969429ab

- <img width="539" alt="Screenshot 2024-09-04 at 10 25 14 AM" src="https://github.com/user-attachments/assets/a1a1f8ac-8069-4b07-9ca1-d0c77596ff3b">

## Expected behavior

- https://github.com/user-attachments/assets/63e92a6a-6be5-4d0a-b42f-d4310492b8b4

- <img width="226" alt="Screenshot 2024-09-04 at 10 36 49 AM" src="https://github.com/user-attachments/assets/94e360c2-26ed-41f3-8943-dfee2b6c2a48">

**Comment by harshit078** [comment]
Hey @Bonapara, Should we adjust the `theme` section by editing the padding and css properties or should we give it a Scroll behaviour like in the above. What are your views on this?

**Comment by Bonapara** [comment]
@harshit078 thanks for this issue! A scroll sounds good ;)
