### ISSUE TITLE
Add dataTestId attribute to workspace dropdown

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6895]
While writing necessary code for E2E tests, I stumbled upon problem with locating properly the workspace dropdown as this `<div>` can't be found using data-testid attribute, placeholder text nor any indirect way but only by visible text (which itself is kinda problematic when new workspaces will be made and it changes every time when different workspace is selected) or by CSS class (which is a no-go in testing as these can be changed easily in the code, also it's a class so there can be more than 1 object having this class which will force using indexes which may result in 'flaky' tests). 
Please add data-testid attribute to this dropdown with value `workspaceDropdown` or anything similar (to be decided but it has to be unique compared to other values used in this attribute)
![image](https://github.com/user-attachments/assets/f342103c-5b24-4a81-a0ad-a45c9904b37f)

For comparison, that's how options inside workspace dropdown look like (they have data-testid attribute implemented)
![image](https://github.com/user-attachments/assets/c001695a-9038-4298-86ae-82b432c69489)

**Comment by Bonapara** [comment]
@Weiko you may want to have a look!

**Comment by FelixMalfait** [comment]
@BOHEUS would you want to handle this yourself? Otherwise I'll probably close this issue as it's a bit too specific to your current use-case / could be tackled as part of a test creation maybe? I'm trying to cleanup the issue to keep the ~250 most critical ones (we were at 350 yesterday, now down to 278).

I'll close it but please re-open if you can tackle this!

**Comment by BOHEUS** [comment]
If that's the case, I'll try to handle it by myself, I didn't work with React earlier but it doesn't seem to be a big change. Also, could you recommend some resources for self-learning React? I'd like to learn this if I'll ever need to implement something in the future

**Comment by FelixMalfait** [comment]
Hey @BOHEUS, what you can do is download this extension: https://chromewebstore.google.com/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?pli=1 ; it will help you locate the right component. 

To learn React the official documentation is quite good! https://react.dev/learn

Thanks
