### ISSUE TITLE
API Docs - Remove 'disabled' from link input for the local host option.

### ISSUE THREAD

**Issue by danxcraig** [twentyhq/twenty#6900]
I can submit a PR if approved for this one.

**Details** 

https://twenty.com/developers/rest-api/core#/

There are plenty of times a person might not select the default port of 3000 when running on localhost (for example, if they already have a service running on that port). 

However, when localhost is selected from the dropdown, the input field for the url is disabled, so the developer has no other choice either to abandon, or to figure out they can use 'Other', which isn't necessarily intuitive.

Suggestion is that input is enabled so that the user can update the port/address if required.

**Comment by danxcraig** [comment]
> Then maybe we should only keep `Other`? And change `Other` to `Localhost/Other`

I like it, but maybe just `Custom`? Makes it more obvious that this is the box you can put your own stuff in, but you won't be able to in the other two.

**Comment by Bonapara** [comment]
@FelixMalfait if you have an opinion

**Comment by FelixMalfait** [comment]
What you can do is change the input field to be editable and automatically match the select value to the string in the input field. So if a person goes and change the text then it automatically switches to "Other", unless for example it's changed to `https://api-demo.twenty.com`, then it becomes "Demo API"
Thanks a lot

**Comment by FelixMalfait** [comment]
@danxcraig do you want to raise a PR or should I close this? happy to merge the PR if you do! Thanks a lot

**Comment by danxcraig** [comment]
Thanks @FelixMalfait it's been a hectic week but yep I should finally have some time to take a crack at this tomorrow in the way you suggested.

**Comment by FelixMalfait** [comment]
Oh great thanks @danxcraig!

**Comment by FelixMalfait** [comment]
@danxcraig I'll close this since it's been open for long but a PR would always be welcome if you ever have time. No problem if not! Thanks
