### ISSUE TITLE
Automatic Logout and Recurring Fetch Errors Toast on Twenty Tab After Inactivity

### ISSUE THREAD

**Issue by neilk17** [twentyhq/twenty#6901]
Description:

Issue: After a period of inactivity on the Twenty Tab I get automatically logged out.

And I keep seeing a repeated toast notifications displaying fetch errors.

Expected Behavior:
- No error toast should appear

**Comment by Bonapara** [comment]
Thanks for raising this issue. Can you provide the error @neilk17?

**Comment by ehconitin** [comment]
Thats meant to be that way @neilk17 
For now, If you dont want to get logged out frequently just increase the EXPIRES_IN tokens in .env of twenty-server
for eg

![image](https://github.com/user-attachments/assets/9a788c9f-6313-44fd-be22-2317ee823e79)

**Comment by neilk17** [comment]
<img width="1728" alt="Screenshot 2024-09-05 at 4 10 44 PM" src="https://github.com/user-attachments/assets/abe8abd6-4a6f-4381-85b4-58f02154f950">

Thank you for the response - I'll update that!

But those toasts are the bug

**Comment by ehconitin** [comment]
@Bonapara 
If token is expired should those toasts appear? i dont think so .
They dont appear if u manually logout.
:)

**Comment by Bonapara** [comment]
@Weiko any idea on this one?

**Comment by BOHEUS** [comment]
@Bonapara I already reported the same issue #6731 and #6732

**Comment by FelixMalfait** [comment]
Thanks for the report! I'll close this issue to keep #6731 which we'll set as high priority
