### ISSUE TITLE
Unable to Scroll Long Notes

### ISSUE THREAD

**Issue by ehconitin** [twentyhq/twenty#6902]
## Bug Description

It's impossible to scroll through notes with content that overflows. The only way to go down is to use the keyboard arrows. This is because the wrapper height is not set to fill container.

https://github.com/user-attachments/assets/ac4757c4-133f-402b-9e0f-0ff78968d200

## Technical inputs

RichTextEditor should have scroll wrapper/ Its height should be set to fill container instead of hug content.

**Comment by Bonapara** [comment]
Sure @godwintrav, thanks for contributing!

**Comment by ehconitin** [comment]
@Bonapara 
its already fixed in #6903

**Comment by Bonapara** [comment]
Didn't catch it, thanks @ehconitin, unassigning you then @godwintrav, maybe you can grab another Good First Issue!
