### ISSUE TITLE
Verification popup can be activated multiple times

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6912]
**Scenario:**
1. Log in
2. Go to Settings > Developers
3. Generate new API key
4. Go back to Developers and check details of newly created key
5. Regenerate that key, write yes in popup and click Enter several times
- Instead of regenerating key, new keys are created
[Screencast from 2024-09-05 19-37-52.webm](https://github.com/user-attachments/assets/f8d56132-3afb-4caf-90b5-134788b1cd6b)
6. Close popup by clicking 'Cancel' button, click 'Delete' button, type 'yes' and click Enter several times
- Keys generated from step 5 and now being deleted
[Screencast from 2024-09-05 19-37-02.webm](https://github.com/user-attachments/assets/38d87b43-1735-495e-a856-2c7504ecdc0e)

**Actual:** By clicking Enter key over and over, user can repeat action (look how page refreshes and how UUID in URL changes)
**Expected:** When 'yes' is typed in popup and user clicks Enter key once, popup should disappear and correlated action should be performed only once

**Comment by ffshreyansh** [comment]
@BOHEUS  I tried following your mentioned steps when logged in with the `test credentials` but when i am trying to save the New API key form this error is thrown : `Error: ApolloError: Variable "$input" got invalid value { id: "42bcac73-3a07-4a01-8d7a-4320c940aacf" }; Field "expiresAt" of required type "DateTime!" was not provided.`. I tried changing the input of the expiration date, but still same error. 

Please let me know if it's and issue to be noted or am I doing something wrong!

<img width="1409" alt="Screenshot 2024-09-08 at 4 07 30 AM" src="https://github.com/user-attachments/assets/9f0c4fe1-cb4e-4baf-9c43-30aeb9bac2c7">

**Comment by ffshreyansh** [comment]
@Bonapara @BOHEUS  I just started the project in my local, but the above error i mentioned doesn't appear there. If all good can you please assign this issue to me... Thanks

**Comment by BOHEUS** [comment]
@ffshreyansh could you try repeating this on demo? I could reproduce it on both demo and locally. About the issue with expiration date, maybe it's a new bug, I'll confirm it whether I'm able to reproduce it and report it back, for now, use Never in expiration date if that works

**Comment by BOHEUS** [comment]
I created API keys with different expiration dates without any problems, I have no idea how can I help you with your problem, does any error (other than ApolloError) in devtools or in terminal appear when creating API key?

**Comment by ffshreyansh** [comment]
@BOHEUS only the demo is having this issue otherwise my locally it's all fine with different expiration dates. For now I will move ahead with this Issue's PR, i don't think it will affect it.

**Comment by BOHEUS** [comment]
@ffshreyansh now I see what you meant by this error, someone literally broke the whole app

@Bonapara @charlesBochet please take a closer look at `noah@demo.dev` account in dev, this account is unusable, object's records aren't loading, webhook/API key details aren't loading either, activating disabled objects doesn't work, maybe creating a database dump and trying to reverse it locally will help find out what happened and fix those bugs?

**Comment by ffshreyansh** [comment]
@BOHEUS  I have created the PR for this issue #6938 , please let me know what is the next step for the review.

**Comment by BOHEUS** [comment]
Wait till someone from core team will review it and either give feedback what needs further fixing or merge it
