### ISSUE TITLE
[bug 🐛 ]: Minor bugs in notes pages

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#6913]
## Bug Description

- Body of notes are not aligned with respect to content inside and clips out.
- `selected tag `lacks width for mobile viewport

## Currently behavior

<img width="646" alt="Screenshot 2024-09-06 at 1 12 33 AM" src="https://github.com/user-attachments/assets/60f3ec83-5976-40b1-a89e-01f28b8e809b">

<img width="244" alt="Screenshot 2024-09-06 at 1 13 31 AM" src="https://github.com/user-attachments/assets/89b77e03-fe58-4fab-88e2-f121d6e7eb72">

## Expected behaviour

<img width="585" alt="Screenshot 2024-09-06 at 1 15 07 AM" src="https://github.com/user-attachments/assets/206d4f65-c9d1-449a-8f05-f485116157ae">

<img width="242" alt="Screenshot 2024-09-06 at 1 15 20 AM" src="https://github.com/user-attachments/assets/88cd6acd-bb8e-4cf3-b5cf-169cb51c9f91">

**Comment by Bonapara** [comment]
Thanks @harshit078, great eye ;)
