### ISSUE TITLE
Different order of links on Twenty website

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6917]
There's different order of links on Twenty website:
- main page (story page has the same order as main page)
![image](https://github.com/user-attachments/assets/8caef189-f444-4de1-92af-c1e5f3043ae9)
- releases page (docs have the same order as main page)
![image](https://github.com/user-attachments/assets/a474a7ac-34a6-4a14-b168-e4ac633db85f)

Please fix this and make sure all pages on Twenty website have the same order of links

**Comment by Bonapara** [comment]
Done, thanks ;)
