### ISSUE TITLE
Update demo data "Created by" values

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6924]
# Current Behavior

When we create a workspace, it includes samples from 5 companies and 5 people to ensure it doesn't feel empty for first-time users. The "Created by" value is currently set to "System."

![CleanShot 2024-09-06 at 14 46 34](https://github.com/user-attachments/assets/988e148e-a080-4cb1-8b9d-afe94c8cdc53)

# Desired Behavior

We want to update the "Created by" value to "Twenty (Sample data)" and add the Twenty logo to enhance its appearance.

![CleanShot 2024-09-06 at 14 47 08](https://github.com/user-attachments/assets/a883d0b9-6ec7-453b-b8a9-8e7155d0b600)

**Comment by BoraTurkmen** [comment]
I would like to try completing this

**Comment by Brijesh206** [comment]
Hey @Bonapara , I'd love to work on this issue.

**Comment by yuvaraj8019** [comment]
Hey @Bonapara  , I like to work on this issue

**Comment by Bonapara** [comment]
@BoraTurkmen assigned you because you were first. Let me know if you're no longer interested!

**Comment by Bonapara** [comment]
/oss.gg 150
