### ISSUE TITLE
Make Dropdown properly handle max height

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#6927]
## Scope & Context

Dropdown should implement and handle the overflowing of its content.

Here I used a mock filter list to show that most dropdowns aren't handling it for now because we never have the case : 

<img width="491" alt="image" src="https://github.com/user-attachments/assets/b918c81b-b03b-4cbb-adc4-371c9c610141">

## Technical inputs

Since we're using floating-ui library, the best is to :
- See if we can portal all dropdowns by default
- Implement a size middleware (https://floating-ui.com/docs/size) that will resize the dropdown content div container automatically
- Verify that all dropdowns in the application are still behaving correctly

**Comment by Faisal-imtiyaz123** [comment]
@lucasbordeau This is the same issue as #6105

**Comment by FelixMalfait** [comment]
Good catch @Faisal-imtiyaz123 thanks!
