### ISSUE TITLE
Disabled typo in API key details

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6934]
Found originally by @lionelhorn on Discord https://discord.com/channels/1130383047699738754/1130383048173682821/1281262769412374599

**Scenario:**
1. Log in
2. Go to Settings > Developers
3. Create new API key if there's none
4. Check the details of API key

**Actual:** Instead of 'disabled' there's 'diasbled'
![image](https://github.com/user-attachments/assets/026531ee-853a-4bc8-a701-56e99579f4b4)

**Expected:** There must be 'disabled'

**Comment by Virajjai** [comment]
@BOHEUS I have opened a PR correcting this typo you can check it out. #6937
