### ISSUE TITLE
Notes are not visible in Timeline section

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#6935]
## Bug Description

- When created a note, it is not visible as its original color is set to black as a result If the theme is set to dark mode it's not visible. It works fine in light mode.

## Current behavior
<img width="1185" alt="Screenshot 2024-09-08 at 12 20 05 PM" src="https://github.com/user-attachments/assets/1de51150-9731-43e4-84b9-b3b92f95007a">

<img width="1195" alt="Screenshot 2024-09-08 at 12 20 27 PM" src="https://github.com/user-attachments/assets/2fb868b0-b66c-485f-b574-1beaf83bfb23">

## Expected Behaviour

<img width="1194" alt="Screenshot 2024-09-08 at 12 19 17 PM" src="https://github.com/user-attachments/assets/12455593-051d-490d-bc53-f5c5699f9c97">

**Comment by Bonapara** [comment]
Related to https://github.com/twentyhq/twenty/issues/6942
