### ISSUE TITLE
Timeline with notes has inconsistent behavior

### ISSUE THREAD

**Issue by gvkhna** [twentyhq/twenty#6942]
## Bug Description

Noticing several issues with notes/timeline. 

- In the timeline it does not show the link to the note, until you put a title. (Recommend to name a note untitled by default)
- In the timeline, in dark mode, the title is black
  
![Screenshot 2024-09-08 at 15 35 43](https://github.com/user-attachments/assets/eae05bd3-ee60-404b-ba7a-0053f2e73585)

- In the timeline, the link for the note doesn't seem to load until you also load the notes, but this is also inconsistent.

**Comment by Bonapara** [comment]
We once had a feature that prevented saving empty notes. We should reimplement this behavior.

**Comment by Bonapara** [comment]
Related to https://github.com/twentyhq/twenty/issues/6935
