### ISSUE TITLE
Bug - Ability to create empty kanban

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6946]
# Current behavior

It's possible to create a Kanban by pressing `Enter` even if there is no Select field assigned to it

https://github.com/user-attachments/assets/c770b956-0029-47a0-88c0-d2d768bb415a

# Desired Behavior

Pressing `Enter` should do nothing

**Comment by Nabhag8848** [comment]
@Bonapara working on it, do assign

**Comment by Bonapara** [comment]
Sure @Nabhag8848, thanks for contributing
