### ISSUE TITLE
View Switcher - Default Icon Display

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6947]
# Current behavior

If not customized, The view icon is set to the `Kanban` or `Table` icon. But the icon displayed in the `Icon Picker` doesn't reflect this. (It displayed the last icon selected in the picker, and by default the list icon)

https://github.com/user-attachments/assets/3f8c94f8-419a-475a-a685-2e6eb80c228f

# Desired Behavior

The picker should display the Table icon by default. If the icon hasn't been edited, the picker should reflect the default icon (Table or Kanban) until the user takes control and chooses a custom icon.

**Comment by Nabhag8848** [comment]
working on it @Bonapara

**Comment by Bonapara** [comment]
Thanks @Nabhag8848!

**Comment by rathodvinod5** [comment]
@Bonapara, I have resolved this bug, could you please assign it to me so that I can raise a PR?

**Comment by Nabhag8848** [comment]
hey @rathodvinod5 make the PR. thanks :)

**Comment by rathodvinod5** [comment]
@Nabhag8848, Thanks.
