### ISSUE TITLE
Enhance Field Type Page with Icons and Breadcrumb Update

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6950]
# Current behavior

When we add a new field to an object, we first need to choose the `field type` we want to add. There are two things to improve on this page:

- The field-type cards have no illustrations
 
![CleanShot 2024-09-09 at 14 21 35](https://github.com/user-attachments/assets/81aabc78-6939-4ccf-a294-c79b569d6543)

- The Breadcrumb Step selector is a 32px high Select element that displays the entire step name.

![CleanShot 2024-09-09 at 14 29 32](https://github.com/user-attachments/assets/9f5dfedd-5a38-4273-8781-56372e3178e0)

# Desired Behavior

- Add an illustration before each field type (dark and light mode). Ideally, use SVGs from Figma; otherwise, use the PNGs from the zip file below. 

[Icons.zip](https://github.com/user-attachments/files/16930352/Icons.zip)

![image](https://github.com/user-attachments/assets/a2de7688-01c7-4cba-9fa9-82396bc4c526)

- The breadcrumb step selector should be a 24px light icon button (tertiary).

![CleanShot 2024-09-09 at 14 31 28](https://github.com/user-attachments/assets/9d0800c2-a0eb-47c8-a3e2-9f633ddda0bd) 

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=36855-123514&node-type=FRAME&t=geQxFuEOuhKoYhCr-11

**Comment by dev13-suthar** [comment]
can i work on this

**Comment by Bonapara** [comment]
Sorry @dev13-suthar, @anamarn will handle it!

**Comment by BOHEUS** [comment]
@FelixMalfait this issue can be closed since changes are merged

**Comment by FelixMalfait** [comment]
Thanks @BOHEUS
