### ISSUE TITLE
Add Keyboard Navigation for Custom Field Selection

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6954]
# Current behavior

When creating a new custom field, the "Text field type" is selected by default on step one (displayed in a darker gray). 

![image](https://github.com/user-attachments/assets/789b1e85-7ac6-4c63-becc-86a2f2e52126)

# Desired Behavior

We want to introduce keyboard navigation to clarify why the "Text field" is pre-selected but most importantly to improve the navigation feeling! 

Press ⇥ to switch to the next field type
Press ⇧⇥ to switch to the previous field type
Press ⏎ to select a field type and navigate to step 2

![image](https://github.com/user-attachments/assets/3e4a83b3-2722-4b5f-bad6-319a6f19a31e)

Hover should be `Background Tertiary` and Selected `Background Quarternary`

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=36855-127361&node-type=FRAME&t=q1mVGIcAsAXgtU4g-11

**Comment by Bonapara** [comment]
@ehconitin, please comment so I can assign you!

**Comment by ehconitin** [comment]
:)
