### ISSUE TITLE
Set a record name on Kanban card creation

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6957]
# Current behavior

When creating a new record on a kanban board, you cannot set a name for the record from the kanban view. To name the record, you must go to the record detail page.

This doesn't apply to the opportunities kanbans where a specific behavior applies.

https://github.com/user-attachments/assets/cbd69ebb-ec2e-404f-a171-30e769daa9db

# Desired Behavior

We should implement the same behavior we have on table views: when creating a new record, we should display an input to set the record name from the board view. If the input is left empty, the card should be deleted, and the record should not be saved.

This doesn't apply to Opportunities kanbans.

![CleanShot 2024-09-09 at 17 34 55](https://github.com/user-attachments/assets/3b579c25-f8b4-4213-b26c-4f2e9c31361c)

The input label should be the object identifier. We should display the double input for people kanbans.

Table behavior to copy:

https://github.com/user-attachments/assets/8f58fdbc-fe75-44fc-a303-918f7fe78338

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara I would like to work.

**Comment by Bonapara** [comment]
Hi @Faisal-imtiyaz123, thanks! I believe it will be handled along with the other issue!

**Comment by Faisal-imtiyaz123** [comment]
@Bonapara Sure!

**Comment by ehconitin** [comment]
@Bonapara 
I think Ill work on this.
I still cant figure out #7002 :(

**Comment by Faisal-imtiyaz123** [comment]
@ehconitin @Bonapara can i work on #7002 since @ehconitin hasn't been able to figure it out yet?

**Comment by lucasbordeau** [comment]
Please @ehconitin could you drive this issue ? It's more important than https://github.com/twentyhq/twenty/issues/7002 and we I'll be really busy with code review this week so I'll appreciate that you focus on this.

**Comment by ehconitin** [comment]
Got it!

**Comment by ehconitin** [comment]
@lucasbordeau 
I am facing the same issue what I faced in #7002 
I just cant think of an efficient way to render a card or dropdown when clicked on top right add, adding them from inside a column is pretty straight forward.
Should we have something similiar to what we have for tables in RecordIndexPage, where we setPendingRecordId(v4()) and then setSelectedTableCellEditMode(-1, 0)
But then I couldnt figure how it would work in context of a kanban.
Need help :)

**Comment by lucasbordeau** [comment]
Yes we should follow the same approach !

**Comment by lucasbordeau** [comment]
Each column has its own scope so you should find a way to get the scope of a column and then all the recoil component state can be called by passing this scope as a parameter.

We use the parameter precisely for this use case where we want to access the component states from outside of their context.

**Comment by ehconitin** [comment]
@lucasbordeau Got it! Will let you know if I get stuck somewhere!
