### ISSUE TITLE
Update Email Sender Name for Workspace Invitations

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6958]
# Current Behavior

Currently, invitations to workspaces are sent from `contact@mail.twenty.com` with the name Félix from Twenty.

![CleanShot 2024-09-09 at 17 42 08](https://github.com/user-attachments/assets/1ac0ca87-424c-4ca4-a348-7142a25badb5)

# Desired Behavior

Invitations should still be sent from `contact@mail.twenty.com`, and the email name should be the `invitation sender name (via Twenty)` e.g. `Tim Cook (via Twenty)`

**Comment by Bonapara** [comment]
@Weiko, could you handle it since it's only about the cloud version? 🙏

**Comment by Bonapara** [comment]
Not implemented yet

**Comment by FelixMalfait** [comment]
@Bonapara there was an other issue already

**Comment by Bonapara** [comment]
@FelixMalfait do you have its number so I can link it to #7140?

**Comment by FelixMalfait** [comment]
It's 7001
