### ISSUE TITLE
Shortcuts to be added on tasks to edit relations and time

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#6959]
## Scope & Context

Clicking on Relations and Due date should open the component Relations and Due date in Fields which would act as an shortcut. Or as an alternate we should allow user to edit components directly from the task screen.

## Current behavior

<img width="1177" alt="Screenshot 2024-09-09 at 8 39 38 PM" src="https://github.com/user-attachments/assets/d044330e-bb92-4fe7-a490-5345d1cd6a1f">

<img width="460" alt="Screenshot 2024-09-09 at 8 41 56 PM" src="https://github.com/user-attachments/assets/6ffe07e4-5987-495f-b0b4-2e329c1a397c">

## Expected behavior

When clicked on due date and relations, it should allow user to directly edit the components here- 

<img width="216" alt="Screenshot 2024-09-09 at 9 01 09 PM" src="https://github.com/user-attachments/assets/e5ffaeb8-f422-411e-9e96-5d89a4d5fe73">

**Comment by harshit078** [comment]
@Bonapara, what are your views on this ? Should something like this be implemented

**Comment by Bonapara** [comment]
Hi @harshit078, good point! For V1, we should at least redirect to the correct tab in the side panel. For instance, when clicking on the relations, the side panel should open on the "Fields" tab.

**Comment by FelixMalfait** [comment]
I'm going to close this one for now because we don't have a good navigation system to send to the right tab. We can come back to it one day when the frontend layout/navigation system is a bit more mature. 
Thanks @harshit078 for the suggestions always
