### ISSUE TITLE
Members' emails are not shown

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6961]
Found on demo

I'm not sure what are the steps to reproduce this bug but on demo account `noah@demo.dev` in Settings > Members members' emails are not shown. Please investigate the root cause of the problem and steps to reproduce it.
![image](https://github.com/user-attachments/assets/6ea837fd-6150-4eb6-b7b3-145a050ff0f0)
If anyone thinks that's because of theme, it's not, because the position of members' first and last name is different, for reference here's how it normally looks
![image](https://github.com/user-attachments/assets/06f0705f-749e-441e-81f6-e5e7a3f21ad6)

**Comment by ffshreyansh** [comment]
@BOHEUS  I think we were having issue with this `noah@demo.dev` account as we discussed here: https://github.com/twentyhq/twenty/issues/6912#issuecomment-2336596598, shall we still move forward in fixing this issue for this particular account ?

**Comment by BOHEUS** [comment]
I created this issue mainly for investigation for core team since this account is the one provided in documentation for anyone who wants to try out the product without having to deal with all the problems setting up the app locally, I don't really expect anyone to be able to fix this since there are no steps provided to replicate it.

**Comment by charlesBochet** [comment]
@BOHEUS It's probably a seed issue!

when we provision demo, the userEmail are empty in the workspaceMember table in the workspaceSchema
<img width="1042" alt="image" src="https://github.com/user-attachments/assets/7f6c408b-a6d2-48b5-b7f8-323d3b6a15cb">

**Comment by Bonapara** [comment]
Fixed
