### ISSUE TITLE
Scroll per table in Developers

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6962]
As of now, if user has more than 20 API keys or webhooks, whole page has scroll, when for the end user (UX) it'd be better if each table had it's own scroll. I'm aware it's rather rare occurence but still something worth fixing. For reference that's how it looks like
[Screencast from 2024-09-09 17-41-44.webm](https://github.com/user-attachments/assets/a54572ab-f032-4b70-a9e4-3da486456e40)

**Comment by ffshreyansh** [comment]
@BOHEUS  I am on it, can you please assign this to me

**Comment by Bonapara** [comment]
Thanks for the fix @ffshreyansh!
