### ISSUE TITLE
Enhance picture uploader

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6966]
# Current behavior

1. The Remove button is red
2. The label is not well positioned

![CleanShot 2024-09-10 at 11 38 31](https://github.com/user-attachments/assets/c629f966-f9d1-4718-934d-bcd2f4c7a290)

# Desired Behavior

### Buttons

The button should be secondary and set to "hug content" rather than "fill content"

Activated:

![CleanShot 2024-09-10 at 11 34 51](https://github.com/user-attachments/assets/c488b4f6-dba9-4403-a37b-8499487ea219)

Deactivated:

![CleanShot 2024-09-10 at 11 35 23](https://github.com/user-attachments/assets/31678f6a-67c7-4555-9b01-133a265a3940)

### Label

The label should be under the buttons and not at the bottom of the container

![CleanShot 2024-09-10 at 11 37 11](https://github.com/user-attachments/assets/fe083483-c9cd-48a9-adac-d543ecf8c6f4)

**Comment by KoyalkarAditya** [comment]
Can I work on this issue??

**Comment by Bonapara** [comment]
Sure @VriaA, thanks for contributing!

**Comment by heber59** [comment]
i submit a pull request, I read you policy abut assigned issues but i start working on it beffore u assigned it and what to help :) hope u could see it.

**Comment by Bonapara** [comment]
@VriaA, do you mind creating another [Good First Issue](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee) this time?

**Comment by Bonapara** [comment]
Thanks a lot @VriaA :)

**Comment by Smnthjm08** [comment]
can i work on this @Bonapara , i'm new to open source

**Comment by Bonapara** [comment]
Hi @Smnthjm08, unfortunately, there is already a PR for this one! Maybe you can grab another [Good First Issue](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)
