### ISSUE TITLE
Empty screen when creating new field

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6967]
# Bug description

In the Data Model Settings - When a field is deactivated, clicking on "Add field" produces an empty page. The user has to reload the page to see the content.

https://github.com/user-attachments/assets/fa2364f1-d395-4003-8b70-1c0188b21ec6

**Comment by charlesBochet** [comment]
Assigning to @anamarn who is working on this part
@ijreilly FYI

@ehconitin to reproduce it you need to have at least one disabled field

**Comment by ehconitin** [comment]
Oh I can see this bug now, for some reason when I and Thomas were looking at it would appear but after like 10 secs.
But now it doesnt appear, not unless clicked somewhere on the screen.
Weird

**Comment by charlesBochet** [comment]
Yep, don't spend time on it we are refactoring this piece anyway!
