### ISSUE TITLE
Tasks page overflows with large title and body

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#6968]
## Bug Description

In Tasks page, When title and body are large there seems to occur a variety of bugs such as - 

- Task body and title not aligned with the checkbox.
<img width="1347" alt="Screenshot 2024-09-10 at 5 23 59 PM" src="https://github.com/user-attachments/assets/6409bace-28b4-48d9-93e4-3243ecbc5713">

- when a long title is given, the body cannot be seen and is overlayed by title.
<img width="1544" alt="Screenshot 2024-09-10 at 5 25 00 PM" src="https://github.com/user-attachments/assets/8124fa3d-8998-4d14-beed-8353f43d393c">

- when title is too long, the page gets scrolled hence it gets overflow

https://github.com/user-attachments/assets/7a18498e-1185-423e-922f-585d0f93eafb

## Expected behavior

- when long title, body should be seen and page should not get overflow

https://github.com/user-attachments/assets/3f64e246-6431-4eea-9acf-5bf124aadc22

**Comment by Bonapara** [comment]
Thanks @harshit078 for raising issues... and their PR!

**Comment by Hitarthsheth07** [comment]
@FelixMalfait can you please close this if it's merged! Thanks
