### ISSUE TITLE
Add support for Call/SMS (Phone) objects

### ISSUE THREAD

**Issue by gvkhna** [twentyhq/twenty#6973]
## Scope & Context

Add new standard objects: (Call/SMS)

Standard objects would allow for specific behavior around these objects, but still allow adding fields for users to customize data.

Calls (Fields):
- Transcription (text) [can be editable by api only]
- Notes (text)
- Time (duration)
- From
- To
- Date

SMS
- From
- To
- Message
- Date

Timeline view:
- Show SMS message inline
- Show "Call to Example Person - 10:43m", "Call from Example Person - 3:22m"

Separate tab for Phone (with combined call/sms)

This is how streak does it.

![Screenshot 2024-09-10 at 08 59 36](https://github.com/user-attachments/assets/66cf6f63-8c59-4255-908a-b7ac614fc925)

## Current behavior

Custom objects would get most of the way there. But the need to show this data in specific ways in the timeline for convenience, especially around SMS makes a new standard object that is handled slightly differently a better choice.

**Comment by charlesBochet** [comment]
@FelixMalfait 
@Bonapara

**Comment by Bonapara** [comment]
I think we should establish standard behaviors before creating standard objects, as it could be confusing to have standard objects that behave like any regular custom object.

I'll Keep it in mind for the near future though, maybe workflows will enable us to offer some custom behaviors and make such objects more interesting!
