### ISSUE TITLE
Remove dependency to chakra-ui

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6976]
We copy/pasted a spreadsheet-importer components which had a few chakra-ui components.

We should get rid of them and migrate to internal equivalents.

https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/spreadsheet-import/steps/components/MatchColumnsStep/components/UnmatchColumn.tsx#L11

I think it's just used in the context of matching values of select fields

**Comment by ehconitin** [comment]
Working on this @FelixMalfait

**Comment by FelixMalfait** [comment]
Thanks a lot @ehconitin!

I think we do have equivalent already. @Bonapara can probably help here!

**Comment by ehconitin** [comment]
Got it!

**Comment by ehconitin** [comment]
Merged ✅ 
Could you please close this issue

**Comment by charlesBochet** [comment]
Yes, ty!
