### ISSUE TITLE
[bug 🐛 ]: Tasks with longer body overflows in Timeline summary

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#6977]
## Bug Description

This issue is related to the already existing issue #6968.

- when a task with long title and body, it makes timeline summary scrollable.

## Current behaviour

<img width="1527" alt="Screenshot 2024-09-11 at 1 22 21 PM" src="https://github.com/user-attachments/assets/3ead52f5-e662-4926-8dd4-87afbef423aa">

https://github.com/user-attachments/assets/992c8b7a-04b2-4550-bcab-1f6e9706bf95

## Expected behavior

<img width="1218" alt="Screenshot 2024-09-11 at 1 21 58 PM" src="https://github.com/user-attachments/assets/ac0cb198-7768-44b7-8b59-5b20577d5263">

**Comment by Bonapara** [comment]
Thanks for creating this issue @harshit078!

**Comment by ranjithjupaka** [comment]
Hey, I would like to contribute to this issue

**Comment by Bonapara** [comment]
Sure @ranjithjupaka, thanks for contributing!

**Comment by ranjithjupaka** [comment]
Thanks for assigning. i was able to setup the repo locally but I am not able to find that exact page. can you help me to find that page.

![image](https://github.com/user-attachments/assets/90de17e7-1246-4646-b412-e5d1961a5341)

**Comment by Bonapara** [comment]
When you click on the title of a record @ranjithjupaka, for instance on a person in the company tab. Not sure it's occurring with the task object!

**Comment by harshit078** [comment]
@ranjithjupaka , Are you able to get to a solution ?

**Comment by Bonapara** [comment]
Looking good! Can you check why some values are not taking the full width? 
![CleanShot 2024-11-05 at 14 55 59](https://github.com/user-attachments/assets/e2d4785f-ce92-4249-a345-3e672c947f0f)
