### ISSUE TITLE
[Bug] Select options names can't start with a number

### ISSUE THREAD

**Issue by ijreilly** [twentyhq/twenty#6980]
## Current behavior

If a select (or multi-select) option starts with a number (ex: "12 months"), it will fail as it will attempt to create a 12_MONTH type in graphQL while graphQL types can't be prefixed by numbers.

## Expected behavior

This should be possible

## Technical inputs

Let's add prefix to options graphql types (ex: option_)

**Comment by Bonapara** [comment]
Related to https://github.com/twentyhq/twenty/issues/6146

**Comment by ijreilly** [comment]
@Bonapara thanks for the input, it's related indeed, but I think we can tackle this issue first independently. We should give user the possibility to create options starting with numbers without having to manually update the api option name through the advanced settings I think.
