### ISSUE TITLE
Improve storybook test logs

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#6981]
## Scope & Context

Storybook tests logs in CI (and local)

## Technical inputs

The Storybook test logs are very verbose, we want to create a new command where the following logs are not printed : 
- Static assets built (list at the beginning)
- Network logs : `error: Missing field '%s' while writing result %o, workspaceMembers,`, `log: Request:, {"url":"http://localhost:3000/graphql`, `log: Handler:, {"info"`, etc.

The goal is to end up with only the relevant logs when we have errors to fix.

**Comment by lucasbordeau** [comment]
@ehconitin Do you think you could tackle this ? It would be really helpful for code review on our side !

**Comment by ehconitin** [comment]
@lucasbordeau Sorry, out of my scope :(

**Comment by charlesBochet** [comment]
@lucasbordeau I'm closing this one, I think we should actually address those logs, they are covering underlying issues (cache won't be updated properly when they appear)
