### ISSUE TITLE
Allow input and display of floats for Number fields

### ISSUE THREAD

**Issue by ijreilly** [twentyhq/twenty#6987]
## Scope & Context
We only allow to persist and display integers for fields of type Number while there is demand for persisting/displaying floats + all our number fields data is stored in a column that accepts floats.

## Expected behavior

We always persist the input value if it's a number, but we display the value according to the decimal settings.
So for example let's say we have set the number of decimal to 0, but the input the value is 2.6.
We persist 2.6 and display 3.

## Technical inputs

The vision is to introduce a setting on fieldType of type 'NUMBER'.
NumberFieldTypeSetting {
decimals: number
}
This settings is settable in the product. Here is the design:
![image](https://github.com/user-attachments/assets/d923b988-e681-4f29-b80b-b2dfb712cf18)

This settings should be leveraged in the FE to display the value correctly.
In case it can be of any help - [a first PR](https://github.com/twentyhq/twenty/pull/6785) was opened on this topic but the issue can be taken over from scratch.

**Comment by gitstart-twenty** [comment]
Hello @Bonapara 👋 
could you send the Figma design for the option section?
![image](https://github.com/user-attachments/assets/b4dff24d-d9f3-4c2b-b601-aee241552b01)

**Comment by gitstart-twenty** [comment]
Thank you @Bonapara 
could you give us access to the dev mode on Figma? I sent this message with more details on discord: https://discord.com/channels/1130383047699738754/1163747555461570650/1283749603157610536
