### ISSUE TITLE
Research how to customize focus

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#699]
When navigation on tab: 
![Image](https://github.com/twentyhq/twenty/assets/19412894/388f179f-e100-477d-938d-63836d2c7c30)

I created some focus states on Figma

**Comment by charlesBochet** [comment]
On several components, we are handling the focus manually (tab). By default browsers also provide an easy way to specify focus order with tabIndex.
Would be nice to find a way to have both systems working (maybe programmatically add :focus css state and style :focus in css !?)
