### ISSUE TITLE
Prevent empty notes to appear in the timeline

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#700]
Two solutions:
1) Wait for something to be typed or modified to create the note

![Image](https://github.com/twentyhq/twenty/assets/19412894/9896f369-f935-477f-a400-fd50a19fb432)

Do not: create the note in DB but not display it if it's empty (that would pollute the DB), instead make sure the note is not created in DB if there is no content

**Comment by Mbistami** [comment]
I'll handle this one 😄

**Comment by charlesBochet** [comment]
Right now, we are creating the activity in two different places:
- useOpenCreateActivityDrawerForSelectedRowIds (triggered from the table when you select multiple lines)
- useOpenCreateActivityDrawer (triggered from the Timeline)

it looks we have some technical debt here, that we should also clean.
The behavior we would like:
- from these hooks, set a recoil state with the right activity target (re-use the old commentableEntityArray and rename into activityTargetsArray) and remove the activityCreation mutation call
- remove the RightDrawerTimeline that should not be use anymore
- make RightDrawerActivity work with either an activity, either an activityTargetsArray
- in RightDrawerActivity, we should store the activity in a state. We cannot keep it reactive as this would create conflicts between what the user is typing.
- in case we don't have an activity yet, we would need to have an async createActivity function that is called and awaited before all mutation (title, body, assignee, targets, dueDate) to create the activity.
- we also need to handle the case for the ActivityRelationPicker that might be a bit trickier (let's see if it can easily be solved too, using the same philosphy.

**Comment by charlesBochet** [comment]
@gitstart-twenty reassigning this issue to the core team

**Comment by Bonapara** [comment]
created #3649 to replace this one
