### ISSUE TITLE
Profile picture gets the same value of files

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7000]
## Bug Description

- Under files, inset any image
- Go to settings, refresh the page and see the profile picture gets the same image.

## Current Behaviour

https://github.com/user-attachments/assets/16ffd9d1-6c67-4667-855b-4a46f373760d

- On removal of file, however the profile photo doesn't get remove. You have to remove separately

https://github.com/user-attachments/assets/4903fbc0-3839-4bda-b06a-a0b5283cf2ce

## Expected behavior

On insertion of file of image, profile image shouldn’t take that value

**Comment by harshit078** [comment]
https://github.com/user-attachments/assets/13bc0caf-fa95-4413-97ea-96df7013ea9f

It also works when image is added under General/Picture and refreshed Profile section. Although vice versa doesn't happen. Only for General section

**Comment by sid0-0** [comment]
I haven't been able to recreate this. Are there any more steps to recreate this?

**Comment by ehconitin** [comment]
Could not reproduce either!
@harshit078 could you recheck if this was fixed?

**Comment by Bonapara** [comment]
https://github.com/twentyhq/twenty/issues/8425
