### ISSUE TITLE
Send workspace invitation email from the logged-in user

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#7001]
# Current Behavior

Currently, invitations to workspaces are sent from the server's default message sender

![CleanShot 2024-09-09 at 17 42 08](https://github.com/user-attachments/assets/1ac0ca87-424c-4ca4-a348-7142a25badb5)

# Desired Behavior

Invitations should appear to be sent by the person who created the invite.
e.g. if John Doe is logged in to Twenty and invites someone. Then the invite should be from "John Doe (via Twenty)". That's how Google Drive does it.

**Comment by KoyalkarAditya** [comment]
Can I work on this ?

**Comment by FelixMalfait** [comment]
Sure!
Maybe wait for #6626 to be merged (it will be merged tonight) and then tomorrow you can do the followup PR.
It's probably here:
https://github.com/twentyhq/twenty/pull/6626/files#diff-238c844112a9e74b07c4b90d5cc70dd55ac32e014b8d91aae1fb5fc5e34cf561R171

**Comment by venom-10** [comment]
Hey @FelixMalfait, can I work on this now?

**Comment by FelixMalfait** [comment]
@venom-10 sorry it's still ongoing! But by end of week it will be merged for sure.
It was replaced by #6804

**Comment by FelixMalfait** [comment]
@venom-10 good to go! you can make the change

**Comment by KoyalkarAditya** [comment]
sure will work on this

**Comment by JorgeGraciaViveros** [comment]
Hi @FelixMalfait ! I am currently working in a group of 5 students from Carnegie Mellon taking a software engineering course and our final project is to contribute to an open-source repo. Our project has multiple checkpoints and will be due on December 8 (meaning our PR will take longer to open). Would it be possible for us to be assigned to this issue (or any issues that you think would be a good fit)? Thanks!

**Comment by FelixMalfait** [comment]
@JorgeGraciaViveros yes this should be an easy one! Assigning it to you

**Comment by JorgeGraciaViveros** [comment]
@FelixMalfait Good evening,

Thank you for assigning this issue to us. We believe that we have successfully resolved this issue. Is there a way to check our changes before we create a pull request?

I am using branch p5 (for reference).

Thanks!

**Comment by FelixMalfait** [comment]
Hey @JorgeGraciaViveros just raise the PR, it doesn't need to be perfect to be raised - we can give feedback on the PR directly. Thanks!

**Comment by JorgeGraciaViveros** [comment]
Sounds great!

I checked the contributors list for the repository and I did not see my name which I’m not sure if it is causing my push branch error: remote:

Permission to twentyhq/twenty.git denied to JorgeGraciaViveros.
fatal: unable to access 'https://github.com/twentyhq/twenty.git/': The requested URL returned error: 403

By any chance could you add me as a contributor or how should I approach this?

From: Félix Malfait ***@***.***>
Date: Tuesday, December 3, 2024 at 4:25 AM
To: twentyhq/twenty ***@***.***>
Cc: JorgeGraciaViveros ***@***.***>, Mention ***@***.***>
Subject: Re: [twentyhq/twenty] Send workspace invitation email from the logged-in user (Issue #7001)

Hey @JorgeGraciaViveros<https://github.com/JorgeGraciaViveros> just raise the PR, it doesn't need to be perfect to be raised - we can give feedback on the PR directly. Thanks!

**Comment by FelixMalfait** [comment]
You can push to your fork on Github and create the pull request from your fork:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by JorgeGraciaViveros** [comment]
Got it, thanks! I just created a PR. Feel free to take a look and ping me once comments are made!:

https://github.com/twentyhq/twenty/pull/8858

**Comment by JorgeGraciaViveros** [comment]
Good afternoon,

I was wondering you could direct me to the area where we can send workspace invitations so that our team can demonstrate that this function works? @FelixMalfait

**Comment by FelixMalfait** [comment]
![Image](https://github.com/user-attachments/assets/18ae60be-b093-4215-bc89-bfa29d7259a9)
