### ISSUE TITLE
New cards process improvements on Kanban

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7002]
# Current Behavior

The plus icon button displays a menu to select the Kanban stage where the new card will be added.

![CleanShot 2024-08-29 at 11 32 59](https://github.com/user-attachments/assets/36dc46a4-8901-48a8-90b7-48e3a18b1732)

# Desired Behavior

### Case 1 - Regular kanbans boards

A new, empty card should be added directly at the top of the selected column. Ideally, implement https://github.com/twentyhq/twenty/issues/6957 simultaneously.

![CleanShot 2024-08-29 at 11 37 23](https://github.com/user-attachments/assets/e36bc0f0-fbf4-4692-8c77-01ffdb36e114)

### Case 2 Opportunities Kanban

When adding a card on an opportunity kanban, the interface should show a company selection menu at the top of the selected stage, similar to the column-specific plus icon button. This will enable a consistent behavior for the + button at the top right corner, displaying only the stage selector.

![image](https://github.com/user-attachments/assets/23157bf7-46a5-44bf-adbd-2cea9bb7d36a)

**Comment by ehconitin** [comment]
Closed in #7285
