### ISSUE TITLE
Last update field should update on new email reply/time line activity

### ISSUE THREAD

**Issue by paulyili** [twentyhq/twenty#7009]
The last update field should update when the timeline has created a new event/email etc. 

This way, you can further filter which customers you've interacted via email with today or in the last week. 

This can also be further used with API to an email marketing platform. E.g filter last updated 90 days or more to add a tag in the email marketing platform and trigger a workflow. 
As it'll be a little more accurate to actual activity. 

I thought it does work this way, but i noticed it doesn't update on a new email sent & received.

**Comment by Bonapara** [comment]
Could you provide an example of the format you expect for a "Last Update" field? Do you rather mean a `Last Interaction` field?

**Comment by paulyili** [comment]
> Could you provide an example of the format you expect for a "Last Update" field? Do you rather mean a `Last Interaction` field?

I was just looking at the default "Last update" field as it's already there. 
![Last Update](https://github.com/user-attachments/assets/f3d31df6-55c9-4316-a825-b6350e346d17)

**Comment by Bonapara** [comment]
Thanks for clarifying. I believe the `Last Update` field should remain as it is: a way to log user activity on the record. We should introduce another field to achieve what you want, which could be either `Last Interaction` or `Last Activity`.

**Comment by mitodrummer** [comment]
@Bonapara  Has "Last Interaction" been implemented? I am looking for a way to sort my contacts by most recent "activity" (e.g. new emails, new meetings etc...) This is a seemingly critical ability that I cannot find a solution for in the current version (1.6.7).

At the moment it's impossible for our clients to know which contacts are responsive, which are not, which imho is a pretty critical feature of a CRM.

TY
