### ISSUE TITLE
Fix property design on Show

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#701]
# Online
https://github.com/twentyhq/twenty/assets/19412894/5fb5a293-42ad-43d4-a19e-6849cf4cdfab

# Figma
https://github.com/twentyhq/twenty/assets/19412894/5d9086ab-d88f-473f-b55f-1b0a550c440a

**Comment by Bonapara** [comment]
Close from #664

**Comment by FelixMalfait** [comment]
https://github.com/twentyhq/twenty/pull/724
