### ISSUE TITLE
Center Functions Empty state

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7012]
# Current Behavior

![CleanShot 2024-09-12 at 16 03 05](https://github.com/user-attachments/assets/ac995753-16df-4b83-834f-e25c01623c2e)

The empty state is not aligned on the page center

# Desired Behavior

![image](https://github.com/user-attachments/assets/b76ffcda-9e6a-4557-8b52-724e6c7ffafc)

Center the empty state

**Comment by chistym17** [comment]
hey i would like to work on this.

**Comment by Bonapara** [comment]
Sure @chistym17, thanks for contributing!

**Comment by kant-github** [comment]
Hi @Bonapara , I looked into the issue, the issue persists because OBJECT_SETTINGS_WIDTH is hardcoded to 512 px, that is the reason why <SettingsServerlessFunctionsTableEmpty/> is centred to its parents 512 px width, not where it supposed to. I can't think of a solution, also someone else has marked it to solve..

**Comment by chistym17** [comment]
@kant-github hey if you find the solution feel free to solve it. i am having some problems with the frontend localhost..

**Comment by Bonapara** [comment]
> Hi @Bonapara , I looked into the issue, the issue persists because OBJECT_SETTINGS_WIDTH is hardcoded to 512 px, that is the reason why is centred to its parents 512 px width, not where it supposed to. I can't think of a solution, also someone else has marked it to solve..

The 512px width is expected, we should just make an exception for Settings empty states. Thanks!

**Comment by rajeshkrishnait** [comment]
Is this issue resolved, it is center aligned for me in the empty state.

**Comment by Bonapara** [comment]
![CleanShot 2024-09-18 at 09 58 16](https://github.com/user-attachments/assets/0abb13a5-02fd-4eca-82bf-044657b9fbac)

Not fixed!

**Comment by admodev** [comment]
I will take a look to see if I can fix this...

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by Utzig26** [comment]
Hey @Bonapara I've submitted a PR that fixes the issue. Please review it when you have a chance. Thank you!

**Comment by Bonapara** [comment]
Thanks @Utzig26, the team will review it shortly!
