### ISSUE TITLE
Filter options doesn't reduce after being added

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7015]
## Bug Description

- When choosing filters, it doesn't remove the already applied filters which and allows users to edit the already existing filters.
- On choosing the filters, it allows to re-edit the existing filters

## Before Behaviour

<img width="1575" alt="Screenshot 2024-09-13 at 1 05 12 PM" src="https://github.com/user-attachments/assets/6678313c-d7cc-4e17-bd9c-4a7161260925">

## Expected behaviour

- Filters should be removed and remaining filters should be shown. Just like when adding filters in record Table
<img width="1563" alt="Screenshot 2024-09-13 at 1 12 08 PM" src="https://github.com/user-attachments/assets/f4e2f99a-0ec7-40f4-b8ba-8c1d3dcc00f0">

**Comment by Bonapara** [comment]
I understand this may feel awkward, but this behavior was intentional so I removed the `bug` Label. We can remove the applied filter from the filter menu to clear things up
