### ISSUE TITLE
[bug 🐛 ]:  Filter chips lacks width for longer values

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7018]
## Bug Description

- In mobile viewport, Filter chips lacks sufficient width which causes them to break spaces on longer values

## Before Behaviour
<img width="433" alt="Screenshot 2024-09-13 at 4 52 43 PM" src="https://github.com/user-attachments/assets/f6a51daf-9d76-49bd-816e-eecc0d75f390">

## Expected behavior

Approach 1 - 

https://github.com/user-attachments/assets/ee12fe64-ed0c-4c35-8436-f56c04722f59

Approach 2- 

<img width="435" alt="Screenshot 2024-09-13 at 5 00 28 PM" src="https://github.com/user-attachments/assets/a2c03595-8b22-405e-a959-55f8e1f59158">

**Comment by harshit078** [comment]
@Bonapara, what are your views on this ? Among these approaches, is anyone good for implementing or a new approach.

**Comment by Bonapara** [comment]
Hi @harshit078! Thanks for raising the issue. In V1, we should make the filter block horizontally scrollable. (Reset & Save button should not be included in the scroll)

https://github.com/user-attachments/assets/899572e6-c2d7-4177-8bfb-fc153f6e6ce4

**Comment by rajeshkrishnait** [comment]
Can i take this up?

**Comment by harshit078** [comment]
Hi @rajeshkrishnait, I am currently working on the solution. If I can't get to a solution, then you can surely take it up .
