### ISSUE TITLE
Add necessary information about Redis cache to contributor's guide

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7031]
After introducing changes related to the metadata querying to project (which forces using Redis as cache for optimization), there are no changes reflected in documentation, potentially creating problems for those interested in self-hosting for the first time or upgrading their instance. Please add necessary information about Redis cache to contributor's guide.

**Comment by charlesBochet** [comment]
Good point

**Comment by BOHEUS** [comment]
@charlesBochet since #7369 is merged and changes are live, I think this issue should be closed, what do you think?

**Comment by charlesBochet** [comment]
yes, sir!
