### ISSUE TITLE
Unable to add my currency

### ISSUE THREAD

**Issue by bilogic** [twentyhq/twenty#7033]
Are we really limited to only the available currencies with no option to add our own?

**Comment by BOHEUS** [comment]
@bilogic the only way to add your currency is by modifying source code, you can't add in UI your own currency as it uses the hardcoded constants, if you want, you can add it by yourself (for reference #5989)

**Comment by bilogic** [comment]
Ok thanks, I'm surprised no one felt frustrated by this
