### ISSUE TITLE
Always display icons to add record, not just on hover

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7036]
## Scope & Context

- When a new user creates an account with Twenty and only operates it though mobile, then they can't get to know that sections like Account Owner, People and Opportunities have dropdowns. On large devices, there is hover so they know the actions and features.

https://github.com/user-attachments/assets/09ce7588-a960-4f7a-baa5-a04fdbee528e

- on mobile viewport

https://github.com/user-attachments/assets/36b5b5d2-298d-4195-b5df-10a2dd5d7009

- For views, on light tap edit button does show up but no clue until not tapped.
<img width="426" alt="Screenshot 2024-09-15 at 6 08 44 PM" src="https://github.com/user-attachments/assets/a116ef8c-4671-4426-a600-dd863d272f4f">

## Expected behavior

- We can introduce tooltips or information badges for first time user or we can get to a better desing approach.
- On mobile viewports, user has no idea that there exists dropdowns or actions on blank space until clicked on them
- We could use  `:focus ` which is closest to hover for mobile viewports or animations.

**Comment by FelixMalfait** [comment]
cc @Bonapara 
I think we're not big fans of tooltips/guided tour but maybe he will have ideas
