### ISSUE TITLE
(Discussion) Opening a general discussion around the paid customer experience, general communication, breaking changes 

### ISSUE THREAD

**Issue by LucasZapico** [twentyhq/twenty#7037]
## Story 

I'm currently paying for the hosted Twenty services and I woke up today to find my contact forms were not working.  After some debugging I discovered the shape of the `email` object was changed via this PR [Handle migration of Email to Emails fields #6885](https://github.com/twentyhq/twenty/pull/6885). 

I wanted to callout this issue as Twenty is being sold as production ready on the open market for team that may not be technical. I believe some versioning processes and CX update process guidelines is in order to ensure a customer doesn't suddenly have broken operations when the core API changes on a PR. 

## Solutions Suggestions 

1. Update the README and marketing copy on the site and convey that this product is in BETA and breaking changes may occur at any time and it is not recommended for nontechnical teams who are not following PRs. 
2. Have a release schedule for the paid version so customers are informed of breaking changes via email if they are not watching PRs. 

These two suggestions are not mutually and it may be best if both are implemented. Definitely not a good experience for a paying customer if the expectations are not set early. In my opinion, Twenty's marketing material makes is sound more production-ready then it is.

**Comment by BOHEUS** [comment]
@LucasZapico you could open a discussion in https://github.com/twentyhq/twenty/discussions instead of opening an issue with `(Discussion)` in title, people are checking there too

**Comment by FelixMalfait** [comment]
This is very fair criticism @LucasZapico - you are right. We'll discuss it internally and come back to you.

**Comment by LucasZapico** [comment]
@BOHEUS pardon that's my oversight. I will search and move it over if there isn't an open discussion.

**Comment by LucasZapico** [comment]
@FelixMalfait Thank you for taking the time to acknowledge my callout.

**Comment by LucasZapico** [comment]
I'm going to close this and move it to discussions.
