### ISSUE TITLE
New objects cannot be created if list is empty

### ISSUE THREAD

**Issue by shodgson** [twentyhq/twenty#7043]
## Bug Description

If all objects (e.g. People) are deleted, new users can not be added via the UI. Clicking 'Add a Person' does nothing - no UI feedback, no console messages, no network requests.
![image](https://github.com/user-attachments/assets/2c59f714-55ee-4bcb-a133-f789c726e01c)

Users can still be added via the Import function or the GraphQL API.

## Expected behavior

Clicking 'Add a Person' should open the usual input boxes
![image](https://github.com/user-attachments/assets/286ecc8d-14bc-4710-ae79-c917d46e4ef7)

## Technical inputs

Tested with Twenty v0.21.1 on Firefox v129.0

**Comment by ehconitin** [comment]
Weird, I think its fixed!
Cant reproduce in v0.24.2

**Comment by shodgson** [comment]
Ah yes, confirmed it's working with the docker twenty:main image. Thank you
