### ISSUE TITLE
Email won't load in the timeline

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7059]
# Bug description

My email doesn't get loaded in the timeline

![CleanShot 2024-09-16 at 16 04 11@2x](https://github.com/user-attachments/assets/60b6212c-e25a-4f1b-b671-856454503c6b)

The email content is just "Test"

![CleanShot 2024-09-16 at 16 06 28@2x](https://github.com/user-attachments/assets/b3f7612f-1179-4f82-9fb2-4741d0cd65b0)

**Comment by Bonapara** [comment]
@bosiraphael WDYT?

**Comment by bosiraphael** [comment]
I'll take a look
