### ISSUE TITLE
Update visible standard fields on Table views

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#706]
Add 
- Linkedin on Company and People
- JobTitle on People

On Company, leave address column at the end

**Comment by FelixMalfait** [comment]
I think we'll also need a design input here? We probably want to display something else than just the url 
cc @Bonapara

**Comment by Bonapara** [comment]
Here is the updated design @emilienchvt :

https://github.com/twentyhq/twenty/assets/19412894/ec5153d0-5303-4beb-990d-07ef77e2efd3

Component: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=6347-206998&mode=design&t=n1A9Pn6gxWZMeADE-4
