### ISSUE TITLE
Empty notes & tasks should not be auto-saved

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7068]
# Current behavior

Empty notes and tasks (Empty title and body) are persisted.

![CleanShot 2024-09-16 at 18 21 34@2x](https://github.com/user-attachments/assets/136c0762-2a0c-4ecf-b312-9531fcc207ad)

# Desired Behavior

We should not persist Notes & Tasks that don't have a title or body like we used to do.

**Comment by harshit078** [comment]
#6736 This issue should be a part of the already existing work done for whitespaces !

**Comment by FelixMalfait** [comment]
See https://github.com/twentyhq/twenty/issues/6801#issuecomment-2325095525 - I'm not sure if we should keep this open. We should have a clear product + tech strategy and it isn't the case yet (linked to 'draft' backend status and potentially all data validation problem)
