### ISSUE TITLE
Delete a note/task from side panel

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7069]
# Current Behavior

You can't delete a note/task without navigating to it or accessing the `Notes` object list.

https://github.com/user-attachments/assets/c1c825cc-c3e5-4b48-9b3e-6006d0c1f514

# Desired Behavior

Add an action button that allows deletion of the note/task directly from the side panel.

![7030b76bd9750096c880648d49d6fb75b2e886ff37f1c3014753b6713f8c2056](https://github.com/user-attachments/assets/826eece4-6e5e-438b-b97b-165d2d5de466)

![image](https://github.com/user-attachments/assets/a1d8954d-91b2-4f01-a5f9-6ad5de405f69)

**Comment by harshit078** [comment]
@Bonapara, what if we allow the user to delete the notes directly from the card itself for ease of functionality ? 

<img width="394" alt="Screenshot 2024-09-17 at 12 56 42 AM" src="https://github.com/user-attachments/assets/49573be9-49a4-468e-85d6-bc1dd8a98c67">

And for tasks we can add the delete in the side panel as mentioned

**Comment by FelixMalfait** [comment]
@Bonapara we need to think of this in the context of all objects not just notes/tasks because it's the same panel. For example in your desired behavior, could you please provide additional guidance that would apply to every object? Should we remove the object type in the header for all objects?

**Comment by Bonapara** [comment]
We synced with Félix. For V1 this should be hardcoded on every record side panel which means:

- When I create or edit a task from a record page
- When I create or edit a note from a record page
- When I create a record from a side panel:

https://github.com/user-attachments/assets/68d59fe3-7db7-4414-8f3c-78de2a9221e3

In V2, we will display all the actions a user can take on a record.

**Comment by ehconitin** [comment]
@Bonapara can I work on this If no one is assigned yet?

**Comment by Bonapara** [comment]
Sure Nitin! Thanks

**Comment by ehconitin** [comment]
@Bonapara 
How about a confirmation modal on delete?

**Comment by FelixMalfait** [comment]
@ehconitin the goal here is for this side panel to be a small version of the record show page with as little duplicated code as possible but shared code instead, so we wouldn't want to introduce new behavior. Introducing a confirmation modal on the show page had been discussed in #6559 but was not prioritized by @Bonapara so far I think (we instead bet on soft delete / be able to recover records easily). Maybe @Bonapara would decide to reopen a similar issue but I think it's better to invest time here in doing things as cleanly as we can. In an ideal world, the list of actions displayed would come from a single source of truth



Restore button on show page mobile view / in sidebar:
![Command bar](https://github.com/user-attachments/assets/0a227438-193e-4f15-baf5-6b02d2e39fdb)


Actions:
<img width="371" alt="Screenshot 2024-09-23 at 21 25 54" src="https://github.com/user-attachments/assets/31248719-a3e9-40fe-b26a-3e254c493c67">

The actions that will be displayed are the same that you have with "..." on the showpage. We will just have special attributes to indicate which one is "pinned" and which one is the "cta". For the mobile/sidebar view we only display one action, the CTA in blue if there's a CTA, then the first pinned action if there isn't any (in grey like the delete button in the screenshot).

Not sure if it's clear, @Bonapara might explain it best 😅

**Comment by ehconitin** [comment]
Oh, thanks for the insights, @FelixMalfait!
It makes sense not to introduce new behavior by adding a confirmation modal for deletions and to have an option to restore them easily. So instead of closing the right drawer on the deletion of the record, a restore banner should appear at the top right? I’ll make the changes in #7200. (@Bonapara, tagging you for confirmation.) 
The actions part is still a bit unclear to me, but I’ll discuss it with Thomas to clarify things.

**Comment by Bonapara** [comment]
> Oh, thanks for the insights, @FelixMalfait! It makes sense not to introduce new behavior by adding a confirmation modal for deletions and to have an option to restore them easily. So instead of closing the right drawer on the deletion of the record, a restore banner should appear at the top right? I’ll make the changes in #7200. 

💯

> (@Bonapara, tagging you for confirmation.) The actions part is still a bit unclear to me, but I’ll discuss it with Thomas to clarify things.

Anytime!

**Comment by FelixMalfait** [comment]
@ehconitin The restore banner should already be there, it's just the show page that's embedded into the panel already.

**Comment by ehconitin** [comment]
@FelixMalfait Yup you are correct, but the banner does not appear till `RecodShowContainer` is re-rendered somehow. In the recording I am setting a new title for deleted record to forcefully re-render, which then gets `recordFromStore` and `recordFromStore.deletedAt` which is responsible for the banner. How would this work in our case? 
#7146 is related to this behaviour i guess.

https://github.com/user-attachments/assets/1fff0e5e-9e66-4dc9-bc50-fe21f809f5c0
