### ISSUE TITLE
On Notes and Tasks, I can attach files

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#707]
Backend endpoint has been completed: https://github.com/twentyhq/twenty/issues/669

And Blocknote is working on adding this capability to their editor.
Once they've completed the work, we should update the dependency and plug our backend endpoint

**Comment by dev-DTECH** [comment]
I want to work on this feature can you assign this issue to me.

**Comment by FelixMalfait** [comment]
Hey @dev-DTECH thanks a lot! We are still blocked on a dependency for this one (we don't own the lib that does the text editor and they don't allow drag'n'droping attachments yet. But they did integrate "add image" recently which we incorporated)
