### ISSUE TITLE
Gap Between Note Title Input and Placeholder

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7070]
# Bug Description

There is a gap between the note title input and the note/task title placeholder.

![CleanShot 2024-09-16 at 18 32 16@2x](https://github.com/user-attachments/assets/7b447195-cbc0-4f0c-b708-9c3808f05975)

# Desired Behavior

The note/task title input should appear above the note/task title placeholder, not beside it.

**Comment by yuvaraj8019** [comment]
I like to work on this issue

**Comment by Bonapara** [comment]
Sure @yuvaraj8019, thanks for contributing!

**Comment by samimshoaib01** [comment]
I am interested in this. can i work on this issue >?

**Comment by Bonapara** [comment]
Sorry @samimshoaib01 and @thejasviES, @yuvaraj8019 is already on it. Maybe can you grab another [Good First Issue](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)? Thanks

**Comment by charlesBochet** [comment]
Issue seems to be already fixed
