### ISSUE TITLE
Error Creating Object After Deleting One with the Same Name

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7073]
# Bug description

Error while creating an object with the name of one that was previously permanently deleted

https://github.com/user-attachments/assets/66f72329-3b17-4f05-93b5-b52e99035597

# How to reproduce

1. Create an object
2. Disable it then Delete it
3. Create another object with the same name
4. The new object is not getting saved

**Comment by shyamsundertard** [comment]
@Bonapara in current version of this repo this bug is not there. A new object can easily be created with same name of an object which was present earlier but deleted.

https://github.com/user-attachments/assets/53ce6fe0-a30f-4a4c-961f-53ab58709248

**Comment by Bonapara** [comment]
The issue occurred due to performance problems. Thank you for investigating!
