### ISSUE TITLE
Relation Field Label Empty Until Object Relation Switch

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7082]
# Bug description

When creating a relation field on an object, the "field on _other object name_" label is empty. An object relation switch makes it appear.

<img width="564" alt="image" src="https://github.com/user-attachments/assets/76933d0f-dbe8-4f9d-a28d-579c602bb11d">

# How to reproduce

Go to Objects Settings - create a relation field

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by yadavshubham01** [comment]
\assign

**Comment by yadavshubham01** [comment]
@Bonapara can you please provide more context about this issue

**Comment by yadavshubham01** [comment]
hey @Bonapara please review this PR #7727

**Comment by Bonapara** [comment]
Thanks @yadavshubham01! the tech team will review it shortly

**Comment by Bonapara** [comment]
Ohh didn't noticed, indeed looks fixed already! Thanks for reporting @ehconitin and sorry @yadavshubham01 :(
