### ISSUE TITLE
Header overflows in Data model for mobile viewport

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7085]
## Bug Description

- Go to Settings/Data Model
- Add field and use it on mobile viewports
- Since header has Type and configure properties, it makes the buttons component overflow

## Current Behaviour

<img width="433" alt="Screenshot 2024-09-17 at 11 55 28 AM" src="https://github.com/user-attachments/assets/7faebd70-4c8e-45ab-8927-9ca4cb3a1254">
<img width="437" alt="Screenshot 2024-09-17 at 12 09 22 PM" src="https://github.com/user-attachments/assets/183c8789-155d-41d7-8c2c-e509fbe7e164">

## Expected behavior

<img width="418" alt="Screenshot 2024-09-17 at 11 56 43 AM" src="https://github.com/user-attachments/assets/6dda4093-bba8-4b0b-87af-f6b7ce59a3e9">

## Approach

- New field has a lot of unused spacing and padding. Removing that spacing could yield more header room
- Instead of New field and then type, we can directly give type dropdown and remove New fiedl altogether which would give a clean look.
<img width="431" alt="Screenshot 2024-09-17 at 12 08 41 PM" src="https://github.com/user-attachments/assets/1c262b58-6e2c-489c-98b6-dcaf5e299c8d">

**Comment by Bonapara** [comment]
I think we should introduce a mobile version of the breadcrumb - Will provide a design

**Comment by Bonapara** [comment]
https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=40192-452783&node-type=frame&t=IXWRE0LasgigcLyR-11

![image](https://github.com/user-attachments/assets/e59b4e70-73e8-42cc-b1d9-cd1fc6f2b23b)

We should display a `back` button with back to `previous step name` as label

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by NitinPSingh** [comment]
hi @Bonapara ,
i am working on the issue , want to know what would be the back button for workspace as it redirect to /general 
![Screenshot 2024-10-02 142800](https://github.com/user-attachments/assets/25b3090e-b0a7-4762-8d44-8fd576aa06b3)

![Screenshot 2024-10-02 142533-2](https://github.com/user-attachments/assets/e74cb387-c2ef-45a1-a44b-dccd53a6af22)

**Comment by Bonapara** [comment]
`< Back to App` that would close the settings would be cool @NitinPSingh. WDYT?

**Comment by NitinPSingh** [comment]
hi can anyone review the pr

**Comment by Bonapara** [comment]
The tech team is on it @NitinPSingh ;)
