### ISSUE TITLE
I can see the number of companies/people on list views

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#709]
This ticket probably isn't as easy/quick as it seems since we should implement this on the backend to have something more robust

**Comment by Bonapara** [comment]
This should be linked to the views
<img width="240" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/0f015579-6281-4f97-aa93-d1d78b5ec304">

**Comment by Bonapara** [comment]
Closing this issue as it seems in prod @charlesBochet
