### ISSUE TITLE
I can see the number of opportunities on each stage

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#710]
@Bonapara could you please provide a design for this? Thanks a lot

**Comment by Bonapara** [comment]
<img width="221" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/f06963b5-6df6-435c-a805-48a5b6f7cbc9">

**Comment by Bonapara** [comment]
Figma:

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5910-77816&mode=design&t=GMBHxG3P5dZsG4iz-4

**Comment by proof3** [comment]
Hi @Bonapara @FelixMalfait , I would like to work on this issue.

**Comment by FelixMalfait** [comment]
Of course! Thanks a lot @proof3

**Comment by proof3** [comment]
No problem!
