### ISSUE TITLE
Remove 8px Left Padding in Settings Page Tabs

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7100]
# Current behavior

There is an unexpected 8px left padding when there are multiple emails/calendar accounts connected to Twenty

![CleanShot 2024-09-17 at 17 32 45](https://github.com/user-attachments/assets/f7248859-1bb5-49d3-99f4-f9f18c50a723)

# Desired Behavior

The gap is **necessary** for the record detail page. **Keep it as today**

![CleanShot 2024-09-17 at 17 35 20](https://github.com/user-attachments/assets/0f9783ca-4694-459f-b96e-729e3e65545c)

But it should be removed for the Settings page Tabs:

![CleanShot 2024-09-17 at 17 36 48](https://github.com/user-attachments/assets/136c3693-b46e-4d1e-96b9-46a4bea0e9a7)

# Figma

App -> https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=32530-139410&node-type=frame&t=vjg6Ofev4bkaijG1-11

Settings -> https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34851-511709&node-type=frame&t=vjg6Ofev4bkaijG1-11

**Comment by gabbijonsson** [comment]
I would like to work on this issue if possible 😊

**Comment by Bonapara** [comment]
Sure @gabbijonsson, thanks for contributing!

**Comment by Dhiraj5789** [comment]
@Bonapara Hi, I can fix this. Please assign it to me

**Comment by Bonapara** [comment]
Sure @Dhiraj5789, thanks for contributing!

**Comment by Dhiraj5789** [comment]
Hi @Bonapara, getting this error while logging in with tim@apple.dev. 

Error: relation 'core.user' doesn't exist.

**Comment by Dhiraj5789** [comment]
query failed: SELECT "User"."id" AS "User_id", "User"."firstName" AS "User_firstName", "User"."lastName" AS "User_lastName", "User"."email" AS "User_email", "User"."defaultAvatarUrl" AS "User_defaultAvatarUrl", "User"."emailVerified" AS "User_emailVerified", "User"."disabled" AS "User_disabled", "User"."passwordHash" AS "User_passwordHash", "User"."canImpersonate" AS "User_canImpersonate", "User"."createdAt" AS "User_createdAt", "User"."updatedAt" AS "User_updatedAt", "User"."deletedAt" AS "User_deletedAt", "User"."defaultWorkspaceId" AS "User_defaultWorkspaceId" FROM "core"."user" "User" WHERE (("User"."email" = $1)) LIMIT 1 -- PARAMETERS: ["tim@apple.dev"]
error: error: relation "core.user" does not exist
[Nest] 82621  - 09/21/2024, 9:47:32 AM   ERROR [ExceptionsHandler] relation "core.user" does not exist

**Comment by Dhiraj5789** [comment]
Sure

**Comment by shyamsundertard** [comment]
@Bonapara I would like to fix it, please assign it to me.
