### ISSUE TITLE
The settings flash during loading

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7102]
# Current behavior

The Settings page flashes on load.

https://github.com/user-attachments/assets/6cdbe08c-79ff-44f5-b211-c5297298154c

# Desired Behavior

The White background layout should always be loaded and not flash on every page change. We should put a small Skeleton to indicate the page loading. The breadcrumb should not be part of the loading and already displayed (if possible).

![image](https://github.com/user-attachments/assets/01c7feee-ace6-4de8-8399-42d616f4c83b)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=40069-430620&node-type=frame&t=vjg6Ofev4bkaijG1-11

# Techical guidelines

@lucasbordeau

**Comment by Muralidhar22** [comment]
Hi @Bonapara  Can I work on this?

**Comment by Muralidhar22** [comment]
<img width="1792" alt="Screenshot 2024-09-24 at 12 04 36 AM" src="https://github.com/user-attachments/assets/4d13af98-197d-454f-848f-515edeb0fd88">
Hi @Bonapara / @lucasbordeau would this work, I added suspense fallback element.

**Comment by Bonapara** [comment]
I believe @charlesBochet mentioned it was an issue with caching the layout. This needs to be confirmed by him or @lucasbordeau.
