### ISSUE TITLE
We should be allowed to override the defaultValue on standard fields

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#7104]
### Discussed in https://github.com/twentyhq/twenty/discussions/6933

<div type='discussions-op-text'>

<sup>Originally posted by **domenico-ruggiano** September  8, 2024</sup>
Possibility to set a default currency other than USD dollars, for example € EUR.</div>

I think we should let the user override the default value for standard fields
(we already let the edit values for enums) 

![CleanShot 2024-09-18 at 16 23 26](https://github.com/user-attachments/assets/26335434-1c9d-46e2-a43c-c2f9608259fc)

**Comment by Bonapara** [comment]
Maybe we can start with the `True/False` and `Currency` fields:

![image](https://github.com/user-attachments/assets/f4e2e5e9-7e61-44f0-be37-ecd96afd098c)

![image](https://github.com/user-attachments/assets/5a258b71-200a-4e73-945a-937061cfaa28)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34845-127895&node-type=frame&t=IXWRE0LasgigcLyR-11

**Comment by FelixMalfait** [comment]
@Bonapara the design has already been implemented for both. The issue is just that we are blocking the edition for standard fields (but it's possible to edit it on custom fields)

**Comment by FelixMalfait** [comment]
Also valid for the options (stored in "settings"):
<img width="555" alt="Screenshot 2024-09-25 at 11 02 23" src="https://github.com/user-attachments/assets/aef212ac-7bdb-4cad-965d-b102b4050d2f">

Merging #6945 as it is but would be great to fix it in the context of this current issue - we'd like those options to be modifiable

**Comment by FelixMalfait** [comment]
@ad-elias will be working on this

Todo: check with `px nx run twenty-server:command workspace:sync-metadata -f` that it doesn't get overwritten

**Comment by ehconitin** [comment]
Thanks for taking this one @ad-elias!
