### ISSUE TITLE
Fixed column header on Kanban boards

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7105]
# Current Behavior

Currently, Kanban column headers are not fixed. When the page is scrolled, they disappear.

https://github.com/user-attachments/assets/c6649976-62f2-4b20-b4d3-9684c091776c

# Desired Behavior

Change the column header position to fixed so they stay on top while scrolling the page

![image](https://github.com/user-attachments/assets/6e6b984e-59ff-49a9-8e62-b7cdd6add69c)

Video to explain the expected behavior:

https://github.com/user-attachments/assets/1825fe2c-392d-4ef2-a53c-998bfe1d4096

# Figma

Introduce a 40px heigh column header container ![CleanShot 2024-09-17 at 18 20 50](https://github.com/user-attachments/assets/8ad8687b-9612-42f9-b789-0a8f9c8a5e1c)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=24955-194300&node-type=frame&t=vjg6Ofev4bkaijG1-11

**Comment by dilshad-knk** [comment]
can i work on this ?

**Comment by Bonapara** [comment]
Sure @dilshad-knk, thanks for contributing!

**Comment by ehconitin** [comment]
@Bonapara 
No response on the PR, should I fix this?

**Comment by Bonapara** [comment]
Would be great, thanks @ehconitin!
