### ISSUE TITLE
I can add a card to the top of the list from opportunities

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#711]
Right now the only way to add a card is to go to the bottom of the list in each stage which can be cumbersome if you have a lot of opportunities in the same stage.
Instead we would like to have a way to add a card directly on the top

**Comment by Bonapara** [comment]
We should add two behaviors:

1) Clicking on the top right "+" should create a new card and horizontally scroll to the card place.
https://github.com/twentyhq/twenty/assets/19412894/bb914888-025f-4826-86b5-731af6e225ea

2) Creating a card from a column. It should also scroll to where the card has been created
https://github.com/twentyhq/twenty/assets/19412894/14a67669-bee5-42df-9d91-9326b645d5c7

**Comment by FelixMalfait** [comment]
Thanks @Bonapara! Why not add the card to the top directly when it's added through the button? It's how Trello or Asana do it. Scrolling to the bottom feels off imo. It's not a pattern you usually see, and if you have several cards to add you would still have to scroll down the up then down. Maybe I didn't get your point

**Comment by FelixMalfait** [comment]
> By default the newly created card should be place on top if you use the column header or "+" to add a card, and at bottom if you use the "new" button at the bottom of a column

Ok thanks, I thought you meant always keeping it at the bottom when you said "scroll to the card place". Makes sense now.
