### ISSUE TITLE
Update theme card width

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7119]
# Current behavior

Now that the container is 512px wide, there is a white gap on the right side of the Theme cards.

![CleanShot 2024-09-18 at 15 39 21](https://github.com/user-attachments/assets/ebc7fa0a-6bd4-48b1-bb2b-8969ed3622e5)

# Desired Behavior

Make the card fill the space. (The new card width should be 160px)

![image](https://github.com/user-attachments/assets/441f0ab6-f40b-45ba-81de-401c6be202a1)

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34845-125367&node-type=frame&t=IXWRE0LasgigcLyR-11

**Comment by harshit078** [comment]
@Bonapara Already working on it !

**Comment by Bonapara** [comment]
Thanks @harshit078 !
