### ISSUE TITLE
Fix Incorrect Step Display When Creating New Field

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7121]
# Current behavior

When creating a new field, we display `Step-2` on the page to select the field type.

![image](https://github.com/user-attachments/assets/48fdeea7-0af2-4bf4-8d2a-594e3296f985)

# Desired Behavior

We should remove `step-2` and only keep `new-field`

**Comment by harshit078** [comment]
@Bonapara, working on it !

**Comment by Bonapara** [comment]
Thanks @harshit078!
