### ISSUE TITLE
Update the email thread action bar

### ISSUE THREAD

**Issue by gvkhna** [twentyhq/twenty#7134]
Feature request of a setting to open email links in gmail compose directly. I have no use of mailto: URLs because they open Mail.app on Mac. Would be great to have a setting for this.

Here's how to open an email directly in gmail:

`https://mail.google.com/mail/?fs=1&to=someone@example.com&tf=cm&authuser=myemail@gmail.com`

_Originally posted by @gvkhna in https://github.com/twentyhq/twenty/issues/4217#issuecomment-2342340797_

# Desired behavior

1. Transform the `Reply` button in a `See in Gmail` button
2. Add a Reply button with the command above
3. Use the same action bar that we will use for #7069. (Today the email thread action bar is too big and lacks a top border)

**Today**

![CleanShot 2024-09-19 at 09 35 48](https://github.com/user-attachments/assets/16029bd5-57db-4b9c-a29f-dda03d8c56fb)

**Desired**

![image](https://github.com/user-attachments/assets/17ce59c2-34ce-4006-84b9-74f3b1a447c1)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=40252-73703&node-type=frame&t=gdg73IZVBD9uB3D3-11

**Comment by Bonapara** [comment]
Sure @Mihan786Chistie, thanks for contributing!

**Comment by gvkhna** [comment]
@Bonapara Sorry I wasn't clear. That wasn't my feature request although great. 

![Screenshot 2024-09-19 at 06 49 21 Large](https://github.com/user-attachments/assets/9359127e-ff6b-409c-a061-dad6aa746e66)

##Feature Request

This link with the arrow is currently a mailto: URL. Which opens Mail.app, not desired behavior. Setting for this link to open Gmail.

I wanted a setting in the General Settings for the following

(Select Option)
Default Email App:
- System
- Gmail (web)

Similar to how iOS does it.

**Comment by Bonapara** [comment]
> This link with the arrow is currently a mailto: URL. Which opens Mail.app, not desired behavior. Setting for this link to open Gmail.

You can set up this behavior in Chrome without needing Twenty. 

https://github.com/user-attachments/assets/6b870730-ba80-49cf-8b98-876941132e5b

**Comment by gvkhna** [comment]
I know but it typically gets messed up with the default account etc. Because twenty has knowledge of the account i want to use, would be great to get that integrated I figured. Chrome has no clue, defaults to 0, usually the wrong one in my case.

**Comment by Bonapara** [comment]
I see! This is a great idea, but I think we should wait to implement the email sending in Twenty rather than adopting a temporary solution that's not trivial. Closing it for now, but keeping it in mind!

**Comment by gvkhna** [comment]
Shoot I don’t want email sending in twenty, way too much to emulate unless it can be done correctly, especially for multiple sending domains, signatures and formatting. Although that would be awesome if done correctly. 

I looked for a way to get the email compose pop up separated through iframe etc, doesn’t seem possible unfortunately. 

Please reconsider this simple feature would probably solve a ton of issues.

**Comment by Bonapara** [comment]
We will soon introduce workflows to help you hack something!

**Comment by mitodrummer** [comment]
Any progress on this front? I'm evaluating whether twenty is a good fit as a CRM to compliment our webapp. The fact that mailto is the default for all email links in the app is a bit disappointing. Love the idea of an option to have it open a gmail compose modal (though i guess it's limited in that if a user has multiple gmail accounts, we can't dictate which is used in the from address).

We could fork and temporarily update all mailto links ourselves, but wanted to see if anyone has a workaround that doesn't rely on on setting browser options or external mail client / system OS options.

Looking forward to the ability to reply to emails within the CRM itself. Sounds like it's slated for Q4 2025? TY

**Comment by gvkhna** [comment]
@mitodrummer See my OC. You can target an email even if the user is logged into multiple accounts. This is a super simple feature for integrating directly into google, because mailto links by themselves do open gmail, but don't let you choose the user. This seems like a no-brainer to integrate, I looked into integrating it myself but haven't had a chance.

**Comment by mitodrummer** [comment]
> [@mitodrummer](https://github.com/mitodrummer) See my OC. You can target an email even if the user is logged into multiple accounts. This is a super simple feature for integrating directly into google, because mailto links by themselves do open gmail, but don't let you choose the user. This seems like a no-brainer to integrate, I looked into integrating it myself but haven't had a chance.

will take a stab at it once i shake out the rest of the system to see if leadership will go for this avenue.

The other thing they would be looking for is an easy button to schedule a meeting with a specific contact. Not sure if that is achievable with workflows, or with a mechanism similar to sending a gmail.

**Comment by mitodrummer** [comment]
> > [@mitodrummer](https://github.com/mitodrummer) See my OC. You can target an email even if the user is logged into multiple accounts. This is a super simple feature for integrating directly into google, because mailto links by themselves do open gmail, but don't let you choose the user. This seems like a no-brainer to integrate, I looked into integrating it myself but haven't had a chance.
> 
> will take a stab at it once i shake out the rest of the system to see if leadership will go for this avenue.
> 
> The other thing they would be looking for is an easy button to schedule a meeting with a specific contact. Not sure if that is achievable with workflows, or with a mechanism similar to sending a gmail.

after a quick search it looks like the same is possible with gcal. it even supports the authuser query param as well :)
