### ISSUE TITLE
Update System Data Type Names to Display 'System'

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7136]
# Current Behavior

We currently display a lock icon for system data types, but each type has a different name. This is confusing because users cannot utilize these field types.

![CleanShot 2024-09-19 at 09 40 45](https://github.com/user-attachments/assets/d33baf74-277a-4b15-b3de-4da2fb4c4619)

# Desired Behavior

Instead of names like `actor` or `rich text`, we want to display `System` as their data type.

**Comment by subhamengine** [comment]
Can you assign this to me?

**Comment by Bonapara** [comment]
Sure @subhamengine, thanks for contributing!

**Comment by subhamengine** [comment]
Cool, please assign it to me.

**Comment by subhamengine** [comment]
Hey @Bonapara , it's done. On which branch should i raise a PR?

**Comment by subhamengine** [comment]
Hey @Bonapara , I have fixed the issue and have raised a PR as well. [#7170](https://github.com/twentyhq/twenty/pull/7170)
