### ISSUE TITLE
Contextual menu in ⌘K on record pages

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7138]
# Current Behavior

Currently, the `3 dots icon button` opens a menu on the record page.

![CleanShot 2024-09-19 at 10 37 49](https://github.com/user-attachments/assets/0479785c-8b28-4680-967c-f4730363379c)

# Desired Behavior

We want it to open a ⌘K with the record contextual actions displayed. Pressing ⌫ should remove the `Qonto` chip and return the user to the root ⌘K.

Add the following actions to the contextual menu:

![image](https://github.com/user-attachments/assets/9a216ccd-f6a4-438f-864c-01ded86f5c20)

Long term Vision with more actions:

![CleanShot 2024-09-19 at 10 46 29](https://github.com/user-attachments/assets/67457b33-4535-46f5-a99b-0c6e792300e7)

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=40263-80372&node-type=frame&t=GPMRKGqFNWATUOMD-11

**Comment by FelixMalfait** [comment]
@bosiraphael completed this I believe. Closing
