### ISSUE TITLE
Feature request: Calculated fields / formulas 

### ISSUE THREAD

**Issue by thinkbig1979** [twentyhq/twenty#7139]
It would be great to have the ability to create a field type that allows for calculated values.
E.g. In Opportunities,you may have an expected gross value, let's say $1000, but you may also have an expected margin value, let's say 10%. It would be great to have a calculated field called "Expected profit" that uses the previous two fields to calculate that the expected profit on this sale is $100.

Another prime example:
Being able to separately enter First Name and Surname, and then having a field that concatenates those to a Full Name value.

You could 'outsource' this to another app using a webhook, but having fields update themselves in real time in the CRM is just so much nicer, and would add a lot of value. 

teable.io has a nice implementation of this.

**Comment by Bonapara** [comment]
Hi @thinkbig1979! Great idea, we have this on our radar and can't wait to implement something. Closing this as a discussion already exists on the topic: https://github.com/twentyhq/twenty/discussions/4117. I'll mention your issue in the thread. Thanks for using Twenty!
