### ISSUE TITLE
Email invite design improvements

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7140]
# Current behavior

The invitation email sent using the "invite by email" feature doesn't display correctly.

![CleanShot 2024-09-19 at 11 08 46](https://github.com/user-attachments/assets/0bb70ba2-2472-4d70-89e0-6768e060c0dd)

# Desired Behavior

The layout should look like this:

![image](https://github.com/user-attachments/assets/42063574-e09e-463a-894c-872a74038139)

The email sender name should look like this: https://github.com/twentyhq/twenty/issues/6958

**Comment by janvi01** [comment]
Hi @Bonapara I would like to work on this.

**Comment by Bonapara** [comment]
Sure @janvi01, thanks for contributing!

**Comment by Bonapara** [comment]
Related to #7001

**Comment by FelixMalfait** [comment]
@Bonapara If you don't mind maybe editing your Figma for future reference because the bottom text was changed in the PR (while the correct company name/address are in the initial screenshot). Thanks!

**Comment by FelixMalfait** [comment]
I think the text isn't much better also ("user friendly open source CRM"). Imo it should explain the software in simple words for non-technical users that get invited. So it could be "It's a CRM, a software to help business manage their customer data and relationships efficiently" (I guess it's nice to add CRM which was missing and many people do understand)

**Comment by Accheng21** [comment]
Hi @FelixMalfait ,  I am currently working in a group of 5 students from CMU taking an introductory software engineering course and our final project is to contribute to an open-source repo. Our project has multiple checkpoints and will be due on December 8 (meaning our PR will take longer to open). Would it be possible for us to be assigned to this issue (or any issues that you think would be a good fit)? Thanks!
