### ISSUE TITLE
Compact sidebar

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7143]
# Current behavior

Today, you can hide the sidebar. When the sidebar is hidden, all commands are also hidden. To navigate, you need to either open ⌘K or reopen the navbar.

![CleanShot 2024-09-19 at 11 31 44](https://github.com/user-attachments/assets/b7eb1f55-12d1-48c5-99bb-e76cc29797e1)

# Desired Behavior

Instead of hiding the full sidebar, we want to transform it into a "Compact sidebar" that displays only the navigation item icons. Please pay attention to UX details while implementing this 🙏

![image](https://github.com/user-attachments/assets/50c9ee63-b4e8-4101-a6f1-d1736fc430bc)

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=5910-77814&node-type=frame&t=GPMRKGqFNWATUOMD-11

**Comment by harshit078** [comment]
@Bonapara Would the use of [React pro Sidebar library](https://www.npmjs.com/package/react-pro-sidebar) be an efficient approach ?

**Comment by Bonapara** [comment]
@harshit078 I think it's better to do it manually, but let's see what @lucasbordeau thinks!

**Comment by ehconitin** [comment]
@Bonapara Could you assign me please? :)

**Comment by Bonapara** [comment]
Thanks @ehconitin !
