### ISSUE TITLE
Implement Optimistic Rendering on Soft-Delete 

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7146]
# Description

Soft-deleted items don't appear with the deleted items until you refresh. We should implement Optimistic rendering to improve this behavior.

https://github.com/user-attachments/assets/adaf1818-096c-48b7-895b-42b19ec6d75d

**Comment by sid0-0** [comment]
Hey I was looking into this issue. Can someone help out with how to update Apollo cache for queries with a different set of filters (filters for deleted records only)? Do I just invalidate them? The solution could be to hard code the filters in a query and update its cache but that seems unreliable.
