### ISSUE TITLE
Emails doesn't follow regex pattern in table

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7149]
> [!Caution]
> User can add any email without any pattern.
> On adding emails in **Companies** or **People**, the email doesn't follow any regex pattern and accepts any email.

## Current behavior

<img width="206" alt="Screenshot 2024-09-19 at 6 24 07 PM" src="https://github.com/user-attachments/assets/e2b6e035-07eb-4224-a713-d1a93cae2f8e">
<img width="196" alt="Screenshot 2024-09-19 at 6 26 49 PM" src="https://github.com/user-attachments/assets/0bab32e2-74c4-42cd-97c6-8d535d78a46f">

## Expected behaviour

<img width="444" alt="Screenshot 2024-09-19 at 6 25 32 PM" src="https://github.com/user-attachments/assets/1a79e99f-f00e-4bbe-bd0d-63406633a7b1">

**Comment by Weiko** [comment]
FYI @Bonapara

**Comment by Bonapara** [comment]
Put some instructions as comment in the PR https://github.com/twentyhq/twenty/pull/7245#issuecomment-2376130120
