### ISSUE TITLE
Tab design improvements

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7150]
# Current behavior

To open a tab: Open a note or task on a record, then press the minimize button:

![CleanShot 2024-09-19 at 15 24 19](https://github.com/user-attachments/assets/c9764207-c93c-49d4-91cc-d2b182f8a390)

This reduce the side panel in a tab that look like this

![CleanShot 2024-09-19 at 15 19 00](https://github.com/user-attachments/assets/bd3883c2-0f6e-44c9-bbe1-e492007fcd4e)

# Desired Behavior

Improve the tab design:
- Background should be transparent/secondary
- The tab should have a blur (like the one we use on menus)
- The tab should have a top left border-radius
- The tab should have some border
- Check the different spacings

![image](https://github.com/user-attachments/assets/151b4cc4-b3e9-4680-9ae5-01a761f3b804)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=40315-524430&node-type=frame&t=VEnadEyAJpb29rmb-11

**Comment by ehconitin** [comment]
@Bonapara if opened different record in side panel after minimizing the before viewed record , should the side panel be minimized or we want to reset it everytime?

**Comment by Bonapara** [comment]
Hi @ehconitin, for now, we should keep the current behavior and restore the panel each time. Thanks!

**Comment by ArafatOSDev** [comment]
Hello @Bonapara Can i work on this task?

**Comment by Bonapara** [comment]
Sure @ArafatOSDev, thanks for contributing!
