### ISSUE TITLE
Improve relation empty states on record page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7152]
# Current behavior

The empty relation states are displayed like this, taking up too much unnecessary space.

![CleanShot 2024-09-19 at 15 38 20](https://github.com/user-attachments/assets/5f506acd-369b-4eea-8297-0d6c67a61297)

# Desired Behavior

- Remove the "No XXX" empty state
- Remove the `All(0)` button when there is no relation
- When **there is no relation set**, display the "+" or "pen" icon button that allows to add or modify the relation. Keep it on hover when there is a relation to lighten the interface.

![image](https://github.com/user-attachments/assets/ea917ecb-9b3a-4824-af35-e0f2b2ccb0a5)

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=32530-139682&node-type=frame&t=VEnadEyAJpb29rmb-11

**Comment by falgunmpatel** [comment]
@Bonapara May i work on this issue?

**Comment by Bonapara** [comment]
Sure @falgunmpatel, thanks for contributing!

**Comment by FelixMalfait** [comment]
Completed!
