### ISSUE TITLE
Email thread action bar UX improvements

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7155]
# Current behavior

The action bar on the email thread is too big and lacks a top border

![CleanShot 2024-09-19 at 09 35 48](https://github.com/user-attachments/assets/16029bd5-57db-4b9c-a29f-dda03d8c56fb)

# Desired Behavior

Use the same action bar that we will use for #7069. (Today the email thread action bar is too big and lacks a top border)

![image](https://github.com/user-attachments/assets/317edf72-3710-4641-9269-c5dbf5f98cbc)

**Comment by ehconitin** [comment]
@Bonapara is the height of the button correct? or that need a change too?

**Comment by ehconitin** [comment]
https://github.com/user-attachments/assets/1ca338f6-508f-4bca-99d0-1cd6e4fac1c6

**Comment by ehconitin** [comment]
![Untitled design (1)](https://github.com/user-attachments/assets/7b68fe83-9924-4149-9985-5c17903cad91)

**Comment by Bonapara** [comment]
@ehconitin, height looks correct (32px right?). Thanks!

**Comment by ehconitin** [comment]
@Bonapara  yup 32px.
