### ISSUE TITLE
Kanban card inline field design improvements

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7163]
# Bug description

1. All inline field heights should be 24px, as they are on record pages.
2. There should be a 2px gap between inline field rows.

Make sure it works on all object types.

![CleanShot 2024-09-19 at 18 52 35](https://github.com/user-attachments/assets/0ef335ab-3453-4035-bbd2-15b136be133f)

# Figma

![CleanShot 2024-09-19 at 18 57 59](https://github.com/user-attachments/assets/0ce99ef3-a238-40bd-bd26-a8d393948a1b)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=24955-194483&node-type=frame&t=QiAhlR2aMME8996Z-11

**Comment by ehconitin** [comment]
Ill address them in #6957 @Bonapara

**Comment by ehconitin** [comment]
fixed in #7169
