### ISSUE TITLE
Created by should not have left & right margins

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7164]
# Current behavior

The `Created by` chip has a 4px margin on both the left and right sides.

![26c80322be1d8255ef2f9dccf9f5867fed7cb9d1cb2c3d0a1259a24115ddff76](https://github.com/user-attachments/assets/ae4ef1f3-b54e-4f83-adc1-eeb8bbf94a62)

# Desired Behavior

Remove the chip as it's not a relation. This should allow content to be vertically aligned with text fields on kanban cards and on record pages.

Make sure it doesn't break anything else

![CleanShot 2024-09-19 at 19 17 13](https://github.com/user-attachments/assets/d0dd6120-e191-4799-ad13-e5f6dee83d75)

**Comment by GARY121github** [comment]
Hello @Bonapara Can I work on this issue ?

**Comment by Bonapara** [comment]
Sure @GARY121github, thanks for contributing!

**Comment by maheswar-dileep** [comment]
@GARY121github  are you still working on this issue??
@Bonapara  If not please assign it to me.

**Comment by Bonapara** [comment]
Unassigning you, @GARY121github, as it's been three weeks, and assigning you, @maheswar-dileep. Thank you both for contributing!

**Comment by vamus092** [comment]
is the issue resolved otherwise i can work on that
@Bonapara

**Comment by Bonapara** [comment]
Nope @vamus092!

**Comment by khuddite** [comment]
I am looking into the issue

**Comment by khuddite** [comment]
@Bonapara Are we gonna remove the `Created by` option from the Kanban board, so there is no way to see `Created by` field on the cards? Or are we just gonna hide it by default so it shows up here where you can make it visible as necessary?

![CleanShot 2024-11-06 at 09 20 50](https://github.com/user-attachments/assets/38e7d850-4980-4752-b310-ffc9a406cbd9)

**Comment by khuddite** [comment]
Oh, I think I got you. If you meant to remove the avatar(CSV in ur screenshot, T in mine), I think it will cause some inconsistencies because 'Created by` is not the only field that has an avatar.

![CleanShot 2024-11-06 at 10 00 40](https://github.com/user-attachments/assets/f43f9922-1ad3-412d-914e-081f16b15470)

For ex, here, `Company` field also has an associated avatar.

**Comment by Bonapara** [comment]
Hi @khuddite, I mean remove the margins/paddings from the "created by" that seems to be in an invisible chip.

**Comment by khuddite** [comment]
![CleanShot 2024-11-07 at 09 31 53](https://github.com/user-attachments/assets/0d28c20d-0464-4c56-98eb-9b12b5f519e5)

I think it requires many more changes than just removing padding/margin from the `Created by` chip. Honestly I think making that one change might cause more problems than it solves. For example, in the above screenshot, many columns (like name, email, creation date, city, etc) are not vertically aligned between the header and content. 

This is a file that has all different types of fields - https://github.com/twentyhq/twenty/blob/a58236e6dae7c8ccb4375ca5e2ca2e8f9c957cb7/packages/twenty-front/src/modules/object-record/record-field/components/FieldDisplay.tsx

**Comment by Bonapara** [comment]
@khuddite everything has a 6px margin left in cells. But created by has a 6px left + 4px empty chip that should be removed

**Comment by JorgeGraciaViveros** [comment]
Hi @Bonapara  ! I am currently working in a group of 5 students from Carnegie Mellon taking a software engineering course and our final project is to contribute to an open-source repo. Our project has multiple checkpoints and will be due on December 8 (meaning our PR will take longer to open). Would it be possible for us to be assigned to this issue (or any issues that you think would be a good fit)? Thanks!

**Comment by tinchil** [comment]
Hi @Bonapara. Can I be assigned to work on this issue?

**Comment by Bonapara** [comment]
@tinchil There is already an open PR for this one!
