### ISSUE TITLE
Demo login not functioning

### ISSUE THREAD

**Issue by hr23232323** [twentyhq/twenty#7165]
## Bug Description
Login for the demo application (https://demo.twenty.com/welcome) is not working when using credentials in the repository README.

## Screenshot
<img width="1509" alt="image" src="https://github.com/user-attachments/assets/5679a813-0d7f-4f07-8a62-f761fe19f3a6">

## Expected behavior
Login successfully

## Misc. Details
If helpful, seeing this in console logs - 
```
{errors: [{message: "Wrong password", extensions: {code: "FORBIDDEN"}}], data: null}
```

**Comment by FelixMalfait** [comment]
It should be working now! We also changed the default login to tim@apple.de so that it's prefilled automatically like in the local environment
