### ISSUE TITLE
Impossible to update soft-deleted record

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#7172]
In the UI it's possible to edit a soft-deleted record but the backend refuses it.

**Comment by sid0-0** [comment]
I see that this is marked as a backend issue, but soft deleted records should not be editable, right?
I believe the fix should be to block editing of soft deleted items from frontend.

**Comment by FelixMalfait** [comment]
@sid0-0 I was thinking it'd be best to leave it editable on fix it on the backend yes. Because for example when we introduce unicity constraints then it would allow the person to edit the email and restore the record even though there's a conflict. 

But I'm not against a pure-frontend solution making it readonly, only if it's elegant code. I don't know that part of the codebase well enough to know if it's possible to do someting elegant across the app or if that implies refactoring the read-only implementation

**Comment by FelixMalfait** [comment]
Haha great thanks @pau-not-paul

**Comment by ehconitin** [comment]
Any update on this issue? 
@pau-not-paul are you still working on the PR?
