### ISSUE TITLE
How to Setup Messaging & Calendar sync

### ISSUE THREAD

**Issue by Bullrich** [twentyhq/twenty#7189]
Hi!

I'm a bit confused on the wording in the [Setup Messaging & Calendar sync](https://twenty.com/developers/section/self-hosting/self-hosting-var#setup-messaging-&-calendar-sync) section:

> Twenty offers integrations with Gmail and Google Calendar. To enable these features, you need to connect to register the following recurring jobs:
> `# from your worker container`
> `yarn command:prod cron:messaging:messages-import`
> `yarn command:prod cron:messaging:message-list-fetch`
> `yarn command:prod cron:calendar:calendar-event-list-fetch`

What does `connect to register the following recurring jobs` means in this context?

Do I need to jump into the docker image and run those commands? Or do I need to do a different thing?

**Comment by Bonapara** [comment]
Hi Bullrich, please use the #help channel of our [Discord](https://discord.com/invite/cx5n4Jzs57)
