### ISSUE TITLE
Allow filtering by ICP

### ISSUE THREAD

**Issue by Sytten** [twentyhq/twenty#7190]
## Scope & Context

Default account created a few days ago.

## Current behavior

I can't filter on ICP (true/false) in compagnies.
<img width="209" alt="Screenshot 2024-09-20 at 6 43 09 PM" src="https://github.com/user-attachments/assets/6d58aef7-e208-4ef9-b469-58650aa96ea4">

## Expected behavior

Please let me filter on ICP to I can find my leads!

**Comment by az1plo** [comment]
Hello, I'd like to work on this issue. Can you please assign me?

**Comment by FelixMalfait** [comment]
/oss.gg 200

**Comment by FelixMalfait** [comment]
This is probably a missing configuration on the boolean filter type in the frontend

**Comment by 0xnim** [comment]
If you dont finish it ill take it.

**Comment by FelixMalfait** [comment]
@ad-elias would you mind also looking into this?
