### ISSUE TITLE
Warning about forwardRef in devtools

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7192]
**Scenario:**
1. Log in

**Actual:** There's error in devtools about forwardRef render (error appears already in login page after clicking "Continue with email" button)
![image](https://github.com/user-attachments/assets/799399ab-96da-40e7-ac88-2db03f604d75)
**Expected:** No error should be added in devtools

Error:
```
Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
```

**Comment by zephearmin** [comment]
This would be fixed by https://github.com/twentyhq/twenty/pull/7183

**Comment by Bonapara** [comment]
Closing this issue then @zephearmin, thanks!
