### ISSUE TITLE
Account page not displaying connected accounts

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7194]
# Bug description

The account page shows no connected accounts, even though I have two linked emails. The bug persists even after refreshing the page.

<img width="1395" alt="image" src="https://github.com/user-attachments/assets/db5cf0b0-41cf-44ca-b7a8-e5f955cf879b">

![CleanShot 2024-09-21 at 18 59 44@2x](https://github.com/user-attachments/assets/2ab34d67-59cc-4e12-9198-088a8225484d)

**Comment by ffshreyansh** [comment]
Hi @Bonapara I am working on it, will update you if anything occurs.

**Comment by ehconitin** [comment]
@Bonapara working on this!

**Comment by ffshreyansh** [comment]
@Bonapara in my local env, It is showing the connected acocunt. PS: I am using the tim@apple.dev account.
Is it account specific??

**Comment by ehconitin** [comment]
@Bonapara couldnt reproduce.
@ffshreyansh I dont think so! It should not be account specific.

![downloaded](https://github.com/user-attachments/assets/3edc8ba4-3417-4d77-a98d-6407c7afc05d)

**Comment by Bonapara** [comment]
The core team is on it @ehconitin, thanks for having a look!

**Comment by ehconitin** [comment]
oh okay, thanks for letting me know!
