### ISSUE TITLE
Appearance Settings Cropped Card

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7198]
# Bug description

The right edge of the `System settings` card is cropped:

![CleanShot 2024-09-23 at 12 02 43](https://github.com/user-attachments/assets/8eeb7273-4d3b-4b08-b08c-51e3e92f3785)

# How to reproduce

Go to the appearance settings

**Comment by Nisarg-Sha** [comment]
any specific browser problem ? because it looks fine on chrome

**Comment by ehconitin** [comment]
fixed in #7232
