### ISSUE TITLE
Support EMAILS, LINKS, PHONES in Zapier Inputs

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#7203]
## Scope & Context

We have recently introduced EMAILS, LINKS, PHONES composite fields in Twenty. However these fields are not available on Zapier. We should add them too.

## How

See: packages/twenty-zapier/src/utils/computeInputFields.ts
Remove LINK case (it has been removed)
Introduced LINKS, PHONES, EMAILS (take inspiration on ADDRESS). Composite types are defined here in the backend: packages/twenty-server/src/engine/metadata-modules/field-metadata/composite-types/address.composite-type.ts

## How to test

I'm unsure how to test it but you will likely need to create a test account on zapier and deploy the twenty app in "test" mode there

**Comment by Naman-Jaju** [comment]
Is this issue open or already completed?
If not I would like to work on it.
