### ISSUE TITLE
Last field overflows to the screen's right edge

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7216]
# Bug description

The email field in the last column adds extra width to the screen. It should not be able to overflow over the app content, instead, the input should shift slightly to the left when too large.

![176e0a0cc145c58f5bb1e489c316d25b933fe65ce2dc2d8ed56b0b9cceadbd52](https://github.com/user-attachments/assets/663d8f74-0f81-4587-9e36-ce17bddabdde)

Desired:

![CleanShot 2024-09-23 at 16 56 47](https://github.com/user-attachments/assets/d0285b9b-5e4c-4533-99a6-c9fd6fd83ed5)

**Comment by adarshmalviya12** [comment]
Can I work on this issue?

**Comment by Bonapara** [comment]
Sure, thanks for contributing @adarshmalviya12!

**Comment by balvind3r** [comment]
@mav92121 
Are you working on the issue?
I would like to contribute in the same.

**Comment by harshrajeevsingh** [comment]
@devcodes9 are you still working on this?

**Comment by harshrajeevsingh** [comment]
@Bonapara Can I take this up?

**Comment by Bonapara** [comment]
Sure @harshrajeevsingh, thanks for contributing!

**Comment by Bonapara** [comment]
I can still reproduce it, @harshrajeevsingh. If you reduce the column width, it will still overflow as described in the issue.

https://github.com/user-attachments/assets/611755ff-d49d-4926-a92b-470d435ab2df
