### ISSUE TITLE
Remove Primary Banner Icon When Only One Value Present

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7220]
# Current Behavior

The first `email, phone, or domain` field has a banner icon to indicate it's the default/primary value.

![CleanShot 2024-09-23 at 16 58 03](https://github.com/user-attachments/assets/445ab5f6-c273-456e-b3fa-b4bd6346110a)

# Desired Behavior

**When there is only one value**, we don't need to indicate it's the primary value or display the banner icon, as it is unnecessary and confusing for the three-dot icon menu.

**Comment by syeddhasnainn** [comment]
i am working on this, i managed to fix it for the emails and domains but i cant see the option to add phone numbers

**Comment by Bonapara** [comment]
@syeddhasnainn The phone numbers issue is -> https://github.com/twentyhq/twenty/issues/6260

**Comment by KeeratKK** [comment]
Sorry I started working on this and did not check to see that someone else had already said they wanted to work on it. This is my first contribution so I was just wondering if it was still okay to submit the PR?

**Comment by Bonapara** [comment]
Thanks @KeeratKK, yes as it's a very small fix. @syeddhasnainn do you want to pick another [Good First Issue](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)?

**Comment by syeddhasnainn** [comment]
> Thanks @KeeratKK, yes as it's a very small fix. @syeddhasnainn do you want to pick another [Good First Issue](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)?

Sure
