### ISSUE TITLE
Email Sync w/ Office 365

### ISSUE THREAD

**Issue by ShantanuJoshi** [twentyhq/twenty#7228]
## Scope & Context

My organization needs email sync w/ office 365

## Current behavior

GSuite accounts sync only at the moment

**Comment by FelixMalfait** [comment]
/oss.gg 3000

**Comment by FelixMalfait** [comment]
This is a complex issue that probably takes a week to complete. We have tried to abstract some of the gmail code already to prepare for that. The work consists of copying what has been done for gmail and doing something similar with the Outlook/Office APIs. The MS SSO has already been implemented

**Comment by Sulochan-khadka** [comment]
> This is a complex issue that probably takes a week to complete. We have tried to abstract some of the gmail code already to prepare for that. The work consists of copying what has been done for gmail and doing something similar with the Outlook/Office APIs. The MS SSO has already been implemented

May you ,guide me what has already been done and what is the required task? The issue which has been described enough helps me work better.

**Comment by 11w5** [comment]
I am super interested in sponsoring or supporting this feature. I want to utilize a plethora of distribution groups to create workflows and work streams from my Office 365.

**Comment by FelixMalfait** [comment]
Thanks to @brendanlaschke who kindly took this task alone, this is probably coming soon!!! Closing the issue (there was a discussion already: https://github.com/twentyhq/twenty/discussions/3940)
