### ISSUE TITLE
Values field card lacks width in mobile viewports

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7230]
> [!Note]
> Go to **Settings/Data model/open any existing objects/open fields**
> In mobile viewports, Custom and standard chips clips through the card

## Current Behaviour
<img width="411" alt="Screenshot 2024-09-24 at 9 51 42 AM" src="https://github.com/user-attachments/assets/65d283b8-24fa-4e25-b3bd-2e35efabf768">

## Expected behavior

Since the header and chip can't fit in one row space for all mobile viewports so they can be arranged in the following possible way- 

<img width="430" alt="Screenshot 2024-09-23 at 1 10 18 PM" src="https://github.com/user-attachments/assets/101e4278-6e9e-4512-9206-f196d1f89ae5">

**Comment by harshit078** [comment]
@Bonapara, Instead of passing flex-direction: row and altering other values which would result in a design disruptency. Can we pass flex direction: column only when there are 2 cards as a result it would only hamper that particular case. What are you views on this ? Is there ant better approach to follow.

<img width="556" alt="Screenshot 2024-09-25 at 10 38 40 AM" src="https://github.com/user-attachments/assets/97a32497-4230-438f-b048-707bdcd9b674">

<img width="578" alt="Screenshot 2024-09-25 at 10 38 52 AM" src="https://github.com/user-attachments/assets/74e7d055-96fc-4bf4-bddc-e84cf03a6599">

Instead of - 

<img width="601" alt="Screenshot 2024-09-25 at 10 40 08 AM" src="https://github.com/user-attachments/assets/a6cde571-fd89-4ecd-a314-0ec8d720313d">
<img width="602" alt="Screenshot 2024-09-25 at 10 40 32 AM" src="https://github.com/user-attachments/assets/acf69247-8046-470b-b015-14c1894fb1ea">

**Comment by Bonapara** [comment]
Much better @harshit078, thanks! 🙏

**Comment by ehconitin** [comment]
fixed in #7248
