### ISSUE TITLE
Whitescreen when user not found

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#7244]
I was going back to demo.twenty.com and since the database was reset it threw a "user not found" error. But this error wasn't properly interpreted by the frontend and I just had a full blank page. Instead I should have been logged out and sent to the login page (we should already have this mechanism for token expiration).

Maybe check if it's a proper AuthException being thrown in every case?

This probably happens to everyone who visits the demo website and comes back the following day.

**Comment by himanshuraimau** [comment]
can i work on this issue?

**Comment by FelixMalfait** [comment]
Sure @himanshuraimau thanks!

**Comment by himanshuraimau** [comment]
no problem i will try to figure it out.

**Comment by himanshuraimau** [comment]
the issue is this page right?
![Screenshot from 2024-09-27 00-37-35](https://github.com/user-attachments/assets/bca7d080-51ff-40a1-bae2-524ac51e5a94)

**Comment by FelixMalfait** [comment]
@himanshuraimau Mmh no I think that's something different linked to the fact that your database schema changed (no artist object)

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by Bonapara** [comment]
Removing you @Anujv93 as it's been two weeks, thanks for contributing!

**Comment by krVatsal** [comment]
Is this issue already solved?

**Comment by krVatsal** [comment]
@FelixMalfait  Can you help me to replicate the issue such that i can fix it more efficiently

**Comment by nicolasrouanne** [comment]
I just tried to reproduce this locally and I wonder if it's still happening.

Here's what I did:
- seeded in `demo`
  ```sh
  cd packages/twenty-server
  npx nx workspace:seed:demo
  ```
- logged in using `tim@apple.dev`
- reseeded in `demo` (deleting all previous data)
- (waited for the `accessToken` to expire)
- refreshed the frontend

I get a `Token has expired.` error, followed by a `Token invalid.` error when trying to renew the token - which is expected.
```json
{
  "errors": [
    {
      "message": "Token has expired.",
      "extensions": {
        "code": "UNAUTHENTICATED"
      }
    }
  ]
}
```

```json
{
  "errors": [
    {
      "message": "Token invalid.",
      "extensions": {
        "code": "UNAUTHENTICATED"
      }
    }
  ],
  "data": null
}
```

I'm then redirected to the login page, as expected too.

I'm currently logged in on the real `demo` environment, and will try to reproduce tomorrow morning.

**Comment by Anuragyadav622003** [comment]
ensure frontend recognize the "unauthenticated" errors from the expire token and trigger a  refresh request. 
to correctly generate the new access token the refress token must be valid  that helps to generate new access tokens.
clear all browser storage like (local storage) to prevent using of out dated tokens

**Comment by nicolasrouanne** [comment]
@Anuragyadav622003 I'm not sure I understand your point... I'm saying that as far as I'm concerned everything seems to work as expected.

I will double check tomorrow on the [demo](https://demo.twenty.com/) environment if I can reproduce the issue, once the cron task to reseed the `demo` environment has run.

**Comment by FelixMalfait** [comment]
@nicolasrouanne I suspect it's this:

<img width="464" alt="Screenshot 2024-11-13 at 10 23 44" src="https://github.com/user-attachments/assets/0588b16d-d7a5-464b-88d0-e93d1f897c0f">
<img width="461" alt="Screenshot 2024-11-13 at 10 24 59" src="https://github.com/user-attachments/assets/1cece683-80fb-4c81-a397-abde43559b50">

When we validate the token we throw a `INVALID_INPUT` instead of `USER_NOT_FOUND`

**Comment by FelixMalfait** [comment]
FYI behavior on the frontend is defined here:
<img width="350" alt="Screenshot 2024-11-13 at 10 33 52" src="https://github.com/user-attachments/assets/e18454e3-8776-43d1-9ab0-5ea012728450">

**Comment by nicolasrouanne** [comment]
@FelixMalfait I still couldn't reproduce either in `demo` or `development` environment. Refreshing the page with yesterday's accessToken on `demo` still logged me in, although the DB was re-seeded (which is weird no?)

Anyway, I believe it may happen and you maybe are able to reproduce it on your side, so I'm still going to try to fix it. 🤞🏻 

 Thanks for the pointers it really helped me out, and I think you were right in your analysis. I try to sum it up here:
- if the user isn't found, we throw an `AuthException` but with the `AuthExceptionCode.INVALID_INPUT` code (weird hun)
  https://github.com/twentyhq/twenty/blob/898006f89d099872f514d533241bf116096fdadb/packages/twenty-server/src/engine/core-modules/auth/strategies/jwt.auth.strategy.ts#L114-L117
- this exception is then caught and a `UserInputError` is thrown
  https://github.com/twentyhq/twenty/blob/898006f89d099872f514d533241bf116096fdadb/packages/twenty-server/src/engine/core-modules/auth/filters/auth-graphql-api-exception.filter.ts#L21-L22
- but this error doesn't have an `UNAUTHORIZED` error code, that would have allowed _graphql_ to properly try to renew a token and redirect to login
  https://github.com/twentyhq/twenty/blob/898006f89d099872f514d533241bf116096fdadb/packages/twenty-front/src/modules/apollo/services/apollo.factory.ts#L99-L111
  https://github.com/twentyhq/twenty/blob/898006f89d099872f514d533241bf116096fdadb/packages/twenty-front/src/modules/apollo/hooks/useApolloFactory.ts#L67-L82
 It [has](https://github.com/twentyhq/twenty/blob/898006f89d099872f514d533241bf116096fdadb/packages/twenty-server/src/engine/core-modules/graphql/utils/graphql-errors.util.ts#L147-L153) a `BAD_USER_INPUT` error code, which graphql doesn't know what to do with.

So I suggest rather, when a user is not found in `jwt.auth.strategy`, to throw a `USER_NOT_FOUND` exception, which will properly be rethrown as an `AuthenticationError`.
https://github.com/twentyhq/twenty/blob/898006f89d099872f514d533241bf116096fdadb/packages/twenty-server/src/engine/core-modules/auth/filters/auth-graphql-api-exception.filter.ts#L26-L28

By the way, that's what's done in `impersonate`, `verify`, `challenge` and `updatePassword`.

>[!WARNING]
> This will change the HTTP response code for the REST API though... It will go from 400 to 404. Which is actually a breaking change.
> https://github.com/twentyhq/twenty/blob/898006f89d099872f514d533241bf116096fdadb/packages/twenty-server/src/engine/core-modules/auth/filters/auth-rest-api-exception.filter.ts#L20-L24

**Comment by FelixMalfait** [comment]
Agree with your analysis @nicolasrouanne thanks a lot!
You can create random accounts in demo. I guess it worked for you because you used tim@apple.dev which is seeded with the exact same uuid every day, but in my case maybe I have created a different account in demo and therefore it wasn't there the following day 🤔 that's my best guess!

**Comment by nicolasrouanne** [comment]
Arf I completely forgot UUIDs are hardcoded that's why! Thanks!

Is changing the HTTP code for the REST API not an issue? Do you want that I open a PR?

**Comment by FelixMalfait** [comment]
@nicolasrouanne yes changing that part of the REST API isn't a big deal, I don't even think the token endpoints should be available in REST as we only use GraphQL internally and this is not something workspace users should care about
If you don't mind raising a PR that's always appreciated of course 😌 thanks a lot!

**Comment by nicolasrouanne** [comment]
I managed to reproduce, following your [hint](https://github.com/twentyhq/twenty/issues/7244#issuecomment-2473888374) @FelixMalfait . It was indeed because I was using the `tim@apple.dev` seeded user that I didn't experience any issue.

Here is how to reproduce in dev environment
- seed the `database` using `npx nx database:reset twenty-server`
- login using `tim@apple.dev`
- copy the _Invite member by link_ URL
- open the invitation link in _Incognito window_  and signup with another email
=> you are now logged in using a new user, **don't close this browser window**
- re-seed the `database`: `npx nx database:reset twenty-server`
- refresh the browser window where you were previously logged in as a new user
=> the _white screen_ appear and never leaves 💥 

If you inspect the browser console requests, you can see that the `graphql` exception code is `INVALID_INPUT`
