### ISSUE TITLE
Invite by email table overflows in mobile viewport

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7253]
## Bug Description

- Go to workspace/Members
- Add emails to be invited
- when email input is long then the table overflows.

## Current behaviour

<img width="435" alt="Screenshot 2024-09-25 at 6 36 15 PM" src="https://github.com/user-attachments/assets/1b17f8ab-ba74-4edb-8f56-71d797430626">

## Expected behavior

<img width="427" alt="Screenshot 2024-09-25 at 6 48 13 PM" src="https://github.com/user-attachments/assets/f8a376b2-7f4e-4172-a695-fead7be40574">

**Comment by Bonapara** [comment]
🙏🙏

**Comment by dilshad-knk** [comment]
hey can i work on this

**Comment by ehconitin** [comment]
@harshit078 are you working on it yourself? or should I assign @dilshad-knk ? ;)

**Comment by harshit078** [comment]
@ehconitin I'm working on this :)

**Comment by ehconitin** [comment]
@dilshad-knk Thankyou for contributing, please pick another [good first issue](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee) from here :)

**Comment by ehconitin** [comment]
closed in #7273
