### ISSUE TITLE
Clicking Enter selects the first field in custom Select fields

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7266]
## Bug Description

- When created a custom Select field and given dropdowns, On pressing enter it selects the first value
- This only happens in Select field and not Multi select field

## Current Behaviour

On pressing enter - 

https://github.com/user-attachments/assets/7e87d0fe-c43b-4b94-8d7c-f5334a9279c3

<img width="614" alt="Screenshot 2024-09-26 at 5 44 04 PM" src="https://github.com/user-attachments/assets/75306383-ac7f-467b-8a77-88888cd64237">

## Expected behavior

- On pressing enter, the dropdown should not select the first value and nothing should trigger.

**Comment by badmuffin** [comment]
hii, i would like to work on this issue

**Comment by lucasbordeau** [comment]
@harshit078 We want to be able to navigate with the keyboard and press enter to select our option, there's an ongoing global refactor about that in this issue https://github.com/twentyhq/twenty/issues/4365, so I'm closing this one.
