### ISSUE TITLE
Cursor should not be "pointer" when record image identifier is not editable

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7277]
# Current behavior

cursor is set to `pointer`

https://github.com/user-attachments/assets/d1e50f13-fb7a-4ef3-90c2-29e5f0b99da2

# Desired Behavior

cursor should be set to `default` when record image identifier is not editable

**Comment by sachinks07** [comment]
@Bonapara I would like to work on this issue.

**Comment by Bonapara** [comment]
Sure @sachinks07, thanks for contributing!

**Comment by Bonapara** [comment]
Sorry @idleShubh, @sachinks07 is already on it. Maybe can you grab another [Good First Issue](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)? Thanks.

**Comment by sachinks07** [comment]
@Bonapara This issue has been Fixed(#7320)
