### ISSUE TITLE
SMTP not working on self-hosted instance

### ISSUE THREAD

**Issue by whollacsek** [twentyhq/twenty#7280]
## Bug Description

Spent a day investigating suitability of Twenty for our use case how ever no email is being sent. I've setup all the `EMAIL_` env vars and our SMTP provider is Resend so I just copied the same configs from our existing system.

I've checked on Resend dashboard and no requests have landed there and in the logs of twenty there's no error messages either.

## Expected behavior

Email should be sent, at least if there is an issue it should be logged.

**Comment by FelixMalfait** [comment]
Hey @whollacsek that's strange, we use NodeMailer under the hood which is a pretty standard library. Are you sure there isn't anything misconfigured?

https://resend.com/docs/send-with-nodemailer-smtp

**Comment by whollacsek** [comment]
Is there any way to log the output of the mailer?

**Comment by ludovicbarreca** [comment]
Encountering the exact same issue, trying to use Resend and cannot seed any logs about the email sending, it makes it quite hard to debug configuration issues with no logs.

**Comment by FelixMalfait** [comment]
You can output the emails in logs, there's a driver for that: https://github.com/twentyhq/twenty/blob/0d570caff5d923e132789d7a5a62a04253d0a531/packages/twenty-server/src/engine/core-modules/email/interfaces/email.interface.ts#L4

Set `EMAIL_DRIVER=logger` in your .env then restart the server

**Comment by FelixMalfait** [comment]
Maybe that's your issue actually, you left EMAIL_DRIVER=logger (default value)? Feel free to raise a PR in the docs if there's something we could clarify! Thanks

**Comment by AmsellemJoseph** [comment]
Hey,
I had the same issue, but I resolved it by adding smtp env var also in worker container.
I hope it will help you

**Comment by whollacsek** [comment]
Thanks I'll give it a try when I have some time

**Comment by chrisjenx** [comment]
Having the same issue, not getting emails from Sendgrid (setup sendgrid in a bunch of different services before including our backend), seems like an error is getting caught silently somewhere, would be good to get errors printed to logs if it fails to send.

**Comment by chrisjenx** [comment]
Also a few other things, do the env vars need to be set in the docker-compose.yaml? if so they aren't on their by default (i added them to try and get working)
Also not obvious that it's set to logger by default (is that true?), if it is, I still wasn't seeing logs sent before I set it to smtp.

On. 0.40.1 fyi

**Comment by FelixMalfait** [comment]
@ehconitin will soon be working on migrating most env variables to the db-level so in the future we'll provide an admin panel to edit them. Hopefully that should help people who self-host!

Note that the emails are sent by the WORKER (async) not by the server so the email logs would appear on the worker's logs not on the server logs :)

**Comment by chrisjenx** [comment]
@FelixMalfait I added env vars to both worker and server and tailed both and didn't see anything from either :(

**Comment by grrinch** [comment]
Had the same issue as the others today. 

After doing what @chrisjenx did - once I added the email+smtp environment vars to worker section in docker-compose.yml everything started to work.

**Comment by chrisjenx** [comment]
Mmm mine still doesn't work after adding to both. I'll double check I didn't typo something

**Comment by whollacsek** [comment]
For people who have issues after adding the env vars, back then I noticed
some database issues so I manually applied the migrations, you can find the
command in the server's package.json

**Comment by sredfern** [comment]
Hi, I'm having similar issues on a new install. 

I needed to check the ENV was being passed correctly. You can use this command to work that out: 

```
docker exec twenty-worker-1 env
```
and 
```
docker inspect twenty-worker-1 | grep -A 20 "Env"
```

**Comment by moorenot** [comment]
I did what @sredfern told, the .env is ok, but the default options was conflicting with .env info.

When I added the info to admin config, it worked.

Note that the "EMAIL_SMTP_NO_TLS" is false when you want secure connection using port 465.

My SMTP provider is Resend.

**Comment by chrisjenx** [comment]
I haven't retried, but I can't upgrade my instance, so will probably blow it away then create a new setup, wish could export and import instances :(
