### ISSUE TITLE
`Notes` and `Tasks` icons size issue

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7282]
# Bug description

The `Notes` and `Tasks` icons resize when the title is long or the column width is reduced.

https://github.com/user-attachments/assets/eeacf5ca-e08c-4fd0-83d7-5a1266eb2144

# How to reproduce

- Create a note/title with a very long title
- Resize the Title column

**Comment by Vardhaman619** [comment]
@Bonapara I would love to work on this issue.

**Comment by Bonapara** [comment]
Sure @Vardhaman619, thanks for contributing!

**Comment by ehconitin** [comment]
closed in #7318
