### ISSUE TITLE
Adjust Floating Input Padding and Border Color

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7286]
# Current Behavior

- The floating input's left padding is too large (4px + 8px padding when the vertical padding is only 8px).
- The border is too light.

![fd020e3be8ca21f48d0164d4b6009c909ca8393281162f7a5d546520af354b61](https://github.com/user-attachments/assets/28d6048b-cb3a-4479-acf2-d6e57519f42c)

# Desired Behavior

- Set the left-padding to 8px.
- Change the border color to `Borders/medium`.

![image](https://github.com/user-attachments/assets/fb265897-8fc9-407a-83ae-a1bab2fec894)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=3007-69739&node-type=frame&t=yAzVtdp6KfcheBnI-11

**Comment by nganphan123** [comment]
Hi @Bonapara , can I take this?

**Comment by Bonapara** [comment]
Sure @nganphan123, thanks for contributing!

**Comment by Supratim69** [comment]
Is this issue sorted? or is there something left to be done?

**Comment by Bonapara** [comment]
It looks like it was fixed indeed, thanks for notifying @Supratim69!

**Comment by ehconitin** [comment]
closed in #7328
