### ISSUE TITLE
Relation picker UX improvements

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7287]
# Current behavior

On record pages relation pickers

![ed3fe0f44e5b33f5794b7892a39f039985c9c62f0aa6c20222c705016648a2b6](https://github.com/user-attachments/assets/05da14a4-0131-4f0b-b49a-ff1aab3423d7)

![bcb49101f04146e7eb34836344eafb1a9050721275ca7e3cee716d2218a4c960](https://github.com/user-attachments/assets/692ccda3-953b-4700-9f58-2ac2409eb228)

# Desired Behavior

1. the left margin between the `Add new` button and the separator is too narrow (Should be 4px)
2. The separator should take the full width

**Comment by harshit078** [comment]
@Bonapara, Can I take this up ?

**Comment by Bonapara** [comment]
Sure @harshit078, thanks for contributing!
