### ISSUE TITLE
Add Header to Email & Calendar Tabs

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7288]
# Current Behavior

### Accounts Page

![532ccb9f68e3fdbf19ad9dcc73c2cad46c6551c56b0de47a1f0b46ae6c175938](https://github.com/user-attachments/assets/d027ba32-9f8f-4055-9624-a65602a85a1d)
 
### Email & Calendar Page

No section titles introduce the "No connected account" message.

![CleanShot 2024-09-27 at 12 07 24](https://github.com/user-attachments/assets/b11aae24-640c-44ee-aed7-27a7c1250e5d)

# Desired Behavior

Add the following header to the Email & Calendar tabs when no account is connected. Ensure the spacing matches the account page to prevent content glitches when switching pages.

**Connected Accounts**
Manage your internet accounts

![CleanShot 2024-09-27 at 12 08 14](https://github.com/user-attachments/assets/e925114e-46c1-4c4a-80df-2b23142bae55)

**Comment by kant-github** [comment]
Hi @Bonapara , Can I solve this issue?
