### ISSUE TITLE
Cursor pointer on Settings cards

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7289]
# Current behavior

In `/settings/accounts` there is no cursor pointer on card hover

![CleanShot 2024-09-27 at 12 12 19](https://github.com/user-attachments/assets/74b0d932-f3ed-471a-b16b-6f87983173b1)

# Desired Behavior

Add a cursor pointer to indicate that the settings cards are clickable. Ideally, we should change the HTML tags for accessibility rather than relying solely on CSS.

**Comment by MuditxRajput** [comment]
where I find this component in the codebase?
