### ISSUE TITLE
(Docs) Enhance local hosting docs with reference to the REST API url as well as the Graphql API url 

### ISSUE THREAD

**Issue by LucasZapico** [twentyhq/twenty#7316]
### Context

> I already have a PR on my fork and wanted to create an issue to associate. It has been my experience that all PRs on open-source repos require an issue to be associated. Though I did not see this called out in your contribution guidelines it seemed heavily implied. 

--------

**Description:** The current documentation for setting up the Twenty server and frontend does not clearly mention the REST API URL. This can lead to confusion for users who are self-hosting the application.

### Proposed Change:

- Add a callout for the local REST API URL alongside the GraphQL API URL.
- This change aims to reduce confusion and complexity for the self-hosted community.

*Affected File:*

[local-setup.mdx](/packages/twenty-website/src/content/developers/local-setup.mdx)

Additional Context: This change will help improve the onboarding experience for new users and maintainers who are setting up the project locally.

**Comment by SagarChandra07** [comment]
download

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme

you may need to install the c compiler
