### ISSUE TITLE
Select in Data model > Object > date field details in dark mode isn't clearly visible

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7321]
**Scenario:**
1. Log in
2. Go to Experience and select dark mode
3. Go to Settings > Data model > any object > Add field > select date or date and time type field > Options

**Actual:** Select in Options of date/datetime type field isn't clearly visible in dark mode
![image](https://github.com/user-attachments/assets/38c3668e-3fb8-4901-aa24-f3c9ce23bc61)

**Expected:** Select in Options of date/datetime type field should be clearly visible both in dark and light mode (below comparison in light mode)
![image](https://github.com/user-attachments/assets/94ebb20f-f698-48f1-a98d-9ceb0883c89b)

**Comment by harshit078** [comment]
- Adding onto the same -

<img width="662" alt="Screenshot 2024-09-30 at 12 16 41 AM" src="https://github.com/user-attachments/assets/d0b8f697-2d4a-4f86-83c2-c33a162497c3">

<img width="195" alt="Screenshot 2024-09-30 at 12 17 30 AM" src="https://github.com/user-attachments/assets/b6fe192b-4e09-499b-befb-8c6bfb904a4b">
