### ISSUE TITLE
Renaming file shouldn't allow changing file extension

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7323]
**Scenario:**
1. Log in
2. Go to People > record details > (doesn't matter which object as long as it has field with File type)
3. Upload a file if there are no files
4. Click on three vertical dots near date of upload and select "Rename" option
5. Change extension of the file and save changes

**Actual:** After changing the file extension, file is saved properly but after downloading modified file, it's broken (which is expected as there was no conversion between old and new file format)
[Screencast From 2024-09-29 21-53-31.webm](https://github.com/user-attachments/assets/e6e2e2a6-36a7-4f40-8819-4af60558e14b)

**Expected:** User must be able to change file's name but not the format/extension)

**Comment by harshit078** [comment]
I'm working on this one also !
