### ISSUE TITLE
Remove "Add task" button for Done tasks

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7333]
# Current Behavior

On any record page `Tasks` tab, we display an "add task" button above the "Done" tasks section.

![CleanShot 2024-09-30 at 13 30 03](https://github.com/user-attachments/assets/a3a7700e-6eab-4355-9ba0-648bc1b22f0b)

# Desired Behavior

Only the `Todo` section should have an "add task" button, as it doesn't make sense to create a done task.

**Comment by YuraL13** [comment]
Hey. I would like to help with this one!

**Comment by NinaVincova** [comment]
Hello. I would like to try to do my first issue on this task. Is it possible?

**Comment by Bonapara** [comment]
Hi @NinaVincova, sorry @YuraL13 was first. You can have a look to our [Good First Issues](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)

**Comment by ehconitin** [comment]
closed in #7362
