### ISSUE TITLE
New Relation Design hot fix

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7353]
# Current Behavior

Following [this pull request](https://github.com/twentyhq/twenty/pull/7248), we changed the new relation design.

![image](https://github.com/user-attachments/assets/30d50b89-013e-434f-ab63-1af2c4294c27)

# Desired Behavior

-  This layout **should apply only to the mobile display**. We should retain the original behavior for Desktop.
-  Ensure the relation between the cards is displayed correctly in mobile (top to bottom, not left to right).

Desktop:
![image](https://github.com/user-attachments/assets/3c972f11-4ea5-4ff0-ae4c-969dd2e5e820)

Mobile
![image](https://github.com/user-attachments/assets/63d6bc25-3a5b-4b98-a56f-0756dd3c8e2c)

# Figma

Desktop:

[View the design on Figma](https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34845-128489&node-type=frame&t=YZppWDu8cDmzxDmJ-11)

Mobile:

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=41197-120415&node-type=frame&t=YZppWDu8cDmzxDmJ-11

**Comment by harshit078** [comment]
@Bonapara can I take this up ?

**Comment by harshit078** [comment]
@Bonapara , when longer chip name then it will tend to take more space and hence would look like this - 
<img width="530" alt="Screenshot 2024-10-01 at 12 13 59 AM" src="https://github.com/user-attachments/assets/d1e337fa-bc01-49c4-ad35-618822c88376">

- Should we handle this or let it be ?

**Comment by Bonapara** [comment]
We should crop the name with ... and display the full name in a tooltip. for instance, `Workspace Mem...` Thanks @harshit078!

**Comment by harshit078** [comment]
Okay, I'll take this up

**Comment by Bonapara** [comment]
This one is fixed right @harshit078?
