### ISSUE TITLE
Prefill Relation Fields with Initiating Object Icon and Name

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7355]
# Current Behavior

Today, when we create a relation:

![CleanShot 2024-09-30 at 16 48 26](https://github.com/user-attachments/assets/8d1969c4-3a80-490d-8d82-58cd26707919)

1. We display the `user` icon as the default "Field on XXX" icon.
2. We display the `Field name` as the "Field on XXX" placeholder.

# Desired Behavior

Since we know the object that initiates the relation creation, we want to prefill the "field on XXX" input and icon:
1. The object that initiates the relation icon
2. The object that initiates the relation name (adjusted for plural or singular based on the relation type: one-to-many, many-to-many, or many-to-one)

In the example above, the relation is initiated from the company object so the default "field on people" infos should be prefilled like this:

![CleanShot 2024-09-30 at 17 03 09](https://github.com/user-attachments/assets/c56deb77-8aab-44f3-916c-514c00c81ca4)

We should keep the `Field name` placeholder if the user removes the `Object initiator name` text.

**Comment by ehconitin** [comment]
are you working on this @sid0-0 ?

**Comment by sid0-0** [comment]
Yes @ehconitin a PR is raised.

**Comment by lucasbordeau** [comment]
Closed by #7363
