### ISSUE TITLE
User can delete object's name

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7357]
**Scenario:**
1. Log in
2. Go to People tab (or any tab)
3. Create new record or use existing
4. Check details of record
5. Click on record's name, delete all data and save by pressing Enter key

**Actual:** User can delete object's name
[Screencast From 2024-09-30 17-29-38.webm](https://github.com/user-attachments/assets/cb33d7c6-4f63-45b5-9073-247cc062c7aa)

**Expected:** User can't delete object's name

**Comment by katbas145** [comment]
Hi, could I help with this issue?

**Comment by motuz0001** [comment]
Hey, is it still available? I would like to work on this one
