### ISSUE TITLE
Remove many to many relation option

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7359]
# Current behavior

In Settings > Data Model > Object > New field

When creating a new `relation field` on an object, you can choose between 3 options:

![CleanShot 2024-09-30 at 17 50 48](https://github.com/user-attachments/assets/4b4aefa1-cfa4-4456-8ac5-4d97982a8583)

# Desired Behavior

Remove the `Belongs to Many` option as it's not implemented yet.

**Comment by sid0-0** [comment]
Dang!

**Comment by MK884** [comment]
if this issue is still open, I would like to work on it

**Comment by Bonapara** [comment]
Sorry @MK884, seems we already have PR to fix this one!

**Comment by ehconitin** [comment]
closed in #7360

**Comment by mayankified** [comment]
may i work on this @Bonapara

**Comment by FurquanAnwer** [comment]
Please assign this to me!

**Comment by ehconitin** [comment]
Its already fixed @FurquanAnwer !
Just some ts errors cleanup required, for which PR is raised already.
Please pick another good first issues
