### ISSUE TITLE
Enhance REST API documentation for querying on nested objects 

### ISSUE THREAD

**Issue by LucasZapico** [twentyhq/twenty#7365]
## Scope & Context

**Description**: The current OpenAPI spec does not call out the preferred method for filtering by nested object properties. 

### Proposed Change: 

- Add abstract for to filter on nested object properties 
- Add example for filter on nested object  properties 

#### Affected Files: 

- [parameters.utils.spec.ts](packages/twenty-server/src/engine/core-modules/open-api/utils/__tests__/parameters.utils.spec.ts)
- [parameters.utils.ts](packages/twenty-server/src/engine/core-modules/open-api/utils/parameters.utils.ts)

**Additional Context**: This change will help improve the developer experience (DX) for users who are setting up integrations and services with the RestAPI.

**Comment by BOHEUS** [comment]
@FelixMalfait this issue can be closed as changes are merged
