### ISSUE TITLE
Missing referenced development container?

### ISSUE THREAD

**Issue by hozza** [twentyhq/twenty#7370]
## Bug Description

_Backstory: Onboarding for development is not quick at the moment as the docs are out-of-date._ 

When digging though the code I may have found a reference to a non-existent development container (separate from the self-hosting containers) perhaps setup for development of twenty, specifically with the correct tooling etc.

This was created by @charlesBochet - but it seems some months ago there was a multi-repo/mono-repo merger and so perhaps this is lost or outdated?

TL;DR Is there a specific development container (including dev tooling etc) that's being used by the core team that you can share, or should this reference be removed from the code?

**Example:** 
https://github.com/twentyhq/twenty/blob/cde255a03171cfbefb8c4449b7983524aea0d701/packages/twenty-docker/Makefile#L1-L19

## Expected behavior

A container or compose stack designed for development would help onboarding for development a lot, especially across OS/systems. It seems one may have existed at `/packages/twenty-docker/dev/*`.

**Comment by Utzig26** [comment]
Given the discussion in [PR #7369](https://github.com/twentyhq/twenty/pull/7369#discussion_r1782821134) about removing Docker from the contributor guide, shouldn't this issue be closed? Since the team has decided not to maintain Docker dev?

**Comment by charlesBochet** [comment]
Yes you are correct @Utzig26, we should clean it as we don't maintain it and it could be misleading for users

**Comment by BOHEUS** [comment]
@charlesBochet I created #7648 as a following issue to this, I think it can be closed

**Comment by BOHEUS** [comment]
@charlesBochet this issue can be closed as changes are merged
