### ISSUE TITLE
After deleting record, any new duplicate is automatically deleted

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7379]
**Scenario:**
1. Log in
2. Go to Companies tab and create new record
3. Delete it
4. Click Options > Deleted companies
5. Delete this record permamently
6. Create new record with the same name as record from step 2 and click Options > Deleted companies

**Actual:** Duplicate record is automatically deleted and is visible in both normal and deleted view
[Screencast From 2024-10-02 08-11-14.webm](https://github.com/user-attachments/assets/a4bbbfa4-cef7-48ce-a176-7474a5efe17e)

**Expected:** To be decided by @CoreTeamTwenty

**Comment by FelixMalfait** [comment]
It seems findDuplicate doesn't filter out soft-deleted records.

Assigning to @Weiko as that endpoint is still on pg_graphql, linked issue: #6859
This should probably solve it
