### ISSUE TITLE
Records can be created in Deleted view

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7380]
**Scenario:**
1. Log in
2. Go to Companies tab (or any other tab), click Options > Deleted records
3. Create new record

**Actual:** New record can be created in Deleted view and is visible in both normal and deleted view
[Screencast From 2024-10-02 08-12-29.webm](https://github.com/user-attachments/assets/65f083df-96c2-46fb-82c8-6a64131d89bd)

**Expected:** Records can't be created in Deleted view

**Comment by BOHEUS** [comment]
Related to #7379

**Comment by BOHEUS** [comment]
All new records are in both states after any record is fully deleted

**Comment by FelixMalfait** [comment]
Should be tackled as part of #6331 probably as it's the same underlying issue. But I'm not sure what's the right strategy to solve this elegantly
