### ISSUE TITLE
After creating duplicate record, it can view deleted duplicates and restore them

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7381]
**Scenario:**
1. Log in
2. Go to Companies tab and create new record
3. Delete it
4. Click Options > Deleted companies
5. Delete this record permamently
6. Create new record with the same name as record from step 2
7. Check details of newly created record

**Actual:** Duplicate record has info about deleted duplicates, it's possible to check details and restore them

**Expected:** Deleted duplicates can't be visible in duplicate record details

**Comment by FelixMalfait** [comment]
thanks! Linked to #7379 so I'll just keep this issue as I think @Weiko's migration will fix all issues linked to duplicates
