### ISSUE TITLE
Deleting record isn't soft deleted but permamently deleted

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7382]
**Scenario:**
1. Log in
2. Go to Companies tab (or any other tab) and create new record
3. Delete new record and click Options > Deleted companies to check if there's new record

**Actual:** There is no record after deleting

**Expected:** There must be record after deleting

**Comment by FelixMalfait** [comment]
Let's prioritize #6701 which still hasn't been completed
