### ISSUE TITLE
Vertically Center Kanban Card Titles in Compact Mode

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7385]
# Current Behavior

In compact mode, the Kanban card titles are not vertically centered in their container.

![CleanShot 2024-10-02 at 10 55 09](https://github.com/user-attachments/assets/be63ab32-9550-4985-82fa-8e13dc8dc6fd)

# Desired Behavior

-  Titles should be vertically centered.
-  Compact cards' height should be 40px.
-  Ensure this change doesn't cause other issues.

![image](https://github.com/user-attachments/assets/b20ee8da-89eb-409d-acf3-0e596ee98c21)

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by Vardhaman619** [comment]
@Bonapara I would like to work on this issue.

**Comment by prakhar1535** [comment]
@Bonapara i would like to pick this issue

**Comment by Bonapara** [comment]
Sure @Vardhaman619, thanks for contributing! Sorry @prakhar1535, it was tight but @Vardhaman619 commented first ;)

**Comment by Vardhaman619** [comment]
@Bonapara take a look at this pull request.

**Comment by Bonapara** [comment]
Not merging PR, but someone from the tech team will very soon!

**Comment by ehconitin** [comment]
closed in #7391
