### ISSUE TITLE
Button group dropdown is too large

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7386]
# Current behavior

The button dropdown is too wide (32px)

![CleanShot 2024-10-02 at 11 14 33](https://github.com/user-attachments/assets/28e81def-04d4-4405-83f9-dbd85f05dfa0)

# Desired Behavior

Should be 24px x 24px for "Height Small" buttons and 32px (like today) for "Height Medium" buttons

![d84bb65bc68d5e21892097bc6957d6c5fdd68db5e6d8272bc866ba1c775a6e9f](https://github.com/user-attachments/assets/8b2b259d-1082-4e75-b763-c2813b9efde0)

**Comment by prakhar1535** [comment]
may i work on this issue ?

**Comment by gaurimadan** [comment]
Hey, I would like to work on this issue. Assign me under Hacktoberfest 2024 @Bonapara

**Comment by Bonapara** [comment]
Sure @prakhar1535, thanks for contributing! Sorry @gaurimadan, @prakhar1535 was first ;)

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by prakhar1535** [comment]
hey @Bonapara have a look #7393

**Comment by Bonapara** [comment]
Someone from tech team will review it shortly, thanks @prakhar1535!

**Comment by ehconitin** [comment]
closed in #7409
