### ISSUE TITLE
Display Record content when drag & dropping

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7388]
# Current behavior

The content hides when dragging & dropping a record.

### Kanban

https://github.com/user-attachments/assets/7f32181a-e02d-4846-b858-d40ec72d4d38

### Table

https://github.com/user-attachments/assets/f3ce7252-3670-42a8-b583-5cf18b7c48d7

# Desired Behavior

The fields should remain visible when drag & dropping a record.

**Comment by Bonapara** [comment]
/oss.gg 300

**Comment by Vardhaman619** [comment]
@Bonapara  I would like to work on this issue.

**Comment by Bonapara** [comment]
Sure @Vardhaman619, thanks for contributing!

**Comment by Bonapara** [comment]
Just assigned you @Nabhag8848, thanks!

**Comment by isreeks** [comment]
I've worked on issue #7388. Could you please assign it to me?
/assign

https://github.com/user-attachments/assets/765d00a2-a9a4-4181-b915-70b5aeb90889

**Comment by Nabhag8848** [comment]
Hey @aniketghavte   are you still working on it and made progress ? if not, in that case unassigning would help. Thanks as I have already figured out this

**Comment by Bonapara** [comment]
@Nabhag8848 just assigned you since you raised a PR!

**Comment by charlesBochet** [comment]
@Nabhag8848 I have commented on your PR, could you take a look?
