### ISSUE TITLE
Toggle Eye Icon to Expand/Collapse Kanban Card

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7389]
# Current Behavior

In Kanban compact mode, we display an eye icon button to expand the card. When clicked, the card expands, but the button remains even though it's not clickable.

https://github.com/user-attachments/assets/ab907f35-5d1b-4bf6-94a3-a3c00c309fa5

# Desired Behavior

Clicking the button again should close the card and make it compact.

**Comment by gaurimadan** [comment]
@Bonapara I would like to work on it

**Comment by Bonapara** [comment]
Sure @gaurimadan, thanks for contributing!

**Comment by DGamer007** [comment]
If this issue is still open, I would like to work on this.

**Comment by Bonapara** [comment]
Taken sorry @DGamer007

**Comment by ehconitin** [comment]
@Vardhaman619 
Thanks for the PR, but please make sure you are assigned the issue before raising one. 
Sorry @gaurimadan, but if possible could you please another good first issue!

**Comment by gaurimadan** [comment]
hey @ehconitin i have been working on this issue, will make a pr on this if that works before picking up any other issue

**Comment by ehconitin** [comment]
@Bonapara help! :)

**Comment by Bonapara** [comment]
I understand this is frustrating. Since it was assigned to you @gaurimadan, if you submit a PR today with good code quality, it will be prioritized for merging.

@Vardhaman619, please ask to be assigned before contributing to avoid this situation.

**Comment by vanshajkataria** [comment]
@Bonapara 
Is this issue still open?

**Comment by Bonapara** [comment]
Nope, fixed! Thanks @vanshajkataria ;)
