### ISSUE TITLE
Hide calendar icon if no deadline on task

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7402]
# Current behavior

On `Record Pages → Tasks Tab` We display a calendar icon on tasks without deadlines:

![af50be4b9e5cb1b5ea948af97499b7798165d66338bbe033427d6006ddc3b3cd](https://github.com/user-attachments/assets/1dd20199-69db-4e1a-96bc-8175ee5ce588)

With deadline:

![ff0cd5d06f0caa4e90165e66607442619d0a20e0a728bf195af6b8176cbcfe3b](https://github.com/user-attachments/assets/c98f4195-2af6-4452-858c-14542a2d3a21)

# Desired Behavior

Don't display the calendar icon when there is no deadline set

**Comment by motuz0001** [comment]
hey, I would like to work on this one

**Comment by Bonapara** [comment]
Sure @motuz0001, thanks for contributing!

**Comment by Bonapara** [comment]
@motuz0001 are you still on it? Thanks to you both

**Comment by vanshajkataria** [comment]
@Bonapara 
Is this issue still open for work?

**Comment by ebe25** [comment]
hey @Bonapara, if the issue is still open i would like to work on it?

**Comment by Vardhaman619** [comment]
@Bonapara  If no one is currently working on this issue, I’d like to take it on.

**Comment by Bonapara** [comment]
I just assigned you, @Vardhaman619, since @motuz0001 was not responding. Thank you both!

**Comment by Vardhaman619** [comment]
@Bonapara could you please provide the steps to reproduce this issue?
