### ISSUE TITLE
Webhooks chevron is not on the right edge enough

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7403]
# Current behavior

The webhook list chevron right in `Settings > Developers` are too much on the left

![2eb1abd382a3eaff2249a150ca9ffc3b9a1ea297903a21055bd04fea1b12f3aa](https://github.com/user-attachments/assets/95f9624e-9675-47e8-bdc1-4af1b4700d90)

# Desired Behavior

They should be only 4px to the right edge of the table

![708578e737a4621d06bbaa6ffc3e2eaa35115252b51ce06c159c360c9a1c1ada](https://github.com/user-attachments/assets/eeaee6fe-cbe8-4ed8-9b45-26bb0bfeafcd)

**Comment by Bonapara** [comment]
Yes thanks for contributing @thezeeshann!

**Comment by Bonapara** [comment]
This also occurs on the API key table:

![e75be7ef5e468d6c550f353a2de383e549a674735c5d32c402fb2126ddf83fc2](https://github.com/user-attachments/assets/44dd6723-b661-47d7-a682-01a08db30c8a)

**Comment by thezeeshann** [comment]
@Bonapara is there any doc file that can guide me on setting up a project locally? Facing some issue 

🎞️
![image](https://github.com/user-attachments/assets/ae64b4fd-1c23-47f2-897a-d58171d12d8c)

**Comment by Vardhaman619** [comment]
@Bonapara I would like to work on this issue

**Comment by Bonapara** [comment]
Sorry @Vardhaman619, @thezeeshann is already on it. Maybe can you grab another [Good First Issue](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)? Thanks

**Comment by thezeeshann** [comment]
@Bonapara is there any doc file to set the project locally? struggling to setup a project.

**Comment by Vardhaman619** [comment]
> @Bonapara is there any doc file to set the project locally? struggling to setup a project.

https://twenty.com/developers/local-setup

**Comment by thezeeshann** [comment]
@Vardhaman619  if you want to work on this issue go ahead. I'm not working on this issue.

**Comment by Bonapara** [comment]
> @Bonapara is there any doc file to set the project locally? struggling to setup a project.

On https://docs.twenty.com/ or on our Discord #help channel!

**Comment by Shaik-mohd-huzaifa** [comment]
Can you Assign me this issue?

**Comment by Bonapara** [comment]
Sorry @Shaik-mohd-huzaifa, @Vardhaman619 is already on it. Maybe can you grab another [Good First Issue](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)? Thanks
