### ISSUE TITLE
Can not link tasks to opportunities or companies

### ISSUE THREAD

**Issue by StefanoMarchesi** [twentyhq/twenty#7405]
## Bug Description

After creating a task if i try to connect it to a company or an opportunity i get 
```
Error: ApolloError: GraphQL errors on insertIntotaskTarget:
        {"message":"cannot pass more than 100 arguments to a function"}
```
If I try to create it directly from a company or opportunity I have no error but the task disappears from the company instantly, going to tasks it's there but with no relation to the company or opportunity

I came from version 0.22.0 and I'm currently on 0.30.0

**Comment by LaNochePerfecta** [comment]
> ## Descripción del error
> Después de crear una tarea, si intento conectarla a una empresa o una oportunidad, obtengo
> 
> ```
> Error: ApolloError: GraphQL errors on insertIntotaskTarget:
>         {"message":"cannot pass more than 100 arguments to a function"}
> ```
> 
> Si intento crearlo directamente desde una empresa u oportunidad no tengo ningún error pero la tarea desaparece de la empresa instantáneamente, yendo a tareas está allí pero sin relación con la empresa u oportunidad
> 
> Vengo de la versión 0.22.0 y actualmente estoy en la 0.30.0

**Comment by Bonapara** [comment]
Closing as duplicate of https://github.com/twentyhq/twenty/issues/5056

Please comment if you don't think so!
