### ISSUE TITLE
Minor fixes in Current Input field for mobile viewport

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7412]
## Bug Description

- Currency Input field input is not optimised for mobile viewports `(min-width:360px)` where devices **Samsung S8, S8+, iphone SE** and few other devices which had curved displays fall under.
- As a result it made the screen overflow and components clip outside
- the input layout lacked padding and dropdown menu container didn't take up entire width of input field

## Current behaviour

<img width="532" alt="Screenshot 2024-10-03 at 1 26 11 PM" src="https://github.com/user-attachments/assets/3c1da138-3ef9-4054-96a0-a82c34ad604c">

<img width="612" alt="Screenshot 2024-10-03 at 1 25 59 PM" src="https://github.com/user-attachments/assets/7fcefbbd-dee7-4628-83c1-f12e2b303572">

## Expected behavior

<img width="540" alt="Screenshot 2024-10-03 at 1 27 42 PM" src="https://github.com/user-attachments/assets/9ca8f9b1-0eda-4d65-9d0d-5a3bc073083b">

<img width="563" alt="Screenshot 2024-10-03 at 1 28 10 PM" src="https://github.com/user-attachments/assets/00a290d3-f547-48d5-99dd-a88fe5dae5c0">

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by harshit078** [comment]
@Bonapara, I'll be taking this up !

**Comment by Bonapara** [comment]
Thanks @harshit078! By the way did you see my email? I sent it to har(...)467@gmail.com

**Comment by harshit078** [comment]
Yes, I got the email and sent the invite @Bonapara. Sorry for the delayed response !
