### ISSUE TITLE
[Serverless Functions]: Update environment variables in a dedicated tab in settings > Functions, not a .env file

### ISSUE THREAD

**Issue by martmull** [twentyhq/twenty#7415]
Why?
Updating a .env file is not a very common way to add and update environment variables

What?
We want to create a dedicated table in the serverless function detail view to CRUD env variables, and remove the .env file 
We can add a new tab, or add a new section in the setting tab
![Image](https://github.com/user-attachments/assets/7c100462-b05b-41cb-811a-1b3fa123f1ec)
![Image](https://github.com/user-attachments/assets/6904e07f-4df9-442f-b57c-59402f44a12d)
@Bonapara what do you think?

Technically, we could also store environment variables in a dedicated encrypted JSONb column in the metadata.serverlessFunction table and use that to store environment variables instead of a file

**Comment by Bonapara** [comment]
![image](https://github.com/user-attachments/assets/db9f818d-a6d0-4ae2-8f31-65c1b504de2f)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=36235-121089&node-type=frame&t=xVPIyU11BfC01eON-11

**Comment by martmull** [comment]
To do also
- move serverlessFunction from metadata to workspace_schema
- add a serverlessFunctionVersion table
