### ISSUE TITLE
Enable IPv6 Support for Redis Database Connections Over a Private Netwoork

### ISSUE THREAD

**Issue by AbdelrahmanAhmed605** [twentyhq/twenty#7421]
## Bug Description

When attempting to connect to a Redis database over a private network, I get the following error: `Error: getaddrinfo ENOTFOUND`. I think it is because currently the caching system utilizes BullMQ, which relies on ioredis internally, and ioredis by default is configured to work only with IPv4 addresses.

## Expected behavior

The expected behavior is for the `twenty-server` and `twenty-worker` to establish a successful connection to the Redis database over the private network, eliminating the `ENOTFOUND` error.

## Technical inputs
I think this would require a change in the connection options for `messageQueueModuleFactory` in [message-queue.module-factory](https://github.com/twentyhq/twenty/blob/a946c6a33de378c1cb6818efee8f0d891208ded7/packages/twenty-server/src/engine/core-modules/message-queue/message-queue.module-factory.ts#L43)

and possibly the socket properties for `cacheStorageModuleFactory` in [cache-storage.module-factory](https://github.com/twentyhq/twenty/blob/a946c6a33de378c1cb6818efee8f0d891208ded7/packages/twenty-server/src/engine/core-modules/cache-storage/cache-storage.module-factory.ts#L38)

**Comment by AbdelrahmanAhmed605** [comment]
I think that adding `family: 0` to the connection option allows both IPv4 and IPv6. I tried adding it to the `messageQueueModuleFactory` and it seems to work. I am not sure if anything needs to be done to the `cacheStorageModuleFactory` but just editing the `messageQueueModuleFactory` seemed to work for me :)

**Comment by Bonapara** [comment]
@ijreilly what do you think?

**Comment by ijreilly** [comment]
I have too limited knowledge on this, maybe @Weiko knows better?

**Comment by Weiko** [comment]
LGTM, thanks for the technical input. Feel free to open a PR 👍

**Comment by FelixMalfait** [comment]
<img width="723" alt="Screenshot 2024-10-14 at 22 05 49" src="https://github.com/user-attachments/assets/871929df-654e-4979-9df2-48b19ff84e5d">

I'm going to close this since no PR was raised and it's possible to pass the parameter through the url (see screenshot from the Railway docs for example). But feel free to raise one

**Comment by thomasmol** [comment]
While it's true that you can pass the parameter through the URL, Twenty does not expose env vars for connection urls for redis, only for the `HOST`, `PORT`, `USERNAME` and `PASSWORD`. Should an env var be added e.g. `REDIS_FAMILY` or add `REDIS_URL` ?

**Comment by FelixMalfait** [comment]
@thomasmol that's a good point - I didn't see that, we should probably replace REDIS_HOST, REDIS_PORT, REDIS_USERNAME, REDIS_PASSWORD by a single REDIS_URL param to be consistent with what we do on Postgres. Re-opening the issue, PR welcome :))
