### ISSUE TITLE
Error: Field "position" is not defined in "WorkspaceMemberOrderByInput".

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7427]
> [!Caution]
> - When accessing properites such as Accout owner, an error is thrown ` GraphQL Error "Field "position" is not defined by type "WorkspaceMemberOrderByInput"`
>  - This issue is seems related to issue #7426 

## Current behavior
https://github.com/user-attachments/assets/0e5566a7-5d92-4a65-8793-06dedbc386c8

**Comment by harshit078** [comment]
One possible approach to this issue can be that since we are trying to access `Position` field from `WorkspaceMemberOrderByInput` in graphQL schema which doesn't have Position defined in it. We can add `position?: InputMaybe<OrderByDirection>;` and keep it optional which will not log errors on both Sentry and Ts console.

**Comment by Utzig26** [comment]
I could work on it, please assign this issue to me

**Comment by FelixMalfait** [comment]
@harshit078 good catch. WorkspaceMember is a system object. We used to have something hardcoded to disable the links, I think that's what we should do for now. In the future we might be able to display the system objects within the app, but that will require backend work (right now not all fields on WorkspaceMember can be edited without consequence)

**Comment by FelixMalfait** [comment]
/award 1000
(for creating all the mobile issues + this one + all the PRs)

**Comment by FelixMalfait** [comment]
Looks like this has been fixed
