### ISSUE TITLE
Add an empty default value to the select components for trigger step in workflow visualizer

### ISSUE THREAD

**Issue by Devessier** [twentyhq/twenty#7432]
Currently, the selects show a value but they don't have one actually. We should have a default "None" value for these fields.

![image](https://github.com/user-attachments/assets/f72b6c9f-ea37-48e2-81a5-0d26808d61a1)

The file to update: https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/workflow/components/WorkflowEditTriggerForm.tsx.

Resources: 

- https://stackoverflow.com/questions/8605516/set-the-select-option-as-blank-as-default-in-html-select-element sent by @martmull

**Comment by Devessier** [comment]
/oss.gg 150

**Comment by manishsahanidev** [comment]
@HimanshuGaur14 Do you mind if I take this on? I'd like to contribute to this issue if it's not being actively worked on?

**Comment by manishsahanidev** [comment]
This is wrong @Devessier,
Brother @HimanshuGaur14 unassign himself and re-assign to bypass 48h time limit.

**Comment by FelixMalfait** [comment]
@manishsahanidev if you raise a PR first we'll merge it and give you the points :)

**Comment by HimanshuGaur14** [comment]
im sorry for this i was not able to setup the repo locally so i bypass the time limit ! i sincerely apologize for this ..

**Comment by AndrewHamal** [comment]
@Devessier where can i find this page in https://demo.twenty.com/

**Comment by AndrewHamal** [comment]
please help, I'm not able to find this workflow visualizer page.

**Comment by Devessier** [comment]
Hey @AndrewHamal,
I'm not sure whether this page is available on the live demo version. I would checkout the main branch and reset my local database. You should see the page on your local version of the app.

**Comment by AndrewHamal** [comment]
@Devessier even on the local version of the app, I'm unable to find this. can you please guide me.

**Comment by AndrewHamal** [comment]
> Hey @AndrewHamal, I'm not sure whether this page is available on the live demo version. I would checkout the main branch and reset my local database. You should see the page on your local version of the app.

@Devessier even on the local version of the app, I'm unable to find this. can you please guide me?

**Comment by Devessier** [comment]
@AndrewHamal 

1. Ensure you correctly reset your database and the `IsWorkflowEnabled` feature flag is set to `true` in the `packages/twenty-server/src/database/typeorm-seeds/core/feature-flags.ts` file.
2. Go to `localhost:3001`; you should see a "Workflows" link on the left sidebar. If not, go to `http://localhost:3001/objects/workflows`
3. Create a new workflow
4. Go to the workflow and click on the trigger node; you should see the same thing as the screenshot I shared on the description of the issue

![CleanShot 2024-10-19 at 20 08 07@2x](https://github.com/user-attachments/assets/21e0fa1e-6d14-4576-9bb9-0dde3bc1386c)

**Comment by AndrewHamal** [comment]
@Devessier please review this fast i want to work on other issues too.
