### ISSUE TITLE
Readme improvement

### ISSUE THREAD

**Issue by guillim** [twentyhq/twenty#7433]
## Scope & Context

**Documentation:** 
```
We want to l=Local Setup tutorial to be straightforward. At the moment, it is missing a redis command to be it.
```

## Current behavior

When following the `Local Setup` tutorial from the [online documentation](https://twenty.com/developers/local-setup#step-4:-set-up-a-redis-database-(cache)) there is a problem at step 7

**Logs:** 
```
Warning: command "nx command-no-deps -- cache:flush" exited with non-zero status code
[...]
Error: connect ECONNREFUSED 127.0.0.1:6379
```

## Expected behavior
A clean install

**Example:** 
```
 NX   Successfully ran target command-no-deps for project twenty-server (32s)
```

**Comment by FelixMalfait** [comment]
Thanks for the report :)
What change would you suggest?  I didn't get what was missing. The command to start the redis server after you've installed it maybe?

**Comment by guillim** [comment]
I created a PR with the suggested change

**Comment by FelixMalfait** [comment]
Oh great thanks @guillim!
