### ISSUE TITLE
Add the structure of the authentication callback url in the documentation 

### ISSUE THREAD

**Issue by voslucas** [twentyhq/twenty#7442]
The self-hosted documentation shows example of the Google and Microsoft authentication configuration. 
But it is unclear what the structure of the callback url should be (as it depends on the codebase / controller that receives the callback)

After some digging i found that it is https:// site-url/auth/[provider]/redirect  
Provider being either microsoft or google. But, as far as i see, this is never mentioned anywhere in the documentation.

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by Bonapara** [comment]
Oss.gg -> Reproduce and enrich the documentation with the appropriate explanations

**Comment by NitinPSingh** [comment]
i had made this changes , if its fine I can create pr

![Screenshot 2024-10-07 172140](https://github.com/user-attachments/assets/da3f62d2-68b5-4e28-a038-819463c6ea46)

**Comment by Bonapara** [comment]
@charlesBochet does it look right to you?

**Comment by RajuGangitla** [comment]
@NitinPSingh are you still working on this one

**Comment by NitinPSingh** [comment]
@RajuGangitla I have completed it just waiting to create PR

**Comment by RajuGangitla** [comment]
@NitinPSingh whenever you are working on issue make sure you are commenting "/assign" 
Then it's assigned to yourself

**Comment by RajuGangitla** [comment]
@NitinPSingh I'm unassign myself 
Assign yourself

**Comment by charlesBochet** [comment]
LGTM :) Please open a PR if you want :)

**Comment by charlesBochet** [comment]
There seems to be a bug with this ticket and oss.gg
This ticket has already been closed and rewarded

**Comment by ShantanuGaur26** [comment]
@charlesBochet  is it rewarded to me?
since my pr got accepted

**Comment by charlesBochet** [comment]
it should be, haven't you got the points?

**Comment by ShantanuGaur26** [comment]
Not yet

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/5dfe3c67-06fe-488d-8a4f-d829c83762c9">

**Comment by charlesBochet** [comment]
Mmh ok, seems the bot get lost on this issue. Please assign yourself on: https://github.com/twentyhq/twenty/issues/7629
