### ISSUE TITLE
Minor bug in column scroll in mobile viewport

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7447]
## Bug Description

- When scrolling across the columns, the first letter of the input often gets displayed which hinders the design.
- Text input container when clicked outside and opened again in right Drawer makes the text  in ellipsis fashion even when text is small.

## Current Behaviour

https://github.com/user-attachments/assets/8ad1fa47-07a8-4dd5-8431-6246e7ad932d

https://github.com/user-attachments/assets/d5e947d6-b7d7-40a0-af85-9854a094c7bd

## Expected behavior

https://github.com/user-attachments/assets/94f113e1-dbf2-4551-b243-a25d6844c132

https://github.com/user-attachments/assets/791b83c1-9a12-4937-a11e-5f45dab1bcf6

**Comment by FurquanAnwer** [comment]
Please assign this to me

**Comment by charlesBochet** [comment]
Hi @FurquanAnwer, @harshit078 already has raised a PR about it

@harshit078 thanks for creating such a clear issue, taking a look at your PR
