### ISSUE TITLE
Drop typeorm_metadata / generated columns

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#7453]
When introducing the new vector search, we used`generated columns` in Postgres for the first time
TypeORM created a table called `typeorm_metadata` to handle this concept which is ugly and is probably similar to what we could want to do in our own metadata layer. 
We should maybe look at implementing generated columns at the raw sql layer and avoid using typeorm for that?

**Comment by FelixMalfait** [comment]
Discussed with @Weiko, maybe we just want to leverage `TYPEORM_MIGRATIONS_TABLE_NAME` to rename the table from `typeorm_metadata` to `_typeorm_generated_columns_and_materialized_views` (very long but at least it's explicit that it's just about that and it begins with a `_` to show it's a technical table like `_typeorm_migrations`)

**Comment by Weiko** [comment]
cc @ijreilly
