### ISSUE TITLE
Connecting a New Mailbox crashing server

### ISSUE THREAD

**Issue by jackbeeby** [twentyhq/twenty#7454]
## Bug Description

I am attempting to link the google mailbox and calendar to a self hosted instance 0.31 using docker latest tag. When clicking the google button to link in settings it performs a redirect however this action immediately crashes the server and no other page loads. It reactivates after 30 sec however this function is unable to be completed. 

## Expected behavior

Correct dialogues should come up to sign into google account and the server should not crash. 

## Technical inputs

I have used the docker environment and compose files provided with an acceptation being removing the change-vol-ownership services due to initialisation issues and being unnecessary on my instance. Also using custom volume paths to my desired directories however all files are saving correctly, database also functions as expected.

**Comment by Bonapara** [comment]
@ijreilly what do you think?

**Comment by ijreilly** [comment]
@bosiraphael @Weiko any idea?

**Comment by Weiko** [comment]
What's the error on your server logs? Have you correctly configured your AUTH_GOOGLE env variables to match with your google api client?

**Comment by jackbeeby** [comment]
@Weiko 

I have all the AUTH_GOOGLE env enabled correctly as per (packages/twenty-server/.env.test). I have enabled the gmail API on my google cloud portal and inserted the OAuth 2.0 Client IDs and secret into the corresponding env variables. I have declared them in the .env and then declared in the docker compose worker environment section as  AUTH_GOOGLE_ENABLED: ${AUTH_GOOGLE_ENABLED} for each of the below.

Probably an issue on my end however I wanted to report for documentation purposes or incase it is a bug, mostly the former. Am I missing something here

AUTH_GOOGLE_ENABLED=true
MESSAGING_PROVIDER_GMAIL_ENABLED=true
CALENDAR_PROVIDER_GOOGLE_ENABLED=true
AUTH_GOOGLE_CLIENT_ID=**
AUTH_GOOGLE_CLIENT_SECRET=**
AUTH_GOOGLE_APIS_CALLBACK_URL=**
AUTH_GOOGLE_CALLBACK_URL=**

### Logs for crash
twenty-latest-server-1  | UnauthorizedException: Google apis auth is not enabled
twenty-latest-server-1  |     at AuthRestApiExceptionFilter.catch (/app/packages/twenty-server/dist/src/engine/core-modules/auth/filters/auth-rest-api-exception.filter.js:28:23)
twenty-latest-server-1  |     at ExceptionsHandler.invokeCustomFilters (/app/node_modules/@nestjs/core/exceptions/exceptions-handler.js:33:26)
twenty-latest-server-1  |     at ExceptionsHandler.next (/app/node_modules/@nestjs/core/exceptions/exceptions-handler.js:13:18)
twenty-latest-server-1  |     at /app/node_modules/@nestjs/core/router/router-proxy.js:13:35
twenty-latest-server-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
twenty-latest-server-1  |   response: {
twenty-latest-server-1  |     statusCode: 401,
twenty-latest-server-1  |     message: 'Google apis auth is not enabled',
twenty-latest-server-1  |     error: 'Unauthorized'
twenty-latest-server-1  |   },
twenty-latest-server-1  |   status: 401,
twenty-latest-server-1  |   options: {}
twenty-latest-server-1  | }
twenty-latest-server-1  | 
twenty-latest-server-1  | Node.js v18.17.1
twenty-latest-server-1 exited with code 0

**Comment by obcydianshard** [comment]
Encountered the same exact issue, config and error are the same.

**Comment by Weiko** [comment]
Can confirm that adding those 2 env variables should fix the issue. `Google apis auth is not enabled` error should only be thrown when it's not the case.
