### ISSUE TITLE
Settings card inconsitent for mobile viewports

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7457]
## Bug Description

- In Settings/Accounts, the Settings card is inconsitent for mobile viewports and its width changes.
- It should be consistent across all ports

## Current Behaviour
<img width="430" alt="Screenshot 2024-10-07 at 11 43 17 AM" src="https://github.com/user-attachments/assets/4b757e19-94f7-4ed3-917e-faae040a00e0">
<img width="394" alt="Screenshot 2024-10-07 at 11 43 28 AM" src="https://github.com/user-attachments/assets/9b5a67a3-4642-410c-9ec4-23b49e50be46">

## Expected behavior

<img width="308" alt="Screenshot 2024-10-07 at 11 43 45 AM" src="https://github.com/user-attachments/assets/706931a8-42ed-4fee-b3a4-e6a50aaea70f">

**Comment by Bonapara** [comment]
Hi @harshit078, thanks for pointing this out! On mobile devices, the cards  should display in a column, one above the other.

**Comment by harshit078** [comment]
@Bonapara makes sense, This is on me then !

**Comment by ASANIYAN** [comment]
I am new here but I would love to contribute to the project.
Can you assign this to me?

We need each card to be display in a column for mobile devices right?
