### ISSUE TITLE
Currency Field Trims Input at First Comma

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7458]
# Bug description

The currency field type trims the input values to what appears before the first comma. For instance, if I try to enter `400,000` only `400` will be saved and displayed.

https://github.com/user-attachments/assets/08159ac6-c426-4eb2-aa8b-bc0aa40db986

**Comment by harshrajeevsingh** [comment]
Hey @Bonapara I fixed this. Please assign it to me.

**Comment by Bonapara** [comment]
@harshrajeevsingh, you can open a PR, but I can't assign it because we need to fix it today for the release. The core team plans to handle it.

**Comment by Bonapara** [comment]
Thanks for contributing!
