### ISSUE TITLE
Release 0.31

### ISSUE THREAD

**Issue by ijreilly** [twentyhq/twenty#7459]
🎈
- [x] Search
- [x] Advanced settings 

Other topics
- [ ] https://github.com/twentyhq/twenty/pull/7162
- [x] https://github.com/twentyhq/twenty/pull/7418 (check REST API too)

**Comment by charlesBochet** [comment]
Additional PR we would like to include before merge:
- https://github.com/twentyhq/twenty/pull/7162
- https://github.com/twentyhq/twenty/pull/7418 (check REST API too)
