### ISSUE TITLE
Settings Error Layout: Add White Container and Breadcrumb

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7460]
# Current behavior

Errors in the Settings display without a white container.

![image](https://github.com/user-attachments/assets/8202258b-df0e-45cd-938c-2d3daae3928a)

# Desired Behavior

They should use the Settings layout, add the white container, and include a page in the breadcrumb where the issue occurred.

![image](https://github.com/user-attachments/assets/038f6bdf-0b7c-4d06-a0e3-b1531b410fe2)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=41919-62168&node-type=frame&t=brJpLaLaOW2WXqgH-11

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by NinaVincova** [comment]
Hi. It is possible to work on this issue? I would like to try. :)

**Comment by Bonapara** [comment]
Hi Nina, sure! Assigning you. Thanks for contributing.

**Comment by ppmpreetham** [comment]
Hi! is it possible that I could work on this issue? I would like to try too :D

**Comment by Bonapara** [comment]
@ppmpreetham @NinaVincova is working on it. Let's wait a few days for her to raise a PR.

**Comment by NinaVincova** [comment]
Hello, I had some problems with the  installation. Someone else can proceed with this issue. Thank you <3

**Comment by lucasbordeau** [comment]
@Bonapara Breadcrumb is too complex to develop, I think we should just stick to UI improvements here.
