### ISSUE TITLE
While setup project on local - permissions error in Postgres provisioning script

### ISSUE THREAD

**Issue by Karankhatik** [twentyhq/twenty#7468]
While running the **make postgres-on-linux** command, which executes the script at /twenty-postgres/linux/provision-postgres-linux.sh, I encountered a permissions error during the following line:

cp ./init.sql /tmp/init.sql

![image](https://github.com/user-attachments/assets/6549b057-c338-4889-8d8f-783920a2ae86)

Also a minor code improvement on this file that we don't need **su** there, its unneccessary:

![image](https://github.com/user-attachments/assets/961d40af-631c-4145-a179-69b375b6c505)

Machine description:
Distributor ID:  Ubuntu
Description:  Ubuntu 24.04.1 LTS

**Comment by Bonapara** [comment]
@Weiko what do you think?

**Comment by BOHEUS** [comment]
@Karankhatik are you sure you're running newest version of Twenty? I've made changes to this file a month ago and I deleted this unnecessary `su` command https://github.com/twentyhq/twenty/pull/6819

**Comment by Karankhatik** [comment]
@BOHEUS Thanks I noticed that my forked repository is not in sync with the main repository. now its sync.

I deleted the database, remove everything and did a fresh installation, but I encountered a "permission denied" error because the command cp ./init.sql /tmp/init.sql didn't include sudo. After adding sudo, the error was resolved.

Should I push this change, or is it likely that only I encountered this error?

**Comment by BOHEUS** [comment]
It's like that only you have encountered this error as there were no issues related to error while copying to `tmp/` directory, I don't think you should push this change as `tmp/` by default should allow all users write to it (despite `root` being the owner of the folder https://unix.stackexchange.com/questions/71622/what-are-correct-permissions-for-tmp-i-unintentionally-set-it-all-public-recu)

**Comment by Karankhatik** [comment]
Thanks @BOHEUS for letting me know. I m closing this issue.
