### ISSUE TITLE
Short highlight for links in Developers category in Settings

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7477]
**Scenario:**
1. Log in
2. Go to Settings
3. Turn on Advanced settings
4. Hover on API & Webhooks

**Actual:** Links in Developers category have shorter highlight compared to other links in Settings
[Screencast From 2024-10-07 18-51-05.webm](https://github.com/user-attachments/assets/3901cd02-6c9b-47b7-934a-97b25392e668)

**Expected:** All links in Settings must have the same length of highlight

**Comment by Karankhatik** [comment]
@BOHEUS  can u please assign this issue to me.

**Comment by BOHEUS** [comment]
I'm closing this as all links in Settings now have the same width in highlight
![image](https://github.com/user-attachments/assets/9f09196b-5350-4fd4-834e-71ac6ea3cdfb)
