### ISSUE TITLE
Typo in Settings > Advanced > API & Webhooks > webhook details

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7478]
**Scenario:**
1. Log in
2. Go to Settings
3. Turn on Advanced settings
4. Go to API & Webhooks > webhook details
5. Click on first dropdown in Filters section

**Actual:** There is `Api key` option
![image](https://github.com/user-attachments/assets/a35b0fd2-11ba-410b-b1eb-cd9951a36e79)

**Expected:** There must be `API key` option

**Comment by Smnthjm08** [comment]
can i work on this @BOHEUS
