### ISSUE TITLE
[🕹️] oss.gss no-code quest: Create a "new" logo for twenty 

### ISSUE THREAD

**Issue by adityadeshlahre** [twentyhq/twenty#7479]
### Points : 300

- [x] logo tweet link https://x.com/adityadeshlahre/status/1843354963176718374

![13](https://github.com/user-attachments/assets/972e54f1-e7a0-4ddf-bb1a-6264d2b7be12)
![12](https://github.com/user-attachments/assets/f65eb047-31a6-4685-b6d8-14a2330fe464)
![11](https://github.com/user-attachments/assets/00c2eeba-5d00-463f-921b-922fdfbfe73a)
![10](https://github.com/user-attachments/assets/8b13653e-4e86-41c5-ba69-d6501800a7e2)
![9](https://github.com/user-attachments/assets/2e32b214-d5f0-4cad-97dc-b80a6eea373f)
![8](https://github.com/user-attachments/assets/63f21033-bc0d-46cb-8739-4444cd1b9066)

- i have all the canav template if any changes needed lmk

Thank You :slightly_smiling_face:

**Comment by Bonapara** [comment]
What Tool did you use @adityadeshlahre? Thanks for the logos!

**Comment by Bonapara** [comment]
/oss.gg 300

**Comment by adityadeshlahre** [comment]
> What Tool did you use @adityadeshlahre? Thanks for the logos!

**Canva**

**Comment by Bonapara** [comment]
Did you open a related pr so I can grant the points?

**Comment by adityadeshlahre** [comment]
> Did you open a related pr so I can grant the points?

doing it RN
