### ISSUE TITLE
[Storybook Testing] Fix NavigationDrawer story

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#7492]
## Context

This issue is part of a Storybook effort on the project. You will find more context and guidance in the main issue: https://github.com/twentyhq/twenty/issues/7491

## What

Fix the following existing story: `/story/ui-navigation-navigationdrawer-navigationdrawer--default`

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/d51c3e93-7cbc-4c5d-81ff-68b87f03dc56">

**Comment by charlesBochet** [comment]
/oss.gg 150

**Comment by sateshcharan** [comment]
@uluckydev you can attempt this now if you are still interested !

**Comment by uluckydev** [comment]
I tried running the storybook with `npx nx run twenty-front:storybook:serve:dev --configuration=modules` command. The frontend getting stopped and the frontend is not working. Any idea how can i fix that for dev environment?

**Comment by sateshcharan** [comment]
@uluckydev only storybook will start with limited config will start for npx nx run twenty-front:storybook:serve:dev --configuration=modules you can access it at port 6006

**Comment by uluckydev** [comment]
@sateshcharan I tried it. It is running on the first time but when I am going to NavigationDrawer story the frontend stopped responding.

**Comment by uluckydev** [comment]
https://github.com/user-attachments/assets/49accf5e-5388-4e3a-8e59-779330c4fe1d
hey @sateshcharan 
Please refer to this video, I even tried the --verbose. Do you think it can happen because of the codespace?

**Comment by sateshcharan** [comment]
> https://github.com/user-attachments/assets/49accf5e-5388-4e3a-8e59-779330c4fe1d hey @sateshcharan Please refer to this video, I even tried the --verbose. Do you think it can happen because of the codespace?

 it probably is, try local dev it worked for me

**Comment by TakuyaKurimoto** [comment]
@charlesBochet 
I have created a PR. I would appreciate it if you could take a look when you have time.
https://github.com/twentyhq/twenty/pull/9235
