### ISSUE TITLE
Improve command menu object list

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#7503]
## Scope & Context

In the command menu

## Current behavior

<img width="506" alt="image" src="https://github.com/user-attachments/assets/86d9a25f-db92-4640-91cc-6a248090bb4e">

We have a list of objects : 
- The shortcuts for object with the same first letter are conflicting
- Settings seems to be an object and is not sorted alphabetically which seems odd

## Expected behavior

@Bonapara  ?

**Comment by Bonapara** [comment]
I think we should keep them for `Standard Objects` for now and think of our global shortcut strategy later. WDYT?

**Comment by FelixMalfait** [comment]
Agree let's keep shortcuts on standards objects only, but display all objects in command bar 👍

**Comment by FelixMalfait** [comment]
/oss.gg 150

**Comment by ketanMehtaa** [comment]
@lucasbordeau How to create Go To Atest1s

**Comment by Bonapara** [comment]
By pressing `⌘K` or clicking the search button in the sidebar @ketanMehtaa

**Comment by ketanMehtaa** [comment]
@Bonapara my question was , I am not able to see Go to atest1 , go to atest2 , go to atest3 in command menu
