### ISSUE TITLE
New Kanban View -> Redirect to new-field step 2

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7505]
# Current behavior

When creating a `kanban` view on an object that doesn't have any `Select` field, I'm redirected to the Settings. This redirection goes to `https://app-main.twenty.com/settings/objects/OBJECT/new-field/step-2?fieldType=SELECT` but step-1 is displayed.

![CleanShot 2024-10-08 at 16 34 30](https://github.com/user-attachments/assets/916753fa-646e-4d2f-bf2e-2a24add55e6e)

https://github.com/user-attachments/assets/2ad55907-2b2d-4cdd-baed-56e8b785aa06

# Desired Behavior

Show step 2 with the "Select" field type pre-selected.

**Comment by ehconitin** [comment]
Yep!
