### ISSUE TITLE
Trigger Github CIs only if related files have changed

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#7508]
## Scope & Context

Twenty CIs are stored and run as Github Actions (located in the `.github/workflows` folder). They are conditionally run depending on modified files.

Right now, these conditions are expressed in github action triggers (ex: paths: - 'package.json'). This is an issue because we would like all CIs to be **VALID** before merging but a non-run CI is not considered as valid.

What we would like is to run ALL CI (remove condition on trigger), but to skip it and return it as **VALID** when there is no need to run it because the files are not related.

## How

For each CI in .github/workflows`:
- Implement https://github.com/tj-actions/changed-files step
- Move the condition from the trigger.xxx.paths section to changed-files, if the condition is met run the steps, if not return **VALID**

**Comment by charlesBochet** [comment]
/oss.gg 300

**Comment by yadavshubham01** [comment]
hey @charlesBochet I want to work on this issue

**Comment by yadavshubham01** [comment]
hey @charlesBochet please checkout this PR #7828

**Comment by charlesBochet** [comment]
Thanks @yadavshubham01
