### ISSUE TITLE
Trim Names in Settings > Members table

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7509]
# Desired behavior

Long values should be trimmed with ellipses in the Settings/Members table.

![28cf3be7396f37107a861ae99655972982f93cb675012575c575e26fa05b110e](https://github.com/user-attachments/assets/db77f37f-3d60-4e43-bee7-8f4b9196b410)

**Comment by Karankhatik** [comment]
Please assign this issue to me.

**Comment by Bonapara** [comment]
Sure @Karankhatik, thanks for contributing!

**Comment by SyedHamzaHussain000** [comment]
\assign

**Comment by AnubhavSingh99** [comment]
\assign

**Comment by Karankhatik** [comment]
close

**Comment by Karankhatik** [comment]
@Bonapara can u please close this issue as this is merged successfully.

**Comment by Bonapara** [comment]
Sure, thanks @Karankhatik
