### ISSUE TITLE
Issue with Email Validation and API Call Trigger on Login

### ISSUE THREAD

**Issue by Karankhatik** [twentyhq/twenty#7510]
## Bug Description

Explanation:

1. **Email Validation Not Strict Enough:** The current system allows invalid email formats, causing the API to be triggered unnecessarily. The system should only send API requests when the email input matches a valid email format.
2. **Password Field Displayed Even for Non-existent Users:** After the API returns a "user not found" message, the password input field still appears, which is misleading.
3. **Sign-up Button Disabled Despite Invalid State:** Even though the user doesn't exist, the sign-up button remains disabled, which should be enabled to encourage user registration.

**The issue was tested across Brave, Chrome, and Firefox, indicating it is system-specific and not related to browser differences.**

[twentylogin-bug.webm](https://github.com/user-attachments/assets/77f60581-387b-4c4b-96ec-0dce6b3f0d6a)

**Comment by Karankhatik** [comment]
@Bonapara Please give me the green flag to work on this issue. Thank you!

**Comment by Bonapara** [comment]
Hi @Karankhatik, thanks for raising this issue! I understand points 1 and 2, but not point 3. The button is expected to remain disabled while the fields are incomplete. What would you suggest?

**Comment by Karankhatik** [comment]
Even when the fields are filled, like with an invalid email and a password, it can be misleading.

The correct flow should be:
1. Strictly validate the email format.
2. Call the API to check if the input email corresponds to a registered user. If the user exists, display the password field; otherwise, show a toaster notification that the user or email does not exist.
3. Finally, show the "Sign In" button, which should remain disabled until the user enters a valid password.

Please let me know your thoughts!

**Comment by Bonapara** [comment]
The behavior we have today is that if the email entered in step 1 is not recognized as a user, the flow redirects to the sign-up page. We use the same process for both sign-in and sign-up use cases. So we should not implement 2) & 3)

But we can implement 1) -> Strictly validate the email format then go to the second step that sounds like a great idea!

**Comment by Karankhatik** [comment]
sure I will work on this.

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by Khaan25** [comment]
@charlesBochet Can I work on this please?

**Comment by Khaan25** [comment]
@FelixMalfait Can I work on this please?

**Comment by Bonapara** [comment]
Replacing this issue by https://github.com/twentyhq/twenty/issues/7967 to clear the discussion output. Thanks @Karankhatik for opening it. @Khaan25 comment the issue if you still want to handle it.
