### ISSUE TITLE
Search results flash

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7511]
# Current Behavior

The search results "flash" when I type a new character.

https://github.com/user-attachments/assets/8cacd6b5-86c7-46fc-9d5d-8227e60a31e3

# Desired Behavior

The content should remain stable and not flash.

**Comment by zsskar** [comment]
Hey , I would like to work on this issue.

**Comment by Bonapara** [comment]
Sure @zsskar, thanks for contributing!

**Comment by Vardhaman619** [comment]
Hello @Bonapara Can I work on this issue ?

**Comment by Vardhaman619** [comment]
@Bonapara Can I work on this issue ?

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by Bonapara** [comment]
Yes @Vardhaman619, unassigning you @zsskar as you didn't open a PR :)
