### ISSUE TITLE
Tasks page overflows on Adding a task

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7516]
## Bug Description

- When added a task, the page overflows. This behaviour is not connected to task title or body but creating a task makes the page scroll.

## Current behavior

https://github.com/user-attachments/assets/bce2aa99-9c78-4d38-a84e-1aa1472bd7b7

## Expected behaviour

https://github.com/user-attachments/assets/07afcd1b-e508-4347-9076-d92f5292a220

**Comment by govindplal** [comment]
I can work on this. Can you assign me?

**Comment by Bonapara** [comment]
Sure @KartikDevarde2601, thanks for contributing!

**Comment by Bonapara** [comment]
Sorry @govindplal and @KartikDevarde2601, @NitinPSingh is already on it. Maybe can you grab another [Good First Issue](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)? Thanks.
