### ISSUE TITLE
Add cache-flush step in Twenty upgrade command

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#7521]
## Scope & Context

`upgrade-x.xx` commands can sometimes bring migrations to the data model and now that the default cache is redis and persistent we need to make sure to clear it by the end of the command.

## Current behavior

Cache needs to be flushed after we run the upgrade command

## Expected behavior
Cache flush should be part of the global command

## Technical inputs

A command already exists (see FlushCacheCommand) and can be directly added but it's flushing the whole cache. While this could be fine like this, I think we only want to remove keys that follow that pattern `engine:*` and not interact with the rest (bull, module, ...). This command could be updated to take an optional parameter for that purpose.

**Comment by yadavshubham01** [comment]
i can work this issue

**Comment by yadavshubham01** [comment]
@Weiko 
please checkout this pr #7553
