### ISSUE TITLE
Turn off autocomplete / password managers on editable fields

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#753]
The first name field (and maybe others?) seem to be detected by 1Password.
Haven't tried other password managers to see if there was a similar.

Based on what I read, adding `autocomplete="off"` to the field should suffice, but I haven't tried it.

<img width="226" alt="Screenshot 2023-07-19 at 18 05 41" src="https://github.com/twentyhq/twenty/assets/6399865/a25e063a-962b-4385-8b0a-c8d108355b63">

**Comment by gfr2003** [comment]
Hello, I really liked the project and I want to contribute to solve this problem, has anyone already started the development?

**Comment by FelixMalfait** [comment]
Thanks a lot @gfr2003! I've assigned you to the issue

**Comment by AdityaPimpalkar** [comment]
Hi @FelixMalfait, can I take this up? Thanks!
