### ISSUE TITLE
Hide tasks everywhere when deactivated

### ISSUE THREAD

**Issue by x3mp** [twentyhq/twenty#7548]
## Current behavior
Currently when you have disabled the tasks object it'll still show up in the view and allow you to create new tasks. This creates a lot of confusion.

**Example:** 
![image](https://github.com/user-attachments/assets/7e6260d0-3598-4202-840b-1e74bd3c0a4e)
Image shows that the task object is inactive.

![image](https://github.com/user-attachments/assets/730fbe37-63d0-40cf-bf4f-5507478a5ab7)
Image shows that the tasks field is inactive.

![image](https://github.com/user-attachments/assets/f3639077-6a3b-4512-aa79-ffb8d9a43ade)
Image shows that the tasks still show on record view even though the tasks object and fields have been disabled.

## Expected behavior
The tasks tab is not visible in the record view if the task object is disabled. It'll remove the confusion. 
A tab should not be shown if it's respective parent is disabled. Same goes the for the Notes tab.
![image](https://github.com/user-attachments/assets/18612e69-ea08-41aa-b783-0d4f6419ecb7)

**Comment by Bonapara** [comment]
This is definitely something we will do, @x3mp. Thanks for raising the issue. But I think we want to have a clearer vision on custom layouts to avoid introducing a poor product strategy there.

**Comment by x3mp** [comment]
> This is definitely something we will do, @x3mp. Thanks for raising the issue. But I think we want to have a clearer vision on custom layouts to avoid introducing a poor product strategy there.

Good point, being able to freely customize the record page is (in my personal opinion) a highly valuable addition. It'll also be a way better implementation.

However, in terms of "Quick wins" wouldn't this be a short term improvement?

**Comment by Bonapara** [comment]
We try to avoid implementing "hard-coded" features that we will later remove to prevent technical debt, but I'll keep this in mind in case we find a smart way to implement it!

**Comment by ehconitin** [comment]
@FelixMalfait this could be closed now?

**Comment by FelixMalfait** [comment]
Sure thanks!
