### ISSUE TITLE
Blocklist table overflows in long emails

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7549]
## Bug Description

- Blocklist Table in Settings is not optimised for Long emails
- Long emails should not affect the other column

## Current Behaviour
<img width="389" alt="Screenshot 2024-10-10 at 3 42 15 PM" src="https://github.com/user-attachments/assets/86bf6876-9421-4f42-8589-ff209b6d2712">

<img width="329" alt="Screenshot 2024-10-10 at 3 42 35 PM" src="https://github.com/user-attachments/assets/aec79bc4-aa3f-4ea3-8973-ba34b9940bda">

## Expected behavior

<img width="376" alt="Screenshot 2024-10-10 at 3 41 42 PM" src="https://github.com/user-attachments/assets/fb68cb92-e23e-4668-8ef8-fa1e5219ea78">

**Comment by harshit078** [comment]
@Bonapara, I'll take this up

**Comment by Bonapara** [comment]
Thanks @harshit078!
