### ISSUE TITLE
Settings Navigation drawer crops elements

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7550]
## Bug Description

- The current navigation drawer clips the  search icon and Toggle containers as they are not shown in mobile viewport.
- In mobile, the navigation drawer feels too close to left margin and a little bit of spacing would be ideal

## Current Behaviour

<img width="574" alt="Screenshot 2024-10-10 at 11 38 03 AM" src="https://github.com/user-attachments/assets/94aa184f-8abc-47d5-8a7b-228041aae72e">

## Expected behavior

- Approach 1.
<img width="444" alt="Screenshot 2024-10-10 at 11 43 14 AM" src="https://github.com/user-attachments/assets/e25c34ea-65b1-4b5a-a9fc-690a5a6e184e">

-  in the traditional approach, the column looks too far from the left border

- Approach 2.
<img width="435" alt="Screenshot 2024-10-10 at 11 51 38 AM" src="https://github.com/user-attachments/assets/722f103e-86f1-497f-88a9-c9cfe472fc36">

https://github.com/user-attachments/assets/949fa136-c6d4-4799-aa0d-2d47c46ad708

Along with animation, this approach could be improvised.

**Comment by harshit078** [comment]
@Bonapara, whats your take on this ?

**Comment by Bonapara** [comment]
Approach 1 looks great! Thanks @harshit078
