### ISSUE TITLE
Wrap Long text fields (textarea)

### ISSUE THREAD

**Issue by x3mp** [twentyhq/twenty#7552]
## Current behavior

Currently, there is no long text fields in which you could add some more information about a problem (task for example). You can add normal text fields but text isn't shown fully. Only on hover, which by design is pretty bad UI/UX.

Default:
![image](https://github.com/user-attachments/assets/c68b2798-2ca1-44cd-ac65-fef10dd20cbd)

On hover:
![image](https://github.com/user-attachments/assets/b820f44c-1932-4f0a-b15e-9e4f8a8db0b4)

## Expected behavior

A textarea field as implemented in (for example) salesforce. While, still remaining the ability to filter on long text fields (not possible in salesforce, so a huge win in my eyes).

How it would look
![image](https://github.com/user-attachments/assets/e57b7cda-693e-4c75-bc81-e9a265a09f00)

Also supports (shift+enter) newlines for better readability.
![image](https://github.com/user-attachments/assets/79e94510-ca7a-48d1-98ac-47ee7224d05a)

This will be very nice when being able to customize your own record pages.

## Technical inputs
No clue to be honest, just throwing the idea out there.

**Comment by Bonapara** [comment]
I think this is the option to "wrap" content, similar to what Notion offers.
![image](https://github.com/user-attachments/assets/2b14b71a-6dee-476b-aa69-19cf06734f6c)

**Comment by Bonapara** [comment]
Should Wait Custom Layouts to work on this

**Comment by FelixMalfait** [comment]
Let's do this as an option to the field type.
E.g. Type = Single-Line vs Multi-Line, and Display Line Count = 2 to +infty

**Comment by Bonapara** [comment]
![image](https://github.com/user-attachments/assets/d4d63d5f-8855-42a3-baf1-22cb1a19d4d1)

![image](https://github.com/user-attachments/assets/57b93025-0aa5-4243-9e45-47d17816ff7a)

After some Figma tests, I think a single setting could do the job, @FelixMalfait.

**Comment by Bonapara** [comment]
![CleanShot 2024-11-14 at 14 43 00](https://github.com/user-attachments/assets/1c0f7c22-de6b-41f8-af7b-3ca63d54aff3)

Let's not implement the `All lines` option to prevent excessive scrolling before reaching the field below.

**Comment by Bonapara** [comment]
> [!WARNING]
> Final design

### Menu 

![CleanShot 2024-11-14 at 14 54 11](https://github.com/user-attachments/assets/48ba362d-712f-4a11-8b8c-8961074511b7)

All Lines should be 99 lines.

### Updated Wording

![CleanShot 2024-11-14 at 14 57 49](https://github.com/user-attachments/assets/fb421418-7607-4759-aca1-3c4d175886bf)
