### ISSUE TITLE
Settings Nav item doesn't stay selected 

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7573]
# Bug description

When clicking on a webhook, the `api & webhooks` menu item loose its selection

https://github.com/user-attachments/assets/c775cbf9-4e8c-4f3c-a43a-8ddcb4ee2523

# Desired Behavior

Should keep its selection like when navigating the data model settings

**Comment by AryanK1511** [comment]
@Bonapara , I can pick this one up

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by Bonapara** [comment]
Sure @AryanK1511, thanks for contributing!

**Comment by sow-coding** [comment]
One line of code, the navigationDrawerItem component must take matchSubPages = true as a prop

**Comment by AryanK1511** [comment]
@Bonapara Are you able to assign this issue to someone else as I am having a lot issues trying to run this locally
