### ISSUE TITLE
Add role="button" to navbar search

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7575]
# Current behavior

The search button is using a `div`

![CleanShot 2024-10-10 at 17 44 13](https://github.com/user-attachments/assets/8baf68e5-809d-4ed9-b8fe-42b3f0154700)

# Desired Behavior

It should use a role="button"

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by Neeraj-2525** [comment]
/oss.gg 150

**Comment by Preetibansal08** [comment]
```

``` unassign

**Comment by Preetibansal08** [comment]
ok so why I get notification related to that issue

**Comment by Bonapara** [comment]
@Preetibansal08 
![Uploading CleanShot 2024-10-16 at 18.06.18.png…]()

**Comment by Khaan25** [comment]
Hey @Bonapara, It's been a week for this issue, I would love to contribute to this? My other PRs are under review

**Comment by Bonapara** [comment]
@Saksham-garg just unassigned you as it's been two weeks. @Khaan25 sorry but n
[DivyanshuLohani](https://github.com/DivyanshuLohani) already opened a PR

**Comment by Khaan25** [comment]
Right. but the one who get's assigned is gonna work on it :)

**Comment by Aashana101** [comment]
@Bonapara kindly assign this to me. I would like to contribute to it

**Comment by Khaan25** [comment]
@Bonapara Can I work on this? It's simple and can be done in few minutes

**Comment by Bonapara** [comment]
It's already fixed @Khaan25

**Comment by Khaan25** [comment]
Perfect. Great to hear.

**Comment by Aashana101** [comment]
kindly assign this task to me. I would be grateful to contribute to this task
