### ISSUE TITLE
The failure of Google Auth displays "Status: 401" on screen

### ISSUE THREAD

**Issue by Kiran-pande-30** [twentyhq/twenty#7584]
## Bug Description

If the user tries to log in using Google Auth, and in the process if he cancels the selected email. The status 401 displayed on the screen.

Video Link: 
https://github.com/user-attachments/assets/cdefbbed-1116-4dcc-a4b2-eeb56be7b8f0

## Expected behavior

After the cancellation of the login process, the user should see "try with different account" or the login page to try out another email Id.

## Technical inputs

We can redirect the cancellation process to desired location.

**Comment by Pushpender1122** [comment]
I would like to work on intersecting issues. Please assign this task to me.

**Comment by Kiran-pande-30** [comment]
Hello maintainers, I would love to work on this issue

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by Kiran-pande-30** [comment]
Why this issue is not assigned to me?

**Comment by Bonapara** [comment]
Since three of you requested before I added the oss.gg tags, I didn't want to choose between you, so I let speed decide @Kiran-pande-30!

**Comment by Bonapara** [comment]
I'll soon create some other [Good First Issue](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)

**Comment by Kiran-pande-30** [comment]
> Since three of you requested before I added the oss.gg tags, I didn't want to choose between you, so I let speed decide @Kiran-pande-30! 

Okay, but isn't it by default that the one who raised the issue should get assigned.

**Comment by DeepaPrasanna** [comment]
No @Kiran-pande-30 , only after the maintainers approve an issue and oss.gg label, one can assign and the first one to /assign gets assigned.

**Comment by Bonapara** [comment]
Sorry Kiran, didn't see you raised the issue :( Usually, I'll assign the person who raised the issue, specify it in your comment next time as we have a lot of people willing to handle issues at the moment!
