### ISSUE TITLE
Array data type accepts whitespace as input

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7593]
## Bug Description

- If a custom field Array datatype is created, it accepts Whitespace and null input as valid form

## Current Behaviour

https://github.com/user-attachments/assets/243a8106-348f-4bcb-8e72-e0b2c03bb928

## Expected behavior
It should not accept Whitespace and null values just like the rest of UI

**Comment by harshit078** [comment]
@Bonapara, I'll be working on this one !

**Comment by imshivamgupta** [comment]
/oss.gg

**Comment by DeepaPrasanna** [comment]
please wait for the maintainers to approve an issue and add labels before you assign yourself.

**Comment by Bonapara** [comment]
Thanks @harshit078 for bringing up the issue.
