### ISSUE TITLE
Droppable setup issue

### ISSUE THREAD

**Issue by harshrajeevsingh** [twentyhq/twenty#7597]
## Bug Description

The Droppable component from hello-pangea/dnd expects a placeholder element to be added as its child to reserve space when a draggable item is moved out of its place. This placeholder element is currently missing from the Droppable component. 
The warning can be found in the console. 

![Screenshot from 2024-10-11 19-28-05](https://github.com/user-attachments/assets/d2a7720d-d544-454b-85df-73b61069c0d5)

**Comment by harshrajeevsingh** [comment]
@Bonapara I will take this up :)

**Comment by ankitxvx** [comment]
I can do this Wrap the content of your Droppable component in a function that renders both the droppable content and the placeholder.

Add the provided.placeholder that is passed down from the Droppable render prop. This ensures that the library can reserve space when the item is being dragged.
