### ISSUE TITLE
Add a helper for passwords during sign-up.

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7601]
# Current Behavior

Users are not informed that they need to set a password with at least 8 characters when creating an account.

# Desired Behavior

Add a helper message under the password field that says, "At least 8 characters long."

![image](https://github.com/user-attachments/assets/6b7a9286-8b1b-40d3-85ca-b3097397ec58)

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by BhavdeepSinghNijhawan** [comment]
@Bonapara 

I hope this message finds you well. I am reaching out to seek your assistance regarding several issues I encountered while setting up the project locally. Unfortunately, I am unable to successfully run the project, which is preventing me from making the necessary changes.

Could you kindly provide guidance or solutions to resolve these errors? Your support would be greatly appreciated.

Thank you for your time and assistance.

![Screenshot from 2024-10-12 11-36-31](https://github.com/user-attachments/assets/25f2f8da-ecc8-40ec-baf2-e8be2c59a79e)

![Screenshot from 2024-10-12 11-36-58](https://github.com/user-attachments/assets/41767181-1fa1-44c4-9e0e-79796fdd6482)

**Comment by sumeet-y** [comment]
@Bonapara can you assign this task to me if @Musaveershaik  is not working on this.

**Comment by sans-byte** [comment]
<img width="489" alt="Screenshot 2024-10-26 at 1 14 07 AM" src="https://github.com/user-attachments/assets/bcb4b72c-e549-4c97-a998-8a1abaf7befc">
<img width="478" alt="Screenshot 2024-10-26 at 1 13 12 AM" src="https://github.com/user-attachments/assets/5c0fe991-8828-4e98-959c-cf4a27e5830f">

Created a PR @Bonapara
