### ISSUE TITLE
Wrong Twitter Icon on "Take Control Own your CRM" Page

### ISSUE THREAD

**Issue by Indrajeety993648** [twentyhq/twenty#7610]
#### Description:
The Twitter icon on the "Take Control Own your CRM" page is incorrect. The current icon being used is not consistent with the expected official Twitter icon. It needs to be replaced with the correct version. Everywhere else, the correct icon is being used.

#### Screenshot:

![Screenshot from 2024-10-11 22-04-21](https://github.com/user-attachments/assets/70ab7ccb-ae33-461f-9261-e5c0a634fb40)

#### Steps to Reproduce:
1. Go to the "Take Control Own your CRM" page.
2. Look for the Twitter icon floating on the page.
3. Notice that the Twitter icon is incorrect.

#### Expected Outcome:
The correct Twitter icon should be displayed, consistent with other areas of the site.

#### Suggested Fix:
Replace the incorrect Twitter icon with the official version of the Twitter icon.

#### Additional Context:
Rest of the Twitter icons across the website are correct; this issue only affects the CRM page.

**Comment by FelixMalfait** [comment]
@Indrajeety993648 thanks for the report. This page is actually the only thing that's not managed on this github repo. So I'll be closing this since it can't be addressed by the community. But pinging @Bonapara fyi

**Comment by Bonapara** [comment]
Done @Indrajeety993648 ;)
