### ISSUE TITLE
🕹️Like & Re-Tweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by AliYar-Khan** [twentyhq/twenty#7611]
Points: 50
Task: Like & Re-Tweet [oss.gg](http://oss.gg/) Launch Tweet

Proof:
![375826443-ec5732af-4c65-425c-a110-e5ee65ae89f1](https://github.com/user-attachments/assets/93faabdd-6fd2-4ac8-a37c-59bcf94a4fd7)

**Comment by FelixMalfait** [comment]
Please open a PR not an issue so we can assign points there! Thank you :)
