### ISSUE TITLE
Horizontal scroll when adding new record in Kanban style record table

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7615]
**Scenario:**
1. Log in
2. Go to Opportunities > By stage (or any other records tab in Kanban style)
3. Click '+' icon to add new record

**Actual:** There's horizontal scroll despite values being shorter than the total width of the popup
![image](https://github.com/user-attachments/assets/9a7e88b8-2d71-46e0-bc1f-8ca847308a0f)

**Expected:** There shouldn't be horizontal scroll

**Comment by ehconitin** [comment]
/oss.gg 150

**Comment by heygogu** [comment]
Waiting

**Comment by VenkateshSircilla123** [comment]
waiting

**Comment by ehconitin** [comment]
closed in #7682
