### ISSUE TITLE
Retrieving attachments results in Unauthorized-Error

### ISSUE THREAD

**Issue by janwo** [twentyhq/twenty#7620]
## Bug Description

If you upload an attachment in `0.31.0` and directly open it, twenty shows it up fine. As soon as you reload the page and open the link again, it says `{"error":"Unauthorized, missing workspaceId"}`.

<img width="724" alt="Bildschirmfoto 2024-10-12 um 16 36 52" src="https://github.com/user-attachments/assets/f2e861af-3eb1-4bdd-bfc4-ad4e035cb587">

## Expected behavior

It should show the attachment at all times.

## Technical inputs

I also realized that the `fullPath` does not come with a `token` via the GraphQL-API.

<img width="992" alt="Bildschirmfoto 2024-10-12 um 16 37 39" src="https://github.com/user-attachments/assets/8be44e80-14e0-47bc-a484-c0db6b897526">

**Comment by BOHEUS** [comment]
Related to #7325

**Comment by BOHEUS** [comment]
@janwo for the time being, you can use workaround and rename your file if this affects your work

**Comment by janwo** [comment]
Thank you, this works for twenty. 👍 However, we are still unable to fetch the attachments via API. 😰

**Comment by charlesBochet** [comment]
@janwo This has been fixed on 0.31.2 :)

**Comment by janwo** [comment]
That's so great ❤️ Thank you :)
