### ISSUE TITLE
🕹️Like & Re-Tweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by mdaatifayman786** [twentyhq/twenty#7627]
Points: 50
Task: Like & Re-Tweet [oss.gg](http://oss.gg/) Launch Tweet

Proof:
![Screenshot 2024-10-12 233930](https://github.com/user-attachments/assets/49b1a205-f5ff-442a-a6e1-39a4f8fdaf58)

**Comment by charlesBochet** [comment]
Thank you @mdaatifayman786 :)

**Comment by charlesBochet** [comment]
/oss.gg 50
