### ISSUE TITLE
[OSS.gg] Add the structure of the authentication callback url in the documentation

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#7629]
Placeholder issue to reward @ShantanuGaur26 for the work on https://github.com/twentyhq/twenty/issues/7442

**Comment by charlesBochet** [comment]
/oss.gg 150

**Comment by ShantanuGaur26** [comment]
@charlesBochet idts i need to do anything now.

**Comment by charlesBochet** [comment]
...

**Comment by charlesBochet** [comment]
@ShantanuGaur26 can we try another way. Could you create an issue (like this one)? It seems that the bot takes the issue author into account: https://github.com/formbricks/oss.gg/blob/main/lib/github/hooks/issue.ts#L394

**Comment by ShantanuGaur26** [comment]
ohhh man im not well versed with gihub. wait lemme try. can i reopen the same issue again??

**Comment by ShantanuGaur26** [comment]
did it on #7630

**Comment by ShantanuGaur26** [comment]
@charlesBochet

**Comment by charlesBochet** [comment]
All good!
