### ISSUE TITLE
Add the structure of the authentication callback url in the documentation

### ISSUE THREAD

**Issue by ShantanuGaur26** [twentyhq/twenty#7630]

**Comment by charlesBochet** [comment]
All good!

**Comment by ShantanuGaur26** [comment]
Thanks man

**Comment by ShantanuGaur26** [comment]
hey @charlesBochet can i reach out to you on mail or discord? i really wanna deep dive into open source. i know mern and bit of next js but im not able to contribute, i really want to give back to the community so if you could help me out, that would be freaking awesome. here also i was able to make the change because it was a non code issue. also i only focus on backend and the issues there are pretty difficult. so yeah.
thanks and regards 🙏

**Comment by charlesBochet** [comment]
@ShantanuGaur26 sure, feel free to DM me on Discord
