### ISSUE TITLE
[🕹️] Like & Re-Tweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by utsavdotdev** [twentyhq/twenty#7632]
Point: 50 Points
Task: Like & Re-Tweet oss.gg Launch Tweet
Proof:
<img width="597" alt="Screenshot 2024-10-13 at 4 40 11 PM" src="https://github.com/user-attachments/assets/72e8438b-34f3-4b0f-a3d3-d6442909d5c7">

<img width="1402" alt="Screenshot 2024-10-13 at 4 10 33 PM" src="https://github.com/user-attachments/assets/17883ebd-faf5-4dfc-84bd-a9a55c3ed79f">

**Comment by FelixMalfait** [comment]
Hey @utsavdotdev I think you need to open a PR as per the instructions, I don't think I can award points on an issue. Thank you!
