### ISSUE TITLE
Enhance PostgreSQL Setup Script and Documentation for Various Distros

### ISSUE THREAD

**Issue by dostavic** [twentyhq/twenty#7636]
I've modified Step 3: Set up a PostgreSQL Database to ensure it works with Debian/Ubuntu, Arch, and Manjaro. Here are additional notes from the testing process:

- Debian: Tested and working as expected.
- Ubuntu: Successfully tested and confirmed to be working.
- Arch: Also tested and verified as functional.
- Manjaro: Since Docker for Manjaro is not available, testing was performed directly on Manjaro.

Additionally, I encountered the following issues:

- npx nx start: If this doesn’t work, it's recommended to use the alternative command.
- make postgres-on-docker: Occasionally, this command can hang.
- Out of Memory on the frontend: Consider using to prevent memory issues.NODE_OPTIONS="--max-old-space-size=4096" npx nx start twenty-front
- specific: Use for AUR support on Manjaro and Arch.yay

It would be helpful to update the documentation to address these points.

**Comment by dostavic** [comment]
I have created the pull request for the updates made to the PostgreSQL setup script. Please review the changes.

**Comment by Hitarthsheth07** [comment]
Hey @dostavic which command do you use if npx nx start throws error. I am having problems setting up the project locally?

**Comment by dostavic** [comment]
Hi @Hitarthsheth07! Instead of npx nx start, I used two separate commands for the server and frontend:

`npx nx start twenty-server`

For the frontend, I added a memory option to avoid out-of-memory errors:

`NODE_OPTIONS="--max-old-space-size=4096" npx nx start twenty-front`

If these commands don't work, just let me know the error you're seeing, and I'll try to help!

**Comment by BOHEUS** [comment]
@Bonapara this issue can be closed as changes in #7637 are merged
