### ISSUE TITLE
[🕹️] Follow Dub on Twitter

### ISSUE THREAD

**Issue by sohelhussain** [twentyhq/twenty#7643]
<img width="705" alt="Screenshot 2024-10-13 at 7 40 37 PM" src="https://github.com/user-attachments/assets/7b4c51cd-1c47-4819-b887-b1bdf8325a8b">

**Comment by sohelhussain** [comment]
hay @FelixMalfait where is my points?

**Comment by FelixMalfait** [comment]
@sohelhussain you don't get point for that as per the instructions :). There are many other ways to get points but they all involve creating a PR. Thanks!
