### ISSUE TITLE
Remove Docker references from documentation and code

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7648]
As core team decided not to support Docker development containers [here](https://github.com/twentyhq/twenty/pull/7369#discussion_r1782821134) thanks to many tickets in #help channel on Discord server and general problems in maintaining, we should clean this before next release. Only Docker dev containers should be affected, Postgres and Redis container are still supported.

```[tasklist]
### Tasks
- [ ] Remove Dockerfiles for Docker from `packages/twenty-docker`
- [ ] Remove Docker references in developers' documentation (`twenty-website/src/content/developers`)
```

**Comment by BOHEUS** [comment]
@charlesBochet did I miss something? If you want, I can handle this

**Comment by charlesBochet** [comment]
@BOHEUS I think we should keep them but make clear they are community maintained.
I think we can get rid of:
- twenty-docker/twenty-website
- Makefile

but I would keep the other ones.

Regarding the docs, we should remove the references to docker except for self-hosting + postgres local container. I'm not sure there are actually

**Comment by charlesBochet** [comment]
I think the mindset of these dockers config is that they can be used for production hosting (production built container). We don't want to support docker for local setup (to contribute).

So the Makefile does not make sense + twenty-website does not makes sense

- twenty is still useful for self-host
- postgres + postgres-spilo are useful to get postgres for self-host (and local contribution for this one as we don't need a dev specific container for postgres)

**Comment by BOHEUS** [comment]
Okay, I'll handle this and create a PR soon

**Comment by charlesBochet** [comment]
TY!
