### ISSUE TITLE
Unable to go on welcome screen

### ISSUE THREAD

**Issue by Udaypawar004** [twentyhq/twenty#7650]
### Discussed in https://github.com/twentyhq/twenty/discussions/7649

<div type='discussions-op-text'>

<sup>Originally posted by **Udaypawar004** October 13, 2024</sup>
When i start the project locally i am unable to go on the route which is related to my issue #7612.
The issue is about docs button on the welcome route but when i set up project locally it directly redirects me to dashboard section like in the demo.twenty.com, how can go to that route to contribute on that issue.

 I want to go on this window given below:

![image](https://github.com/user-attachments/assets/822b04cc-08df-47d9-b0c5-dded8186ecd4)

but it takes me here:

![image](https://github.com/user-attachments/assets/743cf6e9-3505-4760-819f-ed298f1f0dc4)

</div>

**Comment by Naprila** [comment]
I ended up wasting 2 hours trying to go welcome screen, i am still facing the same issue.

**Comment by ehconitin** [comment]
@Udaypawar004
Thank you for your report. To clarify:

1. The landing page you're trying to access is part of the twenty-website, what you are running is twenty-front (ie main app)

2. This homepage is built directly with Framer.

3. twenty-website is split across different platforms depending on the page type.

4. We use Cloudflare to distribute traffic between these different parts.

Regarding issue #7612 about the docs button on the welcome route: this would be handled by our core team.
