### ISSUE TITLE
Add repositories under twentyhq for low-code workflows

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7651]
Since more and more people are moving from other CRMs to Twenty, we should focus on making it more accessible and easy to use. One way is to support connections to Twenty via low-code workflows such as n8n, Make, Windmill and such (which are requested for a long time #3828). In my opinion, creating repositories for specific low-code workflows under twentyhq is a perfect solution as:
- it can be 100% community maintained
- core team or others on behalf of core team will have a direct control of changes
- if someone finds a problem, it'll know where to report
- it adds another way of customization
- people can expect fast changes to low-code nodes repo reflecting to changes in main repo

The cost of implementing this is quite low compared to workflows which are right now in progress and won't be finished until next year.
Repo for n8n is a good starting point as there are starting templates which will directly help in fast implementation of this idea.

**Comment by BOHEUS** [comment]
@charlesBochet what do you think? It's a fast win from my perspective as implementation won't take much time (up to a day in worst case), also good for marketing (if that matters)

**Comment by FelixMalfait** [comment]
@BOHEUS actually workflows will be finished this year! I think we'd like to double down on that rather than extend the surface. So I'll close this sorry :(. I wish we could do everything but trust me workflows will be worth the wait ;-) (even though there will still be many iterations after we launch the v1 in November)

**Comment by BOHEUS** [comment]
No problem, thanks for the feedback
