### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by jaredreich** [twentyhq/twenty#767]
> A CRM that ban self-hosted for free, on your own network and close to your data sources

should read

> A CRM that can be self-hosted for free, on your own network and close to your data sources

**Comment by FelixMalfait** [comment]
Good catch thanks! We'll fix it tomorrow

**Comment by gbraad** [comment]
Wasn't the only one who noticed. *phew*

**Comment by charlesBochet** [comment]
Fixed by https://github.com/twentyhq/twenty/pull/770
