### ISSUE TITLE
[🕹️]Like & Re-Tweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by Naprila** [twentyhq/twenty#7703]
### What side quest or challenge are you solving?

Like & Re-Tweet [oss.gg](http://oss.gg/) Launch Tweet

### Points

50

### Description

Retweeted oss.gg launch tweet on X

### Provide proof that you've completed the task

<img width="1320" alt="Screenshot 2024-10-15 at 10 37 29 AM" src="https://github.com/user-attachments/assets/55a5c6f2-e9ba-4f00-8b28-42ae47051cca">

**Comment by FelixMalfait** [comment]
(posted in another repo already)
