### ISSUE TITLE
[🕹️] Liked & Re-Tweeted oss.gg Launch Tweet

### ISSUE THREAD

**Issue by sahiladit** [twentyhq/twenty#7717]
### What side quest or challenge are you solving?

 Like & Re-Tweet oss.gg Launch Tweet

### Points

50

### Provide proof that you've completed the task

<img width="1440" alt="Screenshot 2024-10-15 at 7 50 11 PM" src="https://github.com/user-attachments/assets/92327c55-a1fe-484c-aaff-0dc33d13ac7d">

**Comment by Bonapara** [comment]
Please create the associated PR so we can award the points!
