### ISSUE TITLE
Update setup documentation to reflect removal of `pg_graphql` and local setup scripts

### ISSUE THREAD

**Issue by akshatvishu** [twentyhq/twenty#7721]
## Bug Description

The current setup [documentation](https://twenty.com/developers/local-setup#step-3:-set-up-a-postgresql-database) for local development still includes instructions related to `pg_graphql` and provisioning a PostgreSQL database using local setup scripts. However, this appears to be outdated based on the recent PR  #7716 that removed `pg_graphql`  and local setup scripts from the project.

**Example:** 
currently, following  [Step 3: Set up a PostgreSQL Database](https://twenty.com/developers/local-setup#step-3:-set-up-a-postgresql-database)
```
make postgres-on-linux
```
results in the following error:
```
[user@arch twenty]$ make postgres-on-linux
make -C packages/twenty-postgres provision-on-linux
make[1]: Entering directory '/home/user/twenty'
make[1]: *** packages/twenty-postgres: No such file or directory.  Stop.
make[1]: Leaving directory '/home/user/twenty'
make: *** [Makefile:26: postgres-on-linux] Error 2
```

**Comment by Bonapara** [comment]
@akshatvishu, the update will be online in the coming hours! Thanks for raising this issue
