### ISSUE TITLE
[🕹️] GIF, MEME, Retweet, Logo, Poster, Feature [SIDE QUEST]

### ISSUE THREAD

**Issue by harshsbhat** [twentyhq/twenty#7724]
### What side quest or challenge are you solving?

GIF: 150 points
Meme: 150 points
Retweet: 50 points
Favourite Feature: 50 points
Logo: 300 points
Poster 300 points

Total: 1000

### Points

1000

### Provide proof that you've completed the task

GIF: 

https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcDRuenQ1emluYmM2eWo3dzJ5YnExYTRpNTZvNWIzc2M2eG05azRoOCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/mgoYSDrjIalUL7XJzm/giphy.gif

Favourite Feature tweet:

https://x.com/HarshBhatX/status/1846075312691413066

LAUNCH TWEET:

https://x.com/HarshBhatX/status/1846252536241508392

Meme:

https://x.com/HarshBhatX/status/1844698253104709899

Logo ( heavily inspired by unkey ):

https://x.com/HarshBhatX/status/1846234658712772977

Poster:

https://x.com/HarshBhatX/status/1846233330435477531

**Comment by FelixMalfait** [comment]
Would you mind opening a PR instead of an issue? Thanks a lot!
