### ISSUE TITLE
[🕹️]Like & Re-Tweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by rajeevDewangan** [twentyhq/twenty#7732]
### What side quest or challenge are you solving?

Like & Re-Tweet oss.gg Launch Tweet

### Points

50

### Description

Liked & Re-Tweeted oss.gg Launch Tweet

### Provide proof that you've completed the task

![Screenshot (1235)](https://github.com/user-attachments/assets/161e0208-8216-462f-893e-6aa14bc0e798)

**Comment by rajeevDewangan** [comment]
where are my points?

**Comment by FelixMalfait** [comment]
Hey @rajeevDewangan - ours required to quote-tweet tagging twenty. Also we usually give points through PR rather than issues. Thanks
