### ISSUE TITLE
Navigation Bar extends beyond the screen size 

### ISSUE THREAD

**Issue by Hitarthsheth07** [twentyhq/twenty#7733]
## Bug Description

When the items in the left navigation bar are filled it extends beyond the screensize. 

![overflow ](https://github.com/user-attachments/assets/28603c83-a727-4841-8862-9f7d642caf21)

## Expected behavior

When items overflow the navigation bar should allow vertical scroll.

**Comment by Bonapara** [comment]
@Hitarthsheth07, please ensure to check the responsiveness -> #7743. Thanks!

**Comment by Hitarthsheth07** [comment]
> @Hitarthsheth07, please ensure to check the responsiveness -> #7743. Thanks!

Yupp, on it!

**Comment by Hitarthsheth07** [comment]
@Bonapara Is it possible for some team member who has good CSS knowledge to hop on a short call. 
I've made the workspace scrollable but some or the other thing is breaking?

**Comment by Hitarthsheth07** [comment]
Not sure which PR did this, but now the workspace title scrolls and the doesn't occupy the space available.. 

![image](https://github.com/user-attachments/assets/350ddfc3-a194-477f-a024-6b11fc207556)

**Comment by Bonapara** [comment]
Cannot see the scroll on main 🤔

![CleanShot 2024-10-17 at 09 11 37](https://github.com/user-attachments/assets/84e5d427-a06c-4464-a2de-3aa82905f81f)

**Comment by Devessier** [comment]
Hi @Hitarthsheth07, where can I find the code you started to write? I can give it a look.

**Comment by Hitarthsheth07** [comment]
> Hi @Hitarthsheth07, where can I find the code you started to write? I can give it a look.

Hey @Devessier, just solved it a minute ago. I am about to push it now!
