### ISSUE TITLE
Hardly visible text in dark mode in Workflow

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7737]
**Scenario:**
1. Log in
2. Go to Settings > Experience
3. Set dark mode
4. Exit settings and go to Workflows
5. Create new Workflow record
6. Check details of workflow
7. Set trigger

**Actual:** Text is black on dark background making it hard to read
![image](https://github.com/user-attachments/assets/f807723d-b40a-4cf1-9d28-8f465bdb8280)

**Expected:** Text should be white on dark background

CC: @thomtrp

**Comment by Bonapara** [comment]
@Devessier color should be `text/primary`

**Comment by akshayjoshi892** [comment]
@Bonapara
I think issue is not reproducible .
![Screenshot from 2024-10-25 15-30-22](https://github.com/user-attachments/assets/89683edc-6e25-4fc7-bc59-e57bea1c75c7)

 @BOHEUS  is text color should be text/primary before even adding trigger? if not then issue is not present 

![Screenshot from 2024-10-25 15-32-48](https://github.com/user-attachments/assets/aa9d3d6c-2ba3-44ef-ab5e-990088cfd13b)

**Comment by Devessier** [comment]
I already solved this issue in this PR: https://github.com/twentyhq/twenty/pull/7829.

We can close. Thanks @akshayjoshi892 for double-checking it.
