### ISSUE TITLE
Cleanup after removing pgGraphql

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7739]
Since pgGraphql was removed from codebase, there are still some leftovers in codebase, I checked and command `make postgres-on-docker` isn't supported anymore despite files still existing in codebase
![image](https://github.com/user-attachments/assets/d2cdf5b4-a4c7-4441-8c86-75cf8d42e760)

@charlesBochet @Weiko should I remove Makefile from root of the project as well as `twenty-postgres` and `twenty-postgres-spilo` folders in `twenty-docker`?

**Comment by Bonapara** [comment]
@Weiko leftovers or still waiting for the updated doc to get pushed online?

**Comment by BOHEUS** [comment]
@Bonapara changes are live as presented on screenshot above, there is no mention about make commands, my question is are they still needed if there's no mention of them in docs?

**Comment by Weiko** [comment]
@BOHEUS good catch, this makefile could be removed indeed

**Comment by BOHEUS** [comment]
Okay, I'll create a PR soon @Weiko

**Comment by Weiko** [comment]
@BOHEUS actually I changed my mind, let's keep the makefile for convenience but we need to update it to run `docker run ...` instead. I'll also add one for redis. We can remove the other rules. Will create a PR in a few
