### ISSUE TITLE
I can delete my account easily

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#774]
https://news.ycombinator.com/item?id=36797498

Design available here in Figma: 
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=1192%3A37582&mode=dev
(see also video in Bonapara's post below)

On deletion:
- remove the workspace if the user is the last member of the workspace and all entities tied to the workspace (companies, people, comment_threads, pipelines, pipeline_stages, pipeline_progresses)
- remove the account

**Comment by Bonapara** [comment]
Ready for implementation 🫡
https://github.com/twentyhq/twenty/assets/19412894/cc26717e-0ecf-4921-80a9-d2c2366a80f7

**Comment by FelixMalfait** [comment]
Great! And same design for workspace deletion?  (in General section).
Creating a second issue

**Comment by charlesBochet** [comment]
We actually don't want to move the log-out to this section

**Comment by Bonapara** [comment]
Thanks @charlesBochet for your sharp eyes 👀
Here is the updated Figma where logout should stay in the left menu with a gray color:

Uploading Screen Recording 2023-07-21 at 15.37.49.mov…

**Comment by Rumone** [comment]
Hey, I am interested in working on this issue. I have never contributed to open source before and I think this would be a good place to start. How would I go about assisting?

**Comment by FelixMalfait** [comment]
Hi @Rumone, thanks a lot!

Have you ever work with NestJS +  React? If you don't have experience on Nest, usually the front-end only tickets are a bit easier to start with than something full stack like this issue. See some here: https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+label%3AFront (I will be tagging more soon)

Figma is very helpful for the frontend tickets, the developer mode give you all of the styling directly.

You can pick any ticket you like that is not assigned and let us know. We would assign it to you, to make sure someone is not working on this at the same time.

Feel free to ask on [Discord](https://discord.gg/cx5n4Jzs57) if you need help!

**Comment by Rumone** [comment]
Awesome thanks [here](https://github.com/twentyhq/twenty/issues/819) is another task that seemed interesting. Could I work on that one instead.

**Comment by FelixMalfait** [comment]
@Rumone  Yes of course! Could you please comment on the issue? I don't have the rights the assign you to an issue an Github unless you have commented on it

**Comment by FelixMalfait** [comment]
@gitstart-twenty assigning to you for later (not urgent) since it's similar to the workspace deletion issue
