### ISSUE TITLE
Left sidebar causing app to overflow

### ISSUE THREAD

**Issue by NitinPSingh** [twentyhq/twenty#7743]
## Bug Description

In https://demo.twenty.com/ , too many entries in left sidebar causes the app to overflow

**Example:** 
in desktop

https://github.com/user-attachments/assets/bfc42107-5701-4b58-8127-10ec6183aa4c

in mobile view
![16 10 2024_15 15 05_REC](https://github.com/user-attachments/assets/abdf6408-4d22-4157-8720-7785282f833f)

**Comment by krVatsal** [comment]
can i work on this?

**Comment by BOHEUS** [comment]
Related to #7733

**Comment by Bonapara** [comment]
Closing in favor of #7733, which was opened first. Thank you for the issue, @NitinPSingh.
