### ISSUE TITLE
[🕹️] Side Quest: Like & Re-Tweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by Kritikaadhikarii** [twentyhq/twenty#7744]
### What side quest or challenge are you solving?

[🕹️] Side Quest: Like & Re-Tweet oss.gg Launch Tweet

### Points

50

### Description

I've completed the task

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/ab414e0f-1872-488b-af52-2071b3e14d5a)
![image](https://github.com/user-attachments/assets/a518de49-47f6-49d0-8f03-6b8b958e9a48)

**Comment by Bonapara** [comment]
Thanks @Kritikaadhikarii ;)
