### ISSUE TITLE
Link for side quest of twenty isn't working in oss.gg website

### ISSUE THREAD

**Issue by Kritikaadhikarii** [twentyhq/twenty#7745]
## Bug Description

https://[oss.gg](https://oss.gg/side-quests)/side-quests
Upon clicking side quests: twenty, we are redirect to notion, where we're asked to login. But upon login, nothing is being shown, we are being directed to our own personal notion dashboard.

**Example:** 
![image](https://github.com/user-attachments/assets/e77c0929-1d91-4d70-afc9-5bff4b06c5ce)

## Expected behavior
Notion link with descriptions of the side quest should've been shown.

**Comment by Bonapara** [comment]
Fixed!

**Comment by Bonapara** [comment]
Thanks for raising the issue @Kritikaadhikarii
