### ISSUE TITLE
[🕹️] [bug] Error in Hover Effect UI 

### ISSUE THREAD

**Issue by deepikaa0402** [twentyhq/twenty#7752]
### What side quest or challenge are you solving?

In this "Plus all the features of a great CRM" section of the homepage under the dark mode, on hovering over LinkedIn only the name div is highlighted but on hovering over Qonto the entire block is highlighted. 

https://github.com/user-attachments/assets/b71c8594-34d7-40db-b16a-bbbda8d45172

### Points

I am not sure.

### Description

There is an inconsistency in the hover behavior between the LinkedIn and Qonto blocks on the page. While the LinkedIn block only highlights the icon or text on hover, the Qonto block highlights the entire element, causing an unintended visual effect. This seems to be due to differences in the CSS rules or parent container structure, particularly related to the data-border attribute and hover state. The expected behavior is for both blocks to have a consistent hover effect, focusing only on specific elements like the icon or text.

### Provide proof that you've completed the task

The issue has been identified and documented with the required investigation into the CSS and DOM structure. The problem is related to inconsistent hover behavior between the LinkedIn and Qonto blocks, potentially due to differences in the data-border attribute and parent container structure. The next step is to implement and test a fix to ensure consistent hover effects across both elements.

**Comment by Bonapara** [comment]
Thanks for raising this issue. I'll grant you 50 points for it!
