### ISSUE TITLE
After pressing Enter in ConfirmationModal, no action is performed

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7753]
Follow-up of #6663 (all affected places are mentioned there)

**Scenario:**
1. Log in
2. Go to Settings > Profile
3. Click "Delete account" button
4. Type email in input and press Enter key

**Actual:** After entering proper value to input and pressing Enter, no action is performed

**Expected:** After entering proper value to input and pressing Enter, respective action must be performed

![CleanShot 2024-10-16 at 17 09 37](https://github.com/user-attachments/assets/e6c36fe4-1c96-416f-b9d8-5097cd6f27a3)

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by Owaiseimdad** [comment]
having an issue during local setup, 

[Nest] 61756  - 10/17/2024, 12:21:25 AM   ERROR [ExceptionHandler] redis cache storage requires REDIS_URL to be defined, check your .env file

**Comment by Owaiseimdad** [comment]
also when I am doing yarn, it is throwing some errors
<img width="1128" alt="Screenshot 2024-10-17 at 12 34 11 AM" src="https://github.com/user-attachments/assets/975b5083-5fb0-42d1-b31b-c717e682f60e">

**Comment by jayabha-jayas** [comment]
Hi @BOHEUS @Bonapara I completed the local setup and tried the scenario mentioned above. after clicking on delete button, i got redirected to the login page again. and when i tried logging in again, it said "User is not a member of this workspace". That means the user's account already got deleted, right?

Please correct me if my understanding is wrong. 
Also please explain a little more on this part - **After entering proper value to input and pressing Enter, respective action must be performed**
what do we mean by respective action?

**Comment by BOHEUS** [comment]
Exactly what I wrote, after you type whatever input requires (email or "yes" depending from where this popup is triggered), you have to press Enter key on your keyboard and not click red button "Delete account". 

And yes, account is deleted.

**Comment by jayabha-jayas** [comment]
Apologies, I missed the Enter key part. Thanks for clarifying. I will check this.

**Comment by jayabha-jayas** [comment]
Hi @Bonapara @BOHEUS I have raised the PR. Please check. Its a small change. thanks!
