### ISSUE TITLE
Letters are slightly cut in placeholder in Functions

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7757]
**Scenario:**
1. Log in
2. Go to Settings
3. Toggle "Advanced" settings
4. Go to Functions

**Actual:** If no functions were created, there is placeholder which contains text slightly cut at the bottom
![image](https://github.com/user-attachments/assets/bcc25627-4f08-4242-bef4-9c51b5683523)

**Expected:** Letters aren't cut at the bottom

**Comment by Bonapara** [comment]
/oss.gg 150
