### ISSUE TITLE
[🕹️] Starry-eyed Supporter

### ISSUE THREAD

**Issue by Atharva-3000** [twentyhq/twenty#7765]
### What side quest or challenge are you solving?

The quest to get 5 peeps to star the repo.

### Points

150

### Description

Got 5 friends to star the repo and also lectured them about oss.gg 😋😋

### First
![WhatsApp Image 2024-10-15 at 11 24 27_258c5876](https://github.com/user-attachments/assets/61b24da2-e71c-47fc-a975-32de8b85a2e6)

### Second
<img width="1440" alt="Screenshot 2024-10-15 at 10 30 58 AM" src="https://github.com/user-attachments/assets/5028a015-08d3-4a8e-b8b5-a9084c37aa44">

### Third
![WhatsApp Image 2024-10-15 at 14 29 49_72aa2be0](https://github.com/user-attachments/assets/eb97ba4c-b62c-4c4b-82b5-67d435f59211)

### Fourth
![WhatsApp Image 2024-10-15 at 14 29 50_4e6d9a32](https://github.com/user-attachments/assets/e5ce8036-c7fc-4a73-994c-902725283a5f)

### Fifth
![WhatsApp Image 2024-10-15 at 17 45 51_6920a8fd](https://github.com/user-attachments/assets/026b32c0-a0d0-4116-9317-13426439d758)

**Comment by Bonapara** [comment]
Thanks for sharing the project with your friends @Atharva-3000!
