### ISSUE TITLE
Add feature to show total row in table where numeric fields are summed

### ISSUE THREAD

**Issue by asdev29** [twentyhq/twenty#7767]
Description: 
We need to implement a feature that adds a "Total" row at the bottom of tables displaying numeric data. This row should sum the values of all numeric fields in the table columns and display the total for each corresponding column. Non-numeric fields should remain blank in this row.

Acceptance Criteria:

1. A new row should appear at the bottom of tables that have numeric fields.
2. All numeric fields in this row should contain the sum of the respective column values.
3. Non-numeric fields in the total row should be left blank or display a placeholder (e.g., "-").
4. This feature should be configurable, allowing it to be turned on or off as needed.
5. Check compatibility with existing filters and pagination

**Comment by Bonapara** [comment]
@asdev29 do you mean something like https://github.com/twentyhq/twenty/issues/6868 ?

**Comment by asdev29** [comment]
@Bonapara yes exactly - i've searched in issues but couldn't find it - i will close this issue then :)

**Comment by Bonapara** [comment]
And by the way we're about to start #6868!
