### ISSUE TITLE
Add title/tag for opportunity

### ISSUE THREAD

**Issue by luposlip** [twentyhq/twenty#777]
If you want to sell more than one product/service to the same company, you can create more than one opportunity for the same company.

But there's no way to see from the opportunities board which is which.

It'd be nice if it was possible to add a title or tag to an opportunity.

**Comment by luposlip** [comment]
Thanks for your reply.

That would solve my immediate requirement, yes.

But it would still be nice to see everything in one overview (ie. merged
boards).

Best,
Henrik

tor. 20. jul. 2023 18.38 skrev Félix Malfait ***@***.***>:

**Comment by FelixMalfait** [comment]
The thing is, we allow different column per board, so a merge column wouldn't really be possible... 

I understand the problem you describe and the need for something more customizable (e.g. title). I don't think we would implement that as a standard field for all users, but that will be possible for sure once we implement once we've shipped Standard fields: https://github.com/twentyhq/twenty/issues/501 (which is going to take some time to ship, I'd say we'll have it in September)

cc @Bonapara fyi interesting conversation

**Comment by FelixMalfait** [comment]
Closing the issue to keep the backlog clean but feel free and without duplicate but feel free to continue the conversation here!

**Comment by Bonapara** [comment]
Interesting point, thanks @luposlip
