### ISSUE TITLE
[🕹️]Starry-eyed Supporter

### ISSUE THREAD

**Issue by sohelhussain** [twentyhq/twenty#7770]
### What side quest or challenge are you solving?

five friends to star our repository.

### Points

150

### Description

my five friends to star our repository.

### Provide proof that you've completed the task

![WhatsApp Image Oct 11 (1)](https://github.com/user-attachments/assets/ec26cfc8-100e-4065-82af-4293ed43a2a5)
![WhatsApp Image Oct 14 (2)](https://github.com/user-attachments/assets/58a4c849-807f-4543-91ef-16889dee01a9)
![WhatsApp Image Oct 14](https://github.com/user-attachments/assets/c20e7edf-608e-4088-95dc-ca19fc445988)
![WhatsApp Oct 14 Image (1)](https://github.com/user-attachments/assets/5a3d6d24-dc6b-41da-87e1-631ef87cf6bd)
![WhatsApp Oct 15 Image (5)](https://github.com/user-attachments/assets/4c49cbb0-df5a-4c9e-8b13-d0c5def7fbd8)

**Comment by Bonapara** [comment]
Thanks for sharing Twenty with your friends @sohelhussain!
