### ISSUE TITLE
[🕹️]Meme Magic (150 Points): Craft a meme where the number twenty plays a role. Tweet it, and tag @twentycrm.

### ISSUE THREAD

**Issue by Rohan-Rathod** [twentyhq/twenty#7771]
### What side quest or challenge are you solving?

Meme Magic (150 Points): Craft a meme where the number twenty plays a role.
Tweet it, and tag @twentycrm.

### Points

150

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/0f7953cf-ed00-44f0-bcd5-dc47c937f634)

**Comment by Bonapara** [comment]
@Rohan-Rathod Twenty is not 20yo 😂
Awarding 50 points. Thanks for contributing

**Comment by Rohan-Rathod** [comment]
> @Rohan-Rathod Twenty is not 20yo 😂 Awarding 50 points. Thanks for contributing

oh okay 😂🤣 I thought they completed 20yo my bad😂😁
