### ISSUE TITLE
[🕹️] Share a tweet about your favorite feature in Twenty

### ISSUE THREAD

**Issue by Kritikaadhikarii** [twentyhq/twenty#7774]
### What side quest or challenge are you solving?

[🕹️] Share a tweet about your favorite feature in Twenty

### Points

50

### Provide proof that you've completed the task

https://x.com/kritikaadhikar/status/1846813219215888754
![image](https://github.com/user-attachments/assets/96bf21f5-2e5f-403a-b1a3-0a6127c3397b)

**Comment by Bonapara** [comment]
Closing as you opened it x3 @Kritikaadhikarii
