### ISSUE TITLE
[🕹️] Gif Magic

### ISSUE THREAD

**Issue by Kritikaadhikarii** [twentyhq/twenty#7775]
### What side quest or challenge are you solving?

[🕹️] Gif Magic

### Points

150

### Provide proof that you've completed the task

Link of gif:
https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcHk3aTdweGtjdDBkODdydTdjeWdjbTg0Mjljd2phb3Y5eXEzaHpqbCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/SeNAT0aX1jJLYJaQj0/giphy-downsized-large.gif

Link of tweet:
https://x.com/kritikaadhikar/status/1846813219215888754

![Screenshot 2024-10-17 130534](https://github.com/user-attachments/assets/26a8a837-7418-4eb0-9e8e-fa1aaadb6da2)

**Comment by Bonapara** [comment]
Closing as this one is a duplicate. Thanks for your contribution @Kritikaadhikarii!

**Comment by Kritikaadhikarii** [comment]
Hii looks like maybe you got confused !! I've created two different gifs.

**Comment by Kritikaadhikarii** [comment]
> Closing as this one is a duplicate. Thanks for your contribution @Kritikaadhikarii!

Hii looks like maybe you got confused !! I've created two different gifs. I'm sorry for confusing you, but can you recheck it once, the gif in another issue is a different one than this.
