### ISSUE TITLE
Regression on filters Left-margin

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7779]
# Bug description

![CleanShot 2024-10-17 at 10 51 18](https://github.com/user-attachments/assets/e8ca1b57-34c4-4ae8-9ca1-2a8bca958729)

We should have an 8px padding left

**Comment by NitinPSingh** [comment]
can i work on this @Bonapara

**Comment by Bonapara** [comment]
/oss.gg 150
