### ISSUE TITLE
Prevent empty records creation from Side Panel

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7782]
## Scope & Context

- Currently when creating a company,opportunities,people etc through Rightdrawer, it accepts Null values and whitespaces.
- This tends to create a lot of empty fields
- As a behaviour, if clicked outside of RightDrawer then it should not create the field just like the rest of UI

## Current behavior
- It creates multiple empty fields
<img width="1162" alt="Screenshot 2024-10-16 at 1 25 43 PM" src="https://github.com/user-attachments/assets/3201f48c-0bc6-4db5-858f-889d91c23015">

<img width="573" alt="Screenshot 2024-10-16 at 1 26 27 PM" src="https://github.com/user-attachments/assets/a46344fa-8671-478c-a942-281782ca324f">

## Expected behavior

https://github.com/user-attachments/assets/be2c7c3e-868c-4063-afa8-21f15ff437c2

## Technical Inputs

- We should handleClickedOutside function to make sure that if no value is entered then a field is not created.

**Comment by harshit078** [comment]
@Bonapara, whats your opinion on this ?

**Comment by Bonapara** [comment]
I 100% agree on the problem. The clean way to implement it is quite complex though, as it would involve creating a "Draft" status for records. Will create an issue to track this

**Comment by askarthikey** [comment]
heyy @Bonapara please assign me this issue under hacktoberfest. Im interested to work on this issue
