### ISSUE TITLE
[🕹️] Crafting a meme where the number 20 plays a role

### ISSUE THREAD

**Issue by Khaan25** [twentyhq/twenty#7799]
### What side quest or challenge are you solving?

I crafted a meme where the number 20 played a role, tweeted it, and tagged [twentycrm](https://x.com/twentycrm).

### Points

50

### Provide proof that you've completed the task

Link to [Tweet](https://x.com/zia_webdev/status/1846954638953926675)

![image](https://github.com/user-attachments/assets/51eb2b18-9c77-4bc2-9221-8d6078453a25)

**Comment by Bonapara** [comment]
Thanks for the Meme @Khaan25 😂
