### ISSUE TITLE
Sizing of badge isn't good when single timeline

### ISSUE THREAD

**Issue by Khaan25** [twentyhq/twenty#7811]
## Bug Description

A clear and concise description of what the current behavior is.
Please also add **screenshots** of the existing application.

You can see that I've only one timeline and the icon has too much vertical padding, I would expect it to have equal padding, maybe a square shape.

![image](https://github.com/user-attachments/assets/8f700590-c17c-4ea0-9b9c-eb9cc44a49b5)

It's looking great if we've more than 1:
![image](https://github.com/user-attachments/assets/96e69cd8-608f-4112-b631-f4504ec87a5e)

## Expected behavior

I would expect it to have square shape align to the text next to it if single timeline.

**Comment by Pushpender1122** [comment]
I want to work on this issue

**Comment by Bonapara** [comment]
@Khaan25 do you think I would look better like this? 

![image](https://github.com/user-attachments/assets/7897fb42-2f53-4d13-84f6-cb3e5ab97b9b)

**Comment by Khaan25** [comment]
Yes, yes, definately. There's a massive difference between the design and current version

**Comment by Bonapara** [comment]
Great! Here is the design if you want to implement it: https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=43128-110542&node-type=frame&t=OOVK3xhrcy5zJPVL-11

**Comment by Vardhaman619** [comment]
@Bonapara i would like to work on this

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by Bonapara** [comment]
I'll let @Khaan25 decide if he wants to work on it since he raised the issue. Otherwise, I'll assign it to you, @Vardhaman619.

**Comment by Khaan25** [comment]
Hey @FelixMalfait, won't I get points for pointing out the bugs? :)

**Comment by Bonapara** [comment]
Thanks for this improvement idea @Khaan25!
