### ISSUE TITLE
Use `<a>` or `role=button` for Chip Navigation

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7817]
# Current Behavior

The chips are made with `div`.

![CleanShot 2024-10-18 at 11 01 08](https://github.com/user-attachments/assets/bab17548-aa66-4809-a702-ce442774598c)

# Desired Behavior

Ideally, use an `<a>` element when chips are used as navigation items. Otherwise, add `role=button`.

**Comment by Bonapara** [comment]
@lucasbordeau, should we implement `<a>` tags across all chips, or are some not designed for navigation?

**Comment by harshit078** [comment]
@Bonapara, mind if I take this up ? Already working in this area

**Comment by Bonapara** [comment]
Sure @harshit078, thanks for contributing!

**Comment by Khaan25** [comment]
Hey @Bonapara, Let me know if times up and I can contribute to this  🙌
