### ISSUE TITLE
Refreshing Page makes switch to light mode

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7819]
## Bug Description

- Currently, when the selected theme is selected dark mode on doing a page refresh, for a few seconds the page loads in light mode before reverting to dark mode again.
- This behaviour is only noticed when appearance is dark mode. On light mode no such bug is reported.

Edge Case  - If the session is left in background for a long time and user refreshes the page then the appearance switches to light mode.

## Current Behaviour

https://github.com/user-attachments/assets/416f83cd-bce5-4307-b339-3bb519967eb6

https://github.com/user-attachments/assets/4eded128-0a4a-452b-95ae-ec4be6f58fba

## Expected behavior

- Appearance should not be affected on reload

**Comment by harshit078** [comment]
## Approach

- It is seen that only in dark mode, **Light-noise.png** loads before **dark-noise.png** on refresh. Whereas in Light mode **dark-noise.png** never loads.
- use of SSR with the help of `localStorage`. We can use   `localStorage.setItem` which would load the required theme immediately on reload.

@Bonapara, what's your take on this ?

**Comment by Bonapara** [comment]
I think this is a regression, this use to work fine. @charlesBochet wdyt?

**Comment by FelixMalfait** [comment]
@Bonapara I think this was already there - see https://github.com/twentyhq/twenty/issues/5295#issuecomment-2147836101

**Comment by talibraath** [comment]
Please assign me. I can fix this.

**Comment by FelixMalfait** [comment]
@harshit078 I'll close this one to keep #5295 ; Thanks!
it's something to fix long-term but this will be a fairly difficult issue. I don't think it's worth hardcoding it in localstorage as a hack
