### ISSUE TITLE
There should be 4px gap in tag and count in kanbar board column header

### ISSUE THREAD

**Issue by NitinPSingh** [twentyhq/twenty#7821]
## There should a gap of 4px in tag and count 

in kanban board

Current behaviour:
![Screenshot 2024-10-18 153342](https://github.com/user-attachments/assets/4b2edfa6-7832-4d5c-8776-b36b018e5e60)

figma 
![Screenshot 2024-10-18 144328](https://github.com/user-attachments/assets/60e531fe-c384-4f37-a20c-9abb62f29e4f)

## Expected behavior

![Screenshot 2024-10-18 153624](https://github.com/user-attachments/assets/b7bb86a6-717c-4b0e-b212-a2f75cd46901)

**Comment by NitinPSingh** [comment]
i will take this

**Comment by Bonapara** [comment]
Thanks for raising this issue, @NitinPSingh. You have laser-sharp vision! 🔬
