### ISSUE TITLE
API requests in metadata API gives empty object (500 Internal server error)

### ISSUE THREAD

**Issue by Hitarthsheth07** [twentyhq/twenty#7831]
## Bug Description

Most of the API requests are not working. Check https://twenty.com/developers/rest-api/metadata#/paths/objects

![image](https://github.com/user-attachments/assets/758236f0-68e4-4736-9cc1-64200ed35319)

## Expected behavior

The request should return an example object. 

![image](https://github.com/user-attachments/assets/f402b6fc-ec57-4a0e-a0b7-6098a345c964)

**Comment by shodgson** [comment]
Most API requests are still not working in v0.32.2 for both Core and Metadata API.
The /open-api/ endpoints work, but the /rest/ endpoints result in a `500 Internal Server Error`

**Comment by BOHEUS** [comment]
@Bonapara this issue can be closed as API is working properly

**Comment by shodgson** [comment]
Confirmed that the Metadata API is working in v0.32.3. However, the Core API is returning 403 errors. I have created a separate issue ([#8449](https://github.com/twentyhq/twenty/issues/8449)) if you would like to close this one.
