### ISSUE TITLE
Alignment of the logo isn't correct

### ISSUE THREAD

**Issue by Khaan25** [twentyhq/twenty#7833]
## Bug Description

![image](https://github.com/user-attachments/assets/e099e69e-7a64-483b-8175-72a85531fca8)

## Expected behavior

It should be aligned with the rest of the menu items

**Comment by harshrajeevsingh** [comment]
@Khaan25 I can't reproduce it. What browser are you using? Although I checked it on both Chrome & Firefox.

**Comment by dishafaujdar** [comment]
@Khaan25 can i work on it ?

**Comment by Khaan25** [comment]
Can you reproduce it?

**Comment by FelixMalfait** [comment]
I also can't reproduce it (Chrome)

**Comment by Bonapara** [comment]
Cannot reproduce on main

**Comment by Bonapara** [comment]
I'm closing this, but please comment, and I'll reopen it if you experience the issue too!

**Comment by Khaan25** [comment]
@Bonapara I can still see this on production
![image](https://github.com/user-attachments/assets/9469d006-d8d2-4ec8-b700-4e2469839b62)
