### ISSUE TITLE
[🕹️]Design a new logo for Twenty (300 points)

### ISSUE THREAD

**Issue by sahiladit** [twentyhq/twenty#7834]
### What side quest or challenge are you solving?

Design a new logo for Twenty

### Points

300

### Provide proof that you've completed the task

![WhatsApp Image 2024-10-19 at 12 17 17 AM](https://github.com/user-attachments/assets/34d8edba-7499-4656-917c-02b2d76b7397)

**Comment by Bonapara** [comment]
Sorry @sahiladit cannot accept this logo (doesn't make sense + looks AI generated) Thanks for trying though!

**Comment by sahiladit** [comment]
@Bonapara New logo:
![PaperMark](https://github.com/user-attachments/assets/7643f426-6fb3-468a-a9ae-acfec5e95bfe)
