### ISSUE TITLE
[🕹️] ossgg: side-quest and design challenges

### ISSUE THREAD

**Issue by adityadeshlahre** [twentyhq/twenty#7848]
### What side quest or challenge are you solving?

- Design a poster promoting Twenty 
![postPRO](https://github.com/user-attachments/assets/29ce7858-5d81-4319-bc49-fe185266980a)

- Gif Magic 
https://github.com/user-attachments/assets/3a0762f9-da09-47f4-b87d-9a17ad221f5b

- Meme Magic
![977ros](https://github.com/user-attachments/assets/d5614a2e-e42f-4330-bdbe-4f85e3071bcc)

- Share a tweet about your favorite feature in Twenty
[tweet](https://x.com/adityadeshlahre/status/1847622457332486402)

- Initial [tweet](https://x.com/adityadeshlahre/status/1847621397578756196)

### Points

- poster : 300
- meme : 150
- gif : 150
- best feat : 50
- retweet : 50 

# Total points : 700 points

### Description

tweets and Design

### Provide proof that you've completed the task

- promoting post [tweet](https://x.com/adityadeshlahre/status/1847624791026516169)
- gif [tweet](https://x.com/adityadeshlahre/status/1847624173243265025)
- meme [tweet](https://x.com/adityadeshlahre/status/1847623400354717886)
- best feat [tweet](https://x.com/adityadeshlahre/status/1847622457332486402)
- initial tweet [tweet](https://x.com/adityadeshlahre/status/1847621397578756196)

**Comment by Bonapara** [comment]
Thanks for all your work @adityadeshlahre, awarding 500 points for it
