### ISSUE TITLE
Proper HTTP methods for webhooks

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7852]
Right now, webhooks are using only POST method for all actions, be it create, update or delete, and sends information in body/payload what happened to specific object/record. While this solution works fine, it's possible to elevate user's experience by differentiating whether object was created/updated/deleted by using corresponding [HTTP methods](https://prismatic.io/blog/anatomy-webhook-http-request/#method) (POST for create, PATCH for update, DELETE for delete)

**Comment by ehconitin** [comment]
@martmull wdyt?

**Comment by martmull** [comment]
Hey, we can discuss that. Probably not that obvious 
![image](https://github.com/user-attachments/assets/a5386d46-3ba9-420d-a935-caedd94965d0)

https://prismatic.io/blog/anatomy-webhook-http-request/

![image](https://github.com/user-attachments/assets/ed03733b-3616-4725-9bf9-de40a0f87f01)
https://optoro.redoc.ly/content/webhooks/

**Comment by FelixMalfait** [comment]
I'll close this because on most apps I've used it's always been POST (e.g. Stripe). I don't think it would make it easier to go against the norm. But thanks a lot @BOHEUS for always pushing us to go further :)
