### ISSUE TITLE
[🕹️] Design a new logo for Twenty (300 points)

### ISSUE THREAD

**Issue by naaa760** [twentyhq/twenty#7853]
### What side quest or challenge are you solving?

Design a new logo for Twenty

### Points

300

### Provide proof that you've completed the task

![Untitled design(3)](https://github.com/user-attachments/assets/cd558138-b266-459b-a1d7-617c4483765f)

**Comment by Bonapara** [comment]
GPT doesn't count @naaa760 + not looking like a logo ;) 
 Thanks for contributing
