### ISSUE TITLE
[🕹️Follow Twenty LinkedIn & X/Twitter Pages (0 Point),]Like and retweet the side quest post of Twenty.

### ISSUE THREAD

**Issue by tejaslakade99** [twentyhq/twenty#7856]
### What side quest or challenge are you solving?

Follow Twenty LinkedIn & X/Twitter Pages (0 Point),Like and retweet the side quest post of Twenty.

### Points

0+50=50

### Provide proof that you've completed the task

# Linkedin:
![Screenshot 2024-10-19 at 8 15 25 PM](https://github.com/user-attachments/assets/db103ff0-6feb-4824-a3c1-ddd6a987f65a)

# X/Twitter:
![Screenshot 2024-10-19 at 8 15 49 PM](https://github.com/user-attachments/assets/f624a069-4fc3-4676-8444-9087d8b2b366)

# Like and retweet the side quest post of Twenty
![378076032-dcbc6c3f-bd25-48e9-ae1e-fa4a800c2eab](https://github.com/user-attachments/assets/21212945-9d6a-456a-ba2a-20c883aebb17)

**Comment by Bonapara** [comment]
Thanks for contributing @tejaslakade99!
