### ISSUE TITLE
[🕹️]Meme Magic (150 Points) and Gif Magic (150 Points)

### ISSUE THREAD

**Issue by tejaslakade99** [twentyhq/twenty#7858]
### What side quest or challenge are you solving?

Meme Magic (150 Points) and Gif Magic (150 Points)

### Points

150+150=300

### Description

Meme Magic (150 Points) and Gif Magic (150 Points)

### Provide proof that you've completed the task

# Meme
![supermeme_20h40_29](https://github.com/user-attachments/assets/053214b7-ab01-4d26-95cc-9fc821e5442e)
# Giffy
![supermeme_20h42_39](https://github.com/user-attachments/assets/2c43c7d4-e007-4bf0-951d-024295d99cdb)

**Comment by Bonapara** [comment]
@tejaslakade99 did you share them on X? Cannot see links

**Comment by tejaslakade99** [comment]
Yes, I did share them.

Here are the links 

https://x.com/TejasLakadeX2/status/1848309557149290902?t=cGxs44GjI6fjH9nosrWO2Q&s=19

https://x.com/TejasLakadeX2/status/1848309349610873259?t=etSJpX3h1ptHE-b6tD5wSw&s=19

**Comment by Bonapara** [comment]
Sorry @tejaslakade99 I can't award points for them (Don't seem related to Twenty)

**Comment by tejaslakade99** [comment]
As part of the Side Quest for Meme Magic, the objective is to creatively integrate the number 20 into a meme, drawing a reference to April 2020, marking the onset of the COVID-19 pandemic. I have designed a meme centered around the theme of the year 2020 and its association with the pandemic.


![Screenshot_20241021-180748_Chrome.png](https://github.com/user-attachments/assets/4e724f14-f392-4b41-a97c-6f6d0180303a)

For the Gif Magic I will create a different one by using twenty technology concept.

@Bonapara
