### ISSUE TITLE
`//` can't be typed in URL in API docs

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7861]
As per title, `//` can't be typed in URL in REST & GraphQL API docs when "Other" is selected

**Expected:** `//` can be typed in URL so user can type `https://` without any problems

**Comment by Bonapara** [comment]
@FelixMalfait, do you think you might have a fix for this?

**Comment by FelixMalfait** [comment]
/award 100 to @BOHEUS for reporting the issue

**Comment by FelixMalfait** [comment]
https://github.com/twentyhq/twenty/blob/2f72e22ff95ee77f4650b609c59d83dd307c938b/packages/twenty-website/src/app/_components/playground/token-form.tsx#L79 <- this is the part that needs to be updated. Let's just remove the trimming part.

**Comment by FelixMalfait** [comment]
/oss.gg 50
