### ISSUE TITLE
[🕹️] 🌟 Starry-eyed Supporter

### ISSUE THREAD

**Issue by aritradevelops** [twentyhq/twenty#7862]
### What side quest or challenge are you solving?

Starry-eyed Supporter

### Points

150

### Description

# Profiles
1. https://github.com/finallyRaunak/
2. https://github.com/arijit192/
3. https://github.com/suparnacodes/
4. https://github.com/Biprodipnh/
5. https://github.com/Reyden49q1/

# Screenshots that they confirmed

<img width="630" alt="Screenshot 2024-10-17 at 9 44 56 PM" src="https://github.com/user-attachments/assets/1cc27c79-ec38-4788-b7da-4f250a8efd24">
<img width="924" alt="Screenshot 2024-10-17 at 9 46 23 PM" src="https://github.com/user-attachments/assets/7584c121-8e23-4c84-b000-1b2e1f980f16">
<img width="939" alt="Screenshot 2024-10-17 at 9 52 13 PM" src="https://github.com/user-attachments/assets/8739b44c-8946-4a7d-89b2-79da2eec24c4">
<img width="949" alt="Screenshot 2024-10-17 at 9 54 09 PM" src="https://github.com/user-attachments/assets/2df689ee-4c33-444f-9add-36b13120c33b">
<img width="924" alt="Screenshot 2024-10-17 at 9 55 36 PM" src="https://github.com/user-attachments/assets/4728b12e-0418-4023-b77e-e3ac9baf5787">

### Provide proof that you've completed the task

# Proof (Screenshots from their end)
<img width="1430" alt="image_2024_10_13T10_30_10_055Z" src="https://github.com/user-attachments/assets/5fbfdc76-4624-451b-bc98-0705347d5c69">
<img width="1440" alt="3" src="https://github.com/user-attachments/assets/c434848c-8616-4432-8a09-8c246655cd1f">

![1](https://github.com/user-attachments/assets/53cd5217-d5aa-47ac-a845-6f2c765b6f1f)
![2](https://github.com/user-attachments/assets/794fcacd-ee2f-4a5f-884f-fecad6a4a9dc)
![3](https://github.com/user-attachments/assets/dae6acdd-4426-4ffb-ab03-945046cad9c7)

**Comment by Bonapara** [comment]
Thanks for sharing Twenty @aritradevelops!
