### ISSUE TITLE
[🕹️] Follow Twenty LinkedIn & X/Twitter Pages

### ISSUE THREAD

**Issue by Sa1-Codes** [twentyhq/twenty#7865]
### What side quest or challenge are you solving?

Follow Twenty LinkedIn & X/Twitter Pages

### Points

0

### Description

followed twenty on linkedin and twitter/X

### Provide proof that you've completed the task

twitter:

![image](https://github.com/user-attachments/assets/fa5dd18b-5ec4-4c22-8e7a-4fdeb306e020)

linkedin:
![image](https://github.com/user-attachments/assets/77da0ac8-d5ca-40a5-860a-3273a4138cec)

**Comment by FelixMalfait** [comment]
Thank you!!!
