### ISSUE TITLE
Kanban columns margin no longer extend to the bottom

### ISSUE THREAD

**Issue by ehconitin** [twentyhq/twenty#7868]
## Bug Description
As per title

<img width="1389" alt="Screenshot 2024-10-20 at 00 36 04" src="https://github.com/user-attachments/assets/6e5aa53f-3553-4aba-a204-0dbeb40bb846">

## Expected behavior

Column margins should extend to the bottom.

<img width="1051" alt="Screenshot 2024-10-20 at 00 40 31" src="https://github.com/user-attachments/assets/0b16506d-3ad6-4c37-bd1b-44782f31f3e8">

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=24955-194300&node-type=frame&t=IlVBRHG7XrFQOD7c-0

**Comment by ehconitin** [comment]
/oss.gg 150

**Comment by harshrajeevsingh** [comment]
@ehconitin can you assign me this? My other PR is already in review for the past 3 days.

**Comment by VAIBHAVSING** [comment]
Can you elaborate details with this issue

**Comment by ayesparshh** [comment]
please assign me this

**Comment by ehconitin** [comment]
@VAIBHAVSING 
The pointed margins should go all the way to the bottom. 

<img width="1337" alt="Screenshot 2024-10-21 at 14 11 08" src="https://github.com/user-attachments/assets/648c1f80-5473-49b2-aa62-11f03c37f878">

**Comment by Bonapara** [comment]
💯 Yes they should! 👀🔬

**Comment by charlesBochet** [comment]
This actually looks solved to me, I cannot reproduce on main. Can you @ehconitin?

**Comment by charlesBochet** [comment]
Oh yes, true!

**Comment by harshrajeevsingh** [comment]
@Bonapara I fixed it. Can I raise a PR?

**Comment by ehconitin** [comment]
Sure @harshrajeevsingh ,go ahead!
