### ISSUE TITLE
[🕹️] Design a new logo for Twenty

### ISSUE THREAD

**Issue by rajeevDewangan** [twentyhq/twenty#7874]
### What side quest or challenge are you solving?

Design a new logo for Twenty

### Points

300

### Description

link to post : https://x.com/rajeevdew/status/1847862611976864180
Created a new logo design for Twenty, tweeted my design, and mentioned @twentycrm

### Provide proof that you've completed the task

new logo : 
![Screenshot 2024-10-20 101737](https://github.com/user-attachments/assets/a30f31dc-f480-4d22-be2d-907dbffcc621)
post : 
![Screenshot 2024-10-20 101948](https://github.com/user-attachments/assets/de0da079-ae23-495c-a1ec-4088352fb54a)

**Comment by Bonapara** [comment]
Thanks for your logo @rajeevDewangan! Awarding 50 for it
