### ISSUE TITLE
[🕹️] Meme Magic

### ISSUE THREAD

**Issue by rajeevDewangan** [twentyhq/twenty#7875]
### What side quest or challenge are you solving?

Meme Magic

### Points

150

### Description

Crafted a meme where the number twenty plays a role.
Tweeted it, and tag @twentycrm.

### Provide proof that you've completed the task

![Screenshot 2024-10-20 103336](https://github.com/user-attachments/assets/bec0d392-1ac5-4f8e-b377-2c263a85b66e)
link to post : https://x.com/rajeevdew/status/1847866102833172772

**Comment by poorvibajpai** [comment]
@rajeevDewangan  I have created PR for this issue, PR no. #7878. Need someone to review the PR please verify and approve it.

**Comment by rajeevDewangan** [comment]
I am not a member I can't do it

**Comment by Bonapara** [comment]
Thanks for your Meme @rajeevDewangan ;)

**Comment by poorvibajpai** [comment]
@Bonapara I have created PR for this issue, PR no. https://github.com/twentyhq/twenty/pull/7878. Need someone to review the PR please verify and approve it.
