### ISSUE TITLE
[🕹️]side quest: Meme Magic and Gif Magic

### ISSUE THREAD

**Issue by Naprila** [twentyhq/twenty#7876]
### What side quest or challenge are you solving?

Meme Magic: Craft a meme where the number twenty plays a role.
Gif Magic: Create a gif related to Twenty 

### Points

150  + 150

### Description

Created a meme & gif and tweeted on X.
Meme Link: https://x.com/mkprasad_821/status/1847877149857870164
Gif Link: https://x.com/mkprasad_821/status/1847877615102603561

### Provide proof that you've completed the task

<img width="1369" alt="Screenshot 2024-10-20 at 11 17 20 AM" src="https://github.com/user-attachments/assets/5343f569-afbe-4c0c-8d50-d032603d9a22">
<img width="1369" alt="Screenshot 2024-10-20 at 11 19 03 AM" src="https://github.com/user-attachments/assets/7e4ebcb2-50b4-46b8-ab97-97d0cf56e422">

**Comment by Bonapara** [comment]
Thanks for your contributions @Naprila loved the fire one 😅
