### ISSUE TITLE
Filter/sort button position when scrolling horizontally

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#788]
Filter/Sort should remain on the right side as you scroll horizontally

See issue:
<img width="1127" alt="Screenshot 2023-07-21 at 08 56 46" src="https://github.com/twentyhq/twenty/assets/6399865/a3e8a978-570d-4f96-af0f-5926c38f3da5">

Cc @Bonapara

**Comment by AdityaPimpalkar** [comment]
Hi @FelixMalfait, Can I take this up? Thanks!
