### ISSUE TITLE
Wrong command in Twenty container 

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7886]
[twentyhq/twenty](https://hub.docker.com/layers/twentycrm/twenty/main/images/sha256-54ae68564a7641f79b1160342f969ae1b63b8fb8bb7fa11fe67d22aab5034dd9?context=explore) container uses `npm install` command for installing packages while in docs it's clearly stated that `npm` shouldn't be used for installing but `yarn`, please fix this command
![image](https://github.com/user-attachments/assets/e4b5b0d3-29d5-46a4-bf2e-4f23efc97e08)
![image](https://github.com/user-attachments/assets/bd329579-f2d9-4a4b-ae88-963b879af421)

**Comment by SShanks451** [comment]
@BOHEUS please assign this issue to me

**Comment by Bonapara** [comment]
@charlesBochet WDYT?

**Comment by charlesBochet** [comment]
This is to install tsx globally in the production container build, I think it's fine and not causing any trouble :)
