### ISSUE TITLE
Date Picker flips above even when there is enough space.

### ISSUE THREAD

**Issue by harshrajeevsingh** [twentyhq/twenty#7897]
### Bug Description

The date picker flips to the top position even when sufficient space is below the table cell.

[Screencast from 2024-10-20 23-37-55.webm](https://github.com/user-attachments/assets/1002fec3-388c-4595-b936-35f4e69a865d)

### Expected

 It should only flip when there isn't enough space below to accommodate it.

## Important

This bug is only reproducible when the number of records in the table is low, just like in the above video. It works as expected when the records are larger in number. Look the screencast down below, it's working fine I added more records.

[Screencast from 2024-10-21 00-10-41.webm](https://github.com/user-attachments/assets/6dd1211d-b626-42a7-9671-495e06854f4a)

**Comment by harshrajeevsingh** [comment]
@Bonapara I'm working on this :)

**Comment by Bonapara** [comment]
Good point @harshrajeevsingh, thanks for raising this issue 🙏
