### ISSUE TITLE
I can create a new pipeline

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#790]
As of today we seed a default pipeline when you create a workspace but we don't allow you to create a second pipeline.

The underlying idea is that maybe 2 types of opportunities tracked by two different teams can be attached to a company.
(E.g. one team is trying to upsell them with product X, while another is working on the renewal of product Y)

**Comment by AdityaPimpalkar** [comment]
Hey folks! Any update on this? 🙂

**Comment by FelixMalfait** [comment]
@AdityaPimpalkar Still no design ready! I agree it'd be cool to prioritize it

**Comment by Bonapara** [comment]
We'll need to wait for the Opportunities refactoring to handle this correctly. Kanbans will be a view type that can be added to any objects with an enum field.

**Comment by FelixMalfait** [comment]
@Bonapara ; There are currently 3 objects : Pipeline, PipelineProgresses, PipelineStages.
Currently the opportunities view is displaying the PipelineProgresses groupedBy PipelineStage.
The problem above is that I can create a PipelineProgress or a PipelineStage but I cannot create a Pipeline through the UI. I feel that it's not really that correlated with the problem you describe. Even if PipelineProgress can be seen as a listview, that won't change the fact that we can't create a pipeline. And I feel that wouldn't impact the design. But maybe I'm missing something

**Comment by Bonapara** [comment]
I believe this relates to refactoring, aiming to enable users to create a pipeline for any "enum." If we create a second pipeline in opportunities, we would need to create a new "enum" on the opportunity object. This behavior should apply universally to all object types.

We need to determine the user experience for this, such as whether to create the enum first and then the view, or if it's possible to create both the view and enum simultaneously.

Maybe I'm also missing something, happy to talk about what you have in mind.

**Comment by FelixMalfait** [comment]
Todo:
- rename pipeline_stages to enums, drop column "type", add a column "name" (fill with name=stage)
- rename pipeline_progresses to opportunities, update pipelineStageId to stageEnumId 
- rename pipeline to opportunity_type
- allow creating new opportunity types (frontend)

Need more detailed tech specs before we can tackle this / probably not a good first issue!
