### ISSUE TITLE
Country Select Picker Text Overflow Issue

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7906]
# Current behavior

Address field Country Select picker doesn't crop values

![image](https://github.com/user-attachments/assets/7d13786b-1a09-4bc9-950f-dced46fb2b44)

# Desired Behavior

The text should fill the container and be truncated with "..." when it exceeds the available space.

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by prathameshpatil5181** [comment]
@Bonapara Can you please assign this to me?

**Comment by Saathvik-Sheerla** [comment]
how to reproduce the issue?
