### ISSUE TITLE
Tooltip lacks information in Number model

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7908]
## Bug Description

- In Settings/Data Model/Number, tooltip is present but has no information on hover and lacks color
- Reset button in sort lacks padding making it difficult to view and click on

## Current behaviour
<img width="76" alt="Screenshot 2024-10-21 at 3 37 07 PM" src="https://github.com/user-attachments/assets/99c6ecf1-344a-4b97-8bdb-7e170c30aae4">

<img width="245" alt="Screenshot 2024-10-21 at 3 39 53 PM" src="https://github.com/user-attachments/assets/3a385938-1c00-4b3c-84aa-c616ee2cbadd">

## Expected behavior

<img width="64" alt="Screenshot 2024-10-21 at 3 38 04 PM" src="https://github.com/user-attachments/assets/c4601939-0667-4aad-af0c-947047435cce">

**Comment by sahilshityalkar** [comment]
assign this issue to me. I'd love to work on it!

**Comment by Bonapara** [comment]
Thanks @harshit078, I think it lacks color because it is in its disabled state, so that's normal, even though it could be improved.

The tooltip should be:
`Sets decimal precision for numeric field values, e.g., 12.34.`

So this issue is about fixing the Reset button size to 20px and setting the tooltip.

**Comment by Bonapara** [comment]
Sure @sahilshityalkar, thanks for contributing!

**Comment by FelixMalfait** [comment]
Seems like this isn't relevant anymore with the new design and changes by @guillim actually! 

![Image](https://github.com/user-attachments/assets/7d223a72-fae3-4df0-b223-3f17a1e77bd6)
