### ISSUE TITLE
Drag to select kanban cards

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#791]
We should be able to click and hold to draw a selection of cards

Related: https://github.com/twentyhq/twenty/issues/413, https://github.com/twentyhq/twenty/issues/792

**Comment by Bonapara** [comment]
# Design:
![Image](https://github.com/twentyhq/twenty/assets/19412894/2c65e417-9979-4024-a5d4-51bdb559c263)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=6512-56182&mode=design&t=GMBHxG3P5dZsG4iz-4

**Comment by abhip167** [comment]
Is this issue still valid ?
If yes, I would like to take it.

**Comment by Bonapara** [comment]
A first version has been implemented. Only it doesn't check the checkboxes:

<img width="653" alt="Screenshot 2023-08-11 at 11 08 57" src="https://github.com/twentyhq/twenty/assets/19412894/b6be096e-b689-43dd-86d5-02134feb8879">

**Comment by Bonapara** [comment]
I think so, closing it under your control @charlesBochet

**Comment by charlesBochet** [comment]
yes!
