### ISSUE TITLE
Ex: In DarkMode, a blank square appears in bottom right corner while scrolling

### ISSUE THREAD

**Issue by Crims-on** [twentyhq/twenty#7912]
## Bug Description

I get a non-verbose 500 error when trying to use the Create One Company and Create One Person functionalities. The request is directly copied from the documentation site yet error each time.

API seems to be broken

## Expected behavior

Company or person entry created, or a verbose 500 error if it is a problem on my end

**Comment by Bonapara** [comment]
I think this is because you didn't change the relation ID (e.g. `company id` for `create one person`), which is a fake one set by default.

**Comment by Bonapara** [comment]
Strange then couldn't reproduce, it worked for me:

![CleanShot 2024-10-21 at 14 06 12](https://github.com/user-attachments/assets/898e1a44-984c-4a14-ab62-2ca4f41c8ede)

![CleanShot 2024-10-21 at 14 07 09](https://github.com/user-attachments/assets/85cddd19-36e8-40c0-95d1-c665e1329234)
