### ISSUE TITLE
Got an issue on the Docker Compose 

### ISSUE THREAD

**Issue by unrealandychan** [twentyhq/twenty#7926]
I tried to deploy on a ec2 server or on my Mac , but got this error:

server-1  | [Nest] 1  - 10/21/2024, 6:05:18 PM   ERROR [ExceptionHandler] connect ECONNREFUSED 127.0.0.1:6379
server-1  | Error: connect ECONNREFUSED 127.0.0.1:6379
server-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)

Checked that the Redis is running okay with the redis-cli, should be something wrong on the Server side.

And check TAG with v0.31.0 and latest

**Comment by ehconitin** [comment]
You need to setup redis for cache.
https://twenty.com/developers/local-setup

**Comment by ehconitin** [comment]
I think you are missing redis env variables.
Could you share server .env?

**Comment by corrosive4354** [comment]
Make sure the Redis service is configured correctly in your Docker Compose file. Here is an example configuration:

version: '3'

services:

redis:

image: redis:latest

ports:

- "6379:6379"

server:

image: your-server-image

depends_on:

- redis

environment:

- REDIS_HOST=redis


- REDIS_PORT=6379
Here, the server service depends on the redis service and specifies the host and port of Redis through environment variables.

In addition, you can try to use [Servbay](servbay.com) to replace docker, which is better on mac and has higher compatibility
