### ISSUE TITLE
Rename CommentThread to Activities

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#793]
There is some tech debt because commentThread don't reflect what they were be built for and should be renamed "activities" across the codebase instead.

**Comment by charlesBochet** [comment]
Breaking change here, exceptionaly we accept it. We will need to deploy during low traffic

**Comment by A-Alanbri** [comment]
> There is some tech debt because commentThread don't reflect what they were be built for and should be renamed "activities" across the codebase instead.
