### ISSUE TITLE
[🕹️] bug report vertical scrollbar in https://twenty.com/developers

### ISSUE THREAD

**Issue by adilkadivala** [twentyhq/twenty#7932]
## Bug Description

cA vertical scrollbar see in a https://twenty.com/developers sidebar, That seems like bad design practice

**Example:** 

![twentydesingBug](https://github.com/user-attachments/assets/d138fe05-d4b5-4664-b430-b263c602b554)

```

## Expected behavior

overflow-x should be hidden

**Example:** 
```
![bugbehaviour](https://github.com/user-attachments/assets/84a34874-2411-4ca1-80a7-57904584dd14)

```

## Technical inputs
<div class="emotion-cache-itc2b0" style="
    overflow-x: hidden;     instead of overflow : hidden
">flex



```

**Comment by Bonapara** [comment]
I can't reproduce this issue. How did you make it appear? @sans-byte, can you reproduce it?

**Comment by sans-byte** [comment]
Go to the link provided [https://twenty.com/developers ](url) there we can see the vertical scroll bar below the sidebar .

**Comment by Bonapara** [comment]
Ok assigning you @sans-byte if you find a fix! Thanks for contributing!

**Comment by sans-byte** [comment]
Finding : Issue can only be seen on the windows not on mac.
