### ISSUE TITLE
I can use "enter" key to navigate in login/signup forms

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#794]
It's not possible to use the "enter" key to navigate to the next step in the signup/login forms. I would like to be able to do everything with the keyboard only.

Note: there is a custom hook for hotkeys in the codebase already

<img width="549" alt="Screenshot 2023-07-21 at 16 24 00" src="https://github.com/twentyhq/twenty/assets/6399865/adce8f02-266e-4a2a-b763-e57b83888aae">

**Comment by charlesBochet** [comment]
The login form is being rebuilt, let's hold on this one!

**Comment by charlesBochet** [comment]
This has been fixed
