### ISSUE TITLE
Glitch when searching relation picker

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7957]
# Bug description

Relation picker is flashing each time a new letter is getting typed

https://github.com/user-attachments/assets/ca3263f6-ad38-4283-9109-fbe3dcb6efb2

# How to reproduce

Type anything in a relation picker

**Comment by Bonapara** [comment]
Related to https://github.com/twentyhq/twenty/issues/7511?

**Comment by sans-byte** [comment]
Hi, I have solved this issue can I raise a PR for this? @Bonapara Please assign it to me

**Comment by ehconitin** [comment]
@sans-byte yes please!

**Comment by FelixMalfait** [comment]
Made a comment in the PR, thanks a lot for the effort but I don't think that's what we want

**Comment by sans-byte** [comment]
https://github.com/user-attachments/assets/2c26aca2-e8af-4ef4-a721-fbce1bd84ad3

@FelixMalfait is this one better ? I took your suggestion of result -> white -> result and also tested it for different size results

**Comment by FelixMalfait** [comment]
@sans-byte thanks but no it's stil blinking each time you type a letter :), we want to avoid that

**Comment by sans-byte** [comment]
Yeah, each time we type a letter request is going out which is getting it into a loading state, I can fix it by introducing small debounce on input.
Or else can you please suggest me how to fix it? @FelixMalfait

**Comment by FelixMalfait** [comment]
We don't want a debounce, that would be a hack :) ; I don't know this component well enough but we should probably remove a condition that hides results based on the loading state or something like that

**Comment by sans-byte** [comment]
https://github.com/user-attachments/assets/5757bea5-19dd-4cdc-a8c7-5933ce40393d

**Comment by sans-byte** [comment]
Sure will raise the PR

**Comment by harshrajeevsingh** [comment]
@FelixMalfait This can be closed now.

**Comment by FelixMalfait** [comment]
thanks!
