### ISSUE TITLE
Relation should not move once openened

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7959]
# Bug description

Relation pickers are repositioned dynamically as text is typed. We should choose their opening position dynamically, but once opened, they should remain in the same place.

https://github.com/user-attachments/assets/8b52f952-321e-4825-adda-0df3b3be3691

# How to reproduce

Open a relation picker near the edge of the screen on a record page.

**Comment by ketanMehtaa** [comment]
please assign me @Bonapara.

**Comment by Bonapara** [comment]
You can give it a try, @ketanMehtaa, but I think it's quite challenging since we rely on an external library. Let's wait for @charlesBochet to confirm.

**Comment by harshrajeevsingh** [comment]
@Bonapara I can see why it's happening since I solved some related issues. Should I make a PR?

**Comment by Bonapara** [comment]
Yes thanks @harshrajeevsingh, and maybe you can sync with @ketanMehtaa if he still wants to work on it?

**Comment by charlesBochet** [comment]
I think it's doable with useFloating, happy to give hints if needed

**Comment by ketanMehtaa** [comment]
@harshrajeevsingh  I am not working on it right now , please make PR if you are intrested.
