### ISSUE TITLE
Disable Continue Button for Invalid Email in Sign in/Sign up

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7967]
# Current Behavior

I can enter an invalid email in the `Sign in` / `Sign up` flows and proceed to the password step.

https://github.com/user-attachments/assets/f346ef33-438e-4dd6-84ff-c5716a21cdcc

# Desired Behavior

The `Continue` button should stay disabled until a valid email is entered.

**Comment by Khaan25** [comment]
Hey @Bonapara, Yes I want to work on it

**Comment by yadavshubham01** [comment]
hey @Bonapara i think we can use zod validation in email

**Comment by Bonapara** [comment]
Sorry @yadavshubham01, I told @Khaan25 he could work on it on the other issue :(
