### ISSUE TITLE
Update 1-click install script to take same source of truth as docker image

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#7968]
See https://github.com/twentyhq/twenty/issues/7768#issuecomment-2419927885
In the install script here: https://github.com/twentyhq/twenty/blob/main/install.sh
We take the `docker-compose.yml` in the main branch and not the one that matches the version given by the user. 
We should instead take the file from the Github branch for that version (tbc how it works for sub-version / if there's no exact match?)

**Comment by yadavshubham01** [comment]
hey @FelixMalfait can you please provide more context of this issue
