### ISSUE TITLE
[🕹️] Meme Magic - Side Quest

### ISSUE THREAD

**Issue by techwizard31** [twentyhq/twenty#7981]
### What side quest or challenge are you solving?

I made a meme on twenty

### Points

50

### Provide proof that you've completed the task

![Twenty Meme](https://github.com/user-attachments/assets/9aa6c733-64c3-465d-ad66-f1ccbf921534)

**Comment by FelixMalfait** [comment]
/award 50
(usually it has to be posted on X + sent through a PR but okay for this time!)
