### ISSUE TITLE
[🕹️] Starry-eyed Supporter

### ISSUE THREAD

**Issue by rajeevDewangan** [twentyhq/twenty#7985]
### What side quest or challenge are you solving?

Starry-eyed Supporter

### Points

150

### Description

github accounts:
https://github.com/umairullah0905
https://github.com/akaswang
https://github.com/umeshs25
https://github.com/giteshsarvaiya
https://github.com/Hamsegg

### Provide proof that you've completed the task

![Screenshot 2024-10-23 124939](https://github.com/user-attachments/assets/5da97ea9-9c65-4b97-8583-18b1b91f4d66)
![Screenshot 2024-10-23 125032](https://github.com/user-attachments/assets/bae505fb-f5db-428c-9a33-abbe6a2fe66d)
![Screenshot 2024-10-23 125102](https://github.com/user-attachments/assets/0fa2d7f5-445d-483d-bf82-23e1446c6393)
![Screenshot 2024-10-23 125133](https://github.com/user-attachments/assets/a1781226-ef6d-462a-9c4a-a700da564d1a)
![Screenshot 2024-10-23 125158](https://github.com/user-attachments/assets/de2d6fa5-90e6-430b-be61-ac0685b34b61)
![yash1](https://github.com/user-attachments/assets/b0b72c8e-6576-4cf2-b4f6-a0c04ce77823)
![gitesh1](https://github.com/user-attachments/assets/3e638bb5-06eb-4380-8023-7529629b8abe)
![umesh1](https://github.com/user-attachments/assets/93f47f72-4f8a-4343-a98d-f63741d93ac8)
![akash1](https://github.com/user-attachments/assets/333643b6-0e29-4891-8ab1-7133da880706)
![umair1](https://github.com/user-attachments/assets/febdee98-34aa-497f-a5b3-584b6a29d685)

**Comment by Bonapara** [comment]
Thanks @rajeevDewangan for spreading the word!
