### ISSUE TITLE
[🕹️]oss.gg related Side Quests & Formbricks Side Quests Multiple 

### ISSUE THREAD

**Issue by r0x5r** [twentyhq/twenty#7990]
### What side quest or challenge are you solving?

oss.gg side quest and form brick side quest multiple

### Points

200

### Provide proof that you've completed the task

1:- Like &[Re-Tweet oss.gg Launch Tweet ](https://x.com/ossgoodgame/status/1841019549183066552)(50 Points): https://x.com/ossgoodgame/status/1841019549183066552 [50]

![image](https://github.com/user-attachments/assets/f59391aa-746c-4a02-87b2-4096964bf97b)

2:-  upvote and comment on[Reddit launch thread] (https://www.reddit.com/r/opensource/comments/1ftwbl9/weve_spent_a_few_months_building_ossgg_to_gamify/) (50 Points): [Post is Locked by Mods so upvoted] [50]

![image](https://github.com/user-attachments/assets/9ce03286-0d0d-4309-9d90-e249a50ecdeb)

3:- follow on X [50]

![image](https://github.com/user-attachments/assets/f4fccfbf-6927-470f-92a4-b3d8595ceb90)

4:- follow on linkedin [50]

![image](https://github.com/user-attachments/assets/fb3bb61c-0781-4d08-a7eb-86f239a5eee3)

**Comment by Bonapara** [comment]
Sorry @r0x5r cannot grant points for this. Don't open issues on several repos for the same quest
