### ISSUE TITLE
[UI Bug] Continue Button Width Doesn't Match Pricing Cards Width

### ISSUE THREAD

**Issue by Botuns** [twentyhq/twenty#7993]
Hi everyone! I'm very new to open source and find it a bit overwhelming, but I noticed this UI issue and wanted to contribute. I'd really appreciate any guidance on open source contribution practices. You can reach me at +2349134516158 or abdulqaharolajide@gmail.com if you'd like to help mentor me!

## Bug Description
The "Continue" button width is inconsistent with the pricing cards above it, creating a visual misalignment. The button appears narrower than the cards, breaking the layout consistency.

![image](https://github.com/user-attachments/assets/d88fb004-3434-470f-8332-355091867852)

## Expected behavior
The "Continue" button should extend to match the full width of the pricing cards container above it, creating a visually consistent layout.

## Technical inputs
- This appears to be a styling issue
- The pricing cards seem to use full container width while the button has a default/restricted width
- Likely fixable by updating the button's CSS width property to match its parent container
- A simple CSS fix like `w-100%/full` might resolve this

Thanks for reviewing my first bug report! Looking forward to learning more about contributing to open source.

**Comment by sans-byte** [comment]
Hi, can you please provide the info on how to reproduce this issue?

**Comment by Botuns** [comment]
@sans-byte , Reproduce this by trying to create a new account then the subscription modal pops out.

**Comment by Bonapara** [comment]
Sorry @Botuns, this isn't a bug; it's intentional as button shouldn't be too wide. Thanks for the report though!

![image](https://github.com/user-attachments/assets/0ce52e21-df2a-47c8-90d0-f7cf5803716b)

**Comment by Bonapara** [comment]
If you want to contribute, maybe you can find another [Good First Issue](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)!

**Comment by Botuns** [comment]
@Bonapara , thank you
