### ISSUE TITLE
UI Inconsistency on smaller screens - Insufficient Padding for Price Card Title

### ISSUE THREAD

**Issue by sans-byte** [twentyhq/twenty#7999]
## Bug Description

On screens with lower resolutions, the title of the price card component appears too close to the surrounding elements. There is a lack of padding above and below the title, causing the UI to look cramped and inconsistent compared to other components. This affects the overall user experience, making the interface less readable and visually appealing.

**Example:** 

https://github.com/user-attachments/assets/c43f9e13-e66f-4709-9aab-5884d22ffe3f

## Expected behavior

The price card title should have consistent padding from both the top and bottom, ensuring sufficient space around the text for better readability and visual alignment with other UI elements.

## Technical inputs
The issue seems to be related to how padding or margin is handled within the price card component on smaller screens. Adjusting the top and bottom padding should resolve this.

**Comment by khuddite** [comment]
@Bonapara Do we still wanna fix this issue?

**Comment by Bonapara** [comment]
Sure, thanks @khuddite! The best thing would be to implement a scroll inside the popup if there is not enough vertical room. We should make sure the modal padding-top stays even on small screen.

**Comment by Bonapara** [comment]
Hi @khuddite, sure! You need to activate the "is billing enabled" flag and set some fake Stripe variables locally.

**Comment by khuddite** [comment]
@Bonapara I set these env variables because they seem required when `IS_BILLING_ENABLED` is true - 
```
BILLING_PLAN_REQUIRED_LINK=https://twenty.com/stripe-redirection
BILLING_STRIPE_API_KEY=replace_me_with_stripe_secret_key
BILLING_STRIPE_WEBHOOK_SECRET=replace_me_with_stripe_webhook_secret
BILLING_STRIPE_BASE_PLAN_PRODUCT_ID=replace_me_with_stripe_product_id
```

However, I am getting this error locally - `[Nest] 19064  - 12/03/2024, 8:27:17 AM   ERROR [ExceptionsHandler] Invalid API Key provided: replace_*********************_key`. It fails because `BILLING_STRIPE_API_KEY` is invalid.

**Comment by khuddite** [comment]
@Bonapara Maybe I can modify front-end code to just display the UI without any functionalities involved. I will see what I can change there to make it show up.

**Comment by khuddite** [comment]
@Bonapara Nvm, I got it working.
