### ISSUE TITLE
Remove empty values from relation picker

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#801]
They should not appear in the relation picker 
(Today there is results with no text, but a color circle or a ray square with a 1 inside)

![Image](https://github.com/twentyhq/twenty/assets/19412894/72aa6158-af1e-4cad-830f-ed58bf9c765d)
![Image](https://github.com/twentyhq/twenty/assets/19412894/3f926465-6965-4627-ac4f-dd3bcb15ea1b)

Check all relation picker components: Check MultiSelect and SingleSelect relation pickers

**Comment by Mbistami** [comment]
Hello, if no one is working on this I can fix it, if you can please assign it to me.
