### ISSUE TITLE
[🕹️] Bug hunter

### ISSUE THREAD

**Issue by sateshcharan** [twentyhq/twenty#8013]
### What side quest or challenge are you solving?

Bug Hunter

### Points

50-150

### Description

In self-hosted setups, twenty-server crashes and restarts frequently, likely due to memory overuse. While the documentation includes a disclaimer, enforcing memory limits in the docker-compose.yml could help prevent this issue:

server:
  image: twentycrm/twenty:${TAG}
  volumes:
    - server-local-data:/app/packages/twenty-server/${STORAGE_LOCAL_PATH:-.local-storage}
    - docker-data:/app/docker-data
  ports:
    - "3000:3000"
  mem_limit: 2g  # Enforce memory limit

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/ff40e16a-3a9c-44dc-b465-2d84aa51725b)

**Comment by Bonapara** [comment]
@Weiko what do you think?
