### ISSUE TITLE
[🕹️]Design a poster promoting Twenty

### ISSUE THREAD

**Issue by Sam-at-code** [twentyhq/twenty#8018]
### What side quest or challenge are you solving?

Design a poster promoting Twenty

### Points

300

### Description

Created a poster that promotes Twenty and shared it on social media.

### Provide proof that you've completed the task

![Purple Modern Software Business Instagram Post](https://github.com/user-attachments/assets/25e93abc-3b39-40db-8bc0-6a15780b7d48)
![Screenshot 2024-10-24 092525](https://github.com/user-attachments/assets/b04d5208-0d7d-46f0-80a0-67f968584fd8)

**Comment by Bonapara** [comment]
Thanks for your poster @SNIDGHA 🙌
