### ISSUE TITLE
bug 🐛 : Mobile Navigation drawer overlays for rightdrawer

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#8025]
## Bug Description

- Currently when number of items in the Activity drawer increases, the navigation bar overlays with the items making it difficult to interact. This also leads to scroll in navigation bar which can be seen on every page.
- When tasks such as RightDrawer is called upon (creating notes,tasks), the navigation bar overlays with the drawer and doesn't interact and scrolls. 

## Current Behaviour

https://github.com/user-attachments/assets/924016bd-d4cc-4b18-ad42-80524db49420

https://github.com/user-attachments/assets/d6e63ef3-124b-49d3-8f05-ac1a6af6cb31

## Expected behavior

- The Navigation bar should work when interacting with Rightdrawer. 

- The navigation bar should stay at its position when Activity is activated.

## Proposal

Approach 1- 
<img width="395" alt="Screenshot 2024-10-24 at 1 51 12 PM" src="https://github.com/user-attachments/assets/4ef46d3a-8d41-4380-9116-5d03f3335250">

- Taking reference from Search, The navigation bar should have the same behaviour resulting in a fixed position at the bottom of screen and Activity bar item scrolls behind the navigation bar.

Approach 2- 

- Taking reference from desktop webapp, when Actitvity drawer is triggered the navigation bar should'nt appear and minimize drawer button should be present. The same should be applied for RightDrawer with navigation bar not appearing when triggered and close icon to be triggered giving it a cleaner look.

- <img width="223" alt="Screenshot 2024-10-24 at 1 57 51 PM" src="https://github.com/user-attachments/assets/bae101fc-2b18-49b2-9dfe-847560cf780f">

- <img width="393" alt="Screenshot 2024-10-24 at 2 00 27 PM" src="https://github.com/user-attachments/assets/72e3798f-a841-4cab-89c0-62298ca349f4">

**Comment by harshit078** [comment]
@Bonapara, whats your opinion on this ?

**Comment by Bonapara** [comment]
Hi @harshit078! I think approach 1 makes more sense. However, I'll close this issue because I believe https://github.com/twentyhq/twenty/issues/7826 will introduce some changes. We should check afterward to see if the bug is still there!
