### ISSUE TITLE
Add ability to add oportunities with a top right "+" icon

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#803]
I should be able to create an opportunity card from the navbar "+" button:

https://github.com/twentyhq/twenty/assets/19412894/36389a74-e217-46f0-9283-de6aa3802a24

See also: https://github.com/twentyhq/twenty/issues/819

**Comment by FelixMalfait** [comment]
Note: the card would go on the column the most on the left

**Comment by Bonapara** [comment]
By default yes, unless you specified a specific step in the menu at the top:

https://github.com/twentyhq/twenty/assets/19412894/8408c966-7412-4945-b3df-760813ec71ff

**Comment by FelixMalfait** [comment]
Ah indeed I missed that! Thanks

**Comment by charlesBochet** [comment]
We have an ongoing refactoring on pipelines, let's wait on this one
