### ISSUE TITLE
Search feature doesn't work in Docs

### ISSUE THREAD

**Issue by Hitarthsheth07** [twentyhq/twenty#8047]
## Bug Description

The search feature in docs for developers.
However it does work for the page:  [twenty/user-guide](https://twenty.com/user-guide)

**Example:** 
https://www.loom.com/share/962f4710901c44a19736d8267922a1ec
## Expected behavior

Steps to reproduce:
Go to [twenty/developers](https://twenty.com/developers)
Click on search and try searching for something

**Comment by ijreilly** [comment]
@Hitarthsheth07 thank you for reporting! 

From my understanding we are using Algolia's docsearch solution for our search engine on twenty website.
We configure indexes corresponding to certain parts of the website that are then crawled by docsearch, filling the index.
The error here is "Index twenty-developer does not exist", the index name being defined in [AlgoliaDocSearch](https://github.com/twentyhq/twenty/blob/main/packages/twenty-website/src/app/_components/docs/AlgoliaDocSearch.tsx) component

I see that before this PR [Migrated developer doc](https://github.com/twentyhq/twenty/pull/5683) we were always looking into user-guide index. Was a new index created along with the PR? Im not sure where this is configured
@FelixMalfait do you have more knowledge here?

**Comment by sans-byte** [comment]
The index names present in Algolia are 
1. twenty-developer-docs ( This is wrong in code twenty-developer is used )
2. twenty-user-guide ( This index name is correct in code that's why this is working )
I would like to work on this assign it to me @ijreilly

**Comment by FelixMalfait** [comment]
@sans-byte how did you find without having access to Algolia haha? Great 👍

**Comment by BOHEUS** [comment]
@FelixMalfait this issue can be closed since changes are merged

**Comment by Hitarthsheth07** [comment]
@sans-byte @FelixMalfait heyy, 

It seems the search issue has been fixed but it raises a new problem. When you visit the link given in the search results by aloglia, you're directed to 404 page. 

This is because the redirect link is invalid. 

![image](https://github.com/user-attachments/assets/8221e79e-613c-423f-a1df-667f9f596a1a)

![image](https://github.com/user-attachments/assets/ffc76095-1f35-4469-8aed-a41e8b090ab5)

**Comment by sans-byte** [comment]
Okay,I Will try fixing it thanks  @Hitarthsheth07

**Comment by FelixMalfait** [comment]
Hey @sans-byte sorry you couldn't have fixed it yourself, it's a setup issue on Algolia. I've just fixed it, we should be good now!

**Comment by sans-byte** [comment]
Yeah Thankyou @FelixMalfait  I was trying it but I figured I can't fix it was going to unassign myself today.
