### ISSUE TITLE
 Cannot read properties of undefined (reading 'firstName')

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#8052]
## Bug Description

- When prompting search model to open, it throws an undefined ts error
- It seems that firstName is going undefined in CommandMenu.tsx

## Current Behaviour

https://github.com/user-attachments/assets/9bd697ef-3b46-4953-82f4-f414f2cbf126

**Comment by ijreilly** [comment]
thanks @harshit078 for reporting, we will have a look asap !
