### ISSUE TITLE
Search vector doesn't exist for workspace members

### ISSUE THREAD

**Issue by reesericci** [twentyhq/twenty#8056]
## Bug Description

When I create a relation to workspace members, I am unable to search and add one because the search vector doesn't exist.

```
Error during useSearchRecords for "workspaceMembers", column "searchVector" does not exist
```

![image](https://github.com/user-attachments/assets/8256c89f-bdea-4eee-9de7-9d9e9fe0fec6)

## Expected behavior

I'm able to search through workspace members and add one as related to my model.

## Technical inputs

I don't know how to fill this out

**Comment by Bonapara** [comment]
@ijreilly WDYT?

**Comment by ijreilly** [comment]
Hi @reesericci, thanks for pointing out, this has been fixed and will be available in our next release (coming this week)!
