### ISSUE TITLE
When hovering over task items, the task icon becomes visible.

### ISSUE THREAD

**Issue by droidbg** [twentyhq/twenty#8058]
## Bug Description

Currently the task icon appears on hover over empty task items.
Expected behaviour: it should not appear when hovering over empty fields.

**Example:** 
<img width="772" alt="image" src="https://github.com/user-attachments/assets/86af9d7b-cd23-4764-aa26-f889098db714">

Video: 

https://github.com/user-attachments/assets/b5243d97-9faa-4780-ad02-6603ea5cc43c

- [X] I want to work on it

**Comment by sans-byte** [comment]
I would like to work on it

**Comment by FelixMalfait** [comment]
Closing in favor of https://github.com/twentyhq/twenty/issues/7851 :)
