### ISSUE TITLE
Timeline section is not optimised for mobile viewports

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#8060]
## Bug Description

 - Timeline section is not optimised for mobile viewport as content inside it clip behind date section

 ## Current Behaviour
 
 
<img width="395" alt="Screenshot 2024-10-25 at 5 34 28 PM" src="https://github.com/user-attachments/assets/857f4a92-2e53-4873-80f4-d23a5007c9ff">

 
<img width="403" alt="Screenshot 2024-10-25 at 5 43 32 PM" src="https://github.com/user-attachments/assets/2768d465-a40c-40ce-84d8-ed456ba82ee2">

## Expected behavior

- The content after **You** in timeline should be visible and if the length is long, it should have a scroll for ease of convience
- the date column should be fixed the right side of the page and aligned
- card containing multiple fields in row direction should be scrollable for long lenght content and should have fixed width.

<img width="409" alt="Screenshot 2024-10-25 at 5 42 07 PM" src="https://github.com/user-attachments/assets/10281db0-e8dc-4743-a1e5-0fad87efce57">

**Comment by Bonapara** [comment]
Thanks for raising this issue @harshit078! I think the card should take the full width in mobile

**Comment by harshit078** [comment]
@Bonapara should the text scroll behind the title Emails or Intro or the way shown here ? whats your take

https://github.com/user-attachments/assets/6480d77c-c220-4d1e-aae5-56df96547be8

**Comment by Bonapara** [comment]
Just behind may look better. Thanks @harshit078!

**Comment by FelixMalfait** [comment]
Closing as I had hidden the dates on mobile (not enough space) - there is still a lot of room for improvements later, especially the cards that now look bad and overflow
