### ISSUE TITLE
Horizontal bar in login popup despite no SSO key set

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8071]
**Scenario:**
1. Open Twenty

**Actual:** When login popup appears, user can see unnecessary horizontal bar dividing space between missing "Continue with Google" button and visible "Continue with email" button
![image](https://github.com/user-attachments/assets/55dd7e5c-b85a-4441-8226-91416385fed7)

**Expected:** Horizontal bar should be visible only if SSO key is added

**Comment by Bonapara** [comment]
Thanks, @BOHEUS, it bugs me every time I connect to the local version :)

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by DeepaPrasanna** [comment]
May I work on this?

**Comment by sans-byte** [comment]
Hi, already worked on this while working on other issue as it was looking strange to me too so raised a PR, maybe look at the PR if it's fine. @Bonapara

**Comment by karthik-nair-20** [comment]
<img width="1440" alt="Screenshot 2024-10-27 at 12 51 45 AM" src="https://github.com/user-attachments/assets/a1fde088-33a1-4695-89ea-f183f72327c9">

**Comment by dilshad-knk** [comment]
are u working on this @karthik-nair-20

**Comment by karthik-nair-20** [comment]
Hey @dilshad-knk ,No I did not raise PR, the SS I shared should fix the issue

**Comment by BOHEUS** [comment]
I'm closing this issue as fix is merged
