### ISSUE TITLE
When collapsing the side editor (Note, Task), pending changes are lost

### ISSUE THREAD

**Issue by brandon93s** [twentyhq/twenty#8074]
## Bug Description

If you quickly dismiss the right sheet, for example when editing a note within an opportunity, prior to the debounced `handleEditorChange` having an opportunity to update cache and persist, your changes are lost.  This can happen when doing quick entry (e.g., via pasting in notes).

**Example:** 
1. Paste some content in from your clipboard
2. Quickly click out of the sidebar to return to the opportunity
3. Note the content is absent form the preview (cache)
4. Reload the page, observe that persistence did not occur, content is lost

![CleanShot 2024-10-25 at 13 24 48@2x](https://github.com/user-attachments/assets/16799efe-36ca-45a7-9412-63dc006f1861)

## Expected behavior

A final "dirty" check and cache/persist should be performed on the content when the sidebar collapses to ensure work is not lost.

**Comment by Bonapara** [comment]
@lucasbordeau wdyt?

**Comment by lucasbordeau** [comment]
It's complex to implement, I think that we could reduce the delay of debounce as a start but I don't know if the time we'll invest is worth it.

**Comment by Bonapara** [comment]
Thanks for the advice @lucasbordeau, closing this as not planned in the short term but keeping the issue in mind. Thanks @brandon93s for raising it 🙏
