### ISSUE TITLE
Documentation padding is too large on Mobile

### ISSUE THREAD

**Issue by rajeevDewangan** [twentyhq/twenty#8086]
# Current Behavior

The padding of the Twenty's documentation and user guide on mobile is too large.

![WhatsApp Image 2024-10-26 at 14 07 14_1bad26c4](https://github.com/user-attachments/assets/d9a0536d-2538-49d1-bfb1-79d5b80a7fab)

![CleanShot 2024-10-28 at 10 19 43](https://github.com/user-attachments/assets/2b5192fd-33ce-4f5c-9c40-5903f00ca944)

# Desired Behavior

The padding between the content and the screen edge should be 32px on each side instead of 40px + 30px

**Comment by FizanMuhammedFaisal** [comment]
is this issue not resolved? can I take it

**Comment by Bonapara** [comment]
Not fixed

**Comment by FizanMuhammedFaisal** [comment]
> Not fixed

could you assign this to me

**Comment by khuddite** [comment]
@FizanMuhammedFaisal @Bonapara Fixed and created a PR - https://github.com/twentyhq/twenty/pull/8318
