### ISSUE TITLE
When exporting records, 2 files are downloaded instead of 1

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8098]
**Scenario:**
1. Log in
2. Go to People tab (or any other tab)
3. Select 1 record or more
4. Click "Export" button

**Actual:** 2 files are downloaded instead of 1
[Screencast From 2024-10-26 20-54-48.webm](https://github.com/user-attachments/assets/70fa5fe6-f8ef-4fa7-8f44-305ed6819d47)

**Expected:** Only 1 file should be downloaded

**Comment by sans-byte** [comment]
Please assign this to me I would like to work on this

**Comment by Bonapara** [comment]
Is it because of https://github.com/twentyhq/twenty/issues/6729 @BOHEUS? Thanks for creating this issue ;)

**Comment by BOHEUS** [comment]
Totally forgot about that one :P I was testing some stuff in Chromium instead of Firefox and it just happened to find this bug as I didn't have a prompt asking for place to save it

**Comment by Bonapara** [comment]
I'll close this one since it's mentioned in the other issue. It will be easier to keep track of it! Thanks again
