### ISSUE TITLE
Duplicated favorite record

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8107]
**Scenario:**
1. Log in
2. Go to People tab (or any other tab)
3. Delete any record
4. Open Deleted records view
5. Select deleted record and try to add to Favorites

**Actual:** Record is added but it's value is overwritten (probably to null)
[Screencast From 2024-10-26 21-54-07.webm](https://github.com/user-attachments/assets/1785076b-92eb-44b1-ade1-4cf981116827)

**Comment by Bonapara** [comment]
Duplicate of https://github.com/twentyhq/twenty/issues/7666
