### ISSUE TITLE
[🕹️] Twenty side quest Twenty Content Challenges 

### ISSUE THREAD

**Issue by adilkadivala** [twentyhq/twenty#8111]
### What side quest or challenge are you solving?

Writing a  blog post about Twenty 

### Points

750 points

### Description

I have shared my experience in this blog post

### Provide proof that you've completed the task

Post [Link](https://dev.to/k-adi/twenty-the-next-generation-self-hosting-platform-for-enhanced-control-and-flexibility-31h9)

**Comment by adilkadivala** [comment]
Hi @Bonapara , @FelixMalfait

**Comment by FelixMalfait** [comment]
Could you please delete the article? It’s AI generated and not accurate at all (Twenty is not software to plan with friends). I’m afraid it could mislead people if they find it in search engine. Thank you!

**Comment by adilkadivala** [comment]
deleted

**Comment by FelixMalfait** [comment]
Thank you @adilkadivala!
