### ISSUE TITLE
New standard fields on People

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#812]
# People
Linkedin - Link
Twitter - Link - Hidden by default

Introducing a new kind of property and a redesign:

### Links:

Related to: #933 #938 This is only **related** to these issues. If the chips design will be the same, we will add some custom behavior for social links (the displayed text inside the chip will be custom) **See comments below** to see how.

https://github.com/twentyhq/twenty/assets/19412894/50c23bf8-2f0d-4d4d-9a2a-15ee9b7f6252

Introducing the pen to the table inputs (to enable easy value modification when the cell content is a chip with a link)

Todo:
- introduce twitterUrl in database
- create the SocialLinkChip (based on Chip, variant rounded) https://main--647862655ef7071d35328bb2.chromatic.com/?path=/story/ui-chip-chip--default (similar to EntityChip).
- create Twitter and Linkedin customization (see comment below)
- use it in People Table (viewFields)

**Comment by FelixMalfait** [comment]
Great! Just to be sure: it's a conscious choice to display company names in the LinkedIn column but not in Twitter column? 
On edit I should paste a full url, correct? And we expect the name  displayed to be taken from the name column and be unrelated to the URL right? E.g. if I paste the wrong url on Qonto, I'd still see Qonto?

**Comment by Bonapara** [comment]
No indeed, just noticed Figma customization has been overridden and is not reflected in the video.

We should fetch the username in the profile URL. Here are the different behaviors:

### Twitter

https://twitter.com/elonmusk
Display → @elonmusk

https://twitter.com/SpaceX
Display → @SpaceX

Make sure to add the "@"

### Linkedin

**Profile without url customization:**
https://www.linkedin.com/in/elon-musk-3262451b4/
Remove the numbers from the display
Display → elon-musk

**Customized URLs:**
https://www.linkedin.com/in/tdesfrancs/
Display the user name → tdesfrancs

**Companies:**
All companies have a dedicated username
https://www.linkedin.com/company/twenty
Display → twenty
