### ISSUE TITLE
Creating a new company in twenty doesn't activate on Zapier 

### ISSUE THREAD

**Issue by jackbeeby** [twentyhq/twenty#8130]
I have setup a zap that should trigger immediately when a customer is created. I have manually added a customer, and added through another API however it doesn't seem to trigger. When setting up the zap it connects perfectly and finds previous entries and when combining it with the second zap it sends those entries off however this is only when running it as a test. 

Could this be a bug or a known issue or something on my end that has been misconfigured.

Self hosted instance on docker. Replication steps:
1) Connect to zapier and setup a trigger when a company is created
2) Connect a second app (google contacts etc)
3) Link the fields to creating a new contact. You will see already created companies appear as expected. Save the zap
4) Add new company in twenty (through adding the details onto a new line in the companies, or adding a new company through the API). Save
5) No task is created in zapier, and a new contact doesn't get created.

<img width="849" alt="Screenshot 2024-10-28 at 10 21 23 am" src="https://github.com/user-attachments/assets/b1e06b0d-a453-457c-b246-a396d516958e">
<img width="876" alt="Screenshot 2024-10-28 at 10 22 21 am" src="https://github.com/user-attachments/assets/27a57757-2d23-4946-bc6c-6cb605fbc055">

**Comment by martmull** [comment]
@jackbeeby thank you for the report, on it today
