### ISSUE TITLE
[BUG] 3dots at PEOPLE workspace at {EMAIL} edit is not working

### ISSUE THREAD

**Issue by adityadeshlahre** [twentyhq/twenty#8132]
## Bug Description

At PEOPLE workspace {EMAIL} option on click after edit option 3dot option is not working properly

#### Brave Browser
https://github.com/user-attachments/assets/b7a8dcd4-ce7f-4261-9bd5-b9784aafaaf3

#### FireFix Browser
https://github.com/user-attachments/assets/be5f2dfb-bb0a-4529-8b07-ca8ff69ebd61

#### CHROMIUM Browser
https://github.com/user-attachments/assets/b41f3d32-b8e9-44b5-85b1-4c7689bbd592

## Expected behavior

It should show or display options to EDIT or REMOVE or SEND_MAIL options.

**Comment by sans-byte** [comment]
I would like to work on it. If it's confirm please assign it to me.

**Comment by Bonapara** [comment]
This is a big regression, thanks @adityadeshlahre!

**Comment by Bonapara** [comment]
@sans-byte, please give it a try. However, since it's a significant bug, the core team will fix it tomorrow if your contribution cannot be merged as is. Thanks for contributing!

**Comment by ehconitin** [comment]
@Bonapara this is fixed. Could not reproduce.

**Comment by Bonapara** [comment]
Yes!
