### ISSUE TITLE
[🕹️] Bug Hunter

### ISSUE THREAD

**Issue by AkashJana18** [twentyhq/twenty#8133]
### What side quest or challenge are you solving?

Bug Hunter / Improve Documentation UX/UI

### Points

50-150

## Add Dark Theme Option for Developer and User Guide

**Description:**

Currently, the [Twenty Docs](https://twenty.com/developers/) and user guide only support a light theme. A dark theme option would be beneficial for users who prefer or require a darker interface, which can reduce eye strain, especially in low-light environments and for long working hours. 

**Proposed Solution:**

1. **Dark Theme Toggle:** Add a toggle (e.g., sun/moon icon) on the developer portal to switch between light and dark modes.
2. **Automatic Theme Detection:** Optionally, implement auto-detection based on user device settings for a seamless experience.
3. **CSS Variables:** Define and use CSS variables for easy theme switching.

**Benefits:**

- Enhanced user experience, especially for developers working long hours.
- Accessibility improvements for users sensitive to bright screens.
  
**Additional Notes:**

If feasible, please consider applying this dark theme to the entire user guide documentation for a consistent experience across the platform.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/223e214f-11c4-4d8b-98d5-ff84652be7c1)

### Willing to submit a PR?
Yes, I would like to work on this issue.

**Comment by FelixMalfait** [comment]
Hey, the website is partially managed by Framer, so this would be complex to do (we'd have to do it on both sides). Closing as it's not a priority / worth the effort. Thanks for the suggestion!
