### ISSUE TITLE
[🕹️]Designed New Theme for Twenty's Website on figma

### ISSUE THREAD

**Issue by Vanshdeepsingh-2232** [twentyhq/twenty#8135]
### What side quest or challenge are you solving?

Create a custom theme for Twenty's interface (150-750 points): Duplicate the Figma file and customize the variables to create a new theme for Twenty’s interface.

### Points

150-750 points

### Description

Design of a new theme (coffee) for twenty's website in figma.

### Provide proof that you've completed the task

>>By : VanshdeepSingh

>> Link to the Figma file of the design:

https://www.figma.com/design/akgDOb37YLUW9iWLB155EV/Twenty-(Copy)?node-id=478-19796&t=8Gz1yqls2Q3dsN9h-1

>>Prototype:

https://www.figma.com/proto/akgDOb37YLUW9iWLB155EV/Twenty-(Copy)?node-id=1406-44830&node-type=canvas&t=eBvFkq4KeD1Sgkbn-1&scaling=min-zoom&content-scaling=fixed&page-id=478%3A19796&starting-point-node-id=1406%3A44830

>>Images:

![image](https://github.com/user-attachments/assets/97e5f894-c85a-4b42-87bd-a6ef85c09d26)
![image](https://github.com/user-attachments/assets/65123e65-21b5-4868-a77a-3b3dd170c93e)
![image](https://github.com/user-attachments/assets/fa46330e-fe40-4dda-a51f-a3c267c8e646)

**Comment by Bonapara** [comment]
Thanks for the theme @Vanshdeepsingh-2232!
