### ISSUE TITLE
The "No Result" flashes on every keystroke in Relation Picker

### ISSUE THREAD

**Issue by harshrajeevsingh** [twentyhq/twenty#8137]
## Bug Description

When searched items are not found and we still enter some input, the "No Result" text flashes on every keystroke. 

[Screencast from 2024-10-28 12-41-10.webm](https://github.com/user-attachments/assets/0ee343ef-afe6-46a9-afb2-21ba61c176bb)

## Expected behavior

The text "No Result" should stay. 

## Scenario
1. Open any person's profile
2. Find Linked Opportunities section
3. Click on ```+``` icon to open Relation Picker 
4. Enter input that's not in the list, keep on entering some text to see this behaviour.

**Comment by sans-byte** [comment]
Please assign it to me I have worked on this before

**Comment by sans-byte** [comment]
https://github.com/user-attachments/assets/08582e9c-acb1-4040-8903-ca4310ec7703

Does this looks better @FelixMalfait @harshrajeevsingh

**Comment by FelixMalfait** [comment]
It does @sans-byte thanks!

**Comment by FelixMalfait** [comment]
/oss.gg 150

**Comment by harshrajeevsingh** [comment]
@sans-byte Yes, just one more thing. ```DropdownMenuSeparator``` is missing between the Add new button & items menu list.

**Comment by sans-byte** [comment]
Okay @harshrajeevsingh will add.

**Comment by FelixMalfait** [comment]
Good catch @harshrajeevsingh thanks!
