### ISSUE TITLE
latest tag(till 20241029) can not start

### ISSUE THREAD

**Issue by diucicd** [twentyhq/twenty#8142]
just follow this docker compose manual: https://twenty.com/developers/section/self-hosting/docker-compose

and server can not start, it shows redis still connect to 127.0.0.1, please check

[Nest] 1  - 10/28/2024, 10:05:28 AM     LOG [InstanceLoader] FileUploadModule dependencies initialized +0ms
[Nest] 1  - 10/28/2024, 10:05:28 AM     LOG [InstanceLoader] FileModule dependencies initialized +0ms
[Nest] 1  - 10/28/2024, 10:05:28 AM   ERROR [ExceptionHandler] connect ECONNREFUSED 127.0.0.1:6379
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)

**Comment by Bonapara** [comment]
Hi @diucicd can you ask on our Discord #help channel?

**Comment by vngvng** [comment]
I have same issue, cannot start docker container.
