### ISSUE TITLE
I can see my notifications

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#816]
https://github.com/twentyhq/twenty/assets/19412894/e812a44e-d6f2-410b-a18b-1a8934fbcfea

**Comment by FelixMalfait** [comment]
Just to confirm: the blue icon disappears the first time I read it? And then archive is a second separate feature? 
(So would be two fields first_viewed_at / archived_at in notifications table)

**Comment by Bonapara** [comment]
Yes & yes

**Comment by FelixMalfait** [comment]
We probably need to implement the ability to tag first before we implement this.
- Implementing tagging in the text editor will require switching to the text editor.
- Implementing tagging in the comments will also require a refactorisation.

Should I create tickets for those 2 @Bonapara?

**Comment by Bonapara** [comment]
We can indeed create these 2 other tickets! 

I think we can start implementing the notifications for the assignement part though:
- "I've been assigned as account manager"
- "I've been assigned on a task"
