### ISSUE TITLE
[🕹️]  Starry Eyed

### ISSUE THREAD

**Issue by harshsbhat** [twentyhq/twenty#8162]
### What side quest or challenge are you solving?

Asked my friends to star the repo

### Points

150

### Provide proof that you've completed the task

https://github.com/Deadgrudge117?tab=stars
https://github.com/omkar07070?tab=stars
https://github.com/Pranav-019?tab=stars
https://github.com/abhishekbelgaonkar23?tab=stars
https://github.com/aditya-supare?tab=stars

1] 

![image](https://github.com/user-attachments/assets/0ec153e2-752b-4350-b430-2cec00f4927c)

2]

![image](https://github.com/user-attachments/assets/2c69a2cb-1492-4467-bbae-b11702e61a81)

3]

![image](https://github.com/user-attachments/assets/3b41ea1e-38b4-4e5b-970f-c3dc700c6c21)

4]

![image](https://github.com/user-attachments/assets/c9685b8b-f9f8-4619-a5ea-163adc2d3ff2)

5]

![image](https://github.com/user-attachments/assets/ca597be1-d8ee-423d-a3d0-1600a47e08e7)

**Comment by Bonapara** [comment]
Thanks @harshsbhat!

I think:

https://github.com/abhishekbelgaonkar23?tab=stars
https://github.com/aditya-supare?tab=stars

missed Twenty. 

Awarding 90 points in the meantime!

**Comment by Bonapara** [comment]
Please comment if there is an update, and I will grant you the extra points

**Comment by harshsbhat** [comment]
@Bonapara  I feel betrayed lol. These were my closest friends that's why I didn't check. Can you check now? Should be good!
