### ISSUE TITLE
Is it just me or there is documentation missing for major functionalities

### ISSUE THREAD

**Issue by yashb042** [twentyhq/twenty#8164]
Hello,

First of all, extremely grateful to the creators for creating this library.

I have been wanting to integrate email functionality into my self hosted version. I have gone through the docs, but couldn't find any suitable reference for connecting email with my G-suite.
I tried this link - [](https://twenty.com/developers/start/self-hosting#email), but it doesn't seem to work.

Am I missing some major documentation. Could anyone please help, if only for the email part atleast, that would be really great.

**Comment by yujonglee** [comment]
this might be helpful?

https://twenty.com/developers/section/self-hosting/self-hosting-var#email-smtp-server-configuration-examples

**Comment by Bonapara** [comment]
Thanks for sharing the link, @yujonglee! Feel free to update the documentation if anything is missing
