### ISSUE TITLE
Standardize "Add New" button in dropdown menus

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8169]
# Current Behavior

### Multi-select

The `Add New` button has its own container.

https://github.com/user-attachments/assets/856d8f59-df83-40ea-a4a5-d5b5a25585e9

### Select

The `Add New` button is within the Select choices container.

https://github.com/user-attachments/assets/417b8428-6851-4f00-8b3f-51b7abcccfbb

# Desired Behavior

We should apply the behavior of the multi-select to all dropdown menus. The `Add New` button should have its own container/menu section everywhere.

**Comment by prithak01** [comment]
Can i try this issue @Bonapara ? I'm relatively new.

**Comment by Bonapara** [comment]
Sure @prithak01, thanks for contributing!

**Comment by prathameshpatil5181** [comment]
@Bonapara  Can I work on this?

**Comment by Bonapara** [comment]
Yes @prathameshpatil5181 thanks for contributing, @prithak01 unassigning you as it's been 5 days, you can grab another [Good First Issue](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)!

**Comment by matosGu1lherme** [comment]
@Bonapara Can I work on this activity or does it already belong to someone else, I would really like to contribute

**Comment by Bonapara** [comment]
@prathameshpatil5181 are you still willing to handle it or should I assign it to @matosGu1lherme?

**Comment by prathameshpatil5181** [comment]
I will Handle this @Bonapara
