### ISSUE TITLE
I can resize a column

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#817]
![Image](https://github.com/twentyhq/twenty/assets/19412894/63e7fcf6-3669-4a65-b2ae-b168eb253933)

**Comment by FelixMalfait** [comment]
Linked to https://github.com/twentyhq/twenty/issues/467 for the backend to persist size across sessions

But we can maybe consider this ticket as pure frontend, and just do a console.log temporarily instead of saving the new field size to the db

**Comment by thaisguigon** [comment]
The issue mentioned by @FelixMalfait was deleted so as discussed with @charlesBochet, here is the new issue for persisting column sizes: #981
