### ISSUE TITLE
Dragging Favorites doesn't reorder them

### ISSUE THREAD

**Issue by Hitarthsheth07** [twentyhq/twenty#8181]
## Bug Description

When the favorites are dragged their position is not changed. 

https://www.loom.com/share/5e2347ddbb474f32a9b67db6e4a4ac4d?sid=20e1d863-4c8a-4460-aa3e-18be140b37c6

## Expected behavior

The favorites item should reorder when dragged to another place. 

Would love to work on this issue if it's approved. 

Cheers! 🍻

**Comment by Bonapara** [comment]
@ehconitin you're on it right? Closing in the meantime
