### ISSUE TITLE
[🕹️] Starry-eyed supporter

### ISSUE THREAD

**Issue by Mukku27** [twentyhq/twenty#8189]
### What side quest or challenge are you solving?

Starry-eyed supporter

### Points

150

### Description

Got five friends to star twenty repository.

### Provide proof that you've completed the task

![bharath github](https://github.com/user-attachments/assets/52ee9cb9-3f8a-4da9-94e8-10d0765f4b06)
![likki](https://github.com/user-attachments/assets/6a37b4c3-4197-4aa3-9f8f-91baf2124995)
![oss](https://github.com/user-attachments/assets/4e1913d3-e219-41ca-81e5-02c01ee8fd36)
![oss g](https://github.com/user-attachments/assets/90860c6f-7eaf-4254-9077-c3ef96d689a8)
![oss gg](https://github.com/user-attachments/assets/baff828f-e17f-4b1b-a0fd-82c4e14b2c3f)

**Comment by Bonapara** [comment]
Hi @Mukku27, can you share the links? Sorry, they don't look like real people, so I will close it in the meantime.
