### ISSUE TITLE
Add a card from column top

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#819]
https://github.com/twentyhq/twenty/assets/19412894/d8007621-b480-4f26-834c-0562481ad18d

See also: https://github.com/twentyhq/twenty/issues/803

Create card on top of the column

**Comment by FelixMalfait** [comment]
Looks like a duplicate? https://github.com/twentyhq/twenty/issues/711 ; feel free to close the previous one!

+ maybe create a second one that covers the (+) button on top right?

**Comment by Rumone** [comment]
I'd like to work on this issue

**Comment by FelixMalfait** [comment]
Thanks @Rumone!
