### ISSUE TITLE
Settings Option Card component

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8195]
# Current behavior

We use various designs for options throughout the Settings.

**Email options**

![image](https://github.com/user-attachments/assets/2831a21a-85a5-4840-a79f-d2b42217ea7d)

_No icons / Spacing too big between title and decription_

**Fields options**

![CleanShot 2024-10-30 at 11 59 36](https://github.com/user-attachments/assets/c7aa4b24-5b41-4b08-af2a-747e704909df)

_No card, no consistency in design_

# Desired Behavior

We want to use a single component to standardize the settings design.

## Emails 

![CleanShot 2024-10-30 at 12 04 21](https://github.com/user-attachments/assets/3ca90c60-d468-4358-bc53-3e03fd23ea6b)

## Calendar

![CleanShot 2024-10-30 at 12 04 34](https://github.com/user-attachments/assets/d7d7490d-cf70-4b5c-9344-1f606d432a8a)

## SSO

![CleanShot 2024-10-30 at 12 04 51](https://github.com/user-attachments/assets/007dc2f8-8e9c-4823-a415-9187b01cffae)

## Data Model > Object

![CleanShot 2024-10-30 at 12 05 21](https://github.com/user-attachments/assets/54022726-d869-49b4-a6b4-2bb7fed4bbb5)

## Data Model > Object > Field

![CleanShot 2024-10-30 at 12 05 54](https://github.com/user-attachments/assets/369b514e-4992-47a9-bc46-f6125e71e330)

![CleanShot 2024-10-30 at 12 06 11](https://github.com/user-attachments/assets/357d2055-daee-4aa1-8677-95818a359117)

![CleanShot 2024-10-30 at 12 06 21](https://github.com/user-attachments/assets/703ff96f-4f33-4e8f-be60-74b7b616a9e3)

![CleanShot 2024-10-30 at 12 06 42](https://github.com/user-attachments/assets/557af8f5-dc57-419c-b78a-9ab3e039f575)

![CleanShot 2024-10-30 at 12 06 55](https://github.com/user-attachments/assets/e7cc591a-12c3-4713-be51-2a4f080f3383)

# Component

![image](https://github.com/user-attachments/assets/d24a4dac-a6e0-494f-a93f-59f922080c3e)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=35741-193252&node-type=frame&t=CiXmqWSMdYd6vVDl-11

**Comment by tanayvaswani** [comment]
First time contributor, would love to give it a try. Should I get this issue assigned before start working ?

**Comment by Bonapara** [comment]
@tanayvaswani I think this issue is too large for a first contribution. Maybe check out our [Good First Issues!](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)

**Comment by ehconitin** [comment]
@Bonapara this is free to pick right?

**Comment by Bonapara** [comment]
Yes, @ehconitin, thanks! I'm available for any additional information if needed.

**Comment by ehconitin** [comment]
Closed in #8456
