### ISSUE TITLE
Group By revamp for Table and Kanban Views

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8203]
# Current Behavior

We can use the group-by function on kanbans, but not on tables yet.

# Desired Behavior

We want to unify the group-by behavior on both `table` and `kanban` views. Therefore, we aim to rename the kanban `stages` setting to `group by` in the kanban options menu.

## Options menu "root" level

![CleanShot 2024-10-30 at 14 53 59](https://github.com/user-attachments/assets/fc709a9b-460d-48d2-a965-dcb176ce8970)

Display the chosen `Select field` name

## Group by menu

![CleanShot 2024-10-30 at 14 53 28](https://github.com/user-attachments/assets/02fa8935-53d2-416e-b154-08dcc64253f7)

### Group by Options

![CleanShot 2024-10-30 at 14 57 39](https://github.com/user-attachments/assets/39b157ae-a0a3-4195-accf-5acfa176a0f7)

- Allows to choose which select field to use for the group by. `None` should only available for table views (as you can't create a Kanban view without group by). 
- `Create Select Field` should redirect to `/settings/objects/xxx/new-field/configure?fieldType=SELECT`

![image](https://github.com/user-attachments/assets/63be723a-face-4ed6-ab58-ca151db2b6ef)

_This is what should be shown when no select field is available on a table view_

### Sort Options

![CleanShot 2024-10-30 at 15 03 05](https://github.com/user-attachments/assets/a9d40c23-3fe2-4ddf-91bd-5d3021302991)

### Hide Empty Groups

![CleanShot 2024-10-30 at 15 05 02](https://github.com/user-attachments/assets/74b71b67-256f-4783-ba26-c2f9846f2b91)

Hide columns that don't contain at least one card.

### Visible groups

Disable the grips if `Alphabetical` or `Reverse-Alphabetical` is selected

![CleanShot 2024-10-30 at 15 05 11](https://github.com/user-attachments/assets/41b1e240-05b4-4129-a823-0c88c74f378b)

Customize which fields are displayed and in what order.

**Comment by charlesBochet** [comment]
@Bonapara Closing this issue, let's do a QA session to quickly iterate over it if needed
