### ISSUE TITLE
Add validation on Select field option keys

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#8204]
## Scope & Context

We can input special characters in Select API values 

+ We need to change the label "API keys" to "API values" as it is misleading

<img width="597" alt="image" src="https://github.com/user-attachments/assets/c3592943-3afe-4c30-8672-f2d97ab3e396">

**Comment by ketanMehtaa** [comment]
assign me @lucasbordeau  :)

**Comment by ketanMehtaa** [comment]
@lucasbordeau  just wants to confirm: 
1) You want to stop inputting special characters in Select API values, and
 2) change "API keys" to "API values".   :)
