### ISSUE TITLE
DoubleText input is trapped inside cell

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#821]
# Online

![Image](https://github.com/twentyhq/twenty/assets/19412894/c2306d25-8464-4a2d-b819-91f891509927)

# Expected behavior:

![Image](https://github.com/twentyhq/twenty/assets/19412894/105a57b4-f135-4641-8c04-dc8ec5b9570a)

**Comment by FelixMalfait** [comment]
Changing the size of the input from 100% to a fixed px value seems to do what you want. What px value would you like? (e.g. here with 92px)

<img width="1273" alt="Screenshot 2023-07-22 at 11 20 16" src="https://github.com/twentyhq/twenty/assets/6399865/975288be-223d-444c-af43-c1e23d42829e">

**Comment by Bonapara** [comment]
Looks great! 96px so it's a [multiple of 8 ](https://medium.com/@sainzkike/controlling-spacing-in-design-systems-multiple-spacing-9bf1afec87f) sounds perfect 😅

**Comment by FelixMalfait** [comment]
Ok great thank you! 

(I'm not taking this issue, I was just clarifying)
