### ISSUE TITLE
Change Icon button color to Secondary

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8212]
# Current behavior

Icon button color is Tertiary

![1ba4fba925afde8fa4c1c71596d4054de972cf0f648a79ebf722814a604160ff](https://github.com/user-attachments/assets/bd5e778b-9240-4a4a-9318-217c656d0d41)

The strange thing is that the icon color in the data model field and object icon is correct.

![image](https://github.com/user-attachments/assets/c58aec9b-6040-48d3-9d02-50f2e41fcd0d)

# Desired Behavior

We want the icon color of the `Icon Button` component to be Secondary everywhere

![CleanShot 2024-10-30 at 16 27 15](https://github.com/user-attachments/assets/ac225546-0073-4ea9-adb5-9ab9e67a95d9)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=3122-142114&node-type=frame&t=OOIqna3WNmE194bK-11

**Comment by BOHEUS** [comment]
I'll take care of it :saluting_face:

**Comment by Bonapara** [comment]
Thanks @BOHEUS!

**Comment by BOHEUS** [comment]
@Bonapara I fixed the button color but Charles changed it in #8346, in the end which one should be for IconButton?

**Comment by Bonapara** [comment]
The color should be secondary - everything seems to work! Thanks @BOHEUS :)
