### ISSUE TITLE
[🕹️]  Starry-eyed supporter

### ISSUE THREAD

**Issue by RajuGangitla** [twentyhq/twenty#8222]
### What side quest or challenge are you solving?

asked five of my friends to star the repository 

### Points

150

### Provide proof that you've completed the task

1. https://github.com/vkaushik017?tab=stars
![image](https://github.com/user-attachments/assets/1b548f8f-9cb9-42f4-9f1d-90fa9ce7f355)
![image (9)](https://github.com/user-attachments/assets/4be96ba7-7a45-47f0-b861-f01350aa4a53)

2.https://github.com/hari4742?tab=stars
![image](https://github.com/user-attachments/assets/94f052c2-2465-471c-bc97-cbf55682efe6)
![{63B236C9-91B5-44B9-92B0-40F6CBF23FD6}](https://github.com/user-attachments/assets/18730a29-d3d5-41f2-8e22-b1ebaf9c253e)

3.https://github.com/JoshanSai?tab=stars
![image](https://github.com/user-attachments/assets/4daa380b-22b8-4c0c-86bb-f08659382feb)
![image](https://github.com/user-attachments/assets/f1680cc3-fc56-4719-8471-0e6fd729ff8a)

4. https://github.com/aakash-zedblock?tab=stars
![image](https://github.com/user-attachments/assets/65dae879-cfc8-472f-a371-974b9c4b6fbf)
![image](https://github.com/user-attachments/assets/a1c0e150-b5e9-4aa2-814a-1730d27aab9e)

5. https://github.com/Suri-Jayraj?tab=stars
![image](https://github.com/user-attachments/assets/515a083c-bc40-4fc7-bdd1-bd5e25f77a4d)
![WhatsApp Image 2024-10-31 at 12 05 27 AM](https://github.com/user-attachments/assets/c4781f77-f22a-40b7-913c-802ae5133166)

**Comment by Bonapara** [comment]
Thanks for sharing the project @RajuGangitla!

**Comment by RajuGangitla** [comment]
@Bonapara your welcome
