### ISSUE TITLE
Multi-select field can't have no options selected

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8224]
**Scenario:**
1. Log in
2. Go to Settings > Data model
3. Create new object (not necessary step but easier to clean up)
4. Add new multi-select field
5. Create new record
6. Check details of record
7. Select option in multi-select field
8. Uncheck option from step 7

**Actual:** When trying to uncheck selected option, error in UI appears
[Screencast From 2024-10-30 22-07-17.webm](https://github.com/user-attachments/assets/beb4541a-f477-4320-8b63-e1ade270f125)
![image](https://github.com/user-attachments/assets/a876a6e9-3af9-4200-b316-6190ae1f854c)

**Expected:** Multi-select can have no options selected

**Comment by khuddite** [comment]
I will take a look at it

**Comment by khuddite** [comment]
@Bonapara Fixed and created a PR
