### ISSUE TITLE
Bug: total Count is not updating when i delete th people 

### ISSUE THREAD

**Issue by RajuGangitla** [twentyhq/twenty#8228]
## Bug Description

When i am deleting the people in  dashbaord ,  the count should reduce after i delete but its not working as expected 

[screen-capture (28).webm](https://github.com/user-attachments/assets/08a84094-178f-4e12-87de-e0f1dcc32366)

**Comment by khuddite** [comment]
@Bonapara can you assign this ticket to me? Thanks

**Comment by Bonapara** [comment]
Sure @khuddite, thanks for contributing!

**Comment by khuddite** [comment]
@Bonapara Does table view support pagination currently? 

![CleanShot 2024-11-06 at 09 20 50](https://github.com/user-attachments/assets/b2f5e3dd-15c8-456b-a48b-b12c8c1f73e1)

**Comment by khuddite** [comment]
@Bonapara You can unassign me from this ticket since I am no longer working on this issue.

**Comment by FelixMalfait** [comment]
@ijreilly assigning this to you since it's related to the aggregate fields migration

Thanks @khuddite for helping us figure out the right path!

**Comment by ijreilly** [comment]
@FelixMalfait aggregate fields have not been released on prod yet + they are not present on the table view yet but I will work on making this work with the aggregate queries !
(I am closing this as this is already covered by the aggregate queries scope)

**Comment by FelixMalfait** [comment]
Thank you @ijreilly
