### ISSUE TITLE
Relation picker is broken on kanban 

### ISSUE THREAD

**Issue by ijreilly** [twentyhq/twenty#8233]
## Bug Description

![image](https://github.com/user-attachments/assets/4589d1e5-86a2-43ba-9daa-39c19c84d3d8)

Search is not working (impossible to type)
Need to click two times to validate after trying to input a search
No pen icon to open picker (need to click in the few px padding zone...)

**Comment by Hitarthsheth07** [comment]
Heyy @ijreilly, any chance I could work on this?
