### ISSUE TITLE
Emails input field stays in errored state

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#8235]
Steps to reproduce : 
- enter an emails field edit mode in a table cell
- type a wrong email like : "asd.com"
- input gets in errored state
- type a correct email and validate
- input stays in errored state

Emails input field should exit errored state when we've successfully entered a correct email.

![image](https://github.com/user-attachments/assets/948cd0ca-04c5-4490-963a-d6b7d6fbf00c)

**Comment by harshit078** [comment]
@lucasbordeau I'll take this up !

**Comment by harshit078** [comment]
This is not only limited to Email input but also applies to URL fields.


https://github.com/user-attachments/assets/57814ac6-fe80-4d1b-9c56-db02298ddaaa
