### ISSUE TITLE
[🕹️] Completed All Side quests 

### ISSUE THREAD

**Issue by RajuGangitla** [twentyhq/twenty#8237]
### What side quest or challenge are you solving?

completed all side quests 

### Points

700

### Provide proof that you've completed the task

1.  Like & Re-Tweet oss.gg Launch Tweet. Quote-tweet it tagging @twentycrm (50 points) 
[Link](https://x.com/Raju_Os1/status/1851932770081317142)
![image](https://github.com/user-attachments/assets/56816af7-af90-4c0d-93a0-04184196d5dd)

2.  tweet about your favorite feature in Twenty (50 points)
[link](https://x.com/Raju_Os1/status/1851934119732875683)
![image](https://github.com/user-attachments/assets/db64ef5e-80f2-411b-83d5-bef42156681b)

3. Create a bug report.
https://github.com/twentyhq/twenty/issues/8228

4. Meme Magic: (150 points)
[Link](https://x.com/Raju_Os1/status/1851935421443322302)

5.  Gif Magic: (150 points)
https://x.com/Raju_Os1/status/1851938742593785879
Giphy [link](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExeW54OXdqZWx5bGtzMmtsbThnaDFkdTNmeDd3ZzdyOTdxd2gxaXEyMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/AbiYKGyy5fAyGdVyNL/giphy.gif)

6) With this i completed all side quests (300 points)

**Comment by RajuGangitla** [comment]
@Bonapara only 300 ?

**Comment by RajuGangitla** [comment]
@Bonapara  I think you misunderstood
I completed and posted all side quests in this post 

For completing 300 
For all side quests 400

Hope you understand thanks

**Comment by Bonapara** [comment]
I see, thanks @RajuGangitla 🙌
