### ISSUE TITLE
Creation Date is updated only when I hover the cell

### ISSUE THREAD

**Issue by martmull** [twentyhq/twenty#8241]
https://github.com/user-attachments/assets/8e3e4abf-9ff9-40ab-9e01-3309ea9caeef

@Bonapara @charlesBochet do we want to fix this? If yes, what behavior do we want? Disable update? Update every minutes?

**Comment by Bonapara** [comment]
I think we want real time tackle this isn't it?⚡

https://github.com/twentyhq/twenty/discussions/210
