### ISSUE TITLE
[🕹️] Write a blog post about Twenty

### ISSUE THREAD

**Issue by DeepaPrasanna** [twentyhq/twenty#8245]
### What side quest or challenge are you solving?

Wrote the blog post sharing my experience with twenty

### Points

250-750 points

### Provide proof that you've completed the task

https://dev.to/deepaprasanna/from-overwhelmed-to-organized-my-experience-with-twenty-crm-2hpk

**Comment by charlesBochet** [comment]
Thank you @DeepaPrasanna :)

/award 450
