### ISSUE TITLE
Pressing ⎋ on indexes should deselect all records

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8247]
# Current behavior

Nothing happens when pressing `⎋ (escape)` on an index:

https://github.com/user-attachments/assets/c3a90858-2370-49ad-a247-7732f26c3061

# Desired Behavior

We should deselect all records when pressing escape.

**Comment by harshit078** [comment]
@Bonapara working on this !

**Comment by harshit078** [comment]
@Bonapara Should we handle a case where if the user wants to select all fields after dragging  using ctrl + a ? 


https://github.com/user-attachments/assets/a7d853f3-e852-495e-8119-8f39507d0ef8

**Comment by Bonapara** [comment]
Yes, that sounds good @harshit078, thanks! Would close https://github.com/twentyhq/twenty/issues/8206
