### ISSUE TITLE
On Tasks Show Page, I should be able to edit the Assignee of a Task

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#8248]
## Scope & Context

On the following page: 
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/0081446d-2af8-460c-805d-a06901e505ae">

Task standard objects has a relation to WorkspaceMember named Assignee but it cannot be changed from the Task show page

## Expected behavior

Assignee relation should be displayed. Similar to the `Account Owner` field on Company:
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/7f7b1568-dcd6-4661-835a-ee3c9fb830ac">

**Comment by amitsgh** [comment]
@charlesBochet, I’m interested in working on this. Could you please assign it to me?

**Comment by FelixMalfait** [comment]
Fixed!
