### ISSUE TITLE
Fix Misalignment and Excessive Padding in Relation Card

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8249]
# Current Behavior

The relation card content is not properly aligned on the record detail page, and the spacing is too large. This issue is caused by an undesired 12px padding, which we cannot simply remove as it is useful above.

![CleanShot 2024-10-31 at 14 34 45](https://github.com/user-attachments/assets/45dcf04f-7354-4814-b278-97c169a20a88)

![image](https://github.com/user-attachments/assets/d5a30f35-1b35-4af1-ab33-42b626d5b1ab)

# Desired Behavior

![CleanShot 2024-10-31 at 14 32 12](https://github.com/user-attachments/assets/0b8a6e08-6d49-4cca-b9fe-e401b1ea2b03)

-  Content should be aligned to the left
-  Spacing between the card title and content should be smaller

**Comment by harshit078** [comment]
@Bonapara how much spacing should be there between title and content ?

**Comment by Bonapara** [comment]
0px if the header has the right size (40px)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=19653-53231&node-type=frame&t=OWXnEcGRNTLeMsyd-11

**Comment by harshit078** [comment]
<img width="344" alt="Screenshot 2024-11-01 at 5 01 05 PM" src="https://github.com/user-attachments/assets/641e836a-50ee-401b-b73b-cbf972998a4b">

@Bonapara does this look close to figma design ? In this, spacing is small and content is aligned to left

**Comment by harshit078** [comment]
I'll take this up @Bonapara !
