### ISSUE TITLE
I have an endpoint for AI completion

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#825]
We will implement auto-completion features in the editor similar to what was done on https://novel.sh

Here's the code we would need to take inspiration from: https://github.com/steven-tey/novel/blob/main/app/api/generate/route.ts

But we need to adapt this to our codebase.

Option 1:  Use incremental delivery (quicker but still in alpha it seems so may not be ideal?):  https://www.apollographql.com/docs/apollo-server/workflow/requests/#incremental-delivery-experimental 
Option 2: Subscriptions (word by word?) - server: https://docs.nestjs.com/graphql/subscriptions ; client: https://www.apollographql.com/docs/react/data/subscriptions/ ; but this might require more upfront thinking about how we want to implement that then. Because we'll probably implement subscriptions for collaborative note edition in the future, so we should think of both at the same time

**Comment by Bonapara** [comment]
Opened a conversation in https://github.com/twentyhq/twenty/discussions/3647
