### ISSUE TITLE
Fix Phone Input Design

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8251]
# Current behavior

The phone input is not implemented correctly:

![CleanShot 2024-10-31 at 14 38 59](https://github.com/user-attachments/assets/47f50aa8-9ea4-4c0d-87da-51b91d55c941)

# Desired Behavior

![image](https://github.com/user-attachments/assets/6b6db9ea-0245-41b0-a0b9-2cc73693a3a2)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=3007-69739&node-type=frame&t=L4Zw8NIeonoYkIdd-11

- Flag/region dropdown button should be hoverable
- Flag/region button is too wide
- Input is too high (40px instead of 32px)
- There should be a 8px margin left before the phone number
- The country code should be `Tertiary` instead of `Primary `

**Comment by Hitarthsheth07** [comment]
Any chance I could work on this?

**Comment by Bonapara** [comment]
Sure @Hitarthsheth07, thanks for contributing!

**Comment by Bonapara** [comment]
Looks like #8266 removed the padding when the input has already some values:

### Introduced

![Image](https://github.com/user-attachments/assets/d33176eb-ae4e-42f2-91b9-64cf530ac68f)

### Before (desired)

![Image](https://github.com/user-attachments/assets/2a72fc0e-3440-4859-9f23-264a8aae20a4)

- 4px padding around the input
- The button icon has an 8px margin from the right edge of the menu and a 4px margin from the input border.

**Comment by harshrajeevsingh** [comment]
@Bonapara I think it will be fixed by my PR #8451

**Comment by Bonapara** [comment]
Thanks, @harshrajeevsingh! Please ensure it still works with the first data entry that should use this input design.

![Image](https://github.com/user-attachments/assets/b4fe9098-d4ba-4e1c-a5a4-4e62694628c0)
 
https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=44486-309242&node-type=instance&t=eIjo2j6BeyrW9ISl-11
