### ISSUE TITLE
🐲 Drag to select

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#826]
```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/791
- [ ] https://github.com/twentyhq/twenty/issues/413
```

# Design:
![Image](https://github.com/twentyhq/twenty/assets/19412894/2c65e417-9979-4024-a5d4-51bdb559c263)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=6512-56182&mode=design&t=GMBHxG3P5dZsG4iz-4

We are Introducing the "Transparent accent" color in the theme

**Comment by FelixMalfait** [comment]
@Bonapara the only thing I see missing from a design perspective is the background color + border color of the selection. Would you mind adding it? Thanks a lot

**Comment by FelixMalfait** [comment]
We probably want to think of "drag to select" as a global feature across the app as much as we can.

Two libraries we could potentially use:
- https://github.com/pablofierro/react-drag-select
- https://github.com/AirLabsTeam/react-drag-to-select

Probably needs a bit of tech spec/guidance before starting implementation

**Comment by Bonapara** [comment]
> @Bonapara the only thing I see missing from a design perspective is the background color + border color of the selection. Would you mind adding it? Thanks a lot

Don't see what you mean @FelixMalfait
