### ISSUE TITLE
Dropdown Overlapping Sidebar on Column Header Click in Horizontal Table When Scrolling

### ISSUE THREAD

**Issue by parmarKaran01** [twentyhq/twenty#8272]
## Bug Description

On any table view when the dropdown is expanded, the horizontal scroll is still active and user can scroll horizontally
this creates the weird floating dropdown overlapping the first name column and the menu sidebar as well

Attaching the video for the reference
### Recording

https://github.com/user-attachments/assets/efff459c-51d3-4f91-a7fb-c06a86f64b75

## Steps to recreate

1. On any table Click the dropdown on any column header and scroll

# Desired behavior

Prevent horizontal scroll when a field menu is opened.

**Comment by FelixMalfait** [comment]
Thanks for the report! Also seems like there are other bugs? Menu not loading + plan required ? Do you know why you have that?

**Comment by parmarKaran01** [comment]
@FelixMalfait its the plan-required page, so had just added the display none property on the payment modal 😅

On Local sharing the video


https://github.com/user-attachments/assets/dc1064a6-6f13-4f8b-9f4a-039d1239d1f9

**Comment by FelixMalfait** [comment]
Haha smart @parmarKaran01 😂 - we'll move to a free plan by end of year

**Comment by Bonapara** [comment]
Thanks @parmarKaran01! We should prevent horizontal scroll when a menu is opened - editing the issue description
