### ISSUE TITLE
Add a new theme for twenty

### ISSUE THREAD

**Issue by arg387** [twentyhq/twenty#8278]
### I have made a new theme for twenty. It is a light-turquoise theme.(mainly featuring turquoise color..)
![Screenshot 2024-11-01 203232](https://github.com/user-attachments/assets/08e4c6d2-6b8e-4071-844f-2b57205efb1a)
![Screenshot 2024-11-01 203304](https://github.com/user-attachments/assets/b9a0d987-5657-4a00-baab-becdcc1a87e5)
![Screenshot 2024-11-01 203318](https://github.com/user-attachments/assets/baa2c87e-422a-4f91-b6ae-eb493a04e231)
[Link of Figma]( https://www.figma.com/design/eUytzhKLfF2qyGlwmNkKgB/Twenty-(Copy)?node-id=478-19796&t=TVFAAk3OidaNFL0y-1)
I hope you like it.
#### If you like it please tell me how to merge this in your repo.(I really hope you use this for your app. I am totally frustrated by a lagging figma.) [This is not a ogg submission.]

**Comment by Bonapara** [comment]
Thanks for the theme, @arg387! We haven't implemented theming yet, but we might in the future. We're keeping this in mind for when that day comes. ;)
