### ISSUE TITLE
Text Input width is broken in new task card

### ISSUE THREAD

**Issue by rathodvinod5** [twentyhq/twenty#8279]
Width of text input is broken when creating a new task

<img width="1512" alt="Screenshot 2024-11-01 at 8 54 20 PM" src="https://github.com/user-attachments/assets/3a10d5da-9324-4426-8ae3-66558781a54a">

Expected behaviour
- The text input width should be not exceed card width

**Comment by Bonapara** [comment]
Thanks for raising this @rathodvinod5, but this is a desired behavior ;)

**Comment by rathodvinod5** [comment]
Thanks @Bonapara
