### ISSUE TITLE
dropdown menu doesn't close and remains open

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#8285]
## Bug Description

- In fields containing dropdown menus items container, on clicking the three dots the menu doesn't close and remains open until user closes it.
- Ideally, the previous dropdown menu should close when next dropdown menu is triggered. As a result, multiple dropdown menu can be triggered at the same time.

## Current Behaviour

https://github.com/user-attachments/assets/d8c6c85b-b37a-45a0-8dd9-35b4bce643ef

**Comment by harshit078** [comment]
- Adding to this issue, Currency picker dropdown doesn't close after selecting a currency and remains open until clickOutside.

https://github.com/user-attachments/assets/70fe9510-8fa4-450a-b0d4-09a0b944de98

**Comment by stevenysy** [comment]
Can I try this? This would be my first issue

**Comment by VamshiAlugoju** [comment]
@harshit078  is the issue fixed? I cannot reproduce it. Seems like its working fine.
