### ISSUE TITLE
Error in devtools while checking Security tab

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8297]
**Scenario:**
1. Log in
2. Go to Settings > Security

**Actual:** There's error in devtools about `isDisabled` attribute
![image](https://github.com/user-attachments/assets/7bd967ca-3e7e-45c7-a968-705259b82e5b)

**Expected:** There should be no error in devtools

CC: @AMoreaux

**Comment by harshrajeevsingh** [comment]
I'm working on this :)
