### ISSUE TITLE
As a user, when I add an email to a person, in show page, I see timeline "add email event" not properly formatted

### ISSUE THREAD

**Issue by martmull** [twentyhq/twenty#8300]
## Bug Description
- create a user
- add an email
- go to user show page
- see issue in timeline
![image](https://github.com/user-attachments/assets/4ed1d15a-5d10-428d-8379-e3614b1a129c)
- if i add an aditional email, the additional emails are poorly rendered
![image](https://github.com/user-attachments/assets/7beca6b1-18d6-442b-9291-a2c6f687c00a)
<img width="1231" alt="image" src="https://github.com/user-attachments/assets/6fd063aa-2126-4eae-afc2-bd0e64af6f9b">

## Expected behavior

No `[` `]` visible for composite fields

## Technical input
- for composite fields, arrays are returned as strings not as array in `FindManyTimelineActivities`. In the front, they are expected to be array. We might fix backend so it returns a proper array
<img width="369" alt="image" src="https://github.com/user-attachments/assets/f9874b72-7bec-435e-ae0a-e8d5da0f900e">

**Comment by Bonapara** [comment]
Related to https://github.com/twentyhq/twenty/issues/8264

**Comment by yashkhokhar28** [comment]
I would like to work on it.

**Comment by Bonapara** [comment]
Sure @yashkhokhar28! Please have a look to the related issue. Thanks for contributing!

**Comment by sarvagyakrcs** [comment]
I would like to work on it

**Comment by FelixMalfait** [comment]
@ad-elias would you mind having a look at this one later? Thank you!

**Comment by ad-elias** [comment]
@FelixMalfait Sure!

**Comment by FelixMalfait** [comment]
@ad-elias as discussed, let's let Martin do it since he assigned himself

**Comment by martmull** [comment]
too hard for me, giving that to @Weiko
