### ISSUE TITLE
Self hosting documentation is out of date for v0.32.0

### ISSUE THREAD

**Issue by chsasank** [twentyhq/twenty#8301]
With v0.32.0 version, app-secret replaces other secrets: https://github.com/twentyhq/twenty/blob/740ca550cc17fa5d6277e3b531b4812d79951f69/packages/twenty-website/src/content/developers/self-hosting/upgrade-guide.mdx#v0310-to-v0320

But documentation is still for old version:

https://twenty.com/developers/section/self-hosting/docker-compose#option-2:-manual-steps

v0.32 is not yet on docker hub. So looks more yet to release. But note that the docker compose and env link in documentation has main links: 

```
curl -O https://raw.githubusercontent.com/twentyhq/twenty/main/packages/twenty-docker/docker-compose.yml
```

**Comment by BOHEUS** [comment]
@chsasank documentation is outdated because changes made last week aren't live, not sure why that's the case or when docs updates will be live but it's already done in #7810

**Comment by chsasank** [comment]
The issue is documentation has the docker compose link from main branch when it should be last tagged stable release.

**Comment by skyfox675** [comment]
A quick side-note, it looks like somewhere around v0.24.0 the right-panel anchors stopped publishing

**Comment by BOHEUS** [comment]
@skyfox675 I'd wait for the release, if core team won't update docs after the release, then go ahead

**Comment by FelixMalfait** [comment]
Sorry for not replying to this. Doc has been updated since 😅

We also improve the 1-click install script to be much smart about which version to pull for docker-compose/.env/image version
