### ISSUE TITLE
Action menu buttons alignment

### ISSUE THREAD

**Issue by ehconitin** [twentyhq/twenty#8304]
## Bug Description
@Bonapara 
Unnecessary gap after more button
**Example:** 

https://github.com/user-attachments/assets/e583f285-8a9b-41dc-b867-8fa0dc85f9a5

## Expected behavior

https://github.com/user-attachments/assets/07de86dc-13bf-4e0d-bdf2-0535f28eb605

**Comment by Yashgupta9330** [comment]
I want to work on this issue can you assign it to me

**Comment by Bonapara** [comment]
Sure @Yashgupta9330, thanks for contributing!

**Comment by BaoHanNgHuynh** [comment]
Hi, I want to work this issue. Can you assign it to me
