### ISSUE TITLE
Copy buttons not copying input field to clipboard

### ISSUE THREAD

**Issue by usag1r** [twentyhq/twenty#8305]
## Bug Description

Copy buttons such as the one next to API key field are not functioning properly. Previously other fields with copy button also didn't work.

### Example 1: Next to API key copy button
Notification shows up as "successfully copied" but Ctrl+V shows content hasn't been copied
### Example 2: Settings > Members > Invite User copy button
same bug behavior

## Technical inputs

**Environment:** 
```
- Twenty CRM latest version 0.31, docker 2+
- Server OS is cloud hosted on Enterprise Linux.
- Client OS is also Linux, browser is Firefox
```

**Comment by ehconitin** [comment]
I tried it on Firefox and Chrome, and it works fine on both!

**Comment by jhmonroe** [comment]
Confirming this is still happening (self-hosted). it says "could not copy" (on the red warning overlay) from the copy icon from the webhooks in workflow

**Comment by FelixMalfait** [comment]
Are you on HTTPS? I think that's the issue usually

**Comment by FelixMalfait** [comment]
@claude could you please confirm if there's an issue with copy across the app when the domain isn't localhost nor https? I'm pretty sure browser apis block this and that it would be the issue. In that case /then we should probably have a more descriptive error message for end-users when we know it failed for this reason. Raise a PR to fix that, but only if you can do it in a centralized way, this shouldn't be scattered across the codebase?

**Comment by jhmonroe** [comment]
@FelixMalfait yes! on http. just this morning came across your note while re-reading this page: https://docs.twenty.com/developers/self-host/capabilities/docker-compose

thanks for your updates above!

**Comment by jhmonroe** [comment]
PS: confirming all copy buttons work now that I added SSL on my cloud compute and all necessary nginx, A records, etc! thank you!

**Comment by FelixMalfait** [comment]
Great! Thanks for letting us know
