### ISSUE TITLE
Slash Menu has more height than it's content

### ISSUE THREAD

**Issue by Hitarthsheth07** [twentyhq/twenty#8326]
## Bug Description

The slash menu takes up more space vertically than needed. 

![image](https://github.com/user-attachments/assets/76b94abd-48b4-4405-9da6-a2b6f4ef5f53)

## Expected Behavior

The height should not exceed more than required to wrap element inside it. 
![image](https://github.com/user-attachments/assets/49257c8d-b2a3-4f6e-bc5e-1133de534cfe)

**Comment by Bonapara** [comment]
Thanks for fixing this @Hitarthsheth07 ;)
