### ISSUE TITLE
The sign-in with Google option is not functioning on the hosted platform.

### ISSUE THREAD

**Issue by skdishansachin** [twentyhq/twenty#8330]
I attempted to sign up for the platform using my Google account, but it failed and displayed a 500 Internal Server Error.

![image](https://github.com/user-attachments/assets/093832b7-4958-418f-a564-3bc8ab065a6d)

**Steps I took -**

1, Visit this URL - [https://app.twenty.com/welcome](https://app.twenty.com/welcome)

2, Click on *Continue with Google* button.

3, I was prompted to select my Google account.

4, On the redirect back it failed and displayed a 500 Internal server error.

**Comment by Bonapara** [comment]
We fixed the issue, sorry for the inconvenience @skdishansachin 🙏
