### ISSUE TITLE
Add fields column disappears after all fields

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#8331]
## Bug Description

- Currently, when user has selected all fields in a relation then the column to add fields disappears and doesn't allow the user to customize fields unless he hides a field.
- Expected behaviour should be that add fields column should be present at all times and allow users to select customize fields even when selected all fields. 

## Current Behaviour

<img width="1048" alt="Screenshot 2024-11-05 at 1 06 27 PM" src="https://github.com/user-attachments/assets/55b5dfcd-1137-4e3b-924a-539eb5c04e06">
<img width="915" alt="Screenshot 2024-11-05 at 1 07 00 PM" src="https://github.com/user-attachments/assets/1ba255f9-c9ba-4c56-9462-0894d5fa6142">

**Comment by Bonapara** [comment]
We can keep the customize field button when there are no more fields to show.

**Comment by heypratik** [comment]
@Bonapara Please assign this bug to me

**Comment by Bonapara** [comment]
Thanks for contributing @heypratik

**Comment by nealgoogs** [comment]
has this issue been solved?

**Comment by Bonapara** [comment]
Not yet @nealgoogs!

**Comment by aushwin** [comment]
Having trouble reproducing this (Actually I might be doing it wrong)... @harshit078 Can you drop a video if possible ?

**Comment by harshit078** [comment]
@Bonapara if no one is solving this I'll take this up, already working in this area !

**Comment by Bonapara** [comment]
Sure @harshit078, thanks for contributing!

**Comment by JorgeGraciaViveros** [comment]
Hello @harshit078 @Bonapara  ! I am currently working in a group of 5 students from CMU taking an introductory software engineering course and our final project is to contribute to an open-source repo. Our project has multiple checkpoints and will be due on December 8 (meaning our PR will take longer to open). Would it be possible for us to be assigned to this issue (or any issues that you think would be a good fit)? Thanks!

**Comment by Bonapara** [comment]
@harshit078 Can I close this? Did you fix it in your PR?

**Comment by harshit078** [comment]
@Bonapara yes, please close this
