### ISSUE TITLE
Minimisation of fields occurs in one window

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#8335]
## Bug Description

- When minimising a task/note or email, the minimisation occurs in only window resulting in losing previous minimsation state.

https://github.com/user-attachments/assets/cc4141ef-f464-408b-8b77-7e9545535583

- When minimising, the state which has been minimised cannot be opened by clicking that state. It will only reopen on clicking the minimised box.
- Any other state can open the minimised state even though it is not the same state.

https://github.com/user-attachments/assets/168957b7-f225-44fe-ba37-116d47f976bd

## Expected behavior

- The minimised state should only be reopened by the state which it was closed by.
- **feat**: Add multiple windows for minimised state resulting in smooth layout

**Comment by harshit078** [comment]
- The minimised state remains placed everywhere resulting in a bug specially in settings

https://github.com/user-attachments/assets/f6e152d1-1c71-4a7a-8c6c-9e563cd2a3eb

**Comment by Bonapara** [comment]
@bosiraphael FYI, I'll close this for now as we plan to address it in the near future. I will create the issue myself with more details. Thanks, @harshit078, for sharing it!
