### ISSUE TITLE
The menu that opens when you right click with the mouse in the companies table is not obvious.

### ISSUE THREAD

**Issue by HusemZ** [twentyhq/twenty#8341]
![image](https://github.com/user-attachments/assets/f078a0b3-8bc7-45c2-9be1-380b9c29015a)

**Comment by AjayAdsule** [comment]
can i work on this issue

**Comment by harshrajeevsingh** [comment]
Can't reproduce on main. What browser are you using?

**Comment by Bonapara** [comment]
Was able to reproduce on demo.twenty.com using Chrome

**Comment by FelixMalfait** [comment]
Closing as this has been fixed! Thanks for the report
