### ISSUE TITLE
Header should be Small/Medium

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8350]
# Current behavior

Menu Titles are `Small/Medium`

![CleanShot 2024-11-05 at 19 01 41](https://github.com/user-attachments/assets/b81871ec-605a-403f-93f3-5e75b1fc0725)

# Desired Behavior

They should use `Base/Medium`

![image](https://github.com/user-attachments/assets/1f898f89-25cd-4b51-8ed3-acdb6cae3127)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=2979-174004&node-type=frame&t=fx0JJQdJ9FGZ4S4D-11

**Careful, the dropdown header font-size should stay base/small/medium:** 

![image](https://github.com/user-attachments/assets/7cda9970-e2cb-4e1e-b366-4e0be5bf3826)

**Comment by khuddite** [comment]
@Bonapara Can you assign this issue to me? Thanks
