### ISSUE TITLE
Increase `Filter` `Sort` and `Options` menu width

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8357]
# Current behavior

The menu's width is `160px`.

![CleanShot 2024-11-06 at 09 12 17](https://github.com/user-attachments/assets/3950e505-b27c-4020-99a2-b127d677d1ae)

# Desired Behavior

Increase the menu's width to `200px`

![CleanShot 2024-11-06 at 09 09 36](https://github.com/user-attachments/assets/d34e1361-8eda-4a1e-8933-f5770c003a7c)

**Comment by harshrajeevsingh** [comment]
Only be done for ```Filter```, ```Sort``` & ```Options``` ?

**Comment by yadavshubham01** [comment]
Hey @Bonapara please me assign this issue

**Comment by Bonapara** [comment]
Fixed by the core team

**Comment by khuddite** [comment]
@Bonapara Can you help attach the PR link here? I have been looking into the issue as well, and it was not apparent to me what/how to change it without impacting other parts of the app.

**Comment by Bonapara** [comment]
Can't find the the PR, but @charlesBochet did it as a release fix earlier this week!
