### ISSUE TITLE
Sidebar clips items when list is too long

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#8358]
## Bug Description

- Sidebar clips items when favorites list is long resulting in some items getting clipped
- Settings option gets cropped due to which it can be difficult to access it
- Support isn't optimised for minimised state bar.

https://github.com/user-attachments/assets/bdc324e3-3739-4d58-8cef-5caa5f613613

https://github.com/user-attachments/assets/4caf0722-5692-433b-abd0-ddbdfd24689b

## Expected behavior

- Favorites list should be scrollable too when the list is long.
- Support button should only have its button and not text

**Comment by harshrajeevsingh** [comment]
Same behaviour #8063

**Comment by Bonapara** [comment]
Closing as duplicate (Support button has been fixed yesterday)
