### ISSUE TITLE
Settings is not showing properly

### ISSUE THREAD

**Issue by harishnanthan** [twentyhq/twenty#8359]
## Bug Description
      Settings CTA is not showing properly because of the height of the left slider. 

## Technical inputs
      -Need to fix the height of the left side containers using CSS
      
 ## SS     
<img width="190" alt="image" src="https://github.com/user-attachments/assets/a097baf6-d179-4d0a-a60c-feaa8755e8e6">

Settings is hided here below the search.

**Comment by Bonapara** [comment]
great point, there should be no scroll on sidebar. @ehconitin do you think you can fix this in your PR?

**Comment by harishnanthan** [comment]
Can i fix this @Bonapara pls assign to me

**Comment by ehconitin** [comment]
@Bonapara yep, I removed the scroll in the PR already!

**Comment by Bonapara** [comment]
Closing this issue then, thanks everyone
