### ISSUE TITLE
Add storybook tests on UI module

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#838]
We should test more components on our UI module storybook:
https://main--647862655ef7071d35328bb2.chromatic.com/

## Todo
- Create detailed tickets on what we would like to test in @/ui folder

**Comment by FelixMalfait** [comment]
Spec needed: list which stories are missing

**Comment by thaisguigon** [comment]
List of folders with untested components in @/ui :
- @/ui/animation/components/*
- @/ui/board/card-field/components/*
- @/ui/board/components/* => currently only BoardColumnEditTitleMenu is tested
- @/ui/checkmark/components/* #895 
- @/ui/color-scheme/components/ColorSchemePicker
- @/ui/display/component/*
- @/ui/editor/components/*
- @/ui/filter-n-stort/components/*
- @/ui/icon/components/*
- @/ui/inplace-input/components/*
- @/ui/input/components => Checkbox, DatePicker, ImageInput
- @/ui/layout/components/*
- @/ui/layout/show-page/components/*
- @/ui/layout/top-bar/components/*
- @/ui/link/components/RawLink
- @/ui/modal/components/* #893 
- @/ui/navbar/components/*
- @/ui/progress-bar/components/* #894 
- @/ui/relation-picker/components/*
- @/ui/right-drawer/components/* => currently only RightDrawerTopBar is tested
- @/ui/snack-bar/components/*
- @/ui/table/components/*
- @/ui/table/action-bar/components/*
- @/ui/table/editable-cell/components/* & @/ui/table/editable-cell/types => currently only EditableCellText is tested
- @/ui/title/components/* #892 
- @/ui/tooltip/* #891

**Comment by FelixMalfait** [comment]
Closing as it's marked as "done" in project board
