### ISSUE TITLE
Environment variable IS_SIGN_UP_DISABLED ignored

### ISSUE THREAD

**Issue by florianloewen** [twentyhq/twenty#8386]
## Description

Twenty ignores set environment variable IS_SIGN_UP_DISABLED with value "true". Twenty fails to block new workspace creation.

## Expected behavior

Block the creation of new accounts and workspaces without explicit invites.

## Details

Install command: bash <(curl -sL https://git.new/20)
Reproduced with: twenty v0.31.0 – v0.32.0
Fresh install: Yes

**Comment by FelixMalfait** [comment]
@AMoreaux could you please fix this in the next release? Thanks a lot!
