### ISSUE TITLE
I can search through Activities title and bodies

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#839]
As of today cmd+k only allows searching through companies/people.

We would like to search through Notes too.

**Comment by Bonapara** [comment]
V1 should display the note title in a new "Notes" Section. V2 will introduce a side panel to preview the result.

![Image](https://github.com/twentyhq/twenty/assets/19412894/92875d56-b5ad-4693-844f-ce0f6a6a04fe)
