### ISSUE TITLE
Default login information same as in the demo

### ISSUE THREAD

**Issue by kbkozlev** [twentyhq/twenty#8395]
## Bug Description

When self-hosting, when I open the page, the login information from the demo is already prefilled.

## Expected behavior

The login fields should be empty so that a user can login 
![image](https://github.com/user-attachments/assets/77b1b76a-6f65-4bbf-b44c-f9ea148646dd)

**Comment by BOHEUS** [comment]
That's expected as login info for demo and self hosted instance is the same

**Comment by kbkozlev** [comment]
> That's expected as login info for demo and self hosted instance is the same

Can this be removed? Or where is this stored in the code?

**Comment by BOHEUS** [comment]
There's environmental variable called SIGN_IN_PREFILLED responsible for filling data in login page https://twenty.com/developers/section/self-hosting/self-hosting-var

**Comment by kbkozlev** [comment]
Thank you this solved it!
