### ISSUE TITLE
Problems with documentation in mobile view

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8396]
Layout of [environment variables](https://twenty.com/developers/section/self-hosting/self-hosting-var), [1-click Docker Compose](https://twenty.com/developers/section/self-hosting/docker-compose), [Cloud providers](https://twenty.com/developers/section/self-hosting/cloud-providers), [Best practices - front](https://twenty.com/developers/section/frontend-development/best-practices-front), [Backend commands](https://twenty.com/developers/section/backend-development/server-commands),  is broken when viewport has less than 450px width
![image](https://github.com/user-attachments/assets/035855f6-c045-42d8-a6e4-edd32cd37534)

Code in heading is broken when viewing on mobile (768px width or less)
![image](https://github.com/user-attachments/assets/c937beb8-c5cd-47d7-b77d-e596cb10ee56)

**Comment by khuddite** [comment]
I am looking at the issue

**Comment by khuddite** [comment]
@BOHEUS, what's the desired font size for the code in the heading?
