### ISSUE TITLE
Table with record groups can handle record re-order

### ISSUE THREAD

**Issue by magrinj** [twentyhq/twenty#8403]
Table in with multiple record groups should handle correctly re-order of record under the same record group.

**Comment by Nastyga** [comment]
> Table in with multiple record groups should handle correctly re-order of record under the same record group.

[Skip to content](https://github.com/twentyhq/twenty/actions/runs/11740821958/job/32708183520?pr=8405#start-of-content)
Navigation Menu

Code
Issues
305
Pull requests
41
[Discussions](https://github.com/twentyhq/twenty/discussions)
[Back to pull request #8405](https://github.com/twentyhq/twenty/pull/8405)
Add CI timeouts and enable playwright #13699
Annotations
1 warning
danger-js
succeeded 14 minutes ago in 43s
1s
Current runner version: '2.320.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v4' (SHA:[1](https://github.com/twentyhq/twenty/actions/runs/11740821958/job/32708183520?pr=8405#step:1:1)1bd71901bbe5b1630ceea73d27597364c9af683)
Complete job name: danger-js
[2](https://github.com/twentyhq/twenty/actions/runs/11740821958/job/32708183520?pr=8405#step:1:2)s
Run actions/checkout@v4
Syncing repository: twentyhq/twenty
Getting Git version info
Temporarily overriding HOME='/home/runner/work/_temp/ba5e88dd-2c77-424[6](https://github.com/twentyhq/twenty/actions/runs/11740821958/job/32708183520?pr=8405#step:1:7)-927f-6c28727b290c' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/twenty/twenty
Deleting the contents of '/home/runner/work/twenty/twenty'
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
Determining the checkout info
/usr/bin/git sparse-checkout disable
/usr/bin/git config --local --unset-all extensions.worktreeConfig
Checking out the ref
/usr/bin/git log -1 --format=%H
b2004fe6b490c7a7e1c30d2afefa99f0d6f98af5
26s
[13](https://github.com/twentyhq/twenty/actions/runs/11740821958/job/32708183520?pr=8405#step:1:16)s
0s
0s
0s
FelixMalfait added 2 commits Temporarily enable it on PRs 49002fa Temporarily enable it on PRs d5993d1
