### ISSUE TITLE
Update opportunities "confidence" attribute

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#841]
- Change the "Lost" text to "0%"
- Give more height to dots containers so they are easier to click (see purple on the picture below)

![Image](https://github.com/twentyhq/twenty/assets/19412894/3989765a-eccb-4b02-ad50-eef40ec056a0)

**Comment by FelixMalfait** [comment]
Dots are currently 8px. Let's do 12px to keep a multiple of 4. (that will make that square).

**Comment by Bonapara** [comment]
To clarify, dots height should stay the same, but their container (which should be the one clickable) should be 16px heigh.

**Comment by FelixMalfait** [comment]
@Bonapara Thanks for clarifying, I didn't get it!

**Comment by jessicali2023** [comment]
@FelixMalfait I'll pick up this issue 😸 . I don't see an option to assign the issue to myself. Maybe I don't have the permission?

**Comment by FelixMalfait** [comment]
@jessicali2023 Thanks a lot!

Yes unfortunately you can't assign it to yourself, you have to comment on it first and then we can assign you (done!) 

The best would be to do the changes on the `main` branch of your main. That way, the maintainers of the repo will be able to push a small commit change to it.  If you create a new branch on your fork,  you can still create a working PR, but I believe we would lose those the rights to push a commit to your branch (mostly if we need to do a micro-fix and want to avoid back-and-forth)

**Comment by jessicali2023** [comment]
@FelixMalfait Thanks! Here is the PR from the fork. https://github.com/twentyhq/twenty/pull/921

**Comment by jessicali2023** [comment]
@FelixMalfait FYI https://github.com/twentyhq/twenty/pull/921 has been merged. Close the issue?

**Comment by FelixMalfait** [comment]
Thanks!
