### ISSUE TITLE
Add records selection context inside the command menu

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#8414]
## Scope & Context

Add records selection context inside the command menu.

![image](https://github.com/user-attachments/assets/7d8de697-0c16-4bef-be0f-2316997742c8)
![image](https://github.com/user-attachments/assets/8c4fd4ae-a2b8-4353-b97a-46be69b122e4)

## Current behavior

No context.

## Expected behavior

A record chip is displayed next to the command menu search bar when a record is selected.
When multiple records are selected, the number of selected records is displayed.
When all records are selected, 'All `objectName`' is displayed with the number of records.
When the user hits the `backspace` key when the search bar is empty, we should go back to the general command menu (ie. with no records selected)

## Technical inputs

Refactor `CommandMenu` by extracting the search bar into a component called `CommandMenuSearchBar`.
Create a component named `CommandMenuSearchBarContext`.
If the user hits `backspace` when the search bar is empty, we should reset the context of the command menu.

**Comment by Bonapara** [comment]
![image](https://github.com/user-attachments/assets/b19826dc-50c4-4bc2-8e31-b82c299aba08)

Design when several records are selected
