### ISSUE TITLE
feat: Future Sentry Integrations for Error Tracking

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#8415]
## Scope & Context

- Currently, we only use 2 main sentry integrations `browserTracingIntegration` and `replayIntegration`
- We can add few more sentry integrations which would help us catch many related errors - 

1. Global Handlers Integration: To capture unhandled exceptions and unhandled promise rejections. This would help us capture both unhandled exceptions and unhandled promise rejections and sent to Sentry.
2. Breadcrumbs Integration: To capture breadcrumbs for better context in error reports. It creates a trail of events that happened prior to an issue which would act as a rich datat logs.
3. Linked Errors Integration: To link errors that are caused by other errors.
4. CaptureConsoleIntegration: This would capture all failing console API calls made in our webapp as a result, we could get more context API calls.

## Technical Input

- https://docs.sentry.io/platforms/javascript/configuration/integrations/

**Comment by Bonapara** [comment]
@FelixMalfait will have better thoughts on this

**Comment by FelixMalfait** [comment]
Hey, thanks! But breadcrumbsIntegration, globalHandlers and linkedErrorsIntegration are auto enabed. CaptureConsole is not a good idea in my opinion.
