### ISSUE TITLE
Add csv upload/download feature

### ISSUE THREAD

**Issue by Morluche** [twentyhq/twenty#842]
As a user I would like to be able to import xls or csv files and map them to the fields in companies/people
```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/1025
- [ ] https://github.com/twentyhq/twenty/issues/1026
- [ ] https://github.com/twentyhq/twenty/issues/1027
- [ ] https://github.com/twentyhq/twenty/issues/1028
- [ ] https://github.com/twentyhq/twenty/issues/1029
- [ ] https://github.com/twentyhq/twenty/issues/1030
```

**Comment by FelixMalfait** [comment]
Thanks! We definitely need this but CSV import isn't trivial if you want to do it well (column mapping, etc.)
Ideally we'd find a solution like https://www.oneschema.co but open source. That led me to https://tableflow.com but it's written in go / you have to spin up a server so it's not going to help us much as we'd like to keep the install simple and have something written in typescript that we can embed.
Probably we'll have to build our own...

**Comment by FelixMalfait** [comment]
https://github.com/beamworks/react-csv-importer tried this which could be good but it still has many limitation (e.g. supports csv but not xls/xslx)

**Comment by FelixMalfait** [comment]
Ah much better: https://github.com/UgnisSoftware/react-spreadsheet-import this one looks great!

**Comment by FelixMalfait** [comment]
Adding tech spec needed for @charlesBochet to validate using the lib above. Also if you have any comments on how to do bulk inserts on the backend? I know this lib has downsides (it's already styled), but we could not afford rebuilding something similar now so I have a strong feeling this is the best path to take

@Bonapara We would need a design for the import button only. For the flow itself, the customization would be by passing variables that are in  this file: https://github.com/UgnisSoftware/react-spreadsheet-import/blob/master/src/theme.ts ; let us know if you want to give specific guidance (textColor, subtitleColor, borderColor, etc.)

**Comment by Bonapara** [comment]
The import button designed is in #1025

> @Bonapara We would need a design for the import button only. For the flow itself, the customization would be by passing variables that are in this file: https://github.com/UgnisSoftware/react-spreadsheet-import/blob/master/src/theme.ts ; let us know if you want to give specific guidance (textColor, subtitleColor, borderColor, etc.)
