### ISSUE TITLE
add a new option to the opportunities stage and it's not shown in the stage kanban view

### ISSUE THREAD

**Issue by code1704** [twentyhq/twenty#8443]
After adding a new option to the opportunities stage field,  the new option is not shown in the stage kanban view

<img width="803" alt="image" src="https://github.com/user-attachments/assets/2915e3e3-61e2-493d-ab4a-ba5c4f706e58">

<img width="1244" alt="image" src="https://github.com/user-attachments/assets/f079b7b2-f788-4e71-850b-2443d32acdb4">

**Comment by BOHEUS** [comment]
I do not reproduce it, are you sure you saved changes?

**Comment by code1704** [comment]
> I do not reproduce it, are you sure you saved changes?

Thanks for the quick reply. I cannot repro it. I will close this.
