### ISSUE TITLE
Incorrect Type for Multiselect Fields in OpenAPI Specification

### ISSUE THREAD

**Issue by asdev29** [twentyhq/twenty#8446]
## Description
In the OpenAPI specification, all multiselect fields currently have an incorrect type. The type is set as Enum, which represents a generated type for possible values. However, it should be a List<Enum>, as multiple values can be selected for these fields.

## Expected Behavior
Multiselect fields in OpenAPI should be represented as a list of the Enum type, allowing for multiple selections.

## The current implementation represents multiselect fields as a single Enum type, which limits the field to a single selection.

Steps to Reproduce

- Generate the OpenAPI specification.
- Check the type of any multiselect field.
- Observe that the field is defined as Enum instead of a List<Enum>.

**Comment by Bonapara** [comment]
@martmull Wdyt?

**Comment by martmull** [comment]
@asdev29 is right. In the image below, `multiSelect` field should be an array not a string
![image](https://github.com/user-attachments/assets/74594a36-29e0-479d-8b43-058cc8387a91)
