### ISSUE TITLE
Core API returns 403 errors

### ISSUE THREAD

**Issue by shodgson** [twentyhq/twenty#8449]
## Bug Description

The open-api/core endpoints can be reached, but the rest/* endpoints result in 403 errors, despite using a valid API key.

![image](https://github.com/user-attachments/assets/5b1ecefe-d150-4deb-b3d0-665a7ab231ca)

Observed in v0.32.3 on the demo server.

## Expected behavior

API responds with 200 and app data.

**Comment by Bonapara** [comment]
Is your API key still valid? I can't reproduce the issue:

![CleanShot 2024-11-11 at 12 00 37](https://github.com/user-attachments/assets/3d8fd1f5-2b65-4867-95e0-df5ff15d3f1e)

**Comment by Bonapara** [comment]
Closing in the meantime

**Comment by shodgson** [comment]
Oh, sorry - you are right. I didn't see the Auth token for the request. I thought the API token at the top was the only necessary token.

Thanks for your help.
