### ISSUE TITLE
Can't create new opportunity record in Kanban view if all companies are deleted

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8454]
**Scenario:**
1. Log in
2. Go to Companies
3. Delete all records permamently
4. Log out and log in to refresh cache
5. Go to Opportunities > By stage (Kanban) view
6. Click "+ New" button in any column

**Actual:** Empty popup appears with no results
![image](https://github.com/user-attachments/assets/2b001c14-3279-4447-ab9d-1a7b77ecf2d1)

**Expected:**If there are no Companies records, popup for creating new Opportunity record should like this [(it's visible in Opportunities when Company field in Opportunities object is disabled)](https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/object-record/record-board/record-board-column/components/RecordBoardColumnCardsContainer.tsx)
![image](https://github.com/user-attachments/assets/dc86fa5b-046a-45a1-a1cf-b4b5dddb33bf)

**Comment by Bonapara** [comment]
Hi @BOHEUS, I believe we shouldn't implement this in the short term to avoid complicating the codebase. However, I created this issue: https://github.com/twentyhq/twenty/issues/8455 to address the matter.
