### ISSUE TITLE
Relation picker no result and new record improvements

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8455]
# Current Behavior

![f9dc8a8a45d268784f6b0efcff5e0d501d58a6782ee53636d2ec22368a5caefa](https://github.com/user-attachments/assets/7352a9ed-823a-4eaf-ad4a-c210a8dd0ec6)

1. We display an unnecessarily prominent "No result" message.
2. It's unclear which object will have the record created.

# Desired Behavior

### 1 - No Result

Hide the "No result" message when the search or input yields no results.

### 2a - When Nothing is Typed in the Search

Display "Create _Object-name-singular_."

![CleanShot 2024-11-11 at 15 04 25](https://github.com/user-attachments/assets/dc24e70e-8a3b-4a3b-9a52-e9699d982825)

### 2b - When Something is Typed in the Search

Display "Create _Object-name-singular: Record name_."

![CleanShot 2024-11-11 at 15 03 28](https://github.com/user-attachments/assets/06a0acc8-b227-4939-9469-1db846e2cf51)

**Comment by khuddite** [comment]
I will look into the issue

**Comment by khuddite** [comment]
https://github.com/user-attachments/assets/bd76200f-6303-478a-aeaf-77774f3efa6a

@Bonapara I've found that when there are no results that match my search, `Create new` button is there and doesn't seem to work at all. Is it a separate issue?


https://github.com/user-attachments/assets/e57ee178-a793-4e57-ab84-e110258eb4be

Also, when the search input is empty, `Create new` button doesn't even appear. 

If they are not desired behaviors, I think they should be addressed first before this ticket.

**Comment by Bonapara** [comment]
@ehconitin that would indeed be the good behavior, but maybe it's too expensive?

Your second point is related to: https://github.com/twentyhq/twenty/issues/8169 @khuddite 

Thank you both

**Comment by ehconitin** [comment]
@Bonapara its definitely expensive, maybe just create a company and not show it in the right drawer?
I don't see any other use case where we would need a company in the right drawer

**Comment by ehconitin** [comment]
Oh there is already a pr for this one https://github.com/twentyhq/twenty/pull/8353

**Comment by khuddite** [comment]
@Bonapara So it sounds like what we wanna address in the scope of this ticket is to remove `No result`, correct?
