### ISSUE TITLE
Fix BullMQ deprecation warning

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8470]
When running Twenty on self-hosting instance, I found this error appear in the console
```
BullMQ: DEPRECATION WARNING! Your redis options maxRetriesPerRequest must be null. On the next versions having this settings will throw an exception
```

**Comment by FelixMalfait** [comment]
Could you try something like this and tell us if it goes away? (and raise a PR if it does). Thanks a lot!
<img width="519" alt="Screenshot 2024-11-13 at 16 10 38" src="https://github.com/user-attachments/assets/7a975217-ae0e-4db1-9e22-2672e725d10c">
