### ISSUE TITLE
Filters and Options not working

### ISSUE THREAD

**Issue by markusthiel** [twentyhq/twenty#8482]
## Bug Description

I tested v0.32 and 0.33, and as soon as I click on the filters in Companies, an error occurs:

Server’s on a coffee break
Object metadata item "viewFilterGroup" cannot be found in an array of 34 elements

Klicking on options right top corner:

Server’s on a coffee break
Object metadata item "viewGroup" cannot be found in an array of 34 elements

**Comment by charlesBochet** [comment]
Hi @markusthiel, please follow the upgrade guide: https://twenty.com/developers/section/self-hosting/upgrade-guide

If it still doesn't work, feel free to reach on our Discord!

**Comment by markusthiel** [comment]
I have, of course, done exactly that. Unfortunately, I am still encountering many errors. The search function also doesn’t work at all. As soon as I click on "Search," another message appears:

![error](https://github.com/user-attachments/assets/20ecc64a-1861-42f7-9e7f-3e533227e577)

I will try to contact via Discord.
