### ISSUE TITLE
Fix "The file does not exist" on Vite

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#8491]
We keep seeing this error when changing branches on the frontend:

<img width="1344" alt="Screenshot 2024-11-14 at 08 43 48" src="https://github.com/user-attachments/assets/02a54009-54a8-469f-a3ce-c7f0bfb4eaf6">
`The file does not exist at "/Users/felixmalfait/Projects/twenty/node_modules/.vite/packages/twenty-front/deps/chunk-6I2LCRRF.js?v=9b88e4ae" which is in the optimize deps directory. The dependency might be incompatible with the dep optimizer. Try adding it to `optimizeDeps.exclude`.`

Different solutions are suggested here: https://github.com/vitejs/vite/discussions/17738

```
  optimizeDeps: {
    exclude: [".vite"],
  },
```

```
 optimizeDeps: {
    force: true,
 },
```
```
optimizeDeps: {
exclude: ['node_modules/.cache']
}
```

TODO: understand impact and implement the best one

**Comment by FelixMalfait** [comment]
@yadavshubham01 are you still using AI to generate comments/PRs? You didn't replace [insert version] and [insert relevant dependencies]

**Comment by yadavshubham01** [comment]
Sorry but used for reply in professional way so I use AI

**Comment by FelixMalfait** [comment]
Hey @yadavshubham01 it's okay if you don't speak perfect english or speak in a "non-professional" way! It's much better than burying the message in a bunch of AI words where the initial intent gets lost :)
