### ISSUE TITLE
Phone, Email, Domain input Light Icon Button color change

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8492]
# Current behavior

The button color has changed to secondary.

![CleanShot 2024-11-14 at 09 02 41](https://github.com/user-attachments/assets/4e19337d-9c7a-4002-826a-03863c6e6848)

![CleanShot 2024-11-14 at 09 04 17](https://github.com/user-attachments/assets/855f47d8-ae2e-4dfe-8b65-959c464d2c2d)

# Desired Behavior

Use the "Light Icon Button" in its `Tertiary` variant.

![CleanShot 2024-11-14 at 09 05 02](https://github.com/user-attachments/assets/d4900c0d-10a0-4195-a764-a9b2ee3aa39a)

Make sure to do it for Domain, phone, and email inputs

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=28562-74852&node-type=instance&t=PcKBW7G3Bj3eu6UD-11

**Comment by aushwin** [comment]
@Bonapara Can I try out this ?

**Comment by ehconitin** [comment]
Sure @aushwin! Thanks for contributing!
