### ISSUE TITLE
New or Modified Stages not showing in Kanban View

### ISSUE THREAD

**Issue by usag1r** [twentyhq/twenty#8511]
## Bug Description
If you add a new Stage to Opportunities from the Data Model, it doesn't show in the "Kanban View" "by Stage". Also if you modify the name of an existing Stage such as *Customer* to *Client*, it will disappear from the by Stage view. They also don't show when trying to edit this view.

**Example:** 
![ksnip_20241115-110655](https://github.com/user-attachments/assets/44decff2-68c5-4bc5-be7c-7a315d2dfb27)
![ksnip_20241115-110817](https://github.com/user-attachments/assets/ce49c54a-c027-4c10-a0e0-952ecf982451)

**Comment by Bonapara** [comment]
Can't reproduce.

**Comment by usag1r** [comment]
Environment is self-hosted, docker/container. Local database. Twenty V0.32.0-canary

I just tried again on a different computer and the bug is still there. New stage option added to Opportunities in the Data Model not showing in Kanban View or Filters but it's showing inside the opportunity details as a valid option.

I also constantly get an error about *Meta information syncing error* or something like that. That's maybe because I chose 3rd option for email integration after signing up and then never actually integrated email. Probably not related to this.

**Comment by usag1r** [comment]
I just tried to replicate the same behavior with Status of Tasks, added new entry to Status Data Object and it also isn't showing up in Tasks Kanban View. I also tried adding new Kanban Views to no avail. So there is a disconnect with Kanban View catching these new entries. Similarly, if I change the name of original Statuses/Stages (i.e.: Customer or In-Progress) they will disappear from Kanban View.

**Comment by PhantasWeng** [comment]
> Can't reproduce. Any additional context?

I encountered the same issue.

Environment: Self-Hosted Docker

Version: 0.32.0

After creating the KANBAN view, if I add or edit the corresponding select, the already established KANBAN does not change and will not appear in the filter either.

**Comment by Bonapara** [comment]
@usag1r @PhantasWeng thanks. Can you open a thread on our Discord https://discord.com/invite/cx5n4Jzs57 help channel?

**Comment by Bonapara** [comment]
We will open an issue focused on the root cause of the problem after it's identified.

**Comment by usag1r** [comment]
Thanks for managing this @Bonapara 
Indeed @ehconitin , I just updated from 0.32.0 to 0.32.3 and the bug seems to have been fixed! Fantastic.
