### ISSUE TITLE
Onboarding 🐛 : Infinite loop if I want to sync Emails and Calendar

### ISSUE THREAD

**Issue by guillim** [twentyhq/twenty#8520]
## Bug Description

During the Onboarding, I encountered an issue trying to sync emails and calendar.
<img width="774" alt="Screenshot 2024-11-15 at 17 04 54" src="https://github.com/user-attachments/assets/4d4a5329-2552-4870-8805-76c8270fe433">

**Steps to reproduce** 
- ask someone to create an account for you 
- click on the email you received
- signup
- click "subject and metadata" and sync your calendar and emails
- click authorize on the next screens
- you end up again on the same screen, The loop starts again... so click "subject and metadata" and sync your calendar and emails...

## Expected behavior

You should end up in the hompage after the onboarding

## Technical inputs

Tested in production, cloud env from the twenty core team. Email Invitation to join the team was done by @FelixMalfait 
Browser : Chrome latest version

**Comment by bosiraphael** [comment]
@martmull

**Comment by martmull** [comment]
Can't reproduce locally or in production, I might miss something, can you post a screen record?

**Comment by guillim** [comment]
https://github.com/user-attachments/assets/a103ba85-3794-4959-a97f-26007d5d9ba2

**Comment by guillim** [comment]
@martmull is it good enough for you ? Do you need more information ?

**Comment by martmull** [comment]
@guillim I can reproduce if I begin to create a workspace that I leave in "PENDING_CREATION" state. Then the user is stuck in the infinite loop when being invited on another workspace
