### ISSUE TITLE
Feature Request: Add Quick Search (Ctrl + K) for All Objects by Record Text

### ISSUE THREAD

**Issue by asdev29** [twentyhq/twenty#8522]
## Scope & Context

**Example:** 

We are working on enabling users to use quick search (Ctrl + K) for all objects in their workspace.  
The ticket is about allowing search functionality for custom objects based on their record text in addition to standard objects.

## Current behavior

The quick search (Ctrl + K) functionality currently supports only standard objects (e.g., predefined types such as people, notes, or companies). Custom objects are not included in the search results, even if the record text matches the query.  

## Expected behavior

The quick search (Ctrl + K) should support both standard and custom objects. The search results should include any custom objects where the record text matches the query. And on click on the search result, user is redirected to detail page of the object

**Comment by FelixMalfait** [comment]
I agree we should have custom objects in the cmd+k. @ijreilly I guess this is a quick fix?

**Comment by asdev29** [comment]
@FelixMalfait is this comming as patch version  in 0.32?

**Comment by FelixMalfait** [comment]
@asdev29 sorry this will only be in 0.33
