### ISSUE TITLE
Documentation Table Error

### ISSUE THREAD

**Issue by Fierthraix** [twentyhq/twenty#8525]
## Scope & Context

**Example:** 
In the Documentation for **Auth** for [Environment Variables](https://twenty.com/developers/section/self-hosting/self-hosting-var#auth), it appears that `AUTH_GOOGLE_APIS_CALLBACK_URL` appears twice, first with `http://[YourDomain]/auth/google/redirect` and secondly with `http://[YourDomain]/auth/microsoft-apis/get-access-token`.  I think the second time, the Variable is supposed to be `AUTH_MICROSOFT_APIS_CALLBACK_URL` instead.

## Technical inputs
Documentation Change.

**Comment by FelixMalfait** [comment]
Thanks! Good catch
