### ISSUE TITLE
Left menu in settings shouldn't have 2 links

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#8531]
In the settings menu:

![Image](https://github.com/user-attachments/assets/ec209749-77b9-4953-961d-cbb6d066b726)

When I "cmd+click" there's the <Link> which opens a new tab as expected but I'm also redirected to the page in the current tab (which is unexpected). We should keep only the <Link> behavior as it's better for accessibility. There's probably an extra "onclick + navigate" that is un-necessary as the UndecoratedLink should be enough

**Comment by khuddite** [comment]
I am taking a look at the issue
