### ISSUE TITLE
Popup never yields on Docs?

### ISSUE THREAD

**Issue by alphastrata** [twentyhq/twenty#8539]
## Bug Description
![Image](https://github.com/user-attachments/assets/1ee7fd51-d7ea-4bb1-b6fe-bf1712c38efd)

Popup demanding API token does not yield despite entering API key & setting to Localhost.

I have tried FF, Chrome, Chrome beta & Brave.

**Example:** 
1. go here https://twenty.com/developers/rest-api/core#/
2. generate a (on your local instance) API key
3. copy pasta it in
4. get suck there forever?

## Expected behavior
1. go here https://twenty.com/developers/rest-api/core#/
2. generate a (on your local instance) API key
3. copy pasta it in
4. be able to access the docs.

A clear and concise description of what the expected behavior is.

**Example:** 
N/A

## Technical inputs

**Example:** 
N/A

Am I missing something?

Why don't you let ppl peruse the docs without a key at all?

**Comment by alphastrata** [comment]
It looks like the api-key generation is the problem (but I checked they are valid tokens  with (verbatim: ```sh
❯echo "eyJI....J9" | base64 -d | jq .
{
  "alg": "HS256",
  "typ": "JWT"
}
```
if you manually snip a token from your browser's network tab and use that instead of the one generated from the advanced menu's developer settings things appear normal... so maybe that's broken?

**Comment by Bonapara** [comment]
Can't reproduce using `main`

https://github.com/user-attachments/assets/b08ffb65-9486-461c-96af-aab031605dab

**Comment by Bonapara** [comment]
Any additional context @alphastrata? We need an api key as the documention is custom generated according to the data model. We might move it to the app to ease things in the future though

**Comment by alphastrata** [comment]
Interesting, yours does indeed work.. mine does not -- but I can copy paste a token from the browser for now so it's no big deal on my end.

Thanks for the speedy check, it's obviously on my end so happy to see this closed.
