### ISSUE TITLE
Add 'type' to reserved keywords

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#8543]
We had an issue with a user creating an object called "type" which caused issues.

We need to add "type" to the exclusion list here:  https://github.com/twentyhq/twenty/blob/main/packages/twenty-server/src/engine/metadata-modules/object-metadata/utils/validate-object-metadata-input.util.ts

**Comment by yadavshubham01** [comment]
hey @FelixMalfait can please assign this issue to me ?

**Comment by FelixMalfait** [comment]
Sure thanks @yadavshubham01

**Comment by yadavshubham01** [comment]
hey @FelixMalfait checkout this pr #8548

**Comment by FelixMalfait** [comment]
Thanks!
