### ISSUE TITLE
Unify dropdown behavior with floating-ui

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#8544]
## Scope & Context

We still have many dropdowns that don't have the right behavior (overflow problem, parent container resizing out of window, etc.) 

We want to unify the dropdown behavior by using the right configuration for our floating-ui middlewares which are already fully capable of handling our common use cases.

Then we will be able to remove any CSS workaround for this and let floating-ui fully handle the dropdowns, which is what we want.

- Secondary goal : have the search input placed at the bottom / top when floating-ui switches the position so it stays where it was before, when we have the list loading and floating-ui placing the dropdown at the opposite for example.

- We want to disable the create new button on record dropdowns when we cannot create : 

![Image](https://github.com/user-attachments/assets/38aa4de9-a0b4-4007-b8ae-9eb8fe5502cb)

- We want to fix the overflow / resize behavior which is not properly handled right now : 

![Image](https://github.com/user-attachments/assets/827102b5-207f-4818-bd0a-a3e8c67a7929)

**Comment by FelixMalfait** [comment]
@lucasbordeau I think I can speak on behalf of @Bonapara - happy to discuss whenever you want today

**Comment by lucasbordeau** [comment]
I updated the issue following our discussion.

**Comment by lucasbordeau** [comment]
Closing this issue as it's too vague and seem to duplicate other more precise issues in the master issue.
