### ISSUE TITLE
Table cell display first line only

### ISSUE THREAD

**Issue by guillim** [twentyhq/twenty#8552]
## Table cell

**See Example:**

![Image](https://github.com/user-attachments/assets/ac473f36-75b3-46e2-a3fe-12f17dd6a219)
 

## Current behavior

Currently in production you can see that properties types
- Rich text 
- text
have an incoherent behavior on tables, if they have more than one line.

## Expected behavior
We want the table to display only one line, even though the text record have more text than just one line.

## Technical input

This should be fixed with only CSS changes on the appropriate Table Cell component. Avoid using specific JS properties to solve this (discussed with @FelixMalfait today)

**Comment by khuddite** [comment]
I will take a look

**Comment by sinrajat43** [comment]
Can i pick this ??

**Comment by khuddite** [comment]
I am close to creating a PR

**Comment by JorgeGraciaViveros** [comment]
Hi @guillim ! I am currently working in a group of 5 students from CMU taking an introductory software engineering course and our final project is to contribute to an open-source repo. Our project has multiple checkpoints and will be due on December 8 (meaning our PR will take longer to open). Would it be possible for us to be assigned to this issue (or any issues that you think would be a good fit)? Thanks!

**Comment by guillim** [comment]
if you are close to a PR @khuddite let's go for that. I will assign it to you then.

**Comment by khuddite** [comment]
It's already in the PR
