### ISSUE TITLE
Preview : Inline Settings not reactive

### ISSUE THREAD

**Issue by guillim** [twentyhq/twenty#8556]
## Preview Form Settings are not reactive

**Example:** 
![Image](https://github.com/user-attachments/assets/75a5c8ce-7566-4178-b3dc-231c23e6062c)

## Current behavior

Go on [settings](http://localhost:3001/settings/objects/companies/) and click on a Number type. You can edit the number of decimals you would like to see. However, after changing to 0 decimals we can see the preview still with on decimal.

Same behavior on changing the "Number Type" and also the settings on Text type (Wrap record on pages)

## Expected behavior
The preview should be updated once the settings field is changed

## Technical Suggestion
- [ ] Numbers Settings Percentage
- [ ] Numbers Settings Decimals
- [ ] Text Settings
- [ ] Date Settings
- [ ] DateTime Settings

**Comment by JorgeGraciaViveros** [comment]
Hi @guillim ! I am currently working in a group of 5 students from CMU taking an introductory software engineering course and our final project is to contribute to an open-source repo. Our project has multiple checkpoints and will be due on December 8 (meaning our PR will take longer to open). Would it be possible for us to be assigned to this issue (or any issues that you think would be a good fit)? Thanks!

**Comment by guillim** [comment]
Hello @JorgeGraciaViveros ,
I believe you are looking for issues that have the label "Good first issue". They are well documented and pretty easy to start with. This issue requires a bit more work IMO. 
Many "Good first issue" are created every week, I am sure you will find what you want. 
Thanks for your future contributions !

**Comment by guillim** [comment]
Fields identified that will require changes :
- TEXT
- ADDRESS
- NUMBER

**Comment by JorgeGraciaViveros** [comment]
> Hello [@JorgeGraciaViveros](https://github.com/JorgeGraciaViveros) , I believe you are looking for issues that have the label "Good first issue". They are well documented and pretty easy to start with. This issue requires a bit more work IMO. Many "Good first issue" are created every week, I am sure you will find what you want. Thanks for your future contributions !

That is fine by us. Would you mind assigning it so we can take a jab at it?
