### ISSUE TITLE
cannot edit array item

### ISSUE THREAD

**Issue by code1704** [twentyhq/twenty#8578]
1. add field of type Array
2. add value item to that field
3. click edit and try edit the value 

bug: cannot edit the value

![Image](https://github.com/user-attachments/assets/cfdeb917-3089-4d63-bdcc-04855e6f1b8e)

**Comment by harshit078** [comment]
I'll take a look into this !

**Comment by JorgeGraciaViveros** [comment]
Hi @code1704 ! I am currently working in a group of 5 students from CMU taking an introductory software engineering course and our final project is to contribute to an open-source repo. Our project has multiple checkpoints and will be due on December 8 (meaning our PR will take longer to open). Would it be possible for us to be assigned to this issue (or any issues that you think would be a good fit)? Thanks!

**Comment by code1704** [comment]
> Hi [@code1704](https://github.com/code1704) ! I am currently working in a group of 5 students from CMU taking an introductory software engineering course and our final project is to contribute to an open-source repo. Our project has multiple checkpoints and will be due on December 8 (meaning our PR will take longer to open). Would it be possible for us to be assigned to this issue (or any issues that you think would be a good fit)? Thanks!

Thanks for your interest in contributing to this project. However, I am just a user of this project and not its maintainer, and I do not know how to assign the issue to you.
