### ISSUE TITLE
I can display company properties in people list

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#859]

**Comment by Bonapara** [comment]
Instead of displaying company properties in the people list, I think we should ease the navigation to the company detail page 

https://github.com/twentyhq/twenty/assets/19412894/105bb93e-d61e-4487-8df3-a4582610a03b

**Comment by FelixMalfait** [comment]
@Bonapara  Agree this isn't top priority, I logged it because "nested objects" needs to be thought of as a whole imo. And it's a powerful feature that we'll need long-term to have a robust platform.

I feel like the navigation to the company detail page is already easy and working well. Do you want to create a ticket for something in particular?

**Comment by Bonapara** [comment]
Nothing particular. As of now, I'm not convinced displaying Companies fieds in People table is a great idea from a product perspective, but let's see how things evolve!
