### ISSUE TITLE
cannot hide or move No Value for custom stage field on kanban view

### ISSUE THREAD

**Issue by code1704** [twentyhq/twenty#8591]
1. add a custom stage field to some object
2. add a kanban view

Bug: cannot hide No Value; cannot move No Value to the top

![Image](https://github.com/user-attachments/assets/cfbbe502-b928-4b3d-85a9-64f27585ee02)

**Comment by khuddite** [comment]
I will take a look

**Comment by sriharika13** [comment]
I understand the issue, Pl assign it to me, I can solve it

**Comment by khuddite** [comment]
@Bonapara It seems hide/dnd(drag-and-drop) has been intentionally disabled for no value groups in this PR - https://github.com/twentyhq/twenty/commit/e8d96cfd10fc4d6fd1bb9bf14dd6761e2f372120

Now, do we wanna change that behavior and not differentiate them?

You can check out these 2 specific lines in the PR - 
[const noValueViewGroups =](https://github.com/khuddite/twenty/blob/24c0b0f8733565912efda91077597773cb1909a1/packages/twenty-front/src/modules/views/components/ViewGroupsVisibilityDropdownSection.tsx#L53-L54)
[const viewGroupsWithoutNoValueGroups = viewGroups.filter(](https://github.com/khuddite/twenty/blob/24c0b0f8733565912efda91077597773cb1909a1/packages/twenty-front/src/modules/views/components/ViewGroupsVisibilityDropdownSection.tsx#L58)

**Comment by Bonapara** [comment]
Notion allows it, so I don't see why we wouldn't!
