### ISSUE TITLE
Navigation drawer clip while making folder in favorites

### ISSUE THREAD

**Issue by harshrajeevsingh** [twentyhq/twenty#8606]
### This is specific to Chromium-based browser on Linux
The navigation drawer overflows from the screen when a favourite folder input is active. 

![Image](https://github.com/user-attachments/assets/83af87bd-5e86-46e0-8722-3b7ec830c5cb)

https://github.com/user-attachments/assets/c33c8dc8-7f51-4958-8c44-5e96d10b991b

**Comment by Bonapara** [comment]
@ehconitin you may want to have a look

**Comment by ehconitin** [comment]
@Bonapara weird, I was just playing around with it and it seemed fine.
Will have another look!
Thanks for the report @harshrajeevsingh !

**Comment by harshrajeevsingh** [comment]
@ehconitin It's happening due to the padding of ```TEXT_INPUT_STYLE```.
It can be fixed by overriding padding in ```StyledTextInput``` of ```NavigationDrawerInput```. 

![Image](https://github.com/user-attachments/assets/fe07573f-090f-4ba1-b69e-03a6f8ca5760)

**Comment by ehconitin** [comment]
Give me your discord! I will add you

**Comment by harshrajeevsingh** [comment]
@ehconitin It's:   harsh_rk_singh
:)
