### ISSUE TITLE
Remove the right drawer full page button for emails and calendar events

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#8612]
## Scope & Context

The full page is implemented only for records for the moment, it redirects to the record showpage. There is no implementation of the full page for the calendar events and the emails.

## Technical inputs

Remove the right drawer full page button for emails and calendar events.

![Image](https://github.com/user-attachments/assets/2d284ae1-8f6f-4f09-b5a8-e0489b465f6e)

**Comment by yeonicy** [comment]
Hello @bosiraphael, I’d like to work on this issue. Could you please assign it to me? Thank you!
