### ISSUE TITLE
Dropdown Tick box

### ISSUE THREAD

**Issue by guillim** [twentyhq/twenty#8649]
# We would like to have a Dropdown Tick box for selected option in field metadata select

## Current behavior

When Selecting Currencies or Countries, you click on the dropdown. If you click again, there is no visual element showing that the row was clicked.

**Example:**
 
![Image](https://github.com/user-attachments/assets/56aee440-b1e0-4fee-bcd0-9348984740cb)

![Image](https://github.com/user-attachments/assets/efee38f7-bac1-41f9-9d67-71d72f9c8d2d)

## Expected behavior
Let's add a tickbox to show the selected item(s)

![Image](https://github.com/user-attachments/assets/be9b7ed8-5c18-4317-987c-a14eef40c9a4)

## Technical inputs
Only frontend work here. Backend should remain untouched.
- [ ] CodeBase review : check if this component has the option ready. 
- [ ] Check other components that might fulfill the requirements. If they exist, can we re-use them ?

Related to #8647 (search ability)

As view with @Bonapara

**Comment by Bellahuang3715** [comment]
Hi, I would like to take on this issue, can you please assign it to me? Thank you!

**Comment by AbdulQadeer-55** [comment]
Hi I would like to contribute on this feature can you please provide me instructions to get started contributing in this repo.

**Comment by guillim** [comment]
Did you start working on this @Rohitk131 ?

**Comment by Rohitk131** [comment]
Not yet
