### ISSUE TITLE
Rich Text Editor throws error

### ISSUE THREAD

**Issue by harshrajeevsingh** [twentyhq/twenty#8658]
## Bug Description

After writing some notes, if the tab changes or any navigation occurs, it throws an error. 

https://github.com/user-attachments/assets/0bf2ed48-3d1c-4078-9be1-28737a38a508

**Comment by artsinli** [comment]
I can take a look at this.

**Comment by FelixMalfait** [comment]
I think this was fixed here: https://github.com/twentyhq/twenty/pull/8676
