### ISSUE TITLE
Demo page doesn't load after logging in with test credentials

### ISSUE THREAD

**Issue by iamkhaya** [twentyhq/twenty#8667]
## Bug Description

The demo page does not load when you follow the instructions given on the[ user guides](https://twenty.com/user-guide/section/getting-started/what-is-twenty#demo). 

**Example:** 
[screenshot]![Image](https://github.com/user-attachments/assets/ebffd6aa-a866-4a7f-a5e8-15c7dba81537)
```
The demo page does not load, it briefly shows the landing page then moves on to show an error as shown below. 


```

## Expected behavior

The demo app should load when you correctly follow the instructions in the guides.

## Technical inputs

n/a

**Comment by FelixMalfait** [comment]
Sorry about that. A bad actor knows a way to crash the workspace by creating a specific object name and has been playing with us :). We need to rollout a fix. Thanks for the report!
