### ISSUE TITLE
Update 1-click install script to use /tags endpoint instead of /relase

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#8679]
In the two scripts here:
https://github.com/twentyhq/twenty/tree/main/packages/twenty-docker/scripts

We should call and parse `https://api.github.com/repos/twentyhq/twenty/tags ` 

Instead of `https://api.github.com/repos/twentyhq/twenty/releases/latest`

Because for sub-versions (ex: v0.32.4) we only create a tag and don't create a release so users will end-up with an outdated version (v0.32 instead of v0.32.4)

**Comment by MrSuddenJoy** [comment]
@FelixMalfait Its super easy thing to do.

**Comment by FelixMalfait** [comment]
@MrSuddenJoy feel free to raise a PR! Thanks! Please test it well

**Comment by yadavshubham01** [comment]
@FelixMalfait just solved this isssue review this  pr #8689
