### ISSUE TITLE
🔐 Guards and permissions

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#869]
We need a robust way to manage data-access in the context of multi-tenancy today, and in the context of user-defined roles and permissions tomorrow.

Example implementation on Hasura: https://hasura.io/docs/latest/auth/authorization/permissions/common-roles-auth-examples/

Library that could potentially help us: https://github.com/dimatill/graphql-shield

Other example:
https://www.producthunt.com/posts/permit-io

**Comment by Bonapara** [comment]
Closing as not planned in the short term. In the meantime see https://github.com/twentyhq/twenty/discussions/209
