### ISSUE TITLE
Clarify "Delete" vs "Detach" Actions in Object Detail View

### ISSUE THREAD

**Issue by asdev29** [twentyhq/twenty#8698]
## Problem Description
In the detail view of an object, there are options to "Detach" or "Delete" related fields. The current UI/UX implementation can cause confusion because:

- Users may mistake "Delete" as an action to only break the relationship between the current object and the related object.
- Clicking "Delete" completely removes the related object without any warning or confirmation.
- This leads to unintended data loss, where other objects that were related to the deleted object lose their relationship as well.
## Steps to Reproduce
- Navigate to the detail view of an object with related fields.
- Click the "Delete" option for a related field.
- Observe that the related object is permanently deleted without any confirmation, and all other objects lose their relationship with it.
![Image](https://github.com/user-attachments/assets/04b2684a-4508-4af2-bc7b-b84aa4fd6f32)
## Proposed Solution
- Introduce a confirmation popup for the "Delete" action.
- The popup should clearly warn the user that:
> - The related object will be permanently deleted.
>- The deletion will also break all relationships with other objects linked to the related object.
- Example confirmation message:
`"Are you sure you want to delete this related object? This action is irreversible and will break its relationship with all other associated objects."`
- Consider improving the UI to make the "Detach" and "Delete" options more distinct (e.g., different button styles or placement).

**Comment by asdev29** [comment]
Correction: it is not permanently deleted - it can be restored - but all other relationships with this object are not restored

**Comment by FelixMalfait** [comment]
cc @Bonapara for input.

**Comment by Bonapara** [comment]
Hi @asdev29, thanks for raising the issue. I agree with your point. Let's add a confirmation modal when "Delete" is pressed!

Title: `Delete Related Object_singular` _e.g. Object_singular: Companies _
Description: `"Are you sure you want to delete this related Object_singular? This action will break all its relationships with other objects."
`

**Comment by artsinli** [comment]
I can tackle this

**Comment by FelixMalfait** [comment]
Thanks @artsinli

**Comment by nitin251198** [comment]
@artsinli have you done this?

**Comment by khuddite** [comment]
It seems the issue was assigned 4 days ago but still not addressed. I created a PR here - https://github.com/twentyhq/twenty/pull/8818

**Comment by Bonapara** [comment]
thank you @khuddite!
