### ISSUE TITLE
Minor bugs in Add Fields Column

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#8699]
## Bug Description

- Currently, when clicked on AddFields column it is only clickable in the plus icon div area whereas the entire column header should be clickable
- the Plus icon should be aligned center

## Current behavior

https://github.com/user-attachments/assets/3d6ca5fd-9b73-4cef-af47-72a3df1b4829

## Expected Behaviour

https://github.com/user-attachments/assets/a3aebbcb-815c-46d5-837d-e8c4afa79843

**Comment by FelixMalfait** [comment]
Not sure about this one @harshit078 - let's wait for @Bonapara's input.  We don't want the centered (+) for sure.
We could try to make the whole bar clickable but that might be a bit more challenging than it appears to do it, I'm not sure if it's worth the effort.

**Comment by Bonapara** [comment]
I agree with @FelixMalfait. We should keep the plus sign aligned to the left and could make the entire cell clickable if not too costly.

**Comment by FelixMalfait** [comment]
@harshit078 let us know if you managed to make the entire cell clickable while keeping it aligned on the left and not affecting anything else in the current display (table resizing, etc.). If you don't manage to do it I think we should just close the issue for now. Thanks!

**Comment by harshit078** [comment]
@FelixMalfait I agree to your point, rather than making the entire headcell clickable for which we would have to refactor some other components. We should close this issue !
