### ISSUE TITLE
I receive a notification when I'm assigned to a task

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#870]

**Comment by jessicali2023** [comment]
@FelixMalfait I'm interested in this issue. Is this related to #827 ? Is the spec ready?

**Comment by FelixMalfait** [comment]
@jessicali2023 yes indeed, you can see the master issue here https://github.com/twentyhq/twenty/issues/815

The first step is to write the tech specs for #827. Do you want to take a shot at doing a proposal? It's not an easy task, it requires experience designing software, but I believe you do have this experience.

The 2 packages I linked are old and not popular enough so we cannot use them but we could take inspiration from them.
Laravel is a great source of inspiration on how to do notifications well: https://laravel.com/docs/10.x/notifications#sending-notifications. We probably also need a queue system too... 

So it's a definitely hard task. You could pick an issue labeled with "good first issue" instead if you're looking for something more hands-on and easier
