### ISSUE TITLE
Filter by True False in table UI

### ISSUE THREAD

**Issue by rob-luke** [twentyhq/twenty#8704]
## Scope & Context

I would love if I could filter by True/False (bool) fields.

## Current behavior

Currently you can sort by True/False, but not filter.

## Expected behavior

When in a view, I would like to be able to click on the column name and select filter. I would like to be able to filter by True or False.

**Comment by FelixMalfait** [comment]
Haha yes right in time :)
Just merged @ad-elias's PR so it should be in the next major release (maybe next sub-release but less likely)
