### ISSUE TITLE
Custom Icon Persists Across New View Creations

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8714]
# Bug description

By default, we now set the `table` or `kanban` icon for newly created views. The issue arises when a custom icon is assigned to a new view. If I create another custom view afterward, its icon will be set to the custom icon of the previously created view, even if the default table or kanban icon is displayed.

We want the default icon to apply instead of the previously used custom icon.

# How to reproduce

https://github.com/user-attachments/assets/362c2f5e-5bf1-4dd9-85a5-599200c15260

**Comment by Bonapara** [comment]
Thanks @harshit078! 🙏

**Comment by charlesBochet** [comment]
@harshit078 Thanks for taking this issue, this is a high priority bug and we would like to have a fix quickly on this one.
Are you available to tackle it today? Otherwise the core team can take over and we can assign you another issue :)

**Comment by harshit078** [comment]
@charlesBochet I couldn't get the time to complete the solution, please assign the core team.

**Comment by charlesBochet** [comment]
No worries! Thanks a lot for all the help @harshit078, it's much appreciated!
