### ISSUE TITLE
Scroll broken on DropDown listing hidden fields Column

### ISSUE THREAD

**Issue by martmull** [twentyhq/twenty#8716]
## Bug Description

When a lot of items are present in dropdown, we cannot scroll to see the last items

![Image](https://github.com/user-attachments/assets/4cbb4e61-d644-4af6-bafd-c148f66e13d4)

## Expected behavior

Dropdown should stop just before bottom of screen, but should overflow scroll when necessary

**Comment by harshrajeevsingh** [comment]
Hi @martmull I will take this up ;)
