### ISSUE TITLE
When google calendar / auth is enabled, the authentication, authorization and callbacks work, but calender sync fails

### ISSUE THREAD

**Issue by shairozan** [twentyhq/twenty#8743]
## Bug Description

Google authentication for SSO and calendar sync is enabled on the server. The google client-id and client-secret are set, and google integration works. SSO login for users is functional and we can see in the request that it's asking for calendar data:

![Image](https://github.com/user-attachments/assets/2d4926a7-37e2-4170-8f29-823aaa859dfe)

Right after adding the calendar, however we immediately end up with `sync failed`

![Image](https://github.com/user-attachments/assets/904591a6-1e84-4829-a735-aa5ed6f1d82c)

Is there any guidance on expectations for setup of the OIDC client from Google's side? Everything works purely from an OIDC perspective, but I'm not sure if there's something _additional_ I need to grant the client access to. From what I can see it's asking for the right data, just not sure why sync fails. 

# Server
We get this from the server logs:

```json
Exception Captured
  {
    operation: { name: 'GetCurrentUser', type: 'query' },
    document: 'query GetCurrentUser {\n' +
      '  currentUser {\n' +
      '    ...UserQueryFragment\n' +
      '    __typename\n' +
      '  }\n' +
      '}\n' +
      '\n' +
      'fragment UserQueryFragment on User {\n' +
      '  id\n' +
      '  firstName\n' +
      '  lastName\n' +
      '  email\n' +
      '  canImpersonate\n' +
      '  supportUserHash\n' +
      '  analyticsTinybirdJwts {\n' +
      '    getWebhookAnalytics\n' +
      '    getPageviewsAnalytics\n' +
      '    getUsersAnalytics\n' +
      '    getServerlessFunctionDuration\n' +
      '    getServerlessFunctionSuccessRate\n' +
      '    getServerlessFunctionErrorCount\n' +
      '    __typename\n' +
      '  }\n' +
      '  onboardingStatus\n' +
      '  workspaceMember {\n' +
      '    ...WorkspaceMemberQueryFragment\n' +
      '    __typename\n' +
      '  }\n' +
      '  workspaceMembers {\n' +
      '    ...WorkspaceMemberQueryFragment\n' +
      '    __typename\n' +
      '  }\n' +
      '  defaultWorkspace {\n' +
      '    id\n' +
      '    displayName\n' +
      '    logo\n' +
      '    domainName\n' +
      '    inviteHash\n' +
      '    allowImpersonation\n' +
      '    activationStatus\n' +
      '    isPublicInviteLinkEnabled\n' +
      '    hasValidEntrepriseKey\n' +
      '    featureFlags {\n' +
      '      id\n' +
      '      key\n' +
      '      value\n' +
      '      workspaceId\n' +
      '      __typename\n' +
      '    }\n' +
      '    metadataVersion\n' +
      '    currentBillingSubscription {\n' +
      '      id\n' +
      '      status\n' +
      '      interval\n' +
      '      __typename\n' +
      '    }\n' +
      '    workspaceMembersCount\n' +
      '    __typename\n' +
      '  }\n' +
      '  workspaces {\n' +
      '    workspace {\n' +
      '      id\n' +
      '      logo\n' +
      '      displayName\n' +
      '      domainName\n' +
      '      __typename\n' +
      '    }\n' +
      '    __typename\n' +
      '  }\n' +
      '  userVars\n' +
      '  __typename\n' +
      '}\n' +
      '\n' +
      'fragment WorkspaceMemberQueryFragment on WorkspaceMember {\n' +
      '  id\n' +
      '  name {\n' +
      '    firstName\n' +
      '    lastName\n' +
      '    __typename\n' +
      '  }\n' +
      '  colorScheme\n' +
      '  avatarUrl\n' +
      '  locale\n' +
      '  timeZone\n' +
      '  dateFormat\n' +
      '  timeFormat\n' +
      '  __typename\n' +
      '}',
    user: undefined
  }
  [
    ForbiddenException: Forbidden resource
        at canActivateFn (/app/node_modules/@nestjs/core/helpers/external-context-creator.js:157:23)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async target (/app/node_modules/@nestjs/core/helpers/external-context-creator.js:73:31)
        at async Object.currentUser (/app/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
        at async field.resolve (/app/node_modules/@envelop/on-resolve/cjs/index.js:36:42)
        at async /app/node_modules/@graphql-tools/executor/cjs/execution/promiseForObject.js:18:35
        at async Promise.all (index 0) {
      path: undefined,
      locations: undefined,
      extensions: { code: 'INTERNAL_SERVER_ERROR', response: 'Forbidden resource' }
    }
  ]
```

# Worker
And this from the worker logs 

```json
Exception Captured
  undefined
  [
    CalendarEventImportException [Error]: Unknown error occurred while importing calendar events for calendar channel 26519613-4550-4ed6-ab23-bfc1e4221d78 in workspace bb9899bf-1318-41e5-b9ea-4adf3081cfb9: Could not determine client ID from request.
        at CalendarEventImportErrorHandlerService.handleUnknownException (/app/packages/twenty-server/dist/src/modules/calendar/calendar-event-import-manager/services/calendar-event-import-exception-handler.service.js:100:15)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async CalendarEventImportErrorHandlerService.handleDriverException (/app/packages/twenty-server/dist/src/modules/calendar/calendar-event-import-manager/services/calendar-event-import-exception-handler.service.js:54:17)
        at async CalendarFetchEventsService.fetchCalendarEvents (/app/packages/twenty-server/dist/src/modules/calendar/calendar-event-import-manager/services/calendar-fetch-events.service.js:77:13)
        at async CalendarEventListFetchJob.handle (/app/packages/twenty-server/dist/src/modules/calendar/calendar-event-import-manager/jobs/calendar-event-list-fetch.job.js:54:17)
        at async MessageQueueExplorer.invokeProcessMethods (/app/packages/twenty-server/dist/src/engine/core-modules/message-queue/message-queue.explorer.js:111:17)
        at async MessageQueueExplorer.handleProcessor (/app/packages/twenty-server/dist/src/engine/core-modules/message-queue/message-queue.explorer.js:103:13)
        at async /app/packages/twenty-server/dist/src/engine/core-modules/message-queue/message-queue.explorer.js:79:17
        at async _bullmq.Worker [as processFn] (/app/packages/twenty-server/dist/src/engine/core-modules/message-queue/drivers/bullmq.driver.js:33:13)
        at async Worker.processJob (/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28) {
      code: 'UNKNOWN'
    }
  ]
```

## Expected behavior

1. Enable Google Auth
2. Add calendar via the UI
3. See Sync occuring

**Comment by bosiraphael** [comment]
Taking a look

**Comment by bosiraphael** [comment]
Hello @shairozan could you ping me on discord inside the help channel? It will be easier if we can exchange there.

**Comment by shairozan** [comment]
@bosiraphael Yeah I'll have to find the discord channel but I can shoot you a message there

**Comment by shairozan** [comment]
Wanted to clarify here that I resolved the source of this issue. The `Id` error referenced in the logs was because I had defined all of the `AUTH_GOOGLE` variables on the server, but not the worker. Now I'm in a state where it's still failing (`Sync failed`) without a lot of data, but I'll follow up on that in the discord separately

**Comment by FelixMalfait** [comment]
Thanks for the feedback @shairozan - created this as a followup https://github.com/twentyhq/twenty/issues/8780 I think we need to allow people to set env variables more easily without tweaking server configs

**Comment by shairozan** [comment]
@FelixMalfait I think it may not be necessary to do that. I feel like that's possibly pushing configuration too far into the application personally. From a setup perspective, I'm running in kubernetes, and the manifests that are available as a starting point are pretty limiting. I need to re-write a lot of them, but leveraging a config map in kubernetes removes the concern by just mounting the configmap to the environment for both the worker and the server such that the configuration is shared. 

Can we also supply .env files? If so we could just define the entire configuration as a config map / secret combination and mount it to the file system as well

**Comment by FelixMalfait** [comment]
@shairozan makes sense for Kubernetes/pro users, you will always be able to do it at that level if you want to. But I think many people just want Wordpress-like setup where you can configure your connected apps and config in an admin panel. It's two different audiences and it's possible to accommodate both I think, I just misclassified you! The goal of doing this and then the panel is also to provide a visual interface to surface potential config errors in a friendly way - which could in the end also be helpful for Kubernetes users

**Comment by viper151** [comment]
@shairozan @FelixMalfait  thank yo so much for this tip. The exact same issue existed also on Microsoft auth. I just needed to add the env variables in the worker as well so simply and yet I spent 3 hours trying to make this work.
