### ISSUE TITLE
Small fixes for the options menu

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8789]
# Current behavior

Today, in the View Options menu:

We display the Object name
We display a list icon whatever the view/object

![Image](https://github.com/user-attachments/assets/ae3a2e76-6e1a-4075-9b13-3f0caf398329)

# Desired Behavior

- The name of the menu header should be the view name (not the object name)
- We should display the proper view icon instead

**Comment by yadavshubham01** [comment]
hey @Bonapara please assign me this issue

**Comment by Bonapara** [comment]
related to https://github.com/twentyhq/twenty/issues/8200

**Comment by Lucifer4255** [comment]
![Image](https://github.com/user-attachments/assets/2245f5bd-29ec-4a91-b608-c673b8dd622a)
is this the desired output @Bonapara if so can you assign me this issue?
