### ISSUE TITLE
Invalid input syntax for type double precision: "first"

### ISSUE THREAD

**Issue by shawnhaywood** [twentyhq/twenty#8797]
## Bug Description

Successfully installed Twenty CRM on a fresh install of Ubuntu via Docker.  When I attempt to create an entry, I receive an error message "invalid input syntax for type double precision: "first".  

Log Info:  
extensions: {
server-1                |         code: 'INTERNAL_SERVER_ERROR',
server-1                |         response: 'invalid input syntax for type double precision: "first"'
server-1                |       }

```

```

```

**Comment by shawnhaywood** [comment]
![Image](https://github.com/user-attachments/assets/3931e20c-073d-46fd-a100-0e246bc00e7f)

**Comment by FelixMalfait** [comment]
Hey, sorry for this - this has been solved already in the latest images (v0.33.2+). Could you upgrade your docker image version and let us know if you still have the issue? I'll re-open this issue if you do!

**Comment by FelixMalfait** [comment]
I assume it was v0.33.1 or something like before?

**Comment by shawnhaywood** [comment]
Thank you for the reply.  Looks like I'm already running the current version 0.33.0

![Image](https://github.com/user-attachments/assets/3c703342-cc2c-4d49-8ae9-17d0fe71633b)

**Comment by shawnhaywood** [comment]
Thank you.  That fixed it.  I was running 0.33.0.
