### ISSUE TITLE
Search not working properly

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#880]
Search feature doesn't work properly, if I click G and then specific letter, there's no reaction (I suppose after clicking e.g. G and C, I should be moved to customers tab, but I'm not transferred) from the system

Scenario:
1. Click the Search
2. Click the G key on keyboard and one out of four showed in popup

Actual: Page doesn't change
Expected: Page should be changed?

Also, search popup could appear when I'm not focused on any field and I click / or ?, simply UX improvement

**Comment by FelixMalfait** [comment]
Yes this one is confusing. The shortcuts are actually meant to be using outside of any input. 

One way to educate people could be to display an a message if someone inputs "gp" or "gc", etc in the box to let them know it should be typed outside. 
Another option could be to add "gp" as a new property "on go to people" and similarly on other items. If there is an exact match with a shortcut then we hide all other results and only display the matching entry

**Comment by charlesBochet** [comment]
This has been solved by https://github.com/twentyhq/twenty/pull/996
