### ISSUE TITLE
Empty record by default

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#881]
When creating new record in companies/people, it's by default empty but user shouldn't be allowed to change pages when the main characteristic of record (I guess it's name) is empty

Scenario:
1. Go to Companies/People
2. Create new record

Actual: Record without any data is added and user can go to another page
Expected: Record should be added after user inserts key value (probably name), otherwise if user tries to change the page, the prompt for discarding changes should appear

**Comment by FelixMalfait** [comment]
Thanks for the suggestion!
I'm not sure we should change that. Blocking the navigation seems like a strange pattern we wouldn't want to enforce.
Maybe we could "cleanup" and not save anything if the user switches to a new page. But I'm not even sure it's worth it, maybe the user wants to check something on the company page and continue the record he was about to create?
