### ISSUE TITLE
Tasks and Notes created from Record show page have a null position

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#8810]
## Bug Description

Tasks and Notes created from Record show page have a null position

## Expected behavior

1) they should be sent with 'last'
2) the backend should not allow a null for positions (we should add a constraint + make sure the backend applies the defaultValue

Also: backfill existing positions

**Comment by FelixMalfait** [comment]
Related: https://github.com/twentyhq/twenty/issues/5268 - would be great if we could tackle both

**Comment by GANES1998** [comment]
Hi @FelixMalfait, Can I take this Bug. If so, can you please assign it to me?
