### ISSUE TITLE
Vertical Scroll Missing in "Company" Filter Dropdown

### ISSUE THREAD

**Issue by mdrazak2001** [twentyhq/twenty#8827]
## Bug Description
The filter dropdown for "**Company**" does not support vertical scrolling when the list of options exceeds the viewable area. This limits the ability to access options that are not immediately visible.

![Image](https://github.com/user-attachments/assets/90466d49-61c6-4369-9d0c-397eb3e06292)

## Expected behavior
The behavior should align with other dropdowns (e.g., The Filter dropdown itself) where vertical scrolling is supported.

**Comment by ehconitin** [comment]
related to #8807 ?

**Comment by lucasbordeau** [comment]
@ehconitin I'll fix it in my PR about dropdown refactor : https://github.com/twentyhq/twenty/pull/8807

**Comment by mdrazak2001** [comment]
Closing this as it will be fixed in https://github.com/twentyhq/twenty/pull/8807 by @lucasbordeau
