### ISSUE TITLE
Add international/formatted phone number input

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#883]
Company can have a letters in phone - solution: regex which assures that phone number contains only numbers, +, -, ( and )

Scenario:
1. Add new record or modify existing and insert letter in phone number

Actual: Record is properly saved
Expected: If user inserts any character which isn't number, +, - or (), then system should throw error, otherwise record should be properly saved

**Comment by FelixMalfait** [comment]
Yes I agree we should probably implement a proper library for phone formatting.
But I feel like displaying flags as it's usually done would clutter the interface.
Maybe we should display a flag on edition mode only but not on read mode?
Also it's annoying to have to change the default country everytime if you're not working with US clients. Should that come from a setting/client config? What do you think @Bonapara?

Tabler icons doesn't have flags. 


https://github.com/bl00mber/react-phone-input-2
https://github.com/benaubin/react-headless-phone-input
https://github.com/goveo/react-international-phone

**Comment by Bonapara** [comment]
I think you're talking about two different things?

@BOHEUS implementing Regex on phone numbers sounds like a good idea! We can run a regex when a user is closing a phone input to check it's an actual phone numbers. If it's not a proper phone number, we should return to previous value when the input is closed. 

We could attach a alert to inform the user the value he entered was not a valid phone number. 

<img width="569" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/392ab0ac-54ad-4d18-9a45-a3e5f29dd0a9">

@FelixMalfait Concerning the flags, I agree it would clutter the interface, and I think we can let the user insert a "+XX" in the phone number but don't need to display a flag picker for now.

**Comment by FelixMalfait** [comment]
@Bonapara We're talking about the same problem but different solutions.

I don't think we should use a regex or show an error. I think instead we should introduce a library to input the phone number properly.

On read-mode we should keep a simple display format that doesn't clutter the interface. But on edit mode we should provide  a more detailed interface to make sure the data remains clean (for example the day we want to integrate calls it will be a mess if we don't have the right country codes)

See how Hubspot does it for example :
<img width="634" alt="Screenshot 2023-07-26 at 09 16 20" src="https://github.com/twentyhq/twenty/assets/6399865/346b2c4c-be9b-4492-889a-f57bbd68e2f6">

It's the same for the address field. If we don't introduce a more sophisticated edition form, we'll end-up with unstructured data that will become a big burden in the future

**Comment by Bonapara** [comment]
Final design will be ready on Monday July 31.

**Comment by Bonapara** [comment]
@jenalla can you add the final design & behavior?

**Comment by jenalla** [comment]
This issue is now handled in the ticket #1055
