### ISSUE TITLE
Wrong phone format shown in table

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8838]
**Scenario:**
1. Log in
2. Go to People tab

**Actual:** Numbers have double plus sign at the beginning (when editing number, only 1 plus sign is visible)
![Image](https://github.com/user-attachments/assets/41d91afa-26aa-4860-987f-f6d40c3ca645)
![Image](https://github.com/user-attachments/assets/c747ae37-4eb4-4ef1-bac2-148b79ba457f)

**Expected:** Numbers must have single plus sign

**Comment by khuddite** [comment]
I've noticed the same issue yesterday. Let me take a look at it

**Comment by khuddite** [comment]
@Bonapara You can assign this ticket to me
