### ISSUE TITLE
Possibility to add custom icons

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#885]
Right now, icons are fetched once user types proper URL address but is there a way to add custom icons for company? If not, will it be added?

**Comment by FelixMalfait** [comment]
Thanks again!
We fetch the icon through https://faviconkit.com ; in most case it returns the right logo.
What would be your use case for a different logo?
I can see the use-case if the company doesn't have a website and is just an individual. But then we should probably handle it in the context of this issue then: https://github.com/twentyhq/twenty/issues/595
