### ISSUE TITLE
Calendar empty state is red instead of Blue

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8853]
# Current behavior

![Image](https://github.com/user-attachments/assets/f117f90d-8656-424d-a179-3f201087544c)

# Desired Behavior

The background should be blue. Understand why this happened to prevent causing issues elsewhere.

**Comment by ehconitin** [comment]
@Bonapara 
https://github.com/twentyhq/twenty/pull/6877/files :)

**Comment by Bonapara** [comment]
Right, it looks inverted with the soft-delete page empty state @ehconitin!

![Image](https://github.com/user-attachments/assets/b8929bb4-325f-4e4f-af19-9301ccc10c97)

![Image](https://github.com/user-attachments/assets/0aaf2cf0-bc52-41df-94b1-8ee23f40fc0d)
