### ISSUE TITLE
Skeleton loading on Table cells

### ISSUE THREAD

**Issue by emilienchvt** [twentyhq/twenty#886]
### Context

As of now, the skeleton loading for the table view is not working: when the query for fetching the company/people data is ongoing, we simply show an empty table.

### Problem

We do have the behaviour coded as part of the cell, see here:
https://github.com/twentyhq/twenty/blob/07180af8c02048a4672d11ee986eab3d5bd58af8/front/src/modules/ui/table/editable-cell/types/EditableCellText.tsx#L52

But the `loading` prop is not passed to the cells components when called.

### Proposed solution

We show some loading table rows while the results are being fetched.
- Define a `loading` piece of state for the table when fetching the data - example for `Companies`: https://github.com/twentyhq/twenty/blob/07180af8c02048a4672d11ee986eab3d5bd58af8/front/src/modules/companies/table/components/CompanyEntityTableData.tsx#L13
- Have columns render some skeleton-loading cells based on this state

### Pending points

Is that the design we want ? 
How many loading rows should we show (we most probably won't know how many rows the table has when loading the data) ?
@Bonapara

**Comment by Bonapara** [comment]
"we simply show an empty table." 
Today, we don't even show an "empty table" but a blank space right?

**Comment by Bonapara** [comment]
I think we can drop the idea of skeleton loading on tables for now as it would burden the experience
