### ISSUE TITLE
On People object, sorting by name.ascending prevents scrolling

### ISSUE THREAD

**Issue by phjackl3** [twentyhq/twenty#8863]
## Bug Description

Sorting the People object, by name ascending, does not display all people

**Example:** 
Go to your people object. Create at least 100 people with first names starting with all different letters of the alphabet
Sort by first name ascending and scroll down the list to see all names
The list will stop at about 50 people, will look like it's going to load more people, and will then stop
Sort by first name descending. All 100 people are visible.
Sort by first name ascending. Again, the list is cut off at about 50 people

## Expected behavior

All people should be visible when a sort is applied.

**Comment by Bonapara** [comment]
https://github.com/user-attachments/assets/402465f3-ce59-40f0-9c7b-8a2c406c1eca

**Comment by lucasbordeau** [comment]
The place where this bug appears is in `GraphqlQueryParser.applyFilterToBuilder` in the backend.

Somehow those variables in the frontend : 

```
{
  "filter": {},
  "orderBy": [
    {
      "name": {
        "firstName": "AscNullsFirst",
        "lastName": "AscNullsFirst"
      }
    },
    {
      "position": "AscNullsFirst"
    }
  ],
  "lastCursor": "eyJuYW1lIjp7ImZpcnN0TmFtZSI6IkNocmlzdG9waCIsImxhc3ROYW1lIjoiQ2FsbGlzdG8ifSwicG9zaXRpb24iOjEsImlkIjoiMjAyMDIwMjAtMWMwZS00OTRjLWExYjYtODViMWM2ZmVmYWE1In0="
}
```

Get transformed into the following query parameters : 

```
appliedFilters: '{\n' +
    '  and: [\n' +
    '    {},\n' +
    '    {\n' +
    '      or: [\n' +
    '        {\n' +
    '          name: {\n' +
    "            firstName: { lt: 'Christoph' },\n" +
    "            lastName: { lt: 'Callisto' }\n" +
    '          }\n' +
    '        },\n' +
    '        {\n' +
    '          name: {\n' +
    "            firstName: { eq: 'Christoph' },\n" +
    "            lastName: { eq: 'Callisto' }\n" +
    '          },\n' +
    '          position: { gt: 1 }\n' +
    '        },\n' +
    '        {\n' +
    '          name: {\n' +
    "            firstName: { eq: 'Christoph' },\n" +
    "            lastName: { eq: 'Callisto' }\n" +
    '          },\n' +
    '          position: { eq: 1 },\n' +
    "          id: { gt: '20202020-1c0e-494c-a1b6-85b1c6fefaa5' }\n" +
    '        }\n' +
    '      ]\n' +
    '    }\n' +
    '  ]\n' +
    '}'
```
