### ISSUE TITLE
Problematic notes

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#887]
Notes (in companies and people) - these are problematic, needs to be fixed as it affects UX

Scenario: 
1. Click any checkbox
2. Click 'Note' option at the bottom of page
3. Write one character in note text (not title)
4. Wait a 1 or 2 sec and delete it

Actual: After deleting character, interface will start bugging and flashing note's title (deleted character)
Expected: After deleting character, note's title should be empty unless user types something in context or in note's title

**Comment by FelixMalfait** [comment]
Thanks for this report! I tried to follow the steps, multiple time, but I haven't been able to reproduce. Would you mind sending a video?

**Comment by BOHEUS** [comment]
I tried reproducing it on prod version @ app.twenty.com without any results, probably some commit from yesterday which is live on prod fixed the problem.
