### ISSUE TITLE
Message and button for deleted filter appear after reset when filtering no deleted records

### ISSUE THREAD

**Issue by omarNaifer12** [twentyhq/twenty#8874]
When we are on the deleted records page and use the filter, if no records are found, we see the no deleted recordName message along with a button to remove the deleted filter. However, if we reset and filter again, and still don't find any records, this message and button for the deleted filter continue to display.
The message and button should only appear on the deleted records page and should not be shown after a reset.
![Image](https://github.com/user-attachments/assets/27357c18-d589-4336-8374-a0927ae95e75)

**Comment by omarNaifer12** [comment]
@Bonapara  Thank you! I made a pull request for this issue and I'm just waiting for it to be reviewed. I will do my best and learn as much as I can. If you know of any small issues like this one, for beginners or a bit more challenging, please let me know.

**Comment by Bonapara** [comment]
Sure, thanks @omarNaifer12!
