### ISSUE TITLE
Not secured domain input

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8876]
# Do not reproduce it unless you're willing to lose your data

**Scenario:**
1. Log in
2. Go to Settings > General, click Domain button
3. Change subdomain's URL
4. Save changes

**Actual:** Redirect works but if user types forbidden characters, then whole workspace is locked out
[video](https://github.com/user-attachments/assets/21041144-087b-48dc-9315-71523038ecb6)

**Expected:** Input shouldn't allow forbidden characters

**Comment by AMoreaux** [comment]
Thanks a lot, @BOHEUS [this PR](https://github.com/twentyhq/twenty/pull/8902) solve the issue.
