### ISSUE TITLE
Weird shadows on sides of workspace creation popup in dark mode

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8877]
**Scenario:**
1. Type any other mail than `tim@apple.dev`, e.g. `test@apple.dev` and create new account
2. Create new workspace

**Actual:** There are weird subtle shadows on sides of workspace creation popup
![Image](https://github.com/user-attachments/assets/94e57cab-f487-4b49-bb9c-0548b41f3e8a)

**Expected:** There mustn't be shadows on sides of workspace creation popup

**Note:** It's on Chromium, not Firefox :P

**Comment by FelixMalfait** [comment]
Thanks @BOHEUS 
cc @Bonapara
