### ISSUE TITLE
Connect with provider button doesn't disappear/appear when this option is disabled/enabled

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8878]
**Scenario 1:**
1. Log in
2. Go to Settings, toggle Advanced, go to Security
3. Hide Google option
4. Go to Settings > Accounts

**Actual:** Connect with Google button is still visible

**Expected:** Connect with Google button must be hidden

**Scenario 2:**
1. Log in
2. Go to Settings, toggle Advanced, go to Security
3. Show Microsoft option
4. Go to Settings > Accounts

**Actual:** Connect with Microsoft button is hidden

**Expected:** Connect with Microsoft button must be shown

**Comment by BOHEUS** [comment]
Related to #8473

**Comment by Bonapara** [comment]
Hi @BOHEUS, this will be another setting we introduce later. The setting you're referring to should only concerns connection methods, not the ability to sync emails with a specific provider.
