### ISSUE TITLE
Login page when changing between workspaces

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8881]
**Scenario:**
1. Create new workspace with any email, e.g. `test@apple.dev`
2. Go to Settings > Members and copy invite link
3. Logout and remove subdomain from URL to go back to main page
4. Paste copied link and log in as `tim@apple.dev`
5. Go to different workspace

**Actual:** When changing workspaces, there's login page (only for first time)
[video](https://github.com/user-attachments/assets/dda34541-2cc4-437b-a9c6-15b019f74e45)

**Comment by FelixMalfait** [comment]
Thanks @BOHEUS for the recent reports!

@AMoreaux will confirm but I think this one is by design for security reasons (because each workspace can now have their own security settings like enforce login through SSO and disable Google login)

**Comment by AMoreaux** [comment]
Yes it's expected since the authentication is now at the workspace level.
