### ISSUE TITLE
Onboarding switches from Dark to Light Mode

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8884]
# Bug description

When my browser is set to dark mode, the initial pages of the sign-up process are displayed in dark mode. However, this suddenly changes during profile creation, where the app switches to light mode - before switching back to dark mode on later steps

https://github.com/user-attachments/assets/ccc77cf7-d1dd-44d5-8a29-9f1e0326aa73

# How to reproduce

Create a new account on demo.twenty.com

**Comment by BOHEUS** [comment]
@Bonapara I reported it earlier in #8110

**Comment by Bonapara** [comment]
Thanks @BOHEUS, will close this one then!
