### ISSUE TITLE
I can hide/show filter bar and add filters directly from filter bar 

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#889]
I should be able to hide/show the filter bar by clicking either on the "Filter" button when there is an active "Filter".

When there is no "Filter" clicking on the filter button should keep the actual behavior: First, the menu opens to set the filter, then the filter bar appears.

If the filter bar is hidden and there is an active sort It should both open the filter bar and a menu next to the sort button to add a secondary sorting.

https://github.com/twentyhq/twenty/assets/19412894/6a194450-b997-4b82-9725-3f7c591b949e

**Comment by FelixMalfait** [comment]
I understand the behavior for filters. But I'm not sure I understand it for sort. As of today we can add multiple sort criterias. How would that work it the sort button now becomes a "hide bar" button once 1 sort has been added?

**Comment by Bonapara** [comment]
Thanks for noticing this behavior, updated the description!
