### ISSUE TITLE
Bug with Phone field input

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#8891]
Bug with Phones input, the input stays open after value has been persisted, it should close, also bugs when editing, deleting, the value is persisted but in the dropdown the value stays the same.

**Comment by harshit078** [comment]
@lucasbordeau If not taken interally, I'll take this up !

**Comment by lucasbordeau** [comment]
@harshit078 Thank you for proposing, we'll keep this in the core team.

**Comment by ijreilly** [comment]
check with @guillim if that has not already been done !

**Comment by guillim** [comment]
looks like it was fixed here no ? https://github.com/twentyhq/twenty/pull/8918

**Comment by lucasbordeau** [comment]
Indeed tested on main everything is fixed, thanks !
