### ISSUE TITLE
Consider adding repo-review badge to README

### ISSUE THREAD

**Issue by richardanderson001** [twentyhq/twenty#890]
Thanks for creating this repo!

Successful repos have added a **review** badge to their repo's README:

<a href='https://github.com/repo-reviews/repo-reviews.github.io/blob/main/create.md' target="_blank"><img alt='Github' src='https://img.shields.io/badge/review_me-100000?style=flat&logo=Github&logoColor=white&labelColor=888888&color=555555'/></a>

These help the open-source community collect and share UX stories via repo-reviews.github.io and thereby increase productivity, sponsorship, and cross-pollination on a global scale.

Please consider adding a review badge- happy to provide one in a PR!

**Comment by FelixMalfait** [comment]
Thanks for the suggestion, cool project!
We don't have any badge now and are trying to keep the number of links to the minimum, so we would not implement this

**Comment by richardanderson001** [comment]
thanks @FelixMalfait appreciate your feedback and consideration!

**Comment by richardanderson001** [comment]
btw, nice Richard Feynman photo! 👍
