### ISSUE TITLE
Opportunities - Amount in each stage

### ISSUE THREAD

**Issue by ajolo2ky** [twentyhq/twenty#8913]
Hi team,

Would it be possible to calculate the amount of money sitting on each stage of the Opportunities Kanban? I currently have this on Pipedrive and it's very useful:

![Image](https://github.com/user-attachments/assets/0803b49d-3bbb-4398-82cd-7f95363632a0)

**Comment by Bonapara** [comment]
Yes it will be possible really soon! https://github.com/twentyhq/twenty/issues/8754

**Comment by Bonapara** [comment]
(It's currently being developed)
