### ISSUE TITLE
Cannot navigate to next record after uploading an image identifier

### ISSUE THREAD

**Issue by phjackl3** [twentyhq/twenty#8949]
## Bug Description

After uploading an image identifier, the next button on a People record page does not navigate to the next record

**Example:** 

Go to _All People_

Click on a person to view their detail page.
![Image](https://github.com/user-attachments/assets/7bee9804-3e44-4107-b2c7-d105ff03aeb9)

Click their profile image, in this case the circle with 'T' in it.
Upload a new image to their profile
![Image](https://github.com/user-attachments/assets/f32a1bcc-998c-4dd8-8b84-b38055257740)

Click on the up `↑` or down `↓`  icon to navigate to the next record

Nothing happens.

https://github.com/user-attachments/assets/61ae4df9-d714-4dab-ba36-abb153b77fc8

If I go back to the previous record, I can then navigate again to the next records

## Expected behavior

The person being displayed is changed

**Comment by Ameerjafar** [comment]
@Bonapara can you assign me this issue sir.

**Comment by Bonapara** [comment]
Please have a look but I think this issue is not that easy to tackle.

**Comment by Ameerjafar** [comment]
@Bonapara i have read the problem I think i can able to solve the bug.

**Comment by Bonapara** [comment]
Please have a try then!
