### ISSUE TITLE
Favorite menu issues

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8972]
- Gap is too large (12px instead of 8px)
- Background isn't blur
- Border radius issue on the Search input

![Image](https://github.com/user-attachments/assets/64e20ca5-784c-4894-980f-3871869b2317)

**Comment by ehconitin** [comment]
@Bonapara, oh! I just saw the master issue. Is Lucas working on this? I assigned myself, but please reassign if so! Thanks!

**Comment by Bonapara** [comment]
Thanks @ehconitin! @lucasbordeau what do you think?

**Comment by Bonapara** [comment]
Let's deprecate this one in regard on the future ⌘K strategy
