### ISSUE TITLE
Add navigation inside the command menu for showpage

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#8978]
## Scope & Context

We want to be able to navigate between the records using the command menu.

## Technical inputs

Create `useNavigateToNextRecordSingleRecordAction` and `useNavigateToPreviousRecordSingleRecordAction`.
These actions are the first one that we implement that should be visible only on the record show page and not on the index page. We should use the `contextStoreCurrentViewIdComponentState` to know if we are on a show page or an index page.

**Comment by Paarth-Kashyap** [comment]
I would like to try this
