### ISSUE TITLE
Error while creating new workspace

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8984]
**Scenario:**
1. Open Twenty
2. Change email (e.g. test@apple.dev) to create new workspace and provide password
3. Click "Sign up" button

**Actual:** Error appears in UI
![Image](https://github.com/user-attachments/assets/84533dbc-d4db-4b5a-a155-ebdf00953f73)

**Expected:** No error should appear

**Comment by MrSuddenJoy** [comment]
@BOHEUS The error message explicitly states whats wrong: `Cannot query.....`. Means that either:
* there is no DB with given table/field,
* said DB is unreachable. Firewall maybe?

**Comment by BOHEUS** [comment]
Probably DB doesn't have these columns or tables as firewall doesn't block DB hosted in Docker

@charlesBochet FYI I can reproduce it on demo

**Comment by charlesBochet** [comment]
This is a HIGH bug, taking it in the sprint

**Comment by BOHEUS** [comment]
@charlesBochet could someone else try to reproduce it? After pulling newest changes, I do not reproduce it, on demo I get message that creating new workspaces is disabled

**Comment by charlesBochet** [comment]
I think it's when you create a workspace for the first time in IS_MULTI_WORKSPACE_ENABLED=false case (which is the case for the self hosting)

**Comment by charlesBochet** [comment]
So maybe create a fresh setup with bash <(curl -sL https://git.new/20) ?

**Comment by BOHEUS** [comment]
Still no luck, also, on screenshot there's different URL `bold_wolf.localhost:3001` so IS_MULTIWORKSPACE_ENABLED was set to true, otherwise it wouldn't be possible to set it up this way

**Comment by charlesBochet** [comment]
Good point! I'm almost sure it's resolved in IS_MULTIWORKSPACE_ENABLED=true case

**Comment by charlesBochet** [comment]
Thanks @BOHEUS
