### ISSUE TITLE
Broken UI when coming back to main page

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8986]
**Scenario:**
1. Log in to workspace
2. Go to Settings and logout
3. Go back to `app.localhost:3001/welcome`

**Actual:** UI is broken
![Image](https://github.com/user-attachments/assets/1b993ca7-16ff-4a0b-8470-0cc650a306a7)

**Expected:** UI should look the same like earlier

**Note:** Also, error in logs appears that user doesn't have access to workspace but no user is logged in

**Comment by MrSuddenJoy** [comment]
@BOHEUS Im confused. You expect non-logged-in user (guest) to be able to see page thats reserved to logged-in user? If so, than this is not a bug but desired behaviour.

**Comment by MrSuddenJoy** [comment]
@BOHEUS isn't it what's presented on screenshot you've posted?

**Comment by BOHEUS** [comment]
@Bonapara I tried to reproduce it like earlier but no luck this time, I'm closing this issue
