### ISSUE TITLE
Non-primary email addresses are not associating emails with a person

### ISSUE THREAD

**Issue by rob-luke** [twentyhq/twenty#8991]
## Scope & Context

Non-primary email addresses are not associating emails with a person.

## Current behavior

If I have multiple email addresses associated with a person:
- only the emails of the primary email address are shown in the email tab
- if I receive an email from a non-primary email, a new user is created 

## Expected behavior

- The email tab shows emails associated with any of the emails of the person
- New users are not automatically created when I get an email that is associated with a persons non-primary email

## Technical inputs

None

**Comment by FelixMalfait** [comment]
Good feedback / definitely something we need to do! but I'll close because it's a duplicate of https://github.com/twentyhq/twenty/issues/7205

**Comment by rob-luke** [comment]
Hi @FelixMalfait, I just circled back on this and noticed that the issue https://github.com/twentyhq/core-team-issues/issues/108 is marked as completed and was moved to done. However, when I tested this on v0.52.8, I still have the issue that _only the emails of the primary email address are shown in the email tab for a person_, not all emails from all primary and secondary email addresses—which is what I would expect if multiple emails are associated with a single person. 

It may be that my expectations are wrong, and in that case I can continue to create multiple people with the same names and one email per person. No worries if so, then I can just update my data (and mental) models accordingly.

**Comment by rob-luke** [comment]
Hi @FelixMalfait, just wanted to close the loop here and determine if I should have one person per email address (so multiple people in the CRM representing the same real life person) or associate multiple emails with one person (assuming that future releases will then associate emails from multiple addresses with the single entity). Either way works for me, I appreciate any guidance so I can align my setup with the future plans for Twenty. Thanks!

**Comment by FelixMalfait** [comment]
Should be in the next release! Thanks @bosiraphael and @rob-luke for the feedback

**Comment by rob-luke** [comment]
Amazing. Thanks so much
