### ISSUE TITLE
Twenty Requires Re-login After Browser Restart

### ISSUE THREAD

**Issue by dascwf** [twentyhq/twenty#8992]
Hi Twenty team and anybody ,

I'm experiencing an issue where I have to re-login to Twenty every time I restart my browser. I'd really appreciate it if Twenty could remember my login state so I don't have to log in repeatedly. It would significantly improve my workflow.

**Environment:**
Twenty Version: v0.33.7 (specified via TAG=v0.33.7)
Operating System: Ubuntu Server 24.10
Deployment: Docker Compose

Here's the relevant portion of my .env file:
```
TAG=v0.33.7
LOGIN_TOKEN_EXPIRES_IN=90d
REFRESH_TOKEN_EXPIRES_IN=90d
ACCESS_TOKEN_EXPIRES_IN=2h
``` 

I have set LOGIN_TOKEN_EXPIRES_IN and REFRESH_TOKEN_EXPIRES_IN to 90d, expecting the login token and refresh token to be valid for 90 days. However, these settings don't seem to be working, and I still need to re-login after a browser restart.

**Comment by FelixMalfait** [comment]
Hey @dascwf,
Login Token is just something temporary. What matters is usually the refresh token time ('remember me for X'). And if the refresh mechanism didn't work then you could cheat and set a long access token (token doesn't need to be renewed).
I'm not sure why it doesn't work for you. Did you restart the server after changing the environment variable values?

**Comment by shairozan** [comment]
What browser is it? Each browser takes a rather opinionated approach to cookie data and it may _actually_ be enforced by upstream things like Active Directory controllers via policy? I do see an Expiration value on the cookies, which is normally what triggers anomalous behavior from browser to browser.

**Comment by dascwf** [comment]
@shairozan  @FelixMalfait 

Thank you for your reply.
**Now, I still can't remember to log in.**


**.env**
```
TAG=v0.33.7
#LOGIN_TOKEN_EXPIRES_IN=90d
#ACCESS_TOKEN_EXPIRES_IN=90d
REFRESH_TOKEN_EXPIRES_IN=90d
``` 

**restart**
```
docker compose -f /home/git/app/crm/twenty/docker-compose.yml down;
sleep 3;
docker compose -f /home/git/app/crm/twenty/docker-compose.yml up -d
```

**system**
```
PHP Version 8.4.1
Web Server Caddy/v2.8.4
Ubuntu Server 24.10
Chrome 131.0.6778.109
```

**logined cookie**
```
analyticsCookie | eebc4a16-1f76-4b90-b1d0-c2fa7e41064d | *** | / | 2024-12-11T16:37:09.708Z | 51 |   | ✓ |   |   |   | Medium
tokenPair	{%22__typename%22:%22AuthTokenPair%22%2C%22accessToken%22:{%22__typename%22:%22AuthToken%22%2C%22token%22:%22eyJhbG.........3XQ0ew%22%2C%22expiresAt%22:%222024-12-11T16:37:07.518Z%22}%2C%22refreshToken%22:{%22__typename%22:%22AuthToken%22%2C%22token%22:%22eyJ........aF4%22%2C%22expiresAt%22:%222025-02-09T16:07:07.534Z%22}}	***	/ 2024-12-18T16:07:08.000Z 883 Medium
```
