### ISSUE TITLE
FolderPicker doesn't open when isPageHeaderV2Enabled={true}

### ISSUE THREAD

**Issue by ehconitin** [twentyhq/twenty#9030]
## Bug Description
FolderPicker doesn't open on clicking 'Add to Favorite' in RecordShowActionMenuButtons

## Expected behavior
Clicking 'Add to favorite' should add the record as a favorite. It shouldn't open the favorite folder on the first click; it should only open it on the second click when the record is already a favorite.

**Comment by bosiraphael** [comment]
Actually it's not a bug, it's just that we want the actions in the header and the command menu to have a consistent behavior and we don't want them to be able to open a dropdown. We're not sure yet of the final behavior, but for the favorite folders, people will be able to add the items to the folders by dragging and dropping them inside the navbar.
