### ISSUE TITLE
Remove useEffect from OverflowingTextWithTooltip display mode.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#904]

**Comment by FelixMalfait** [comment]
(Assigning it to you directly since I feel it doesn't have enough context to be taken by someone else)

**Comment by charlesBochet** [comment]
I think Lucas wants to extract this to a void compoment next to the OverflowingTextWithTooltip. Leaving it here for now

**Comment by lucasbordeau** [comment]
Looks ok for me as it is, I close this ticket.
