### ISSUE TITLE
RecordIndexContext error in data model settings

### ISSUE THREAD

**Issue by shivampandya24** [twentyhq/twenty#9052]
## Bug Description

Facing RecordIndexContext error while trying to access "settings" option under data model.

I am facing this issue under paid plan.

<img width="758" alt="Image" src="https://github.com/user-attachments/assets/75392296-f4a8-4784-9f2c-2b2fe5407584" />

**Comment by charlesBochet** [comment]
Hi @shivampandya24, we have just issue a patch under v0.34.1 that should fix the issue. Do you still face it?
If yes could you dm me on Discord to give me your email address so I can check your workspace.

You can also use the Support button in the bottom left corner

**Comment by Bonapara** [comment]
@shivampandya24 I will close the issue. Please comment if you still experience the problem!
