### ISSUE TITLE
Fix Datepicker overlay

### ISSUE THREAD

**Issue by brendanlaschke** [twentyhq/twenty#907]
<img width="208" alt="Bildschirmfoto 2023-07-24 um 23 36 36" src="https://github.com/twentyhq/twenty/assets/48770548/ba8484a2-6853-4835-b472-4e16a7f28b89">

Found while implementing #814.

The Datepicker overflows the viewport, when no place is left to the right. This is also problematic when implementing scroll on the columns as the scroll container would cut off the popover. This could be solved by placing the date picker popover in the body instead of the column.

**Comment by FelixMalfait** [comment]
Thanks for the report! I think this has been fixed with the current implementation. Feel free to let me know and I'll reopen if not
