### ISSUE TITLE
In right drawer, when soft deleted a task/note, all the tabs shows timeline

### ISSUE THREAD

**Issue by ehconitin** [twentyhq/twenty#9073]
## Bug Description
as per title, found on demo, i.e., v0.34.2

https://github.com/user-attachments/assets/d798c56f-24fe-4013-aa87-daf2dc22e8d5

**Comment by Lucifer4255** [comment]
can i work on this issue?

**Comment by ehconitin** [comment]
Sure, go ahead and raise the PR if you find the fix!

**Comment by Lucifer4255** [comment]
Do we need to show delete instead of updated a task in timeline?? @ehconitin

**Comment by ehconitin** [comment]
I am pretty sure it does show 'delete' on the timeline if it's deleted!
Although the recording suggests different, could you verify?

**Comment by ehconitin** [comment]
I just checked -- it does show 'deleted'

**Comment by Lucifer4255** [comment]
well then other than that can you clarify what we need to edit

**Comment by ehconitin** [comment]
The issue is regarding all the tabs being timeline in the right drawer after deleting a task/note :)

**Comment by ehconitin** [comment]
closed in #9176
