### ISSUE TITLE
No scroll shown when scrolling through kanban board

### ISSUE THREAD

**Issue by ehconitin** [twentyhq/twenty#9083]
## Bug Description
No scroll is shown when scrolling through the Kanban board.

https://github.com/user-attachments/assets/20863068-ca66-469e-a1cb-5bf2b2ef8981

## Expected behavior
Scroll should be visible while scrolling

**Comment by harshrajeevsingh** [comment]
@ehconitin Duplicate of : #8944

**Comment by ehconitin** [comment]
Oh, thanks! Closing this in favor of #8944
