### ISSUE TITLE
Update company picker to navigate with arrow keys and add a border

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#909]
We miss two things:
- I can use keyboard to switch from list items to create button with down/up arrow
- a light border above the create button

Desired:
<img src="https://github.com/twentyhq/twenty/assets/19412894/a49242b9-ae1a-455a-b56a-0c872bef9b9b">

Current:
<img width="233" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/d41cbb08-5167-4666-9d8f-a53517e2c54b">

**Comment by Ashutosh-Bhadauriya** [comment]
@FelixMalfait I can take this

**Comment by FelixMalfait** [comment]
Hey @Ashutosh-Bhadauriya thanks a lot!

**Comment by dhruvkaravadiya** [comment]
@FelixMalfait sir, i would like to work on this issue if its still open and is in backlog

**Comment by Bonapara** [comment]
This issue has been almost fixed. It missed 2 behaviors:
- keyboard, switch from content to create button with down arrow
- a border top on the create button

@charlesBochet pour info

<img width="233" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/d41cbb08-5167-4666-9d8f-a53517e2c54b">

**Comment by charlesBochet** [comment]
Ok! @dhruvkaravadiya Feel free to work on it!

**Comment by dhruvkaravadiya** [comment]
Sure thing

**Comment by FelixMalfait** [comment]
Hey @dhruvkaravadiya should we unassign you from this? Thanks!

**Comment by dhruvkaravadiya** [comment]
@FelixMalfait Yes, please do unassign me. I reached almost half way there, but my college exams are taking too much time. And might not be able to complete this issue. It was great exploring your extremely maintained code base.

**Comment by FelixMalfait** [comment]
@dhruvkaravadiya good luck for your college exams!!! Thanks for letting us know
