### ISSUE TITLE
Horizontal line on login page when no SSO providers are selected

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#9094]
**Scenario:**
1. Open login page

**Actual:** There's horizontal line despite no SSO providers
![Image](https://github.com/user-attachments/assets/e1cd12af-221a-47cb-9438-8f9b708b4917)

**Expected:** Horizontal line must be visible only if at least 1 SSO provider is selected

**Comment by muraliSingh7** [comment]
@BOHEUS 
The issue appears to be in the `SignInUpWorkspaceScopeForm.tsx` file.
The logic which needs to be removed is :
```
{(authProviders.google ||
          authProviders.microsoft ||
          authProviders.sso.length > 0) &&
        authProviders.password ? (
          <HorizontalSeparator visible />
        ) : null}
```

As each authentication provider has its own `HorizontalSeparator`, and the password provider is displayed last, it should not have a separator following it.

**Comment by FurquanAnwer** [comment]
Can I work on this issue ?

**Comment by imjaglan** [comment]
hey @muraliSingh7  i believe it's the `SignInUpWorkspaceScopeForm.tsx`. component not the `SignInUpWorkspaceScopeForm.tsx`. that HorizontalSeparator is coming from that component

**Comment by muraliSingh7** [comment]
> hey @muraliSingh7  i believe it's the `SignInUpWorkspaceScopeForm.tsx`. component not the `SignInUpWorkspaceScopeForm.tsx`. that HorizontalSeparator is coming from that component 

I am also saying about same component.
