### ISSUE TITLE
Update show title edition style

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#910]
# Actual behavior

https://github.com/twentyhq/twenty/assets/19412894/aad96d43-2a57-4aba-af49-de08e044bddc

# Desired behavior

Keep the edition in place (Don't add an input above when clicking to edit). Add a Transparent light background behind the editable fields. Resize automatically (hug content) and maintain centered the two fields in the medium of the column (even while editing)

Using tab should switch from First name to last name. 

https://github.com/twentyhq/twenty/assets/19412894/c53a309a-8279-4704-9208-53bb224510e3

**Comment by nikman21** [comment]
Hello, I would like to work on this.

**Comment by Bonapara** [comment]
@nikman21 are you still interested? Sorry for the delay, and thanks for offering your contribution!

**Comment by nikman21** [comment]
Yes, i am still interested!

**Comment by Bonapara** [comment]
@nikman21 assigned you

**Comment by charlesBochet** [comment]
@nikman21 Are you working on this one? If not, it's better to unassign it so other can work on it :)

**Comment by thaisguigon** [comment]
As discussed: the input sizes on edition seem to have been fixed already.
We still want to improve on the following behaviors:
- style on hover (grey background, see video above)
- when the input is empty, show "Empty" in a grey font color (similar to empty editable fields)
