### ISSUE TITLE
unable to login fresh install selfhosted

### ISSUE THREAD

**Issue by jilusm** [twentyhq/twenty#9109]
follow the documentation @ https://twenty.com/developers/section/self-hosting/docker-compose

successfull installed the app without facing any major issue 

here are the logs

twenty worker log

[32m[Nest] 34  - [39m12/17/2024, 5:02:20 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mUserModule dependencies initialized[39m
[32m[Nest] 34  - [39m12/17/2024, 5:02:20 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mAuthModule dependencies initialized[39m

twenty server log

[39m[32mMapped {/metadata, POST} route[39m
[32m[Nest] 1  - [39m12/17/2024, 5:02:06 PM [32m    LOG[39m [38;5;3m[GraphQLModule] [39m[32mMapped {/graphql, POST} route[39m
[32m[Nest] 1  - [39m12/17/2024, 5:02:06 PM [32m    LOG[39m [38;5;3m[NestApplication] [39m[32mNest application successfully started[39m

twenty db log

[38;5;6mpostgresql [38;5;5m17:01:41.08 [0m[38;5;2mINFO [0m ==> ** Starting PostgreSQL **
2024-12-17 17:01:41.148 GMT [1] LOG:  pgaudit extension initialized
2024-12-17 17:01:41.166 GMT [1] LOG:  starting PostgreSQL 15.5 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2024-12-17 17:01:41.167 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-12-17 17:01:41.167 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2024-12-17 17:01:41.174 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-12-17 17:01:41.182 GMT [84] LOG:  database system was shut down at 2024-12-14 10:50:56 GMT
2024-12-17 17:01:41.210 GMT [1] LOG:  database system is ready to accept connections

redis log

1:M 17 Dec 2024 17:01:40.747 * monotonic clock: POSIX clock_gettime
1:M 17 Dec 2024 17:01:40.749 * Running mode=standalone, port=6379.
1:M 17 Dec 2024 17:01:40.749 * Server initialized
1:M 17 Dec 2024 17:01:40.750 * Ready to accept connections tcp

login screen appeared 

tried to login with google sso got error

[32m[Nest] 1  - [39m12/17/2024, 5:02:06 PM [32m    LOG[39m [38;5;3m[NestApplication] [39m[32mNest application successfully started[39m
Exception Captured
  {
    operation: { name: 'GetCurrentUser', type: 'query' },
    document: 'query GetCurrentUser {\n' +
      '  currentUser {\n' +
      '    ...UserQueryFragment\n' +
      '    __typename\n' +
      '  }\n' +
      '}\n' +
      '\n' +
      'fragment UserQueryFragment on User {\n' +
      '  id\n' +
      '  firstName\n' +
      '  lastName\n' +
      '  email\n' +
      '  canImpersonate\n' +
      '  supportUserHash\n' +
      '  analyticsTinybirdJwts {\n' +
      '    getWebhookAnalytics\n' +
      '    getPageviewsAnalytics\n' +
      '    getUsersAnalytics\n' +
      '    getServerlessFunctionDuration\n' +
      '    getServerlessFunctionSuccessRate\n' +
      '    getServerlessFunctionErrorCount\n' +
      '    __typename\n' +
      '  }\n' +
      '  onboardingStatus\n' +
      '  workspaceMember {\n' +
      '    ...WorkspaceMemberQueryFragment\n' +
      '    __typename\n' +
      '  }\n' +
      '  workspaceMembers {\n' +
      '    ...WorkspaceMemberQueryFragment\n' +
      '    __typename\n' +
      '  }\n' +
      '  defaultWorkspace {\n' +
      '    id\n' +
      '    displayName\n' +
      '    logo\n' +
      '    domainName\n' +
      '    inviteHash\n' +
      '    allowImpersonation\n' +
      '    activationStatus\n' +
      '    isPublicInviteLinkEnabled\n' +
      '    isGoogleAuthEnabled\n' +
      '    isMicrosoftAuthEnabled\n' +
      '    isPasswordAuthEnabled\n' +
      '    subdomain\n' +
      '    hasValidEntrepriseKey\n' +
      '    featureFlags {\n' +
      '      id\n' +
      '      key\n' +
      '      value\n' +
      '      workspaceId\n' +
      '      __typename\n' +
      '    }\n' +
      '    metadataVersion\n' +
      '    currentBillingSubscription {\n' +
      '      id\n' +
      '      status\n' +
      '      interval\n' +
      '      __typename\n' +
      '    }\n' +
      '    workspaceMembersCount\n' +
      '    __typename\n' +
  [
    ForbiddenException: Forbidden resource
        at canActivateFn (/app/node_modules/@nestjs/core/helpers/external-context-creator.js:157:23)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async target (/app/node_modules/@nestjs/core/helpers/external-context-creator.js:73:31)
        at async Object.currentUser (/app/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
        at async field.resolve (/app/node_modules/@envelop/on-resolve/cjs/index.js:36:42)
        at async /app/node_modules/@graphql-tools/executor/cjs/execution/promiseForObject.js:18:35
        at async Promise.all (index 0) {
      path: undefined,
      locations: undefined,
      extensions: { code: 'INTERNAL_SERVER_ERROR', response: 'Forbidden resource' }
    }
  ]
      '  }\n' +
      '  workspaces {\n' +
      '    workspace {\n' +
      '      id\n' +
      '      logo\n' +
      '      displayName\n' +
      '      domainName\n' +
      '      subdomain\n' +
      '      __typename\n' +
      '    }\n' +
      '    __typename\n' +
      '  }\n' +
      '  userVars\n' +
      '  __typename\n' +
      '}\n' +
      '\n' +
      'fragment WorkspaceMemberQueryFragment on WorkspaceMember {\n' +
      '  id\n' +
      '  name {\n' +
      '    firstName\n' +
      '    lastName\n' +
      '    __typename\n' +
      '  }\n' +
      '  colorScheme\n' +
      '  avatarUrl\n' +
      '  locale\n' +
      '  timeZone\n' +
      '  dateFormat\n' +
      '  timeFormat\n' +
      '  __typename\n' +
      '}',
    user: undefined,
    workspace: {
      id: undefined,
      displayName: undefined,
      createdAt: undefined,
      activationStatus: undefined
    }
  }
[33m[Nest] 1  - [39m12/17/2024, 5:08:02 PM [33m   WARN[39m [33mIn single-workspace mode, there should be only one workspace. Today there are 2 workspaces[39m
[33m[Nest] 1  - [39m12/17/2024, 5:08:02 PM [33m   WARN[39m [33mundefined[39m
[33m[Nest] 1  - [39m12/17/2024, 5:08:16 PM [33m   WARN[39m [33mIn single-workspace mode, there should be only one workspace. Today there are 2 workspaces[39m
[33m[Nest] 1  - [39m12/17/2024, 5:08:16 PM [33m   WARN[39m [33mundefined[39m
Exception Captured
  {
    operation: { name: 'GetCurrentUser', type: 'query' },
    document: 'query GetCurrentUser {\n' +
      '  currentUser {\n' +
      '    ...UserQueryFragment\n' +
      '    __typename\n' +
      '  }\n' +
      '}\n' +
      '\n' +
      'fragment UserQueryFragment on User {\n' +
      '  id\n' +
      '  firstName\n' +
      '  lastName\n' +
      '  email\n' +
      '  canImpersonate\n' +
      '  supportUserHash\n' +
      '  analyticsTinybirdJwts {\n' +
      '    getWebhookAnalytics\n' +
      '    getPageviewsAnalytics\n' +
      '    getUsersAnalytics\n' +
      '    getServerlessFunctionDuration\n' +
      '    getServerlessFunctionSuccessRate\n' +
      '    getServerlessFunctionErrorCount\n' +
      '    __typename\n' +
      '  }\n' +
      '  onboardingStatus\n' +
      '  workspaceMember {\n' +
      '    ...WorkspaceMemberQueryFragment\n' +
      '    __typename\n' +
      '  }\n' +
      '  workspaceMembers {\n' +
      '    ...WorkspaceMemberQueryFragment\n' +
      '    __typename\n' +
      '  }\n' +
      '  defaultWorkspace {\n' +
      '    id\n' +
      '    displayName\n' +
      '    logo\n' +
      '    domainName\n' +
      '    inviteHash\n' +
      '    allowImpersonation\n' +
      '    activationStatus\n' +
      '    isPublicInviteLinkEnabled\n' +
      '    isGoogleAuthEnabled\n' +
      '    isMicrosoftAuthEnabled\n' +
      '    isPasswordAuthEnabled\n' +
      '    subdomain\n' +
      '    hasValidEntrepriseKey\n' +
      '    featureFlags {\n' +
      '      id\n' +
      '      key\n' +
      '      value\n' +
      '      workspaceId\n' +
      '      __typename\n' +
      '    }\n' +
      '    metadataVersion\n' +
      '    currentBillingSubscription {\n' +
      '      id\n' +
      '      status\n' +
      '      interval\n' +
      '      __typename\n' +
      '    }\n' +
      '    workspaceMembersCount\n' +
      '    __typename\n' +
      '  }\n' +
      '  workspaces {\n' +
      '    workspace {\n' +
      '      id\n' +
      '      logo\n' +
      '      displayName\n' +
      '      domainName\n' +
      '      subdomain\n' +
      '      __typename\n' +
      '    }\n' +
      '    __typename\n' +
      '  }\n' +
      '  userVars\n' +
      '  __typename\n' +
      '}\n' +
      '\n' +
      'fragment WorkspaceMemberQueryFragment on WorkspaceMember {\n' +
      '  id\n' +
      '  name {\n' +
      '    firstName\n' +
      '    lastName\n' +
      '    __typename\n' +
      '  }\n' +
      '  colorScheme\n' +
      '  avatarUrl\n' +
      '  locale\n' +
      '  timeZone\n' +
      '  dateFormat\n' +
      '  timeFormat\n' +
      '  __typename\n' +
      '}',
    user: undefined,
    workspace: {
      id: undefined,
      displayName: undefined,
      createdAt: undefined,
      activationStatus: undefined
    }
  }
  [
    ForbiddenException: Forbidden resource
        at canActivateFn (/app/node_modules/@nestjs/core/helpers/external-context-creator.js:157:23)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async target (/app/node_modules/@nestjs/core/helpers/external-context-creator.js:73:31)
        at async Object.currentUser (/app/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
        at async field.resolve (/app/node_modules/@envelop/on-resolve/cjs/index.js:36:42)
        at async /app/node_modules/@graphql-tools/executor/cjs/execution/promiseForObject.js:18:35
        at async Promise.all (index 0) {
      path: undefined,
      locations: undefined,
      extensions: { code: 'INTERNAL_SERVER_ERROR', response: 'Forbidden resource' }
    }
  ]
[33m[Nest] 1  - [39m12/17/2024, 5:08:18 PM [33m   WARN[39m [33mIn single-workspace mode, there should be only one workspace. Today there are 2 workspaces[39m
[33m[Nest] 1  - [39m12/17/2024, 5:08:18 PM [33m   WARN[39m [33mundefined[39m

my env looks like

TAG=latest

POSTGRES_ADMIN_PASSWORD=19Vishxxxxxxxx

PG_DATABASE_HOST=db:5432
REDIS_URL=redis://redis:6379

SERVER_URL=https://app.xxxxxxx.com

# Use openssl rand -base64 32 for each secret
APP_SECRET=YG62bJQLaT35ajivCJX6Twvxxxxxxxxxxxxxxx

SIGN_IN_PREFILLED=false

STORAGE_TYPE=local

**Comment by FelixMalfait** [comment]
Hey, those logs look pretty healthy (you can ignore the Forbidden resource error: #8632). The only things is that it seems your database was seeded with 2 test workspaces which maybe you didn't want? (it happens if you run `database:reset`)

**Comment by jilusm** [comment]
Hi @FelixMalfait  thanks for the reply After the fresh setup of twenty i faced the issue so I tried https://twenty.com/developers/section/self-hosting/troubleshooting

docker exec -it twenty-server-1 yarn docker exec -it twenty-server-1 npx nx database:reset

Now I am messed up with my database as you replied with multiple workspace.

So guide me how i solve this issue

**Comment by FelixMalfait** [comment]
You can login with tim@apple.dev / Applecar2025 and remove the 2 test workspaces you just created

**Comment by jilusm** [comment]
![IMG_20241218_154538.jpg](https://github.com/user-attachments/assets/03bee4a9-a741-4d58-a626-6ccbfc8c905c)

**Comment by jilusm** [comment]
The filter option is not working for me in kanban view. I created a custom data model with select data type.  Expected behaviour > in the picture above you can see I selected only "Success"  but it shows all the options even the filter option is selected. And when I use the status field with the conjunction of other fields then it is working

**Comment by jilusm** [comment]
![IMG_20241218_160220.jpg](https://github.com/user-attachments/assets/2cffb6af-b927-4762-9575-3f389fe8881b)

**Comment by FelixMalfait** [comment]
@jilusm OK we'll have a look. But I recommend hiding the column instead of doing a filter on the kanban column values

<img width="244" alt="Image" src="https://github.com/user-attachments/assets/b9db5130-fdc4-4452-bbde-cd99480cf320" />
