### ISSUE TITLE
Update skeleton loading menu picker

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#912]
# Actual behavior

We don't see enough of the skeleton loading:

https://github.com/twentyhq/twenty/assets/19412894/a8341c15-6005-4c36-bf46-4703416e545b

# Desired behavior

https://github.com/twentyhq/twenty/assets/19412894/2f03e2a4-fef9-41f7-b624-62379abfc803

### Update the colors:
--base-color: #EBEBEB

### Update the linear gradient

linear-gradient(
    90deg,
    var(--base-color),
    var(--highlight-color),
90%,
    var(--base-color)
  )
  
  
  Related: https://github.com/twentyhq/twenty/issues/902
```[tasklist]
### Tasks
- [x] Update DropdownMenuSkeletonItem.tsx to pass style to       <SkeletonTheme         baseColor={theme.background.quaternary}         highlightColor={theme.background.secondary}       >
```

**Comment by jaykesarkar** [comment]
I would like to work on this issue. Please guide me.

**Comment by nsv23** [comment]
Hi, can I work on this one?

**Comment by Bonapara** [comment]
@nsv23 are you still willing to work on this one since you've got the other issue? Let me know!

**Comment by nsv23** [comment]
@Bonapara I will finish the other one first. In the meantime if someone else wants this, no problem

**Comment by jaykesarkar** [comment]
I would like to work on this issue. Please guide me.

**Comment by charlesBochet** [comment]
@jaykesarkar I'm adding some guidance in the task list in the description

**Comment by dhruvkaravadiya** [comment]
@charlesBochet i would like to contribute on this issue sir

**Comment by charlesBochet** [comment]
@dhruvkaravadiya This one has actually already been fixed, closing it.
You can work on the other issue: https://github.com/twentyhq/twenty/issues/909, thanks a lot for the help!
