### ISSUE TITLE
I can re-order columns using the Option Button

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#914]
Related to https://github.com/twentyhq/twenty/issues/813

**Comment by FelixMalfait** [comment]
Maybe not something worth the cost/value since we can do it through Options menu. Closing it for now
cc @Bonapara I think you won't mind since you didn't do it in the prototype / created this issue, but feel free to reopen if you do

**Comment by AdityaPimpalkar** [comment]
@FelixMalfait I want to give this a try, can I take this up? Thanks!

**Comment by FelixMalfait** [comment]
@AdityaPimpalkar Haha you like to take on big tasks! Of course you are most welcome to take it.

There is a similar issue on pipelines stages order. An index column has already been introduced. But I don't think re-ordering is possible yet in the UI. In the future we'll want to be able to drag-n-drop to re-order both from the options menu and directly dragging the whole column, like in Notion (but we don't have to do it all at once!)

Doing this well is a bit trickier that it seems.
(1) Either you have to re-update every index because there can be conflicting values
(2) Either you can decide that index is a float and compute the new position as the mean between the 2 columns you're inserting it in
(3) Or you could use a sequential referencing mechanism where each column points to the next one

(2) is my favorite option but I'm not sure @charlesBochet would agree? And we would have to update the column type on the pipeline_stage because it was defined as an int

**Comment by AdityaPimpalkar** [comment]
I dug around the code to find how I can implement this in options menu-

1) To re-order the columns list (Menu item) we need to wrap each element with a `Draggable`, example of this implementation I found was in `EntityBoard` component
2) The list is being rendered by calling the api referring to `viewFields` schema. As of now, If I want to change the ordering I have to update every index individually by providing its respective `key` and `viewId`

Am I missing anything else? 
I also noticed that backend call to update column visibility is missing on the front end

**Comment by charlesBochet** [comment]
@Bonapara could you take a look at this one?

**Comment by FelixMalfait** [comment]
@charlesBochet not sure if you read my comment? There's a question on backend architecture (can we use float for position index?)

As for design,  @Bonapara already provided a design that has ": :" draggable icons on the option menu in the issue linked above: https://github.com/twentyhq/twenty/issues/813 
He also provided another design for the other way of re-ordering: https://github.com/twentyhq/twenty/issues/1524

I think it's an eng issue now more than a design issue

**Comment by charlesBochet** [comment]
I think we should use the float alternative. 
@AdityaPimpalkar 
- could you change ViewField and PipelineStage index types to float?
- implement https://github.com/twentyhq/twenty/issues/1524 ?

Let me know if you need more information!
