### ISSUE TITLE
Load logo automatically during workspace

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#9151]
When someone signs up with a work email and creates a new workspace, we want to load the logo that corresponds to their domain from twenty-icons.com (ex: twenty-icons.com/airbnb.com) and set it as the default logo.

The user can still replace it by a desktop image if he wants to.

Useful: https://github.com/twentyhq/twenty/blob/main/packages/twenty-server/src/utils/is-work-email.ts

Note: in the future we might want to return additional enrichment infos from the backend (e.g. we could pull company Name from twenty-companies.com etc), so the architecture should take that into account

**Comment by samyakpiya** [comment]
Hi @FelixMalfait! I'd like to work on this issue. Could you please assign it to me? Thanks!

**Comment by FelixMalfait** [comment]
Thanks @samyakpiya!

**Comment by samyakpiya** [comment]
@FelixMalfait I've implemented this feature in PR #9158. Please review when you have a chance! 🙏
