### ISSUE TITLE
Wrong Total Persons count in Person View

### ISSUE THREAD

**Issue by mdrazak2001** [twentyhq/twenty#9152]
## Bug Description

When viewing the Person View page, the total count of persons displayed is incorrect.

**Example:** 
```
In the dashboard, the total number of persons is displayed as 7. 
However, when navigating to the Person View page, the total count displayed is 6.
```
![Image](https://github.com/user-attachments/assets/5b7a915f-fd08-4b0f-b301-d24155b4ca9d)

![Image](https://github.com/user-attachments/assets/f4db1c9b-62b3-42f9-8159-8b8d802fc098)

## Expected behavior

The total count of persons on the Person View page should match the count displayed on the dashboard.

**Comment by Weiko** [comment]
Should have been fixed in https://github.com/twentyhq/twenty/pull/9199
