### ISSUE TITLE
Crypto error when not using https

### ISSUE THREAD

**Issue by abdurrahmanarikan** [twentyhq/twenty#9186]
## Bug Description

When first time installed with a Docker container, it happens

**Example:** 
```
The error is printed on the console.
```
<img width="1976" alt="Image" src="https://github.com/user-attachments/assets/8a3840be-b8c7-45f0-9d3b-11073970e200" />

## Expected behavior

There should not be an error in the console

**Comment by FelixMalfait** [comment]
Hey, this is because you are not on HTTPS

Maybe we should set an error message in the console to recommend people switch to https (unless it's localhost, in which case it's not required because the browser has a special behavior)
