### ISSUE TITLE
Add an optional "secret" field on webhook for authentication

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#9187]
After the "Filters" section on a webhook edition page, add an optional field "Secret".

Sub-text: 
Optional: Define a secret string that we will include in every webhook. Use this to authenticate and verify the webhook upon receipt.

Implement it when we send webhooks, update the open api spec.

**Comment by samyakpiya** [comment]
Hi @FelixMalfait,

I'd like to be assigned to this issue.

**Comment by FelixMalfait** [comment]
Thanks @samyakpiya

**Comment by samyakpiya** [comment]
Hi @FelixMalfait,

The PR for this issue is ready for review: #9219. Let me know if you have any feedback!

Thanks!
