### ISSUE TITLE
Sanitize url before fetching favicon and display letter avatar if it can't be retrieved

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#919]
# Problem

When I paste a link from Google Omnibox ex:(http://google.com/) it inserts a "/" at the end of the URL and "https://" at the beginning of the URL. **This prevents the favicon to get fetched**

![Image](https://github.com/twentyhq/twenty/assets/19412894/7e06b455-d281-40fa-963a-9bfe35cd27d1)

Apple favicon doesn't get fetched if no "www" is added in front of the domain name, instead, it gives a "little temple"

![Image](https://github.com/twentyhq/twenty/assets/19412894/be148bcd-5918-408b-8d49-8ab1d5f87e8b)

# Solution

## Api call

We should try fetching the favicon in cascade with different URLs formats, in that order:

1) "example.com" by removing any "https://" "www" and the "/" at the end of the sentence.
2) "www.example.com"
3) "https://www.example.com"

![Image](https://github.com/twentyhq/twenty/assets/19412894/b1f5baf8-ca77-4875-96ad-ce488d7c82e6)

## Display

In the table, we should display the URL in "example.com" format (no "https", no "www") to make it easy to read.

## In case of no results

if no results can be fetched, we should insert the following placeholders:

![Image](https://github.com/twentyhq/twenty/assets/19412894/c66f4bdc-a39c-4bf7-9340-83e7414d718f)
![Image](https://github.com/twentyhq/twenty/assets/19412894/f7cd28e6-8687-4815-b5df-ced11aedf2a9)

Figma components:
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=3625-52525&mode=design&t=kDoI67TzhyFkHyn1-4
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=808-51105&mode=design&t=kDoI67TzhyFkHyn1-4

**Comment by FelixMalfait** [comment]
Ok so 2 distinct tasks:
- sanitize url
- if favicon can't be fetched, display letter avatar

**Comment by charlesBochet** [comment]
We would like to treat this one differently:
- create a company-logo folder in our file storage (similar to workspace-logo)
- add a companyLogoUrl field on Companies table
- when a company URL is updated, fetch the logo using faviconkit (see frontend code), upload it to the storage in 60x60 format or close, and store the image in companyLogoUrl (see workspaceLogo or avatarUrl to see how to do that) ==> probably do that in companyService
- on FE, use this companyLogoUrl
