### ISSUE TITLE
Unwanted behavior while navigating with arrows on Menu picker

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#920]
# Problem

When I'm on a "main point of contact" field, if I navigate with arrows and then press enter, it looks like I'm selecting the instance above the one I was clicking on. (Display problem, the value saved is the good one)

On the example below: When I'm clicking on "Bob Marrant", it looks like I'm selecting "Phil Shcille" (Hover behavior plus check icon)

https://github.com/twentyhq/twenty/assets/19412894/8cac7592-42fc-491c-a535-deca0b515b28

**Comment by FelixMalfait** [comment]
This one isn't very clear for me. I think we should close it or clarify it. Not sure what the resolution is

**Comment by Bonapara** [comment]
Indeed this isn't clear on a screen as It's not possible to record keyboards shortcuts.

What happens is: When you press the "enter" key on "Bob Marrant", the hover/selected state move to the first line "Phil Shcille" instead of staying on the menu Item I just pressed enter on.

Also the item I just pressed is not getting "checkmarked" before the menu picker closes (the checkmark is staying on the initial value (Phil Shcille in the video)

This gives an overall feeling that the wrong menu item is getting selected

**Comment by FelixMalfait** [comment]
https://github.com/twentyhq/twenty/blob/main/front/src/modules/ui/input/relation-picker/components/SingleEntitySelectBase.tsx#L56
https://github.com/twentyhq/twenty/blob/main/front/src/modules/pipeline/components/PipelineProgressPointOfContactPicker.tsx

Not familiar with the concept of optimistic rendering in Apollo but this might be linked to that?

**Comment by charlesBochet** [comment]
Not sure how to solve this one, would need investigation

**Comment by FelixMalfait** [comment]
Closing as path to resolution isn't clear and user impact is acceptable. We can reopen in the future
