### ISSUE TITLE
Change "contains" filter text

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#922]
# Actual behavior

We display "Contains" and the name of the company

![Image](https://github.com/twentyhq/twenty/assets/19412894/2815c4ad-b098-4c9a-81df-8a5b2f85ff8d)

# Desired behavior

**Make it shorter**

- Remove "Contains" and only keep ":"
- For "doesn't contains" display "Not"

![Image](https://github.com/twentyhq/twenty/assets/19412894/db312602-c8f6-4481-b15f-9ddca93146ac)

![Image](https://github.com/twentyhq/twenty/assets/19412894/a4571457-2a1f-4b68-8f92-4f70f812fe95)

**Comment by FelixMalfait** [comment]
Closing, thanks to @brendanlaschke!
