### ISSUE TITLE
CSV import - Select Dropdown does not have a background

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#9245]
## Bug Description

See screenshots

<img width="977" alt="Image" src="https://github.com/user-attachments/assets/97202bc7-421b-4ec4-a4d9-50af0b512357" />

<img width="483" alt="Image" src="https://github.com/user-attachments/assets/e58c7561-d4d4-4b20-9888-fed5940629e6" />

**Comment by muraliSingh7** [comment]
@Weiko Is this what you expect ?
![Image](https://github.com/user-attachments/assets/faedd62a-0083-4069-abee-c16844cb8706)

**Comment by muraliSingh7** [comment]
@Weiko exactly I was asking about that only from my screenshot should we use OverlayContainer ?
