### ISSUE TITLE
Change Snackbar to remove useless title

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#9259]
## Scope & Context

Snackbar component

## Current behavior

The snackbar has a title which meaning is already conveyed by the color and the icon of the component.

## Expected behavior

We want to remove the title and instead have message and detailedMessage props with detailedMessage props optional and message required. 

The fix shouldn't be difficult to implement, it's more a naming refactor.

**Comment by samyakpiya** [comment]
@lucasbordeau I'd like to be assigned to this issue.

**Comment by pranav-kadam** [comment]
@lucasbordeau Could you please assign the issue to me?
I thinking of removing the title prop, making message a required field, and implementing detailedMessage as an optional prop in SnackBar.tsx  I'll also refactor the related component [which here is SnackBarProvider.tsx] and logic. Is that a sound approach?

**Comment by ehconitin** [comment]
@samyakpiya, I am assigning you since you asked first! :)

**Comment by samyakpiya** [comment]
@lucasbordeau Let me know what you think about the PR!
