### ISSUE TITLE
Text Color Issue in Notes: CustomSlashMenu Option Displays Black Text in Dark Mode

### ISSUE THREAD

**Issue by muraliSingh7** [twentyhq/twenty#9265]
In Dark Mode, the text color within the `CustomSlashMenu` option in the Notes app appears as black, which is not compliant with the theme settings. The text should be rendered using the `theme.font.color.secondary` color instead of black, ensuring consistency with the dark mode design. 

#### Steps to Reproduce:
1. Enable Dark Mode in the app settings.
2. Navigate to the Notes section and access the `CustomSlashMenu` option by typing `/` in notes body.
3. Observe that the text appears in black color.

#### Screenshots:
1. **Current Behavior (Black Text in Dark Mode)**:
   ![Current Behavior - Black Text](https://github.com/user-attachments/assets/dc8d7b77-55da-4e71-9aa7-893164b7efdc)

2. **Expected Behavior (Text in `theme.font.color.secondary`)**:
   ![Expected Behavior - Secondary Font Color](https://github.com/user-attachments/assets/29a17f93-c775-47e8-98b0-7cb5d1166787)

**Comment by muraliSingh7** [comment]
@Weiko @lucasbordeau  Could you kindly confirm if this is intended behavior or if it should be considered a bug?

**Comment by lucasbordeau** [comment]
It's a bug yes

**Comment by khuddite** [comment]
@lucasbordeau I will take a look at the issue

**Comment by khuddite** [comment]
@muraliSingh7 @lucasbordeau I've linked a PR - https://github.com/twentyhq/twenty/pull/9280

Thanks!
