### ISSUE TITLE
Add tooltips on new column menu (good first issue)

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#927]
# Expected behavior:

When I press the "info" button, a tooltip opens to explain what is the purpose of the Field.

https://github.com/twentyhq/twenty/assets/19412894/cc9805d8-932e-4b24-b882-b279c665ac03

@jenalla can you prepare the texts and tag me when they are ready?

**Comment by FelixMalfait** [comment]
This issue is part of a "master issue" that will lead to introducing this Options button which does not currently exist. This task needs to be done first before we can tackle this one: https://github.com/twentyhq/twenty/issues/813

**Comment by Bonapara** [comment]
Tooltips content is inside Figma:


![Image](https://github.com/twentyhq/twenty/assets/19412894/2842d63b-3160-4c67-bda0-7c06b1af58ea)


https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=6901-116699&mode=design&t=kqAWI0RJ6EXygfgU-4

**Comment by FelixMalfait** [comment]
@Bonapara could you please also provide tooltips for the opportunities? Thanks!

**Comment by jenalla** [comment]
Tooltip content for the opportunities

<img width="311" alt="Screenshot 2023-09-21 102443" src="https://github.com/twentyhq/twenty/assets/102394218/99081133-20e3-485e-b2e9-d0e322137726">

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=11323-45550&mode=design&t=zeyZ5kCfVPADRPGz-4
