### ISSUE TITLE
Unify file download mechanism

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#9277]
In #9269 we introduced yet another way to download files.

There was already:

https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/activities/files/utils/downloadFile.ts 

And:

https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/object-record/record-index/export/hooks/useExportRecords.ts#L18

Let's migrate everything to the file-saver package @samyakpiya introduce

cc @samyakpiya do you want to take this followup? Thanks!

**Comment by samyakpiya** [comment]
I'll take it! Could you assign me?

**Comment by FelixMalfait** [comment]
Thanks!

**Comment by samyakpiya** [comment]
Done!
