### ISSUE TITLE
Deleted companies opportunities remain in opportunities without reloading

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#930]
# Current Behavior:

Currently, there is an issue where the opportunities associated with a deleted company remain visible in the Opportunities Show even after the company has been deleted. A hard refresh is required to remove them.

https://user-images.githubusercontent.com/102394218/256013738-fb5f729c-98a6-4b84-8a12-644ad206fd87.mp4

# Expected Behavior:

After deleting a company, its associated opportunities should be promptly removed from the Opportunities Show without the need for a hard refresh.

**Comment by charlesBochet** [comment]
Closing this one, as it's a duplicate
