### ISSUE TITLE
First column style update (Good first issue)

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#935]
# Current behavior

Today, clicking outside the chip opens the input to edit the company name. Clicking on the chip navigates to the associated show

https://github.com/twentyhq/twenty/assets/19412894/5e85c2be-6c1e-4759-801b-483a6bb3218d

Precision: for sure, clicking on the input should not close it but allow to edit it! (Did it only on Figma to show the behavior)

# Desired behavior

### New line

Clicking on the "plus" icon on the top right should directly open a field above the new empty line. Once something as been written in the Company name input, and the input has been closed, the behavior should be the one of _existing line_ below (clicking on the first cell should navigate to the associate show page). If the input has been closed, but no content has been written inside, clicking again on the empty cell should open it again. 

https://github.com/twentyhq/twenty/assets/19412894/98a237a8-2c5c-4f34-b1b3-dd58c52d0314

### Existing lines

Once a line has been created, the whole cell should be clickable, and link to the associated show page. On cell hover, a button should appear, and the chip state should be changed to its hover state (the one that appears on chip hover today). 

The button has an independent hover, even if it will redirect to the corresponding detail page on click as the rest of the cell. Once the name of the company or people has been updated, it should no longer be editable on the index page (maybe we can add the option back in a contextual menu later) so **make sure the instance name edition is perfectly working on the show page first!**

https://github.com/twentyhq/twenty/assets/19412894/44b58497-6882-4ddc-bac6-2284aca30c19

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=1406-44830&mode=design&t=rYlqqQ4Pj9HITkSR-4

**Comment by FelixMalfait** [comment]
Just a note in case it's not 100% clear that we want that not just for companies but also for people

**Comment by lucasbordeau** [comment]
We should handle read only first column / name in a separate issue

**Comment by Bonapara** [comment]
Reopening the issue as the **New line** behavior hasn't been implemented

> # Desired behavior
> ### New line
> Clicking on the "plus" icon on the top right should directly open a field above the new empty line. Once something as been written in the Company name input, and the input has been closed, the behavior should be the one of _existing line_ below (clicking on the first cell should navigate to the associate show page). If the input has been closed, but no content has been written inside, clicking again on the empty cell should open it again.

**Comment by Bonapara** [comment]
Opening a dedicated issue for "New line" that hasn't been implemented yet: #3069
