### ISSUE TITLE
Add pen button icon on fields that are links

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#937]
# Current behavior

Clicking on the URL opens the link. To edit the link value, I have to click on the cell outside of the link. Sometimes the space can be narrow to click.

https://github.com/twentyhq/twenty/assets/19412894/54ed766a-1bc7-46f9-b5bc-cffd4d895a0a

# Desired behavior

The "pen icon button" behavior concerns each cell that implies navigation (going to another page, be it another Twenty pages or an external link)

Clicking on the cell should trigger the link. We will introduce a pen icon on cell hover to enable value edition. If the field is empty, clicking anywhere on the cell should open the input (as there is no active link)

Hovering the cell (not only the link chip) should change the link chip to its hovered state.

There should be a validation on the cell. If the link is not valid when the cell is closed, the cell should be restored to its previous state.

https://github.com/twentyhq/twenty/assets/19412894/288bdeb7-f018-449e-9023-bc180a3276d3

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=1406-44830&mode=design&t=rYlqqQ4Pj9HITkSR-4

**Comment by FelixMalfait** [comment]
Note this pen icon is already implemented in the app elsewhere, ex:

<img width="346" alt="Screenshot 2023-07-30 at 05 23 10" src="https://github.com/twentyhq/twenty/assets/6399865/67aa50d7-9cb8-423e-80ec-b8d070af9c53">

**Comment by nsv23** [comment]
Hi @FelixMalfait can I work on this?

**Comment by FelixMalfait** [comment]
Yes of course! Thanks @nsv23

**Comment by FelixMalfait** [comment]
Thanks a lot @abhip167 ; this has just been implemented. You can find other good first issues here https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
