### ISSUE TITLE
Update link style, now in a rounded chip

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#938]
# Current behavior

Links are a plain underlined text

![Image](https://github.com/twentyhq/twenty/assets/19412894/3cb4ae8b-24cc-4d9f-8fef-35b75ab420a5)

# Desired behavior

Links should be in a rounded chip

![Image](https://github.com/twentyhq/twenty/assets/19412894/e338a371-75c2-4d3e-a449-bde75d59aab2)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=6347-206998&mode=design&t=rYlqqQ4Pj9HITkSR-4

**Comment by jaykesarkar** [comment]
I would like to work on this issue. Please guide me.

**Comment by shobhitexe** [comment]
Hey is this still open am willing to take this

**Comment by FelixMalfait** [comment]
Yes it is! Thanks a lot @shobhitexe

**Comment by FelixMalfait** [comment]
@shobhitexe FYI there is a related issue that will come after this one: https://github.com/twentyhq/twenty/issues/937 but they can be handled separately / by different persons
