### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by waleed-alshiekh** [twentyhq/twenty#942]
I got this issue when I am trying to start server
```[tasklist]
### Tasks
```

**Comment by FelixMalfait** [comment]
I'm not able to reproduce sorry. Maybe linked to the size of the machine you're running it on?

**Comment by FelixMalfait** [comment]
Closing to keep backlog clean but I will re-open it if we have a clear way to reproduce the error. Thanks!

**Comment by amrali21** [comment]
i am having the same issue. running linux with 16gb of ram. why is this not resolved yet? i can't run the project for 30 seconds before it throws this error although my ram usage isn't even crossing 10gb
