### ISSUE TITLE
Update desactivated state of onboarding button

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#952]
# Current style

![Image](https://github.com/twentyhq/twenty/assets/19412894/4082ee45-04f9-4f14-a436-6ac48f8e0660)

# Desired style

Remove box-shadow (on the deactivated state only) and change the background to "secondary"
Border color should be "Transparent lighter"

![Image](https://github.com/twentyhq/twenty/assets/19412894/0d495c47-5f91-41c6-8576-c69fc1760d9d)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=3193-63417&mode=design&t=sj4NhD0g7qMJY0yH-4

**Comment by FelixMalfait** [comment]
@Bonapara fyi the link does not allow checking the properties I think? Maybe for "good first issue" we should find something easier for people to access

<img width="1509" alt="Screenshot 2023-07-30 at 13 26 26" src="https://github.com/twentyhq/twenty/assets/6399865/b232fa4e-8d7c-4a29-813b-f2440944d670">

**Comment by FelixMalfait** [comment]
Closed thanks to @indrajitbnikam!
