### ISSUE TITLE
Enable Sort and Filter editing

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#956]
# Current Behavior

Today, users can't change the active sort and filter fields by clicking on the blue field. This makes it hard to modify the sorting and filtering quickly and easily. (you need to delete the existing one to modify it)

https://user-images.githubusercontent.com/102394218/256372062-209a7135-187e-4ce5-a5e1-8b377c4e90dc.mp4

# Desired Behavior

**Check #1215 for updated style changes first**

Users should be able to easily edit the active sort and filter by clicking on it.

List of changes on the active sort and filter:
- Clickable: Enable clickability with hover effects - background-color changes to Accent/tertiary and border to Accent/primary.
- Change the hover effect of the tabler-icon-x (delete button) to Accent/secondary background-color.
- Disable text selection when clicking on the element.

**The style change should also be applied to the opportunities filters**

### Sort

When clicking on the blue field of the active sort, it should open the same menu as when you click on the "Sort" button, allowing users to change the sorting parameters (e.g., name, employees).

https://user-images.githubusercontent.com/102394218/256371039-2f8f23e8-7381-45c2-96f6-b30e4be047f5.mp4

### Filter

Similarly, when clicking on a filter, it should open the filter menu of the selected category, giving users the option to modify the entered value (e.g., in Account owner: is Tim Cook, allow change of "Tim Cook").

https://user-images.githubusercontent.com/102394218/256371053-3fdb1e74-c58e-4b3b-92a1-b44c918aa1e8.mp4

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=6775-72724&mode=design&t=JHNORCQzqa5Ms34q-4

**Comment by charlesBochet** [comment]
Seems expensive and low value added, let's hold a bit on this one?

**Comment by FelixMalfait** [comment]
Just a note that there is something strange change in the "sort" video where 🔗 icon is displayed instead of 🔼🔽. This is an error, let's keep the current behavior with arrows.

**Comment by charlesBochet** [comment]
@gitstart-twenty Let's use DropdownButton and useDropdownButton hook here even if we don't have a dropdown button. (see ColumnHead dropdown) for example
