### ISSUE TITLE
Add opportunities on company show

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#957]
# Desired behavior:

I should be able to see and edit opportunities on their associated company detail page:

![Image](https://github.com/twentyhq/twenty/assets/102394218/7e6eedf7-ba9a-40d3-a611-8580d2bc50d6)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5910-71659&mode=design&t=0Lkm52Fnls3DJLFl-4
```[tasklist]
### Tasks
- [ ] Only on CompanyShow, create a specific component close to CompanyBoardCard.
- [ ] Re-use the same fields as CompanyBoardCard (you will need to display the labels, there is an option in EditableFields for that)
```

**Comment by FelixMalfait** [comment]
Hey @Bonapara, we just implement the box with various not the monthly/all time right? Maybe we could update the Figma to reflect this? I feel like monthly/all time is nice in theory but not something that we'd be able to have in practise

Also is it on purpose to have a $ icon in front of "Sales"? Do we want the "target with arrow" icon instead?

**Comment by charlesBochet** [comment]
We probably want to hold this one until we have completed the Fields refactoring

**Comment by Bonapara** [comment]
@jenalla Can you update all the Figma screens with:
- The right fields (the one that are currently in prod)
- The title "🎯 Opportunities" instead of "﹩Sales"

**Comment by charlesBochet** [comment]
Putting this one on-hold as design does not seem to be ready!

**Comment by Bonapara** [comment]
Replaced by #3099

**Comment by muraikenta** [comment]
🚧 Railway ロック取得 #1713 (role=unknown, session=murai-mba/twenty-cacco)

cacco-build-image 0.1.41 の反映（deploy-image.sh, worker→server）。村井指示によるCI復旧後の一括マージ後のイメージ反映

**Comment by muraikenta** [comment]
✅ Railway ロック解放 #1713 (role=unknown, session=murai-mba/twenty-cacco)

cacco-build-image 0.1.41 を twenty-worker/twenty-server に反映完了。deploy-image.sh の parity ゲート緑（healthz 200・稼働イメージ/digest一致・worker分離済み）。既知の赤（twenty-backup alpine:3.21）は持ち越し・別Issue
