### ISSUE TITLE
I want to add a deadline to a task

### ISSUE THREAD

**Issue by mxcrbn** [twentyhq/twenty#963]
Can be specific to tasks or more generic (add date as basic block type?)

**Comment by FelixMalfait** [comment]
Agree we need it! We should add that by end of next week

We actually already have plans for tasks. You can check Figma here: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=5910%3A71347&mode=dev

![Task details](https://github.com
![Tasks](https://github.com/twentyhq/twenty/assets/6399865/39eb3141-68c7-4a14-aa76-fb05559b41e0)
/twentyhq/twenty/assets/6399865/4d9c2347-248f-4800-9e56-6535647a08da)

**Comment by FelixMalfait** [comment]
OK step 1 (adding due date in the panel) is live in production so I'll close this issue!

We still need to ship the task overview page, probably in a week or so.
Also we need to improve the design in edit mode, this really isn't pretty:

<img width="475" alt="Screenshot 2023-07-30 at 04 56 53" src="https://github.com/twentyhq/twenty/assets/6399865/1e94cb29-93e4-49ad-bbae-4d7d84a5af6d">
