### ISSUE TITLE
Opportunities columns style is the old one when I create an account

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#968]
# Current behavior

When I create an account, the opportunities columns titles have the old style:

![Image](https://github.com/twentyhq/twenty/assets/19412894/65f90bab-3197-4dd1-949f-dc935e554505)

# Desired behavior:

Opportunities columns titles should have the "tag" style:
And from a more general point of view, there shouldn't be some old & new column name in the same board

![Image](https://github.com/twentyhq/twenty/assets/19412894/c5e2ec06-4e87-4211-a97b-6707e317f9b4)

```[tasklist]
### Tasks
- [ ] Update server/src/core/pipeline/seed-data to use default colors available in BoardColumnEditTitleMenu.tsx instead of hexa colors
```

**Comment by FelixMalfait** [comment]
There is a file pipeline-stages.json on the server that needs to be modified in order to solve this.

COLOR_OPTIONS are defined on the frontend in BoardColumnEditTitleMenu
