### ISSUE TITLE
I can signup without going through the "signing" flow

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#973]
The current process feels off. I have to enter my email on the sign-in page in order to be redirected to signup.
Should we change the title to something for generic or add a subtext to let the user know this input is used both for sign-in and sign-up? 

cc @Bonapara 

<img width="1191" alt="Screenshot 2023-07-28 at 03 28 07" src="https://github.com/twentyhq/twenty/assets/6399865/ae928fe6-83cf-4807-8909-771f6643c31f">

**Comment by Bonapara** [comment]
Will be fixed when we'll introduce "sign-in" / "sign-up" on "twenty.com"
