### ISSUE TITLE
Concurrency issue when uploading images

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#978]
Got this bug report sent from a user today.

When we upload an image, it would be nice to cancel the previous upload. If the previous upload was a larger image it will end up finishing after and therefore taking over the second image that I uploaded.

**Comment by FelixMalfait** [comment]
Need spec: do we show a loading bar? Do we use a more robust external library for uploads? (could be one that handles dropping elements in the area, etc.)

**Comment by charlesBochet** [comment]
Let's try to implement this: 
https://github.com/jaydenseric/apollo-upload-client/issues/119

**Comment by friendlymatthew** [comment]
Hi @FelixMalfait @charlesBochet, I have a pr that integrates the apollo upload client with other helpful features:
https://github.com/twentyhq/twenty/pull/1400

**Comment by charlesBochet** [comment]
This has been completed, thank you @friendlymatthew
