### ISSUE TITLE
I can save the resized columns sizes

### ISSUE THREAD

**Issue by thaisguigon** [twentyhq/twenty#981]
**GIVEN** I am logged in my workspace
**AND** I am on the People/Companies page
**WHEN** I resize a People/Companies table's column
**AND** I leave the app
**AND** I open the app again on the People/Companies page
**THEN** the table's column is in the size I previously resized it to

➡ Upsert a `ViewField` for each resized column
➡ Persist the column size in the `sizeInPx` `ViewField` property

**Comment by charlesBochet** [comment]
could you actually upsert all the ViewField not only the resized one, we will need anyway
