### ISSUE TITLE
Click glitch on profile page

### ISSUE THREAD

**Issue by shobhitexe** [twentyhq/twenty#993]
while clicking anywhere on /settings/profile page dialog box of deleting account appears as shown in below recording
however its only on local dev on prod website its not there 

https://github.com/twentyhq/twenty/assets/29349136/2d57070b-6d42-4505-8255-9b435ab5e23b

**Comment by FelixMalfait** [comment]
Ouch, this one is bad. Thanks for the report, we should look into it quickly

**Comment by indrajitbnikam** [comment]
I am working it.

**Comment by FelixMalfait** [comment]
Thanks a lot @indrajitbnikam!

**Comment by indrajitbnikam** [comment]
Hi @shobhitexe , I can't reproduce this locally. Can you confirm once again?

**Comment by charlesBochet** [comment]
@indrajitbnikam This was fixed yesterday already, if you pull again main locally, it should be good. Good catch though!

**Comment by FelixMalfait** [comment]
Thanks again for having a look at it @indrajitbnikam

**Comment by shobhitexe** [comment]
> @indrajitbnikam @shobhitexe This was fixed yesterday already, if you pull again main locally, it should be good. Good catch though!

Yes i updated main and the issues is no longer there thanks
