### ISSUE TITLE
Show snackbar on network, authentification and graphql errors

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#999]
## Issue

We need to give a feedback to the user if he's been logged out. If he's offline. Or if the server returned an error.
There seemed to be already an implementation of ErrorLink in apollo.factory.ts but we need to surface those errors to the end user in a friendly format,.

## Reference

Client side error handling:
https://www.apollographql.com/docs/react/data/error-handling/#advanced-error-handling-with-apollo-link

See list of GraphQL errors:
https://www.apollographql.com/docs/apollo-server/data/errors/#graphql_parse_failed

Error SnackBar:
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=3063-54842&mode=design&t=R2W7BwvSY7vlgqFV-0
(no need to redesign, should already be implemented in the code)

**Comment by abhithory** [comment]
Hi @FelixMalfait , I did not understand this properly that is exactly what I have to do. But this seems interesting to me. So, i am ready to work on this, if you can provide me some context on this.

**Comment by FelixMalfait** [comment]
Sorry @abhitory that we never answered to your comment! The issue wasn't very clear indeed.
I feel like error handling has been improved, now if you disconnect internet and do something at least you'll see a snack bar error "failed to fetch". It's clearly not perfect (we should do more user friendly error messages for when the user is offline, when the user has been logged out, etc.), but it's probably good enough for now... I'll close this
